mattermost/mattermost

config/client.go
config/client_test.go

Cherry pick of #13183 on release-5.18.
- #13183: MM-19551: Add IsDefaultMarketplace to client config

Automated cherry pick of #13183

---

cmd/mattermost/commands/user.go
cmd/mattermost/commands/user_test.go

Cherry pick of #13155 on release-5.18.
- #13155: Allowing user delete command to delete bot accounts.

Automated cherry pick of #13155

---

api4/post.go
app/auto_posts.go
app/channel_test.go
app/command_loadtest.go
app/file.go
app/plugin_api.go
app/post.go
model/post.go
store/sqlstore/post_store.go
store/store.go
store/storetest/mocks/PostStore.go
store/storetest/post_store.go
store/storetest/reaction_store.go
store/timer_layer.go

Revert on the changes that improved performance loading threads
[MM-20725](https://mattermost.atlassian.net/browse/MM-20725)

[MM-20725] Revert threads performance change on 5.18

---

Makefile

Fixes the references to `mattermost-server` modules on the Makefile. 
https://mattermost.atlassian.net/browse/MM-19948

Fix the LDFLAGS references to use the version suffix

---

Makefile

Cherry pick of #13242 on release-5.18.
- #13242: Fix the LDFLAGS references to use the version suffix

Automated cherry pick of #13242

---

app/analytics.go
app/command_loadtest.go
app/diagnostics.go
store/sqlstore/user_store.go
store/storetest/user_store.go

Cherry pick of #13232 on release-5.18.
- #13232: corrected active count function
/cc  @reflog

Automated cherry pick of #13232

---

.circleci/config.yml
build/Jenkinsfile.pr

Cherry pick of #13281 on release-5.18.
- #13281: update context and s3 buckets
/cc  @cpanato

Automated cherry pick of #13281

---

app/slackimport.go
i18n/en.json

Cherry pick of #12514 on release-5.18.
- #12514: Limit size of files inside Zip archive before JSON
/cc  @abhisek

Automated cherry pick of #12514

---

api4/plugin_test.go
app/plugin.go
i18n/en.json

Cherry pick of #13237 on release-5.18.
- #13237: MM-20642 - Failed to install marketplace plugin on older

Automated cherry pick of #13237

---

app/plugin_api.go
app/plugin_key_value_store.go
app/plugin_test.go
i18n/en.json
model/plugin_kvset_options.go
plugin/api.go
plugin/client_rpc_generated.go
plugin/plugintest/api.go
store/sqlstore/plugin_store.go
store/store.go
store/storetest/mocks/ChannelStore.go
store/storetest/mocks/PluginStore.go

Cherry pick of #13213 on release-5.18.
- #13213: Drop EncodeJSON from PluginKVSetOptions
/cc  @hanzei

Automated cherry pick of #13213

---

app/channel_test.go
app/post.go
app/post_test.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/mocks/ChannelStore.go

Cherry pick of #13245 on release-5.18.
- #13245: MM-20649 Fix incorrect mention count when marking a DM
/cc  @hmhealey

Automated cherry pick of #13245

---

model/manifest.go

Cherry pick of #13306 on release-5.18.
- #13306: Added custom type to manifest setting types documentation

Automated cherry pick of #13306

---

app/web_hub.go

The PR link uses the github repo path, not the module path.

Fix typo for v5 module path

---

cmd/mattermost/commands/integrity.go
store/sqlstore/integrity.go
store/sqlstore/integrity_test.go
store/store.go

- Fixed a couple of bugs with query building which were generating false positives.
- Added new tests for the fixed bugs.
- Added support for NULL fields.
- Improved tool output.
https://mattermost.atlassian.net/browse/MM-20761

[MM-20761] Fix and improve integrity check tool

---

cmd/mattermost/commands/integrity.go
store/sqlstore/integrity.go
store/sqlstore/integrity_test.go
store/store.go

Cherry pick of #13246 on release-5.18.
- #13246: Fix query and add tests

Automated cherry pick of #13246

---

api4/team_test.go
api4/websocket_test.go
app/import_functions_test.go
app/import_test.go
model/utils.go
store/sqlstore/integrity_test.go

(cherry picked from commit 6e6a44764cafdfbe71baf8eb181dc85ffa12ea67)

[MM-19892] Fix failing test TestImportBulkImport (#13003)

---

store/localcachelayer/channel_layer.go
store/localcachelayer/channel_layer_test.go
store/localcachelayer/layer.go
store/localcachelayer/main_test.go
store/sqlstore/channel_store.go

Reverting https://github.com/mattermost/mattermost-server/pull/13189 due to performance issues.
Fixes https://mattermost.atlassian.net/browse/MM-20946

MM-20946 - Revert "MM-20105: Migrate channelByNameCache cache from store/sqlstor…e/channel_store.go to the new store/localcachelayer (#13189)"

---

store/sqlstore/upgrade.go

Update DB to 5.18
/cc @amyblais

upgrade DB to 5.18

---

web/static.go
web/web_test.go

Serve static plugin assets with a `Cache-Control: no-cache, public` header. This avoids caching a 404 response for such an asset, preventing it from being loaded until expiry even if the file later becomes available.
This is currently preventing updates of plugins on community and would generally affect any customer with a cache in front of the Mattermost servers.
Fixes: https://mattermost.atlassian.net/browse/MM-20948

MM-20948: nocache for static plugin assets

---

store/sqlstore/upgrade.go

Cherry pick of #13315 on release-5.18.
- #13315: upgrade DB to 5.18
/cc  @cpanato

Automated cherry pick of #13315

---

web/static.go
web/web_test.go

Cherry pick of #13322 on release-5.18.
- #13322: MM-20948: nocache for static plugin assets

Automated cherry pick of #13322

---

app/integration_action.go
app/integration_action_test.go

Cherry pick of #13248 on release-5.18.
- #13248: MM-20755: fix post actions in DMs/GMs

Automated cherry pick of #13248

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/4474
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/3680

translations PR 20191209

---

web/handlers.go
web/handlers_test.go

Cherry pick of #13354 on release-5.18.
- #13354: Add CSRF check for handlers that do not require a session but

Automated cherry pick of #13354

---

api4/apitestlib.go
api4/channel_test.go
api4/websocket_test.go
wsapi/user.go

Cherry pick of #13373 on release-5.18.
- #13373: Add permissions check on user_typing event

Automated cherry pick of #13373

---

services/filesstore/localstore.go

Cherry pick of #13369 on release-5.18.
- #13369: corrected file permissions for localstore
/cc  @reflog

Automated cherry pick of #13369

---

app/diagnostics.go

@hahmadia https://github.com/mattermost/mattermost-server/pull/13018
@sbishel https://github.com/mattermost/mattermost-server/pull/12362
@ali-farooq0 https://github.com/mattermost/mattermost-server/pull/13017
This list is based on Amy's changelog summary at https://github.com/mattermost/docs/pull/3164/files#r355637942
https://mattermost.atlassian.net/browse/MM-21094

MM-21094 Add missing diagnostics for 5.18 release

---

.circleci/config.yml

This reverts commit 05192cb3f8e60898d4fb9ef9c012e6679d5a8aad.
This CI step was simplified in the past, but doesn't seem to work, so reverting to previous solution

Revert "fix npm ci step"

---

app/diagnostics.go

Cherry pick of #13358 on release-5.18.
- #13358: Add missing diagnostics for 5.18 release

Automated cherry pick of #13358

---

store/sqlstore/channel_store.go
store/sqlstore/channel_store_test.go

Cherry pick of #13371 on release-5.18.
- #13371: MM-21116: Improve channelSearch SQL query generation
/cc  @agnivade

Automated cherry pick of #13371

---

api4/plugin_test.go
app/plugin.go
app/plugin_install.go
app/plugin_signature.go
app/plugin_test.go

Cherry pick of #13360 on release-5.18.
- #13360: MM-21103: change plugin signature path

Automated cherry pick of #13360

---

app/login.go
build/Jenkinsfile.pr
model/client4.go
model/session.go
web/handlers.go
web/handlers_test.go

PR improves CSRF check.
https://mattermost.atlassian.net/browse/MM-21048

[MM-21048] Improve CSRF check

---

api4/channel.go
api4/channel_test.go
i18n/en.json

Cherry pick of #13387 on release-5.18.
- #13387: Disallow changing type when updating a channel

Automated cherry pick of #13387

---

config/file.go
config/file_test.go

Cherry pick of  #13386 on release-5.18.

Cherrypick for MM-21119

---

i18n/en.json
store/sqlstore/channel_store.go
store/storetest/channel_store.go

Cherry pick of #13429 on release-5.19.
- #13429: Return same error when trying to create a channel with

Automated cherry pick of #13429

---

api4/channel.go
api4/channel_test.go
store/sqlstore/channel_store.go

Cherry pick of #13443 on release-5.19.
- #13443: Return http.StatusNotFound error when trying to get a channel

Automated cherry pick of #13443

---

model/websocket_client.go
model/websocket_message.go
model/websocket_request.go

Added some godocs to a few websocket related structs

Added some godocs to a few websocket related structs

---

model/license.go
utils/license.go

Cherry pick of #13431 on release-5.19.
- #13431: MM-21290: Adds licensing feature for LockTeammateNameDisplay.
/cc  @mkraft

Automated cherry pick of #13431

---

store/sqlstore/upgrade.go

https://github.com/mattermost/mattermost-server/pull/12229 added a new column but did not add the migration code. I needed to add the prep upgrade code to get this to work.

Fix Bots table lacking schema migration

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20191223

---

app/notification_push.go
app/notification_push_test.go

Cherry pick of #13353 on release-5.19.
- #13353: MM-20225: Fix notification badge count for All Activity
/cc  @agnivade

Automated cherry pick of #13353

---

api4/oauth.go
api4/oauth_test.go

PR adds an extra permission check when updating a OAuth application.
https://mattermost.atlassian.net/browse/MM-21359

[MM-21359] Add extra permission check when updating an OAuth app

---

api4/oauth.go
api4/oauth_test.go

Cherry pick of #13445 on release-5.19.
- #13445: Add permission check

Automated cherry pick of #13445

---

api4/oauth.go
api4/oauth_test.go

Cherry pick of #13445 onto release-5.17

Cherry pick of #13445

---

app/command_invite.go
app/command_invite_test.go

Cherry pick of #13392 on release-5.19.
- #13392: Fix incorect bot message
/cc  @iomodo

Automated cherry pick of #13392

---

app/channel.go
app/channel_test.go
i18n/en.json

Cherry pick of #13441 on release-5.19.
- #13441: MM-21336: Improve channel rename restrictions
/cc  @agnivade

Automated cherry pick of #13441

---

app/notification_test.go
go.sum

Migrate tests from "app/notification_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12097

MM-18384 - Migrate tests from "app/notification_test.go" to use testify

---

app/diagnostics.go
config/client.go
model/config.go

Server changes to support the server-wide toggle for the new channel sidebar.
https://mattermost.atlassian.net/browse/MM-20881
Webapp changes: https://github.com/mattermost/mattermost-webapp/pull/4553
Redux changes: https://github.com/mattermost/mattermost-redux/pull/1020

[MM-20881] Server changes for new experimental channel sidebar setting

---

app/notification.go
app/slack.go
app/web_conn.go
go.mod
model/access.go
model/compliance.go
model/config.go
model/file_info.go
model/guest_invite.go
model/job.go
model/post.go
model/role.go
model/team.go
model/team_search.go
model/user.go
model/websocket_message.go
plugin/client_rpc.go
store/sqlstore/compliance_store.go
store/sqlstore/file_info_store.go
store/sqlstore/supplier.go
store/sqlstore/team_store.go
store/sqlstore/user_store.go

Fix inconsistencies in variable names for struct methods

Fix inconsistencies in variable names for struct methods

---

api4/saml_test.go
web/handlers.go
web/saml.go

Cherry pick of #13562 onto release-5.9

Cherry pick of #13562

---

.circleci/config.yml
Makefile
build/Jenkinsfile.pr

This ensure that EE code doesn't get leaked by accident, if new linters are added.
https://mattermost.atlassian.net/browse/MM-21108
https://community-release.mattermost.com/private-core/pl/5m8ksaq3xpfefd5siiyd8ew7po

Don't lint EE code in TE CI

---

.golangci.yml
config/client.go
config/client_test.go
config/config_generator/generator/generator.go
config/database_test.go
config/file.go
config/memory.go
config/migrate.go
config/utils_test.go

A small step towards a golint clean code base.

Golint fix config

---

model/version.go
store/sqlstore/upgrade.go

Update DB to 5.19 in the release branch
/cc @amyblais

upgrade DB to 5.19.0

---

app/cluster_handlers.go
app/web_hub.go
store/localcachelayer/user_layer.go
store/localcachelayer/user_layer_test.go
store/sqlstore/user_store.go
store/store.go
store/storetest/mocks/UserStore.go
store/storetest/user_store.go
store/timer_layer.go

Removing certain unneded cluster invalidation messages

Removing certain unneded cluster invalidation messages

---

store/storetest/post_store.go

Cherry pick of #13437 on release-5.19.
- #13437: Caching removed from post_store.go, remove caching test
/cc  @sbishel

Automated cherry pick of #13437

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200106

---

app/server.go

This code is old and not required to be present now.
https://mattermost.atlassian.net/browse/MM-21608

MM-21608: Remove buggy migration code

---

app/server.go

Cherry pick of #13600 on release-5.19.
- #13600: MM-21608: Remove buggy migration code
/cc  @agnivade

Automated cherry pick of #13600

---

store/storetest/compliance_store.go

Convert store/storetest/compliance_store.go t.Fatal call into require call
Fixes #12784

Convert store/storetest/compliance_store.go t.Fatal to require

---

.golangci.yml
store/layer_generators/main.go
store/timer_layer.go

This PR fixed a couple of issues that newly came up with golangci v1.22.2. https://github.com/golangci/golangci-lint/issues/910 is blocking bumping the version to 1.22.2. This will be done in a different PR.
Part of https://mattermost.atlassian.net/browse/MM-21506

 Fix issues found by golangci v1.22.2

---

i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ro.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200113

---

build/Dockerfile

- bump alpine image
- use latest available MM release

bump alpine version and mm as well

---

api4/post.go
app/auto_posts.go
app/channel_test.go
app/command_loadtest.go
app/file.go
app/plugin_api.go
app/post.go
model/post.go
store/localcachelayer/main_test.go
store/localcachelayer/post_layer.go
store/localcachelayer/post_layer_test.go
store/sqlstore/post_store.go
store/store.go
store/storetest/mocks/PostStore.go
store/storetest/post_store.go
store/storetest/reaction_store.go
store/timer_layer.go

Revert thread fetching changes

Thread fetching revert

---

Makefile

plugin | prev | new 
--- | --- | ---
zoom | `v1.1.2` | `v1.2.0`
autolink | `v.1.1.1` | `v1.1.2`
antivirus | `v0.1.1` | `v0.1.2`
jira | `v2.2.2` | `v2.3.2`

Update bundled plugins for v5.20

---

store/localcachelayer/user_layer.go
store/localcachelayer/user_layer_test.go

This PR fixes some data integrity issues that are causing several unexpected behaviours related to user's notifications settings and patching.
The main issue has to do with the `LocalCacheUserStore` returning (in some cases) a pointer to the stored data instead of a copy.
This data is, at times, sanitized for security reasons through the use of `User.Sanitize()` or `User.SanitizeProfile()` methods which can remove/blank important information like `User.Email` and `User.NotifyProps`.   
These changes are being reflected in the cached objects hence corrupting the user's data for everyone.
While returning a shallow copy of the stored `model.User` seems sufficient to fix the current bugs, I preferred, for integrity reasons, to leverage the existing `User.DeepCopy()` and make sure the data …

[MM-21693] Make LocalCacheUserStore.Get/GetProfileByIds return a copy of the stored data

---

api4/user_test.go
app/user.go
app/web_conn.go
model/websocket_message.go
model/websocket_message_test.go

- Fixed the root cause for panic by properly converting
the map to a User struct.
- Added a check for type conversion for extra safety.
- Fixed a somewhat unrelated issue of a pointer to pointer reference.
https://mattermost.atlassian.net/browse/MM-21481

MM-21481: Fixed several issues from user marshalling

---

app/channel.go

Fail if creating ChannelMemberHistory record fails.
https://mattermost.atlassian.net/browse/MM-12773

MM-12773: Return error if ChannelMemberHistory record creation fails.

---

api4/user_test.go
app/user.go
app/web_conn.go
model/websocket_client.go
model/websocket_message.go
model/websocket_message_test.go

Cherry pick of #13627 onto release-5.18

Cherry pick of #13627

---

i18n/en.json

Change string from plural to singular
https://mattermost.atlassian.net/browse/MM-21725

MM-21725 change to singular

---

.circleci/config.yml
.golangci.yml
build/Jenkinsfile.pr

~~Blocked by https://github.com/golangci/golangci-lint/issues/910 and https://github.com/golangci/golangci-lint/issues/885~~
https://mattermost.atlassian.net/browse/MM-21506
Enterprise PR: https://github.com/mattermost/enterprise/pull/560

Bump GolangCI-Lint to v1.23.0

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200120

---

api4/role.go
api4/team.go
api4/user.go

Cherry pick of #13643 on release-5.20.
- #13643: Avoid taking into account guest accounts flag

Automated cherry pick of #13643

---

app/email.go

Cherry pick of #13637 on release-5.20.
- #13637: Don't send welcome email if verificaiton is off
/cc  @hahmadia

Cherry pick of #13637

---

.circleci/config.yml

Set the GOBIN to install go-junit-report in the correct location

---

.golangci.yml

Remove imports from golint blacklist
None
- Has Enterprise changes: https://github.com/mattermost/enterprise/pull/567

Remove imports from golint blacklist

---

.gitignore
bin/.gitignore

Add bin folder which is required by the build process. 
By adding it here as an empty direcory less build pipelines need modifying and adjusting.

Add mm server bin directory

---

api4/apitestlib.go
api4/user_test.go
app/user.go

Cherry pick of #13683 on release-5.20.
- #13683: Invalidate after promote/demote update

Automated cherry pick of #13683

---

app/plugin_requests.go

This fixes a one case typo in app/plugin_requests.go

Fix small typo

---

app/config.go

Compare config without environment variables to send config updates to the cluster

Compare config without environment variables to send config updates to the cluster

---

Makefile

export GOBIN

---

cmd/mattermost/commands/config.go
cmd/mattermost/commands/config_test.go

Cherry pick of #13350 on release-5.20.
- #13350: Fix config set panic
/cc  @iomodo

Automated cherry pick of #13350

---

api4/plugin.go
api4/plugin_test.go

Cherry pick of #13636 on release-5.20.
- #13636: Disable InstallFromUrl if EnableUploads is false
/cc  @iomodo

Automated cherry pick of #13636

---

app/opengraph.go
app/post_metadata.go

Making private opengraph methods in the app layer

Making private opengraph methods in the app layer

---

app/cluster_handlers.go
app/server.go

Making private app/cluster_handlers.go methods
This PR depends on this other PR mattermost/enterprise#572

Making private app/cluster_handlers.go methods

---

api4/system.go
api4/system_test.go
app/notification_push.go
app/notification_push_test.go
i18n/en.json
model/push_notification.go
model/push_notification_test.go

Cherry pick of #13751 on release-5.20.
- #13751: Handle empty push notifications messages

Automated cherry pick of #13751

---

plugin/helpers_config.go
plugin/helpers_config_test.go

Cherry pick of #13748 on release-5.20.
- #13748: plugin/helpers: fix an unchecked issue when comparing two

Automated cherry pick of #13748

---

api4/config.go
api4/config_test.go

Cherry pick of #13682 on release-5.20.
- #13682: Disable signatures modification through API
/cc  @iomodo

Automated cherry pick of #13682

---

api4/team.go
api4/team_test.go
app/team.go
model/client4.go
model/team_member.go

MM-20977 - Inviting multiple users with valid/allowed and inva… (#13779)

---

app/team.go
app/team_test.go
app/user_test.go

Cherry pick of #13776 on release-5.20.
- #13776: Check guest email allowance separately

Automated cherry pick of #13776

---

store/sqlstore/channel_store.go

Removing unused param and unneeded query from SaveMember in the ChannelStore

Removing unused param and unneeded query

---

model/manifest.go
model/manifest_test.go

Given that `number` as a setting type is supported and it's pretty useful, it should also be documented.
https://community-release.mattermost.com/core/pl/kjwpuu5hffyhmb7amgsnsd71xr

Add documentation for number field for plugins

---

Makefile

Updating process for mmctl to use DIST_PATH/bin

---

app/email.go

This reverts commit c4c7f06f01e4aa32a4ab374fd09503ed3ec9de41.
This feature needs to be pushed to Fix Version 5.22 so that it can work alongside https://mattermost.atlassian.net/browse/MM-21682
https://mattermost.atlassian.net/browse/MM-21373

Revert "[MM-21373] Don't send verification (#13637) (#13674)"

---

store/localcachelayer/main_test.go
store/localcachelayer/user_layer.go
store/localcachelayer/user_layer_test.go
store/storetest/user_store.go

See https://mattermost.atlassian.net/browse/MM-22200

Revert "MM-21209: Use the LRU cache for UserStore.Get call too (#13456)"

---

build/Jenkinsfile.branch

Add more build to be retained in the jenkins logs
per @agnivade request

retain the logs for more builds 

---

store/sqlstore/upgrade.go

Upgrade DB to 5.20
@amyblais there are some new columns, need to check with @mkraft

Upgrade db to 5.20

---

api4/user.go
i18n/en.json

Cherry pick of #13790 on release-5.20.
- #13790: MM-21882: Remove the license requirement to promote
/cc  @jespino

Automated cherry pick of #13790

---

store/sqlstore/upgrade.go

Cherry pick of #13820 on release-5.20.
- #13820: update db to 5.20
/cc  @cpanato

Automated cherry pick of #13820

---

i18n/en.json

Fixed wording
Fixes https://mattermost.atlassian.net/browse/MM-22188

MM-22188  Minor grammatical error in Guest User restriction text

---

app/diagnostics.go
report.xml

Cherry pick of #13844 on release-5.20.
- #13844: Merge upstream

Automated cherry pick of #13844

---

Makefile

Cherry pick of #13836 on release-5.20.
- #13836: Bump zoom plugin version to v1.3.0
/cc  @jfrerich

Automated cherry pick of #13836

---

app/diagnostics.go

Cherry pick of #13868 on release-5.20.
- #13868: Add missing "AutomaticPrepackagedPlugins" to diagnostics.go

Automated cherry pick of #13868

---

.circleci/config.yml
build/Jenkinsfile.pr

Lock CI for the next release. 
Previous error will be fixed by this PR: https://github.com/mattermost/mattermost-server/pull/13915

Lock Release 5.21

---

app/plugin_hooks_test.go
plugin/environment.go
plugin/supervisor.go

Cherry pick of #13604 on release-5.21.
- #13604: MM-20865 - Demo Plugin: Enabling and disabling demo

Automated cherry pick of #13604

---

api4/apitestlib.go
api4/channel.go
api4/channel_test.go
api4/team.go
api4/team_test.go
app/channel.go
app/channel_test.go
app/helper_test.go
app/user.go
i18n/en.json

Manual cherry-pick of #13672

---

app/file.go
web/handlers.go

Cherry pick of #13827 on release-5.21.
- #13827: MM-22057: Limit incoming request bodies
/cc  @agnivade

Automated cherry pick of #13827

---

model/websocket_client.go

Cherry pick of #13655 on release-5.21.
- #13655: Terminate WebSocketClient.pingWatchdog goroutine when closing

Automated cherry pick of #13655

---

i18n/en.json

Cherry pick of #13847 on release-5.21.
- #13847: fixed wording
/cc  @reflog

Automated cherry pick of #13847

---

api4/team.go
api4/user.go
app/import_functions.go
app/slackimport.go
app/user.go
cmd/mattermost/commands/team.go
cmd/mattermost/commands/user.go
model/gitlab/gitlab.go
model/utils.go
model/utils_test.go
web/context.go

Cherry pick of #13794 on release-5.21.
- #13794: Enable uppercase letters in the email
/cc  @iomodo

Automated cherry pick of #13794

---

store/localcachelayer/layer.go

Insert appropriate spaces and comments where needed.
As promised in https://github.com/mattermost/mattermost-server/pull/13784.

Clean localcache/layer.go

---

store/storetest/plugin_store.go

In submitting https://github.com/mattermost/mattermost-server/pull/13942, I encountered a flaky test caused by my original changes, and then discovered a coverage issue with the original code. This pull request addresses both issues.
https://mattermost.atlassian.net/browse/MM-21672

Improved kv testing

---

app/plugin_test.go
model/plugin_kvset_options.go
store/sqlstore/plugin_store.go
store/sqlstore/plugin_store_test.go
store/storetest/plugin_store.go

This is a clean cherry-pick of the various changes to address a number of issues with the plugin key value store.
* https://mattermost.atlassian.net/browse/MM-22074 (https://github.com/mattermost/mattermost-server/pull/13769)
* https://github.com/mattermost/mattermost-server/pull/13753
* https://mattermost.atlassian.net/browse/MM-21672 (https://github.com/mattermost/mattermost-server/pull/13858)
* https://github.com/mattermost/mattermost-server/pull/13943

KV set improvements for 5.21

---

api4/channel.go
api4/channel_test.go
api4/commands_test.go
app/channel_test.go
model/client4.go
web/params.go

Cherry pick of #13877 on release-5.21.
- #13877: Include deleted channels user channels endpoint

Automated cherry pick of #13877

---

go.mod
go.sum
vendor/golang.org/x/crypto/acme/acme.go
vendor/golang.org/x/crypto/acme/autocert/listener.go
vendor/modules.txt

Cherry pick of https://github.com/mattermost/mattermost-server/pull/13930

update golang.org/x/crypto (#13930)

---

model/version.go
store/sqlstore/upgrade.go

- upgrade db to 5.21
/cc @amyblais

db: upgrade db to 5.21

---

i18n/es.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/ru.json

translations PR 20200302

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ru.json

translations PR 20200309

---

store/sqlstore/user_store.go

`GetAllProfilesInChannel` is being called frequently from `App.SendNotification`. This PR optimizes that path by removing reflection overhead caused by gorp.
https://mattermost.atlassian.net/browse/MM-22066

MM-22066  - rewrote GetAllProfilesInChannel to avoid using gorp

---

store/storetest/post_store.go

Fixing flaky tests on save multiple posts
[MM-23226](https://mattermost.atlassian.net/browse/MM-23226)

Fixing flaky tests on save multiple posts

---

app/notification_push_test.go

3rd PR in the series. This branch compares with the previous PR's branch.
- Add synthetic benchmark.
This benchmark uses a mock store with a dummy push notification server,
so that everything happens in-memory.
We create 50 users each having 2 sessions. And we send 2 messages
from each user of various message types. We repeat the entire
thing in a loop.
https://mattermost.atlassian.net/browse/MM-23276

MM-23276: Refactor push notifications (Part 3)

---

app/notification_push_test.go

2nd PR in the series. This branch compares with the previous PR's branch.
- Add tests to cover all scenarios. Brings up the test coverage
from 70% to 87%.
- Add a test http server handler to verify that requests are being
properly sent and check their contents.
- Also verify that messages are sent in order per user.
https://mattermost.atlassian.net/browse/MM-23276

MM-23276: Refactor push notifications (Part 2)

---

app/notification_push.go
app/notification_push_test.go

- Unexport types that are not used from outside app
- Convert if-else to a switch to make it more idiomatic
https://mattermost.atlassian.net/browse/MM-23276

MM-23276: Refactor push notifications (Part 1)

---

.circleci/config.yml
build/Jenkinsfile.pr

Lock 5.22 CI.

---

app/user_agent.go
app/user_agent_test.go

https://mattermost.atlassian.net/browse/MM-22167

[MM-22167] Add mmctl to the User-Agent parser

---

app/channel.go

Cherry pick of #14042 on release-5.22.
- #14042: MM-22368 Log Channel Moderation events
/cc  @fm2munsh

Automated cherry pick of #14042

---

model/config.go
model/config_test.go

These are some very modest code coverage changes made as part of speaking to students from the Free University of Tbilisi today.
See https://docs.google.com/presentation/d/1tVH2kw_WJ5_rCCOIGHPxVc8O07g1zHK0hQIloCwEYAk/edit#slide=id.g8175639bd3_0_52 for the original slides and https://github.com/mattermost/mattermost-developer-documentation/pull/564 for the blog post.

Minor model/config.go coverage improvements

---

app/export_converters.go
app/export_test.go
app/import_functions.go
app/import_test.go
app/import_types.go

This PR is to merge the changes from PR #14034 into the 5.22 release branch.

cherry pick PR #14034 into 5.22 release branch

---

.circleci/config.yml
build/Dockerfile.buildenv
build/Jenkinsfile.branch
build/Jenkinsfile.pr
build/README.md
build/local-test-env.sh
plugin/helpers_plugin_test.go

Reverts mattermost/mattermost-server#14123

Revert "IS-364: Bump Golang CI."

---

app/plugin_api.go
app/plugin_api_test.go

Cherry pick of #14125 on release-5.22.
- #14125: Fix plugin API's GetPostsForChannel

Automated cherry pick of #14125

---

.circleci/config.yml
build/Dockerfile.buildenv
build/Jenkinsfile.branch
build/Jenkinsfile.pr
build/README.md
build/local-test-env.sh
model/config.go
model/config_test.go

https://github.com/mattermost/mattermost-server/pull/14123 was accidentally merged and reverted. This is the revert of the revert. 
https://mattermost.atlassian.net/browse/IS-364

IS-364: Bump golang build image. 

---

store/searchlayer/post_layer.go

https://mattermost.atlassian.net/browse/MM-23510

[MM-23510] Avoid race condition searching post's channel by channel id instead of post id

---

store/searchlayer/post_layer.go

Cherry pick of #14154 on release-5.22.
- #14154: Avoid race condition searching post's channel by

Automated cherry pick of #14154

---

scripts/depcheck-alert.sh

Include links to PRs and the suppression file in depcheck alerts.

Update depcheck alert messages

---

store/localcachelayer/layer.go
store/localcachelayer/role_layer.go
store/localcachelayer/scheme_layer.go
store/localcachelayer/team_layer.go

Cherry pick of #14156 on release-5.22.
- #14156: MM-23606: Fix role cache invalidation.
/cc  @mkraft

Automated cherry pick of #14156

---

app/app.go
app/app_iface.go
app/enterprise.go
app/file.go
app/opentracing_layer.go
app/server.go
app/server_app_adapters.go
app/web_hub.go

Removing some unneded FakeApp instance
[MM-23561](https://mattermost.atlassian.net/browse/MM-23561)
mattermost/enterprise#599

Removing some unneded FakeApp instance

---

plugin/hooks.go

Documents minimum server version required for plugin hooks
Fixes https://github.com/mattermost/mattermost-server/issues/14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mattermost/mattermost-server/14153)

[GH-14136] Document minimum server version required for plugin hooks

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200330

---

store/searchlayer/channel_layer.go

Cherry pick of #14209 on release-5.22.
- #14209: avoid panic in search channel store

Automated cherry pick of #14209

---

api4/channel_test.go
app/channel.go

Cherry pick of #14210 on release-5.22.
- #14210: MM-23770: Fix for blank DefaultChannelGuestRole on team
/cc  @mkraft

Automated cherry pick of #14210

---

store/searchlayer/user_layer.go

Fixing searching users without team
[MM-23610](https://mattermost.atlassian.net/browse/MM-23610)

Fixing searching users without team

---

.circleci/config.yml

IS-255: Remove trigger for now.

---

Makefile
config/default.go
go.mod
utils/test_files_compiler.go
vendor/modules.txt

With Go 1.14 (https://tip.golang.org/doc/go1.14#go-command),
it now automatically checks for the existence of a vendor directory.
So there is no need to explicitly set the `-mod=vendor` flag.
https://mattermost.atlassian.net/browse/MM-23817

MM-23817: Use auto-vendoring

---

store/sqlstore/upgrade.go

Upgrade DB to 5.22
/cc @amyblais

db: upgrade db to 5.22

---

store/sqlstore/upgrade.go

Cherry pick of #14224 on release-5.22.
- #14224: db: upgrade db to 5.22
/cc  @cpanato

Automated cherry pick of #14224

---

api4/channel_test.go
app/channel.go
model/role.go

Cherry pick of #14239 on release-5.22.
- #14239: MM-23876: Fix for patching channel moderations with a
/cc  @mkraft

Automated cherry pick of #14239

---

.circleci/config.yml
Makefile
api4/api.go

This PR introduces additional Mattermost GoVet check for verifying that all API endpoints are properly documented.

OpenAPI Mattermost Go Vet integration

---

build/Dockerfile

Update the placeholder in the docker file to use the latest release available

update dockerfile to use the latest release available

---

store/sqlstore/upgrade.go

db: prepare db upgrade to 5.23

---

Makefile
app/app_iface.go
app/layer_generators/main.go
app/opentracing_layer.go

1. A bug was found in struct2interface (multiple named parameters were not supported), it was fixed, and interface regenerated
2. I've re-enabled struct2interface in makefile `make app-layers` command as previously discussed with @jespino

fixed app-layer generator, re-enabled struct2interface in makefile

---

app/diagnostics.go
store/opentracing_layer.go
store/sqlstore/user_store.go
store/store.go
store/storetest/mocks/UserStore.go
store/storetest/user_store.go
store/timer_layer.go

Adding guest accounts count telemetry
[MM-23697](https://mattermost.atlassian.net/browse/MM-23697)

Adding guest accounts count telemetry

---

store/opentracing_layer.go
store/timer_layer.go

Fixed some missing methods in the opentracing and timelayer layers
`CountByScope` was added in [this PR](https://github.com/mattermost/mattermost-server/pull/14095) and `RemoveMembers` was added in [this PR](https://github.com/mattermost/mattermost-server/pull/14053)

Add some missing methods in time and opentracing layers

---

app/diagnostics.go

Add IdleTimeout to telemetry
https://mattermost.atlassian.net/browse/MM-24095

MM-24095: Add IdleTimeout to telemetry

---

api4/command_test.go
api4/post_test.go
app/channel_test.go
app/command.go
app/command_test.go
app/file.go
app/integration_action.go
app/integration_action_test.go
app/notification.go
app/notification_push.go
app/notification_test.go
app/plugin_deadlock_test.go
app/post.go
app/post_metadata.go
app/post_metadata_test.go
app/post_test.go
app/webhook.go
app/webhook_test.go
model/integration_action.go
model/post.go
model/post_list.go
model/post_test.go
plugin/example_help_test.go
store/sqlstore/post_store.go
store/storetest/post_store.go

Cherry-pick for MM-21378 on 5.19

Cherrypick for MM-21378

---

i18n/de.json
i18n/es.json
i18n/it.json
i18n/ko.json
i18n/pt-BR.json
i18n/ro.json
i18n/zh-CN.json

translations PR 20200413

---

store/opentracing_layer.go
store/storetest/mocks/GroupStore.go
store/timer_layer.go

Looks like this https://github.com/mattermost/mattermost-server/pull/14010 was merged without running `make store-layers` maybe before the ci check was added? 
- none dev only changes

Fix broken master build by updating store

---

i18n/de.json
i18n/fr.json
i18n/ro.json

translations PR 20200414

---

store/sqlstore/team_store.go

Documenting 'sqlTeamStore' analytics methods
JIRA: [https://mattermost.atlassian.net/browse/MM-22997](https://mattermost.atlassian.net/browse/MM-22997)
GitHub #14009

Document 'sqlTeamStore' analytics methods

---

dependency-suppression.xml

Adds data_tools_project CPE to suppressions.

Update Dependency-Check suppressions

---

app/diagnostics.go

Cherry pick of #14279 on release-5.23.
- #14279: MM-24095: Add IdleTimeout to telemetry
/cc  @agnivade

Automated cherry pick of #14279

---

model/websocket_client.go
model/websocket_client_test.go

Cherry pick of #14160 on release-5.23.
- #14160: MM-23503: Fix race in websocket_client writer
/cc  @agnivade

Automated cherry pick of #14160

---

app/notification.go
app/notification_test.go

Cherry pick of #14097 on release-5.23.
- #14097: MM-23211: Fix user not being notified in out of channel
/cc  @agnivade

Automated cherry pick of #14097

---

api4/channel.go
api4/channel_test.go

Cherry pick of #14302 on release-5.23.
- #14302: Remove unnecessary check for

Automated cherry pick of #14302

---

app/diagnostics.go

Cherry pick of #14298 on release-5.23.
- #14298: added enable_opentracing to diagnostics
/cc  @reflog

Automated cherry pick of #14298

---

store/opentracing_layer.go
store/sqlstore/post_store.go
store/timer_layer.go

Removing accidentally included debug log

Removing accidentally included debug log

---

app/web_conn.go
app/web_hub.go
app/web_hub_test.go

Cherry pick of #13799 on release-5.23.
- #13799: MM-22044: Fix panic on web_conn send hello
/cc  @agnivade

Automated cherry pick of #13799

---

app/cluster_handlers.go
model/websocket_client.go

Cherry pick of #14050 on release-5.23.
- #14050: MM-23254: Add nil checks to WebSocketEventFromJson
/cc  @agnivade

Automated cherry pick of #14050

---

app/diagnostics.go
store/sqlstore/store.go
store/sqlstore/supplier.go
store/sqlstore/supplier_test.go
store/store.go
store/storetest/mocks/SqlStore.go
store/storetest/mocks/Store.go
store/storetest/store.go

Cherry pick of #14258 on release-5.23.
- #14258: Add database server version to telemetry

Automated cherry pick of #14258

---

app/diagnostics.go

Cherry pick of #14283 on release-5.23.
- #14283: app/diagnostics: add telemetry for smtp_server_timeout

Automated cherry pick of #14283

---

app/channel.go
app/channel_test.go

Cherry pick of #14204 on release-5.23.
- #14204: MM-23620: Handle error from GetUser
/cc  @agnivade

Automated cherry pick of #14204

---

app/user.go

Cherry pick of #14334 on release-5.23.
- #14334: ensure updating Mfa secret and status invalidates cache
/cc  @wiggin77

Automated cherry pick of #14334

---

app/post.go
app/post_test.go
testlib/assertions.go

Cherry pick of #14253 on release-5.23.
- #14253: MM-23926: avoid setting last viewed for bots

Automated cherry pick of #14253

---

i18n/nl.json
i18n/ru.json
i18n/zh-CN.json

translations PR 20200420

---

model/utils.go
model/utils_test.go
services/mfa/mfa.go
services/mfa/mfa_test.go

Cherry-pick of MM-23684 onto `release-5.23` branch.

Cherry-pick of MM-23684

---

app/channel.go
app/channel_test.go
i18n/en.json
model/channel.go

[MM-23727] Make channel validation consistent on the server (#14230) 

---

app/team.go
model/websocket_message.go

[MM-23605] Create new team scheme updated socket event (#14305)

---

app/app_iface.go
app/notification.go
app/notification_test.go
app/opentracing_layer.go

Cherry pick of #14254 on release-5.23.
- #14254: Fixing system messages about non-visible users
/cc  @jespino

Automated cherry pick of #14254

---

model/utils.go

Updates the list of restricted team names with all existing client routes. Plus `plug` which will be added with https://github.com/mattermost/mattermost-webapp/pull/5367
https://mattermost.atlassian.net/browse/MM-24516

MM-24516 Update restricted team names.

---

dependency-suppression.xml

Suppress a jQuery issue that doesn't affect us.

Suppress jQuery issue in Dependency-Check

---

i18n/en.json
store/sqlstore/audit_store.go

This pull request refactors the audit store to use squirrel queries instead of raw SQL queries.

Refactor audit_store to use squirrel

---

app/auto_responder.go
app/post.go

Cherry-pick of https://mattermost.atlassian.net/browse/MM-24651
https://mattermost.atlassian.net/browse/MM-24651

MM-24575 & MM-24651 cherry-pick 

---

app/app.go
app/app_test.go
app/config.go
app/enterprise_test.go
app/notification_push_test.go
app/plugin_signature_test.go
app/post_test.go
app/server.go
app/server_app_adapters.go
model/system.go
testlib/store.go
web/handlers_test.go

Cherry-pick https://github.com/mattermost/mattermost-server/pull/14374

Cherry-pick 4374

---

app/import_functions.go

MM-24707 fix reply import bug (#14442)

---

app/import_functions.go

MM-24707 cherry pick - fix reply bulk import bug

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200427

---

model/version.go
store/sqlstore/upgrade.go

upgrade DB to 5.23 on release branch 5.23
/cc @amyblais

upgrade db to 5.23

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200504

---

store/sqlstore/license_store.go

This pull request refactors the license store to use squirrel queries instead of raw SQL queries.

[MM-24662] Refactor license_store to use squirrel Closes #14422

---

app/command_autocomplete.go
app/plugin_commands.go
model/command.go
model/command_autocomplete.go

This PR will add support of the icons in slash command autocomplete
Fixes https://mattermost.atlassian.net/browse/MM-24767
webapp - https://github.com/mattermost/mattermost-webapp/pull/5450
demoplugin -https://github.com/mattermost/mattermost-plugin-demo/pull/104

Add support for icons

---

store/sqlstore/user_store.go

Correct copy-paste error in log message.
n/a

Fix log message typo.

---

app/channel.go
app/channel_test.go

* MM-24987 Dont call a.GetSchemeRolesForChannel and instead load the scheme using the channel directly
* Trigger CI
* MM-24987 Add a test for concurrent patch to channel moderation
* MM-24987 Cleanup
Cherry pick of https://github.com/mattermost/mattermost-server/pull/14514

cherry-pick of [MM-24987] Dont call GetSchemeRolesForChannel and instead load the scheme from channel 

---

app/channel.go
app/channel_test.go

- Cherry pick of #14514 for 5.22 dot release

cherry-pick of [MM-24987] Dont call GetSchemeRolesForChannel and instead load the scheme from channel

---

i18n/de.json
i18n/ja.json
i18n/nl.json

translations PR 20200511

---

api4/api.go
api4/plugin_local.go
api4/plugin_test.go

https://mattermost.atlassian.net/browse/MM-24833
https://mattermost.atlassian.net/browse/MM-24834
https://mattermost.atlassian.net/browse/MM-24835
https://mattermost.atlassian.net/browse/MM-24836

[MM-24832] Migrate plugin endpoints to local mode

---

api4/api.go
api4/config_local.go
api4/config_test.go

https://mattermost.atlassian.net/browse/MM-24776
https://mattermost.atlassian.net/browse/MM-24777

[MM-24776] Migrate config endpoints to local mode

---

.circleci/config.yml

Cut release

---

app/diagnostics.go
store/opentracing_layer.go
store/sqlstore/group_store.go
store/store.go
store/storetest/group_store.go
store/storetest/mocks/GroupStore.go
store/timer_layer.go

- Manual cherry-pick of #14614

[MM-25385] Add group_count_with_allow_reference telemetry (#14614)

---

i18n/en.json

https://mattermost.atlassian.net/browse/MM-25413

MM-25413: Fix empty localization string

---

i18n/en.json

Fix typo (alredy -> already), add missing periods
Reported at https://community.mattermost.com/core/pl/ftsmmf4repn83e7kop6opkuazy

Fix typo (alredy -> already), add missing periods

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200525

---

app/team.go
i18n/en.json
store/opentracing_layer.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/mocks/ChannelStore.go
store/timer_layer.go

When a user leaves a team, we should remove the corresponding entries from the SidebarCategories and SidebarChannels tables in the database.
https://mattermost.atlassian.net/browse/MM-25276

MM-25276  Remove categories when leaving a team

---

app/channel_test.go
store/sqlstore/channel_store.go

Ensure that the new category order includes the IDs of all categories and that none of the IDs are invalid
https://mattermost.atlassian.net/browse/MM-25280

MM-25280  Ensure that the "update category order" API call only contains real category IDs and isn't missing any IDs

---

app/diagnostics.go

Cherry pick of #14661 on release-5.24.
- #14661: MM-25388 Add telemetry for default picture attribute
/cc  @fmunshi

Automated cherry pick of #14661

---

api4/apitestlib.go
api4/channel_test.go
api4/group_test.go
api4/ldap.go
app/group_test.go
app/helper_test.go
app/notification.go
app/notification_test.go
app/syncables_test.go
cmd/mattermost/commands/group_test.go
model/auditconv.go
model/group.go
store/sqlstore/upgrade.go
store/storetest/channel_store.go
store/storetest/group_store.go
store/storetest/user_store.go

Cherry pick of #14651 on release-5.24.
- #14651: make Group.Name a pointer to allow null
/cc  @sbishel

Automated cherry pick of #14651

---

app/post_test.go
app/server.go
app/server_app_adapters.go
app/server_test.go
config/utils.go
config/utils_test.go
model/config.go
model/config_test.go
store/sqlstore/supplier.go
store/sqlstore/supplier_test.go

Cherry-pick of PR #14576

---

app/channel.go
model/client4.go

Cherry pick of #14635 on release-5.24.
- #14635: MM-24517: Add newly created channel admin role to redux
/cc  @mkraft

Automated cherry pick of #14635

---

store/sqlstore/status_store.go

We're removing the usage of gorp in some of the most used
queries in our system. This is one of them
https://mattermost.atlassian.net/browse/MM-24091

Move StatusStore.GetByIds away from gorp

---

api4/api.go
api4/group_local.go
api4/group_test.go

- local mode for getGroupsByChannel
- local mode for getGroupsByTeam
- https://mattermost.atlassian.net/browse/MM-25073
- https://mattermost.atlassian.net/browse/MM-25074

MM-25073/MM-25074: local mode for getGroupsByChannel and getGroupsByTeam

---

services/searchengine/bleveengine/search.go

Cherry pick of #14664 on release-5.24.
- #14664: Adds the termOperator and takes it into account

Automated cherry pick of #14664

---

.circleci/config.yml

https://github.com/mattermost/enterprise/pull/675

Fix webapp checkout

---

app/diagnostics.go
config/client.go
model/config.go

Adds an experimental setting for disabling prefetching of posts
PR for prefetching: https://github.com/mattermost/mattermost-webapp/pull/5547
https://mattermost.atlassian.net/browse/MM-25723

MM-25723 Add an experimental setting for data prefetching

---

app/diagnostics.go

Cherry pick of #14684 on release-5.24.
- #14684: Add Jitsi plugin to diagnostics

Automated cherry pick of #14684

---

app/import.go

This PR makes the importer correctly report errors if there is a problem when importing multiple posts. The patch doesn't make line number reporting accurate, that will come in a follow up PR as part of [this ticket](https://mattermost.atlassian.net/browse/MM-25714).
https://mattermost.atlassian.net/browse/MM-25712

[MM-25712] Fix silent errors on post import failures

---

api4/bot_test.go
app/bot.go
app/user.go
go.sum

Cherry pick of #14699 on release-5.24.
- #14699: invalidate the user profile cache bc we know it's now
/cc  @cpoile

Automated cherry pick of #14699

---

app/import.go

Cherry pick of #14729 on release-5.24.
- #14729: Fix silent errors on post import failures

Automated cherry pick of #14729

---

api4/post_test.go

This PR adds a fix to a test case by adding some time to wait events from the websocket pipeline.
https://mattermost.atlassian.net/browse/MM-25716

[MM-25716] api4/post_test: add timeout to TestCreatePostCheckOnlineStatus

---

store/sqlstore/upgrade.go

upgrade db to 5.24 for master branch
n/a
/cc @amyblais

database: upgrade db to 5.24

---

store/sqlstore/upgrade.go

Cherry pick of #14749 on release-5.24.
- #14749: database: upgrade db to 5.24
/cc  @cpanato

Automated cherry pick of #14749

---

store/sqlstore/group_store.go
store/storetest/group_store.go

Cherry pick of #14746 on release-5.24.
- #14746: MM-25737: Fix for groups list not returning results.
/cc  @mkraft

Automated cherry pick of #14746

---

build/Dockerfile

dockerfile: bump base MM package to 5.23.1
I will cherry pick this to release-5.23 branch to sync
n/a

dockerfile: bump base MM package to 5.23.1

---

app/import.go
app/import_functions.go
app/import_functions_test.go
store/opentracing_layer.go
store/sqlstore/post_store.go
store/store.go
store/storetest/mocks/PostStore.go
store/storetest/post_store.go
store/timer_layer.go

https://mattermost.atlassian.net/browse/MM-25714

[MM-25714] Keeps track of the import lines of the posts while importing to report the right line on error

---

app/import_functions.go

Fixes bad import due cherry-pick conflict

---

build/docker-compose.yml
docker-compose.yaml

Reverts mattermost/mattermost-server#14771

Revert "Docker compose network"

---

app/diagnostics.go

Add telemetry for new config settings.
https://mattermost.atlassian.net/browse/MM-24483

MM-24483: Add telemetry for new config settings.

---

services/mailservice/mail_test.go

This PR adds applies a fix to a test case which seems to be leading to a conflicting port.
https://mattermost.atlassian.net/browse/MM-25715

[MM-25715] services/mailservice: fix a flaky test

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

translations PR 20200608

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

Fix the reply count for pinned posts
[MM-17468](https://mattermost.atlassian.net/browse/MM-17468)

Fix the reply count for pinned posts

---

i18n/en.json

Cherry pick of #14791 on release-5.24.
- #14791: Fix bleve error string

Automated cherry pick of #14791

---

app/post_metadata.go
app/post_metadata_test.go

added post sanitation for deleted posts
https://mattermost.atlassian.net/browse/MM-25450

MM-25450  deleted posts should be  sanitised

---

api4/api.go
api4/system_local.go
api4/system_test.go

- local mode handler for getLogs
- https://mattermost.atlassian.net/browse/MM-25075

MM-25075: local mode for getLogs

---

store/sqlstore/team_store.go

Document SqlTeamStore delete methods
Fixes https://github.com/mattermost/mattermost-server/issues/14005
JIRA: [https://mattermost.atlassian.net/browse/MM-23001](https://mattermost.atlassian.net/browse/MM-23001)

Document SqlTeamStore delete methods

---

plugin/api_timer_layer_generated.go
plugin/hooks_timer_layer_generated.go
plugin/interface_generator/main.go

Template update to check for error return value to be `nil` if it exists otherwise defaults to `true`.
Closes #14754 on Github
Closes JIRA https://mattermost.atlassian.net/browse/MM-25779

MM-25779 - Update apiTimerLayerTemplate and hooksTimerLayerTemplate to record error values

---

app/app.go
app/server_app_adapters.go

Fixing plugin routes broken because the fake app removal

Fixing plugin routes

---

app/enterprise.go
app/server.go

Moving back saml to the fakeapp approach

Moving back saml to the fakeapp approach

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

Cherry pick of #14673 on release-5.25.
- #14673: MM-24674 Update channel members by group to look at
/cc  @fmunshi

Automated cherry pick of #14673

---

config/client.go
config/client_test.go

Cherry pick of #14777 on release-5.25.
- #14777: Moved password settings to limited configuration

Automated cherry pick of #14777

---

app/integration_action.go
app/integration_action_test.go

Cherry pick of #14366 on release-5.25.
- #14366: Pass query string params to interactive dialog request
/cc  @Ashniu123

Automated cherry pick of #14366

---

api4/team.go
api4/team_test.go
i18n/en.json

Cherry pick of #14797 on release-5.25.
#14797: fix teamImport panic and return better error

Manual cherry pick of #14797

---

api4/channel_test.go
api4/team_test.go

Applying the same fix done in #14840

MM-26376: Fix flaky test SearchAllChannels

---

api4/user_test.go
i18n/en.json
model/config.go
model/config_test.go

Co-authored-by: mattermod <mattermod@users.noreply.github.com>
(cherry picked from commit 938176be3e93c1fb4bb3818ba335a97c6393235c)

MM-24467-Manual Cherry Pick

---

api4/api.go
api4/role_local.go
api4/role_test.go

This PR adds ole endpoints to local mode.
https://mattermost.atlassian.net/browse/MM-25076
https://mattermost.atlassian.net/browse/MM-25077

[MM-25076] api4/role: add role endpoints to local mode

---

store/sqlstore/scheme_store.go

[MM-24560] [cherry-pick] Clear team cache on delete team scheme (#14671)

---

i18n/en.json
model/group.go
store/storetest/group_store.go

* update error message for length violations
* fix unit test
(cherry picked from commit 53ef4d120b119f03305b34d680a0c52c100b81ef)

MM-25544-Manual Cherry Pick

---

einterfaces/ldap.go
einterfaces/mocks/LdapInterface.go

(cherry picked from commit 23e306bc3accd9545f877299b2a14227a8389436)

MM-25039-cp Manual Cherry Pick

---

store/storetest/channel_store.go

The same problem as #14840 plagues this test too.
https://mattermost.atlassian.net/browse/MM-26452

MM-26452: Fix flaky test ChannelStore//SearchInTeam/the_in_name

---

app/integration_action.go
app/integration_action_test.go

MM-26441 - fix for doPluginRequest (#14897)

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

Check whether or not the default sidebar categories exist before trying to create them to avoid potentially creating duplicates in weird cases.
This unfortunately can't be prevented with a unique constraint like we originally wanted to do because the a user can have any number of `custom` categories. It sounds like Postgres has a way to do this with a partial unique constraint, but nothing like that exists for MySQL.
https://mattermost.atlassian.net/browse/MM-26343

MM-26343 Make CreateInitialSidebarCategories idempotent

---

model/version.go
store/sqlstore/upgrade.go

- upgrade DB to 5.25 on the release branch
n/a
cc @amyblais

upgrade DB to 5.25 on the release branch

---

store/sqlstore/upgrade.go

- upgrade db to 5.25
n/a
cc @amyblais

upgrade db to 5.25

---

build/Dockerfile

- update base image alpine to use release 3.12
- update MM package to use 5.24.2 as default
n/a
We can cherry pick this to the release 5.24 branch as well

Update Dockerfile 

---

api4/user.go
app/app_iface.go
app/login.go
app/oauth.go
app/opentracing_layer.go
app/plugin_hooks_test.go
app/session.go
app/session_test.go
model/saml.go
model/session.go
web/oauth.go
web/saml.go

Cherry Pick https://github.com/mattermost/mattermost-server/pull/14874

Cherry Pick 

---

api4/license.go
i18n/en.json
model/license.go

Adding terms_accepted and receive_emails_accepted params to request trial
[MM-26481](https://mattermost.atlassian.net/browse/MM-26481)

Adding terms_accepted and receive_emails_accepted params to request trial

---

api4/license.go
i18n/en.json
model/license.go

Manual cherry pick of PR #15937

Adding terms_accepted and receive_emails_accepted params to request trial (#14937)

---

cmd/mattermost/commands/jobserver.go

Fix jobserver run

---

app/diagnostics.go
config/client.go
model/config.go

The setting for disabling ask community links on the UI
https://mattermost.atlassian.net/browse/MM-26620

MM-26620 Add a config setting for controlling ask community link

---

i18n/en.json
store/opentracing_layer.go
store/sqlstore/cluster_discovery_store.go
store/store.go
store/storetest/mocks/ClusterDiscoveryStore.go
store/timer_layer.go

Migration of `ClusterDiscoveryStore` to return plain errors.
Fixes https://github.com/mattermost/mattermost-server/issues/14596

ClusterDiscoveryStore migration

---

i18n/nl.json
i18n/pt-BR.json

https://github.com/mattermost/mattermost-mobile/pull/4552

Fix i18n release-5.25

---

store/sqlstore/scheme_store.go

- Manual cherry-pick of (#14989)

[MM-24560] [cherry-pick] Always clear channel cache when scheme is deleted (#14989)

---

app/analytics.go
app/expirynotify.go
app/notification_push.go
app/oauth.go
app/session.go
app/session_test.go
app/user.go
i18n/en.json
store/opentracing_layer.go
store/sqlstore/session_store.go
store/store.go
store/storetest/mocks/SessionStore.go
store/storetest/oauth_store.go
store/storetest/session_store.go
store/storetest/user_access_token_store.go
store/timer_layer.go

Migration of `SessionStore` to return plain errors.
Fixes https://github.com/mattermost/mattermost-server/issues/15006
Jira ticket: https://mattermost.atlassian.net/browse/MM-26843

SessionStore migration

---

api4/channel_local.go
api4/channel_test.go

https://mattermost.atlassian.net/browse/MM-24602

[MM-24602] Adds local patch channel endpoint

---

api4/system_local.go
api4/system_test.go

https://mattermost.atlassian.net/browse/MM-25089
https://mattermost.atlassian.net/browse/MM-25090
https://mattermost.atlassian.net/browse/MM-25088

[MM-25089] Migrate server busy endpoints to local mode

---

api4/team_test.go

Updates the names on some test that were incorrectly named initially
https://mattermost.atlassian.net/browse/MM-26720

[MM-26720] Update testing names

---

store/sqlstore/channel_store.go

There's currently logic where orphaned channels (channels without a category) are automatically added to the DMs and Channels categories to prevent them from being inaccessible. This is done by calling `completePopulatingCategoryChannels` on those categories before returning them to the client. Any issues with that function are more prominent in DMs since we don't create SidebarChannels entries for the DMs category because it doesn't support manual ordering.
The problem we have currently is that any changes made are ran on the database master and `completePopulatingCategoryChannels` is ran on a replica, so if there's any lag between the two servers, the call to `completePopulatingCategoryChannels` will include stale data. This causes duplicated DMs when moving a DM into another category …

MM-26826 Populate orphaned channels in a transaction

---

app/oauth.go
app/oauth_test.go
app/session.go
app/user.go
i18n/en.json
store/opentracing_layer.go
store/sqlstore/oauth_store.go
store/store.go
store/storetest/mocks/OAuthStore.go
store/storetest/oauth_store.go
store/timer_layer.go
web/oauth_test.go

This PR adds the `OAuthStore` to return plain errors on top of release-5.26 branch.

Cherry-Pick OAuthStore migration - Release 5.26

---

store/sqlstore/upgrade.go

Prepare DB to upgrade to 5.27
waiting for https://github.com/mattermost/mattermost-server/pull/15068 to be merged first
n/a

db: prepare db upgrade to 5.27

---

Makefile
scripts/prereq-check-enterprise.sh

- Check enterprise prereqs before running full tests. Some devs don't have them installed, so better to fail early with message.
- https://mattermost.atlassian.net/browse/MM-26886

[MM-26886]: check enterprise prereqs before running tests

---

api4/user_local.go
api4/user_test.go

https://mattermost.atlassian.net/browse/MM-27170

[MM-27170] Migrate verify user by id endpoint to local mode

---

api4/channel.go
api4/channel_test.go
app/channel.go
model/channel.go
model/channel_search.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/channel_store.go

* MM-25990 Add filters to search all channels endpoint and clean up tests
* Add deleted filter
* Remove redundant private public query
Manual cherry-pick

[MM-25990] Add filters to search all channels (#15009)

---

i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

Weblate mattermost mattermost server release 5 26

---

app/app.go

Fix invalid reference to non-instantiated var.
https://mattermost.atlassian.net/browse/MM-27197

MM-27197 - fix reference to non-instantiated error var

---

app/diagnostics.go

https://mattermost.atlassian.net/browse/MM-25050

MM-25050: Add gossip encryption to telemetry

---

app/diagnostics.go

Cherry pick of #15137 on release-5.26.
/cc  @agnivade

Automated cherry pick of #15137

---

app/admin.go

Cherry pick of #15138 on release-5.26.
/cc  @cpanato

Automated cherry pick of #15138

---

build/Dockerfile

Cherry pick of #15153 on release-5.26.
/cc  @cpanato

Automated cherry pick of #15153

---

app/user.go
i18n/en.json

Fix empty string on app error

---

api4/channel_test.go
app/channel.go

Cherry pick of #15149 on release-5.26.
/cc  @fmunshi

Automated cherry pick of #15149

---

model/post.go
model/post_test.go

Cherry pick of #14972 on release-5.25.
/cc  @agnivade

Automated cherry pick of #14972

---

i18n/en.json

For context, see https://community.mattermost.com/private-core/pl/zofoam4moigsbfuch8t3d8jrrc
@amyblais candidate for 5.26

Update "Enterprise E20" to "Enterprise Edition"

---

app/team.go

Cherry pick of #15193 on release-5.26.
/cc  @hahmadia

Automated cherry pick of #15193

---

app/team.go

Cherry pick of #15193 on release-5.25.
/cc @hahmadia

Cherry pick of #15193

---

i18n/en.json

Cherry pick of #15194 on release-5.26.

Automated cherry pick of #15194

---

model/channel_member_history_result.go
store/sqlstore/channel_member_history_store.go

We don't want to include deactivated users in compliance report.
Credit to @mkraft for doing the majority of this work 👍 
https://mattermost.atlassian.net/browse/MM-27194

[MM-27194] Dont include users who have been deactivated in compliance report

---

i18n/en.json

Cherry pick of #15199 on release-5.26.

Automated cherry pick of #15199

---

cmd/mattermost/commands/export.go
config/utils.go
i18n/en.json
model/config.go

Cherry pick of #15100 on release-5.26.

Automated cherry pick of #15100

---

model/channel_member_history_result.go
store/sqlstore/channel_member_history_store.go

Cherry pick of #15191 on release-5.26.
/cc @hahmadia

Cherry pick of #15191 release-5.26

---

model/channel_member_history_result.go
store/sqlstore/channel_member_history_store.go

Cherry pick of #15191 on release-5.25.
/cc @hahmadia

Cherry pick of #15191 release-5.25

---

api4/channel_local.go
api4/channel_test.go
app/channel.go

This PR adds `moveChannel` endpoint to local mode.
https://mattermost.atlassian.net/browse/MM-27376

[MM-27376] api4/channel: add move channel to local mode

---

store/sqlstore/post_store.go

Cherry pick of #15207 on release-5.26.
/cc  @agnivade

Automated cherry pick of #15207

---

app/authorization.go
app/authorization_test.go

Cherry pick of #15215 on release-5.26.

Automated cherry pick of #15215

---

Makefile
config.mk

PR makes sure we start the required docker services before running tests.
https://mattermost.atlassian.net/browse/MM-27485

[MM-27485] Start required docker services before running tests

---

app/app_iface.go
app/login.go
app/opentracing_layer.go
app/session_test.go
model/saml.go
model/session.go
model/session_test.go
web/oauth.go

* Add new session prop for oauth
* Make it isOAuthUser to differentiate better
* Fix up caps
* Fix tests
* Add tests for IsOAuthUser
Manual cherry-pick of #15221 into release-5.25

[MM-27623] Add new session prop for oauth (#15221)

---

app/app_iface.go
app/login.go
app/opentracing/opentracing_layer.go
app/session_test.go
model/saml.go
model/session.go
model/session_test.go
web/oauth.go

* Add new session prop for oauth
* Make it isOAuthUser to differentiate better
* Fix up caps
* Fix tests
* Add tests for IsOAuthUser
- Manual cherry-pick of #15221

[MM-27623] [cherry-pick] Add new session prop for oauth (#15221)

---

app/plugin_requests.go

This helps with debugging what kind of requests are made to a plugin.
None

Log URL for requests to non-existing plugins

---

app/auto_channels.go
app/auto_environment.go
app/auto_posts.go
app/command_loadtest.go

Cherry pick of #15155 on release-5.27.

Automated cherry pick of #15155

---

model/status.go

Cherry pick of #14484 on release-5.27.
/cc  @agnivade

Automated cherry pick of #14484

---

store/sqlstore/user_store.go
store/storetest/user_store.go

Cherry pick of #14587 on release-5.27.
/cc  @justledbetter

Automated cherry pick of #14587

---

api4/system_test.go
app/admin.go

Cherry pick of #15022 on release-5.27.

Automated cherry pick of #15022

---

store/storetest/channel_store.go

This PR attempts to fix a flaky test that is probably caused for searching a too short term that could possibly generated in random names.
https://mattermost.atlassian.net/browse/MM-27700

[MM-27700] storetest/channel_store: fix flaky test for search too short term

---

api4/file.go
app/file.go

Cherry pick of #15143 on release-5.27.

Automated cherry pick of #15143

---

app/plugin.go

Cherry pick of #15140 on release-5.27.

Automated cherry pick of #15140

---

api4/config.go
api4/config_test.go

Cherry pick of #15262 on release-5.27.

Automated cherry pick of #15262

---

web/oauth.go

Cherry pick of #15001 on release-5.27.
/cc  @sbishel

Automated cherry pick of #15001

---

cmd/mattermost/commands/export.go
jobs/jobs.go
jobs/schedulers_test.go
store/opentracing_layer.go
store/sqlstore/job_store.go
store/store.go
store/storetest/job_store.go
store/storetest/mocks/JobStore.go
store/timer_layer.go

* add warning as success result
* revert config changes
* add unit test, update unit test
* add a couple more tests
* update store layers
(cherry picked from commit 0302e0f47770266780c570a45cde4c73acf71aa2)

MM-27449: Compliance Jobs rerun after warning status (#15178)

---

app/login.go

Cherry pick of #15284 on release-5.27.
/cc  @sbishel

Automated cherry pick of #15284

---

model/license.go
utils/license.go

Adds new license feature for cloud. 
Redux: https://github.com/mattermost/mattermost-redux/pull/1218
License Generator: https://github.com/mattermost/license-generator/pull/6
[MM-27930](https://mattermost.atlassian.net/browse/MM-27930)

MM-27930 - Cloud license feature

---

store/sqlstore/upgrade.go

Update DB to 5.27 on master branch

db: upgrade db to 5.27

---

app/session.go
app/web_hub_test.go

Cherry pick of #15293 on release-5.27.
/cc  @agnivade

Automated cherry pick of #15293

---

.circleci/config.yml

https://mattermost.atlassian.net/browse/MM-27948

MM-27948: Use --depth=1 to clone git repos faster

---

store/sqlstore/user_store.go

Tracing this back, it looks like I'm responsible for leaving some spurious logging in the user store.
None.

cleanup error logging from user_store

---

Makefile
go.mod
go.tools.mod
go.tools.sum

This is a workaround for this weblate issue: https://github.com/WeblateOrg/weblate/issues/4076
So this checks for occurrences like this:
```
{
"id": "api.post.delete_post.can_not_delete_post_in_deleted.error",
"translation": ""
},
```

Implement empty translation check.

---

app/enterprise.go

Cherry pick of https://github.com/mattermost/mattermost-server/pull/15371 into 5.25

Cherrypick change 15371 into 5.25

---

app/enterprise.go

Cherrypick https://github.com/mattermost/mattermost-server/pull/15371 into 5.26

Cherrypick change 15371 into 5.26

---

app/enterprise.go

Cherrypick https://github.com/mattermost/mattermost-server/pull/15371 into 5.27

Cherrypick change 15371 into 5.27

---

app/user.go

https://mattermost.atlassian.net/browse/MM-28304

Fix undefined variable error

---

app/diagnostics.go
config/client.go
model/config.go

Feature flag to toggle Cloud Billing. Default off.
https://mattermost.atlassian.net/browse/MM-28313

[MM-28313] Add Cloud Billing feature flag

---

services/filesstore/s3store.go

PR fixes error handling in `S3FileBackend.FileExists()`.
https://mattermost.atlassian.net/browse/MM-28122

[MM-28122] Fix error handling in S3FileBackend.FileExists()

---

services/upgrader/upgrader_linux.go
services/upgrader/upgrader_linux_test.go

Add support for rc versions in upgrader
[MM-26873](https://mattermost.atlassian.net/browse/MM-26873)

Add support for rc versions in upgrader

---

services/upgrader/upgrader_linux.go
services/upgrader/upgrader_linux_test.go

Cherry pick of #15424 on release-5.27.
/cc  @jespino

Automated cherry pick of #15424

---

Makefile
model/config.go
model/config_test.go

Cherry-pick https://github.com/mattermost/mattermost-server/pull/15360 to cloud-beta.
https://mattermost.atlassian.net/browse/MM-28103

MM-28103: prepackage incident-response (#15360)

---

app/post.go

We should break the execution if we get an error here. Dug this from a sentry report.
https://mattermost.atlassian.net/browse/MM-28123

[MM-28123] app/post: continue to loop in case of an error

---

.circleci/config.yml
build/Jenkinsfile.branch

Add the cloud beta pipeline as discussed. Related jenkins pr: https://github.com/mattermost/mattermost-shared-pipelines/pull/83

Add cloud beta pipeline

---

build/Jenkinsfile.branch

Fix jenkins dollar problem. Remove pushing to cloud-beta dockerhub repo.

Fix jenkins dollar

---

build/Jenkinsfile.branch

Fix DCT signing

---

build/Jenkinsfile.branch

I think was missing this, lets try out!

add DOCKER_CONTENT_TRUST env var

---

build/Jenkinsfile.branch

remove DCT for now

---

api4/system.go
api4/system_test.go
model/config.go

Cherry pick of #15528 on cloud-beta.

Automated cherry pick of #15528

---

app/channel.go

This PR solves an error introduced in another PR belonging to the error migration campaign. More details in the linked issue.
Fixes #15501

Fix incorrect error handling

---

Makefile

Update bundled version of nps to 1.1.0
https://mattermost.atlassian.net/browse/MM-28520

[MM-28520] Update bundled version of nps to 1.1.0

---

model/config.go

Set new sidebar to 'always_on' for Cloud Beta
https://mattermost.atlassian.net/browse/MM-28972

[MM-28972] Set new sidebar to 'always_on' for Cloud Beta

---

api4/bleve.go
api4/bleve_test.go

- https://mattermost.atlassian.net/browse/MM-28537

[MM-28537] System role with write experimental should be able to purge indexes

---

store/sqlstore/upgrade.go

Upgrade DB to 5.28
/cc @amyblais

upgrade DB to 5.28

---

i18n/en.json
jobs/jobs.go

Cherry pick of #15564 on release-5.28.
/cc  @sbishel

Automated cherry pick of #15564

---

app/notification_push.go
app/notification_push_test.go
app/server.go

Cherry pick of #15508 on release-5.28.
/cc  @agnivade

Automated cherry pick of #15508

---

Makefile

Deliver Incident Response v0.7 to cloud beta customers.

prepackage incident response v0.7

---

Makefile
app/product_notices.go
app/product_notices_test.go
jobs/product_notices/scheduler.go
model/config.go

notices urls are now config variables
team admin notification fixed
https://mattermost.atlassian.net/browse/MM-28835

MM-28835  Configure/update notices setting for TeamAdmin

---

store/sqlstore/upgrade.go

Cherry pick of #15556 on release-5.28.

upgrade DB to 5.28 (#15556)

---

Makefile
app/product_notices.go
app/product_notices_test.go
jobs/product_notices/scheduler.go
model/config.go

Cherrypick MM-28835  Configure/update notices setting for TeamAdmin

Cherrypick MM-28835  Configure/update notices setting for TeamAdmin (#15632)

---

api4/config.go
model/config.go
model/config_test.go

Cherry pick of #15578 on cloud-beta.

Automated cherry pick of #15578

---

build/Dockerfile

bump the package placeholder to use the latest mm package release
none

bump the package placeholder to use the latest mm package release

---

app/authorization_test.go

added TestHasPermissionToCategory
https://mattermost.atlassian.net/browse/MM-26719

MM-26719  Add unit tests for SessionHasPermissionToCategory

---

model/config.go

Cherry pick of #15725 on cloud-beta.

Automated cherry pick of #15725

---

services/filesstore/filesstore_test.go
services/filesstore/s3store.go

PR addresses an issue introduced in https://github.com/mattermost/mattermost-server/pull/15252 which is causing an excessive allocation for file uploads when using an S3 compatible filestore.
We now limit the allocation by setting the part size for the upload to the minimum allowed value of 5MBs.
```
name           old time/op    new time/op    delta
S3WriteFile-8    34.9ms ± 2%    13.9ms ±38%  -60.24%  (p=0.001 n=7+7)
name           old alloc/op   new alloc/op   delta
S3WriteFile-8     671MB ± 0%       5MB ± 0%  -99.20%  (p=0.000 n=7+8)
name           old allocs/op  new allocs/op  delta
S3WriteFile-8     1.03k ± 1%     1.00k ± 0%   -2.64%  (p=0.000 n=8+8)
```
https://mattermost.atlassian.net/browse/MM-29229

[MM-29229] Set part size for S3 uploads to avoid excessive allocation

---

services/filesstore/filesstore_test.go
services/filesstore/s3store.go

Cherry pick of #15737 on release-5.28.

Automated cherry pick of #15737

---

.circleci/config.yml
app/oauth.go
web/handlers.go

Until we investigate the issues we're encountering with nginx ingress not setting the correct HTTP headers this is a temporary fix for OAuth not working.
https://mattermost.atlassian.net/browse/MM-28720

MM-28720 Temporary fix for oauth on cloud beta

---

store/sqlstore/upgrade.go

Post image schema fix

---

api4/job_test.go
i18n/en.json

Cherry pick of #15718 on release-5.28.
/cc @hahmadia

Cherry pick of #15718

---

services/telemetry/telemetry.go
services/telemetry/telemetry_test.go

Cherry pick of #15572 on release-5.28.
/cc  @jespino

Automated cherry pick of #15572

---

app/plugin.go
model/marketplace_plugin.go

Cherry pick of #15436 on cloud-beta.

Automated cherry pick of #15436

---

api4/cloud.go
einterfaces/cloud.go
model/client4.go
model/cloud.go

[MM-28217] Server API to serve up cloud customer information (#15656) - cherry-pick

---

app/product_notices.go
app/product_notices_test.go

Cherry pick of #15756 on release-5.28.
/cc  @reflog

Automated cherry pick of #15756

---

app/app_iface.go
app/opentracing/opentracing_layer.go
app/product_notices.go
app/user.go

Added clearing of notices for new users
https://mattermost.atlassian.net/browse/MM-29400

MM-29400  Mark all current notices as viewed for newly created users

---

app/app_iface.go
app/opentracing/opentracing_layer.go
app/product_notices.go
app/user.go

Cherry pick of #15840 on release-5.28.
/cc  @reflog

Automated cherry pick of #15840

---

services/telemetry/telemetry.go

Add missing config telemetry for 5.28 release.
https://mattermost.atlassian.net/browse/MM-28540

MM-28540: Add missing config telemetry for 5.28 release.

---

api4/apitestlib.go
api4/config_test.go
app/helper_test.go
cmd/mattermost/commands/cmdtestlib.go
model/config.go
services/mailservice/mail_test.go

Cherry pick of #15540 on cloud-ga.

Automated cherry pick of #15540

---

model/cloud.go

Cherry pick of #15857 on cloud-ga.

Automated cherry pick of #15857

---

app/plugin.go

Cherry pick of #15910 on cloud-ga.

Automated cherry pick of #15910

---

config/client.go

Added CWSUrl to the client config to create the url for Cloud contact us.
- Webapp: https://github.com/mattermost/customer-web-server/pull/245
- Redux: https://github.com/mattermost/mattermost-redux/pull/1255
Needed for [MM-27454 - Cloud Contact Us](https://mattermost.atlassian.net/browse/MM-27454)

MM-27454 - Added CWSUrl to Client Config

---

config/client.go

Cherry pick of #15916 on cloud-ga.

Automated cherry pick of #15916

---

app/product_notices.go

fixed cloud check in product notices
https://mattermost.atlassian.net/browse/MM-29560

MM-29560  Correct Cloud detection in InProduct Notices

---

app/product_notices.go

Cherry pick of #15938 on release-5.28.
/cc  @reflog

Automated cherry pick of #15938

---

.circleci/config.yml

Fixes https://github.com/mattermost/mattermost-server/issues/15901

Update golangci-lint to v1.31.0

---

store/sqlstore/upgrade.go

Cherry pick to fix the migration problem introduced by https://github.com/mattermost/mattermost-server/pull/15376

Post image schema fix (#15763)

---

api4/team.go
api4/team_test.go

Cherry pick of #15958 on cloud-ga.
```release-note
NONE
```

Automated cherry pick of #15958

---

model/product_notices.go

quick fix for on-prem/cloud notice validation

on prem/cloud validation fixed

---

model/product_notices.go

Cherry pick of #15972 on release-5.28.
/cc  @reflog

Automated cherry pick of #15972

---

model/websocket_message.go

This PR adds the constant to dispatch a websocket event for updating the payment status for cloud.
https://mattermost.atlassian.net/browse/MM-29723

[MM-29723] Added websocket event constant for updating the payment status for cloud

---

Makefile
build/release.mk
scripts/download_mmctl_release.sh

Updates to support mmctl being published to S3
Paths will need to be updated

Update to get latest release from S3

---

model/websocket_message.go

Cherry pick of #15988 on cloud-ga.

Automated cherry pick of #15988

---

api4/user.go
model/websocket_message.go

Cherry pick of #15990 on cloud-ga.

Automated cherry pick of #15990

---

app/oauth.go
app/user.go
einterfaces/oauthproviders.go
model/gitlab/gitlab.go
web/oauth_test.go

Cherry pick of #15426 on release-5.29.
```release-note
NONE
```

Automated cherry pick of #15426

---

api4/cloud.go
einterfaces/cloud.go
model/client4.go
model/cloud.go

Cherry pick of #15974 on cloud-ga.

Automated cherry pick of #15974

---

store/storetest/user_store.go

Cherry pick of #15543 on release-5.29.
```release-note
NONE
```

Automated cherry pick of #15543

---

Makefile

Prepackaging incident response 1.0.
```release-note
Pre-package Incident Response v1.0.0
```
https://mattermost.atlassian.net/browse/MM-29747

MM-29747 Prepackage incidnet response 1.0 for cloud ga

---

build/release.mk
model/config.go

DOPS-243: Add manifest.txt

---

app/app_iface.go
app/auto_responder.go
app/auto_responder_test.go
app/opentracing/opentracing_layer.go
app/post.go

Cherry pick of #15625 on release-5.29.
/cc  @larkox

Automated cherry pick of #15625

---

model/cloud.go

Cherry pick of #16058 on cloud-ga.

Automated cherry pick of #16058

---

store/sqlstore/supplier_test.go

This test is too flaky to be written as a test. Let's just remove it.
https://mattermost.atlassian.net/browse/MM-29950
```release-note
NONE
```

MM-22950: Remove supplier test

---

model/version.go
store/sqlstore/upgrade.go

upgrade DB to 5.29 tin release 5.29 branch
None
/cc @amyblais 
```release-note
NONE
```

upgrade DB to 5.29

---

api4/cloud.go
einterfaces/cloud.go
model/client4.go
model/cloud.go
web/context.go
web/params.go

Cherry pick of #16056 on cloud-ga.

Automated cherry pick of #16056

---

api4/user.go
app/app_iface.go
app/cloud.go
app/email.go
app/opentracing/opentracing_layer.go
i18n/en.json
templates/reached_user_limit_body.html

Cherry pick of #16053 on cloud-ga.

Automated cherry pick of #16053

---

api4/plugin_test.go
app/plugin.go
model/marketplace_plugin.go

Cherry pick of #15913 on cloud-ga.
/cc  @hanzei

Automated cherry pick of #15913

---

api4/user_test.go
model/user.go

Cherry pick of #16031 on cloud-ga.

Automated cherry pick of #16031

---

Makefile
build/release.mk
scripts/download_mmctl_release.sh

Cherry pick of #15952 on cloud-ga.
/cc  @jaydeland

Automated cherry pick of #15952

---

scripts/download_mmctl_release.sh

Cherry pick of #15993 on cloud-ga.
/cc  @jaydeland

Automated cherry pick of #15993

---

build/release.mk

Cherry pick of #15959 on cloud-ga.
/cc  @metanerd

Automated cherry pick of #15959

---

build/release.mk
scripts/download_mmctl_release.sh

Cherry pick of #16105 on cloud-ga.

Automated cherry pick of #16105

---

app/web_conn.go

Reverts mattermost/mattermost-server#16098
Caused websocket issues: https://community-daily.mattermost.com/core/pl/dq1frrosobr58jjpbiwoxqt4de

Revert "MM-29979: make websocket writes zero-alloc"

---

model/cloud.go

Cherry pick of #16111 on cloud-ga.
```release-note
NONE
```

Automated cherry pick of #16111

---

build/Dockerfile

Cherry pick of #16118 on release-5.29.
/cc  @amyblais

Automated cherry pick of #16118

---

services/filesstore/s3_overrides.go
services/filesstore/s3store.go

Cherry pick of #15955 on cloud-ga.
/cc  @agnivade

Automated cherry pick of #15955

---

model/websocket_client.go

occuring -> occurring
```release-note
NONE
```

Fix typo in comment

---

api4/cloud.go
einterfaces/cloud.go

Cherry pick of #16203 on cloud-ga.

Automated cherry pick of #16203

---

app/web_conn.go
model/websocket_message.go

This reverts commit 31dac80e66c31a123e56b116e8173f64d1a88d2d.

MM-29979: make websocket writes zero-alloc

---

web/web_test.go

https://mattermost.atlassian.net/browse/MM-30217
```release-note
NONE
```

flaky test fix related to product notices

---

config/client.go
model/config.go

Cherry pick of #16213 on release-5.29.
/cc  @hmhealey
```release-note
NONE
```

MM-30090 Add ManagedResourcePaths setting (#16213)

---

services/telemetry/telemetry.go

Missed this with the initial PR.
https://mattermost.atlassian.net/browse/MM-30090
```release-note
NONE
```

MM-30090 Add telemetry for ManagedResourcePaths

---

services/telemetry/telemetry.go

Cherry pick of #16221 on release-5.29.
/cc  @hmhealey

Automated cherry pick of #16221

---

api4/user.go

Cherry pick of #16230 on cloud-ga.

Automated cherry pick of #16230

---

web/static.go
web/web.go
web/web_test.go

Fixes misspelling of compatibility on `web.CheckClientCompatibility`.
No ticket associated with this.
```release-note
NONE
```

Fixed misspelled compatibility

---

app/server_test.go

Reorganize `TestSentry` to be more robust. Added `*cfg.LogSettings.EnableDiagnostics = true` to make sure every setting is set to enable sentry. Also, added a check if the `SENTRY_DSN` is set up properly.
https://mattermost.atlassian.net/browse/MM-30395
```release-note
NONE
```

[MM-30395] app/server_test: make sure sentry is ready to be setup

---

build/release.mk

Cherry pick of #16277 on cloud.

Automated cherry pick of #16277

---

.gitlab-ci.yml
.gitlab-ci/test-schema.yml
.gitlab-ci/test.yml

https://mattermost.atlassian.net/browse/DOPS-243
```release-note
```

DOPS-243: Fix images

---

model/session.go

```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-30704

MM-30704: Change to idiomatic receiver names for model.Session

---

model/config.go

Cherry pick of #16309 on cloud.
```release-note
NONE
```

Automated cherry pick of #16309

---

Makefile
model/config.go
model/config_test.go
services/telemetry/telemetry.go

Cherry-pick https://github.com/mattermost/mattermost-server/pull/16323 to cloud.
https://mattermost.atlassian.net/browse/MM-30800
```release-note
NONE
```

Cherry-pick MM-30800 (prepackage incident management 1.1)

---

store/layer_generators/main.go
store/layer_generators/retry_layer.go.tmpl

Removing AppError check from the retry layer. This is part of the clean up of
the AppError usage on the store layers.

Removing AppError check from the retry layer

---

app/post_metadata.go
app/post_metadata_test.go

Cherry pick of #16326 on cloud.
/cc  @hmhealey

Automated cherry pick of #16326

---

app/post_metadata.go
services/httpservice/client.go
services/httpservice/httpservice.go

Cherry pick of #16210 on cloud.
/cc  @hanzei

Automated cherry pick of #16210

---

app/slashcommands/command_offline.go

JIRA - https://mattermost.atlassian.net/browse/MM-30817
Issue - Fixes #16329
```release-note
NONE
```

MM-30817: Change to idiomatic receiver names for slashcommands.OfflineProvider

---

.gitlab-ci.yml

Add build and publish stages

---

app/helper_test.go

JIRA - https://mattermost.atlassian.net/browse/MM-30825
Issue - Fixes #16337
```release-note
NONE
```

MM-30825: Change to idiomatic receiver names for app.TestHelper

---

model/security_bulletin.go

JIRA - https://mattermost.atlassian.net/browse/MM-30824
Issue - Fixes #16336
```release-note
NONE
```

MM-30824: Change to idiomatic receiver names for model.SecurityBulletin

---

api4/config.go

Cherry pick of #16365 on cloud.
```release-note
NONE
```

Automated cherry pick of #16365

---

api4/websocket_norace_test.go
api4/websocket_test.go

We just skip the test for now
https://mattermost.atlassian.net/browse/MM-30706
```release-note
NONE
```

MM-30706: Skip racy test TestWebSocket

---

web/saml.go

https://mattermost.atlassian.net/browse/MM-30861
```release-note
NONE
```

MM-30861: Fix racy test TestSaml2Login

---

app/enterprise.go
app/enterprise_test.go

Cherry pick of #16361 on release-5.29.
/cc  @sbishel
```release-note
Enable goSAML2 library as the only supported SAML Library.
```

Automated cherry pick of #16361

---

store/sqlstore/post_store.go

fix reply count calculation (avoid deleted posts)
https://mattermost.atlassian.net/browse/MM-30917
```release-note
NONE
```

MM-30917 Fix invalid reply count calculation during thread migration

---

i18n/en.json

Adding some missing translation strings

---

services/cache/lru.go
services/cache/lru_test.go

After shortening the critical section, we missed out the fact
that the byte slice is still accessible after the element is returned.
So the lock needs to be active until the byte slice is fully read and
unmarshaled
https://mattermost.atlassian.net/browse/MM-30863
```release-note
NONE
```

MM-30863: Fix race in LRU

---

app/slashcommands/command_dnd.go

Updated receiver name for (me *DndProvider) to be more idiomatic.
Fixes : #16367 
JIRA: https://mattermost.atlassian.net/browse/MM-30908
```release-note
NONE
```

[MM-30908]: Change receiver name for (me *DndProvider) in app/slashcommands/command_dnd.go to be more idiomatic.

---

app/slashcommands/command_remove.go

Updated receiver name for (me *KickProvider) and (me *RemoveProvider)in app/slashcommands/command_remove.go to be more idiomatic.
Fixes: #16368 
JIRA: https://mattermost.atlassian.net/browse/MM-30909
```release-note
NONE
```

[MM-30909]: Change receiver name for (me *KickProvider) and (me *RemoveProvider)in app/slashcommands/command_remove.go to be more idiomatic.

---

model/initial_load.go

Updated receiver name for (me *InitialLoad)  to be more idiomatic.
Fixes: #16369 
JIRA: https://mattermost.atlassian.net/browse/MM-30910
```release-note
NONE
```

[MM-30910]: Change receiver name for (me *InitialLoad) in model/initial_load.go to be more idiomatic

---

app/slashcommands/command_channel_rename.go

Updated receiver name for (me *RenameProvider) to be more idiomatic.
Fixes: #16371 
JIRA: https://mattermost.atlassian.net/browse/MM-30912
```release-note
NONE
```

[MM-30912]: Change receiver name for (me *RenameProvider) in app/slashcommands/command_channel_rename.go to be more idiomatic.

---

store/sqlstore/post_store.go
store/storetest/thread_store.go

don't remove the user from participants on post delete
https://mattermost.atlassian.net/browse/MM-30865
```release-note
NONE
```

MM-30865 Invalid Participants handling on post delete in thread

---

api4/user_test.go
app/channel.go
app/notification.go
app/post.go
app/user.go
model/thread.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/sqlstore/thread_store.go
store/store.go
store/storetest/mocks/ThreadStore.go
store/storetest/thread_store.go
store/timerlayer/timerlayer.go

added unreadmentions column to memberships
https://mattermost.atlassian.net/browse/MM-30970
```release-note
Added UnreadMentions column to ThreadMembership table
```

MM-30970 Add Basic unreadMentions support for collapsed threads

---

i18n/en.json

Add miss translations 29

---

i18n/en.json

Add miss translations 28

---

.gitlab-ci.yml

Add GitLab.

---

app/slashcommands/command_join.go

Updated receiver name for (me *JoinProvider) to be more idiomatic. 
Fixes: #16374  
JIRA: https://mattermost.atlassian.net/browse/MM-30915
```release-note
NONE
```

[MM-30915]: Change receiver name for (me *JoinProvider) in app/slashcommands/command_join.go to be more idiomatic.

---

store/sqlstore/post_store.go
store/storetest/thread_store.go

Cherry pick of #16353 on release-5.29.
/cc  @reflog

Automated cherry pick of #16353

---

app/channel.go
app/notification.go
app/post.go
einterfaces/mocks/LdapInterface.go
model/thread.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/sqlstore/thread_store.go
store/store.go
store/storetest/mocks/ThreadStore.go
store/storetest/thread_store.go
store/timerlayer/timerlayer.go

```release-note
'UnreadMentions' column added to ThreadMemberships table
```

Cherrypick MM-30970 into 5.29

---

store/sqlstore/post_store.go

Cherry pick of #16395 on release-5.29.
/cc  @reflog

Automated cherry pick of #16395

---

build/release.mk
scripts/download_mmctl_release.sh

Fix mmctl and add manifest for 5.28

---

Makefile
model/system.go

See https://github.com/mattermost/enterprise/pull/858 for description of this PR
https://mattermost.atlassian.net/browse/MM-30973
```release-note
None
```

[MM-30973] Delinquent Account Emails: Possibility for duplicate emails to be sent

---

api4/cloud.go
app/app_iface.go
app/cloud.go
app/email.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/cloud.go
templates/payment_failed_no_card_body.html

Cherry pick of #16442 on cloud.

Automated cherry pick of #16442

---

app/import_functions.go
app/import_functions_test.go

Cherry pick of #16455 on cloud.

Automated cherry pick of #16455

---

i18n/en.json

Adds missing translation strings.
https://mattermost.atlassian.net/browse/MM-30880
https://mattermost.atlassian.net/browse/MM-30881
https://mattermost.atlassian.net/browse/MM-29985
https://mattermost.atlassian.net/browse/MM-29991
```release-note
NONE
```

add missing translation strings

---

store/sqlstore/upgrade.go
store/sqlstore/upgrade_test.go

db: upgrade db to 5.30
/cc @amyblais 
NONE
```release-note
db: upgrade db to 5.30
```

db: upgrade db to 5.30

---

build/Dockerfile

Cherry pick of #16488 on release-5.30.
/cc  @amyblais

Automated cherry pick of #16488

---

Makefile
model/config.go
model/config_test.go
services/telemetry/telemetry.go

Cherry pick of #16406 on release-5.30.

Automated cherry pick of #16406

---

api4/user_test.go
app/channel.go
app/notification.go
app/post.go
app/user.go
model/thread.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/sqlstore/thread_store.go
store/store.go
store/storetest/mocks/SqlStore.go
store/storetest/mocks/ThreadStore.go
store/storetest/thread_store.go
store/timerlayer/timerlayer.go

```release-note
Added UnreadMentions to ThreadMemberships table
```

cherry-pick-MM-30970-release-5.30

---

app/product_notices.go
app/product_notices_test.go

MM-30918 Fix product notice check when user setting is missing (#16396)

---

app/server.go
store/localcachelayer/layer.go

https://mattermost.atlassian.net/browse/MM-31236
```release-note
NONE
```

MM-31326: Fix Striped LRU to have minimum of 1 bucket

---

.circleci/config.yml

Enable circleci test only for master

---

einterfaces/mocks/OauthProvider.go

Update einterface mocks not updated in this PR -
https://github.com/mattermost/enterprise/pull/819
https://mattermost.atlassian.net/browse/MM-31366
```release-note
NONE
```

MM-31366 -update einterface mocks

---

.circleci/config.yml

implemented validating mocks during ci
https://mattermost.atlassian.net/browse/MM-31154
```release-note
NONE
```

MM-31154 Add CI step to validate store mocks

---

store/searchlayer/user_layer.go

Cherry pick of #16550 on cloud.

Automated cherry pick of #16550

---

go.mod
go.sum
vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
vendor/modules.txt

Cherry pick of #16528 on cloud.
/cc  @hmhealey

Automated cherry pick of #16528

---

app/server.go
config/client.go
model/config.go
services/telemetry/telemetry.go

https://mattermost.atlassian.net/browse/MM-30836
```release-note
NONE
```

MM-30836: Feature flag for remote cluster service

---

Makefile

Pre-package incident management v1.2.0.
Fixes: https://mattermost.atlassian.net/browse/MM-30450
```release-note
Pre-package Incident Management v1.2.0.
```

MM-30450: Pre-pacakge Incident Management v1.2.0

---

api4/channel.go
api4/config_test.go
api4/user.go
app/channel.go
app/command.go
app/login.go
app/notification.go
app/notification_email.go
app/oauth.go
app/team.go
app/user.go
app/webhook.go
model/command_webhook.go
model/config.go
model/file_info.go
model/outgoing_webhook.go
model/scheme.go
model/search_params.go
store/localcachelayer/role_layer.go
store/localcachelayer/scheme_layer.go
store/sqlstore/audit_store.go
store/sqlstore/group_store.go
store/sqlstore/user_store.go
web/handlers.go
web/saml.go

https://mattermost.atlassian.net/browse/MM-31062
```release-note
NONE
```

MM-31062: Rewrite empty string checks to be more idiomatic

---

web/handlers.go

Downgrade `4xx` and `501` errors to info/debug level.
https://mattermost.atlassian.net/browse/MM-31512
```release-note
NONE
```

[MM-31512] Downgrade 4xx and 501 errors to info/debug level

---

api4/job.go
api4/websocket.go
app/app.go
app/auto_responder.go
app/bot.go
app/channel.go
app/command.go
app/ldap.go
app/login.go
app/notification.go
app/oauth.go
app/upload.go
app/user.go
model/session.go
services/awsmeter/awsmeter.go
services/mailservice/mail.go
store/searchlayer/post_layer.go
utils/html.go
wsapi/status.go

I removed many error lines were already getting logged somewhere else.
https://mattermost.atlassian.net/browse/MM-31359
```release-note
NONE
```

[MM-31359] remove duplicated error logs

---

api4/image.go
api4/image_test.go

Cherry pick of #16189 on release-5.31.

Automated cherry pick of #16189

---

store/searchlayer/channel_layer.go
store/searchlayer/post_layer.go
store/searchlayer/user_layer.go
store/sqlstore/integrity.go
store/sqlstore/post_store.go

Downgraded some error level logs to warning level which does not break the function/method flow. Kept error logs for upgrade function.
https://mattermost.atlassian.net/browse/MM-31572
```release-note
NONE
```

[MM-31572] downgrade some error logs for store package

---

web/context.go

Cherry pick of #16648 on cloud.

Automated cherry pick of #16648

---

api4/remote_cluster.go
app/server.go
einterfaces/metrics.go
einterfaces/mocks/MetricsInterface.go
i18n/en.json
model/remote_cluster.go
services/remotecluster/invitation.go
services/remotecluster/mocks_test.go
services/remotecluster/ping.go
services/remotecluster/recv.go
services/remotecluster/send.go
services/remotecluster/service.go

PR implements some Prometheus metrics for the remote cluster service.
https://mattermost.atlassian.net/browse/MM-31289
```release-note
none
```
https://github.com/mattermost/enterprise/pull/885

[MM-31289] Add some metrics for remote cluster service

---

web/handlers.go

This was overwritten by the merge from master. This should be the last release this change is needed for.
```release-note
None
```

Temporary fix for OAuth on cloud

---

.circleci/config.yml

Disable known issue with Api spec on cloud

---

app/plugin.go

For on-prem, we don't need downgrade control. 
https://mattermost.atlassian.net/browse/MM-31699
```release-note
NONE
```

MM-31699 Don't downgrade plugins with feature flag for on-prem

---

i18n/en.json

Fix a typo reported by a community translator.

Update en.json to fix a typo

---

store/sqlstore/upgrade.go

Fixes missing column in ThreadMemberships table
```release-note
NONE
```

hotfix-threads-migrate

---

store/sqlstore/upgrade.go

hotfix-cherrypick-release-5.31

---

store/sqlstore/upgrade.go

hotfix-cherrypick-cloud-upgrade

---

.golangci.yml

https://mattermost.atlassian.net/browse/MM-31992
```release-note
NONE
```

MM-31992: Remove some unnecessary words from the unused linter

---

store/sqlstore/upgrade.go

migration hotfix

---

scripts/download_mmctl_release.sh

Hardcode mmctl version

---

store/sqlstore/upgrade.go

Release 5.29 hotfix upgrade

---

.github/PULL_REQUEST_TEMPLATE.md

Includes more detailed release note instructions.
n/a
```release-note
NONE
```

Expands release note instructions.

---

build/Dockerfile.buildenv

Bump up Go docker image to 1.15.5

---

store/sqlstore/upgrade.go

upgrade fix

---

.golangci.yml

This will be implemented via a mattermod check
to make PR review suggestions.
```release-note
NONE
```

Remove local imports from golangci

---

api4/license.go
app/email.go
app/license.go
app/server.go
i18n/en.json
i18n/es.json
i18n/uk.json

This PR updates some of the content in the license renewal email. We update the wording of the button and also change the link to point to the CWS form.
Fixes [https://mattermost.atlassian.net/browse/MM-31112?atlOrigin=eyJpIjoiNWY0OThmZTJlMjYwNGFlNzk2ODNlMWNkZGJhZmI5ZGYiLCJwIjoiaiJ9](https://mattermost.atlassian.net/browse/MM-31112?atlOrigin=eyJpIjoiNWY0OThmZTJlMjYwNGFlNzk2ODNlMWNkZGJhZmI5ZGYiLCJwIjoiaiJ9)
```release-note
NONE
```

[MM-31112] - Update license renewal email

---

api4/license.go
app/email.go
app/license.go
app/server.go
i18n/en.json
i18n/es.json
i18n/uk.json

This PR updates some of the content in the license renewal email. We update the wording of the button and also change the link to point to the CWS form.
Fixes [https://mattermost.atlassian.net/browse/MM-31112?atlOrigin=eyJpIjoiNWY0OThmZTJlMjYwNGFlNzk2ODNlMWNkZGJhZmI5ZGYiLCJwIjoiaiJ9](https://mattermost.atlassian.net/browse/MM-31112?atlOrigin=eyJpIjoiNWY0OThmZTJlMjYwNGFlNzk2ODNlMWNkZGJhZmI5ZGYiLCJwIjoiaiJ9)
```release-note
NONE
```

cherry-pick#31112: Update license renewal email

---

api4/api.go
api4/export.go
api4/export_local.go
api4/export_test.go
app/app.go
app/app_iface.go
app/enterprise.go
app/export.go
app/opentracing/opentracing_layer.go
i18n/en.json
imports/placeholder.go
jobs/export_process/worker.go
jobs/import_process/worker.go
jobs/interfaces/export_process_interface.go
jobs/jobs_watcher.go
jobs/server.go
jobs/workers.go
model/client4.go
model/config.go
model/config_test.go
model/job.go
web/params.go

PR implements a job to generate export files.
https://mattermost.atlassian.net/browse/MM-31597
https://mattermost.atlassian.net/browse/MM-31248
```release-note
NONE
```

[MM-31597] Implement export process job

---

Makefile
web/saml.go

Adds the check for https://github.com/mattermost/mattermost-server/issues/16674
in the Makefile
```release-note
NONE
```

Enable govet check for empty strings

---

app/product_notices.go
app/product_notices_test.go

Cherry pick of #16782 on cloud.
/cc  @reflog

Automated cherry pick of #16782

---

store/storetest/channel_store.go

Use a 5 letter stop word to prevent a flaky test.
https://mattermost.atlassian.net/browse/MM-27700
```release-note
NONE
```

storetest/channel_store: update a stop word

---

Makefile

Cherry pick of #16302 on release-5.32.
/cc  @hanzei

Automated cherry pick of #16302

---

app/notification.go
app/post.go

Cherry pick of #16794 on release-5.32.
/cc  @larkox

Automated cherry pick of #16794

---

store/sqlstore/post_store.go

Cherry pick of #16797 on release-5.32.
/cc  @larkox

Automated cherry pick of #16797

---

app/file.go
app/file_test.go
app/helper_test.go
services/slackimport/slackimport.go

Cleanup - remove unused code
```release-note
NONE
```

[NO-TICKET] Cleanup - remove unused code

---

config/common_test.go
config/database_test.go
config/file_test.go
config/store.go

Cherry pick of #16836 on cloud.

Automated cherry pick of #16836

---

app/file.go
services/slackimport/slackimport.go
utils/i18n.go
web/handlers.go

Remove unused function attributes
```release-note
NONE
```

[NO-TICKET] Remove unused function attributes

---

services/awsmeter/awsmeter_test.go
services/cache/lru_test.go
services/cache/provider_test.go
services/docextractor/docextractor_test.go
services/filesstore/filesstore_test.go
services/filesstore/s3store_test.go
services/httpservice/client_test.go
services/imageproxy/atmos_camo_test.go
services/imageproxy/local_test.go
services/mailservice/mail_test.go
services/searchengine/bleveengine/bleve_test.go
services/upgrader/upgrader_linux_test.go

Changed require.Nil to require.NoError when error type is used
Not yet
```release-note
NONE
```

Changed require.Nil to require.NoError when error type is used

---

app/user.go

Remove unnecessary concurrent DB calls, and replace them with JIT fetches instead. For scenarios that the OAuth user is present, we do not need to fetch the user by email at all, so instead of always fetching both, we use a JIT retrieval.
N/A
```release-note
* Use JIT db fetches on User. CreateOAuthUser
```

Cleanup unnecessary concurrent db calls on user

---

api4/post_test.go
store/searchtest/post_layer.go
store/sqlstore/post_store.go

Reverts mattermost/mattermost-server#16618
Failed during release testing.
```release-note
NONE
```

Revert "MM-24530-Add support for search terms with underscore using postgresql engine"

---

api4/post_test.go
store/searchtest/post_layer.go
store/sqlstore/post_store.go

Cherry pick of #16950 on release-5.32.
/cc  @agnivade

Automated cherry pick of #16950

---

build/docker-compose.common.yml

Updates the release version of the `osixia/openldap` Docker image.
n/a
```release-note
NONE
```

Updates the release version of the osixia/openldap Docker image.

---

api4/status.go
app/app_iface.go
app/command.go
app/opentracing/opentracing_layer.go
app/slashcommands/command_custom_status.go
app/status.go
config/client.go
i18n/en.json
model/config.go
model/custom_status.go
model/emoji.go
model/feature_flags.go
model/preference.go
model/user.go
services/telemetry/telemetry.go

- Create a system console setting for custom status feature enabled.
- Create server APIs for custom status.
- Create slash commands to set/unset status.
- Add logic to set/unset status.
- ~~Note - Call to `a.sendUpdatedUserEvent(*user)` can be removed after https://github.com/mattermost/mattermost-server/pull/16604 is merged.~~
* Config changes - additions
* API additions—new endpoints
* Websocket additions or changes
```release-note
Added new API endpoints PUT /api/v4/users/<id>/status/custom, DELETE /api/v4/users/<id>/status/custom, and DELETE  /api/v4/users/<id>/status/custom/recent.
```
```release-note
Added a new config setting TeamSettings.EnableCustomUserStatuses.
```

Custom status feature

---

app/authentication.go
app/user.go
i18n/en.json
model/utils.go
model/utils_test.go
services/mfa/mfa.go
services/mfa/mfa_test.go

Isolate more the mfa service
[MM-33010](https://mattermost.atlassian.net/browse/MM-33010)
```release-note
NONE
```

Isolate more the mfa service

---

api4/status.go
app/app_iface.go
app/command.go
app/opentracing/opentracing_layer.go
app/slashcommands/command_custom_status.go
app/status.go
config/client.go
i18n/en.json
model/config.go
model/custom_status.go
model/emoji.go
model/feature_flags.go
model/preference.go
model/user.go
services/telemetry/telemetry.go

Cherry pick of #16835 on cloud.
/cc  @chetanyakan

Automated cherry pick of #16835

---

api4/websocket.go

Was debugging [MM-33009](https://mattermost.atlassian.net/browse/MM-33009) and this missing piece resulted to be quite helpful.
```release-note
NONE
```

Improve error during WebSocket upgrade

---

model/config.go
store/sqlstore/store.go
store/sqlstore/store_test.go

Remove any references to Sqlite3 as per https://community.mattermost.com/core/pl/e9e7gf8by3835frh9zacifqqhe
N/A
```release-note
* Remove any references to SqlLite3
```

Remote any references to sqlite

---

services/mailservice/mail_test.go

Fix mailservice tests race condition
[MM-33159](https://mattermost.atlassian.net/browse/MM-33159)
```release-note
NONE
```

Fix mailservice tests race condition

---

app/integration_action.go
app/integration_action_test.go
app/plugin_hooks_test.go
app/post.go
services/sharedchannel/sync_recv.go
services/sharedchannel/sync_send.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/searchlayer/file_info_layer.go
store/sqlstore/post_store.go
store/store.go
store/storetest/mocks/PostStore.go
store/storetest/post_store.go
store/storetest/thread_store.go
store/timerlayer/timerlayer.go

This PR combines PostStore.GetSingleInclDeleted with GetSingle as per https://github.com/mattermost/mattermost-server/pull/16962#discussion_r578996612
**To be merged with feature branch**
Will be QA'd when feature branch is merged with master.
https://mattermost.atlassian.net/browse/MM-33221
```release-note
NONE
```

MM-33221 Merge GetSingleInclDeleted into GetSingle for PostStore

---

i18n/en.json

Add missed translation for file indexing
```release-note
NONE
```

Add missed translation for file indexing

---

Makefile
db/migrations/bindata.go
db/migrations/mysql/000011_create_link_metadata.down.sql
db/migrations/mysql/000011_create_link_metadata.up.sql
db/migrations/postgres/000011_create_link_metadata.down.sql
db/migrations/postgres/000011_create_link_metadata.up.sql
store/sqlstore/link_metadata_store.go
store/sqlstore/store.go

https://mattermost.atlassian.net/browse/MM-33075
```release-note
* Moves LinkMetadata gorp driven migrations to schema-based migrations
```

[MM-33075] Add migrations for link metadata

---

config/migrate_test.go

Add cleanup to the migrate test.
https://mattermost.atlassian.net/browse/MM-32479
```release-note
NONE
```

[MM-32479] config/migrate_test: add cleanup

---

api4/post.go
app/app_iface.go
app/opentracing/opentracing_layer.go
app/post.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/post_store.go
store/store.go
store/storetest/mocks/PostStore.go
store/storetest/post_store.go
store/timerlayer/timerlayer.go

Some API calls around post paging didn't handle the collapsedThreads=true properly (next/prev posts were not calculated)
https://mattermost.atlassian.net/browse/MM-32785
```release-note
NONE
```

MM-30304 - Handle collapsed threads in page apis

---

app/server.go
migrations/helper_test.go

Disable notices for migrations test helper.
https://mattermost.atlassian.net/browse/MM-32626
```release-note
NONE
```

[MM-32626] Disable notices for migrations test helper

---

api4/status.go
app/command.go
app/slashcommands/command_custom_status.go
config/client.go
model/feature_flags.go

Remove Custom statuses feature flag
[MM-33166](https://mattermost.atlassian.net/browse/MM-33166)
```release-note
Add user custom statuses
```

Remove Custom statuses feature flag

---

app/emoji.go

Getting the emoji by id using the cache
[MM-33576](https://mattermost.atlassian.net/browse/MM-33576)
```release-note
NONE
```

Getting the emoji by id using the cache

---

model/feature_flags.go

Enable custom statuses feature flag by default
```release-note
NONE
```

Enable custom statuses feature flag by default

---

app/user.go

Clarify a log line.
https://mattermost.atlassian.net/browse/MM-30270
```release-note
NONE
```
`

[MM-30270] app/user: clarify log message

---

go.tools.mod
go.tools.sum
i18n/en.json

Fix translations of emails
[MM-33595](https://mattermost.atlassian.net/browse/MM-33595)
```release-note
NONE
```

Fix translations of emails

---

app/email_test.go
app/helper_test.go
templates/invite_body.html

Cherry pick of #17065 on cloud.
/cc  @jespino

Automated cherry pick of #17065

---

store/sqlstore/upgrade.go

https://mattermost.atlassian.net/browse/MM-33655
```release-note
Add database upgrade step for schema version 5.29.1
```

[MM-33655] Add db upgrade step 5.29.1

---

store/sqlstore/upgrade.go

https://mattermost.atlassian.net/browse/MM-33655
```release-note
Adds database upgrade step for schema version 5.29.1
```

[MM-33655] Add db upgrade step for 5.29.1

---

store/sqlstore/upgrade.go

https://mattermost.atlassian.net/browse/MM-33655
```release-note
Add database upgrade step for schema version 5.29.1
```

[MM-33655] Add database upgrade step for 5.29.1

---

app/email.go
i18n/en.json
templates/invite_body.html
templates/invite_body.mjml
templates/partials/card.mjml
templates/partials/style.mjml
templates/reset_body.html
templates/reset_body.mjml
templates/verify_body.html
templates/welcome_body.html

Cherry pick of #17029 on cloud.
/cc  @jp0707

Automated cherry pick of #17029

---

i18n/bg.json
i18n/de.json
i18n/es.json
i18n/fr.json
i18n/it.json
i18n/ja.json
i18n/ko.json
i18n/nl.json
i18n/pl.json
i18n/pt-BR.json
i18n/ro.json
i18n/ru.json
i18n/sv.json
i18n/tr.json
i18n/uk.json
i18n/zh-CN.json
i18n/zh-TW.json

Cherry pick of #17133 on cloud-2021-03-15.
/cc  @weblate

Automated cherry pick of #17133

---

store/localcachelayer/layer.go
store/localcachelayer/user_layer.go

Cherry pick of #17119 on cloud.
/cc  @agnivade

Automated cherry pick of #17119

---

api4/user_local.go
api4/user_test.go

Add promote/demote user to local router
https://mattermost.atlassian.net/browse/MM-32943
```release-note
NONE
```

[MM-32943] api4/user: add promote/demote user to local router

---

api4/websocket.go

Cherry pick of #17142 on cloud.
/cc  @agnivade

Automated cherry pick of #17142

---

model/file_info.go
store/sqlstore/file_info_store.go
store/sqlstore/store.go

Improve file search results with postgres
[MM-28019](https://mattermost.atlassian.net/browse/MM-28019)
```release-note
NONE
```

Improve file search results with postgres

---

store/storetest/post_store.go

Making the posts tests a bit more robust
No ticket
```release-note
NONE
```

Making the posts tests a bit more robust

---

api4/websocket.go
app/web_conn.go

Cherry pick of #17172 on cloud.
/cc  @agnivade

Automated cherry pick of #17172

---

.circleci/config.yml

Enable race tests on master branch 
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-34124

MM-34124: Enable race tests on master branch

---

templates/cloud_welcome_email.html

Cherry pick of #17198 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```

Automated cherry pick of #17198

---

go.tools.mod
go.tools.sum
i18n/en.json

Removes an unused i18n string from en.json
**To be merged into Shared Channels branch.**
NONE
```release-note
NONE
```

Remove unused i18n string

---

services/sharedchannel/permalink_test.go
store/storetest/reaction_store.go

A few merge issues with master have made it into the feature branch.
`store/storetest/reaction_store.go`
`services/sharedchannel/permalink_test.go`
https://mattermost.atlassian.net/browse/MM-34239
```release-note
NONE
```

MM-34239 repair merge issues with master

---

app/admin.go
app/app.go
app/app_iface.go
app/cluster_handlers.go
app/opentracing/opentracing_layer.go
app/server.go
app/session.go
app/web_hub.go
cmd/mattermost/commands/server.go

Move some cluster handlers registrations to server creation.
https://mattermost.atlassian.net/browse/MM-34179
```release-note
NONE
```

[MM-34179] app: move cluster registeration to server creation

---

cmd/mattermost/commands/server.go
cmd/mattermost/commands/server_test.go

It seems like https://github.com/mattermost/mattermost-server/pull/17306 introduced a race condition. 
https://mattermost.atlassian.net/browse/MM-34557
```release-note
NONE
```

[MM-34557] commands/server_test: add skip

---

app/admin.go
app/app.go
app/app_iface.go
app/cluster_handlers.go
app/opentracing/opentracing_layer.go
app/server.go
app/session.go
app/web_hub.go
cmd/mattermost/commands/server.go
cmd/mattermost/commands/server_test.go

Cherry-pick of https://github.com/mattermost/mattermost-server/pull/17306
```release-note
NONE
```

[MM-34179] cherry-pick of: app: move cluster registeration to server creation (#17306)

---

cmd/mattermost/commands/server_test.go

Cherry pick of #17321 on release-5.34.

Automated cherry pick of #17321

---

app/server.go

There was a small chance where the metrics server initialized but before the go routine starts it, another call to stop server was being called. This was causing failures in CI. I removed the `nil` check approach and added a notify channel to make sure the go routine is being started before releasing the lock.
https://mattermost.atlassian.net/browse/MM-34520
```release-note
NONE
```

[MM-34520] app/server: make sure if metrics server goroutine executed

---

app/email.go

Cherry pick of #17338 on cloud.
/cc  @AGMETEOR

Automated cherry pick of #17338

---

api4/config_test.go

Fix broken test 
```release-note
NONE
```

[No-Ticket] Fix Broken Test

---

.circleci/config.yml
app/admin.go
app/app.go
app/app_iface.go
app/cluster_handlers.go
app/opentracing/opentracing_layer.go
app/server.go
app/session.go
app/web_hub.go
cmd/mattermost/commands/server.go

Cherry pick of #17306 on release-5.34.

Automated cherry pick of #17306

---

model/version.go

Fix missing version

---

api4/websocket.go
app/web_conn.go
app/websocket_router.go
model/config.go

Cherry pick of #17297 on cloud.
/cc  @agnivade

Automated cherry pick of #17297

---

i18n/en.json

Small update to the title field of the cloud welcome email for trials
https://mattermost.atlassian.net/browse/MM-34504
```release-note
None
```

[MM-34504] Change cloud welcome email copy

---

services/remotecluster/ping_test.go

https://mattermost.atlassian.net/browse/MM-34785
```release-note
NONE
```

MM-34785: Skip TestPing

---

api4/shared_channel_test.go
app/remote_cluster_service_mock.go
app/remote_cluster_test.go
app/session_test.go
app/slashcommands/command_remote.go
i18n/en.json
model/at_mentions.go
model/auditconv.go
model/config.go
model/remote_cluster.go
model/remote_cluster_test.go
model/user.go
model/user_test.go
services/remotecluster/invitation.go
services/remotecluster/send_test.go
services/remotecluster/sendmsg.go
services/remotecluster/service.go
services/sharedchannel/channelinvite_test.go
services/sharedchannel/mock_AppIface_test.go
services/sharedchannel/msg.go
services/sharedchannel/service.go
services/sharedchannel/sync_recv.go
services/sharedchannel/sync_send.go
services/sharedchannel/util.go
services/sharedchannel/util_test.go
store/sqlstore/remote_cluster_store.go
store/storetest/remote_cluster_store.go
store/storetest/shared_channel_store.go

Cherry pick of #17347 on cloud.
/cc  @wiggin77

Automated cherry pick of #17347

---

app/post_metadata.go
services/httpservice/client.go

Cherry pick of #17186 on cloud.
/cc  @elyscape

Automated cherry pick of #17186

---

api4/cloud.go
app/app_iface.go
app/cloud.go
app/email.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/cloud.go
templates/cloud_trial_end_warning.html
templates/cloud_trial_end_warning.mjml

Cherry pick of #17397 on cloud.

Automated cherry pick of #17397

---

api4/cloud.go
app/email.go
templates/cloud_welcome_email.html

Cherry pick of #17350 on cloud.
/cc  @AGMETEOR

Automated cherry pick of #17350

---

store/sqlstore/file_info_store.go

Fix problem with nulls in file infos content field
[MM-34857](https://mattermost.atlassian.net/browse/MM-34857)
```release-note
NONE
```

Fix problem with nulls in file infos content field

---

store/sqlstore/file_info_store.go

Cherry pick #17404
```release-note
NONE
```

Cherry pick #17404

---

store/sqlstore/store.go
store/sqlstore/store_test.go

Cloud cherry-pick of https://github.com/mattermost/mattermost-server/pull/17428
```release-note
* Fix datasource connection parsing issue when appending multiStatements param for MySQL.
```

Hotfix add multistatements param on mysql url

---

store/sqlstore/upgrade.go

Trying to fix this once and for all. Cloud branch didn't get updated so we ended up doing the migration on MySQL on the newly cut release branch.
https://mattermost.atlassian.net/browse/MM-34888
```release-note
NONE
```

[MM-34888] Fix 5.32 migration (cloud branch)

---

store/sqlstore/upgrade.go

Keeping both branches (cloud and master) in sync so that this won't happen again.
https://github.com/mattermost/mattermost-server/pull/17414
https://github.com/mattermost/mattermost-server/pull/17413
https://mattermost.atlassian.net/browse/MM-34888
```release-note
NONE
```

[MM-34888] Fix 5.32 migration (master branch)

---

app/plugin_api_test.go
app/plugin_requests.go
plugin/context.go

Cherry pick of #17418 on cloud.
/cc  @hanzei

Automated cherry pick of #17418

---

i18n/en.json
model/config.go

Cherry pick of #17431 on cloud.
/cc  @agnivade

Automated cherry pick of #17431

---

build/Dockerfile

Cherry pick of #17403 on cloud.
/cc  @jespino

Automated cherry pick of #17403

---

app/permissions_migrations.go

Cherry pick of #17401 on cloud.
/cc  @hahmadia
```release-note
NONE
```

Automated cherry pick of #17401

---

app/app.go
app/bot.go
app/server.go

Completely disabled Admin Advisor
https://mattermost.atlassian.net/browse/MM-34893
None
1. **Docs** - https://github.com/mattermost/docs/pull/4503

#MM-34893 Completely disabled Admin Advisor

---

app/app.go
app/bot.go
app/server.go

Cherry pick of #17422 on cloud.

Automated cherry pick of #17422

---

store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/searchlayer/file_info_layer.go
store/sqlstore/file_info_store.go
store/store.go
store/storetest/mocks/FileInfoStore.go
store/timerlayer/timerlayer.go

Fixing problem with read-replica on indexing files
[MM-34857](https://mattermost.atlassian.net/browse/MM-34857)
```release-note
NONE
```

Fixing problem with read-replica on indexing files

---

store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/searchlayer/file_info_layer.go
store/sqlstore/file_info_store.go
store/store.go
store/storetest/mocks/FileInfoStore.go
store/timerlayer/timerlayer.go

Cherry pick of #17460 on cloud.
/cc  @jespino

Automated cherry pick of #17460

---

services/docextractor/plain.go

Fix performance problem on document extraction
```release-note
NONE
```

Fix performance problem on document extraction

---

services/docextractor/plain.go

Cherry pick of #17470 on cloud.
/cc  @jespino

Automated cherry pick of #17470

---

api4/api.go
api4/permission.go
api4/permissions_test.go
api4/role.go
model/client4.go

Cherry pick of #17466 on release-5.35.
/cc  @hahmadia

Automated cherry pick of #17466

---

Makefile
api4/remote_cluster.go
model/user.go
services/remotecluster/mocks_test.go
services/remotecluster/send.go
services/remotecluster/sendfile.go
services/remotecluster/sendmsg.go
services/remotecluster/sendprofileImage.go
services/remotecluster/sendprofileImage_test.go
services/remotecluster/service.go
services/sharedchannel/mock_AppIface_test.go
services/sharedchannel/msg.go
services/sharedchannel/service.go

This PR adds support for synchronizing user's profile image for shared channels.
https://mattermost.atlassian.net/browse/MM-34712
```release-note
NONE
```

MM-34712 shared channels: sync user profile image

---

model/version.go
store/sqlstore/upgrade.go

upgrade DB for 5.35
N/A
```release-note
```

upgrade DB for 5.35

---

api4/cloud.go
app/app_iface.go
app/cloud.go
app/email.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/cloud.go
templates/cloud_trial_ended_email.html
templates/cloud_trial_ended_email.mjml

Cherry pick of #17478 on cloud.
/cc  @AGMETEOR

Automated cherry pick of #17478

---

Makefile
api4/remote_cluster.go
model/user.go
services/remotecluster/mocks_test.go
services/remotecluster/send.go
services/remotecluster/sendfile.go
services/remotecluster/sendmsg.go
services/remotecluster/sendprofileImage.go
services/remotecluster/sendprofileImage_test.go
services/remotecluster/service.go
services/sharedchannel/mock_AppIface_test.go
services/sharedchannel/msg.go
services/sharedchannel/service.go

Cherry pick of #17375 on cloud.
/cc  @wiggin77

Automated cherry pick of #17375

---

model/version.go
store/sqlstore/upgrade.go

cherry pick of https://github.com/mattermost/mattermost-server/pull/17488
```release-note
NONE
```

upgrade DB for 5.35 (#17488)

---

store/sqlstore/file_info_store.go

Fix file info index batch
```release-note
NONE
```

Fix file info index batch

---

store/sqlstore/file_info_store.go

Cherry pick of #17525 on release-5.35.
/cc  @jespino

Automated cherry pick of #17525

---

app/notification.go
store/sqlstore/upgrade_test.go

Cherry pick of #17503 on cloud.
/cc  @reflog

Automated cherry pick of #17503

---

Makefile

Cherry pick of #17465 on release-5.35.
/cc  @hanzei

Automated cherry pick of #17465

---

.circleci/config.yml

Follow up of https://github.com/mattermost/mattermost-server/pull/17154
none
```release-note
NONE
```

bump golangci-lint to 1.39.0

---

app/migrations.go

This migration was failing during scheme validation since we were setting both channel and team roles.
PR fixes this by only setting the role based on the scope for the scheme.
I am not very experienced with our permissions system so please let me know if you think this should be addressed differently.
https://mattermost.atlassian.net/browse/MM-35222
```release-note
NONE
```

[MM-35222] Fix DoGuestRolesCreationMigration

---

app/migrations.go

Cherry pick of #17523 on release-5.35.

Automated cherry pick of #17523

---

app/migrations.go

Add migration to set the ExtractContent settings to true by default
[MM-35304](https://mattermost.atlassian.net/browse/MM-35304)
```release-note
NONE
```

Add migration to set the ExtractContent settings to true by default

---

app/migrations.go

Cherry pick of #17545 on cloud.
/cc  @jespino

Automated cherry pick of #17545

---

app/plugin.go

A race happens when we try to enable plugins
in an HA environment. There is no loss in functionality
here, but it's a timing bug.
There are two bugs here.
The first one is a case of nested config listeners. a.InitPlugins
is called in InitServer, and as well as a config listener. And that
calls a.SyncPluginsActiveState(). But inside a.InitPlugins,
there is yet another config listener which again calls
a.SyncPluginsActiveState(). The first fix is to simply not call
the method again from the nested listener.
The second bug happens because the config changed message is sent
across the cluster only after saving the config locally
in the store. To fix this, we simply change GetPluginStatus
to not fail and return empty status when other nodes don't have plugins
enabled. …

MM-34419: Fix plugin enable race

---

api4/file.go
api4/file_test.go
app/file.go
app/migrations.go
app/post_metadata_test.go
app/upload.go
cmd/mattermost/commands/extract_content.go
i18n/en.json
model/feature_flags.go
services/docextractor/plain.go
services/docextractor/plain_test.go
services/searchengine/bleveengine/indexer/indexing_job.go
testlib/store.go

Removing FilesSearch feature flag
[MM-33136](https://mattermost.atlassian.net/browse/MM-33136)
- Has server changes mattermost/mattermost-webapp#8029
- Has mobile changes mattermost/enterprise#988
```release-note
NONE
```

Removing FilesSearch feature flag

---

.circleci/config.yml

ci: drop sentry setup for PRs
We spoke in a Dev meeting and decided that is not relevant to setup sentry for PR testing for now
n/a
```release-note
NONE
```

ci: drop sentry setup for PRs

---

i18n/en.json

Updated i18n strings
Remote Clusters --> Secure Connections
/share --->  /share-channel
https://mattermost.atlassian.net/browse/MM-35582
```release-note
NONE
```

MM-35582 updated i18n strings

---

i18n/en.json
utils/api.go

Cherry Pick of https://github.com/mattermost/mattermost-server/pull/17591 into release-5.35
```release-note
NONE
```

Cherry Pick of https://github.com/mattermost/mattermost-server/pull/17591 into release-5.35

---

i18n/en.json
utils/api.go

https://github.com/mattermost/mattermost-server/pull/17591 cherry pick into cloud
```release-note
NONE
```

https://github.com/mattermost/mattermost-server/pull/17591 cherry pick into cloud

---

store/sqlstore/store.go
store/sqlstore/store_test.go

Cherry pick of https://github.com/mattermost/mattermost-server/pull/17624.
https://mattermost.atlassian.net/browse/MM-35767
```release-note
NONE
```

[MM-35767] Cherrypick on 5.35

---

jobs/schedulers_test.go

Fixes some races introduced in tests of https://github.com/mattermost/mattermost-server/commit/7bb23323d146859ef705c67b35dedd8ca0b14a7e
```release-note
NONE
```

Fix racy tests

---

app/email.go
templates/invite_body.html

Cherry-pick of #17643 to `cloud`

[MM-35841] Fix invalid use of variables in invite_body template (#17643)

---

model/config.go

We identified that sometimes the redirection to the right link is broken
so we want to be sure that our users will end up in the right place.
https://mattermost.atlassian.net/browse/MM-35893
```release-note
NONE
```

Update the about.mattermost.com links to the real ones

---

api4/apitestlib.go
api4/status.go
api4/status_test.go
app/app.go
app/app_iface.go
app/helper_test.go
app/opentracing/opentracing_layer.go
app/plugin_api.go
app/server.go
app/status.go
model/scheduled_task.go
model/scheduled_task_test.go
model/status.go
model/status_test.go
plugin/api.go
plugin/api_timer_layer_generated.go
plugin/client_rpc_generated.go
plugin/plugintest/api.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/status_store.go
store/sqlstore/upgrade.go
store/store.go
store/storetest/mocks/StatusStore.go
store/storetest/status_store.go
store/timerlayer/timerlayer.go

This reverts commit 77d42568f94cf2f1c141d3ee4775269259b3d480.
https://github.com/mattermost/mattermost-server/issues/15640
```release-note
NONE
```

Revert "[MM-8497] Ability to set Do Not Disturb for a specified period of time (#16067)"

---

cmd/mattermost/commands/extract_content.go

Fix typo in `extract-documents-content` command line tool description.
N/A
```release-note
NONE
```

 Fix typo in `extract-documents-content` command line tool description

---

services/docextractor/pdf.go
services/docextractor/pdf_test.go

Making default pdf extracting more robust
https://mattermost.atlassian.net/browse/MM-35990
```release-note
NONE
```

Making default pdf extracting more robust

---

model/feature_flags.go

Adding the focalboard plugin feature flag
```release-note
NONE
```

Adding the focalboard plugin feature flag

---

model/version.go
store/sqlstore/upgrade.go

per request: https://community.mattermost.com/private-core/pl/whe59iimdb8mbjd3adx768m34o
db: upgrade db to 5.36
n/a
```release-note
db: upgrade db to 5.36
```

db: upgrade db to 5.36

---

model/version.go

Upgrade version to 5.36.0
```release-note
NONE
```

Upgrade version to 5.36.0

---

store/sqlstore/store.go
store/sqlstore/store_test.go

Cherry pick of #17723 on release-5.36.

Automated cherry pick of #17723

---

api4/cloud.go
api4/user.go
api4/user_test.go
app/app_iface.go
app/cloud.go
app/opentracing/opentracing_layer.go
i18n/en.json

Cherry pick of #17719 on cloud.
/cc  @AGMETEOR

Automated cherry pick of #17719

---

app/notification_push.go
app/notification_push_test.go

Cherry pick of #17697 on release-5.36.

Automated cherry pick of #17697

---

web/oauth.go
web/saml.go

Cherry pick of #17743 on release-5.36.

Automated cherry pick of #17743

---

utils/api.go
web/oauth_test.go

Cherry pick of #17789 on release-5.34.

Automated cherry pick of #17789

---

app/user.go
app/user_test.go

Cherry pick of #17800 on cloud.

Automated cherry pick of #17800

---

.gitlab-ci.yml

Hotfix to build master branch

---

Makefile

```release-note
Updated focalboard builtin plugin version to v0.7.0
```

Bump focalboard prepackaged plugin version to v0.7.0

---

.gitlab-ci.yml
.gitlab-ci/scripts/test-schema/mysql.sh
.gitlab-ci/scripts/test-schema/postgres.sh
.gitlab-ci/scripts/test/mysql.sh
.gitlab-ci/scripts/test/postgres.sh

https://git.internal.mattermost.com/mattermost/ci/mattermost-server/-/merge_requests/3
```release-note
```

Image as env var.

---

app/auto_responder.go

Cherry pick of #17847 on cloud.
/cc  @agnivade

Automated cherry pick of #17847

---

app/slashcommands/command_custom_status.go
model/emoji.go
model/emoji_test.go
model/utils.go
model/utils_test.go

Cherry pick of #17846 on cloud.

Automated cherry pick of #17846

---

store/sqlstore/upgrade.go

move migration to future release as 536 is already done

---

.gitlab-ci.yml

I forgot the other time to add these additional refs. 
```release-note
```

Run test-schema on additional refs.

---

Makefile

```release-note
Update prepackaged focalboard version to 0.7.3
```

Prepackage focalboard v0.7.3

---

Makefile

Cherry pick of #17867 on release-5.37.
```release-note
Update prepackaged focalboard version to 0.7.3
```

Automated cherry pick of #17867

---

model/cloud.go

This PR adds the new properties to the product model to handle the billing schema and the recurring interval.
https://mattermost.atlassian.net/browse/MM-36731
https://github.com/mattermost/mattermost-webapp/pull/8341
```release-note
NONE
```

MM-36731 - ux changes cloud starter flat fee

---

store/sqlstore/upgrade.go

Set current schema version to 5.37
