app/channel.go
app/channel_test.go
app/team.go
i18n/en.json
store/opentracing_layer.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/channel_store.go
store/storetest/mocks/ChannelStore.go
store/timer_layer.go

This works like the old `FileInfo` migration where `SidebarCategory` entries are created on demand when the client requests them.
A few things to note:
1. Assuming I understand how transactions work, this should prevent duplicate categories from being created even if this is called during migration because of https://github.com/mattermost/mattermost-server/pull/14870
2. This assumes that `GetSidebarCategories` will always be called before any other action involving the sidebar. I think it's safe to assume this because you can't fetch individual categories before they exist and unless the user is hitting the API directly, we won't allow them to create categories until the initial ones are loaded.
3. I am mildly concerned about a potential replication delay between databases when creating …

MM-26753 Create initial sidebar categories on demand if migration hasn't ran

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

The missing where case made it so that, when one user favourites a channel, others have it removed from their Favorites. Gotta fight for those favourites!
https://mattermost.atlassian.net/browse/MM-26793

MM-26793 Fix accidentally removing other users' favorites

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

The last PR fixed a bug where other users' favourites would be deleted when moving a channel into Favorites, but this fixes the same bug when you move a channel into another category. I'm going back through the sidebar code to make sure we don't have any other missing where clauses elsewhere.
https://mattermost.atlassian.net/browse/MM-26793

MM-26793 Fix accidentally removing other users' favorites again

---

store/sqlstore/scheme_store.go

- Since a team scheme always has channel level role names also cached both channel and team caches have to be cleared... my previous PR cleared the Team cache but the channel cache was still only cleared when the scheme was a channel scheme, this fixes that.
- For 5.26 I will add a unit test to ensure that this behaviour always works as expected but for now this needs to go for 5.25 release
- https://mattermost.atlassian.net/browse/MM-24560

[MM-24560] Always clear channel cache when scheme is deleted

---

app/auto_responder_test.go
app/bot_test.go
app/channel_test.go
app/command_autocomplete_test.go
app/command_me_test.go
app/command_test.go
app/config_test.go
app/download_test.go
app/export_test.go
app/file_test.go
app/group_test.go
app/integration_action_test.go
app/notification_test.go
app/permissions_test.go
app/plugin_api_test.go
app/plugin_health_check_test.go
app/plugin_hooks_test.go
app/plugin_install_test.go
app/plugin_shutdown_test.go
app/plugin_test.go
app/post_metadata_test.go
app/session_test.go
app/team_test.go
app/web_hub_test.go
app/webhook_test.go

`th.InitBasic` initializes users, channels, and teams. But a lot of
tests don't use it at all, causing unncessary delays. A single `InitBasic`
call takes around 400ms. This PR removes 71 of them, approximately shaving
off 28 seconds. Arguably, this would be more because some tests run in loops.
https://mattermost.atlassian.net/browse/MM-26750

MM-26750: Remove instances of InitBasic when it's not required

---

app/diagnostics.go
model/config.go

This PR adds `SMTPServerTimeout` value to `GlobalRelayMessageExportSettings`.
https://mattermost.atlassian.net/browse/MM-26754

[MM-26754] config: add server timeout to global_relay settings

---

app/plugin_api_test.go

PR *attempts* to fix flaky `TestPluginAPIUpdateUserPreferences`.
I wasn't able to reproduce it locally but I suspect the problem was that the order of the returned preferences cannot be relied upon.
Feel free to give it a spin and check if this actually fixes it.
https://mattermost.atlassian.net/browse/MM-26877

[MM-26877] Fix flaky TestPluginAPIUpdateUserPreferences

---

utils/testutils/testutils.go

We were just hardcoding to dockerhost which would only work inside
a CI environment. This PR generalizes the logic to use fallbacks
if dockerhost is not available.
https://mattermost.atlassian.net/browse/MM-26883
https://mattermost.atlassian.net/browse/MM-26884

MM-26883/26884: properly identify interface name for test services

---

api4/team.go
api4/team_local.go
api4/team_test.go
i18n/en.json

- If the `EnableAPITeamDeletion` option is not set, then PermanentDeleteTeam returns an error instead of falling back to soft delete. This change was made to bring the behaviour into alignment with admin expectations and docs - https://docs.mattermost.com/administration/config-settings.html#enable-api-team-deletion
- https://mattermost.atlassian.net/browse/MM-26891

MM-26891: return error if option not set instead of soft delete for permanent team deletion

---

i18n/en.json
store/sqlstore/group_store.go

Updating a Group or a GroupMember only changed the UpdateAt or CreateAt times
respectively. And it threw an error if number of rows changed was not 1.
However, it can happen that 2 calls happen so fast that 1 milisecond does not pass,
or even 2 concurrent calls at the same time might happen so that model.GetMillis
return the same timestamp. In those cases, the number of rows updated can be 0.
The error should just check if the number is greater than 1, instead of not equal to 1.
This makes it more robust and correct.

MM-18006: Fix flaky test CreateOrRestoreGroupMember (#14955)

---

api4/post.go
api4/post_test.go
store/sqlstore/post_store.go
store/storetest/post_store.go

PR fixes a 500 error returned by the `/posts/unread` endpoint caused by an [integer overflow](https://en.wikipedia.org/wiki/Integer_overflow) when `limit_after` was set to 0.
https://mattermost.atlassian.net/browse/MM-26535
https://github.com/mattermost/mattermost-api-reference/pull/554

[MM-26535] Fix 500 error on fetching unread posts

---

model/link_metadata.go
store/storetest/link_metadata_store.go

PR fixes `TestLinkMetadataStore` failing locally for some.
The main issue was not forcing the time to be in UTC.
`model.FloorToNearestHour()` would fail for some particular timezones.
https://mattermost.atlassian.net/browse/MM-26881

[MM-26881] Fix TestLinkMetadataStore test failing for some

---

store/sqlstore/store_test.go

We already run the entire test suite for both mysql and postgres in parallel in CI.
So we just run the tests for the current database set.
https://mattermost.atlassian.net/browse/MM-27041

MM-27041: Do not run tests against both DBs in CI

---

app/email.go

* MM-26052: Translate footer text in invite emails
We pass the user locale instead of the default locale to translate
the footer text too.
* Use default server locale

MM-26052: Translate footer text in invite emails (#14956)

---

app/app.go
app/app_iface.go
app/app_test.go
app/opentracing/opentracing_layer.go
cmd/mattermost/commands/channel.go
cmd/mattermost/commands/command.go
cmd/mattermost/commands/config.go
cmd/mattermost/commands/export.go
cmd/mattermost/commands/group.go
cmd/mattermost/commands/import.go
cmd/mattermost/commands/integrity.go
cmd/mattermost/commands/jobserver.go
cmd/mattermost/commands/ldap.go
cmd/mattermost/commands/license.go
cmd/mattermost/commands/permissions.go
cmd/mattermost/commands/plugin.go
cmd/mattermost/commands/reset.go
cmd/mattermost/commands/roles.go
cmd/mattermost/commands/sampledata.go
cmd/mattermost/commands/team.go
cmd/mattermost/commands/test.go
cmd/mattermost/commands/user.go
cmd/mattermost/commands/webhook.go

This PR removes `(*App).Shutdown()`, which forwarded the call to (*Server).Shutdown().  All references to it now call Shutdown on server directly.
https://mattermost.atlassian.net/browse/MM-25744

MM-25744 Remove (*App).Shutdown and update all references.

---

app/channel.go
app/channel_test.go
app/team.go
app/team_test.go

We were just using page and incrementing by 1. This would fetch pages
one by one like (1-100, 2-102, 3-103) rather than (1-100,100-200,200-300).
We fix that to update the correct page offset.
https://mattermost.atlassian.net/browse/MM-27187

MM-27187: Use the correct page offset for cache clear methods

---

app/channel.go
app/channel_test.go
app/team.go
app/team_test.go

* MM-27187: Use the correct page offset for cache clear methods
We were just using page and incrementing by 1. This would fetch pages
one by one like (1-100, 2-102, 3-103) rather than (1-100,100-200,200-300).
We fix that to update the correct page offset.
* Trigger CI

MM-27187: Use the correct page offset for cache clear methods (#15094)

---

api4/user_local.go

This is a 5.28 feature and was mistakenly included in a cherry-pick PR
https://github.com/mattermost/mattermost-server/commit/88586bff05814c37b971f5058b6c3806bac957a1.
More discussion here: https://community-daily.mattermost.com/core/channels/developers-server/qpt6gcfz5pdxpf7gxwbpd9a6aw

Remove localDeleteUser in 5.26

---

app/notification_push.go
app/server.go

* MM-27116: Drain push notification channel before closing
Without this, pending push notifications will not be sent when shutting down
or restarting the server.
* Fix race
* Re-arrange server shutdown

MM-27116: Drain push notification channel before closing (#15066)

---

Makefile

This starts up docker containers which can help avoid failures
during a test run if a developers forgets to manually start them.
https://mattermost.atlassian.net/browse/MM-26882

MM-26882: Ensure to start docker containers during test

---

CODEOWNERS

This PR sets @mattermost/toolkit as the code owner of `/plugin`. I wasn't able to verify the changes as it seams like `master` is always used as the source of information about code owners.
See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-file-location for a syntax guide.
https://community-daily.mattermost.com/core/pl/gzmrhtowspnsxyr1ik6ur84cka

Add toolkit team as owner of plugin package

---

app/admin.go

When accessing the logs via the System Console it prints a header with the name of the instance, if Mattermost is set to use the Cluster mode.
However, this is an E20 feature and if you enable the cluster mode either in team edition or with an E10 license this part will break and have a panic and not show the logs to the user.
This PR fixes this issue by checking if there is a valid license and if that allows the Cluster mode
Steps to test without this fix:
- Spin a mattermost with e10 or team edition and set the configuration `MM_CLUSTERSETTINGS_CLUSTERNAME=production` and `MM_CLUSTERSETTINGS_ENABLE=true`
- Open the system logs and go to the Server Logs option.
- No logs will appear and if you check the network or the console in the google dev tools you will see the request to …

admin/logs: Check if the license allows the cluster mode

---

build/Dockerfile

docker: update base package to use MM release 5.25.2

docker: update base package to use MM release 5.25.2

---

.circleci/config.yml
build/Dockerfile.buildenv
build/Jenkinsfile.branch
build/Jenkinsfile.pr
build/README.md
build/local-test-env.sh

* MM-26584: Bump up Go patch version
This contains a patch fix for https://github.com/golang/go/issues/38023
which have been encountered in our load tests and some users.
I have verified on such a stuck instance and the thread dump seem to match
with what is seen on the issue. All threads stuck on runtime.futex, except one,
which is at runtime.osyield.
And of all the times load tests were run which _did not_ show this issue,
it was run with a version greater than 1.14.1, which further points to the
theory that this bug is the culprit.
* Replace docker image versions.
* Update build/README.md
Co-authored-by: Elisabeth Kulzer <elikul@elikul.de>

MM-26584: Bump up Go patch version (#15156)

---

api4/file.go
app/file.go

- Added `Content-Length` validation for file uploads.
- Removed buffer allocation before the actual uploaded data gets in.
Since the [original code](https://github.com/mattermost/mattermost-server/pull/9835) was designed to address some performance issues I've run both the provided benchmarks and a load-test to verify that the proposed changes wouldn't cause a significant regression.
```
name                                                          old time/op    new time/op    delta
UploadFile/random-5Mb-gif-raw-ish_DoUploadFile-8                65.5ms ± 3%    67.9ms ± 3%    +3.64%  (p=0.032 n=5+5)
UploadFile/random-5Mb-gif-raw_UploadFileX_Content-Length-8      4.30ms ± 1%    7.50ms ± 2%   +74.32%  (p=0.008 n=5+5)
UploadFile/random-5Mb-gif-raw_UploadFileX_chunked-8             6.10ms ± …
```

[MM-27293] Remove heap pre-allocation for file uploads

---

app/plugin.go

PR fixes a panic happening when the server was getting shutdown before `InitPlugins()` was able to complete.
https://mattermost.atlassian.net/browse/MM-27281

[MM-27281] Fix possible panic on server shutdown

---

api4/bot.go

This PR fixes a permission check error for `convertBotToUser`. Only system administrators can perform this action.

api4/bot: fix permission check in convert handler

---

app/team.go

If user tries to login/register via SAML by a guest invite link, it shows the text `This is not a valid link`. 
This PR fixes this problem
https://mattermost.atlassian.net/browse/MM-27519

[MM-27519] Guest User Invites not working in SAML only environment

---

store/sqlstore/post_store.go

Even after specifying all the 3 columns to coerce MySQL into choosing
the right multi-column index, it sometimes uses 2 separate indices
and does an index_merge of them.
This creates problems because the DeleteAt=0 search is essentially
the entire Posts table, and causes a disastrously bad performance
than even choosing the wrong index (idx_create_at).
The problem with this approach is that we hardcode the decision
to a specific index when MySQL was free to choose the right index
depending on table statistics. However, there does not appear to be
a case where this index can cause regressions than using some other index.
Another option here was to set optimizer_switch="index_merge_intersection=off"
at a session level for a transaction and then switch it back on after the
query is done. …

MM-27575: Use index hints to prevent index_merge_intersection

---

store/sqlstore/post_store.go

Even after specifying all the 3 columns to coerce MySQL into choosing
the right multi-column index, it sometimes uses 2 separate indices
and does an index_merge of them.
This creates problems because the DeleteAt=0 search is essentially
the entire Posts table, and causes a disastrously bad performance
than even choosing the wrong index (idx_create_at).
The problem with this approach is that we hardcode the decision
to a specific index when MySQL was free to choose the right index
depending on table statistics. However, there does not appear to be
a case where this index can cause regressions than using some other index.
Another option here was to set optimizer_switch="index_merge_intersection=off"
at a session level for a transaction and then switch it back on after the
query is done. …

MM-27575: Use index hints to prevent index_merge_intersection (#15207)

---

app/authorization.go
app/authorization_test.go

Fixes a regression caused by https://github.com/mattermost/mattermost-server/pull/14961
Permissions where not cascading properly to check for system admin level permissions if the system admin was a member of the team. 
https://mattermost.atlassian.net/browse/MM-27572

MM-27572 permissions regression

---

store/sqlstore/upgrade.go

- slash commands will fail if `PluginId` is null in the database. So set all `PluginId`s to a blank string.
- move the new `PluginId` field to the 5.28 migration (which is when it will appear)
- https://mattermost.atlassian.net/browse/MM-27508

MM-27508 - Fix slash commands

---

app/app_iface.go
app/login.go
app/opentracing/opentracing_layer.go
app/session_test.go
model/saml.go
model/session.go
model/session_test.go
web/oauth.go

- Looks like https://github.com/mattermost/mattermost-server/pull/14874 introduced a breaking change which conflated the `Session.isOAuth` to mean a session created for an OAuth App _and_ a session created by a user logging through an OAuth provider.
- This PR adds a new prop to sessions `USER_AUTH_SERVICE_IS_OAUTH  = "isOAuthUser"` which is set when a _user_ logs in through an oauth provider, while keeping `Session.IsOauth = false`. 
- https://mattermost.atlassian.net/browse/MM-27623

[MM-27623] Add new session prop for oauth

---

store/sqlstore/bot_store.go
store/sqlstore/channel_store.go
store/sqlstore/oauth_store.go
store/sqlstore/team_store.go
store/sqlstore/user_store.go
store/storetest/channel_store.go

Update queries are not guaranteed to always update the row.
Since we are only bumping the UpdateAt timestamps, if 2 update
requests hit concurrently within the same millisecond, then one
is bound to fail.
We fix all cases in the codebase where we were updating the UpdateAt
field to not check for count != 1, but rather count > 1.
A similar fix was already done in 3f46cf6f60863a356c8994f1df306464feb8ae25.
https://mattermost.atlassian.net/browse/MM-27040

MM-27040: Fix flaky tests due to same UpdateAt timestamp

---

api4/team_local.go
api4/team_test.go

This PR adds `updateChannelPrivacy` and `restoreTeam` endpoints to local router.
https://mattermost.atlassian.net/browse/MM-27377
https://mattermost.atlassian.net/browse/MM-27378

[MM-27377] api4/team_local: add updateChannelPrivacy and restoreTeam to local mode

---

cmd/mattermost/commands/version.go

Sometimes we need to know the version of the Mattermost but don't have/want to have it connected to a DB.
In the mattermost cloud context, we need to know which version is the docker image refers to, because we can use tags that do not have the version information in the tag like `mattermost/mattermost-team-edition:5.25.0` which is a 5.25.0 version, we can have something like: `mattermost/mattermost-team-edition:a8445a0` which we don't know which version it is.
In the mattermost-operator we need to know which version that image belongs to so we can enable/disable features that we need to set in the env vars.
this is a proposal to make the operation life a bit better and it is related to https://github.com/mattermost/mattermost-operator/pull/171 and not rely only in the image tag and …

cmd/version: skip server start to get the current mattermost version

---

.circleci/config.yml
build/release.mk

Our codebase uses main_test.go files to control tests at a package level.
However, the problem with that is when we use ./... to build the codebase,
those binaries also get built.
This is unnecessary and creates further delays in the pipeline. All we need to build
are only mattermost and platform binaries in CI. The rest are dependant on the developer.
In my dev environment, this reduces the build times from 13 seconds to 4 seconds.
https://mattermost.atlassian.net/browse/MM-27735

MM-27735: Do not build test and other tools in CI

---

app/channel.go

This PR fixes a server panic when user joins a team and one of the default channels has been archived.
This can be triggered by archiving "Off-Topic" or any of the channels listed in `TeamSettings.ExperimentalDefaultChannels`.
https://mattermost.atlassian.net/browse/MM-27868

MM-27868 fix panic when user joins teams with default channels archived

---

api4/config.go
api4/config_test.go

PR fixes two instances where sending an `nil` `SiteURL` could cause a panic when patching the config.
https://mattermost.atlassian.net/browse/MM-27836

[MM-27836] Fix possible panic when patching config

---

cmd/mattermost/commands/sampledata.go
cmd/mattermost/commands/sampledata_test.go

Restrict the sampledata generation to not run without enough users for group channels
[MM-27886](https://mattermost.atlassian.net/browse/MM-27886)

Restrict the sampledata generation to not run without enough users for group channels

---

cmd/mattermost/commands/server.go

Unless we set traceback level to crash, goroutines from all threads aren't printed.
See: https://github.com/golang/go/issues/13161.
This is important because SIGQUIT traces will miss on goroutines.
https://mattermost.atlassian.net/browse/MM-27887

MM-27887: set traceback to crash from code

---

app/channel.go

Server panics when user joins team and one of the default channels has been archived.
This can be triggered by archiving "Off-Topic" or any of the channels listed in `TeamSettings.ExperimentalDefaultChannels`.
https://mattermost.atlassian.net/browse/MM-27868

MM-27868 cherry pick

---

.gitignore
api4/user.go
app/app_iface.go
app/login.go
app/oauth.go
app/oauth_test.go
app/opentracing/opentracing_layer.go
app/session.go
app/session_test.go
model/session.go
web/handlers_test.go

Mobile users were having their sessions unexpectedly expired, despite having ServiceSettings.ExtendSessionLengthWithActivity enabled. 
Every time a mobile app is opened it called `/api/v4/sessions/device` which calls attachDeviceId which calls `(*Session)SetExpireInDays`. This code above assumed the expiry should be relative to CreateAt which is incorrect when ExtendSessionLengthWithActivity is enabled. Therefore, every time the mobile app was opened, the maximum expiry was set in memory to CreateAt + session_length, even if the session was extended.
(*Session)SetExpireInDays is now deprecated and replaced with (*App)SetSessionExpireInDays which takes into account the ExtendSessionLengthWithActivity setting.
https://mattermost.atlassian.net/browse/MM-27184

MM-27184 cherry pick

---

Makefile
build/release.mk
scripts/get_latest_release.sh

An unauthenticated user can only make 60 requests per hour which means 1
request every minute. This can lead to frequent rate limit errors while
getting the latest release.
We change that to use an authenticated user which is already available
in the CI. This moves us to make 5000 requests per hour.
We also add additional logging in the Makefile targets in case
the command fails again so that it's clear what has happened, and not return
cryptic 404 errors again.
Ideally, we should be able to inspect the output of the curl command, but since
the output value of the entire bash script is fed into the variable, it is a bit
difficult to print debug output.
If this still gives error, then we need to either use a cached artifact somehow
or add additional logging and add a retry logic on top of …

MM-27512: Use an authenticated user to bump up request rate limit

---

.gitignore
api4/user.go
app/app_iface.go
app/login.go
app/oauth.go
app/oauth_test.go
app/opentracing_layer.go
app/session.go
app/session_test.go
model/session.go
web/handlers_test.go

Mobile users were having their sessions unexpectedly expired, despite having ServiceSettings.ExtendSessionLengthWithActivity enabled. Bug was found here:
/model/session.go:118
```go
func (me *Session) SetExpireInDays(days int) {
if me.CreateAt == 0 {
me.ExpiresAt = GetMillis() + (1000 * 60 * 60 * 24 * int64(days))
} else {
me.ExpiresAt = me.CreateAt + (1000 * 60 * 60 * 24 * int64(days))
}
}
```
This gets called for mobile users every time the app is opened via /api/v4/sessions/device which calls attachDeviceId which calls the code above. The code above assumes the expiry should be relative to CreateAt which is incorrect when ExtendSessionLengthWithActivity is enabled. Therefore, every time the mobile app was opened, the maximum expiry was set in memory to CreateAt + session_length, even …

MM-27184 cherry pick (deprecate model.SetExpireInDays to fix mobile logout bug)

---

build/Dockerfile

image: bump default MM package to use release 5.26.0

image: bump default MM package to use release 5.26.0

---

app/session.go
app/web_hub_test.go

This is a bug which has always been there in the codebase.
And it can only occur in the extreme of edge-cases.
Following is the call trace due to which this happens:
```
0  0x0000000001dfea68 in github.com/mattermost/mattermost-server/v5/app.(*Hub).InvalidateUser // deadlock
at ./app/web_hub.go:369
1  0x0000000001dfc0bd in github.com/mattermost/mattermost-server/v5/app.(*App).InvalidateWebConnSessionCacheForUser
at ./app/web_hub.go:109
2  0x0000000001db1be5 in github.com/mattermost/mattermost-server/v5/app.(*App).ClearSessionCacheForUserSkipClusterSend
at ./app/session.go:209
3  0x0000000001db1763 in github.com/mattermost/mattermost-server/v5/app.(*App).ClearSessionCacheForUser
at ./app/session.go:170
4  0x0000000001db2d2f in github.com/mattermost/mattermost-server/v5/app.(*App).RevokeSess …
```

MM-27648: Fix a hub deadlock while revoking session

---

store/storetest/terms_of_service_store.go

The call to testGetLatestTermsOfService would happen after testSaveTermsOfService
which would persist the data between calls. Therefore, if they were to happen under
a milisecond, there would be 2 rows with the same CreateAt timestamp and the DB
would randomly return any row.
If this were to happen, then the wrong row would not match the user id and would fail.
To fix this, we just clear the table data before proceeding with the test.
https://mattermost.atlassian.net/browse/MM-23063

MM-23063: Fix flaky test TestTermsOfServiceStore

---

jobs/jobs.go

The store was changed and now returns a NoRows error rather than eating it. The calling functions need updated in order to handle that error when returned.
https://mattermost.atlassian.net/browse/MM-28043
https://github.com/mattermost/enterprise/pull/750

MM-28043:NoRows error now being returned, handle in callers

---

config/client.go

Might have done a bad copy + paste here. This number should be base 10, not base 8. Base 8 meant that the CloudUserLimit was always higher than the backend has set.
https://mattermost.atlassian.net/browse/MM-27535

[MM-27535] Change ExperimentalCloudUserLimit config to be base 10 

---

scripts/test.sh

This PR tweaks the `test.sh` file to not to remove `./data` directory before running the tests.
https://mattermost.atlassian.net/browse/MM-28080

[MM-28080] scripts/test: do not remove existing data directory

---

config/utils.go
model/config.go

In the future these will all be obfuscated via struct field tags, but for now here are a few missing sanitized passwords and secrets:
* gifycat API secret; and
* oauth app. secrets
https://mattermost.atlassian.net/browse/MM-27525

MM-27525: Sanitizes gifycat's and Oauth secrets.

---

api4/user.go

This pr patches a fix that causing the tests fail on EE builds. Also, converts from auth parameter to empty string if it has `email` as value.

api4/user: fix-failing-ee-tests

---

.circleci/config.yml

When webapp is still building the latest master commit, the appropriate commit is not found as upload in the s3 bucket, when at the same time the server pipeline runs. That's when the trap gets triggered, but it missed the redux building steps and erred on those. This PR adds those steps.

Add redux build for when webapp needs to be built in server pipeline

---

api4/apitestlib.go
api4/config_test.go

If `MM_SERVICESETTINGS_SITEURL` is set in evironment variables, the test fails on updating to the default values since the condition in `api4/config` is not satisfied. (`*old.ServiceSettings.SiteURL == "" || *new.ServiceSettings.SiteURL != ""`) . We can pass an empty string to be able to set default values in the test.
https://mattermost.atlassian.net/browse/MM-27967

[MM-27967] api4/config_test: fix flaky test if siteurl is already set

---

store/storetest/team_store.go

We got hit by yet another random text search issue, but this was
on the more extreme end because this was a string of length 4 and still
it collided.
I am not sure if there is a fool proof solution to this than just
going for a larger string.
https://mattermost.atlassian.net/browse/MM-27953

MM-27953: Fix flaky test TestTeamStore//SearchPrivate

---

app/server.go
mlog/testing.go

PR fixes a couple of races related to logging. There are [more](https://mattermost.atlassian.net/browse/MM-28399) but at least this should enable us to run tests with `-count > 1`.
https://mattermost.atlassian.net/browse/MM-27951
https://mattermost.atlassian.net/browse/MM-27952

[MM-27952] Fix some logging related races

---

api4/post.go
i18n/en.json
model/post.go
model/post_test.go

PR fixes a panic in `api4.searchPosts()` happening in case the decoding of the JSON request body failed.
https://mattermost.atlassian.net/browse/MM-28157

[MM-28157] Fix panic in api4.searchPosts()

---

store/sqlstore/post_store.go

GetPostsSince is used when loading posts for a channel.
An opportunity for optimization is that the primary SQL query
is repeated twice and then a UNION is constructed for the results.
```
SELECT
*
FROM
Posts
WHERE
UpdateAt > :Time AND ChannelId = :ChannelId
LIMIT 1000
```
But we can use a CTE for this which caches the results to be reused later.
This leads to the main query being executed once rather than twice. And from
Postgres 12 onwards, CTEs can be inlined which opens the door to further optimizations.
From the docs (https://www.postgresql.org/docs/10/queries-with.html)
> A useful property of WITH queries is that they are evaluated only once per
execution of the parent query, even if they are referred to more than once
by the parent query or sibling WITH queries. Thus, expensive …

MM-28444: Optimize GetPostsSince in postgres

---

store/sqlstore/supplier_test.go

https://mattermost.atlassian.net/browse/MM-27957

MM-27957: Fix flaky test TestRecycleDBConns

---

api4/team.go
api4/team_test.go

If more than 256 members are added to the list of invite members, then we throw an error. 
This is per comments within the Jira ticket which discussion in the comments lead to this limit being increased from the current 20 to 256.
https://mattermost.atlassian.net/browse/MM-23651
**UNBLOCKS**
https://github.com/mattermost/mattermost-webapp/pull/6405

[MM-23651] No more than 256 members are allowed to be invited 

---

services/telemetry/telemetry.go
services/telemetry/telemetry_test.go

Add an env var to indicate the installation type for telemetry. Various installers will set this appropriately, and the default is an empty string (i.e. en var unset).
https://mattermost.atlassian.net/browse/MM-28115

MM-28115: Add env var for telemetry installation type.

---

services/telemetry/telemetry.go

The initialization of rudder should happen only before the telemetry is sent, and have checked that the placeholders are not used.
[MM-28529](https://mattermost.atlassian.net/browse/MM-28529)

Fix telemetry initialization problem on placeholder usage

---

store/localcachelayer/layer_test.go
store/sqlstore/store_test.go

PR adds a check in `localcachelayer.initStores()` so that when in CI we can run the tests on one DB type only.
https://mattermost.atlassian.net/browse/MM-28033

[MM-28033] Perform localcachelayer tests for one DB type only when in CI

---

utils/subpath.go

This PR adds a function to allow for the asset subpath rewrite to be done in a specific directory, necessary to add the `mmctl config subpath` command.
https://mattermost.atlassian.net/browse/MM-25656

[MM-25656] Adds a function to allow to update assets subpath in a given directory

---

app/diagnostics_test.go

The release build for this branch is failing because of the rudder keys being set and not playing nice with these few tests. In the interest of time and getting this build to pass we can skip the tests for now and revisit a way to have them run and not fail with the pipeline.

Temporarily skip a few failing rudder tests

---

api4/system.go
api4/system_test.go
model/config.go

- Added checks on `RestrictedSystemAdmin` for system logs endpoint. 
- Added `write_restrictable` tag that will guard updates for `RestrictedSystemAdmin` to plugin settings not applicable for cloud. 
Webapp: https://github.com/mattermost/mattermost-webapp/pull/6481
[MM-28834](https://mattermost.atlassian.net/browse/MM-28834)

Restricted cloud settings

---

store/storetest/user_store.go

Fix a flaky test; The `(UserStore).GetNewUsersForTeam()` method is sorting the users with 2 criteria.
a) Creation time (newest first)
b) Name (alphabetical order)
In the test we need to supply names in alphabetical order to cover if the user creation dates are same. 
How come the creation dates can be the same? We calculate the creation date with `time.Now().UnixNano() / int64(time.Millisecond)`. So if two users are created in the same `millisecond` we end up having same `user.CreateAt` field.
https://mattermost.atlassian.net/browse/MM-28195

[MM-28195] storetest/user_store: fix flaky test

---

api4/apitestlib.go
api4/config_test.go
app/helper_test.go
cmd/mattermost/commands/cmdtestlib.go
model/config.go
services/mailservice/mail_test.go

Update settings defaults specifically for cloud **ONLY on `cloud_beta` branch**. Ticket for the server to support setting defaults based on license [MM-28883](https://mattermost.atlassian.net/browse/MM-28883). 
**Settings changed:**
- Max Users for team: `1000`
- EnableCustomEmoji: `true`
- ExperimentalSideBar: `default_on`
- EnableBotAccountCreation: `true`
- RequireEmailVerification: `true`
- RestrictSystemAdmin: `true`
- TeammateNameDisplay: `FullName`
- ExperimentalGossip:
- UseExperimentalGossip: `true`
- EnableExperimentalGossipEncryption: `true`
- SqlSettings:
- MaxIdleConns:`10`
- MaxOpenConns `100`
- Email:
- FeedbackEmail: `feedback@mattermost.com`
- ReplyToAddress: `noreply@mattermost.com`
- ConnectionSecurity: `TLS`
[MM-28803](https://mattermost.atlassian.net/browse/MM-28803)

MM-28803 - Cloud settings defaults

---

model/config.go

The feature's only like 4 years old at this point, so it's probably safe to enable by default for everyone 😛 
https://mattermost.atlassian.net/browse/MM-28347

MM-28347 Enable custom emoji by default for new installs

---

api4/saml.go
api4/team.go
api4/team_test.go
model/client4.go

- These endpoints should not require manage_system instead they should just check `sysconsole_write_auth...` 
- https://mattermost.atlassian.net/browse/MM-28536
- https://mattermost.atlassian.net/browse/MM-28535

[MM-28536] [MM-28535] sysconsole_write_authentication bug fixes 

---

app/role.go

When a role is patched, no websocket event is sent (so we need referesh on webapp).
This PR sends the websocket event and that means you don't need to refresh on front end to see the role take effect.
https://mattermost.atlassian.net/browse/MM-28530

MM-28530 - Changes are not automatically propagated to system console when a permission is added/removed from a role

---

i18n/en.json
jobs/jobs.go

After implementing LDAP certificate authorization, when connecting or searching with invalid or missing certificates. No error is thrown neither on connection nor search.
The real changes are in the related PR. The changes here are in support of that PR.
https://mattermost.atlassian.net/browse/MM-28687
https://github.com/mattermost/enterprise/pull/771

MM-28687:Handle empty returns with invalid certificates 

---

app/notification.go
app/notification_test.go

If we have the "First name trigger mention" setting set, but we don't have a "First Name" set, we start receiving "ghost mentions" (we get the mention, but when we get to the channel, nothing is highlighted as a mention).
The easiest way to reproduce this was using the dot (`.`) or the underscore (`_`), which apparently always trigger the mention. Not sure if there are other characters or compositions that trigger mentions.
https://mattermost.atlassian.net/browse/MM-28447
Fix #15245

[MM-28447] Avoid "ghost mentions" when "First Name" is not set, but "First Name trigger mention" setting is set

---

api4/saml.go
api4/team.go
api4/team_test.go

- Manual cherrypick of #15558 
* MM-28536 User with write-auth should be able to use all saml related endpoints
* MM-28535 allow users with write auth to invalidate pending email invites
* Update api4/team_test.go
* No need for init basic
* Address review comments
* Fix test ordering

[cherry-pick] [MM-28536] [MM-28535] sysconsole_write_authentication bug fixes  

---

model/config.go

Prevents non-system-admins from viewing or updating the LDAP admin filter settings.
https://mattermost.atlassian.net/browse/MM-27523

MM-27523: Remove ability to read/write admin filter settings.

---

build/Jenkinsfile.branch

Add build number to docker tag for cloud-beta releases. This is needed because if the webapp changes but the server doesn't, the new build will use the same server hash and it will update the existing docker tag which could be deployed somewhere. This should make every build make a unique docker tag.

Add build number to docker tag for cloud-beta releases

---

api4/file.go
api4/file_test.go

Add a missing `return` statement in case of an error.
https://mattermost.atlassian.net/browse/MM-28945

[MM-28945] api4/file: add missing return statement

---

i18n/en.json
services/filesstore/s3store.go

When a IAM user is just allowed access to a specific path prefix,
the bucket exists test will fail because that is applicable to the entire bucket.
We modify that check to just list objects under that path prefix and return
on the first non-nil error.
Another consideration was to do a StatObject, but it is only applicable to actual
objects and not at a directory level. Path prefixes are entirely logical and depends
on the underlying implementation. Therefore, ListObjects is a better choice.
https://mattermost.atlassian.net/browse/MM-29033

MM-29033: Modify Test S3 connection to handle path prefix

---

api4/api.go
api4/system_local.go
api4/system_test.go

Adds the ping endpoint required for the `mmctl system version` command to local mode.
https://mattermost.atlassian.net/browse/MM-28630
- [Has mmctl changes](https://github.com/mattermost/mmctl/pull/209)

[MM-28630] Add ping endpoint to local mode

---

model/config.go

Removed `cloud_restrictable` tag for `PluginSettings.Enable` that was causing plugin configuration screens to now show in the System Console in cloud installations 
[MM-29219](https://mattermost.atlassian.net/browse/MM-29219)

Remove `cloud_restrictable` from `PluginSettings.Enabled`

---

app/plugin_install.go
app/plugin_install_test.go

PR fixes a possible panic during plugin installation. The main issue is that `Environment.Activate()` can return both a `nil` manifest and no error in case of an already active plugin. During the installation process this case was not handled and would cause a `nil` dereference panic.
I've added a test to reproduce this: a plugin is installed and activated, then its installation folder is removed. A second attempt to install the same plugin would fail to remove it and de-activate it since the directory would not be found anymore (apparently we don't check for active plugins during installation, but only if the bundle exists). The installation would go ahead but the plugin's activation would fail, returning the `nil` manifest.
https://mattermost.atlassian.net/browse/MM-28420

[MM-28420] Fix possible panic during plugin installation

---

api4/system.go
app/app.go
app/app_iface.go
app/app_test.go
app/opentracing/opentracing_layer.go

Moved two `Srv().Store` calls used for DB health check from `api4/system.go` to `app.go`.
Fixes https://github.com/mattermost/mattermost-server/issues/15742

[GH-15742] Remove direct Store calls from the Api layer for the file api4/system.go

---

i18n/en.json

This is used by SAML library when an xml response has time set
outside the valid range.

[internal]: Added an error string for checking invalid time

---

config/environment.go
config/environment_test.go

This PR adds a check to `reflect.Value`if it is settable, in other words if it is not zero value. In cluster mode we can have at least 2 different versions of MM server running hence 2 different config structs. In order to prevent panics if we receive a undefined value we simply skip it.
https://mattermost.atlassian.net/browse/MM-29215

[MM-29215] config/envrionment: fix a panic where a setting is not defined in model.Config

---

app/post_metadata.go
app/post_metadata_test.go

Add a check to a type casting in `(*App)OverrideIconURLIfEmoji()`.
https://mattermost.atlassian.net/browse/MM-29345

[MM-29345] app/post_metadata: add a check to type casting

---

app/upload.go
app/upload_test.go

PR adds a check to prevent possible inconsistencies in case of parallel upload requests.
While the code was correctly enforcing one request per session at any given time, there was still a case where concurrent requests for the same session could enter the function with an outdated `UploadSession` struct, causing the call to go through without errors.
https://mattermost.atlassian.net/browse/MM-29273

[MM-29273] Fix flaky test: TestUploadDataConcurrent

---

Makefile
go.tools.mod
go.tools.sum
i18n/en.json
model/config.go
model/config_test.go

- (from ticket): We have been using pre-packaging as a means to distribute incident response automatically to cloud, but the version currently available is not final and should not be included in v5.28 proper. Let's remove it, as we intend to list in the marketplace first for on-premise customers.
- Revert of #15608 
- https://mattermost.atlassian.net/browse/MM-29354

MM-29354 - Remove pre-packaged incident response for v5.28

---

api4/team_test.go
model/config.go

- Enable billing by defaulting the feature flag `CloudBilling` to `true` **only for `cloud-ga`** branch. 
- Set `CloudUserLimit` to 10.

Enable cloud billing

---

app/plugin.go

When syncing plugins from the file store on startup, the full path to each plugin is used to fetch the plugins. When using a prefix path on s3, the `a.FileReader` automatically prepends the prefix on every request to s3. The automatic prepending of the prefix results in `my_prefix/my_prefix/antivirus.tar.gz`. This PR makes it so the prefix is stripped if this is the case.
Fixes https://mattermost.atlassian.net/browse/MM-29521

Normalize plugin path when s3 prefix is present

---

model/config.go

Prevents non-system-admins from viewing or updating the SAML admin filter settings.
https://mattermost.atlassian.net/browse/MM-29548

MM-29548: remove ability to update SAML admin filter settings

---

go.tools.mod
go.tools.sum
i18n/en.json
services/filesstore/filesstore.go
services/filesstore/s3store.go

An http.Client is meant as a long-term object to be reused between
consecutive requests. This reduces burden on HTTP servers by reusing TCP connections
and also makes things faster by avoiding the TCP handshake for every single request.
https://mattermost.atlassian.net/browse/MM-29573

MM-29573: Reuse s3 client amongst all requests

---

services/filesstore/s3_overrides.go
services/filesstore/s3store.go

We use a custom transport for minio when an environment variable
indicates that Mattermost is running in cloud.
The transport is used to redirect the request to the S3 endpoint set
in the config. And the scheme is set depending on if S3SSL is set.
A custom credentials provider is needed to return empty credentials
which will be overridden by the service anyways. This is just to allow
the minio client library to work transparently without knowing that
there is something else in the middle intercepting requests.
https://mattermost.atlassian.net/browse/MM-29572

MM-29572: Add Bifrost support to codebase

---

services/telemetry/telemetry_test.go

Some telemetry tests were failing with the final builds because the RUDDER_KEY
and RUDDER_DATAPLANE_URL weren't the placeholders ones. This changes allow the
test to execute properly in that cases by skipping the tests here.

Skipping some telemetry tests on production builds

---

api4/user.go
model/websocket_message.go

In cloud, admins will be able to activate and deactivate users to go over/under the user limit for the free tier. The number of users is important to the front end because it can trigger quite a few different warning banners, so we want the front-end to always be up to date. This PR adds a websocket event for when a users activation state changes, so that the front end can update its user count.
**This doesn't apply directly to this ticket, but would be a logical next bug report I figured I'd fix now.
https://mattermost.atlassian.net/browse/MM-29725

[MM-29725] Add websocket event for when user activation status changes

---

Makefile

v0.7.0 was intended to be released as part of https://github.com/mattermost/mattermost-server/pull/15608, but we only made the change to the `cloud-beta` branch, and not in `master`, so it was lost when `cloud-ga` was later cut directly from `master`.
We can't upgrade directly to v1.0.0 at this time, since there was transient migration code in v0.7.0 to move from the KV store to the SQL store. Once this version successfully updates across the cloud, we'll follow on with prepackaging v1.0.0.
```release-note
Pre-package Incident Response v0.7.0
```
https://mattermost.atlassian.net/browse/MM-29746

bump incident response to v0.7.0 in cloud

---

cmd/mattermost/commands/init.go

Cherry pick of #15683 on release-5.29.
/cc  @sbishel
```release-note
Fixed an issue where mmctl Command Line Tool (Beta) was broken on Mattermost server v5.28.0. [MM-29740](https://mattermost.atlassian.net/browse/MM-29740)
```

Automated cherry pick of #15683

---

app/plugin.go

Cherry pick of #15910 on release-5.29.
```release-note
Fixed an issue where using an s3 file prefix caused plugins to not install properly
```

Automated cherry pick of #15910

---

app/plugin_commands.go
app/plugin_commands_test.go
i18n/en.json
plugin/environment.go
plugin/health_check.go

Cherry pick of #15334 on release-5.29.
/cc  @asimsedhain
```release-note
Added an informative error message to show when a slash command has crashed a plugin, rather than "command not found". Subsequent commands also now show that the plugin has crashed recently.
```

Automated cherry pick of #15334

---

api4/user.go
api4/user_test.go

PR fixes a panic in `api4.saveUserTermsOfService` in case of bad/missing data in the request body.
https://mattermost.atlassian.net/browse/MM-29731

[MM-29731] Fix panic in saveUserTermsOfService

---

app/ldap.go
model/client4.go
model/ldap.go

Fixes a typo in constant name. Updates all references.
https://mattermost.atlassian.net/browse/MM-29547

MM-29522:fix typo in constant name

---

einterfaces/ldap.go
model/config.go
services/telemetry/telemetry.go

Adds a configuration setting for SAML to ignore Guests when Sync'ing LDAP users.
https://mattermost.atlassian.net/browse/MM-28882
https://github.com/mattermost/mattermost-webapp/pull/6750
https://github.com/mattermost/enterprise/pull/801
```release-note
Added configuration setting to ignore Guests when using SAML and synchronizing with LDAP.
```

MM-28882:ignore guest ldap sync

---

model/cloud.go

When updating the Company Information, the stripe implementation expected that unchanged fields would be `nil`, whereas the MM app would send up blank strings, thus resetting those fields.
This PR stops the fields that aren't modified by the MM app from being added to the struct at all, so that they can't be wiped out.
https://mattermost.atlassian.net/browse/MM-29937
```release-note
NONE
```

[MM-29937] Don't allow email and contact name to be updated from the MM app

---

services/filesstore/s3store.go

An AWS path prefix is meant to be an implementation detail
which the calling application should not be aware of. Hence, we should
strip the path prefix when returning objects in a directory
because they anyways get applied while using the other APIs
https://mattermost.atlassian.net/browse/MM-29525

MM-29525: Strip path_prefix from ListDirectory

---

store/storetest/reaction_store.go

We calculate the update date with `time.Now().UnixNano() / int64(time.Millisecond)`. So we need to be sure we have waited that long during testing. 
https://mattermost.atlassian.net/browse/MM-29075
```release-note
NONE
```

[MM-29075] storetest/reaction_store: add sleep before updating entity

---

app/notification_push.go
app/notification_push_test.go

We read the fallback text from message attachments and append that as part
of a push notification.
https://mattermost.atlassian.net/browse/MM-28984
```release-note
NONE
```

MM-28984: Add fallback text to push notification

---

build/release.mk
scripts/download_mmctl_release.sh

It's was including it in the bin folder but when we package we need to include it in the dist/bin so right now the download_mmctl script accepts a second parameter to define the path where the binary is going to be stored
```release-note
NONE
```

MMCTL is not being included in the package

---

app/web_conn.go

Instead of allocating a new slice every time we write a message,
we create a json encoder for a byte buffer and then reset the buffer
every time we write a new message.
This allocates a buffer of a constant size per-connection, but gets rid
of a new allocation for every single write, reducing pressure on GC.
After taking a distrbution of message sizes from a load test, it was seen that
2k is a good enough buffer size within which 98.5% of messages remain.
Taking a look at the alloc profiles for (*webconn).writepump:
- master branch: 8.01% of total allocations totalling 64GB
- with this PR: 4.92% and 10GB.
CPU and Memory graphs
We can see that the new PR has marginally higher memory usage. That's expected. But CPU usage is not very prominently visible at that high a level. The alloc …

MM-29979: make websocket writes zero-alloc

---

model/cloud.go

Added missing field for `LastInvoice` in cloud `Subscription` model. 
Part of https://mattermost.atlassian.net/browse/MM-28214
```release-note
NONE
```

Added Subscription missing field for LastInvoice

---

api4/apitestlib.go
api4/user_test.go
app/bot.go
app/bot_test.go
app/user.go
app/user_test.go
i18n/en.json

We were collapsing all types of user conflict into a single
error message. Fixed it by inspecting the field of the invalidError type
and returning the correct message.
https://mattermost.atlassian.net/browse/MM-30041
```release-note
NONE
```

MM-30041: Return correct error message for user save

---

model/file_info.go

A migration was cherrypicked into 5.29 without the code behind the actual feature (mini previews). This PR adds a field to the struct (still unused, code is in master) to avoid CI issues.
```release-note
NONE
```

Release 5.29 cherrypick fix

---

api4/cloud.go
einterfaces/cloud.go

A change was made to CWS to name invoices in a more user friendly way. Mattermost-server would receive that invoice and then rename it to the old way. This PR along with: https://github.com/mattermost/enterprise/pull/817 will pass along the filename returned by CWS instead of renaming it.
https://mattermost.atlassian.net/browse/MM-30126
```release-note
None
```

[MM-30126] User friendly invoice filenames in-app

---

Makefile
model/config.go
model/config_test.go

Handle the transition from "incident response" to "incident management", automatically enabling the latter now. When the new version of the plugin starts, it will automatically uninstall the old version of the plugin while maintaining backwards compatibility with the underlying data.
```release-note
Pre-package Incident Management v1.1
```
https://mattermost.atlassian.net/browse/MM-30204

prepackage incident management v1.1

---

model/serialized_gen.go
model/user.go
services/cache/lru.go
services/cache/lru_test.go
store/localcachelayer/user_layer.go

We add one more message type to the fast path- profiles in channels. There
are 2 primary reasons for this:
- This is not really a new model type, but just a map of users. And users already use
the fast path. So we can get some more gains without really investing much more code.
- A more important reason is that with the upcoming striped mutex changes, we will get
a higher throughput at the cost of a bit more CPU utilization. The reason being that
since less amount of time will be spent in lock-contention, the CPU is free to do more
stuff. So this change is to counter that increase.
As usual, this gives much better performance than the original decoder.
Micro-benchmark results
```
name               old time/op    new time/op    delta
LRU/UserMap=new-8    16.6µs ± 3%     3.9µs ± 4% …
```

MM-29980: Optimize profilesInChannels cache to fast path

---

config/client.go
model/config.go

Due to some changes in 5.28 around the internal/external link handling in the web app, we broke the newly added [Desktop Managed Resources](https://docs.mattermost.com/install/desktop-managed-resources.html) feature which basically lets non-MM services host stuff at certain routes under the MM server.
Since most paths in the server could be a team URL, the new link handling is correct for anyone not using that feature, so instead of reverting the link handling changes, we're adding a way to the server to manually specify these paths that should not be handled by the web app.
Hopefully I'm setting the correct struct tags on this. I've set it as environment because it affects the web server, and it's not something that would be turned on without making changes to the proxy to intercept …

MM-30090 Add ManagedResourcePaths setting

---

store/sqlstore/file_info_store.go

Add coalesce to get null content as empty string on FileInfo store
[MM-30300](https://mattermost.atlassian.net/browse/MM-30300)
Not needed because is fixing a problem created in master

MM-30300: Add coalesce to get null content as empty string on FileInfo store

---

api4/user.go

This is causing an issue on cloud where if this check fails then the CWS does not complete workspace setup since it thinks the user failed to create when in fact the user was created successfully.
```release-note
None
```

Soft fail on cloud user limit warnings when creating user

---

config/database.go

When an error is encountered initializing the configuration table
of the database on server startup, the database connection is not
closed. This change ensures these connections are cleaned up.
```release-note
Close store database connection on error
```

Close store database connection on error

---

testlib/cluster.go

The messages slice was accessed in a race manner. We protect it
with a mutex
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-29478

MM-29478: Fix race in TestNotifyClusterPluginEvent

---

app/post_metadata_test.go
app/post_test.go
services/imageproxy/atmos_camo.go
services/imageproxy/atmos_camo_test.go
services/imageproxy/imageproxy.go
services/imageproxy/imageproxy_test.go

- We don't bypass protocol relative URLs.
- We don't bypass hostnames with a similar prefix.
https://mattermost.atlassian.net/browse/MM-26425
```release-note
NONE
```

MM-26425: Make URL parsing for image proxy more robust

---

app/notification.go
model/config.go
store/sqlstore/post_store.go
store/storetest/thread_store.go

Participants were not counted properly for collapsed threads, this PR fixes it and adds a config switch that will be used in the future.
Related PR : https://github.com/mattermost/mattermost-server/pull/16234
```release-note
Added config setting 'CollapsedThreads'. Off by default. For future use.
```

Thread hotfix for 5.29

---

cmd/mattermost/commands/server.go
cmd/mattermost/commands/server_test.go

It looks like that `runServer()` does not use the `disableConfigWatch` argument. Removes the unused argument.
No associated ticket found
```release-note
NONE
```

Remove unused argument on runServer

---

build/Jenkinsfile.branch

build: push git commit hash as tags as well
This is useful to debug issues in the images when and if we have
NONE
```release-note
NONE
```

build: push git commit hash as tags as well

---

app/channel_category_test.go

We create a copy of the slice to prevent racy
modification from the hub goroutine.
https://mattermost.atlassian.net/browse/MM-29479
```release-note
NONE
```

MM-29479: Fix racy test TestSidebarCategory

---

jobs/schedulers.go
jobs/schedulers_test.go

We iterate the nextRunTimes slice only after stopping the
scheduler.
And since we are checking the slice 3 times, we split
the test into 3 sub-tests, every time starting a new scheduler
and running the same steps again.
https://mattermost.atlassian.net/browse/MM-29488
```release-note
NONE
```

MM-29488: Fix racy test TestScheduler

---

app/channel_test.go
model/role.go

- We avoid appending to the slice in `(r *Role) IsValidWithoutId`
by just iterating the 2 slices separately.
- We pass deep copies of channels to prevent racy modification.
https://mattermost.atlassian.net/browse/MM-29486
```release-note
NONE
```

MM-29486: Fix racy test TestPatchChannelModeration

---

api4/post_test.go
app/post.go

This lets the client know who deleted the post. This information is stored in the database, but cannot be retrieved from an API endpoint because the API does not return information about deleted post.
The motivation for the change is to improve bridges to other chat platforms, which want to know who performed the deletion, but I can see this being useful in general.
```release-note
In post_deleted websocket event, notify system administrators of the user initiating the deletion.
```
https://mattermost.atlassian.net/browse/MM-30562

[MM-30562] Indicate deleteBy in post_deleted websocket event

---

build/release.mk

That defaults file would be used in the cloud installations to set the
initial values for them
This PR adds to the release process the new cloud defaults configuration file to be used by the cloud installations
https://mattermost.atlassian.net/browse/MM-28883
Here is the EE docker with the new configuration file in the /config folder
```release-note
NONE
```

[MM-28883] Include cloud defaults in the EE release package

---

app/oauth.go
web/handlers.go

Until we investigate the issues we're encountering with nginx ingress not setting the correct HTTP headers this is a temporary fix for OAuth not working.
https://mattermost.atlassian.net/browse/MM-28720
https://github.com/mattermost/mattermost-server/pull/15747
```release-note
NONE
```

[MM-28720] OAuth temporal fix for the cloud branch

---

api4/channel_category_test.go
app/app_iface.go
app/channel.go
app/channel_category.go
app/channel_category_test.go
app/channel_test.go
app/opentracing/opentracing_layer.go
app/slashcommands/command_mute.go
model/channel_member.go
model/channel_sidebar.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/sqlstore/channel_store_categories.go
store/sqlstore/upgrade.go
store/store.go
store/storetest/channel_store.go
store/storetest/channel_store_categories.go
store/storetest/mocks/ChannelStore.go
store/timerlayer/timerlayer.go

A new sidebar feature is muting entire categories at once. Muting a category mutes all channels in it and makes it so that channels moved into it get automatically muted.
Updating the ChannelMembers one-by-one to mute them after muting the category is a bit weird, but we don't have bulk websocket events for updating multiple ChannelMembers at once, and I was worried about mobile compatibility here. Unfortunately, we don't have any way to change the potential websocket events based on client versions, but that would be really nice for something like this.
https://mattermost.atlassian.net/browse/MM-20897
https://github.com/mattermost/mattermost-redux/pull/1286
https://github.com/mattermost/mattermost-webapp/pull/7033
```release-note
Added the ability to mute categories in the new sidebar …
```

MM-20897 Add category muting

---

model/config.go

Adds missing `access` tag to nested struct to grant read and/or write access to the Global Relay config settings per the permissions.
https://mattermost.atlassian.net/browse/MM-29420
```release-note
Fixed bug where permissions did not grant read and/or write access to the Global Relay configuration settings.
```

MM-29420: Adds missing access to the global relay config settings.

---

model/config.go

Removed `cloud_restrictable` from `CloudBilling` and `CloudUserLimit` settings that was causing it to not be returned in the System Console seeing the related bug. 
This was fixed in the `cloud-ga` branch https://github.com/mattermost/mattermost-server/pull/15908 and not enabled in `master`.
[MM-30746](https://mattermost.atlassian.net/browse/MM-30746)
```release-note
NONE
```

Remove `cloud_restrictable` for cloud billing settings

---

Makefile
model/config.go
model/config_test.go
services/telemetry/telemetry.go

A few releases back, we pre-packaged incident _response_ v0.6, cherry-picking those changes into the `cloud-beta` branch for an early rollout. v5.28 and v5.29 did not pre-package incident response, since they were cut just after that commit in `master`, and we had intentions to revisit this prior to v5.30.
Since that time, we renamed the product, released a few more versions, and cherry-picked into `cloud-ga`. All of these changes have been in "production" for a while now, but we need to bring `master` back up-to-date, since a new `cloud` branch is pending release to production but it's still pointing at IR v0.6 instead of IM v1.1.
When IM v1.2 is released, we'll bump the version again, but this commit is important to include in the upcoming release of the `cloud` branch on Tuesday, …

MM-30800: prepackage incident management 1.1

---

app/slashcommands/command_invite_people.go

Change receiver name for (me *InvitePeopleProvider) in app/slashcommands/command_invite_people.go to be more idiomatic
Removed the receiver names as they were not being used anywhere.
JIRA - https://mattermost.atlassian.net/browse/MM-30705
Issue - Fixes #16299 
```release-note
NONE
```

MM-30705: Change to idiomatic receiver names for InvitePeopleProvider

---

app/post_metadata.go
app/post_metadata_test.go

As discussed in SET, we're reverting this for the time being because of some conflicts with other integrations. 
https://mattermost.atlassian.net/browse/MM-29224
```release-note
NONE
```

Revert "[MM-29224] Fix bug where markdown image link doesn't show preview (#15862)

---

app/notification.go
app/notification_test.go
store/store.go

Remove unneeded Err field in the store result struct.
This is part of the clean up after the AppError removal from the store.

Remove unneeded Err field in the store result struct

---

app/config.go
app/server.go

A cluster changed listener always runs in a separate goroutine.
This causes a race condition when a new member gets added in the cluster.
We fix it by accessing the value atomically.
I tried to write a test for this, but it wasn't triggering at all.
The best way is to just start the server with cluster enabled in race mode,
and verify that the race doesn't happen.
https://mattermost.atlassian.net/browse/MM-30319
```release-notes
NONE
```

MM-30319: Fix race in ensureAsymmetricSigningKey

---

app/slashcommands/command_channel_purpose.go

JIRA - https://mattermost.atlassian.net/browse/MM-30819
Issue - Fixes #16331
```release-note
NONE
```

MM-30819: Change to idiomatic receiver names for slashcommands.PurposeProvider

---

app/slashcommands/command_leave.go

JIRA - https://mattermost.atlassian.net/browse/MM-30820
Issue - Fixes #16332
```release-note
NONE
```

MM-30820: Change to idiomatic receiver names for slashcommands.LeaveProvider

---

model/push_response.go

JIRA - https://mattermost.atlassian.net/browse/MM-30823
Issue - Fixes #16335
```release-note
NONE
```

MM-30823: Change to idiomatic receiver names for model.PushResponse

---

api4/config.go

5.30 introduces new System Roles (i.e. System Manager) that by default don't have read/write permissions to `ExperimentalSettings`. For cloud servers, when getting and updating the config, we were checking `ExperimentalSettings.RestrictedAdmin` to filter out `cloud_restrictable` settings. This was causing a panic for these new roles. See related bug. 
This PR drops the check for `RestrictedAdmin` and just filters `cloud_restrictable` for any cloud server to avoid these cases where roles can be granted/removed the Experimental Settings by admins in the System Console. 
[MM-30900](https://mattermost.atlassian.net/browse/MM-30900)
```release-note
NONE
```

MM-30900 - Dropped condition of RestrictAdmin for filtering cloud_restrictable

---

app/slashcommands/command_loadtest.go

JIRA - https://mattermost.atlassian.net/browse/MM-30816
Issue - Fixes #16328
```release-note
NONE
```

MM-30816: Change to idiomatic receiver names for slashcommands.LoadTestProvider

---

app/slashcommands/command_msg.go

JIRA - https://mattermost.atlassian.net/browse/MM-30821
Issue - Fixes #16333
```release-note
NONE
```

MM-30821: Change to idiomatic receiver names for slashcommands.msgProvider

---

app/compliance.go
model/compliance.go

We pass a copy of the compliance object to the goroutine
https://mattermost.atlassian.net/browse/MM-30862
```release-note
NONE
```

MM-30862: Fix racy test RunComplianceReports

---

app/slashcommands/command_away.go

Updated receiver name for (me *AwayProvider) to be more idiomatic.
Fixes: #16366 
JIRA Ticket: https://mattermost.atlassian.net/browse/MM-30907
```release-note
NONE
```

[MM-30907]: Change receiver name for (me *AwayProvider) in app/slashcommands/command_away.go to be more idiomatic.

---

app/product_notices.go
app/product_notices_test.go

if user preference doesn't exist - don't throw error, just fail notice check
https://mattermost.atlassian.net/browse/MM-30918
```release-note
NONE
```

MM-30918 Fix product notice check when user setting is missing

---

store/searchlayer/layer.go
store/searchlayer/layer_test.go
store/searchlayer/post_layer.go

Fixes a race condition due to a non synchronized access of a critical section, in our case updating the config of the search layer. 
Solution: synchronise access via making config to be an `atomic.Value`
https://mattermost.atlassian.net/browse/MM-30868
```release-note
Fix race condition when updating config on search layer.
```

Syncronize access when updating config on search layer

---

mlog/log.go
mlog/log_test.go
mlog/testing.go

Makes mlogger atomic on its basic operation. Started investigating the ticket bellow and it seems that mlogger has many critical sections that a race can happen. This PR synchronizes access to `logger.logrLogger`.
https://mattermost.atlassian.net/browse/MM-30869
```release-note
Make mlogger atomic
```

Make mlogger atomic

---

app/enterprise.go
app/enterprise_test.go

ReEnables SAML2 library as the only library used, requires Enterprise related changes.
https://mattermost.atlassian.net/browse/MM-30802
```release-note
Enable goSAML2 library as the only supported SAML Library.
```
https://github.com/mattermost/enterprise/pull/832

MM-30802: Enable GoSAML2 library support

---

app/enterprise.go
app/enterprise_test.go

* update saml to always use new library
* remove unused variable
* Update tests
(cherry picked from commit e014de0a6599063627b7183d59733afc0628dbdd)
```release-note
Enable goSAML2 library as the only supported SAML Library.
```

MM-30802: Enable GoSAML2 library support (#16361)

---

app/slashcommands/command_logout.go

Updated receiver name for (me *LogoutProvider) to be more idiomatic. 
Fixes: #16375   
JIRA: https://mattermost.atlassian.net/browse/MM-30916
```release-note
NONE
```

[MM-30916]: Change receiver name for (me *LogoutProvider) in app/slashcommands/command_logout.go to be more idiomatic.

---

app/busy.go
app/busy_test.go

A time.AfterFunc runs the function in its own goroutine. So we need
to guard that with a mutex too.
https://mattermost.atlassian.net/browse/MM-30987
```release-note
NONE
```

MM-30987- Fix race in setting clearNotify in Busy

---

app/slashcommands/command_invite.go

Updated receiver name for (me *InviteProvider) to be more idiomatic. 
Fixes: #16373  
JIRA: https://mattermost.atlassian.net/browse/MM-30914
```release-note
NONE
```

[MM-30914]: Change receiver name for (me *InviteProvider) in app/slashcommands/command_invite.go to be more idiomatic.

---

app/server.go
model/utils.go
scripts/test.sh

The translateFunc is a global variable which was unguarded. This wasn't a problem from the code,
but when consecutive tests were run, one test would still be writing to it while the other would be reading.
We wrap the write with a sync.Once so that consecutive tests don't write to it again.
https://mattermost.atlassian.net/browse/MM-30988
```release-note
NONE
```

MM-30988 - Fix racy test ServerSystemdNotification

---

model/manifest.go
model/manifest_test.go

Plugins without a name defined in the manifest are tricky to display in the webapp. This PR changes `IsValid` to enforce a name. Right now `IsValid` is not used, so this changes doesn't have a direct impact.
https://mattermost.atlassian.net/browse/MM-30981
```release-note
NONE
```

[MM-30981] Require Plugin name in manifest

---

cmd/mattermost/commands/channel.go
cmd/mattermost/commands/init.go
cmd/mattermost/commands/permissions.go
cmd/mattermost/commands/server.go
cmd/mattermost/commands/version.go
config/database.go
config/store.go

This change addresses a few issues where config stores were not
properly closed when an error was encountered on server startup.
This could result in leaked database connections when dealing with
a database config store.
Fixes https://mattermost.atlassian.net/browse/MM-30345
```release-note
Cleanup config store on server initialization errors
```

Additional Config Store Cleanup

---

model/marketplace_plugin.go

https://github.com/mattermost/mattermost-marketplace/pull/137 and other PRs added additional filter fields to the Marketplace. This PR adds `Hosting`, `AuthorType`, `ReleaseStage` and `Enterprise` to the Marketplace response send to the client. 
On the Marketplace some of these fields are typed. I opted for not doing this here as the MM server does just passes the data and doesn't look into it. 1/5
https://mattermost.atlassian.net/browse/MM-30982
```release-note
NONE
```

[MM-30982] Add filter metadata to Marketplace response

---

testlib/helper.go

Tests can be run from other tools using a different base path.
We need to respect the MM_SERVER_PATH variable for that.
https://mattermost.atlassian.net/browse/MM-31082
```release-note
NONE
```

MM-31082: Use a base path for test assets

---

config/database.go

When configuration is backed by a database, a separate pool of
connections is used for access from the primary database. This
change sets sensible config DB connection limits in order to
reduce database resource usage at scale.
Fixes https://mattermost.atlassian.net/browse/MM-31158
```release-note
NONE
```

Limit configuration database connections

---

go.mod
go.sum
vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
vendor/modules.txt

YouTube previews are currently broken sporadically on different servers because they started sending HTML with the OpenGraph metadata in the wrong place as well as some other invalid bits. It seems like it's a rolling change being propagated through all their servers since previews went from working on community to working sometimes to not working at all. Their HTML is actually invalid now, so I assume they'll fix it, but I've forked the OpenGraph library to be more relaxed.
The changes to the fork are here: https://github.com/dyatlov/go-opengraph/compare/master...hmhealey:master
In particular, it's these lines: https://github.com/dyatlov/go-opengraph/compare/master...hmhealey:master#diff-47ab48a2396307d97df39eabbd77905aad8cb1b808acfcab8a7a3b5523f08a6fL122-L124 …

MM-31171 Fork OpenGraph library to handle bad HTML from YouTube

---

app/notification.go
app/notification_push.go

In https://github.com/mattermost/mattermost-server/pull/16089,
we added logic to modify the notification text in the presence
of fallback text.
Unfortunately, that created a race condition during publishing
the post via websockets. To fix this, we create a clone of the post
before sending it off for push notifications.
https://mattermost.atlassian.net/browse/MM-31323
```release-note
NONE
```

MM-31323: Fix racy test TestHandleCommandResponsePost

---

store/searchlayer/user_layer.go

As part of the `UserStore` error migration, we started returning `error` from the `searchlayer`, inadvertently returning an empty `AppError` instance in the user autocomplete function, that was then caught as `!= nil` by the caller, causing a panic.
`AppError` strikes yet again.
https://mattermost.atlassian.net/browse/MM-31357
```release-note
NONE
```

[MM-31357] Avoid returning empty appError when autocompleting users

---

app/plugin_test.go

We shutdown all plugins prior to checking the log buffer
so that there are no active plugins writing to the buffer
when we read the contents.
https://mattermost.atlassian.net/browse/MM-31324
```release-note
NONE
```

MM-3124: Fix racy test TestPluginPanicLogs

---

web/oauth.go
web/oauth_test.go

The return statement after setting c.InvalidParam was missing
https://mattermost.atlassian.net/browse/MM-30826
```release-note
NONE
```

MM-30826: Sentry crash: nil deference in model.AuthorizeRequest

---

build/docker-compose.common.yml

https://mattermost.atlassian.net/browse/MM-28549
```release-notes
Mattermost does not support Postgres 9.4 anymore. The minimum
required version for Postgres will be 10.
```

MM-28549: Bump up postgres version

---

app/oauth.go
web/handlers.go

- This reverts commit ee931f5a12e4c39dede8396e191ed5cc2f2d7d67. Fixes oauth on servers running under a subpath
- https://mattermost.atlassian.net/browse/MM-31394
```release-note
NONE
```

[MM-31394] Revert "Temporary fix for oauth on cloud beta (#16281)"

---

model/channel.go
store/sqlstore/upgrade.go

This PR adds a new flag to the Channels table `Shared`.  
This is in support of the upcoming Shared Channels feature and is needed to efficiently determine if a channel needs to sync after Post added/edited/deleted.  Values may be nil, false, true.  `(*Channel).IsShared` has been added as well.
The flag will not be set or queried until the Shared Channels feature branch is merged.
https://mattermost.atlassian.net/browse/MM-31401
```release-note
NONE
```

MM-31401  Add Shared flag to Channels table

---

store/sqlstore/upgrade.go

Since both mentioned PRs were not included in 5.31 I've bumped the schema version for the DB upgrade steps so that those happen in the expected version.

Update db schema version for MM-31401 and MM-27312

---

api4/apitestlib.go
app/helper_test.go
app/slashcommands/helper_test.go
migrations/helper_test.go
store/sqlstore/upgrade.go
testlib/helper.go

We should use `mlog.Critical` if we are going to call `panic` or `os.Exit(>0)`
https://mattermost.atlassian.net/browse/MM-31398
```release-note
NONE
```

[MM-31398] upgrade error level to critical in case of panic or os.Exit

---

app/server.go
services/telemetry/telemetry.go
services/telemetry/telemetry_test.go
store/sqlstore/store.go
store/sqlstore/store_test.go
store/store.go
store/storetest/mocks/Store.go
store/storetest/store.go

To keep conformance with our failing fast and obvious philosophy,
we add a check to prevent Mattermost server from starting
if the postgres version is below 10.0.
This gives customers a chance to upgrade their database before upgrading
their Mattermost version, than to run into weird compatibility issues
after they have finished the upgrade.
https://mattermost.atlassian.net/browse/MM-31356
```release-note
NONE
```

MM-31356: Add a minimum required version check for Postgres

---

go.mod
go.sum
vendor/modules.txt

The package paths were changed. Therefore, go mod tidy
on master failed with:
```
go: finding module for package github.com/hmhealey/go-opengraph/opengraph
go: found github.com/hmhealey/go-opengraph/opengraph in github.com/hmhealey/go-opengraph v0.0.0-20201209151214-f2d823730dba
go: github.com/hmhealey/go-opengraph@v0.0.0-20201209151214-f2d823730dba used for two different module paths (github.com/dyatlov/go-opengraph and github.com/hmhealey/go-opengraph)
```
https://mattermost.atlassian.net/browse/MM-31511
```release-note
NONE
```

MM-31511: Fix incorrect replace repo

---

app/server.go

Add logging to Print Golang Version before server
Fixes: https://github.com/mattermost/mattermost-server/issues/16609
JIRA: https://mattermost.atlassian.net/browse/MM-31555
```release-note
NONE
```

[MM-31555] Print golang version on server startup

---

app/oauth.go
web/handlers.go

- This reverts commit ee931f5. Fixes oauth on servers running under a subpath.
- Cherry-pick of above fix onto the release-5.31 branch.
- Original ticket https://mattermost.atlassian.net/browse/MM-31394
- Related PR https://github.com/mattermost/mattermost-server/pull/16567
```release-note
NONE
```

cherry-pick #16567: revert "Temporary fix for oauth on cloud beta"

---

.circleci/config.yml
.gitlab-ci.yml

https://mattermost.atlassian.net/browse/MM-31618
```release-note
NONE
```

MM-31618: Bump golangci to 1.33.2

---

config/file_test.go

Since this test had t.Parallel set, it would run the sub-tests
in parallel. The issue was that the same file path was being written
from the 2 sub-tests causing duplicate firing of the event handlers.
This would cause a race where the store would be closing, and at the same time,
an event handler would fire, trying to read the fs.watcher field.
Having two separate file paths resolves this.
https://mattermost.atlassian.net/browse/MM-31369
```release-note
NONE
```

MM-31369: Fix racy test TestFileStoreWatcher

---

app/server.go
config/client.go
model/feature_flags.go
services/telemetry/telemetry.go

We use a proper feature flag for toggling this feature.

MM-30836: Use feature flags for RemoteClusterService

---

app/file.go
services/filesstore/filesstore.go
services/filesstore/filesstore_test.go
services/filesstore/localstore.go
services/filesstore/mocks/FileBackend.go
services/filesstore/s3store.go

This PR removes instances of pointers
to slices in the codebase. There are some other instances in app/import_functions.go
but that's necessary to prevent empty arrays from appearing in the JSON output.
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-31061

MM-31061: Remove pointers to slice

---

model/config.go
tests/test-config.json

https://mattermost.atlassian.net/browse/MM-31715
```release-notes
The UseExperimentalGossip field under ClusterSettings is now true by default.
This means that new installations will use the gossip protocol for cluster communication.
There will be no changes to existing installations.
The Gossip protocol is now considered to be in General Availability and is the recommended clustering mode.
```

MM-31715: Flip ExperimentalGossip to be true by default

---

web/context.go

It turns out `mlog.Debug(msg, fields...)` is different than `mlog.Log(mlog.DebugLevel, msg, fields...)`. 🤦 
https://mattermost.atlassian.net/browse/MM-31776
```release-note
NONE
```

[MM-31776] explicitly call level functions for mlog

---

store/sqlstore/post_store.go
store/storetest/post_store.go

[AnalyticsPostCount](https://github.com/mattermost/mattermost-server/blob/d9e8402dc27bd11137e9301cf14eaf01d2786efd/store/sqlstore/post_store.go#L1513-L1541) unconditionally joins on the `Channels` table even when not filtering to a team.
This is a proposal to stop doing this, reducing this to a simple index query when no team or hashtag/file requirement is specified. Note that this is technically a subtle semantic difference, since orphaned posts (from deleted or invalid channel ids) are currently excluded. I submit the benefits outweigh the technical differences here, but would love some consideration on this front lest my assumptions are invalid.
For clarity, these improvements only apply for certain invocation of `AnalyticsPostCount`, namely:
* On startup, during warn metrics: …

MM-30892: Avoid unnecessary table scan in AnalyticsPostCount.

---

Makefile
go.mod

There is a race between go mod tidy and go mod vendor
due to https://github.com/golang/go/issues/37376.
However, if we give priority to go mod vendor, then
gopls complains of inconsistent vendoring. We make go mod tidy happy
as it's a more commonly used command than go mod vendor,
and is a common problem faced by other devs too

Fix go.mod to give priority to go mod tidy

---

store/sqlstore/channel_store_categories.go
store/storetest/channel_store_categories.go

This fixes a strange bug where sometimes a user's custom categories would lose all the channels in them.
It turns out that this happens because of the code that removes the sidebar data when a user leaves or is removed from a team while they have a DM channel in a custom category on that team. This also only affected Postgres, so we weren't going to find it on community even if we did join/leave teams more often.
The reason this happened is because of the DELETE FROM query used to delete the SIdebarChannels, although I'm honestly not sure why. If I ran that query myself, it would reproduce the issue, but if I changed it to a SELECT with the same JOIN and WHERE, it only returned rows on the team that the user would've been leaving. I'm not entirely sure it has to do with a DM channel in …

MM-30314 Don't delete all SidebarChannels when removed from team

---

app/app_iface.go
app/channel_share.go
app/opentracing/opentracing_layer.go
app/slashcommands/command_share.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/shared_channel_store.go
store/store.go
store/storetest/mocks/SharedChannelStore.go
store/storetest/shared_channel_store.go
store/timerlayer/timerlayer.go

We check the store if the remote already exists in the DB.
If it does, we return an error.
https://mattermost.atlassian.net/browse/MM-32033
```release-note
NONE
```

MM-32033: Check if a remote is already added before inviting

---

api4/bot.go
api4/compliance.go
api4/emoji.go
api4/file.go
api4/post.go
api4/team.go
api4/user.go
web/oauth.go

We were incorrectly setting the cache control to public
when it should be rather private.
https://mattermost.atlassian.net/browse/MM-31721
```release-notes
Fix Cache-Control headers to instruct that responses may only be cached
on browsers.
```

MM-31721: Fix Cache-Control directives

---

app/product_notices.go

As mentioned in the documentation:
> Truncate operates on the time as an absolute duration since the zero time;
it does not operate on the presentation form of the time. Thus,
Truncate(Hour) may return a time with a non-zero minute, depending on the
time's Location.
As a result, truncating for anything more than an hour is buggy and should
not be done. The correct way is to construct the date object using the
day, month and year.
https://mattermost.atlassian.net/browse/MM-31353
```release-notes
Fixed a bug in product notices where a date constraint might
fail to match, and would lead to the notice not being fetched
```

MM-31353: Fix incorrect time truncation logic

---

api4/api.go
api4/export.go
api4/export_local.go
api4/export_test.go
app/app_iface.go
app/export.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/client4.go
web/params.go

PR implements a new `/exports` API endpoint to list/delete/download export files.
https://mattermost.atlassian.net/browse/MM-31249
```release-note
NONE
```
https://github.com/mattermost/mattermost-api-reference/pull/597

[MM-31249] Add /exports API endpoint

---

app/helper_test.go
app/post_test.go
app/reaction_test.go
app/server.go
app/shared_channel_notifier_test.go
app/shared_channel_service_iface.go
app/slashcommands/command_share.go
app/slashcommands/command_share_test.go
app/slashcommands/helper_test.go
testlib/cluster.go

Send websocket notification when channels shared state changes.
https://mattermost.atlassian.net/browse/MM-32119
```release-note
NONE
```
*Note* We probably need to create another ticket for sending the system message that notifies that the channel is now shared or unshared.

Send websocket notification when shared channel state changes

---

app/shared_channel_service_iface.go
app/slashcommands/command_share.go
services/sharedchannel/channelinvite.go

When creating a channel mirror on remote, respect the home channel's type
https://mattermost.atlassian.net/browse/MM-32050
```release-note
NONE
```

When inviting a remote send over the home channel type

---

app/product_notices.go
app/product_notices_test.go

Product Notices should ignore server version for cloud instances.
https://mattermost.atlassian.net/browse/MM-32252
```release-note
NONE
```

MM-32252 Ignore serverversion condition on cloud for in-product notices

---

go.tools.mod
go.tools.sum
i18n/en.json
model/config.go
services/telemetry/telemetry.go
store/sqlstore/store.go
store/sqlstore/store_test.go
store/storetest/settings.go

https://mattermost.atlassian.net/browse/MM-31391
```release-note
A new config field called `ConnMaxIdleTimeMilliseconds` was added to `DatabaseSettings` which allows to control the maximum time a database connection can remain idle. The default value is set to 5 minutes.
```
Closes https://github.com/mattermost/mattermost-server/issues/16601

MM-31391: Add max connection idle timeout to config

---

api4/apitestlib.go
api4/config_test.go
app/config.go
app/options.go
app/server.go
app/server_test.go
cmd/mattermost/commands/config.go
cmd/mattermost/commands/config_test.go
cmd/mattermost/commands/db.go
cmd/mattermost/commands/init.go
cmd/mattermost/commands/jobserver.go
cmd/mattermost/commands/plugin.go
cmd/mattermost/commands/plugin_test.go
cmd/mattermost/commands/server.go
config/common_test.go
config/database_test.go
config/file_test.go
config/migrate.go
config/migrate_test.go
config/store.go
config/store_test.go
services/mailservice/mail_test.go

PR fixes an issue with `config.json` getting sporadically reset by adding support for read-only config stores which I enabled for CLI commands (with some exceptions, e.g. `config` command). 
https://mattermost.atlassian.net/browse/MM-32234
```release-note
Fixed an issue where config.json was sporadically getting reset upon CLI command execution.
```

[MM-32234] Fix config.json getting reset

---

Makefile

The Makefile has a command to validate Go version.
We bump it up to require 1.15.
```release-note
NONE
```

Bump up minimum required Go version

---

api4/apitestlib.go
api4/config_test.go
app/config.go
app/options.go
app/server.go
app/server_test.go
cmd/mattermost/commands/config.go
cmd/mattermost/commands/config_test.go
cmd/mattermost/commands/init.go
cmd/mattermost/commands/jobserver.go
cmd/mattermost/commands/plugin.go
cmd/mattermost/commands/plugin_test.go
cmd/mattermost/commands/server.go
config/common_test.go
config/database_test.go
config/file_test.go
config/migrate.go
config/migrate_test.go
config/store.go
config/store_test.go
services/mailservice/mail_test.go

Cherrypick for MM-32234 on 5.31
```release-note
Fixed an issue where config.json was sporadically getting reset upon CLI command execution.
```

Cherrypick for MM-32234 on 5.31

---

app/notification.go
app/post.go

When marking a channel post unread, if there is a rootID, we do some extra checks. Among those checks, is counting the thread mentions. We used to check the team at the beginning of this function, but since DMs don't have a team, it failed. We moved the team check after the DM check to avoid this error.
https://mattermost.atlassian.net/browse/MM-32253
```release-note
NONE
```

[MM-32253] Fix "Cannot mark unread a DM message in a thread"

---

store/sqlstore/post_store.go

At this point, we were checking for `sql.ErrNoRows` instead of a `NotFoundErr`. Since the underlying function (`Thread().Get()`) is already transforming the ErrNoRows into a NotFoundErr, this check was failing.
This mainly caused that permanent deleting users or channels failed on previous versions (e.g. 5.29.1).
https://mattermost.atlassian.net/browse/MM-31731
```release-note
NONE
```

[MM-31731] Fix cleanup threads to properly handle not found errors

---

cmd/mattermost/commands/server.go

We introduce a panic pass-through layer which logs
the panic at a critical level before crashing.
This helps customers to easily get the panic output
in their logging infrastructure, rather than having to
go through journaltctl logs.
https://mattermost.atlassian.net/browse/MM-5639
```release-note
Server crashes due to runtime panics are now captured
as a log line.
```

MM-5639: Write panic to log on the way out

---

services/sharedchannel/channelinvite.go
services/sharedchannel/mock_AppIface_test.go
services/sharedchannel/service.go

When accepting a channel invite a new channel is created. If the subsequent creation of `SharedChannelRemote` fails then the new channel is deleted.
Previously the channel was soft deleted.   This PR changes that to permanent delete the channel otherwise a retry will fail due to id collision.
**To be merged with feature branch**
https://mattermost.atlassian.net/browse/MM-32553
```release-note
NONE
```

MM-32553 hard delete channel when channel invite fails

---

store/sqlstore/channel_store_categories.go
store/storetest/channel_store_categories.go

A 5.31 version of https://github.com/mattermost/mattermost-server/pull/16692. The only change from the original PR is that `SqlSupplier` has been renamed to `SqlStore` on master.
Original PR: https://github.com/mattermost/mattermost-server/pull/16692
https://mattermost.atlassian.net/browse/MM-30314
```release-note
Fixed bug where channels would sometimes be removed from custom categories when a user leaves a team
```

MM-30314 Don't delete all SidebarChannels when removed from team (5.31)

---

config/common_test.go
config/database_test.go
config/file_test.go
config/store.go

PR fixes an issue where the `FeatureFlags` section of the config was getting written back to the store even when `persistFeatureFlags = false` by adding to `loadLockedWithOld()` the same check present in `Set()` to avoid persisting the change.
https://mattermost.atlassian.net/browse/MM-32389
```release-note
Fixed FeatureFlags section erroneously getting written to config.
```

[MM-32389] Fix FeatureFlags section erroneously getting written to config

---

app/app_iface.go
app/import_functions.go
app/opentracing/opentracing_layer.go
app/user.go

- Sends a WebSocket event when `plugin.UpdateUser` is called so it is updated immediately for all the users.
```release-note
- UserUpdate WebSocket Event is now broadcast by 2 more APIs - plugin.UpdateUser and ConvertBotToUser
- Change in a User's NotifyProps during the user import process will not send an email notification. This is done to make it consistent with other parts of the import process where change in user's attributes would also not send any notifications.
```

Send user updated websocket event on plugin.UpdateUser

---

config/file_test.go

PR fixes a race condition occurring in `TestFileStoreWatcherEmitter/enabled`.
The race is triggered by the underlying file (inotify) watcher receiving two `WRITE` events at the same time.
This in turn means spawning two callback goroutines doing the same thing, racing to a finish and eventually writing/reading the `fs.watcher` concurrently.
The reason `ioutil.WriteFile` causes this odd behaviour seems to lie in the use of the `os.O_TRUNC` flag when opening the file.
I've tried using a simple `os.OpenFile` with `os.O_WRONLY` + a `file.Write` (essentially decomposing what `ioutil.WriteFile` does but without `os.O_TRUNC`) and I cannot reproduce the duplicate event any longer. I am guessing the `os.O_TRUNC` is causing an additional write at the OS level. …

[MM-31369] Fix racy TestFileStoreWatcherEmitter/enabled

---

store/storetest/scheme_store.go

There is a potential collision with our team reserved words on the scheme tests when generating team Names. We can have a name that starts with `mfa` which is a reserved word.
https://mattermost.atlassian.net/browse/MM-32236
-->
```release-note
NONE
```

Avoid possible false possitives when generating team names

---

app/app_iface.go
app/opentracing/opentracing_layer.go
app/user.go
app/user_test.go
cmd/mattermost/commands/user.go

During user creation via CLI, we would create the user,
but pass the user ID instead when updating the roles.
This falls into the category of read-after-write within a single request.
We fix this by passing the already created user and
directly update the roles.
https://mattermost.atlassian.net/browse/MM-32471
```release-note
NONE
```

MM-32471: Use created user to update roles

---

api4/cloud.go

This PR removes the session required from the /subscription/stats so it can be used to retrieve subscription information when users try to join a workspace via the invitation link and then decide if the user can join or not based on the stats information
https://mattermost.atlassian.net/browse/MM-31503
```release-note
Removed session requered restriction from, GET api/v4/subscription/stats
```

MM31503 - screen to restrict access because workspace capacity

---

api4/channel.go
api4/channel_local.go
api4/channel_test.go

Currently `mmctl channel move someotherteam teamname:channelname` does not allow moving private channels. The error message only mentions direct message and group message channels that cannot be moved:
https://github.com/mattermost/mattermost-server/blob/15037a510a5da29bf16badb5ae4e6c69ee6fe946/i18n/en.json#L339-L340
While not being able to move direct message and group message channels makes sense, the same should not apply to private channels.
None
```release-note
Fixed an issue where `mmctl channel move` did not allow moving private channels.
```

Allow 'mmctl channel move' to move private channels

---

go.mod

`SetConnMaxIdleTime` was added in go 1.15 so we need to upgrade it in the module.
This method is being used [here](https://github.com/mattermost/mattermost-server/blob/2846ad9f934c72109976a118e7336e26c33aeb43/store/sqlstore/store.go#L271)
NONE
```release-note
NONE
```

Set required go version to 1.15

---

go.mod
store/sqlstore/user_store.go
vendor/golang.org/x/sync/AUTHORS
vendor/golang.org/x/sync/CONTRIBUTORS
vendor/golang.org/x/sync/LICENSE
vendor/golang.org/x/sync/PATENTS
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/modules.txt

Migrate channel to waitgroup for access the store in parallel.
This is a proof of concept of something that can be end up being a campaign to migrate all the cases that still use channels. We talk about this a long time ago, but never was done.
[MM-32865](https://mattermost.atlassian.net/browse/MM-32865)
```release-note
NONE
```

Migrate channel to waitgroup for access the store in parallel

---

store/sqlstore/context.go
store/sqlstore/team_store.go
store/sqlstore/user_store.go

We add a method in *SqlStore that returns the correct DB handle
depending on the context.
https://mattermost.atlassian.net/browse/MM-32893
```release-note
NONE
```

MM-32893: Refactor the getting of DB handle

---

Makefile

Enable config telemetry check in `Makefile`.
```release-note
NONE
```

add config telemetry check to vet tool

---

store/sqlstore/store.go
store/sqlstore/store_test.go

Close any opened searchReplicas on store close.
N/A
```release-note
* Close searchReplicas on store.Close()
```

Close search replicas on store close

---

app/server.go

Sometimes we fail to remove local socket file (e.g. when server crashes). In such cases if we detect that the file already exists, we simply remove it and continue.
https://mattermost.atlassian.net/browse/MM-32521
```release-note
NONE
```

[MM-32521] remove local socket file if it already exists

---

app/product_notices.go

Use `*Server.SearchEngine` instead of `*App.SearchEngine` for the `nil` check.
```release-note
NONE
```

app/product_notices: check if server search engine is nil

---

app/notification.go

When a push notification is not sent because of a user's preferences, a log message is written noting this. Currently, the message is written at `WARN` level. Since this is expected behavior, however, this is an inappropriate log level for the message. This changes the log level for these messages to `DEBUG`.
```release-note
NONE
```

Log intentionally unsent notifications as DEBUG

---

services/searchengine/bleveengine/bleve.go

Only log update conf when there is an actual change in the `BleveSettings`.
https://mattermost.atlassian.net/browse/MM-32348
```release-note
NONE
```

[MM-32348] services/bleve: only log update conf when there is an actual change

---

.circleci/config.yml

When the server tries to include a version of the web app that hasn't been built and uploaded to S3 yet, it falls back to building the web app itself. The process for that hasn't been updated in quite a while, and that's causing problems particularly because the Docker image used for building is a really old one that uses Node 8.
This upgrades to match the latest one from the web app repo, and it also increases the size of the runner to fix an out of memory error that would happen without it.
https://mattermost.atlassian.net/browse/MM-33299
```release-note
NONE
```

Update webapp build image

---

app/channel_category.go
app/team.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store_categories.go
store/store.go
store/storetest/channel_store_categories.go
store/storetest/mocks/ChannelStore.go
store/timerlayer/timerlayer.go

PR removes the need for `app.waitForSidebarCategories()` by making `ChannelStore.createInitialSidebarCategories()` return what it created instead of querying categories (from replica) through `GetSidebarCategories()`.
Interestingly `GetSidebarCategories()` was already querying from master so I am not sure why `app.waitForSidebarCategories()` was ever needed. 
https://mattermost.atlassian.net/browse/MM-32621
```release-note
NONE
```

[MM-32621] Remove app.waitForSidebarCategories

---

store/sqlstore/channel_store_categories.go

PR fixes `GetSidebarCategories()` from failing on db replicas. Now I understand why it was using master before :)
It was running everything in a transaction which isn't going to work on read-only replicas. To avoid code duplication I've added a small interface which makes `getSidebarCategoriesT` accept both transactions and regular db handlers.
https://mattermost.atlassian.net/browse/MM-33333
```release-note
NONE
```

[MM-33333] Fix GetSidebarCategories() failing on db replicas

---

db/migrations/bindata.go
db/migrations/mysql/000003_create_cluster_discovery.down.sql
db/migrations/mysql/000003_create_cluster_discovery.up.sql
db/migrations/postgres/000002_create_team_members.down.sql
db/migrations/postgres/000003_create_cluster_discovery.down.sql
db/migrations/postgres/000003_create_cluster_discovery.up.sql

implements: https://mattermost.atlassian.net/browse/MM-33062
https://mattermost.atlassian.net/browse/MM-33062
```release-note
* Moves ClusterDiscovery gorp driven migrations to schema-based migrations
```

Move cluster discovery table over to new schema migrations

---

app/web_conn.go
app/web_hub_test.go

There would be an edge case where an epoll HUP event
would occur at the same time as a connection close event,
and both would race to close the connection.
We fix this by enclosing the Close method with a sync.Once
thereby guaranteeing idempotency.
https://mattermost.atlassian.net/browse/MM-33233
```release-notes
Fixed a race condition which would crash the app server due
to improper handling of websocket closing.
```

MM-33233: Fix double close of webconn pump

---

model/post.go
scripts/mattermost-mysql-5.0.sql
store/sqlstore/upgrade.go

This migration was reverted in https://github.com/mattermost/mattermost-server/pull/16908 for performance reasons. We diverged from cloud since they had already applied the changes by the time we decided to revert. Still we should not go ahead with this migration on on-prem releases.
```release-note
NONE
```

Revert schema change

---

app/feature_flags.go
config/feature_flags.go

Three things in this PR:
1. Add some cloud attributes to the feature flags so that we can use those to isolate treatments.
2. Allow non-cloud servers to use the split.io feature flag management. Primary motivator there is allowing our test servers to use split.io for feature flags even if they don't have a cloud license.
3. Add a bit more debug logs to feature flags.
```release-note
Add attributes to split.io feature flags
```

Add cloud attributes to feature flags and allow non-cloud servers to use split.io sync

---

web/handlers.go

Extensions in Firefox are hampered by a [long-standing bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1267027) that (incorrectly) applies CSP to content scripts injected by extensions. This precludes the ability to use the React and Redux DevTools in Firefox.
When in dev mode, add `unsafe-inline` to the CSP directives to unlock the use of these extdensions.
None.
```release-note
NONE
```

set CSP unsafe-inline during development

---

model/config.go

Since I forgot to change the access tags on settings in model/config.go , the experimental section is not functioning correctly. This PR aims to address that.
https://mattermost.atlassian.net/browse/MM-33437
```release-note
NONE
```

[MM-33437] Fix config access tags for experimental settings

---

store/localcachelayer/layer.go
store/localcachelayer/user_layer.go

This fixes a regression introduced in https://github.com/mattermost/mattermost-server/pull/16911.
It was causing problems with too many invalidations and overloading the writer instance for big installations.
Reverting this does not affect correctness at all because it was done out of abundance of caution and the
idea at that point was it was to be done for all caches.
https://mattermost.atlassian.net/browse/MM-33789
```release-note
NONE
```

MM-33789: Revert fallback to master for GetAllProfilesInChannel

---

services/remotecluster/mocks_test.go
services/remotecluster/send_test.go
services/remotecluster/sendmsg.go
services/sharedchannel/mock_AppIface_test.go
services/sharedchannel/msg.go
services/sharedchannel/service.go
services/sharedchannel/sync_recv.go
services/sharedchannel/sync_send.go
shared/mlog/default.go
shared/mlog/global.go
shared/mlog/levels.go
shared/mlog/log.go
store/sqlstore/post_store.go

This PR fixes a crash in the client after a sync when edited/deleted posts are included in a certain order.
- don't send the deleted post that is just a copy of an original edited post
- detect true deleted post and use delete api instead of update to get "message deleted" on client
- make sending message for sync a synchronous call so next sync cannot over-take
- add logging levels for logging message traffic
**To be merged with feature branch.**
https://mattermost.atlassian.net/browse/MM-33756
```release-note
NONE
```

MM-33756 fix client crashes on sync (post sync order)

---

api4/websocket.go

Cherry pick of #17142 on release-5.33.
/cc  @agnivade

Automated cherry pick of #17142

---

store/sqlstore/channel_store_categories.go
store/storetest/channel_store_categories.go

This is a deadlock due to reversed locking order of the SidebarChannels
and SidebarCategories table.
I could not find the exact culprit query from the deadlock output
because it only shows the last query a transaction is running. And from looking
at the code, the only query that runs "UPDATE SidebarCategories SET DisplayName = ?, Sorting = ? WHERE Id = ?"
is UpdateSidebarCategories. But for the deadlock to happen, it has to lock
SidebarChannels _first_, and then _then_ lock SidebarCategories.
Looking a bit more thoroughly, I found that DeleteSidebarCategory does indeed
lock the tables in an inverse way and if DeleteSidebarCategory runs concurrently with
UpdateSidebarCategories, they will deadlock.
Here's how it will happen.
```
tx1
DELETE FROM SidebarChannels WHERE CategoryId = 'xx';
tx2 …
```

MM-31396: Fix a possible deadlock with SidebarCategories

---

app/slashcommands/command_share.go
i18n/en.json

This PR removes the slash command for manually initiating a shared channel sync.  It was a temporary solution to testing sync before the automatic triggers were implemented. Also the manual sync command does not work reliably in multi-node clusters since sync must be initiated on the leader node. 
**This will be merged with the feature branch.**
https://mattermost.atlassian.net/browse/MM-33832-->
```release-note
NONE
```

MM-33832 remove slash command for manual shared channel sync 

---

model/post.go
scripts/mattermost-mysql-5.0.sql
scripts/mattermost-postgresql-5.0.sql
store/sqlstore/post_store.go
store/sqlstore/store.go
store/sqlstore/upgrade.go

PR addresses the outstanding merging issues with the cloud branch, specifically related to the [recently reverted](https://github.com/mattermost/mattermost-server/pull/16908) `posts.FileIds` migration. This is done by:
- Defaulting to the increased column size (300 chars) on new installations (for both db drivers).
- Migrating column only for PostgreSQL installations if not previously migrated.
https://mattermost.atlassian.net/browse/MM-33904
```release-note
NONE
```

[MM-33904] Address outstanding merging issues with cloud branch

---

api4/websocket.go
app/web_conn.go

A *crypto/tls.Conn does not expose the underlying TCP connection
or even a File method to get the underlying file descriptor
like the way a *net/TCPConn does. Therefore the netpoll code would
fail to get the file descriptor.
Relevant issue here: https://github.com/mailru/easygo/issues/3
It is indeed possible to use reflect black magic to get the unexported
member, but I have found unexpected errors during writing to the websocket
by getting the file descriptor this way. I do not want to spend time investigating
this especially since this is already released.
Once this is out, we can decide on the right way to fix this, most probably
by proposing to expose the File method or some other way.
https://mattermost.atlassian.net/browse/MM-34000
```release-note
Fix an issue where websockets …
```

MM-34000: Use non-epoll mode for TLS connections

---

Makefile
scripts/test.sh

test-server-race wasn't using the same set of steps
that the test-server step did. Therefore one test was failing.
Refactored it such that scripts/test.sh can be used to run
normal and race tests as well
```release-note
NONE
```

Makefile: Refactor test-server-race

---

.circleci/config.yml

I forgot the server has to build the webapp, so this needs to be removed with the mattermost-redux migration.
```release-note
NONE
```

Stop trying to build mattermost-redux in CI

---

api4/system_test.go
app/server_test.go

Fix Flaky Test because the environment variable is not set which causes problem
https://mattermost.atlassian.net/browse/MM-34166
```release-note
None
```

[MM-34166] Fix Flaky Test TestGenerateSupportPacket

---

api4/user_test.go
i18n/en.json
model/user.go

I took a long time to understand how invalid JSON could end up in a user's timezone field especially since we validate the request body on a call to `/user/patch`. I was finally able to reproduce today by sending more data than what would fit in the MySQL `varchar(256)` column. 
The user update works just fine but data gets truncated making it invalid on any future call that fetches the user.
Honestly I thought the db driver would return an error due to possible data loss/inconsistency but apparently that's not the case.
PR adds a check to `User.IsValid()` to prevent this issue going forward.
https://mattermost.atlassian.net/browse/MM-33934
```release-note
NONE
```

[MM-33934] Prevent User.Timezone field from overflowing column capacity

---

app/server_test.go

https://mattermost.atlassian.net/browse/MM-34086
```release-note
NONE
```

MM-34086: Skippping TestStartServerTLSOverwriteCipher

---

model/version.go
store/sqlstore/upgrade.go

I forgot that I should have added these changes before cutting the release branches. For next release branch cutting I will automate this. 
These changes are already in the release-5.34 branch (https://github.com/mattermost/mattermost-server/commit/4a148671156b416070b61fe01b29259fdf6e8f71#diff-c7561d15f1d9c1a92942b9ce5d2b1d979c89ffd525a8975f190983220cd6f2afR22). Is there any more work pending to improve `upgrade.go` or it will stay this way for the next releases?
```release-note
```

Upgrade db and version

---

shared/filestore/filesstore_test.go

PR fixes S3 filestore related tests which were failing if the bucket didn't exist.
Looks like the previous behaviour (create bucket if none found) was removed in https://github.com/mattermost/mattermost-server/pull/16977.
https://mattermost.atlassian.net/browse/MM-34164
```release-note
NONE
```

[MM-34164] Fix flaky TestS3FileBackend

---

app/server.go
app/websocket_router.go

App contains server.
Server contains WebsocketRouter.
There is no need for WebsocketRouter to contain
server too. As is evident because the code never used it.
```release-note
NONE
```

Remove server from WebsocketRouter

---

shared/mlog/global_test.go
shared/mlog/tcp.go

The global logger is inherently racy in that some global vars are set to function values during startup and it is hoped nothing accesses those before or while they are being set.  Also if they are reset, such as in the case of certain unit tests, the hope is that nothing accesses those after the reset.
8 months ago I added some code to the server that does some logging when exiting a goroutine, which in rare cases during unit testing can trigger race detection for the global vars mentioned above.  
This PR does not fix the racy global logger - that will come as part of a larger clean-up.  However this PR does ensure the exiting goroutine does not try to access the global vars thus removing this specific unit test's (`TestLoggingAfterInitialized`) race condition. …

MM-34271 fix race in TestLoggingAfterInitialized unit test

---

api4/websocket.go
app/web_conn.go
app/websocket_router.go
model/config.go
services/telemetry/telemetry.go

This is the first commit which makes some basic changes
to get it ready for the actual implementation.
Changes include:
- A config field to conditionally enable it.
- Refactoring the WriteMessage along with setting the deadline
to a separate method.
The basic idea is that the client sends the connection_id
and sequence_number either during the handshake (via query params),
or during challenge_auth (via added parameters in the map).
If the conn_id is empty, then we create a new one and set it.
Otherwise, we get the queues from a connection manager (TBD)
and attach them to WebConn.
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-34389

MM-34389: Reliable websockets: First commit

---

.circleci/config.yml
app/server_test.go

This suffered from the same race condition as
https://github.com/mattermost/mattermost-server/pull/17215.
We apply the same approach of using a memstore instead
of a file based config store.
It is likely that the test was also failing because of
the same race. Although I don't obviously see how, because
the race happens with mlog.Info. The test will fail only
if the config wasn't able to set properly. So although
not strictly related, it's somehow related.
If it fails again, we can look into it again. But this
atleast fixes the race.
While here, we also apply some cleanup of the code.
https://mattermost.atlassian.net/browse/MM-34086
```release-note
NONE
```

MM-34086: Fix flaky test StartServerTLSOverwriteCipher

---

app/email.go

This fixes issue where images are not showing in the cloud welcome email
[MM-34240](https://mattermost.atlassian.net/browse/MM-34240?atlOrigin=eyJpIjoiNWZmNjQwNzNjMGZmNDcyMWI4YmM2NWJhZTY2MjdjOWMiLCJwIjoiaiJ9)
```release-note
None
```

[MM-34240]-Cloud: Congratulations welcome email missing images

---

app/brand.go
app/channel.go
app/emoji.go
app/oauth.go
app/plugin.go
app/team.go
app/user.go
cmd/mattermost/commands/webhook.go

There are a couple of places where `model.NewAppError` doesn't wrap a returned `error`. This makes debugging harder.
I stumbled across this when debugging an issue in `app/user.go` and decided to fill all other occurrences that I found. The regex I've used is `err != nil \{\n\t+return model.NewAppError\("[a-zA-Z]+", "[a-zA-Z._]+", nil, ""`. Please note that this is surely not an _exhaustive_ fix, but rather a one time afford. 
https://community-daily.mattermost.com/core/pl/3aya19tnmirabcuxjy7jznmejo
```release-note
NONE
```

Add missing wrapped errors

---

model/cloud.go

CWS will be passing this value, and we want to be able to utilize it in mattermost-server (and pass to webapp)
https://mattermost.atlassian.net/browse/MM-34414
```release-note
NONE
```

[MM-34414] Add TrialEndAt to cloud model Subscription type

---

app/server_test.go

There were a bunch of more tests which concurrently
updated config along with starting the server.
We apply the same fix as before in https://github.com/mattermost/mattermost-server/pull/17215
https://mattermost.atlassian.net/browse/MM-34786
```release-note
NONE
```

MM-34786: Fix racy test TestStartServerTLSSuccess

---

model/config.go
shared/mlog/log.go
shared/mlog/testing.go
utils/logger.go

https://mattermost.atlassian.net/browse/MM-34787
```release-note
A new field EnableColor is added to LogSettings and NotificationLogSettings.
Non-JSON console logs will now be colored if that field is set to true.
```

MM-34787: Add colored output for non JSON console logs

---

model/cloud.go

It's not cut and dry to determine if a subscription is in a trial with or without a credit card. The logic for determining this will live inside the customer portal. We want to be able to consume this value, as well as pass it along to the front-end as part of subscription and subscription stats.
n/a
```release-note
None
```

Add IsFreeTrial to Subscription and SubscriptionStats types

---

app/notification.go
app/post_test.go

implemented auto follow based on root post
https://mattermost.atlassian.net/browse/MM-34774
```release-note
NONE
```

MM-34774 Root post with mention should be auto-followed but hidden from thread results

---

services/remotecluster/mocks_test.go
services/remotecluster/ping_test.go
services/remotecluster/send_test.go
services/remotecluster/service_test.go

Remote cluster ping unit test would in rare occasions shut down the ping emitter right as it was trying to emit a ping. The resulting error would be logged. Normally this would be harmless but caused a race condition as it tried to log the event with `testing.T.Log` after the test was completed.  Logging after a test is completed causes a race on the `testing.T.done` flag in the standard lib.  This is not a bug in stdlib - the bug is caused by holding a reference to `testing.T` after the test is completed.
This PR fixes the issue by ensuring no logging is attempted by explicitly shutting down the mock server, and ensuring no reference to `testing.T` is held after the test is completed.
https://mattermost.atlassian.net/browse/MM-34785
```release-note
NONE
```

MM-34785 fix racy ping test

---

scripts/mattermost-mysql-5.0.sql
store/sqlstore/upgrade.go

We forgot to update the cloud branch to eliminate the reverted migration for MySQL so when a new release branch was cut it still included the migration.
As a follow-up I'll immediately create a similar PR for the cloud branch.
https://mattermost.atlassian.net/browse/MM-34888
```release-note
NONE
```

[MM-34888] Revert Posts.FileIds migration on MySQL

---

store/sqlstore/upgrade.go
store/sqlstore/upgrade_test.go

PR fixes 5.35 migration code to only run performance heavy queries once. This is to fix some issues we are having on community-daily (more context [here](https://community-daily.mattermost.com/private-core/pl/h3s8mpkabjfcfczszqby88sozy)).
```release-note
NONE
```

Fix 5.35 migration

---

store/sqlstore/upgrade.go
store/sqlstore/upgrade_test.go

Upgrade test was relying on specific migration version. Extracted the function under test to make it pass on future versions.
https://mattermost.atlassian.net/browse/MM-34792
```release-note
NONE
```

MM-34792 test shouldn't depend on upgrade sequence

---

app/plugin_api_test.go
app/plugin_requests.go
plugin/context.go

Pass the source plugin ID via a `Mattermost-Plugin-ID` header. The exiting mechanism to pass the id -  the `SourcePluginId` in `plugin.Context´ is now deprecated.
https://mattermost.atlassian.net/browse/MM-34919
```release-note
NONE
```

[MM-34919] Use Mattermost-Plugin-ID header to pass ID in inter-plugin requests

---

go.mod
go.sum
store/sqlstore/store_test.go
store/sqlstore/upgrade.go
vendor/github.com/mattermost/gorp/column.go
vendor/github.com/mattermost/gorp/gorp.go
vendor/github.com/mattermost/gorp/table.go
vendor/modules.txt

PR updates gorp dependency to fix an issue with `ExecNoTimeout()`.
I've linked this to a rather old ticket because I am thinking it might have been created in response to this bug appearing. 
This is not a general solution, meaning we still need to explicitly call `ExecNoTimeout()` (or one of its wrapping methods) in order to avoid timing out on queries taking longer than `SqlSettings.QueryTimeout` but I felt this was good enough to address the issues at hand also given the migration system will soon change.
https://github.com/mattermost/gorp/pull/11
```release-note
Fixes an issue where queries executed during the upgrade process would preemptively timeout on the application side.
```
https://mattermost.atlassian.net/browse/MM-13799

[MM-13799] Avoid queries timing out during upgrade

---

app/web_conn.go
model/feature_flags.go

It has been soaked for enough time in community-daily
and also in community. Enabling it for all.
```release-note
TCP_NO_DELAY is disabled for websocket connections
to allow for higher throughput
```
https://mattermost.atlassian.net/browse/MM-34125

MM-34125: Remove WebSocketDelay feature flag

---

go.mod
go.sum
store/sqlstore/store_test.go
store/sqlstore/upgrade.go
vendor/github.com/mattermost/gorp/column.go
vendor/github.com/mattermost/gorp/gorp.go
vendor/github.com/mattermost/gorp/table.go
vendor/modules.txt

Cherry-pick of https://github.com/mattermost/mattermost-server/pull/17444.
https://mattermost.atlassian.net/browse/MM-13799
```release-note
Fixes an issue where queries executed during the upgrade process would preemptively timeout on the application side.
```

[MM-13799] Avoid queries timing out during upgrade (cloud cherry-pick)

---

app/channel.go
app/channel_test.go
app/post_test.go

viewing the channel shouldn't touch thread timestamp
https://mattermost.atlassian.net/browse/MM-34872
```release-note
NONE
```

MM-34872 CRT: thread last_viewed_at updated when channel is viewed

---

api4/user_test.go
store/sqlstore/thread_store.go

don't count your own replies as unread
https://mattermost.atlassian.net/browse/MM-34895
```release-note
NONE
```

MM-34895 CRT: Replying to a root post with an at-mention triggers an unread mention

---

api4/cloud.go
app/app_iface.go
app/cloud.go
app/email.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/cloud.go
templates/cloud_trial_ended_email.html
templates/cloud_trial_ended_email.mjml

Adds ability to listen to trial ended webhook from the CWS and then send a trial ended email to all admins
[MM-35039](https://mattermost.atlassian.net/browse/MM-35039?atlOrigin=eyJpIjoiNDgyYjg0Nzg5NzAwNGM1NzhiMmU3ODU5YTkzMmE3MWUiLCJwIjoiaiJ9)
- Has webapp changes (https://github.com/mattermost/mattermost-webapp/pull/7967)
```release-note
None
```

[MM-35039] - Send trial ended email

---

.circleci/config.yml
Makefile

- Moving out the lint/vet part from the build step to make more clear when it fails. 
- some updates for some job in the resource_class, because we pay extra for bigger machines and in some steps we don't need that
N/A
```release-note
NONE
```

Updates on CI

---

app/notification.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/thread_store.go
store/store.go
store/storetest/mocks/ThreadStore.go
store/timerlayer/timerlayer.go

post notifications for thread followers, not 'participants'
https://mattermost.atlassian.net/browse/MM-35125
```release-note
NONE
```

MM-35125 CRT: Mention badge on threads doesn't appear until refresh

---

store/sqlstore/upgrade.go

drop wrong migration item 
for context see 🧵  (internal): https://community.mattermost.com/private-core/pl/n6aznzgxfjro9k9m5m6fajigjo
```release-note
NONE
```

drop wrong migration item

---

api4/user_test.go
app/post.go

correctly handle mention counting on timestamp change
https://mattermost.atlassian.net/browse/MM-35127
```release-note
NONE
```

MM-35127 CRT: Marking thread as unread doesn't set the timestamp correctly

---

app/channel.go
store/sqlstore/channel_store.go

don't trigger mentions for an existing thread membership when unread is done from within channel
https://mattermost.atlassian.net/browse/MM-35128
```release-note
NONE
```

MM-35128 CRT: Global Threads item should not be affected by 'mark as unread' in channel

---

app/web_hub_test.go

https://mattermost.atlassian.net/browse/MM-35239
```release-note
NONE
```

MM-35239: Skip TestHubSessionRevokeRace

---

app/notification.go

only process parent post mentions for threads in order to autofollow
https://mattermost.atlassian.net/browse/MM-35103
```release-note
NONE
```

MM-35103 Replies in a thread with an initial mention triggers notification each time

---

app/web_hub_test.go

registerDummyWebConn already registers a webconn
to the hub. We were registering it again later.
This was incorrect. The test just passed nevertheless,
but there were 2 webconns getting added to the same userID.
https://mattermost.atlassian.net/browse/MM-35239
```release-note
NONE
```

MM-35239: Fix racy test HubSessionRevokeRace

---

store/sqlstore/upgrade.go

See discussion here https://community.mattermost.com/private-core/pl/n6aznzgxfjro9k9m5m6fajigjo
Background:  column was added for a PR that didn’t make it into 5.35, but the migration was added to 5.35.  The column migration was removed from 5.35 and this ticket is to put it into 5.36
https://mattermost.atlassian.net/browse/MM-35181
```release-note
NONE
```

MM-35181 Move SharedChannelsUsers.ChannelId column add to 5.36 migration

---

app/slashcommands/command_channel_header.go
app/slashcommands/command_channel_purpose.go
i18n/en.json

The old "Error to update the current channel." error was both gramatically incorrect and didn't actually tell the user what went wrong. This should hopefully improve both of those.
https://mattermost.atlassian.net/browse/MM-22678
```release-note
Improved error messages for /header and /purpose commands.
```

MM-22678 Use more user-friendly errors for channel commands

---

app/notification.go

avoid re-following thread when a new reply comes in without mention
https://mattermost.atlassian.net/browse/MM-35290
```release-note
NONE
```

MM-35290 CRT: Reply on a unfollowed thread causes re-following

---

app/notification.go

mentions in replies should affect count
https://mattermost.atlassian.net/browse/MM-35300
```release-note
NONE
```

MM-35300 CRT: No mention badge on Threads when user is mentioned in both the root post and a reply post

---

model/post.go
store/sqlstore/post_store.go

forgot to copy isFollowing param
https://mattermost.atlassian.net/browse/MM-35206
```release-note
NONE
```

MM-35206 CRT: is_following on posts not reflecting state properly

---

app/web_conn.go
einterfaces/metrics.go
einterfaces/mocks/MetricsInterface.go

Added three new metrics to track successful websocket drain
and dead queue misses.
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-34878

MM-34878: Add metrics for websocket reconnects

---

store/sqlstore/channel_store_categories.go
store/storetest/channel_store_categories.go

PR fixes a potential panic caused by wrapping a `nil` error in  `SqlChannelStore.CreateSidebarCategory()`.
https://mattermost.atlassian.net/browse/MM-35316
```release-note
NONE
```

[MM-35316] Fix panic in app.CreateSidebarCategory

---

build/docker-compose.common.yml

the docker image `jhillyerd/inbucket:release-1.2.0` we were using was removed from docker hub and now is available on `inbucket/inbucket` however that is a new release and have some breaking changes.
I will update our codebase to use the new release but for now, as a workaround, lets use the same image hosted in the mattermost docker hub.
We need to cherry-pick to all supported release branches and cloud, I will cherry pick to all that applies
n/a
```release-note
ci: update inbucket to use mattermost/inbucket:release-1.2.0
```

ci: update inbucket to use mattermost/inbucket:release-1.2.0

---

build/docker-compose.common.yml

cherry pick of https://github.com/mattermost/mattermost-server/pull/17559
-->
```release-note
NONE
```

ci: update inbucket to use mattermost/inbucket:release-1.2.0 (#17559)

---

templates/cloud_welcome_email.html

Fix styling in the welcome email like space between icons and paragraphs
[MM-35061](https://mattermost.atlassian.net/browse/MM-35061?atlOrigin=eyJpIjoiYWIzZjZhMTQ0Zjg1NGRhY2E4NmMyNjVjNTdiN2IyZWIiLCJwIjoiaiJ9)
```release-note
NONE
```

[MM-35061] - Welcome Email: Missing spacing between icon and paragraphs

---

services/sharedchannel/sync_recv.go

This PR fixes a bug where incoming users were not sanitized before being created during shared channel sync.
https://mattermost.atlassian.net/browse/MM-35430
```release-note
Fixed Shared Channels issue where users were not sanitized during remote synchronization.
```

MM-35430 sanitize user before creation during sync

---

i18n/en.json

Fixes trial ended email tenses
[MM-35404](https://mattermost.atlassian.net/browse/MM-35404?atlOrigin=eyJpIjoiNjc3NjAxMjEwYjQ3NDU2Yjk0MTAzOGE4ZmMzM2E5MGMiLCJwIjoiaiJ9)
```release-note
NONE
```

[MM-35404] - Cloud Trial - Body of 'Trial ends today Email (Admin-only)' conflicts with subject line

---

build/release.mk

When we run the `make package` it generated the packages for linux/macos/windows and it keeps the directory `dist\mattermost` which is not needed after the package finish.
removing this also helps in the build/release pipeline when saving the data, will speed up a bit gitlab.
N/A
```release-note
NONE
```

build/package: remove dist/mattermost directory

---

api4/remote_cluster.go
app/remote_cluster_service_mock.go
services/remotecluster/recv.go
services/remotecluster/service.go
services/remotecluster/service_test.go
services/sharedchannel/attachment.go
services/sharedchannel/channelinvite.go
services/sharedchannel/channelinvite_test.go
services/sharedchannel/sync_recv.go
services/sharedchannel/sync_send.go

Discussed with @wiggin77 offline and removed context propagation from the shared channel services as they do not require request specific data. This PR removes `request.Context` arg from several methods of `SharedChannelService` and `RemoteClusterService`. We will use empty context when it is required by the `App` methods.
```
NONE
```

remove request.Context from shared channel service methods

---

build/docker-compose.common.yml

Follow-up of https://github.com/mattermost/mattermost-server/pull/17559
this upgrades the docker image for inbucket, the service we use in the tests to validate the emails.
the newer release of inbucket changed the ports, This PR adjust the ports to match the ones we are already using
No need to cherry pick to other branches.
N/A
```release-note
NONE
```

ci: upgrade inbucket

---

i18n/en.json

Fixes trial ended email tenses
[MM-35404](https://mattermost.atlassian.net/browse/MM-35404?atlOrigin=eyJpIjoiNjc3NjAxMjEwYjQ3NDU2Yjk0MTAzOGE4ZmMzM2E5MGMiLCJwIjoiaiJ9)
```release-note
NONE
```

[MM-35404] cherry-pick - Cloud Trial - Body of 'Trial ends today Email (Admin-only)' conflicts with subject line 

---

store/sqlstore/store.go
store/sqlstore/store_test.go

PR fixes an issue where long-running migrations (on MySQL) could still time out. While we are not setting a timeout for migrations anymore at the app layer (since https://github.com/mattermost/mattermost-server/pull/17444) there was still a timeout happening at the network (tcp) layer governed by the `readTimeout` query parameter from the datasource.
PR fixes this by ignoring the provided parameter and resetting it to zero (no timeout). This should be also safe for queries running outside the "migration phase" since those will respect the timeout value defined at the application level through the `SqlSettings.QueryTimeout` setting.
cc @amyblais 
https://github.com/mattermost/mattermost-server/pull/new/MM-35767
```release-note
Fixed an issue where long migrations where failing with an …
```

[MM-35767] Ignore readTimeout param from MySQL datasource

---

model/shared_channel.go

Mobile team has requested that `model.SharedChannel` serialize to JSON using the same field names as other Channel objects.  i.e. `GetAllSharedChannels` should have matching field names returned as `GetPublicChannels` for any fields they have in common.
API Reference PR:  https://github.com/mattermost/mattermost-api-reference/pull/639
https://mattermost.atlassian.net/browse/MM-35802
```release-note
Response field names changed for experimental API GetAllSharedChannels to match the field names for other channels APIs.
```

MM-35802 Rename json fields for GetAllSharedChannels to match other channel objects

---

store/localcachelayer/user_layer.go

PR fixes a small issue where cache hit/miss metrics counters for user cache were getting incremented/decremented more than needed. `rootStore.doStandardReadCache()` already takes care of that internally. Also, we were using a different cache name which made the resulting metrics more confusing.
```release-note
NONE
```

Remove redundant additions to cache hit/miss counters

---

app/server.go
jobs/schedulers.go
jobs/schedulers_test.go
jobs/server.go

PR fixes an issue where the job scheduler server could potentially miss a "leader change" event. The proposed changes are:
- Moved the schedulers server start so that it happens before doing potentially long-running tasks (e.g. plugins initialization)
- Changed the `handleClusterLeaderChange` semantic to guarantee that the latest change is gets delivered.
- Fixed a possible deadlock case in the config change handler.
https://mattermost.atlassian.net/browse/MM-35424
```release-note
Fixed an issue where the job scheduler server could miss a "changed leader" cluster event.
```

[MM-35424] Fix job schedulers server from missing leader change event

---

config/store.go

PR fixes some races introduced in the configure overhaul PR (https://github.com/mattermost/mattermost-server/pull/17578).
I was a bit too optimistic. The backup/restore of the FeatureFlags section in oldCfg was racy.
```release-note
NONE
```

Fix races in config refactor

---

app/email.go
templates/invite_body.html

This PR fixes invalid uses of variables in the `invite_body` template. Something must have been copied over from `message_notification` without modifying the references. I've also made sure to add the `SenderPhoto` in the props as well, as that was missing.
This should be tested thoroughly before merge to ensure that the invite body templates are working properly.
NOTE: If using inbucket, I don't think you can see the sender photo if it exists. It might only work with a real SMTP server, so that might be worth testing.
https://mattermost.atlassian.net/browse/MM-35841
```release-note
NONE
```

[MM-35841] Fix invalid use of variables in invite_body template

---

app/permissions_migrations.go
model/migration.go
testlib/store.go

A migration was missed during migration of permissions.
https://mattermost.atlassian.net/browse/MM-35861
Fixes GH-17642
```release-note
Fixes bug where users who would upgrade from server version < 5.35 to 5.35 or greater and would not be able to test SMTP connection getting a permission error.
```

[MM-35861] Add missing migration transformation

---

.circleci/config.yml

Just updating the server to match the client here. I'm not sure if the server is able to successfully build the web app at this point, but if it tries, it'll use the right Docker image at least.
https://mattermost.atlassian.net/browse/MM-34363
https://github.com/mattermost/mattermost-webapp/pull/8132
```release-note
NONE
```

Use Node 14 build image for web app

---

store/sqlstore/upgrade.go
store/sqlstore/upgrade_test.go

Saving dot releases versions in `model/version.go` had the outcome of storing that value in the `Systems` table for new installations.
Unfortunately though `store.shouldPerformUpgrade()` did a simple string equality comparison which would essentially fail for any dot release and prevent the migrations from happening, leaving everything frozen db schema wise.
I've changed the behaviour to actually parse the version and go ahead if both major and minor versions match, hence ignoring the patch version value.
Another approach I think could have been to add mock `upgradeDatabaseToVersion5XX()` methods for all the dot releases affected by this but it didn't look like a great solution.
https://mattermost.atlassian.net/browse/MM-35931
```release-note
Fixed an issue where subsequent migrations …
```

[MM-35931] Apply DB migrations regardless of version patch value

---

app/app_iface.go
app/integration_action.go
app/notification_push.go
app/opentracing/opentracing_layer.go
app/plugin_requests.go
app/plugin_requests_test.go
app/plugin_test.go
app/server.go

Migrated any remaining methods under server.
And for everything else, renamed fakeApp to app.
The word fakeApp is confusing and we should just call
it for what it is - an app.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=639a0bc1-4401-43d5-81ec-0dd54e796d9a
```release-note
NONE
```

Remove all remaining occurences of fakeApp

---

api4/user_test.go
store/sqlstore/thread_store.go
store/storetest/thread_store.go

- Threads should not be returned as unread if a reply post has been edited or reacted to since the time the thread was last viewed
- https://mattermost.atlassian.net/browse/MM-35436
- https://mattermost.atlassian.net/browse/MM-35437
```release-note
NONE
```

MM-3543/MM-35436: fix thread being marked unread when updating reply posts

---

store/storetest/thread_store.go

- PR https://github.com/mattermost/mattermost-server/pull/17645 went in right before https://github.com/mattermost/mattermost-server/pull/17673. The former caused breaking changes in the latter. I should have merged master into the second PR before merging it into master.
- N/A
```release-note
NONE
```

MM-34895: fix test from earlier LastViewed CRT changes

---

app/extract_plugin_tar.go
app/extract_plugin_tar_test.go

`ExtractTarGz` can fail on archives with a largish number or files, complaining about too many open file handles. Clean up as we go to avoid this.
Fixes: https://mattermost.atlassian.net/browse/MM-35945
```release-note
NONE
```

MM-35945: handle lots of files in ExtractTarGz

---

.circleci/config.yml

The server version of https://github.com/mattermost/mattermost-webapp/pull/8154.
I'll be talking a bit more about this later in the week, but Node 16 is when NPM 7 becomes default, and we need NPM 7 for the workspaces feature that makes the web app monorepo work.
https://github.com/mattermost/mattermost-webapp/pull/8154
```release-note
NONE
```

Update webapp build image to Node 16

---

shared/driver/conn.go
shared/driver/driver.go
store/sqlstore/store.go
store/sqlstore/store_test.go

This is the first step in implementing a DB layer via RPC.
The plan is to migrate the mattermost-plugin-api to use
this DB connector so that all queries start to get
routed through this library.
And then we will add the DB query capability to the plugin RPC
API and route all queries via RPC. At that point, this will be
completely transparent to all plugins because they will already
be using the DB connector and everything will be behind the scenes
for them.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=c7386db7-65fd-469b-8bcf-8dc8f8e61e4f
```release-note
NONE
```

Pass-through DB Driver implementation

---

Makefile

Adds focalboard as a prepackaged plugin. The name of the plugin is different because of its source code existing within the `focalboard` repository.
```release-note
Added focalboard v0.6.7 as a prepackaged plugin.
```

Adds focalboard v0.6.7 as a prepackaged plugin

---

services/users/users.go

While creating users, the user roles were getting overwritten for the import path. This was intended for the regular user creation path from the API. However, the user roles are already included in the import data and we should've avoid those steps. So, this PR adds a skip condition for those steps as it was [before](https://github.com/mattermost/mattermost-server/blob/d320b50abbdc8c05ebb6738a48ac823328d1a936/app/user.go#L296).
```release-note
NONE
```

hotfix: user import issue where the user roles were overwritten for the import path

---

model/config.go

Originally changed in https://github.com/mattermost/mattermost-server/pull/17651
We want to keep the about link and help link set to a default page that redirects to appropriate page. The reason is that we may, for instance, want to link to a different help link in the future. If we do so, we only have to change the redirect without changes to the codebase.
Did not revert the change to terms of service and privacy policy links, given we want to point these to mattermost.com

Change about and help links back to default redirects

---

shared/driver/conn.go
shared/driver/objects.go

This is a necessary step for adding the RPC communication
because each method call of each object needs to go through
the RPC layer.
Hence doing this part in a separate PR rather than heaping
everything in a single PR.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=c7386db7-65fd-469b-8bcf-8dc8f8e61e4f
```release-note
NONE
```

DB driver: Add wrapper structs for low-level objects

---

store/sqlstore/store.go
store/sqlstore/store_test.go

PR fixes a crash due to a nil map assignment. This was silently introduced in https://github.com/mattermost/mattermost-server/pull/17428 . What's worse is that the test covering this would have failed and showed the issue right away but that also had a bug as it was running concurrently and only testing the last test-case/DSN as a result.
https://mattermost.atlassian.net/browse/MM-36236
```release-note
Fixed an issue where a datasource with missing query parameters could cause the server to crash during startup on MySQL installations.
```

[MM-36236] Fix nil map assignment crash

---

api4/cloud.go
api4/user.go
api4/user_test.go
app/app_iface.go
app/cloud.go
app/opentracing/opentracing_layer.go
i18n/en.json

For cloud instances, when we're at the cloud limit, we should not allow activation of users from the system console
[MM-36198](https://mattermost.atlassian.net/browse/MM-36198?atlOrigin=eyJpIjoiMDMzMDA3ZDM1MGQ2NGI3ZDgxOWNiZDk0NTk4ZWM3OGEiLCJwIjoiaiJ9)
```release-note
NONE
```

[MM-36198] - Activating a user in System Console does not respect cloud user limits

---

api4/user_test.go
app/user.go

Currently upon following a thread the thread is unread,
this commit changes that by explicitly marking it as read.
https://mattermost.atlassian.net/browse/MM-35805
```release-note
NONE
```

MM-35805: following a thread should also mark it as read

---

store/sqlstore/store.go
store/sqlstore/store_test.go
store/sqlstore/upgrade.go

While reviewing some migrations I've figured something odd was happening with column defaults. 
Passing an empty string didn't result in an empty string default but would instead cause the default to get dropped.
PR fixes this issue and also splits the behaviour into two separate methods (alter and remove) to avoid more unwanted surprises. I've also fixed the naming which was rather ambiguous (the exists refers to the column and not the default).
Pre-existing migration code was made semantically equivalent.
https://mattermost.atlassian.net/browse/MM-36217
```release-note
NONE
```

[MM-36217] Improve column default utilities

---

app/email.go

This PR adds a query param to the Cloud Email sent when the subscription is ending in 3 days.
https://mattermost.atlassian.net/browse/MM-35538
https://github.com/mattermost/mattermost-webapp/pull/8234
```release-note
NONE
```

MM-35538 - display purchase modal when coming from email

---

app/server.go
store/sqlstore/store.go

The creation of the store included running the migrations
which means that SQL statements would be executed before
we could make the check for DB version.
We make this a package-level function to allow checking
the DB version even before creating a store.
https://mattermost.atlassian.net/browse/MM-35030
```release-note
NONE
```

MM-35030: Hoist GetDBVersion before creating store

---

cmd/mattermost/commands/version_test.go
config/migrate_test.go

This change disables unit tests that were found to rely on access to a database during ['short' (or 'quick')](https://github.com/mattermost/mattermost-server/blob/0eb50a6777e9d2069fec83b2757ac6d9de9b81ca/Makefile#L393-L400) unit testing.
Some additional context is available at https://github.com/mattermost/mattermost-server/pull/17718#issuecomment-855824322
cc @jespino; also please let me know if it's possible/better to instead upgrade these tests to use autodetection setup approach.  I was looking around for the code that does that, and it wasn't immediately clear to me - perhaps [this test helper code](https://github.com/mattermost/mattermost-server/blob/0eb50a6777e9d2069fec83b2757ac6d9de9b81ca/testlib/helper.go#L69-L71)?  Glad to do that instead if it is preferable to the naive …

Skip database-reliant tests during short mode unit testing

---

app/post.go
app/post_test.go
model/post.go
store/sqlstore/post_store.go
store/storetest/post_store.go

Change Post.IsFollowing to a pointer and set to nil for responses to updates to a Post. The reason we need to do this is that post edits are broadcast to all users in the corresponding channel and the `IsFollowing` field needs to be unique to each user. It would not be performant to look up the following state for every single user in the channel and broadcast individually to each user.
Instead, we explicitly don't set and omit `IsFollowing` in the responses and leave it to the client to figure out what the following state is since it should have all the information needed for that already.
https://mattermost.atlassian.net/browse/MM-36257
```release-note
NONE
```

MM-36257 Change Post.IsFollowing to a pointer and set to nil for responses to updates to Posts

---

docker-compose.yaml

- The servers in a HA cluster won't communicate with each other unless they have the same name. An empty name doesn't work, so we set a generic name. Even with an incorrect configuration the cluster appeared to work because the nginx proxy was distributing http API requests to each individual server, but cluster messaging wouldn't work, because of which websocket events weren't firing correctly.
- Discovered while working on https://mattermost.atlassian.net/browse/MM-35396
```release-note
NONE
```

Give local dev HA cluster a name

---

api4/config_test.go

PR attempts to fix flaky `TestUpdateConfigDiffInAuditRecord`. I wasn't able to reproduce this locally but I have a feeling it may be caused by the logs not getting flushed in time. To force a flush we are now shutting down the server before attempting to read the log file.
https://mattermost.atlassian.net/browse/MM-36411
```release-note
NONE
```

[MM-36411] Fix flaky TestUpdateConfigDiffInAuditRecord

---

app/notification.go
app/notification_test.go

- Ignore 'Trigger notifications on messages in reply threads that I start or participate in' notification setting for CRT reply posts
- https://mattermost.atlassian.net/browse/MM-35415
```release-note
NONE
```

MM-35415: ignore 'any' notification setting for CRT reply posts

---

app/bot.go
model/bot.go
model/bot_test.go

A sudden spike in `getChannelMember` API calls was noticed during the (now hourly) community server updates (full context [here](https://community-daily.mattermost.com/private-core/pl/gen5i1kcu7n68xxs4n5zyufnrr)). Moreover, most of these calls were failing with 404s. After an initial investigation we were able to verify that such errors were all related  to bot users (plugin created) which are usually not part of any channel (hence the not founds).
Most of these plugins do a call to `Helpers.EnsureBot()` during activation. This caused the bot user to get updated and a websocket event to get sent. In response to such event each client would make the API call, which was tracked down to:
https://github.com/mattermost/mattermost-webapp/blob/0e8a3f375306d18eaf52aa191e07d8d5556fbea9/actions/webs …

[MM-36318] Avoid redundant bot user update

---

utils/api.go
web/oauth_test.go

Prevents `javascript:` protocol in pre login OAUTH screens. 
We are using the user passed query param value in the HTML output so that in case of misconfiguration, it will still let the user to **go back** to their respective mobile app. 
https://mattermost.atlassian.net/browse/MM-36250
```release-note
NONE
```

Prevent JS Execution on Pre-login OAUTH screen 

---

api4/post.go
api4/post_test.go
app/app_iface.go
app/channel.go
app/channel_test.go
app/opentracing/opentracing_layer.go
app/post_test.go

The API endpoint for setting posts unread was only being used by the client for posts marked unread from the center channel, in which case the thread should not be followed. However, if a thread membership didn't exist we were setting it to followed automatically so in some instances a user marking a post unread from the center channel would seemingly follow and unfollowed thread. I added the option to specify in `MarkChannelAsUnreadFromPost` what the behaviour should be and set the API endpoint to not follow the threads.
https://mattermost.atlassian.net/browse/MM-35297
```release-note
NONE
```

MM-35297 Add the ability to control if thread is followed when marking post as unread and don't autofollow from API

---

store/sqlstore/thread_store.go

https://github.com/mattermost/mattermost-server/pull/17417 added a nil check for TeamId in this query which seems(?) to be unneeded and is causing threads to report an incorrect number of mentions. This reverts that small change. There is still some weird behaviour happening because even with this nil check the mention count should not report incorrectly. I will be digging into this further but wanted to get a fix onto daily for testing sooner.
FYI @mkraft since you took over ownership of https://github.com/mattermost/mattermost-server/pull/17417
```release-note
NONE
```

Fix thread mention counts

---

Makefile

```release-note
Update the focalboard builtin plugin version to v0.7.0
```

Bump focalboard prepackaged plugin version to v0.7.0 (#17822)

---

app/channel.go
app/channel_test.go
app/user.go
store/sqlstore/thread_store.go
store/storetest/thread_store.go

For root posts that had not been followed before (aka no thread membership) and had no replies (aka no thread) we were incrementing the mention count mistakenly. Added unit tests to cover these cases.
This also fixes a server error that occurs when following a root post that doesn't have a thread.
https://mattermost.atlassian.net/browse/MM-36429
```release-note
Fix bug with collapsed reply threads where some posts without replies can show as having unread mentions
```

MM-36429 Do not increment mention counts when marking root posts with no replies as unread

---

app/auto_responder.go

The time needed to be converted to seconds before extracting
the year, month, an day.
Not sure how it passed CI for so long.
```release-note
NONE
```
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=de13d489-9e10-4fcc-896c-0d738a21f28f

Fix flaky test: TestSendAutoResponseIfNecessary

---

go.mod
go.sum
vendor/github.com/dyatlov/go-opengraph/opengraph/opengraph.go
vendor/modules.txt

The PR is now merged with the original repo, so we can remove
the temporary replace.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=59af323d-35a7-4312-87a1-e374239a03d9
```release-note
NONE
```

Use original opengraph dependency

---

model/feature_flags.go

For beta we want to default the feature flag to on. The feature itself has a config that defaults it to off. This just allows admins to turn on the beta without manually setting the feature flag env var to on.
cc @amyblais @esethna we need this for 5.37
N/A
```release-note
Default make collapsed reply threads beta feature accessible to turn on from the system console
```

Default CollapsedThreads feature flag to on

---

model/config.go

```release-note
The config setting EnableReliableWebSockets now defaults to true.
```

Reliable Websockets: default to true

---

store/sqlstore/preference_store.go

Now that version 10 is minimum, we can start to use
advanced postgres features.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=0445b560-91b9-469b-8f19-febf1881bcd6
```release-note
NONE
```

PreferenceStore: Use native upsert for Postgres

---

app/notification.go
app/notification_push.go

We were using the pointer to the same post object
in multiple push notifications because we were sending
it in a loop of mentioned user list.
This wasn't an issue so far, but after we started to parse
markdown in the push notification flow, we started to edit
the post struct as well.
To fix this, we move the markdown parsing deep into the push notification
construction such that we don't need to write back to the same post pointer
again.
https://mattermost.atlassian.net/browse/MM-36894
```release-note
NONE
```

MM-36894: Racy test: TestExecuteCommandInDirectMessageChannel

---

model/config.go
services/telemetry/telemetry.go

This PR adds a new configuration option `ChimeraOAuthProxyUrl` which allows specifying [Chimera](https://github.com/mattermost/chimera) URL that can be used by plugins to connect with pre-created OAuth applications.
https://mattermost.atlassian.net/browse/MM-36779
```release-note
Added a new config setting PluginSettings.ChimeraOAuthProxyURL
```

MM-36779 - Add ChimeraOAuthProxyURL config option

---

api4/channel_test.go
api4/post_test.go
app/web_conn_test.go
model/websocket_message.go
model/websocket_message_test.go

```release-note
All fields in WebSocketEvent are now unexported. Use the getter methods
to access them.
```
https://mattermost.atlassian.net/browse/MM-21333

MM-21333: Unexport fields in WebSocketEvent

---

.circleci/config.yml
build/README.md
build/local-test-env.sh

go: upgrade builder image to use go1.16
Jira: https://mattermost.atlassian.net/browse/DOPS-504
```release-note
go: upgrade builder image to use go1.16
```

go: upgrade builder image to use go1.16

---

app/slashcommands/helper_test.go

Setting AutomaticPrepackagedPlugins to true was making the test
to download the plugin from the marketplace and initialize it.
While this wasn't wrong in itself but that's not what the test does
and just part of the app initialization and it unnecessarily slowed
down the test by downloading the plugin zip file.
And initializing a plugin from inside a test has some issues
to work properly. While those could be solved, a cleaner way
is to just not download the plugin at all.
https://mattermost.atlassian.net/browse/MM-36947
```release-note
NONE
```
```

MM-36947: Fix TestHeaderProviderDoCommand

---

api4/config_test.go

The fix in https://github.com/mattermost/mattermost-server/pull/17777
doesn't seem to have worked fully as this was seen again.
Skipping it for now until we revisit this.
https://mattermost.atlassian.net/browse/MM-36411
```release-note
NONE
```

MM-36411- Skip flaky TestUpdateConfigDiffInAuditRecord

---

store/sqlstore/thread_store.go
store/sqlstore/upgrade.go
store/sqlstore/upgrade_test.go

- Fix unreads query for threads to check deleted option
- Normalize unreads query to look for threads after given time
- Fix migration to only run once, and increment timestamp by one so that threads are definitely marked as read.
- Fixes issues with https://mattermost.atlassian.net/browse/MM-35345
- And possibly some issues with thread unreads. 
```release-note
NONE
```

[MM-35345]: fix unreads in threads and migration

---

app/post.go
app/post_test.go

- When ThreadAutoFollow is on, replying to a thread that was previously unfollowed should cause the thread to be followed again.
- https://mattermost.atlassian.net/browse/MM-35925
- 
```release-note
NONE
```

[MM-35925] Follow thread when posting in one, even if previously unfollowed

---

api4/cloud.go

Without these returns the front-end thinks it successfully changed the product when it might not have. Thanks @AGMETEOR 
n/a
```release-note
None
```

Add a return in 2 places

---

app/server.go

Another mystery to add to the collection. This was Introduced in e74c66d7f6a1f515d2380d0f163b2958f03c2bc7 . I couldn't exactly figure out why but maybe the config setting was mainly thought for enterprise customers (to limit push notifications?) and a higher default was deemed appropriate for team edition instead. Anyhow, removing this now as it should be left to the configuration.
https://mattermost.atlassian.net/browse/MM-32604
```release-note
Removed hard-coded override of TeamSettings.MaxNotificationsPerChannel on unlicensed servers (e.g team edition).
```

[MM-32604] Remove hard-coded override of MaxNotificationsPerChannel

---

Makefile
build/release.mk

Currently we have per platform `make build-foo` targets yet a single `make package` target.
Introduce separate `make package-foo` targets. Thus people can package only what they need.
As a nice bonus point, this allows macosx, windows and linux packaging to happen in parallel.
N/A
```release-note
Add per-platform `make package' targets - package-osx, package-linux and package-windows.
```

Introduce per platform make package targets

---

app/integration_action.go
app/integration_action_test.go

Consider an empty body in the doPostAction function before doing the unmarshalling.
If we don't do this, an empty response (which is common) will make this function error out after creating the trigger ID and sending it to the integration.
A subsequent call to openDialog will not fail because the trigger ID exist in the server, but the trigger ID has not been passed over to the client (because the function error out). Therefore, openDialog says that everything is fine, but no dialog is shown in the client.
https://mattermost.atlassian.net/browse/MM-36757
```release-note
Fix bug when opening a dialog from an interactive message when returning an empty response
```

Consider empty body before unmarshal on do post action

---

.circleci/config.yml
.gitlab-ci.yml
build/README.md
build/local-test-env.sh

update mattermost server build to use go 1.16.6
JIRA: https://mattermost.atlassian.net/browse/DOPS-521
```release-note
now Mattermost is built using go1.16.6
```

update mattermost server build to use go 1.16.6

---

model/feature_flags.go

Adds the feature flag for global header. The rest of the feature is in the webapp PR: https://github.com/mattermost/mattermost-webapp/pull/8407
https://mattermost.atlassian.net/browse/MM-37130
```release-note
NONE
```

MM-37130 Add feature flag for global header.

---

api4/team.go
api4/team_test.go
api4/user_test.go
app/app_iface.go
app/opentracing/opentracing_layer.go
app/plugin_api.go
app/team.go
model/client4.go
model/team_member.go
model/thread.go
store/sqlstore/thread_store.go

This is a subset of @calebroseland's PR #17813 with some minor updates. I'll be submitting further PRs to handle the other tickets related to team thread unreads.
https://mattermost.atlassian.net/browse/MM-35392
```release-note
Correctly display unread threads on app load for teams in the sidebar when collapsed threads is turned on.
```

MM-35392 Load thread unreads for other teams on app load

---

app/team.go

PR that got merged after the 6.0 branch got merged to master resulted in an undefined constant.
```release-note
NONE
```

Fix bad merge causing undefined CRT constant

---

Makefile
api4/config_test.go
app/options.go
app/server.go
app/server_test.go
cmd/mattermost/commands/cmdtestlib.go
cmd/mattermost/commands/config.go
cmd/mattermost/commands/config_test.go
cmd/mattermost/commands/db.go
cmd/mattermost/commands/init.go
cmd/mattermost/commands/plugin_test.go
cmd/mattermost/commands/root.go
cmd/mattermost/commands/server.go
config/database.go
config/file.go
config/file_test.go
config/memory.go
config/migrate.go
config/migrate_test.go
config/store.go
config/store_test.go

PR disables the file watching logic for the main config file. This should permanently fix various related issues that were reported by users (e.g. config resets on restart).
Ideally we'd like to remove this logic completely but I see the watcher is also used by the advanced logging system. @wiggin77 let me know if you have any objection or foresee problems in doing that.
https://mattermost.atlassian.net/browse/MM-35470
```release-note
Disabled config file watching logic.
```

[MM-35470] Disable config watching logic

---

api4/license.go
api4/license_test.go
i18n/en.json

Cherry pick of #17933 on cloud.
```release-note
Fixed a panic in the getPrevTrialLicense API request when loading system console on team edition.
```

Automated cherry pick of #17933

---

app/channel.go

Improving a log line from the returned error in `App.addUserToChannel()` to include the underlying store error for better debuggability.
Related discussion in https://github.com/mattermost/mattermost-server/pull/16583#discussion_r675379536
```release-note
NONE
```

Improve error logged from App.addUserToChannel

---

api4/post.go
api4/system.go
api4/system_test.go
app/app_iface.go
app/opentracing/opentracing_layer.go
app/post.go
app/post_test.go

Fixes the authorization of the `POST /api/v4/notifications/ack` API endpoint.
A bunch of places in code just do this channel-scoped authorization check:
```go
a.SessionHasPermissionToChannel(*session, channel.Id, model.PermissionReadChannel)
```
... and a few also do this team-scoped check:
```go
a.SessionHasPermissionToTeam(*session, channel.TeamId, model.PermissionReadPublicChannel)
```
I wasn't inclined to remove the team check as part of this fix, but rather opted to centralize similar checks into a common function. As a future iteration we can determine if the team-scoped permission checks are necessary.
https://mattermost.atlassian.net/browse/MM-37417
```release-note
Fixed the authorization of the POST /api/v4/notifications/ack API endpoint.
```

MM-37417: Push notification authz fix.

---

plugin/api.go

This PR fixes minimum version of the server for categorization methods in plugin api
Fixes https://mattermost.atlassian.net/browse/MM-37314
```release-note
NONE
```

[MM-37314] Fix categorization method version for plugin api

---

app/post.go
app/post_test.go

Cherry pick of #17965 on release-5.38.
Replaces the broken automated cherry-pick in #18026

cherry pick of #17965 on release-5.38

---

app/permissions_migrations.go
store/sqlstore/system_store.go
store/storetest/system_store.go

We make the app migration idempotent by using DB native upsert.
https://mattermost.atlassian.net/browse/MM-36990
```release-note
NONE
```

MM-36990: Use upsert for system key update

---

app/plugin_requests.go
plugin/context.go

Plugin should rely on the `Mattermost-Plugin-ID` header as this makes the HTTP handling more uniform. `Context.SourcePluginId` was already deprecated and this PR removes it.
The only Mattermost affected by this is Workflow. I'm not sure if it's worth fixing it.
https://mattermost.atlassian.net/browse/MM-36899
```release-note
Remove deprecated Context.SourcePluginId field.
```

[M-36899] Remove deprecated SourcePluginId

---

api4/channel_test.go
api4/post_test.go
api4/preference_test.go
app/status.go
model/client4.go
model/custom_status.go

PR removes remaining uses of pointer to slice from  `model`.
https://mattermost.atlassian.net/browse/MM-28985
```release-note
NONE
```
https://github.com/mattermost/enterprise/pull/1042

[MM-28985] Remove pointers to slice (part 2)

---

app/server.go

We used to log an error and move forward, which led to
panics later during server execution, because the templates
don't exist.
While technically speaking the server will run fine
because it's just one HTTP handler goroutine which panics,
but properly handling the error requires much more adjustments
in the code to check for nil templates.
It is better to fail earlier and force the application
to start in a clean slate.
https://mattermost.atlassian.net/browse/MM-37574
```release-note
NONE
```

MM-35754: Fail fast if templates directory is not found

---

app/post_metadata.go
app/slack.go
model/post.go
model/post_test.go
model/slack_attachment.go

We extend the same logic done in https://github.com/mattermost/mattermost-server/pull/16556
to Field.
Also handled the case elsewhere in the code with a light grep
for extra safety.
https://mattermost.atlassian.net/browse/MM-37573
```release-note
NONE
```

MM-37573: Ignore nil fields in attachments

---

model/manifest.go
model/manifest_test.go

This PR replaces the field `Executables` with a `map[string]string`, which can only any combination of platform and executable path. You can find more about this field in https://github.com/mattermost/mattermost-server/pull/14682.
Existing plugin are not affected by this change.
https://mattermost.atlassian.net/browse/MM-27593
```release-note
Convert Executables field in plugin manifest to map
```

[MM-27593] s/AllExecutables/Executables/

---

app/notification.go
app/notification_test.go

Since props is a map[string]interface{}, an ", ok" check doesn't
really help because even if a key is not present, by default, a map
will always return the default value of the value, which would be a
nil interface.
So we can just check for the value of the map instead.
https://mattermost.atlassian.net/browse/MM-37575
```release-note
NONE
```

MM-37575: Handle nil value in override_username

---

app/user.go
app/user_test.go

We use the correct error variable returned from
the store method prior to it.
https://mattermost.atlassian.net/browse/MM-37576
```release-note
NONE
```

MM-37576: Fix reference to incorrect error variable

---

services/telemetry/telemetry.go

Add Focalboard to the list of known plugins to enable telemetry.
```release-note
NONE
```

Add Focalboard to known plugin telemetry

---

app/compliance.go

Found this while investigating https://github.com/mattermost/enterprise/pull/1044.
```release-note
NONE
```

Log error from a compliance job failure

---

model/user.go
model/user_test.go

Remove deprecated `model.ComparePassword` method
https://mattermost.atlassian.net/browse/MM-37677
```release-note
Remove deprecated model.ComparePassword method
```

Remove deprecated model.ComparePassword method

---

config/client.go
model/config.go
services/telemetry/telemetry.go
tests/test-config.json

This PR adds a setting `EnableOnboardingFlow` in the configuration to toggle onboarding flow
[MM-37578](https://mattermost.atlassian.net/browse/MM-37578?atlOrigin=eyJpIjoiNzViZDIyN2MzZTkzNGNhODk0NzRiNmUxY2Y0YWM4ZjAiLCJwIjoiaiJ9)
```release-note
Added a new config setting ServiceSettings.EnableOnboardingFlow
```

[MM-37578] - Add setting for onboarding

---

plugin/client_rpc.go
plugin/supervisor.go

This was caught from a race test failure. While the failure manifested due to a log being
written from a test after the test exited, the real reason was hidden further deeper.
What was happening is that the server would always listen for plugin requests in a
separate goroutine via `g.muxBroker.AcceptAndServe` in the `OnActivate` hook. But the
plugin shutdown process would just close the plugin connections and move on, leading
to the classic case of improperly shut down goroutines.
When this happened, an opportunity opens up in a way that the server
would still be executing a request whereas the main goroutine and therefore the parent
test has already finished. This would lead to an error like
```
{"level":"error","ts":1626451258.4141135,"caller":"mlog/sugar.go:25","msg":"pluginAPI …
```

MM-37165: Fix improper plugin shutdown

---

app/app.go
app/server_test.go

Fixing a possible endless loop in case more of 25 admins are present in the system when `notifyAdminsOfWarnMetricStatus` runs.
```release-note
NONE
```

Fix possible endless loop

---

.circleci/config.yml
.gitlab-ci.yml
build/README.md
build/local-test-env.sh

Upgrade go in the mattermost server builder image to use go 1.16.7
This is a security fix for the golang and need to be cherry picked to the release-5.38
None
```release-note
NONE
```

update mm server builder to use go 1.16.7

---

app/import_functions.go
app/user.go
i18n/en.json
services/users/errors.go
services/users/users.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/user_store.go
store/store.go
store/storetest/mocks/UserStore.go
store/storetest/user_store.go
store/timerlayer/timerlayer.go

Performance insights on recent load-tests highlighted a count query on the `Users` table as one of the most expensive being made. This was used to check whether the user was the first in the system in which case it would get promoted to admin.
To improve performance we are replacing this with a simple check on whether the table is empty which runs in constant time.
A quick load-test showed than on average the `createUser` API call time improved by nearly 40%,
https://mattermost.atlassian.net/browse/MM-37306
```release-note
NONE
```

[MM-37306] Replace db count query in user signup process

---

api4/file_test.go
app/brand.go
app/file.go
app/image.go
app/team.go
app/upload.go
app/user.go
model/config.go
model/utils.go
services/telemetry/telemetry.go
tests/test-config.json

PR adds a new `FileSettings.MaxImageResolution` setting to allow admins to set a custom limit to the dimension of uploaded images. We also raise the default limit to 33MP (8K resolution) which seems like a good compromise that should cover most cases.
https://mattermost.atlassian.net/browse/MM-10166
```release-note
Added a new FileSettings.MaxImageResolution config setting to control the maximum dimension (in pixels) of image uploads.
Removed MB constant from model package.
```

[MM-10166] Add MaxImageResolution config setting

---

app/server_test.go

Config watcher has been removed from codebase.
It is safe to bring this back now.
https://mattermost.atlassian.net/browse/MM-37378
```release-note
NONE
```

MM-37378: Unskip TestPanicLog

---

app/server.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/session_store.go
store/store.go
store/storetest/mocks/SessionStore.go
store/storetest/session_store.go
store/timerlayer/timerlayer.go

- We move logging statements to the upper layer.
Store functions are low-level methods and should return error
upwards rather than logging.
- Used IN instead of any (array ()) which is equivalent.
- Made the delay to be of type time.Duration and un-exported it.
- Unexported the batch size constant.
```release-note
NONE
```

Improve session cleanup

---

services/users/users.go
services/users/users_test.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/user_store.go
store/store.go
store/storetest/mocks/UserStore.go
store/storetest/user_store.go
store/timerlayer/timerlayer.go

I forgot to filter out bot users so first user wasn't getting promoted to admin due to their presence. Added a new test to cover this special case for the future.
https://mattermost.atlassian.net/browse/MM-37898
```release-note
NONE
```

[MM-37898] Exclude bots from initial user store emptiness check

---

app/app_iface.go
app/import_functions.go
app/opentracing/opentracing_layer.go
app/user.go
services/users/users.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/user_store.go
store/store.go
store/storetest/mocks/UserStore.go
store/storetest/user_store.go
store/timerlayer/timerlayer.go

The method was only being used during import and it unnecessarily
made multiple queries to the DB.
Changed to a separate query that just updated the props field.
https://community-daily.mattermost.com/plugins/focalboard/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=e4f9a891-85d6-4886-8590-1e327f7f8b8f
```release-note
NONE
```

Modified updateUserNotifyProps to directly update the field

---

api4/post_test.go
app/post.go

PR fixes an issue introduced in https://github.com/mattermost/mattermost-server/pull/17796. The client expects the post field of the deleted websocket event to be serialized. The additional parsing was hence broken causing a JS error.
https://mattermost.atlassian.net/browse/MM-37846
```release-note
NONE
```

[MM-37846] Fix payload for post deleted event

---

shared/mlog/mlog.go

This PR fixes a racy unit test.  Error logging was resolving all `error` interfaces to a string during formatting which happens asynchronously in a log writer thread.  In this case, due to a recent change for AppErrors, the AppError's fields are modified after the log call thus causing a race.  The fix is to resolve the error to a string in the calling thread and not storing the original `error`.
Other structs and interfaces are already resolved to strings by the caller - `error` was a special case because it has a specific `mlog.Err` generating the log field.
https://mattermost.atlassian.net/browse/MM-38004
```release-note
NONE
```

MM-38004 fix racy unit test

---

build/docker-compose.common.yml
build/elastic/Dockerfile
build/gitlab-dc.common.yml

Using es7 for pipeline because we no longer support es 5 & 6
https://mattermost.atlassian.net/browse/MM-36445
https://github.com/mattermost/enterprise/pull/1020
```release-note
Using es7 in circle ci
```

[MM-36445] Changing elastic search docker version

---

services/remotecluster/mocks_test.go
services/remotecluster/ping_test.go
services/remotecluster/send_test.go
services/remotecluster/sendprofileImage_test.go
services/remotecluster/service_test.go
shared/mlog/tlog.go
web/oauth_test.go

While monitoring CI builds after merging mlog refactor I noticed a build fail with a race condition due to the new mlog.  https://app.circleci.com/pipelines/github/mattermost/mattermost-server/27034/workflows/8750c72a-693b-4cf1-9d41-e9e6eabf3da9/jobs/187950/tests#failed-test-1
~~The issue is a new test helper within mlog that creates a logger using `testing.T` to write the logs.  Unfortunately `testing.T`  is not thread safe and cannot be used in this way.  The fix is to remove this utility (CreateTestLogger) and modify the unit tests to use a different logger.~~
The actual issue is a missed `shutdown` call for a mockServer.  Thanks @agnivade .
https://mattermost.atlassian.net/browse/MM-38016
```release-note
NONE
```

MM-38016 Fix racy unit test (TestService_AddTopicListener)

---

app/command_autocomplete.go
app/context.go
app/plugin_hooks_test.go
app/plugin_requests.go
app/ratelimit.go
app/request/context.go
config/environment_test.go
einterfaces/mocks/AppContextInterface.go
model/client4.go
model/cluster_discovery.go
model/cluster_discovery_test.go
model/cluster_info.go
model/cluster_info_test.go
model/config.go
model/utils.go
model/utils_test.go
plugin/context.go
services/telemetry/telemetry.go
tests/test-config.json
web/context.go
web/handlers.go

This is a the third PR that changes identifies to use more idiomatic naming.
I intentional didn't change the field names of structs that are used to create DB columns as `gorp` doesn't like it when you change field names.
In the future we might be able to enforce this via golangci-lint.
https://mattermost.atlassian.net/browse/MM-23279
```release-note
Renamed plugin.Context.IpAddress to plugin.Context.IPAddress
Renamed fields in the model package to have more idiomatic names
```

[MM-23279] Idiomatic naming (IP)

---

cmd/mattermost/commands/jobserver.go

This was inadvertently removed in https://github.com/mattermost/mattermost-server/pull/17995 but we still need to support this special case.
https://mattermost.atlassian.net/browse/MM-38028
```release-note
NONE
```

[MM-38028] Bring back jobserver command

---

Makefile
scripts/wait-for-system-start.sh

Fixes `make test-data` to work with mmctl now that the cli has removed the `config` and `sampledata` commands.
n/a
```release-note
NONE
```

Fix for test-data make target

---

.circleci/config.yml
.gitlab-ci.yml
build/README.md
build/local-test-env.sh

- Fix internal gitlab pipeline to use the correct image to build the go project
- bring the mattermost go builder to the latest image available to fix any potential security issues in the go language
ref: https://community.mattermost.com/core/pl/6ds66mmm1jnd8xdmrogz6738zw
```release-note
Mattermost server for release-5.38 is now built with go 1.16.7
```

update mattermost go builder to 20210810_golang-1.16.7 and fix gitlab image definition

---

app/plugin.go
model/license.go

This PR solves an issue where Enterprise plugins were not showing for systems with a Professional license. We are now checking the license SKU while preparing the request to be sent to the marketplace.
Fixes https://mattermost.atlassian.net/browse/MM-37494
```release-note
E20, Professional, and Enterprise license SKUs are now supported for installing Enterprise plugins.
```

[MM-37494] Cherrypick #18031: Check for license SKU when preparing marketplace requests

---

.circleci/config.yml
.gitlab-ci.yml
.gitlab-ci/test.yml
build/local-test-env.sh

- bring the mattermost go builder to the latest image available to fix any potential security issues in the go language
ref: https://community.mattermost.com/core/pl/6ds66mmm1jnd8xdmrogz6738zw
```release-note
Mattermost server for release-5.37 is now built with go 1.16.7
```

update mattermost go builder to use go 1.16.7

---

api4/license_test.go
app/license.go

PR fixes flaky `TestRequestTrialLicense/trial_license_user_count_less_than_current_users`. We are using a mock HTTP server to return the trial license instead of relying on an actual network call to `https://customers.mattermost.com/api/v1/trials` which caused the flakyness.
https://mattermost.atlassian.net/browse/MM-36695
```release-note
NONE
```

[MM-36695] Fix flaky TestRequestTrialLicense test

---

i18n/en.json
model/config.go
model/config_test.go

- [ThreadAutoFollow](https://docs.mattermost.com/configure/configuration-settings.html#automatically-follow-threads) must be set to true to enable CollapsedThreads. 
- https://mattermost.atlassian.net/browse/MM-37787
```release-note
The ThreadAutoFollow setting must be set to true to enable CollapsedThreads. Previously, this was stated the Mattermost documentation but not enforced - https://docs.mattermost.com/configure/configuration-settings.html#automatically-follow-threads
```

MM-37787: ThreadAutoFollow must be true to enable CollapsedThreads

---

app/plugin_api_tests/test_db_driver/main.go
store/sqlstore/sqlx_wrapper.go
store/sqlstore/sqlx_wrapper_test.go
store/sqlstore/store.go

This layer embeds the original sqlx object and wraps some
key methods to avoid some boilerplate.
- Add timeout to all methods from the timeout in settings.
- Added trace functionality.
- Added auto-rebind capabilities so that each store method
doesn't need to call rebind every time.
- Added auto-lowering of query string to support NamedExec
for both MySQL and Postgres
All methods are not wrapped as all are likely not to be called
from our code. As and when they are called, support will be added.
```release-note
NONE
```

Added a sqlXPassThrough layer

---

app/auto_responder.go
app/auto_responder_test.go
store/sqlstore/post_store.go
store/storetest/post_store.go

We properly truncate the date part from the createAt time.
The SQL query is improved now to directly return the bool.
Fixed the test to properly test the feature.
https://mattermost.atlassian.net/browse/MM-38132
```release-note
Fixed a bug in auto responder where it would incorrectly calculate the time interval and never send the message.
```

MM-38132: Improve Auto Responder logic

---

model/feature_flags.go

Cherry pick of #18281 on release-6.0.
/cc  @neallred
```release-notes
NONE
```

Automated cherry pick of #18281

---

app/auto_responder.go
app/auto_responder_test.go
store/sqlstore/post_store.go
store/storetest/post_store.go

We properly truncate the date part from the createAt time.
The SQL query is improved now to directly return the bool.
Fixed the test to properly test the feature.
https://mattermost.atlassian.net/browse/MM-38132
```release-note
NONE
```

MM-38132: Improve Auto Responder logic (#18264)

---

model/feature_flags.go

removes the global header feature flag and default value.
**Since this is my first PR in here:** If there is something i am missing here please point it out and I will fix that.
[MM-37838](https://mattermost.atlassian.net/browse/MM-37838)
https://github.com/mattermost/mattermost-webapp/pull/8740
```release-note
NONE
```

[MM-37838] - Remove global header feature flag

---

i18n/en.json
model/config.go
model/config_test.go

```release-note
The ThreadAutoFollow setting must be set to true to enable CollapsedThreads. Previously, this was stated the Mattermost documentation but not enforced - https://docs.mattermost.com/configure/configuration-settings.html#automatically-follow-threads
```

Manual cherry pick of #18253 on release-5.39

---

app/user.go
app/user_test.go

We use the correct error variable returned from
the store method prior to it.
https://mattermost.atlassian.net/browse/MM-37576
```release-note
NONE
```

MM-37576: Fix reference to incorrect error variable (#18066)

---

model/feature_flags.go

Reverts mattermost/mattermost-server#18304
The [webapp PR is not yet ready and merged](https://github.com/mattermost/mattermost-webapp/pull/8740), as a result the global header is hidden for everybody.

Revert "[MM-37838] - Remove global header feature flag"

---

app/license.go
utils/license.go
utils/license_test.go

PR fixes two possible panics that could occur during license validation if the input data was particularly "bad".
1. We were enforcing a minimum length but then proceeded to remove some data (null terminators). Then we assumed the data was long enough. This is what triggered the reported panic.
2. I've also noticed the for loop that took care of removing null bytes didn't have an exit condition so it could panic in case the input data was full of them.
Although this should fix the potential crashes, I am still not sure what could have caused it given the reported panic happened on a license trial request so I am thinking whatever data was returned by `https://customers.mattermost.com/api/v1/trials` triggered this. /cc @marianunez 
https://mattermost.atlassian.net/browse/MM-38321 …

[MM-38321] Fix possible panics during license validation

---

Makefile

After the `disableconfigwatch` flag [went away](https://github.com/mattermost/mattermost-server/pull/17913/files) we were left with a rather generic grep match that would result into killing more than expected (any unrelated process running through `go run`). We fix this by adding an additional filtering.
```release-note
NONE
```

Fix stopping mattermost server

---

.circleci/config.yml

Forgot to commit the suggestion :facepalm: . 
It worked: https://app.circleci.com/pipelines/github/mattermost/mattermost-server/27571/workflows/276bb842-43fe-4bef-b768-f3d62634004b/jobs/193598
```release-note
```

Adjust values waiting for webapp.

---

app/syncables_test.go

We ensure `timeAfterLeaving` is actually after the member's `LeaveTime` otherwise the delete won't happen.
https://mattermost.atlassian.net/browse/MM-36909
```release-note
NONE
```

[MM-36909] Fix flaky TestCreateDefaultMemberships

---

app/app_iface.go
app/opentracing/opentracing_layer.go
app/post.go
app/post_metadata_test.go

PR fixes a potential race that was causing `TestPreparePostForClient/no_metadata_for_deleted_posts` to fail.
We do this by avoiding passing the same post object that `App.DeletePost()` also returns to the goroutine that deletes post attachments. Since we are there we also unexport some methods and only create the goroutine if it's actually needed.
https://mattermost.atlassian.net/browse/MM-37757
```release-note
NONE
```

[MM-37757] Fix racy test TestPreparePostForClient

---

model/feature_flags.go

Remove invite members button feature flag. Related to https://github.com/mattermost/mattermost-webapp/pull/8800
QA not needed on this PR; the change in UI will be tested in the related webapp PR.
https://mattermost.atlassian.net/browse/MM-38258
```release-note
Remove invite members button feature flag
```

remove feature flag

---

app/syncables_test.go

This caused several grams of CO2 emissions on the CI pipeline.
```release-note
NONE
```

Fix flaky TestCreateDefaultMemberships (#18330)

---

app/email/email_batching.go
app/notification.go
app/notification_email.go
app/notification_push.go
i18n/en.json
model/user.go

Updates texts of push and email notifications when the user has CRT "on"
and the post is a reply to a thread.
https://mattermost.atlassian.net/browse/MM-38093
```release-note
NONE
```

MM-38093: updates notifications copy on CRT replies

---

app/webhook_test.go
model/post.go

Bumping the limit now that the column datatype supports it. I've simply multiplied existing values by 100 to give plenty of new space but still have some sort of protection against post bombs. Let me know if you had other numbers in mind.
https://mattermost.atlassian.net/browse/MM-25018
```release-note
Increased Post.Props size limit to 800,000 characters.
```

[MM-25018] Bump Post.Props size limits

---

app/server.go

PR disables running the admin support email job on server startup. The scheduled check (once per week) remains unchanged.
https://mattermost.atlassian.net/browse/MM-36537
```release-note
Disabled admin support email status check job on server startup.
```

[MM-36537] Disable admin support email check job on server startup

---

Makefile

The `BuildDate` flag was set at compile time as the current datetime, what makes the go compiler cache useless for the model package.
This change should save some compilation time.
```release-note
NONE
```

Set BuildDate compile flag to dev during development

---

model/feature_flags.go

Sets the default value for the global header feature flag to `true` until we are ready to remove the feature flag completely. This should be possible once [#8740](https://github.com/mattermost/mattermost-webapp/pull/8740) is merged. It depends on another PR to be merged beforehand, that is already up and in review from @deanwhillier: [#8862](https://github.com/mattermost/mattermost-webapp/pull/8862)
this is a replacement for #18397 for the 6.0 release.
no ticket was created for this
```release-note
NONE
```

global header feature flag value

---

store/sqlstore/post_store.go

When a post is edited we should not update the thread recency
(LastReplyAt).
https://mattermost.atlassian.net/browse/MM-37896
```release-note
NONE
```

MM-37896: thread recency when updating a post

---

api4/system_test.go
app/post_metadata.go
app/post_metadata_test.go
model/post.go

Cherry pick of #18400 on release-6.0.
/cc  @mkraft
```release-note
NONE
```

Automated cherry pick of #18400

---

app/file.go

- Review of current situation: We've been getting these errors:
```
{"timestamp":"2021-09-17 18:06:02.129 Z","level":"debug","msg":"generateMiniPreview: prepareImage failed","error":"prepareImage: failed to decode image: imaging: failed to decode image: image: unknown format"}
```
Looking at the logs, it seems that we get a few of those every day normally. But since the last update to daily (about 13 hours ago) we've been getting spikes of up to 685 errors over a 10 minute period.
The error is reported in `prepareImage`: https://github.com/mattermost/mattermost-server/blob/96593580aeea0bc3a4780e5284ab199f5e19bc83/app/file.go#L1127-L1131
If you continue down the call stack, the image library's `sniff` reports the bytes are not an image format (line 89 in `format.go`). 
So, in …

MM-38635 - Debug statements for prepareImage errors on community-daily

---

cmd/mattermost/commands/import.go

We are bringing back the `import` command (and related subcommands) until the `mmctl` counterpart gets full functionality coverage. The `export` command was never removed in the first place so no change is needed there.
@amyblais This will need cherry-picking to 6.0 . Also it will require a small update to the existing release notes.
https://mattermost.atlassian.net/browse/MM-38640

[MM-38640] Revert `import` command deprecation

---

api4/shared_channel.go
api4/shared_channel_test.go
model/shared_channel.go
store/sqlstore/shared_channel_store.go
store/storetest/shared_channel_store.go

getSharedChannels rest API should only return channels the user is a member of, unless the user has "manage_shared_channels" permission.
https://mattermost.atlassian.net/browse/MM-38611
```release-note
NONE
```

MM-38611 getSharedChannels: only return channels user is member of

---

app/email/email_test.go
templates/cloud_trial_end_warning.html
templates/cloud_trial_end_warning.mjml

This PR ensures that when cloud trial emails ending warning emails have the Support Email defaults to `feedback-cloud@mattermost.com`
[MM-36603](https://mattermost.atlassian.net/browse/MM-36603)
```release-note
NONE
```

[MM-36603] - Text is cut-off on the bottom of the 14-day trial 3 day to end of trial email notification

---

app/post_metadata.go

Cherry pick of #18437 on cloud.
```release-note
NONE
```

Automated cherry pick of #18437

---

shared/mlog/global.go
store/sqlstore/store.go
store/sqlstore/upgrade.go

Our store upgrade methods used mlog.Critical and then slept
for a second and triggered os.Exit.
First of all, with the new mlog refactor Critical wasn't a standard
log level so it was never to be logged.
And secondly, this completely missed the fact that there already
existed an API method Fatal which did exactly this.
We mark the Critical API as deprecated, and use Fatal for all
occurences.
The choice should be between either to use Error or Fatal.
While here, we also remove the non-standard exit codes which
just confused things further while debugging.
https://mattermost.atlassian.net/browse/MM-38712
```release-note
NONE
```

MM-38712: Flush logs while exiting from store upgrade

---

shared/mlog/global.go
store/sqlstore/store.go
store/sqlstore/upgrade.go

Our store upgrade methods used mlog.Critical and then slept
for a second and triggered os.Exit.
First of all, with the new mlog refactor Critical wasn't a standard
log level so it was never to be logged.
And secondly, this completely missed the fact that there already
existed an API method Fatal which did exactly this.
We mark the Critical API as deprecated, and use Fatal for all
occurences.
The choice should be between either to use Error or Fatal.
While here, we also remove the non-standard exit codes which
just confused things further while debugging.
https://mattermost.atlassian.net/browse/MM-38712
```release-note
NONE
```

MM-38712: Flush logs while exiting from store upgrade (#18438)

---

app/post_metadata.go
app/post_metadata_test.go

We were ignoring post not found errors, but moving forward nevertheless. This led to nil dereference panics.
To fix this, we return for any error but exclude from logging the error if it was a not found error.
And we also add a unit test and revert some of the old code.
https://mattermost.atlassian.net/browse/MM-38657
```release-note
NONE
```

MM-38657 - Sentry crash: Fix nil dereference when post not found

---

shared/mlog/global.go
store/sqlstore/store.go
store/sqlstore/upgrade.go

Our store upgrade methods used mlog.Critical and then slept
for a second and triggered os.Exit.
First of all, with the new mlog refactor Critical wasn't a standard
log level so it was never to be logged.
And secondly, this completely missed the fact that there already
existed an API method Fatal which did exactly this.
We mark the Critical API as deprecated, and use Fatal for all
occurences.
The choice should be between either to use Error or Fatal.
While here, we also remove the non-standard exit codes which
just confused things further while debugging.
https://mattermost.atlassian.net/browse/MM-38712

Flush logs when exiting from store upgrade

---

build/Dockerfile

- update base container image from alpine 3.12 to 3.14
- update default mm package to 5.39.0
```release-note
update base container image from alpine 3.12 to 3.14
```

Update base container image from alpine 3.12 to 3.14

---

api4/file_test.go
app/file.go

- a fix to try to narrow down whether  generateMiniPreview is causing the community OOM issue
- add prefix `invalid-` to MimeType to prevent image from entering the generateMiniPreview
- https://mattermost.atlassian.net/browse/MM-38774
```release-note
NONE
```

MM-38774 - partial fix for: Community running out of memory

---

plugin/client_rpc.go

- prevent RPC connections from crashing when PreviewPosts are sent to plugins
- split from https://github.com/mattermost/mattermost-server/pull/18445 to keep the commit logs clean
- https://mattermost.atlassian.net/browse/MM-38774
```release-note
NONE
```

register PreviewPost for RPC connections

---

api4/post.go
app/app_iface.go
app/opentracing/opentracing_layer.go
app/post.go
app/post_metadata.go
app/post_metadata_test.go

A FileInfo object contained a MiniPreview which is
a slice of bytes. This can be particularly costly
while marshalling to plugin hooks.
We avoid this by refactoring the Embeds and Images
population to a separate method and calling that
to prevent posts from getting updated.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=9c0b5413-5401-4ef2-83d5-b9f756585bbc
```release-note
NONE
```

Exclude sending file metadata to plugin hooks

---

model/feature_flags.go

Sets the default value for the global header feature flag to `true` until we are ready to remove the feature flag completely. This should be possible once [#8740](https://github.com/mattermost/mattermost-webapp/pull/8740) is merged. It depends on another PR to be merged beforehand, that is already up and in review from @deanwhillier: [#8862](https://github.com/mattermost/mattermost-webapp/pull/8862)
no ticket was created for this
```release-note
NONE
```

global header feature flag default value

---

api4/post.go
app/channel.go
app/post.go
app/reaction.go
app/webhook.go
i18n/en.json

I removed all the mentions of the read only error and now you can post, react and pin just like any other channel. That can be disabled with the permissions in system console.
Town square still has some exceptions to the regular permissions though where you can't leave the channel, change it's type or archive it.
https://mattermost.atlassian.net/browse/MM-38579
```release-note
NONE
```

[MM-38579] Removing some town square permissions stuff

---

store/sqlstore/post_store.go
store/storetest/post_store.go

Previously, we used to send all flagged posts. This created some weird problems with Sysadmins, which had the permissions to see the channels, but they were not member of them (which implied certain values not being available in redux).
To solve this, we are only returning the flagged posts for channels where the user is a member of.
We also have refactored the getFlaggedPosts functions to unify the query string, in a similar fashion to what is being done in the search function.
None
```release-note
Get flagged posts endpoint will return now only flagged posts for channels the user is member of.
```

Only consider flagged posts that are on channels you are member of

---

build/release.mk

build: set 600 permission to config.json when packagin the app
Jira: https://mattermost.atlassian.net/browse/MM-38542
```release-note
NONE
```

build: set 600 permission to config.json when packagin the app

---

.circleci/config.yml

This is the initial work to cleanup the docker repositories and push images tot he official repositories (`mattermost/mattermost-enterprise-edition` / `mattermost/mattermost-team-edition`) only official releases and not testing/prs images
the testing/prs images will be pushed to `mattermost/mm-te-test` and `mattermost/mm-ee-test`
to avoid any breaks for now we will push to both places, after we make sure everything is clean and correct we will do a follow up to remove the push to `mattermost/mattermost-enterprise-edition`
JIRA: https://mattermost.atlassian.net/browse/DOPS-632
webapp: https://github.com/mattermost/mattermost-webapp/pull/8987
enterprise: https://github.com/mattermost/enterprise/pull/1073
Matterwick: https://github.com/mattermost/matterwick/pull/30
```release-note
NONE
``` …

docker/build: push image to the testing repository

---

app/email/email.go
templates/cloud_trial_end_warning.html
templates/cloud_trial_ended_email.html
templates/invite_body.html
templates/invite_body.mjml
templates/license_up_for_renewal.html
templates/reset_body.html
templates/verify_body.html
templates/welcome_body.html

Some code from the style.mjml partial was not built into some generated templates when `make build-templates` is run. This means there's a diff when `make build-templates` is run on master, which shouldn't be the case.
From the diff files, only the invitation template has changes that are not just CSS classes. However, it still renders as before
The guest email template was failing as a result of this change. This was expected due to a change in the past that updated the card.mjml partial for messages notification like mentions and batch email but didn't consider the fact that guest invitation templates also use it.
[MM-39072](https://mattermost.atlassian.net/browse/MM-39072)
```release-note
NONE
```

[MM-39072] - Run make build-templates on latest master

---

model/integration_action.go
model/integration_action_test.go

We check for nil pointer before moving ahead.
https://mattermost.atlassian.net/browse/MM-38497
```release-note
NONE
```

MM-38497: Fix Sentry crash in PostAction.Equals

---

config/diff_test.go
model/config.go
model/config_test.go

Cherry pick of #18132 on release-6.0.
/cc  @sbishel
```release-note
NONE
```

Automated cherry pick of #18132

---

app/web_conn.go
app/web_conn_test.go

Cherry pick of #18840 on release-6.1.
```release-note
NONE
```

Automated cherry pick of #18840

---

model/auditconv.go
model/auditconv_test.go

Removing command arguments from `auditCommandArgs`.
https://mattermost.atlassian.net/browse/MM-39448
```release-note
NONE
```

[MM-39448] Remove command arguments from auditCommandArgs

---

app/server.go
services/searchengine/bleveengine/bleve.go
services/searchengine/bleveengine/bleve_test.go
services/searchengine/bleveengine/indexer/indexing_job_test.go
services/searchengine/searchengine.go
services/telemetry/telemetry_test.go
store/searchlayer/layer_test.go
testlib/helper.go

The job server field was not being used. We remove it
as part of a cleanup of server initialization refactor.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=8a171d5e-4398-4bc9-8fbf-8b9b14f37069
```release-note
NONE
```

Remove job server dependency searchengine

---

app/plugin.go
app/server.go
plugin/environment.go

We were incorrectly calling to start PluginHealthCheckJob
without initializing the plugins environment.
To fix this, we move the code inside initPlugins right after
the environment is initialized.
To respond to config changes, we call it again from pluginsEnvironment.Shutdown
which gets called from ConfigListener when plugins are disabled. And initPlugins
is anyways called again from ConfigListener which plugins are enabled,
so we can avoid checking for PluginSettings.Enable again in the call.
We also rename the method to better indicate its nature.
During this, we also uncover and fix another bug where disabling
plugins would not shut down plugins at all because we were calling
s.GetPluginsEnvironment() directly which returns nil if plugins
were disabled. The approach we follow is to …

Fix PluginHealthCheckJob

---

model/feature_flags.go

This PR removes DownloadAppsCTA from FeatureFlags model
[MM-39503](https://mattermost.atlassian.net/browse/MM-39503)
```release-note
Removed the DownloadAppsCTA feature flag
```

[MM-39503] - Remove DownloadApps Feature Flag

---

app/notification.go
app/post.go
app/post_metadata.go

Checks for presence of slice before index access.
TODO:
https://mattermost.atlassian.net/browse/MM-39420
```release-note
Fixes bug caused by accessing an empty slice by index.
```

MM-39420: Checks for presence of slice before index access.

---

app/notification.go
app/post.go

Cherry pick of #18826 on cloud.
/cc  @mkraft
```release-note
NONE
```

Automated cherry pick of #18826

---

app/server.go

Cloud workspaces are on a monthly subscription where the license expiration does not apply. They do not need to renew or update a license so they should not get prompted to renew. 
This PR checks if the license if for `cloud` and if so, it will skip the license expiration checks and avoid sending the renew now email to admins.
https://mattermost.atlassian.net/browse/MM-39804
Webapp changes: https://github.com/mattermost/mattermost-webapp/pull/9318
```release-note
NONE
```

MM-39804 - Remove license expiration checks for cloud

---

app/status.go

This was being run every 5 minutes and unnecessarily clogs up
the logs. No other job makes a debug log before starting up.
```release-note
NONE
```

Remove DND run debug log

---

store/sqlstore/tokens_store.go

Migrate from `gorp` to `sqlx` in `store/sqlstore/tokens_store.go`
Fixes #18868 
JIRA - https://mattermost.atlassian.net/browse/MM-39630
```release-note
NONE
```

[MM-39630] - Migrate from gorp to sqlx in store/sqlstore/tokens_store.go

---

app/app.go
app/app_iface.go
app/channels.go
app/cluster_handlers.go
app/opentracing/opentracing_layer.go
app/plugin.go
app/plugin_event.go
app/plugin_install.go
app/plugin_requests.go
app/plugin_shutdown_test.go
app/plugin_signature.go
app/plugin_statuses.go
app/plugin_test.go
app/server.go

We move all plugin related fields under *Channels.
This essentially migrates several methods from being under
*Server to under *Channels.
We also move the plugin startup and shutdown code
to be under Channels.Start and Channels.Shutdown.
While here, we remove the getPluginPublicKeyFiles
method which was a one-line method which uselessly
returned an error.
Lastly, we fix the product initialization order which
was incorrect previously. Products are dependent on
the main server.
So startup should be products -> server.
And shutdown should be server -> products.
```release-note
NONE
```

Move plugins under Channels

---

model/feature_flags.go

This PR adds a feature flag to toggle the App Bar for https://github.com/mattermost/mattermost-webapp/pull/9273
Fixes https://mattermost.atlassian.net/browse/MM-39820
```release-note
NONE
```
https://github.com/mattermost/mattermost-webapp/pull/9273

[MM-39820] Add AppBarEnabled feature flag

---

api4/channel.go

https://github.com/mattermost/mattermost-server/pull/18531 introduced an accidental bug where you couldn't use the patch endpoint for the Town Square without specifying a channel name, so the endpoint couldn't be used to update the `Channel.Description` field.
https://mattermost.atlassian.net/browse/MM-40003
```release-note
NONE
```

MM-40003 Fix patch route for Town Square

---

api4/plugin.go
api4/plugin_test.go
app/app.go
app/app_iface.go
app/channels.go
app/integration_action.go
app/notification_push_test.go
app/opentracing/opentracing_layer.go
app/plugin.go
app/plugin_api.go
app/plugin_api_test.go
app/plugin_commands.go
app/plugin_commands_test.go
app/plugin_hooks_test.go
app/plugin_install.go
app/plugin_install_test.go
app/plugin_requests.go
app/plugin_requests_test.go
app/plugin_test.go
app/server.go
web/web_test.go

We move pluginCommands, pluginCommandsLock
into Channels.
We also move the plugin related route handlers
under Channels and move the init code under
NewChannels. To achieve this, the router initialization
is bumped up.
Along with it, we clean up some App methods
which were just wrappers over Channel methods.
Instead, we call the Channel method directly
to make things more readable and easy to understand.
```release-note
NONE
```

Move pluginCommands into Channels

---

api4/system.go
config/client.go
model/config.go
services/telemetry/telemetry.go
tests/test-config.json

`DesktopMinVersion` and `DesktopLatestVersion` are config items that don't do anything. Since they were never finished, we've elected to remove them.
https://mattermost.atlassian.net/browse/MM-39374
```release-note
Removed DesktopLatestVersion and DesktopMinVersion config items
```

[MM-39374] Remove DesktopLatestVersion and DesktopMinVersion

---

app/notification_push.go
app/notification_push_test.go

Sender name is missing in the reply of a thread message.
https://mattermost.atlassian.net/browse/MM-38508
```
NONE
```

MM-38508  CRT: DM notification missing the sender name

---

model/feature_flags.go

This PR removes `PrewrittenMessages` feature flag
[MM-39504](https://mattermost.atlassian.net/browse/MM-39504)
```release-note
NONE
```

[MM-39504] - Remove Prewritten Messages Feature Flag

---

app/plugin_api.go
app/session.go
i18n/en.json
plugin/api.go
plugin/api_timer_layer_generated.go
plugin/client_rpc_generated.go
plugin/plugintest/api.go

This PR adds CRUD methods for users session which will be used in the app specific sessions work.
~~Heads up that the PR includes the commits from https://github.com/mattermost/mattermost-server/pull/18443 as the work on app specific sessions will require changes from that PR. https://github.com/mattermost/mattermost-server/pull/18443 can't be targeted as it's from a fork.~~
~~The real changes are in [`2541016` (#18958)](https://github.com/mattermost/mattermost-server/pull/18958/commits/2541016b442b35e1465c098055a4f5d5b146841a).~~
https://mattermost.atlassian.net/browse/MM-39851
```release-note
Added Add CRUD methods for user sessions to plugin API 
```

[MM-39851] Add CRUD methods for user sessions to plugin API

---

api4/apitestlib.go
api4/websocket_test.go
app/web_conn.go
app/web_hub.go
app/web_hub_test.go
app/websocket_router.go
model/websocket_client.go

The reconnect phase of a websocket was split into two parts:
one where we check if a connection with a given connectionID
exists or not. And second, where we remove that connection
and insert the new connection again in the index.
This would lead to a race where it would be possible
for 2 concurrent requests for the same connectionID to go through
which would lead to separate goroutines working on the same dead queue.
We simplify this by removing the connection from the index
in the check connection stage itself. And then just add that
during register phase.
And to distinguish between a fresh and an old connection, we add
a new field called reuseCount.
While here, we also cleanup some old comments and add more
in some places.
https://mattermost.atlassian.net/browse/MM-39612 …

MM-39612: Make acquiring and removing connections atomic

---

store/sqlstore/thread_store.go
store/storetest/thread_store.go

In some cases, an invalid participant id like an empty string
might creep into the database. It's not exactly clear
how can this happen, but if it does, then it breaks the logic
of assuming that the users slice will contain all users
in the participants slice.
To prevent this, we check if a match was found before
adding it in the slice.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/7sixm4t7c6rsr3d8ydxbtfgy9gr
```release-note
NONE
```

MM-39341: Sentry crash: nil dereference in *User.ClearNonProfileFields

---

app/post.go
app/post_test.go
model/websocket_message.go
model/websocket_message_test.go

Running the latest version of the load-test tool (which includes some coverage for permalink previews) consistently triggered a data race related crash on 6.0+ builds. 
We fix the race by implementing (and using) a non-recursive deep copy method for `model.WebSocketEvent`. I've included a test case that triggered the crash and also executed an additional load-test running this PR's build which completed without further issues.
https://mattermost.atlassian.net/browse/MM-40016
```release-note
Fixed a potential server crash when creating or updating posts with permalink previews.
```

[MM-40016] Implement deep copy method for model.WebSocketEvent

---

config/logger.go

The default log rotation size was mistakenly set to 10GB for V6.  The rotation size is supposed to be specified in megabytes but I think the default was mistakenly changed thinking it was KB.
This PR reverts the default to 100MB. 
https://mattermost.atlassian.net/browse/MM-40191
```release-note
Default log rotation file size was mistakenly set to 10GB for V6, and is now reverted back to 100MB.
```

Change default log rotation size to 100MB 

---

jobs/resend_invitation_email/worker.go

Some installations started to throw panic errors, stack trace pointed to this line. Old cloud installations/invitations may not have had this value populated in the System store, so we should treat nil as the default "0" case.
https://mattermost.atlassian.net/browse/MM-40342
```release-note
None
```

[MM-40342] Fix panic in Mattermost Server for cloud installations

---

model/version.go
store/sqlstore/upgrade.go

- Prepare db for 6.3
need to wait for https://github.com/mattermost/mattermost-server/pull/19085 being merged and then I will rebase and this can be merged
n/a
```release-note
Prepare db for 6.3
```

Prepare db for 6.3

---

app/post_metadata.go

Fixes a parameter used with an invocation of `(*App).getEmbedsAndImages` which led to the re-retrieval of OpenGraph data from external servers because [the database lookup](https://github.com/mattermost/mattermost-server/blob/master/app/post_metadata.go#L505-L510) was being skipped.
https://mattermost.atlassian.net/browse/MM-39433
```release-note
Fixed slow channel loading for instances with website link previews enabled.
```

MM-39433: Fixes (*App).getEmbedsAndImages parameter.

---

web/handlers.go
web/handlers_test.go

Attempting to parse an empty flag would
result in a spurious log line which would
clog up the console.
```release-note
NONE
```

Do not parse developer flags if empty

---

jobs/resend_invitation_email/worker.go

The telemetry 'interval' for the re-invite after 24 hours and the second re-invites (48 and 72) is matching these durations properly.
[MM-40345](https://mattermost.atlassian.net/browse/MM-40345)
```release-note
NONE
```

[MM-40345] - Fix telemetry in resend invite email job

---

model/license.go
utils/license.go

This PR adds the isGovSku value to the license model so we can use the isGov value to show the Gov references in the webapp license page.
https://mattermost.atlassian.net/browse/MM-40222
- Has webapp changes (https://github.com/mattermost/mattermost-webapp/pull/9448)
```release-note
NONE
```

MM-40222 - show gov references in license page when gov license

---

model/feature_flags.go

Cherry pick of #18885 on cloud.
/cc  @pablovelezvidal
```release-note
NONE
```

Automated cherry pick of #18885

---

store/sqlstore/store.go

The old comment wasn't exactly clear on
why is it needed to spawn a new connection.
```release-note
NONE
```

Clarify comment on golang-migrate connection

---

build/release.mk
scripts/download_mmctl_release.sh

- now we are generating and making that public the amr64 binary for linux/osx for mmctl
so now we can include that in the arm64 package as well
/cc @jasonblais another step to have the mattermost available in arm64 with the same components we have in the amd64
```release-note
build: add mmctl to arm64 packages
```

build: add mmctl to arm64 packages

---

api4/websocket.go
api4/websocket_test.go
app/web_conn.go
app/web_conn_test.go
app/web_hub.go
config/client.go
model/config.go

The feature is stable enough to be removed
as a config knob.
For backwards compatiblity with older mobile
clients, we keep sending the config param
as true for client config requests.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/7m95frqbk9o8zxin6xo9c7iusoh
```release-note
The config setting ServiceSettings.EnableReliableWebSockets has been removed, and for compatiblity with older clients, the server will always return true for the /v4/config/client endpoint.
```
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/5843
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/9430

Remove reliable websockets configuration

---

api4/websocket_test.go
app/web_conn.go
model/websocket_client.go
model/websocket_client_test.go
model/websocket_request.go

Our websocket handler currently expects JSON only messages which are text based by nature. This can be problematic and inefficient if we need to send binary data (e.g. to allow for compression). PR adds support for receiving binary (messagepack encoded) content in websocket requests.
https://mattermost.atlassian.net/browse/MM-40485
```release-note
Added server support for receiving binary (messagepack encoded) websocket messages.
```

[MM-40485] Enable receiving binary websocket messages

---

app/brand.go
app/channels.go
app/file.go
app/server.go
app/slack.go
app/team.go
app/upload.go
app/user.go

We move these fields to Channels:
```
uploadLockMapMut sync.Mutex
uploadLockMap    map[string]bool
imgDecoder *imaging.Decoder
imgEncoder *imaging.Encoder
dndTaskMut sync.Mutex
dndTask    *model.ScheduledTask
```
I think this PR should conclue the initial phase
of migrating stuff from Server to Channels.
The remaining task would be to focus on continue
to create the remaining services from the
common things like users, teams, push notifications,
clustering for other products to consume.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/87df1e15-588e-49ff-8bd1-ffa9651b8c82
```release-note
NONE
```

Remove the remaining fields from *app.Server

---

api4/role.go
app/app_test.go
app/migrations.go
app/permissions_migrations.go
app/plugin_api.go
app/scheme.go
model/migration.go
model/permission.go
model/role.go
model/scheme.go
plugin/api.go
plugin/api_timer_layer_generated.go
plugin/client_rpc_generated.go
plugin/plugintest/api.go
store/sqlstore/integrity_test.go
store/sqlstore/scheme_store.go
store/sqlstore/upgrade.go
store/storetest/scheme_store.go
testlib/store.go

Adding roles and permissions for playbooks. None of these are used on the server. They will be used in an upcoming PR for the playbooks product.
This also adds a function to the plugin API to handle checking if a set of roles grant a specific permission. `RolesGrantPermission`
Permissions added:
- PermissionPublicPlaybookCreate
- PermissionPublicPlaybookManageProperties
- PermissionPublicPlaybookManageMembers
- PermissionPublicPlaybookView
- PermissionPublicPlaybookMakePrivate
- PermissionPrivatePlaybookCreate
- PermissionPrivatePlaybookManageProperties
- PermissionPrivatePlaybookManageMembers
- PermissionPrivatePlaybookView
- PermissionPrivatePlaybookMakePublic
- PermissionRunCreate
- PermissionRunManageProperties
- PermissionRunManageMembers
- PermissionRunView
Roles added:
- …

MM-38150 Adding playbooks permissions

---

app/plugin_commands.go
app/plugin_commands_test.go

This was an interesting crash detected via Sentry.
Typically, any HTTP status code outside 100-999 range
will cause a crash in the HTTP server. And `ExecuteCommand`
is the only plugin hook which returns a model.AppError
instead of error.
So an incorrect plugin implementation could return
a status code of 0, and crash the server. We handle that
by rewriting any illegal response code to 500.
https://mattermost.atlassian.net/browse/MM-40469
```release-note
NONE
```

MM-40469: Handle invalid response codes from plugins

---

shared/mfa/mfa_test.go

The TestValidateToken was actually testing
the underlying library rather than testing our code.
So, in a way, it was ineffective.
The actual flaky test was that in a rare case,
the random string generated might actually lead
to 000000 being an actual code rather than invalid.
So using random strings is fundamentally incorrect.
Even the tests in the library use hardcoded strings
and not random strings.
To fix this properly would be to use hardcoded strings,
but then we would just be testing the library
and not our code. To keep things simple,
we just keep the test to verify the error message
and remove the others.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/cidjhgy1ag3yktn5eszae1 …

Remove unnecessary test TestValidateToken

---

build/release.mk
scripts/download_mmctl_release.sh

follow up of https://github.com/mattermost/mattermost-server/pull/19090 that broke the workflow when using the script outside the scope of the release/package rules (https://github.com/mattermost/mattermost-server/pull/19090#issuecomment-990885589)
tested on `mac amd64` / `linux arm64` and `linux amd64` all working now
cc @mtardy thanks for letting us know that, it was my fault
```release-note
NONE
```

fix mmctl download script when using as stand alone script

---

app/plugin.go
app/plugin_test.go

This PR fixes a panic in the initPlugins function that was occurring due to pluginsEnvironment being nil at initialising
[MM-40682](https://mattermost.atlassian.net/browse/MM-40682)
```release-note
NONE
```

[MM-40682] - SIGSEGV after upgrade from 6.1.0 to 6.2.0

---

api4/apitestlib.go
api4/file_test.go
api4/team_test.go

Use `testing.TB` instead of `t *testing.T` for helper methods in `api4/apitestlib.go` so benchmarks can also use them.
https://mattermost.atlassian.net/browse/MM-40654
```release-note
NONE
```

Allow go benchmarks to use api helpers functions

---

model/feature_flags.go

adds a feature flag (`MM_FEATUREFLAG_INLINEPOSTEDITING`) to enable inline post editing, defaulting to `false`
[MM-29137](https://mattermost.atlassian.net/browse/MM-29137)
```release-note
Added a new feature flag `INLINEPOSTEDITING` to enable inline post editing
```

[MM-29137] - adding a feature flag for inline post editing

---

store/sqlstore/link_metadata_store.go
store/storetest/link_metadata_store.go

Due to what I get from https://community.mattermost.com/core/pl/r453amcdmfrtpdjduinyi8arje I think it's ok to overwrite if we have same url and timestamp for the link. Otherwise we may need to do a db read before try inserting new value. 0/5 on either solution and I might be missing some context.
https://mattermost.atlassian.net/browse/MM-39542
```release-note
NONE
```

[MM-39542] Allow upsert for duplicate key in LinkMetadataStore

---

store/sqlstore/upgrade.go

Cherry-pick of #18669
This PR partially missed out in the release branch.
```release-note
NONE
```

Cherry-pick of #18669 Drop existing default on Users.Timezone prior to column type change

---

store/sqlstore/post_store.go

This query deals with posts already created,
and it was originally already querying replica.
In recent performance investigations, this came up
a lot of times. I believe the change to query master
was unintentional.
```release-note
NONE
```

MM-40801: Use replica for getPostsAround

---

store/sqlstore/post_store.go

This PR optimizes the reply count query to use only
the indexed column to count the rows rather than using
the ID column. This results in an index-only scan
rather than an index scan. As a result, the query
can be satisfied directly by scanning the index
and there is no need to touch the heap.
Count(*) also gives the same result, but is not recommended
as it also verifies non-null columns and can take slightly
longer.
Before:
```
explain analyze SELECT p.*, (SELECT COUNT(Posts.Id) FROM Posts WHERE Posts.RootId = (CASE WHEN p.RootId = '' THEN p.Id ELSE p.RootId END) AND Posts.DeleteAt = 0) AS ReplyCount FROM Posts p WHERE (CreateAt < (SELECT CreateAt FROM Posts WHERE Id = 'bguxt6zzcjytpffgza3dc7xody') AND p.ChannelId = '5xmynf36cinrzksuzhq7my1nbc' AND DeleteAt = 0) ORDER BY p.ChannelId, …
```

MM-40799: Improve ReplyCount query

---

shared/filestore/s3store.go

When copying/moving files in the minio server, the code was defining the Encryption value as default to SSE-S3 which was failing as expected as exposed in minio ticket https://github.com/minio/minio/issues/6367#issuecomment-416182961. This PR adds a check to validate the value of AmazonS3SSE config and if it is set to true, then define the encryption.
https://mattermost.atlassian.net/browse/MM-40752
```release-note
NONE
```

MM-40752 - set encryption when copying files to minio honoring config defined value

---

app/post_metadata.go
app/post_metadata_test.go

This PR adds the `Accept-Language` header to the Link Preview request, with its value set to the Default Server Language. If the external server allows this header, it should return content in the language specified.
There aren't any UI changes involved in this PR - but heres a screenshot of the end result for reference:
|  Link preview with server localization settings  | 
|----|
| ![mattermost-link-preview-localized](https://user-images.githubusercontent.com/26177230/145916056-ae597445-363c-4fc6-b5fb-90d6875cfc3e.png) | 
https://mattermost.atlassian.net/browse/MM-40560
```release-note
Add Accept-Language header to generate link previews in the Default Server language
```

[MM-40560] Add Server locale to link preview request

---

store/sqlstore/retention_policy_store.go
store/storetest/retention_policy_store.go

Due to the store method having named returns, the variable
was getting set to nil instead of being an empty slice.
We missed this during code review.
https://mattermost.atlassian.net/browse/MM-40594
```release-note
NONE
```

MM-40594: Fix nil retention policies

---

Makefile
go.tools.mod
go.tools.sum
model/team_member.go
model/user_serial_gen.go

- Fixed the Makefile command so that it can be run in CI
- Changed to go install to make it compatible with >1.16 versions.
- Removed unnecessary lines in go.tools.mod now that we aren't using that.
```release-note
NONE
```

MM-40852: Fix make gen-serialized breakage

---

store/sqlstore/channel_store.go

- Fix ChannelMembers select for null columns
- https://mattermost.atlassian.net/browse/MM-37013
```release-note
Fixes issue with query in the async job that fixes channel unreads caused by an earlier CRT migration.
```

[MM-37013]: Fix store get for null columns

---

api4/apitestlib.go
api4/user.go
api4/user_test.go
app/app_iface.go
app/login.go
app/opentracing/opentracing_layer.go
model/session.go

The CWS has this page https://customers.mattermost.com/cloud/connect-workspace . We want to be able to autofill the company domain field based on a cookie set by a user's workspace after they logged into it. Atm, the cookie will hold a value of the last workspace the user interacted with.
[MM-39583](https://mattermost.atlassian.net/browse/MM-39583)
https://github.com/mattermost/customer-web-server/pull/639
```release-note
NONE
```

[MM-39583] - Intermediary web login page: Workspace Cookies

---

config/database.go
config/utils.go
config/utils_test.go

Stumbled upon this when troubleshooting issue reported to Mattermost Operator https://github.com/mattermost/mattermost-operator/issues/269.
When `postgresql` schema designator is used in the connection string passed with `MM_CONFIG` env the Mattermost server treats it as a file path, not a database connection string.
According to Postgres docs, both designators are valid https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING so I think it would make sense to support both.
> The URI scheme designator can be either postgresql:// or postgres://.
```release-note
Support `postgresql` schema designator
```

Support 'postgresql' schema designator

---

i18n/en.json

This PR updates the wording replacing Professional to Enterprise. And for two texts that refer to the former max user limitations, we restrict the text to say 'Mattermost Cloud'.
https://mattermost.atlassian.net/browse/MM-40827
```release-note
NONE
```

MM-40827 - wording update, replace Professional to Enterprise

---

api4/team.go
api4/team_test.go

We are not sanitizing teams when requested for the total count.
https://mattermost.atlassian.net/browse/MM-40177
```
NONE
```

[MM-40177] Sanitize Teams response when requested with total count

---

app/post_metadata.go
model/feature_flags.go

Removes the BoardsUnfurl feature flag
https://github.com/mattermost/focalboard/issues/1973
```release-note
NONE
```

Remove BoardsUnfurl feature flag

---

Makefile

Reverts mattermost/mattermost-server#19330
See https://community.mattermost.com/core/pl/xyubgtcdgjgc7p7bkfxusoka8o. I opened this PR to revert the Boards update to v0.12.0 from the Cloud branch so that Cloud customers won't see the latest bugs when we do a cloud release this Wednesday. We can cherry-pick the bump to 0.12.1 to the cloud branch once the Boards dot release is ready. Let me know if you see any issues with this.

Revert "Automated cherry pick of #19299"

---

app/channel.go
app/channel_test.go

Cherry pick of #19370 on release-6.3.
/cc  @agnivade
```release-note
NONE
```

Automated cherry pick of #19370

---

web/handlers.go

A similar change to this one was introduced in https://github.com/mattermost/mattermost-server/pull/15747/files
That one was only introduced to the cloud branch. Last week, the cloud branch was deleted and recreated, and this change was lost in the process.
Without this change, the redirect URI is built based off of the `X-Forwarded-For` header, which in the cloud context is _always_ `http` - but the redirect URI the installation actually needs requires https, so there was a mismatch. Now, if in the context of a cloud installation, it will fall back on the siteURL instead.
https://mattermost.atlassian.net/browse/MM-41206
```release-note
```

[MM-41206] Fix: Cloud workspaces unable to use OIDC Authentication

---

api4/channel_test.go

Skipping the test for now. The proper fix will need
to be done by the team.
https://mattermost.atlassian.net/browse/MM-41285
```release-note
NONE
```

MM-41285: Skip flaky test TestAddChannelMemberFromThread

---

model/scheduled_task_test.go

We were noting down the time of execution of a function and
expected that to match with the exact interval that we set.
However, sometimes in very busy CI environments, the goroutine
does not get a chance to be scheduled at the right time for
the interval to match exactly. Sometimes, we see a delay of
1 second.
To account for this, we increase the interval to 3 seconds,
and consider a 1 second buffer for this. If we see lags of
more than a second, then this test becomes useless and we
would need to remove it entirely.
https://mattermost.atlassian.net/browse/MM-41209
```release-note
NONE
```

MM-41209: Fix flaky test CreateRecurringTaskFromNextIntervalTime

---

go.mod
go.sum
vendor/github.com/go-morph/morph/drivers/lock.go
vendor/github.com/go-morph/morph/drivers/mysql/mysql.go
vendor/github.com/go-morph/morph/drivers/postgres/postgres.go
vendor/github.com/go-morph/morph/morph.go
vendor/modules.txt

https://mattermost.atlassian.net/browse/MM-41231
```release-note
NONE
```

MM-41231: Bump morph dependency to avoid advisory locks

---

app/license.go
app/license_test.go

The AND condition would mean that it would try to dereference
token.Valid if there was an error. And there's no guarantee
to always have a non-nil token in case of an error. We need
to track those conditions separately.
https://mattermost.atlassian.net/browse/MM-41236
```release-note
NONE
```

MM-41236: Sentry crash: Fix nil reference to token

---

app/server.go

We don't do instrumentation of Sentry transactions
anywhere in the code. Only opentracing code is present.
One has to explicitly add custom instrumentation for it
to work: https://docs.sentry.io/platforms/go/performance/instrumentation/custom-instrumentation/
It's likely someone is running custom code and sending
transaction data to Sentry. It's not super hard to pick
off the sentry DSN string from the binary.
The PR is more of a best effort to stop any future
transaction events to be sent.
```release-note
NONE
```

Disable sentry tracing completely

---

.circleci/config.yml

The CI fails because of ulimit issues.
https://mattermost.atlassian.net/browse/DOPS-783
```release-note
NONE
```

Remove ulimit for CI testing (#19409)

---

.circleci/config.yml
store/sqlstore/upgrade.go

MySQL returned type for JSON would be lowercase but we checked against an uppercase string, hence failing the check and re-triggering the migration every time.
/cc @neillcollie @isacikgoz 
@amyblais This goes directly into 6.3 release and will need to be included in a dot release. From what I can see bug also affects 6.0.x,6.1.x,6.2.x releases.
https://mattermost.atlassian.net/browse/MM-41330
```release-note
Fixed an issue that on MySQL installations would re-trigger 6.0 migration on server restart.
```

[MM-41330] Fix JSON type check in `hasMissingMigrationsVersion600`

---

i18n/en.json
web/saml.go

Cherry pick of #19423 on release-6.3.
/cc  @iomodo
```release-note
NONE
```

Automated cherry pick of #19423

---

model/post.go
store/sqlstore/channel_store.go
store/sqlstore/post_store.go

Before gorp, to use sqlx we had to resort to using
internal structs without the `db:"-"` tag so that
it doesn't interfere with the gorp table generation.
Now that it's gone, we can use the original model structs.
```release-note
NONE
```

PostStore: Remove `db:"-"` tag and some other hacks

---

model/feature_flags.go

The result of the AB testing led us to pick the "by_team_name" variant. This PR applies this change and removes the other ones.
https://mattermost.atlassian.net/browse/MM-41188
- Has webapp changes https://github.com/mattermost/mattermost-webapp/pull/9702
```release-note
NONE
```

[MM-41188] Remove "Add Channel Button" feature flag

---

api4/user_test.go
app/post_test.go
model/config.go

- `ThreadAutoFollow` is now `false` by default. Won't affect existing systems that have it set to `true`
- 
- https://mattermost.atlassian.net/browse/MM-41351
```release-note
The default for ThreadAutoFollow has been changed to "false". This does not affect existing configurations where this value is already set to true.  
```

[MM-41351] Set ThreadAutoFollow to false by default

---

api4/user_test.go
app/post_test.go
model/config.go

Summary
ThreadAutoFollow is now false by default. Won't affect existing systems that have it set to true.
Ticket Link
https://mattermost.atlassian.net/browse/MM-41351
(cherry picked from commit ae16f51aea1dd4b27f01e6bd94d5d79d0e57ed84)
```release-note
The default for ThreadAutoFollow has been changed to "false". This does not affect existing configurations where this value is already set to true.  
```

[MM-41351] Set ThreadAutoFollow to false by default (#19441)

---

app/channel.go

Summary
CRT server book-keeping should only happen if ThreadAutoFollow is true.
Ticket Link
https://mattermost.atlassian.net/browse/MM-41350
(cherry picked from commit 58879719f2b43840084e3901e1029b3478dc31e5) onto release-6.3
```release-note
On the server, CRT Threads will only be kept up to date if ThreadAutoFollow config is set to true
```

[MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true 

---

services/docextractor/documents.go

Temporary disabling .pages indexing to avoid crashes on malicious files
[MM-41334](https://mattermost.atlassian.net/browse/MM-41334)
```release-note
Temporarily disabled .pages file format for content extraction to avoid crashes on malicious formated .pages files
```

Temporary disabling .pages indexing to avoid crashes on malicious files

---

api4/plugin_test.go
api4/system.go
api4/system_test.go
app/app_iface.go
app/onboarding.go
app/opentracing/opentracing_layer.go
app/plugin.go
i18n/en.json
model/client4.go
model/onboarding.go
services/marketplace/client.go

This PR adds a `/system/onboarding/complete` endpoint. This will be called by the webapp once the onboarding flow in completed and will process the user data. As part of this PR only a list of plugin can be provided, which is then installed and enabled. Additional fields will be added in the future.
The endpoint can be accessed by admins (this is mostly needed for testing, but also to re-run the wizard) and if no user can been created yet.
https://mattermost.atlassian.net/browse/MM-41290
```release-note
Added new API endpoint POST /system/onboarding/complete to complete onboarding
```

[MM-41290] Add Endpoint to complete onboarding

---

api4/config.go
api4/config_test.go
i18n/en.json
model/client4.go

This was introduced to let the functionality happen
via mmctl, but it does not differentiate between
sysadmins vs people having physical access to machines.
Therefore, we remove it and only keep the local endpoint
accessible from mmctl --local.
https://mattermost.atlassian.net/browse/MM-41184
```release-note
The api/v4/config/migrate API endpoint has been removed
in favor of the mmctl --local endpoint. API clients
won't be able to access this endpoint without having
physical access to the server.
```

MM-41184: Remove /config/migrate API endpoint (#19418)

---

app/user.go
app/user_test.go

Password reset message says the password reset link is good for 24 hours when it expires after one hour.
https://mattermost.atlassian.net/browse/MM-41343
```release-note
* Fixed a bug causing the password reset link to be valid for 1 hour instead of 2 4hours.
```

[MM-41343] Password reset must be 24hour

---

app/export.go
app/export_test.go

This corrects a bug where exports that contained deleted teams
could fail to import. Channels must be skipped that belong to these
deleted teams in order to produce a valid import bundle.
Fixes https://mattermost.atlassian.net/browse/MM-41564
```release-note
Export deleted teams to allow for valid imports
```

Skip exporting channels for deleted teams

---

.circleci/config.yml
Makefile
api4/websocket_norace_test.go

Go 1.16+ allows installing a tool directly from a specific version.
Therefore, we don't need to rely on the tool being pre-installed
and can directly install it using standard method.
This keeps the same version of the tool for a repo and limits the
binary placement to the GOBIN of the repo.
```release-note
NONE
```

Pin GolangCI to a specific version

---

app/import_functions.go
app/import_functions_test.go
app/import_validators.go
app/import_validators_test.go
i18n/en.json
model/emoji.go

This changes import behavior related to emoji imports when the name
conflicts with the name of a system emoji. Previously, the import
would fail, but now a warning is logged and the conflicting emoji
is skipped.
Fixes https://mattermost.atlassian.net/browse/MM-41613
```release-note
Skip and warn on emoji import when name conflicts with system emoji
```

Skip and warn on emoji import when name conflicts with system emoji

---

app/login.go

We need this cookie to be accessed by the portal using javascript hence we set it's `HttpOnly` attribute to false
[MM-41534](https://mattermost.atlassian.net/browse/MM-41534)
```release-note
NONE
```

[MM-41534] - Portal not picking up MMCLOUDURL cookie

---

api4/system.go
app/app_iface.go
app/onboarding.go
app/opentracing/opentracing_layer.go
model/plugin_on_install_event.go
plugin/client_rpc_generated.go
plugin/hooks.go
plugin/hooks_timer_layer_generated.go
plugin/plugintest/hooks.go

This PR implements a `OnInstall()` hook that is triggered when the plugin is installed as part of the onboarding flow. A new type `model.OnInstallEvent` is used as an argument that allows future extension.
In the future, other install method like the Marketplace should also trigger the hook.
https://mattermost.atlassian.net/browse/MM-40935
```release-note
Added OnInstall() plugin hook
```

[MM-40935] Add OnInstall() plugin hook

---

model/feature_flags.go

The result of the A/B testing shows that we have a better conversion rate without the autotour. This PR drops the Autotour feature flag.
QA will be done on the webapp ticket
https://mattermost.atlassian.net/browse/MM-41408
- Has webapp changes https://github.com/mattermost/mattermost-webapp/pull/9752
```release-note
NONE
```

[MM-41408] Remove autotour feature flag

---

store/sqlstore/store.go
store/sqlstore/utils.go

We create a custom io.Writer to pass to the logger
instance. For now, we keep everything to debug
as all errors are surfaced back to the server via
the API.
```release-note
NONE
```

MM-41143: Pass a custom logger to morph

---

store/sqlstore/channel_store.go

The UPSERT statement was taking unexplained gap
locks, due to which the import was somehow failing.
I still don't know exactly how this is happening.
But splitting the UPSERT into 2 different statements
in the same transaction changes the locking semantics,
and avoids the deadlock.
Naturally, this proves that even our retrylayer
is sometimes ineffective against some problems.
```release-note
NONE
```

MM-38419: Split UPSERT statement into 2

---

app/team.go
app/team_test.go

We use the correct error variable while checking
for the error
https://mattermost.atlassian.net/browse/MM-41796
```release-note
NONE
```

MM-41796: Sentry crash: use the correct error variable

---

app/export_test.go

The build is failing due to a typo in the `app/export_test.go`
#19205 Might have caused this. As it went in later than #19494
```release-note
NONE
```

fix typo in the app/export_test.go

---

.gitignore
Makefile

This PR allows developers to have a custom `docker-compose.override.yaml` file, to either customize/override or add new service on their local installation.
Two personal use-cases:
- There's a [known issue with the docker MySQL image on arch linux](https://github.com/docker-library/mysql/issues/579#issuecomment-519495808) that makes MySQL use all available memory, I can patch this easily by overriding `ulimit` on the MySQL service.
- while working on a few Rudder PR, I had to run a local installation of rudder that I added to the override file.
N/A
```release-note
NONE
```

Allow developpers to use a docker-compose.override.yaml file

---

.github/workflows/scorecards-analysis.yml

Github Action for Scorecard
https://github.com/ossf/scorecard
The Scorecard provides a (somewhat opinionated) view on the security posture of the repository -- we (the product security team) would like to adopt this on our key repositories to identify possible security improvements

Adding the Scorecard analysis

---

app/plugin_requests.go

As discussed offline, this is not an actionable error message
and should therefore be demoted to debug.
```release-note
NONE
```

Change log level for missing plugin

---

app/team.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/thread_store.go
store/store.go
store/storetest/mocks/ThreadStore.go
store/storetest/thread_store.go
store/timerlayer/timerlayer.go

The GetTeamsUnreadForUser call would be called for every team switch.
In CRT mode, it would make a separate store call for every team, which
would run the 3 aggregate SQL queries in GetThreadsForUser.
This is suboptimal because the complexity is linearly proportional
to the number of teams.
We make the following optimizations:
1. Change the query to a single one which aggregates all teams.
2. The query originally used just 2 out of the 3 queries, so one
query was fully redundant. We remove that query in the new one.
3. Further analysis was done whether it makes sense to run the 2
queries synchronously or not. The load-tests didn't show any degradation
in running them concurrently, so we keep the same behavior.
4. Lastly, we query the replica instead of master to reduce the load on the …

MM-41499: Optimize TeamsUnread

---

app/slashcommands/auto_channels.go
app/slashcommands/command_loadtest.go

Added a new `/test dms` command that generates DMs.
```release-note
Added a new command to `/test` for DM generation for test/development purposes.
```

Add new /test dms command

---

app/audit.go
app/channels.go
app/config.go
app/notification_push_test.go
app/options.go
app/plugin.go
app/plugin_install.go
app/plugin_requests.go
app/plugin_signature.go
app/plugin_statuses.go
app/product.go
app/server.go
app/server_test.go

We create the basic boilerplate to pass services
to each product. The basic idea is to have a map
containing service names and the services.
The server will pass all services to all products.
But it is on the product, to choose what services
they will actually consume.
Each product will cast the received service to
an interface with the methods that product requires.
https://mattermost.atlassian.net/browse/MM-40813
https://mattermost.atlassian.net/browse/MM-40816
```release-note
NONE
```

MM-40813: Add config interface

---

app/web_hub.go
app/web_hub_test.go
model/websocket_message.go

The current implementation of plugin's API `PublishWebSocketEvent()` will eventually send messages across the cluster using the unreliable (UDP backed) channel. This can lead to unexpected message loss or ordering issues. It also imposes some hard limitations on maximum payload size (~64KB).
PR adds an option to allow for broadcasting WS events through the cluster using the reliable, TCP backed channel.
I've opted to extend `model.WebsocketBroadcast` to avoid either breaking the plugin's API or adding a new almost identical method just for this case. Please let me know if it makes sense or if you prefer a new method.
https://mattermost.atlassian.net/browse/MM-41712
```release-note
Added a new ReliableClusterSend field to model.WebsocketBroadcast to allow sending events through the cluster …
```

[MM-41712] Allow sending intra-cluster WS events reliably

---

i18n/en.json

Updating Safari recommended minimum version to v14.1+. This version comes with MacOS 10.14+ which is our minimum recommended version for MacOS.
```release-note
Updated Safari recommended minimum version to v14.1+
```

Update Safari minimum recommended version

---

app/helper_test.go
app/options.go
app/web_hub_test.go

PR fixes racy TestReliableWebSocketSend. I added a server option to set the cluster mock prior to initialization to avoid the race.
https://mattermost.atlassian.net/browse/MM-42033
```release-note
NONE
```

[MM-42033] Fix racy TestReliableWebSocketSend

---

app/notification_test.go

Cherry pick of #19604 on cloud.
/cc  @agnivade
```release-note
NONE
```

Automated cherry pick of #19604

---

api4/user.go

Revert status code to `302 Found` . This reverts an unintended change from https://github.com/mattermost/mattermost-server/pull/18839/files#diff-05b2b4c60779bc21cdec01701ac37a9b8859306a9ccdc333a79fe8a33551dee3L1906-L1921
https://mattermost.atlassian.net/browse/MM-42018
```release-note
NONE
```

revert to status found for login cws

---

app/migrations.go
app/onboarding.go
model/system.go

Mismatched key name between the migration code and the status fetching code meant that even the migration completed successfully, when the client tried to fetch the status of whether admin onboarding had been completed, they falsely saw it reported as `false`.
https://mattermost.atlassian.net/browse/MM-42103
```release-note
NONE
```

fix string constants

---

.circleci/config.yml

CircleCI will deprecate the image we use and we need to upgrade to the latest one.
https://mattermost.atlassian.net/browse/DOPS-822
```release-note
NONE
```

Upgrade circleci ubuntu server image to latest version

---

app/notification.go
i18n/en.json
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/channel_store.go
store/storetest/mocks/ChannelStore.go
store/storetest/user_store.go
store/timerlayer/timerlayer.go

Previously, we were incrementing mentions one-by-one
all concurrently in an unbounded fashion.
This would cause a big spike in memory usage if there
were an `@all` mention in a large channel.
We fix this by changing the SQL query to take all userIDs
at once.
https://mattermost.atlassian.net/browse/MM-41752
```release-note
NONE
```

MM-41752: Batch update mention increment

---

api4/ldap_test.go
api4/saml_test.go
api4/system.go
api4/system_test.go
api4/user_test.go
app/app.go
app/app_iface.go
app/channels.go
app/config.go
app/enterprise.go
app/enterprise_test.go
app/file.go
app/notification_push.go
app/opentracing/opentracing_layer.go
app/server.go
app/server_test.go
app/web_hub_test.go

This is more of a general refactor of the initialization
process which should allow us to pass services more
easily.
The changes are minimal to keep the scope limited.
For now, the objective is to pass the file service
to the Channels product. For that, it was required
to move some of the enterprise interfaces under Channels
from Server.
We also create a filestore field in the server to
avoid creating filestore reference every time
we make a filestore operation. This will be later
passed on to the Channels product.
```release-note
NONE
```

MM-40818: Refactor product initialization to happen late

---

api4/channel_category_test.go
app/channel_category.go
model/channel_sidebar.go

These changes unblock some future feature work on the mobile v2 (gekidou).
Fixes https://mattermost.atlassian.net/browse/MM-40470
```release-note
Adds sort order to category api, and includes category data in websocket category update event
```

API includes sort_order, and WebSocket includes data

---

model/feature_flags.go

Removes the Feature Flag allowing admin to create a channel as part of the previous onboarding experience. The new Use Case Onboarding still has it active.
QA will be done on the webapp part
https://mattermost.atlassian.net/browse/MM-41579
```release-note
NONE
```

[MM-41579] Remove FF guided channel creation

---

model/feature_flags.go
testlib/store.go

Defaulted Use-Case Onboarding feature flag to `true` so that is enabled by default for self-managed servers. 
Feature flag will be removed once the feature has had some time to soak in cloud. 
https://mattermost.atlassian.net/browse/MM-42219
```release-note
NONE
```

Defaulted use case onboarding feature flag to true

---

app/notification.go
app/notification_test.go

This pull request adds a check for userAllowEmail method if user is a bot, and setting userAllowsEmail to false accordingly. Also this PR adds a test for checking if user is a bot, and thus not getting email notifications.
Fixes https://github.com/mattermost/mattermost-server/issues/19406
```release-note
NONE
```

[MM-41170] Disable bot accounts from getting notification emails

---

app/enterprise.go
app/web_hub_test.go

I believe the cluster mock was getting replaced by the `initEnterprise()` method hence failing to save the messages.
PR adds an additional check to ensure we update it only if unset.
https://mattermost.atlassian.net/browse/MM-42033
```release-note
NONE
```

[MM-42033] Fix flaky TestReliableWebSocketSend

---

app/server.go

After refactoring the channels init, the
config service under channels won't have
the config hash until the product gets
started. This caused an issue during
cluster initialization.
Therefore moved it after the product start.
```release-note
NONE
```

Move cluster init during server start

---

.circleci/config.yml

With the current code, if Docker Compose hasn't created the network within 5 seconds the pipeline will crash as the Docker commands are erroring out. This replaces the static sleep with a loop that checks for the network to be created yet.
N/A
```release-note
NONE
```

Mitigate Docker Compose Race in Test Stages

---

Makefile

Adds a Makefile target to inject the test-data into a local instance without trying to start the server.
Context: I run my Makefile with `RUN_SERVER_IN_BACKGROUND=true`, and because the `test-data` target depends on `run-server`, it starts the server in the foreground thus never reaches the injection part.
Also, I did not want to break anybody's workflow so simply extracting the injection part in its own target ensured that everything would work the same as before for people relying on `test-data` to start their server.
N/A
```release-note
NONE
```

Add inject-test-data to the makefile

---

app/channel.go
app/channel_test.go

This PR excludes bots when restricting DMs to members of a team.
https://mattermost.atlassian.net/browse/MM-7968 provided a setting that allowed administrators to restrict DMs to team members only.  A side affect of this is that bots cannot create DM channels with users unless the bots are added to the user’s team.
It was decided (https://community.mattermost.com/core/pl/57ia5zdm7i8epyrbgyyx5xr8fo) to exclude bots from this restriction.
https://mattermost.atlassian.net/browse/MM-42318
```release-note
When restricting direct messages to users on the same team, bots are now excluded from that restriction.
```

Exclude bots when restricting DMs to team members.

---

api4/group_test.go
app/group.go
app/group_test.go
app/user.go
app/user_test.go
i18n/en.json
model/group.go

Validates that...
* creating or updating a group the `Name` ("Mention" on the front-end) isn't the same as any user `Username` values
* creating or updating a user the `Username` isn't the same as any group `Name` ("Mention" on the front-end) values
https://mattermost.atlassian.net/browse/MM-42201
https://github.com/mattermost/mattermost-webapp/pull/9923
```release-note
NONE
```

MM-42201: Enforce group is not the same as username.

---

app/server.go

The user service needs to be created before
loading license.
https://mattermost.atlassian.net/browse/MM-42378
```release-note
NONE
```

MM-42378: Fix server crash while loading license

---

api4/group.go
api4/group_test.go

Cherry pick of #19644 on release-6.5.
```release-note
NONE
```

Automated cherry pick of #19644

---

model/feature_flags.go

set default value for workspace optimization dashboard feature flag to `true`
[MM-42236](https://mattermost.atlassian.net/browse/MM-42236)
```release-note
sets default value for `MM_FEATUREFLAGS_WORKSPACEOPTIMIZATIONDASHBOARD` to `true`
```

workspace optimization dashboard feature flag default value

---

shared/mlog/levels.go

During server startup, the std lib logger is redirected to mlog to capture any logging from third-party libraries.  These log records are emitted using a specific log level so that they can be output to specific log targets, mixed with MM logs or separated.
It was intended this log level be included in the default mlog config but that was missed.  This PR is to add that to the default config such that all stdlib logs are included.
https://mattermost.atlassian.net/browse/MM-42345
```release-note
Logs from third-party libraries are now included in default logging configuration.
```

MM-42345: Include stdlog level in default mlog config

---

app/helper_test.go
app/license.go
app/server.go
app/slashcommands/helper_test.go
jobs/jobs_test.go
jobs/jobs_watcher.go
jobs/schedulers.go
jobs/schedulers_test.go
jobs/server.go
jobs/server_test.go
jobs/workers.go

Refactoring the save license function so the workers can start correctly during prevLicense/nextLicense features are validated. (Add back after fixing master build process)
https://mattermost.atlassian.net/browse/MM-42049
```release-note
NONE
```

MM-42049 - license endpoint not working (#19686)

---

store/sqlstore/channel_store.go
store/sqlstore/user_store.go

This PR ports "AutocompleteInTeamForSearch" and the methods it depends on to Squirrel. It also includes a small optimization for "buildFulltextClause" and moves "spaceFulltextSearchChar" to the file it's actually used in.
I've added buildLIKEClauseX and buildFulltextClauseX which generate the respective conditions for the WHERE clause. I've not removed the original methods, they seem to be used in other, not yet ported methods as well. Be aware that the arguments for these methods have slighly changed from their non-X counterparts. Instead of passing the columns as one string, they expect a list of strings. This simplifies the code.
As an optimization, "buildFulltextClause" and "buildFulltextClauseX" use the `strings.Map` function to replace the characters in "spaceFulltextSearchChars" …

MM-19334 Ported AutocompleteInTeamForSearch to Squirrel

---

store/sqlstore/channel_store.go
store/sqlstore/channel_store_test.go
store/sqlstore/store.go
store/sqlstore/utils.go
store/storetest/channel_store.go

This PR ports GetMembersByIds and GetMembersByChannelIds to Squirrel.
Fixes https://github.com/mattermost/mattermost-server/issues/19336
```release-note
NONE
```

MM-19336 Migrated GetMembersByIds and GetMembersByChannelIds to Squirrel

---

store/sqlstore/thread_store.go
store/storetest/thread_store.go

As per https://community-daily.mattermost.com/core/pl/ugs7ue6e4j8a7cgegk1bxje8to, `ThreadStore.GetThreadsForUser` accepts a `teamId` parameter, but incorrectly handles an empty value of `""` as looking only for channels with an empty `teamId` (aka DMs and GMs) instead of finding all channels and effectively ignoring the team property. Fix the query here, and extend unit test coverage at the store level to verify same.
Fixes: https://mattermost.atlassian.net/browse/MM-42282
```release-note
Fixed ThreadStore.GetThreadsForUser to count correctly when no team id is specified.
```

MM-42282: handle teamId parameter correctly

---

model/feature_flags.go

this removes the feature `InlinePostEditing` flag
- webapp: https://github.com/mattermost/mattermost-webapp/pull/9990
[MM-42431](https://mattermost.atlassian.net/browse/MM-42431)
```release-note
NONE
```

[MM-42431]: remove feature flag for inline post editing

---

api4/resolver_channel.go
api4/resolver_channel_test.go

When we are creating the pretty display name for a DM or GM, we omit the requester name, unless it is a DM to himself.
For the POC this is enough but:
- The names are not ordered based on the locale. This can be done in the client, but then we have to send the names in a format that the client can easily separate (we could separate by commas, but if the name has commas, then it is not possible...).
- We probably want to add the "(you)" string to the pretty display name of a DM to himself.
None
```release-note
NONE
```

[GraphQL POC] Omit self from pretty display name

---

jobs/jobs.go
jobs/migrations/worker.go
services/searchengine/bleveengine/indexer/indexing_job.go

This fixes a classic concurrency bug where the stop channel
was being listened in 2 places. In the Run method and DoJob
method.
The problem with that is that one of them will consume
the signal, and if the DoJob method does, then the parent
for-select loop never exits, because the return statement
only runs when the stop signal is consumed.
This would lead to server hanging on shutdown.
To fix this, we close the channel rather than sending a
message. This exits all listeners listening on the channel
and lets the job exit gracefully.
This is a sample stack dump of a stuck goroutine
```
goroutine 1 [chan receive]:
runtime.gopark(0x235be40?, 0xc000faa530?, 0xa8?, 0xf3?, 0x27a1170?)
/home/agniva/gosource/go/src/runtime/proc.go:366 +0xd6 fp=0xc002e77510 sp=0xc002e774f0 pc=0x43c856 …
```

MM-40272: Fix job server graceful stop

---

einterfaces/cloud.go
einterfaces/mocks/CloudInterface.go

Cloud cache needs a way to invalidate for tests in EE. This exposes that function in the interface.
https://mattermost.atlassian.net/browse/MM-42478
```release-note
None
```

[MM-42478] Add way to invalidate cloud cache

---

app/cluster.go
app/plugin_key_value_store.go
app/server.go

Adds clustering related methods to the wrapper. Since the service is initialized within the `app.Server`, we now pass `productID` (formerly `pluginID`) as a argument in the methods.
The KV related methods are required to initiate plugin mutexes and jobs. These were grouped under clustering in the original API, therefore kept them attached here as well.  See https://github.com/mattermost/mattermost-plugin-api/tree/master/cluster
https://mattermost.atlassian.net/browse/MM-42184
```release-note
NONE
```

[MM-42184] app: add plugin-api/cluster interface provider

---

jobs/jobs.go
store/sqlstore/channel_store.go
store/storetest/channel_store.go

Due to the way our community deployment is done. The job server
is restarted every day. This means that whenever there is a job
that takes more than 24 hours, it will always get cancelled
when the server restarts and therefore will never finish.
This PR adds ability to resume any stopped jobs, by storing
intermediate progress in the job metadata and setting
the job to pending instead of cancelled when everything is
shut down.
The user can still cancel a job explicitly by clicking on
the cross button in the system console. That functionality
hasn't changed. Only server stop or stopping/starting
job server via config will pause/resume jobs.
While here, we also fix some discrepancies in the job progress
calculation. The total estimates were incorrect. …

MM-40272: Ability to resume elasticsearch indexing job

---

app/channel_test.go
model/config.go

Cherry pick of #19797 on cloud.
```release-note
NONE
```

Automated cherry pick of #19797

---

db/migrations/mysql/000079_usergroups_displayname_index.down.sql
db/migrations/mysql/000079_usergroups_displayname_index.up.sql
db/migrations/postgres/000079_usergroups_displayname_index.down.sql
db/migrations/postgres/000079_usergroups_displayname_index.up.sql

Adds an index to `UserGroups.DisplayName`.
https://mattermost.atlassian.net/browse/MM-41866
```release-note
Added index to UserGroups DisplayName for improved autosuggest query performance.
```

MM-41866: Adds index to UserGroups.DisplayName.

---

app/channels.go
app/product.go
app/product_test.go
app/server.go

Introduced another app function `RegisterProductDependencies(name, dependencyMap)` to let products register their dependencies and the dependency map will be resolved during product initialization. It automatically figures out the initialization order by trial and error fashion.
I looked at the literature and this was being made with implementing a sorting algorithm on a tree data structure. I implemented this before checking literature but it's more or less the same with different data structures. 
```release-note
NONE
```

app/products: add dependency resolver

---

web/webhook.go

Without this, the endpoint throws CSRF warnings
if a token is passed.
https://mattermost.atlassian.net/browse/MM-35344
```release-note
NONE
```

MM-35344: Trust Requester for webhook endpoints

---

app/channels.go
app/post.go
app/server.go

Basically the `CreatePost` path is almost travels through the half of our codebase 😅 So I tried to refactor it as a separate standalone service, I had to throw almost every store in it as it would be a `Channels` product itself. My proposal is to expose this API from `Channels` product. Which will require a creation order for the products.
The creation order should use a dependency resolution and it may have it's own PR. Let me know if you think we should include that effort in this PR.
https://mattermost.atlassian.net/browse/MM-42185
```release-note
NONE
```

app: add posts wrapper

---

app/server_inactivity.go
model/config.go
services/telemetry/telemetry.go
tests/test-config.json

This PR adds a configuration in the config.json file , `EnableInactivityEmail` to toggle the ability to send inactivity email notifications
```release-note
Added configuration `EmailSettings.EnableInactivityEmail` to toggle ability to send inactivity email notification to admins
```

[MM-42703] - Add configuration setting to disable Inactive Server email notification

---

app/users/users.go
model/feature_flags.go

Remove `NewAccountNoisy` Feature Flag ([MM-39053](https://mattermost.atlassian.net/browse/MM-39053)) and set control or “none” as default variation.
https://mattermost.atlassian.net/browse/MM-41407
```release-note
NONE
```

MM-41407_Remove FF for MM-39053 Default Notifications

---

api4/channel_test.go

When the test fails, it is not clear whether the method
returned an error or it returned a channel with DeleteAt
set to 0. The if condition was also incorrect because
if the error was not-nil the condition would evaluate
to true and the test would pass.
We split the condition into 2 separate cases which will
let us know exactly what is failing.
https://mattermost.atlassian.net/browse/MM-42092
```release-note
NONE
```

MM-42092: Add better debugging for TestDeleteChannel

---

db/migrations/mysql/000080_posts_createat_id.down.sql
db/migrations/mysql/000080_posts_createat_id.up.sql
db/migrations/postgres/000080_posts_createat_id.down.sql
db/migrations/postgres/000080_posts_createat_id.up.sql
i18n/en.json
model/config.go
model/config_test.go
model/utils_test.go
services/searchengine/bleveengine/indexer/indexing_job.go
services/telemetry/telemetry.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/sqlstore/file_info_store.go
store/sqlstore/post_store.go
store/sqlstore/user_store.go
store/store.go
store/storetest/channel_store.go
store/storetest/file_info_store.go
store/storetest/mocks/ChannelStore.go
store/storetest/mocks/FileInfoStore.go
store/storetest/mocks/PostStore.go
store/storetest/mocks/UserStore.go
store/storetest/post_store.go
store/storetest/user_store.go
store/timerlayer/timerlayer.go
tests/test-config.json

The older method used to reply completely on timestamps
to take batches of items in a timestamp range and then
just incrementing the timestamp. This led to handling
edge-cases such as more items than the batch count, all
having the same timestamp.
Additionally, relying on timestamp as the page cursor
meant that indexing was not very efficient if you had
several items spread out across large spans of time.
To get away from all of that we use a proper cursor-based
approach consisting of createAt+Id. With this, we move
completely to a constant page size where we can fetch
a given number of objects irrespective of when they
were created. This makes indexing much more faster and
efficient.
https://mattermost.atlassian.net/browse/MM-41260
```release-note
Elasticsearch and Bleve indexing have …
```

MM-41260: Revamp ES/Bleve batching logic

---

.github/workflows/scorecards-analysis.yml

Update the action to [v1.0.4](https://github.com/ossf/scorecard-action/releases/tag/v1.0.4)
this should fix the odd failures on periodic runs

Update Scorecards action

---

build/Dockerfile
build/Dockerfile.buildenv

This prevents supply chain attacks where the latest image is replaced with a malicious version.
Pinning done by using https://github.com/Jille/dockpin (pins to the latest hash when run)

Pin the FROM in dockerfiles

---

app/post.go

According to the [docs](https://docs.mattermost.com/configure/deprecated-configuration-settings.html#allow-users-to-edit-their-messages) the time limit on post editing is not a feature you need a license for. 
So this PR removes the license guard around the handling for this.
There is a related bug regarding the post edit time limit setting here: [MM-42961](https://mattermost.atlassian.net/browse/MM-42961)
**unlicensed server**
**ui is not guarded** 
n/a
```release-note
PostEditTimelimit setting now works without a license
```

bugfix: post edit time limit is not a licensed feature anymore

---

api4/post_test.go
app/channel.go

- Send post unread websocket event when CRT is off/disabled.
- https://mattermost.atlassian.net/browse/MM-43073
```release-note
NONE
```

[MM-43073] broadcast post unread websocket when CRT off

---

Makefile
build/release.mk

Adding Calls as pre-packaged plugin. PR is purposely targeting `release-6.6` branch as this is only expected to land on self-managed deployment for the time being in order to unblock some of our closed beta customers.
Had to add a couple of additional checks since Calls currently supports Linux platforms only as backend.
https://mattermost.atlassian.net/browse/MM-42355
```release-note
Pre-package Calls v0.4.8
```

[MM-42355] Prepackage Calls v0.4.8

---

app/email/email.go
app/email/email_test.go
app/email/utils.go

We need to customize the reply to address for some cloud emails like the welcome email. This PR makes it possible.
[MM-42522](https://mattermost.atlassian.net/browse/MM-42522)
```release-note
NONE
```

[MM-42522] - The reply-to email address in our Cloud trial emails is no-reply@mattermost.com instead of feedback-cloud@mattermost.com

---

app/user.go
store/sqlstore/user_store.go

This was introduced with https://github.com/mattermost/mattermost-server/commit/2e027ae9278d60f318e7c286fcbe5c88895cc23f.
We fix it by deep copying the user struct before sending
it to the websocket hub.
Sample failures:
https://app.circleci.com/pipelines/github/mattermost/mattermost-server/32721/workflows/50d2ac52-4ff8-4116-ab50-7eae7a3306e8/jobs/257286
https://app.circleci.com/pipelines/github/mattermost/mattermost-server/32721/workflows/50d2ac52-4ff8-4116-ab50-7eae7a3306e8/jobs/257287
https://mattermost.atlassian.net/browse/MM-43137
```release-note
NONE
```

MM-43137: Fix racy test TestUpdateActiveBotsSideEffect

---

store/sqlstore/channel_store.go
store/storetest/channel_store.go

Currently the channel switcher will display channels even from the teams you have left.
This commit excludes channels from "left" teams to be shown in the switcher.
PS: When a user leaves a team we soft-delete the TeamMembers entry for user-team.
https://mattermost.atlassian.net/browse/MM-42725
```release-note
Fixes channel switcher showing channels from team the user is no longer part of
```

MM-42725: exclude channels from teams user has left

---

model/feature_flags.go

This PR removes the code that was used for the bottom option during the A/B test for adding members to channel button. The conclusion was that the top option performed better so we kept it.
https://github.com/mattermost/mattermost-webapp/pull/10167
https://mattermost.atlassian.net/browse/MM-39565
```release-note
NONE
```

MM-39565 - remove top option ab testing

---

api4/resolver_team.go
model/team.go

We take a shallow copy of the team pointer before
we pass that to the other functions.
This is because the resolvers run in separate
goroutines.
https://mattermost.atlassian.net/browse/MM-43340
```release-note
NONE
```

MM-43340: Fix racy test TestGraphQLChannelMembers

---

config/database_test.go
config/file_test.go
model/config.go

During config validation, we would omit the actual error.
This makes debugging difficult.
```release-note
NONE
```

Propagate the parse error for URLs

---

.gitpod.yml

This PR makes it so when this repository is used to create a Gitpod workspace, the configuration used will be delegated to the [mattermost-gitpod-config](https://github.com/mattermost/mattermost-gitpod-config) repo through its [.gitpod.yml](https://github.com/mattermost/mattermost-gitpod-config/blob/master/.gitpod.yml) file.
This allows multiple repos to share the same Gitpod config, as well as keeping the commit history minimal in regards to the individual repos.
https://www.gitpod.io/docs/references/gitpod-yml
https://www.gitpod.io/docs/multi-repo-workspaces
https://mattermost.atlassian.net/browse/MM-43384
```release-note
NONE
```

Add .gitpod.yml to use mattermost-gitpod-config repo for Gitpod configuration

---

api4/user.go
api4/user_test.go
app/app_iface.go
app/opentracing/opentracing_layer.go
app/user.go
i18n/en.json
model/client4.go

Until now we mark a thread as read/unread by sending a timestamp to the
server. This created some issues when marking a thread as unread from a
post. We needed to send the post.create_at - 1 as a timestamp but we
didn't do so consistently.
This commit adds a new API to set a thread as unread by post id. 
Making all clients agnostic of the timestamp, and thus solving consistency issues.
https://mattermost.atlassian.net/browse/MM-41185
https://mattermost.atlassian.net/browse/MM-41065
https://mattermost.atlassian.net/browse/MM-42473
```release-note
Added new API endpoint POST /api/v4/users/{user_id}/teams/{team_id}/threads/{thread_id}/set_unread/{post_id}.
```

[MM-41185]: new API to mark thread as unread

---

api4/file_test.go

The issue seems to be that different distros
have different set of included mime types
built-in. Go looks into those directories
and it looks like our CI systems don't have
those files.
https://mattermost.atlassian.net/browse/MM-42877
```release-note
NONE
```

MM-42877: Fix TestGetFileHeaders

---

.circleci/config.yml
app/server_test.go

https://mattermost.atlassian.net/browse/MM-43448
```release-note
NONE
```

MM-43448: Bump the CI to use Go 1.18.1

---

.circleci/config.yml
.golangci.yml
Makefile
app/webhub_fuzz.go
cmd/mattermost/main_test.go
utils/markdown.go

- MM-42148: Bump golangci to use 1.18
- Bumped the version

Bump golangci to use 1.18

---

config/logger.go
config/logger_test.go

This PR fixes a customer reported issue where timestamps are not appearing in their audit logs.  This is a bug in the default audit config i.e. using the `FileEnabled` setting:
```
"ExperimentalAuditSettings": {
"FileEnabled": true,
"FileName": "audit.log",
"FileMaxSizeMB": 100,
"FileMaxAgeDays": 0,
"FileMaxBackups": 10,
"FileCompress": true,
"FileMaxQueueSize": 1000,
"AdvancedLoggingConfig": ""
},
```
The AdvancedLoggingConfig works as expected and includes timestamps.
https://mattermost.atlassian.net/browse/MM-43464
```release-note
Timestamps are enabled in the default audit configuration.
```

MM-43464  Enable timestamp for default audit config

---

store/sqlstore/reaction_store.go

Switches to using `PublicChannels` instead of `Channels WHERE Channels.Type = 'O'`.
Likely more optimizations to come, this is just a small tweak with a big performance gain.
1 day:
```shell
jswithtafpdb> \i ~/Desktop/top-reactions-test.sql
+--------------+-------+
| emojiname    | count |
|--------------+-------|
| tada         | 14    |
| raised_hands | 13    |
| +1           | 11    |
| point_up     | 8     |
+--------------+-------+
SELECT 4
Time: 42.458s (42 seconds), executed in: 42.442s (42 seconds)
jswithtafpdb> \i ~/Desktop/top-reactions-rewrite.sql
+--------------+-------+
| emojiname    | count |
|--------------+-------|
| tada         | 14    |
| raised_hands | 13    |
| +1           | 11    |
| point_up     | 8     |
+--------------+-------+
SELECT 4
Time: 0.207s
```
7 days: …

Query optimization for top reactions.

---

api4/cloud.go
app/app_iface.go
app/cloud.go
app/email/email.go
app/email/mocks/ServiceInterface.go
app/email/service.go
app/opentracing/opentracing_layer.go
i18n/en.json
model/cloud.go
templates/cloud_upgrade_confirmation.html
templates/cloud_upgrade_confirmation.mjml

Adds an email to be sent to the customer when successfully upgrading their subscription. I've also left an accessor to this email in the webhooks, so we can trigger this from other systems in the future if necessary. 
https://mattermost.atlassian.net/browse/MM-43339
```release-note
None
```

[MM-43339] Add Cloud Subscription Upgrade Confirmation Email

---

app/imaging/svg.go
app/imaging/svg_test.go

title says it all.
This might need more polishing from someone more proficient in GO.
I commented out and left the block of code where it was checking with regexes for occurences of `viewbox` or `width`/`height` values as a fallback, since afaik a `SVG` with those attributes missing is broken anways.
[MM-43393](https://mattermost.atlassian.net/browse/MM-43393)
```release-note
NONE
```

[MM-43393]: replace .Decoder() method with .Token()

---

api4/resolver_channel.go
api4/resolver_channel_test.go

We fall back to TeammateNameDisplay if a user display_name
preference is not found. This makes the logic consistent
with other parts of the app.
https://mattermost.atlassian.net/browse/MM-43829
```release-note
NONE
```

MM-43829: Default for user display_name preference

---

config/database.go
config/utils.go
store/sqlstore/store.go
store/sqlstore/store_test.go
store/sqlstore/utils.go
store/sqlstore/utils_test.go

This PR removes code duplication around the `appendMultipleStatementsFlag` and `resetReadTimeout` methods, makes them public to be imported from other tools (namely focalboard) and moves them to the `sqlstore/utils.go` file to avoid import cycle.
```release-note
NONE
```

Remove code duplication and move utility methods to the store utils

---

i18n/en.json

Desktop app v5.1 includes major version upgrade of Electron to v18.0.3. 
This version of Electron https://www.electronjs.org/releases/stable?#18.0.3 supports Chrome v100.
Will add to release notes.

Update Chrome supported version to 100+

---

app/import_functions_test.go

We use the specifically created NewTestId
to circumvent any clashes with reserved words.
https://mattermost.atlassian.net/browse/MM-43341
```release-note
NONE
```

MM-43341: Fix flaky TestImportImportUser

---

api4/post_test.go

We increase the timeout further. Without this, there is
no reliable way to wait for a message.
Also consolidated the timeout values for other tests.
https://mattermost.atlassian.net/browse/MM-42997
```release-note
NONE
```

MM-42997: Fix flaky TestDeletePostEvent

---

api4/graphql.go
api4/resolver.go
api4/resolver_user.go
app/app_iface.go
app/bot.go
app/cloud.go
app/export_test.go
app/opentracing/opentracing_layer.go
app/plugin_api.go
app/slashcommands/auto_channels.go
app/user.go
app/user_viewmembers_test.go
app/users/users.go

We were throttling the amount of concurrent resolvers
at a given time. The idea behind this was to avoid overloading
the database with too many requests.
However, with the introduction of dataloaders, this limitation
actually becomes a bottleneck because all DB calls are actually
batched, so we are unnecessarily throttling the amount of
items that can be processed in a single batch.
The only caveat with this is that now all resolvers
need to backed by dataloaders, or otherwise not be queried
as part of a loop.
In a subsequent PR, we will be removing channel stats
from under channel to be a top-level object to be returned
for a given channel.
```release-note
NONE
```

GraphQL: Unlock goroutine throttle to match batch capacity

---

Makefile

Moves setup-go-work as the first target for run-server to solve
"go: inconsistent vendoring error"
```release-note
NONE
```

Fixes: make run-server command

---

Makefile

Since we changed the modules workflow, a small update required in the `update-dependencies` rule.
```release-note
NONE
```

update make update dependencies rule

---

build/docker-compose.common.yml
build/gitlab-dc.common.yml

Upgrades the minor version of the ElasticSearch development Docker image.
Related PR: https://github.com/mattermost/mattermost-elasticsearch-docker/pull/3
Tag: https://github.com/mattermost/mattermost-elasticsearch-docker/releases/tag/7.17.3
n/a
```release-note
Upgrades the minor version of the ElasticSearch development Docker image.
```

Bumps ES minor version.

---

app/cluster.go

`PublishWebSocketEvent` method was overlooked during creating the services.
```release-note
NONE
```

app/cluster.go: add PublishWebSocketEvent method

---

api4/graphql.go
api4/resolver.go
api4/resolver_channel_member.go
api4/resolver_channel_member_test.go
api4/resolver_team.go
api4/schema.graphqls
store/layer_generators/main.go
store/opentracinglayer/opentracinglayer.go
store/retrylayer/retrylayer.go
store/sqlstore/channel_store.go
store/store.go
store/storetest/channel_store.go
store/storetest/mocks/ChannelStore.go
store/timerlayer/timerlayer.go

We add 2 new params to channel members query.
1. Filter by teamId.
2. Negate that filter.
We include some more optimizations like:
- Moved the team role checks inside the dataloader.
- Moved the channel pretty name computation inside the loader.
Now that we load less data on initial load, we can reduce
the concurrency requirement to be a bit on the safer side.
```release-note
NONE
```

MM-44088: Add teamID filter to channelMembers

---

.gitlab-ci.yml

Configures Gitlab pipeline to use Go.1.8.1
```release-note
NONE
```

Configure gitlab pipeline to use Go 1.18.1

---

api4/upload.go
api4/upload_test.go
i18n/en.json

mmctl import is not supported and therefore we stop it.
https://mattermost.atlassian.net/browse/MM-41655
```release-note
NONE
```

MM-41655: Prevent mmctl import into cloud instances

---

build/release.mk

Without this, the go.work file would not get
generated in a fresh build.
```release-note
NONE
```

Makefile: Added setup-go-work to build step as well

---

app/plugin_api.go

This PR checks if the app has the cloud interface set before trying to call it to avoid a null pointer when using the get limits plugin API endpoint in non-cloud mode.
```release-note
NONE
```

Fixes a null pointer if the plugin requests the limits on a non-cloud server

---

api4/config.go
config/diff.go
config/diff_test.go
model/config.go

Added `config.DiffTags` utility function to get diffs according to specific sturct tags. Also added some struct tags to `model.Config` to restrict access.
https://mattermost.atlassian.net/browse/MM-41660
```release-note
NONE
```

config/diff: add utility function to get diffs scoped with struct tags

---

app/channel.go
app/expirynotify.go
app/notification.go
app/notification_push.go

```release-note
Fix bug that allow to send test (empty) notifications even if the `SendPushNotifications` config is set to false.
```

cherrypick-50eaec6

---

app/channels.go
app/permissions.go
app/server.go

The plugin API provides this method under user service:
https://github.com/mattermost/mattermost-plugin-api/blob/e672b88e7c638e3a02ebc2ac0b3c8e16e4005e7f/user.go#L197
But we don't have any team scope on our user service in mattermost-server. The team service already has a dependency to user service for team membership stuff, hence it will be a cyclic dependency even if we go that direction. Since permissions does not have any application logic with other entities such as team/users rather than accessing the id and scheme, we can have a separate service/interface.
https://mattermost.atlassian.net/browse/MM-44331
```release-note
NONE
```

app: add permissions wrapper

---

app/import_functions.go
app/import_functions_test.go
app/import_validators.go
app/import_validators_test.go
i18n/en.json

- In a bulk import, if the createAt of a reply is older than the createAt of the parent post, then instead of erroring, we log a warning and set the createAt of the reply to that of the parent post.
- I checked the exporting logic, there doesn't appear to be away for the reply createAt to be older than the parent createAt, as a side-effect of the exporting logic.
- https://mattermost.atlassian.net/browse/MM-43878
```release-note
NONE
```

MM-43878: don't err when reply createAt before parent createAt

---

api4/usage_test.go
app/usage.go
model/post.go
store/sqlstore/post_store.go
store/storetest/post_store.go

When fetching count, include user posts only in post count. i.e., exclude "system" and "bots" messages.
JIRA - https://mattermost.atlassian.net/browse/MM-44263
```release-note
Fixed API - GET /api/v4/usage/posts, to include user posts only.
```

[MM-44263] Only include user posts in post count

---

store/sqlstore/shared_channel_store.go

When testing the experimental SharedChannels feature `NextSyncAt` was a missing column in the `SharedChannelRemotes` table and causing an application error. We weren't using it anywhere so this removes it from the query for now.
```release-note
Fix an error about a missing column for the Shared Channels experimental feature
```

Remove NextSyncAt from GetRemoteStatus query

---

.circleci/config.yml

CircleCI deprecated old ubuntu version and we need to bump to the recommended by CirclecCI.
In parallel bumped python to 3.7 to match with `master` branch changes.
https://mattermost.atlassian.net/browse/DOPS-1050
```release-note
NONE
```

Fix failures for circleci ubuntu image

---

store/sqlstore/store.go
store/store.go
store/storetest/mocks/Store.go
store/storetest/store.go

This PR adds two methods to the store.Store interface. `GetInternalMasterDB()` returns the `*sql.DB` for the master database. `GetInternalReplicaDBs()` returns a slice of `*sql.DB`s for the configured replica databases (or the master, when no replicas are configured). This behavior is implemented to emulate the functionality of `GetMasterX()` and `GetReplicaX()`.
This PR also updates the mocks to include the new methods.
As an internal change, this adds a method `"sqlStore".Store.hasLicense()` which returns `true` iff the license is not `nil`. Putting it into it's own method allows for simpler (and more efficient) code.
[MM-44329](https://mattermost.atlassian.net/browse/MM-44329)
```release-note
NONE
```

[MM-44329] Add a method to store.Store interface to get sql.DB object

---

utils/utils.go
utils/utils_test.go

The pull request inverts the X-Forwarded-For header parsing to split on `comma` and trim white spaces. This change is backwards compatible as shown by the unit tests, but adds support for some systems such as Cloudflare.
https://mattermost.atlassian.net/browse/MM-44786
```
Fixed bug in X-Forwarded-For header parsing when no whitespaces between values are provided
```

[MM-44786] Fix Trusted Header Parsing for Cloudflare

---

api4/config.go

In some cases, we are not immediately returning after we assign an error to the handler's `*Context`. This PR makes it so we always return for the handlers in `api4/config.go`.
From discussion https://community-daily.mattermost.com/core/pl/pfxrro8p5tdgxpde58mpi1aewy
Fixes https://mattermost.atlassian.net/browse/MM-44604
```release-note
NONE
```

[MM-44604] Ensure we return after setting error in api4/config.go
