- store/sqlstore/upgrade.go
> Bump schema version to 5.37

- store/sqlstore/channel_store.go
Now that version 10 is minimum, we can start to use
advanced postgres features.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=0445b560-91b9-469b-8f19-febf1881bcd6
```release-note
NONE
```
> ChannelStore: Use native upsert for Postgres

- store/sqlstore/plugin_store.go
Now that version 10 is minimum, we can start to use
advanced postgres features.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=0445b560-91b9-469b-8f19-febf1881bcd6
```release-note
NONE
```
> PluginStore: Use native upsert for Postgres

- app/slashcommands/helper_test.go
> MM-36947: Fix failure in master

- app/auto_responder.go
Small fix for the migrations branch, big improvement for my open PRs :)
```release-note
NONE
```
> fix an issue that possibly emerged from upstream merge

- app/syncables_test.go
> MM-36909: Skip flaky CreateDefaultMemberships for now

- store/sqlstore/group_store.go
Now that version 10 is minimum, we can start to use
advanced postgres features.
https://focalboard-community.octo.mattermost.com/workspace/zyoahc9uapdn3xdptac6jb69ic?id=285b80a3-257d-41f6-8cf4-ed80ca9d92e5&v=495cdb4d-c13a-4992-8eb9-80cfee2819a4&c=0445b560-91b9-469b-8f19-febf1881bcd6
```release-note
NONE
```
> GroupStore: Use native upsert

- app/integration_action.go
- app/integration_action_test.go
Cherry pick of #17879 on cloud.
/cc  @larkox
> Automated cherry pick of #17879

- model/cloud.go
This PR updates the Product model so it matches with the product model in CWS and provides necessary information that is needed in the UI as the sku information.
https://mattermost.atlassian.net/browse/MM-37033
```release-note
NONE
```
> MM-37033 - update product model to match with customer web server

- i18n/en.json
- i18n/en_AU.json
This PR is supposed to make a translation string recently added clearer and easier to translate. The motivation is as a result of feedback from a community translator
[MM-36327](https://mattermost.atlassian.net/browse/MM-36327?atlOrigin=eyJpIjoiNjYwOGM5ODg4YzE3NDFmMzhiZmE3NTJhZGZjODcwY2UiLCJwIjoiaiJ9)
```release-note
None
```
> [MM-36327] - Make a translation string clearer

- build/gitlab-dc.mysql.yml
- build/gitlab-dc.schemamysql.yml
> Increase mysql version of gitlab docker-compose.

- api4/team.go
- api4/team_test.go
- api4/user_test.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/plugin_api.go
- app/team.go
- model/client4.go
- model/team_member.go
- model/thread.go
- store/sqlstore/thread_store.go
Cherry pick of #17944 on cloud.
> Automated cherry pick of #17944

- app/server_test.go
> MM-37378: Skip TestPanicLog

- api4/preference_test.go
- app/plugin_api_test.go
- app/user.go
- app/user_test.go
- model/preference.go
Cherry-pick of #17977 to cloud
Release Note
```release-note
NONE
```
cc: @marianunez
> Cherry-pick to cloud of MM-37064

- model/team_test.go
- model/utils.go
Add "playbooks" and "boards" to restricted team URLs list.
https://mattermost.atlassian.net/browse/MM-37042
```release-note
Add "playbooks" and "boards" to restricted team URLs list.
```
> MM-37042 Add "playbooks" and "boards" to restricted team URLs list

- store/sqlstore/upgrade.go
Upgrade db to 5.38 now that release-5.38 is cut. 
```release-note
```
> DB upgrade 5.38

- store/sqlstore/store.go
Refer: https://github.com/mattermost/mattermost-server/issues/18038
```release-note
NONE
```
> Print a helpful message for JSON column update failures.

- api4/system_test.go
- api4/user_test.go
- model/client4.go
```release-note
Removed (*model.Client4).CheckUserMfa
Removed (*model.Client4).GetServerBusyExpires
```
> Remove deprecated *model.Client methods

- app/email/email.go
- app/email/email_test.go
https://mattermost.atlassian.net/browse/MM-37579
```release-note
NONE
```
> MM-37579: Fix typo in map property

- services/telemetry/telemetry.go
Cherry pick of #17971 on release-5.38.
/cc  @chenilim
> Automated cherry pick of #17971

- store/sqlstore/status_store.go
Cherry pick of #18011 on cloud.
> Automated cherry pick of #18011

- Makefile
Cherry pick of #18071 on release-5.38.
/cc  @sbishel
> Automated cherry pick of #18071

- app/post_metadata_test.go
https://mattermost.atlassian.net/browse/MM-37757
```release-note
NONE
```
> Skip racy TestPreparePostForClient

- api4/license.go
- api4/license_test.go
- i18n/en.json
Cherry pick of #17933 on release-5.37.
> Automated cherry pick of #17933

- app/server.go
Cherry pick of #18053 on release-5.37.
/cc  @agnivade
> Automated cherry pick of #18053

- templates/partials/logo.mjml
- templates/partials/style.mjml
- templates/partials/verify.mjml
- templates/verify_body.html
- templates/welcome_body.html
This PR updates the welcome and verify email templates to new branding
-----
[MM-37616](https://mattermost.atlassian.net/browse/MM-37616?atlOrigin=eyJpIjoiZGM4Mjc4M2U0NGU1NDdlYWJmOWU1YzJmZTMzZTViNzYiLCJwIjoiaiJ9)
```release-note
NONE
```
> [MM-37616] Self-managed: Update email template to new branding - Welcome and Verification email

- store/sqlstore/session_store.go
- store/storetest/session_store.go
https://community-daily.mattermost.com/plugins/focalboard/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=6f15ea48-995c-4975-8b28-bd58f7d6a34a
```release-note
NONE
```
> Update Session Props to use one query

- build/docker-compose.common.yml
Switch to mysql/mysql-server docker image for ARM64 support.
n/a
```release-note
NONE
```
> Switch to mysql/mysql-server docker image for ARM64 support.

- model/version.go
> Update version to 5.38.1

- store/storetest/thread_store.go
In storetest/thread_store.go, replaced all instances of ```"zz" + model.NewId()``` with ```NewTestId()```
Fixes https://github.com/mattermost/mattermost-server/issues/18194
> Replaced all instances of "zz" + model.NewId() with NewTestId()(#18194)

- store/storetest/group_store.go
Replace all instances of "zz" + model.NewId() in storetest/group_store.go with NewTestId
Fixes https://github.com/mattermost/mattermost-server/issues/18192
```release-note
NONE
```
> [GH-18192] Replace all instances of "zz" + model.NewId() in storetest/group_store.go with NewTestId

- api4/post_test.go
PR fixes CI build after a bad merge of https://github.com/mattermost/mattermost-server/pull/18131.
```release-note
NONE
```
> Fix bad merge causing CI to fail

- api4/post_test.go
- app/post.go
Cherry pick of #18131 on cloud.
> Automated cherry pick of #18131

- shared/mlog/mlog.go
Cherry pick of #18189 on cloud.
/cc  @wiggin77
> Automated cherry pick of #18189

- i18n/en.json
- store/sqlstore/post_store.go
- store/sqlstore/upgrade.go
Manual cherry-picking #17948 to cloud.
```release-note
NONE
```
> MM-27312 cherrypick to Cloud

- services/remotecluster/mocks_test.go
- services/remotecluster/ping_test.go
- services/remotecluster/send_test.go
- services/remotecluster/sendprofileImage_test.go
- services/remotecluster/service_test.go
- shared/mlog/tlog.go
- web/oauth_test.go
Cherry pick of #18207 on cloud.
/cc  @wiggin77
> Automated cherry pick of #18207

- app/notification_email.go
- templates/messages_notification.html
Cherry pick of #18134 on cloud.
/cc  @AGMETEOR
> Automated cherry pick of #18134

- templates/partials/style.mjml
Cherry pick of #18076 on cloud.
/cc  @AGMETEOR
> Automated cherry pick of #18076

- app/command_autocomplete.go
- app/context.go
- app/plugin_hooks_test.go
- app/plugin_requests.go
- app/ratelimit.go
- app/request/context.go
- config/environment_test.go
- einterfaces/mocks/AppContextInterface.go
- model/client4.go
- model/cluster_discovery.go
- model/cluster_discovery_test.go
- model/cluster_info.go
- model/cluster_info_test.go
- model/config.go
- model/utils.go
- model/utils_test.go
- plugin/context.go
- services/telemetry/telemetry.go
- tests/test-config.json
- web/context.go
- web/handlers.go
Cherry pick of #18152 on cloud.
/cc  @hanzei
> Automated cherry pick of #18152

- templates/invite_body.html
- templates/invite_body.mjml
- templates/messages_notification.html
- templates/partials/style.mjml
- templates/reset_body.html
- templates/verify_body.html
- templates/welcome_body.html
Cherry pick of #18200 on cloud.
/cc  @AGMETEOR
> Automated cherry pick of #18200

- app/notification.go
- app/notification_email.go
- app/notification_push.go
- i18n/en.json
- model/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/mocks/ThreadStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #18088 on cloud.
/cc  @koox00
> Automated cherry pick of #18088

- templates/cloud_trial_end_warning.html
- templates/cloud_trial_ended_email.html
- templates/cloud_upgrade_request_email.html
- templates/cloud_welcome_email.html
- templates/invite_body.html
- templates/license_up_for_renewal.html
- templates/messages_notification.html
- templates/over_user_limit_30_days_body.html
- templates/over_user_limit_7_days_body.html
- templates/over_user_limit_90_days_body.html
- templates/over_user_limit_workspace_suspended_body.html
- templates/partials/style.mjml
- templates/payment_failed_body.html
- templates/payment_failed_no_card_body.html
- templates/reached_user_limit_body.html
- templates/reset_body.html
- templates/verify_body.html
- templates/welcome_body.html
Updates branding for the invitation email for guests
[MM-37731](https://mattermost.atlassian.net/browse/MM-37731)
```release-note
NONE
```
> [MM-37731] - Self-managed: Update email template to new branding - Invitation Guests

- cmd/mattermost/commands/jobserver.go
Cherry pick of #18220 on cloud.
> Automated cherry pick of #18220

- app/notification.go
> Fixes race condition in notification.go

- templates/cloud_trial_end_warning.html
- templates/cloud_trial_ended_email.html
- templates/cloud_upgrade_request_email.html
- templates/cloud_welcome_email.html
- templates/invite_body.html
- templates/license_up_for_renewal.html
- templates/messages_notification.html
- templates/over_user_limit_30_days_body.html
- templates/over_user_limit_7_days_body.html
- templates/over_user_limit_90_days_body.html
- templates/over_user_limit_workspace_suspended_body.html
- templates/partials/style.mjml
- templates/payment_failed_body.html
- templates/payment_failed_no_card_body.html
- templates/reached_user_limit_body.html
- templates/reset_body.html
- templates/verify_body.html
- templates/welcome_body.html
Cherry pick of #18222 on cloud.
/cc  @AGMETEOR
> Automated cherry pick of #18222

- app/notification.go
Cherry pick of #18226 on cloud.
/cc  @koox00
> Automated cherry pick of #18226

- app/notification.go
The followers slice was being read before all goroutines
finished. We fix this by waiting till all goroutines
are done before reading from the slice.
```release-note
NONE
```
> Fix racy test TestViewChannelCollapsedThreadsTurnedOff 

- store/sqlstore/upgrade.go
Cherry-pick of https://github.com/mattermost/mattermost-server/pull/18210 into cloud branch.
```release-note
NONE
```
> Combine alterations on Posts table (#18210) - cloud cherrypick

- templates/reset_body.html
Cherry pick of #18135 on cloud.
/cc  @AGMETEOR
> Automated cherry pick of #18135

- Makefile
- scripts/wait-for-system-start.sh
Cherry pick of #18229 on cloud.
/cc  @mkraft
> Automated cherry pick of #18229

- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
- store/sqlstore/status_store.go
- store/sqlstore/thread_store.go
- store/sqlstore/upgrade.go
Cherry-picking https://github.com/mattermost/mattermost-server/pull/18078 to cloud.
```release-note
NONE
```
> MM-36387 cherry-pick to cloud

- build/docker-compose.common.yml
- build/gitlab-dc.common.yml
Cherry pick of #18117 on cloud.
> Automated cherry pick of #18117

- store/storetest/compliance_store.go
- store/storetest/post_store.go
Issue #18191 and #18193 fixed.
Fixes #18191
Fixes #18193 
```release-note
NONE
```
> Issue #18191 and #18193 fixed

- scripts/download_mmctl_release.sh
Includes mmctl fixes for homebrew: mattermost/mmctl/pull/381
```release-note
```
> Update mmctl to v5.38.1

- app/post_metadata.go
- app/slack.go
- model/post.go
- model/post_test.go
- model/slack_attachment.go
Cherry pick of #18052 on release-5.39.
/cc  @agnivade
> Automated cherry pick of #18052

- config/client.go
Cherry pick of #18146 on release-6.0.
> Automated cherry pick of #18146

- app/auto_responder.go
- app/auto_responder_test.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherry pick of #18264 on release-6.0.
/cc  @agnivade
> Automated cherry pick of #18264

- model/feature_flags.go
Update default treatment for add channel button to current color & by team name.
https://mattermost.atlassian.net/browse/MM-37462
```release-note
Update default treatment for add channel button to current color & by team name.
```
> update add channel button default to by_team_name

- .circleci/config.yml
- .gitlab-ci/scripts/test-schema/mysql.sh
- .gitlab-ci/scripts/test-schema/postgres.sh
- Makefile
- scripts/mattermost-mysql-6.0.sql
- scripts/mattermost-postgresql-6.0.sql
- scripts/mysql-migration-test.sh
- scripts/psql-migration-test.sh
PR updates the db schema validation scripts for 6.0.
https://mattermost.atlassian.net/browse/MM-37621
```release-note
NONE
```
> [MM-37621] Update db schema validation scripts for 6.0

- api4/user.go
- api4/user_test.go
- model/client4.go
- web/params.go
- web/params_test.go
Cherry pick of #18260 on release-6.0.
> Automated cherry pick of #18260

- app/email.go
- app/email_test.go
* MM-37579: Fix typo in map property
https://mattermost.atlassian.net/browse/MM-37579
```release-note
NONE
```
* refactor
```release-note
NONE
```
> MM-37579: Fix typo in map property (#18051)

- .gitignore
- .gitlab-ci.yml
- .gitlab-ci/scripts/test-schema/mysql.sh
- .gitlab-ci/scripts/test-schema/postgres.sh
- .gitlab-ci/scripts/test/mysql.sh
- .gitlab-ci/scripts/test/postgres.sh
- build/gitlab-dc.mysql.yml
- scripts/mattermost-mysql-6.0.sql
- scripts/mattermost-postgresql-6.0.sql
New indexes were missing from the previously generated schemas in https://github.com/mattermost/mattermost-server/pull/18223
Not sure how the merge didn't cause a failure though. Maybe we are not running the schema check step over there.
```release-note
NONE
```
> Update schemas to include new indexes

- .circleci/config.yml
- .gitignore
- .gitlab-ci.yml
- .gitlab-ci/scripts/test-schema/mysql.sh
- .gitlab-ci/scripts/test-schema/postgres.sh
- .gitlab-ci/scripts/test/mysql.sh
- .gitlab-ci/scripts/test/postgres.sh
- Makefile
- build/gitlab-dc.mysql.yml
- scripts/mattermost-mysql-6.0.sql
- scripts/mattermost-postgresql-6.0.sql
- scripts/mysql-migration-test.sh
- scripts/psql-migration-test.sh
Cherry-picking both https://github.com/mattermost/mattermost-server/pull/18223 and https://github.com/mattermost/mattermost-server/pull/18313 to `release-6.0` branch.
```release-note
NONE
```
> [MM-37621] Cherry-pick to release-6.0

- web/params.go
- I forgot to remove some commented out code in https://github.com/mattermost/mattermost-server/pull/18260. 
I noticed it while cherry-picking the commit to release-6.0. The cherry-pick has already been fixed. 
```release-note
NONE
```
> cleanup some commented out code

- app/notification.go
- app/post.go
- app/post_test.go
- app/user.go
- store/sqlstore/thread_store.go
- store/store.go
Cherry pick of #18020 on release-5.39.
> Manual cherry pick of #18020

- .circleci/config.yml
- .gitlab-ci.yml
- Makefile
> Use new mattermost-govet

- store/sqlstore/bot_store.go
- store/sqlstore/sqlx_wrapper.go
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=5da060fd-8fbc-449d-8219-c73a9dd0bd7c
```release-note
NONE
```
> Migrating bot store to use sqlx

- store/sqlstore/post_store.go
- store/sqlstore/thread_store.go
- store/storetest/post_store.go
- store/storetest/thread_store.go
Cherry pick of #18235 on release-6.0.
/cc  @koox00
> Automated cherry pick of #18235

- model/feature_flags.go
Cherry pick of #18350 on release-6.0.
/cc  @neallred
> Automated cherry pick of #18350

- app/license.go
- utils/license.go
- utils/license_test.go
Cherry pick of #18333 on release-6.0.
> Automated cherry pick of #18333

- app/email/email_batching.go
- app/notification.go
- app/notification_email.go
- app/notification_push.go
- i18n/en.json
- model/user.go
Cherry pick of #18332 on release-6.0.
/cc  @koox00
> Automated cherry pick of #18332

- app/webhook_test.go
- model/post.go
Cherry pick of #18370 on release-6.0.
> Automated cherry pick of #18370

- model/feature_flags.go
Add A/B test for prewritten messages. No QA through this PR. It will be tested in the related [webapp PR]().
https://mattermost.atlassian.net/browse/MM-38361
```release-note
Add A/B test for prewritten messages
```
> Mm 38361 pre written messages

- app/server.go
Cherry pick of #18341 on release-6.0.
> Automated cherry pick of #18341

- model/version.go
> Update version to 5.39.1

- app/post.go
- app/post_test.go
Cherry pick of #18361 on release-6.0.
/cc  @mkraft
> Automated cherry pick of #18361

- app/email/email_batching.go
- app/notification_email.go
- i18n/en.json
- templates/messages_notification.html
- templates/partials/card.mjml
- templates/partials/style.mjml
Cherry pick of #18221 on release-6.0.
/cc  @AGMETEOR
> Automated cherry pick of #18221

- model/config.go
- model/config_test.go
- model/feature_flags.go
- services/telemetry/telemetry.go
Updates instances of the playbook plugin ID. 
Should be merged after https://github.com/mattermost/mattermost-plugin-playbooks/pull/740 
https://mattermost.atlassian.net/browse/MM-38122
```release-note
NONE
```
> MM-38122 Update to use new plugin ID for playbooks.

- model/feature_flags.go
Add feature flag support for download apps A/B test.
https://mattermost.atlassian.net/browse/MM-38364
```release-note
NONE
```
> add feature flag

- store/sqlstore/post_store.go
Cherry pick of #18363 on release-6.0.
/cc  @koox00
> Automated cherry pick of #18363

- store/sqlstore/audit_store.go
Fixes https://github.com/mattermost/mattermost-server/issues/18407
```release-note
```
> [GH-18407] Migrate from gorp to sqlx in store/sqlstore/audit_store.go

- cmd/mattermost/commands/import.go
Cherry pick of #18413 on release-6.0.
> Automated cherry pick of #18413

- app/post_metadata.go
Debug log for https://community-daily.mattermost.com/private-core/pl/8bgfagfxktbwdn7mujo4gfsoeh
> Add debug log for nil referencedPost

- app/post_metadata.go
Cherry pick of #18437 on release-6.0.
/cc @mickmister
> Add debug log for nil referencedPost (#18437)

- model/config.go
- model/config_test.go
- model/feature_flags.go
- services/telemetry/telemetry.go
Cherry pick of #18392 on release-6.0.
> Automated cherry pick of #18392

- plugin/client_rpc.go
Cherry pick of #18452 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #18452

- api4/post.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/post.go
- app/post_metadata.go
- app/post_metadata_test.go
Cherry pick of #18454 on release-6.0.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #18454

- api4/post.go
- app/post.go
- app/reaction.go
- app/webhook.go
- i18n/en.json
Cherry pick of #18464 on release-6.0.
```release-note
NONE
```
> Automated cherry pick of #18464

- api4/user.go
- api4/user_test.go
Cherry pick of #18460 on release-6.0.
```release-note
NONE
```
> Automated cherry pick of #18460

- store/sqlstore/upgrade.go
We need to move the `UPDATE Posts` query up in order to make it work since we are dropping the `ParentId` column.
@amyblais This requires cherry-picking to 6.0 branch to fix an issue with the migration code.
https://mattermost.atlassian.net/browse/MM-39014
```release-note
NONE
```
> [MM-39014] Execute update posts query first in 6.0 db schema migration

- app/app.go
- app/options.go
- app/searchengine.go
> Remove searchEngine from App

- store/sqlstore/command_webhook_store.go
Fixes https://github.com/mattermost/mattermost-server/issues/18499
> Migrate from gorp to sqlx in store/sqlstore/command_webhook_store.go

- i18n/pl.json
- i18n/sv.json
Cherry pick of #18545 on release-6.0.
/cc  @weblate
```release-note
NONE
```
> Automated cherry pick of #18545

- config/client.go
Cherry pick of #18539 on cloud.
/cc  @pablovelezvidal
```release-note
NONE
```
> Automated cherry pick of #18539

- store/sqlstore/channel_member_history_store.go
Migrate ChannelMemberHistoryStore to sqlx
Fixes https://github.com/mattermost/mattermost-server/issues/18408
```release-note
NONE
```
> MM-38624 Migrate ChannelMemberHistoryStore to sqlx

- Makefile
Cherry pick of #18405 on release-6.0.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #18405

- app/server.go
Cherry pick of #18860 on release-6.1.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #18860

- api4/config.go
- api4/config_local.go
- config/diff.go
- config/diff_test.go
- model/config.go
Cherry pick of #18855 on release-6.1.
```release-note
NONE
```
> Automated cherry pick of #18855

- api4/post.go
- api4/post_test.go
Cherry pick of #18835 on release-6.1.
```release-note
NONE
```
> Automated cherry pick of #18835

- api4/config.go
- api4/config_local.go
- config/diff.go
- config/diff_test.go
- model/config.go
Cherrypick for https://github.com/mattermost/mattermost-server/pull/18855 to `release-5.39` branch.
```release-note
NONE
```
> [MM-39597] Cherry-pick to 5.39

- model/auditconv.go
- model/auditconv_test.go
Cherry pick of #18862 on cloud.
```release-note
NONE
```
> Automated cherry pick of #18862

- app/oauth.go
- app/oauth_test.go
https://mattermost.atlassian.net/browse/MM-39208
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=bd79b0b2-39d8-4538-81e1-a275b35ff910
```release-note
NONE
```
> Use the correct error variable from provider.GetSSOSettings

- app/oauth.go
- app/oauth_test.go
Cherry pick of #18920 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #18920

- model/version.go
- store/sqlstore/upgrade.go
db: upgrade db for 6.1 on the release 6.1 branch
n/a
```release-note
db: upgrade db for 6.1 on the release 6.1 branch
```
> db: upgrade db for 6.1 on the release 6.1 branch

- app/server.go
Clearly outline the dependency graph
during server bootup.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4?c=87df1e15-588e-49ff-8bd1-ffa9651b8c82
```release-note
NONE
```
> Ordering clarifications

- app/server.go
Cherry pick of #18921 on cloud.
```release-note
NONE
```
> Automated cherry pick of #18921

- app/server.go
Reverts mattermost/mattermost-server#18937
```release-note
NONE
```
> Revert "Ordering clarifications"

- model/config.go
- services/telemetry/telemetry.go
> Add JobSettings.CleanupJobsThresholdDays to telemetry

- model/client4.go
follow up of https://github.com/mattermost/mattermost-server/pull/17435 we merged that but some changes was made and we did not notice
n/a
```release-note
NONE
```
> update client function to match the new format and fix bad merge

- api4/channel.go
Cherry pick of #18971 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #18971

- Makefile
Update prepackaged boards version to 0.10.0
```release-note
Update prepackaged boards version to 0.10.0
```
> prepackage boards to 0.10.0

- Makefile
Cherry pick of #18973 on release-6.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #18973

- store/sqlstore/user_access_token_store.go
Migrate from `gorp` to `sqlx` in `store/sqlstore/user_access_token_store.go`
Fixes https://github.com/mattermost/mattermost-server/issues/18877
JIRA - https://mattermost.atlassian.net/browse/MM-39639
```release-note
NONE
```
> [MM-39639] - Migrate from gorp to sqlx in store/sqlstore/user_access_token_store.go

- app/oauth.go
- app/oauth_test.go
> Use the correct error variable from provider.GetSSOSettings (#18920)

- store/sqlstore/session_store.go
Migrate from `gorp` to `sqlx` in `store/sqlstore/session_store.go`
Fixes https://github.com/mattermost/mattermost-server/issues/18880
JIRA - https://mattermost.atlassian.net/browse/MM-39642
```release-note
NONE
```
> [MM-39642] - Migrate from gorp to sqlx in store/sqlstore/session_store.go

- store/sqlstore/upload_session_store.go
Migrate from `gorp` to `sqlx` in `store/sqlstore/upload_session_store.go`
Fixes https://github.com/mattermost/mattermost-server/issues/18882
JIRA - https://mattermost.atlassian.net/browse/MM-39644
```release-note
NONE
```
> [MM-39644] - Migrate from gorp to sqlx in store/sqlstore/upload_session_store.go

- store/sqlstore/status_store.go
Migrate from `gorp` to `sqlx` in `store/sqlstore/status_store.go`
Fixes https://github.com/mattermost/mattermost-server/issues/18876
JIRA: https://mattermost.atlassian.net/browse/MM-39638
```release-note
NONE
```
> [MM-39638] - Migrate from gorp to sqlx in store/sqlstore/status_store.go

- store/sqlstore/webhook_store.go
For more information, check the ticket [here](https://mattermost.atlassian.net/browse/MM-39641)
Fixes #18879 
```release-note
NONE
```
> [MM-39641] Migrate Webhook store to sqlx

- api4/team.go
- api4/team_local.go
- app/app_iface.go
- app/email/email.go
- app/email/email_test.go
- app/email_test.go
- app/opentracing/opentracing_layer.go
- app/team.go
- i18n/en.json
- jobs/resend_invitation_email/worker.go
- model/feature_flags.go
- model/team_member.go
Cherry pick of #18894 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #18894

- app/plugin_api.go
- app/session.go
- i18n/en.json
- plugin/api.go
- plugin/api_timer_layer_generated.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Cherry pick of #18958 on cloud.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #18958

- api4/apitestlib.go
- api4/websocket_test.go
- app/web_conn.go
- app/web_hub.go
- app/web_hub_test.go
- app/websocket_router.go
- model/websocket_client.go
Cherry pick of #18982 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #18982

- store/sqlstore/thread_store.go
- store/storetest/thread_store.go
Cherry pick of #18966 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #18966

- app/post.go
- app/post_test.go
- model/websocket_message.go
- model/websocket_message_test.go
Cherry pick of #18977 on cloud.
```release-note
NONE
```
> Automated cherry pick of #18977

- store/sqlstore/post_store.go
- Skip searching for deleted posts. Just a follow-up to https://github.com/mattermost/mattermost-server/pull/18340. I forgot to push my local changes before merging on GitHub. 
- Part of https://mattermost.atlassian.net/browse/MM-37013
```release-note
NONE
```
> [MM-37013] Better post filtering for job

- web/oauth.go
- web/oauth_test.go
- web/saml.go
Cherry pick of #19020 on release-5.37.
/cc  @levb
```release-note
NONE
```
> Automated cherry pick of #19020

- jobs/resend_invitation_email/worker.go
Cherry pick of #19046 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19046

- api4/post.go
- api4/post_test.go
- api4/user.go
- api4/user_test.go
- i18n/en.json
https://mattermost.atlassian.net/browse/MM-40159
```release-note
NONE
```
> Take view archived config into account on users and posts api endpoints

- .circleci/config.yml
- .gitlab-ci.yml
- scripts/download_mmctl_release.sh
> Lock CI from /release-6.2

- config/logger.go
Cherry pick of #19018 on release-6.2.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #19018

- store/sqlstore/upgrade.go
- upgrade db to 6.2.0
n/a
```release-note
upgrade db to 6.2.0
```
> upgrade db to 6.2.0

- store/sqlstore/upgrade.go
Cherry pick of #19085 on release-6.2.
/cc  @cpanato
```release-note
NONE
```
> Automated cherry pick of #19085

- api4/post.go
- api4/post_test.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/post.go
- i18n/en.json
- model/client4.go
- store/sqlstore/post_store.go
Cherry pick of #18942 on release-6.2.
```release-note
NONE
```
> Automated cherry pick of #18942

- i18n/en.json
This PR improves the wording in the cloud signup welcome email
[MM-40395](https://mattermost.atlassian.net/browse/MM-39334)
```release-note
NONE
```
> [MM-40395] - Text Changes in Congratulations email after trial signup

- api4/post.go
- api4/post_test.go
- api4/user.go
- api4/user_test.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/plugin.go
- app/post.go
- app/post_metadata.go
- i18n/en.json
- i18n/pl.json
- jobs/resend_invitation_email/worker.go
- model/client4.go
- model/license.go
- model/version.go
- store/sqlstore/post_store.go
- store/sqlstore/upgrade.go
- utils/license.go
- web/handlers.go
- web/handlers_test.go
Merge master into cloud branch for cloud release
```release-note
NONE
```
> [Cloud Sync] Merge remote-tracking branch 'origin/master' 2021-12-02

- model/config.go
https://community-daily.mattermost.com/boards/workspace/g4k9s1f953n4bytz5f9sz9orer/16c12e26-4cda-4237-88c2-9a33f37d20ee/99977bbc-45ec-4aa4-889e-091f43e83737/449824d8-11ed-4103-8329-064bb990439e
Product Documentation update: https://github.com/mattermost/docs/pull/5274
Webapp update: https://github.com/mattermost/mattermost-webapp/pull/9412
```release-note
Updated "Terms of Service" terminology to "Terms of Use" product-wide.
```
> Updated Terms of Service to Terms of Use

- i18n/en.json
Updated **Account Settings** terminology to **Settings**. 
N/A
```release-note
Updated **Account Settings** terminology to **Settings**. 
```
> Updated Account Settings to Settings

- store/sqlstore/license_store.go
Migrate from `gorp` to `sqlx` in `store/sqlstore/license_store.go`.
JIRA [MM-39231](https://mattermost.atlassian.net/browse/MM-39231)
Fixes #18629
```release-note
NONE
```
> [MM-39231] Migrate license store from gorp to sqlx in store/sqlstore/license_store.go 

- Makefile
Cherry pick of #19111 on release-6.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #19111

- Makefile
Update prepackaged boards version to 0.7.5
```release-note
Update prepackaged boards version to 0.7.5
```
> update boards version to 0.7.5

- Makefile
Update prepackaged boards version to 0.9.5
```release-note
Update prepackaged boards version to 0.9.5
```
> update boards version to 0.9.5

- Makefile
Update prepackaged boards version to 0.10.1
```release-note
Update prepackaged boards version to 0.10.1
```
> update boards version to 0.10.1

- app/file.go
This PR makes some improvements to the gif image processing
```release-note
None
```
> Improve gif processing

- app/file.go
Cherry pick of #19164 on release-6.0.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19164

- app/plugin.go
- app/plugin_test.go
Cherry pick of #19192 on release-6.2.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19192

- app/channels.go
Previously, for every config change, we would re-initialize
plugins irrespective of whether there would be any actual
plugin related changed or not.
Now, we compute the difference between previous and new configs
and check whether there has been any changes to plugin related
configuration, and re-init plugins only if that's true.
This improves performance as plugin re-initialization is quite
costly.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/bed59298-27da-4b74-8be5-cdeb4c50c3e2
```release-note
Plugins are re-initialized only when Plugin related config changes happen. This improves performance by avoiding plugin initialization which is quite costly.
```
> Re-initialize plugins only when needed

- store/sqlstore/command_store.go
- store/sqlstore/compliance_store.go
- store/sqlstore/store.go
This Pull Request adds a new helper function to use proper cases for reserved names depending on the database driver.
Fixes https://github.com/mattermost/mattermost-server/issues/19105
```
NONE
```
> [GH-19105] - Add helper function to handle columns on reserved names

- store/sqlstore/post_store.go
During v6 indexing changes, we replaced
idx_posts_root_id with idx_posts_root_id_delete_at.
This causes MySQL to trigger the index_merge path
again with PRIMARY and idx_posts_root_id_delete_at
as shown below:
```
mysql> UPDATE Posts SET DeleteAt = 1637998911685, UpdateAt = 1637998911685, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o';
Query OK, 9 rows affected (17.29 sec)
Rows matched: 10  Changed: 9  Warnings: 0
mysql> EXPLAIN UPDATE Posts SET DeleteAt = 1637998911685, UpdateAt = 1637998911685, Props = JSON_SET(Props, '$.deleteBy', 'buqskqrwmjnhfuqskqrwmjn4ca') Where Id = 'q38uaydtpink5f4wkmcsn8h47o' OR RootId = 'q38uaydtpink5f4wkmcsn8h47o'\G
*************************** 1. row …
```
> Force right index for post deletion

- api4/license.go
- app/license.go
- app/server.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
This PR adds the necessary cloud interfaces to consume the new endpoint added in the portal
[MM-40407](https://mattermost.atlassian.net/browse/MM-40407)
https://github.com/mattermost/enterprise/pull/1116
https://github.com/mattermost/customer-web-server/pull/632
```release-note
NONE
```
> [MM-40407] - Do not show the Renew Now if the license id does not exist in the portal

- .circleci/config.yml
- .gitlab-ci.yml
- scripts/download_mmctl_release.sh
> Lock CI from /release-6.3

- store/sqlstore/store.go
Cherry pick of #19104 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19104

- build/release.mk
- scripts/download_mmctl_release.sh
Cherry pick of #19090 on release-6.3.
/cc  @cpanato
```release-note
NONE
```
> Automated cherry pick of #19090

- api4/websocket.go
- api4/websocket_test.go
- app/web_conn.go
- app/web_conn_test.go
- app/web_hub.go
- config/client.go
- model/config.go
Cherry pick of #19040 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19040

- build/release.mk
- scripts/download_mmctl_release.sh
Cherry pick of #19143 on release-6.3.
/cc  @cpanato
```release-note
NONE
```
> Automated cherry pick of #19143

- api4/role.go
- app/app_test.go
- app/migrations.go
- app/permissions_migrations.go
- app/plugin_api.go
- app/scheme.go
- model/migration.go
- model/permission.go
- model/role.go
- model/scheme.go
- plugin/api.go
- plugin/api_timer_layer_generated.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- store/sqlstore/integrity_test.go
- store/sqlstore/scheme_store.go
- store/sqlstore/upgrade.go
- store/storetest/scheme_store.go
- testlib/store.go
Cherry pick of #19096 on release-6.3.
```release-note
NONE
```
> Automated cherry pick of #19096

- store/sqlstore/product_notices_store.go
Cherry pick of #19012 on release-6.3.
/cc  @YairFernando67
```release-note
NONE
```
> Automated cherry pick of #19012

- model/utils.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherry pick of #18795 on release-6.3.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #18795

- app/plugin_commands.go
- app/plugin_commands_test.go
Cherry pick of #19136 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19136

- model/manifest.go
Cherry pick of #19122 on release-6.3.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #19122

- api4/apitestlib.go
- api4/file_test.go
- api4/team_test.go
Cherry pick of #19179 on release-6.3.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #19179

- store/sqlstore/license_store.go
Cherry pick of #19146 on release-6.3.
/cc  @YairFernando67
```release-note
NONE
```
> Automated cherry pick of #19146

- store/sqlstore/role_store.go
Cherry pick of #19022 on release-6.3.
/cc  @shadowshot-x
```release-note
NONE
```
> Automated cherry pick of #19022

- shared/mfa/mfa_test.go
Cherry pick of #19177 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19177

- app/brand.go
- app/channels.go
- app/file.go
- app/server.go
- app/slack.go
- app/team.go
- app/upload.go
- app/user.go
Cherry pick of #19113 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19113

- store/sqlstore/upgrade.go
- upgrade db to 6.3.0
n/a
```release-note
upgrade db to 6.3.0
```
> upgrade db to 6.3.0

- store/sqlstore/upgrade.go
Cherry pick of #19217 on release-6.3.
/cc  @cpanato
```release-note
NONE
```
> Automated cherry pick of #19217

- web/handlers.go
- web/handlers_test.go
Cherry-pick of #19097 
```release-note
NONE
```
> Cherry-pick of #19097

- model/utils.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
There are several queries which should improve further
if re-written with squirrel. HW tickets will be opened
for those.
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/ctnryw9mga7fu9kc16xsap4phuw
```release-note
NONE
```
> Migrate post_store to sqlx

- model/version.go
- store/sqlstore/upgrade.go
Adds a missing migration for users table.
https://mattermost.atlassian.net/browse/MM-40778
```release-note
NONE
```
> Remove AcceptedTermsOfServiceId from Users table

- model/version.go
- store/sqlstore/upgrade.go
Cherry-pick  #19263 
```release-note
NONE
```
> add migration for removing AcceptedTermsOfServiceId column from Users

- store/sqlstore/upgrade.go
Let's not forget this one
```release-note
NONE
```
> move removal of AcceptedTermsOfServiceId from users table to 6.3

- shared/filestore/s3store.go
Cherry pick of #19251 on release-6.3.
/cc  @pablovelezvidal
```release-note
NONE
```
> Automated cherry pick of #19251

- i18n/de.json
- i18n/en_AU.json
- i18n/hu.json
- i18n/ko.json
- i18n/nl.json
- i18n/sv.json
- i18n/tr.json
> Cherry-pick translations 20220106

- i18n/de.json
- i18n/en_AU.json
- i18n/hu.json
- i18n/ko.json
- i18n/nl.json
- i18n/sv.json
- i18n/tr.json
> Cherry-pick translations 20220106 cloud

- .circleci/config.yml
- i18n/en.json
- model/config.go
- Remove config check for replica lag settings
- Uncomment some CI steps
- Checkout master branch instead
```release-note
NONE
```
> Fix a couple of issues related with morph feature branch

- .circleci/config.yml
https://mattermost.atlassian.net/browse/MM-40852
```release-note
NONE
```
> MM-40852: Add make gen-serialized to CI

- app/email/email.go
- app/email/email_test.go
- go.mod
- go.sum
- vendor/github.com/microcosm-cc/bluemonday/.coveralls.yml
- vendor/github.com/microcosm-cc/bluemonday/.travis.yml
- vendor/github.com/microcosm-cc/bluemonday/CONTRIBUTING.md
- vendor/github.com/microcosm-cc/bluemonday/CREDITS.md
- vendor/github.com/microcosm-cc/bluemonday/LICENSE.md
- vendor/github.com/microcosm-cc/bluemonday/Makefile
- vendor/github.com/microcosm-cc/bluemonday/README.md
- vendor/github.com/microcosm-cc/bluemonday/doc.go
- vendor/github.com/microcosm-cc/bluemonday/go.mod
- vendor/github.com/microcosm-cc/bluemonday/go.sum
- vendor/github.com/microcosm-cc/bluemonday/helpers.go
- vendor/github.com/microcosm-cc/bluemonday/policies.go
- vendor/github.com/microcosm-cc/bluemonday/policy.go
- vendor/github.com/microcosm-cc/bluemonday/sanitize.go
- vendor/modules.txt
PR adds HTML sanitization to the message field that gets inserted in the email template for guest users invitations.
https://mattermost.atlassian.net/browse/MM-40898
```release-note
NONE
```
> [MM-40898] Sanitize message in email template

- store/sqlstore/channel_store.go
Cherry pick of #19310 on release-6.3.
```release-note
NONE
```
> Automated cherry pick of #19310

- go.mod
- go.sum
- i18n/en.json
- model/config.go
- store/sqlstore/store.go
- vendor/github.com/go-morph/morph/README.md
- vendor/github.com/go-morph/morph/drivers/driver.go
- vendor/github.com/go-morph/morph/drivers/lock.go
- vendor/github.com/go-morph/morph/drivers/mysql/lock.go
- vendor/github.com/go-morph/morph/drivers/mysql/mysql.go
- vendor/github.com/go-morph/morph/drivers/postgres/lock.go
- vendor/github.com/go-morph/morph/drivers/postgres/postgres.go
- vendor/github.com/go-morph/morph/drivers/utils.go
- vendor/github.com/go-morph/morph/morph.go
- vendor/github.com/go-morph/morph/sources/file/file.go
- vendor/modules.txt
Updates the morph dependency, with the new version we use our own mutex locking implementation.
```release-note
NONE
```
> Update morph dependency

- i18n/de.json
- i18n/en_AU.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/sv.json
- i18n/tr.json
> Cp translations 2022 01 12 release 6.3

- i18n/de.json
- i18n/en_AU.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/sv.json
- i18n/tr.json
> Cp translations 2022 01 12 cloud

- go.mod
- go.sum
- vendor/github.com/go-morph/morph/drivers/mysql/mysql.go
- vendor/github.com/go-morph/morph/drivers/mysql/utils.go
- vendor/github.com/go-morph/morph/drivers/postgres/postgres.go
- vendor/github.com/go-morph/morph/drivers/postgres/utils.go
- vendor/github.com/go-morph/morph/morph.go
- vendor/modules.txt
Fix a data race on the morph
https://mattermost.atlassian.net/browse/MM-40973
```release-note
NONE
```
> Update morph dependecy to fix a data race

- Makefile
Cherry pick of #19299 on release-6.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #19299

- model/channel.go
- model/utils.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
https://community-daily.mattermost.com/boards/workspace/zyoahc9uapdn3xdptac6jb69ic/285b80a3-257d-41f6-8cf4-ed80ca9d92e5/495cdb4d-c13a-4992-8eb9-80cfee2819a4/chur9rxkghprg7dz1mcqssj34ic
```release-note
NONE
```
> Migrate channel_store to sqlx

- store/sqlstore/channel_store.go
> channel_store: update TODO items with issues

- api4/team.go
- api4/team_test.go
Cherry pick of #19280 on release-6.3.
```release-note
NONE
```
> Automated cherry pick of #19280

- api4/user_test.go
- app/login.go
Cherry pick of #19339 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19339

- i18n/de.json
- i18n/en_AU.json
- i18n/es.json
- i18n/hu.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
Translations update from Mattermost Weblate
Cherry pick from #19371 
```release-note
NONE
```
> Translation cherry pick from #19371

- Makefile
Update prepackaged boards version to 0.12.1
```release-note
Update prepackaged boards version to 0.12.1
```
> Prepackage boards to v0.12.1 release

- Makefile
Cherry pick of #19375 on release-6.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #19375

- api4/config.go
- api4/config_local.go
- api4/config_test.go
- i18n/en.json
Cherry pick of #19373 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19373

- web/handlers.go
Cherry pick of #19393 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19393

- .circleci/config.yml
We want to test with both text and binary mode. Using our CI
to test both in parallel.
```release-note
NONE
```
> CI: Add another parallel stage for binary_parameters=yes

- model/utils.go
PR https://github.com/mattermost/mattermost-server/pull/19404 fixed replies on posts by casting StringArray to a string.
This PR fixes editing and pinning a post by casting `StringMap`, and
`StringInterface` to a string as well.
https://mattermost.atlassian.net/browse/MM-41066
```release-note
Fixed inserting a `jsonb` field into the DB when `binary_parameters=yes`
```
> Fixes editing and pinning a post

- model/cloud.go
Cherry pick of #19340 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #19340

- go.mod
- go.sum
- vendor/github.com/go-morph/morph/drivers/lock.go
- vendor/github.com/go-morph/morph/drivers/mysql/mysql.go
- vendor/github.com/go-morph/morph/drivers/postgres/postgres.go
- vendor/github.com/go-morph/morph/morph.go
- vendor/modules.txt
Cherry pick of #19421 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19421

- app/license.go
- app/license_test.go
Cherry pick of #19417 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19417

- i18n/en.json
- Updated Firefox version to Version 91+ (current ESR) (Let me know any concerns on this)
- Corrected Windows support to 8.1+ (We dropped support for Win 7 for v6.0 release and it was communicated back then. This file missed getting updated)
Will add to release notes.
> Update supported browser/OS versions

- app/channel.go
Summary
CRT server book-keeping should only happen if ThreadAutoFollow is true.
Ticket Link
https://mattermost.atlassian.net/browse/MM-41350
(cherry picked from commit 58879719f2b43840084e3901e1029b3478dc31e5) onto release-5.37
```release-note
On the server, CRT Threads will only be kept up to date if ThreadAutoFollow config is set to true
```
> [MM-41350] All CRT server operations should only happen if ThreadAutoFollow is true

- model/feature_flags.go
This PR removes the feature flag associated with the AB test.
*QA is done on the Webapp PR*
https://mattermost.atlassian.net/browse/MM-41189
https://github.com/mattermost/mattermost-webapp/pull/9709
```release-note
NONE
```
> [MM-41189] Remove "Invite to team" feature flag

- i18n/de.json
- i18n/en_AU.json
- i18n/es.json
- i18n/fr.json
- i18n/hu.json
- i18n/nl.json
- i18n/pl.json
- i18n/tr.json
cherry picks of
https://github.com/mattermost/mattermost-server/pull/19453
https://github.com/mattermost/mattermost-server/pull/19464
in the cloud branch 
```release-note
NONE
```
> cherry picks Translations update from Mattermost Weblate #19453 #19464

- .circleci/config.yml
- .gitlab-ci.yml
- scripts/download_mmctl_release.sh
> Lock CI from /release-6.4

- services/docextractor/documents.go
Cherry pick of #19436 on release-6.3.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #19436

- app/channel.go
Cherry pick of #19411 on release-6.4.
```release-note
NONE
```
> Automated cherry pick of #19411

- i18n/en.json
- web/saml.go
Cherry pick of #19423 on release-6.4.
/cc  @iomodo
```release-note
NONE
```
> Automated cherry pick of #19423

- api4/user_test.go
- app/post_test.go
- model/config.go
Cherry pick of #19441 on release-6.4.
```release-note
NONE
```
> Automated cherry pick of #19441

- .circleci/config.yml
Cherry pick of #19409 on release-6.4.
/cc  @spirosoik
```release-note
NONE
```
> Automated cherry pick of #19409

- store/sqlstore/upgrade.go
bump database for 6.4.0 schema
https://mattermost.atlassian.net/browse/DOPS-786
```release-note
bump database for 6.4.0 schema
```
> Update database to v6.4.0

- store/sqlstore/upgrade.go
Cherry pick of #19500 on release-6.4.
/cc  @spirosoik
```release-note
NONE
```
> Automated cherry pick of #19500

- app/notification.go
We throttle the concurrency limit in maintaining thread membership
for a given thread using a counting semaphore. The limit is currently
8 which is a decent number to start with.
On some more thinking, it would be even better if the sql query
could be modified to support batch updates.
https://mattermost.atlassian.net/browse/MM-41085
```release-note
NONE
```
> MM-41085: Use a counting semaphore in sendNotifications

- i18n/de.json
- i18n/en_AU.json
- i18n/es.json
- i18n/fr.json
- i18n/hu.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/sv.json
- i18n/tr.json
- i18n/zh-CN.json
cherry pick ok https://github.com/mattermost/mattermost-server/pull/19514 in cloud branch
n/a
```release-note
NONE
```
> [Cherry pick] Translations update from Mattermost Weblate 

- store/sqlstore/channel_store.go
Fixes https://github.com/mattermost/mattermost-server/issues/19332
```release-note
NONE
```
> Migrate ChannelStore.UpdateLastViewedAt to squirrel

- model/channel.go
- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_categories.go
- store/sqlstore/preference_store.go
- store/storetest/mocks/dbSelecter.go
Remove db:"-" tags from model.Channel as well.
```release-note
NONE
```
> Migrate Channelstore categories to sqlx

- model/version.go
- store/sqlstore/upgrade.go
https://mattermost.atlassian.net/browse/DOPS-786
```release-note
NONE
```
> prepare for next 6.5.0

- Makefile
Cherry pick of #19518 on release-6.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #19518

- store/storetest/thread_store.go
https://mattermost.atlassian.net/browse/MM-41797
```release-note
NONE
```
> MM-41797: Skip Flaky test in ThreadStore

- go.mod
- go.sum
- vendor/github.com/go-morph/morph/color_logger.go
- vendor/github.com/go-morph/morph/morph.go
- vendor/modules.txt
> Bump morph dependency

- app/license.go
Based on observations from: https://community-daily.mattermost.com/core/pl/opdbqncpx3b9fdbkiaj17t5muy
```release-note
NONE
```
> Changing log level for some license logs

- app/email/email.go
- app/server.go
- app/server_inactivity.go
- i18n/en.json
- model/feature_flags.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/post_store.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/mocks/SessionStore.go
- store/storetest/post_store.go
- store/storetest/session_store.go
- store/timerlayer/timerlayer.go
- templates/inactivity_body.html
- templates/inactivity_body.mjml
Cherry pick of #19374 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19374

- app/notification_test.go
https://mattermost.atlassian.net/browse/MM-41972
```release-note
NONE
```
> MM-41972: Skip flaky test TestAllowGroupMentions

- db/migrations/bindata.go
- db/migrations/mysql/000077_upgrade_users_v6.5.down.sql
- db/migrations/mysql/000077_upgrade_users_v6.5.up.sql
- db/migrations/postgres/000077_upgrade_users_v6.5.down.sql
- db/migrations/postgres/000077_upgrade_users_v6.5.up.sql
Cherrypick of https://github.com/mattermost/mattermost-server/pull/19591
```release-note
```
> Cherry pick of [MM-41756] Remove AcceptedServiceTermsId column #19591

- api4/channel_test.go
https://mattermost.atlassian.net/browse/MM-42092
```release-note
NONE
```
> Skip TestDeleteChannel

- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/team.go
- app/team_test.go
- i18n/en.json
- jobs/jobs.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/job_store.go
- store/store.go
- store/storetest/job_store.go
- store/storetest/mocks/JobStore.go
- store/timerlayer/timerlayer.go
Fixes MM-42027
[MM-42027](https://mattermost.atlassian.net/browse/MM-42027)
```release-note
NONE
```
> Fixed MM-42027

- app/migrations.go
- app/onboarding.go
- model/system.go
Cherry pick of #19642 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #19642

- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/team.go
- app/team_test.go
- i18n/en.json
- jobs/jobs.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/job_store.go
- store/store.go
- store/storetest/job_store.go
- store/storetest/mocks/JobStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #19619 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19619

- i18n/de.json
- i18n/en_AU.json
- i18n/hu.json
- i18n/it.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/tr.json
Reverts mattermost/mattermost-server#19647
> Revert "Translations update from Mattermost Weblate"

- app/license.go
Following the report from the ticket attached to this PR, decision was made to remove the log in the diff
[MM-40962](https://mattermost.atlassian.net/browse/MM-40962)
```release-note
NONE
```
> [MM-40962] - Remove log when checking renewal token validity

- app/import_validators.go
- app/import_validators_test.go
- i18n/en.json
Cherry pick of #19641 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19641

- app/permissions_migrations.go
- model/migration.go
- model/permission.go
- model/role.go
- testlib/store.go
Adding some permissions for playbooks. See details in the linked ticket. 
Tests are added in the playbooks PR. 
https://mattermost.atlassian.net/browse/MM-41950
```release-note
NONE
```
> MM41950 Add new playbooks permissions.

- api4/plugin.go
- api4/plugin_test.go
- app/plugin_install.go
- i18n/en.json
Cherry pick of #19613 on cloud.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #19613

- .circleci/config.yml
- .gitlab-ci.yml
- scripts/download_mmctl_release.sh
> Lock CI from /release-6.5

- api4/resolver_user.go
- api4/resolver_user_test.go
- api4/schema.graphqls
- model/channel.go
- model/session.go
- model/team.go
Also added sessions as part of the user object
https://mattermost.atlassian.net/browse/MM-42268
```release-note
NONE
```
> MM-42268: Added more fields to Channel and Team

- api4/user_test.go
- app/channels.go
- app/post_test.go
- app/product_notices.go
- app/server.go
- app/session.go
https://mattermost.atlassian.net/browse/MM-40816
```release-note
NONE
```
> MM-40813: Use config service more extensively

- api4/system.go
- api4/system_test.go
Fix MM-42270
```release-note
NONE
```
> Fix MM-42270

- scripts/download_mmctl_release.sh
Fix download mmctl script
https://mattermost.atlassian.net/browse/DOPS-853
```release-note
NONE
```
> Fix mmctl download bash script

- store/sqlstore/group_store.go
- store/storetest/group_store.go
Cherry pick of #19600 on release-6.5.
```release-note
NONE
```
> Automated cherry pick of #19600

- plugin/api.go
Cherry pick of #19605 on release-6.5.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #19605

- store/sqlstore/user_terms_of_service.go
- store/storetest/user_terms_of_service.go
Cherry pick of #19587 on release-6.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #19587

- app/web_hub.go
- app/web_hub_test.go
- model/websocket_message.go
Cherry pick of #19594 on release-6.5.
```release-note
NONE
```
> Automated cherry pick of #19594

- app/server.go
Cherry pick of #19733 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19733

- api4/group_test.go
- app/group.go
- app/group_test.go
- app/user.go
- app/user_test.go
- i18n/en.json
- model/group.go
Cherry pick of #19660 on release-6.5.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #19660

- app/server_inactivity.go
Cherry pick of #19668 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19668

- model/feature_flags.go
- testlib/store.go
Cherry pick of #19690 on release-6.5.
```release-note
NONE
```
> Automated cherry pick of #19690

- app/channel.go
- app/channel_test.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/channel_store.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/ThreadStore.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #19566 on release-6.5.
```release-note
NONE
```
> Automated cherry pick of #19566

- app/helper_test.go
- app/license.go
- app/server.go
- app/slashcommands/helper_test.go
- jobs/jobs_test.go
- jobs/jobs_watcher.go
- jobs/schedulers.go
- jobs/schedulers_test.go
- jobs/server.go
- jobs/server_test.go
- jobs/workers.go
Cherry pick of #19748 on release-6.5.
/cc  @pablovelezvidal
```release-note
NONE
```
> Automated cherry pick of #19748

- jobs/server_test.go
https://mattermost.atlassian.net/browse/MM-42412
```release-note
NONE
```
> MM-42412: Skip TestStart/StopWorkers

- jobs/server_test.go
Cherry pick of #19753 on release-6.5.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19753

- api4/system.go
- api4/system_test.go
https://mattermost.atlassian.net/browse/MM-42271
```release-note
NONE
```
> MM-42271: Restrict support packet generation to system admin.

- api4/channel.go
- api4/cloud.go
- api4/config.go
- api4/group.go
- api4/handlers.go
- api4/ldap.go
- api4/license.go
- api4/role.go
- api4/scheme.go
- api4/system.go
- api4/team.go
- api4/terms_of_service.go
- api4/user.go
- app/admin_advisor.go
- app/channels.go
- app/plugin_api.go
- app/web_conn.go
- web/context.go
- web/handlers.go
https://mattermost.atlassian.net/browse/MM-40817
```release-note
NONE
```
> MM-40817: Use license interface in Channels

- i18n/de.json
- i18n/hu.json
- i18n/ru.json
- i18n/tr.json
- Fix weblate conflicts
```release-note
NONE
```
> Fix weblate conflicts

- app/channels.go
- app/file.go
- app/notification_push_test.go
- app/options.go
- app/server.go
We move away from referencing server struct
but pass the filestore service to Channels
explicitly.
https://mattermost.atlassian.net/browse/MM-40818
```release-note
NONE
```
> MM-40818: Pass filestore to channels

- api4/system_test.go
- app/onboarding.go
Cherry pick of #19771 on release-6.5.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #19771

- Makefile
Cherry pick of #19749 on release-6.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #19749

- model/feature_flags.go
removes feature flag `GlobalHeader`
[MM-37838](https://mattermost.atlassian.net/browse/MM-37838)
```release-note
NONE
```
> [MM-37838]: remove feature flag for global header

- store/sqlstore/channel_store_categories.go
- store/sqlstore/post_store.go
- store/sqlstore/sqlx_wrapper.go
- store/sqlstore/store.go
- store/sqlstore/user_store.go
> Removing remaining instances of GetReplica/GetMaster

- store/sqlstore/post_store.go
Cherry pick of #19191 on release-6.3.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19191

- api4/cloud.go
Fix MM-42643
https://github.com/mattermost/enterprise/pull/1172/
```release-note
NONE
```
> Fix MM-42643

- i18n/bg.json
- i18n/en_AU.json
- i18n/es.json
- i18n/fa.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/sv.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
See https://github.com/mattermost/mattermost-webapp/pull/10038
https://mattermost.atlassian.net/browse/MM-42675
https://github.com/mattermost/mattermost-webapp/pull/10038
```release-note
NONE
```
> MM-42675 Update URLs in non-English i18n files

- api4/cloud.go
Cherry pick of #19811 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #19811

- i18n/bg.json
- i18n/en_AU.json
- i18n/es.json
- i18n/fa.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/sv.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Cherry pick of #19817 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #19817

- api4/system.go
- api4/system_test.go
- i18n/de.json
- i18n/en.json
- i18n/hu.json
- i18n/nl.json
- i18n/ru.json
- i18n/tr.json
Adjust the permission requirement to be similar with other system console permission levels.
https://mattermost.atlassian.net/browse/MM-42573
```release-note
NONE
```
> api4/system: adjust permissions for applied schema migrations

- api4/resolver_channel.go
- api4/resolver_channel_test.go
- api4/schema.graphqls
- model/channel_stats.go
Added stats.
https://mattermost.atlassian.net/browse/MM-42342
```release-note
graphql: Added new stats field under channel object.
```
> graphql: Add channel stats under channel

- app/user.go
- app/user_test.go
Makes sanitization more explicit, the only reason we got away from this so far was assigning the pointer to the new value. 
https://mattermost.atlassian.net/browse/MM-42647
```release-note
NONE
```
> app/user: ensure that user gets sanitized while calling plugin hooks

- api4/apitestlib.go
- api4/channel.go
- api4/channel_test.go
- app/app_iface.go
- app/channel.go
- app/opentracing/opentracing_layer.go
- i18n/en.json
- model/channel_stats.go
- model/cluster_message.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
- store/timerlayer/timerlayer.go
This PR adds the number of files in a channel in the channel stats.
QA will be done on the frontend part.
https://mattermost.atlassian.net/browse/MM-41998
https://github.com/mattermost/mattermost-webapp/pull/10045
```release-note
NONE
```
> [MM-41998] Channel Info RHS: display number of files for a channel

- .github/workflows/codeql-analysis.yml
> Add retry logic to initialize CodeQL

- api4/channel_category_test.go
https://mattermost.atlassian.net/browse/MM-42652
```release-note
NONE
```
> MM-42652: Skip Flaky test in CreateCategoryForTeamForUser

- Makefile
https://mattermost.atlassian.net/browse/MM-42571
```release-note
Pre-package Playbooks v1.26.0
Playbooks specific release notes can be found at:
https://github.com/mattermost/mattermost-plugin-playbooks/releases/tag/v1.26.0
```
> MM-42571: Pre-package Playbooks v1.26.0

- app/server.go
- app/teams/teams.go
A new method added to team service. This will be required for compiling Focalboard.
```release-note
NONE
```
> app/teams: add getMember method

- .circleci/config.yml
- .gitlab-ci.yml
> Lock CI from /release-6.6

- model/version.go
Cherry pick of #19795 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #19795

- api4/post_test.go
Skip flaky test.
https://mattermost.atlassian.net/browse/MM-42997
```release-note
NONE
```
> api4/post_test: skip TestDeletePostEvent

- app/post.go
Cherry pick of #19890 on cloud.
/cc  @michelengelen
```release-note
NONE
```
> Automated cherry pick of #19890

- api4/system.go
Cherry pick of #19920 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #19920

- api4/post_test.go
- app/channel.go
Cherry pick of #19927 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19927

- Makefile
- config/diff_test.go
- model/config.go
- model/feature_flags.go
Cherry pick of #19870 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #19870

- store/sqlstore/channel_store.go
Search term was being ignored when browsing archived channels
[MM-42889](https://mattermost.atlassian.net/browse/MM-42889)
```release-note
Fixed search term for archived channels
```
> [MM-42889] fixed search term for archived channels

- store/sqlstore/channel_store.go
Cherry pick of #19937 on cloud.
```release-note
NONE
```
> Automated cherry pick of #19937

- cmd/mattermost/commands/server_test.go
https://mattermost.atlassian.net/browse/MM-42880
```release-note
NONE
```
> MM-42880: Fix TestRunServerSuccess

- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Cherry pick of #19939 on cloud.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #19939

- app/channel.go
- app/server.go
Add channels service wrapper.
https://mattermost.atlassian.net/browse/MM-42186
```release-note
NONE
```
> app: add channels wrapper

- i18n/de.json
- i18n/en_AU.json
- i18n/fr.json
- i18n/pl.json
Weblate conflicts
```release-note
NONE
```
> Weblate 220407

- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/mocks/GroupStore.go
- store/timerlayer/timerlayer.go
Adds some specific group counts to telemetry.
https://mattermost.atlassian.net/browse/MM-43082
```release-note
Added some new telemetry fields to differentiate between LDAP and custom groups to understand usage.
```
> MM-43082: Added new telemetry values for groups.

- api4/graphql.go
- api4/resolver.go
- api4/resolver_team.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/team.go
- app/teams/teams.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/timerlayer/timerlayer.go
> MM-43144: Add teams loader

- app/post_metadata_test.go
https://mattermost.atlassian.net/browse/MM-43252
```release-note
NONE
```
> MM-43252: Skip TestPreparePostForClient

- app/import_functions_test.go
- app/import_test.go
https://mattermost.atlassian.net/browse/MM-43341
```release-note
NONE
```
> MM-43341: Skip TestImportImportUser

- model/websocket_client_test.go
We wait until the loop has exited to finish the test
https://mattermost.atlassian.net/browse/MM-43232
```release-note
NONE
```
> MM-43232: Racy test TestWebsocketRace

- Makefile
> Cleaning up old migration commands

- model/feature_flags.go
> Add feature flag for command palette

- scripts/download_mmctl_release.sh
There are cases that instead of suffix, we get a SHA prefix for cherrypicking branch.
For example this [PR](https://github.com/mattermost/mattermost-server/pull/19906) in which a manual cherrypicking process has started. (because of Mattermod failure to auto-cherrypick due to Conflicts) 
We rewrite the regex to support this case
Ticket: https://mattermost.atlassian.net/browse/DOPS-920
```release-note
```
> [DOPS-920] Fix mmctl download bash script

- i18n/bg.json
- i18n/de.json
- i18n/en_AU.json
- i18n/es.json
- i18n/fa.json
- i18n/fr.json
- i18n/hu.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Cherry pick of https://github.com/mattermost/mattermost-server/pull/20017
> Weblate cloud pr 20017

- db/migrations/mysql/000082_upgrade_oauth_mattermost_app_id.down.sql
- db/migrations/mysql/000082_upgrade_oauth_mattermost_app_id.up.sql
- db/migrations/postgres/000082_upgrade_oauth_mattermost_app_id.down.sql
- db/migrations/postgres/000082_upgrade_oauth_mattermost_app_id.up.sql
Cherry pick of #20028 on release-6.6.
```release-note
NONE
```
> Automated cherry pick of #20028

- store/sqlstore/system_store.go
- store/storetest/system_store.go
https://mattermost.atlassian.net/browse/MM-43653
```release-note
NONE
```
> MM-43653: Fix incorrect system store update

- store/sqlstore/system_store.go
- store/storetest/system_store.go
Cherry pick of #20051 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20051

- app/imaging/svg.go
- app/imaging/svg_test.go
Cherry pick of #19988 on release-6.6.
/cc  @michelengelen
```release-note
NONE
```
> Automated cherry pick of #19988

- api4/system.go
- api4/system_test.go
- app/app_iface.go
- app/notification_push.go
- app/notification_push_test.go
- app/opentracing/opentracing_layer.go
- model/push_notification.go
- store/storetest/group_store.go
- store/storetest/post_store.go
- store/storetest/user_store.go
Cherry pick of #19610 
None
```release-note
NONE
```
> Cherry pick of #19610

- go.mod
- go.sum
- vendor/github.com/mattermost/gosaml2/types/encrypted_key.go
- vendor/modules.txt
> Bump GoSAML dependency

- app/post_test.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-43848
https://mattermost.atlassian.net/browse/MM-43871
```release-note
NONE
```
> MM-43848: Skip flaky TestUserStore/LocalCache+MySQL/UpdateUpdateAt

- .circleci/config.yml
- .gitlab-ci.yml
> Lock CI from /release-6.7

- i18n/en.json
Cherry pick of #20093 on release-6.7.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #20093

- api4/elasticsearch.go
- api4/elasticsearch_test.go
- i18n/en.json
- model/config.go
Add nil value check to elasticsearch settings.
https://mattermost.atlassian.net/browse/MM-43199
```release-note
NONE
```
> [MM-43199] api4/elasticsearch: test elasticsearch after checking the config values

- build/Dockerfile.buildenv
Update dockerfile to 1.18.1
```release-note
NONE
```
> Update Dockerfile to 1.18.1

- build/Dockerfile.buildenv
Cherry pick of #20138 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20138

- model/config.go
Cherry pick of #20137 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #20137

- Makefile
- build/release.mk
Adding Calls to the next on-prem release. 
https://mattermost.atlassian.net/browse/MM-43644
```release-note
Pre-package Calls v0.4.9
```
> [MM-43644] Prepackage Calls v0.4.9

- api4/resolver_user.go
Upgrading the user resolver to dataloader
meant that multiple goroutines would access
the user struct.
Hence we move the user struct sanitization inside
the dataloader itself so prevent access outside
the dataloader.
https://mattermost.atlassian.net/browse/MM-44044
```release-note
NONE
```
> MM-44044: Fix racy TestGraphQLChannelMembers

- app/server.go
We should shutdown the products before shutting down the store.
https://mattermost.atlassian.net/browse/MM-43053
```release-note
NONE
```
> [MM-43053] app/server: shutdown products before closing the store

- app/channel.go
- app/expirynotify.go
- app/notification.go
- app/notification_push.go
Cherry pick of #20063 on release-6.7.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #20063

- app/cloud.go
Cherry pick of #20173 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20173

- Makefile
- app/plugin.go
- app/plugin_install.go
- app/plugin_test.go
- build/release.mk
- model/config.go
- model/config_test.go
- model/feature_flags.go
- model/utils.go
Cherry pick of #20161 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20161

- app/web_conn.go
We use the new API in Go 1.18 to set TCP_NO_DELAY for tls connections
as well.
Also took this chance to add the error handling while setting the read deadline.
https://mattermost.atlassian.net/browse/MM-43775
```release-note
NONE
```
> MM-43775: Use conn.NetConn() to get TCP conn from tls.Conn

- .gitlab-ci.yml
Cherry pick of #20186 on release-6.7.
/cc  @pfltdv
```release-note
NONE
```
> Automated cherry pick of #20186

- plugin/environment.go
The (*Environment).Activate method only guarded against multiple calls
and therefore wasn't properly re-entrant.
If a plugin calls an UpdateConfiguration in the OnActivate hook, it would
again call this method, resulting in 2 plugin processes getting created.
To prevent that from happening, we pre-emptively set the status to running
just after the supervisor is created.
I am not sure why starting the plugin normally from the server does not
cause this because the root cause is the same and there should be 2 plugin
processes created in the normal scenario as well. I have not spent time
looking into that. But let me know if you want me to.
Unit test: This might be a bit hard to test via a unit test. I think
an e2e test maybe written in the playbooks test itself which counts
the number of …
> MM-44045: Fix double plugin creation due to recursive plugin activation

- app/channel_test.go
https://mattermost.atlassian.net/browse/MM-44148
```release-note
NONE
```
> MM-44148: Skip racy TestIsCRTEnabledForUser

- model/feature_flags.go
Add Advanced Text Editor Feature Flag
Fixes https://mattermost.atlassian.net/browse/MM-44123
Epic: https://mattermost.atlassian.net/browse/MM-41347
```release-note
* Add Advanced Text Editor Feature Flag
```
> [MM-44123] Advanced Text Editor Feature Flag

- api4/emoji.go
- api4/resolver.go
- api4/resolver_sidebar_categories_test.go
- api4/resolver_team_member.go
- api4/resolver_team_member_test.go
- api4/schema.graphqls
- api4/team.go
- app/app_iface.go
- app/import_functions.go
- app/import_functions_test.go
- app/opentracing/opentracing_layer.go
- app/team.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/session_store.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/timerlayer/timerlayer.go
Also, add a negate parameter to the team members to get
all sidebarcategories except the default team.
```release-note
NONE
```
> MM-44101: GraphQL: Add sidebar categories at the top level

- api4/config.go
- api4/config_test.go
https://mattermost.atlassian.net/browse/MM-41659
```release-note
NONE
```
> MM-41569: Prevent compliance directory to be changed on cloud instances

- services/slackimport/slackimport.go
- utils/file.go
- utils/file_test.go
Cherry pick of #20144 on release-6.7.
```release-note
NONE
```
> Automated cherry pick of #20144

- api4/system.go
- api4/system_test.go
- app/app_iface.go
- app/channel.go
- app/expirynotify.go
- app/notification.go
- app/notification_push.go
- app/notification_push_test.go
- app/opentracing/opentracing_layer.go
- model/push_notification.go
- store/storetest/user_store.go
```release-note
Ping endpoint now can receive a device ID, which will report whether the device is able to receive push notifications.
```
> Cherrypick 32e3c2f and 50eaec6

- model/config.go
Cherry pick of #20217 on release-6.6.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20217

- api4/cloud.go
- api4/cloud_test.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
- model/client4.go
Cherry pick of #20163 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #20163

- app/post_test.go
- store/sqlstore/post_store.go
Sanitizes participant profiles when fetch posts with threads
```release-note
NONE
```
> MM-44568: sanitizes profiles in posts

- config/client.go
- model/config.go
- model/feature_flags.go
- services/telemetry/telemetry.go
Cherry pick of #20224 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #20224

- app/post_test.go
- store/sqlstore/post_store.go
Cherry pick of #20291 on release-7.0.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #20291

- api4/graphql.go
Adding subresource integrity to the graphqli html.
https://mattermost.atlassian.net/browse/MM-44410
```release-note
NONE
```
> MM-44410 Add subresource integrity

- db/migrations/mysql/000085_fileinfo_add_archived_column.down.sql
- db/migrations/mysql/000085_fileinfo_add_archived_column.up.sql
- db/migrations/postgres/000085_fileinfo_add_archived_column.down.sql
- db/migrations/postgres/000085_fileinfo_add_archived_column.up.sql
- model/file_info.go
- store/sqlstore/file_info_store.go
Cherry pick of #20164 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #20164

- app/notification_push_test.go
- model/config.go
Cherry pick of #20114 on release-7.0.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #20114

- api4/graphql.go
Cherry pick of #20257 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #20257

- .gitlab-ci.yml
Cut-release-branch pipeline introduced a bug for the pipelines. This will fix that case.
<!--
```release-note
NONE
```
> Fix release 7.0 pipeline

- app/post_test.go
- store/sqlstore/post_store.go
Cherry-pick of 3391adb67bc4ed7c5f7079038b91219b814753c0 to release-v6.3
> MM-44568: sanitizes profiles in posts (#20291)

- app/import_functions.go
- app/import_functions_test.go
- app/import_validators.go
- app/import_validators_test.go
- i18n/en.json
Cherry pick of #20292 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #20292

- i18n/en.json
Changed email button text from "View Message" to "Reply in Mattermost".
https://mattermost.atlassian.net/browse/MM-44130
```release-note
Changed the email notifications button text.
```
> MM-44130: Changed email button text.

- i18n/en.json
Cherry pick of #20288 on release-7.0.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #20288

- api4/team.go
- api4/team_test.go
- api4/usage.go
- api4/usage_test.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/usage.go
- i18n/en.json
- model/client4.go
- model/usage.go
Cherry pick of #20281 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20281

- api4/channel_test.go
- app/channel.go
- services/searchengine/bleveengine/search.go
- services/searchengine/interface.go
- services/searchengine/mocks/SearchEngineInterface.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/channel_layer.go
- store/searchtest/channel_layer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/timerlayer/timerlayer.go
Do not allow guest accounts discover public channels if they are not added to those channels in autocomplete.
https://mattermost.atlassian.net/browse/MM-44575
```release-note
NONE
```
> store: guests will only receive results of which channels they are in

- api4/cloud.go
- api4/cloud_test.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- model/client4.go
- model/cloud.go
- model/feature_flags.go
This is the server-side changes in charge of process the verification of the user and customer emails, making sure that those are valid business emails and if they are not, then request a valid business email.
https://mattermost.atlassian.net/browse/MM-43666
enterprise: https://github.com/mattermost/enterprise/pull/1215
mattermost-webapp: https://github.com/mattermost/mattermost-webapp/pull/10405
customer-web-server: https://github.com/mattermost/customer-web-server/pull/790
```release-note
NONE
```
> MM 43666 - request bussiness email

- app/email/email_test.go
- i18n/en.json
This PR replaces all 14-day reference with new freemium 30-day
https://mattermost.atlassian.net/browse/MM-44420
```release-note
NONE
```
> MM-44420 - replace 14-day references with new freemium  30-day

- Makefile
Cherry pick of #20276 on release-7.0.
/cc  @levb
```release-note
NONE
```
> Automated cherry pick of #20276

- app/channel.go
- app/channel_test.go
Cherry pick of #20263 on release-7.0.
```release-note
NONE
```
> Automated cherry pick of #20263

- Makefile
Cherry pick of #20371 on release-7.0.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #20371

- Makefile
Cherry pick of #20370 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20370

- model/config.go
Cherry pick of #20372 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20372

- model/feature_flags.go
Set Advanced Text Editor feature flag default value to True
Fixes https://mattermost.atlassian.net/browse/MM-44704
```release-note
Set Advanced Text Editor feature flag default value to True
```
> Set Advanced Text Editor feature flag default value to True

- model/feature_flags.go
Cherry pick of #20357 on cloud.
/cc  @AshishDhama
```release-note
NONE
```
> Automated cherry pick of #20357

- model/feature_flags.go
Cherry pick of #20357 on release-7.0.
/cc  @AshishDhama
```release-note
NONE
```
> Cherry pick of #20357 on release-7.0.

- api4/channel_test.go
- app/user.go
Cherry pick of #20181 on release-7.0.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #20181

- Makefile
Cherry pick of #20394 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #20394

- app/channel_test.go
- app/file.go
- app/post.go
- services/sharedchannel/permalink.go
- services/sharedchannel/permalink_test.go
- store/localcachelayer/main_test.go
- store/localcachelayer/post_layer.go
- store/localcachelayer/post_layer_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/post_layer.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Sanitize the user object as defined by the config.
[MM-44573](https://mattermost.atlassian.net/browse/MM-44573)
```release-note
NONE
```
> [MM-44573] Sanitize options

- app/channel_test.go
- app/file.go
- app/post.go
- services/sharedchannel/permalink.go
- services/sharedchannel/permalink_test.go
- store/localcachelayer/main_test.go
- store/localcachelayer/post_layer.go
- store/localcachelayer/post_layer_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/post_layer.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #20380 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20380

- app/authentication.go
- app/authentication_test.go
https://mattermost.atlassian.net/browse/MM-42714
```release-note
NONE
```
> MM-42714: Trim token sizes to 26 characters

- app/channel_test.go
- app/file.go
- app/post.go
- services/sharedchannel/permalink.go
- services/sharedchannel/permalink_test.go
- store/localcachelayer/main_test.go
- store/localcachelayer/post_layer.go
- store/localcachelayer/post_layer_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/post_layer.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #20380 on release-6.7
cc @amyblais
> Cherry pick of #20380 (release-6.7)

- api4/config_test.go
- app/integrations.go
- app/plugin_test.go
Cherry pick of #20387 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20387

- app/email/email.go
- app/email/email_test.go
- i18n/en.json
Cherry pick of #20425 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20425

- app/channel_test.go
- app/file.go
- app/post.go
- services/sharedchannel/permalink.go
- services/sharedchannel/permalink_test.go
- store/localcachelayer/main_test.go
- store/localcachelayer/post_layer.go
- store/localcachelayer/post_layer_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/post_layer.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #20380 on release-6.6
cc @amyblais
> Cherry pick of #20380 (release-6.6)

- app/channel_test.go
- app/file.go
- app/post.go
- services/sharedchannel/permalink.go
- services/sharedchannel/permalink_test.go
- store/localcachelayer/main_test.go
- store/localcachelayer/post_layer.go
- store/localcachelayer/post_layer_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/searchlayer/post_layer.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #20380 on release-6.5
cc @amyblais
> Cherry pick of #20380 (release-6.5) (#20434)

- build/Dockerfile
> Update latest version to 6.7.1

- build/Dockerfile
> Update latest version to 7.0.0

- store/sqlstore/file_info_store.go
- store/storetest/file_info_store.go
Cherry pick of #20454 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #20454

- app/cloud.go
- app/email/email.go
- i18n/en.json
Cherry pick of #20423 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20423

- app/post_metadata_test.go
- go.mod
- go.sum
- model/link_metadata.go
- model/link_metadata_test.go
- store/storetest/link_metadata_store.go
Cherry pick of #20506 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20506

- app/plugin_api_tests/test_set_profile_image_plugin/main.go
- app/plugin_install.go
- app/user.go
Cherry pick of #20518 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20518

- README.md
1. Add links to signup to Cloud or deploy on-premises
2. Add "learn more" resources for DevSecOps, Incident Resolution and IT Service Desk use cases. This is to gauge what use cases people visiting the open-source project may have when visiting our repo
```release-note
NONE
```
> Adjustments to README

- api4/cloud.go
- api4/cloud_test.go
- model/cloud.go
For non admin users, sanitize the information returned for cloud products. 
https://mattermost.atlassian.net/browse/MM-45315
```release-note
NONE
```
> Sanitize cloud products for non admin users

- i18n/en_AU.json
- i18n/fr.json
- i18n/hu.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/sv.json
- i18n/tr.json
- i18n/zh-CN.json
Manual cherry pick for cloud of weblate commits from #20554
```release-note
NONE
```
> cherry pick cloud weblate #20554

- app/user_test.go
Fix flaky TestCreateUserWithInitialPreferences test
[MM-45159](https://mattermost.atlassian.net/browse/MM-45159)
```release-note
NONE
```
> [MM-45159] - Flaky test: TestCreateUserWithInitialPreferences

- app/team.go
Cherry pick of #20410 on release-7.1.
/cc  @levb
```release-note
NONE
```
> Automated cherry pick of #20410

- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/post.go
- app/post_test.go
- jobs/base_workers.go
- jobs/last_accessible_post/worker.go
Cherry pick of #20598 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #20598

- api4/graphql.go
- web/context.go
- web/handlers.go
https://mattermost.atlassian.net/browse/MM-45536
```release-note
NONE
```
> MM-45536: Track GraphQL queries in Grafana

- Makefile
Cherry pick of #20593 on release-7.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #20593

- app/channel_test.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Filters posts `from_webhook` and `from_bot`.
* https://mattermost.atlassian.net/browse/MM-45395
* https://mattermost.atlassian.net/browse/MM-45308
```release-note
NONE
```
> MM-45395: Exclude bot and webhook posts from Top Team Channels. Exclude webhook posts from My Top Channels.

- api4/resolver_channel.go
- api4/resolver_channel_test.go
- api4/resolver_team.go
This PR contains a bunch of small optimizations, both performance- and code-wise, in the GraphQL resolvers. Nothing fancy, just a bunch of low hanging fruit.
```release-note
NONE
```
> General GraphQL resolver optimizations

- db/migrations/migrations.list
- db/migrations/mysql/000089_add-channelid-to-reaction.down.sql
- db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
- db/migrations/postgres/000089_add-channelid-to-reaction.down.sql
- db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
- model/reaction.go
- store/sqlstore/integrity_test.go
- store/sqlstore/reaction_store.go
- store/storetest/reaction_store.go
Cherry pick of #20572 on release-7.1.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #20572

- app/channel_test.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Cherry pick of #20599 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #20599

- i18n/de.json
- i18n/en_AU.json
- i18n/hu.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/tr.json
- i18n/zh-CN.json
> Fix weblate

- db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
- db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
Cherry pick of #20643 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #20643

- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
> Weblate 20220713

- app/busy_test.go
https://mattermost.atlassian.net/browse/MM-45725
```release-note
NONE
```
> MM-45725: Skip BusySet

- Makefile
> Enable GraphQL in dev environments

- build/Dockerfile
> Update latest version to 7.1.1

- app/platform/config.go
- app/platform/service.go
Adds service skeleton to unblock refactoring other services.
https://mattermost.atlassian.net/browse/MM-45835
```release-note
NONE
```
> app/platform: add initial platform service skeleton

- model/version.go
> Update version to 7.1.3

- build/Dockerfile
> Update latest version to 7.1.2

- app/plugin_api.go
- app/post.go
- model/post.go
- model/post_list.go
- model/post_search_results.go
- plugin/client_rpc.go
Fixed the race condition introduced in #20612
```release-note
NONE
```
> MM-45208: strip post meta for plugins

- app/plugin_api.go
- app/post.go
- model/post.go
- model/post_list.go
- model/post_search_results.go
- plugin/client_rpc.go
Cherry pick of #20686 on cloud.
/cc  @levb
```release-note
NONE
```
> Automated cherry pick of #20686

- services/sharedchannel/sync_send_remote.go
Cherry pick of #20414 on cloud.
/cc  @iomodo
```release-note
NONE
```
> Automated cherry pick of #20414

- app/plugin_test.go
- model/plugin_status.go
- plugin/environment.go
Cherry pick of #20430 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20430

- api4/upload_test.go
- app/upload.go
- model/file_info.go
Cherry pick of #20681 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20681

- model/feature_flags.go
Cherry pick of #20166 on cloud.
/cc  @michelengelen
```release-note
NONE
```
> Automated cherry pick of #20166

- app/post_metadata_test.go
- go.mod
- go.sum
- model/link_metadata.go
- model/link_metadata_test.go
- store/storetest/link_metadata_store.go
https://mattermost.atlassian.net/browse/MM-45000
```release-note
NONE
```
> MM-45000: Upgrade to new opengraph module path

- api4/apitestlib.go
- app/config.go
- app/platform/config.go
- app/platform/metrics.go
- app/platform/service.go
- app/server.go
Move metrics 
https://mattermost.atlassian.net/browse/MM-45863
```release-note
NONE
```
> move metrics server into platform service

- model/feature_flags.go
Cherry pick of #20676 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #20676

- api4/resolver_team_member_test.go
> Fix bad merge due to https://github.com/mattermost/mattermost-server/pull/20674

- i18n/en.json
- Changing reminder text as suggested in https://github.com/mattermost/mattermost-webapp/pull/10688#pullrequestreview-1033583383, 
- N/A
```release-note
NONE
```
> Update post reminder text

- api4/bot.go
- app/app_iface.go
- app/bot.go
- app/import_functions.go
- app/opentracing/opentracing_layer.go
- app/post.go
- app/user.go
https://mattermost.atlassian.net/browse/MM-45195
```release-note
NONE
```
> MM-45195: Use api4/bot and app/bot to use logger context

- app/app_iface.go
- app/file.go
- app/file_bench_test.go
- app/opentracing/opentracing_layer.go
- app/plugin_hooks_test.go
- i18n/en.json
- shared/filestore/s3store.go
Cherry pick of #20740 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20740

- config/store.go
Cherry pick of #20694 on release-7.1.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20694

- api4/user.go
Cherry pick of #20662 on release-7.2.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #20662

- model/feature_flags.go
Fixes the splitio feature flag treatment
https://mattermost.atlassian.net/browse/MM-45666
```release-note
NONE
```
> Fix feature flag treatment

- model/feature_flags.go
Cherry pick of #20753 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #20753

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherry pick of #20615 on release-7.2.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #20615

- store/storetest/post_store.go
https://mattermost.atlassian.net/browse/MM-46134
```release-note
NONE
```
> MM-46134: Skip flaky test PostStore//GetForThread

- i18n/de.json
- i18n/en_AU.json
- i18n/fr.json
- i18n/hu.json
- i18n/ja.json
- i18n/ko.json
- i18n/pl.json
- i18n/tr.json
Cherry-picking translations from Weblate (July 25th)
origin: https://github.com/mattermost/mattermost-server/pull/20705/
```release-note
None
```
> Cherry-picking translations from Weblate

- model/feature_flags.go
Change post forwarding feature flag default value to true
Fixes https://mattermost.atlassian.net/browse/MM-45935
```release-note
* change post forwarding feature flag default value to true
```
> Change post forwarding feature flag default value to true

- store/sqlstore/reaction_store.go
Avoids join on Posts table to get ChannelId of a Reaction
https://mattermost.atlassian.net/browse/MM-45561
```release-note
NONE
```
> [MM-45561] Improve user top reactions query

- store/sqlstore/reaction_store.go
Cherry-picking https://github.com/mattermost/mattermost-server/pull/20761 changes
https://mattermost.atlassian.net/browse/MM-45561
```release-note
NONE
```
> MM-45561: manual cherrypick

- api4/post.go
- api4/post_test.go
- i18n/en.json
Cherry pick of #20811 on cloud.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #20811

- Makefile
Cherry pick of #20809 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #20809

- app/app_iface.go
- app/file.go
- app/import.go
- app/import_functions.go
- app/opentracing/opentracing_layer.go
- app/team.go
- i18n/en.json
We just log a warning instead of failing completely.
https://mattermost.atlassian.net/browse/MM-38702
```release-note
NONE
```
> MM-38702: Do not fail during importing without attachment

- app/channels.go
This PR adds a missing entry to the services map provided by channels product.
NONE
```release-note
NONE
```
> Add userService to the services provided by channels product

- app/enterprise.go
- app/platform/cluster.go
- app/platform/config_test.go
Cherry pick of #20839 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20839

- api4/user_test.go
https://mattermost.atlassian.net/browse/MM-46450
```release-note
NONE
```
> MM-46450: Skip flaky TestSearchUsers

- app/server.go
- app/server_test.go
Cherry pick of #20827 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20827

- store/sqlstore/store.go
> Warn on MariaDB servers

- services/upgrader/upgrader_linux.go
This PR removes the download limit for enterprise upgrades. Previous upgrades would fail because the downloaded file was silently truncated to 300 MiB and the signature verification failed. The PR also adds error reporting for failed downloads.
[MM-46455](https://mattermost.atlassian.net/browse/MM-46455)
```release-note
NONE
```
> MM-46455 Remove download limit

- Makefile
- api4/handlers.go
- api4/user.go
- app/admin.go
- app/admin_test.go
- app/channel.go
- app/group.go
- app/group_test.go
- app/post.go
- app/reaction.go
- app/team.go
- app/user.go
- app/user_test.go
- i18n/en.json
- model/github_release.go
- model/utils.go
We replace the empty translation key with <untranslated>
which is ignored by the translation check tool.
https://mattermost.atlassian.net/browse/MM-46577
https://mattermost.atlassian.net/browse/MM-40109
```release-note
NONE
```
> MM-46577: Remove empty translation strings

- .circleci/config.yml
Cherry pick of #20889 on cloud.
/cc  @phoinixgrr
```release-note
NONE
```
> Automated cherry pick of #20889

- Makefile
Cherry pick of #20877 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #20877

- build/Dockerfile
Cherry pick of #20901 on cloud.
/cc  @pfltdv
```release-note
NONE
```
> Chore/cherry pick of mattermost server #20901 upstream cloud

- store/sqlstore/channel_store.go
Address the FileInfo count query by implementing the query discussed in the Jira ticket. 
- Upload a few files to a channel
- Open the Channel Info RHS
- The count on the "Files" submenu should work as before.
https://mattermost.atlassian.net/browse/MM-46097
```release-note
NONE
```
> [MM-46097] Change FileInfo count query

- i18n/hu.json
- i18n/sv.json
> Weblate fix

- app/slashcommands/command_marketplace.go
- app/slashcommands/command_marketplace_test.go
Cherry pick of #20919 on release-7.3.
```release-note
NONE
```
> Automated cherry pick of #20919

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Fix counting of total messages in a TopDM entry: use `count(posts.Id)` instead of `channels.TotalMsgCount`
https://mattermost.atlassian.net/browse/MM-46516
```release-note
NONE
```
> [MM-46516] P1 - Fix total message counting for top DM

- api4/post_test.go
https://mattermost.atlassian.net/browse/MM-46902
```release-note
NONE
```
> MM-46902: Skip TestFileinfosForPost

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherry pick of #20858 on release-7.3.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #20858

- api4/insights_test.go
https://mattermost.atlassian.net/browse/MM-46911
```release-note
NONE
```
> MM-46911: Skip flaky TestGetTopDMsForUserSince

- api4/insights_test.go
- store/sqlstore/post_store.go
Cherry pick of #20896 on release-7.3.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #20896

- store/sqlstore/post_store.go
Cherry pick of #20762 on cloud.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #20762

- go.mod
- go.sum
Cherry pick of #20960 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20960

- jobs/import_process/worker.go
Cherry pick of #20978 on cloud-2022-09-15-backup.
/cc  @noxer
```release-note
NONE
```
> Automated cherry pick of #20978

- store/sqlstore/user_store.go
- store/storetest/user_store.go
Cherry pick of #20963 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20963

- api4/insights_test.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherry pick of #20965 on release-7.3.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #20965

- store/sqlstore/user_store.go
- store/storetest/user_store.go
Reverts mattermost/mattermost-server#20984
> Revert "Automated cherry pick of #20963"

- api4/insights_test.go
- app/channel_test.go
- app/helper_test.go
- model/channel.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Cherry pick of #20905 on cloud-2022-09-15-backup.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #20905

- i18n/en.json
Add translations for https://github.com/mattermost/enterprise/pull/1266
https://mattermost.atlassian.net/browse/MM-31745
```release-note
NONE
```
> [MM-31745] Add translations for enterprise PR#1266

- build/Dockerfile
Cherry pick of #20998 on cloud.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #20998

- i18n/nl.json
fix weblate block
```release-note
NONE
```
> Weblate 220913

- app/file.go
- app/server.go
Use a buffered channel to do the extraction
JIRA - https://mattermost.atlassian.net/browse/MM-41962
```release-note
NONE
```
> [MM-41962] File extraction happens in an unbounded manner

- app/web_conn.go
- app/web_hub.go
- app/web_hub_test.go
Cherry pick of #20996 on release-7.1.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #20996

- i18n/en.json
- jobs/base_workers.go
- jobs/jobs.go
- jobs/jobs_test.go
The import reports all errors as `We could not count the users.` and since the last error improvements it doesn't report the original error anymore.
[MM-46990](https://mattermost.atlassian.net/browse/MM-46990)
```release-note
NONE
```
> MM-46990 Report correct import error

- model/post_list.go
- model/wrangler.go
Wrangler contribute project: Start wrangler model
```release-note
NONE
```
> Contribute: Wrangler model

- i18n/en.json
- model/config.go
- services/telemetry/telemetry.go
Adds Wrangler config
```release-note
None
```
> Add wrangler config

- app/eventbus.go
- shared/eventbus/eventbus.go
Adds event bus interfaces
```release-note
```
> Event bus interfaces

- app/eventbus.go
- go.mod
- go.sum
- shared/eventbus/eventbus.go
This PR adds event bus pub sub as well as eventTypes methods
```release-note
```
> Add event bus pub sub

- app/plugin_api.go
- plugin/api.go
- plugin/api_timer_layer_generated.go
- plugin/client_rpc_generated.go
- plugin/eventbus_helper/plugin_helper.go
- plugin/hooks.go
- plugin/hooks_timer_layer_generated.go
- plugin/plugintest/api.go
- plugin/plugintest/hooks.go
- plugin/product_hooks_generated.go
Plugin API and helper functions for the event bus
```release-note
NONE
```
> Plugin API for Event Bus

- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
For least active channels, Use `Channels.Id` to join on ChannelMembers instead of `Posts.ChannelId` since the second column would be null due to lack of posts in a new channel.
https://mattermost.atlassian.net/browse/MM-47002
```release-note
Bugfix: Fixed an insights bug where channels with no posts in a particular time window doesn't show up in Least Active Channel insights.
```
> [MM-47002] Fix new private channels not showing up in least active channels insights

- api4/post.go
- api4/post_test.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/post.go
- model/post.go
- model/user.go
> Wrangler logic

- api4/group_test.go
- i18n/en.json
- model/group.go
Prevent making user groups with reserved names in the API.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-42400)
```release-note
NONE
```
> [MM-42400] Prevent making groups with reserved names

- web/web.go
Assigned content type application/json for NotFound (404), to stay true to the document.
Fixes https://github.com/mattermost/mattermost-server/issues/20878
JIRA: https://mattermost.atlassian.net/browse/MM-46605
```release-note
NONE
```
> Update Header with application/json

- templates/cloud_14_day_arrears.html
- templates/cloud_30_day_arrears.html
- templates/cloud_30_day_arrears.mjml
- templates/cloud_45_day_arrears.html
- templates/cloud_7_day_arrears.html
- templates/cloud_90_day_arrears.html
- templates/cloud_upgrade_confirmation.html
- templates/inactivity_body.html
- templates/invite_body.html
- templates/license_up_for_renewal.html
- templates/messages_notification.html
- templates/partials/style.css
- templates/payment_failed_body.html
- templates/reset_body.html
- templates/verify_body.html
- templates/welcome_body.html
Fix delinquency email formatting in gmail.
before:
after: 
```release-note
None
```
> Fix delinquency emails

- shared/eventbus/eventbus.go
- shared/eventbus/eventbus_test.go
This PR adds Eventbus tests.
No ticket
```release-note
```
> Eventbus tests

- Makefile
Cherry pick of #21206 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21206

- model/utils.go
- store/sqlstore/user_store.go
- store/storetest/user_store.go
Cherry pick of #20900 on cloud.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #20900

- app/platform/config.go
- app/platform/service.go
- app/server.go
Cherry pick of #21281 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21281

- api4/team.go
- api4/team_test.go
- api4/user.go
- api4/user_test.go
- i18n/en.json
- model/license.go
Cherry pick of #21195 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #21195

- Makefile
Cherry pick of #21288 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21288

- api4/post.go
- app/post.go
- app/post_test.go
- config/client.go
- einterfaces/metrics.go
- einterfaces/mocks/MetricsInterface.go
- i18n/en.json
- model/config.go
- model/feature_flags.go
- model/file_info.go
- model/file_info_test.go
- model/post.go
- services/telemetry/telemetry.go
This PR adds the following elements:
- support for voice post type
- validation rules for this new post type
- configuration, including an experimental setting and a feature flag
- adds enterprise metrics support
- Webapp https://github.com/mattermost/mattermost-webapp/pull/11170
- Enterprise https://github.com/mattermost/enterprise/pull/1275
N/A
```release-note
NONE
```
> Contribute Voice Message: Add initial config for voice messages

- Makefile
Cherry pick of #21382 on release-7.4.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21382

- config/client.go
> Typo ExperimentalEnableVoiceMessage -> ExperimentalEnableVoiceMessages

- app/app_iface.go
- app/channel.go
- app/opentracing/opentracing_layer.go
- app/user.go
- app/user_test.go
- model/feature_flags.go
- model/post.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
- store/timerlayer/timerlayer.go
Cherry pick of #20926 on cloud.
```release-note
NONE
```
> Automated cherry pick of #20926

- app/email/email.go
- i18n/en.json
- templates/email_change_verify_body.html
This PR updates the email UI which is being sent when the user updates his email address and needs to verify his email.
https://mattermost.atlassian.net/browse/MM-44790
|----|----|
|  ![Screenshot 2022-09-19 at 21 30 04](https://user-images.githubusercontent.com/841955/191089666-527f19aa-75a5-4500-9136-6b95477737cd.png) | ![Screenshot 2022-10-13 at 16 51 30](https://user-images.githubusercontent.com/841955/195616245-176d5650-edb3-4423-a573-8c85f008ef02.png) |
```release-note
NONE
```
> new ui for email verification due to change in the email address

- api4/channel_test.go
https://mattermost.atlassian.net/browse/MM-47465
```release-note
NONE
```
> MM-47465: Skip flaky TestDeleteChannel

- app/plugin_api_test.go
https://mattermost.atlassian.net/browse/MM-47612
```release-note
NONE
```
> MM-47612: Skip flaky test TestPluginAPIDeleteUserPreferences

- model/cloud.go
Allow the new property to record the feedback from the modal of Wire Transfer Survey. 
https://mattermost.atlassian.net/browse/MM-46549
```release-note
NONE
```
> Mm 46549 gather intent cloud monthly subscription

- app/permissions_migrations.go
- model/config.go
- model/migration.go
- model/permission.go
- model/role.go
- services/telemetry/telemetry.go
- testlib/store.go
We add a new section in system console
for products.
```release-note
Added a new section in system console
for products. For now, it only contains
boards specific settings.
```
> MM-47250: Add new system console section

- api4/group.go
- api4/group_local.go
- api4/handlers.go
- api4/insights.go
https://github.com/mattermost/mattermost-server/blob/a6a44b5824e7bcf0249836b3a0b6d1d423ab24f4/web/handlers.go#L33-L40 this links API stats for insights in grafana to `func1`.
A temporary fix is to move the permission checks to inside handler functions, until a clean solution comes up to tag an API endpoint with the handler name.
https://mattermost.atlassian.net/browse/MM-47538
```release-note
NONE
```
> [MM-47538] Pass handler functions directly while creating API endpoints

- api4/cloud.go
- api4/cloud_test.go
- model/client4.go
Replace 500 errors with more meaningful codes. What seemed to be the root cause of the errors that led to the creation of the ticket was fixed by https://github.com/mattermost/customer-web-server/pull/899 , however this PR replaces these generic 500 errors with more meaningful error codes.
https://mattermost.atlassian.net/browse/MM-46873
```release-note
NONE
```
> Replace 500 errors with more meaningful error codes

- api4/cloud.go
- api4/cloud_test.go
- model/client4.go
Cherry pick of #21439 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #21439

- i18n/de.json
- i18n/es.json
- i18n/nl.json
Fixes diverging history weblate and mattermost repositories (alert Oct 19 https://community.mattermost.com/core/channels/localization )
```release-note
NONE
```
> Fix translations

- app/notification_push_test.go
- app/options.go
- app/platform/options.go
- app/platform/service.go
- app/server.go
- app/server_test.go
Move file backend into platform service
https://mattermost.atlassian.net/browse/MM-45840
```release-note
NONE
```
> move file backend to the platform service

- Makefile
Update prepackaged boards version to v7.4.3
```release-note
Update prepackaged boards version to v7.4.3
```
> Update prepackage boards to v7.4.3

- i18n/de.json
- i18n/es.json
- i18n/hu.json
- i18n/nl.json
Cherry-picking translations from master to cloud https://github.com/mattermost/mattermost-server/pull/21452
```release-note
NONE
```
> Cherry-picking translations into cloud

- Makefile
Cherry pick of #21481 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21481

- api4/team_local.go
- app/app_iface.go
- app/email/email.go
- app/email/email_test.go
- app/email/mocks/ServiceInterface.go
- app/email/service.go
- app/email/utils.go
- app/opentracing/opentracing_layer.go
- app/team.go
- app/team_test.go
- app/user.go
We want to track the number of invited users by admins and by end users, as well as the success rate of invitations for each.
https://mattermost.atlassian.net/browse/MM-46528
```release-note
NONE
```
> MM-46528_Verify Invitation Flow Tracking Telemetry

- app/opentracing/opentracing_layer.go
- app/user.go
Fix [build](https://email.circleci.com/c/eJxVUMtqhTAQ_Zq4ixijJlm46IMLLZRyd92VmIyaNg-JUbl_31wslA7DwDlzOPOAnnQ5Gla1otA97wQvTA_7sD6-v7jXp7eP65XeBhqCOMpT2glGOOOoqZawJmlLZaKygC1MUt2wD8mMBiLeCe50lqth1AzvtuV7Mfda0la0lWhqBowIkQ2pbAgnolVMClrYfk5pWRF9QPUl5-muTKmCy3Cac3EyJYguj_8H8Apxh5g5SimpBaKXLblPJd0izeQRfT5C_B5tOPAojQWN6u4ucKDN5nIbXKZ_yTVsUUEmz4OUTCb4IvZfmzXSly54HeUUfP7D3wb3JX8AbS1vEA) after merging https://github.com/mattermost/mattermost-server/pull/21227
Needed to rebase with changes implemented previously in https://github.com/mattermost/mattermost-server/pull/20899
```release-note
NONE
```
> MM-46528_Verify Invitation Flow Tracking Telemetry - Fix build

- api4/apitestlib.go
- api4/websocket.go
- api4/websocket_test.go
https://mattermost.atlassian.net/browse/MM-46874
```release-note
NONE
```
> MM-46874: Change to 400 for failed to upgrade ws

- app/permissions.go
- product/api.go
Cherry pick of #21433 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21433

- model/job.go
- model/job_test.go
`model/job.go` was untested, Also `job.IsValid` didn't accept warnings as a valid status.
> Fixed job.IsValid and added tests

- .circleci/config.yml
- app/platform/service_test.go
- build/release.mk
Cherry-pick of #11461
https://mattermost.atlassian.net/browse/MM-46275
https://mattermost.atlassian.net/browse/MM-46979
https://github.com/mattermost/enterprise/pull/1285
https://github.com/mattermost/mattermost-webapp/pull/11462
```release-note
NONE
```
> MM-46275/MM-46979 Production MPA for web app (#21401)

- .circleci/config.yml
Cherry pick of #21513 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #21513

- api4/insights.go
- api4/insights_test.go
- app/channel_test.go
- app/reaction_test.go
- i18n/en.json
- model/insights.go
Cherry pick of #21048 on release-7.5.
/cc  @cyrilzhang-mm
```release-note
NONE
```
> Automated cherry pick of #21048

- model/feature_flags.go
Cherry pick of #21508 on release-7.5.
/cc  @ConorMacpherson
```release-note
NONE
```
> Automated cherry pick of #21508

- .circleci/config.yml
Cherry-pick of #21513
#21513
https://github.com/mattermost/enterprise/pull/1287
```release-note
NONE
```
> Actually build Boards product files in release builds (#21513)

- model/feature_flags.go
This PR adds a feature flag for reduce onboarding task list item.
https://mattermost.atlassian.net/browse/MM-47931
```release-note
NONE
```
> [MM-47931] feature flag for reduced onboarding task list item

- store/sqlstore/post_store.go
Cherry pick of #20976 on release-7.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #20976

- api4/emoji.go
- api4/post.go
- app/app_iface.go
- app/emoji.go
- app/export.go
- app/export_test.go
- app/opentracing/opentracing_layer.go
- app/plugin_api.go
- app/post.go
- app/post_metadata.go
- app/post_metadata_test.go
Small part of the effort to introduce the context logger for the whole app. This PR just adds the context to `app/emoji.go`.
[MM-48060](https://mattermost.atlassian.net/browse/MM-48060)
```release-note
NONE
```
> [MM-48060] Added context for emoji

- app/plugin_api.go
- app/plugin_api_tests/test_bots_plugin/main.go
Cherry pick of #21560 on release-7.5.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #21560

- model/feature_flags.go
Adds a feature flag for the work template feature. While we are working on the feature, I'll be enabled only using the feature flag.
No QA necessary as this is a technical only ticket
https://mattermost.atlassian.net/browse/MM-47843
```release-note
NONE
```
> [MM-47843] Feature Flag for Work Template Modal

- api4/user_test.go
- store/sqlstore/user_store.go
- store/storetest/group_store.go
Cherry pick of #21559 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21559

- api4/post_test.go
Adds hosting and running a plugin support in createPost context.
Adds tests with plugin running
```release-note
NONE
```
> Add 'create post against topic' tests

- Makefile
Cherry pick of #21623 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21623

- i18n/de.json
- i18n/en_AU.json
- i18n/es.json
- i18n/nl.json
- i18n/pl.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
- i18n/zh-CN.json
Cherry-picking translations from https://github.com/mattermost/mattermost-server/pull/21625
```release-note
NONE
```
> Cherry-picking translations

- model/feature_flags.go
https://mattermost.atlassian.net/browse/MM-47866
https://github.com/mattermost/mattermost-webapp/pull/11552
```release-note
NONE
```
> MM-47866 - remove deprecated inviteToTeam FF

- app/channels.go
- app/collection.go
- app/plugin.go
PR changes data types to `collectionTypes` and `topicTypes` maps to map[string]string like
collectionType -> pluginId
topicType -> collectionType
This makes them automatically unique and easier to access later.
Fixes https://mattermost.atlassian.net/browse/MM-48161
```release-note
NONE
```
> [MM-48161] Change data types for collections and topics

- app/post.go
- model/permission.go
Adds PermissionReadTopic to the ChannelScopedPermissions
Not adding permission to default roles. Permission is granted by the plugin using the `PluginGivesUserPermissionToCollection` hook
Fixes https://mattermost.atlassian.net/browse/MM-48160
```release-note
NONE
```
> [MM-48160] Add read topic permission

- Makefile
This PR updates the prepackaged version of Boards to v7.5.1
```release-note
NONE
```
> Prepackage boards v7.5.1

- Makefile
Cherry pick of #21681 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21681

- i18n/en.json
MacOS 10.14 has been unsupported for some time now.
Also updated Edge version to v106+ because our Chrome minimum version is now v106+ (our Desktop app v5.2 comes with an Electron version that supports Chrome v106+. Chrome and Edge are using the same code base and they normally need to be on the same version.
```release-note
Updated MacOS supported version to 11+ and Edge supported version to v106+.
```
> Update minimum supported MacOS and Edge versions

- api4/cloud.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
- model/client4.go
> Add Health Check to CWS

- api4/cloud.go
- api4/license.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
See: https://github.com/mattermost/enterprise/pull/1290
https://mattermost.atlassian.net/browse/MM-48563
```release-note
Changing the license in a cloud environment will now force an update of the subscription and kick the cache for all cluster members
```
> Call Cloud HandleLicenseChange when license is changed in Cloud

- Makefile
Prepackage Boards `v7.5.2` to be included in the event of a dot release
```release-note
NONE
```
> Prepackage Boards v7.5.2

- Makefile
Cherry pick of #21713 on release-7.5.
```release-note
NONE
```
> Automated cherry pick of #21713

- store/storetest/file_info_store.go
Cherry pick of #21731 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21731

- app/cluster_handlers.go
- plugin/environment.go
Cherry pick of #21737 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21737

- model/feature_flags.go
Cherry pick of #21721 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #21721

- app/cluster_handlers.go
- plugin/environment.go
Reverts mattermost/mattermost-server#21743
> Revert "Automated cherry pick of #21737"

- app/team.go
- app/team_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #21735 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #21735

- api4/scheme.go
- api4/scheme_test.go
Cherry pick of #21660 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #21660

- api4/group.go
- config/client_test.go
- model/feature_flags.go
Cherry pick of #21739 on cloud.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #21739

- app/email/email.go
- i18n/en.json
- templates/cloud_30_day_arrears.html
- templates/cloud_30_day_arrears.mjml
- templates/cloud_45_day_arrears.html
- templates/cloud_90_day_arrears.html
- templates/partials/cloud_title_3subtitles_button.mjml
The following changes have been made to the Delinquency Emails: 
- Day 7 Email: Added the plan name, so that the subject to longer shows "Payment failed for Mattermost \<no value\>"
- Day 30 Email: Fixed spacing between the "Update Pyament" button and the image
- Day 45 Email: “Outstanding invoices dates _______” → “Outstanding invoices since _______”. 
- Added/ Removed punctuation and capitalized letters in various emails . 
- Fixed spacing between the “Downgrade to Cloud Starter” CTA and the image. 
https://mattermost.atlassian.net/browse/MM-48097
```release-note
NONE
```
> [MM-48097]: Delinquency Email Spacing/Wording Changes

- NOTICE.txt
Cherry pick of #21751 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21751

- i18n/bg.json
- i18n/fa.json
- i18n/fr.json
- i18n/hu.json
- i18n/it.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/uk.json
Cherry-picking translations from master to cloud
https://github.com/mattermost/mattermost-server/pull/21698 and 
https://github.com/mattermost/mattermost-server/pull/21750
```
NONE
```
> cherry-picking translations from master to cloud pr 21698 and 21750

- api4/insights.go
https://github.com/mattermost/mattermost-server/pull/20796#discussion_r942013427
This PR refactors insights endpoints' response writers .
https://mattermost.atlassian.net/browse/MM-46331
```release-note
NONE
```
> [MM-46331] Change insights response writers as per convention

- app/email/email_batching.go
- app/email/notification_email.go
- app/email/notification_email_test.go
- app/notification_email.go
Cherry pick of #21736 on release-7.6.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #21736

- .circleci/config.yml
We are not shipping boards with release 7.3 hence no need to include it into the build
https://mattermost.atlassian.net/browse/MM-48430
```release-note
NONE
```
> exlude boards build from release 7.3

- .circleci/config.yml
- build/docker/mysql.conf.d/custom.cnf
- build/docker/postgres.conf
- templates/cloud_30_day_arrears.html
Revert commit https://github.com/mattermost/mattermost-server/commit/57afc97f2495e41dee1936288eac31f77aa312fd
Revert commit https://github.com/mattermost/mattermost-server/commit/1ef24221e3b2cfb0172e4843d007dc2bfb431543
Reverts the optimization PR as well, there were many conflicts so had to revert that as well. And also had to run `make build-templates`.
```release-note
NONE
```
> Revert "[feat] CI essential multi-product architecture changes #20783)" 

- .circleci/config.yml
- app/platform/service.go
- app/platform/service_test.go
- build/docker/mysql.conf.d/custom.cnf
- build/docker/postgres.conf
- build/release.mk
Revert MPA circle CI build PRs for the release branch
```release-note
NONE
```
> Revert MPA circle CI build PRs for the release-7.5 branch

- app/plugin.go
- app/plugin_api_test.go
- app/plugin_hooks_test.go
- model/config.go
- plugin/environment.go
- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
- web/web_test.go
Cherry pick of #21171 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21171

- model/feature_flags.go
Cherry pick of #21720 on release-7.6.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #21720

- api4/drafts.go
- app/draft.go
Cherry pick of #21818 on release-7.6.
/cc  @mylonsuren
```release-note
NONE
```
> Automated cherry pick of #21818

- app/server.go
- model/config.go
- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
Cherry pick of #21821 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #21821

- model/insights.go
Cherry pick of #21703 on cloud.
/cc  @cyrilzhang-mm
```release-note
NONE
```
> Automated cherry pick of #21703

- app/user.go
Cherry pick of #21836 on cloud.
/cc  @emmyni
```release-note
NONE
```
> Automated cherry pick of #21836

- app/platform/config.go
- app/platform/config_test.go
- app/platform/service.go
- app/platform/service_test.go
Cherry pick of #21831 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21831

- web/static.go
- web/web_test.go
Cherry pick of #21817 on release-7.6.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #21817

- templates/cloud_45_day_arrears.html
- templates/cloud_90_day_arrears.html
- templates/partials/cloud_title_3subtitles_button.mjml
Update the redirect url for the "Downgrade to cloud free" and "View Plans & Pricing" CTA button to point to the pricing modal (?action=show_pricing_modal) instead of the purchase modal (?action=show_delinquency_modal) for the delinquency emails. 
https://mattermost.atlassian.net/browse/MM-48098
```release-note
NONE
```
> [MM-48098]: "Downgrade to Starter" CTA's go to purchase modal instead of pricing modal

- api4/cloud.go
- api4/cloud_test.go
- app/user_test.go
- model/cloud.go
Remove all references to IsPaidTier / is_paid_tier.
Related PRs: 
https://github.com/mattermost/customer-web-server/pull/1024
https://github.com/mattermost/enterprise/pull/1326
There weren't any references in mm-webapp. 
https://mattermost.atlassian.net/browse/MM-48091
```release-note
NONE
```
> [MM-48091]: Remove is_paid_tier

- Makefile
Cherry pick of #21879 on release-7.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21879

- app/app_iface.go
- app/file.go
- app/opentracing/opentracing_layer.go
- jobs/export_process/worker.go
- shared/filestore/filesstore_test.go
- shared/filestore/s3store.go
Cherry pick of #21774 on cloud.
/cc  @noxer
```release-note
NONE
```
> Automated cherry pick of #21774

- api4/post.go
- model/post.go
Cherry pick of #21898 on cloud.
/cc  @DSchalla
```release-note
NONE
```
> Automated cherry pick of #21898

- jobs/export_process/worker.go
Cherry pick of #21854 on cloud.
/cc  @noxer
```release-note
NONE
```
> Automated cherry pick of #21854

- store/sqlstore/channel_store.go
Cherry pick of #21911 on release-7.7.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #21911

- config/client.go
Cherry pick of #21940 on cloud.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #21940

- app/user.go
Add comments for the subscriptionHistoryEvent call
From a comment here: https://github.com/mattermost/mattermost-server/pull/21836#pullrequestreview-1222654882
```release-note
NONE
```
> Add comments for the subscriptionHistoryEvent call

- store/sqlstore/store.go
Make `SetupConnection` public to 
https://mattermost.atlassian.net/browse/MM-49352
```release-note
NONE
```
> sqlstore/store: make SetupConnection public to be used by products

- app/export.go
- jobs/export_process/worker.go
This change includes the following:
- Adds the job ID as a log field for bulk exports
- Adds checkpoint logging for posts and direct posts so that progress can be tracked.
Fixes https://mattermost.atlassian.net/browse/MM-49341
```release-note
Improve bulk export logging
```
> Improve bulk export logging

- app/plugin_install.go
- plugin/environment.go
On plugin install/activation, adds logs with plugin id and version numbers
Sample output logs from tests:
```
...
{"timestamp":"2022-12-18 22:36:08.727 -05:00","level":"debug","msg":"Installing plugin","caller":"app/plugin_install.go:405","plugin_id":"testplugin","version":"0.0.1"}
{"timestamp":"2022-12-18 22:36:08.727 -05:00","level":"debug","msg":"Installing plugin","caller":"app/plugin_install.go:405","plugin_id":"testplugin2","version":"1.2.3"}
{"timestamp":"2022-12-18 22:36:08.741 -05:00","level":"debug","msg":"Starting plugin","caller":"plugin/environment.go:333","plugin_id":"testplugin","version":"0.0.1"}
{"timestamp":"2022-12-18 22:36:08.751 -05:00","level":"debug","msg":"Starting plugin","caller":"plugin/environment.go:333","plugin_id":"testplugin2","version":"1.2.3"}
...
```
- …
> MM-48988 Log plugins version on install and on startup

- api4/user.go
Track event when sign up from CWS with a UTM_CAMPAIGN
https://mattermost.atlassian.net/browse/MM-48759
```release-note
NONE
```
> [MM-48759] track event when redirect from cws signup with utm campaign

- .circleci/config.yml
https://mattermost.atlassian.net/browse/MM-45967
```release-note
NONE
```
[MM-45967]: https://mattermost.atlassian.net/browse/MM-45967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-45967: Print diff output in go mod tidy

- i18n/en.json
Cherry pick of #21969 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #21969

- .circleci/config.yml
Manual cherry pick of #21990 
```release-note
NONE
```
> cicleci: add ability use target branch for pulling focalboard (#21990)

- i18n/en.json
Manual Cherry pick of #21969 on release-7.7.
/cc  @amyblais 
```release-note
NONE
```
> Manual cherry pick of #21969

- store/sqlstore/store.go
Cherry-pick for #21896
```release-note
NONE
```
> Manual cherry pick of #21896

- Makefile
Cherry pick of #21980 on release-7.7.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #21980

- Makefile
Cherry pick of #22013 on cloud.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #22013

- config/client.go
Cherry pick of #22046 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #22046

- store/sqlstore/store_test.go
See related ticket for more information: https://mattermost.atlassian.net/browse/MM-49604. If I'm not mistaken, this is something our team needs to fix.
--
```release-note
NONE
```
> Skip TestReplicaLagQuery until MM-49604 is fixed

- web/handlers.go
https://mattermost.atlassian.net/browse/MM-49154
```release-note
NONE
```
> MM-49154: Do not translate server side logs

- app/plugin.go
Manual cherry pick of 0e6dc93
```release-note
NONE
```
> MM-49658: Correctly disable plugin in product mode (#22071)

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit d27d7bc8f75326b690e63530ab783fea78224ee5.
> Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)"

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit d27d7bc8f75326b690e63530ab783fea78224ee5.
> Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)" (#22075)

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit 5ae6d6e1082f535d819b7ed584260830ea990497.
```release-note
NONE
```
> Revert "Revert "MM-49485: Set BoardsProduct FF to on by default (#22006)" (#22075)"

- app/preference.go
- model/config.go
- services/telemetry/telemetry.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
- store/timerlayer/timerlayer.go
This pull request will revert the code change that [caused an incident](https://community.mattermost.com/core/pl/excrysyp8pfydkq3bjzho661ho) until a more suitable solution is identified.
https://mattermost.atlassian.net/browse/MM-46579
```release-note
NONE
```
> Revert "[MM-46579] Add a limit for preferences"

- app/platform/config.go
- app/platform/config_test.go
Original PR: https://github.com/mattermost/mattermost-server/pull/22102
```release-note
Fixed an issue that prevented the creation of the initial admin user for new servers
```
> Cherry-pick 544304d into release 7.7

- store/sqlstore/channel_store.go
Cherry pick of #22093 on release-7.7.
/cc  @mkraft
```release-note
NONE
```
> Automated cherry pick of #22093

- app/channel.go
- app/channels.go
- app/server.go
- product/api.go
Cherry pick of #22112 on cloud.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #22112

- app/email/email_batching.go
- app/email/notification_email.go
- app/email/notification_email_test.go
- app/notification_email.go
- utils/markdown.go
- utils/markdown_test.go
Transform relative links into absolute links when converting Markdown to HTML.
This will fix invalid links in emails.
[MM-48089](https://mattermost.atlassian.net/browse/MM-48089)
```release-note
Fixed broken links in emails
```
[MM-48089]: https://mattermost.atlassian.net/browse/MM-48089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-48089 Fix broken links in emails

- app/platform/shared_channel_notifier.go
- app/platform/shared_channel_notifier_test.go
Cherry pick of #22103 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #22103

- app/email/email_batching.go
- app/email/notification_email.go
- app/email/notification_email_test.go
- app/notification_email.go
- utils/markdown.go
- utils/markdown_test.go
Cherry-pick fix for relative email urls from #22101 for the cloud
[MM-48089](https://mattermost.atlassian.net/browse/MM-48089)
```release-note
Fixed broken links in emails
```
[MM-48089]: https://mattermost.atlassian.net/browse/MM-48089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cloud: Fix relative email urls

- .circleci/config.yml
- .golangci.yml
- Makefile
- build/Dockerfile.buildenv
- go.mod
- scripts/setup_go_work.sh
https://mattermost.atlassian.net/browse/MM-49703
```release-note
NONE
```
> MM-49703: Bump Go version to 1.19

- app/group.go
- app/group_test.go
- i18n/en.json
Cherry pick of #22022 on cloud.
/cc  @kostaspt
```release-note
NONE
```
> Automated cherry pick of #22022

- i18n/de.json
- i18n/en_AU.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
- i18n/zh-TW.json
Cherry-picking translations from master
https://github.com/mattermost/mattermost-server/pull/22122
```release-note
NONE
```
> Cherry-picking translations from master

- api4/cloud.go
Cherry pick of #22143 on cloud.
/cc  @Afsoon
```release-note
NONE
```
> Automated cherry pick of #22143

- app/post_acknowledgements.go
- app/post_acknowledgements_test.go
- store/sqlstore/post_acknowledgements_store.go
- store/storetest/post_acknowledgements_store.go
Cherry pick of #22124 on cloud.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #22124

- cmd/mattermost/commands/import.go
Cherry pick of #22155 on cloud.
/cc  @noxer
```release-note
NONE
```
> Automated cherry pick of #22155

- app/worktemplates/categories.yaml
- app/worktemplates/generator/main.go
- app/worktemplates/templates.yaml
- app/worktemplates/worktemplate_generated.go
- i18n/en.json
Mostly add content to the work templates system. Also did an improvement to the translation helper of the work template generator to provide the line in correct order, just have to copy/paste now :)
https://mattermost.atlassian.net/browse/MM-49715
```release-note
NONE
```
> [MM-49715] Work templates: add content

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit 6b6150d37453403eaf834904bc4139aa2d8d1bed.
> Revert "Set BoardsProduct FF to on by default"

- build/Dockerfile
Cherry pick of #22174 on cloud.
/cc  @saturninoabril
```release-note
NONE
```
> Automated cherry pick of #22174

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit 6b6150d37453403eaf834904bc4139aa2d8d1bed.
```release-note
NONE
```
> Revert "Set BoardsProduct FF to on by default" (#22177)

- app/post.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
https://mattermost.atlassian.net/browse/MM-50024
```release-note
NONE
```
> MM-50024: Handle empty team name for DM/GMs

- build/Dockerfile
> update libcurl3-gnutls (#22174)

- api4/team.go
- api4/team_test.go
- api4/user_test.go
- app/app_iface.go
- app/channel.go
- app/email/email.go
- app/opentracing/opentracing_layer.go
- app/user.go
- app/user_test.go
Cherry pick of #22119 on release-7.8.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #22119

- api4/cloud.go
- api4/hosted_customer.go
- api4/hosted_customer_test.go
- i18n/en.json
Cherry pick of #22211 on release-7.8.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #22211

- app/platform/web_hub_test.go
- model/websocket_message.go
Cherry pick of #22156 on release-7.5.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #22156

- store/sqlstore/user_store.go
Cherry pick of #21816 on cloud.
```release-note
NONE
```
> Automated cherry pick of #21816

- api4/hosted_customer.go
- api4/hosted_customer_test.go
- i18n/en.json
Cherrypick for https://mattermost.atlassian.net/browse/MM-50049
```release-note
Team edition requests to check CWS availability get a 400 Bad Request instead of a panic
```
> cherry-pick MM-50049

- api4/hosted_customer.go
Cherry pick of #22118 on release-7.8.
/cc  @neallred
```release-note
NONE
```
> Automated cherry pick of #22118

- api4/user_test.go
- store/sqlstore/thread_store.go
Cherry pick of #22228 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #22228

- Makefile
Cherry pick of #22239 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #22239

- config/client.go
Cherry pick of #22171 on cloud.
/cc  @plant99
```release-note
NONE
```
> Automated cherry pick of #22171

- model/feature_flags.go
Adds a feature flag to disable tour tips.
*See https://community.mattermost.com/core/pl/b4pwu6jeb3n7pkejqcci5uy7fh for further context.*
https://mattermost.atlassian.net/browse/MM-50349
```release-note
NONE
```
> [MM-50349] Add Feature Flag to Disable Tour Tips

- model/feature_flags.go
Cherry pick of #22263 on cloud.
/cc  @mylonsuren
```release-note
NONE
```
> Automated cherry pick of #22263

- api4/user_test.go
- app/email/email.go
Cherry pick of #22267 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #22267

- api4/team.go
- api4/team_test.go
- api4/user_test.go
- app/app_iface.go
- app/channel.go
- app/email/email.go
- app/opentracing/opentracing_layer.go
- app/user.go
- app/user_test.go
Manual cherry-pick for release-7.7 of
https://github.com/mattermost/mattermost-server/pull/22119
And 
https://github.com/mattermost/mattermost-server/pull/22267
n/a
```release-note
NONE
```
> Manual cherry pick of mattermost server 22119 upstream release 7.7

- api4/cloud.go
- api4/file.go
- api4/hosted_customer.go
- api4/job.go
- api4/system.go
- shared/web/files.go
Cherry pick of #22226 on release-7.8.
/cc  @Rajat-Dabade
```release-note
NONE
```
> Automated cherry pick of #22226

- shared/filestore/s3store.go
- shared/filestore/s3store_test.go
We were incorrectly returning a subset of the methods,
whereas at other places, clients needed access to other
interfaces as well.
https://mattermost.atlassian.net/browse/MM-50419
```release-note
NONE
```
> MM-50419: Fix panic at interface conversion

- api4/cloud.go
- api4/file.go
- api4/hosted_customer.go
- api4/job.go
- api4/system.go
- shared/web/files.go
Manual cherry-pick of 825b281 into release-7.7
```release-note
NONE
```
> Moving file response functionality to shared folder (#22226)

- app/work_templates.go
- app/work_templates_test.go
- i18n/en.json
When it is set, limit the max length for the name field
https://mattermost.atlassian.net/browse/MM-50080
```release-note
NONE
```
> [MM-50080] Limit max length for the name field

- shared/filestore/s3store.go
- shared/filestore/s3store_test.go
We were incorrectly returning a subset of the methods,
whereas at other places, clients needed access to other
interfaces as well.
https://mattermost.atlassian.net/browse/MM-50419
```release-note
NONE
```
> MM-50419: Fix panic at interface conversion (#22284)

- Makefile
Cherry pick of #22297 on release-7.8.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #22297

- app/migrations.go
- testlib/store.go
Cherry pick of #22245 on release-7.8.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #22245

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit aa61f8dfbbccc9fecb7cee20af1cd2feccffcf48.
> Revert "Revert "Set BoardsProduct FF to on by default" (#22177)"

- app/web_hub_test.go
- model/websocket_message.go
* MM-49048: do not omit needed wsbroadcast vars
Cherry pick of #22156
```release-note
NONE
```
> MM-49048: do not omit needed wsbroadcast vars (#22156)

- store/sqlstore/post_store.go
- store/sqlstore/thread_store.go
Cherry pick of #22304 on release-7.1.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #22304

- app/migrations.go
- testlib/store.go
Cherry pick of #22245 on release-7.7.
```release-note
NONE
```
> Cherry pick of #22245

- .circleci/config.yml
Cherry pick f17b226 into `release-7.7`
```release-note
NONE
```
> The GH token is not required for accesing PR metadata (#22309)

- .circleci/config.yml
Cherry pick of #22309 on release-7.8.
```release-note
NONE
```
> Automated cherry pick of #22309

- Makefile
Update prepackaged boards to v7.8.2
```release-note
Update pre-package boards to v7.8.2
```
> Update prepackaged boards to v7.8.2

- Makefile
Cherry pick of #22316 on release-7.8.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #22316

- Makefile
Update prepackage boards to v7.7.1
```release-note
Update prepackage boards to v7.7.1
```
> Update prepackage boards to v7.7.1

- api4/cloud.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
- model/cloud.go
Cherry pick of #22200 on cloud.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #22200

- app/post_metadata.go
Currently, we only support one. This way, we could make sure multiple works as well.
https://mattermost.atlassian.net/browse/MM-50516
```release-note
NONE
```
> [MM-50516] Support multiple embed

- app/post_metadata.go
Cherry pick of #22337 on cloud.
```release-note
NONE
```
> Cherry pick of #22337
