- app/channels.go
- app/plugin.go
- app/plugin_requests.go
- app/server.go
Add router service to enable products register their existing router to the main router. We use the same logic as plugins, so that plugins wouldn't need to change anything on their end.
https://mattermost.atlassian.net/browse/MM-44330
```release-note
NONE
```
> app/plugin: add product middleware and allow products register routers

- Makefile
Bump pre-packaged version of Zoom to v1.6.0
--
```release-note
Updated pre-packaged Zoom plugin version to v1.6.0
```
> Bump pre-packaged version of Zoom to v1.6.0

- web/params.go
- web/params_test.go
This PR cleans up the `ParamsFromRequest` function. It simplifies the file by using two default behaviors of Go. Firstly the `map` type returns the default value for keys not in the map and secondly, struct properties are initialized with the default value for their respective type. Also `strconv.Parse*` functions return the default value when an parsing error has occurred. Putting this together allows us to replace
```go
if var, ok := props["key"]; ok {
params.Key = val
}
```
with
```go
params.Key = props["key"]
```
This greatly simplifies the function and makes it more readable.
The PR also adds tests for the more complex transformations.
```release-note
NONE
```
> Simplify ParamsFromRequest

- app/post_test.go
Removed the skip for the main test and the parallel markers for the sub-tests. I tried running it multiple times and multiple ways and it seems to work now. Running the sub-tests in parallel triggered a fail once but I couldn't reproduce it again.
[MM-43831](https://mattermost.atlassian.net/browse/MM-43831)
```release-note
NONE
```
> [MM-43831] removed the parallel marker from the subtests

- model/utils.go
This PR improves the ID generation. Instead of generating the base32 encoding with the padding and then stripping the padding off, we just generate it without the padding to begin with. The result is exactly the same but without the need to allocate a byte buffer and with much simpler code.
[MM-44925](https://mattermost.atlassian.net/browse/MM-44925)
```release-note
NONE
```
> [MM-44925] simplified the ID generator

- api4/config_test.go
- app/integrations.go
- app/plugin_test.go
When checking the freemium limits for enabling an integration, we check the Cloud Freemium feature flag, but we don't check for a Cloud license. This is not an issue in production, but testing servers are having issues when the feature flag is set, but a Cloud license is not installed. An error occurs when we request limits from the CWS server in this case.
This PR makes it so we check for the Cloud license, and avoid checking limits when there is not one present.
This PR also treats the case where we receive an error from the CWS server as a pass. The only time we will block an integration enable is when we have proof that a server has reached its limit.
Fixes https://mattermost.atlassian.net/browse/MM-44905
```release-note
NONE
```
> Check for cloud license and CWS error when checking integration freemium limits

- app/email/email.go
- app/email/email_test.go
- i18n/en.json
Removes reference to 30 days trial in cloud welcome email + add test
The QA should be done post-merge as the email will not get triggered on a spinwick
https://mattermost.atlassian.net/browse/MM-44995
```release-note
NONE
```
> [MM-44995] remove reference to 30 days trial in welcome email

- model/client4.go
UpdateUserCustomStatus server API never returned the object.
But the client driver tried to parse the JSON response into
a struct, which always parsed as an empty struct.
We fix that by returning the original response and added
a comment to clarify that.
Found while adding coverage for custom status in the load-test
tool.
```release-note
NONE
```
> Fix client driver API for UpdateUserCustomStatus

- api4/channel_category.go
- api4/channel_category_test.go
Passing null is a valid JSON input for a pointer struct. So we avoid
passing pointer to pointer.
https://mattermost.atlassian.net/browse/MM-44805
```release-note
NONE
```
> MM-44805: Avoid pointers in JSON parsing in createCategoryForTeamForUser

- api4/channel_category.go
- api4/channel_category_test.go
Passing null is a valid JSON input for a pointer struct. So we avoid
passing pointer to pointer.
https://mattermost.atlassian.net/browse/MM-44806
```release-note
NONE
```
> MM-44806: Avoid pointers in JSON parsing in updateCategoryForTeamForUser

- app/channels.go
- i18n/en.json
- model/config.go
- services/telemetry/telemetry.go
```release-note
We create a new config option MaxImageDecoderConcurrency which
indicates how many images can be decoded concurrently at once.
The default is -1 which means number of CPUs present.
This affects the total memory consumption of the server. The
maximum memory of a single image is dictated by MaxImageResolution * 24 bytes.
Therefore, a good rule of thumb to follow is that MaxImageResolution
* MaxImageDecoderConcurrency * 24 should be less then the allocated memory for
image decoding.
```
https://mattermost.atlassian.net/browse/MM-43733
> MM-43733: Set concurrency limits via configuration

- app/upload_test.go
Removing the error id check should reduce flakiness as there is a rare edge case in which one upload attempt completes before others could get a chance to grab the lock.
https://mattermost.atlassian.net/browse/MM-41026
```release-note
NONE
```
> [MM-41026] Fix flaky TestUploadDataConcurrent

- store/sqlstore/file_info_store.go
- store/storetest/file_info_store.go
If there are no entries in the FileInfo table, then null results, which can't be cast to a number. So we add a COALESCE expression to default to 0 in that case. Because the frontend handles errors gracefully, I don't think we need to cherry-pick this for June 15 release, although we may see a few error logs in brand new installations until a file is uploaded.
https://mattermost.atlassian.net/browse/MM-45057
```release-note
Fix for cloud instances that had backend errors when fetching file storage usage when no files had been uploaded.
```
> File storage usage default 0

- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
- store/timerlayer/timerlayer.go
Adds separate telemetry counts of unique users in groups for each group type (`custom` and `ldap`).
n/a
```release-note
Improves group membership telemetry.
```
> Improves group membership telemetry.

- app/server_test.go
The config store was incorrectly initialized. Other than that,
I don't think there is any "flakyness" in the test.
https://mattermost.atlassian.net/browse/MM-43832
```release-note
NONE
```
> MM-43832: Fix flaky TestReadReplicaDisabledBasedOnLicense

- api4/channel.go
- api4/cloud_test.go
- app/channel.go
- app/cloud.go
- i18n/en.json
- model/channel.go
- model/channel_search.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
Use a single critical section. If unable to fetch system value, only proceed if the system value row did not exist.
Supports https://github.com/mattermost/mattermost-server/pull/20338/files
```release-note
NONE
```
> Use a single critical section for users notified admin

- config/client.go
- config/client_test.go
Couldn't check for SKU short name directly on the chat-facing frontend because system users (ie non-admins) are not authorized to read the SKU short name. Added a new client config setting instead.
https://mattermost.atlassian.net/browse/MM-44642
```release-note
Added new client config setting to indicate if the Insights feature is accessible based to clients.
```
* https://github.com/mattermost/mattermost-webapp/pull/10584
> MM-44642 hide insights per license

- build/docker/postgres.conf
- store/sqlstore/channel_store.go
- store/sqlstore/file_info_store.go
- store/sqlstore/post_store.go
- store/sqlstore/store.go
We use the default_text_search_config param from the DB
and pass that as the search config instead of hardcoding
it to english.
The docs do say that if no param is passed, by default
it will automatically fall back to default_text_search_config.
But I have seen different query plans being created
when the parameter is not passed versus when it is passed.
I am not sure why this is happening, but to be safe,
I have taken the search config during startup and stored
it in the SqlStore struct.
For reference, this is what happens without a search config
passed:
```
[bigdb] # explain analyze  SELECT *, (SELECT COUNT(*) FROM Posts WHERE Posts.RootId = (CASE WHEN q2.RootId = '' THEN q2.Id ELSE q2.RootId END) AND Posts.DeleteAt = 0) as ReplyCount FROM Posts q2 WHERE q2.DeleteAt = 0 AND q2.Type NOT …
```
> MM-25554: Remove hardcoded english as the search config

- app/user.go
As part of an SET escalation a temporary check is added to `App.GetUser`, which seems to return `nil,nil` when called via some plugins.
NONE     See https://community.mattermost.com/core/pl/qyd9mschzjnfmp4ecwjhy6os5c
```release-note
NONE
```
> Check for nil,nil returned from GetUser

- Makefile
This can cause some confusion while switching
to older branches which does not support module
workspaces.
```release-note
NONE
```
> Remove go.work files in make nuke

- app/user.go
Reverts the PR https://github.com/mattermost/mattermost-server/pull/20501 which was added for SET escalation.
It was determined that the plugins call to GetUser never made it to the app layer.
Fixes https://mattermost.atlassian.net/browse/MM-45209
```release-note
NONE
```
> MM-45209  Revert PR checking for GetUser returning nil,nil

- services/imageproxy/local.go
- services/imageproxy/local_test.go
For the local proxy, we weren't following redirects.
We remove the CheckRedirect function and use the default
function, which is good enough for our purposes.
https://mattermost.atlassian.net/browse/MM-40450
```release-note
NONE
```
> MM-40450: Follow redirects in image proxy

- api4/cloud.go
- api4/cloud_test.go
This PR make the getSubscription endpoint available with restricted and containing non-sensitive information to non-admin users so we can start implementing the functionalities where end users will be able to notify admins about "starting a trial" or "subscribing" depending on the subscription status.
https://github.com/mattermost/mattermost-webapp/pull/10609
https://mattermost.atlassian.net/browse/MM-44863
```release-note
NONE
```
> MM-44863 - update trial details in product menu

- api4/user.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
- store/timerlayer/timerlayer.go
Allows us to sort users of a channel by admin. The channel admins will be returned first, followed by all other members.
https://github.com/mattermost/mattermost-webapp/pull/10577
https://mattermost.atlassian.net/browse/MM-44159
```release-note
NONE
```
> [MM-44159] Add user sort by admin status in channels

- app/post_metadata.go
- app/upload.go
- app/upload_test.go
- i18n/en.json
- model/file_info.go
- utils/imgutils/gif.go
- utils/imgutils/gif_test.go
This was an interesting journey as it turned out that several assumptions I had were wrong:
- The new resumable upload code path was using [`model.GetInfoForBytes`](https://github.com/mattermost/mattermost-server/blob/e5ee5eecd835163ad0aedebad4a2806d32cf3b16/model/file_info.go#L133) to generate the file info object from the uploaded data. This involved some extra decoding in case the image format was GIF which would happen before any check on image resolution opening up a path for potential unbounded memory allocation. Turns out other upload paths don't call this at all and the GIF file is decoded regardless at a later point ([`preprocessImages`](https://github.com/mattermost/mattermost-server/blob/e5ee5eecd835163ad0aedebad4a2806d32cf3b16/app/file.go#L808) / …
> [MM-45504] Improve GIF preprocessing logic

- api4/resolver_channel_member_test.go
- api4/resolver_channel_test.go
- api4/schema.graphqls
- model/channel.go
- model/channel_member.go
This PR adds the fields `totalMsgCountRoot` and `lastRootPosAt` to Channel, and `msgCountRoot` to ChannelMember as per [this comment](https://mattermost.atlassian.net/browse/MM-45168?focusedCommentId=129675). The `mentionCountRoot` field already exists.
[MM-45168](https://mattermost.atlassian.net/browse/MM-45168)
```release-note
NONE
```
> MM-45168 Added GraphQL fields to channel and channel_member

- api4/resolver_team_member_test.go
- api4/schema.graphqls
- model/team.go
This PR adds the fields `createAt`, `deleteAt`, `schemeId`, `policyId`, and `cloudLimitsArchived` to the Team returned by GraphQL.
[MM-45168](https://mattermost.atlassian.net/browse/MM-45168)
```release-note
NONE
```
> MM-45168 GraphQL: add fields to Team

- app/web_conn.go
- app/web_conn_test.go
We were incorrectly returning from the method without
resetting the pointer.
Fixes https://github.com/mattermost/mattermost-server/issues/20622
```release-note
NONE
```
> Fix incorrect dead queue clear logic

- model/config.go
Make three file settings editable in Cloud System Console UI
- EnableFileAttachments
- EnableMobileUpload
- EnableMobileDownload
Context on this thread: https://community-daily.mattermost.com/private-core/pl/mcwz7e78a78ejd78a4gmqntsmw
```release-note
NONE
```
> Make three file settings editable in Cloud System Console UI

- store/sqlstore/store.go
We replace expected/received with the source of the collation.
This makes it more clear as to from where the values
were retrieved.
```release-note
NONE
```
> Clarify collation mismatch string

- db/migrations/mysql/000089_add-channelid-to-reaction.up.sql
- db/migrations/postgres/000089_add-channelid-to-reaction.up.sql
When populating Reactions.ChannelId via the migration some Reactions have no associated Post and since the ChannelId column is `NOT NULL` the migration fails unless we coalesce to `''`.
n/a
```release-note
NONE
```
> Coalesce migration of Reactions.ChannelId to '' if Post does not exist.

- app/app.go
- app/bot.go
- app/channel.go
- app/channels.go
- app/cloud.go
- app/cluster.go
- app/config.go
- app/file.go
- app/license.go
- app/permissions.go
- app/plugin.go
- app/plugin_key_value_store.go
- app/post.go
- app/server.go
- app/team.go
- product/api.go
- store/store.go
This PR fixes a breaking change introduced via https://github.com/mattermost/mattermost-server/pull/20575.  The structs passed during product init must implements the interfaces defined in `product/api.go`.  Unfortunately, when the method signatures are changed the failures happen at run-time via type assertions.
Additionally, this PR adds compile-time checks to ensure changes to method signatures are detected immediately.
NONE 
```release-note
NONE
```
> Fix broken master; ensure all product service APIs have correct implementations

- app/product_notices_test.go
- app/teams/helper_test.go
- app/users/helper_test.go
- cmd/mattermost/commands/import.go
- cmd/mattermost/commands/init.go
- jobs/import_process/worker.go
- services/slackimport/slackimport_test.go
- web/context_test.go
- web/oauth_test.go
Some imports and tests just initialize an empty context, causing nil pointer dereferences is the server. This PR initializes them.
Thanks to @josephbaylon for reporting this issue.
[MM-45769](https://mattermost.atlassian.net/browse/MM-45769)
```release-note
NONE
```
> [MM-45769] Properly initialize the request.Context for imports and tests

- config/client.go
- model/config.go
- services/telemetry/telemetry.go
This PR adds the ability to configure showing of the upgrade button to self hosted admins
https://mattermost.atlassian.net/browse/MM-45684
https://github.com/mattermost/mattermost-webapp/pull/10764
```release-note
Added a new config setting ExperimentalSettings.EnableUpgradeForSelfHostedStarter
```
> [MM-45684] - Self Managed: Add pricing modal + Upgrade button

- model/config.go
Based on feedback from customer success team
cc @sadohert 
```release-note
NONE
```
> Make 'DisableBotsWhenOwnerIsDeactivated' and 'HelpLink' editable in Cloud

- build/notice-file/Readme.md
- build/notice-file/config.yaml
Building on https://github.com/mattermost/mattermost-plugin-playbooks/pull/1255 we continue the effort to automate `notice.txt` generation for `mattermost-server` 
We selected `build/notice-file` directory, to store the configuration files. Let us know if we need to relocate this. 
Ticket: https://mattermost.atlassian.net/browse/CLD-3697
> [feat] Notice.txt generation configuration

- config/client.go
- model/config.go
- services/telemetry/telemetry.go
Reverts mattermost/mattermost-server#20653
This PR adds the ability to configure showing of the upgrade button to self hosted admins
https://mattermost.atlassian.net/browse/MM-45684
https://github.com/mattermost/mattermost-webapp/pull/10764
```release-note
Added a new config setting ExperimentalSettings.EnableUpgradeForSelfHostedStarter
```
> Revert "[MM-45684] - Self Managed: Add pricing modal + Upgrade button"

- store/storetest/group_store.go
It's almost impossible to find a problem with the test conditions without the actual values that caused the condition to fail. This PR adds those values and the operation that failed so we can investigate better in the future. I could not reproduce the actual problem. The test ran without problems for me (`go test -timeout 45m -run ^TestGroupStore$ github.com/mattermost/mattermost-server/v6/store/sqlstore -count=1`, about 30 times).
[MM-44365](https://mattermost.atlassian.net/browse/MM-44365)
```release-note
NONE
```
> [MM-44365] Add values and operation to the condition checks

- api4/upload_test.go
- app/upload.go
- model/file_info.go
Some code was missing from https://github.com/mattermost/mattermost-server/pull/20595 which generated fileinfos with missing size and extension.
Interestingly this was not caught by any test. I updated them here but it may be worth having something on the e2e side as well, like checking that the filesize is correctly displayed.
https://mattermost.atlassian.net/browse/MM-45862
```release-note
NONE
```
> [MM-45862] Set size and extension to fileinfo

- go.mod
Correctly updating this requires PRs
in multiple repositories. Fixing this
with a hammer for now to unblock server.
```release-note
NONE
```
> Killing dyatlov/go-opengraph with fire

- model/feature_flags.go
This adds a feature flag, FeatureFlagServerUpgradeButtonText to control the text to be shown on Plan Upgrade Button for cloud workspaces
FeatureFlagServerUpgradeButtonText = A , the button reads "Upgrade"
FeatureFlagServerUpgradeButtonText = B, the button reads "View plans"
https://app.split.io/org/e23fa240-f3b6-11ea-b78e-12a8e42e6081/ws/e244d260-f3b6-11ea-b78e-12a8e42e6081/splits/70a0aef0-0745-11ed-a805-0e7877c91061/env/e24b3b00-f3b6-11ea-b78e-12a8e42e6081/definition
https://mattermost.atlassian.net/browse/MM-45666
- Has webapp changes (https://github.com/mattermost/mattermost-webapp/pull/10798)
```release-note
NONE
```
> [MM-45666] - A/B Test: Nav Bar Upgrade button

- app/file.go
- app/file_test.go
This creates faulty requests to Bifrost and results in
errors and warnings in the logs. Even without Bifrost,
this would make unnecessary requests to S3.
We only extract info from documents and therefore we can
safely avoid this.
```release-note
NONE
```
> MM-45871: Do not try to extract content from images

- api4/user.go
- api4/user_test.go
- app/login.go
Right now, we only attached the cloud cookie (`MMCLOUDURL`) when the user was logging in using email/password.
I was trying to copy this same way to every login place before realizing that every single time I was inserting new code just behind `AttachSessionCookies`, so I moved the call to set the cloud cookie inside of `AttachSessionCookies`, this also allows us to be future proof.
https://mattermost.atlassian.net/browse/MM-45817
```release-note
NONE
```
> [MM-45817] Set cloud cookies whenever user gets logged in

- .github/PULL_REQUEST_TEMPLATE.md
A schema migration template is now available to help guide release note development.
```release-note
NONE
```
> Added schema migration template to PR template

- app/app_iface.go
- app/file.go
- app/file_bench_test.go
- app/opentracing/opentracing_layer.go
- app/plugin_hooks_test.go
- i18n/en.json
- shared/filestore/s3store.go
For user profile and plugin upload, we use a bytes.Buffer.
In that case, we know the object size and can find
it out from the length of the buffer.
This helps reduce multi-part uploads.
This approach can also be taken in thumbnail and preview
images. However, they use an io.Pipe to directly upload
the image as it is being encoded. We could make the whole
process in separate parts of writing the full image in the
buffer and then upload it. But taking a conservative approach
for now.
Also, while here, removed some unused code.
Fixes https://github.com/mattermost/mattermost-server/issues/20066
https://mattermost.atlassian.net/browse/MM-43828
```release-note
NONE
```
> MM-43828: Pass object length for some image operations

- api4/resolver_team.go
- api4/resolver_team_member_test.go
GraphQL checked the wrong permission when requesting teams. This prevented guest users from successfully logging in when GraphQL was in use.
[MM-45715](https://mattermost.atlassian.net/browse/MM-45715)
```release-note
NONE
```
> [MM-45715] Check for correct permission when requesting teams

- api4/resolver_team_member_test.go
- app/authorization.go
We missed a case to return if there are no
items in the slice. Otherwise it falls through
and returns false incorrectly.
Rectified the tests to trigger the case.
https://mattermost.atlassian.net/browse/MM-45715
```release-note
NONE
```
> MM-45715: Fix incorrect permissions (Round 2)

- app/app_iface.go
- app/file.go
- app/file_bench_test.go
- app/opentracing/opentracing_layer.go
- app/plugin_hooks_test.go
- i18n/en.json
- shared/filestore/s3store.go
Reverts mattermost/mattermost-server#20711
This causes issues when used with bifrost. Reverting for now
> Revert "MM-43828: Pass object length for some image operations"

- store/sqlstore/post_store.go
- store/storetest/post_store.go
In a few scenarios of `PostStore/Get` method, a duplicate Order entry is added in the PostList.Order.
This duplicate entry is causing the issue in filtering the inaccessible posts.
So, this PR makes sure there are no duplicates in Order.
Jira - https://mattermost.atlassian.net/browse/MM-45726
```release-note
Fixed a bug, causing the crash when fetching the unread posts.
```
> [MM-45726] Fix Sentry crash: nil deference in app/post_helpers.go:85

- api4/post.go
- api4/post_test.go
- i18n/en.json
Cherry pick of #20565 on release-7.2.
```release-note
NONE
```
> Automated cherry pick of #20565

- .circleci/config.yml
This updates the build-images used for CI to:
- node: 16.2.0 -> 16.10.0
- npm: 7.13.0 -> 7.24.0
Internal consumed images: 
```
> docker run --platform linux/amd64 -it ${CI_REGISTRY}/mattermost/ci/devops-images/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d node -v
v16.10.0
> docker run --platform linux/amd64 -it ${$CI_REGISTRY}/mattermost/ci/devops-images/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d npm -v
7.24.0
```
Public consumed images: 
```
> docker run --platform linux/amd64 mattermost/mattermost-build-webapp:20220802_node-16.10.0@sha256:3272aa759f10c2ef1719ed08cc82ddb07224bec5be86f09800c72f5e2a623c3d  node -v
v16.10.0
> docker run …
```
> [chore] Update Node and Npm build image

- store/sqlstore/post_store.go
We use * instead of a column name to use
index-only scan always even when other column filters
are applied.
Right now, index-only scan will only get applied
in the basic query of "select count(p.id) as value
from posts p". But it won't get applied if the query
is "select count(p.id) as value from posts p where
p.deleteat=0".
So this is a minor optimization which improves
some corner cases.
This was found from the slow query monitoring.
```release-note
NONE
```
> Optimize AnalyticsPostCount

- app/app_iface.go
- app/file.go
- app/file_bench_test.go
- app/opentracing/opentracing_layer.go
- app/plugin_hooks_test.go
- i18n/en.json
- shared/filestore/s3store.go
- Revert "Revert "MM-43828: Pass object length for some image operations (#20711)" (#20740)"
- Fix to work in bifrost mode
```release-note
Updating profile image and creating new emojis don't use multi-part uploads anymore when using S3 storage.
```
> Fix minio client breakage with bifrost round 2

- app/channel.go
- app/channel_test.go
A weird code fragment in `channel.go` caused MM to call `errors.As` on a `(*model.AppError)(nil)` which lead to a crash in the `Unwrap` method. The code effectively only skipped missing channels and did nothing useful. This PR removes the code and replaces it with a log statement.
[MM-46054](https://mattermost.atlassian.net/browse/MM-46054)
```release-note
NONE
```
> [MM-46054] Log missing default channels

- app/channel.go
The method a.postRemoveFromChannelMessage was being called
from a goroutine. Therefore, when SystemAdminClient.GetFlaggedPostsForUser
was being called later in the test with a mock post store,
it would naturally fail because the store would now be a
different store but the goroutine was supposed to be finished.
A hacky solution would be to add a sleep before
starting the mocked API call. But a deeper question
is why was the method run in a goroutine in the first place.
Removing a user from a channel is not a very common operation
and even if we look at the method, if the user is trying to
remove themselves, that message happens synchronously, but if
they are removing another user, that runs in a goroutine.
This seems like a very weird behavior. Therefore, to be consistent
I have just …
> MM-45021: Fix flaky testGetFlaggedPostsForUser

- app/app_iface.go
- app/channel.go
- app/channel_category.go
- app/channel_test.go
- app/emoji.go
- app/group.go
- app/opentracing/opentracing_layer.go
- app/post.go
- app/preference.go
- app/role.go
- app/slashcommands/command_expand_collapse.go
- app/syncables.go
- app/team.go
- app/team_test.go
- app/user.go
- i18n/en.json
During attaching an object to a websocket message, we would
marshal it to json and attach the string output. But if the
marshalling failed, we would just log a warning and move on.
This would add an empty string to the message. But the client
assumes that the object is correctly attached and would
fail silently if it cannot find it.
So we become more strict and return the error so that
it reaches the caller.
https://mattermost.atlassian.net/browse/MM-45993
```release-note
NONE
```
> MM-45993: Return errors during sending websocket messages

- Makefile
Whenever we execute golangci-lint it activates rules of mattermost-server at focalboard repo.
We should not apply server lint rules to that repo. PR contains changes to execute lint on focalboard repo with it's own rules.
https://mattermost.atlassian.net/browse/CLD-3800
```release-note
NONE
```
> Stop applying server lint rules to focalbard repo.

- app/channel.go
- app/channel_test.go
Cherry pick of #20738 on release-7.2.
/cc  @noxer
```release-note
NONE
```
> Automated cherry pick of #20738

- api4/channel_test.go
The returned elements weren't in a specific order.
Therefore, we need to perform an order insensitive match.
https://mattermost.atlassian.net/browse/MM-45534
```release-note
NONE
```
> MM-45534: Fix flaky TestCreateGroupChannel

- api4/channel.go
- api4/channel_test.go
- api4/cloud.go
- api4/cloud_test.go
- api4/file.go
- api4/file_test.go
- api4/group.go
- api4/group_test.go
- api4/user_test.go
- app/emoji.go
There were lots of cases where we were using the code 501
in an incorrect manner, and since 5xx codes are considered
as SLO violations, these were flagged by our monitoring incorrectly.
These were the guidelines to change the codes:
1. Any case of missing license or config not correctly enabled
is set as Forbidden. The logic is that the user is correctly
authenticated with a session, but does not have enough privileges
to have the higher license, or hasn't changed the config correctly.
2. Any case of incorrectly formed request is obviously a 400.
https://mattermost.atlassian.net/browse/MM-43202
```release-note
NONE
```
> MM-43202: Change some 501 response codes to fix SLO violations

- app/import_functions_test.go
- Flush log buffer before asserting log text. 
- https://mattermost.atlassian.net/browse/MM-44922
```release-note
NONE
```
> MM-44922: Flush log buffer before assert

- api4/insights.go
- api4/insights_test.go
- app/app_iface.go
- app/import_functions.go
- app/opentracing/opentracing_layer.go
- app/slashcommands/auto_users.go
- app/team.go
- app/team_test.go
- app/teams/teams.go
- db/migrations/migrations.list
- db/migrations/mysql/000092_add_createat_to_teammembers.down.sql
- db/migrations/mysql/000092_add_createat_to_teammembers.up.sql
- db/migrations/postgres/000092_add_createat_to_teamembers.down.sql
- db/migrations/postgres/000092_add_createat_to_teamembers.up.sql
- i18n/en.json
- model/client4.go
- model/insights.go
- model/team_member.go
- model/team_member_serial_gen.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/team_store.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/timerlayer/timerlayer.go
* Adds a new `CreateAt` column to the `TeamMembers` table to track the time users join a team.
* Adds a new btree index to the new `TeamMembers.CreateAt` column.
* Adds a new API endpoint `GET /api/v4/teams/:team_id/top/team_members` to retrieve the team members who have joined the given team (today, or in the past 7 or 28 days).
Example API request:
```shell
curl 'http://localhost:8065/api/v4/teams/okofznhigfna3js4ue9fsrjtma/top/team_members?page=0&per_page=1&time_range=today' \
-H 'Authorization: Bearer heqd4eawgffsmczgb18m68fkga' \
-H 'X-Requested-With: XMLHttpRequest'
```
Example response:
```json
{
"has_next": true,
"items": [
{
"id": "bwmd5gwsnpn39du1chysa4rw6r",
"username": "albert.torres",
"first_name": "Albert",
"last_name": "Torres",
"nickname": "Lazz",
"position": "Accountant …
```
> MM-45120: Track team join times. Add API to retrieve new team members since a given time.

- api4/post.go
- api4/post_test.go
- i18n/en.json
Reverts mattermost/mattermost-server#20748
Reverted as this wasn’t working as expected. I’ll revert the PR from the 7.2 branch and will check with the Channels team if we want to revert from the master branch too.
> Revert "Automated cherry pick of #20565"

- api4/post.go
- api4/post_test.go
- i18n/en.json
Reverts mattermost/mattermost-server#20565
During v7.2 QA release testing, the QA team found that https://mattermost.atlassian.net/browse/MM-45272 wasn't working at all in v7.2-RC3, so we're reverting the PR (we've already reverted the PR from the v7.2 branch via [pr-mattermost-server-20808](https://github.com/mattermost/mattermost-server/pull/20808)). I asked Guillermo and he said he's ok with reverting. We also suspect that this is causing the permalink issue https://mattermost.atlassian.net/browse/MM-46217.
> Revert "MM-45272: Fix getPostThread permissions"

- build/Dockerfile
- build/entrypoint.sh
We are proposing switching to building docker container for `matermmost-server` & `enterprise` from Alpine Linux(unsupported) to Debian(supported).
For context, this image is actually used for e2e testing.
Alpine is actually an [unsupported distribution](https://docs.mattermost.com/install/software-hardware-requirements.html#mattermost-server-operating-system) for mattermost-server. On top of that, Alpine linux uses **musl libc** vs **glibc**, which can introduce several challenges, that can be difficult to actually troubleshoot. 
https://github.com/golang/go/issues/51280
Finally We got to a point of being unable to run Alpine based mattermost instances with: `Error relocating ./mattermost: fcntl64: symbol not found`, caused by using Alpine linux. 
PR affected by the issue : …
> [CLD-3942] Container Image used for e2e testing, migration from Alpine to Debian Linux

- api4/import.go
- app/import.go
- app/import_test.go
- i18n/en.json
We migrate them to use logger context.
https://mattermost.atlassian.net/browse/MM-45198
```release-note
NONE
```
> MM-45198: Migrate app/import and api4/import

- i18n/en.json
Add missing words to message sent when inviting someone to join a channel in a team.
https://mattermost.atlassian.net/browse/MM-43663
```release-note
NONE
```
> MM-43663 - add missing words to email invite

- Makefile
- scripts/setup_go_work.sh
We flip the default mode to always regenerate the file,
and expose an option to ignore if it exists.
The way to preserve the old behavior is to use an additional `IGNORE_IF_EXISTS` flag
like `make run-server IGNORE_IF_EXISTS=true`.
```release-note
NONE
```
> Always regenerate go.work file

- app/enterprise.go
- app/platform/cluster.go
- app/platform/config_test.go
Fixes an issue where cluster interface was not passed to platform service after initialized.
https://mattermost.atlassian.net/browse/MM-46426
```release-note
NONE
```
> re-assign cluster interface after initializing enterprise interfaces

- app/post.go
`Order` field may contain an extra post id in case, `all` or `lastUnreadPostId` is filtered out as per the cloud plan's limit. This extra `Id` then cause this issue in `SortByCreateAt`.
JIRA - https://mattermost.atlassian.net/browse/MM-45730
```release-note
Fixed a bug, causing the crash when fetching the unread posts.
```
> [MM-45730] Fix Sentry crash: nil deference in model/post_list.go:152

- api4/post_test.go
- model/utils.go
- model/utils_test.go
Wrapped errors would be lost once the AppError is serialized and deserialized. To prevent the error message from being lost, it's added to the detailed field on serialization.
```release-note
NONE
```
> Put wrapped errors into the detailed field on serialization

- app/server.go
- app/server_test.go
- We need a pointer to a pointer to set the original pointer to nil
- The original task was not being set to `nil` (the local variable containing the pointer was being set to nil). The cancel func was being called even though the task had already been cancelled. This repeated cancellation was causing a panic because we were trying to close a channel that had already been closed the first time the task was cancelled.
- https://mattermost.atlassian.net/browse/MM-46402
```release-note
NONE
```
> MM-46402: Use pointer to pointer to set pointer to nil

- web/context.go
Due to the recent changes in error wrapping, the DetailedError
field does not contain the full info of all the wrapped errors.
Therefore, while printing the error, we display the stringified
representation instead of only the DetailedError field.
```release-note
NONE
```
> Print full error string instead of only detailed error

- shared/filestore/s3store.go
PR https://github.com/minio/minio-go/pull/1668 introduced
an option to disable sha256, which by default was disabled.
This meant all content was always hashed and this broke
in bifrost because the key signing fails in streaming
mode.
So for cloud installations, we disable sha256.
https://mattermost.atlassian.net/browse/MM-46475
```release-note
NONE
```
> MM-46475: Disable sending content sha in bifrost mode

- app/busy_test.go
I think the ordering for the check and compare was wrong as `cluster.Busy` is never set to be busy.
https://mattermost.atlassian.net/browse/MM-45725
```release-note
NONE
```
> fix flaky busy test

- app/channels.go
- app/preference.go
- app/server.go
- product/api.go
This PR adds a Preferences service API which allows products to access user preferences.  Currently this service is provided by channels because preferences are implemented in App, but should be moved to server once App is refactored.
NONE
```release-note
NONE
```
> Add preferences service API for products

- store/sqlstore/user_store.go
- store/storetest/user_store.go
There were 2 main problems after https://github.com/mattermost/mattermost-server/pull/20367.
1. The : wasn't escaped.
2. Empty search didn't work.
For 1, we escape the ':'. For 2, we just use
pattern search.
```release-note
NONE
```
> MM-46503: Escape incorrect pg user search query

- scripts/test.sh
In CI environment, race tests take a huge amount
of memory. Since we only run it on master, there's
no rush to finish it quickly. Hence we can limit
the parallelism and throttle memory usage.
```release-note
NONE
```
> Limit GOMAXPROCS while running race tests

- store/errors.go
- store/sqlstore/adapters.go
- store/sqlstore/bot_store.go
- store/sqlstore/channel_member_history_store.go
- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_categories.go
- store/sqlstore/cluster_discovery_store.go
- store/sqlstore/command_webhook_store.go
- store/sqlstore/emoji_store.go
- store/sqlstore/group_store.go
- store/sqlstore/integrity.go
- store/sqlstore/oauth_store.go
- store/sqlstore/post_store.go
- store/sqlstore/preference_store.go
- store/sqlstore/product_notices_store.go
- store/sqlstore/reaction_store.go
- store/sqlstore/retention_policy_store.go
- store/sqlstore/role_store.go
- store/sqlstore/scheme_store.go
- store/sqlstore/shared_channel_store.go
- store/sqlstore/status_store.go
- store/sqlstore/store.go
- store/sqlstore/system_store.go
- store/sqlstore/team_store.go
- store/sqlstore/thread_store.go
- store/sqlstore/user_access_token_store.go
- store/sqlstore/user_store.go
- store/sqlstore/user_terms_of_service.go
- store/sqlstore/utils.go
This PR adds a number of returns for previously ignored errors in the sqlstore package. It also adds functionality to report errors in the rollback of operations. In once instance, it removes the reporting of errors returned by `bytes.Buffer`, which only panics but never actually returns errors.
[MM-45994](https://mattermost.atlassian.net/browse/MM-45994)
```release-note
NONE
```
> MM-45994 ensure database operations return their errors

- .circleci/config.yml
This is to compensate for increased memory usage for DB Tests running with `-race` option. 
Go process consuming 24GB RSS, then system is rendered as unresponsive, (crashing) due to memory depletion.
Therefore, we are doubling the system memory, from 32GB to 64GB to compensate for the increased usage. 
Ticket: https://mattermost.atlassian.net/browse/CLD-4014
```release-note
```
> [chore] Doubling the instance size used for CI

- build/Dockerfile
curl depends on libcurl, since dependencies are not pinned, docker build fails cause latest version of libcurl is not compatible with the pinned curl in the dockerfile.
Pinned every apt dependency in the dockerfile, so we will not have similar features in future.
Related Problem:
Our first level configured dependencies are:
```
ca-certificates=20200601~deb10u2 \
curl=7.64.0-4+deb10u2 \
mime-support=3.62 \
unrtf=0.21.10-clean-1 \
wv=1.2.9-4.2+b2 \
poppler-utils=0.71.0-5 \
tidy=2:5.6.0-10 \
```  
Indirect dependencies are:
```
libssl1.1=1.1.1n-0+deb10u3 \
sensible-utils=0.0.12 \
libsasl2-modules-db=2.1.27+dfsg-1+deb10u2 \
libsasl2-2=2.1.27+dfsg-1+deb10u2 \
libldap-common=2.4.47+dfsg-3+deb10u7 \
libldap-2.4-2=2.4.47+dfsg-3+deb10u7 \
libicu63=63.1-6+deb10u3 \
libxml2=2.9.4+dfsg1-7+deb10u4 \ …
```
> Apt dependencies are not pinned, so upgrades will break docker builds.

- .circleci/config.yml
- store/sqlstore/channel_store.go
This query is causing issues in a customer's large scale environment. This is backporting a fix that already exists on `master`. Deleted group members don't need to be counted.
```release-note
Improve groups query performance by not counting deleted members
```
> [Backport to 5.37] Exclude deleted group members from query to count channel members by group

- app/export.go
- app/export_converters.go
- app/import.go
- app/import_functions.go
- app/import_functions_test.go
- app/import_test.go
- app/imports/import_types.go
- app/imports/import_validators.go
- app/imports/import_validators_test.go
In order for the validators in the server and in `mmctl` to share code, we need to put it into a separate package. This PR moves the import validators and types into the `app/imports` package. In order for this change to be a non-invasive as possible, it creates one type alias to prevent two interface changes (`AppIface` and `OpenTracing Layer`).
The linter insisted on not allowing anonymous fields in struct literals, so there are a few changes for this as well.
[MM-38705](https://mattermost.atlassian.net/browse/MM-38705)
```release-note
NONE
```
> [MM-38705] Move import validators into own package

- app/web_conn.go
Apparently, this can happen in normal situations as well
and is causing confusion amongst customers. Reverting.
This reverts commit 9534efe534d09d0378e9e1f1b51b9bb8b059bb66.
```release-note
NONE
```
> Revert "Use error log level for websocket timeouts (#19609)"

- store/sqlstore/channel_store.go
This is a backport which was originally part of
https://github.com/mattermost/mattermost-server/pull/18839.
But we extract it out specially to fix the correctness
of this query.
```release-note
NONE
```
> [6.3 Backport] - Exclude deleted group members

- app/slashcommands/command_marketplace.go
- app/slashcommands/command_marketplace_test.go
Add checks on the `/marketplace` command to only allow autocomplete when the server config has plugins and marketplace enabled
https://mattermost.atlassian.net/browse/MM-46663
```release-note
NONE
```
> [MM-46663] Only enable marketplace command completion when config allows it

- api4/resolver_channel.go
- api4/resolver_channel_test.go
- model/utils.go
The props map was being null, but the schema did not
allow nulls. Therefore, the whole response was being
set to null. There was no error which created more
confusion.
To avoid making the property nillable, which would
mean sending pointers to maps, we just create
empty maps if they are nil.
https://mattermost.atlassian.net/browse/MM-46869
```release-note
NONE
```
> MM-46869: Fix channel props not appearing in GraphQL

- go.mod
- go.sum
Split finally upgraded their dependency.
This means we can bump this and get rid of any hacks
in our dependency upgrade process!
```release-note
NONE
```
> Bump splitio dependency

- jobs/import_process/worker.go
Import workers may crash when trying to log due to the logger not being configured in the context. This PR takes the logger from the `*App` and uses it to initialize the context.
[MM-46928](https://mattermost.atlassian.net/browse/MM-46928)
```release-note
NONE
```
> Initialize the logger for imports

- app/audit.go
- app/platform/config.go
- config/logconfigsrc.go
- config/logconfigsrc_test.go
- config/migrate.go
- config/utils.go
- config/utils_test.go
- model/config.go
- services/telemetry/telemetry.go
This reverts commit 5211d5de157a8b6ba1ac091f1836995bd136a5fc.
PR https://github.com/mattermost/mattermost-server/pull/20954 was expected to not be a breaking change, but indeed did break the plugin RPC layer.  It must be reverted.
NONE
```release-note
NONE
```
> Revert "Allow inline JSON in config.json for advanced logging config (#20954)

- app/notification_push.go
- app/notification_push_test.go
- app/web_hub_test.go
- i18n/en.json
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
- store/timerlayer/timerlayer.go
The server is sending the wrong badge count when CRT is enabled.
When CRT is enabled, we must only consider the root mentions as we also add the thread mentions count to it. This PR fixes the column name to be used in the query while getting unread counts for the user based on whether CRT is enabled/disabled.
https://mattermost.atlassian.net/browse/MM-46333
```release-note
Fixes badge count on mobile when channel/thread is viewed
```
> Badge count fix for push notifications when CRT is enabled

- api4/post.go
- api4/post_test.go
- model/client4.go
- model/post.go
When we move a thread we should receive:
- a post deleted event for the root post
- a posted event for the root post in another channel
- as many posted events as replies in the thread
- as many thread updated events as replies in the thread
```release-note
NONE
```
> Adds api tests for the moveThread endpoint

- model/config.go
> Wrangler config use pointers

- api4/post.go
- api4/post_test.go
- model/config.go
- model/user.go
Adds logic to actually check the wrangler config and apply it to the current user to determine if they should be able to move threads or not.
```release-note
```
> Check wrangler config

- store/sqlstore/post_store.go
This PR simplifies a query to make it more readable (and slightly more performant). The execution of the original and new queries was tested in production for MySQL and locally for Postgres. The times are slightly better in Postgres, while they stay the same for MySQL.
In MySQL, tested in Community, times for the old and new queries are mostly the same:
- Original : 6 s 250 ms (execution: 258 ms, fetching: 5 s 992 ms)
- New      : 6 s 148 ms (execution: 148 ms, fetching: 6 s)
The output from EXPLAIN in Community is also similar for both queries:
- Original:
| id | select_type | table      | partitions | type   | possible_keys          | key                    | key_len | ref                  | rows    | filtered | Extra                 | …
> MM-46105: Simplify posts batch retrieval query

- app/notification_email.go
- shared/mail/mail.go
- shared/mail/mail_test.go
Now, whenever no ```Message-ID``` is passed, smtp config is used for getting hostname and ```Message-ID``` is generated as ```< model.NewRandomString - time.Now() @ hostname >```
Unexported ```SendMail``` function and passed smtp config to it.
Fixes https://github.com/mattermost/mattermost-server/issues/20828
```release-note
Added randomly generated for default message-ID for every outgoing email.
```
> Mm 46416 add default random message

- model/feature_flags.go
for some reason the feature flag seems to have been re-introduced 
this PR removes it form the feature flag model and the default value
[MM-44400](https://mattermost.atlassian.net/browse/MM-44400)
```release-note
NONE
```
> [MM-44400]: removed feature flag for Advanced Text Editor

- app/platform/helper_test.go
- app/platform/service.go
- app/platform/web_hub.go
- app/platform/web_hub_test.go
- app/server.go
We were reading the hubs first (while registering some listeners) and then initializing it with the extra method `platformService.HubStart`, we change it to `platformService.Start` and register config and license listeners so that they are handled together.
```release-note
NONE
```
> fix a data race in the platform service

- app/platform/config.go
- app/platform/service.go
- app/server.go
There was an issue in the app startup sequence:
We initialize the config first then pass it to the platform service. But, disregardless we create a failover config store (we need to create that once it's required) and try to validate it. It didn't fail so far because we either had a valid config as backup or empty one (which is created with valid values). On the community, probably we had an invalid `config.json` somewhere and it made this bug come to surface.
We now moved config store failover logic into platform service.
```release-note
NONE
```
> app/platform: move failover config initialization to platform

- plugin/interface_generator/main.go
- plugin/product_hooks_generated.go
We need to do this to pass the hooked events
to the products.
https://mattermost.atlassian.net/browse/MM-47403
```release-note
NONE
```
> MM-47403: Populate the productHooks field

- config/client.go
- model/config.go
- services/telemetry/telemetry.go
Remove CloudBilling Feature Flag
[MM-29625](https://mattermost.atlassian.net/browse/MM-29625)
```release-note
NONE
```
> MM-29625: Remove CloudBilling Feature Flag

- Makefile
Update prepackaged boards version to v7.4.1
Fixes https://github.com/mattermost/focalboard/issues/3690
```release-note
Update prepackaged boards version to v7.4.1
```
> Update prepackaged boards to v7.4.1

- store/sqlstore/channel_store_categories.go
- store/storetest/channel_store_categories.go
We used to send the categories for teams deleted or not a member of when we use the "exclude" option. This fixes that.
None
```release-note
Get categories with the "exclude" option does not return categories for deleted or teams you are no longer a member.
```
> Do not send categories for teams deleted or not member of

- app/platform/cluster.go
- app/platform/config.go
- app/platform/enterprise.go
- app/platform/helper_test.go
- app/platform/log.go
- app/platform/metrics.go
- app/platform/options.go
- app/platform/service.go
- app/platform/service_test.go
- app/platform/session.go
- app/platform/web_conn.go
- app/platform/web_hub.go
There was a regression in database metrics due to a bug in the server initialization. We need to initialize metrics implementation before database gets initialized. Did some re-arrangement and added a test for this.
https://mattermost.atlassian.net/browse/MM-47468
```release-note
NONE
```
> [MM-47468] Fix store metrics initialization

- Makefile
Update prepackaged boards version to v7.4.2
Fixes https://github.com/mattermost/focalboard/issues/3690
```release-note
Update prepackaged boards version to v7.4.2
```
Closing https://github.com/mattermost/mattermost-server/pull/21375, because it fails from a forked branch.
> Update prepackage boards v7.4.2

- api4/resolver_channel.go
- api4/resolver_channel_test.go
- api4/schema.graphqls
Channel Stats isn't optimized with dataloaders.
And it's a heavy call, therefore clients
can mistakenly call this with multiple channels
and bring down the server.
Since there is no advantage compared to a REST API,
let's just remove it and keep things safe.
```release-note
NONE
```
> GraphQL: Remove channel stats from the API

- store/sqlstore/user_store.go
- store/storetest/user_store.go
This PR applies a bugfix for: role filters aren't currently being applied for [GetProfilesInChannel](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/user_store.go#L705-L733).
https://mattermost.atlassian.net/browse/MM-47230
```release-note
Fixed a bug where role filters weren't being applied to routes doing 'get users in channel'.
```
> [MM-47230] Apply role filters for /get/users in channel

- store/searchlayer/user_layer.go
- store/sqlstore/user_store.go
- store/storetest/user_store.go
There were 2 separate issues here:
1. We were excluding DM/GM channels for user indexing.
Not sure why. This prevented users to be shown as
channel members in autocomplete results in both
Bleve and Elasticsearch.
2. We were incorrectly excluding DM/GM channels
in the query to calculate allowed channels. Fixed that
to include the current channel if it's a DM/GM one.
One catch is that for the correct results to appear,
a re-indexing is required.
https://mattermost.atlassian.net/browse/MM-35036
https://mattermost.atlassian.net/browse/MM-45723
```release-note
Autocompletion results using Elasticsearch or Bleve will
correctly show a user as a channel member in DM/GM channels.
To force this change to appear, a re-indexing will be
necessary.
```
> MM-45723: Include DM/GM channels for user indexing

- model/feature_flags.go
Adds basic support for `MM_FEATUREFLAGS_PEOPLEPRODUCT`
Relates to: 
- #21108
- https://github.com/mattermost/mattermost-webapp/pull/11147
None
```release-note
NONE
```
> add PeopleProduct feature flag

- model/user.go
- model/user_test.go
When logging via openID, if the user email is invalid,
we don't log the invalid email address. This makes
debugging difficult.
https://mattermost.atlassian.net/browse/MM-40690
```release-note
NONE
```
> MM-40690: Populate the error message with email address

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Ensure that `ParentId` column is dropped from the `Posts` table. There is a chance that `ParentId` column is not dropped if a mattermost administrator runs manual queries while upgrading from `5.x` to future versions. To avoid any inconsistencies in the schema, we run the `DROP COLUMN ParentId` query anyway. 
https://mattermost.atlassian.net/browse/MM-46973
```release-note
```
> db/migrations: ensure to drop parentid from posts table

- model/config.go
Instead of blindly setting the initial flag value
to false, we set it to the original plugin setting.
https://mattermost.atlassian.net/browse/MM-47884
```release-note
NONE
```
> MM-47884: Migrate config state from focalboard plugin

- web/handlers.go
This PR is based on https://github.com/mattermost/mattermost-server/pull/21401. Changes specific to it are here: https://github.com/mattermost/mattermost-server/compare/MM-46981_production-mpa...MM-47238_boards-dev-server-url
This makes it so that people who develop MM on a URL other than `http://localhost` can redefine the URL, port, and protocol that the Boards Webpack dev server runs on for MPA development. Without it sets, it still defaults to running the dev server on `http://localhost:9006`
https://mattermost.atlassian.net/browse/MM-47238
https://github.com/mattermost/mattermost-server/pull/21401
https://github.com/mattermost/focalboard/pull/4026
https://github.com/mattermost/mattermost-webapp/pull/11381
```release-note
NONE
```
> MM-47238 Add MM_BOARDS_DEV_SERVER_URL environment variable for MPA

- app/platform/service.go
The `metricsInterfaceFn` was being used once the `metrics` package initialized in the EE build. We also need to check if the metrics interface is set beforehand to run `metricsInterfaceFn` function.
The reason it didn't get caught on CI still unknown to me. Because we have `EE` builds and this should've cause tests with EE to fail. Something to look at. cc @phoinixgrr 
https://mattermost.atlassian.net/browse/MM-47635
```release-note
NONE
```
> platform/service: fix a flaky test for metrics

- app/slashcommands/auto_channels.go
- app/slashcommands/auto_posts.go
- app/slashcommands/auto_users.go
- app/slashcommands/command_loadtest.go
- model/post.go
- model/user.go
- store/sqlstore/team_store.go
Adds a timestamp parameter to the test data slash commands, so that historical test data can be generated. Technically, test data in the future can also be generated. I don't think it's necessary to check this because any accidentally generated data can be manually deleted.
The commands now use named parameters. The parameters are as follows:
- `range=<min>,<max>` or `range=<num>` for the number of data to generate
- `time=<timestamp>` for the Unix timestamp representing the time of the data
- `images=<num>` for the number of images to add to posts
- `u=@<username>` or `u=<username>` for the user to create DMs with
The parameters are easy to rename if we don't like these names. 
Additionally, the `/test dms` command now creates a number of random-text DM messages between the current user …
> [MM-44336] Add timestamp parameter to test data slash commands

- api4/config.go
- app/plugin.go
As discussed in [this thread](https://community.mattermost.com/core/pl/ng8c5wstttykiytwk1wfdwnbja), it'd make a bit more sense to use a 400 error here.
```release-note
NONE
```
> Change status code to 400 when attempting to enable Boards plugin with product enabled

- jobs/base_schedulers.go
- jobs/schedulers_test.go
There can be a case where if a config change happened
at the same time for a large number of installations,
it can trigger a job to re-run all at the same time,
therefore causing a thundering herd issue.
To prevent this, we add a jitter.
https://mattermost.atlassian.net/browse/MM-47736
```release-note
NONE
```
> MM-47736: Add jitter to job scheduler run time

- api4/user_test.go
After looking at this for some time, I don't see
any way for this test to fail other than model.NewId
returning the same value for BasicUser and BasicUser2.
I think edge cases like this can exist from time to time.
Nothing much we can do about it.
https://mattermost.atlassian.net/browse/MM-46450
```release-note
NONE
```
> MM-46450: Enable skipped test

- .circleci/config.yml
When copy and pasting from the untagged-build pipeline to the release-build one, I didn't realize that the branch filters were inverted, so we weren't building the web app files for Boards before trying to copy them into the server bundle
#21401
https://github.com/mattermost/enterprise/pull/1281
```release-note
NONE
```
> Actually build Boards product files in release builds

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Cherry pick  of #21493 into `release-7.1` branch.
```release-note
```
> Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.1

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Cherry pick  of #21493 into `release-7.2` branch.
```release-note
```
> Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.2

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Cherry pick  of #21493 into `release-7.5` branch.
```release-note
```
> Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.5

- app/platform/goroutines.go
- app/platform/service.go
- app/platform/service_test.go
- app/server.go
We need to wait for goroutines after we stop the web hub. Let me know if you see testing adds value to this as now this is guarded by being a private method. There should be no way to mix the order of the calls anymore.
https://mattermost.atlassian.net/browse/MM-47535
```release-note
NONE
```
> app/platform: fix an issue about accessing to a closed db on shutdown

- app/post.go
- app/post_test.go
Fix error in case of no cloud limits.
JIRA - https://mattermost.atlassian.net/browse/MM-47716
```release-note
NONE
```
> [MM-47716] Fix error in case of no cloud limits

- app/import_functions.go
Depending on the database config teams, users and channels might be matched case insensitive on import. That can lead to crashes when the casing in the import file doesn't 100% match the one in the database. This PR fixes the problem by making the match case insensitive in the server as well (for the import).
[MM-47795](https://mattermost.atlassian.net/browse/MM-47795)
```release-note
NONE
```
> MM-47795 Match teams, channels, and users case insensitively on import

- api4/resolver_channel_test.go
- app/channel.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
In the scenario of getting channels with cursor at the last channel, no error should be thrown. Instead it should return empty array of channels to indicate no more channels are left for pagination.
Discussion https://community.mattermost.com/core/pl/ijqe8oanc7nt7k6hyis8hfk89c
```release-note
NONE
```
> Return empty list of channels when requested more channels at the end of cursor

- store/sqlstore/post_store.go
When we use `getPostSince`, we want to know what posts have been deleted, to properly remove them while doing the synchronization.
The way it was implemented, was omitting the deleted posts, so the posts never would get deleted on the client.
None
```release-note
`getPostSince` properly return deleted posts when CRT is enabled.
```
> Send deleted posts on getPostSince when collapsed threads is enabled

- api4/cloud.go
- api4/config.go
- api4/license.go
- api4/team.go
- api4/upload.go
- api4/user.go
- app/file.go
- app/integrations.go
- app/login.go
- app/platform/license.go
- app/plugin.go
- app/post.go
- app/server.go
- config/client.go
- model/license.go
- model/license_test.go
- services/telemetry/telemetry.go
- web/context.go
- web/handlers.go
Invalidates cloud caches when a new license is loaded, to aid in plan change hardening.
related change: https://github.com/mattermost/enterprise/pull/1289
```release-note
None
```
> Invalidate cloud caches when a new license is loaded

- app/plugin_api.go
- app/plugin_api_tests/test_bots_plugin/main.go
In https://github.com/mattermost/mattermost-server/pull/20521 an `EnsureBotUser` endpoint was added to the pluginapi. In order to mirror the existing functionality of the `github.com/mattermost/mattermost-plugin-api` `EnsureBot` method, the `OwnderId` should always be set to the pluginID. Otherwise plugins updating to a newer version of `github.com/mattermost/mattermost-plugin-api` will error on startup. 
https://mattermost.atlassian.net/browse/MM-48058
```release-note
Set OwnerId for bots created via EnsureBotUser
```
> [MM-48058] Set OwnerId for bots created via EnsureBotUser

- .circleci/config.yml
golangci has terrible error messages
if the code doesn't compile or there
are some basic errors. Doing a go vet
check is a quick way to eliminate any
head scratching.
```release-note
NONE
```
> Run go vet before golangci

- jobs/import_process/worker.go
- shared/filestore/s3store.go
- shared/filestore/s3store_test.go
Due to the size of import archives, the reader may run into timeouts when importing from an S3 file. This PR adds functionality to cancel the timeout for S3 readers. Caveat: Unreasonably low timeouts may still cancel the request before it's passed back to the import job.
[MM-46610](https://mattermost.atlassian.net/browse/MM-46610)
```release-note
NONE
```
> MM-46610 Ignore the reader timeout for S3 files when importing

- store/sqlstore/thread_store.go
As part of the ongoing Threads Everywhere initiative, I found myself stumbling over duplicate implementations of the `JoinedThread` helper struct, and wanted to pre-emptively refactor before making further changes in this area.
Note that the existing unit test coverage already encompasses these changes.
None.
```release-note
NONE
```
> Refactor common JoinThread helper struct

- app/export.go
- app/export_converters.go
- app/export_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/timerlayer/timerlayer.go
Favorited direct channels were missing from the export file. This PR adds them. The import part was already implemented.
[MM-47171](https://mattermost.atlassian.net/browse/MM-47171)
```release-note
Exports now contain favorited direct channels
```
> MM-47171 Export direct channel favorites

- app/channel.go
- store/sqlstore/channel_store.go
The channel store code doesn't check for the error when retrieving the info for an existing channel. Attempting to create an already existing channel may return invalid data. This PR returns a different error in that case so the calling code doesn't assume it got the info for the existing channel.
```release-note
NONE
```
> Fix unchecked request when saving channel

- api4/post_test.go
- api4/user.go
- app/app_iface.go
- app/channel.go
- app/channel_test.go
- app/notification.go
- app/notification_test.go
- app/opentracing/opentracing_layer.go
- app/post_test.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/mocks/ThreadStore.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
This PR simplifies getThreadForUser method by getting rid of teamID
Fixes https://mattermost.atlassian.net/browse/MM-47998
```release-note
NONE
```
> [MM-47998] Simplify get thread for user

- Makefile
Update pre-package boards to v7.5.0
Fixes https://github.com/mattermost/focalboard/issues/4019
```release-note
Update prepackaged boards version to v7.5.0
```
> Update pre-package boards to v7.5.0

- model/feature_flags.go
remove deprecated guided channel creation ff
https://mattermost.atlassian.net/browse/MM-47865
https://github.com/mattermost/mattermost-webapp/pull/11551
```release-note
NONE
```
> MM-47865 - remove deprecated guided channel creation ff

- api4/license_test.go
Skip flaky test.
Ticket to fix it assigned to Suite Users team, who created it [last year](https://github.com/mattermost/mattermost-server/pull/17359): https://mattermost.atlassian.net/browse/MM-48416
--
```release-note
NONE
```
> Skip flaky test TestRequestTrialLicense/trial_license_user_count_less_than_current_users

- api4/channel_test.go
- app/channel.go
Creating the post in a separate goroutine would create a race condition
because that method also calls GetChannel. This can cause a bug
if the cache was wiped before the the other goroutine would get
a chance to update the cache. And if that happens, then
it would populate the cache with the old value.
Pseudo-code
```
func deleteChannel() {
go func() {
getFromCache()
}()
updateDB()
wipeCache() // a
}
func getFromCache() {
err := checkCache()
if err == ErrNotFound {
getFromDB() // x
updateCache() // y
}
}
func Test() {
deleteChannel()
getFromCache()
}
```
If the sequence of events happen like
- x
- a
- y
Then the getFromCache() call later will get the wrong
value from cache.
The fix is to make the call synchronous.
https://mattermost.atlassian.net/browse/MM-47465
Special thanks to @noxer …
> MM-47465: Fix flaky TestDeleteChannel

- api4/upload.go
- api4/upload_test.go
- app/plugin_api.go
- app/plugin_api_test.go
- app/upload.go
- app/upload_test.go
- i18n/en.json
- plugin/api.go
- plugin/api_timer_layer_generated.go
- plugin/client_rpc.go
- plugin/client_rpc_generated.go
- plugin/interface_generator/main.go
- plugin/plugintest/api.go
PR exposes the existing resumable uploads API to the plugins side. This change is currently required by Calls as we need some extra flexibility to deal with recording files, such as being able to upload into any channel (DMs included) and potentially bypassing the configured max file size (to be confirmed).
I am testing a bit locally that the uploaded data is properly buffered and no unexpected allocation happens due to having to go through the RPC layer. Everything is looking good so far.
@amyblais This PR is a requirement for the upcoming Calls release so looking to include it in 7.6
https://mattermost.atlassian.net/browse/MM-48523
```release-note
Exposed the resumable uploads API to plugins.
```
> [MM-48523] Expose resumable uploads API to plugins

- app/file.go
- app/file_test.go
- app/post.go
- app/post_test.go
The logic for ComputeLastAccessiblePostTime was not clearing the System store value in the event the limits were 0 - this causes the value to not be cleared after an upgrade from Starter to Professional, keeping the history limit. 
This PR will remove both the LastAccessiblePostTime and LastAccessibleFileTime if the limits for each are nil/0  (with the way LastAccessibleFileTime was implemented it's technically not a problem as it will store CreateAt `0` - but added the delete so both implementations are similar) 
https://mattermost.atlassian.net/browse/MM-48560
```release-note
None
```
> [MM-48560] LastAccessiblePostTime not removed on upgrade to Professional

- .github/workflows/codeql-analysis.yml
- build/release.mk
We are using CodeQL Autobuild which is by default running `make` to create a build for Mattermost server. The challenge is that our default target for `make` is running `make run`, resulting CodeQL to be in an infinite loop as the process is running. We may want to consider changing that, as `make` default target is usually to create a build vs running it.
https://mattermost.atlassian.net/browse/CLD-4570
```release-note
NONE
```
> [CLD-4570] Disable CodeQL Auto Build

- store/storetest/file_info_store.go
A test, added [in this PR](https://github.com/mattermost/mattermost-server/pull/20703), was found to be flaky in [this commit](https://github.com/mattermost/mattermost-server/commit/a05dd722edd0e5eaad6c5a3a90b92cfa113a3dc4) to the master branch. The relevant error is:
```
=== RUN   TestFileInfoStore/PostgreSQL/GetUptoNSizeFileTime
file_info_store.go:870: 
Error Trace:	/mattermost/mattermost-server/store/sqlstore/file_info_store.go:870
/mattermost/mattermost-server/store/sqlstore/file_info_store.go:35
Error:      	Not equal: 
expected: 1669294161253
actual  : 1669294151252
Test:       	TestFileInfoStore/PostgreSQL/GetUptoNSizeFileTime
```
This PR skips it until https://mattermost.atlassian.net/browse/MM-48627, assigned to the Channels team, is fixed.
--
```release-note
NONE
```
> Skip flaky test GetUptoNSizeFileTime

- app/cluster_handlers.go
- plugin/environment.go
This PR updates the `HooksForPlugin` function to return product registered hooks as well, and allows for clustered websocket messages to be processed.
```release-note
* Adds support for product websocket messages on high availability instances.
```
> Adds support for clustered websocket messages for products

- docker-compose.yaml
This PR includes the `boards` product on the `haserver` targets.
```release-note
NONE
```
> Update haserver docker-compose to include boards as a product

- app/team.go
- app/team_test.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
- store/timerlayer/timerlayer.go
Fixes a cache invalidation bug that occurs when applying a team scheme.
https://mattermost.atlassian.net/browse/MM-48181
```release-note
Fixes a permissions caching bug when applying a team scheme.
```
> MM-48181: Invalidate cache to reflect permissions changes from a team scheme.

- api4/group.go
- config/client_test.go
- model/feature_flags.go
Removes CustomGroups feature flag.
https://mattermost.atlassian.net/browse/MM-47936
https://github.com/mattermost/mattermost-webapp/pull/11644
```release-note
Removed the CustomGroups feature flag.
```
> MM-47936: Removes CustomGroups feature flag.

- .circleci/config.yml
Boards team would like CI fetches of boards repo to use the `rolling-stable` branch.  This branch will be updated every few days from main, once the latest batch of PR's are tested.  
Similar PRs are being issued for enterprise, and the gitlab CI repos.
https://mattermost.atlassian.net/browse/CLD-4604
```release-note
NONE
```
> Use `rolling-stable` branch when fetching focalboard repo

- app/email/email_batching.go
- app/email/notification_email.go
- app/email/notification_email_test.go
- app/notification_email.go
Some recent additions to single notification email renders weren't applied to batch email, causing them to fail. This PR patches batch notification events with `MessageAttachments`.
https://mattermost.atlassian.net/browse/MM-48521
```release-note
Fixed bug where batch notifications failed while rendering.
```
> [MM-48521] Fix for batch notification email not rendering properly

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Cherry pick  of #21493 into `release-7.4` branch.
```release-note
```
> Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.4

- db/migrations/migrations.list
- db/migrations/mysql/000095_remove_posts_parentid.down.sql
- db/migrations/mysql/000095_remove_posts_parentid.up.sql
- db/migrations/postgres/000095_remove_posts_parentid.down.sql
- db/migrations/postgres/000095_remove_posts_parentid.up.sql
Cherry pick  of #21493 into `release-7.3` branch.
```release-note
```
> Cherry-pick of db/migrations: ensure to drop parentid from posts table (#21493) into release-7.3

- app/channel.go
- app/channels.go
- app/file.go
- app/login.go
- app/plugin.go
- app/post.go
- app/reaction.go
- app/team.go
- app/upload.go
- app/user.go
It seems like on of the recent MPA refactor PR (#21772) caused a data race in a test as following test log. 
Also while checking on this I realized that I missed a huge point, if you disable the plugins, product hooks wouldn't work. I also added that bit as the second commit.
```
==================
WARNING: DATA RACE
Write at 0x00c009b22260 by goroutine 571:
github.com/mattermost/mattermost-server/v6/app.(*Channels).ShutDownPlugins()
/mattermost/mattermost-server/app/plugin.go:395 +0x1f9
github.com/mattermost/mattermost-server/v6/app.(*Channels).Stop()
/mattermost/mattermost-server/app/channels.go:285 +0x44
github.com/mattermost/mattermost-server/v6/app.(*Server).Shutdown()
/mattermost/mattermost-server/app/server.go:748 +0x14c8
github.com/mattermost/mattermost-server/v6/api4.(*TestHelper) …
```
> app: avoid plugin env check for RunMultiHook and use pluginslock while accessing plugin env

- app/server.go
- model/config.go
- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
We didn't use to handle the error returned from the Enqueue
method. We fix that.
Additionally, we add a verbosity flag that can allow us to
look into verbose logs from the rudder client. This can
help us to debug issues regarding telemetry not being sent.
https://mattermost.atlassian.net/browse/MM-48651
```release-note
NONE
```
> MM-48651: Log error while queuing telemetry

- app/user.go
The `SendSubscriptionHistoryEvent` function will now be called in a Go routine, so that it does not stall the UI when a new user is created.
Also related to this PR: https://github.com/mattermost/enterprise/pull/1317
https://mattermost.atlassian.net/browse/MM-48649
```release-note
NONE
```
> [MM-48649]: Call the SendSubscriptionHistoryEvent function in a GO routine

- app/platform/config.go
- app/platform/config_test.go
- app/platform/service.go
- app/platform/service_test.go
It seems like there are no checks if a metrics server restart is required or not.
https://mattermost.atlassian.net/browse/MM-48947
```release-note
Bugfix on metrics server restart when there is a config change.
```
> [MM-48947] app/platform: do not restart metrics on every config save

- api4/user.go
- api4/user_local.go
- api4/user_test.go
- i18n/en.json
- model/client4.go
- model/role.go
In `getUsers` API handler, we currently only check if parameters `role, roles, channelRoles, teamRoles` are checked for alphanumeric characters and `_`, but not for validity.
The endpoint returns empty result, while it should return 4xx. This PR adds validity checks to these parameters.
https://mattermost.atlassian.net/browse/MM-47378
```release-note
Added validity checks for role related parameters in GET /users
```
> [MM-47378] Respond with bad requests for wrong query parameters 'roles' in getUsers

- app/team_test.go
There is a recent flaky test [failing with a data race](https://app.circleci.com/pipelines/github/mattermost/mattermost-server/39336/workflows/13f67056-9a30-409f-8a4e-ce8066e4c3b4/jobs/356399), possibly introduced by #21836. This PR skips the test until https://mattermost.atlassian.net/browse/MM-48973 is fixed.
--
```release-note
NONE
```
> Skip "block user by domain but allow bot" test

- app/plugin_db_driver.go
- app/plugin_db_driver_test.go
If a timeout is missing, this goroutine waits indefinitely trying
to get a connection. Leading to a goroutine accumulation in a scenario
where the DB is somehow not release connections.
https://mattermost.atlassian.net/browse/MM-48984
```release-note
NONE
```
> MM-48984: Add missing timeout while creating a connection

- web/static.go
- web/web_test.go
As discussed in the threads linked in the accompanying Jira ticket, module federation introduces `remote_entry.js` files for each federated container (currently the web app and the Boards product) that contain the locations of each chunk of the JS bundle and where to find them. Each version of those files has a unique name which means they can be cached, but the names of the `remote_entry.js` files are non-unique, so we can't cache them.
I looked at possibly giving them unique names, but given that the different entry points need help finding each other, it doesn't seem like we can do that right now. Best I can tell, it's intended that we don't cache these files since they're very small anyway (~8kb).
https://mattermost.atlassian.net/browse/MM-48924
```release-note
Prevented browsers and …
```
> MM-48924 Don't cache remote_entry.js files

- model/feature_flags.go
Sets global drafts feature flag to true.
https://mattermost.atlassian.net/browse/MM-48622
```release-note
NONE
```
> [MM-48622] Set Global Drafts Feature Flag to True

- api4/remote_cluster.go
- api4/upload.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/plugin_api.go
- app/upload.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/upload_session_store.go
- store/store.go
- store/storetest/mocks/UploadSessionStore.go
- store/storetest/upload_session_store.go
- store/timerlayer/timerlayer.go
PR fixes a potential read-after-write issue when uploading data through the new resumable uploads API.
The main problem is that in `UploadData` (both at [api](https://github.com/mattermost/mattermost-server/blob/731c81cd108973d5515a61e299b60956c646065f/api4/upload.go#L126) and [app](https://github.com/mattermost/mattermost-server/blob/731c81cd108973d5515a61e299b60956c646065f/app/upload.go#L205) and [plugin](https://github.com/mattermost/mattermost-plugin-calls/blob/0796721cf5ccb44232b3f1d02ec3a6bf0b00bace/server/bot_api.go#L88) levels) we fetch the upload session from store and there's a chance this could be missing still since the method is likely to be called right after a call to `CreateUploadSession`.
https://mattermost.atlassian.net/browse/MM-48946
```release-note
Fixed a potential …
```
> [MM-48946] Fix read after write issue when uploading data

- app/channels.go
- product/api.go
We don't need to wait plugins environment to exist to register hooks. It's also guaranteed to Channels product initialized first. So, other product can safely call hooks service in their initialized
```release-note
NONE
```
> product/hooks: hooks service no longer requires channels service start

- api4/user.go
- api4/user_test.go
- app/app_iface.go
- app/group.go
- app/opentracing/opentracing_layer.go
- model/client4.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
- store/timerlayer/timerlayer.go
Adds a new `sort` parameter to the endpoint `/users?in_group=<groupid>`. The parameter can have value `sort=display_name` which will return group members in order of display name, which is determined by the logged-in user's display name setting.
Intended to be used for this feature: [Jira ticket](https://mattermost.atlassian.net/browse/MM-44347)
```release-note
Added an allowed value sort=display_name to GET /api/v4/users?in_group=<groupid>.
```
> [MM-44347] Add parameter to return group members in order of display name

- app/file.go
- app/upload.go
This is a sibling PR to https://github.com/mattermost/mattermost-server/pull/21854. I discovered two more instances of go-routines potentially getting stuck when the `FileWriter` experiences an error.
[MM-49172](https://mattermost.atlassian.net/browse/MM-49172)
```release-note
NONE
```
> [MM-49172] Close pipes on file writer error

- api4/post.go
- model/post.go
Add implementation of the auditable interface for `PostPatch`. 
https://mattermost.atlassian.net/browse/MM-49170
```release-note
NONE
```
> [MM-49170] Implement Auditable Interface for Patch Post Struct

- store/sqlstore/store.go
Embedded FS's use the forward slash `/` as a path separator. So the use of `filepath` may cause errors on platforms that use another path separator (like Windows `\`).
```release-note
NONE
```
> Use path rather than filepath for embedded files

- store/sqlstore/channel_store.go
`UrgentMentionCount` does not have a default values, so `COALESCE` has to be used.
`SELECT * FROM ChannelMembers` fails for the above reason. This commit `SELECT`s each and every column from `ChannelMembers` instead.
https://mattermost.atlassian.net/browse/MM-49077
```release-note
NONE
```
> MM-49077: fixes errors in migration job

- config/client.go
We want to set CWSURL for all installations now, not just cloud ones. Self-hosted ones will need this info in the client for things like contact us links.
https://mattermost.atlassian.net/browse/MM-49258 / https://docs.google.com/document/d/1TDpO4woW3rlUxGGwSSWE0j4F0nNKeO0LpzmQs9eNZ4Y/edit#
-->
```release-note
NONE
```
> always set CWSURL in client config

- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/compliance_store.go
- store/sqlstore/sqlx_wrapper.go
- store/store.go
- store/storetest/compliance_store.go
- store/storetest/mocks/ComplianceStore.go
- store/timerlayer/timerlayer.go
We accept a context that can cancel the query.
This allows us to exit a job faster.
```release-note
Compliance export job can now cancel the SQL query
execution during server shutdown which will allow
the job to exit faster.
```
> MM-49354: Make compliance export query cancellable

- product/api.go
This PR adds `DuplicateBoard` to the Boards service API.
focalboard PR: 
NONE
```release-note
NONE
```
> Add DuplicateBoard to service API

- api4/drafts.go
This log is continuously spamming our community server
and I see it all the time in my dev environment.
Let's remove this to keep the logs clean.
```release-note
NONE
```
> Remove unnecessary debug log

- api4/license.go
- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/true_up.go
Noticed a few additional things we might want:
* share the get-or-create review status code between endpoints
* The API handler code is getting pretty long. It's standard to keep business logic out of the API layer. Since you need to access multiple data sources, we can't cleanly put it in a single store method, so I think the typical way to do this is to add an app method.
* Noticed that the payload sent by telemetry was the flattened object, but the profile written to the client for the case of download was a json version of the structured profile. I'm thinking we should send the same format to the client so that its easier to ingest into CWS once we get there.
```release-note
NONE
```
> dry up some code. Move other code to app layer

- config/client.go
- model/hosted_customer.go
Add email to response so that other admins can know if someone else is already trying to do a self-hosted purchase, and if so, don't interfere with it.
See also:
* https://github.com/mattermost/enterprise/pull/1350
* https://github.com/mattermost/mattermost-webapp/pull/11879
https://mattermost.atlassian.net/browse/MM-49258
```release-note
NONE
```
> Mm 49258 - Inform admins trying to self-hosted purchase who the email listed on the JWT claim is

- app/migrations.go
- app/platform/metrics.go
- app/server.go
- services/upgrader/upgrader_linux.go
- shared/mlog/global.go
- shared/mlog/global_test.go
Critical wasn't added in the StdLevels slice
and due to that mlog.Critical wasn't printing anything.
This was a complete blindspot that was missed.
We have removed all references to mlog.Critical in the codebase
and pointed Critical to be Fatal in the library.
In v8, we will remove Critical altogether.
```release-note
Servers with an encrypted key will throw an error
during startup now.
```
> MM-48345: Fix Critical level logging

- model/utils.go
- model/utils_test.go
Remove the word "`<untranslated>`" from appearing
in the logs.
```release-note
NONE
```
> Clean untranslated logs

- app/post_test.go
- app/user.go
- app/user_test.go
We were incorrectly returning by checking
for `err != nil` when a 404 error was included
in that condition.
```release-note
NONE
```
> Return 404 when thread membership not found

- .circleci/config.yml
We are now going to pull target branch for focalboard. The only problem here is that the build started before opening the PR will checkout `rolling-stable` branch but once it's re-run it will get the target branch for the PR.
https://mattermost.atlassian.net/browse/MM-49372
```release-note
NONE
```
[MM-49372]: https://mattermost.atlassian.net/browse/MM-49372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> cicleci: add ability use target branch for pulling focalboard

- app/server.go
- config/client.go
- config/client_test.go
- model/license.go
- model/license_test.go
Manual cherry pick of #21882 onto `release-7.7`
cc/ @amyblais 
```release-note
NONE
```
> Manual cherry pick of #21882

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
https://mattermost.atlassian.net/browse/MM-49485
```release-note
Boards will be served as an in-built product from
within Mattermost server instead of a plugin.
If you want to disable this, please set the
MM_FEATUREFLAGS_BoardsProduct env var to "false" (without
the quotes).
In this mode, the boards plugin will remain disabled.
```
> MM-49485: Set BoardsProduct FF to on by default

- app/migrations.go
- app/platform/metrics.go
- app/server.go
- services/upgrader/upgrader_linux.go
- shared/mlog/global.go
- shared/mlog/global_test.go
Critical wasn't added in the StdLevels slice
and due to that mlog.Critical wasn't printing anything.
This was a complete blindspot that was missed.
We have removed all references to mlog.Critical in the codebase
and pointed Critical to be Fatal in the library.
In v8, we will remove Critical altogether.
```release-note
Servers with an encrypted key will throw an error
during startup now.
```
> Cherry-pick: MM-48345: Fix Critical level logging (#21952)

- app/post_test.go
- store/sqlstore/thread_store.go
We return a store error always to be handled correctly
at the app layer.
https://mattermost.atlassian.net/browse/MM-49546
```release-note
NONE
```
> MM-49546: Sentry crash: fix nil pointer dereference

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
https://mattermost.atlassian.net/browse/MM-49485
```release-note
Boards will be served as an in-built product from
within Mattermost server instead of a plugin.
If you want to disable this, please set the
MM_FEATUREFLAGS_BoardsProduct env var to "false" (without
the quotes).
In this mode, the boards plugin will remain disabled.
```
> Cherry-pick: MM-49485: Set BoardsProduct FF to on by default (#22006)

- api4/channel_category_test.go
At that time, it was reported that this test was failing. However, it still passes even by checking both the server and enterprise to commits before skipping the test. Any code related to that functionality didn't have any change that could affect it. It was probably a plugin or a setup issue at that time that affected it, and it looks ok now to re-enable it.
https://mattermost.atlassian.net/browse/MM-42652
```release-note
NONE
```
[MM-42652]: https://mattermost.atlassian.net/browse/MM-42652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-42652] Re-enable test

- app/post_test.go
- store/sqlstore/thread_store.go
Cherry pick of #22018 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #22018

- app/app_iface.go
- app/export.go
- app/export_test.go
- app/opentracing/opentracing_layer.go
- cmd/mattermost/commands/export.go
- jobs/base_workers.go
- jobs/export_process/worker.go
If a bulk export is triggered via a job, then
we update the metadata field of the job as it
progresses through the records.
https://mattermost.atlassian.net/browse/MM-49374
```release-note
Now you can monitor the progress of the bulk export job
via its metadata field. It is available at
`mmctl export job show <jobID>`.
```
[MM-49374]: https://mattermost.atlassian.net/browse/MM-49374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-49374: Update job metadata for bulk export

- config/client.go
We're already writing that information as part of the Makefile, but this will expose it to the frontend like it does for the build hashes of the server and enterprise repos
```release-note
Added Boards build information to client config
```
> Add Boards build information to client config

- app/file.go
- shared/filestore/filesstore.go
This PR introduces a new convenience function to disable filestore write timeouts without having to manually define and assert the interface. Instead we can use `filestore.TryWriteFileContext` which does the assertion for us.
[MM-49083](https://mattermost.atlassian.net/browse/MM-49083)
```release-note
NONE
```
[MM-49083]: https://mattermost.atlassian.net/browse/MM-49083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-49083 Disable write timeouts for exports

- app/preference.go
- model/config.go
- services/telemetry/telemetry.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
- store/timerlayer/timerlayer.go
Adds a limit when getting user preferences to avoid bad actors slowing down the database when fetching their preferences.
https://mattermost.atlassian.net/browse/MM-46579
```release-note
Adds a limit when getting user preferences.
```
> [MM-46579] Add a limit for preferences

- app/post.go
- i18n/en.json
Previously, when trying to move a thread to a group message or direct message, it results in an error. This is because the target channel (DM/ group message) didn't have a teamID and the `GetTeam` function fails. 
I've moved the call to `GetTeam` into an if statement that only executes when the target channel has a teamID. This means that any attempts to move a thread to a direct/group message can skip the `GetTeam` function and the thread can be moved.
https://mattermost.atlassian.net/browse/MM-48403
```release-note
NONE
```
> [MM 48403]: Allow Wrangler to work for DMs/ Group messages

- app/plugin.go
We disable the plugin now at a higher level
which goes through all the layers correctly.
Initially, it was trying to extract the plugin,
failing, and removing the local installation
as well, causing confusion.
https://mattermost.atlassian.net/browse/MM-49658
```release-note
NONE
```
> MM-49658: Correctly disable plugin in product mode

- app/platform/config.go
- app/platform/config_test.go
Bots may maintain sessions during the initial setup of the server. This throws off `IsFirstUserAccount` and prevents the creation of the initial admin account.
[MM-49720](https://mattermost.atlassian.net/browse/MM-49720)
```release-note
Fixed an issue that prevented the creation of the initial admin user for new servers
```
[MM-49720]: https://mattermost.atlassian.net/browse/MM-49720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-49720 Remove the check for active sessions in IsFirstUserAccount

- app/email/email.go
- i18n/de.json
- i18n/en.json
- i18n/en_AU.json
- i18n/es.json
- i18n/hu.json
- i18n/ja.json
- i18n/nl.json
- i18n/pl.json
- i18n/ru.json
- i18n/sv.json
- i18n/tr.json
As a part of the [Delinquency Automation Feature](https://mattermost.atlassian.net/browse/MM-43398), the mention of boards and integrations limits, as well as "Cloud Starter" on delinquency emails should be removed or replaced.
Text Changes:
- Board Limits: `Removed`
- Integration Limits: `Removed`
- Cloud Starter: `Replaced: "Cloud Free"`
[MM-49681](https://mattermost.atlassian.net/browse/MM-49681)
```release-note
NONE
```
[MM-49681]: https://mattermost.atlassian.net/browse/MM-49681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-49681 - Remove mentions of boards and integrations limits on delinquency emails, and replace remaining "Cloud Starter" text with "Cloud Free" text.

- store/sqlstore/channel_store.go
In order to use timezone names, which we're using as a parameter to the `CONVERT_TZ` with MySQL, the database needs to have a matching value in the `mysql.time_zone_name` table. I didn't realize when I originally added the query that MySQL does not populate that table by default. It must be [populated on Linux](https://dev.mysql.com/doc/refman/8.0/en/time-zone-support.html#time-zone-installation) with something like `mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql` or windows using another documented method.
If the current user's timezone is not present in the `time_zone_name` table then [they were seeing a blank Top Channels widget](https://community.mattermost.com/core/pl/c7ewitjkain6tci1qqd5z5gtuc).
This fixes that so that if the timezone name isn't present they'll at …
> Handles an empty mysql.time_zone_name table.

- app/platform/shared_channel_notifier.go
- app/platform/shared_channel_notifier_test.go
We were trying to dereference without a nil check first.
https://mattermost.atlassian.net/browse/MM-49551
```release-note
NONE
```
> MM-49551: Check if RemoteId is nil for participant

- app/channel.go
- app/channels.go
- app/server.go
- product/api.go
This PR adds `GetDirectChannelOrCreate` to the product API for Channels.  This is needed to fix a bug in Boards.  See https://github.com/mattermost/focalboard/pull/4496
https://mattermost.atlassian.net/browse/MM-49752
```release-note
NONE
```
> Add `GetDirectChannelOrCreate` to product API

- api4/hosted_customer.go
If cloud interface reports upstream is off, notify the web client of the same so that it can open a new tab instead of showing airgapped modal.
https://mattermost.atlassian.net/browse/MM-49772
Supports https://github.com/mattermost/mattermost-webapp/pull/12046
```release-note
NONE
```
> if cloud interface reports upstream is off, notify the web client

- .gitlab-ci.yml
https://mattermost.atlassian.net/browse/MM-49703
```release-note
NONE
```
> MM-49703: Bump Gitlab CI to 1.19

- store/sqlstore/store_test.go
The AssertExpectations was being called after the store
was closed. To fix it we move it to the last line.
https://mattermost.atlassian.net/browse/MM-49604
```release-note
NONE
```
> MM-49604: Fix race condition in test

- app/post_acknowledgements.go
- app/post_acknowledgements_test.go
- store/sqlstore/post_acknowledgements_store.go
- store/storetest/post_acknowledgements_store.go
GetPostsSince returns posts updated after a user requested date. If a user acknowledges a post the post's update at won't change thus not getting that post returned from GetPostsSince. This is troublesome particularly for the mobile client since it relies a lot to GetPostsSince for keeping the data up to date.
This commit updates the post's update_at when a user acknowledges/un-acknowledges a post fixing this way the issue above.
https://mattermost.atlassian.net/browse/MM-49845
```release-note
NONE
```
> MM-49845: fixes acknowledgements in getpostsince

- api4/config.go
- api4/team_test.go
- i18n/en.json
When a config like the default server translation was changed, there was no action taken to update the server until it was reinitialized after a full server restart, which is rare for most systems.
https://mattermost.atlassian.net/browse/MM-49265
- Has webapp changes: https://github.com/mattermost/mattermost-webapp/pull/12044
```release-note
Fixed new teams to use the updated translation for default channels after config change.
```
[MM-49265]: https://mattermost.atlassian.net/browse/MM-49265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-49265] Update translations when config is changed

- cmd/mattermost/commands/import.go
The logger was not properly initialized for bulk import from the mattermost CLI, We now initialize the logger.
[MM-49959](https://mattermost.atlassian.net/browse/MM-49959) and https://github.com/mattermost/mattermost-server/issues/22142
```release-note
NONE
```
[MM-49959]: https://mattermost.atlassian.net/browse/MM-49959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-49959] Initialize the logger for CLI imports

- api4/work_templates.go
- app/worktemplates/model.go
- app/worktemplates/model_test.go
- i18n/en.json
This PR ensures that we do not let users create private playbooks if the server's license is not enterprise or E20.
A PR will come later in the webapp to disable the "private" option if the server does not hold an E20 license.
https://mattermost.atlassian.net/browse/MM-50007
```release-note
NONE
```
> [MM-50007] WorkTemplate: disallow creating private playbook without an enterprise license

- app/platform/web_hub_test.go
- model/websocket_message.go
It seems that are omitting ContainsSanitizedData, and ContainsSensitiveData variables in WebsocketBroadcast. This created a bug in cluster mode, where we where sending duplicate events to users when normally they would have access to only one of those.
https://mattermost.atlassian.net/browse/MM-49048
```release-note
Fixed an issue where duplicate `post_deleted`, and `user_updated` events would get sent to users when in cluster
```
> MM-49048: do not omit needed wsbroadcast vars

- api4/plugin.go
Plugins are no longer in beta or marked as experimental. The codebase should reflect that.
https://mattermost.atlassian.net/browse/MM-49932
```release-note
NONE
```
> [MM-49932] Remove experimental warning about plugins

- api4/channel_category_test.go
Reverts mattermost/mattermost-server#21986
We are seeing the failure again in our CI.
```release-note
NONE
```
> Revert "[MM-42652] Re-enable test"

- app/channels.go
- app/plugin.go
- app/plugin_install.go
There were multiple issues at play here.
1. If the plugin was disabled in ch.syncPlugins,
then the prepackaged plugin would not be processed.
Therefore, if there was an earlier version of the plugin
that remained in S3, that would show up instead.
Therefore, we have to let the full plugin extraction
procedure go ahead, but not enable focalboard.
2. We also need to send the disablePlugin signal
to the other node. But the signal won't be sent
until the cluster leader is elected and inter-node
communication is set up. Therefore, we need to listen
to the ClusterLeaderChanged event and send out
a disable plugin event as well.
When both these issues are taken care of,
then we would correctly see the version of the plugin
from the prepackaged_plugins directory in the disabled
state. …
> MM-49485: Properly disable plugin in product mode (round 2)

- api4/cloud.go
- api4/hosted_customer.go
- api4/hosted_customer_test.go
- i18n/en.json
If not an enterprise build (e.g. there is no cloud interface), attempts to check CWS connectivity result in 400 Bad request instead of panics. Not strictly needed because [the webapp PR](https://github.com/mattermost/mattermost-webapp/pull/12117) should prevent requests from being made in the first place, but it would be better to not go through the http handler panic/recover cycle if someone crafts a request to these endpoints manually.
* https://mattermost.atlassian.net/browse/MM-50049
* https://mattermost.atlassian.net/browse/MM-50050
```release-note
* Team edition returns 400 Bad request for attempts to check CWS availability
```
> error instead of panic if cloud endpoints are hit

- model/config.go
On a freshly installed MM server, the Apps Plugin does not correctly work because OAuth 2.0 in the MM server need to be enabled.
To ease the first UX with apps, the setting should be enabled by default.
https://mattermost.atlassian.net/browse/MM-49991
```release-note
Enable EnableOAuthServiceProvider by default
```
> [MM-49991] Enable EnableOAuthServiceProvider by default

- store/sqlstore/user_store.go
When a post is marked as unread, we are sending a push notification with the updated badge count.
Currently in the query, for the direct messages, we are doing `totalMessages - messagesCount` which is leading to the wrong count of the messages as it includes all the messages by both users. We are doing this to count all DM `unreads` as `mentions`. 
https://github.com/mattermost/mattermost-server/blob/91ee9ed2ebf1a9cd3ecf365dff1c4261452a576f/app/post.go#L1756-L1778
For the direct messages, we are already including all the `unreads` as `mentions`, and the same query used for the rest of the channels will also work for the direct messages.
https://mattermost.atlassian.net/browse/MM-36289
```
NONE
```
> [MM-36289] App badge count fix for the direct messages

- app/work_template_executor.go
- app/worktemplates/model.go
- app/worktemplates/model_test.go
- app/worktemplates/templates.yaml
- app/worktemplates/worktemplate_generated.go
- i18n/en.json
- Changes names of work templates
- If the user input a name, this name will be used as the channel name. Also works on playbook run's generated channels.
- Boards and playbook will now be suffixed  with the user input (`Mobile: Projet Tasks` becomes `Project Tasks Mobile`)
- Playbook run channel visibility is forced to match the user selection. It also allows us to simplify the permission check.
Make sure to also take a look at the frontend PR to have more details on all changes: https://github.com/mattermost/mattermost-webapp/pull/12114
https://mattermost.atlassian.net/browse/MM-50082
```release-note
NONE
```
> [MM-50082] Work templates: copy + other tweaks

- api4/user_test.go
- store/sqlstore/thread_store.go
When the `since` param is used, API only returns new threads with `since` greater than `ThreadMembership.LastUpdatedAt`. Due to this threads with new replies are not synced on the mobile client. 
https://mattermost.atlassian.net/browse/MM-48010
```
behavioral change
```
> [MM-48010] Fetch Threads since parameter should return threads with new replies.

- app/slashcommands/command_templates.go
- app/slashcommands/command_work_template.go
- i18n/en.json
Adds a `/templates` command to open the modal.
N/A: OSF 
- Has webapp changes https://github.com/mattermost/mattermost-webapp/pull/12145
```release-note
NONE
```
> [OSF] Allows opening the work template modal from a slash command

- app/worktemplates/templates.yaml
- app/worktemplates/worktemplate_generated.go
Change work template definitions to use PNG instead of SVGs
N/A
Webapp https://github.com/mattermost/mattermost-webapp/pull/12136
```release-note
NONE
```
> Work templates: move form SVG to PNG

- api4/user_test.go
- app/email/email.go
As part of https://github.com/mattermost/mattermost-server/pull/22119 a new validation was added when signing up a new user created from an invitation via email token. There was a regression because in the function that sends the invitation for the Guest users, the senderId (inviter) data was not added, causing that the function running the validation has no user to check permissions against and returning false (no permission) for each of the channels.
This PR makes sure to add the senderId to the invitation token for Guests so the validation can be performed successfully.
https://user-images.githubusercontent.com/10082627/217282222-3b1a788b-b23a-4685-a8e0-2c98440863d6.mov
https://mattermost.atlassian.net/browse/MM-50355
```release-note
NONE
```
> MM-50355 - add senderId so the channel validations function can validate sender permissions when inviting guests

- api4/cloud.go
- api4/file.go
- api4/hosted_customer.go
- api4/job.go
- api4/system.go
- shared/web/files.go
Moved the attachment serve response functionality method to the shared folder so that all other Mattermost products can use them which achieves to use of only a single attachment serve response throughout the Mattermost ecosystem. 
```release-note
Moved the attachment serve functionality to a shared folder making it universal throughout the mm ecosystem
```
> Moving file response functionality to shared folder

- api4/user_test.go
- app/email/email.go
Manual Cherry pick of https://github.com/mattermost/mattermost-server/pull/22267 on release-7.1.
Replaces: https://github.com/mattermost/mattermost-server/pull/22277
n/a
```release-note
NONE
```
> MM-50355 - add senderId so the channel validations function can validate sender permissions when inviting guests (#22267)

- api4/notify_admin.go
- app/notify_admin.go
Commit done after the review of the notify admin for plugin installation have changed the value of the cooldown + introduced some debug logs. This PR fixes those changes.
N/A
```release-note
NONE
```
> Restore admin notify cooloff and remove debug logs

- app/migrations.go
- testlib/store.go
We want to enable `PostPriority` by default since 7.7 onward. Unfortunately while the feature was still behind a feature flag we had the config as default false thus some servers have it as false even when we updated the config to default to true.
This commit inserts an one-time migration to change the config from false to true.
https://mattermost.atlassian.net/browse/MM-49851
```release-note
[Message Priority & Acknowledgement](https://docs.mattermost.com/configure/site-configuration-settings.html#message-priority) is now enabled by default for all instances. You may disable this feature in the System Console by going to **Posts > Message Priority** or via the config ``PostPriority`` setting.
```
> MM-49851: forces PostPriority config to true

- app/post.go
- model/post.go
The webapp needs to construct the full message because
the team_name needs to be inserted into the permalink.
So we need to send everything in the metadata for the
client to construct the message.
Also, we set a custom post type for the client to easily
add a custom condition.
```release-note
NONE
```
> Add additional metadata to post reminder

- app/platform/web_hub.go
This PR avoids a divide-by-zero panic on server start-up due to websocket messages being sent during plugin start-up, before web_hubs are created.  `GetHubForUserId` assumes the hubs are created but can get called before they are.  All callers of `GetHubForUserId` check for a nil return, so this PR simply returns a nil in this case. 
This is a simpler fix than trying to refactor the server init sequence (again).
```
error [2023-02-10 10:31:26.450 -05:00] CallbackQueue callback panic                  caller="utils/callbackqueue.go:124" product=boards name=blockChangeNotifier panic="runtime error: integer divide by zero" stack="goroutine 5374 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).exec. …
```
> Avoid divide by zero when hubs not created before first websocket msg

- .circleci/config.yml
It appears that we don't need to use the token, this would solve the context issue in the automated cherry-picks
```release-note
NONE
```
> The GH token is not required for accesing PR metadata

- app/ldap.go
This adds a simple error that occurs when you run an LDAP sync via mmctl or the api.
https://mattermost.atlassian.net/browse/MM-50443
```release-note
Added an error message when you run LDAP sync with `SyncEnabled` set to false.
```
> MM-50443 - LdapSettings.SyncEnabled error message

- store/sqlstore/post_store.go
- store/sqlstore/thread_store.go
For some queries MySQL performed poorly until we slightly
tune the query. Here are the results:
Old query
```
// 5.7
mysql> explain SELECT Posts.Id FROM Posts LEFT JOIN Channels ON Posts.ChannelId = Channels.Id WHERE Channels.Id IS NULL LIMIT 3000;
+----+-------------+----------+------------+--------+---------------+--------------------------------+---------+----------------------------+---------+----------+--------------------------------------+
| id | select_type | table    | partitions | type   | possible_keys | key                            | key_len | ref                        | rows    | filtered | Extra                                |
+----+-------------+----------+------------+--------+---------------+--------------------------------+---------+----------------------------+------ …
```
> Cherry-pick: MM-50435: Improve data retention queries on MySQL (#22304)

- plugin/supervisor.go
This PR makes sure we include the specific error that occurred in the log message, when we fail to generate a checksum for a plugin. In my case, the linux binary was missing from my plugin bundle because I built with `MM_SERVICESETTINGS_ENABLEDEVELOPER=true`, but I didn't know this was the case until I made the change in this PR.
```release-note
NONE
```
> Improve error handling when plugin checksum fails

- app/server.go
The ticket linked below intended to enable Shared Channels for Professional licenses.  The PRs missed adding the dependency Remote Cluster Service to the professional license.  This PR corrects that by assuming Remote Cluster Service is enabled if Shared Channels is enabled.  It also simplifies configuration by allowing users to simply set the Shared Channels config item.
https://mattermost.atlassian.net/browse/MM-47489
```release-note
Shared Channels feature included in Professional license.
```
> MM-47489 Assume Remote Cluster Service enabled if Shared Channels enabled.

- .github/workflows/ci.yml
The sentry organization is required for the sentry-cli. Since it was being set from the env vars before, I missed to include that.
```release-note
NONE
```
> add sentry org to the env vars

- .github/workflows/ci.yml
Use getsentry/action-release@v1 for sentry release
```release-note
NONE
```
> Use getsentry/action-release@v1 for sentry release

- config/common_test.go
- config/environment.go
PR implements some logic to enable overriding the plugins state through env variables more granularly (at plugin level). Before it was only possible to set the whole JSON object (e.g. `MM_PLUGINSETTINGS_PLUGINSTATES="{\"com.mattermost.calls\":{\"Enable\":true}"`) which isn't very convenient.
To be noted, this won't behave exactly like other environment overrides as the implementation is lacking a way to detect the applied override and remove it from config so it's more of a permanent override meaning the value gets actually persisted in the config. I think this is fine for the current need (permanently disable certain plugins) and can be improved at a later time.
@amyblais This is needed to unblock https://community.mattermost.com/private-core/channels/edwwn1bfafgzxxsufk8znst7ye …
> [MM-51054] Allow enabling/disabling plugins through env override

- model/feature_flags.go
Reverts mattermost/mattermost-server#22427
Boards is being reverted back to plugin mode due to an incident in the latest Cloud release.
> Revert "[MM-50996] Set WorkTemplate FF to true by default"

- Makefile
(cherry picked from commit c300c4600c95bf24210069b258ea1a69bf8b1b79)
Prepackage boards v7.9.0
Fixes https://github.com/mattermost/focalboard/issues/4585
```release-note
Prepackage boards to v7.9.0
```
> prepackage boards v7.9.0 (#22423)

- app/server.go
- model/license.go
- web/context.go
- web/handlers.go
The ticket linked below intended to enable Shared Channels for Professional licenses.  This is the third (and final) PR to implement the intended logic.  This PR ensures the licence check in the web handler also respects the rule that if SharedChannels is enabled then RemoteClusterService is enabled.
Without this fix, the services were started, but invitations to connect remote servers fail on the license check with Pro licenses. 
https://mattermost.atlassian.net/browse/MM-47489
```release-note
Fixes issue with Shared Channels under Professional license.
```
> MM-47489 Fix all occurrences of checking for RemoteClusterServiceLicense

- model/websocket_message.go
- model/websocket_message_test.go
fmt.Sprintf was badly optimized and in cases of heavy traffic,
it was in the hot path and caused a lot of allocations.
We sacrifice readability for performance here.
Fixes https://github.com/mattermost/mattermost-server/issues/22351
https://mattermost.atlassian.net/browse/MM-50589
```
10:46:40-~/mattermost/mattermost-server/model] benchstat base.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/mattermost/mattermost-server/v6/model
cpu: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
│  base.txt   │               new.txt               │
│   sec/op    │   sec/op     vs base                │
EncodeJSON-8   2.061µ ± 1%   1.588µ ± 2%  -22.93% (p=0.000 n=10)
│  base.txt  │              new.txt               │
│    B/op    │    B/op     vs base                │
EncodeJSON-8   545.0 ± 0%   472.0 ± …
```
> Optimize precomputing of websocket event

- model/config.go
Added `cloud_restrictable` to local mode settings to restrict access in Cloud. 
https://mattermost.atlassian.net/browse/MM-51051
```release-note
None
```
> Updated Local Mode settings for cloud

- Makefile
Update prepackage board to v7.9.2
```release-note
Update prepackage boards to v7.9.2
```
Not going into main, as main is closed. Will need to cherry-pick original fix https://github.com/mattermost/focalboard/pull/4635 into mono-repo.
Will also need to Cherry pick this PR to cloud.
> Prepackage boards v7.9.2

- Makefile
Update prepackage board to v7.9.2
```release-note
Update prepackage boards to v7.9.2
```
Manual cherry-pick of https://github.com/mattermost/mattermost-server/pull/22502
> update prepackage boards to v7.9.2

- app/server.go
- services/telemetry/telemetry.go
- services/telemetry/telemetry_test.go
We are making sure that the telemetry ID is written or being read from the systems table. If not, we are returning the error upwards.
https://mattermost.atlassian.net/browse/MM-49993
```release-note
The app server won't start if the telemetry ID in the systems table doesn't exist. Although there is no action required by the administrators, it may be good to be aware of this change.
```
> [MM-49993] Return error if there is no telemetry ID

- .github/workflows/channels-ci.yml
- server/build/release.mk
- webapp/Makefile
- webapp/channels/Makefile
Instead of having the web app generate a tarball with its `make dist`, it now builds all parts of the web app and then copies the Playbooks/Boards files into the web app's dist folder in `webapp/channels/dist`. As far as I can tell, that tarball isn't needed any more.
I also updated the server's `release.mk` to look for the web app files in the above location
```release-note
NONE
```
> Re-add dist target for web app

- .github/workflows/ci.yml
- server/build/release.mk
Apparently I was wrong for assuming the `build-client` target is actually called by `make build` or `make build-cmd`
```release-note
NONE
```
> Actually build the web app when the server builds

- api4/channel.go
- api4/channel_test.go
- model/client4.go
- Added a `exclude_files_count` param to exclude file counts from channel stats API. Returns -1 if file counts have been excluded. This is to differentiate between a zero files count, and excluded files count.
- cherry-pick https://github.com/mattermost/mattermost-server/pull/22096 
- https://mattermost.atlassian.net/browse/MM-49486
```release-note
Added a `exclude_files_count` parameter to exclude file counts from channel stats API
```
> [MM-49486]: Option to exclude file count in channel stats

- plugin/environment.go
- plugin/environment_test.go
- server/channels/app/channels.go
- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
- server/channels/app/plugin_install_test.go
Adds a blocklist for plugins that have been integrated into the monorepo. These plugins will not be installed or start.
Warnings are printed to the debug logs, otherwise no errors are raised. 
Removed boards blocking code from plugins. Left it everywhere else since it seemed to be used by the tests. Separate PR needed to remove the boards feature flag entirely. 
Fixes https://github.com/mattermost/mattermost-plugin-playbooks/issues/1832
Fixes https://github.com/mattermost/focalboard/issues/4628
```release-note
NONE
```
> Add blocklist for monorepo integrated plugins

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- server/channels/app/team.go
There is a standard IDNA2008 which defines how unicode characters
in domain names can be compared using UTS (Unicode Technical Standard) 46.
We use that to convert any links in messages to ASCII and
then compare with the domain list in config.
https://mattermost.atlassian.net/browse/MM-51486
```release-note
NONE
```
> MM-51486: Implementing UTS 46 to check for preview blocklist

- model/file_info.go
- server/channels/api4/file_test.go
- server/channels/app/file.go
- server/channels/app/file_test.go
- server/channels/app/import_functions.go
- server/channels/app/post.go
- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000106_fileinfo_channelid.down.sql
- server/channels/db/migrations/mysql/000106_fileinfo_channelid.up.sql
- server/channels/db/migrations/postgres/000106_fileinfo_channelid.down.sql
- server/channels/db/migrations/postgres/000106_fileinfo_channelid.up.sql
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/searchlayer/file_info_layer.go
- server/channels/store/searchtest/file_info_layer.go
- server/channels/store/searchtest/helper.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/sqlstore/file_info_store.go
- server/channels/store/sqlstore/integrity.go
- server/channels/store/sqlstore/integrity_test.go
- server/channels/store/store.go
- server/channels/store/storetest/file_info_store.go
- server/channels/store/storetest/mocks/FileInfoStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/slackimport/slackimport.go
We Denormalize Post.ChannelId on FileInfo.ChannelId
```release-note
The file info stats query is now optimized by denormalizing the channelID column into the table itself. This will speed up the query to get the file count for a channel on clicking the RHS.
Migration times:
On a MySQL 8.0.31 DB with
1405 rows in FileInfo and 11M posts, it took around 0.3s
On a Postgres 12.14 DB with
1731 rows in FileInfo and 11M posts, it took around 0.27s
```
https://mattermost.atlassian.net/browse/MM-45956
> MM-45956: Optimize FileInfo stats query

- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
We still hold pointer of the last element when WebConn is removed. https://go101.org/article/container.html#slice-manipulations:~:text=Delete%20one%20slice%20element
Fixed https://github.com/mattermost/mattermost-server/issues/22351
```release-note
NONE
```
> fix mem leak in hubConnectionIndex

- .github/workflows/channels-ci.yml
- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-ci.yml
- .github/workflows/test.yml
To reduce costs and have a similar behavior with our previous CI, we cancel previous workflows if there are new workflows started for the specific branch.
```release-note
NONE
```
> add concurrency limitation to gh actions

- webapp/channels/src/components/admin_console/admin_definition.jsx
Fix EmailSettings.FeedbackEmail client validation. This is the same change as https://github.com/mattermost/mattermost-webapp/pull/12378, but applying it to the monorepo.
https://mattermost.atlassian.net/browse/MM-50952
No release notes, this only impacts RFQA servers.
```release-note
NONE
```
> Fix EmailSettings.FeedbackEmail client validation

- server/channels/api4/hosted_customer.go
Return 404 if the enterprise library error returned is 404
https://mattermost.atlassian.net/browse/MM-51294
```release-note
Invoice not found is a 404 instead of a 500 error.
```
> Invoice not found is a 404 instead of a 500 error

- model/config.go
- server/channels/api4/config.go
- server/config/diff_test.go
- server/i18n/en.json
Removes the automatic enabling of Playbooks and Boards on new configurations that are created.
```release-note
NONE
```
> Remove configuration auto enable.

- server/channels/app/platform/web_conn.go
We log warnings whenever our websocket buffer sizes exceed
certain thresholds. The problem with that is, when this happens,
the logs are completely spammed with these lines
making it annoying for the customer.
To improve the situation, we use a timer that only gets reset
every minute.
https://mattermost.atlassian.net/browse/MM-51700
> MM-51700: Suppress websocket warnings with a threshold

- webapp/platform/client/src/websocket.ts
**NOTE** This is the same as https://github.com/mattermost/mattermost-webapp/pull/12302 created against the mono-repo. It has been code & QA reviewed, so it's ready to be merged.
When restarting (among other things) the server, there is a logic in `websocket.ts` that handles reconnecting after a certain amount of time (3 seconds currently). In case something goes wrong and an exception is thrown in any of the reconnect/missedMessages handlers (which e.g. can be handlers registered from plugins and this has happened in the past with the Todo plugin), the rest of the code in that branch of the file is not executed.
The most important part of the code not executed in that case is resetting the `serverSequence`, so after the `hello` message from the newly connected websocket, all subsequent …
> [MM-50002] Fix infinite reconnect loop when reconnect handler fails

- server/playbooks/product/playbooks_product.go
https://mattermost.atlassian.net/browse/MM-51744
```release-note
NONE
```
> MM-51744: Ignore http.ErrServerClosed from Playbooks metricsServer

- CODEOWNERS
- webapp/channels/CODEOWNERS
The web app repo was previously set up so that our review was needed on the package.json files so that we'd see when dependencies changed. I also added it to the web app CI config, Makefile, and build scripts just since I want to be aware of when those change
https://mattermost.atlassian.net/browse/MM-51683
```release-note
NONE
```
> MM-51683 Re-add CODEOWNERS for Web Platform files

- webapp/boards/package.json
- webapp/boards/src/components/cloudUpgradeNudge/cloudUpgradeNudge.tsx
- webapp/boards/src/index.tsx
- webapp/boards/src/rudder.ts
- webapp/boards/src/types/mattermost-webapp/index.d.ts
- webapp/boards/webpack.config.js
- webapp/package-lock.json
- webapp/playbooks/jest.config.js
I was hoping to have Boards just use the latest version of mattermost-redux from the web app like Playbooks does, but I ran into some other issues that would've taken too much time to sort out right now. For example, Boards uses the proper `createSelector` which has a different interface than our custom `createSelector` that we use in the rest of the web app, and I couldn't figure out how to make that work nicely without changing the import paths of one or the other.
Since the only parts of mattermost-redux used directly by Boards are:
1. Some types exposed in `@mattermost/types` already
2. The selectTeam action creator
3. Some telemetry stuff
It was easier to just copy over the code for 2 and 3 instead of fix those properly.
https://mattermost.atlassian.net/browse/MM-51735 …
> MM-51735 Remove references to mattermost-redux from Boards

- webapp/channels/src/actions/global_actions.tsx
- webapp/channels/src/components/channel_info_rhs/channel_info_rhs.test.tsx
- webapp/channels/src/components/channel_info_rhs/channel_info_rhs.tsx
- webapp/channels/src/components/channel_info_rhs/index.ts
- webapp/channels/src/components/channel_info_rhs/menu.test.tsx
- webapp/channels/src/components/channel_info_rhs/menu.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
- webapp/platform/client/src/client4.ts
Exclude file count on channel stats API call on from channel header.
Migrating from `mattermost-webapp` https://github.com/mattermost/mattermost-webapp/pull/12245
Fixes https://mattermost.atlassian.net/browse/MM-49090
- Has server changes (Merged) https://github.com/mattermost/mattermost-server/pull/22096
```release-note
* Exclude file count on channel stats API call on from channel header.
```
> [MM-49090]: Exclude file count on channel stats api call on from channel header

- webapp/channels/src/components/signup/__snapshots__/signup.test.tsx.snap
- webapp/channels/src/components/signup/signup.tsx
- webapp/channels/src/utils/utils.tsx
This PR adds telemetry events for first admins when they initially land to the account creation page . The intention is to capture some of the interactions and events the first users have with the account creation page in order to be able to measure and take actions aiming to improve the product usage and adoption.
Captured Events:
The category used for these telemetry values is: `signup` and the extra data that will contain each one of these values is the serverId value.
* Then there are events captured if the user has typed anything in the email, username or password inputs
- `typed_input_email`
- `typed_input_username`
- `typed_input_password`
we listen for the blur event on the email, username and password inputs, then we check if there is a value in the input meaning the user entered …
> MM-49865 - add telemetry to account creation screen

- webapp/channels/src/components/tours/worktemplate_explore_tour/boards_tour_tip.tsx
- webapp/channels/src/components/tours/worktemplate_explore_tour/playbooks_tour_tip.tsx
- webapp/channels/src/components/tours/worktemplate_explore_tour/useShowTourTip.tsx
- webapp/channels/src/components/work_templates/index.tsx
- webapp/channels/src/components/work_templates/utils.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/work_templates.ts
- webapp/platform/types/src/work_templates.ts
This PR makes sure that the tourtip shown after a worktemplate execution is shown only once per user and not on every worktemplate use
https://mattermost.atlassian.net/browse/MM-51028
https://github.com/mattermost/mattermost-webapp/pull/12219
Migrated from: https://github.com/mattermost/mattermost-webapp/pull/12301
https://user-images.githubusercontent.com/10082627/222408535-8c37277a-f67d-45ec-a9f1-a83143a17831.mov
```release-note
NONE
```
> MM-47849 - show worktemplate tourtip only once

- server/channels/store/sqlstore/remote_cluster_store.go
- server/channels/store/sqlstore/shared_channel_store.go
This PR fixes a customer reported issue where their database had a previously removed column in the `sharedchannels` table.  This can happen when customers run a pre-release version of server (when Shared Channels was in development) and then continue upgrading per normal.  The field in question was not included in a release.
The fix is to remove all instances of `SELECT (*)` from shared channels store so that any extra columns are ignored.
https://mattermost.atlassian.net/browse/MM-51705
```release-note
Fixes an issue where the experimental Shared Channels feature would fail to synchronize if a previously removed table column was still present.
```
> MM-51705 Fixes Shared Channels issue due to SELECT('*')

- webapp/boards/src/components/sidebar/sidebarCategory.scss
Will rebase to master once mono-repo is merged.
Set the color for sidebar dialog box. Currently defaults to Sidebar Color `rgb(var(--sidebar-text-rgb))`, which cannot be seen in normal color scheme.
Fixes https://github.com/mattermost/focalboard/issues/4649
```release-note
Fixes issue with Delete Category Dialog message not visible
```
> update dialog color for sidebar category

- server/playbooks/server/api/api.go
While inspecting Pyroscope, the function api.ReturnJSON
was seen to take some chunk of the overall memory allocations.
Looking deeper, we can see that the entire object
is json marshalled into bytes, and then wrote to the network.
Instead, we can just do a streaming write to the network
which avoids pre-allocating the entire object.
A similar approach is taken in the server channels codebase
as well.
```release-note
NONE
```
> Optimize JSON marshalling in playbooks

- webapp/channels/src/utils/text_formatting.test.ts
- webapp/channels/src/utils/text_formatting.tsx
- If a user clicked on a channel link for a channels the user was not a part of, the webapp would refresh. This caused the current call to drop. The problem was an accidental quotation mark. (Hat-tip to Harrison for spotting the typo!)
- I've added a test so this particular issue won't regress
- https://mattermost.atlassian.net/browse/MM-49080
```release-note
Fixed a problem where clicking on a channel link (for a channel the user was not a part of) would cause the webapp to refresh, dropping the user's current call.
```
> MM-49080 - Fix for: channel links causing the webapp to refresh

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
Because the ephemeral message does not have a `user_id`, it returns an empty string as `id` of a user.
Duplicate of https://github.com/mattermost/mattermost-webapp/pull/12350 because of "mono-repo".
https://mattermost.atlassian.net/browse/MM-51280
N/A
N/A
```release-note
NONE
```
> [MM-51280] Fix JS error after ephemeral message

- model/feature_flags.go
- server/Makefile
- server/boards/product/boards_product.go
- server/boards/server/boards_service_util.go
- server/channels/app/product.go
- server/docker-compose.yaml
This PR replaces the Boards feature flag with an env var on the back-end.  A PR to remove from front-end is pending.
Currently Boards can be disabled via a feature flag that defaults to disabled. Multiple production incidents have happened on community due to not having the feature flag set.  The FF will be replaced with a env var that defaults to enabled.  
This is temporary until mm-server unit tests can run without disabling Boards.
https://mattermost.atlassian.net/browse/MM-51792
```release-note
NONE
```
> MM-51792 Replace Boards feature flag with env var

- model/feature_flags.go
Manual cherry-pick of the webapp side for https://github.com/mattermost/mattermost-server/pull/22714
n/a
- Monorepo: https://github.com/mattermost/mattermost-server/pull/22714
- Webapp: https://github.com/mattermost/mattermost-webapp/pull/12386
```release-note
NONE
```
> make autolinked board ff false as default

- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_spec.ts
- webapp/channels/src/components/invitation_modal/invite_view.scss
- webapp/channels/src/components/invitation_modal/invite_view.tsx
Hides the "copy invite link" button when selecting guest in the invitation modal
ported from https://github.com/mattermost/mattermost-webapp/pull/12364
[mattermost.atlassian.net/browse/MM-51098](https://mattermost.atlassian.net/browse/MM-51098)
```release-note
NONE
```
> [MM-51098] Hide "copy invite link" when selecting guest - migrated from webapp

- server/boards/api/files.go
This PR fixes a panic in the Boards Rest API for fetching files.  It panics if the `app.getFile` call returns an error other than `not found`.
The panic is caught and handled, but it is logged and thus is [reported by customers](https://community.mattermost.com/private-core/pl/pqnrooyqj3b9fcz7ktq46rkshr) as a crash.  It also returns the wrong error to the client.
https://mattermost.atlassian.net/browse/MM-51885
```release-note
Fixes an innocuous panic in Boards Rest API when requesting files and a error other than `not found` is encountered.
```
> Boards: Avoid panic in Boards file request handler when file not found.

- webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
- webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
- webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
This PR adds the necessary logic and tests to make sure that when a user has no permissions to create any kind of channel, the add channels cta button opens the browse channels modal directly once clicked
n/a
https://github.com/mattermost/mattermost-server/pull/22743
User can not create channels:
https://user-images.githubusercontent.com/10082627/229211904-45078197-ca3a-4beb-87b8-b7bf0be87973.mov
User can create channels:
https://user-images.githubusercontent.com/10082627/229211929-1d0b5643-5dbd-49e0-a067-6f5f61fb8824.mov
```release-note
NONE
```
> open browse channels directly when user has no channel creation permissions

- webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
- webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
- webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
- webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
- webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/layout/_sidebar-left.scss
This PR fixes a couple of issues related to the add channels cta button located at the lhs. The following points describes what was fixed:
- By clicking the button the button was being show outside of the viewport so it was giving the impression it was not working. This was caused to a css naming clash with a Menu class coming from boards after the monorepo changes.
- The above space between the lhs cta add channels and invite members was bigger than other list elements, this was also fixed in this PR.
- The lhs menu in mobile view was being shown separated from the lhs edge of the screen.
Button not working: https://mattermost.atlassian.net/browse/MM-51804
Top space in buttons: https://mattermost.atlassian.net/browse/MM-51803
LHS not working in mobile view: I need to find the ticket …
> MM-51804 - add channels lhs not working

- server/boards/api/files.go
Cherry-pick for https://github.com/mattermost/mattermost-server/pull/22792 into cloud branch.
This PR fixes a panic in the Boards Rest API for fetching files.  It panics if the `app.getFile` call returns an error other than `not found`.
The panic is caught and handled, but it is logged and thus is [reported by customers](https://community.mattermost.com/private-core/pl/pqnrooyqj3b9fcz7ktq46rkshr) as a crash.  It also returns the wrong error to the client.
https://mattermost.atlassian.net/browse/MM-51885
```release-note
Fixes an innocuous panic in Boards Rest API when requesting files and a error other than `not found` is encountered.
```
> Cherry pick MM-51885: Avoid panic in Boards file request handler

- server/channels/app/slashcommands/command_loadtest.go
Fixed /test url and json by pointing to new server path
Note: @amyblais This should be cherry-picked for April 13th Cloud release.
https://mattermost.atlassian.net/browse/MM-51870
```release-note
NONE
```
> MM-51870 Fix /test url and json

- webapp/channels/src/components/invitation_modal/invite_view.tsx
Screen reader announcing link copied on copying the link in invite modal.
Pr for https://github.com/mattermost/mattermost-webapp/pull/11081
Co-authored-by: Babinder Rathi <babinderrathi@gmail.com>
Fixes https://mattermost.atlassian.net/browse/MM-44860
None
|  before  |
|----|
https://user-images.githubusercontent.com/102028591/188860492-8e308cf1-e6e7-42bb-a06c-65cfa5809290.mp4 
|  after |
|----|
https://user-images.githubusercontent.com/102028591/188861546-eed97466-0b40-440d-85b7-fd27cec8ac99.mp4
```release-note
* Screen reader announcing link copied on coping the link in invite modal
```
> [MM-44860] Screen reader announcing link copied on copying the link in invite modal

- webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
- webapp/channels/src/sass/layout/_sidebar-left.scss
While applying a fix for the add channels cta button a regression was introduced preventing the LHS banner to scroll-y. This PR removes that regression.
Regression cause: https://github.com/mattermost/mattermost-server/pull/22743/files#diff-d0500ece0484af3ff1e13165533525a6abc038f889de5261c37660f0d946b781R581
https://mattermost.atlassian.net/browse/MM-51912
Before:
https://user-images.githubusercontent.com/10082627/229735692-9a8986f9-b8ae-4904-80fe-88d2b9d4dc58.mov
After:
https://user-images.githubusercontent.com/10082627/229735584-7e1bc539-ceb8-4bf5-a7e3-69eeccf24163.mov
```release-note
NONE
```
> MM-51912 - fix  not able to scroll in the LHS

- webapp/channels/src/i18n/de.json
- webapp/channels/src/i18n/en.json
when opening the browse channels modal there is an issue with English and German translations for the text "No more channels to join".
Original regression: https://github.com/mattermost/mattermost-webapp/pull/11262/files#diff-1a490f08504158838befaa816ee8d5c08dff9e694d5a568ce4b0a4398dcc563eR4170
https://mattermost.atlassian.net/browse/MM-51915
Before:
After:
```release-note
NONE
```
> MM-51915-fix no more channels to join text

- webapp/channels/src/components/admin_console/billing/delete_workspace/delete_workspace_cta.tsx
Clicking the `Delete Worksapce` CTA opens a new tab, where the delete workspace modal is then opened.
The modal should open on the same tab.
[MM-51911](https://mattermost.atlassian.net/browse/MM-51911)
Ensure you have a license for a workspace with the following conditions:
- Is subscribed to a cloud product
- Is on a free trial **OR**
- Is on a starter subscription **OR**
- Is on a monthly professional subscription
For clarity, these subscriptions may be deleted:
- Cloud-Starter.
- Cloud-Professional (monthly).
- Enterprise Free Trial.
1. Log in as an admin user
2. Go to the system console, and navigate to the `Billing > Subscription` page
3. Scroll to the bottom of the page and click the `Delete Workspace` button.
4. Notice the `Delete Workspace` modal opens in the same page, and that a …
> MM-51911 - The Delete Workspace Button Opens the Modal in a New Tab

- model/license.go
- server/channels/api4/license_test.go
- server/i18n/en.json
Fix two small issues, one of which made debugging a unit test failure harder due to the wrong copy/pasted error message.
None
```release-note
NONE
```
> fix various copy/paste/typos

- webapp/channels/src/actions/views/rhs.ts
- webapp/channels/src/components/activity_and_insights/insights/top_channels/top_channels.tsx
- webapp/channels/src/components/custom_status/custom_status_emoji.test.tsx
- webapp/channels/src/components/custom_status/custom_status_emoji.tsx
- webapp/channels/src/components/custom_status/custom_status_modal.tsx
- webapp/channels/src/components/dot_menu/index.ts
- webapp/channels/src/components/post_markdown/index.ts
- webapp/channels/src/components/post_reminder_custom_time_picker_modal/index.ts
- webapp/channels/src/components/post_view/post_edited_indicator/index.ts
- webapp/channels/src/components/profile_popover/index.ts
- webapp/channels/src/components/profile_popover/profile_popover.tsx
- webapp/channels/src/components/root/effects.ts
- webapp/channels/src/components/status_dropdown/index.ts
- webapp/channels/src/components/suggestion/search_date_suggestion/index.ts
- webapp/channels/src/components/timestamp/index.test.tsx
- webapp/channels/src/components/timestamp/index.ts
- webapp/channels/src/components/user_settings/display/index.ts
- webapp/channels/src/components/user_settings/display/manage_timezones/index.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/timezone.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/timezone.ts
- webapp/channels/src/packages/mattermost-redux/src/utils/timezone_utils.ts
- webapp/channels/src/selectors/general.ts
- webapp/channels/src/selectors/views/custom_status.ts
The original goal of this PR was to make it so that we were using the `makeGetUserTimezone` selector factory properly, but I ended up doing a bunch of cleanup to the timezone-related selectors since that didn't really need to be a factory to begin with. I also found out that we had some redundant selectors, so I got rid of those as well.
https://mattermost.atlassian.net/browse/MM-51359
https://github.com/mattermost/mattermost-webapp/pull/12231
```release-note
Improved performance of web app code related to timezone calculations
```
> MM-51359 Replace makeGetUserTimezone selector with getCurrentTimezone and similar selectors

- server/channels/api4/apitestlib.go
- server/channels/app/app_test.go
- server/channels/app/helper_test.go
- server/channels/app/platform/helper_test.go
- server/channels/app/platform/service_test.go
- server/channels/app/server_test.go
- server/channels/app/slashcommands/helper_test.go
- server/channels/web/web_test.go
- server/cmd/mattermost/commands/server_test.go
- server/playbooks/server/main_test.go
When running unit tests, explicitly bind to `localhost:0` instead of just `:0` to avoid binding to all available interfaces and in turn avoid triggering firewall warnings on MacOS:
None.
```release-note
NONE
```
> bind to localhost:0 for tests

- server/boards/integrationtests/boardsapp_test.go
- server/boards/server/boards_service_util.go
- webapp/boards/src/components/__snapshots__/workspace.test.tsx.snap
- webapp/boards/src/components/centerPanel.test.tsx
- webapp/boards/src/components/kanban/__snapshots__/kanbanColumnHeader.test.tsx.snap
- webapp/boards/src/components/kanban/kanbanColumnHeader.tsx
- webapp/boards/src/components/shareBoard/__snapshots__/shareBoard.test.tsx.snap
- webapp/boards/src/components/shareBoard/shareBoard.tsx
- webapp/boards/src/components/shareBoard/shareBoardLoginButton.test.tsx
- webapp/boards/src/components/shareBoard/shareBoardLoginButton.tsx
- webapp/boards/src/components/viewHeader/viewHeader.tsx
- webapp/boards/src/components/viewTitle.tsx
- webapp/boards/src/components/workspace.test.tsx
- webapp/boards/src/hooks/permissions.tsx
- webapp/boards/src/index.tsx
- webapp/boards/src/public/app.tsx
- webapp/boards/src/types/mattermost-webapp/index.d.ts
- webapp/channels/src/components/admin_console/admin_definition.jsx
- webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/root/root.test.tsx
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/plugins/pluggable/pluggable.tsx
- webapp/channels/src/plugins/registry.ts
- webapp/channels/src/types/store/plugins.ts
- webapp/channels/src/utils/test_helper.ts
- webapp/playbooks/src/index.tsx
* Adds support for public routes on shared boards
* Fix linter
* Address review comments
* Update playbooks registerProduct call
* Use boards product config for setting
* update additional product locations for parameter changes
* fixes for read-only when logged in
* turn off global header and don't initialize plugin if shared board
* fix unit tests
* revert package-lock.json
* more fixes
* Remove FF check for system console setting for boards
* update tests, Product boards is displayed in system console
* only check products section of config
* update test for config change
---------
Co-authored-by: Scott Bishel <scott.bishel@mattermost.com>
(cherry picked from commit 4cc2fed0791b2f2152e3d1c9cd62c5f5fc67177a)
```release-note
Added a …
```
> Adds support for public routes on shared boards (#22710)

- webapp/platform/types/src/config.ts
API response for data retention was missing the boards components.
```
GET http://localhost:8065/api/v4/data_retention/policy
```
```json
{
"message_deletion_enabled": true,
"file_deletion_enabled": true,
"boards_deletion_enabled": false,
"message_retention_cutoff": 1649217600000,
"file_retention_cutoff": 1649217600000,
"boards_retention_cutoff": 0
}
```
```release-note
NONE
```
> Added missing types

- scripts/esrupgrades/esr.5.37-7.8.mysql.up.sql
This PR modifies the script to upgrade from v5.37 to v7.8 by squashing together all migrations that affect the same table. For example Channels-related queries were present in migrations 56, 70, 76 and 90, with sometimes multiple queries per migration, while now they are grouped in a couple of queries inside the same MigrateChannels procedure. This happens for all tables affected by the migrations in this path. The goal of these procedures is two-fold:
1. Build and run a single query per table (sometimes not possible, since we need both an `ALTER TABLE` and an `UPDATE`).
2. Keep the idempotency of the individual migrations.
You can review by commit, but I think it's probably easier to just go through the whole file at once. However, the passing tests give me great confidence that the …
> ESR Upgrade: One procedure per table in the v5.37 > v7.8 upgrade script

- CODEOWNERS
Proposing we deprecate Toolkit's ownership of `/plugin` via CODEOWNERS.
None.
```release-note
NONE
```
> Deprecate Toolkit CODEOWNERS

- model/command_args.go
- server/channels/api4/command.go
This PR removes the session from `model.CommandArgs`. Plugins should use the RPC API directly to modify the server state or create custom session using the same API.
For more context, please see https://github.com/mattermost/mattermost-server/pull/14880#discussion_r443693131.
To my knowledge, no plugin uses this field.
https://mattermost.atlassian.net/browse/MM-26398
```release-note
Remove the deprecated model.CommandArgs.Session 
```
> [MM-26398] Remove deprecated model.CommandArgs.Session

- server/boards/integrationtests/clienttestlib.go
- server/boards/server/server.go
```
warn  [2023-04-12 09:16:55.397 +05:30] Failed to save status                         caller="platform/status.go:175" user_id=gt5aricnu7g7xkr4jstfybgmbc error="failed to upsert Status: sql: database is closed"
```
The DB handle is a global object that is finally closed
at a higher layer after all the necessary tasks are finished.
So closing it prematurely, in the boards shutdown phase
is not necessary and can cause failures as observed above.
To fix this, we just remove the shutdown method.
```release-note
NONE
```
> Do not shutdown DB handle from boards product

- server/boards/auth/auth.go
- server/boards/integrationtests/permissions_test.go
The public boards setting was not applied properly. This fixes it so the setting will now apply to existing board links.
https://mattermost.atlassian.net/browse/MM-51820
```release-note
NONE
```
> Fix public boards setting not applying properly.

- webapp/channels/src/components/post_view/post_aria_label_div.tsx
- webapp/channels/src/components/post_view/post_list_virtualized/latest_post_reader.test.tsx
- webapp/channels/src/components/post_view/post_list_virtualized/latest_post_reader.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
- webapp/channels/src/utils/post_utils.ts
Ported from https://github.com/mattermost/mattermost-webapp/pull/12233
`makeCreateAriaLabelForPost` is a bit weird because the value we're trying to calculate uses a bunch of data from a redux context and then it needs access to the `intl` object which is only available in the React context. It works okay, but the big problem that it has is that it wasn't memoized fully because it needed the `intl` object. This changes it to be memoized and also converts it into a hook so that I could use `useMemo` instead of our custom memoization stuff.
MM-50577
https://github.com/mattermost/mattermost-webapp/pull/12233
```release-note
Improved performance of code used for post list screen reader support
```
> MM-50577 Replaced makeCreateAriaLabelForPost with better memoized usePostAriaLabel

- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/web_conn.go
Seems like this is not needed from the `app.App` hence removing
```release-note
NONE
```
> server/channels: remove newWebConn method

- webapp/boards/src/components/sidebar/sidebarCategory.test.tsx
Skips "sidebar template close other" test in the file "webapp/boards/src/components/sidebar/sidebarCategory.test.tsx" temporarily due to random test failures of "fetch not defined."
```release-note
NONE
```
> Skip flaky "sidebar template close other" Boards test temporarily

- server/playbooks/server/api/api.yaml
Summary
Identifies a hidden API field required to successfully create a Playbook, using the free tier.
Ticket Link
Not a ticket, but a common error identified and disclosed in the forums.
https://forum.mattermost.com/t/error-unable-to-decode-playboook/15315/5?utm_source=mattermost&utm_medium=in-product&utm_content=post_attachment_opengraph&uid=pitfe5zmwbgixyq13uwdfa1age&sid=93mykbogbjfrbbdqphx3zhze5c
```release-note
NONE
```
> POST playbook api specification includes public boolean definition

- model/client4.go
- plugin/api_timer_layer_generated.go
- plugin/hooks_timer_layer_generated.go
- server/channels/api4/license.go
- server/channels/api4/license_test.go
- server/channels/einterfaces/cloud.go
- server/channels/einterfaces/mocks/CloudInterface.go
- server/i18n/en.json
- webapp/channels/src/components/analytics/true_up_review.tsx
Adds alternative route for true up review submission via CWS in the case that telemetry is disabled on the server.
[MM-51907](https://mattermost.atlassian.net/browse/MM-51907)
1. Ensure telemetry is ***DISABLED***.
2. Go to either `System Console > Site Statistics` or `System Console > Team Statistics`
3. Submit the true-up review by clicking the button in the true-up review panel.
To see the true-up review panels outside of true-up season, you should be able to modify records in the table `trueupreviewhistory` within Mattermost's database to a date within the next few days.
[CWS](https://github.com/mattermost/customer-web-server/pull/1163)
[Enterprise](https://github.com/mattermost/enterprise/pull/1417)
```release-note
NONE
```
[MM-51907]: …
> MM-51907 - Route True-Up Review Telemetry to CWS

- webapp/channels/src/components/admin_console/generated_setting.tsx
Generated values for settings are a random base64 string with a length of 32. Unfortunately, base64 has some accepted characters like `+` and `/` that don't behave correctly if we use them in a URL without the proper additional encoding.
Use instead this safe version of base64 https://datatracker.ietf.org/doc/html/rfc4648#section-5, where:
- `/` becomes `_`
- `+` becomes `-`
I checked other encodings like base32 or base58, but they required additional dependencies and this seemed good enough. 
Fixes https://mattermost.atlassian.net/browse/MM-51923
```release-note
Type-generated settings will be generated (only for future generations) with a URL-safe version of base64 encoding.
```
> safer base64 generated values in settings

- server/channels/app/license_test.go
- server/channels/app/platform/license_test.go
- server/channels/utils/license.go
So far, only people with enough permission to read license details would have access to this information. After discussions with the security team and approval from Joram, we decided to expose the `SkuShortName` when any user retrieves the license info.
A huge benefit for us is to be able to easily control if a user can access a feature or not in the webapp.
Fixes MM-52152
https://mattermost.atlassian.net/browse/MM-52152
```release-note
NONE
```
> [MM-52152] Expose license SkuShortName to all users

- server/playbooks/server/api_actions_test.go
- server/playbooks/server/api_bot_test.go
- server/playbooks/server/api_general_test.go
- server/playbooks/server/api_graphql_playbooks_test.go
- server/playbooks/server/api_graphql_runs_test.go
- server/playbooks/server/api_playbooks_test.go
- server/playbooks/server/api_runs_test.go
- server/playbooks/server/api_settings_test.go
- server/playbooks/server/api_stats_test.go
- server/playbooks/server/api_telemetry_test.go
- server/playbooks/server/main_test.go
The main package was used unnecessarily without a main function.
```release-note
NONE
```
> playbooks/server: Avoid using main package

- server/boards/services/store/sqlstore/schema_table_migration.go
The old check was using `sq.Eq`, which replaces its values with strings, and for the case of `table_schema` we want to call a function.
https://mattermost.atlassian.net/browse/MM-52281
```release-note
NONE
```
> Updates the check for the schema_migrations information

- server/playbooks/server/api/api.yaml
Prefixing `/plugins/playbooks/api/v0` explicitly on the spec for all Playbooks API paths, complementing the linked API pull request to allow these two differently rooted APIs to render correctly in all cases. 
None, but see https://github.com/mattermost/mattermost-api-reference/pull/732.
```release-note
NONE
```
> Absolute paths in Playbooks API Spec

- webapp/channels/src/components/admin_console/billing/billing_summary/index.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
Before we reverse the current cloud flow, when workspaces are on starter and never done a trial, admins have the ability to start an enterprise trial. However, soon workspaces won't be able to request their own trials, and that means we need to take away this ability.
https://mattermost.atlassian.net/browse/MM-52287
```release-note
NONE
```
> [MM-52287] - Cloud Free should not show the ability to start a trial

- webapp/channels/src/components/admin_console/billing/delete_workspace/delete_workspace_modal.scss
- webapp/channels/src/components/admin_console/billing/delete_workspace/delete_workspace_modal.tsx
There were some styling issues related to the Workspace Deletion modal:
1. The illustration (laptop image) should be 246 px width / 156 px height. Currently, it is 246px width / 182 px height (the default of the SVG): Set the SVG height property to `156px` (changing in CSS causes issues with overlapping, missing padding/margins, etc.)
3. The text colour should be center channel text colour (except for the bold text): Changed from `--sys-denim-center-channel-text` to `--center-channel-text`
4. The space above the illustration should be 48px (currently it appears to be 40px total with the modal’s padding and the existing padding on the illustration: Added 8px of padding above the SVG.
5. Bold text should be regular bold, not semibold: Seems to already be bold, but have applied styling to …
> MM-52155 - Workspace Deletion Modal Style Issues

- .github/workflows/ci.yml
The `Check style` step probably does not need an overspec'd runner. This hopefully mitigates these long waiting times to get an available runner:
https://mattermost.atlassian.net/browse/MM-52472
--
```release-note
NONE
```
> MM-52472: Use ubuntu-22.04 in the check-style step in CI

- webapp/channels/src/components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
Enables the "Mark All Threads as Read" button even when you don't have unreads.
This is done as a temporary action to mitigate the phantom unread mentions pending issue.
https://mattermost.atlassian.net/browse/MM-52451
```release-note
NONE
```
> MM-52451: always show mark all threads as read button

- .github/workflows/artifacts.yml
The build artifacts with branch names are no longer required as there are no other builds needs to be built for other repositories such as mattermost-webapp.
https://mattermost.atlassian.net/browse/MM-52493
```release-note
NONE
```
> [MM-52493] workflows/artifacts.yml: do not upload build artifacts for branches

- server/Makefile
The version `v1.50.1` seems to be broken as it's consuming more than hundred gb of ram. I was able to overcome it by upgrading the version.
https://mattermost.atlassian.net/browse/MM-52492
```release-note
NONE
```
> [MM-52492] Makefile: bump golangci-lint version

- e2e-tests/cypress/package-lock.json
- e2e-tests/cypress/package.json
- e2e-tests/cypress/tests/integration/playbooks/channels/app_bar_spec.js
- e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
- e2e-tests/cypress/tests/integration/playbooks/channels/rhs/status_update_spec.js
- e2e-tests/cypress/tests/integration/playbooks/lhs_spec.js
- e2e-tests/cypress/tests/integration/playbooks/playbooks/edit_metrics_spec.js
- e2e-tests/cypress/tests/integration/playbooks/runs/permissions_spec.js
- e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_header_spec.js
- e2e-tests/cypress/tests/integration/playbooks/runs/rdp_main_statusupdate_spec.js
- Enabled skipped tests in playbooks
- Removed `@cypress/skip-test` to prevent using it in the future
none
```release-note
NONE
```
> E2E: Enable skipped tests in playbooks

- webapp/channels/src/components/app_bar/app_bar.scss
Marketplace button in App bar is now responsive when RHS open
https://mattermost.atlassian.net/browse/MM-52439
```release-note
NONE
```
> MM-52439_MM-52439: New Marketplace icon on apps bar non-responsive when RHS open

- webapp/channels/src/components/autosize_textarea.tsx
We are getting an unknown-prop warning because we attempt to render a DOM element with a prop that is not recognized by React as a legal DOM attribute/property. Excluding this prop from the textarea props removed the warning.
https://mattermost.atlassian.net/browse/MM-50204
```release-note
NONE
```
> [MM-50204] - Don't pass invalid prop to textarea by advanced text editor

- .github/workflows/ci.yml
- .github/workflows/test.yml
Cache the dependencies correctly with the right path to go.sum file
```release-note
NONE
```
> Fix setup-go action

- webapp/boards/package.json
- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
- webapp/playbooks/package.json
I'm trying to do this early so that I don't have to make a change to the release branch after the release has been cut (see https://github.com/mattermost/mattermost-webapp/commit/3e848ac828834d3b2b145a54c9abbbdde243ad89).
The only ones of these that actually matter are the Client and Types packages since those are shipped on NPM, but we're going to just keep them all in sync for now
https://mattermost.atlassian.net/browse/MM-51562
```release-note
NONE
```
> MM-51562 Update package versions to 7.11.0

- webapp/channels/src/sass/responsive/_mobile.scss
Below a certain screen size, modals used to cover the whole screen, but when we changed that, we forgot to reduce the height of the `.modal-dialog` div to match that. Because it covered the whole screen, you couldn't tap below a modal to dismiss it since the tap wasn't considered "outside" the modal
MM-49937
| before (>= 640px) | before (< 640px) | after (< 640px) |
-|-|-
```release-note
Fix modals not closing when clicking below them on certain screen sizes
```
> MM-49937 Fix tappable area of modals on mobile

- server/channels/utils/utils.go
- server/channels/utils/utils_test.go
Add verification if the Trusted Proxy IP header is a valid ipv4/ipv6 address.
https://mattermost.atlassian.net/browse/MM-52366
```release-note
NONE
```
> [MM-52366] server/utils: verify trusted ip headers are valid ip addresses

- server/i18n/en.json
- server/model/config.go
- server/model/config_test.go
Now we do a `os.Stat` on local mode socket directory if local mode is enabled.
https://mattermost.atlassian.net/browse/MM-51329
```release-note
NONE
```
> [MM-51329] server/config: add validation for local mode socket file

- e2e-tests/cypress/tests/integration/channels/menus/status_dropdown_spec.js
Fix issue with MM-T2927_1 Should show all available statuses with their icons caused by https://github.com/mattermost/mattermost-server/pull/22941
Fixes https://mattermost.atlassian.net/browse/MM-52647
NA
```release-note
NONE
```
> [E2E]: Fix issue with MM-T2927_1 Should show all available statuses with their icons

- server/build/release.mk
It seems like we are searching for the manifest file in the wrong path in release.mk file:
```
if [ -f ../manifest.txt ]; then \
cp ../manifest.txt $(DIST_PATH); \
fi
```
This was working before because we were keeping the manifest.txt file in the project root. The project root is changed, but on the other hand we already copy the manifest file in bin directory. I think it should remain with the binaries in bin hence I think we should look for that file instead.
The current release pipelines are blocked because of this. So we need to cherry pick this into `release-v7.11` branch as well.
https://mattermost.atlassian.net/browse/MM-52659
```release-note
NONE
```
> [MM-52659] server/release: use the manifest file from bin directory

- server/channels/imports/boards_imports.go
- server/channels/imports/playbooks_imports.go
This reverts commit 76ad948b805696c6cc192a39725ec37d60c3541f. Without it, it looks like neither playbooks nor boards starts up correctly. 
None.
```release-note
NONE
```
> Revert "Remove unnecessary blank imports (#23283)"

- api4/command.go
- api4/command_test.go
- model/permission.go
Cherrypick of #22468
```release-note
NONE
```
> Cherrypick to 7.8 "Update slash command permission (#22468)"

- api4/command.go
- api4/command_test.go
- model/permission.go
Cherrypick of #22468
```release-note
NONE
```
> Cherrypick to 7.9 "Update slash command permission (#22468)"

- api4/command_test.go
There was a merge issue in `command_test` when cherrypicking to `release-7.10` https://github.com/mattermost/mattermost-server/commit/160428329ad41bc11c94d462affbd2425376ae73
```release-note
NONE
```
> Fix 7.10 merge issue from "Update slash command permission (#22468)"

- .github/workflows/ci.yml
- server/Makefile
Reverts mattermost/mattermost-server#23240
Revert for now since it's causing timeout errors in some PRs and git commands are failing. Refer: https://community.mattermost.com/core/pl/u59c6ouz8ifaufc9bomew6utcc
> Revert "Run golangci in server CI"

- server/channels/imports/boards_imports.go
- server/channels/imports/playbooks_imports.go
- server/cmd/mattermost/main.go
I mistakenly assumed that those packages are naturally imported.
And also atleast one test would have broken.
None of them are true. :)
So we just import it again at a better place
This reverts commit 30a053314b9611cc5dbe2d47a5d31bc7828165fc.
```release-note
NONE
```
> Remove unnecessary blank imports (round 2)

- web/context.go
We were logging directly the DetailedError field in 7.1 branch.
We fix that to log err.Error() which is how it is in master.
https://mattermost.atlassian.net/browse/MM-52216
```release-note
NONE
```
> MM-52216: Re-fix for release-7.1

- app/oauth.go
- app/oauth_test.go
- db/migrations/migrations.list
- db/migrations/mysql/000105_remove_tokens.down.sql
- db/migrations/mysql/000105_remove_tokens.up.sql
- db/migrations/postgres/000105_remove_tokens.down.sql
- db/migrations/postgres/000105_remove_tokens.up.sql
- i18n/en.json
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/oauth_store.go
- store/store.go
- store/storetest/mocks/OAuthStore.go
- store/timerlayer/timerlayer.go
Backporting fix from https://github.com/mattermost/mattermost-server/pull/22310 and the subsequent migration fix in https://github.com/mattermost/mattermost-server/pull/23036 for `postgres000105_remove_tokens.up.sql`.
As per our discussion in server platform I was asked to update the migrations for backports in order to avoid unnecessary table locks. I added some select statements in order to avoid running the `DELETE` queries if we don't need to.
**Migration timings on the large data dump:**
**MySQL@5.7.12:**
No data to delete:
`remove_tokens: migrated (0.0092s)`
Some data to delete:  
`remove_tokens: migrated (0.0172s)`
**Postgres@10:**
No data to delete:
`remove_tokens: migrated (0.0218s)`
Some data to delete:
`remove_tokens: migrated (0.0099s)` (This was faster for some reason?) …
> [MM-50219] Cherry picking oauth2 fix

- server/playbooks/server/api_runs_test.go
Racy test failed in master branch.
https://mattermost.atlassian.net/browse/MM-52694
```release-note
NONE
```
> MM-52694: Skip TestRunPostStatusUpdate

- e2e-tests/cypress/tests/integration/boards/channel_header_spec.ts
- e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
- webapp/boards/src/components/rhsChannelBoardsToggleIcon.tsx
- webapp/boards/src/index.tsx
- webapp/boards/src/widgets/icons/compassIcon.tsx
- webapp/boards/src/widgets/icons/logo.tsx
- webapp/playbooks/src/components/assets/icons/playbooks_product_icon.tsx
- webapp/playbooks/src/components/channel_header.tsx
Fixes Boards and Playbooks channel header button styling to match Channel Info styling.
https://mattermost.atlassian.net/browse/MM-51798
|----|----|
| ![CleanShot 2023-05-03 at 14 33 20](https://user-images.githubusercontent.com/11724372/236026169-7d4b13c3-43f3-49de-ad13-aa8628ac190a.gif) | ![CleanShot 2023-05-03 at 14 30 52](https://user-images.githubusercontent.com/11724372/236025607-5a9ff386-5f9e-44b8-a6b5-d7024781ebf9.gif) |
```release-note
NONE
```
> MM-51798: Fix Boards+Playbooks channel header RHS button styling 

- webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
- webapp/channels/src/components/post_edit_history/post_edit_history.tsx
- webapp/channels/src/components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx
A while ago, we introduced the PropsFromRedux pattern, which was mostly used in class-based components or functional components if hooks were not used for selectors and dispatch. However, we discussed that it is recommended to import the type PropsFromRedux back to the component file from its index file with the type to avoid any cyclic import bugs.
```js 
import type {PropsFromRedux} from './index'; ✔️ 
```
https://mattermost.atlassian.net/browse/MM-52695
```release-note
NONE
```
> [MM-MM-52695] webapp/channels : Change plain import of PropsFromRedux to "import type" for certain files

- webapp/boards/webpack.config.js
- webapp/playbooks/webpack.config.js
Node's `URL` sets its `port` field to the empty string when the URL is using a default port, even if you add `:443` to the end of an https URL, but Webpack Dev Server expects its `port` option to always have the actual number, so we have to do some extra negotiation to let the servers run on 80/443 for http and https respectively
```release-note
NONE
```
> Let Boards/Product dev servers run on default ports

- api4/user.go
- api4/user_test.go
- app/channel.go
- app/channel_test.go
- db/migrations/migrations.list
- db/migrations/mysql/000107_threadmemberships_cleanup.down.sql
- db/migrations/mysql/000107_threadmemberships_cleanup.up.sql
- db/migrations/postgres/000107_threadmemberships_cleanup.down.sql
- db/migrations/postgres/000107_threadmemberships_cleanup.up.sql
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/mocks/ThreadStore.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherrypick of #22559
```release-note
Fixed a bug where a user would still see threads, in threads view, of channels they have left.
Migration execution time in MySQL: Query OK, 2766769 rows affected (4 min 47.57 sec)
Migration execution time in PostgreSQL: Execution time: 58.11 sec, DELETE 2766690
```
> Cherrypick of #22559

- api4/user.go
- api4/user_test.go
- app/channel.go
- app/channel_test.go
- db/migrations/migrations.list
- db/migrations/mysql/000107_threadmemberships_cleanup.down.sql
- db/migrations/mysql/000107_threadmemberships_cleanup.up.sql
- db/migrations/postgres/000107_threadmemberships_cleanup.down.sql
- db/migrations/postgres/000107_threadmemberships_cleanup.up.sql
- model/utils.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/mocks/ThreadStore.go
- store/storetest/thread_store.go
- store/timerlayer/timerlayer.go
Cherrypick of #22559
```release-note
Fixed a bug where a user would still see threads, in threads view, of channels they have left.
Migration execution time in MySQL: Query OK, 2766769 rows affected (4 min 47.57 sec)
Migration execution time in PostgreSQL: Execution time: 58.11 sec, DELETE 2766690
```
> Cherrypick of #22559 into v7.1

- webapp/boards/src/components/sidebar/sidebarCategory.test.tsx
We see more tests from the same file fail
with the same error
https://mattermost.atlassian.net/browse/MM-52212
```release-note
NONE
```
> MM-52212: Skip all sidebarCategory tests

- webapp/package-lock.json
- webapp/package.json
The terminal filled up with engines not compatible "EBADENGINE" warning because we had hard set the values of node and npm. We had to add "^" symbol indicating that the version range includes any minor or patch version updates that are backwards-compatible with the specified version in dependencies package.json. The actual update of node will be separate.
https://mattermost.atlassian.net/browse/MM-52788
|----|----|
| <img width="871" alt="image" src="https://github.com/mattermost/mattermost-server/assets/17708702/aa5b8e82-b83a-452f-91f8-58e225ae3f0b"> | <img width="871" alt="image" src="https://github.com/mattermost/mattermost-server/assets/17708702/46400a14-8025-4421-9224-e4e87f863004"> |
```release-note
NONE
```
> [MM-52788] webapp : Fix the "EBADENGINE" warnings on npm console

- server/scripts/download_mmctl_release.sh
Going from `release-7.9` to `release-7.10,` has introduced a bug, in the `download_mmctl_release.sh` script, in which it is unable to match version numbers with multiple digits Specifically, `release-7.10` returns `release-7.1` downloading wrong mmctl binary.
We are refactoring the regular expression used, to match version numbers with multiple digits.
Before: 
```
> git rev-parse --abbrev-ref HEAD
release-7.10
> ./download_mmctl_release.sh
Downloading prepackaged binary: https://releases.mattermost.com/mmctl/release-7.1
```
After the fix: 
```
> git rev-parse --abbrev-ref HEAD
release-7.10
> ./download_mmctl_release.sh
Downloading prepackaged binary: https://releases.mattermost.com/mmctl/release-7.10
```
Ticket: https://mattermost.atlassian.net/browse/CLD-5682
```release-note
NONE
```
> [fix] download mmctl release script

- webapp/boards/package.json
- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
- webapp/playbooks/package.json
I'm doing this ahead of time so that I won't need to do it after the release branch gets cut. These version numbers only matter once we go to publish the non-private packages to NPM
https://mattermost.atlassian.net/browse/MM-52599
```release-note
NONE
```
> Bump JS package versions to 8.0.0

- e2e-tests/cypress/tests/integration/channels/messaging/image_attachment_spec.js
Fixes the failing tests in `image_attachmemt_spec.js`.
https://mattermost.atlassian.net/browse/MM-52523
```release-note
NONE
```
> Fixed image attachment e2e cypress test

- scripts/download_mmctl_release.sh
Related PR: https://github.com/mattermost/mattermost-server/pull/23488
```release-note
NONE
```
> fix: Fix mmctl binary download script with the correct version

- scripts/download_mmctl_release.sh
Related PR: https://github.com/mattermost/mattermost-server/pull/23488
```release-note
NONE
```
> fix: Fix mmctl download script to download the correct binary

- server/public/model/permission.go
https://github.com/mattermost/mattermost-server/pull/22819 introduce a regression, that causes server which import the load-test DB dump to fail on startup.
As part of the migrations that happen on every server start, all roles [get fetched from the store](https://github.com/mattermost/mattermost-server/blob/cfa5be4d3e0da608d0f0cb3cacc5925ce2a864b3/server/channels/app/permissions_migrations.go#L1140-L11449). These roles do contain the legacy permission `use_slash_commands`, as it's still in the DB.
Later, the roles [get saved in the DB](https://github.com/mattermost/mattermost-server/blob/cfa5be4d3e0da608d0f0cb3cacc5925ce2a864b3/server/channels/app/permissions_migrations.go#L231) again (which in most cases is a no-op). As part of that, [it's checked if the permissions of the role are …
> [MM-52574] Add back PermissionUseSlashCommands

- webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx
When the combined join/leave message component was changed recently, it became possible for multiple lines in that post to have the same actor, post type, and user ID, so the key we were using for them became non-unique. 
While it's usually a bad practice to use an index as a key, there's no truly unique identifier for these items, so we have to use that. That list of combined messages also isn't likely to be reordered often, so we're not really helping React's reconciliation process with a better key either
```release-note
NONE
```
> Fix duplicate keys in CombinedSystemMessage component

- webapp/channels/src/sass/components/_post.scss
- webapp/channels/src/utils/utils.tsx
During the big refactor of the post, we moved around some CSS rules that were meant to turn the bar to the left of replies to the user's mention colour when they were mentioned by that thread due to their Reply Mentions setting. This fixes that by rearranging the CSS, and I also took the chance to move that to being coloured with CSS variables
MM-52544
<details>
Light theme, reply mentions disabled:
Dark theme, reply mentions enabled:
Light theme, reply mentions enabled:
</details>
```release-note
Fixed reply bar not being highlighted when a user is mentioned by a reply because of their Reply Notifications setting
```
> MM-52544 Fix missing reply bar mention highlight

- server/channels/app/platform/config.go
- server/channels/app/platform/config_test.go
- server/channels/app/platform/service.go
This change should fix an issue where we are unnecessarily getting the total user count for every license request. We only need to know that they have at least 1 user. This var gets reset on server restart
```release-note
fix an issue where we are unnecessarily getting the total user count for every license request. We only need to know that they have at least 1 user
```
> Avoid calling the user count query in future if we get a count > 0

- server/channels/app/platform/config.go
- server/channels/app/platform/license.go
- server/channels/app/platform/service.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub_test.go
- server/channels/store/searchlayer/layer.go
`go1.19` added a typed [`atomic.Pointer`](https://pkg.go.dev/sync/atomic#Pointer). This PR makes use of this and covers some of the use of `atomic.Value` to a typed `atomic.Pointer`.
The remaining types used with an `atomic.Value` are `string` and `map`, which currently can't be typed without using a pointer.
None
```release-note
NONE
```
> Make used of typed atomic.Pointer

- e2e-tests/cypress/tests/support/ui/post.ts
Some of the failures in https://github.com/mattermost/mattermost-server/pull/23510#issuecomment-1568335023 seem to be caused because these tests look for the existence of a `post-pre-header` in the search results, but depending on the order that the E2E tests run, you can sometimes have a pinned post in the search results which is actually supposed to show a `post-pre-header`. So, in this PR, I made some of these selectors narrower to ensure that other tests don't break these tests
```release-note
NONE
```
> Make save_post_spec less affected by other E2E tests

- webapp/channels/src/actions/notification_actions.jsx
- webapp/channels/src/components/logged_in/logged_in.tsx
- webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.tsx
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
This PR cleans up the use of `window.desktop.version`, which was used for versions of the Desktop App before v5 to check for the version to turn functionality on or off.
As it stands, there's nothing that has used this since v5, and since v4.7 and before is no longer supported, removing this makes sense.
Going forward, we're going to implement a new Desktop API in the Web App to check to see if certain features are enabled or not.
https://mattermost.atlassian.net/browse/MM-52919
```release-note
NONE
```
> [MM-52919] Remove all uses of window.desktop.version from webapp

- server/public/model/config.go
Temporarily let `AdvancedLoggingConfig` take precedence over `AdvancedLoggingJSON`.  This addresses an issue where environment overrides for `AdvancedLoggingJSON` do not work because the override resolver does not support []byte (json.RawMessage), causing community to not get audit logging.
This will be undone asap via a PR that includes support for []byte in the override resolver.
NONE
```release-note
NONE
```
> Temporarily let AdvancedLoggingConfig take precedence over AdvancedLoggingJSON

- .github/workflows/esrupgrade-common.yml
It seems that the `/mattermost` path is the one used [in the image](https://github.com/mattermost/mattermost/blob/master/server/build/Dockerfile), and it somehow conflicted with the running process of the server here. I honestly am not sure why, but using any other path does seem to work.
I also downgraded the machine type in the `esr-upgrade-diff` job, since that's not compute-heavy at all.
https://mattermost.atlassian.net/browse/MM-53002
--
```release-note
NONE
```
> MM-53002: Fix ESR CI

- .github/workflows/ci.yml
Added ignore_missing flag for creating sentry release likely introduced by repo rename
```release-note
NONE
```
> ci/fix: add ignore_missing flag for creating sentry release likely introduced by repo rename

- server/channels/db/migrations/mysql/000092_add_createat_to_teammembers.up.sql
- server/scripts/esrupgrades/esr.6.3-7.8.mysql.up.sql
This PR fixes a typo in the migration script `000092_add_createat_to_teammembers.up.sql` that breaks idempotency.  The check for existence of index `idx_teammembers_create_at` is different than the index creation name `idx_teammembers_createat`
This is blocking a customer upgrade.
The fix is to make the names consistent, and the name will be `idx_teammembers_createat` to match the existing created indexes. 
https://mattermost.atlassian.net/browse/MM-53031
```release-note
Fixed typo in database migration scripts that broke idempotency.
```
> MM-53031  Fix typo in index name for idx_teammembers_create_at

- db/migrations/mysql/000092_add_createat_to_teammembers.up.sql
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/23632
This PR fixes a typo in the migration script `000092_add_createat_to_teammembers.up.sql` that breaks idempotency.  The check for existence of index `idx_teammembers_create_at` is different than the index creation name `idx_teammembers_createat`
This is blocking a customer upgrade.
The fix is to make the names consistent, and the name will be `idx_teammembers_createat` to match the existing created indexes. 
https://mattermost.atlassian.net/browse/MM-53031
```release-note
Fixed typo in database migration scripts that broke idempotency.
```
> Cherry-pick MM-53031 Fix typo in index name for idx_teammembers_create_at

- .gitlab-ci.yml
The docker CI image upgrade was already submitted [in this MR](https://git.internal.mattermost.com/ci/bundle/-/merge_requests/65), but actually the `IMAGE_BUILD_DOCKER` in this repo overrides the variables of the same name in any downstream multi-project pipelines (eventually leading to [this issue](https://git.internal.mattermost.com/ci/bundle/-/jobs/1567540)), bringing docker back to `19.03.14` despite the above MR.
This PR should finally bring the change we need to the release pipeline.
https://mattermost.atlassian.net/browse/CLD-5770
```release-note
NONE
```
> CLD-5770 - Upgrade docker CI image to 23.0.1

- e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/open_thread_dm_spec.js
- webapp/channels/src/components/post/post_component.tsx
Fixes an issue when opening a thread in a DM/GM channel from the reply button in thread footer (CRT=ON) where the root post would be highlighted instead of the thread opening in RHS.
- Fixes https://mattermost.atlassian.net/browse/MM-52995
Before:
https://github.com/mattermost/mattermost/assets/11724372/26382992-59ef-4903-84a8-67af1645e949
After:
https://github.com/mattermost/mattermost/assets/11724372/a8d10557-9124-4753-83e6-73586c958108
```release-note
NONE
```
> MM-52995: Fix opening DM/GM thread from thread footer

- .gitlab-ci.yml
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/23664
https://mattermost.atlassian.net/browse/CLD-5770
```release-note
NONE
```
> Upgrade docker CI image to 23.0.1 (#23664)

- server/scripts/esrupgrades/esr.5.37-7.8.mysql.up.sql
There's a customer that reported that this `UPDATE` was taking ages to finish, even when it was useless, since there was no matching rows to update. According to their report, the SELECT with the same filter was orders of magnitude faster.
We offered this workaround, and they're running it with this patch, so we should merge it into master, or at least have a discussion around it.
As for the impact of this in the script: I was not able to reproduce the behaviour reported by the customer in the first place, but I didn't see any negative impact either, so I don't think it's harmful.
--
--
```release-note
NONE
```
> Fine-tuning the ESR2ESR migration script

- server/Makefile
- server/channels/store/storetest/settings.go
- server/scripts/test-xprog.sh
- server/scripts/test.sh
In the course of preparing https://github.com/mattermost/mattermost/pull/22826, I realized my server-side tests were running 3x faster. Thinking something was perhaps wrong, I narrowed it down to my ripping out the already unused coverage. 
To prove the effect, I pulled out those changes into this PR, turning off the collection of coverage data when running the Go server tests, and reducing the runtime of the test suite from ~30m to ~10m. That's ~60m of `ubuntu-latest-8-cores` usage per build!!
As part of this, bump the `settings.MigrationsStatementTimeoutSeconds` from `10s` to `60s` only when running tests to work around performance issues with the CI runners, e.g.:
```
driver: mysql, message: failed when applying migration, command: apply_migration, originalError: context deadline …
```
> disable coverage

- .github/workflows/docker-push-mirrored.yml
- .github/workflows/e2e-tests-ci.yml
- e2e-tests/.ci/.e2erc
- e2e-tests/.ci/.env.cypress
- e2e-tests/.ci/.env.dashboard
- e2e-tests/.ci/.env.server
- e2e-tests/.ci/.gitignore
- e2e-tests/.ci/dashboard.entrypoint.sh
- e2e-tests/.ci/dashboard.override.yml
- e2e-tests/.ci/dashboard.start.sh
- e2e-tests/.ci/dashboard.stop.sh
- e2e-tests/.ci/server.override.yml
- e2e-tests/.ci/server.prepare.sh
- e2e-tests/.ci/server.run_cypress.sh
- e2e-tests/.ci/server.start.sh
- e2e-tests/.ci/server.stop.sh
- e2e-tests/.gitignore
- e2e-tests/Makefile
- e2e-tests/README.md
- e2e-tests/cypress/package-lock.json
- e2e-tests/cypress/tests/support/index.js
- server/build/gitlab-dc.common.yml
- server/build/gitlab-dc.mysql.yml
- server/build/gitlab-dc.postgres.yml
- server/build/gitlab-dc.schemamysql.yml
- server/build/gitlab-dc.schemapostgres.yml
- server/scripts/mirror-docker-images.json
- server/scripts/mirror-docker-images.sh
This PR reintroduces the Github Actions E2E smoketests originally added by https://github.com/mattermost/mattermost/pull/23301 , but fixes the first PR's problem which prevented the full E2E tests from running.
The root cause was the change to the docker-compose file networking, which was not expected by the currently existing E2E test run scripts. That has been addressed in this PR.
tl;dr of the changes compared to https://github.com/mattermost/mattermost/pull/23301 :
- Fix the root cause of the revert: do not change the docker-compose networking that E2E scripts currently rely on.
- Use Docker Hub as a registry, for the images required by E2E tests
* Due to parallelism, we incurred in docker's [infrastructural rate limits](https://docs.docker.com/docker-hub/download-rate-limit/#other-lim …
> CLD-5698 - Add e2e smoketests

- utils/imgutils/gif.go
- utils/imgutils/gif_test.go
* MM-52720: use an io.LimitedReader in gif frame counting
* Address review feedback
---------
```release-note
NONE
```
> MM-52720: use an io.LimitedReader in gif frame counting (#23372)

- webapp/channels/src/actions/views/profile_popover.test.ts
- webapp/channels/src/actions/views/profile_popover.ts
- webapp/channels/src/components/profile_popover/index.ts
- webapp/channels/src/components/profile_popover/profile_popover.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/teams.ts
This PR is to salvage the parts of #23628 that we want to keep since we decided not to make those functional changes
None
```release-note
NONE
```
> Migrate actions/views/profile_popover to TS

- server/channels/app/migrations.go
- server/public/model/feature_flags.go
Remove use case onboarding feature flag that is no longer used. Currently, the full-screen onboarding is only shown for the first admin the first time they start a new server. 
https://mattermost.atlassian.net/browse/MM-53085
```release-note
NONE
```
> Remove use case onboarding feature flag

- webapp/channels/src/components/post/user_profile.tsx
- webapp/channels/src/components/post_view/commented_on/__snapshots__/commented_on.test.tsx.snap
- webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
- webapp/channels/src/components/user_profile/user_profile.test.tsx
- webapp/channels/src/components/user_profile/user_profile.tsx
- webapp/channels/src/utils/constants.tsx
This PR sets the default value for the username color using the theme provided value replacing the hardcoded values (#000000) which was causing the system messages not displaying correctly in dark themes.
https://mattermost.atlassian.net/browse/MM-52259
Before:
*Dark theme:
*Light Theme:
After:
```release-note
NONE
```
> Mm 52259 system message ignore colorize

- webapp/channels/src/components/dropdown_input.scss
This dropdown input component wasn't displaying correctly when certain dark mode themes were activated because its default styles were not overridden by the theme variables. 
Before:
After:
```release-note
None
```
> [MM-52986] Add theming support to one of the dropdown input components

- e2e-tests/cypress/tests/fixtures/markdown/markdown_inline_images_6.md
- e2e-tests/cypress/tests/integration/channels/files_and_attachments/image_link_preview_new_window_spec.js
- e2e-tests/cypress/tests/integration/channels/files_and_attachments/image_link_preview_spec.js
- e2e-tests/cypress/tests/integration/channels/integrations/slash_commands_spec.js
- e2e-tests/cypress/tests/integration/channels/markdown/markdown_image_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/inline_images_open_preview_window_spec.js
Fixed failed e2e tests
https://mattermost.atlassian.net/browse/CLD-5824
Found at https://github.com/mattermost/mattermost/pull/23660
```release-note
NONE
```
> Cypress/E2E: Fixed failed e2e tests

- server/channels/app/platform/service.go
- server/channels/app/platform/service_test.go
- server/platform/services/telemetry/telemetry.go
We need to regenerate client config immedeately after we update the diagnostic ID (ie. telemetry ID) as there is a possibilty we don't compute client config for a while and this makes client config to miss diagnostic ID.
https://mattermost.atlassian.net/browse/MM-53195
```release-note
NONE
```
> [MM-53195] services/telemetry: regen client config right after assigning diagnostic ID to platform

- server/build/docker-compose.yml
- server/build/gitlab-dc.mysql.yml
- server/build/gitlab-dc.postgres.yml
Don't list Prometheus and Grafana as targets in the `start_dependencies` target of the docker compose file used in CI and local development. These can still be started by hand, but will no longer waste resources in CI, nor fail builds spuriously if they fail to come online.
Most relevantly, fixes this:
None.
```release-note
NONE
```
> Don't start grafana/prometheus by default

- server/config/diff_test.go
- server/public/model/config.go
Boards should be default enabled for 6.29 cloud release. 
This will need to be reverted from release-8.0 after creation from cloud release.
Fixes https://mattermost.atlassian.net/browse/MM-53289
```release-note
NONE
```
> MM-53289 Default boards to be on.

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Adds stricter checks before accessing post permalink embed data post id, basically following whats being done in other location. I couldn't reproduce the bug llocally amd am still thinking of scenarios where this could occur, but meanwhile adding stricter checks before accessing values.
https://mattermost.atlassian.net/browse/MM-53138
```release-note
NONE
```
> Added debug log for missing post id in embedded permalink

- webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.test.tsx
- webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.tsx
- webapp/channels/src/components/user_settings/notifications/index.ts
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.test.tsx
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
- webapp/channels/src/selectors/calls.ts
- Because we'll be shipping Calls ringing in 8.0 without mobile support, we want to have a kind of 'feature flag' which will default off for now.
- This PR looks at that value from the calls plugin, if it exists, and turns on/off the calls ringing desktop notifications settings accordingly.
/cc @amyblais This feature flags the calls ringing notification setting, so I think it's low risk enough for 8.0 branch, if that's ok with you?
- https://mattermost.atlassian.net/browse/MM-53274
- Related Calls PR: https://github.com/mattermost/mattermost-plugin-calls/pull/449
```release-note
NONE
```
> MM-53274 - Add a "feature flag" for Calls ringing

- webapp/channels/src/actions/emoji_actions.js
- webapp/channels/src/actions/emoji_actions.test.js
- webapp/channels/src/actions/post_actions.test.ts
- webapp/channels/src/actions/post_actions.ts
Previously, we just updated the user preference that stores recent emojis once for each emoji that a user posted. That was fine when recent emojis were stored in browser storage, but since we store those on the server now, we should batch them into a single request to avoid spamming the server with multiple requests
https://mattermost.atlassian.net/browse/MM-53164
```release-note
Batch updates to recent emojis when multiple emojis are posted at once
```
> MM-53164 Batch adding multiple custom emojis when making a post

- server/Makefile
https://github.com/mattermost/mattermost/pull/23345 moved the `public` directory under the new `public` go module. This broke the `pluginapi` make target, as it doesn't pick up the `//go:generate` directives any longer.
I suppose the reason is the newly added go module. This PR fixes the issue by running `go generate` from inside the `public` module.
https://mattermost.atlassian.net/browse/MM-53254
```release-note
NONE
```
> [MM-53254] Fix make pluginapi

- server/channels/app/platform/searchengine.go
- server/platform/services/searchengine/bleveengine/bleve.go
- server/platform/services/searchengine/interface.go
- server/platform/services/searchengine/mocks/SearchEngineInterface.go
During some investigation of Elasticsearch issues, I found out that the Elasticsearch engine wasn't properly booting on a server restart. Putting a breakpoint on the `Start()` method of the engine showed that this was only called on a configuration or license change (as it should be), but the initial call wasn't going through because the `IsActive()` checks for the engine to be enabled, and the `Start()` method takes care of that (but it's never called). 
I've added a new method to the interface `IsEnabled()` that will return if the engine is enabled regardless if it is currently running or not.
https://mattermost.atlassian.net/browse/MM-52943
--
```release-note
fix: properly start elasticsearch on startup if enabled
```
> [MM-52943] fix: enable Elasticsearch properly on restart

- webapp/channels/src/sass/components/_scrollbar.scss
- webapp/channels/src/utils/utils.tsx
On https://github.com/mattermost/mattermost/pull/23604 I removed a scrollbar css that was creating conflict that was not supposed to be removed, but changed. This caused the scrollbar not showing as it should on certain themes (specially dark ones). I brought it back with the correct values and now it is applying the right color and it is not conflicting.
https://mattermost.atlassian.net/browse/MM-53225
Since this is going to release along #23604 , those are the release notes to be used.
```release-note
NONE
```
> Fix scrollbar color on Chrome

- webapp/channels/src/components/edit_category_modal/edit_category_modal.tsx
- webapp/channels/src/components/modal_controller/modal_controller.tsx
- webapp/platform/components/src/generic_modal/generic_modal.tsx
A customer reported that while creating a new category using Korean characters, two categories were created instead of one. Also, it was reported that sometimes dbl-clicking quickly the Create Category button would end in the creation of two categories. During investigation it was found that dbl-enter keypress will also trigger the creation twice.
The root cause of the Korean characters issue is because the IME ([Input Method Editor](https://www.w3.org/TR/ime-api/#background)) used for Korean input, you can notice that when using Korean keyboard while you type several characters together it kind of waits and then summarize those chars and enters a Korean syllable in the place of the other characters. This means that keystrokes are entered and depending on which chars it creates a Korean …
> MM-51676 - korean chars create duplicate categories

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
If the request is routed via bifrost, then we need to encode the path
to avoid signature validation errors.
This happens because in bifrost, we are signing the URL outside the SDK
and therefore the signature sent from the bifrost client
will contain the encoded path, whereas the original path is sent un-encoded.
More info at: https://github.com/aws/aws-sdk-go/blob/a57c4d92784a43b716645a57b6fa5fb94fb6e419/aws/signer/v4/v4.go#L8
https://mattermost.atlassian.net/browse/MM-51753
```release-note
NONE
```
> MM-51753: URL encode the file path in S3 uploads

- webapp/channels/src/components/markdown_image_expand/index.ts
- webapp/channels/src/components/markdown_image_expand/markdown_image_expand.test.tsx
- webapp/channels/src/components/markdown_image_expand/markdown_image_expand.tsx
In a community PR https://github.com/mattermost/mattermost/pull/23524 it was discovered we didn't type the component MarkdownImageExpand.
QA:
Verify images are correctly expanded and collapsed in Center or RHS
n/a
n/a
```release-note
NONE
```
> Fix prop types for "markdown_image_expand" component

- api/v4/source/introduction.yaml
With api.mattermost.com now being hosted in the monorepo, update a few missed links in the documentation -- and test that the deployment work as expected!
None.
```release-note
NONE
```
> Update API repo links

- server/channels/app/notification_test.go
Manually sets the license expected for a bunch of tests instead of relying on the resulting state from the previous test
https://mattermost.atlassian.net/browse/MM-41972
```release-note
NONE
```
> Set license for group mentions flaky test

- webapp/channels/src/packages/mattermost-redux/src/store/configureStore.ts
- webapp/channels/src/stores/redux_store.jsx
[Redux DevTools](https://github.com/reduxjs/redux-devtools) gives developers and users insight into the client-side state of the Mattermost application. Instead of restricting this to developer builds, allow it for production builds too, simplifying debugging when an issue reproduces in production but not in a development environment.
There is no performance overhead unless the devtools are installed and opened by the enduser. There should be no security impact, since all this information is already client-side. Furthermore, major websites expose Redux in production: e.g. https://cbc.ca and https://medium.com/.
While we're in here, remove the community-specific override that allow direct access to the store via `window.store`. This doesn't help outside of this one instance, and is now …
> enable redux-devtools in all environments

- server/public/model/post_metadata.go
This PR fixes a receiver name mismatch for method `Postmetadata.Auditable` introduced by https://github.com/mattermost/mattermost/pull/23745.  
**This was caught via linter check for 7.x release branches, but is not caught by master linter settings.**
@amyblais this is already applied to 7.8, 7.9, 7.10 via cherry-picks for the original PR.
NONE
```release-note
NONE
```
> Fix mismatched receiver name on method PostMetadata.Auditable

- server/config/diff_test.go
- server/public/model/config.go
This PR reverts https://github.com/mattermost/mattermost/pull/23819, as boards is expected to be default on for the cloud release but off for `v8`
https://mattermost.atlassian.net/browse/MM-53290
```release-note
NONE
```
> Disable boards by default in v8

- server/channels/app/notify_admin_test.go
Removes skipping from the `SendNotifyAdminPosts` test. The data race seems to be related to the boards product startup, which is not part of the tests anymore. I've tried to reproduce it with no success in the current `master`, so proposing to simply reenable the test.
https://mattermost.atlassian.net/browse/MM-52743
```release-note
NONE
```
> Disable skipping SendNotifyAdminPosts test

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Deleting entire embed object instead of only it's data when its a permalink embed and user doesn't have access to the linked post.
Also removed debug logs from webapp added previously for debugging this issue.
```release-note
NONE
```
> Fixed a bug that prevent post deletion

- server/channels/api4/user_test.go
- server/public/model/user.go
Don't allow `deleteAt` field to be set when creating a new user
Fixes https://mattermost.atlassian.net/browse/MM-53427
```release-note
NONE
```
> MM-53427 - don't allow deletedAt to be set when creating user

- server/channels/app/server.go
- server/channels/app/server_test.go
The UpdateProductNotices method runs in a separate goroutine
which modifies a global structure called noticesCache.
This creates race condition when one test finishes
but the goroutine hasn't finished running.
To fix this, we simply prevent the spawning of the goroutine
by disabling the feature in the config.
Ideally, we'd not have global state in the first place.
But that's a separate matter.
https://mattermost.atlassian.net/browse/MM-52646
```release-note
NONE
```
> MM-52646: Fix data race on product notices

- model/config.go
- model/feature_flags.go
- services/telemetry/telemetry.go
https://github.com/mattermost/mattermost/pull/23927
https://mattermost.atlassian.net/browse/MM-53466
```release-note
New feature flag, DataRetentionConcurrencyEnabled, to enable/disable concurrency for data retention batch deletion. New config  DataRetentionSettings.TimeBetweenBatchesMilliseconds to control the sleep time between batch deletions.
```
> [MM-53466] Release-7.8 cherry pick

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
We've found some cases where this change meant that certain fields which are only set for the current user object are erased because the user is replaced by a sanitized version of the object like others would receive. The most difficult case that causes the most issues here is the `auth_service` field which track's the user's login method. That field is sanitized to be the empty string, but it's also the empty string if the user uses email/password login, so we can't differentiate between the two cases to merge the objects smartly.
We'll hopefully reintroduce this code shortly, but for the time being, we're reverting it.
https://mattermost.atlassian.net/browse/MM-53377
https://mattermost.atlassian.net/browse/MM-53216
https://mattermost.atlassian.net/browse/MM-53422
```release-note
Revert …
```
> MM-53377 Revert "[MM-52547] Include current user profile in every redux action (#23219)"

- e2e-tests/cypress/tests/integration/channels/plugins/marketplace/disabled_remote_marketplace_spec.js
- e2e-tests/cypress/tests/integration/channels/plugins/marketplace/invalid_marketplace_url_spec.js
- e2e-tests/cypress/tests/integration/channels/plugins/marketplace/ui_spec.js
- e2e-tests/cypress/tests/integration/channels/plugins/plugin_buttons_spec.js
- e2e-tests/cypress/tests/integration/channels/plugins/upgrade_spec.js
- e2e-tests/cypress/tests/integration/channels/system_console/search_box_not_cloud_spec.js
- Added @plugins_uninstall metadata to sort it last during run
Note: Updated the filter in CI - https://git.internal.mattermost.com/qa/cypress-ui-automation/-/commit/1ca476ec81645ec980e202ef4b20025e731f8cb0 (to be cherry-picked into `e2e-daily` and `e2e-release`)
https://mattermost.atlassian.net/browse/CLD-5934
```release-note
NONE
```
> CLD-5934 Cypress/E2E: Add @plugins_uninstall metadata to sort it last during run

- .github/workflows/server-ci-master.yml
- .github/workflows/server-ci-pr.yml
- .github/workflows/server-ci-template.yml
Leverage `secrets: inherit` to make the secret available for reporting flaky test back to https://community.mattermost.com.
See discussion at https://community.mattermost.com/core/pl/ws4kz3746frjzj7o43uib487fe.
```release-note
NONE
```
> secrets: inherit, to fix flaky tests report

- server/public/LICENSE.txt
Add missing Apache 2.0 License to `public` submodule, both clarifying usage and explicitly signalling same to https://pkg.go.dev/github.com/mattermost/mattermost/server/public.
None.
```release-note
Add Apache 2.0 license to public submodule
```
> add Apache 2.0 license to public submodule

- server/channels/app/app_iface.go
- server/channels/app/channel.go
- server/channels/app/channel_test.go
- server/channels/app/export_test.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/post.go
In a single createPost flow, there were
3 separate calls to App.IsCRTEnabled. This
showed up very slightly in the CPU profiles.
Not a big deal, but good to get it out of
the way.
```release-note
NONE
```
> Reduce number of calls to IsCRTEnabled

- server/channels/store/sqlstore/user_store.go
For MySQL, a query for type LEFT JOIN .. IS NULL
leads to a nested antijoin which leads to poor performance.
We fix this by rewriting the query to avoid the antijoin.
See the JIRA epic for more context behind this.
We also make another improvement to remove the DISTINCT
clause. It didn't serve any purpose since userids would
already be unique.
https://mattermost.atlassian.net/browse/MM-53406
```release-note
NONE
```
> MM-53406: Fix userstore.count to avoid antijoin

- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
When trying to send an `@here` (or other global mention) in the RHS, if you press Enter without blurring the post box, it would keep your draft when the message was sent.
This is being caused by the state updating when the textbox is blurred after pressing Enter. The component is supposed to save the draft as is when it's blurred, but only if the post is not mid-submission.
The fix here was then to have the component still be in "submitting" state while the modal was open, and only clear it if the message was chosen not to be sent.
https://mattermost.atlassian.net/browse/MM-53430
```release-note
Fix an issue where the draft would persist after sending an `@here` mention in the RHS
```
> [MM-53430] Don't stop the `isDraftSubmitting` flow when the notification modal is popped

- webapp/.gitignore
- webapp/Makefile
We removed this at some point after the monorepo migration because we no longer needed to upload the web app as an artifact, but our customization docs refer to using that to customize the web app.
```release-note
NONE
```
> Re-add package target to web app Makefile

- e2e-tests/cypress/tests/integration/channels/account_settings/profile/mm_53377_regression_test_spec.js
- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
This is blocked on https://github.com/mattermost/mattermost/pull/23912 since it reverts that while fixing the regression that it caused. Those now-unreverted fixes were about ensuring that the current user object would be updated by without refreshing (see https://mattermost.atlassian.net/browse/MM-52546).
Unfortunately, that caused the web app to lose privileged information that it had about the current user (first_name, last_name, email, auth_service) because it would be overwritten by values coming from sanitized versions of the user object. With the changes that were added, some of the ways this could happen are as simple as:
1. Having a GM channel in your LHS
2. Seeing yourself in the at mention autocomplete
We always sanitize user objects before sending them to the client, but we …
> MM-53467 Unrevert changes that update current user object

- e2e-tests/.ci/server.override.yml
- server/i18n/en.json
While debugging smoketest failures, I noticed a small inconsistency in the usage of the `MM_SERVICEENVIRONMENT` variable: it is defined only for the `server` container, but is actually essential also for the `utils` container, since that's the container that generates the configuration for the server (which is impacted by that variable's value).
Note that specifying the variable value is a no-op: this PR sets it to its default value for the test builds (same as for the server container) so setting it has actually zero effect. However it's important to know of its impact within that file, thus it's valuable to set it explicitly for discoverability reasons. E.g. if we need to change it for testing, having it explicitly set makes it easier not to forget it must be changed for the utils …
> Debug smoketests

- webapp/channels/src/components/toast_wrapper/toast_wrapper.tsx
`atBottom` is set to null the first time we enter the channel, because some logic seems to rely on it being null, according to a comment.
Nevertheless, in many places we were checking `!atBottom` when in reality, the app is not at bottom only when `atBottom === false`.
This PR fixes the issue and (I think) other potential issues around the same code.
Nevertheless, a refactoring on this would be great to make it more understandable.
Fix https://mattermost.atlassian.net/browse/MM-53242
```release-note
Fix issue where the "New messages" toast appear on channels that were completely visible.
```
> Fix New Messages toast showing when it should not

- server/channels/app/emoji.go
- server/channels/app/emoji_test.go
- server/channels/app/post_metadata.go
- server/channels/store/localcachelayer/emoji_layer.go
- server/channels/store/localcachelayer/emoji_layer_test.go
- server/channels/store/localcachelayer/main_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/emoji_store.go
- server/channels/store/store.go
- server/channels/store/storetest/emoji_store.go
- server/channels/store/storetest/mocks/EmojiStore.go
- server/channels/store/timerlayer/timerlayer.go
There was already a cache present for emoji names. But we weren't using
it for the GetMultipleByName method. Now we implement that method
to look up the cache for every emoji name passed.
Secondly, a bigger problem was that we were making the DB call for system
emojis as well. Since system emojis aren't stored in the DB, it would
fall through the cache layer and always make a redundant DB call. In the
profiles, this should up as taking 16% of the total time to serve
a getPostsForChannel API endpoint.
We fix this by filtering the emojis to only custom emojis
before making the call.
https://mattermost.atlassian.net/browse/MM-53669
```release-note
NONE
```
> MM-53669: Use the cache layer for EmojiStore.GetMultipleByName

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
We do a check to see if a non-encoded path is present
or not, and in that case, choose not to encode it.
This accrues an additional StatFile call. But after
we have encoded all paths to the new style, we will
get rid of this.
https://mattermost.atlassian.net/browse/MM-53709
```release-note
NONE
```
> MM-53709: Handle older non-encoded paths in bifrost

- server/i18n/en.json
Update minimum required Edge version to v112+ as the minimum supported Chrome version was recently updated to v112+. Chrome and Edge are using the same code base and they normally need to be on the same version.
```release-note
Update minimum required Edge version to 112+.
```
> Update minimum supported Edge version

- .github/workflows/mmctl-test-template.yml
- .github/workflows/server-ci-template.yml
- server/go.mod
- server/go.sum
During development of the public/ submodule, a replace directive remained that was both unnecessary and harmful as discussed in https://community.mattermost.com/private-core/pl/w77sh7igwpfb9ecj5o4jjjbbyo.
Remove that, and bump the explicit dependency (even though we use go.work) to v0.0.6 so the import paths match (e.g. `mattermost` vs `mattermost-server`).
None.
```release-note
NONE
```
> drop public submodule replace directive

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
Now that we have identified the true fix
from Bifrost side, we will slowly revert
the changes that have happened.
Starting with this first fix, we will revert
to writing out non-encoded paths while still
doing the double read. This will break uploading
files with + for a short while, and then
the new Bifrost fix should fix that as well.
https://mattermost.atlassian.net/browse/MM-53747
```release-note
NONE
```
> MM-53747: Bifrost: write original paths

- server/channels/testlib/store.go
- server/public/model/migration.go
The rename is needed to allow the fix to rerun as the fix in previous patch didn't do the job in a case.
https://mattermost.atlassian.net/browse/MM-49257
```release-note
NONE
```
> Renamed channel index fix migration key

- Makefile
Prepackage boards 7.8.8
```release-note
Prepackage boards 7.8.8
```
> Prepackage boards 7.8.8

- .github/workflows/e2e-tests-ci.yml
- e2e-tests/.ci/server.run_cypress.sh
Uploading of smoketest run results (including debug-level server logs and screenshot of failures), for better debuggability whenever it fails.
Example with failing test cases (so that screenshots are included): https://github.com/mattermost/mattermost/actions/runs/5625322158
Indirectly related, this is the investigation that prompted this improvement: https://mattermost.atlassian.net/browse/CLD-6003
```release-note
NONE
```
> CLD-6003 - Upload smoketest results, better server logs

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
Now that we have identified the true fix
from Bifrost side, we will slowly revert
the changes that have happened.
Starting with this first fix, we will revert
to writing out non-encoded paths while still
doing the double read. This will break uploading
files with + for a short while, and then
the new Bifrost fix should fix that as well.
https://mattermost.atlassian.net/browse/MM-53747
```release-note
NONE
```
> Cherry pick: MM-53747: Bifrost: write original paths (#24079)

- webapp/channels/src/components/profile_popover/profile_popover.tsx
- webapp/channels/src/i18n/en.json
Fixing unnecessary line break
Fixes https://github.com/mattermost/mattermost/issues/24092
Jira https://mattermost.atlassian.net/browse/MM-53776
|----|----|
| <img width="245" alt="Screenshot 2023-07-22 at 18 02 17" src="https://github.com/mattermost/mattermost/assets/37421564/4a574402-63c5-477f-a75f-35671c283203"> | <img width="245" alt="Screenshot 2023-07-22 at 17 53 27" src="https://github.com/mattermost/mattermost/assets/37421564/57f4b348-c351-4a93-9fab-448492e8b10f"> |
```release-note
UI bug fixed in the bot profile popover
```
> MM-53776: BOT Profile popover - fix line break 

- webapp/channels/src/components/suggestion/modal_suggestion_list.tsx
- webapp/channels/src/utils/utils.tsx
Removed closest parent util function in favour of now [closest](https://caniuse.com/element-closest) dom method.
https://mattermost.atlassian.net/browse/MM-53230
```release-note
NONE
```
> MM-53230 : Remove custom polyfilled 'getClosestParent' with browser 'closest'

- webapp/channels/src/actions/global_actions.tsx
- webapp/channels/src/components/channel_info_rhs/menu.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
- webapp/platform/client/src/client4.ts
This PR is a follow up to https://github.com/mattermost/mattermost/pull/23793 and is intended to go to v8.0 where the query that was causing the original problem will be fixed. The intention of this PR is to prevent fetching the fileCount unnecessarily from some other places like the system console or when adding/removing users from a channel where this data is not needed.
https://mattermost.atlassian.net/browse/MM-53237
https://github.com/mattermost/mattermost/assets/10082627/ebddeedc-63c6-4eb0-b5a4-f36cb88d00e1
```release-note
NONE
```
> MM52237 - prevent fetching fileCount from unnecessary places

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
Full context can be found in the thread attached to the issue. The gist is that tracking connections with no connection ID is a bit hard if not impossible so I am including that info for next time we need to debug ws related issues.
https://mattermost.atlassian.net/browse/MM-53821
```release-note
NONE
```
> [MM-53821] Include connection ID in webconn related logs

- e2e-tests/cypress/tests/integration/channels/messaging/post_pre_header_spec.js
- webapp/channels/src/components/post/post_component.tsx
A change I made recently [here](https://github.com/mattermost/mattermost/pull/23649) caused an issue where the Saved Posts section would not show the Channel/Team names at all.
This PR restores those specifically for the Saved Posts view.
https://mattermost.atlassian.net/browse/MM-53636
-->
```release-note
Fixed an issue where the Saved Posts section would not show the channel and team names
```
> [MM-53636] Add channel/team name back for the Saved Posts view

- .github/workflows/server-test-template.yml
GitHub actions' YAML supports the `>` directive to a multi-line command to be merged into a single line, but requires that all segments have no leading whitespace otherwise they get silently ignored.
Since this is not nearly as obvious as one might expect, fallback to just the `|` syntax using `\` to extend the lines and keep the overall formatting, fixing the reporting of retried tests via curl webhook.
None.
```release-note
NONE
```
> Use | and \ vs. >

- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000110_update_vacuuming.down.sql
- server/channels/db/migrations/mysql/000110_update_vacuuming.up.sql
- server/channels/db/migrations/postgres/000110_update_vacuuming.down.sql
- server/channels/db/migrations/postgres/000110_update_vacuuming.up.sql
After some analysis of vacuuming statistics of our large
Postgres customers, it was observed that the default vacuuming
thresholds for some tables are not optimal enough for our workload.
We need more frequent vacuuming for some tables. The analysis
showed that the top 4 tables that needed rectification
were posts, preferences, threadmemberships and fileinfo.
So we reduce the threshold by half for those tables, triggering
autovacuum and autoanalyze doubly often.
```release-note
NONE
```
> Update vacuuming parameters for some tables

- .github/workflows/server-ci-template.yml
Now that the API source is part of the monorepo, this is already handled by the new api workflow, and can simply be removed.
None.
```release-note
NONE
```
> remove legacy "Build API specification" workflow

- server/channels/app/platform/service.go
- server/platform/shared/filestore/filesstore.go
- server/platform/shared/filestore/s3store.go
This PR:
- ensures that the export filestore will not use Bifrost
- Adds an INFO log at startup to let admins we are using a dedicated filestore for exports
https://mattermost.atlassian.net/browse/MM-53881
```release-note
NONE
```
> [MM-53881] Make sure export filestore won't use bifrost

- server/channels/app/plugin.go
This reverts 0af0a4eff45b133fb36496a73b839f55005aae02. During the [implementation](https://github.com/mattermost/mattermost/pull/15910) of the original change we [discussed](https://github.com/mattermost/mattermost/pull/15910#issuecomment-705925227) fixing the underlying issue. When we did [fix](https://github.com/mattermost/mattermost/pull/15949) the underlying issue, we didn't revert these changes.
Revert it now to simplify the code in anticipation of more changes to come re: pre-packaged plugins.
I've tested in the linked Setup Cloud Test Server, verifying that a prefix is configured:
and then that a plugin can be installed and activated from the marketplace:
None.
```release-note
NONE
```
> Revert s3 path prefix normalization for plugins

- server/channels/app/platform/service.go
- server/channels/app/plugin_api_tests/test_db_driver/main.go
- server/channels/store/localcachelayer/layer_test.go
- server/channels/store/searchlayer/layer_test.go
- server/channels/store/sqlstore/migrate_test.go
- server/channels/store/sqlstore/store.go
- server/channels/store/sqlstore/store_test.go
- server/channels/testlib/helper.go
- server/cmd/mattermost/commands/db.go
- server/cmd/mattermost/commands/init.go
- server/platform/services/searchengine/bleveengine/bleve_test.go
If the store fails to initialize (e.g. run a migration), it would `log.Fatal` and then `os.Exit`. Unfortunately, this trips up `TestMain`, which happily keeps running tests, now guaranteed to fail:
Avoid this by instead returning an error from the store initialization, handling appropriately at the layer above. Now the migration failure happens immediately:
None.
```release-note
NONE
```
> Fail vs. fatal on store startup

- e2e-tests/.ci/.e2erc
Adapt the E2E testing scripts to be runnable on MacOS as well.
This would benefit both users that want to run the tests locally, and also enables the Desktop E2E tests for MacOS to reuse these scripts.
https://mattermost.atlassian.net/browse/CLD-6051
```release-note
NONE
```
> Fix: adapt e2e scripts to support MacOS as well

- server/channels/app/app_iface.go
- server/channels/app/cluster_handlers.go
- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
- server/channels/app/plugin_install_test.go
- server/i18n/en.json
- server/public/model/feature_flags.go
- server/public/plugin/environment.go
Some documentation and organization prior to changing how deprecated, pre-packaged plugins work:
* remove support for feature flag managed plugins (we don't use this anymore)
* remove the plugin blocklist (product mode isn't a thing)
* avoid the use of the global logger
* leverage wrapped loggers (e.g. more consistently logging `plugin_id`)
* promote some logs from `Debug` to `Info` for better visibility
Note that this focuses on just `plugin.go` and `plugin_install.go`, and tries to avoid moving code (we can reorganize the functions into files at at a later date).
There should be no user-facing changes as a result of this PR.
Relates-to: https://mattermost.atlassian.net/browse/MM-53355
```release-note
Improved logging on plugin initialization, activation, and removal.
```
> MM-53355: tidy up plugins

- server/channels/api4/user_test.go
- server/channels/app/user.go
- server/public/model/user.go
`UserAuth.Password` is unused in the codebase. This PR removes it to clean up the code.
https://mattermost.atlassian.net/browse/MM-53943
```release-note
Remove deprecated UserAuth.Password field
```
> [MM-53943] Remove deprecated UserAuth.Password field

- server/public/model/manifest.go
`ManifestExecutables` was marked for removal in v7.0, but the JIRA ticket got closed by accident. It's unused in code so it's safe to remove.
https://mattermost.atlassian.net/browse/MM-40531
```release-note
Remove deprecated ManifestExecutables struct
```
> [MM-40531] Remove deprecated ManifestExecutables struct

- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
Fix a logging issue for prepackaged plugins error handling trying to reference a `nil` pointer, and update a few more instances of the global logger.
Relates-to: https://mattermost.atlassian.net/browse/MM-53355
```release-note
NONE
```
> plugins: further logging tweaks, fixes

- server/channels/app/license.go
- server/channels/app/platform/license.go
- server/go.mod
- server/go.sum
Summary
Update https://github.com/dgrijalva/jwt-go to https://github.com/golang-jwt/jwt.
Because of THIS REPOSITORY IS NO LONGER MAINTANED, it looks good to change it.
Ticket Link
None
Screenshots
None
Release Note
None
> Update to github.com/golang-jwt/jwt/v5

- webapp/.npmrc
Enforce the existing `engine` directives requiring node at `16.x` and npm at `7.x`, failing with a clear error message if a mismatch exists (e.g. my npm version is wrong below):
```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: undefined
npm ERR! notsup Not compatible with your version of node/npm: undefined
npm ERR! notsup Required: {"node":"^16.10.0","npm":"^7.24.0"}
npm ERR! notsup Actual:   {"npm":"8.5.0","node":"v16.14.2"}
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jesse/.npm/_logs/2023-08-08T15_09_40_758Z-debug-0.log
```
This change makes the version mismatch exceedingly and immediately clear instead of the developer having to infer from an obscure error much later on in the …
> .npmrc: engine-strict

- .github/workflows/server-ci-template.yml
Fix `master` build issues introduced by https://github.com/mattermost/mattermost/pull/24217. Since that PR only touched webapp assets, the server pipeline wasn't run at all during the PR. I'm opting not to fix that for now, but it's probably something to revisit.
None.
```release-note
NONE
```
> setup-node for master build from server

- webapp/channels/src/components/post_view/post_list/index.tsx
- webapp/channels/src/components/post_view/post_view.tsx
I thought the case where this warning occurred had been previously fixed, but this component is still sometimes rendered before that value is loaded.
Looking at the `PostList` component, it seems to have handling for before a channel is loaded, so I *think* that case is okay, but I can't be 100% sure of that since all this code is rather convoluted. We should really rewrite it all at some point. Given that this is just silencing a warning that's existed for ages now, I don't think there's anything particularly wrong here at the moment though
https://mattermost.atlassian.net/browse/MM-49063
```release-note
NONE
```
> MM-49063 Silence warning when lastViewedAt is undefined

- webapp/channels/src/components/browse_channels/browse_channels.tsx
This fixes an issue when user searching a channel in browse channel modal, the member count displayed zero as incorrectly
Fixes https://github.com/mattermost/mattermost/issues/24220
**before**
https://github.com/mattermost/mattermost/assets/37421564/2f907845-8d68-4ec7-a59a-c8e14b6e6184 
**after**
https://github.com/mattermost/mattermost/assets/37421564/df52d084-b99c-4045-94f4-0c2a711a8891
```release-note
NONE
```
> GH-24220: Fix member count shown as zero when searching in browse channel modal

- server/cmd/mmctl/commands/root.go
- server/cmd/mmctl/commands/root_test.go
Re-opened from [mmctl PR 646](https://github.com/mattermost/mmctl/pull/646)
This PR introduces a change to trim whitespace from command arguments globally across the entire `mmctl` tool. I decided to go this route rather than fixing the specific case since I figured it would be nice to solve this "once and for all" rather than having to address individual cases. If however we desire a more direct fix I have a version of that change stashed as well.
- Also includes a new test for the `root` file to ensure that this whitespace trimming is working as expected.
This change not only addresses the raised issue but should prevent trailing whitespace from being an issue on any commands from `mmctl`. 
<details>
<summary>Examples can be found here</summary>
(Using input (With CRLF line endings)
``` …
```
> Trims whitespace from command arguments in RootCmd

- server/Makefile
Somewhere in the build pipeline, we run `make config-reset` to generate a default `config.json` to include with the tarball. Unfortunately, this was being built without the `-tags production` signal that changes the default service environment to `production`, and in turn caused the `CWS` environment to default to testing. The trial licenses returned by the testing environment aren't compatible with the production environment, preventing new customers from starting trials by themselves.
As an immediate workaround, customers can simply delete the `config.json` included with the tarball and start the server anew. Without any further configuration, it will correctly default to the `production` service environment and use the correct `CWS` environment.
Fix the tarball generation by adding …
> config-reset: -tags production

- server/channels/jobs/s3_path_migration/s3_path_migration.go
This got missed out in the initial PR review.
There's been only one instance of this, and that too in a spinwick
so it's not widepsread. We will cp this if we see more crashes.
https://mattermost.atlassian.net/browse/MM-54158
```release-note
NONE
```
> MM-54158: S3PathMigration: Re-initialize stop chan

- e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
- e2e-tests/cypress/tests/integration/channels/files_and_attachments/paste_image_spec.js
- webapp/channels/src/components/file_upload/file_upload.test.tsx
- webapp/channels/src/components/file_upload/file_upload.tsx
Added ability to paste plain text while copy-pasting from MS Office products on Mac, **WITHOUT** picture.
This is a second version if this PR: https://github.com/mattermost/mattermost-server/pull/23401
[hmhealey](https://github.com/hmhealey) suggested to drop an image and save only text in this case.
Fixes https://github.com/mattermost/mattermost-server/issues/16858
https://mattermost.atlassian.net/browse/MM-32576
```release-note
NONE
```
> [MM-32576] Text copied from Microsoft OneNote pastes as an image (v2)

- server/go.mod
- server/go.sum
Since `[server/public/v0.0.8](https://github.com/mattermost/mattermost/releases/tag/server/public/v0.0.8)` got released, `make modules-tidy` wants to update `github.com/mattermost/mattermost/server/public` to `v0.0.8`. I'm not sure what is happening here. I thought the version is controlled by `go.work` and does not need an update.
Anyway, this PR fixes the broken CI see in e.g. https://github.com/mattermost/mattermost/pull/24319.
None
```release-note
NONE
```
> Run make modules-tidy

- server/tests/template.load
I've tweaked some casting rules and added preserve index names clause to ensure index names are consistent after a migration.
https://mattermost.atlassian.net/browse/MM-54160
```release-note
NONE
```
> [MM-54160] postgres migration: preserve index names and a couple of fixes

- webapp/channels/src/components/sidebar/sidebar.test.tsx
- webapp/channels/src/components/sidebar/unread_channels.tsx
Looks like that if statement got removed by mistake at some point since the corresponding E2E test for this is broken on master
https://mattermost.atlassian.net/browse/MM-54211
```release-note
NONE
```
> MM-54211 Fix Unreads category being visible with no unread channels

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
After reliable websockets were introduced,
we would keep pushing to a webConn even after
the client has disconnected. This would lead
to the websocket.slow/full and eventually
the disconnect messages which unnecessarily
confuse the admin.
We don't log them if the connection is inactive.
We use the active field and convert it to an atomic
to use more widely.
```release-note
NONE
```
> Improve websocket logging (#24259)

- server/Makefile
Cloud instances do not presently list prepackaged plugins in the in-product marketplace, they instead rely on remote marketplace listings, which is being disabled in #24311.
`mattermost-plugin-zoom` v1.6.0 is the current prepackaged version, and is the presently the only prepackaged plugin that is not Cloud-compatible.
**This updates zoom prepackaged to 1.6.2.** Prior to 1.6.1, the zoom plugin had separate cloud and on-prem specific versions. (See: https://github.com/mattermost/mattermost-marketplace/blob/production/plugins.json.) 
**See below table for audit on cloud-readiness of prepackaged plugins.** 
(Add'l context: after https://github.com/mattermost/mattermost/commit/ad142c958e32d3222c5e4560b8cdc63b4b736691, only GitHub, GitLab, Jira, ServiceNow, Zoom, + other supported 1st-party …
> Upgrade & verify prepackaged plugins in prep for remote marketplace decommissioning.

- server/channels/app/user.go
- server/channels/app/user_test.go
When a user updates their `username` the response by the api was not sanitized.
https://mattermost.atlassian.net/browse/MM-54226
```release-note
```
> Sanitize user in update user response

- server/channels/app/audit.go
- server/channels/app/request/context.go
- server/channels/audit/audit_test.go
- server/channels/audit/record.go
- server/channels/web/context.go
- server/channels/web/handlers.go
This PR adds the `X-Forwarded-For` request header to the audit stream for all Rest API calls. This allows customers to view the IP's of trusted proxies that the request traversed.
https://mattermost.atlassian.net/browse/MM-53165
```release-note
Added the `X-Forwarded-For` request header to the audit stream for all Rest API calls.
```
> MM-53165 Add X-Forwarded-For header to audit for rest api calls

- server/Makefile
Updates the `config-ldap` make target to point to the right `config.json` file path after the mono-repo changes.
```release-note
NONE
```
> Fixes config path for config-ldap make target

- server/i18n/en.json
Updated Chromium minimum supported version to v116+. Desktop app v5.5 release includes Electron v26.1.0, which includes Chromium v116 (https://releases.electronjs.org/release/v26.1.0). 
```release-note
Updated Chromium minimum supported version to 116+.
```
> Update supported Chromium version

- webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
- webapp/channels/src/components/post_edit_history/post_edit_history.scss
- webapp/channels/src/components/post_edit_history/post_edit_history.tsx
Fixes a CSS scoping issue to resolve a styling issue in playbooks RHS that has overlapping content. The root problem may have caused issues in other places—this would fix those, too, if any occurred. 
- https://mattermost.atlassian.net/browse/MM-54261
|----|----|
| ![CleanShot 2023-08-28 at 12 04 19@2x](https://github.com/mattermost/mattermost/assets/11724372/a4a7f393-5cb1-4b0f-92d4-5a8adc602f72) | ![CleanShot 2023-08-28 at 12 03 54@2x](https://github.com/mattermost/mattermost/assets/11724372/b3e1dc27-b88f-4f35-9537-8c011b4a3271) |
```release-note
NONE
```
> MM-54261: re-scope css to intended target

- server/channels/api4/drafts_test.go
- server/channels/app/draft_test.go
Fix two flaky draft tests by adding a delay between the draft creations to `UpdateAt` is different for each draft.
https://mattermost.atlassian.net/browse/MM-52088
https://mattermost.atlassian.net/browse/MM-53452
```release-note
NONE
```
> [MM-52088] Fix flaky draft tests

- server/channels/app/post_metadata.go
- server/platform/services/imageproxy/imageproxy.go
- server/platform/services/imageproxy/imageproxy_test.go
There was no check for embedded images which made "copy text" paste
the siteURL instead of the actual image content.
This does not change the behavior of actually rendering the image
which is how other sites behave as well.
https://mattermost.atlassian.net/browse/MM-49627
```release-note
NONE
```
> MM-49627: Suppress transformation of embedded images via image proxy

- server/tests/template.load
Some findings along the migration documentation has been applied:
- Drop/Create index requirements can be eliminated by adding them into the `pgLoader` configuration itself.
- We don't need to use `MATERIALIZE VIEWS` clause.
- Restore `SEARCH_PATH` after the migration, this was preventing mm-server to find `public` schema.
```release-note
NONE
```
> updates on the migration template

- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/channels/app/channel.go
- server/channels/app/notification_test.go
- server/channels/app/plugin_signature.go
- server/channels/app/role.go
- server/channels/app/role_test.go
- server/channels/store/searchtest/testlib.go
- server/channels/store/storetest/group_store.go
- server/channels/utils/utils.go
- server/cmd/mmctl/commands/sampledata.go
- server/public/model/command_autocomplete.go
- server/public/utils/utils.go
- server/public/utils/utils_test.go
In Go 1.18 version, introduced package slices which uses generics.
I think it would be better to change it to a slice package.
None
None
```release-note
NONE
```
> Refactor: func StringInSlice to slices.Contains

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
I'm a bit later than I'd like to be for this, but at least it's still before the release has been cut unlike the last 2 releases
https://mattermost.atlassian.net/browse/MM-54344
```release-note
NONE
```
> Update version of JS subpackages to 9.0.0

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
I missed getting these version numbers updated before work started on 8.1.1, so I figure I'll just skip releasing 8.1.0 versions of these packages and release them for 8.1.1 when that ships.
https://mattermost.atlassian.net/browse/MM-54164
```release-note
NONE
```
> Update subpackage versions to 8.1.1

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
Cherry pick of #24438 on release-9.0.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #24438

- webapp/channels/src/sass/layout/_sidebar-left.scss
Fixed a bug where unread badge was hidden in LHS on desktop app after resizable RHS feature merge.
This also fixes the missing ellipses bug 😍
Note that it works fine on Firefox and Chrome anyways.
https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/126?modal=detail&selectedIssue=MM-54346&assignee=6054be09e394c30069d776ea
Before:
After:
```release-note
NONE
```
> Fixed a bug where unread badge was hidden in LHS on desktop app

- server/channels/app/plugin_api_test.go
Fix the flaky test `TestPluginAPIDeleteUserPreferences` by ignoring the order in `GetPreferencesForUser` returns the preferences.
https://mattermost.atlassian.net/browse/MM-47612
```release-note
NONE
```
> [MM-47612] Fix flaky TestPluginAPIDeleteUserPreferences

- server/channels/app/support_packet.go
- server/channels/app/support_packet_test.go
- server/public/model/system.go
This PR contains a couple of changes to the support package code:
- Update `support_package.go` to use idiomatic error handling [c5a7d54](https://github.com/mattermost/mattermost/pull/24382/commits/c5a7d54b07bd73c93d492d9fa44b4f7a114349a8)
- Add `bleve_post_indexing` jobs to support package [47b8818](https://github.com/mattermost/mattermost/pull/24382/commits/47b88184593dd8703877779a2b8c6cb255d3bbfa)
- Reorder code to match `model/job.go` for better readability [c78a72e](https://github.com/mattermost/mattermost/pull/24382/commits/c78a72ea6c65b884f848bbbda065f709fb17c94f)
https://mattermost.atlassian.net/browse/MM-54245
```release-note
NONE
```
> Migrate to idiomatic error handling in support_package.go

- server/channels/api4/system.go
- server/channels/api4/system_test.go
- server/channels/app/notification_push.go
- Treat redirect urls over a certain size as failures
- After discussion with @jupenur and looking at a good summary of browser and crawler support, 2100 seems like a good length to support. https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers
- This endpoint is used by mobile to get expanded links.
- https://mattermost.atlassian.net/browse/MM-54219
I've attached before and after heap profiles, [heap-profiles.zip](https://github.com/mattermost/mattermost/files/12480522/heap-profiles.zip) . The before fix before/after shows the cache hitting 613MB, the after fix before/after shows this is fixed. I also included a `heap-after-fix-after-test-smaller-location` which shows the effect of requesting 3000 locations that just fit the location limit …
> MM-54219 - Fix: Improve limits on redirectLocationDataCache

- e2e-tests/.ci/.e2erc
- e2e-tests/.ci/server.override.yml
- server/scripts/mirror-docker-images.json
As mentioned [here](https://github.com/mattermost/mattermost/pull/24283#issuecomment-1696080783), it'd be better to use `.nvmrc` as a single source of truth for the Node version required within the repo.
This cannot be done everywhere (e.g. the cypress image is monolithic), but for the node image that we mirror we can do that.
This PR:
- Creates the required images
- Updates the node image reference in the server.override.yml file, to indirectly utilize `.nvmrc`
- Fixes a minor annoyance that caused `e2e-tests/cypress/package-lock.json` to change everytime e2e tests were run locally
https://mattermost.atlassian.net/browse/CLD-6206
```release-note
NONE
```
> Use .nvmrc for determining the node image used for E2E tests

- server/channels/app/support_packet.go
- server/channels/app/support_packet_test.go
- server/platform/shared/filestore/filesstore.go
- server/platform/shared/filestore/localstore.go
- server/platform/shared/filestore/mocks/FileBackend.go
- server/platform/shared/filestore/s3store.go
- server/public/model/system.go
6dbb6d2a02aa815eaec534b6c3d241788ba581d6 adds two pieces of information about the file storage to the support package: `file_driver`, which contains the driver type, and `file_status`, which contains status information about the file store. That should make it easier to spot if the file store is misconfigured.
51bbfc9cdfe881cd8acdd389e55e31d015fc0250 orders the fields in the support package by type, which makes it easier to read the information.
f789c67404413a7f5889535c99acd2e2fed0dc4d adds the cluster ID. This allows the matching of multiple support packages to the nodes. 
https://mattermost.atlassian.net/browse/MM-54318
```release-note
Add file storage information to support package
```
> [MM-54318] Add file storage information to support package

- webapp/channels/src/components/desktop_auth_token.tsx
Firefox revealed an issue with how we are changing the protocol of the current `href` to the `mattermost` protocol to be opened in the Desktop App. Normally, the `protocol` field of the `URL` object isn't supposed to be mutable, but Chrome (and presumably other WebKit-based browsers) allows this.
This PR changes to a solution that should be more compliant and should avoid the issue for Firefox users.
https://mattermost.atlassian.net/browse/MM-54402
```release-note
NONE
```
> [MM-54402] Change protocol transform method for Desktop Auth to be compliant with web standards

- app/user.go
- db/migrations/migrations.list
- db/migrations/mysql/000113_create_retentionidsfordeletion_table.down.sql
- db/migrations/mysql/000113_create_retentionidsfordeletion_table.up.sql
- db/migrations/postgres/000113_create_retentionidsfordeletion_table.down.sql
- db/migrations/postgres/000113_create_retentionidsfordeletion_table.up.sql
- i18n/en.json
- model/config.go
- model/data_retention_policy.go
- model/feature_flags.go
- services/telemetry/telemetry.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/channel_member_history_store.go
- store/sqlstore/post_store.go
- store/sqlstore/reaction_store.go
- store/sqlstore/retention_policy_store.go
- store/sqlstore/thread_store.go
- store/store.go
- store/storetest/channel_member_history_store.go
- store/storetest/mocks/PostStore.go
- store/storetest/mocks/ReactionStore.go
- store/storetest/mocks/RetentionPolicyStore.go
- store/storetest/post_store.go
- store/storetest/preference_store.go
- store/storetest/reaction_store.go
- store/timerlayer/timerlayer.go
Cherry pick https://github.com/mattermost/mattermost/pull/24253
```release-note
Improved performance on data retention `DeleteOrphanedRows` queries.
New migration for a new table:
Mysql
CREATE TABLE IF NOT EXISTS RetentionIdsForDeletion (
Id varchar(26) NOT NULL,
TableName varchar(64),
Ids json,
PRIMARY KEY (Id),
KEY idx_retentionidsfordeletion_tablename (TableName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Postgres
CREATE TABLE IF NOT EXISTS retentionidsfordeletion (
id varchar(26) PRIMARY KEY,
tablename varchar(64),
ids varchar(26)[]
);
CREATE INDEX IF NOT EXISTS idx_retentionidsfordeletion_tablename ON retentionidsfordeletion (tablename);
Hard deleting a user or a channel will now also clean up associated reactions.
Removed feature flag: DataRetentionConcurrencyEnabled. Data retention …
```
> [MM-53291] Data retention improvements cherry pick 7.8

- server/channels/api4/system.go
- server/channels/api4/user_test.go
- server/channels/app/admin.go
- server/channels/app/license.go
- server/channels/app/license_test.go
- server/channels/app/notification_test.go
- server/channels/app/oauth.go
- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/license.go
- server/channels/app/platform/service.go
- server/channels/app/server.go
- server/cmd/mattermost/commands/init.go
- server/cmd/mattermost/commands/jobserver.go
- server/public/model/cluster_message.go
Reverts mattermost/mattermost#24200
The PR missed testing in HA scenarios and introduced a regression. Reverting for now.
@agarciamontoro - We can probably pin to the exact version of 8.1 you are using to prevent regressing to the old behavior again.
https://mattermost.atlassian.net/browse/MM-54442
> Revert "MM-53879: Fix recursive loading of license"

- server/channels/app/user.go
- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000113_create_retentionidsfordeletion_table.down.sql
- server/channels/db/migrations/mysql/000113_create_retentionidsfordeletion_table.up.sql
- server/channels/db/migrations/postgres/000113_create_retentionidsfordeletion_table.down.sql
- server/channels/db/migrations/postgres/000113_create_retentionidsfordeletion_table.up.sql
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_member_history_store.go
- server/channels/store/sqlstore/post_store.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/sqlstore/retention_policy_store.go
- server/channels/store/sqlstore/thread_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_member_history_store.go
- server/channels/store/storetest/mocks/PostStore.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/mocks/RetentionPolicyStore.go
- server/channels/store/storetest/post_store.go
- server/channels/store/storetest/preference_store.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/i18n/en.json
- server/platform/services/telemetry/telemetry.go
- server/public/model/config.go
- server/public/model/data_retention_policy.go
- server/public/model/feature_flags.go
Cherry pick https://github.com/mattermost/mattermost/pull/24253
```release-note
Improved performance on data retention `DeleteOrphanedRows` queries.
New migration for a new table:
Mysql
CREATE TABLE IF NOT EXISTS RetentionIdsForDeletion (
Id varchar(26) NOT NULL,
TableName varchar(64),
Ids json,
PRIMARY KEY (Id),
KEY idx_retentionidsfordeletion_tablename (TableName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Postgres
CREATE TABLE IF NOT EXISTS retentionidsfordeletion (
id varchar(26) PRIMARY KEY,
tablename varchar(64),
ids varchar(26)[]
);
CREATE INDEX IF NOT EXISTS idx_retentionidsfordeletion_tablename ON retentionidsfordeletion (tablename);
Hard deleting a user or a channel will now also clean up associated reactions.
Removed feature flag: DataRetentionConcurrencyEnabled. Data retention …
```
> [MM-53291] Data retention improvements cherry pick 8.1

- server/public/model/job.go
Fixes a race in `JobServer.HandleJobPanic` by implementing `mlog.LogCloner` in `model.Job`
See https://community.mattermost.com/core/pl/99jzw5wdiirxxjwg397zdsxauo
NONE
```release-note
NONE
```
> Fix race in JobServer.HandleJobPanic 

- webapp/channels/src/plugins/registry.ts
- Part of the PR https://github.com/mattermost/mattermost-plugin-calls/pull/452 was accidentally removed by https://github.com/mattermost/mattermost/pull/23952
- This PR replaces what was removed
- @amyblais I'm not certain if any of the on-prem MM versions were shipped with this missing... But I hope this can be cherry picked into cloud and whatever necessary.
```release-note
NONE
```
> MM-54443 - Fix: registerDesktopNotificationHook is missing

- server/public/model/service_environment_test.go
A late change to the service environment functionality had us defaulting to `dev` instead of `test` without the `production` build tag. Unfortunately, because these tests were unintentionally being skipped within the submodule, the failure wasn't caught at the time. A simple update addresses the unit tests.
Fixes: https://mattermost.atlassian.net/browse/MM-54197
```release-note
NONE
```
> fix TestGetServiceEnvironment

- server/channels/jobs/migrations/scheduler.go
`GetMigrationState` can return a `nil` job, which leads to the panic. Use the job server's logger in this case.
https://community.mattermost.com/core/pl/99jzw5wdiirxxjwg397zdsxauo
```release-note
NONE
```
> Fix logger panic in migration scheduler

- server/channels/store/sqlstore/channel_store.go
- webapp/channels/src/components/browse_channels/browse_channels.tsx
This PR fixes two issues
a) when a channel has only 1 member and when that user leaves the channel, users still see 1 as member count in the browse channel modal 
b) private channels member count always shown as zero
Jira https://mattermost.atlassian.net/browse/MM-54260
a) when a channel has only 1 member and when that user leaves the channel, users still see 1 as member count in the browse channel modal 
**before**
https://github.com/mattermost/mattermost/assets/37421564/0557de99-0622-453f-917f-0d230d7e2d65
**after**
https://github.com/mattermost/mattermost/assets/37421564/809ac64c-2379-4467-9d2a-c74c9cff4265
b) private channels member count always shown as zero
**before**
https://github.com/mattermost/mattermost/assets/37421564/054675f1-e61c-4497-8ff9-a8b305438c82
**after** …
> MM-54260: Browse Channel Modal - Fix member count on private channels and when there is only 1 member in the channel

- server/channels/app/emoji.go
- server/channels/app/import_functions.go
- server/channels/app/import_functions_test.go
- server/channels/store/localcachelayer/channel_layer_test.go
- server/channels/store/localcachelayer/emoji_layer.go
- server/channels/store/localcachelayer/emoji_layer_test.go
- server/channels/store/localcachelayer/file_info_layer_test.go
- server/channels/store/localcachelayer/main_test.go
- server/channels/store/localcachelayer/post_layer_test.go
- server/channels/store/localcachelayer/reaction_layer_test.go
- server/channels/store/localcachelayer/role_layer_test.go
- server/channels/store/localcachelayer/scheme_layer_test.go
- server/channels/store/localcachelayer/team_layer_test.go
- server/channels/store/localcachelayer/terms_of_service_layer_test.go
- server/channels/store/localcachelayer/user_layer_test.go
- server/channels/store/localcachelayer/webhook_layer_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/context.go
- server/channels/store/sqlstore/emoji_store.go
- server/channels/store/store.go
- server/channels/store/storetest/emoji_store.go
- server/channels/store/storetest/mocks/EmojiStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/public/shared/request/context.go
Migrate `EmojiStore` methods that make use of a `context.Context` to use `request.CTX` instead.
..
```release-note
Migrate EmojiStore to use request.CTX
```
> Migrate emojiStore to use request.CTX instead of context.Context

- webapp/channels/src/components/admin_console/admin_definition.jsx
- webapp/channels/src/i18n/en.json
In-product config setting text now aligned with product documentation.
```release-note
NONE
```
> Clarified in-product hint text

- e2e-tests/playwright/support/ui/components/channels/center_view.ts
- e2e-tests/playwright/support/ui/components/channels/header_mobile.ts
- e2e-tests/playwright/support/ui/components/channels/post_create.ts
- e2e-tests/playwright/support/ui/components/channels/sidebar_right.ts
- e2e-tests/playwright/support/ui/components/index.ts
- e2e-tests/playwright/support/ui/pages/channels.ts
- e2e-tests/playwright/tests/accessibility/channels/intro_channel.spec.ts
- e2e-tests/playwright/tests/functional/channels/drafts/drafts_on_deleted_message.spec.ts
- e2e-tests/playwright/tests/functional/channels/search/find_channels.spec.ts
- webapp/channels/src/components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
- webapp/channels/src/components/channel_layout/channel_controller.tsx
- webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
- webapp/channels/src/components/channel_view/channel_view.tsx
- webapp/channels/src/components/post/post_component.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/create_comment.tsx
- Updated the code to improve the usage of post text boxes, channel headers, and post lists, making them more consistent and generic.
- Components such as post list, post textbox, and post can be used interchangeably in either the Center or RHS
- Refactored the Main Channels page component to break down into their respective app areas for better code organisation.
https://mattermost.atlassian.net/browse/MM-54458
```diff
- channelsPage.postMessage('hello');
+ channelsPage.centerView.postCreate.postMessage('hello');
- sidebarRight.getInputValue();
+ sidebarRight.postCreate.getInputValue()
- sidebarRight.getRHSPostById(adminPost.id)
+ sidebarRight.getPostById(adminPost.id)
```
```release-note
NONE
```
> MM-54458 : Refactor playwright test with app areas

- webapp/channels/src/components/profile_popover/index.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
- webapp/channels/src/selectors/calls.ts
Latest version of Calls included a refactor of our redux store and I completely forgot we were relying on it on this side which is breaking functionality and in 7.10 even causing a crash. 
Ideally we'd port this functionality on the other side through a pluggable and avoid this altogether but now we need to keep some sort of compatibility so we are exporting both names from the plugin (see related PR).
I'll also plan to add an E2E test on the Calls side since we should have caught it prior to release.
https://github.com/mattermost/mattermost-plugin-calls/pull/524
https://mattermost.atlassian.net/browse/MM-54494
```release-note
NONE
```
> [MM-54494] Update selector to get profiles connected to calls

- server/channels/api4/plugin_test.go
- server/channels/api4/system_test.go
- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
- webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
- webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
As a follow up to #24311, and in relation to https://github.com/mattermost/mattermost-marketplace/pull/384, this re-enables remote marketplace functionality and adds back the loading screen. `FeatureFlags.StreamlinedMarketplace` now only affects marketplace UI.  
https://github.com/mattermost/mattermost/assets/11724372/9b29656c-7078-4b25-af26-64088c3ee8b8
- https://mattermost.atlassian.net/browse/MM-54505
```release-note
Re-enables remote marketplace functionality (if configured as per `PluginSettings.EnableRemoteMarketplace`)
```
> MM-54505: re-enable remote marketplace functionality

- server/channels/app/user.go
- server/channels/app/user_test.go
Cherry pick of #24362 on release-9.0.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #24362

- api/v4/html/ssr_template.hbs
This pull request fixes a regression introduced by https://github.com/mattermost/mattermost/issues/24504 by removing the "static" folder in the favicon's url path definition the folder duplication issue stopped occuring in the dev environment but introduced a breaking change in production since the favicon no longer loads in production, I have restored the old favicon url path definition.
https://mattermost.atlassian.net/browse/MM-54449
See issue: https://github.com/mattermost/mattermost/issues/24504
```release-note
NONE
```
> reverted to the old favicon path

- server/channels/app/post_metadata_test.go
Since we were using static channel names, in the same test suite we had conflicts when creating new channels. I changed all the occurrences of the offending string (which also had a typo and not always made sense) with `model.NewId()`, which should never collide.
None
```release-note
NONE
```
> Fix flaky test introduced in #24495

- .github/workflows/server-test-template.yml
We already report flaky tests on `master` and `release-*` branches, but unfortunately squelch these during PRs. If they are truly unrelated, this is great, since we don't have to retry the whole test suite in the hopes they go away. But if they are caused by the pull request itself, we can accidentally introduce this to `master`.
Update our reporting strategy to post a comment on the pull request itself if flaky tests are detected. This won't block merging, but give the author a chance to review to see if relevant.
None.
See comments below from earlier experimentation, but also:
```release-note
NONE
```
> Report flaky tests on pr

- webapp/channels/src/components/confirm_modal_redux/confirm_modal_redux.test.tsx
Since Node 18, web app unit tests take longer to run in CI. These tests time out when they fail, and we give them a much lower timeout than any other test. Since they run slower with Node 18, I assume they've become flaky because that timeout is too low now.
MM-54349
```release-note
NONE
```
> MM-54349 Increase timeout for ConfirmModalRedux test

- server/channels/jobs/base_workers.go
- server/channels/jobs/base_workers_test.go
- server/channels/jobs/jobs_test.go
If GetJob fails, we would return a nil job and then try to log
with that. To prevent this, we keep a reference to the old job
and log with that in the error case.
https://mattermost.atlassian.net/browse/MM-54580
```release-note
Fix a panic where a simple worker would crash if if failed to get a job.
```
> MM-54580: Fix panic in jobs/base_workers.go

- webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
- webapp/channels/src/components/system_notice/notices.tsx
- webapp/channels/src/components/system_notice/system_notice.tsx
- webapp/channels/src/sass/components/_system-notice.scss
The style of the notices broke, probably after the latest button refactor (and maybe due to bad merges).
This fixes it.
Also addresses some other minor style concerns seen during review.
Fix https://mattermost.atlassian.net/browse/MM-54583
|----|----|
| ![Screenshot from 2023-09-28 13-34-34](https://github.com/mattermost/mattermost/assets/1933730/a2c8b0ef-5f6b-4f07-8cb4-e53a76187202) | ![Screenshot from 2023-09-28 16-56-31](https://github.com/mattermost/mattermost/assets/1933730/f8f9c39b-3e16-4a9d-93ef-c4b4f63a8d56)|
| ![Screenshot from 2023-09-28 13-34-49](https://github.com/mattermost/mattermost/assets/1933730/1b3c7a55-be1d-4694-9514-ff6bfc7dd927) | ![Screenshot from 2023-09-28 16-55-39](https://github.com/mattermost/mattermost/assets/1933730/a2e6642b-6330-4cab-9ff …
> Fix style for notices

- server/channels/jobs/base_workers.go
- server/channels/jobs/base_workers_test.go
If GetJob fails, we would return a nil job and then try to log
with that. To prevent this, we keep a reference to the old job
and log with that in the error case.
https://mattermost.atlassian.net/browse/MM-54580
```release-note
Fix a panic where a simple worker would crash if if failed to get a job.
```
> CP: MM-54580: Fix panic in jobs/base_workers.go

- webapp/channels/src/sass/components/_buttons.scss
MM-54723 - Updating btn icon sizes
Fixes https://mattermost.atlassian.net/browse/MM-54723
**Before**
**After**
```release-note
NONE
```
> MM-54723 - Fixing btn icon sizes for RHS

- webapp/channels/.eslintrc.json
- webapp/channels/package.json
- webapp/channels/src/components/external_link/index.tsx
- webapp/channels/src/components/size_aware_image.jsx
- webapp/package-lock.json
- webapp/package.json
- webapp/platform/eslint-plugin/LICENSE.txt
- webapp/platform/eslint-plugin/README.md
- webapp/platform/eslint-plugin/configs/.eslintrc-react.json
- webapp/platform/eslint-plugin/configs/.eslintrc.json
- webapp/platform/eslint-plugin/index.js
- webapp/platform/eslint-plugin/package.json
- webapp/platform/eslint-plugin/rules/no-dispatch-getstate.js
- webapp/platform/eslint-plugin/rules/use-external-link.js
I've wanted to get rid of https://github.com/mattermost/eslint-plugin-mattermost/ for a while since:
1. It's hard to update since it's so far away
2. It's used as a git dependency, and it can't even be published to NPM currently because someone stole our package name
This just brings it into the monorepo so that we can archive that other one. I'll also be publishing this to NPM so that we can use it in other JS projects without all the hassles that come from git dependencies
```release-note
NONE
```
> Move the shared ESLint plugin/config into the monorepo

- .github/workflows/mmctl-test-template.yml
- server/Makefile
- Remove coverage mode. They increase run time by 3x.
- Remove -race mode in PR builds. They increase run time by 2x and memory consumption as well.
```release-note
NONE
```
> Optimize mmctl CI run

- webapp/channels/src/components/emoji/emoji_list/emoji_list.tsx
Replaces the 'LocalizedInput' component in `webapp/channels/src/components/emoji/emoji_list/emoji_list.tsx` to a regular input component
Fixes No Github issue
Jira https://mattermost.atlassian.net/browse/MM-54829
n/a
```release-note
NONE
```
> [MM-54829] Convert LocalizedInput of 'emoji_list.tsx' to regular input component

- webapp/channels/package.json
- webapp/package-lock.json
Bump to latest mmjstool so `defineMessage` is also handle by `i18n-extract`
None
```release-note
NONE
```
> Bump to latest mmjstool

- webapp/channels/src/components/claim/components/oauth_to_email.tsx
Converted `LocalizedInput` components in `oauth_to_email.tsx` to `input` and added `React-Intl AP` to accommodate translated strings.
Fixes https://github.com/mattermost/mattermost/issues/24830
Jira https://mattermost.atlassian.net/browse/MM-54841
```
NONE
```
> [MM-54841] Convert LocalizedInput of 'oauth_to_email.tsx' to regular input component

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
`release-9.1` has been branched so we can update these now for the following release.
Note that I didn't update the ESLint plugin version since it's not dependent on the MM server version. We're also not likely to update it as often.
```release-note
Update versions of NPM packages for 9.2
```
> Update subpackage versions for 9.2

- webapp/channels/src/components/post_view/message_attachments/action_button/action_button.test.tsx
- webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
- webapp/channels/src/sass/layout/_webhooks.scss
This PR improves the styling for the slack attachment buttons and aligns them better with the new button classes that are now available since merging https://github.com/mattermost/mattermost/pull/24483#event-10460608133.
This also resolves theming issues that have been reported with dark themes for slack attachment buttons.
Fixes https://github.com/mattermost/mattermost/issues/23968
Jira https://mattermost.atlassian.net/browse/MM-53513
**Denim Theme**
<table>
<tr>
<td>Before</td>
<td><img width="989" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/e8198fb8-8576-4993-a685-44fe41d65929"></td>
</tr>
<tr>
<td>After</td>
<td><img width="988" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/093a71d2-5683-4f5c-b482-102a9cf4aaba"></td>
</tr> …
> MM-53513 Update styles of slack attachment buttons

- webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/database_settings.test.tsx
This PR migrates the database_settings.test.jsx to typescript. This should be
done with the migration of the `database_settings.jsx`, but wasn't done, so
I've done it separately.
https://mattermost.atlassian.net/browse/MM-52825
```release-note
NONE
```
> migrating database_settings.test.jsx to typescript

- server/channels/app/authorization.go
- server/channels/app/post_metadata_test.go
Cherry pick of #24495 on release-8.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24495

- server/channels/app/import.go
- server/channels/store/sqlstore/context_test.go
- server/public/shared/request/context.go
Cherry pick of #24897 on release-9.2.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #24897

- webapp/channels/src/components/claim/components/email_to_oauth.tsx
Converted LocalizedInput components in 'email_to_oauth.tsx' to input and added React-Intl AP to accommodate translated strings
Fixes https://github.com/mattermost/mattermost/issues/24831
```release-note
NONE
```
> [MM 24831] Convert LocalizedInput of 'email_to_oauth.tsx' to regular input component

- webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx
- webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Replace `LocalizedInput` component in `webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx` to a regular input.
Fixes https://github.com/mattermost/mattermost/issues/24834
Jira https://mattermost.atlassian.net/browse/MM-54837
The field is highlighted in this screenshot (has a focus):
```
NONE
```
> [MM-54837] Convert LocalizedInput of 'permission_team_scheme_settings.tsx' to regular input component

- .github/workflows/i18n-ci-pr.yml
- .github/workflows/i18n-ci-template.yml
Only the @weblate user should be allowed to modify non-English translation files. Enforce this with a CI check, noting that in exceptional cases an admin can still force merge when a future (but now far less likely) merge conflict has to be resolved.
None.
```release-note
NONE
```
> Prevent modifying non-English i18n files

- server/channels/app/mention_keywords.go
- server/channels/app/mention_keywords_test.go
- server/channels/app/mention_parser_standard.go
- server/channels/app/mention_parser_standard_test.go
- server/channels/app/mention_results.go
- server/channels/app/notification.go
- server/channels/app/notification_test.go
- server/channels/app/post.go
- server/channels/app/post_persistent_notification.go
This is the third PR for this ticket following https://github.com/mattermost/mattermost/pull/24932 and https://github.com/mattermost/mattermost/pull/24936. All 3 together are hopefully going to set us up well to swap the mention parsing logic more easily. The other two are mostly moving code around, but this is the one that really changes code, so more care should be taken when reviewing it.
For this, I wanted to make it so that the parsing of user and group mentions are handled by the exact same code because we don't really care if `@someone` is one person or multiple people at this step of the process. To do this, I removed the group mention specific code from the `StandardMentionParser` and made it so that I could add groups to the map of "mention keywords" that we look for when …
> MM-54201 Unify user and group mention parsing logic

- webapp/channels/src/components/password_reset_send_link/__snapshots__/password_reset_send_link.test.tsx.snap
- webapp/channels/src/components/password_reset_send_link/password_reset_send_link.test.tsx
- webapp/channels/src/components/password_reset_send_link/password_reset_send_link.tsx
- webapp/channels/src/tests/helpers/intl-test-helper.tsx
Replace `LocalizedInput` component in `webapp/channels/src/components/password_reset_send_link/password_reset_send_link.tsx` to a regular input.
Fixes https://github.com/mattermost/mattermost/issues/24824
Jira https://mattermost.atlassian.net/browse/MM-54832
```
NONE
```
> [MM-54832] Convert LocalizedInput of 'password_reset_send_link.tsx' to regular input component

- server/channels/app/platform/web_conn.go
I was looking at the high number of user_updated ws events
and ran across this piece of code. Had a hard time digesting it,
thought of adding a comment for people to understand it more
clearly.
```release-note
NONE
```
> Clarify the sensitive/sanitized logic

- webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.scss
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Using the lightbulb icon for the in-app documentation links.
There is not a ticket for this, but is to easy the community development of tickets like #25000
Before:
After:
```release-note
NONE
```
> Using the lightbulb icon for linking to the documentation

- server/Makefile
`master` is currently failing to download and install `gotestsum@1.7.0`:
```
go: gotest.tools/gotestsum@v1.7.0: gotest.tools/gotestsum@v1.7.0: verifying module: gotest.tools/gotestsum@v1.7.0: Get "https://sum.golang.org/lookup/gotest.tools/gotestsum@v1.7.0": EOF
```
Upgrade this to `gotestsum@v1.11.0`.
None.
```release-note
NONE
```
> upgrade gotestsum@v1.11.0

- server/Makefile
The `inject-test-data` command has been introduced to inject test data in a running instance, this PR fixes the behavior by removing the stop-server instruction, but adding it to the `test-data` command to not break any workflow relying on this.
N/A
```release-note
NONE
```
> (makefile) Injecting test data should not stop the server

- webapp/channels/src/components/widgets/icons/fa_next_icon.tsx
Replaced the usage of LocalizedIcon in 'fa_next_icon.tsx' with i tag
Fixes #25092 
Icon used in add custom emoji page's next icon
```release-note
NONE
```
> [MM-55118] Replace usage of LocalizedIcon in 'fa_next_icon.tsx' with i/span tags

- server/i18n/en.json
Update minimum required Firefox version to v115+ per request at https://community.mattermost.com/private-core/pl/ozre94egk38dzx7e5c4tcwzxuw. There is a bug in PDF previews that's fixed by updating it, but it requires a newer version of Firefox than we currently support.
```release-note
Update minimum required Firefox version to 115+.
```
> Update minimum supported Firefox version

- webapp/channels/src/components/user_profile/user.test.ts
- webapp/channels/src/components/user_profile/utils.ts
Generate higher contrast for some usernames
I've kept the 3 tries but return the best value instead of the last one.
Added test to check that it works.
For the record I've tested increasing the number of tries but it isn't especially better:
| tries | # over 4.5 | worst ratio |
| ----- | ---------- | ----------- |
| 03    | 3/8        | 2.29        |
| 04    | 3/8        | 2.5         |
| 05    | 5/8        | 2.5         |
| 06    | 5/8        | 2.64        |
| 07    | 6/8        | 2.64        |
| 08    | 6/8        | 2.95        |
| 09    | 6/8        | 2.95        |
| 10    | 6/8        | 2.95        |
This is in contrast with the previous implementation:
| tries | # over 4.5 | worst ratio |
| ----- | ---------- | ----------- |
| 03    | 3/8        | 1.07        |
| 04    | 3/8        | …
> MM-52280: Generate higher contrast for some usernames

- webapp/channels/src/components/admin_console/request_button/__snapshots__/request_button.test.tsx.snap
- webapp/channels/src/components/widgets/icons/fa_success_icon.tsx
Replaced the usage of LocalizedIcon in 'fa_success_icon.tsx' with i tag
Fixes #25089 
Jira https://mattermost.atlassian.net/browse/MM-55121
```release-note
NONE
```
> [MM-55121] Replace usage of LocalizedIcon in 'fa_success_icon.tsx' with i/span tags

- webapp/channels/src/components/rhs_card/__snapshots__/rhs_card.test.tsx.snap
- webapp/channels/src/components/rhs_card_header/rhs_card_header.tsx
This PR converts the LocalizedIcon in `rhs_card_header.tsx` to I tag
fixes: #25107
https://mattermost.atlassian.net/browse/MM-55103
```release-note
NONE
```
> [MM-55103] Replace usage of LocalizedIcon in 'rhs_card_header.tsx' with i/span tags

- webapp/channels/src/components/admin_console/request_button/__snapshots__/request_button.test.tsx.snap
- webapp/channels/src/components/widgets/icons/fa_warning_icon.tsx
Replaced the usage of LocalizedIcon in 'fa_warning_icon.tsx' with i tag
Fixes #25088
Jira https://mattermost.atlassian.net/browse/MM-55122
```release-note
NONE
```
> [MM-55122] Replaced the usage of LocalizedIcon in 'fa_warning_icon.tsx' with i/span tags

- webapp/channels/src/components/widgets/icons/fa_previous_icon.tsx
This PR replaces the usage of LocalizedIcon with i tag in `webapp/channels/src/components/widgets/icons/fa_previous_icon.tsx` file.
Jira https://mattermost.atlassian.net/browse/MM-55119
Fixes : #25091 
```release-note
NONE
```
> [MM-55119] Replace usage of LocalizedIcon in 'fa_previous_icon.tsx' with i/span tags

- webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
- webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
- webapp/channels/src/components/user_group_popover/group_member_list/group_member_list.tsx
Replaced the usage of LocalizedIcon in 'group_member_list.tsx' with i tag
Jira https://mattermost.atlassian.net/browse/MM-55109
Fixes [#25101](https://github.com/mattermost/mattermost/issues/25101)
```release-note
NONE
```
> [MM-55109] Replace usage of LocalizedIcon in 'group_member_list.tsx' with i/span tags

- webapp/channels/src/components/__snapshots__/loading_image_preview.test.tsx.snap
- webapp/channels/src/components/__snapshots__/pdf_preview.test.jsx.snap
- webapp/channels/src/components/admin_console/data_grid/__snapshots__/data_grid.test.tsx.snap
- webapp/channels/src/components/apps_form/__snapshots__/apps_form_component.test.tsx.snap
- webapp/channels/src/components/login/login.test.tsx
- webapp/channels/src/components/login/login_mfa.test.tsx
- webapp/channels/src/components/post_view/message_attachments/action_button/action_button.test.tsx
- webapp/channels/src/components/widgets/loading/__snapshots__/loading_spinner.test.tsx.snap
- webapp/channels/src/components/widgets/loading/__snapshots__/loading_wrapper.test.tsx.snap
- webapp/channels/src/components/widgets/loading/loading_spinner.test.tsx
- webapp/channels/src/components/widgets/loading/loading_spinner.tsx
- webapp/channels/src/components/widgets/loading/loading_wrapper.test.tsx
Replace the usage of LocalizedIcon in 'loading_spinner.tsx' with i/span tags
Fixes #25087
Jira https://mattermost.atlassian.net/browse/MM-55123
```release-note
NONE
```
> [MM-55123] Replace the usage of LocalizedIcon in 'loading_spinner.tsx' with i/span tags

- webapp/channels/src/sass/components/_files.scss
- webapp/channels/src/sass/components/_modal.scss
- webapp/channels/src/sass/components/_post.scss
This seems straightforward enough of a fix.
I've been thinking of adding an scss helper function so that we don't need to remember to use `var(--theme-variable)` or `rgba(var(--theme-variable-rgb), 0.5)` exactly, but that seems like it'll result in a lot of changes, so I'd be hesitant to do that.
```release-note
NONE
```
> Fix typos caused by applyTheme migration

- webapp/channels/src/sass/responsive/_tablet.scss
- webapp/channels/webpack.config.js
These warnings have been printed by Webpack for ages, but they get really annoying if using `make dev`
That CSS has never done anything since it's always been invalid, and since we're not actively using module federation, I don't think we need to fix the version of prop-types. By the time we actually get back to module federation, we'll hopefully all be on TypeScript so we won't need that library anyway
```release-note
NONE
```
> Fix Webpack warnings

- .github/workflows/workflow-failure-check.yml
The `master` build has been failing for some time now with minimal visibility. In general, this often catches us by surprise because we don't have anything wired up to notify developers. While this will be "noisy" when `master` is broken, it's by design as we should all consider shared ownership of a working build to be of utmost importance.
None.
```release-note
NONE
```
> report master/release-* failures

- server/Makefile
A one liner that save me from always searching why the test-data make target fails inevitably until I remember local mode should be enabled
```release-note
NONE
```
> server: Force local mode when launching test-data target

- .github/workflows/workflow-failure-check.yml
Looks like my check to report when `master` fails had a YAML syntax check. Somehow I had hoped GitHub's CI would test this even though it doesn't run on PRs, but it looks like I need to be more careful with my editor setup instead. (Suggestions welcome!)
None.
```release-note
NONE
```
> fix yaml formatting issue

- server/channels/app/post_test.go
Apparently, the order of execution of the hooks is not deterministic, causing in some circumstances the final message to be `new message 2 1` instead of `new message 1 2`.
In order to avoid make this deterministic, instead of adding to the end of the message the string, one of the plugins will add it to the end, and the other to the beginning. That way it is properly deterministic.
NONE
```release-note
NONE
```
> Fix flaky test introduced in #24602

- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
This PR implements the following changes in `user_settings_notifications.tsx`:
- replaced `LocalizedIcon` with `i` tag
- replaced `t` function with `intl.formatMessage` in `aria-label` prop
Fixes https://github.com/mattermost/mattermost/issues/25098
Jira https://mattermost.atlassian.net/browse/MM-55112
|----|----|
| ![before](https://github.com/mattermost/mattermost/assets/75561750/d2722b50-6bce-4a9f-8616-4ca8ddae700d)  | ![after](https://github.com/mattermost/mattermost/assets/75561750/60f50a07-6c24-4489-8938-ae5542f0fa35) |
```release-note
NONE
```
> [MM-55112] Replace usage of LocalizedIcon in 'user_settings_notifications.tsx' with i/span tags

- api/v4/source/introduction.yaml
- webapp/platform/client/README.md
I noticed earlier that https://api.mattermost.com hasn't pointed to the correct location of the API client since before that was moved into the web app repo and it was shipped as part of its own package, so I wanted to update that. At the same time, I also realized that the documentation on the NPM package was lacking, so I added a bit more information to the README as well.
```release-note
NONE
```
> Update documentation on JS API client

- server/channels/api4/hosted_customer.go
- server/channels/app/notification_email.go
- server/channels/app/platform/session.go
- server/channels/store/searchtest/helper.go
- server/channels/utils/hash.go
- server/cmd/mmctl/commands/utils_unix.go
- server/config/client.go
- server/platform/services/searchengine/bleveengine/testlib.go
Optimizes server code by replacing `fmt.Sprint` usages with faster alternatives such as `strconv.FormatBool`
cf https://github.com/catenacyber/gostrconv
No ticket, just optimization...
No UI changes (only server)
```release-note
NONE
```
> Replace `fmt.Sprint` usages with faster alternatives such as `strconv.FormatBool`

- .github/workflows/server-ci-artifacts.yml
- e2e-tests/README.md
Workflows running on PRs targeting `release-7x` are currently failing, see for example https://github.com/mattermost/mattermost/pull/25185
The root cause is that the `Server CI Artifacts` workflow only supports the monorepo branches. This PR will exclude problematic jobs if the workflow is not running in a monorepo (= `release-7.x` branches)
I tested this implementation in [this other PR](https://github.com/mattermost/test-private-project/pull/4):
- You can see how the changes would run respectively for the [release-9.1](https://github.com/mattermost/test-private-project/actions/runs/6735834974/job/18309939502) and the [release-7.8](https://github.com/mattermost/test-private-project/actions/runs/6735918005/job/18310201227) branches.
- I also tested that if there's no step running for a …
> Fix - Run artifacts workflow only for monorepo branches

- .github/workflows/server-ci-artifacts.yml
In the [previous PR](https://github.com/mattermost/mattermost/pull/25279), I added a job to check if we're running in a monorepo or not, for the `Server CI Artifacts` workflow.
However, I forgot to specify the `ref` we're checking out to do this check: this means currently we're always checking out `master`, which is always a monorepo, which is no problem for monorepo pipelines but also doesn't help `release-7.x` branches.
Here i leverage the `github.event.workflow_run` to get the SHA of the commit where the initiating workflow had completed.
Docs on that:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
- https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run …
> CLD-6507 - Fix the monorepo-checker CI job

- webapp/channels/src/actions/websocket_actions.jsx
We changed how we deal with the history replace after a channel updated event to use the channel id, to handle team changes.
Nevertheless, the channel may change for other reasons, like updating the channel header. In GMs/DMs this resulted in a JavaScript error.
Now we make sure the teamId is always defined, taking the one from the channel, and if there is none (is a GM or a DM) we use the current one (which we assume always defined).
Fix https://mattermost.atlassian.net/browse/MM-54737
```release-note
Fix issue when updating the header of GMs.
```
> MM-54737 Fix error when updating a GM/DM

- webapp/channels/src/components/channel_header_mobile/unmute_channel_button/unmute_channel_button.test.tsx
- webapp/channels/src/components/channel_header_mobile/unmute_channel_button/unmute_channel_button.tsx
This pull request migrates the existing unmute_channel_button component to a react functional component.
Fixes: https://github.com/mattermost/mattermost/issues/24781
Jira: https://mattermost.atlassian.net/browse/MM-54820
```release-note
NONE
```
> [MM-54820] Convert ./components/channel_header_mobile/unmute_channel_button/unmute_channel_button.tsx from Class Component to Function Component

- store/searchtest/post_layer.go
- store/sqlstore/post_store.go
[MM-54357] Recent Mentions is showing posts for other similar named users. (#25010)
* Handle double quotes in Postgres
* quote the username when performing the search
(cherry picked from commit dfb561a6413d2e703d0f8cd83a77d10f5e150819)
[MM-54357]: https://mattermost.atlassian.net/browse/MM-54357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Related WebApp PR: https://github.com/mattermost/mattermost-webapp/pull/12423
```release-note
NONE
```
> release-7.8 cherry pick of #25010

- webapp/channels/src/components/preparing_workspace/preparing_workspace.tsx
The preparing workspace page would redirect to `/channelstown-square` instead of `/channels/town-square`. This worked, because the webapp router would spit you out at the default channel regardless, but this fixes the issue anyways. 
https://mattermost.atlassian.net/browse/CLD-6528
```release-note
None
```
> [CLD-6528] Fix preparing workspace redirecting to invalid channel

- server/channels/app/platform/web_conn.go
- server/public/model/websocket_message.go
- server/public/model/websocket_message_test.go
Marshalling a json.RawMessage is not zero overhead. Instead,
it compacts the raw message which starts to have an overhead
at scale.
https://github.com/golang/go/issues/33422
Since we have full control over the message constructed, we
can simply write the byte slice into the network stream.
This gives considerable performance boost.
```
goos: linux
goarch: amd64
pkg: github.com/mattermost/mattermost/server/public/model
cpu: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
│   old.txt    │              new_2.txt              │
│    sec/op    │   sec/op     vs base                │
EncodeJSON-8   1640.5n ± 2%   289.6n ± 1%  -82.35% (p=0.000 n=10)
│  old.txt   │             new_2.txt             │
│    B/op    │    B/op     vs base               │
EncodeJSON-8   528.0 ± 0%   503.0 ± 0%  -4.73% …
```
> MM-54998: Optimize JSON marshalling in websocket broadcast

- webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
- webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Change the version we depict on the about modal. 
- Show the proper version regardless the environment
- Always show the build number . No need to keep that a secret. 
- Show `n/a` buildNumber when local development and `dev` as version
Related issue: https://github.com/mattermost/mattermost/issues/24034
https://mattermost.atlassian.net/browse/CLD-6573
```release-note
NONE
```
> fix: Show proper version on about modal

- webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
- webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Cherry pick of #25370 on release-9.0.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25370

- webapp/channels/src/sass/components/_suggestion-list.scss
This PR fixes the horizontal scrollbar when the command description overflows while searching for slash commands. Instead, the description is now wrapped.
Fixes https://github.com/mattermost/mattermost/issues/25120
Jira https://mattermost.atlassian.net/browse/MM-55088
-->
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/10843836/70dbe7ab-01ff-4b40-a729-c4ecda12fdad) | <img width="573" alt="image" src="https://github.com/mattermost/mattermost/assets/10843836/7fd3dffd-f549-4ebf-a911-5a713a64fc7d"> |
```release-note
NONE
```
> Fixes #25120 - Horizontal scrollbar appearing on slash command autocomplete

- webapp/channels/src/components/file_info_preview/__snapshots__/file_info_preview.test.tsx.snap
- webapp/channels/src/components/file_info_preview/file_info_preview.tsx
When clicking a file preview link in the Desktop App, users would be redirected out to the browser since the link we provided included `target=_blank`, which forces a new window/tab.
This PR removes that so that it should open in the same window. I thought initially this could be an issue with files where we don't support previewing but the browser does, however, it seems that we force those to be downloaded anyways so this works.
https://mattermost.atlassian.net/browse/MM-55165
```release-note
Fixed an issue where Desktop App clients would be shown an error when trying to open file preview links
```
> [MM-55165] Remove target=_blank from file preview links

- server/Makefile
I was assuming that `make config-ldap` would create a "ready to go" configuration. In ma case, I had an old filter setting the config, resulting in missing LDAP data.
The makefile command now clears any LDAP filters.
None
```release-note
NONE
```
> Wipe LDAP filter when running make config-ldap

- webapp/channels/src/components/team_controller/team_controller.tsx
Instead of using `try` and `catch` use a go-style of returning actually errors for anticipated issues and let exceptions happen for things that are - well- exceptionally.
I tried adding a snapshot test to ensure the component renders as expected when `initializeTeam` or `joinTeam` throws, but it's hard to mock all the props.
https://mattermost.atlassian.net/browse/MM-55412
```release-note
NONE
```
> [MM-55412] Use go-style error handling in team_controller

- server/channels/api4/ip_filtering.go
- server/channels/api4/ip_filtering_test.go
Master pipeline has a flaky test - it seems that there is some propagation issue with both the license and the cloud mock, and their usage inside a go routine. See thread here for more discussion on the issue: https://community.mattermost.com/private-core/pl/taeawck8up8cpqesimi5sro96y
For now I've opted to move the license and cloud check outside of the go routine, resolving the flakiness. Will follow up later with the server team to try and figure out the root cause of the propagation issues
https://mattermost.atlassian.net/browse/CLD-6627
```release-note
None
```
> Fix flaky test api4/Test_applyIPFilters

- server/channels/store/sqlstore/migrate.go
We were not handling the error from initConnection.
https://mattermost.atlassian.net/browse/MM-55450
```release-note
NONE
```
> MM-55450: Handle error in db migrate phase

- server/i18n/en.json
Desktop app v5.6 will include Electron v27.0.2, which includes Chrome v118+.
```release-note
Updated minimum required Edge and Chrome versions to 118+.
```
> Update minimum supported Edge and Chrome versions

- webapp/channels/src/sass/components/_suggestion-list.scss
Fixed a bug where team name in channel switcher was not right-aligned.
The bug was caused by #24800 when it accidentally increased the width of div that contained team name.
Fixes https://mattermost.atlassian.net/browse/MM-55336
```release-note
none
```
> [MM-55336] Fixed team name alignment in channel switcher

- server/channels/app/product_notices.go
- server/channels/app/product_notices_test.go
Cherry pick of #25435 on release-9.0.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25435

- server/channels/app/platform/session.go
- server/channels/app/platform/session_test.go
- server/channels/app/user.go
(cherry picked from commit 818a48190ed0c27e231fd82d545142a10f440ee0)
Cherry-pick - https://github.com/mattermost/mattermost/pull/25156
```release-note
Update session roles when user/guest is promoted/demoted.
```
> MM-54774 - update session roles when promote/demote guests (#25156)

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
Cherry pick of #25226 on release-9.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25226

- webapp/channels/src/components/post_view/post_recent_reactions/post_recent_reactions.tsx
- webapp/channels/src/components/post_view/reaction/__snapshots__/reaction.test.tsx.snap
- webapp/channels/src/components/post_view/reaction/reaction.scss
- webapp/channels/src/components/post_view/reaction/reaction.tsx
- webapp/channels/src/components/post_view/reaction/reaction_tooltip/reaction_tooltip.tsx
- webapp/channels/src/sass/components/_emoticons.scss
- webapp/channels/src/sass/components/_tooltip.scss
MM-55293 + MM-36719 - Updating emoji icon on hover and on popover
Fixes https://mattermost.atlassian.net/browse/MM-36719
Fixes https://mattermost.atlassian.net/browse/MM-55293
```release-note
NONE
```
> MM-55293 + MM-36719 - Updating emoji icon on hover and on popover

- server/channels/app/notification.go
- server/channels/app/notification_test.go
- server/channels/app/platform/helper_test.go
- server/channels/app/platform/service.go
- server/channels/app/platform/web_broadcast_hook.go
- server/channels/app/platform/web_broadcast_hook_test.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
- server/channels/app/server.go
- server/channels/app/web_broadcast_hooks.go
- server/channels/app/web_broadcast_hooks_test.go
- server/public/model/websocket_message.go
- server/public/utils/utils.go
- server/public/utils/utils_test.go
This is a backport of https://github.com/mattermost/mattermost/pull/24641.
The reason this is being manually cherry-picked is because:
1. There was a git conflict with some import statements in one file
2. After cherry-picking, I found out that I was using a newer utility function. It was added in https://github.com/mattermost/mattermost/pull/24262, but since that PR includes more changes to use that function everywhere, I manually copied it over instead of cherry-picking the whole thing. 
Outside of those two things, everything else is as it was on the original PR.
MM-54328
```release-note
Added new way to modify WebSocket messages sent to individual connections
```
> MM-54238 Add WebSocket broadcast hook and don't broadcast when other users were mentioned (8.1)

- server/cmd/mmctl/commands/export.go
- server/cmd/mmctl/docs/mmctl_export_create.rst
Updated mmctl export create command flag to align with product documentation (updated via https://github.com/mattermost/docs/pull/6796)
```release-note
NONE
```
> Updated mmctl export create command flag

- server/channels/app/channel.go
- server/channels/app/channel_test.go
Fixed a bug where channel admin wasn't being set when converting GM to private channel. The user who converts the channel becomes the admin.
Fixes https://mattermost.atlassian.net/browse/MM-55408
```release-note
Fixed a bug where channel admin wasn't being set when converting GM to private channel. The user who converts the channel becomes the channel admin.
```
> [MM-55408] Fixed a bug where channel admin wasn't set when converting GM to private channel

- webapp/channels/src/sass/components/_emoticons.scss
Updating custom emoji hover state
Looks like the custom emoji is not using a sprite (obviously), so the zooming effect is a bit different via css, which I missed.
```release-note
NONE
```
> Updating custom emoji hover state

- server/channels/app/migrations.go
Cherrypick of #24342 for v9.2
```release-note
Updated the fix to run on license change on running server, thus removing the step to restart Mattermost server for the fix to take affect.
```
> Cherrypick of #24342 for v9.2

- server/channels/api4/drafts.go
- server/channels/app/app_iface.go
- server/channels/app/draft.go
- server/channels/app/draft_test.go
- server/channels/app/opentracing/opentracing_layer.go
We have an extra unnecessary call to `Store().Draft().Get()` that we can remove here.
https://mattermost.atlassian.net/browse/MM-55631
```release-note
NONE
```
> [MM-55631] Remove extra call to Draft().Get()

- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
When updating a remote user via Shared Channel sync, the username or email may be changed.  If a collision occurs, the username is munged until it is unique.  This is done by checking the specific error code from the user store.
Unfortunately the user store is inconsistent in the error types for collisions between inserting users and updating users.   
`SqlUserStore.Save` returns `store.ErrInvalidInput` on collision.  `SqlUserStore.Update` returns `store.ErrConflict` on collision.  
Shared Channels was looking for `store.ErrInvalidInput` when updating and failing to detect collisions.  This only happens when a username or email is changed.
The fix is resilient to User.Store becoming consistent in the future.
https://mattermost.atlassian.net/browse/MM-55983
```release-note
NONE
```
> Fix username collision for shared channels sync update

- server/platform/services/sharedchannel/util.go
- server/platform/services/sharedchannel/util_test.go
When a remote username collides with an existing local one, the remote username is modified to make it unique.  The mung method used a tilde plus number, however the tilde is not a valid username character and the user create call fails.
`SharedChannelServiceError [2023-11-29 15:48:17.466 -05:00] Error upserting sync user remote=tower channel_id=7n6nd4gyp7y6xcdduf9oadc9so user_id=f1zbmzur8iyafjjnq8pqxwqn7w  error="error inserting sync user f1zbmzur8iyafjjnq8pqxwqn7w: User.IsValid:  Username must begin with a letter, and contain between 3 to 22 lowercase characters made up of numbers, letters, and the symbols ".", "-", and "_".,  user_id=f1zbmzur8iyafjjnq8pqxwqn7w username=dlauder~2:tower"`
The tilde has been changed to a valid character '-'.     `dlauder~2:tower`  -->  `dlauder-2:tower` …
> Fix mung of usernames on collision in shared channels; tilde is not a valid character

- server/Makefile
https://mattermost.atlassian.net/browse/MM-56036
```release-note
NONE
```
> Pin morph and dbcmp versions used in test-migration

- server/channels/api4/group.go
- server/channels/api4/notify_admin_test.go
- server/channels/api4/post_test.go
- server/channels/api4/user.go
- server/channels/api4/user_test.go
- server/channels/app/app_iface.go
- server/channels/app/authorization.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/post.go
- server/channels/web/context.go
- server/cmd/mmctl/commands/bot_e2e_test.go
- server/cmd/mmctl/commands/channel_e2e_test.go
- server/cmd/mmctl/commands/channel_users_e2e_test.go
- server/cmd/mmctl/commands/command_e2e_test.go
- server/cmd/mmctl/commands/export_e2e_test.go
- server/cmd/mmctl/commands/extract_e2e_test.go
- server/cmd/mmctl/commands/group_e2e_test.go
- server/cmd/mmctl/commands/import_e2e_test.go
- server/cmd/mmctl/commands/plugin_e2e_test.go
- server/cmd/mmctl/commands/plugin_marketplace_e2e_test.go
- server/cmd/mmctl/commands/team_e2e_test.go
- server/cmd/mmctl/commands/token_e2e_test.go
- server/cmd/mmctl/commands/user_e2e_test.go
- server/public/model/permission.go
- server/public/model/permission_test.go
- server/public/model/utils.go
- server/public/model/utils_test.go
- https://github.com/mattermost/mattermost/pull/25648/commits/7e24f35b5d9cf8f38de3125762448c8e6965a74f: If the `where` field in `model.AppError` is not present (which is the case for anyone using `model.Client4` as `Where` is not sent over the wire), the returned `Error()` would look weird, as it contains ` :` as a prefix.
- https://github.com/mattermost/mattermost/pull/25648/commits/1c36a44c7a221de3dc7f520bebb6033a97c8bca6: The permission would contain a trailing comma, making the rendered `Error()` awkward to read. I also moved `MakePermissionError` into `model` to make it easier to test. (And added a test :wink:)
https://mattermost.atlassian.net/browse/MM-56061
```release-note
Only render where field in model.AppError when it's present
```
> [MM-56061] Only render where field in model.AppError when it's present

- webapp/channels/src/components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
- webapp/channels/src/components/rhs_thread/rhs_thread.test.tsx
- webapp/channels/src/components/rhs_thread/rhs_thread.tsx
- webapp/channels/src/components/sidebar_right/index.ts
- webapp/channels/src/components/sidebar_right/sidebar_right.test.tsx
- webapp/channels/src/components/sidebar_right/sidebar_right.tsx
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
There are certain screens (Global Threads and Global Drafts) that "suppress" the RHS.
The RHS autofocus the input box when it is mounted.
This caused an issue where navigating to a different channel from the Global Threads or Global Drafts the focus went to the thread instead of the center pane.
This is fixed by passing a property when we are mounting the RHS from suppression, so it does not focus in that scenario.
https://mattermost.atlassian.net/browse/MM-43331
```release-note
RHS stops getting the focus when navigating from Global Threads or Global Drafts
```
> [MM-43331] No autofocus after RHS supression

- webapp/channels/src/utils/markdown/link_only_renderer.test.tsx
- webapp/channels/src/utils/markdown/remove_markdown.test.tsx
- webapp/channels/src/utils/markdown/remove_markdown.ts
The current tests go through `stripMarkdown` which returns unescaped text because it expects to be rendered by React. The `Markdown` component uses `dangerouslySetInnerHTML`, so we should test its renderer separately.
https://mattermost.atlassian.net/browse/MM-56094
```release-note
NONE
```
> MM-56094 Add dedicated tests for RemoveMarkdown renderer

- server/channels/api4/websocket_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/websocket_router.go
- server/public/model/websocket_client.go
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
- webapp/platform/client/src/websocket.ts
We also track the channelID of the thread opened.
Additionally on every connection create or re-connect
with an existing queue, we reset the active state to empty
to avoid any edge-cases.
https://mattermost.atlassian.net/browse/MM-56071
```release-note
NONE
```
> MM-56071: Thread presence indicator

- server/go.mod
- server/go.sum
This was failing with the following error:
```
github.com/mattermost/mattermost/server/public@v0.0.10-0.20231116111926-0bc542620ce2: invalid version: unknown revision 0bc542620ce2
```
The reason is probably that `0bc5426` is not in the `master` tree. This happened to me again a few month back from now. Module workspaces should've been handling this but I am still getting errors. 
```release-note
NONE
```
> bump the server/public module revision to an existing commit

- server/Makefile
Developers might want to use a different go version then one installed as `go`. They can now do that by setting the `GO` env variable (same for `DELVE`).
See https://go.dev/doc/manage-install for more information on how to install different go versions.
Once go1.21 is widely adopted, the `GOTOOLCHAIN` variable will serve the same purpose. See https://go.dev/blog/toolchain for more details.
NONE
```release-note
NONE
```
> Allow developers to set a custom go version via env variables

- api/v4/source/bookmarks.yaml
- server/channels/api4/channel_bookmark.go
- server/channels/api4/channel_bookmark_test.go
- server/channels/app/channel_bookmark.go
- server/channels/store/sqlstore/channel_bookmark_store.go
- server/channels/store/storetest/channel_bookmark.go
- server/channels/web/params.go
- server/i18n/en.json
- server/public/model/client4.go
This PR adds the update channel bookmarks sort order endpoint. Sits on top of https://github.com/mattermost/mattermost/pull/25653, so it should be merged after it
https://mattermost.atlassian.net/browse/MM-54420
```release-note
Added update channel bookmark sort order endpoint at /api/v4/channels/{channel_id}/bookmarks/{bookmark_id}/sort_order.
```
> Adds update channel bookmark sort order endpoint

- api/v4/source/bookmarks.yaml
- server/channels/api4/apitestlib.go
- server/channels/api4/channel_bookmark.go
- server/channels/api4/channel_bookmark_test.go
- server/public/model/client4.go
This PR adds the list channel bookmarks endpoint. Sits on top of https://github.com/mattermost/mattermost/pull/25693, so it should be merged after it
https://mattermost.atlassian.net/browse/MM-54422
```release-note
Added list channel bookmarks endpoint at /api/v4/channels/{channel_id}/bookmarks.
```
> Adds list channel bookmarks endpoint

- webapp/channels/src/components/dot_menu/dot_menu.tsx
To get around the issue where MUI and React Bootstrap fight for focus, we have to ensure the menu is fully closed before the modal starts to fade in. `handleDropdownOpened` doesn't do that fast enough, but `forceCloseMenu` does. I think that's because the former lets the menu fade out while the latter just closes it immediately
https://mattermost.atlassian.net/browse/MM-56087
```release-note
NONE
```
> MM-56087 Change Move Thread hotkey to force close menu

- server/i18n/en.json
This PR fixes an issue in a merge issue from https://github.com/mattermost/mattermost/pull/25589. Essentially a translation was put in the wrong order during the cherry-pick. 
```release-note
NONE
```
> Fix translation ordering for release-8.1

- server/channels/api4/websocket_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/websocket_router.go
- server/public/model/websocket_client.go
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
- webapp/platform/client/src/websocket.ts
We can have 2 types of threads open at the same time. One from
the thread view, and another from RHS.
We add another variable to distinguish between the 2 states.
In future, if we have the ability for more than 2 threads, then
we would need to track by threadID.
https://mattermost.atlassian.net/browse/MM-56071
```release-note
NONE
```
> MM-56071: Track multiple threads

- webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
When a plugin dismissed a post, this was done correctly on the back-end, but the front-end kept the post visible without any trace of the post being rejected.
This was because batchActions does not seem to support thunks, so we should call dispatch directly on the `removePost` function.
We may have to do this in other parts of the app, but we will look into it at a different time.
https://mattermost.atlassian.net/browse/MM-55200
```release-note
Fix error where posts dismissed by a plugin were not properly removed from the view.
```
> Fix auto delete post when dismissed by a plugin

- server/channels/api4/license_test.go
https://mattermost.atlassian.net/browse/MM-56359
Introduced in https://github.com/mattermost/mattermost/pull/21364.
```release-note
NONE
```
> MM-56359: Skip TestUploadLicenseFile

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/localstore.go
I didn't get why this was there anyway, if `maxDepth` is `0`, we just stop recursion anyway. This is also not an actionable item from the administrator point of view right?
I mean this always warns when using local filebackend's list directory method.
```Go
func (b *LocalFileBackend) ListDirectory(path string) ([]string, error) {
return appendRecursively(b.directory, path, 0)
}
```
```release-note
NONE
```
> shared/filestore/localstore.go: remove unnecessary warning

- server/channels/app/channel.go
- server/channels/app/command.go
- server/channels/app/integration_action.go
- server/channels/app/notification.go
- server/channels/app/post.go
- server/channels/app/team.go
- server/channels/app/user.go
- server/channels/app/webhook.go
- server/channels/store/searchlayer/user_layer.go
- server/channels/store/sqlstore/post_store.go
- server/channels/store/store.go
- server/platform/services/telemetry/telemetry.go
The campain started with https://github.com/mattermost/mattermost/pull/25086 is over. All code has been migrated to use the generic variant of `StoreResult`, which is `GenericStoreResult` and hence, `StoreResult` can be removed and `GenericStoreResult` renamed back to `StoreResult`.
https://mattermost.atlassian.net/browse/MM-56284
```release-note
NONE
```
> [MM-56284] Remove non-generic StoreResult

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
We weren't accounting for public channels that users were not a member on when checking permissions for channel member stats. This PR runs the `HasPermissionToReadChannel` method on all channels passed up, which will not fail on a public channel assuming the user can see the public channel in the first place.
https://mattermost.atlassian.net/browse/MM-56266
```release-note
NONE
```
> [MM-56266] Check for public channels when getting channel member counts to avoid 403 errors

- server/channels/api4/group.go
Fixes calls to `MakePermissionError` on `App` that should have been migrated to call `model`
```release-note
NONE
```
> Fix make permission error

- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/mocks/ChannelStore.go
- server/channels/store/timerlayer/timerlayer.go
When checking if a user has access to a post on a specific channel, we weren't accounting for the fact that the channel might be archived, as we were just fetching the channel member, irrespective of the setting allowing/denying users to view archived channels.
This PR adds a parameter to the store call to remove archived channels from the fetched member list, and uses the view archived channel setting in the permission check to toggle this on or off.
https://mattermost.atlassian.net/browse/MM-56174
```release-note
Fixed an issue where users could access archived channels when `Allow users to view archived channels` was set to false.
```
> [MM-56174] Account for archived channels in channel member for post permission check

- server/channels/app/authorization.go
- server/channels/app/channel.go
- server/channels/app/post.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/searchlayer/channel_layer.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/mocks/ChannelStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
Load tests show that channelstore.GetMember and
channelstore.GetMembersForUser are among the chief
queries that take up CPU in the DB.
In this PR, we attempt some strategic optimizations to
reduce/optimize calls to channelstore.GetMember
1. Optimize  `(a *App) HasPermissionToChannel`
We replace GetChannelMember with GetAllChannelMembersForUser
because it's cache backed. So although it gets more data,
it does not hit the DB and saves some latency.
2. Optimize getPostsForChannelAroundLastUnread
We repace getChannelMember with getChannelMemberLastViewedAt
which queries just the ChannelMembers table. This is because
in the app layer, we just use the LastViewedAt attribute.
Therefore, there is no reason to join with 5 tables when
a single table can do the job.
3. Optimize …
> MM-55295: Improve DB performance of some (Take 2)

- server/Makefile
This PR removes the `enterprise` folder deletion from the `make nuke` target, as after https://github.com/mattermost/mattermost/pull/24879 this is not necessary anymore.
```release-note
NONE
```
> Removes enterprise deletion from nuke make target

- webapp/channels/src/sass/components/_post-right.scss
This PR extends the width of the `MsgTyping` component to the full width of the post textbox in a thread.
Fixes https://github.com/mattermost/mattermost/issues/25829
Jira https://mattermost.atlassian.net/browse/MM-56258
|----|----|
| <img width="389" alt="Screenshot 2024-01-06 at 17 25 42" src="https://github.com/mattermost/mattermost/assets/37827647/e438aa4b-3e76-4de1-8079-2838099919d5"> | <img width="396" alt="Screenshot 2024-01-06 at 17 25 13" src="https://github.com/mattermost/mattermost/assets/37827647/b991f070-cf97-41d0-aba7-e364ef1671e1">|
```
NONE
```
> [MM-56258] Extend the width of the "User is typing" message in a thread

- server/channels/api4/plugin_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/plugin_api_tests/manual.test_websocket_session/main.go
None of the WebSocket plugin hooks we provide implement `plugin.Context` and the one that includes a `model.Session` object (`WebSocketMessageHasBeenPosted`) has it completely empty. This makes it very hard to have any control from the plugin side on which session messages belong to and potentially track session expiration. PR adds this information to the cloned request object prior to calling the hook. 
I am including purely the id value because this will be called for every message received so I'd like to limit the data we need to send through the RPC layer. The rationale is that given the id, if the plugin needs more, they can use the existing [`GetSession`](https://developers.mattermost.com/integrate/reference/server/server-reference/#API.GetSession) call to retrieve the rest.
To add …
> [MM-54359] Include session id in request info of `WebSocketMessageHasBeenPosted`

- server/channels/api4/cloud.go
- server/channels/app/cloud.go
- server/public/model/cloud.go
- webapp/channels/src/components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
- webapp/channels/src/components/announcement_bar/cloud_annual_renewal/index.tsx
- webapp/channels/src/components/purchase_modal/index.ts
- webapp/channels/src/utils/cloud_utils.ts
- webapp/platform/types/src/cloud.ts
The annual renewal announcement bar has a small bug where after you dismiss the 60 day one it will never enter the condition to return null. I've removed the check that's causing the issue, and put an else to return null at the end of the if/else if chain. 
I've also added a small check in 2 places so that the banners and emails for renewals aren't sent to those subscriptions that are on a trial, because their start/end dates will be within the 60 day renewal period due to the way Stripe handles CurrentPeriodStart and CurrentPeriodEnd while that subscription is trialing.
https://mattermost.atlassian.net/browse/CLD-6950
```release-note
None
```
> [CLD-6536] Adjustments to cloud annual renewal announcement bar

- e2e-tests/cypress/cypress.config.ts
- e2e-tests/cypress/tests/support/api/cloud_default_config.json
- e2e-tests/cypress/tests/support/api/on_prem_default_config.json
- e2e-tests/cypress/tests/support/api/system.js
- e2e-tests/playwright/support/server/default_config.ts
- e2e-tests/playwright/test.config.ts
- e2e-tests/playwright/types.ts
- webapp/platform/types/src/config.ts
- Made pushNotificationServer configurable in E2E via env
Others:
- Updated the server config
- Updated config types
https://mattermost.atlassian.net/browse/CLD-6922
n/a
```release-note
NONE
```
> Cypress/E2E: Make pushNotificationServer configurable in E2E via env

- webapp/channels/src/sass/routes/_get-app.scss
The margin between the buttons and the "Remember my preference" box was missing. This PR adds the margin to the bottom as well to space properly.
https://mattermost.atlassian.net/browse/MM-56522
|----|----|
| <img width="470" alt="image" src="https://github.com/mattermost/mattermost/assets/52460000/374cf7fc-6401-4cf3-834c-2c5bfa739632"> | <img width="485" alt="image" src="https://github.com/mattermost/mattermost/assets/52460000/7fd71778-270f-4d07-b52d-b457786a641f"> |
```release-note
NONE
```
> [MM-56522] Fix margin on landing page remember preference checkbox

- server/channels/app/channel_test.go
- server/channels/app/notification_test.go
Instead of having `connectFakeWebSocket` always read the first two WS messages and assume it knows what they are, I added a new parameter to let test code specify which WS message types it cares about in the test and which should be discarded.
MM-56565
```release-note
NONE
```
> MM-56565 Add filter to connectFakeWebSocket to fix flakiness

- server/channels/store/sqlstore/channel_store.go
Whoops. One of my previous PRs left in some extra trace logging I meant to remove
```release-note
NONE
```
> Remove accidentally included trace logs

- webapp/channels/src/actions/cloud.tsx
- webapp/channels/src/components/payment_form/country_selector.tsx
- webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/countries.ts
Changes occurrences of "Country" to "Country/Region" in the country selectors. Overrides ISO3166 country name for a certain island in the pacific.
This change applies to anywhere the country selector is used in product - including
Cloud Purchase Modal
Self hosted purchase modal
Payment method page in the system console
Start trial form modal
etc
https://mattermost.atlassian.net/browse/CLD-6487
```release-note
None
```
> [CLD-6487] Replace 'Country' with 'Country/Region' in country selectors

- server/channels/store/sqlstore/user_store.go
- server/channels/store/storetest/user_store.go
This PR turns off the post stats for MySQL users, as the performance is not up to par.
https://mattermost.atlassian.net/browse/MM-56362
```release-note
NONE
```
> [MM-56362] Disable post stats for MySQL

- server/channels/store/sqlstore/channel_store.go
- server/channels/store/storetest/channel_store.go
PR https://github.com/mattermost/mattermost/pull/18114
mistakenly left out updating the lastUpdateAt of the field.
We fix that here.
https://mattermost.atlassian.net/browse/MM-56457
```release-note
NONE
```
> MM-56457: Update LastUpdateAt in UpdateMemberNotifyProps

- server/channels/app/server.go
During server start, runLicenseExpirationCheckJob was being called
from a goroutine which would eventually call SetLicense and iterate
through the ps.licenseListeners.
But at the same time doElasticsearchFixChannelIndex would also
call AddLicenseListener and try to edit the ps.licenseListeners map,
leading to a race condition.
To fix this, we simply move the runLicenseExpirationCheckJob
to be synchronous. This fixes the race, and also improves
the correctness because after https://github.com/mattermost/mattermost/commit/1f431bf72276b98edd35fc5e130d08d2491c2c39
there was no license check being done synchronously during server boot.
So theoretically, the server might go on doing some stuff
until the Go runtime decides to run the license check goroutine. …
> MM-56611: Move license expiration check to be synchronous

- server/build/docker-compose.common.yml
Ubuntu recently upgraded Docker compose packages to v25.0 which broke short-form `ports` syntax in some cases.  This PR fixes it by switching to long form syntax. 
This only affects development environments using docker compose.  Error happened even when mysql was excluded from the services list.
Symptoms were an error on `make run-server`:
```
Starting docker containers
docker compose rm start_dependencies
No stopped containers
go run ./build/docker-compose-generator/main.go mysql postgres inbucket  minio openldap elasticsearch | docker compose -f docker-compose.makefile.yml -f /dev/stdin  run -T --rm start_dependencies
service ports services.mysql-read-replica.ports.[0] is missing a target port
make: *** [Makefile:235: start-docker] Error 15
```
Ref: …
> Fix breaking change in Docker 25 by using long form port definition

- server/channels/api4/post_test.go
- server/channels/app/post.go
On https://github.com/mattermost/mattermost/pull/24701 we started using the Post Info endpoint. This had a bug that we did not caught on that PR.
The problem is that we are checking permissions before checking membership. If a user is a member of the channel, they have access to the channel, no matter their permissions. But the code was first checking the manage private channel members permission, which can be revoked in the settings.
The issue is fixed by checking first for the channel membership.
Fix https://mattermost.atlassian.net/browse/MM-56575
```release-note
Fix issue where with certain configuration, users were not able to navigate through links to private channels they are member of.
```
> Fix issue where users may not follow links to private messages they belong to

- server/cmd/mmctl/commands/utils_unix_test.go
The failure seemed to be due to incorect detection from gotestsum
itself rather than any failure in the test.
I note that from that time onwards, gotestsum has had a new release
and we are using that.
I also ran the test several times with gotestsum and could not
repro this. Let's hope that the new version of gotestsum has fixed
the issue. Otherwise, there isn't much we can do.
https://mattermost.atlassian.net/browse/MM-54264
```release-note
NONE
```
> MM-54264: Unblock TestCheckValidSocket

- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/i18n/en.json
https://mattermost.atlassian.net/browse/MM-56631
```release-note
Clarify that LDAP profile picture setting is optional
```
> [MM-56631] Clarify that LDAP profile picture setting is optional

- server/go.mod
- server/go.sum
Bump golang.org/x/image dependency
I do not have a ticket... How do I get one ? (This is my second contribution...)
The problem is that an user can crash the server with a malformed webp image (like `UklGRjEAAABXRUJQVlA4WAoAAAAAAAAAAAAAAAAAVlA4WAoAAAAQAAAA////////QUxQSAEAAAAA` base64-decoded). This got fixed in golang.org/x/image v0.15 (by https://go-review.googlesource.com/c/image/+/551416 precisely)
This was deemed out of scope on HackerOne as "Denial of service attacks that only affect yourself"
Stack trace from the server is 
```
runtime: out of memory: cannot allocate 281474976710656-byte block (136282112 in use)
fatal error: out of memory
goroutine 739 [running]:
runtime.throw({0x278aad6?, 0x800000000?})
runtime/panic.go:1047 +0x5d fp=0xc0054c9478 sp=0xc0054c9448 pc=0x438d1d …
```
> Bump golang.org/x/image dependency

- webapp/channels/src/utils/markdown/index.test.ts
- webapp/channels/src/utils/markdown/renderer.tsx
We added a new line I guess for style purposes to the result of the markdown renderer. That new-line normally won't be displayed, but in certain cases (not sure the root cause) it was displayed, creating a weird spacing between the list and other elements.
Removing that line break fixes the issue.
https://mattermost.atlassian.net/browse/MM-42628
```release-note
Fixed markdown issue where in some occasions, extra space was found before a list.
```
> MM-42628 Fix wrong spacing between header and lists when a inline image is used

- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
In https://github.com/mattermost/mattermost/pull/25622 we added some styles that are (apparently) not needed, and were messing with the alignment on tooltips.
This PRs removes those unneeded styles.
NONE
```release-note
Fix shortcuts alignment on tooltips
```
> Fix shortcuts alignment on tooltips

- server/public/model/utils.go
Small refacto to use Golang's 1.17 UnixMilli instead of the current `UnixNano/time.Milli` approach.
https://mattermost.atlassian.net/browse/MM-56680
```release-note
NONE
```
> [MM-56680] Use Golang UnixMilli instead of UnixNano in Milli helpers

- webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.test.tsx
- webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_bar.tsx
- webapp/channels/src/components/advanced_text_editor/formatting_bar/hooks.tsx
Turns out that a `button` without a `type` set will trigger a form's `onSubmit` when clicked on. This is the one button that didn't have a `type` set
MM-56705
```release-note
Fixed clicking on the more formatting options button in the post textbox sending the draft post
```
> MM-56705 Don't send post when clicking on the more formatting options button

- webapp/channels/src/components/profile_popover/profile_popover_name/user_name.tsx
In https://github.com/mattermost/mattermost/pull/25608 , when refactoring the profile popover, I missed one negation in the code, so the username was showing as a header when there was already a full name, and not showing as a header when there was no full name.
This PR fixes that.
Fix https://mattermost.atlassian.net/browse/MM-56596
I think this will be in the same release as the mentioned PR, so there should be no need for release notes.
```release-note
NONE
```
> MM-56596 Fix username style in profile popover

- webapp/channels/package.json
- webapp/package-lock.json
Based on a suggestion from https://github.com/mattermost/mattermost/issues/24155, adding these as required dependencies might help solve some issues where they're not downloaded by NPM automatically for whatever reason. These libraries tend to cause problems for many contributors, so hopefully this reduces the chances of those problems happening.
Fixes #24155
https://mattermost.atlassian.net/browse/MM-53919
```release-note
NONE
```
> MM-53919 Add imagemin-gifsicle and imagemin-mozjpeg as required dependencies

- server/channels/app/channel_category_test.go
- server/channels/app/email/helper_test.go
- server/channels/app/slashcommands/auto_users.go
- server/channels/app/slashcommands/command_loadtest.go
- server/channels/app/teams/teams.go
- server/channels/manualtesting/manual_testing.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/searchlayer/team_layer.go
- server/channels/store/searchtest/helper.go
- server/channels/store/sqlstore/integrity_test.go
- server/channels/store/sqlstore/team_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/compliance_store.go
- server/channels/store/storetest/group_store.go
- server/channels/store/storetest/mocks/TeamStore.go
- server/channels/store/storetest/post_store.go
- server/channels/store/storetest/retention_policy_store.go
- server/channels/store/storetest/team_store.go
- server/channels/store/storetest/user_store.go
- server/channels/store/timerlayer/timerlayer.go
Fixes #26027
Add Request Context to TeamStore.SaveMember
JIRA: https://mattermost.atlassian.net/browse/MM-55736
```release-note
NONE
```
> MM-55736 Add Request Context to TeamStore.SaveMember

- webapp/channels/src/utils/utils.tsx
When an admin clicks on a link to a private channel they're not a member of, this crashed the app by incorrectly trying to render a Channel object instead of its name.
There's no test included with this PR because I did this as part of migrating `stores/index.js` to TS which caught this automatically. I'm just submitting it separately because it's small and self-contained.
https://mattermost.atlassian.net/browse/MM-56759
```release-note
Fixed a web app crash when a system admin clicks on a link to a private channel that they're not a member of
```
> MM-56759 Fix crash caused by joinPrivateChannelPrompt

- webapp/channels/src/sass/components/_modal.scss
As a user, I want to quit the preview mode by clicking outside the doc preview. 
https://mattermost.atlassian.net/browse/MM-56602
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/39456891/23c647d8-9a18-45c8-9c46-66a0eee13231)| ![image](https://github.com/mattermost/mattermost/assets/39456891/629fbf23-91eb-4f73-bd9b-19c16fd03989)|
> [MM-56602] Clicking outside the file preview area doesn't close the modal

- server/channels/app/notification.go
Implemented a change in the `CRTNotifier`'s `shouldChannelMemberNotifyCRT` method so that it doesn't send a notification to the user when they have global `thread reply notifications` disabled.
https://mattermost.atlassian.net/browse/MM-56180
#25948 
```release-note
Changed notifications so that, if you have Thread Reply Notifications disabled for your account and "Automatically follow threads in this channel" for a channel, you'll no longer receive thread notifications for that channel
```
> MM-56180 changed CRTNotifier condition

- webapp/channels/src/utils/text_formatting.tsx
This is a small type inference which is failing some lower versions of ts which we do for other app version. So this is a small patch to make ts checker happy regardless of its version.
```release-note
NONE
```
> Add type inference for isFormatTokenLimitError function

- webapp/channels/src/components/admin_console/system_users/system_users_date_range_menu/system_users_date_range_menu.scss
- webapp/channels/src/i18n/en.json
Two small fixes for the user reporting interface:
- Fixed the wrap issue on the date range dropdown message
- Changed "Active users" to "Activated users"
https://mattermost.atlassian.net/browse/MM-56782
https://mattermost.atlassian.net/browse/MM-56783
```release-note
NONE
```
> [MM-56782][MM-56783] Fix two small visuals with the user reporting interface

- server/cmd/mmctl/commands/user_e2e_test.go
Address testing issues introduced by https://github.com/mattermost/mattermost/pull/25721, avoiding a call to `DeletePreferences` without any preferences to delete.
None.
```release-note
NONE
```
> fix build: do not delete an empty set of preferences

- webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
- webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
- webapp/channels/src/components/emoji_picker/emoji_picker.tsx
- Auto selects the first emoji in the emoji picker so the user can press enter to insert the first emoji without navigating with the arrow keys
Fixes https://github.com/mattermost/mattermost/issues/26119
```
First emoji is auto selected in the emoji picker
```
> [MM-56683] Auto select first emoji in emoji picker

- server/channels/app/platform/service.go
- server/channels/app/platform/shared_channel_notifier.go
CI is failing with racy unit test for Shared Channels due to setting and reading the `Platform.sharedChannelsService` ref.  
A recent change to remove Shared Channels service mock and use real service uncovered this race condition.
This PR fixes the issue by protecting access to the service ref with a RWMutex.
NONE
```release-note
NONE
```
> Fix racy unit tests by protecting Shared Channels service ref with a mutex

- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.jsx
A [previous change](https://github.com/mattermost/mattermost-webapp/pull/5913) that fixed an issue with the suggestion list made it so that on every clear of the list (which is what happens when the user presses ESC, OR if they select an item), the pretext would be cleared. Unfortunately though that doesn't clear the actual pretext in the textbox, which causes the list to then refresh since the pretext "changed" and needs to be refetched. The symptom of this was that a user would press ESC and the list would simply re-open.
To fix this, we want to avoid running `handlePretextChanged` for the ESC case since we're still actively using the suggestion box, meaning that we at least want to keep typing. We can also remove it for the debounced version since that will likely just loop as well. …
> [MM-56478] Only clear the suggestion pretext when the suggestion is completed and not when the list is cleared

- server/channels/app/plugin_hooks_test.go
Continuing from #26057 there's a few plugin hooks that I wanted to ensure worked the way I expected to. Unfortunately they don't work in one case (which is how I found MM-56776), but it's better for us to know that before we shipped the MS Teams plugin feature that relies on it.
```release-note
NONE
```
> Add some tests for plugin hooks used by MS Teams plugin automute

- server/Makefile
- Prepackage Calls v0.24.0
- https://mattermost.atlassian.net/browse/MM-56571
```release-note
Prepackage Calls version v0.24.0
```
> MM-56571 - Update prepackaged calls to v0.24.0

- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_comment/index.ts
- webapp/channels/src/plugins/exported_create_post.tsx
Follow up to https://github.com/mattermost/mattermost/pull/24972 that exposed the AdvancedCreateComment to the LLM plugin.
The original PR restricted plugins from specifying all props. This caused the LLM plugin to use a nasty workaround to fix a bug where the component would disable itself for non system admins if a channelID was not spcified. 
This PR exposes all the props to prevent further issues. Also works around some code by specifying that a plugin is using the component. 
```release-note
NONE
```
> Allow plugins to specify all props for create comment.

- server/channels/app/channel.go
- server/channels/app/plugin_hooks_test.go
Somehow, we forgot to call this hook for GM channels even though it's called for both regular channels and DMs
MM-56776
```release-note
Fixed ChannelHasBeenCreated plugin hook not being called when a group channel is created
```
> MM-56776 Call ChannelHasBeenCreated plugin hook for GMs

- server/channels/app/channel.go
- server/channels/app/plugin_hooks_test.go
Cherry-pick of https://github.com/mattermost/mattermost/pull/26226
The extra unit tests added were made in some related changes, but they test pre-existing code so I just left them in
MM-56776
```release-note
Fixed ChannelHasBeenCreated plugin hook not being called when a group channel is created
```
> MM-56776 Call ChannelHasBeenCreated plugin hook for GMs (9.6)

- server/channels/app/shared_channel.go
A plugin using the Shared Channels plugin APIs that is uninstalled will log errors every minute as the shared channels service tries to ping it to ensure sync messages should continue to be generated for it.  Uninstalled plugins are not given a chance to cleanup, and this cannot unregister with the service.
Plugins are continually checked by the service to ensure they are accepting calls to their sync hooks, since sync messages can be expensive to generate and should not be done for plugins that are no longer accepting calls.  
This PR changes that error to a warning that is emitted only once per hour, and includes instructions on how to clean up the plugin's registration.
https://mattermost.atlassian.net/browse/MM-56912
```release-note
NONE
```
> Log warning when plugin using Shared Channels APIs is uninstalled

- server/channels/api4/license.go
- server/channels/api4/license_test.go
- webapp/channels/src/components/analytics/true_up_review.test.tsx
- webapp/channels/src/components/analytics/true_up_review.tsx
The true-up review card was not rendering in the event of telemetry being disabled. This meant that instances that currently send telemetry and are asked for true-up information are not able to send via the button in the true-up review card
This PR removes the telemetry config from the picture, meaning the card will always show to those eligible. 
https://mattermost.atlassian.net/browse/CLD-6430
```release-note
None
```
> [CLD-6430] Remove telemetry check from true_up_review

- server/channels/api4/ip_filtering_test.go
This line was brought over from another test - it resets the cloud mock back to whatever it was set to before the test run (a pattern that is needed elsewhere in cloud tests) - this causes a race because the cloud interface is removed before the Go routine that's sending the emails can finish. There are no subsequent actions that would actually require this to be reset so the line isn't necessary.
```release-note
None
```
> Fix flaky IP Filtering test

- webapp/channels/src/components/threading/global_threads_link/global_threads_link.scss
- webapp/channels/src/components/threading/global_threads_link/threads_icon.tsx
Fixes a minor inconsistency in icon size with the LHS Threads item compared to icons in other LHS items.
Jira https://mattermost.atlassian.net/browse/MM-56971
|----|----|
| <img width="238" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/fe209f1c-375b-4be7-83fc-03390f29e79a"> | <img width="241" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/09fc0386-214f-4a35-a147-a40a1719a17c"> |
```release-note
NONE
```
> Fix thread icon size and color

- server/public/model/integration_action.go
- server/public/model/integration_action_test.go
A Sentry crash report showed that the check `p.Integration.URL != input.integration.URL` was dereferencing a nil pointer. At that point in the code, `input.Integration` is known to be non-nil, but we still need to check whether the original, `p.Integration`, is.
Crash report: https://mattermost-mr.sentry.io/issues/4918263046/events/5738b67edcee4c9c883d40f7d26563a6
https://mattermost.atlassian.net/browse/MM-56780
--
```release-note
NONE
```
> MM-56780: Ensure p.Integration is not nil

- server/channels/app/platform/session.go
- server/channels/store/localcachelayer/terms_of_service_layer.go
- server/platform/services/cache/cache.go
- server/platform/services/cache/lru_test.go
- server/platform/services/cache/provider_test.go
This is in preparation to make the codebase
ready to use Redis. In Redis, iterating all
the keys at once is an expensive operation.
It is recommended to work on batches of keys.
Remove the Len method as it was unused.
I tried to repurpose the Keys method to iterate
on keys rather than returning all keys at once, but
it has other complicacies because the code calls
other cache functions on those keys, so to handle
the LRU cache properly, it becomes slightly more
painful.
For now, we keep it like this and rather collect
all keys from Redis and then return.
https://mattermost.atlassian.net/browse/MM-56987
```release-note
NONE
```
> MM-56987: Improve cache API

- webapp/channels/package.json
- webapp/channels/src/components/channel_header/channel_header.tsx
- webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
- webapp/channels/src/components/suggestion/switch_channel_provider.tsx
- webapp/channels/src/packages/mattermost-redux/src/utils/file_utils.ts
- webapp/channels/src/types/external/react-bootstrap.d.ts
- webapp/package-lock.json
- webapp/package.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
This was a straightforward enough upgrade. There's a couple places where TS is slightly stricter which I needed to update, but none of them seem particularly notable.
I haven't really looked at all the new features from this, but I see that they made improvements to enums and have at least started work on `using`, so those will be neat to play with eventually.
MM-57037
```release-note
Upgraded `@mattermost/client` and `@mattermost/types` to support TypeScript 5.x
```
> MM-57037 Upgrade web app and pacakges to TypeScript 5.3.3

- server/platform/shared/web/files.go
This pull request changes the `Cache-Control` header to have a `max-age=86400` instead of `no-cache`
Fixes https://github.com/mattermost/mattermost/issues/26020
Jira https://mattermost.atlassian.net/browse/MM-56651
```release-note
Changed the cache headers for file endpoints to cache privately for 24 hours, instead of not caching at all.
```
> [MM-56651] fix: set cache duration

- webapp/platform/client/package.json
- webapp/platform/types/package.json
A customer was confused as to why `mattermost-server` was in the link for the npm packages. This cleans it up a bit so that we directly link to the monorepo instead of using the redirect.
n/a
n/a
```release-note
NONE
```
> Update client and types npm packages to link to monorepo directly

- server/public/pluginapi/store.go
- server/public/pluginapi/store_test.go
Previously, we would setup both pools only when
GetMasterDB was called. This was inefficient and
would waste open connections if the replica wasn't used
at all.
We fix it to initialize the pools as they are called.
https://mattermost.atlassian.net/browse/MM-56402
```release-note
NONE
```
> MM-56402: Initialize replica conn pool on-demand
