- app/server.go
Cherry-pick https://github.com/mattermost/mattermost-server/pull/22376 into release-7.7
https://mattermost.atlassian.net/browse/MM-47489
```release-note
Shared Channels feature included in Professional license.
```
> Cherry-pick MM-47489 (Shared Channels feature included in Professional license)

- build/Dockerfile
Updating libcurl3-gnutls since the previous one was removed .
```
➜   docker run -ti --entrypoint /bin/bash debian:buster-slim@sha256:5b0b1a9a54651bbe9d4d3ee96bbda2b2a1da3d2fa198ddebbced46dfdca7f216
root@a8ad0fb9f04a:/# apt-get update
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://deb.debian.org/debian buster/main arm64 Packages [7737 kB]
Get:5 http://deb.debian.org/debian-security buster/updates/main arm64 Packages [428 kB]
Get:6 http://deb.debian.org/debian buster-updates/main arm64 Packages [8780 B]
Fetched 8387 kB in 3s (3223 kB/s)
Reading package lists... Done
root@a8ad0fb9f04a:/# apt-cache madison …
```
> update libcurl3-gnutls to 7.64.0-4+deb10u5

- model/client4.go
- store/sqlstore/license_store.go
Add support code for showing past invoices for prior self-hosted purchases
enterprise PR: https://github.com/mattermost/enterprise/pull/1385
https://mattermost.atlassian.net/browse/MM-49495
No release note, this mattermost-server PR only supports test code for the backing enterprise code and has a small refactor on a SQL query that doesn't affect anything customer facing.
```release-note
NONE
```
> Mm 49495 Show past invoices for prior self-hosted purchases

- build/Dockerfile
Update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390) 
https://mattermost.atlassian.net/browse/CLD-5213
```release-note
```
> update libcurl3-gnutls to 7.64.0-4+deb10u5 (#22390)

- config/common_test.go
- config/environment.go
Cherry picking https://github.com/mattermost/mattermost-server/pull/22426 to `cloud` branch.
```release-note
NONE
```
> Cherry-pick of MM-51054 to `cloud`

- model/feature_flags.go
Change work template feature flag value to true.
https://mattermost.atlassian.net/browse/MM-50996
```release-note
NONE
```
> [MM-50996] Set WorkTemplate FF to true by default

- model/feature_flags.go
Manual cherry pick of MM-MM-50996 (pr https://github.com/mattermost/mattermost-server/pull/22427)
N/A
```release-note
NONE
```
> Manual cherry pick of MM-MM-50996

- api4/cloud.go
- api4/cloud_test.go
- api4/license.go
- app/email/email.go
- app/email/mocks/ServiceInterface.go
- app/email/service.go
- app/server.go
- einterfaces/cloud.go
- einterfaces/mocks/CloudInterface.go
- i18n/en.json
- model/client4.go
- model/cloud.go
Manual cherry pick of https://github.com/mattermost/mattermost-server/pull/22350
```release-note
none
```
> Manual Cherry pick MM 50534 to release 7.9

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
Reverts mattermost/mattermost-server#22213
> Revert "Revert "Revert "Set BoardsProduct FF to on by default" (#22177)""

- model/feature_flags.go
Reverts mattermost/mattermost-server#22431
> Revert "Manual cherry pick of MM-MM-50996"

- config/diff_test.go
- model/config.go
- model/config_test.go
- model/feature_flags.go
- scripts/test.sh
This reverts commit 9f7e361621304e419b23ac081f8846156debf4b3.
```release-note
NONE
```
> Revert "Revert "Revert "Set BoardsProduct FF to on by default" (#22177)" (#22213)" (#22437)

- Makefile
(cherry picked from commit 0a001b9c03a8b32e7ac6e82149aa0f9f729ff72a)
```release-note
Prepackage boards to v7.9.1
```
> update prepackage boards to 7.9.1 (#22462)

- model/config.go
Cherry pick of #22480 on cloud.
```release-note
NONE
```
> Automated cherry pick of #22480

- server/boards/app/boards.go
- server/boards/app/boards_test.go
This is essentially a cherry-pick of https://github.com/mattermost/focalboard/pull/4620
This was committed to focalboard after cutoff for mono-repo.
https://mattermost.atlassian.net/browse/MM-51062
```release-note
NONE
```
> check permissions to channel before patching via api(4620)

- app/server.go
- model/license.go
- web/context.go
- web/handlers.go
Cherry pick of #22453 on release-7.8.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #22453

- server/boards/ws/plugin_adapter.go
Fixing websockets
https://mattermost.atlassian.net/browse/MM-51466
```release-note
NONE
```
> [MM-51466] Fixing monorepo websockets for boards

- e2e/cypress/tests/integration/playbooks/channels/broadcast_spec.js
- e2e/cypress/tests/integration/playbooks/channels/rhs/checklist_spec.js
- e2e/cypress/tests/integration/playbooks/channels/rhs/status_update_spec.js
- e2e/cypress/tests/integration/playbooks/channels/slash_command/commands_spec.js
- e2e/cypress/tests/integration/playbooks/channels/slash_command/info_spec.js
- e2e/cypress/tests/integration/playbooks/channels/slash_command/owner_spec.js
- e2e/cypress/tests/integration/playbooks/channels/slash_command/test_spec.js
- e2e/cypress/tests/integration/playbooks/channels/slash_command/todo_spec.js
- e2e/cypress/tests/integration/playbooks/digest_spec.js
- e2e/cypress/tests/integration/playbooks/lhs_spec.js
- e2e/cypress/tests/integration/playbooks/playbooks/edit_spec.js
- e2e/cypress/tests/integration/playbooks/playbooks/overview_spec.js
- e2e/cypress/tests/integration/playbooks/runs/rdp_main_header_spec.js
- e2e/cypress/tests/integration/playbooks/runs/rdp_main_statusupdate_spec.js
- e2e/cypress/tests/integration/playbooks/runs/taskinbox_spec.js
- e2e/cypress/tests/support/api/playbooks.js
- e2e/cypress/tests/support/index.js
- e2e/cypress/tests/support/ui/playbooks.js
- Added workaround for `this.get('prev')` being undefined
```release-note
NONE
```
> E2E fix for mono-repo

- .github/workflows/ci.yml
- .github/workflows/test.yml
Add setup-go action
```release-note
NONE
```
> Add setup-go action

- server/boards/app/boards_test.go
https://mattermost.atlassian.net/browse/MM-51699
```release-note
NONE
```
> MM-51699: Skip flaky test

- webapp/channels/src/components/post_priority/post_priority_picker.tsx
Replaces the broken Message Priority feedback link on TE servers.
https://mattermost.atlassian.net/browse/MM-51436
```release-note
NONE
```
> MM-51436: fixes broken link

- app/server.go
Spawn a goroutine from the server layer to have better
control for compliance tests.
https://mattermost.atlassian.net/browse/MM-51504
```release-note
NONE
```
> MM-51504: Control compliance export goroutine

- .github/workflows/channels-ci.yml
Removes unhelpful test publish.
```release-note
NONE
```
> Remove unhelpful test publish.

- webapp/boards/src/components/boardsUnfurl/__snapshots__/boardsUnfurl.test.tsx.snap
- webapp/boards/src/components/boardsUnfurl/boardsUnfurl.test.tsx
- webapp/boards/src/components/boardsUnfurl/boardsUnfurl.tsx
Fixes issue where bad board link can cause issue with displaying channels.
Fixes https://mattermost.atlassian.net/browse/MM-51713
```release-note
Fixes issue with bad board link 
```
> fix issue with card id being valid block but not card

- server/channels/store/searchtest/user_layer.go
- server/channels/store/sqlstore/user_store.go
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
Allows to search by part of the first name, last name, nickname or username in admin console users section.
Fixes https://mattermost.atlassian.net/browse/MM-51197
Fixes https://mattermost.atlassian.net/browse/MM-30399
```release-note
none
```
> Allowed searching users by substring in admin console

- .github/workflows/codeql-analysis.yml
Updates the codeql workflow to scan both Golang and JavaScript after the monorepo merge
N/A
```release-note
NONE
```
>   [SEC-3469] Update codeql config for monorepo

- app/support_packet.go
- model/system.go
Cherry pick of #22441 on release-7.8.
/cc  @coltoneshaw
```release-note
NONE
```
> Automated cherry pick of #22441

- app/notify_admin.go
- jobs/notify_admin/install_plugin_scheduler.go
Cherry pick of #22568 on release-7.9.
/cc  @AGMETEOR
```release-note
NONE
```
> Automated cherry pick of #22568

- app/post_metadata.go
- app/post_metadata_test.go
Cherrypick of #22532
https://mattermost.atlassian.net/browse/MM-51060
```release-note
NONE
```
> Cherrypicking PR 22532 to v7.9

- app/post_metadata.go
- app/post_metadata_test.go
Cherrypick of #22532
https://mattermost.atlassian.net/browse/MM-51060
```release-note
NONE
```
> Cherrypicking PR 22532 to v7.8

- app/post_metadata.go
- app/post_metadata_test.go
Cherrypick of #22532
https://mattermost.atlassian.net/browse/MM-51060
```release-note
NONE
```
> Cherrypicking PR 22532 to v7.7

- app/post_metadata.go
- app/post_metadata_test.go
Cherrypick of #22532
https://mattermost.atlassian.net/browse/MM-51060
```release-note
NONE
```
> Cherrypicking PR 22532 to cloud

- app/server.go
Spawn a goroutine from the server layer to have better control for compliance tests.
https://mattermost.atlassian.net/browse/MM-51504
```release-note
NONE
```
> MM-51504: Control compliance export goroutine (#22672)

- webapp/channels/src/components/onboarding_tasklist/__snapshots__/onboarding_tasklist_completed.test.tsx.snap
- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.test.tsx
- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.tsx
- webapp/channels/src/i18n/en.json
This PR adds the no thanks button to the onboarding completed screen
https://mattermost.atlassian.net/browse/MM-49786
https://user-images.githubusercontent.com/10082627/228473643-3c6fdddf-f490-4efb-a860-9957c51e44d6.mov
```release-note
NONE
```
> MM-49786 - add no thanks button to onboarding completed screen

- api4/hosted_customer.go
cherry-pick MM-51294 return 404 if invoice could not be fetched for self-hosted
```release-note
return 404 if invoice could not be fetched for self-hosted
```
> MM-51294 return 404 if invoice could not be fetched for self-hosted

- webapp/channels/src/components/widgets/menu/menu.tsx
- webapp/channels/src/components/widgets/menu/menu_group.tsx
- webapp/channels/src/components/widgets/menu/menu_header.tsx
- webapp/channels/src/components/widgets/menu/menu_items/menu_item.tsx
- webapp/channels/src/components/widgets/menu/menu_items/submenu_item.tsx
- webapp/channels/src/components/widgets/menu/menu_wrapper.tsx
- webapp/channels/src/components/widgets/menu/menu_wrapper_animation.tsx
https://mattermost.atlassian.net/browse/MM-50384
```release-note
Marked "webapp/channels/src/components/widgets/menu" as now deprecated. 
```
> MM-50384 : Mark all other menus deprecated

- e2e-tests/playwright/support/server/default_config.ts
- model/feature_flags.go
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
- webapp/platform/types/src/config.ts
Adding feature flag `AppsSidebarCategory` that gates ALL the new functionality in epic https://mattermost.atlassian.net/browse/MM-51568
https://mattermost.atlassian.net/browse/MM-51711
```release-note
NONE
```
> MM-51711_Feature flag: APPS sidebar category

- model/feature_flags.go
- server/Makefile
- server/boards/product/boards_product.go
- server/boards/server/boards_service_util.go
- server/channels/app/product.go
- server/docker-compose.yaml
Cherry-pick https://github.com/mattermost/mattermost-server/pull/22739 into cloud branch.
https://mattermost.atlassian.net/browse/MM-51792
```release-note
NONE
```
> Cherry-pick:  MM-51792 Replace Boards feature flag with env var (#22739)

- server/channels/store/sqlstore/store.go
- server/channels/store/sqlstore/utils.go
- server/channels/store/sqlstore/utils_test.go
- server/config/database.go
- server/config/database_test.go
- server/config/utils.go
- server/config/utils_test.go
https://mattermost.atlassian.net/browse/MM-51768
```release-note
NONE
```
> MM-51768: Scrub username/password from SQL datasource

- server/channels/api4/user.go
- server/channels/api4/user_test.go
> [MM-51724]

- webapp/channels/.eslintignore
- webapp/channels/.eslintrc.json
- webapp/channels/.gobom.json
- webapp/channels/Makefile
- webapp/channels/jest.config.js
- webapp/channels/package.json
- webapp/channels/tsconfig.json
- webapp/package-lock.json
https://mattermost.atlassian.net/browse/MM-51845
```release-note
NONE
```
> MM-51845 : Remove any allusion of e2e from webapp

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_sidebar_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_1_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel_sidebar/category_sorting_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel_sidebar/custom_categories_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel_sidebar/new_channel_dropdown_spec.ts
- e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_guest_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/system_scheme_permission_part2_spec.js
- e2e-tests/cypress/tests/integration/channels/mark_as_unread/helpers.js
- e2e-tests/cypress/tests/support/ui/sidebar_left.ts
> Fixed Add Channel_test_cases

- webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
- webapp/channels/src/components/sidebar/add_channels_cta_button.test.tsx
- webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
- webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
- webapp/channels/src/components/widgets/menu/menu_items/menu_cloud_trial.test.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/layout/_sidebar-left.scss
Manual cherry pick for (#22743) - add channels lhs not working 
n/a
```release-note
NONE
```
> MM-51804 - Manual cherry pick for (#22743) - add channels lhs not working 

- Makefile
Prepackage boards 7.8.4
```release-note
Update prepackage boards  to 7.8.4
```
> Update prepackage boards to v7.8.4

- Makefile
Prepackage boards 7.9.3
```release-note
Update prepackage boards 7.9.3
```
> update prepackage boards to v7.9.3

- webapp/channels/src/components/choose_different_shipping/choose_different_shipping.scss
- webapp/channels/src/components/payment_form/mixins.scss
- webapp/channels/src/components/payment_form/payment_form.scss
Fix choose different shipping spacing
https://mattermost.atlassian.net/browse/MM-51904
```release-note
NONE
```
> MM-51904 Fix choose different shipping spacing

- webapp/channels/src/components/choose_different_shipping/choose_different_shipping.scss
- webapp/channels/src/components/payment_form/mixins.scss
- webapp/channels/src/components/payment_form/payment_form.scss
Cherry-pick of https://github.com/mattermost/mattermost-server/pull/22829
https://mattermost.atlassian.net/browse/MM-51904
```release-note
NONE
```
> cherry-pick MM-51904 to cloud

- webapp/channels/src/i18n/en.json
Manual cherry pick 22810
n/a
```release-note
NONE
```
> Manual cherry pick 22810

- server/channels/api4/user.go
- server/channels/api4/user_test.go
> [MM-51724] Cherry-pick for cloud

- api4/user.go
- api4/user_test.go
> [MM-51724] Cherry-pick for release-7.9

- api4/user.go
- api4/user_test.go
> [MM-51724] Cherry-pick for release-7.8

- api4/user.go
- api4/user_test.go
> [MM-51724] Cherry-pick for release-7.1

- config/database.go
- config/database_test.go
- config/utils.go
- config/utils_test.go
- store/sqlstore/store.go
- store/sqlstore/utils.go
- store/sqlstore/utils_test.go
https://mattermost.atlassian.net/browse/MM-51768
```release-note
NONE
```
> CP: MM-51768: Scrub username/password from SQL datasource

- api4/user.go
- api4/user_test.go
> [MM-51724] Cherry-pick for release-7.10

- server/channels/app/post.go
Cherry pick of #22424 on cloud.
/cc  @kostaspt
```release-note
NONE
```
> Automated cherry pick of #22424

- server/channels/app/oauth.go
- server/channels/app/oauth_test.go
- server/channels/app/user.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/oauth_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/OAuthStore.go
- server/channels/store/timerlayer/timerlayer.go
https://mattermost.atlassian.net/browse/MM-50733
```release-note
NONE
```
> Fixes MM-50733

- server/channels/app/oauth.go
- server/channels/app/oauth_test.go
- server/channels/app/user.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/oauth_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/OAuthStore.go
- server/channels/store/timerlayer/timerlayer.go
Cherry pick of #22784 on cloud.
/cc  @srkgupta
```release-note
NONE
```
> Automated cherry pick of #22784

- webapp/channels/src/components/post/post_component.tsx
- webapp/channels/src/components/post/post_options.tsx
- webapp/channels/src/sass/components/_post-right.scss
- webapp/channels/src/sass/components/_post.scss
- webapp/channels/src/sass/responsive/_tablet.scss
Cherry pick of #22711 on cloud.
/cc  @AshishDhama
```release-note
NONE
```
> Automated cherry pick of #22711

- webapp/channels/src/components/post/post_component.tsx
A performance improvement to not add listeners to every visible post just for the case of handling `alt` key being pressed.
https://mattermost.atlassian.net/browse/MM-50744
```release-note
NONE
```
> [MM-50744] do not add event listeners to every visible post

- .github/PULL_REQUEST_TEMPLATE.md
add screenshots section to github pr template so it is easier to add the screenshots/videos images and also serves as a reminder to people to do that before sending the PRs
n/a
```release-note
NONE
```
> add screenshots section to github pr template

- webapp/boards/src/properties/number/__snapshots__/number.test.tsx.snap
- webapp/boards/src/properties/number/number.test.tsx
- webapp/boards/src/properties/number/number.tsx
Cherry pick of #22795 into `cloud`
- https://mattermost.atlassian.net/browse/MM-51842
```release-note
Fixed issue while creating/editing cards with multiple number fields
```
> Cherry pick: MM-51842: fix value-change detection in number properties

- webapp/channels/webpack.config.js
Cherry pick of #22860 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #22860

- .github/workflows/artifacts.yml
We are defining the `workflow` directive to for `Artifacts generation and upload`/cd/Download artifacts step. To be the `workflow_id` from the calling workflow
```release-note
```
> [fix] CI Correctly identify artifact downloads, calling workflow

- e2e-tests/cypress/tests/integration/channels/channel/new_channel_with_board_spec.js
- e2e-tests/playwright/global_setup.ts
- e2e-tests/playwright/support/constant.ts
- e2e-tests/playwright/support/flag.ts
- e2e-tests/playwright/support/server/client.ts
- e2e-tests/playwright/support/server/default_config.ts
- e2e-tests/playwright/support/test_fixture.ts
- e2e-tests/playwright/test.config.ts
- e2e-tests/playwright/tests/functional/boards/board-creation-and-set-up/create_empty_board.spec.ts
- e2e-tests/playwright/tests/visual/boards/board_template.spec.ts
- e2e-tests/playwright/tests/visual/boards/view_untitled_board.spec.ts
Expect boards product by default in E2E
```release-note
NONE
```
> E2E: expect boards product by default

- webapp/channels/src/sass/layout/_sidebar-left.scss
Cherry pick of #22867 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #22867

- server/channels/api4/system.go
- server/channels/app/admin.go
- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
This PR adds the request context and logger to all public methods in app/admin.go
Fixes https://github.com/mattermost/mattermost-server/issues/21563
```release-note
NONE
```
> GH21563: Add the request context and logger to all public methods in app/admin.go

- webapp/boards/package.json
- webapp/package-lock.json
This package was added during the resolution of issues with Boards CI tests. This pull request isolates and tests the package's impact after recent npm changes. It was found that removing the stub package did not result in any issues.
https://mattermost.atlassian.net/browse/MM-52144
n/a
```release-note
NONE
```
> MM-52144 : Remove stub package "@types/react-day-picker"

- model/config.go
Fixes https://github.com/mattermost/mattermost-server/pull/22848/files
https://mattermost.atlassian.net/browse/MM-52142
Credit to @JulienTant for noticing this issue on a fresh install.
```release-note
NONE
```
> CWS URL public url fix

- app/oauth.go
- app/oauth_test.go
- db/migrations/migrations.list
- db/migrations/mysql/000105_remove_tokens.down.sql
- db/migrations/mysql/000105_remove_tokens.up.sql
- db/migrations/postgres/000105_remove_tokens.down.sql
- db/migrations/postgres/000105_remove_tokens.up.sql
- i18n/en.json
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/oauth_store.go
- store/store.go
- store/storetest/mocks/OAuthStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #22310 on release-7.9.
```release-note
NONE
```
> Automated cherry pick of #22310

- server/Makefile
```release-note
Upgrade pre-packaged Autolink plugin version to 1.4.0
```
> Bump autolink plugin version to 1.4.0

- model/version.go
Cherry pick of #22959 on cloud.
```release-note
NONE
```
> Automated cherry pick of #22959

- server/channels/api4/user.go
- server/channels/api4/user_test.go
- server/channels/app/channel.go
- server/channels/app/channel_test.go
- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.down.sql
- server/channels/db/migrations/mysql/000107_threadmemberships_cleanup.up.sql
- server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.down.sql
- server/channels/db/migrations/postgres/000107_threadmemberships_cleanup.up.sql
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/thread_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ThreadStore.go
- server/channels/store/storetest/thread_store.go
- server/channels/store/timerlayer/timerlayer.go
Cherry pick of #22559 on cloud.
/cc  @koox00
```release-note
NONE
```
> Automated cherry pick of #22559

- app/post_metadata.go
- app/post_metadata_test.go
- app/team.go
Cherry pick of #22601 on release-7.8.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #22601

- model/client4.go
- plugin/api_timer_layer_generated.go
- plugin/hooks_timer_layer_generated.go
- server/channels/api4/license.go
- server/channels/api4/license_test.go
- server/channels/einterfaces/cloud.go
- server/channels/einterfaces/mocks/CloudInterface.go
- server/i18n/en.json
Cherry-Pick PR 22917 into cloud
```release-note
Fix true-up review submissions always failing.
```
> Cherry-Pick PR 22917 into Cloud

- server/channels/app/license_test.go
- server/channels/app/platform/license_test.go
- server/channels/utils/license.go
Cherry pick of #22955 on cloud.
```release-note
NONE
```
> Automated cherry pick of #22955

- webapp/channels/src/actions/channel_actions.ts
- webapp/channels/src/components/team_controller/actions/index.ts
Reverts mattermost/mattermost-server#22984
> Revert "MM-50123 : Identify causes of removal of channel and channel members re fetching on team switch"

- webapp/channels/src/components/plugin_marketplace/marketplace_item/marketplace_item.tsx
- webapp/channels/src/components/plugin_marketplace/marketplace_modal.scss
Updates in App Marketplace modal
- Records with a 2nd line for update now fits in the row without creating sub-scroll
- Long descriptions shown with ellipsis add a tooltip with full description
- Description opacity updated
https://mattermost.atlassian.net/browse/MM-52161
```release-note
NONE
```
> MM-52161_The Marketplace modal has some display issues

- server/platform/shared/markdown/inlines.go
Use StringBuilder.
JIRA - https://mattermost.atlassian.net/browse/MM-52164
```release-note
NONE
```
> [MM-52164]

- server/channels/store/sqlstore/channel_store.go
- server/channels/store/storetest/channel_store.go
https://mattermost.atlassian.net/browse/MM-52352
```release-note
NONE
```
> MM-52352: Limit channel search results

- webapp/channels/src/components/profile_popover/profile_popover.tsx
Update the email field in profile popover to match the new design
https://mattermost.atlassian.net/browse/MM-51502
```release-note
NONE
```
> [MM-51502] - Update email field position in profile popover

- server/channels/app/worktemplates/generator/worktemplate.tmpl
- server/channels/app/worktemplates/templates.yaml
- server/channels/app/worktemplates/types.go
- server/channels/app/worktemplates/worktemplate_generated.go
- server/model/worktemplate.go
- webapp/channels/src/components/work_templates/components/preview.tsx
- webapp/channels/src/components/work_templates/index.tsx
- webapp/platform/types/src/work_templates.ts
Add a recommended tag to work template integration:
- Exclude them from the preview page.
- Remove those plugins from being sent for installation.
QA: everything must work as it did before
https://mattermost.atlassian.net/browse/MM-52271
```release-note
NONE
```
> [MM-52271] Add recommended tag to Work Template integrations

- server/platform/shared/markdown/inlines.go
Cherry-picked from https://github.com/mattermost/mattermost-server/pull/23021
```release-note
NONE
```
> Cherry-pick of #23021

- model/utils.go
- model/utils_test.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/sqlstore/file_info_store.go
- server/channels/store/sqlstore/post_store.go
- server/channels/store/sqlstore/utils.go
Cherry pick of #23040 on cloud-latest.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #23040

- server/channels/store/sqlstore/channel_store.go
- server/channels/store/storetest/channel_store.go
Cherry pick of #23070 on cloud-latest.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #23070

- webapp/channels/src/components/signup/signup.test.tsx
- webapp/channels/src/components/signup/signup.tsx
Newsletter opt-in should also be available for cloud workspaces
https://mattermost.atlassian.net/browse/MM-52236
```release-note
NONE
```
> [MM-52236] - Include newsletter opt-in for cloud signups

- webapp/channels/src/components/admin_console/billing/billing_summary/index.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
Manual cherry-pick of https://github.com/mattermost/mattermost-server/pull/23073
```release-note
NONE
```
> Manual Cherry pick MM-52287 to cloud latest

- model/cloud.go
- server/channels/api4/cloud.go
- webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_yearly_nudge_banner.test.tsx
- webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_yearly_nudge_banner.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/constants.tsx
- webapp/platform/types/src/cloud.ts
Manual cherry-pick of https://github.com/mattermost/mattermost-server/pull/22963
```release-note
NONE
```
> Manual Cherry pick MM-52158 to cloud latest

- server/boards/services/store/sqlstore/schema_table_migration.go
Cherry pick of #23032 on cloud-latest.
```release-note
NONE
```
> Automated cherry pick of #23032

- .github/workflows/artifacts.yml
Remove upload workflow attack vector 
https://community.mattermost.com/private-core/channels/sec-3673---command-injection-in-workflow_run-pipeline
https://mattermost.atlassian.net/browse/SEC-3673
```release-note
```
> fix: Disable branch name manipulation to remove attack vector

- webapp/channels/src/components/post/user_profile.tsx
Cherry pick of #22926 on cloud.
/cc  @AshishDhama
```release-note
NONE
```
> Automated cherry pick of #22926

- server/build/Dockerfile
Cherry pick of #23084 on cloud.
/cc  @spirosoik
```release-note
NONE
```
> Automated cherry pick of #23084

- webapp/channels/src/actions/views/create_comment.test.jsx
- webapp/channels/src/actions/views/drafts.test.ts
- webapp/channels/src/actions/views/drafts.ts
- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.jsx
- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_comment/index.ts
- webapp/channels/src/components/advanced_create_post/advanced_create_post.test.jsx
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
- webapp/channels/src/components/advanced_create_post/index.ts
- webapp/channels/src/components/drafts/__snapshots__/draft_row.test.tsx.snap
- webapp/channels/src/components/drafts/__snapshots__/drafts.test.tsx.snap
- webapp/channels/src/components/drafts/channel_draft/__snapshots__/channel_draft.test.tsx.snap
- webapp/channels/src/components/drafts/channel_draft/channel_draft.test.tsx
- webapp/channels/src/components/drafts/channel_draft/channel_draft.tsx
- webapp/channels/src/components/drafts/draft_row.test.tsx
- webapp/channels/src/components/drafts/draft_row.tsx
- webapp/channels/src/components/drafts/drafts.test.tsx
- webapp/channels/src/components/drafts/drafts.tsx
- webapp/channels/src/components/drafts/index.ts
- webapp/channels/src/components/drafts/thread_draft/__snapshots__/thread_draft.test.tsx.snap
- webapp/channels/src/components/drafts/thread_draft/thread_draft.test.tsx
- webapp/channels/src/components/drafts/thread_draft/thread_draft.tsx
- webapp/channels/src/reducers/storage.ts
- webapp/channels/src/reducers/views/drafts.ts
- webapp/channels/src/reducers/views/index.ts
- webapp/channels/src/types/store/draft.ts
- webapp/channels/src/types/store/views.ts
- webapp/channels/src/utils/constants.tsx
Cherry pick of #22820 on cloud.
/cc  @kostaspt
```release-note
NONE
```
> Automated cherry pick of #22820

- .github/workflows/artifacts.yml
Fixing the event that CI for Sentry should run for. 
Ticket: https://mattermost.atlassian.net/browse/CLD-5592
```release-note
```
> [fix] CI Sentry. running on push events

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_post_spec.js
- webapp/channels/src/components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
- webapp/channels/src/components/dot_menu/dot_menu.tsx
- webapp/channels/src/i18n/en.json
- Fixed dot menu accessibility
https://mattermost.atlassian.net/browse/MM-52447
```release-note
NONE
```
> MM-52447 Fixed dot menu accessibility

- webapp/channels/src/components/preparing_workspace/organization.tsx
- webapp/channels/src/components/preparing_workspace/plugins.tsx
- webapp/channels/src/components/preparing_workspace/preparing_workspace.tsx
Manual cherry-pick of (#23051)
n/a
n/a
```release-note
n/a
```
> Manual cherry-pick of (#23051)

- model/hosted_customer.go
- server/channels/api4/hosted_customer.go
- server/channels/einterfaces/cloud.go
- server/channels/einterfaces/mocks/CloudInterface.go
Manually cherry-pick [22657](https://github.com/mattermost/mattermost-server/pull/22657) into `cloud`
```release-note
NONE
```
> Manually cherry-pick 22657 into cloud

- webapp/channels/src/actions/global_actions.tsx
- webapp/channels/src/components/do_verify_email/do_verify_email.tsx
- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/index.ts
- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.test.tsx
- webapp/channels/src/components/login/login.tsx
- webapp/channels/src/components/preparing_workspace/preparing_workspace.tsx
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/root/root_redirect/index.ts
- webapp/channels/src/components/signup/signup.tsx
- webapp/channels/src/components/terms_of_service/index.ts
- webapp/channels/src/components/terms_of_service/terms_of_service.test.tsx
- webapp/channels/src/components/terms_of_service/terms_of_service.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
Cherry pick of #23090 on cloud.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #23090

- server/Makefile
Cherry pick of #22619 on cloud.
```release-note
NONE
```
> Automated cherry pick of #22619

- model/permission.go
- server/channels/api4/command.go
- server/channels/api4/command_test.go
- https://github.com/mattermost/mattermost-server/pull/22468
```release-note
NONE
```
> Cherrypick to Cloud "Update slash command permission (#22468)"

- e2e-tests/cypress/tests/integration/channels/insights/insights_spec.ts
- server/playbooks/server/api/playbooks.go
- webapp/channels/src/components/activity_and_insights/insights/insights.tsx
https://github.com/mattermost/mattermost-server/pull/23076
```release-note
Cherry pick of top playbooks fix
```
> [MM-52339] Top playbooks cherry-pick

- webapp/channels/src/components/invitation_modal/invitation_modal.tsx
- webapp/channels/src/components/invitation_modal/invite_view.tsx
this PR fixes an error that happens while removing all channels in guest invite form
https://mattermost.atlassian.net/browse/MM-52499
Before:
https://user-images.githubusercontent.com/10082627/234790052-6dae2825-c958-45fe-97bb-7d838bd39ca8.mov
After:
https://user-images.githubusercontent.com/10082627/234789869-b34f86cf-41f5-46c8-a5b2-3637e6b608dc.mov
```release-note
NONE
```
> MM-52499 - fix error while removing all channels in guest invite form

- webapp/channels/src/components/app_bar/app_bar.scss
Cherry pick of #23112 on cloud.
/cc  @julmondragon
```release-note
NONE
```
> Automated cherry pick of #23112

- app/post.go
Cherry pick of #22424 on release-7.1.
```release-note
NONE
```
> Cherry pick of #22424

- .github/workflows/artifacts.yml
We are disabling uploading e2e artifacts to mattermost dockerhub repository. This was temporary, to help with the migration to the new repo, of all sourounding services.
Ticket: https://mattermost.atlassian.net/browse/CLD-5614
```release-note
NONE
```
> [chore] CI. Disabling artifacts upload to mattermost dockerhub

- webapp/channels/src/components/external_link/external_link.test.tsx
- webapp/channels/src/components/external_link/index.tsx
- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_completed.tsx
- webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
Cherry pick of #23048 on release-7.11.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #23048

- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000108_remove_orphaned_oauth_preferences.down.sql
- server/channels/db/migrations/mysql/000108_remove_orphaned_oauth_preferences.up.sql
- server/channels/db/migrations/postgres/000105_remove_tokens.up.sql
- server/channels/db/migrations/postgres/000108_remove_orphaned_oauth_preferences.down.sql
- server/channels/db/migrations/postgres/000108_remove_orphaned_oauth_preferences.up.sql
Cherry pick of #23036 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #23036

- webapp/boards/package.json
- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
- webapp/playbooks/package.json
Cherry pick of #23230 on release-7.11.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23230

- api4/team.go
- api4/team_test.go
Cherry pick of #22531 on release-7.8
```release-note
NONE
```
> Cherry pick of #22531 on release-7.8

- api4/team.go
- api4/team_test.go
Cherry pick of #22531 on release-7.1
```release-note
NONE
```
> Cherry pick of #22531 on release-7.1

- shared/markdown/inlines.go
Cherry pick of #23021 on release-7.9.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #23021

- server/build/release.mk
Cherry pick of #23290 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #23290

- server/build/Dockerfile
Cherry pick of #22987 on release-7.11.
/cc  @DSchalla
```release-note
NONE
```
> Automated cherry pick of #22987

- model/utils.go
- model/utils_test.go
- store/sqlstore/channel_store.go
- store/sqlstore/file_info_store.go
- store/sqlstore/post_store.go
- store/sqlstore/utils.go
https://mattermost.atlassian.net/browse/MM-52216
```release-note
NONE
```
> MM-52216: Trim errors (#23040)

- app/oauth.go
- app/oauth_test.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/oauth_store.go
- store/store.go
- store/storetest/mocks/OAuthStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #22784 on release-7.9.
/cc  @amyblais 
```release-note
NONE
```
> Manual cherry pick of #22784 into 7.9

- app/oauth.go
- app/oauth_test.go
- app/user.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/oauth_store.go
- store/store.go
- store/storetest/mocks/OAuthStore.go
- store/timerlayer/timerlayer.go
Cherry pick of #22784 on release-7.1.
/cc  @amyblais 
```release-note
NONE
```
> Manual cherry pick of #22784 into 7.1

- server/channels/imports/boards_imports.go
- server/channels/imports/playbooks_imports.go
They aren't necessary after the monorepo
```release-note
NONE
```
> Remove unnecessary blank imports

- e2e-tests/playwright/support/server/channel.ts
- e2e-tests/playwright/support/test_fixture.ts
- e2e-tests/playwright/support/ui/components/channels/find_channels_modal.ts
- e2e-tests/playwright/support/ui/components/channels/header_mobile.ts
- e2e-tests/playwright/support/ui/components/channels/sidebar_left.ts
- e2e-tests/playwright/support/ui/components/index.ts
- e2e-tests/playwright/support/ui/pages/channels.ts
- e2e-tests/playwright/tests/functional/channels/search/find_channels.spec.ts
- e2e-tests/playwright/tests/visual/channels/intro_channel.spec.ts
- webapp/channels/src/components/quick_switch_modal/__snapshots__/quick_switch_modal.test.tsx.snap
- webapp/channels/src/components/quick_switch_modal/quick_switch_modal.tsx
- Automated  test for [MM-T5424](https://github.com/mattermost/mattermost-test-management/blob/f04ab54c4a2f2d888fe490d29b936d263cd0e80f/data/test-cases/channels/search/MM-T5424.md)
- Added components: `FindChannelsModal`, `ChannelsHeaderMobile`, `ChannelsSidebarLeft`
- Fixed aria-label of "Find Channels" modal
none
```release-note
NONE
```
> E2E/Playwright: MM-T5424 Find channel limit to 50 results

- e2e-tests/cypress/tests/integration/channels/bot_accounts/tags_spec.js
- e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/edit_incoming_webhook_spec.js
- e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_shift_slash/react_to_center_spec.js
Fixes few E2E Integration tests 
https://mattermost.atlassian.net/browse/MM-52519
https://mattermost.atlassian.net/browse/MM-52520
https://mattermost.atlassian.net/browse/MM-52498
```
NONE
```
> MM-52428: Fix few E2E integration tests 

- webapp/channels/src/actions/views/posts.js
Fix import issue in forward post action
Fixes https://mattermost.atlassian.net/browse/MM-52283
https://user-images.githubusercontent.com/16203333/236754742-54423e82-4efc-43a1-ba87-43f847d5ac3c.mov
```release-note
- Fix import issue in forward post action
```
> [WebApp][MM-52283] : Fix import issue in forward post action

- webapp/channels/src/actions/views/posts.js
Fix import issue with forward post action
Cherry-pick https://github.com/mattermost/mattermost-server/pull/23329
Fixes https://mattermost.atlassian.net/browse/MM-52283
NA
```release-note
NONE
```
> [MM-52283]: Fix import issue with forward post action

- model/feature_flags.go
Cherry pick of #23367 on release-7.11.
```release-note
NONE
```
> Automated cherry pick of #23367

- webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
- webapp/channels/src/components/sidebar/add_channels_cta_button.tsx
- webapp/channels/src/sass/layout/_sidebar-left.scss
https://mattermost.atlassian.net/browse/MM-52613
Release note:
```release-note
NONE
```
> MM-52613: Add icons to "Add channels" LHS menu

- server/channels/app/notify_admin_test.go
https://mattermost.atlassian.net/browse/MM-52743
```release-note
NONE
```
> MM-52743: Skip racy test Test_SendNotifyAdminPosts

- server/boards/services/store/sqlstore/schema_table_migration.go
Spotted it while upgrading my server and checking the logs
```release-note
```
> Small grammar change

- scripts/download_mmctl_release.sh
Cherry pick of #23441 on release-7.10.
/cc  @phoinixgrr
```release-note
NONE
```
> Automated cherry pick of #23441

- webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
Cherry pick of #23219 on cloud.
/cc  @LeonardJouve
```release-note
NONE
```
> Automated cherry pick of #23219

- webapp/boards/package.json
- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/components/package.json
- webapp/platform/types/package.json
- webapp/playbooks/package.json
Cherry pick of #23442 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23442

- server/channels/einterfaces/mocks/ElasticsearchFixChannelIndexInterface.go
Fix an incorrect import in cloud branch.
```release-note
NONE
```
> Fix import

- server/Makefile
https://github.com/mattermost/mattermost-plugin-welcomebot/pull/105
```release-note
Include prepackaged Welcomebot plugin v1.3.0
```
> Bump welcomebot plugin version to 1.3.0

- server/scripts/download_mmctl_release.sh
Fix missing logic from https://github.com/mattermost/mattermost-server/commit/42f472f34b27f3dd0fb7df266fef903673331175 commit 
The logic behind this change 👇🏼 
> If `release-X.Y` pattern exist in branch name then we download the related binary. If not fallback to master. 
https://mattermost.atlassian.net/browse/CLD-5682
```release-note
```
> fix: Fix download mmctl script and point it to proper release branch

- api4/team.go
- api4/team_test.go
Manual cherrypick of #22531
```release-note
NONE
```
> Manual Cherrypick of #22531

- server/channels/app/server.go
- server/channels/app/server_test.go
https://mattermost.atlassian.net/browse/MM-52898
```release-note
NONE
```
> MM-52898: WS fix

- .github/workflows/server-ci-pr.yml
https://mattermost.atlassian.net/browse/MM-52441
```release-note
NONE
```
> MM-52441: Apply path filtering to selectively run workflows

- server/boards/services/store/sqlstore/migrations/README.md
Fix `baord` typo in [server/boards/services/store/sqlstore/migrations/README.md](https://github.com/mattermost/mattermost-server/blob/0cb3a406da7a339cc47bb72e32106b24e13c2a9a/server/boards/services/store/sqlstore/migrations/README.md?plain=1#L10)
```release-note
NONE
```
> Fix typo in sqlstore migrations guide.

- webapp/platform/types/src/apps.ts
When this property is enabled, include the user-level access token.
Docs is [here](https://developers.mattermost.com/integrate/apps/structure/call-metadata/).
Nothing.
Nothing.
Nothing.
```release-note
```
> webapp/platform/types : Add 'acting_user_access_token' type to AppExpand

- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.jsx
- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/components/file_upload/file_upload.test.tsx
- webapp/channels/src/components/file_upload/file_upload.tsx
- webapp/channels/src/components/message_submit_error.tsx
Cherry pick of #23502 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23502

- webapp/channels/src/components/admin_console/set_by_env.tsx
In this PR, completes migration of `components/admin_console/set_by_env.jsx` to TypeScript.
Fixes [GitHub issue #23419](https://github.com/mattermost/mattermost-server/issues/23419)
https://mattermost.atlassian.net/browse/MM-52841
```release-note
NONE
```
> [GH-23419] Migrate "components/admin_console/set_by_env.jsx" to Typescript

- server/channels/store/sqlstore/post_store.go
- server/public/shared/markdown/inspect.go
- server/public/shared/markdown/inspect_test.go
Cherry pick of #23519 on cloud.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #23519

- .github/workflows/server-ci-template.yml
- server/.golangci.yml
- server/Makefile
This time we are just using the Makefile command
to see if that makes a difference
```release-note
NONE
```
> Enable golangci-lint (attempt 2)

- app/platform/config.go
- app/platform/config_test.go
- app/platform/service.go
Cherry pick of #23545 on release-7.8.
```release-note
NONE
```
> Manual cherry pick  of #23545

- server/channels/app/platform/config.go
Debug log
```release-note
NONE
```
> Adding debug log when executing query

- .github/workflows/server-ci-template.yml
- .github/workflows/server-test-template.yml
Some renaming after the project rename
[MM-52996](https://mattermost.atlassian.net/browse/MM-52996)
```release-note
NONE
```
[MM-52996]: https://mattermost.atlassian.net/browse/MM-52996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-52996] fix server ci after renaming the project

- webapp/README.md
- webapp/platform/client/README.md
- webapp/platform/components/README.md
- webapp/platform/types/README.md
webapp/packages does not exist.
Nothing.
Nothing.
Nothing.
```release-note
```
> Fix references from 'packages/*' to 'platform/*' in READMEs

- Makefile
Update prepackage boards to v7.8.5
```release-note
Update prepackage boards to v7.8.5
```
> Update prepackage boards to v7.8.5

- .github/workflows/server-ci-template.yml
- .github/workflows/server-test-template.yml
Cherry pick of #23576 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23576

- .github/PULL_REQUEST_TEMPLATE.md
Including Jira tickets helps us track contributions in Jira. As Jira tickets for contributors are not part of the sprint and require manual movement, linking them here will display the status of the pull request in Jira.
n/a
n/a
```release-note
NONE
```
> Update PULL_REQUEST_TEMPLATE.md to include Jira ticket for contributors

- server/channels/store/sqlstore/post_store.go
- server/channels/store/storetest/post_store.go
- webapp/channels/src/components/forward_post_modal/forward_post_modal.tsx
- webapp/channels/src/components/post_view/post_body_additional_content/post_body_additional_content.tsx
- webapp/channels/src/components/post_view/post_message_preview/__snapshots__/post_message_preview.test.tsx.snap
- webapp/channels/src/components/post_view/post_message_preview/index.ts
- webapp/channels/src/components/post_view/post_message_preview/post_message_preview.test.tsx
- webapp/channels/src/components/post_view/post_message_preview/post_message_preview.tsx
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Cherry pick of #23226 on cloud.
/cc  @kostaspt
```release-note
NONE
```
> Automated cherry pick of #23226

- server/public/model/config.go
Cherry pick of #23578 on cloud.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #23578

- webapp/channels/src/components/post/post_component.tsx
Cherry pick of #23068 on cloud.
/cc  @sinansonmez
```release-note
NONE
```
> Automated cherry pick of #23068

- server/playbooks/server/api/graphql_root_playbook.go
- server/playbooks/server/api/playbooks.go
- server/playbooks/server/api_graphql_playbooks_test.go
- server/playbooks/server/api_playbooks_test.go
- server/playbooks/server/app/permissions_service.go
- server/playbooks/server/main_test.go
Cherry pick of #23279 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23279

- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
This PR hides the `Menu.ItemExternalLink` component for `Help Resources` when there is no link.
Fixes https://github.com/mattermost/mattermost/issues/23297
Jira https://mattermost.atlassian.net/browse/MM-44165
[before_help_link.webm](https://github.com/mattermost/mattermost/assets/20505926/8b0e78da-a1d5-4a6b-a812-eabdcf13359a)
[after_help_link.webm](https://github.com/mattermost/mattermost/assets/20505926/8bcc5cf3-247e-406a-9290-f24a6b52ad45)
```release-note
NONE
```
> [MM-44165] : When Help link is left blank Help Resources option remains available in the help menu

- app/app_iface.go
- app/opentracing/opentracing_layer.go
- app/user.go
- app/user_test.go
- i18n/en.json
* remove recovery tokens when creating a new one
* add app layers, unit test, i18 extract
* lint fixes
* fix unit test
(cherry picked from commit 355bc6502c56a56c35afcded467771a4619f33a0)
```release-note
remove recovery token when creating a new one
```
> MM-52477 - remove recovery tokens when creating a new one (#23171)

- Makefile
Update prepackaged board to v7.9.4 
```release-note
Update prepackaged board to v7.9.4 
```
> Update Prepackage boards  to 7.9.4

- webapp/channels/src/components/admin_console/multiselect_settings.tsx
- webapp/channels/src/components/admin_console/schema_admin_settings.jsx
…in file that import it
migrated components/admin_console/multiselect_settings.jsx to Typescript :
- Rename the files from jsx to tsx TypeScript extensions,  update the schema_admin_setting.jsx with the correct import. Did not see any associated test with this file. 
fixes https://github.com/mattermost/mattermost-server/issues/23427
https://mattermost.atlassian.net/browse/MM-52833
```
> MM-52833 : Migrate "components/admin_console/multiselect_settings.jsx" and tests to Typescript

- webapp/channels/src/components/admin_console/__snapshots__/bleve_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/bleve_settings.jsx
- webapp/channels/src/components/admin_console/cluster_settings.jsx
- webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
- webapp/channels/src/components/admin_console/database_settings.jsx
- webapp/channels/src/components/admin_console/elasticsearch_settings.jsx
- webapp/channels/src/components/admin_console/message_export_settings.jsx
- webapp/channels/src/components/admin_console/password_settings.jsx
- webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
- webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
- webapp/channels/src/components/admin_console/push_settings.jsx
- webapp/channels/src/components/admin_console/schema_admin_settings.jsx
- webapp/channels/src/components/admin_console/session_length_settings.jsx
- webapp/channels/src/components/admin_console/settings_group.tsx
In this PR, completes migration of `components/admin_console/settings_group.jsx` to TypeScript.
Fixes [GitHub issue #23425](https://github.com/mattermost/mattermost-server/issues/23425)
https://mattermost.atlassian.net/browse/MM-52835
```release-note
NONE
```
> [MM-52835] : Migrate "components/admin_console/settings_group.jsx" and tests to Typescript

- shared/markdown/inspect.go
Cherry pick of #23197 on release-7.9.
/cc  @vish9812
```release-note
NONE
```
> Automated cherry pick of #23197

- app/server.go
- app/server_test.go
https://mattermost.atlassian.net/browse/MM-52898
```release-note
NONE
```
> MM-52898: WS fix (#23489)

- e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/open_thread_dm_spec.js
- webapp/channels/src/components/post/post_component.tsx
Cherry pick of #23579 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23579

- shared/markdown/inspect.go
Cherry pick of #23197 on release-7.10.
```release-note
NONE
```
> Manual cherry pick of [MM-52527] (#23197)

- shared/markdown/inspect.go
- shared/markdown/inspect_test.go
- store/sqlstore/post_store.go
Cherry pick of https://github.com/mattermost/mattermost/pull/23519 on release-7.10.
```release-note
NONE
```
> Manual cherry pick of [MM-52527] (#23519)

- .github/workflows/server-ci-template.yml
https://mattermost.atlassian.net/browse/MM-53090
```release-note
NONE
```
> MM-53090: Do not run PG binary tests on master

- webapp/channels/src/components/post/post_component.tsx
Cherry pick of #23649 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23649

- Makefile
Prepackage boards to v7.10.3
```release-note
Prepackage boards to v7.10.3
```
> Prepackage boards to v7.10.3

- Makefile
Update Prepackage boards to v7.9.5
```release-note
Update Prepackage boards to v7.9.5
```
> Update Prepackage boards to v7.9.5

- Makefile
Update Prepackage boards v7.8.6
```release-note
Update Prepackage boards v7.8.6
```
> Update Prepackage boards v7.8.6

- e2e-tests/cypress/tests/integration/channels/archived_channel/archive_channel_reaction_spec.ts
- e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_1_spec.ts
- e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_2_spec.ts
- e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_4_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel/new_channel_with_board_spec.js
- e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_1_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/auth_sso/authentication_spec.js
- e2e-tests/cypress/tests/support/api/preference.js
- e2e-tests/cypress/tests/support/api/setup.ts
- e2e-tests/cypress/tests/support/api/user.d.ts
- e2e-tests/cypress/tests/support/api/user.js
- e2e-tests/cypress/tests/support/ui/channel.d.ts
- e2e-tests/cypress/tests/support/ui/channel.js
Fixed known failed E2E tests
To follow
```release-note
NONE
```
> Cypress/E2E: Fixed known failed E2E tests

- Makefile
Prepackage board v7.8.7
```release-note
Prepackage board v7.8.7
```
> Prepackage board v7.8.7

- Makefile
Prepackage board v7.9.6
```release-note
Prepackage board v7.9.6
```
> Prepackage board v7.9.6

- Makefile
Prepackage board v7.10.4
```release-note
Prepackage board v7.10.4
```
> Prepackage board v7.10.4

- webapp/channels/src/components/post/post_component.test.tsx
- webapp/channels/src/components/post/post_component.tsx
These are some tests I wrote for the fixes made in #23579 before I realized that bug had already been fixed
```release-note
NONE
```
> Add PostComponent tests involving thread footer

- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/compliance_export_multiple_post_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/compliance_export_ui_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/s3_bucket_storage_spec.js
- e2e-tests/cypress/tests/support/ui/compliance_export.js
Fix e2e about compliance test
```release-note
NONE
```
> Cypress/E2E: Fix e2e about compliance test

- server/channels/app/platform/service.go
- server/channels/app/platform/service_test.go
- server/platform/services/telemetry/telemetry.go
Cherry pick of #23773 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23773

- .github/workflows/esrupgrade.yml
Speaking of what to do with flaky tests, let's skip this for now in master until I fix it. Created
--
--
```release-note
NONE
```
> Skip ESR CI in master

- server/public/model/version.go
Cherry pick of #23811 on cloud.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #23811

- webapp/channels/src/sass/routes/_admin-console.scss
MM-51984 - Fixing footer bar in system console
https://mattermost.atlassian.net/browse/MM-51984
<!--
Add a release note for each of the following conditions:
* Config changes (additions, deletions, updates).
* API additions—new endpoint, new response fields, or newly accepted request parameters.
* Database changes (any).
* Schema migration changes. Use the [Schema Migration Template](https://docs.google.com/document/d/18lD7N32oyMtYjFrJKwsNv8yn6Fe5QtF-eMm8nn0O8tk/edit?usp=sharing) as a starting point to capture these details as release notes. 
* Websocket additions or changes.
* Anything noteworthy to a Mattermost instance administrator (err on the side of over-communicating).
* New features and improvements, including behavioral changes, UI changes, and CLI changes.
* Bug fixes and fixes …
> MM-51984 - Fixing footer bar in system console

- webapp/channels/src/sass/routes/_admin-console.scss
Cherry pick of #23730 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23730

- server/channels/api4/user.go
- server/channels/api4/user_test.go
Cherry pick of #23750 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #23750

- webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
- webapp/channels/src/components/channel_move_to_sub_menu_old/index.tsx
- webapp/channels/src/components/delete_category_modal/delete_category_modal.tsx
- webapp/channels/src/components/delete_post_modal/__snapshots__/delete_post_modal.test.tsx.snap
- webapp/channels/src/components/delete_post_modal/delete_post_modal.tsx
- webapp/channels/src/components/dot_menu/__snapshots__/dot_menu.test.tsx.snap
- webapp/channels/src/components/dot_menu/dot_menu.test.tsx
- webapp/channels/src/components/dot_menu/dot_menu.tsx
- webapp/channels/src/components/dot_menu/index.ts
- webapp/channels/src/components/dot_menu/post_reminder_submenu.tsx
- webapp/channels/src/components/edit_category_modal/edit_category_modal.tsx
- webapp/channels/src/components/menu/menu.tsx
- webapp/channels/src/components/menu/menu_context.ts
- webapp/channels/src/components/menu/menu_item.tsx
- webapp/channels/src/components/menu/menu_item_separator.tsx
- webapp/channels/src/components/menu/sub_menu.tsx
- webapp/channels/src/components/more_direct_channels/__snapshots__/more_direct_channels.test.tsx.snap
- webapp/channels/src/components/more_direct_channels/more_direct_channels.tsx
- webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
- webapp/channels/src/components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx
- webapp/channels/src/components/sidebar/sidebar.tsx
- webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_menu/sidebar_category_menu.tsx
- webapp/channels/src/components/sidebar/sidebar_category/sidebar_category_sorting_menu/sidebar_category_sorting_menu.tsx
- webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_menu/sidebar_channel_menu.tsx
- webapp/platform/components/src/generic_modal/generic_modal.tsx
Cherry pick of #23749 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23749

- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.test.jsx
- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_comment/index.ts
- webapp/channels/src/components/advanced_create_post/advanced_create_post.test.jsx
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
- webapp/channels/src/components/edit_post/edit_post.tsx
- webapp/channels/src/components/file_upload/file_upload.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/create_comment.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
- webapp/channels/src/tests/setup.js
- webapp/channels/src/utils/exec_commands.ts
- webapp/channels/src/utils/paste.test.tsx
- webapp/channels/src/utils/paste.tsx
- webapp/channels/src/utils/turndown.ts
Cherry pick of #23535 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23535

- webapp/channels/babel.config.js
- webapp/channels/src/components/create_team/__snapshots__/create_team.test.tsx.snap
- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap
Cherry pick of #23817 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23817

- webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.test.tsx
- webapp/channels/src/components/user_settings/notifications/desktop_notification_setting/desktop_notification_settings.tsx
- webapp/channels/src/components/user_settings/notifications/index.ts
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.test.tsx
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
- webapp/channels/src/selectors/calls.ts
Cherry pick of #23810 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #23810

- webapp/channels/src/utils/notification_sounds.ts
Cherry pick of #23775 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #23775

- server/channels/app/platform/searchengine.go
- server/platform/services/searchengine/bleveengine/bleve.go
- server/platform/services/searchengine/interface.go
- server/platform/services/searchengine/mocks/SearchEngineInterface.go
Cherry pick of #23806 on cloud.
/cc  @fmartingr
```release-note
NONE
```
> Automated cherry pick of #23806

- webapp/channels/src/actions/notification_actions.jsx
- webapp/channels/src/plugins/export.js
Cherry pick of #23779 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #23779

- webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap
- webapp/channels/src/components/advanced_create_comment/__snapshots__/advanced_create_comment.test.jsx.snap
- webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx
- webapp/channels/src/components/advanced_create_post/__snapshots__/advanced_create_post.test.jsx.snap
- webapp/channels/src/components/advanced_create_post/advanced_create_post.test.jsx
- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/components/edit_post/edit_post.tsx
- webapp/channels/src/components/forward_post_modal/forward_post_comment_input.tsx
- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
- webapp/channels/src/components/textbox.test.tsx
- webapp/channels/src/components/textbox/textbox.tsx
- webapp/channels/src/utils/utils.test.tsx
- webapp/channels/src/utils/utils.tsx
Cherry pick of #23823 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23823

- webapp/channels/src/utils/markdown/apply_markdown.ts
- webapp/channels/src/utils/paste.test.tsx
- webapp/channels/src/utils/paste.tsx
Cherry pick of #23784 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23784

- webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx
Small typo in AdvancedCreatePost. The draft is updated with the wrong key for the message (`newMessage` instead of `message`) :)
```release-note
none
```
> Fix typo in AdvancedCreatePost as it was updating draft with incorrect key for message

- server/public/model/feature_flags.go
- webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.test.tsx
- webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts
- webapp/platform/types/src/config.ts
This PR removes the code used for run the AB test for the reduced onboarding task list item added by https://github.com/mattermost/mattermost-webapp/pull/11526
https://mattermost.atlassian.net/browse/MM-53087
n/a
```release-note
NONE
```
> MM-53087 - remove AB test for reduced onboarding task list item

- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
- webapp/channels/src/utils/notification_sounds.ts
- Default should be `Calm`, not `Dynamic`
- https://mattermost.atlassian.net/browse/MM-53363
```release-note
NONE
```
> MM-53363 - Calls default sound should be Calm

- server/Makefile
Prepackage boards v7.11.0
https://mattermost.atlassian.net/browse/MM-53317
```release-note
Prepackage boards v7.11.0
```
> Prepackage boards v7.11.0

- server/Makefile
Cherry pick of #23844 on release-8.0.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #23844

- app/post_metadata_test.go
- model/post.go
- model/post_embed.go
- model/post_metadata.go
Cherry-pick #23745: Sanitize post for audit with preview links
https://mattermost.atlassian.net/browse/MM-53158
```release-note
Fixed issue where posts were not fully sanitized for audit output when a link preview was included.
```
> Cherry-pick #23745: Sanitize post for audit with preview links

- app/post_metadata_test.go
- model/post.go
- model/post_embed.go
- model/post_metadata.go
Cherry-pick #23745: Sanitize post for audit with preview links (#23745)
https://mattermost.atlassian.net/browse/MM-53158
```release-note
Fixed issue where posts were not fully sanitized for audit output when a link preview was included.
```
> Cherry-pick #23745: Sanitize post for audit with preview links 

- app/post_metadata_test.go
- model/post.go
- model/post_embed.go
- model/post_metadata.go
Cherry-pick #23745: Sanitize post for audit with preview links (#23745)
https://mattermost.atlassian.net/browse/MM-53158
```release-note
Fixed issue where posts were not fully sanitized for audit output when a link preview was included.
```
> Cherry-pick #23745: Sanitize post for audit with preview links (#23745)

- NOTICE.txt
Cherry pick of #23857 on release-8.0.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #23857

- server/public/model/post_metadata.go
Cherry pick of #23904 on cloud.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #23904

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherrypick of https://github.com/mattermost/mattermost/pull/23226 for 7.8
Webapp PR - https://github.com/mattermost/mattermost-webapp/pull/12405
https://mattermost.atlassian.net/browse/MM-52541
```release-note
NONE
```
> Cherrypick 23226 for v7.8

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherrypick of https://github.com/mattermost/mattermost/pull/23226 for 7.9
Webapp PR - https://github.com/mattermost/mattermost-webapp/pull/12406
https://mattermost.atlassian.net/browse/MM-52541
```release-note
NONE
```
> Cherrypick 23226 for v7.9

- store/sqlstore/post_store.go
- store/storetest/post_store.go
Cherrypick of https://github.com/mattermost/mattermost/pull/23226 for 7.8
Webapp PR - https://github.com/mattermost/mattermost-webapp/pull/12407
https://mattermost.atlassian.net/browse/MM-52541
```release-note
NONE
```
> Cherrypick 23226 for v7.10

- server/channels/api4/drafts_test.go
https://mattermost.atlassian.net/browse/MM-53452
```release-note
NONE
```
> MM-53452: Skipping some flaky tests

- e2e-tests/playwright/support/server/default_config.ts
- server/config/client.go
- server/platform/services/telemetry/telemetry.go
- server/public/model/config.go
- webapp/channels/src/components/admin_console/admin_definition.jsx
- webapp/channels/src/components/channel_header/channel_header.test.tsx
- webapp/channels/src/components/channel_header/channel_header.tsx
- webapp/channels/src/components/channel_header/index.ts
- webapp/channels/src/components/post_markdown/index.ts
- webapp/channels/src/components/post_markdown/post_markdown.test.tsx
- webapp/channels/src/components/post_markdown/post_markdown.tsx
- webapp/channels/src/components/post_markdown/system_message_helpers.tsx
- webapp/channels/src/components/widgets/tag/__snapshots__/guest_tag.test.tsx.snap
- webapp/channels/src/components/widgets/tag/guest_tag.test.tsx
- webapp/channels/src/components/widgets/tag/guest_tag.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/tests/react_testing_utils.tsx
- webapp/platform/types/src/config.ts
Add a setting to remove the guest badges. This includes guest badges in the system console.
Also removed the "Channel has guest" text on the channel header, and the distinction between adding/joining a channel messages between guests and not guests.
Any other text that makes references to guests are still visible in the product and the system console. For example:
- The role on the manage channel members and manage team members.
- Any error regarding guests (for example, when trying to invite a guest to the team)
https://mattermost.atlassian.net/browse/MM-53109
|----|----|
| ![Screenshot from 2023-06-22 13-13-50](https://github.com/mattermost/mattermost/assets/1933730/8ed9187b-8abb-4f4c-8371-0b18904f8c58) | ![Screenshot from 2023-06-22 …
> Remove guest badge

- server/.golangci.yml
- server/public/model/bot.go
- server/public/model/channel.go
- server/public/model/cluster_discovery.go
- server/public/model/compliance.go
- server/public/model/file_info_list.go
- server/public/model/post.go
- server/public/model/post_list.go
- server/public/model/post_search_results.go
- server/public/model/push_notification.go
- server/public/model/utils_test.go
- server/public/model/websocket_message.go
- server/public/model/websocket_message_test.go
https://mattermost.atlassian.net/browse/MM-52532
```release-note
NONE
```
> MM-52532: Fix golangci warnings for public module

- .github/workflows/artifacts.yml
- .github/workflows/server-ci-master.yml
- .github/workflows/server-ci-pr.yml
- .github/workflows/server-ci-template.yml
- .github/workflows/server-test-template.yml
- Use same conventions as master branch for CI
- Migrate to artifacts secret push
- Fix issue with docker images uploaded without proper permissions  
This will be cherry picked to release 7.8 and 7.9 
https://mattermost.atlassian.net/browse/CLD-5914
```release-note
```
> Unify release 7.10 CI / Deprecate completely CircleCI

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Cherry pick of #23908 on cloud.
```release-note
NONE
```
> Automated cherry pick of #23908

- server/channels/api4/user_test.go
- server/public/model/user.go
Cherry pick of #23914 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #23914

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Cherry pick of #23912 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23912

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
Manual cherrypick of #23908
https://mattermost.atlassian.net/browse/MM-53138
```release-note
Fixed a bug that sometimes caused delete posts to fail.
```
> Manual cherrypick of delete post fix for v8.0

- webapp/channels/src/components/suggestion/channel_mention_provider.tsx
Fixed private channel icon in channel suggestion list to use the outline one. 
https://mattermost.atlassian.net/browse/MM-50242
|----|----|
| <img width="401" alt="Screen Shot 2023-06-30 at 1 17 17 PM" src="https://github.com/mattermost/mattermost/assets/936315/ac71bf84-e8a3-411e-be3b-7f078330d447"> | <img width="381" alt="Screen Shot 2023-06-30 at 1 43 08 PM" src="https://github.com/mattermost/mattermost/assets/936315/b84f6903-45bf-42f3-9b1d-e70d5aa86399">
|
```release-note
None
```
> MM-50242 - Fix icon for private channels in channel suggestion list

- server/channels/store/sqlstore/user_store.go
Fix `userstore.AnalyticsActiveCount` calls to avoid `LEFT JOIN .. IS NULL` for MySQL
https://mattermost.atlassian.net/browse/MM-53407
```release-note
NONE
```
> [MM-53407] server/user_store: avoid antijoin for AnalyticsActiveCount query

- webapp/channels/src/components/admin_console/password_settings.tsx
Was breaking master's type check
```release-note
NONE
```
> Removed unneeded optional prop 'type' from 'admin_console/password_settings'

- server/Makefile
Cherry pick of #23991 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #23991

- server/channels/api4/user.go
- server/channels/app/login.go
- server/channels/utils/api.go
- server/channels/web/handlers.go
- server/channels/web/handlers_test.go
- server/channels/web/oauth.go
- webapp/channels/src/components/linking_landing_page/linking_landing_page.tsx
Cherry pick of #23776 on release-8.0.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #23776

- server/public/model/version.go
Cherry pick of #24016 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24016

- server/Makefile
- tools/README.md
- tools/mmgotool/commands/i18n.go
- tools/mmgotool/commands/root.go
- tools/mmgotool/go.mod
- tools/mmgotool/go.sum
- tools/mmgotool/main.go
Move `mmgotool` project into monorepo.
```release-note
NONE
```
> tools/mmgotool: move into monorepo

- webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
- webapp/channels/src/components/channel_header/channel_header.tsx
Cherry pick of #24029 on cloud.
/cc  @veronicadip
```release-note
NONE
```
> Automated cherry pick of #24029

- webapp/channels/src/components/integrations/__snapshots__/abstract_command.test.tsx.snap
- webapp/channels/src/components/integrations/abstract_command.test.tsx
- webapp/channels/src/components/integrations/abstract_command.tsx
Cherry pick of #24043 on cloud.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #24043

- server/channels/app/team.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/team_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/TeamStore.go
- server/channels/store/storetest/team_store.go
- server/channels/store/timerlayer/timerlayer.go
Cherry pick of #24027 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24027

- server/channels/app/channel.go
- server/channels/app/export.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/storetest/channel_store.go
- server/i18n/en.json
- server/public/model/channel_member.go
- server/public/model/channel_member_test.go
Cherry pick of #24031 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24031

- .gitignore
- e2e-tests/playwright/README.md
- e2e-tests/playwright/global_setup.ts
- e2e-tests/playwright/package-lock.json
- e2e-tests/playwright/package.json
- e2e-tests/playwright/support/server/init.ts
- e2e-tests/playwright/support/test_fixture.ts
- e2e-tests/playwright/support/ui/components/channels/post_dot_menu.ts
- e2e-tests/playwright/tests/accessibility/common/login.spec.ts
- e2e-tests/playwright/tests/functional/channels/drafts/drafts_on_deleted_message.spec.ts
- webapp/channels/src/components/header_footer_route/header.tsx
- webapp/channels/src/components/start_trial_form_modal/__snapshots__/start_trial_form_modal.test.tsx.snap
- webapp/channels/src/components/widgets/inputs/input/input.tsx
- webapp/channels/src/components/widgets/inputs/password_input/password_input.tsx
- webapp/channels/src/root.html
Cherry pick of #23254 on cloud.
/cc  @saturninoabril 
```release-note
NONE
```
> Manual cherry pick of #23254

- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
Cherry pick of #24058 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #24058

- webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
Cherry pick of #23618 on cloud.
/cc  @hchorfispiria
```release-note
NONE
```
> Automated cherry pick of #23618

- server/channels/testlib/store.go
- server/public/model/migration.go
Cherrypick of #24061
https://mattermost.atlassian.net/browse/MM-49257
```release-note
NONE
```
> Cherrypick of 24061 for v8.0

- model/migration.go
- testlib/store.go
Cherrypick of #24061 for 7.10
https://mattermost.atlassian.net/browse/MM-49257
```release-note
NONE
```
> Cherrypick of #24061 for 7.10

- model/migration.go
- testlib/store.go
Cherrypick of #24061 for 7.8
https://mattermost.atlassian.net/browse/MM-49257
```release-note
NONE
```
> Cherrypick of #24061 for 7.8

- server/channels/testlib/store.go
- server/public/model/migration.go
Cherry pick of #24061 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24061

- Makefile
Prepackage boards 7.10.5
```release-note
Prepackage boards 7.10.5
```
> prepackage boards v7.10.5

- Makefile
prepackage boards v7.9.7
```release-note
Prepackage boards v7.9.7
```
> prepackage boards v7.9.7

- server/Makefile
- webapp/package-lock.json
Cherry pick of #24085 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24085

- server/channels/app/authorization_test.go
- server/channels/app/notification.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub_test.go
- server/channels/app/post.go
- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- server/public/model/websocket_message.go
Reverts mattermost/mattermost#23812
> SEC 4206: Revert "MM-42810: Introduce a channel hook for a websocket event"

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
Cherry pick of #23970 on release-8.1.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #23970

- server/channels/app/migrations.go
- server/channels/jobs/jobs.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/job_store.go
- server/channels/store/store.go
- server/channels/store/storetest/job_store.go
- server/channels/store/storetest/mocks/JobStore.go
- server/channels/store/timerlayer/timerlayer.go
We missed this out last time. It's possible in an HA
scenario for a second pod to start later while the other
job is in-progress. In that case, it would schedule
two jobs.
https://mattermost.atlassian.net/browse/MM-53747
```release-note
NONE
```
> MM-53747: Do not start if job is in-progress as well.

- webapp/channels/src/components/profile_popover/profile_popover.tsx
- webapp/channels/src/i18n/en.json
Cherry pick of #24095 on release-8.1.
/cc  @sinansonmez
```release-note
NONE
```
> Automated cherry pick of #24095

- server/build/Dockerfile
Cherry pick of #23760 on release-8.1.
/cc  @3kami3
```release-note
NONE
```
> Automated cherry pick of #23760

- app/team.go
- store/opentracinglayer/opentracinglayer.go
- store/retrylayer/retrylayer.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/timerlayer/timerlayer.go
Backport of #24027 to v7.8
https://mattermost.atlassian.net/browse/MM-53192
-->
```release-note
Fix an issue where an Insights API would show data that a user may not have access to.
```
> [MM-53192] Cherry-pick of #24027

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
Cherry pick of #24143 on release-8.1.
```release-note
NONE
```
> Automated cherry pick of #24143

- app/channel.go
- app/export.go
- i18n/en.json
- model/channel_member.go
- model/channel_member_test.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Cherry pick of #24031 on release-7.8.
```release-note
NONE
```
> Cherry pick of #24031

- e2e-tests/cypress/tests/integration/channels/messaging/post_pre_header_spec.js
- webapp/channels/src/components/post/post_component.tsx
Cherry pick of #24117 on release-8.1.
```release-note
NONE
```
> Automated cherry pick of #24117

- api/v4/source/commands.yaml
- api/v4/source/files.yaml
- api/v4/source/groups.yaml
- api/v4/source/ldap.yaml
- api/v4/source/users.yaml
- server/channels/api4/group.go
Fix a handful of documentation issues with the API. We're not ready to re-enable vetting of the OpenAPI spec, but this gets us (slightly) closer.
None.
```release-note
NONE
```
> API Updates

- server/channels/app/platform/service.go
- server/platform/shared/filestore/filesstore.go
- server/platform/shared/filestore/s3store.go
Cherry pick of #24169 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24169

- server/channels/store/storetest/file_info_store.go
See https://mattermost.atlassian.net/browse/MM-53905
None.
```release-note
NONE
```
> MM-53905: Skip racy test testGetUptoNSizeFileTime

- .github/workflows/tag-public-module.yaml
- Added manual workflow to create public module tag
- Generate release notes in commit message for only changes in the `server/public` folder 
```bash
git log --oneline --graph --decorate --abbrev-commit server/public/v0.0.7...$(git rev-parse HEAD) server/public
```
* 885802eae7 (origin/master, origin/HEAD, master) Updated API Code Samples (#24141)
* aa88f8bf59 Add read_channel_content permission (#24118)
* 2a4de2eecc Revert "Add read_channel_content permission (#24018)" (#24114)
* 26617fcbdc Remove insights (#23952)
* 6d6e589c11 MM-53747: Create job to encode older image paths (#24073)
* 29bd0c9357 Revert "MM-42810: Introduce a channel hook for a websocket event (#23812)" (#24107)
> Semver bump can be `patch`,`minor`,`major` related to our codebase.
> Defaults to `patch` and can be …
> feat: Introduce workflow to tag public server module

- store/sqlstore/user_store.go
- store/storetest/user_store.go
Cherry pick of #23920 on release-7.8
related PR - https://github.com/mattermost/mattermost-webapp/pull/12416
/cc  @sbishel
```release-note
NONE
```
> Cherry pick of #23920 on release-7.8

- README.md
Change the wording from "Use cloud" to "Try cloud"
```release-note
NONE
```
> Update README.md: Try cloud instead of use

- webapp/channels/src/components/copy_text.tsx
- webapp/channels/src/components/integrations/__snapshots__/installed_command.test.tsx.snap
- webapp/channels/src/components/integrations/__snapshots__/installed_incoming_webhook.test.tsx.snap
- webapp/channels/src/components/integrations/__snapshots__/installed_outgoing_webhook.test.tsx.snap
- webapp/channels/src/components/integrations/confirm_integration/__snapshots__/confirm_integration.test.tsx.snap
- webapp/channels/src/components/integrations/installed_oauth_app/__snapshots__/installed_oauth_app.test.tsx.snap
Example for "Class to functional component" campaign. Refactors `webapp/channels/src/components/copy_text.tsx` from class component to functional component.
Details of the changes within the comments of the PR.
None
```release-note
NONE
```
> Class to functional component example 2

- server/channels/app/bot.go
This PR removes getting the bot owner because we already got it earlier.
```release-note
NONE
```
> remove redundant getUser call

- app/platform/web_conn.go
Cherry pick of #22637 on release-7.8.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #22637

- server/Makefile
Cherry pick of #24277 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24277

- server/channels/jobs/s3_path_migration/s3_path_migration.go
Cherry pick of #24286 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #24286

- server/channels/app/notification_push.go
- server/channels/app/notification_push_test.go
- server/channels/app/plugin_hooks_test.go
- server/channels/app/test_templates/hook_notification_will_be_pushed.tmpl
- server/public/model/plugin_push_notification.go
- server/public/plugin/client_rpc_generated.go
- server/public/plugin/hooks.go
- server/public/plugin/hooks_timer_layer_generated.go
- server/public/plugin/plugintest/hooks.go
- server/public/plugin/product_hooks_generated.go
Cherry pick of #24263 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #24263

- server/channels/app/notification_push.go
- server/channels/app/plugin_api.go
- server/channels/app/plugin_api_test.go
- server/public/model/plugin_push_notification.go
- server/public/plugin/api.go
- server/public/plugin/api_timer_layer_generated.go
- server/public/plugin/client_rpc_generated.go
- server/public/plugin/hooks.go
- server/public/plugin/plugintest/api.go
Cherry pick of #24273 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #24273

- server/channels/api4/post.go
Context: https://community.mattermost.com/core/pl/6q5hbw36ppytb8htzi3cr4wabr
```release-note
NONE
```
> Add missing return

- webapp/channels/src/actions/views/rhs.test.ts
- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/actions/websocket_actions.test.jsx
- webapp/channels/src/components/team_controller/actions/index.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/groups.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/groups.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/search.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
- webapp/platform/client/src/client4.ts
Cherry pick of #24292 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24292

- server/Makefile
Cherry pick of #24330 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24330

- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/channels/api4/user_test.go
Cherry pick of #24344 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24344

- webapp/channels/src/components/sidebar/sidebar.test.tsx
- webapp/channels/src/components/sidebar/unread_channels.tsx
Cherry pick of #24334 on cloud.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #24334

- server/channels/api4/bot_test.go
- server/channels/api4/user.go
- server/channels/api4/user_test.go
- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
Cherry pick of #23751 on release-8.0.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #23751

- e2e-tests/cypress/tests/integration/channels/files_and_attachments/disabled_file_upload_spec.js
- e2e-tests/cypress/tests/integration/channels/files_and_attachments/paste_image_spec.js
- webapp/channels/src/components/file_upload/file_upload.test.tsx
- webapp/channels/src/components/file_upload/file_upload.tsx
Cherry pick of #23530 on release-8.1.
/cc  @akaravashkin
```release-note
NONE
```
> Automated cherry pick of #23530

- server/public/model/version.go
Cherry pick of #24364 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24364

- api4/channel.go
- api4/file.go
- api4/integration_action.go
- api4/post.go
- api4/preference.go
- api4/reaction.go
- api4/user.go
- api4/webhook.go
- app/app_test.go
- app/authorization.go
- app/authorization_test.go
- app/permissions_migrations.go
- app/post.go
- app/webhook.go
- model/migration.go
- model/permission.go
- model/role.go
- store/sqlstore/integrity_test.go
- store/storetest/scheme_store.go
- testlib/store.go
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/24118
https://mattermost.atlassian.net/browse/MM-53203
```release-note
Added permission to read the contents of a channel
```
> Add read_channel_content permission

- server/Makefile
Cherry pick of #24336 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24336

- server/channels/app/authorization_test.go
Add a couple unit tests to show it does check the wrapped error correctly.
https://mattermost.atlassian.net/browse/MM-53098
```release-note
NONE
```
> Add additional unit test for bot/user access

- webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
- webapp/channels/src/components/post_edit_history/post_edit_history.scss
- webapp/channels/src/components/post_edit_history/post_edit_history.tsx
Cherry pick of #24396 on release-9.0.
```release-note
NONE
```
> Automated cherry pick of #24396

- server/channels/store/sqlstore/channel_store.go
https://mattermost.atlassian.net/browse/MM-53410
```release-note
NONE
```
> MM-53410: Avoid antijoin for channelstore.channelSearchQuery

- server/Makefile
- server/config/client.go
- server/config/client_test.go
- server/public/model/config.go
> Cherry pick MM-54275 to v8.1

- server/Makefile
- server/config/client.go
- server/config/client_test.go
- server/public/model/config.go
- server/public/model/emoji.go
> Cherry pick MM-54275 to v8.0

- server/Makefile
- server/config/client.go
- server/config/client_test.go
- server/public/model/config.go
> Cherry pick MM-54275 to v9.0

- server/Makefile
- server/config/client.go
- server/config/client_test.go
- server/public/model/config.go
> Cherry pick MM-54275 to Cloud

- webapp/channels/NOTICE.txt
Cherry pick of #24426 on release-9.0.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #24426

- .github/workflows/scorecards-analysis.yml
Update scorecard workflow
```release-note
NONE
```
> fix: Update scorecard workflow

- webapp/channels/src/sass/layout/_sidebar-left.scss
Cherry pick of #24440 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24440

- webapp/channels/src/actions/global_actions.tsx
- webapp/channels/src/components/channel_info_rhs/menu.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
- webapp/platform/client/src/client4.ts
Cherry pick of #23981 on release-8.1.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #23981

- server/go.mod
- server/go.sum
This CI for go mod was failing in other PR, ran it on the latest master.
none
n/a
```release-note
NONE
```
> Go Mod Tidy on v9

- server/channels/app/app_iface.go
- server/channels/app/draft.go
- server/channels/app/draft_test.go
- server/channels/app/file.go
- server/channels/app/opentracing/opentracing_layer.go
Cherry pick of #24237 on release-8.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24237

- webapp/channels/src/components/onboarding_tasks/onboarding_video_modal/onboarding_video_modal.tsx
Updates the getting started video link to a newer video that excludes boards.
https://community.mattermost.com/private-core/pl/ukbrzfwqktnyjg5w8xp8t3rc3e
Fixes https://mattermost.atlassian.net/browse/MM-54340
```release-note
NONE
```
> MM-54340 - update video link

- webapp/channels/src/components/onboarding_tasks/onboarding_video_modal/onboarding_video_modal.tsx
Cherry pick of #24433 on release-9.0.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24433

- server/channels/api4/system.go
- server/channels/api4/system_test.go
Cherry pick of #24429 on cloud.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #24429

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
I swear this is should be the last one of these I'll need to do for at least a few weeks.
Releasing the new versions of these packages will happen after 9.1 is released, but I'm updating the version numbers now so that I won't need to make changes to the `release-9.1` branch after that's cut
MM-54350
```release-note
NONE
```
> MM-54350 Update subpackage versions to 9.1

- api4/user.go
- api4/user_local.go
- api4/user_test.go
Manual cherry pick of [639d73b](https://github.com/mattermost/mattermost/commit/639d73b3e71addbd8cbba1a4f5f3f745713e537d) into `release-7.8`
```release-note
NONE
```
> Manual cherry pick of #24344 into release-7.8

- webapp/channels/src/components/desktop_auth_token.tsx
Cherry pick of #24479 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24479

- server/channels/api4/system.go
- server/channels/api4/user_test.go
- server/channels/app/admin.go
- server/channels/app/license.go
- server/channels/app/license_test.go
- server/channels/app/notification_test.go
- server/channels/app/oauth.go
- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/license.go
- server/channels/app/platform/service.go
- server/channels/app/server.go
- server/cmd/mattermost/commands/init.go
- server/cmd/mattermost/commands/jobserver.go
- server/public/model/cluster_message.go
Cherry pick of #24498 on cloud.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #24498

- server/channels/api4/system.go
- server/channels/api4/user_test.go
- server/channels/app/admin.go
- server/channels/app/license.go
- server/channels/app/license_test.go
- server/channels/app/notification_test.go
- server/channels/app/oauth.go
- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/license.go
- server/channels/app/platform/service.go
- server/channels/app/server.go
- server/cmd/mattermost/commands/init.go
- server/cmd/mattermost/commands/jobserver.go
- server/public/model/cluster_message.go
This reverts commit dd73c2af0f5ee8a5a2cfa201bcf44e8b08a124c1.
```release-note
NONE
```
> Revert "MM-53879: Fix recursive loading of license (#24200)" (#24498)

- webapp/channels/src/plugins/registry.ts
Cherry pick of #24497 on release-9.0.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #24497

- webapp/channels/src/components/resizable_sidebar/resizable_divider.tsx
- webapp/channels/src/components/resizable_sidebar/resizable_lhs/index.tsx
- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/sidebar/__snapshots__/sidebar.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar.tsx
- webapp/channels/src/components/sidebar_right/index.ts
- webapp/channels/src/components/sidebar_right/sidebar_right.tsx
- webapp/channels/src/sass/components/_post.scss
- webapp/channels/src/sass/responsive/_tablet.scss
Cherry-pick of #24491 to `cloud`
```release-note
NONE
```
> MM-54399 Move resizable sidebar handles to not overlap scrollbars  (#24491)

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
This is a short-term fix. More in-depth analysis of the root cause will take place as part of https://mattermost.atlassian.net/browse/MM-53149.
https://mattermost.atlassian.net/browse/MM-54452
```release-note
NONE
```
> [MM-54452] Add defensive code to makeGetPostsInChannel to avoid panic

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
Cherry pick of #24510 on release-8.1.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #24510

- server/channels/app/platform/license.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/license_store.go
- server/channels/store/store.go
- server/channels/store/storetest/license_store.go
- server/channels/store/storetest/mocks/LicenseStore.go
- server/channels/store/timerlayer/timerlayer.go
PR fixes an issue causing a valid license to fail to get loaded properly due to a read after write error which can result in failing to find a previously stored license due to replica lag.
https://mattermost.atlassian.net/browse/MM-54456
```release-note
Fixed a potential read after write issue when loading license
```
> [MM-54456] Fix potential read after write issue when loading license

- server/public/model/version.go
Cherry pick of #24549 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24549

- server/channels/app/plugin_hooks_test.go
- server/channels/app/post.go
- server/public/plugin/client_rpc_generated.go
- server/public/plugin/hooks.go
- server/public/plugin/hooks_timer_layer_generated.go
- server/public/plugin/plugintest/hooks.go
- server/public/plugin/product_hooks_generated.go
Cherry pick of #22476 on cloud.
/cc  @jespino
```release-note
NONE
```
> Automated cherry pick of #22476

- server/channels/app/platform/license.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/license_store.go
- server/channels/store/store.go
- server/channels/store/storetest/license_store.go
- server/channels/store/storetest/mocks/LicenseStore.go
- server/channels/store/timerlayer/timerlayer.go
Cherry-pick of https://github.com/mattermost/mattermost/pull/24524 on `release-8.1`.
https://mattermost.atlassian.net/browse/MM-54456
```release-note
Fixed a potential read after write issue when loading license
```
> [MM-54456] Cherry-pick of #24524 on `release-8.1`

- webapp/channels/src/components/profile_popover/index.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
- webapp/channels/src/selectors/calls.ts
Cherry pick of #24544 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24544

- server/channels/app/slashcommands/command_invite.go
- server/channels/app/slashcommands/command_invite_test.go
- server/i18n/en.json
- webapp/package-lock.json
Cherry pick of #24553 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24553

- server/channels/app/user.go
- server/channels/app/user_test.go
Cherry pick of #24362 on release-8.1.
/cc  @enahum
```release-note
NONE
```
> Manual cherry pick of #24362

- server/channels/api4/plugin_test.go
- server/channels/api4/system_test.go
- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
- webapp/channels/src/components/plugin_marketplace/__snapshots__/marketplace_modal.test.tsx.snap
- webapp/channels/src/components/plugin_marketplace/marketplace_modal.tsx
Cherry pick of #24561 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24561

- webapp/channels/src/components/admin_console/admin_definition.jsx
- webapp/channels/src/i18n/en.json
Cherry pick of #24375 on release-8.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24375

- e2e-tests/cypress/tests/integration/channels/auth_sso/authentication_4_spec.ts
- e2e-tests/cypress/tests/integration/channels/interactive_dialog/scrollable_spec.js
- e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/ctrl_cmd_k_focuses_message_box_spec.js
- e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/dot_menu_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/ctrl_cmd_k_find_gm_by_matching_name_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/message_with_gif_spec.js
Fixed E2E tests
none
```release-note
NONE
```
> Cypress/E2E: fix tests

- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
https://mattermost.atlassian.net/browse/MM-54512
```release-note
None
```
> [MM-54512] Fix style regression for add channel member modal

- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
Cherry pick of #24605 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24605

- server/channels/web/oauth_test.go
Fixes failing tests introduced in #24554 
https://mattermost.atlassian.net/browse/MM-54489
```release-note
NONE
```
> fix mobile oauth tests

- webapp/channels/src/components/system_notice/notices.tsx
- webapp/channels/src/i18n/en.json
Fix typo
Fix https://mattermost.atlassian.net/browse/MM-54542
Not needed. Fixing a typo introduced in this same version.
```release-note
NONE
```
> [MM-54542] Fix typo

- webapp/channels/src/components/system_notice/notices.tsx
- webapp/channels/src/i18n/en.json
Cherry pick of #24623 on release-9.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24623

- webapp/channels/src/sass/components/_buttons.scss
MM-54566 - Adding color override for the primary button
Fixes https://mattermost.atlassian.net/browse/MM-54566
```release-note
NONE
```
> MM-54566 - Adding color override for button

- server/channels/app/platform/log.go
- server/go.mod
- server/go.sum
- server/platform/services/imageproxy/local.go
- server/public/model/config.go
Cherry pick of #24251 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24251

- webapp/channels/src/sass/components/_buttons.scss
Cherry pick of #24616 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24616

- server/Makefile
Tiny change to test auto-merge functionality.
N/A
```release-note
NONE
```
> add period for consistency in help text

- server/Makefile
update prepackage boards to v7.11.4
Fixes https://mattermost.atlassian.net/browse/MM-54366
```release-note
NONE
```
> update prepackage boards to v7.11.4

- server/channels/app/slashcommands/command_invite.go
- server/channels/app/slashcommands/command_invite_test.go
Fixes ephemeral message when adding a user to a different channel. 
Fixes https://mattermost.atlassian.net/browse/MM-54555
```release-note
NONE
```
> MM-54555 - Include channel name in error

- server/channels/app/slashcommands/command_invite.go
- server/channels/app/slashcommands/command_invite_test.go
Cherry pick of #24614 on release-9.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24614

- webapp/channels/src/components/system_notice/__snapshots__/system_notice.test.tsx.snap
- webapp/channels/src/components/system_notice/notices.tsx
- webapp/channels/src/components/system_notice/system_notice.tsx
- webapp/channels/src/sass/components/_system-notice.scss
Cherry pick of #24636 on release-9.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24636

- server/Makefile
Cherry pick of #24619 on cloud.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #24619

- server/channels/api4/post.go
- server/channels/api4/post_test.go
- server/channels/app/post.go
- server/channels/web/context.go
- server/public/model/post.go
- server/public/model/post_test.go
- server/public/model/session.go
- server/public/model/session_test.go
Cherry pick of #24195 on cloud.
```release-note
NONE
```
> Automated cherry pick of #24195

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/actions/websocket_actions.test.jsx
- webapp/channels/src/packages/mattermost-redux/src/action_types/channels.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/channel_categories.ts
Cherry pick of #24633 on release-9.1.
```release-note
NONE
```
> Automated cherry pick of #24633

- webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
This is just a minor refactor to simplify the logic around `getStateFromNotifyProps` in the Channel Notifications Modal.
There should be no changes in behavior, but I hope this is more resilient to edge cases.
Fix https://mattermost.atlassian.net/browse/MM-54732
None needed, just a refactor on a feature that releases in this release.
```release-note
NONE
```
> Minor refactor to simplify the getStateFromNotifyProps

- webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
Cherry pick of #24635 on cloud.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24635

- webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
- webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
- webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
Fixed a bug where channel URL preview used incorrect team
https://mattermost.atlassian.net/browse/MM-54563
```release-note
None
```
> Fixed a bug where channel URL preview used incorrect team

- e2e-tests/cypress/tests/integration/playbooks/channels/rhs/checklist_spec.js
- e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/commands_spec.js
- e2e-tests/cypress/tests/support/ui/playbooks.js
Ideally, we'd eventually have a single source of truth for these, but for now I'm updating the monorepo with recent fixes from https://github.com/mattermost/mattermost-plugin-playbooks.
None.
```release-note
NONE
```
> Update e2e tests from upstream repository.

- webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
- webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.test.tsx
- webapp/channels/src/components/convert_gm_to_channel_modal/convert_gm_to_channel_modal.tsx
Cherry pick of #24705 on release-9.1.
```release-note
NONE
```
> Automated cherry pick of #24705

- webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
MM-54139 - Updating disabled state menu color
Fixes https://mattermost.atlassian.net/browse/MM-54139
```
NONE
```
> MM-54139 - Updating disabled state menu color

- .github/workflows/mmctl-test-template.yml
> Set env vars properly when running mmctl tests 

- Makefile
Prepackaged boards 7.8.9
```release-note
Prepackaged boards 7.8.9
```
> update prepackage boards to v7.8.9

- webapp/channels/src/components/pricing_modal/content.tsx
- webapp/channels/src/i18n/de.json
- webapp/channels/src/i18n/en.json
- webapp/channels/src/i18n/en_AU.json
- webapp/channels/src/i18n/es.json
- webapp/channels/src/i18n/fa.json
- webapp/channels/src/i18n/fy.json
- webapp/channels/src/i18n/hu.json
- webapp/channels/src/i18n/ja.json
- webapp/channels/src/i18n/lt.json
- webapp/channels/src/i18n/nl.json
- webapp/channels/src/i18n/pl.json
- webapp/channels/src/i18n/ru.json
- webapp/channels/src/i18n/sv.json
- webapp/channels/src/i18n/tr.json
Remove Professional Plus Support offering from in-product offering. This was only available in the Cloud plans modal.
https://mattermost.atlassian.net/browse/MM-54779
**Before**
**After**
```release-note
NONE
```
> Remove professional plus from in-product pricing

- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/user_guide_dropdown.tsx
- webapp/channels/src/components/widgets/menu/menu.tsx
Cause help menu to open right ways.
Jira https://mattermost.atlassian.net/browse/MM-54639
Fixes #24659
```release-note
Fixed alignment of help menu in global header
```
> [MM-54639] Help menu should open correctly aligned

- server/channels/utils/api.go
- server/channels/web/oauth_test.go
Cherry pick of #24554 on release-9.1.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #24554

- webapp/channels/src/components/file_upload/file_upload.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/i18n/en_AU.json
Updated file upload error message when no valid attachments are found
Fixes https://mattermost.atlassian.net/browse/MM-36351
```release-note
none
```
> Updated error message for invalid attachments

- utils/api.go
- web/oauth_test.go
Manual cherry pick of https://github.com/mattermost/mattermost/pull/24554
```release-note
NONE
```
> MM-54489 restrict mobile oauth/saml redirect to native app schemes (manual cherry-pick #24554)

- server/channels/app/platform/log.go
- server/go.mod
- server/go.sum
- server/platform/services/imageproxy/local.go
- server/public/model/config.go
Cherry pick of #24251 to `release-9.0` branch.
```release-note
NONE
```
> Add limiting ability to log fields (#24251)

- server/channels/app/authorization.go
- server/channels/app/post_metadata_test.go
Cherry pick of #24495 on release-9.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24495

- app/authorization.go
- app/post_metadata_test.go
Manual cherry pick #24495 
None
```release-note
NONE
```
> Cherry pick 24495

- webapp/channels/src/plugins/rhs_plugin/rhs_plugin.tsx
In this PR, converted the RhsPlugin component from class component to functional component.
Fixed #24774
Jira ticket: https://mattermost.atlassian.net/browse/MM-54811
```release-note
Converted RhsPlugin component to functional component
```
> #24774 Converted ./plugins/rhs_plugin/rhs_plugin.tsx to Function Component

- webapp/channels/src/components/suggestion/suggestion_list.jsx
Manual cherry pick of #24494 
```release-note
NONE
```
> Cherry pick #24494

- webapp/channels/src/components/emoji_picker/components/emoji_picker_header.tsx
In this PR, converted the EmojiPickerHeader component from class component to functional component.
Fixed #24773
Jira ticket: https://mattermost.atlassian.net/browse/MM-54810
```release-note
Converted EmojiPickerHeader component to functional component
```
> #24773 Converted ./components/emoji_picker/components/emoji_picker_header.tsx to Function Component

- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
Cherry pick of #24828 on release-9.2.
```release-note
NONE
```
> Automated cherry pick of #24828

- api/v4/source/emoji.yaml
Docs for https://github.com/mattermost/mattermost/pull/24651
MM-54640
```release-note
NONE
```
> Add documentation for get emojis by names API

- webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
- webapp/channels/src/components/widgets/icons/shield_outline_icon.tsx
This PR convert shieldOutlineComponet from class to function component
Fixes #24756
Jira MM-54792
```release-note
NONE
```
> Convert ShieldOutlineIcon to function Component

- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/components/_channel-invite-modal.scss
- webapp/channels/src/sass/responsive/_tablet.scss
MM-54777 - Updating invite modal guest button
Fixes https://mattermost.atlassian.net/browse/MM-54881
Fixes https://mattermost.atlassian.net/browse/MM-54777
```release-note
NONE
```
> MM-54777 - Updating invite modal guest button

- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/components/_channel-invite-modal.scss
- webapp/channels/src/sass/responsive/_tablet.scss
Cherry pick of #24977 on release-9.2.
```release-note
NONE
```
> Automated cherry pick of #24977

- webapp/channels/src/components/channel_layout/center_channel/center_channel.tsx
- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/path.ts
- webapp/channels/src/utils/utils.tsx
Cherry pick of #24622 on release-9.2.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24622

- webapp/channels/src/components/file_upload/file_upload.test.tsx
- webapp/channels/src/components/file_upload/file_upload.tsx
- webapp/channels/src/utils/paste.test.tsx
- webapp/channels/src/utils/paste.tsx
Cherry pick of #24718 on release-9.2.
```release-note
NONE
```
> Automated cherry pick of #24718

- webapp/channels/src/components/emoji/add_emoji/add_emoji.tsx
- webapp/channels/src/i18n/en.json
> [GH-25050] Typo in AddEmoji component

- webapp/channels/src/components/__snapshots__/file_upload_overlay.test.tsx.snap
- webapp/channels/src/components/file_upload_overlay.tsx
- webapp/channels/src/components/select_team/components/__snapshots__/select_team_item.test.tsx.snap
- webapp/channels/src/components/select_team/components/select_team_item.test.tsx
- webapp/channels/src/components/select_team/components/select_team_item.tsx
Following LocalizedIcon are replaced : 
- Upload Icon - webapp/channels/src/components/file_upload_overlay.tsx
- Loading Icon, Join Team Icon, Private team - webapp/channels/src/components/select_team/components/select_team_item.tsx
Jira https://mattermost.atlassian.net/browse/MM-54877
**select_team_item.tsx**
|----|----|
| <img width="1364" alt="image" src="https://github.com/mattermost/mattermost/assets/17708702/ae31d369-fc5d-4a80-9da6-c694b7ca6a0e"> | <img width="1364" alt="image" src="https://github.com/mattermost/mattermost/assets/17708702/4f6b90bb-5eac-4a95-8fac-4b88a1c67403"> |
**file_upload_overlay.tsx**
|----|----|
| <img width="1364" alt="image" src="https://github.com/mattermost/mattermost/assets/17708702/6821cf13-0199-49f1-9600-b5a0 …
> [MM-54877] Replace usage of LocalizedIcon in "select_team_item.tsx" & "file_upload_overlay.tsx" with i/span tags

- webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.test.tsx
- webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
Cherry pick of #24586 on release-8.1.
```release-note
NONE
```
> Automated cherry pick of #24586

- webapp/channels/src/components/widgets/icons/fa_search_icon.tsx
Replace LocalizedIcon with i tag in fa_search_icon.tsx
Fixes #25090
Jira https://mattermost.atlassian.net/browse/MM-55120
Icon used in add custom emoji page, search icon in search input
```release-note
NONE
```
> [MM-55120] Replace usage of LocalizedIcon in 'fa_search_icon.tsx' with i/span tags

- webapp/channels/package.json
- webapp/package-lock.json
Update pdfjs to version 3.11.174 to better manage PDF forms
The problem is visible on latest Firefox version, but I've also checked that it works on Firefox 102.15.1esr
Fixes https://github.com/mattermost/mattermost/issues/24895
Jira https://mattermost.atlassian.net/browse/MM-54924
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/60970/8a9dc998-8583-4f7b-b8ba-7ed7e74754f1) | ![image](https://github.com/mattermost/mattermost/assets/60970/69c694e0-7016-4d47-a083-8ce90d3cfbb8) |
```release-note
NONE
```
> MM-54924: Update pdfjs to version 3.11.174

- webapp/channels/src/components/autocomplete_selector.test.tsx
- webapp/channels/src/components/autocomplete_selector.tsx
- webapp/channels/src/components/interactive_dialog/dialog_element/dialog_element.tsx
- webapp/channels/src/components/post_view/embedded_bindings/select_binding/select_binding.tsx
- webapp/channels/src/components/post_view/message_attachments/action_menu/action_menu.tsx
PR migrates AutocompleteSelector and it's tests from Javascript to Typescript
Fixes https://github.com/mattermost/mattermost/issues/23414
None
```release-note
None
```
> [MM-52846] Migrate "components/autocomplete_selector.jsx" and tests to Typescript

- webapp/channels/src/components/admin_console/admin_navbar_dropdown/admin_navbar_dropdown.tsx
Fixes [Issue-#25081](https://github.com/mattermost/mattermost/issues/25081)
JIRA [Link](https://mattermost.atlassian.net/browse/MM-55092)
```release-note
NONE
```
> [MM-55092] Replace usage of LocalizedIcon in 'admin_navbar_dropdown.tsx' with i/span tags

- webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx
Replace usage of LocalizedIcon in 'user_settings_sidebar.tsx' with i/span tags
Fixes #25096 
Jira https://mattermost.atlassian.net/browse/MM-55114
```release-note
NONE
```
> [MM-55114] Replace usage of LocalizedIcon in 'user_settings_sidebar.tsx' with i/span tags

- webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
- Migrate 'components/suggestion/switch_channel_provider.test.jsx' to TypeScript
- fixes: #23932
- https://mattermost.atlassian.net/browse/MM-53474
```release-note
None
```
> [MM-53474] Migrate 'components/suggestion/switch_channel_provider.test.jsx' to TypeScript

- server/templates/cloud_30_day_arrears.html
> template diff

- webapp/channels/src/components/channel_layout/center_channel/center_channel.tsx
- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/path.ts
- webapp/channels/src/utils/utils.tsx
Manual cherrypick of #24622
NONE
```release-note
NONE
```
> Manual cherrypick #24622

- server/channels/app/app.go
- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
Remove dead method `App.Handle404`
NONE
```release-note
NONE
```
> Remove dead method Handle404

- webapp/channels/src/components/update_user_group_modal/__snapshots__/update_user_group_modal.test.tsx.snap
- webapp/channels/src/components/update_user_group_modal/update_user_group_modal.tsx
Replace LocalizedIcon with `i` tag in UpdateUserGroupModal component
Fixes https://github.com/mattermost/mattermost/issues/25103
Jira https://mattermost.atlassian.net/browse/MM-55107
```
NONE
```
> [MM-55107] Replace usage of LocalizedIcon in 'update_user_group_modal.tsx' with i/span tags

- webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
- webapp/channels/src/components/about_build_modal/about_build_modal.tsx
Cherry pick of #25370 on release-9.2.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25370

- server/channels/app/integration_action.go
- webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
- webapp/channels/src/components/markdown/__snapshots__/markdown.test.tsx.snap
- webapp/channels/src/components/markdown/index.ts
- webapp/channels/src/components/markdown/markdown.test.tsx
- webapp/channels/src/components/markdown/markdown.tsx
Converts Markdown component to functional along with correctly typing it. This is a type fix type I had to do in my other PR, so I just thought to make it into a separate PR
https://mattermost.atlassian.net/browse/MM-55339
none
```release-note
NONE
```
> [MM-55339] Improve types for Markdown component

- server/.golangci.yml
- server/channels/app/file.go
- server/channels/app/oauthproviders/gitlab/gitlab.go
- server/platform/shared/filestore/filesstore.go
See https://github.com/mattermost/enterprise/pull/1589
https://mattermost.atlassian.net/browse/MM-55409
```release-note
NONE
```
> [MM-55409] Enable revive linter on enterprise code

- webapp/channels/package.json
- webapp/package-lock.json
n/a
n/a
n/a
```release-note
NONE
```
> Upgrade "mattermost/compass-icons" to 0.1.39

- webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
- webapp/channels/src/components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Fix about cloud modal cloud.
https://github.com/mattermost/mattermost/pull/25370
```release-note
NONE
```
> fix: Fix about modal version for cloud installations

- webapp/channels/src/components/about_build_modal/about_build_modal.test.tsx
- webapp/channels/src/components/about_build_modal/about_build_modal_cloud/about_build_modal_cloud.tsx
Cherry pick of #25389 on release-9.2.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25389

- webapp/package.json
- webapp/platform/components/package.json
Adds workspace `npm run test:updatesnapshot` command for the workspace
https://mattermost.atlassian.net/browse/MM-55456
n/a
```release-note
NONE
```
> [MM-55456] Add npm "test:updatesnapshot" command to workspace

- .github/workflows/server-ci-artifacts.yml
- e2e-tests/.ci/.e2erc
- Deprecate `mm-ee-test` and `mm-te-test` in favor of `mattermost-enterprise-edition` & `mattermost-team-edition` on dev account . 
- Switch e2e tests images 
SIngle point of reference for artifacts [here](https://docs.google.com/spreadsheets/d/1k7MZHEhNpOSdFmxEet1I8rj9Ocly00IZc8mD1BPDZKM/edit#gid=830014074)
```release-note
NONE
```
> fix: Add new and final dev registry for pr artifacts

- webapp/channels/src/components/admin_console/plugin_management/index.ts
- webapp/channels/src/components/admin_console/plugin_management/plugin_management.test.tsx
- webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
Fixes visibility of `Enable Remote Marketplace` and `Marketplace URL` in system console.
- https://mattermost.atlassian.net/browse/MM-55403
|----|----|
| ![CleanShot 2023-11-13 at 15 39 03@2x](https://github.com/mattermost/mattermost/assets/11724372/7893ee4b-cc31-4560-a2f7-e4f5af7ab6cf) | ![CleanShot 2023-11-13 at 15 39 32@2x](https://github.com/mattermost/mattermost/assets/11724372/c76720f4-5f05-40b9-9902-ced7e4afe6c7) |
```release-note
NONE
```
> MM-55403: fix remote marketplace visibility

- server/public/model/push_notification.go
Cherry pick of #25405 on release-9.3.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #25405

- webapp/channels/src/components/admin_console/plugin_management/index.ts
- webapp/channels/src/components/admin_console/plugin_management/plugin_management.test.tsx
- webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx
Cherry pick of #25426 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #25426

- webapp/channels/src/sass/components/_suggestion-list.scss
Cherry pick of #25429 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #25429

- server/channels/app/notification.go
- server/channels/app/notification_test.go
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
Cherry pick of #24987 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #24987

- server/public/model/config.go
- server/public/model/config_test.go
Cherry pick of #25304 on release-9.3.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #25304

- server/channels/app/product_notices.go
- server/channels/app/product_notices_test.go
Cherry pick of #25435 on release-9.3.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25435

- .github/workflows/server-ci-artifacts.yml
- Remove monorepo conditions
- Add docker image on artifacts workflow
```release-note
```
> feat: Add docker image on artifacts generation summary

- webapp/channels/src/components/channel_header_dropdown/__snapshots__/channel_header_dropdown.test.tsx.snap
- webapp/channels/src/components/global_header/center_controls/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
- webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
- webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/product_menu_list.test.tsx
- webapp/channels/src/components/main_menu/__snapshots__/main_menu.test.tsx.snap
- webapp/channels/src/components/search/user_guide_dropdown/__snapshots__/user_guide_dropdown.test.tsx.snap
- webapp/channels/src/components/sidebar/__snapshots__/add_channels_cta_button.test.tsx.snap
- webapp/channels/src/components/status_dropdown/__snapshots__/status_dropdown.test.tsx.snap
- webapp/channels/src/components/widgets/menu/menu_group.tsx
- webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
Convert ./components/widgets/menu/menu_group.tsx from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/24775
Jira https://mattermost.atlassian.net/browse/MM-54814
```release-note
NONE
```
> MM-54814: Convert ./components/widgets/menu/menu_group.tsx from Class Component to Function Component

- webapp/channels/src/sass/layout/_navigation.scss
[MM-42752] Channel header icons impacted by long channel name in mobile view
Fixes https://github.com/mattermost/mattermost/issues/19858
Jira https://mattermost.atlassian.net/browse/MM-42752
**Before**
**After**
```release-note
NONE
```
[MM-42752]: https://mattermost.atlassian.net/browse/MM-42752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-42752] Channel header icons impacted by long channel name in mobile view

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
Cherry pick of #25226 on release-9.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25226

- webapp/channels/src/sass/components/_suggestion-list.scss
MM-55714 - Updating suggestion list height as before
https://mattermost.atlassian.net/browse/MM-55714
**Before**
**After**
```release-note
NONE
```
> MM-55714 - Updating suggestion list height as before

- webapp/channels/src/sass/components/_suggestion-list.scss
Cherry pick of #25516 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #25516

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
I hoped to get this in before the release-9.3.0 branch was cut, but I'm a bit late for that so it may need to be cherry-picked
```release-note
NONE
```
> Update subpackages to 9.3.0

- server/channels/store/sqlstore/post_store.go
https://mattermost.atlassian.net/browse/MM-55710
```release-note
NONE
```
> MM-55710: Remove join with channel in GetFlaggedPosts

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/types/package.json
Cherry pick of #25503 on release-9.3.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #25503

- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/post.go
- server/channels/app/post_test.go
Cherry pick of #24543 on release-8.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24543

- webapp/channels/src/sass/components/_emoticons.scss
Emoji picker hover fix
**Before**
**After**
```release-note
NONE
```
> Emoji picker hover fix

- .gitignore
- server/build/notice-file/config.yaml
Applied required configuration changes to comply with NOTICE.txt file generator
Related PR: https://github.com/mattermost/notice-file-generator/pull/14
https://mattermost.atlassian.net/browse/CLD-5534
```release-note
NONE
```
> feat: Change notice generation configuration file

- server/channels/app/slashcommands/auto_teams.go
Happy hacktoberfest
```release-note
NONE
```
> simplified app/slashcommands/auto_teams.go: remove duplicate line of code

- server/channels/app/channel.go
- server/channels/app/channel_test.go
Cherry pick of #25515 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #25515

- server/channels/app/migrations.go
Cherry pick of #24342 on release-9.3.
```release-note
NONE
```
> Automated cherry pick of #24342

- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
- server/channels/store/storetest/channel_store.go
Cherry pick of #25253 on release-9.3.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25253

- server/channels/app/notification.go
- server/channels/app/notification_test.go
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/groups.ts
Cherry pick of https://github.com/mattermost/mattermost/pull/24987
https://mattermost.atlassian.net/browse/MM-54933
```release-note
Fixed a bug where you couldn't @ mention custom groups in group constrained teams and channels
```
> fix conflicts and cherry pick groups fix

- server/channels/api4/brand.go
- server/channels/app/app_iface.go
- server/channels/app/brand.go
- server/channels/app/opentracing/opentracing_layer.go
- Add request context to all public methods with *App receiver in brand.go
- Resolves #25495
-  Jira https://mattermost.atlassian.net/browse/MM-55606
- not required
```release-note
NONE
```
> [MM-55606]: add the request context to all public methods in server/channels/app/brand.go

- server/channels/app/migrations.go
Cherrypick of #24342 for v8.1
```release-note
Updated the fix to run on license change on running server, thus removing the step to restart Mattermost server for the fix to take affect.
```
> Cherrypick of #24342 for v8.1

- webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
- webapp/channels/src/components/widgets/icons/email_icon.tsx
This PR converts the email icon widget from a class component to function component
If applicable, please include both or either of the following links:
Fixes https://github.com/mattermost/mattermost/issues/24755
Jira https://mattermost.atlassian.net/browse/MM-54791
```release-note
NONE
```
> [MM-54791]: Convert email icon component to function component

- webapp/channels/src/components/app.tsx
This PR converts the app component to a react function component
If applicable, please include both or either of the following links:
Fixes https://github.com/mattermost/mattermost/issues/24765
Jira https://mattermost.atlassian.net/browse/MM-54802
```release-note
NONE
```
> [MM-54802]: Convert app component to function component

- webapp/channels/src/components/discard_changes_modal.tsx
**Summary**
Fixes https://github.com/mattermost/mattermost/issues/25598
JIRA LINK: https://mattermost.atlassian.net/browse/MM-56006
**QA Notes**
Component is converted to React Functional Component, no change in functionality is expected. Component appears on Admin Console.
```release-note
NONE
```
> [MM-56006] Convert ./components/discard_changes_modal.tsx from Class Component to Function Component

- webapp/channels/src/components/toggle_modal_button.test.tsx
[MM-55328] Convert `./components/toggle_modal_button/toggle_modal_button.test.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25357
Jira https://mattermost.atlassian.net/browse/MM-55328
```release-note
None
```
[MM-55328]: https://mattermost.atlassian.net/browse/MM-55328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-55328] Convert `./components/toggle_modal_button/toggle_modal_button.test.tsx` from Class Component to Function Component

- webapp/channels/src/components/admin_console/ip_filtering/add_edit_ip_filter_modal.tsx
- webapp/channels/src/components/admin_console/ip_filtering/enable_section.tsx
Updates the linkouts to permalinks setup to go directly to the relevant docs page, rather than the root of the cloud workspace management directory. 
https://mattermost.atlassian.net/browse/CLD-6778
```release-note
None
```
> [CLD-6778] Update IP filtering docs linkouts

- api/v4/source/posts.yaml
**Summary**
Fixes #25384 
JIRA LINK: MM-55402
```release-note
NONE
```
> [MM-55402]Duplicate operationId SaveAcknowledgementForPost in openapi description document

- server/channels/store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-56039
```release-note
NONE
```
> MM-56039: Skip flaky test TestUserStore/LocalCache+PostgreSQL/SearchNotInTeam/

- server/channels/store/sqlstore/store.go
- server/channels/store/sqlstore/store_test.go
Cherry pick of #25637 on release-9.4.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #25637

- NOTICE.txt
Cherry pick of #25670 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #25670

- server/channels/app/oauth.go
- server/channels/web/oauth_test.go
Cherry pick of #23176 on release-8.1.
/cc  @m1lt0n
```release-note
NONE
```
> Automated cherry pick of #23176

- webapp/channels/src/utils/markdown/link_only_renderer.test.tsx
- webapp/channels/src/utils/markdown/remove_markdown.test.tsx
- webapp/channels/src/utils/markdown/remove_markdown.ts
Cherry pick of #25661 on release-9.4.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #25661

- server/channels/app/post.go
- server/channels/app/post_test.go
Fix MM53181
https://mattermost.atlassian.net/browse/MM-53181
```release-note
NONE
```
> Fix MM53181

- webapp/channels/src/components/post_view/embedded_bindings/embedded_bindings.tsx
Convert `./components/post_view/embedded_bindings/embedded_bindings.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25601
Jira https://mattermost.atlassian.net/browse/MM-56009
```release-note
NONE
```
> [MM-56009] Convert `./components/post_view/embedded_bindings/embedded_bindings.tsx` from Class Component to Function Component

- server/channels/app/post.go
- server/channels/app/post_test.go
Cherry pick of #25684 on release-9.4.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #25684

- server/build/docker-preview/Dockerfile
- server/build/docker-preview/README.md
- server/build/docker-preview/config_docker.json
- server/build/docker-preview/docker-entry.sh
Cherry pick of #25698 on release-9.1.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #25698

- webapp/channels/src/components/channel_invite_modal/team_warning_banner/__snapshots__/team_warning_banner.test.tsx.snap
- webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
- webapp/channels/src/components/user_group_popover/group_member_list/__snapshots__/group_member_list.test.tsx.snap
- webapp/channels/src/components/widgets/simple_tooltip/simple_tooltip.tsx
- webapp/channels/src/components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
- webapp/channels/src/components/widgets/users/avatars/avatars.scss
MM-55505 - Updating thread avatars hover state
Fixes https://mattermost.atlassian.net/browse/MM-55505
```release-note
NONE
```
> MM-55505 - Updating thread avatars hover state

- .github/workflows/server-test-template.yml
> Run contributor PR tests on free tier

- e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_dm_spec.js
- e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_gm_spec.js
- e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_private_channel_spec.js
- e2e-tests/cypress/tests/integration/channels/move_thread/move_thread_from_public_channel_spec.js
> chore: add test case ID to wrangler e2e tests

- .github/workflows/server-test-template.yml
We will use default runners for contributor Pull Requests . If this does not work we will revert the changes.
**Plus:** Automate the image choice 😄 
```release-note
```
> fix: Fix condition for choosing runner

- webapp/channels/src/components/admin_console/filter/filter_list.tsx
Convert `./components/admin_console/filter/filter_list.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25755
Jira https://mattermost.atlassian.net/browse/MM-56293
```release-note
NONE
```
> [MM-56293] Convert `./components/admin_console/filter/filter_list.tsx` from Class Component to Function Component

- server/channels/store/storetest/user_store.go
Re-enables user store test that was marked as flaky. Couldn't get it to fail locally, and a pass through the code doesn't point to anything that should be making it flaky.
https://mattermost.atlassian.net/browse/MM-56039
```release-note
NONE
```
> Remove user search skipped test

- webapp/channels/src/components/widgets/settings/radio_setting.tsx
Convert `./components/widgets/settings/radio_setting.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25759
Jira https://mattermost.atlassian.net/browse/MM-56297
```release-note
NONE
```
[MM-56297]: https://mattermost.atlassian.net/browse/MM-56297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-56297] Convert `./components/widgets/settings/radio_setting.tsx` from Class Component to Function Component

- webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.tsx.snap
- webapp/channels/src/components/widgets/icons/checkbox_partial_icon.tsx
Convert `./components/widgets/icons/checkbox_partial_icon.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25754
Jira https://mattermost.atlassian.net/browse/MM-56292
```release-note
NONE
```
> [MM-56292] Convert `./components/widgets/icons/checkbox_partial_icon.tsx` from Class Component to Function Component

- webapp/channels/src/components/file_attachment/__snapshots__/file_attachment.test.tsx.snap
- webapp/channels/src/components/file_attachment/file_thumbnail/file_thumbnail.tsx
- webapp/channels/src/components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap
Convert `./components/file_attachment/file_thumbnail/file_thumbnail.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25760
Jira https://mattermost.atlassian.net/browse/MM-56298
```release-note
NONE
```
> [MM-56298] Convert `./components/file_attachment/file_thumbnail/file_thumbnail.tsx` from Class Component to Function Component

- api/Makefile
- api/v4/source/definitions.yaml
- api/v4/source/limits.yaml
- server/channels/api4/api.go
- server/channels/api4/limits.go
- server/channels/app/app_iface.go
- server/channels/app/limits.go
- server/channels/app/limits_test.go
- server/channels/app/opentracing/opentracing_layer.go
- server/i18n/en.json
- server/public/model/client4.go
- server/public/model/limits.go
- webapp/platform/client/src/client4.ts
Added API to return user count bands and user count
Fixes https://mattermost.atlassian.net/jira/software/c/projects/MM/boards/126?assignee=6054be09e394c30069d776ea&selectedIssue=MM-56351
```release-note
None
```
> Added API to return user count bands and user count

- webapp/channels/src/components/admin_console/group_settings/group_details/__snapshots__/group_profile_and_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/group_settings/group_details/group_profile.tsx
Convert `./components/admin_console/group_settings/group_details/group_profile.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25756
Jira https://mattermost.atlassian.net/browse/MM-56294
```release-note
NONE
```
> [MM-56294] Convert `./components/admin_console/group_settings/group_details/group_profile.tsx` from Class Component to Function Component

- webapp/channels/src/components/pricing_modal/content.tsx
- webapp/channels/src/components/pricing_modal/self_hosted_content.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/i18n/en_AU.json
Updated in-product tier wording
Fixes https://mattermost.atlassian.net/browse/MM-56367
```release-note
None
```
> Updated tier wording

- api/v4/source/definitions.yaml
- server/channels/app/limits.go
- server/channels/app/limits_test.go
- server/public/model/limits.go
Removed user bands from API
Fixes https://mattermost.atlassian.net/browse/MM-56351
```release-note
None
```
> Removed user bands

- webapp/channels/src/components/air_gapped_contact_sales_modal/index.tsx
- webapp/channels/src/components/air_gapped_contact_sales_modal/style.scss
- webapp/channels/src/components/sidebar/add_channel_dropdown.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/constants.tsx
Added modal for contacting sales in air-gapped instance
Fixes https://mattermost.atlassian.net/browse/MM-56356
```release-note
None
```
> Added air-gapped contact sales modal

- webapp/channels/src/components/setting_item_max.tsx
- webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
Move the deactivate account section to the last, and change the button to danger
Fixes https://github.com/mattermost/mattermost/issues/25675
Jira https://mattermost.atlassian.net/browse/MM-56019
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/88369802/206333c4-5c41-4a54-b4d5-66b5a17a1c7e) | <img width="1245" alt="Screenshot 2023-12-12 at 3 19 29 PM" src="https://github.com/mattermost/mattermost/assets/88369802/6445abd6-9e17-40e3-993b-dc6d990bc67a"> |
```release-note
NONE
```
> [MM-56019] Move the deactivate account section to the last, and change the button to danger

- webapp/channels/src/components/admin_console/group_settings/__snapshots__/group_row.test.tsx.snap
- webapp/channels/src/components/admin_console/group_settings/groups_list/__snapshots__/groups_list.test.tsx.snap
- webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_checkbox.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap
- webapp/channels/src/components/widgets/icons/checkbox_checked_icon.tsx
Convert `./components/widgets/icons/checkbox_checked_icon.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25753
Jira https://mattermost.atlassian.net/browse/MM-56291
```release-note
NONE
```
> [MM-56291] Convert `./components/widgets/icons/checkbox_checked_icon.tsx` from Class Component to Function Component

- server/channels/store/sqlstore/user_store.go
- server/channels/store/storetest/user_store.go
Fixed issue where no results were returned when sorting in descending order, and going to previous page didn't work.
Fixes https://mattermost.atlassian.net/browse/MM-56281
```release-note
none
```
> Fixed user reporting pagination

- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
PR https://github.com/mattermost/mattermost/pull/22560
introduced a regression in the case where we had
multiple connections for a single user.
Because if connIndex.Remove was called during the iteration
from connIndex.ForUser, then the slice would be modified
during iteration and if a connection got removed,
then a good connection would move from the last index
to the current index. But since we would be actively
iterating, the last index would be read as nil and we would
never be able to reach the good connection.
We fix this by returning a copy of the original slice
if there are more than one elements in the slice.
https://mattermost.atlassian.net/browse/MM-56260
```release-note
Fix a bug where if there were multiple websocket
connections from a single user, then in case one connection …
```
> MM-56260: connIndex: safely remove conns while iterating

- server/channels/app/authorization.go
- server/channels/app/channel.go
- server/channels/app/post.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/searchlayer/channel_layer.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/mocks/ChannelStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
Reverts #25318 due to a regression (https://mattermost.atlassian.net/browse/MM-56465).
```release-note
NONE
```
> Revert "MM-55295: Improve DB performance of some APIs (#25318)"

- server/channels/app/authorization.go
- server/channels/app/channel.go
- server/channels/app/post.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/searchlayer/channel_layer.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/mocks/ChannelStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/searchengine/bleveengine/indexer/indexing_job.go
Cherry pick of #25852 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #25852

- webapp/channels/src/components/sidebar/sidebar_channel/__snapshots__/sidebar_channel.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx
Convert `./components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/25758
Jira https://mattermost.atlassian.net/browse/MM-56296
```release-note
NONE
```
> [MM-56296] Convert `./components/sidebar/sidebar_channel/sidebar_group_channel/sidebar_group_channel.tsx` from Class Component to Function Component

- server/channels/api4/post_test.go
- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
- server/channels/app/post.go
- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- server/channels/app/post_test.go
- webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts
- webapp/channels/src/components/permalink_view/actions.ts
- webapp/channels/src/components/permalink_view/permalink_view.test.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/channel_utils.tsx
- webapp/platform/client/src/client4.ts
- webapp/platform/types/src/posts.ts
Cherry pick of #24701 on release-9.3.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #24701

- server/channels/api4/role.go
- server/channels/api4/role_test.go
- server/i18n/en.json
- webapp/channels/src/packages/mattermost-redux/src/actions/roles.ts
- webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
Cherry pick of #25215 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #25215

- api/v4/source/groups.yaml
- server/channels/api4/group.go
- server/channels/api4/group_test.go
Cherry pick of #25462 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #25462

- server/channels/api4/post_test.go
- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
- server/channels/app/post.go
- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- server/channels/app/post_test.go
- webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts
- webapp/channels/src/components/permalink_view/actions.ts
- webapp/channels/src/components/permalink_view/permalink_view.test.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/channel_utils.tsx
- webapp/platform/client/src/client4.ts
- webapp/platform/types/src/posts.ts
Manual cherrpick of #24701 
```release-note
NONE
```
> Manual cherrpick: [MM-45272] Fix MM-45272 (#24701)

- server/channels/app/post.go
- server/channels/app/post_test.go
Manual cherrypick #25684 
```release-note
NONE
```
> Manual cherrypick: Fix MM53181 (#25684)

- server/channels/app/post.go
- server/channels/app/post_test.go
Manual cherrypick of #25585 
```release-note
NONE
```
> Manual cherrypick: Fix 55496 (#25585)

- server/channels/app/notification.go
- server/channels/app/notification_test.go
- server/channels/app/post.go
- server/channels/app/post_metadata.go
Cherry pick of #25683 on release-8.1.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #25683

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
- webapp/channels/src/packages/mattermost-redux/src/utils/post_utils.ts
Cherry pick of #25818 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #25818

- server/channels/api4/role.go
- server/channels/api4/role_test.go
- server/i18n/en.json
- webapp/channels/src/packages/mattermost-redux/src/actions/roles.ts
- webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
Cherry pick for https://github.com/mattermost/mattermost/pull/25215 on `release-8.1`
```release-note
NONE
```
> Improves validation in getRolesByName endpoint (#25215)

- server/channels/app/true_up.go
- server/channels/app/true_up_test.go
- server/public/model/true_up_review_profile.go
Cherry pick of #24921 on release-8.1.
```release-note
NONE
```
> Automated cherry pick of #24921

- server/channels/api4/team.go
- server/channels/api4/team_test.go
- server/i18n/en.json
- webapp/channels/src/i18n/en.json
Cherry pick of #25708 on release-9.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25708

- NOTICE.txt
Cherry pick of #25920 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #25920

- server/channels/app/notification_test.go
https://mattermost.atlassian.net/browse/MM-56565
```release-note
NONE
```
> Skip flaky test SendNotifications_MentionsFollowers

- server/channels/api4/plugin_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/plugin_api_tests/manual.test_websocket_session/main.go
Cherry pick of #25928 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #25928

- server/channels/api4/cloud.go
- server/channels/app/cloud.go
- server/public/model/cloud.go
- webapp/channels/src/components/admin_console/billing/billing_subscriptions/billing_subscriptions.tsx
- webapp/channels/src/components/announcement_bar/cloud_annual_renewal/index.tsx
- webapp/channels/src/components/purchase_modal/index.ts
- webapp/channels/src/utils/cloud_utils.ts
- webapp/platform/types/src/cloud.ts
Cherry pick of #25927 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #25927

- webapp/channels/src/components/admin_console/system_users/system_users.tsx
> [MM-56538]The default sort order is not visible on the column when on first load

- server/channels/api4/team.go
- server/channels/api4/team_test.go
- server/i18n/en.json
- webapp/channels/src/i18n/en.json
Cherry pick of https://github.com/mattermost/mattermost/pull/25708 on release-9.4.
---------
(cherry picked from commit 68be318fa24ef67c4050381e0c3a3808b38672ef)
```release-note
NONE
```
> Cherry-pick MM-55608:check invite guest permission (#25708)

- server/channels/api4/team.go
- server/channels/api4/team_test.go
- server/i18n/en.json
- webapp/channels/src/i18n/en.json
Cherry pick of #25966 on release-9.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25966

- webapp/channels/src/utils/markdown/renderer.test.tsx
- webapp/channels/src/utils/markdown/renderer.tsx
- webapp/channels/src/utils/text_formatting.test.ts
- webapp/channels/src/utils/text_formatting.tsx
Cherry pick of #25946 on release-9.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #25946

- webapp/channels/src/actions/channel_actions.ts
- webapp/channels/src/actions/invite_actions.ts
- webapp/channels/src/components/admin_console/system_users/system_users_dropdown/system_users_dropdown.tsx
- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
- webapp/channels/src/components/integrations/bots/bots.tsx
- webapp/channels/src/components/integrations/installed_incoming_webhooks/installed_incoming_webhooks.tsx
- webapp/channels/src/components/integrations/installed_outgoing_webhooks/installed_outgoing_webhooks.tsx
- webapp/channels/src/utils/constants.tsx
- webapp/platform/client/src/client4.ts
- webapp/platform/types/src/teams.ts
Based on https://github.com/mattermost/mattermost/pull/25983
This makes some small logic changes since I'm still trying to keep those separate from bigger PRs like https://github.com/mattermost/mattermost/pull/25983.
https://mattermost.atlassian.net/browse/MM-56619
```release-note
NONE
```
> Improve Redux types part 4

- server/channels/api4/team.go
- server/channels/api4/team_local.go
- server/i18n/en.json
- server/public/model/utils.go
- server/public/model/utils_test.go
Cherry pick of #25943 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #25943

- server/channels/api4/post_test.go
- server/channels/app/post.go
Cherry pick of #26001 on release-9.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26001

- server/channels/app/user.go
- webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
- webapp/channels/src/i18n/en.json
Update user limits error code text to reference safety limits within free version. 
https://mattermost.atlassian.net/browse/MM-56318 
```release-note
None
```
> Update user limits error code

- server/channels/app/user.go
- webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
- webapp/channels/src/i18n/en.json
Cherry pick of #26059 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26059

- webapp/channels/package.json
- webapp/package-lock.json
These packages are not used anymore and are replaced by @floating-ui/reac
https://mattermost.atlassian.net/browse/MM-56609
```release-note
NONE
```
> [MM-56609] Remove @floating-ui/react-dom & @floating-ui/react-dom-interactions in favour of @floating-ui/react 

- webapp/channels/src/components/admin_console/license_settings/modals/upload_license_modal.scss
- webapp/channels/src/sass/routes/_settings.scss
MM-56583 - Updating settings css for only centre content scroll
Fixes https://mattermost.atlassian.net/browse/MM-56583
Fixes https://mattermost.atlassian.net/browse/MM-56637
```release-note
NONE
```
> MM-56583 - Updating settings css for only centre content scroll

- webapp/channels/src/components/admin_console/license_settings/modals/upload_license_modal.scss
- webapp/channels/src/sass/routes/_settings.scss
Cherry pick of #26064 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26064

- e2e-tests/cypress/tests/integration/channels/bot_accounts/in_lists_1_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/auth_sso/mfa_authentication_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_more_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/system_console_manage_guest_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/authentication_method_spec.js
- e2e-tests/cypress/tests/integration/channels/system_console/user_management/users_spec.js
- e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js
Jira: https://mattermost.atlassian.net/browse/MM-56736
Dev PR : https://github.com/mattermost/mattermost/pull/26055
```release-note
NONE
```
> chore(e2e): Fix tests cases for new user Management ui

- server/channels/api4/file.go
- server/channels/api4/file_test.go
Fixes https://github.com/mattermost/mattermost/issues/25666
```release-note
NONE
```
> Allow HEAD requests on public files

- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
Cherry pick of #26087 on release-9.5.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26087

- server/i18n/en.json
Fixing a typo in en.json
https://community.mattermost.com/core/pl/z7swtk81gfb8zguzdqymjnachw
```release-note
NONE
```
> fixing typo

- server/channels/api4/channel_bookmark.go
- server/channels/api4/channel_bookmark_test.go
- server/public/model/feature_flags.go
Check the feature flag before initializing REST endpoints
```release-note
NONE
```
> Server side FeatureFlag check

- e2e-tests/cypress/tests/integration/channels/messaging/channel_and_posts_links_spec.js
defect : https://mattermost.atlassian.net/browse/MM-56575
for test-id depends on : https://github.com/mattermost/mattermost-test-management/pull/163
```release-note
NONE
```
> Add test case for non channel admin accessing post links

- webapp/channels/src/utils/text_formatting.tsx
Cherry pick of #26154 on release-9.4.
```release-note
NONE
```
> Automated cherry pick of #26154

- webapp/channels/src/utils/markdown/renderer.test.tsx
- webapp/channels/src/utils/markdown/renderer.tsx
- webapp/channels/src/utils/text_formatting.test.ts
- webapp/channels/src/utils/text_formatting.tsx
Cherry pick of #25946 on release-8.1
```release-note
NONE
```
> cherry pick of #25946

- server/channels/api4/user_test.go
- server/channels/app/app_iface.go
- server/channels/app/oauth.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/saml.go
- server/channels/web/saml.go
- server/i18n/en.json
- server/public/model/token.go
Cherry pick of #26100 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26100

- server/channels/api4/user_test.go
- server/channels/app/app_iface.go
- server/channels/app/oauth.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/saml.go
- server/channels/web/saml.go
- server/i18n/en.json
- server/public/model/token.go
https://mattermost.atlassian.net/browse/MM-56752
```release-note
NONE
```
> MM-56752 9.2 cherry pick

- server/channels/api4/user_test.go
- server/channels/app/app_iface.go
- server/channels/app/oauth.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/saml.go
- server/channels/web/saml.go
- server/i18n/en.json
- server/public/model/token.go
https://mattermost.atlassian.net/browse/MM-56752
```release-note
NONE
```
> MM-56752 8.1 cherry pick

- server/i18n/en.json
Cherry pick of #26182 on release-9.6.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #26182

- server/channels/app/platform/service.go
- server/channels/app/platform/shared_channel_notifier.go
Cherry pick of #26183 on release-9.6.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #26183

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Cherry pick of #26196 on release-9.6.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26196

- server/Makefile
Cherry pick of #26189 on release-9.6.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #26189

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/channels/store/storetest/mocks/ChannelStore.go
- server/channels/store/timerlayer/timerlayer.go
IsUserInChannelUseCache wasn't being used anywhere.
https://mattermost.atlassian.net/browse/MM-56878
```release-note
NONE
```
> MM-56878: Remove unused store method

- server/channels/api4/ip_filtering.go
- server/channels/app/app_iface.go
- server/channels/app/ip_filtering.go
- server/channels/app/opentracing/opentracing_layer.go
Refactors the logic for sending IP Filter changes notification emails out of the API controller and into the app layer.
https://mattermost.atlassian.net/browse/CLD-6630
```release-note
None
```
> [CLD-6630] Cleanup: Refactor IP Filters email notification logic into app layer

- webapp/channels/src/components/admin_console/admin_sidebar/__snapshots__/admin_sidebar.test.tsx.snap
- webapp/channels/src/components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx
Convert `./components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/26206
Jira https://mattermost.atlassian.net/browse/MM-56844
```release-note
NONE
```
> [MM-56844] Convert `./components/admin_console/admin_sidebar_header/admin_sidebar_header.tsx` from Class Component to Function Component

- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/outgoing_oauth_connection.go
- server/channels/api4/post.go
- server/channels/api4/preference.go
- server/channels/api4/reaction.go
- server/channels/api4/role.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/team_local.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/public/model/utils.go
- server/public/model/utils_test.go
**Note- This PR is on top of #26148 and the two will be merged together in master**
Removes the user of limited reader from utility deserialisers since the request body is already a limited reader from #26148
Fixes https://mattermost.atlassian.net/browse/MM-56888
```release-note
None
```
> Removed limited reader from util deserializers

- server/platform/services/sharedchannel/service.go
> Remove unnecessary cache invalidation for channel

- server/channels/app/platform/web_conn.go
- server/channels/app/web_conn_test.go
- server/public/model/feature_flags.go
- webapp/channels/src/actions/views/rhs.test.ts
- webapp/channels/src/actions/views/rhs.ts
- webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
- webapp/channels/src/components/channel_view/channel_view.test.tsx
- webapp/channels/src/components/channel_view/channel_view.tsx
- webapp/channels/src/components/channel_view/index.ts
- webapp/channels/src/components/team_sidebar/index.ts
- webapp/channels/src/components/team_sidebar/team_sidebar.tsx
- webapp/channels/src/components/threading/thread_viewer/index.ts
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.tsx
- webapp/channels/src/packages/mattermost-redux/src/action_types/posts.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
- webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
- webapp/channels/src/utils/test_helper.ts
- webapp/platform/types/src/config.ts
- webapp/platform/types/src/posts.ts
Reverts mattermost/mattermost#25794
Bad merge introduced an already removed feature flag.
```release-note
NONE
```
> Revert "MM-56201, MM-56280: Suppress typing and emoji events"

- server/channels/app/cloud.go
- server/public/model/cloud.go
This check was missed in initial implementation - internal/licensed customers all renew sales-serve, so they shouldn't receive this email. 
https://mattermost.atlassian.net/browse/CLD-7210
```release-note
None
```
> Don't email licensed/internal customers about Cloud Renewals

- server/channels/api4/plugin_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/plugin_api_tests/manual.test_websocket_session/main.go
Cherry-pick of https://github.com/mattermost/mattermost/pull/25928 in `release-8.1` branch.
```release-note
NONE
```
> [MM-54359] Manual cherry pick (release-8.1)

- webapp/channels/src/components/modal_controller/modal_controller.tsx
Convert `./components/modal_controller/modal_controller.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/26212
Jira https://mattermost.atlassian.net/browse/MM-56850
```release-note
NONE
```
> [MM-56850] Convert `./components/modal_controller/modal_controller.tsx` from Class Component to Function Component

- webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_icon.tsx
- webapp/channels/src/components/channel_info_rhs/menu.tsx
- webapp/channels/src/components/channel_info_rhs/top_buttons.tsx
- webapp/channels/src/sass/admin_console_base/_sys_css_variables.scss
- webapp/channels/src/sass/base/_css_variables.scss
- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/layout/_headers.scss
MM-56965 - Updating header icon value
I missed some icons, so this updates that.
I also introduced a variable based on @hmhealey's suggestion to manage this better.
I haven't updated everything, but maybe a good to have for future places we touch.
Jira https://mattermost.atlassian.net/browse/MM-56965
```release-note
NONE
```
> MM-56965 - Updating header icon value

- .github/workflows/api.yml
- .github/workflows/docker-push-mirrored.yml
- .github/workflows/e2e-tests-ci.yml
- .github/workflows/esrupgrade-common.yml
- .github/workflows/i18n-ci-template.yml
- .github/workflows/migration.yml
- .github/workflows/mmctl-test-template.yml
- .github/workflows/sentry.yaml
- .github/workflows/server-ci-artifacts.yml
- .github/workflows/server-ci-master.yml
- .github/workflows/server-ci-template.yml
- .github/workflows/server-test-template.yml
- .github/workflows/tag-public-module.yaml
- .github/workflows/webapp-ci-master.yml
- .github/workflows/webapp-ci-template.yml
- Upgrade Github Actions for node20 compatibility to avoid node16 deprecation
- Switch compression level for upload artifacts to increase performance
```release-note
NONE
```
> feat: Upgrade github actions for node20

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- webapp/channels/src/components/markdown_image/index.ts
- webapp/channels/src/components/markdown_image/markdown_image.test.tsx
- webapp/channels/src/components/markdown_image/markdown_image.tsx
- webapp/channels/src/utils/markdown/index.test.ts
- webapp/channels/src/utils/markdown/renderer.tsx
- webapp/channels/src/utils/text_formatting.tsx
- webapp/channels/src/utils/url.tsx
Cherry picked to the 9.6 branch:
- Add handling of posts with unsafe links. (#26129)
- Restrict post metadata to allow for potentially unsafe links (#26098)
```release-note
NONE
```
> Cherry pick of #26098 and #26129

- api/v4/source/preferences.yaml
- server/channels/api4/preference.go
- server/channels/api4/preference_test.go
Cherry pick of #25579 on release-9.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #25579

- server/channels/api4/team_test.go
- server/channels/app/team.go
Cherry pick of #26227 on release-9.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #26227

- e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/emoji_test.go
- server/channels/api4/post.go
- server/channels/api4/reaction.go
- server/channels/api4/role.go
- server/channels/api4/role_test.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/i18n/en.json
- server/platform/services/telemetry/telemetry.go
- server/public/model/client4.go
- server/public/model/config.go
- server/public/model/utils.go
- server/public/model/utils_test.go
- tools/mmgotool/commands/i18n.go
Cherry pick of https://github.com/mattermost/mattermost/pull/25510 on release-9.4.
```release-note
NONE
```
> Manual Cherry-pick of 25510

- server/channels/app/channel.go
- server/channels/app/plugin_hooks_test.go
Cherry pick of #26247 on release-9.5.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #26247

- e2e-tests/cypress/tests/integration/channels/channel_settings/channel_header_spec.ts
- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/emoji_test.go
- server/channels/api4/post.go
- server/channels/api4/reaction.go
- server/channels/api4/role.go
- server/channels/api4/role_test.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/i18n/en.json
- server/platform/services/telemetry/telemetry.go
- server/public/model/client4.go
- server/public/model/config.go
- server/public/model/utils.go
- server/public/model/utils_test.go
- tools/mmgotool/commands/i18n.go
Cherry pick of https://github.com/mattermost/mattermost/pull/25510 on release-9.3.
```release-note
NONE
```
> Manual Cherry-pick of 25510 (#26355)

- webapp/channels/src/sass/components/_channel-switcher.scss
MM-57077 - Updating channel switcher header
Fixes https://mattermost.atlassian.net/browse/MM-MM-57077
```release-note
NONE
```
> MM-57077 - Updating channel switcher header

- webapp/channels/src/components/browse_channels/browse_channels.scss
- webapp/channels/src/components/searchable_channel_list.tsx
Checks and displays the shared channel icon in the searchable channel list.
Fixes https://mattermost.atlassian.net/browse/MM-56980
```release-note
NONE
```
> MM-56980 add shared channel icon to searchable channel list

- NOTICE.txt
Cherry pick of #26427 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26427

- server/Makefile
Cherry pick of #26434 on release-9.7.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #26434

- webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.tsx
- webapp/channels/src/components/threading/thread_viewer/thread_viewer.test.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
- webapp/channels/src/sass/components/_post-right.scss
- webapp/channels/src/sass/responsive/_mobile.scss
- webapp/channels/src/selectors/rhs.ts
- webapp/channels/src/types/store/rhs.ts
MM-55251 - Adding reply count to thread view
I previously did something like `this.props.selected.id.reply_count` to fetch the reply count directly from within the file, but the reply count wasn't updating on delete, so had to fetch the thread from redux.
Fixes https://mattermost.atlassian.net/browse/MM-55251
```release-note
Added a total reply count to the RHS thread view
```
> MM-55251 - Updating reply count on thread post

- server/i18n/en.json
- server/public/model/custom_status.go
- server/public/model/user.go
- server/public/model/user_test.go
- webapp/channels/src/components/status_dropdown/status_dropdown.tsx
- webapp/channels/src/selectors/views/custom_status.test.ts
- webapp/channels/src/selectors/views/custom_status.ts
Cherry pick of #26287 on release-9.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #26287

- server/channels/api4/team_test.go
- server/channels/app/team.go
- server/i18n/en.json
Cherry pick of #25957 on release-8.1.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #25957

- server/channels/api4/team_test.go
- server/channels/app/import_functions_test.go
- server/channels/app/team.go
- server/i18n/en.json
Cherry pick of #26286 on release-9.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #26286

- server/channels/api4/channel_test.go
- server/channels/app/channel.go
- server/channels/app/import_functions_test.go
- server/i18n/en.json
Cherry pick of #26385 on release-9.6.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #26385

- server/Makefile
Cherry pick of #26454 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26454

- e2e-tests/.ci/report.publish.sh
- e2e-tests/.ci/server.generate.sh
Error encountered when running E2E tests locally in my Mac with `make run`.
Tested on Mac but not in other machine.
none
```release-note
NONE
```
> fix: error in truncate command with e2e script

- webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
Fixes the broken docs link for user limits
https://mattermost.atlassian.net/browse/MM-57033
```release-note
NONE
```
> [MM-57033] Update PL for user limit warning link

- webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx
Cherry pick of #26474 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26474

- webapp/channels/src/actions/views/drafts.test.ts
- webapp/channels/src/actions/views/drafts.ts
Cherry pick of #26481 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26481

- webapp/channels/src/sass/components/_multi-select.scss
Cherry pick of #26473 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26473

- server/channels/app/platform/shared_channel_notifier.go
- server/platform/services/sharedchannel/service_api.go
Cherry pick of #26469 on release-9.7.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #26469

- server/channels/api4/post_test.go
- server/channels/app/platform/websocket_router.go
- server/channels/web/handlers.go
- server/channels/wsapi/websocket_handler.go
- server/public/model/utils.go
- server/public/model/utils_test.go
Cherry pick of #26414 on release-9.7.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #26414

- server/channels/api4/post_test.go
- server/channels/app/platform/websocket_router.go
- server/channels/web/handlers.go
- server/channels/wsapi/websocket_handler.go
- server/public/model/utils.go
- server/public/model/utils_test.go
Cherry pick of #26414 on release-9.6.
/cc  @cpoile
```release-note
NONE
```
> Cherry pick of #26414

- server/channels/api4/emoji.go
Fixed create emoji API to be marked as file API
Fixes https://mattermost.atlassian.net/browse/MM-57315
```release-note
None
```
> Fixed create emoji API to be marked as file API

- webapp/channels/src/components/suggestion/search_date_suggestion/index.ts
- webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
- webapp/channels/src/components/suggestion/search_suggestion_list.tsx
- webapp/channels/src/components/suggestion/suggestion_date.tsx
- webapp/channels/src/components/suggestion/suggestion_list.tsx
- webapp/channels/src/components/user_group_popover/__snapshots__/user_group_popover.test.tsx.snap
- webapp/channels/src/components/user_group_popover/user_group_popover.test.tsx
- webapp/channels/src/components/user_group_popover/user_group_popover.tsx
- webapp/channels/src/components/widgets/popover/index.tsx
Cherry pick of #26476 on release-9.7.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26476

- server/channels/store/sqlstore/post_store.go
Cherry pick of #26517 on release-9.7.
```release-note
Improved performance of the ElasticSearch indexing job.
```
> Automated cherry pick of #26517

- server/channels/app/app_iface.go
- server/channels/app/oauth.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/platform/session.go
- server/channels/app/session.go
- server/channels/app/session_test.go
- server/channels/app/user_agent.go
- server/channels/app/user_agent_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/session_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/SessionStore.go
- server/channels/store/storetest/session_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/i18n/en.json
Cherry pick of #25900 on release-9.7.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #25900

- server/channels/api4/brand.go
- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/file.go
- server/channels/api4/handlers.go
- server/channels/api4/outgoing_oauth_connection.go
- server/channels/api4/post.go
- server/channels/api4/preference.go
- server/channels/api4/reaction.go
- server/channels/api4/role.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/team_local.go
- server/channels/api4/upload.go
- server/channels/api4/upload_local.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/channels/web/handlers.go
- server/i18n/en.json
- server/public/model/utils.go
- server/public/model/utils_test.go
Cherry pick of #26148 on release-9.6.
```release-note
NONE
```
> Automated cherry pick of #26148

- webapp/channels/src/actions/views/drafts.test.ts
- webapp/channels/src/actions/views/drafts.ts
- webapp/channels/src/actions/websocket_actions.jsx
Cherry pick of #26553 on release-9.6.
```release-note
NONE
```
> Automated cherry pick of #26553

- server/go.mod
- server/go.sum
Cherry pick of #26558 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26558

- server/channels/api4/emoji.go
- server/channels/api4/ldap.go
- server/channels/api4/license.go
- server/channels/api4/license_local.go
- server/channels/api4/plugin.go
- server/channels/api4/plugin_local.go
- server/channels/api4/remote_cluster.go
Manual cherrypick of #26513 and #26279 for v9.6
```release-note
None
```
> Manual cherrypick for API handler options for v9.6

- server/channels/api4/brand.go
- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/file.go
- server/channels/api4/handlers.go
- server/channels/api4/ldap.go
- server/channels/api4/license.go
- server/channels/api4/license_local.go
- server/channels/api4/plugin.go
- server/channels/api4/plugin_local.go
- server/channels/api4/post.go
- server/channels/api4/preference.go
- server/channels/api4/reaction.go
- server/channels/api4/remote_cluster.go
- server/channels/api4/role.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/team_local.go
- server/channels/api4/upload.go
- server/channels/api4/upload_local.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/channels/web/handlers.go
- server/i18n/en.json
- server/public/model/utils.go
- server/public/model/utils_test.go
Manual cherrypick of #26148, #26513 and #26279 for v9.5
```release-note
None
```
> Cherrypicking API Handler params for 9.5 

- server/channels/api4/brand.go
- server/channels/api4/channel.go
- server/channels/api4/channel_category.go
- server/channels/api4/data_retention.go
- server/channels/api4/emoji.go
- server/channels/api4/file.go
- server/channels/api4/handlers.go
- server/channels/api4/ldap.go
- server/channels/api4/license.go
- server/channels/api4/license_local.go
- server/channels/api4/plugin.go
- server/channels/api4/plugin_local.go
- server/channels/api4/post.go
- server/channels/api4/preference.go
- server/channels/api4/reaction.go
- server/channels/api4/remote_cluster.go
- server/channels/api4/role.go
- server/channels/api4/role_test.go
- server/channels/api4/status.go
- server/channels/api4/system.go
- server/channels/api4/team.go
- server/channels/api4/team_local.go
- server/channels/api4/upload.go
- server/channels/api4/upload_local.go
- server/channels/api4/user.go
- server/channels/api4/user_local.go
- server/channels/web/handlers.go
- server/i18n/en.json
- server/public/model/utils.go
- server/public/model/utils_test.go
Manual cherrypick of #26148, #26513 and #26279 for v8.1
```release-note
None
```
> Cherrypicking API Handler params for 8.1

- server/channels/api4/user.go
- server/channels/app/limits.go
- server/channels/app/plugin_hooks_test.go
- server/channels/app/user.go
- server/channels/app/user_test.go
- server/i18n/en.json
- server/public/model/limits.go
- webapp/channels/src/components/admin_console/system_users/system_users.scss
Manual cherrypick of #26511 for v9.7
```release-note
Added user limit enforcement
```
> Manual cherrypick of #26511 for v9.7

- server/channels/api4/emoji.go
Cherrypick of #26513 for v9.7
Fixes https://mattermost.atlassian.net/browse/MM-57315
```release-note
None
```
> Cherrypick of #26513 for v9.7

- server/Makefile
Cherry pick of #26557 on release-9.7.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #26557

- webapp/channels/src/components/post_view/post_image/post_image.tsx
Migrate `webapp/channels/src/components/post_view/post_image/post_image.tsx` from class component to function component.
Fixes https://github.com/mattermost/mattermost/issues/26209
Jira https://mattermost.atlassian.net/browse/MM-56847
```release-note
NONE
```
[MM-56847]: https://mattermost.atlassian.net/browse/MM-56847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-56847] Convert ./components/post_view/post_image/post_image.tsx from Class Component to Function Component

- server/public/model/config.go
Cherry pick of #26581 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26581

- server/i18n/en.json
Small text update to include error code in the user safety limit error text when creating or activating users. 
https://mattermost.atlassian.net/browse/MM-57313
```release-note
NONE
```
> Added error code in safety limit error

- server/i18n/en.json
Cherry pick of #26585 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26585

- webapp/channels/src/components/user_group_popover/user_group_popover.tsx
Cherry pick of #26608 on release-9.7.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26608

- webapp/channels/src/components/admin_console/system_users/system_users.scss
- webapp/channels/src/components/admin_console/system_users/system_users.tsx
- webapp/channels/src/components/profile_popover/profile_popover_name/full_name.tsx
- webapp/channels/src/components/shared_user_indicator.tsx
- webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
- webapp/channels/src/components/suggestion/search_user_provider.tsx
- webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
- webapp/channels/src/components/user_profile/user_profile.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/sass/utils/_mixins.scss
Cherry pick of #26612 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26612

- server/Makefile
Cherry pick of #26580 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26580

- server/channels/web/handlers.go
- server/public/model/utils.go
https://mattermost.atlassian.net/browse/MM-57415
```release-note
Removed unused IsOAuth field from AppError
```
> [MM-57415] Removed unused IsOAuth field from AppError

- server/channels/app/post.go
Previous log lines just had generic errors
which made things difficult to debug because
if a system bot is disabled, it's hard to know
whether the error is coming while trying to send
post reminders or from some other part of the system.
```release-note
NONE
```
> Add context to post reminder error logs

- server/channels/app/app_iface.go
- server/channels/app/export_test.go
- server/channels/app/file.go
- server/channels/app/file_bench_test.go
- server/channels/app/file_test.go
- server/channels/app/import.go
- server/channels/app/import_functions.go
- server/channels/app/import_functions_test.go
- server/channels/app/import_test.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/plugin_api_test.go
- server/channels/app/post_metadata_test.go
- server/channels/app/post_test.go
- server/channels/app/slack.go
- server/channels/app/user_test.go
- server/channels/jobs/import_process/worker.go
- server/cmd/mattermost/commands/import.go
- server/cmd/mmctl/commands/import.go
- server/cmd/mmctl/commands/import_test.go
- server/cmd/mmctl/docs/mmctl_import_process.rst
https://mattermost.atlassian.net/browse/MM-57512
```release-note
NONE
```
> MM-57512: Disable content extraction during import

- server/channels/app/integration_action.go
Cherry pick of #26516 on release-9.5.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #26516

- server/channels/api4/channel_category_test.go
- server/channels/api4/channel_test.go
- server/channels/api4/commands_test.go
- server/channels/api4/integration_action_test.go
- server/channels/api4/post_test.go
- server/channels/api4/user_test.go
- server/channels/app/platform/web_hub_test.go
- server/channels/app/plugin_api_test.go
- server/channels/app/plugin_hooks_test.go
- server/channels/app/server_test.go
- server/channels/jobs/schedulers_test.go
- server/platform/services/telemetry/telemetry_test.go
- server/public/pluginapi/cluster/job_test.go
- server/public/pluginapi/cluster/mutex_test.go
- server/public/pluginapi/kv_memory_test.go
- Bump timeouts for some cases
- Improve sleep with require/assert.EventuallyT
for better performance and reliability.
https://mattermost.atlassian.net/browse/MM-57532
```release-note
NONE
```
> MM-57532: Improve timeouts for some tests

- webapp/channels/package.json
- webapp/package-lock.json
Cherry pick of #26650 on release-9.5.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #26650

- server/public/model/config.go
Cherry pick of #26651 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26651

- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Cherry pick of #26653 on release-9.7.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26653

- e2e-tests/README.md
> Updated e2e-tests README.md

- server/channels/api4/group.go
- server/channels/api4/group_test.go
Cherry pick of #26595 on release-9.1.
/cc  @hanzei
```release-note
NONE
```
> Manual cherry pick of #26595 

- server/Makefile
- Prepackage Calls v0.26.2
- [none](https://mattermost.atlassian.net/browse/MM-57286)
```release-note
Prepackage Calls version v0.26.2
```
> [MM-57286] Prepackage calls v0.26.2

- webapp/channels/src/components/channel_select/channel_select.tsx
- webapp/channels/src/components/integrations/__snapshots__/abstract_incoming_hook.test.tsx.snap
- webapp/channels/src/components/integrations/__snapshots__/abstract_outgoing_webhook.test.tsx.snap
Fixes https://github.com/mattermost/mattermost/issues/26677
Jira https://mattermost.atlassian.net/browse/MM-57709
```release-note
NONE
```
> [MM-57709] Convert `./components/channel_select/channel_select.tsx` from Class Component to Function Component

- webapp/channels/src/components/suggestion/search_date_suggestion/search_date_suggestion.tsx
Convert SearchDateSuggestion from class component to functional component.
Fixes https://github.com/mattermost/mattermost/issues/26695
Jira https://mattermost.atlassian.net/browse/MM-57727
```release-note
NONE
```
> [MM-57727] Convert SearchDateSuggestion to functional component

- webapp/channels/src/components/post_emoji/post_emoji.test.tsx
- webapp/channels/src/components/post_emoji/post_emoji.tsx
- webapp/channels/src/sass/components/_post.scss
This PR adds the tooltip in emojis on hover at post messages.
Fixes https://github.com/mattermost/mattermost/issues/26519
```release-note
Added emoji tooltips on hover in post message.
```
> [MM-55497] Add tooltips with enlarged emojis when hovering over emojis within message content

- webapp/channels/src/components/add_users_to_group_modal/__snapshots__/add_users_to_group_modal.test.tsx.snap
- webapp/channels/src/components/add_users_to_group_modal/add_users_to_group_modal.tsx
- webapp/channels/src/components/admin_console/billing/delete_workspace/result_modal.scss
- webapp/channels/src/components/browse_channels/browse_channels.scss
- webapp/channels/src/components/product_notices_modal/product_notices_modal.scss
- webapp/channels/src/components/searchable_channel_list.tsx
- webapp/channels/src/components/tours/crt_tour/collapsed_reply_threads_modal.scss
- webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
- webapp/channels/src/components/view_user_group_modal/view_user_group_modal_header/view_user_group_modal_header.tsx
- webapp/channels/src/sass/components/_modal.scss
Cherry pick of #26635 on release-9.8.
```release-note
NONE
```
> Automated cherry pick of #26635

- server/channels/api4/group.go
- server/channels/api4/group_test.go
- server/channels/api4/user.go
- server/public/model/client4.go
- server/public/model/group_member.go
Cherry pick of #26551 on release-9.8.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #26551

- server/channels/api4/user_test.go
- server/channels/app/ldap.go
- server/channels/app/oauth.go
- server/i18n/en.json
- webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
- webapp/channels/src/components/user_settings/security/index.ts
- webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
- webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Cherry pick of #26589 on release-9.8.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #26589

- webapp/channels/src/components/root_post_divider/root_post_divider.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
MM-57292 - Adding root post divider component
Jira https://mattermost.atlassian.net/browse/MM-57292
```release-note
NONE
```
> MM-57292 - Adding root post divider component

- webapp/channels/src/components/root_post_divider/root_post_divider.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Cherry pick of #26614 on release-9.8.
```release-note
NONE
```
> Automated cherry pick of #26614

- server/Makefile
- server/build/release.mk
Cherry pick of #26310 on release-8.1.
/cc  @toninis
```release-note
NONE
```
> Automated cherry pick of #26310

- server/build/Dockerfile
- Remove version dependency from Mattermost Dockerfile to avoid pushing on protected branches.
https://mattermost.atlassian.net/browse/CLD-6644
```release-note
NONE
```
> fix: Remove version dependency from Dockerfile

- webapp/channels/src/components/copy_url_context_menu/copy_url_context_menu.tsx
Fixes https://github.com/mattermost/mattermost/issues/26676
Jira https://mattermost.atlassian.net/browse/MM-57708
```release-note
NONE
```
> [MM-57708] Convert `./components/copy_url_context_menu/copy_url_context_menu.tsx` from Class Component to Function Component

- webapp/channels/src/components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx
Fixes https://github.com/mattermost/mattermost/issues/26691
Jira https://mattermost.atlassian.net/browse/MM-57723
```release-note
NONE
```
> [MM-57723] Convert `./components/admin_console/system_user_detail/team_list/team_list_dropdown.tsx` from Class Component to Function Component

- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/sidebar_right_menu/constant.ts
- webapp/channels/src/components/sidebar_right_menu/index.ts
- webapp/channels/src/components/sidebar_right_menu/sidebar_right_menu.tsx
Convert `./components/sidebar_right_menu/sidebar_right_menu.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/26681
Jira https://mattermost.atlassian.net/browse/MM-57713
```release-note
NONE
```
> [MM-57713] Convert `./components/sidebar_right_menu/sidebar_right_menu.tsx` from Class Component to Function Component

- webapp/channels/src/components/common/chip/chip.tsx
Convert `./components/common/chip/chip.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/26693
Jira https://mattermost.atlassian.net/browse/MM-57725
```release-note
NONe
```
> [MM-57725] Convert `./components/common/chip/chip.tsx` from Class Component to Function Component

- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_groups.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/group/__snapshots__/group_list.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.test.tsx
- webapp/channels/src/components/admin_console/team_channel_settings/group/group_list.tsx
- webapp/channels/src/components/admin_console/team_channel_settings/team/details/__snapshots__/team_groups.test.tsx.snap
Fixes https://github.com/mattermost/mattermost/issues/26690
Jira https://mattermost.atlassian.net/browse/MM-57722
```release-note
NONE
```
> [MM-57722] Convert `./components/admin_console/team_channel_settings/group/group_list.tsx` from Class Component to Function Component

- server/channels/api4/user_test.go
- server/channels/app/ldap.go
- server/channels/app/oauth.go
- server/i18n/en.json
- webapp/channels/src/components/user_settings/security/__snapshots__/user_settings_security.test.tsx.snap
- webapp/channels/src/components/user_settings/security/index.ts
- webapp/channels/src/components/user_settings/security/user_settings_security.test.tsx
- webapp/channels/src/components/user_settings/security/user_settings_security.tsx
Cherry pick of #26589 on release-9.1.
```release-note
NONE
```
> Fix MM-57090 (#26589)

- server/channels/app/notification_push.go
- server/public/model/push_notification.go
Manual cherrypick of #26643
```release-note
NONE
```
> Fix MM 56723 (#26643)

- webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx
- webapp/channels/src/components/post_view/message_attachments/message_attachment/__snapshots__/message_attachment.test.tsx.snap
Convert `./components/post_view/message_attachments/action_button/action_button.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/26686
Jira https://mattermost.atlassian.net/browse/MM-57718
```release-note
NONE
```
> [MM-57718] Convert `./components/post_view/message_attachments/action_button/action_button.tsx` from Class Component to Function Component

- server/Makefile
See https://github.com/mattermost/enterprise/pull/1663
https://mattermost.atlassian.net/browse/MM-57789
```release-note
NONE
```
> [MM-57789] Update mockery version for LDAP mocks

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
Cherry pick of #26826 on release-9.8.
```release-note
NONE
```
> Automated cherry pick of #26826

- server/channels/app/channel.go
- server/i18n/en.json
Cherry pick of #26895 on release-9.8.
```release-note
NONE
```
> Automated cherry pick of #26895

- webapp/channels/src/components/logged_in/index.ts
- webapp/channels/src/components/logged_in/logged_in.test.tsx
- webapp/channels/src/components/logged_in/logged_in.tsx
Cherry pick of #26811 on release-9.5.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #26811

- server/cmd/mmctl/commands/import.go
Now we throw an error if the server is in HA. This is
because there is no guarantee that the server where the
request lands has access to the file locally.
https://mattermost.atlassian.net/browse/MM-57997
```release-note
Clarify that `mmctl import process --bypass-upload --local` doesn't work if the server is in HA.
```
> MM-57997: Fix bypass-upload in HA mode

- webapp/channels/src/actions/new_post.ts
- webapp/channels/src/actions/websocket_actions.jsx
Cherry pick of #26938 on release-9.8.
```release-note
NONE
```
> Automated cherry pick of #26938

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Cherry pick of #26947 on release-9.6.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #26947

- NOTICE.txt
Cherry pick of #26982 on release-9.9.
/cc  @amyblais
```release-note
NONE
```
> Automated cherry pick of #26982

- e2e-tests/cypress/tests/integration/channels/account_settings/profile/account_settings_position_spec.ts
- e2e-tests/cypress/tests/integration/channels/account_settings/profile/fullname_truncate_spec.ts
- e2e-tests/cypress/tests/integration/channels/account_settings/profile/username_spec.ts
- e2e-tests/cypress/tests/integration/channels/bot_accounts/display_name_spec.js
- e2e-tests/cypress/tests/integration/channels/channel_settings/add_users_to_channel_spec.ts
- e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_2_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_experience_ui_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_identification_ui_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/profile_popover/profile_popover_spec_user_a_b_spec.ts
- e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/inapp_username_profile_override_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/mobile_profile_popover_spec.js
- e2e-tests/cypress/tests/integration/channels/scroll/fixed_width_spec.js
- webapp/channels/src/components/view_user_group_modal/view_user_group_modal.scss
Fix for : https://github.com/mattermost/mattermost/pull/26420
```release-note
NONE
```
> Fix(cypress): Fix test cases for profile popover

- webapp/channels/src/sass/base/_structure.scss
Cherry pick of #26996 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #26996

- server/channels/api4/metrics.go
Cherry pick of #27011 on release-9.9.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #27011

- webapp/channels/src/sass/routes/_settings.scss
Cherry pick of #26869 on release-9.9.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #26869

- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
- webapp/channels/src/sass/routes/_error-page.scss
MM-58215 - Fixing error page
Jira https://mattermost.atlassian.net/browse/MM-58215
```release-note
NONE
```
> MM-58215 - Fixing error page

- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
- webapp/channels/src/sass/routes/_error-page.scss
Cherry pick of #27002 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27002

- server/channels/api4/remote_cluster.go
Cherry pick of #27008 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27008

- server/channels/app/session.go
Cherry pick of #27007 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27007

- server/channels/app/metrics.go
- server/public/model/metrics.go
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
Cherry pick of #27027 on release-9.9.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #27027

- server/Makefile
Cherry pick of #27031 on release-9.9.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #27031

- server/channels/api4/metrics_test.go
- server/public/model/metrics.go
- server/public/model/metrics_test.go
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
Cherry pick of #27046 on release-9.9.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #27046

- server/channels/app/limits.go
- server/channels/app/limits_test.go
- webapp/channels/src/components/common/accordion/accordion_card.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Cherry pick of #27034 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27034

- server/channels/app/metrics.go
- server/enterprise/metrics/metrics.go
Cherry pick of #27033 on release-9.9.
/cc  @hmhealey
```release-note
NONE
```
> Automated cherry pick of #27033

- webapp/channels/src/sass/base/_structure.scss
MM-58328 - Fixing playbooks and boards layout
Jira https://mattermost.atlassian.net/browse/MM-58328
```release-note
NONE
```
> MM-58328 - Fixing playbooks and boards layout

- webapp/channels/src/sass/base/_structure.scss
Cherry pick of #27075 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27075

- server/platform/services/sharedchannel/attachment.go
Cherry pick of #27018 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27018

- server/public/model/remote_cluster.go
Cherry pick of #27048 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27048

- e2e-tests/cypress/tests/support/index.js
> chore(e2e): Make EnableDiagnostics optional check

- server/channels/api4/user_test.go
- server/public/model/user.go
Cherry pick of #27047 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27047

- server/channels/api4/post.go
- server/channels/api4/post_test.go
- server/public/model/post.go
Cherry pick of #27049 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27049

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss
- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/sass/components/_post-right.scss
- webapp/channels/src/sass/components/_post.scss
Fixes alignment of error messages on posts and makes font sizes consistent with message typing.
Jira https://mattermost.atlassian.net/browse/MM-58183
|----|----|
| <img width="655" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/6d8cb34f-8dca-4df3-9078-5da3cc7d8579"> | <img width="641" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/68742db9-73a5-457f-a89c-0b7221e15165"> |
```release-note
NONE
```
> MM-58183 Post Error Style Fixes

- .github/workflows/build-server-image.yml
- server/build/Dockerfile.buildenv
- Introduce build image in a single common point (Migrate away from Gitlab)
- Migrate it to mattermostdevelopment since it's a dev image 
- Automate the build upon merge 
Removed obsolete checklist from https://hub.mattermost.com/playbooks/playbooks/k6xrudry9fgkxk3mktffyhiega/outline 
```release-note
NONE
```
> feat: Introduce build env image pipeline

- .github/workflows/build-server-image.yml
- Fixed wrong paths 
```release-note
NONE
```
> fix: Fix missing paths for build env docker image

- .github/workflows/build-server-image.yml
Fixed wrong path 
```release-note
NONE
```
> fix: Fix buildEnv Dockerfile path

- .github/workflows/server-ci-artifacts.yml
- .github/workflows/server-ci-template.yml
- Upgrade upload artifact action
- Change download action with the official one since it supports fetching artifacts from different workflows 
```release-note
NONE
```
> fix: Update download action with the official one

- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- webapp/channels/src/i18n/en.json
Cherry pick of #27195 on release-9.9.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #27195

- .github/workflows/server-ci-artifacts.yml
Resolving bug introduced with [pr-mattermost-27194](https://github.com/mattermost/mattermost/pull/27194) 
Added missing github-token directive to properly download the artifacts . 
```release-note
NONE
```
> fix: Add missing Github Token for download artifacts from other workflows

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/public/model/shared_channel.go
Cherry pick of #27143 on release-9.8.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27143

- server/channels/api4/user_test.go
- server/channels/app/oauth_test.go
- server/channels/app/session.go
- server/channels/app/user.go
Cherry pick of #27215 on release-9.5.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27215

- webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
- webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
See https://github.com/mattermost/mattermost/pull/27171
```release-note
```
> Cherry pick (#27171) into release-9.8

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
- server/channels/app/web_broadcast_hooks.go
- server/channels/app/web_broadcast_hooks_test.go
Cherry pick of #27212 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27212

- webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
- webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
See #27171
```release-note
None
```
> Cherry pick (#27171) into release-9.7

- webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
- webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
See #27171
```release-note
```
> Cherry pick (#27171) into release-9.6

- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
Cherry pick of #27203 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27203

- server/go.mod
- server/go.sum
- server/platform/services/sharedchannel/sync_recv.go
Cherry pick of #27290 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27290

- server/Makefile
Cherry pick of #27296 on release-9.10.
```release-note
NONE
```
> Automated cherry pick of #27296

- server/channels/app/server.go
Cherry pick of #27308 on release-9.10.
```release-note
NONE
```
> Automated cherry pick of #27308

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
- server/public/model/reaction.go
Cherry pick of #27317 on release-9.10.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27317

- server/channels/app/helper_test.go
- server/channels/app/metrics.go
- server/channels/app/metrics_test.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/enterprise/metrics/metrics_test.go
- server/public/model/metrics.go
Cherry pick of #27045 on release-9.10.
/cc  @larkox
```release-note
NONE
```
> Automated cherry pick of #27045

- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.jsx
Cherry pick of #26151 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26151

- server/platform/services/sharedchannel/sync_recv.go
Cherry pick of #27334 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #27334

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/platform/services/sharedchannel/mock_AppIface_test.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_recv.go
Cherry pick of #27331 on release-9.10.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27331

- webapp/channels/src/components/analytics/system_analytics/system_analytics.test.tsx
- webapp/channels/src/components/analytics/system_analytics/system_analytics.tsx
- webapp/platform/types/src/admin.ts
Cherry pick of #27188 on release-9.10.
```release-note
NONE
```
> Automated cherry pick of #27188

- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/components/_modal.scss
- webapp/channels/src/sass/layout/_headers.scss
Cherry pick of #27313 on release-9.10.
```release-note
NONE
```
> Automated cherry pick of #27313

- server/channels/store/storetest/mocks/ReactionStore.go
> fix 9.5 CI

- server/channels/api4/channel.go
- server/channels/app/app_iface.go
- server/channels/app/authorization.go
- server/channels/app/opentracing/opentracing_layer.go
Cherry pick of #26820 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26820

- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
Cherry pick of #27330 on release-9.10.
```release-note
NONE
```
> Automated cherry pick of #27330
