- server/Makefile
- Prepackage Calls v0.25.0
- https://mattermost.atlassian.net/browse/MM-56892
```release-note
Prepackage Calls version v0.25.0
```
> MM-56892- Update prepackaged calls to v0.25.0

- server/i18n/en.json
I did consider parsing the markdown instead of removing it. Given that the error is thrown by a third-party library and it's not well-defined which data ends up in the error, I do consider it a security risk to parse arbitrary markdown in the webapp.
https://mattermost.atlassian.net/browse/MM-57065
|----|----|
| ![image-20240301-190138](https://github.com/mattermost/mattermost/assets/16541325/947a3f3e-467c-4879-b00a-1c485e1b4751)| ![Screenshot from 2024-03-04 12-32-11](https://github.com/mattermost/mattermost/assets/16541325/81567534-bc16-4401-983b-cd877081f86b) |
```release-note
Remove markdown from AD page size error
```
> [MM-57065] Remove markdown from LDAP page size error

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.jsx.snap
- webapp/channels/src/components/admin_console/admin_console.tsx
- webapp/channels/src/components/admin_console/admin_settings.tsx
- webapp/channels/src/components/admin_console/custom_plugin_settings/custom_plugin_settings.test.tsx
- webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.test.tsx
- webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx
- webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.test.tsx
- webapp/channels/src/components/admin_console/data_retention_settings/data_retention_settings.tsx
- webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.test.tsx
- webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/global_policy_form.tsx
- webapp/channels/src/components/admin_console/data_retention_settings/global_policy_form/index.ts
- webapp/channels/src/components/admin_console/data_retention_settings/index.ts
- webapp/channels/src/components/admin_console/index.ts
- webapp/channels/src/components/admin_console/openid_convert/index.ts
- webapp/channels/src/components/admin_console/openid_convert/openid_convert.test.tsx
- webapp/channels/src/components/admin_console/openid_convert/openid_convert.tsx
- webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/edit_post_time_limit_modal.tsx
- webapp/channels/src/components/admin_console/permission_schemes_settings/edit_post_time_limit_modal/index.tsx
- webapp/channels/src/components/admin_console/schema_admin_settings.test.jsx
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/admin.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/admin.ts
While updating config from admin console, the webapp would set
any config param to null if the user doesn't have permission to edit
that setting.
This is common in cloud environments where a lot of config settings
are set to `cloud_restrictable`.
The problem due to that is since the client uses the updateConfig
endpoint, this acts as a full config replace and therefore, the null
fields get replaced by their default values.
To fix this, we use the patch endpoint which only updates the fields
that are actually set.
https://mattermost.atlassian.net/browse/MM-56625
```release-note
Fix a bug where config cannot be updated from admin console
in cloud environments.
```
> MM-56625: Use patchConfig to update configs from system console (#26332)

- server/Makefile
Adding the Mattermost AI plugin https://github.com/mattermost/mattermost-plugin-ai to be a pre-packaged plugin.
```release-note
Adding mattermost-plugin-ai to pre-packaged plugins.
```
> Adding AI plugin to pre-packaged plugins

- server/channels/api4/team_test.go
- server/channels/app/import_functions_test.go
- server/channels/app/team.go
- server/i18n/en.json
* dont allow guests to be set via team API
* comment out invalid test
* Update import_functions_test.go
---------
(cherry picked from commit e0f3713bdf2897ee325cbee26b157c3a42ef6368)
```release-note
NONE
```
> MM-56929- Dont allow guests to be set via team API (#26286)

- server/scripts/mirror-docker-images.json
Switching to quay.io for keycloak. Used for CD Process on providing a mirror of keyclock image under  `mattermostdevelopment/mirrored-keycloak` 
Local DRY RUNs follow
Before: 
```
[2024-03-14T15:07:36+02:00] Pushing image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1@sha256:f798d6cc25d724210be3660e95f63ae75d052ef392e3fc5ae728d02da7e52df8 ---> mattermostdevelopment/mirrored-cypress-browsers-public:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1 (dry run mode, set the DRY_RUN=no env var to disable)
[2024-03-14T15:07:36+02:00] Pushing image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge@sha256:f8459ee677ce356eff64698095fbdf48eb9ab018fc5eb0d30c07ba23884edace ---> mattermostdevelopment/mirrored-cypress-browsers-public:node16. …
```
> [CLD-7344] CD. Revisiting image registry for mattermostdevelopment/mirrored-keycloak

- webapp/channels/src/components/admin_console/full_log_event_modal/full_log_event_modal.tsx
- webapp/channels/src/i18n/en.json
This functionality has never worked and really isn't useful as is. It only exports a single log item at a time. Its been implemented a year and this is the first report, therefore it isn't being used.
Remove the export button from the log item viewer.
Fixes https://mattermost.atlassian.net/browse/MM-57068
```release-note
NONE
```
> MM 57068 - remove export button from log item viewer.

- webapp/channels/src/components/threading/virtualized_thread_viewer/thread_viewer_row.tsx
Apparently our i18n tooling silently ignores when two components have different `defaultMessage`s for the same `id` since this wasn't caught be CI
```release-note
NONE
```
> Fix incorrect translation string

- webapp/channels/src/actions/views/drafts.test.ts
- webapp/channels/src/actions/views/drafts.ts
When calling `removeDraft` (ie. after clicking delete on a draft or posting a message that had a draft), we were explicitly calling `removeGlobalitem` to delete the local draft, before other tabs were synced up. This would cause rehydration to sync drafts from other tabs (if open) back to the original tab, thus leaving the orphaned draft still in storage.
This PR defers that call to only do this when synced drafts are disabled, which should stop the bug from happening with server-synced drafts, and reduce it for local drafts (or at least only make it happen ephemerally).
The better solution going forward might be to rework the way we handle drafts when server syncing is turned on. It's unfortunately very hard to reproduce since it relies on the rehydration completing before the server can …
> [MM-57076] Stop removing local drafts when calling `removeDraft` for servers with synced drafts

- webapp/channels/src/components/widgets/admin_console/admin_panel.scss
- webapp/channels/src/sass/base/_css_variables.scss
- webapp/channels/src/sass/components/_alerts.scss
- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/components/_dnd-pickers-dropdown-menu.scss
- webapp/channels/src/sass/components/_edit-post-time-limit-button.scss
- webapp/channels/src/sass/components/_emoticons.scss
- webapp/channels/src/sass/components/_inputs.scss
- webapp/channels/src/sass/components/_popover.scss
- webapp/channels/src/sass/components/_scrollbar.scss
- webapp/channels/src/sass/routes/_about-modal.scss
- webapp/channels/src/sass/routes/_admin-console.scss
- webapp/channels/src/sass/utils/_variables.scss
This PR adds css variables for border radius and applies them in a few select areas (mainly where the sass variable `$border-rad` was being used. Also includes a few minor fixes to CSS in the admin panel CSS to fix how the border radius looks.
Future PRs are in the works that would like to take advantage of these variables.
The only place where a visible change occurs is where admin panels are used in the system console (fixes the corner radiuses and shadow)
| Before | After |
| --- | --- |
| <img width="2032" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/26d36ee0-0088-4d93-be2b-ffd2868678ad"> | <img width="2032" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/210ecb95-3bea-4e70-98ae-76e9c78d57ff"> |
```release-note
NONE
```
> Add css variables for border radius

- server/channels/app/platform/shared_channel_notifier.go
- server/platform/services/sharedchannel/service_api.go
The new/recent auto-share feature changes the code path to get channels automatically shared.  One code path wasn't creating a proper ShareChannels record.  This PR addresses that issue.
This only affects MS Teams plugin since normal Shared Channels does not auto subscibe.
NONE
```release-note
NONE
```
> Create proper SharedChannel record for InviteRemoteToChannel

- server/channels/app/platform/service.go
- server/channels/app/platform/status.go
- server/channels/store/localcachelayer/channel_layer.go
- server/channels/store/localcachelayer/file_info_layer.go
- server/channels/store/localcachelayer/post_layer.go
- server/channels/store/localcachelayer/team_layer.go
- server/channels/store/localcachelayer/terms_of_service_layer.go
- server/channels/store/localcachelayer/user_layer.go
- server/channels/store/localcachelayer/webhook_layer.go
We use the same name for hit/miss/invalidation metrics.
The downside is that now we have conflated a full cache purge
and a single cache key invalidation into a single label, but
the advantage is that it's easier to monitor the usage of a single
cache.
And moreover, duplicating the same string across multiple places
increases the chances of making a mistake. Centralizing the cache
name only at instantiation simplifies the code.
After this, we would be ready to use Redis.
https://mattermost.atlassian.net/browse/MM-57193
```release-note
NONE
```
> MM-57193: Standardize the cache names

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/common.ts
MM-56966 - cancel status request only on explicitly false config value
https://mattermost.atlassian.net/browse/MM-56966
```release-note
NONE
```
> MM-56966 - cancel status request only on explicitly false config value

- server/cmd/mmctl/commands/completion.go
- server/cmd/mmctl/commands/completion_test.go
- server/cmd/mmctl/commands/init.go
Cobra commands can expose dynamic shell completion by leveraging the `ValidArgsFunction` field. For example, `mmctl user activate` can show a list of deactivated users that match the provided prefix. This PR lays the foundation for adding shell completion for command in `mmctl` by introducing generic helper methods.
Search and list operations are costly as they load on the DB and consume a lot of memory. It's crucial to implement shell completion to ensure the Mattermost Server's performance is not compromised.
This is done in two ways:
- The number of returned items is limited to 50. Once 50 items are collected (e.g. via multiple list API calls), the results are returned.
- A timeout of 5 seconds if used for all API calls. It's unlikely that a user is willing to wait longer than this …
> [MM-56853] Add mmctl shell completion for commands

- server/channels/api4/channel_bookmark_test.go
`TestEditChannelBookmark` and `TestCreateChannelBookmark` are both flaky. Skip them until they are fixed.
https://mattermost.atlassian.net/browse/MM-57392
https://mattermost.atlassian.net/browse/MM-57393
```release-note
NONE
```
> [MM-57392] Skip flaky TestEditChannelBookmark test

- webapp/channels/src/components/user_group_popover/user_group_popover.tsx
In https://github.com/mattermost/mattermost/pull/26476 I did some cleanup, and removed the extra props that were apparently not being used. But that broke the popover.
~~Looking deeper, the component is receiving some props without nobody explicitly passing them. I guess is some kind of weird behavior of the Popover, but no idea. Either way, passing the props to the popover fixes the issue.~~
The reason is because the component is passed as a child to `Overlay` which fill up the missing props. I don't think there is a good way to type this without being more confusing.
Fix https://mattermost.atlassian.net/browse/MM-57482
```release-note
NONE
```
This just fixes a bug introduced in 9.7, so there should be no need for release notes.
> Fix user group not being properly potitioned

- webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.scss
- webapp/channels/src/components/threading/common/button/button.scss
This PR resolves an issue with the reply and follow buttons in the thread footer in the channel view.
Jira https://mattermost.atlassian.net/browse/MM-47680
<table>
<tr>
<td>Before</td><td><img width="950" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/2e916f85-604c-42e6-ad3f-cfd60be8c5a1"></td>
</tr>
<tr><td>After</td><td><img width="955" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/484380fe-07a8-4e65-96a6-b77f0c8a52cf"></td>
</tr>
</table>
```release-note
NONE
```
> MM-47680 Fix Thread Footer Buttons

- server/public/pluginapi/bot.go
- server/public/pluginapi/bot_test.go
Extend the `EnsureBot` functionality with a `ProfileImageFromBytes` option that doesn't require an on-disk file but can instead be supplied with `embed` or some other means.
At the same time, switch to `plugintest.NewAPI` in the affected tests based on the conversation in https://community.mattermost.com/core/pl/hzc71rikdjrztq97t3frf95hxw.
None.
```release-note
Expose `pluginapi.ProfileImageBytes` to simplify bot setup from a plugin.
```
> Profile image from bytes

- webapp/channels/src/components/admin_console/system_users/system_users.scss
- webapp/channels/src/components/admin_console/system_users/system_users.tsx
- webapp/channels/src/components/profile_popover/profile_popover_name/full_name.tsx
- webapp/channels/src/components/shared_user_indicator.tsx
- webapp/channels/src/components/suggestion/at_mention_provider/at_mention_suggestion.tsx
- webapp/channels/src/components/suggestion/search_user_provider.tsx
- webapp/channels/src/components/user_profile/__snapshots__/user_profile.test.tsx.snap
- webapp/channels/src/components/user_profile/user_profile.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/sass/utils/_mixins.scss
Add shared user icon for users with remote in systems users
https://mattermost.atlassian.net/browse/MM-57369
```release-note
NONE
```
> [MM-57369] Remote users no longer labeled as 'remote' after updates to the System Console Users UI

- server/Makefile
Updating AI plugin to 0.6.3
```release-note
NONE
```
(note this is a NONE release note since the previous PR introducing the AI plugin in this version is still valid)
> Update AI Plugin prepackaged version

- webapp/channels/src/components/team_sidebar/components/team_button.tsx
-  Only one `Tab` is needed to switch team buttons now 
- Did not add in functionality for `Space` to activate a team button because it is currently used for selecting and swapping the position of team buttons (see GIF below)
- I can add in functionality for `Space` to activate button (i.e same behavior as `Enter`) if that's something we still want to do
GH: https://github.com/mattermost/mattermost/issues/26489
JIRA: https://mattermost.atlassian.net/browse/MM-55272
|  Before  |  After  |
|----|----|
|<img src="https://github.com/mattermost/mattermost/assets/112513258/fff3f6d4-4dba-48e9-91f9-a5db94fe3cca" width="250" height="350"/>|<img src="https://github.com/mattermost/mattermost/assets/112513258/d394fd2b-ed72-4bf5-ab1c-48593dd99ee0" width="250" height="350"/>|
| Using `Space` To Switch …
> [MM-55272] Accessibility: Team Icon requires tabbing twice

- webapp/channels/src/components/rhs_thread/__snapshots__/rhs_thread.test.tsx.snap
- webapp/channels/src/components/rhs_thread/rhs_thread.tsx
- webapp/channels/src/sass/components/_post-right.scss
This PR cleans up the RHS thread view by removing the date separators and uses relative timestamps instead. This makes the RHS thread view consistent with the Global Threads view. Before this PR, the two views used different time stamp methods.
Jira https://mattermost.atlassian.net/browse/MM-55252
|----|----|
| <img width="571" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/1e4d8379-6c46-4e8a-8fd9-b66ea01f104b"> | <img width="570" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/5a462f2b-439d-4e42-bdb3-8ec4814cb3f3"> |
```release-note
Updated the RHS Thread view to use relative time stamps to be more consistent with the global Threads view.
```
> MM-55252 Update RHS Thread View to Use Relative Timestamps

- server/build/docker/nginx/default.conf
Plugins are generally larger than 50mb
```release-note
NONE
```
> Update default nginx client_max_body_size configuration

- server/channels/app/platform/config.go
- server/channels/app/platform/log.go
This PR makes minor improvements to logging start-up.
- comments have been added
- order of configuration is adjusted to allow the main logger to capture errors in notification logger
- redundant logger initialization removed; no need to configure the logger just to replace the configuration immediately after
https://mattermost.atlassian.net/browse/MM-57569
```release-note
NONE
```
> Improvements to logging start-up.

- server/channels/app/post.go
The log entry for when a permalink post notification doesn't need to be sent was very noisy as it was running on every post, and at the WARN level. Upon further investigation this doesn't really help with notification debugging since it just shouldn't be sent, so I've removed the log entry altogether.
```release-note
NONE
```
> Remove very noisy log entry

- server/public/model/config.go
Increased default payload limit from 100 kB to 300 kB
Fixes https://mattermost.atlassian.net/browse/MM-57572
```release-note
Increased default payload size limit (setting `MaximumPayloadSizeBytes`) from 100 kB to 300 kB
```
> Increased default payload limit from 100 kB to 300 kB

- server/platform/shared/filestore/filesstore.go
- server/platform/shared/filestore/filesstore_test.go
- server/platform/shared/filestore/s3store.go
- server/platform/shared/filestore/s3store_test.go
- server/public/model/config.go
The default and hard coded part size we use (5MB, which is the minimum value supported) can cause issues when uploading huge files since S3 has a limitation of [10,000 parts](https://docs.aws.amazon.com/AmazonS3/latest/userguide/qfacts.html) per upload which results in a 50GB hard limit for a single file upload. 
While this value should be generally enough for file attachments, it may be often exceeded by bulk exports which are single zip archive that can include all the attachments in a Mattermost installation.
To overcome this issue, PR provides two new config settings in case custom tuning is needed along with a couple of sensible defaults:
- `FileSettings.AmazonS3UploadPartSizeBytes` -> 5MB
- Not changing this seems reasonable as the mean uploaded file size is usually in the ballpark …
> [MM-57156] Make S3 upload part size configurable

- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
While refactoring the admin console in https://github.com/mattermost/mattermost/pull/25406 we added a bug where the default value of a setting will override the visible setting if we remove the whole string.
This was due to using the `||` operator when the first member (the value stored in the state) could valid when falsy (empty string).
Changing to the `??` operator solves the issue.
Fix https://mattermost.atlassian.net/browse/MM-57570
```release-note
Fix issue where it was not possible to clear plugin settings with a default value in the admin console
```
> Fix default text setting on admin console not getting cleared

- server/channels/app/post.go
Cherry pick of #26660 on release-9.7.
```release-note
NONE
```
> Automated cherry pick of #26660

- webapp/channels/package.json
- webapp/channels/src/actions/global_actions.tsx
- webapp/channels/src/components/logged_in/logged_in.tsx
- webapp/channels/src/utils/desktop_api.ts
- webapp/package-lock.json
This PR is the complement to https://github.com/mattermost/desktop/pull/2999 where we now have the server notify the Desktop App directly when it has logged in or logged out.
```release-note
NONE
```
> Add login/logout signal to Desktop App API

- server/cmd/mmctl/commands/team.go
- server/cmd/mmctl/commands/team_e2e_test.go
- server/cmd/mmctl/commands/team_test.go
- Return error instead of nil for modifyTeamsCmdF when encountering error 
- Error is returned using go-multierror
Fixes [#21571](https://github.com/mattermost/mattermost/issues/21471)
```release-note
None
```
> updated modifyTeamsCmdF to return error instead of nil when encounting error

- server/cmd/mmctl/commands/bot.go
- server/cmd/mmctl/commands/channel.go
- server/cmd/mmctl/commands/completion.go
- server/cmd/mmctl/commands/export.go
- server/cmd/mmctl/commands/extract.go
- server/cmd/mmctl/commands/import.go
- server/cmd/mmctl/commands/init.go
- server/cmd/mmctl/commands/logs.go
- server/cmd/mmctl/commands/oauth.go
- server/cmd/mmctl/commands/plugin_marketplace.go
- server/cmd/mmctl/commands/team.go
- server/cmd/mmctl/commands/team_test.go
- server/cmd/mmctl/commands/token.go
- server/cmd/mmctl/commands/user.go
- server/cmd/mmctl/commands/utils.go
The `mmctl` code has a lot of different ways to select the page size for requests. The PR unifies that to using `DefaultPageSize`, which is 200.
NONE
```release-note
NONE
```
> Simplify page size in mmctl

- server/channels/store/sqlstore/user_store.go
- server/channels/store/storetest/user_store.go
When the new User Admin Reporting screen was added, we removed the extra logic to go lookup a user by their ID if an ID was supplied. We were unable to keep it in its current state since that would require a separate endpoint to look up by ID that also provided the extra reporting data points.
This PR insteads adds the exact ID lookup to the server, where now any searching done using the user store will allow the exact ID to be matched as part of the user lookup.
https://mattermost.atlassian.net/browse/MM-57517
```release-note
Fixed an issue where you couldn't look up a user by their ID in the System Console anymore
```
> [MM-57517] Add exact user ID lookup to the search query for Users

- server/channels/api4/group.go
- server/channels/api4/group_test.go
Cherry pick of #26595 on release-9.5.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #26595

- server/channels/app/audit.go
- server/public/shared/mlog/mlog.go
Cloud team requested the ability to have a secondary source of configuration for audit logging.  This is available only via env var.   In the case of a target name colliding with one in config.json, this config will take precedence. 
Example:
```bash
export MM_EXPERIMENTALAUDITSETTINGS_ADDITIONAL=$(jq -n -c '{
"additional_audit_file_1": {
"Type": "file",
"Format": "json",
"Levels": [
{"ID": 100, "Name": "audit-api"},
{"ID": 101, "Name": "audit-content"},
{"ID": 102, "Name": "audit-permissions"},
{"ID": 103, "Name": "audit-cli"}
],
"Options": {
"Compress": true,
"Filename": "additional_mattermost_audit.log",
"MaxAgeDays": 1,
"MaxBackups": 10,
"MaxSizeMB": 500
},
"MaxQueueSize": 1000
}
}')
```
https://mattermost.atlassian.net/browse/MM-57823
```release-note
NONE
```
> Support for additional audit config via env var

- webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.scss
Fixes z-indexes to prevent weirdness in the UI 
https://mattermost.atlassian.net/browse/CLD-7375
|----|----|
| ![image](https://github.com/mattermost/mattermost/assets/12176405/9d9f248b-a40b-40ed-a4c7-e5c2763e1155) | ![image](https://github.com/mattermost/mattermost/assets/12176405/3de94906-f1a3-4f4e-ba60-ed9473ade993) |
```release-note
None
```
> [CLD-7375] Fix z index in stat trial form modal

- webapp/channels/src/sass/routes/_admin-console.scss
This PR updates the header in the system console to use Metropolis as the font to better align with headings elsewhere.
https://mattermost.atlassian.net/browse/MM-57186
|----|----|
| <img width="808" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/e615a8a9-c072-42b0-a41f-27dbb25883c8"> | <img width="811" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/8b5de212-e1f9-4d7e-8279-69ef8f84e440"> |
```release-note
NONE
```
> MM-57186 Update System Console Header Font

- server/channels/jobs/import_process/worker.go
We were passing the incorrect variable, which printed nil
in the logs
```release-note
NONE
```
> Import_process: Pass the right variable for error

- .github/workflows/server-test-template.yml
Migrate to mattermost reusable action for sending notifications
https://github.com/mattermost/action-mattermost-notify
```release-note
NONE
```
> fix: Migrate notifications to reusable actions

- webapp/channels/src/components/dot_menu/dot_menu.tsx
Fixes https://github.com/mattermost/mattermost/issues/26674
Fixes Jira https://mattermost.atlassian.net/browse/MM-52675
```release-note
When clicking on the "Copy Text" list item in a channel post dot menu (accessed by clicking the three dots) for a post that includes embedded images using markdown, the clipboard now receives the markdown as was entered into the original post instead of one that includes a proxy link.
```
> [MM-52675] Use message_source in copy text action (#26674)

- server/platform/services/remotecluster/ping_test.go
On occasion (at least once) the platform/services/remotecluster/ping_test.go units tests would fail.  
This is due to the line https://github.com/mattermost/mattermost/blob/ffc08858cf6344af2855dd5bec4e7a00dd866fd8/server/platform/services/remotecluster/service.go#L264 introduced in PR https://github.com/mattermost/mattermost/pull/26753
All registered remotes are pinged immediately on service startup, whereas before they were pinged via a thread loop asynchronously.  The flaky test is counting the number of pings for one cycle, which now means the initial ping on service start, and on occasion the thread loop kicks in before the test gets shutdown and adds some more pings.
To fix this the unit test has been refactored to achieve the underlying goal of making sure all the remotes get …
> Fix flaky ping test for remote clusters service

- webapp/channels/src/components/logged_in/index.ts
- webapp/channels/src/components/logged_in/logged_in.test.tsx
- webapp/channels/src/components/logged_in/logged_in.tsx
This was spurious code left from old times. It's not
needed now, and it was causing a race condition with the server
side where we were setting the status to offline on
websocket disconnect. So if this request reached the server
after the status was set to offline, the status would
reset to online.
https://mattermost.atlassian.net/browse/MM-57885
```release-note
Fixed a bug where status would incorrectly get stuck to online
after user closes the tab.
```
> MM-57885: Do not mark channel as read on tab unload

- server/channels/api4/channel.go
- server/channels/app/app_iface.go
- server/channels/app/authorization.go
- server/channels/app/opentracing/opentracing_layer.go
We made a fix to allow users that had the permission to read public channels to also be able to see the member count. This worked fine except for servers with compliance turned on, which wouldn't make sense to allow for channel read without explicitly being in the channel.
This PR adds a different permission check for the member count specifically, checking for the `ListTeamChannels` permissions which is already used when listing the available public channel objects.
https://mattermost.atlassian.net/browse/MM-56266
```release-note
Fixed an issue where on some server you cannot see the member count in the Browse Channels dialog
```
> [MM-56266] Use ListTeamChannels for member count permission for public channels

- webapp/channels/src/components/suggestion/modal_suggestion_list.tsx
The dropdown of select field in the modal has an absolute position (instead of fixed).
Fixes https://github.com/mattermost/mattermost/issues/26831
```release-note
NONE
```
> [GH-26831] fix modal suggestion list position

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
With the MSTeams plugin, we promote a user by removing their `remote_id` and changing their username. The username update was reflected by the webapp but the user still appeared as remote until a refresh was done
I found that the merge did not take into consideration the fact that the `remote_id` field can disappear: it's set to NULL in the DB and [the go model has an omitempty](https://github.com/mattermost/mattermost/blob/446c763fa8933e8262e71b0a0dd71a479ca0afd9/server/public/model/user.go#L101). The PR fixes this by deleting the field if the received user does not have it anymore.
https://mattermost.atlassian.net/browse/MM-57121
```release-note
NONE
```
> [MM-57121] Remove remote_id if necessary when merging user profile

- api/v4/source/bots.yaml
- api/v4/source/channels.yaml
- api/v4/source/dataretention.yaml
- api/v4/source/introduction.yaml
- api/v4/source/ldap.yaml
- api/v4/source/users.yaml
This PR includes two changes:
1. It documents the 200 maximum page size cap for the per_page parameter in a common place within the documentation.
2. It eliminates specific mentions of the 200 cap at individual API endpoints to avoid future inconsistencies, ensuring that this limit is consistently referenced from a single common location.
Related Issue: https://github.com/mattermost/mattermost/issues/26830
cc: @agnivade @amyblais @connorkuehl
https://mattermost.atlassian.net/browse/MM-57966
> [MM-57966]Document the 200 maximum page size cap for the per_page parameter in a central location in the documentation

- server/channels/app/imaging/decode.go
- server/platform/shared/web/files.go
Changes the default content disposition for WebP attachments from *download* to *inline*.
Add WebP codec support side-effect to decode.go. To prevent future issues caused by possible changes in emoji.go.
This PR adds WebP to MediaFormats on the server side. This changes behaviour related to WebP attachments.
Currently WebP Attachments are downloaded when accessed by the `Public Link` Feature. After this change those files all displayed inline in the browser as one might expect. This aligns with other image formats that are supported by the preview feature. It adds a most likely overseen (required) change related to [MM-11777].
Fixes https://github.com/mattermost/mattermost/issues/26628
Jira https://mattermost.atlassian.net/browse/MM-57851
```release-note
Added inline display of WebP …
```
> [MM-57851] Add WebP to MediaFormats #26628

- server/Makefile
Prepackage Zoom plugin 1.8.0
```release-note
Prepackage Zoom plugin version [v1.8.0](https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.8.0).
```
Prepackage Zoom plugin version [v1.8.0](https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.8.0).
> Bump prepackage Zoom plugin version to 1.8.0

- webapp/channels/src/components/browse_channels/browse_channels.scss
This PR fixes a styling issue with the checkbox on the Browse Channels Modal.
Jira https://mattermost.atlassian.net/browse/MM-58032
|----|----|
| <img width="624" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/57e87ca7-9c04-46af-b69a-cab12f0bf7b3"> | <img width="629" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/455bf1b3-8a66-4ca7-8eae-9462ecea2c71"> |
| <img width="626" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/46b64d3c-c5e5-4ebb-a471-231e9291e076"> | <img width="627" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/dfc7d427-6646-429d-8106-4b4636abb899"> |
```release-note
NONE
```
> MM-58032 Fix "Hide Joined" checkbox in "Browse channels" modal

- server/i18n/en.json
Desktop app v5.8 will include Electron 29.0 which supports Chrome 122+. macOS 11 went out of support last year.
```release-note
Updated minimum Edge and Chrome versions to 122+, and updated minimum macOS version to 12+.
```
> Updated minimum supported Edge, Chrome and macOS versions

- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.jsx
- webapp/channels/src/components/suggestion/suggestion_box/suggestion_box.test.tsx
I think I've finally tracked down the cause of this nasty bug where autocompleting something earlier in the post textbox will occasionally wipe out everything after the autocompleted text. If I understand correctly, the issue is because
1. https://github.com/mattermost/mattermost-webapp/pull/2078 added the ability to press enter while results are loading and then have the autocomplete wait to trigger until those results are loaded. The important part of this is that, the `SuggestionBox` passes a `resultCallback` into the `Provider` which calls `SuggestionBox.handleCompleteWord` whenever results are received.
2. Providers can call their `resultCallback` multiple times so that they can return a mix of local data and data from the server. When the above logic triggers, this means that it can …
> MM-57320 Fix autocomplete occasionally erasing all text after caret

- webapp/channels/src/components/desktop_auth_token.tsx
The original ticket for this is barely valid any more because the surrounding code around here has been rewritten, but there's one place that we still give the wrong type to the return value of the `loginWithDesktopToken`. It actually returns a boolean result, but since the `Login` component doesn't even look at that value, it didn't matter.
There's no functional changes here
https://mattermost.atlassian.net/browse/MM-53148
```release-note
NONE
```
> MM-53148 Fix an incorrect type

- server/.golangci.yml
See https://github.com/mattermost/enterprise/pull/1674
https://mattermost.atlassian.net/browse/MM-58043
```release-note
NONE
```
> [MM-58043] Enable errcheck linter for enterprise/data_retention package

- server/i18n/en.json
macOS minimum supported version was recently updated to 12+ https://github.com/mattermost/mattermost/pull/26748 , so I'm updating the Safari version to 17+ https://en.wikipedia.org/wiki/Safari_(web_browser)#History_and_development.
```release-note
Updated minimum Safari version to 17+.
```
> Update minimum supported Safari version

- webapp/channels/src/utils/paste.test.tsx
- webapp/channels/src/utils/paste.tsx
Previously, we made it so that ctrl+shift+v would make it so that text with links would be pasted without the links. Now, we want it to prevent any special formatting.
https://mattermost.atlassian.net/browse/MM-52570
```release-note
Ensured that pasting in the post textbox can always paste without formatting
```
> MM-52570 Prevent pasteHandler from having any effect when shift is held

- server/channels/api4/channel_bookmark_test.go
If the websocket is closed before we receive the expected message, this test fails spuriously with a panic. (This doesn't resolve the root cause of why the websocket event doesn't get delivered during some test runs, but pushing this for now to focus the test report.)
None.
None.
```release-note
NONE
```
> avoid segfault in TestDeleteChannelBookmark

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
Fix system console defaults by not using the default when the value is falsy (empty strings or false boolean value), only when the value is not set (i.e. undefined).
Fix https://mattermost.atlassian.net/browse/MM-58102
Fix https://github.com/mattermost/mattermost-plugin-calls/issues/720
```release-note
Fix some plugin settings with defaults not changing value.
```
> Fix system console defaults

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
PR fixes an issue that can cause the websocket connection gauges to go negative. Here's how Community is looking today:
In https://github.com/mattermost/mattermost/pull/26763 I made a wrong assumption that webconn registrations will always match unregistrations. This is not the case, in fact, if the session is not authenticated we could end up unregistering only:
https://github.com/mattermost/mattermost/blob/f1019d076edd5b7b42f2c61c630c3ad4620383f0/server/channels/api4/websocket.go#L77-L82
https://github.com/mattermost/mattermost/blob/f1019d076edd5b7b42f2c61c630c3ad4620383f0/server/channels/app/platform/web_conn.go#L406
I am adding the inc/dec operations to the webconn read pump function as I think it's more realistic than tracking registrations. This means that the counter will show …
> [MM-58091] Fix tracking websocket connections

- server/channels/app/notification.go
- server/channels/app/web_broadcast_hooks.go
- server/config/client.go
- server/public/model/config.go
- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/i18n/en.json
Adding a setting to accompany the feature for Notification Metrics, so that admins can turn it off via the System Console if they choose. Setting is default-on.
https://mattermost.atlassian.net/browse/MM-58159
```release-note
Added a setting for Notification Metrics `MetricsSettings.EnableNotificationMetrics`
```
> [MM-58159] Add admin setting for notification monitoring alongside feature flag

- webapp/channels/jest.config.js
- webapp/channels/src/actions/views/rhs.ts
- webapp/channels/src/components/post_view/post_list/post_list.tsx
- webapp/channels/src/components/rhs_thread/index.ts
- webapp/channels/src/components/rhs_thread/rhs_thread.tsx
- webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- webapp/channels/src/components/team_sidebar/components/team_button.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/index.ts
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.test.tsx
- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
- webapp/channels/src/utils/performance_telemetry/index.ts
As it says in the title, this is another metric to measure how long this takes since it's very important for perceived performance of the web app. It doesn't differentiate if the thread has already been loaded or if the RHS itself is already open from another thread, but I think that's fine because it'll skew the results towards whichever of those are the more common case anyway.
https://mattermost.atlassian.net/browse/MM-57881
```release-note
Added a metric to track time it takes for the RHS to load
```
> MM-57881 Add metric for the amount of time it takes for the RHS to load a thread

- webapp/channels/src/components/announcement_bar/__snapshots__/text_dismissable_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/sass/components/_announcement-bar.scss
MM-57548 - Fixing announcement banner icon
Jira https://mattermost.atlassian.net/browse/MM-57548
```release-note
NONE
```
> MM-57548 - Fixing announcement banner icon

- server/channels/api4/metrics.go
- server/enterprise/metrics/metrics.go
- server/public/model/client4.go
- server/scripts/vet-api-check.sh
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/platform/client/src/client4.ts
As discussed in a PR review comment: https://github.com/mattermost/mattermost/pull/26919#discussion_r1592959738 changing the API path to `client_perf`.
Since we are here, fixing the Prometheus labels as we are using `agent` everywhere else for the user agent label.
```release-note
NONE
```
> Change client metrics api path to client_perf

- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_more_spec.ts
- e2e-tests/cypress/tests/integration/channels/enterprise/guest_accounts/guest_invitation_ui_spec.ts
- webapp/channels/src/actions/invite_actions.test.ts
- webapp/channels/src/actions/invite_actions.ts
- webapp/channels/src/i18n/en.json
The error string for when a user is not a guest was wrong. Updated the string to show the correct copy.
Fix https://mattermost.atlassian.net/browse/MM-57861
```release-note
Improve error text when inviting guests to a team.
```
> Fix test for invite modal error

- server/channels/store/sqlstore/user_store.go
We noticed errors on the `RefreshPostStats` job where we had read-only transaction, where we need to guarantee a write. This PR switches to using `GetMasterX()`
```release-note
Fix an issue where the `RefreshPostStats` job could fail
```
> Use GetMasterX() to ensure writeability for the RefreshPostStats job

- webapp/channels/src/components/activity_log_modal/components/__snapshots__/activity_log.test.tsx.snap
- webapp/channels/src/components/activity_log_modal/components/activity_log.test.tsx
- webapp/channels/src/components/activity_log_modal/components/activity_log.tsx
- webapp/channels/src/components/activity_log_modal/components/device_icon.tsx
I decided to work for a bit on getting rid of these functions from a few more places. As much as I wanted to, I had to keep myself from trying to rewrite all the logic for determining the platform so that, instead of passing a bunch of values around, we would just pass a single "platform type" value
```release-note
NONE
```
> Remove t and localizeMessage from components/activity_log_modal

- webapp/channels/src/sass/base/_structure.scss
Fixes a layout issue caused by the [UI Refinements PR](https://github.com/mattermost/mattermost/pull/26272).
Jira: https://mattermost.atlassian.net/browse/MM-58206
If the PR includes UI changes, include screenshots/GIFs.
For an easier comparison of UI changes a table (template below) can be used.
|----|----|
| <img width="1840" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/06cd1d95-b4d0-4fc3-ab71-190ca6327a9d"> | <img width="1840" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/a3926e5f-0d44-4c00-84a4-598a5f808230"> |
This view can be accessed by going to `/preparing-workspace`
```release-note
NONE
```
> MM-58026 Adming onboarding UI fix

- server/channels/app/plugin_api.go
- server/channels/app/plugin_api_test.go
- server/public/plugin/api.go
- server/public/plugin/api_timer_layer_generated.go
- server/public/plugin/client_rpc_generated.go
- server/public/plugin/plugintest/api.go
- server/public/pluginapi/user.go
- server/public/pluginapi/user_test.go
Add a way in PluginAPI to retrieve users by ids
N/A
N/A
```release-note
Added new plugin API endpoint to retrieve a list of users by their ids
```
> PluginAPI: add ability to retrieve users by ids

- server/channels/api4/metrics.go
We use navigator.sendBeacon to send the new metrics since it's recommended for that, but it doesn't let us set custom headers which means that we can't set the CSRF token header that we'd need to pass that check
MM-58263
```release-note
NONE
```
> MM-58263 Remove CSRF check from /api/v4/client_perf

- server/channels/api4/remote_cluster.go
This PR adds a check when updating remote user profile images to ensure the user belongs to the remote making the request.
https://mattermost.atlassian.net/browse/MM-57860
```release-note
Check user belongs to remote when Shared Channels updates a user profile image
```
> MM-57860 - Check user belongs to remote when Shared Channels updates a user profile image

- server/channels/app/session.go
This PR replaces a token comparison with `cryto/subtle.ConstantTimeCompare` to guard against timing attacks.
https://mattermost.atlassian.net/browse/MM-58257
```release-note
Use `ConstantTimeCompare` when comparing tokens for Shared Channels
```
> MM-58257 - Use ConstantTimeCompare when comparing token.

- server/build/docker-compose-generator/main.go
- server/build/docker-compose.common.yml
- server/build/docker-compose.yml
- server/build/docker/grafana/dashboards/home.json
- server/build/docker/grafana/provisioning/datasources/loki.yml
- server/build/docker/prometheus.yml
- server/build/docker/promtail/promtail-local-config.yaml
- server/config.mk
- server/docker-compose.makefile.yml
- server/docker-compose.yaml
Extend our docker compose setup to include Loki (along with promtail), scraping `logs/*.log` to ingest development logs as well as all logs from running containers. While we're in here, teach Prometheus to scrape metrics from Docker containers too.
Right now, Loki isn't a default service, so to enable be sure to define something like this before running the server:
```
ENABLED_DOCKER_SERVICES=postgres inbucket openldap grafana prometheus loki promtail
```
You'll also want to enable logging to disk (as currently implemented, Promtail scrapes this file and sends to Loki), either in `config.json` or via:
```
MM_LOGSETTINGS_ENABLEFILE=true
MM_LOGSETTINGS_FILELEVEL=debug
MM_LOGSETTINGS_FILEJSON=true
MM_LOGSETTINGS_FILELOCATION=logs
```
And do a `make stop-docker start-docker` to reload all the …
> configure Loki for local development

- server/channels/app/metrics.go
- server/public/model/metrics.go
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
Alright, after failing to get metrics working now twice, I've finally tested this locally, so I can confirm that it works. The changes here are:
1. Metric values are now `float64`s which is what Prometheus actually expects.
2. Timestamps are still `int64`s because we don't need sub-millisecond resolution which is only supported by certain browsers.
3. I fixed the version number since there was a mismatch between what we had on the server and client.
MM-58281
```release-note
NONE
```
> MM-58281 Allow client metrics to be floats and round timestamps 

- webapp/channels/src/components/threading/global_threads/global_threads.tsx
- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.test.tsx
- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
- webapp/channels/src/components/threading/global_threads/thread_list/virtualized_thread_list.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/threads.test.js
- webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
- webapp/channels/src/packages/mattermost-redux/src/constants/threads.ts
- webapp/channels/src/utils/constants.tsx
I originally made these changes as part of #26983, but I changed where we took that measurement from a previous version, so these changes were no longer needed for it. Still, I think these are good to include since the extra parameters of `getThreads` made calling it kind of annoying when we always called it with the same values for `perPage`, `userId`, and `teamId`.
```release-note
NONE
```
> Simplify how GlobalThreads fetches threads

- server/channels/api4/metrics_test.go
- server/public/model/metrics.go
- server/public/model/metrics_test.go
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
I missed a case in https://github.com/mattermost/mattermost/pull/27027 where I forgot to round a timestamp. Because there's so many places in the web app code where we need to remember to convert these into floats, I've decided that it'd be better to do this on the server because Go's static typing properly differentiates floats and ints which we can't do in TypeScript.
[MM-58281](https://mattermost.atlassian.net/browse/MM-58281)
```release-note
NONE
```
[MM-58281]: https://mattermost.atlassian.net/browse/MM-58281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-58281 Change performance timestamps to be floats

- webapp/channels/src/components/profile_popover/profile_popover.scss
- webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/index.tsx
- webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/profile_popover_call_button_wrapper.scss
- Added disabled styling to the calls button
- Wrapped it in WithTooltip component
- Will be adding e2e in calls repo
https://mattermost.atlassian.net/browse/MM-58271
```release-note
NONE
```
> [MM-58271] User Profile pop up | Make Call button appear Disabled when user is on active call

- .github/workflows/e2e-fulltests-ci.yml
Support running multiple E2E Tests per-PR, one per `MM_ENV` specification.
Also post back the Workflow and Automation Dashboard URLs as soon as possible in the run.
Tested by running with the following settings:
- Leaving `MM_ENV` empty
- Setting `MM_ENV` to `MM_SUPPORTSETTINGS_HELPLINK=https://about.mattermost.com/default-help/?dummy`
Note that in the future, the `E2E Tests/test` status check (created by runs that leave `MM_ENV` empty) will be the only one required for PR mergeability.
https://mattermost.atlassian.net/browse/CLD-7553
https://mattermost.atlassian.net/browse/CLD-7647
```release-note
NONE
```
> CLD-7553 Implement per-MM_ENV runs, post the E2E test links back to user

- webapp/channels/src/components/root/__snapshots__/root.test.tsx.snap
- webapp/channels/src/components/root/root.tsx
Cherry pick of #27035 on release-9.9.
/cc  @cpoile
```release-note
NONE
```
> Automated cherry pick of #27035

- server/public/model/remote_cluster.go
This PR removes message payloads from RemoteClusterFrame audit logs.
https://mattermost.atlassian.net/browse/MM-58262
```release-note
Removes message payloads from RemoteClusterFrame audit logs.
```
> MM-58262 Remove payload from RemoteClusterFrame audit

- server/channels/app/metrics.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/public/model/metrics.go
- webapp/channels/src/components/threading/global_threads/global_threads.tsx
- webapp/channels/src/components/threading/global_threads_link/global_threads_link.tsx
- webapp/channels/src/utils/performance_telemetry/index.ts
Note that this only captures the time taken by clicking on the Threads item in the LHS, not switching via a hotkey or using the quick switcher. This matches how channel_switch and team_switch are measured as well.
MM-57882
```release-note
Added a metric to track time it takes for the Threads view to load
```
> MM-57882 Add metric for the time it takes to open the Threads list

- webapp/channels/src/components/admin_console/group_settings/group_settings.tsx
- webapp/channels/src/components/admin_console/ip_filtering/save_confirmation_modal.tsx
- webapp/channels/src/components/admin_console/jobs/job_download_link.tsx
- webapp/channels/src/components/analytics/activated_users_card/title.tsx
- webapp/channels/src/components/external_link/__snapshots__/external_link.test.tsx.snap
- webapp/channels/src/components/external_link/external_link.test.tsx
- webapp/channels/src/components/external_link/index.tsx
- webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
- webapp/channels/src/components/invitation_modal/overage_users_banner_notice/overage_users_banner_notice.test.tsx
- webapp/channels/src/components/login/login.tsx
- webapp/channels/src/components/main_menu/learn_about_teams_link.tsx
- webapp/channels/src/components/preparing_workspace/organization_status.tsx
- webapp/channels/src/components/reaction_limit_reached_modal.tsx
- webapp/channels/src/components/search_hint/search_hint.tsx
- webapp/channels/src/components/seats_calculator/consequences.tsx
- webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap
- webapp/channels/src/components/user_settings/notifications/user_settings_notifications.tsx
Marketing has requested that the `utm_content` parameter not be empty - it's driven by the `location` prop on the `ExternalLink` component. This PR removes the optionality of that prop so that it must be passed. This PR also updates existing occurrences of the ExternalLink that were missing the `location` prop. 
https://mattermost.atlassian.net/browse/CLD-7742
```release-note
None
```
> [CLD-7742] Make location prop on ExternalLink component required

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/threads.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/threads.ts
- webapp/channels/src/packages/mattermost-redux/test/test_helper.ts
- We previously had two selector `getThreadsInChannel` and `getThreadItemsInChannel`, the former is not used anywhere and hence its removed. While the latter is renamed to be `getThreadsInChannel` reason for that being it actually returns threads as per the name while the older `getThreadsInChannel` used to return threads id so it should have been called getThreadIdsInChannel. 
- Moved other actions to redux thunk actions
- Added a new test helper for creating thread
https://mattermost.atlassian.net/browse/MM-58108
n/a
```release-note
NONE
```
> [MM-58108] Posts missing channel_id in handleThreadReadChanged, handleAllThreadsInChannelMarkedRead, getThreadItemsInChannel

- webapp/channels/src/components/profile_popover/profile_popover.scss
- webapp/channels/src/components/profile_popover/profile_popover.test.tsx
- webapp/channels/src/components/profile_popover/profile_popover_call_button_wrapper/index.tsx
Withtooltip component supports the element with disabled attribute as well so i just removed the hack we did to make it work previously with aria-disabled.
https://mattermost.atlassian.net/browse/MM-58326
n/a
```release-note
NONE
```
> [MM-58326] Remove aria-disabled for disabled tooltip in calls button following WithTooltip integration

- webapp/channels/src/components/profile_popover/profile_popover.scss
- webapp/channels/src/components/profile_popover/profile_popover.tsx
https://mattermost.atlassian.net/browse/MM-58274
```release-note
NONE
```
> [MM-58274] No side padding in plugins section of user profile popover

- webapp/channels/src/components/admin_console/billing/billing_subscriptions/to_paid_plan_nudge_banner.tsx
- webapp/channels/src/components/admin_console/billing/delete_workspace/progress_modal.tsx
- webapp/channels/src/components/announcement_bar/cloud_trial_announcement_bar/cloud_trial_announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/cloud_trial_ended_announcement_bar/index.tsx
- webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/overage_users_banner/index.tsx
- webapp/channels/src/components/announcement_bar/payment_announcement_bar/index.tsx
- webapp/channels/src/components/cloud_usage_modal/lhs_nearing_limit_modal.tsx
- webapp/channels/src/components/common/hooks/useExpandOverageUsersCheck.ts
- webapp/channels/src/components/common/hooks/useShowAdminLimitReached.ts
- webapp/channels/src/components/common/multi_select_cards/multi_select_card.tsx
- webapp/channels/src/components/downgrade_modal/index.tsx
- webapp/channels/src/components/invitation_modal/overage_users_banner_notice/index.tsx
- webapp/channels/src/components/preparing_workspace/plugins.tsx
- webapp/channels/src/components/pricing_modal/starter_disclaimer_cta.tsx
- webapp/channels/src/components/purchase_modal/icon_message.tsx
- webapp/channels/src/components/start_trial_form_modal/index.tsx
This is part of my mission to eradicate `t` from last week. Most of it is pretty straightforward replacement of `t` with `defineMessage`/`defineMessages`, and I also occasionally removed some use of `localizeMessage` as well, but I'll comment on anything noteworthy below.
https://mattermost.atlassian.net/browse/MM-58324
```release-note
NONE
```
> Remove t from from cloud-related and license-related code

- server/channels/app/metrics.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/public/model/metrics.go
- webapp/channels/src/utils/performance_telemetry/index.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
This value is sort of reflected by the FCP and LCP metrics (both of which will happen after this), but I decided to this to Prometheus since it lets us compare to the existing `page_load` metrics that we've collected with the Rudder/Looker stack
https://mattermost.atlassian.net/browse/MM-58359
```release-note
Add page load time to client performance metrics
```
> MM-58359 Add page_load to Prometheus metrics

- api/v4/source/teams.yaml
Adds missing query parameters for GetTeamMembers API Documentation.
Fixes https://mattermost.atlassian.net/browse/MM-58348
```release-note
NONE
```
> MM-58348 Add missing query parameters to GetTeamMembers API doc

- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/i18n/en.json
Adds the configuration setting `ServiceSettings.MaximumPayloadSizeBytes` to the Environment/Web Server system console page.
Fixes https://mattermost.atlassian.net/browse/MM-55980
```release-note
NONE
```
> Add ServiceSettings.MaximumPayloadSize to SystemConsole

- webapp/channels/src/components/__snapshots__/setting_picture.test.tsx.snap
- webapp/channels/src/components/setting_picture.tsx
This setting was narrower than other settings which meant there was not enough space for the three buttons in it which caused them to stack up. It's now the same width as any other setting which uses `SettingItemMax`
MM-58116
```release-note
Increased the width of the profile picture setting to match other user settings
```
> MM-58116 Increase width of profile picture setting

- webapp/channels/src/components/announcement_bar/__snapshots__/announcement_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx
- webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/sass/base/_structure.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
Some users have a requirement to always display an admin-created banner to all users, at all times. This was problematic when a system banner was displayed to administrators, as those would take precedence over the administrator-set ones. This PR makes it so that any banners set by the administrators have their own placement, below that of any system banners. 
Note: this PR makes no changes to the behaviour of existing banners - they will still be displayed in the order of the announcement_bar_controller, it just added a special section to the CSS grid to display the administrator-configured announcements. 
https://mattermost.atlassian.net/browse/CLD-7724
Before:
(An admin banner is configured, it's just not visible because it's behind the 3 days left in trial banner)
After
Without a …
> [CLD-7724] Allow admin-set announcement banners to stack below system ones

- server/channels/store/sqlstore/channel_store.go
- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_details.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx
- webapp/channels/src/i18n/en.json
Previously both Teams and Channels had the same text…so it all got updated…only the Teams text should have been changed.
This PR reverts the changes to the channels text.
Fixes https://mattermost.atlassian.net/browse/MM-58479
```release-note
NONE
```
> MM-58479 - Revert text changes on channel archive.

- webapp/channels/src/components/threading/global_threads/global_threads.tsx
This fixes an issue I introduced because of a copy-paste typo in https://github.com/mattermost/mattermost/pull/26984 where switching to the Unreads tab in the Threads view wouldn't load anything unless you first selected a thread in the list to view.
I would've liked to add a unit test for this, but unfortunately, the threads code is extremely unfriendly to being tested, so I gave up after an hour or so fighting with that.
https://mattermost.atlassian.net/browse/MM-58459
No release note for this since the previous PR hasn't shipped yet
```release-note
NONE
```
> MM-58459 Fix unread threads not always being loaded correctly

- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
- server/channels/app/web_broadcast_hooks.go
- server/channels/app/web_broadcast_hooks_test.go
When the websocket connection is closed at the client, the server still keeps the connection object alive and will process `POSTED` events for that connection, even if they go nowhere. We cleanup the connections eventually, but in that time we are counting notifiable events still that will never get an ACK.
This PR flips the `PostedAck` flag off on the connection at unregistry so that we don't expect ACKs back for the POSTED events that we send. This should improve the metrics a bit since we were adding measuring errors here.
https://mattermost.atlassian.net/browse/MM-58500
```release-note
NONE
```
>  [MM-58500] Turn off PostedAck when the connection is no longer registered

- server/channels/api4/user_test.go
- server/channels/app/oauth_test.go
- server/channels/app/session.go
- server/channels/app/user.go
This PR ensures that remote/synthetic users cannot create sessions or reset password.
https://mattermost.atlassian.net/browse/MM-58245
https://mattermost.atlassian.net/browse/MM-58255
```release-note
Ensures that remote/synthetic users cannot create sessions or reset password.
```
> MM-58349 Don't allow remote user to create sessions or reset password

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/public/model/shared_channel.go
Cherry pick of #27143 on release-9.9.
/cc  @wiggin77
```release-note
NONE
```
> Automated cherry pick of #27143

- webapp/channels/src/sass/layout/_markdown.scss
A few years ago, we changed the CSS of numbered lists so that the numbers for each item were right aligned and always showed each digit of the number properly. We did that by making each row render as a row of a table and then adding our own number using `:before` which then rendered as a column of the table.
For whatever reason, tables seem to have different behaviour for breaking words when wrapping text, so long words with no spaces (or long lines of CSV data like in the ticket) wouldn't be broken in the middle. Manually specifying the `word-break` behaviour on the text in the row (but not the fake item number) fixes that.
MM-58354
Fixes #27104 
```release-note
Fixed incorrect wrapping of long words in numbered lists
```
> MM-58354 Fix numbered Markdown lists not wrapping long words

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/public/model/shared_channel.go
Cherry-pick MM-57867 into release-9.5
This PR addresses an issue where sharing a channel can result in a channel being deleted if the invite errors.  Specifically,  A remote can send an invite with a channel ID that exists on the local server, then send that same invite again, which errors because of a constraint violation and permanently deletes the local channel.
As a consequence of this fix, new channels are always created on servers that are invited to a shared channel, which fixes other cases. See tickets below.
https://mattermost.atlassian.net/browse/MM-57867
https://mattermost.atlassian.net/browse/MM-57869
https://mattermost.atlassian.net/browse/MM-57871
```release-note
Fixes issue where sharing a channel can result in a channel being deleted if the invite errors.
```
> Cherry-pick MM-57867 into release-9.5

- server/channels/utils/testutils/static_config_service.go
- server/platform/services/imageproxy/atmos_camo.go
- server/platform/services/imageproxy/atmos_camo_test.go
- server/platform/services/imageproxy/imageproxy.go
- server/platform/services/imageproxy/imageproxy_test.go
- server/platform/services/imageproxy/local.go
- server/public/model/builtin.go
At some point, we changed the image proxy to store a parsed URL instead of getting the site URL directly from the config each time, but it didn't update that stored URL correctly when the config is updated which leads to some double proxying if a server's site URL is changed without restarting the server. This fixes that, and I also fixed a related bug where the options for the atmos/camo proxy aren't always updated. Hopefully, this solves the rare double proxying bugs that get reported occasionally.
I also made it so that neither of the image proxy backends directly reference `proxy.ConfigService` any more to reduce the chance that this sort of bug might happen again. I would've removed `proxy.ConfigService` entirely, but we needed it to remove remove the image proxy's config listener. …
> MM-58275 Ensure image proxy site URL is updated when that changes

- webapp/channels/src/sass/layout/_sidebar-left.scss
Icons in the LHS are being improperly bolded in unread or untouched states. This removes the unneeded bold style for icons in the LHS to prevent rendering issues (primarily noticeable in Safari).
Jira https://mattermost.atlassian.net/browse/MM-58499
Notice the difference with the plus icon for the 'Add channels' item in the LHS
|----|----|
| <img width="329" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/8d8c822b-b9ee-4f64-92fc-99ba9b65d55b"> | <img width="330" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/5d48aab0-7070-4f53-95d3-ab5bd1d010ac"> |
```release-note
NONE
```
> MM-58499 Fix bolded icon issue in LHS

- webapp/channels/src/entry.tsx
- webapp/channels/webpack.config.js
The initial JS should have high priority regardless of other chunks. So only the initial chunk along with remote entry are not defered with HTMLWebpackPlugin as this plugin is responsible for rending the initial HTML page, rest other chunks are loaded by webpack in deferred without any changes as they should be loaded. This should marginally improve and parsing the initial scripts.
After
```html
<script src="/static/main.2ef0b4d9e5e308934fe0.js"></script>
<script src="/static/remote_entry.js?bt=1717453929387"></script>
```
Before
```html
<script defer="defer" src="/static/main.4bfd7c2a87a6b0a05c35.js"></script>
<script defer="defer" src="/static/remote_entry.js?bt=1717212713679"></script>
```
https://mattermost.atlassian.net/browse/MM-58463
```release-note
NONE
```
> [MM-58463] Remove defer for main/entry JS scripts

- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
Cherry-pick https://github.com/mattermost/mattermost/pull/27203 into release-9.5
This PR addresses an issue where a check is needed to ensure that a user update comes from the remote that owns the user.  This ensures remotes cannot update users from other remotes, including setting the user's remoteID so that the user appears to originate from somewhere else.
https://mattermost.atlassian.net/browse/MM-58253
https://mattermost.atlassian.net/browse/MM-58249
```release-note
Ensures remotes cannot update users belonging to different remotes.
```
> MM-58252 cherry-pick into release 9.5

- server/channels/app/server.go
This check was removed in error, causing some workspaces to receive emails in Cloud about license expiration when they shouldn't have. 
```release-note
NOne
```
> Add check to not send license expiration email when in Cloud

- server/channels/app/server.go
Cherry pick of #27308 on release-9.9.
```release-note
NONE
```
> Automated cherry pick of #27308

- server/channels/api4/cloud.go
- server/i18n/en.json
- server/public/model/config.go
Cherry pick of #26070 on release-9.5.
```release-note
NONE
```
> Automated cherry pick of #26070

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
- server/public/model/reaction.go
This PR ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
Also ensures that posts and reactions are only modified/deleted by the remote that owns them.
A new store API was needed for reactions to ensure reactions can only be deleted by the remote that owns it.
https://mattermost.atlassian.net/browse/MM-58577
https://mattermost.atlassian.net/browse/MM-58579
```release-note
Ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
```
> MM-58577  Check remote ownership for posts and reactions

- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
These tests seem to fail randomly sometimes such as in https://github.com/mattermost/mattermost/actions/runs/9355062430/job/25749374384#step:4:1125. I thought that was due to other tests failing, but that doesn't seem to be the case based on the log I linked there.
I can't get these to fail reliably, but I think the issue is that the tests are affecting each other because of all the async stuff they have happening, so I changed this to better isolate them from each other which should hopefully fix this issue
```release-note
NONE
```
> Improve isolation of PerformanceReporter tests to increase their stability

- server/channels/app/busy_test.go
- server/channels/app/platform/busy_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
- server/channels/testlib/cluster.go
- server/einterfaces/cluster.go
- server/einterfaces/mocks/ClusterInterface.go
- server/public/model/cluster_message.go
We were setting the user status to offline without
checking for connections on other nodes in a cluster.
Now we implement a request-response mechanism for the whole
cluster and we check that before setting a user to offline.
https://mattermost.atlassian.net/browse/MM-57153
```release-note
Fix a bug where the user status would incorrectly be set to offline
without checking for connections in other nodes in an HA cluster.
```
Co-authored-by: Ibrahim Serdar Acikgoz <serdaracikgoz86@gmail.com>
Co-authored-by: Ben Schumacher <ben.schumacher@mattermost.com>
> [9.5 CP]MM-57152: Get webconn count from the whole cluster (#26813)

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
- server/public/model/reaction.go
Cherry-pick MM-58577 into release-9.9
This PR ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
Also ensures that posts and reactions are only modified/deleted by the remote that owns them.
A new store API was needed for reactions to ensure reactions can only be deleted by the remote that owns it.
https://mattermost.atlassian.net/browse/MM-58577
https://mattermost.atlassian.net/browse/MM-58579
https://mattermost.atlassian.net/browse/MM-58251
```release-note
Ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
```
> MM-58577 cherry-pick to release 9.9

- server/platform/services/sharedchannel/sync_recv.go
This change makes sure that the original username and email are always preserved when creating a user coming from a remote cluster.
https://mattermost.atlassian.net/browse/MM-58575
```release-note
NONE
```
> Updates remote user creation process to preserve username and email

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/platform/services/sharedchannel/mock_AppIface_test.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_recv.go
This PR ensures that when accepting DM channel invites for Shared Channels, a check is made to ensure the users can see each other (allowed to DM).
https://mattermost.atlassian.net/browse/MM-57873
```release-note
Check user visibility when accepting DM channel invites for Shared Channels.
```
> MM-57873 Check user visibility when accepting channel invites for DMs

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
- server/public/model/reaction.go
Cherry-pick MM-58577 into release-9.8
This PR ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
Also ensures that posts and reactions are only modified/deleted by the remote that owns them.
A new store API was needed for reactions to ensure reactions can only be deleted by the remote that owns it.
https://mattermost.atlassian.net/browse/MM-58577
https://mattermost.atlassian.net/browse/MM-58579
https://mattermost.atlassian.net/browse/MM-58251
```release-note
Ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
```
> MM-58577 cherry-pick to release 9.8

- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/reaction_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/ReactionStore.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/sharedchannel/sync_recv.go
- server/platform/services/sharedchannel/util.go
- server/public/model/reaction.go
Cherry-pick MM-58577 into release-9.5
This PR ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
Also ensures that posts and reactions are only modified/deleted by the remote that owns them.
A new store API was needed for reactions to ensure reactions can only be deleted by the remote that owns it.
https://mattermost.atlassian.net/browse/MM-58577
https://mattermost.atlassian.net/browse/MM-58579
https://mattermost.atlassian.net/browse/MM-58251
```release-note
Ensures that posts and reactions can only be added via sync when coming from a remote that the target channel is shared with and done on behalf of a remote user owned by the remote. 
```
> MM-58577 cherry-pick to release 9.5

- webapp/channels/src/sass/components/_buttons.scss
- webapp/channels/src/sass/components/_modal.scss
- webapp/channels/src/sass/layout/_headers.scss
Fixes an issue where the spacing between the icon buttons (members, pinned, files) was too wide in the channel header.
Jira https://mattermost.atlassian.net/browse/MM-58685
|----|----|
| <img width="457" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/b7736fd4-3a4c-41be-a348-fed04bb5d2f4"> | <img width="440" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/bf2f0b53-d78f-4dbd-901f-ea04076e1252"> |
```release-note
NONE
```
> MM-58685 Fix Channel Header Icon Button Spacing

- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
Fixes the 'followed threads' label and prevents it from wrapping on 2 lines.
Jira https://mattermost.atlassian.net/browse/MM-58528
|----|----|
| <img width="275" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/72a8b3bd-3b66-45d8-9610-e0969715ed40"> | <img width="295" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/8a03a1e9-840c-4fd1-b307-ebfe2c3a6787"> |
```release-note
NONE
```
> MM-58528 Fixed wrapping button label for followed threads

- webapp/Makefile
Currently, if you're building under aarch64 and have cppflags set in your environment as such:
```
CPPFLAGS="-O2 -Wall -fomit-frame-pointer -march=armv8-a -mtune=neoverse-n1 -Wp,-D_FORTIFY_SOURCE=3"
```
This will result in `-DPNG_ARM_NEON_OPT=0` being improperly applied:
```
CPPFLAGS="-O2 -Wall -fomit-frame-pointer -march=armv8-a -mtune=neoverse-n1 -Wp,-D_FORTIFY_SOURCE=3 " -DPNG_ARM_NEON_OPT=0""
```
As a result, when npm install is ran, it will fail. To fix this, we remove the quotes around the appended cppflags
```release-note
NONE
```
> fix(webapp/Makefile): Drop quotes around appended cppflags

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
This PR is a follow-up to https://github.com/mattermost/mattermost/pull/27143 handling another edge case.
DM's can possibly collide in channel name due to their having a channel name based on user ids.  When DMs are created the app first checks if the name collides and returns the existing DM channel with that name.  It is possible to construct a shared channel invitation that uses two existing user ids that already have a DM channel.  This PR detects that condition and ensures no channels get deleted on clean-up.
**Note:**  the release note is already provided by https://github.com/mattermost/mattermost/pull/27143
https://mattermost.atlassian.net/browse/MM-57867
```release-note
NONE
```
> MM-57867 Don't delete existing DM on invitation error

- server/config/client.go
- server/public/model/feature_flags.go
This has soaked for long enough that we're confident that this can be enabled for everyone with Prometheus metrics enabled. I've also made sure that the client doesn't report results to the server if the Prometheus metrics themselves are disabled since I forgot to do that previously.
MM-58823
```release-note
Removed feature flag which prevented enabling MetricsSettings.EnableClientMetrics
```
> MM-58823 Remove feature flag from client metrics

- server/.gitignore
- server/channels/app/license.go
- server/channels/app/platform/license.go
- Add SAML private key to `.gitignore`
- Remove unused constants
N/A
N/A
```release-note
NONE
```
> Add saml private key to gitignore, remove unused constants

- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/channelinvite_test.go
- server/platform/services/sharedchannel/mock_AppIface_test.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_recv.go
This PR cherry-picks https://github.com/mattermost/mattermost/pull/27357 and [the](https://github.com/mattermost/mattermost/pull/27331) into release-9.7 
https://mattermost.atlassian.net/browse/MM-57867
https://mattermost.atlassian.net/browse/MM-57873
```release-note
Check user visibility when accepting DM channel invites for Shared Channels.
```
> Cherry-pick MM-57867 into release 9.7

- server/tests/test-search.md
Updated link preview test URL from www.dropbox.com to www.github.com/mattermost, as the dropbox link no longer shows a preview and the github link still does. The github link is likely going to be more stable for us to use in testing over time.
> Update link preview URL in test-search.md

- server/channels/app/metrics.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/public/model/metrics.go
- webapp/channels/src/utils/performance_telemetry/index.ts
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
This cherry-picks both #27159 to re-add the Load Event End/page_load metric to the client metrics and #27396 to fix metric reports being rejected for being outdated
https://mattermost.atlassian.net/browse/MM-58855
```release-note
Added page load time to client performance metrics
Fixed web app performance reports being marked as outdated after the user's computer wakes up from sleep
Increased range of LCP metrics that can be measured
Increased range of Load Event End metrics that can be measured
```
> MM-58855 Cherry pick client metrics fixes

- server/Makefile
- Dot release to fixe a bug: https://github.com/mattermost/mattermost-plugin-calls/pull/792
- https://mattermost.atlassian.net/browse/MM-59037
```release-note
Prepackage Calls version [v0.28.2](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.28.2)
```
Calls [v0.28.2](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.28.2)
> [MM-59037] Prepackage calls v0.28.2 for v9.10

- server/enterprise/metrics/metrics.go
Bumping this up since we've had 30 or more second times as the P99 for this reported using the Rudder/Looker telemetry.
This change will also be made in 9.9.1 by https://github.com/mattermost/mattermost/pull/27415
MM-59033
```release-note
Increased range of Load Event End metrics that can be measured
```
> MM-59033 Increase maximum bucket size for Load Event End metric

- server/platform/services/sharedchannel/channelinvite.go
Fixes the mismatch in the amount of return values in the `handleChannelCreation` method caused by a bad merge.
```release-note
NONE
```
> Fix not enough return values in handleChannelCreation

- webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap
- webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx
- webapp/channels/src/components/edit_channel_header_modal/index.ts
- webapp/channels/src/components/textbox/textbox_links.tsx
- webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx
- webapp/channels/src/utils/constants.tsx
This should have been deleted when we were cleaning up flags for advanced text editor in https://github.com/mattermost/mattermost-webapp/pull/11031 And this flag is currently only used to preview channel header. So i cleaned up this flag and removed it.
https://mattermost.atlassian.net/browse/MM-59059
n/a
```release-note
NONE
```
> [MM-59059] Re enable markdown preview for channel header in user advanced settings

- webapp/channels/src/components/header_footer_route/header.scss
- webapp/channels/src/components/header_footer_route/header.tsx
- webapp/channels/src/components/signup/signup.scss
Fixes an issue with the positioning of the back button on the signup screen when the free edition and custom site name display.
Also fixes an issue with the title wrapping unnecessarily on to 2 lines on mobile screens
**Testing notes**
The following cases need to be considered when testing:
- free edition, no custom site name
- free edition, with custom site name
- licensed edition, no custom site name
- licensed edition, with custom site name
Jira: https://mattermost.atlassian.net/browse/MM-58802
|----|----|
| <img width="458" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/ae082646-a71d-4ded-b73b-d83d1ad227dd"> | <img width="465" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/0e2a1ef7-5509-4b53-be00-5517b9d9cfae"> …
> MM-58802 Fix overlapping back button

- .github/workflows/e2e-fulltests-ci.yml
- .github/workflows/e2e-tests-ci-template.yml
- e2e-tests/.ci/.e2erc
- e2e-tests/.ci/report.publish.sh
- e2e-tests/.ci/server.cloud_init.sh
- e2e-tests/.ci/server.cloud_teardown.sh
- e2e-tests/README.md
- e2e-tests/cypress/save_report.js
This PR adds support for daily master/cloud E2E tests in GHA.
- The `REPORT_TYPE` input will decide how the test will behave.
- In case of daily tests (`MASTER`, `MASTER_UNSTABLE`, `CLOUD` and `CLOUD_UNSTABLE`), the `mattermostdevelopment/mattermost-enterprise-edition:master` image is automatically picked, no matter the given `commit_sha` or `PR_NUMBER` you specified at triggering time
- Zephyr reporting is implemented
The triggering of this job will be done by argo-events.
https://mattermost.atlassian.net/browse/CLD-5704
```release-note
NONE
```
> CLD-5704 Migrate daily master/cloud tests

- webapp/channels/src/utils/performance_telemetry/reporter.ts
Certain browser settings can cause this API to be disabled. For whatever reason, instead of just returning false to say that nothing was sent which the API is already supposed to do, Firefox decides to just blank it out so that an error occurs if you try to call it. Thanks, Firefox!
MM-58777
```release-note
Fix an error caused by performance telemetry when using Firefox with `beacon.enabled` set to false
```
> MM-58777 Confirm that sendBeacon exists before trying to use it

- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
I've already fought with these tests being flaky twice before, so I've given up trying to check the exact values of these because they keep causing CI to periodically fail
NONE
```release-note
NONE
```
> Change PerformanceReporter tests to not check exact values for timestamps

- webapp/channels/src/components/product_notices_modal/__snapshots__/product_notices.test.tsx.snap
- webapp/channels/src/components/product_notices_modal/product_notices_modal.tsx
MM-58755 - Fixing inproduct notices spacing
MM-58449 - Fixing CRT modal
Jira https://mattermost.atlassian.net/browse/MM-58755
Jira https://mattermost.atlassian.net/browse/MM-58449
```release-note
NONE
```
> MM-58755 - Fixing inproduct notices spacing

- tools/mmgotool/commands/i18n.go
Running `make i18n-extract` on a en.json file
with bad JSON will just wipe off all keys instead
of throwing the error. This is very confusing
and can lead to a lot of time wasted because
there's no indication that the JSON is incorrect.
Fixing this.
```release-note
NONE
```
> Bubble up parsing error from en.json

- webapp/channels/src/utils/performance_telemetry/reporter.ts
Cherry-pick of https://github.com/mattermost/mattermost/pull/27458 to 9.9
```release-note
Fix an error caused by performance telemetry when using Firefox with `beacon.enabled` set to false
```
> MM-58777 Confirm that sendBeacon exists before trying to use it (9.9)

- server/channels/api4/team.go
- server/channels/api4/team_test.go
It is possible to remove `PermissionInviteUser` from a role such as System Manager. However, the `regenerateTeamInviteId` only checks for `PermissionManageTeam`.  This PR adds a check for `PermissionInviteUser` as well, before regenerating.
Fixes https://mattermost.atlassian.net/browse/MM-58557
```release-note
Added additional permission check before regenerating invite id.
```
> MM-58557 - Add Permission check to regenerate invite id

- webapp/channels/src/components/app.tsx
- webapp/channels/src/components/channel_layout/channel_controller.test.tsx
- webapp/channels/src/components/channel_layout/channel_controller.tsx
- webapp/channels/src/components/root/index.ts
- Removed redundant index route for Root.tsx
- Moves CRT watcher to deeper component
https://mattermost.atlassian.net/browse/MM-59061
```release-note
NONE
```
> [MM-59061] Remove redundant index route for Root.tsx

- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap
- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.scss
- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
- webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_sequence/keyboard_shortcuts_sequence.scss
General layout and style improvements to the keyboard shortcuts modal along with a fix the the way the shortcut keys were displaying.
Jira https://mattermost.atlassian.net/browse/MM-59047
|----|----|
| <img width="1202" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/647dca16-738e-4084-9bf3-f572f4726ac0"> | <img width="1208" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/2c03a8a9-a443-4457-b45c-71147621d898"> |
| <img width="877" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/fdf91681-d761-4314-97c5-cc1e1e015f74"> | <img width="877" alt="image" src="https://github.com/mattermost/mattermost/assets/2040554/72baaea2-d655-450a-a45d-141f30197fce"> |
```release-note
UI Improvements to the …
```
> MM-59047 Keyboard Shortcuts Modal Improvements

- api/package-lock.json
- api/package.json
Pins `whatwg-url` npm (from 5.0.0) to 12.0.0+ in `/api` to suppress warnings from `whatwg-url` 5.0.0 (through 11.0.0) on `make build` or `make run` in /api with Node.js 21.0+ (including 22.x).
n/a
Note: these warnings do not happen on `make build` in `/api` with Node.js LTS 20 or below.
**Before** (`cd api && make build`)
```
Fetching Playbooks OpenAPI spec
cd playbooks && node --trace-deprecation extract.js
(node:36815) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
fetched Playbooks OpenAPI spec
wrote file paths.yaml
wrote file schemas.yaml
wrote file responses.yaml
wrote file securitySchemes.yaml
(node:36814) [DEP0040] DeprecationWarning: The …
```
> chore(deps): pin whatwg-url to 12.0.0+ in /api

- .github/workflows/e2e-fulltests-ci.yml
Today's daily test all ran correctly, but [one of them](https://github.com/mattermost/mattermost/actions/runs/9689742488) (`CLOUD_UNSTABLE`) ran before [its previous one](https://github.com/mattermost/mattermost/actions/runs/9689475883) could be finished (`MASTER_UNSTABLE`). The current configuration of our `concurrency` directive in the workflow meant that the previously running job was canceled.
This PR configures it so that only workflows of the same  `REPORT_TYPE` can cancel each other, so that master-unstable and cloud-unstable tests can have a small overlap time as well.
https://mattermost.atlassian.net/browse/CLD-5704
```release-note
NONE
```
> CLD-5704 Fix concurrency for daily tests

- webapp/channels/src/components/admin_console/admin_definition.tsx
When I removed the feature flag, I forgot to remove the one place it's used in the system console, so the setting is currently never shown to the user
MM-59254
```release-note
Fix EnableClientMetrics setting not being available in the system console
```
> MM-59254 Fix EnableClientMetrics setting being hidden

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss
- webapp/channels/src/components/announcement_bar/__snapshots__/text_dismissable_bar.test.tsx.snap
- webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx
- webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx
- webapp/channels/src/components/status_dropdown/status_dropdown.scss
- webapp/channels/src/sass/components/_announcement-bar.scss
It turns out that we've been using the compass-icons font incorrectly in some parts of the announcement bar for quite a while now because the unicode values that we used for a couple of icons are incorrect. This fixes that by changing them by having them use one the classes generated by that library.
I also cleaned up a few other places in the code where we referenced the font unnecessarily, and I slightly tweaked the style of a few icons to be consistent. The only notable place where this has an effect is that it slightly shrinks the icon on the admin-configured announcement bar to match other icons
MM-58854
```release-note
NONE
```
> MM-58854 Update how Compass icons are referenced by AnnouncementBar 

- api/package.json
In accordance with https://github.com/mattermost/mattermost-api-reference/pull/735, this updates metadata information in terms of `mattermost-api-reference` npm package.
n/a
n/a
```release-note
NONE
```
> chore: update package metadata for API reference

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
Requires a user to have `edit_other_users` permission in order to mark anothers posts as read.
Fixes https://mattermost.atlassian.net/browse/MM-58837
```release-note
None
```
> MM-58837 - Require permission to user to mark channels as read

- server/cmd/mmctl/commands/root.go
- server/cmd/mmctl/commands/root_test.go
- server/cmd/mmctl/printer/printer.go
When `mmctl` panics, the panic message and the stack trace should be output. However, these lines never printed because the printer was not flushed. This PR fixes that.
I also took the time to add a test that covers the printer output.
https://mattermost.atlassian.net/browse/MM-58796
```release-note
Print panic message when mmctl panics
```
> [MM-58796] Print panic message when mmctl panics

- server/channels/app/migrations.go
Fix potential for panic in app migrations
https://mattermost.atlassian.net/browse/MM-59274
```release-note
NONE
```
> [MM-59274] Potential for panic in app migrations

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
Cherry pick of #27468 on release-9.5.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #27468

- server/Makefile
- server/build/release.mk
- server/cmd/mmctl/commands/plugin_e2e_test.go
Plugin store is gradually migrated
from: 
- https://plugins-store.test.mattermost.com 
to:
- https://plugins.releases.mattermost.com
We reflect that change here
Note: Currently both CDN's are working as expected, to facilitate the migration. Upon succesfull migration, https://plugins-store.test.mattermost.com will be decommissioned
https://mattermost.atlassian.net/browse/CLD-7958
```release-note
NONE
```
> [chore] migration of plugin-store

- server/channels/store/sqlstore/channel_bookmark_store.go
- server/channels/store/storetest/channel_bookmark.go
When deleting a file channel bookmark, also delete file properly.
- https://mattermost.atlassian.net/browse/MM-56774
```release-note
NONE
```
> MM-56774: Delete file along with bookmark

- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql
- server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql
- server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql
- server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql
- webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap
- webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx
- webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap
- webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
- webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
* tie create_post and upload_file permissions together
* update tests
* update file name
* update migration to do in batches
* Update 000122_remove_upload_file_permission.up.sql
* fix formatting
* simplify migrations, fix regex issue
* update file names for recent merge
---------
(cherry picked from commit 71c25fb316cfcda9b9af09df9318e153d5e7e66a)
```release-note
NONE
```
> MM-58525 Fix upload file permissions (#27298)

- server/channels/api4/role.go
- server/channels/api4/role_test.go
There is a set of 3 "role" permissions that cannot be assigned or removed from roles. Making them only available to System Administrators. They are `PermissionSysconsoleWriteUserManagementSystemRoles.Id`, `PermissionSysconsoleReadUserManagementSystemRoles.Id`, `PermissionManageRoles.Id`. This allows only System Admins to Manage Roles, that permission cannot be given to any other Role. 
This PR adds the `manage_system` permission to that list. The only way a user should be able to obtain the permission is be made a system admin.
Fixes https://mattermost.atlassian.net/browse/MM-58771
```release-note
NONE
```
> MM-58771 - Make manage_server permission, non updatable

- server/channels/api4/remote_cluster_test.go
Skips flaky test on the remote cluster API
```release-note
NONE
```
> Skips flaky test on the remote cluster API

- server/channels/api4/remote_cluster_test.go
- server/channels/store/sqlstore/remote_cluster_store.go
> Orders results of the GetAll remote clusters store method

- server/Makefile
Prepackage Github plugin 2.3.0
```release-note
Prepackage Github plugin version [v2.3.0](https://github.com/mattermost/mattermost-plugin-github/releases/tag/v2.3.0).
```
Prepackage Github plugin version [v2.3.0](https://github.com/mattermost/mattermost-plugin-github/releases/tag/v2.3.0).
> Bump prepackage Github plugin version to 2.3.0

- server/channels/app/product_notices.go
- server/channels/app/product_notices_test.go
While debugging a test failure in https://github.com/mattermost/mattermost/pull/27573, I noticed that `TestNoticeValidation` does update the global variable `model.CurrentVersion`, which caused my tests to fail. Changing the global state is an anti-pattern as the makes tests unreliable and unable to parallelize them.
This PR replaces the write to `model.CurrentVersion` will a read and a local write.
NONE
```release-note
NONE
```
> Don't modify global variables in TestNoticeValidation

- webapp/channels/src/components/admin_console/workspace-optimization/dashboard.scss
Adds hover states for expandable cards in the Workspace Optimization page for better affordance when they are interactive. Also tweaked a few styles:
- Updated font for 'Overall Score' to better match styles for headings.
- Removed white background to be more consistent with other views in the console.
- Add hover state to expandable cards.
Jira: https://mattermost.atlassian.net/browse/MM-59345
|----|----|
| ![2024-07-05 16 35 29](https://github.com/mattermost/mattermost/assets/2040554/7cee15ac-1882-44e5-9c78-e2ffdd98c669) | ![2024-07-05 16 34 56](https://github.com/mattermost/mattermost/assets/2040554/430bd1f3-1285-4cc0-9f6d-326105b136e5) |
```release-note
NONE
```
> MM-59345 add hover states expandable containers in workspace optimization page

- .github/workflows/e2e-fulltests-ci.yml
- .github/workflows/e2e-tests-ci-template.yml
- e2e-tests/.ci/server.generate.sh
- e2e-tests/.ci/server.start.sh
This PR adds support for E2E release testing from Github Actions:
- Compute which git ref to test based on `REPORT_TYPE`:
* `NONE` and `PR` will use either `inputs.PR_NUMBER` or `inputs.ref`, in order of preference.
* Daily tests will always test `master` branch.
* Release tests will expect a tag in the `inputs.ref` argument. It'll be used to also select the docker image, and construct the corresponding release branch name
- Add an indirection between `inputs.REPORT_TYPE` and the actual `REPORT_TYPE` used in the job (because `RELEASE` and `RELEASE_CLOUD`, used to distinguish the test filter, will both need to use the `REPORT_TYPE=RELEASE` string)
- Compute the `SERVER_IMAGE` variable outside of the E2E test template, so that it may be fully controlled. If unspecified, e.g. for smoketests, …
> Support release testing

- server/platform/services/sharedchannel/sync_recv.go
This PR prevents a username or email to be update sync'ed from a remote.  The real (updated) username and email are stored in props for display purposes.
**Release note is covered by a previous PR.**
https://mattermost.atlassian.net/browse/MM-58245
```release-note
NONE
```
> MM-58245  Don't allow patching real email or username for remote users

- webapp/channels/src/components/sidebar/sidebar_list/__snapshots__/sidebar_list.test.tsx.snap
- webapp/channels/src/components/sidebar/sidebar_list/sidebar_list.tsx
The problem was, the `react-custom-scrollbars` seems to not work consistent across browsers with `auto-hide` feature. I added my own event that does the same effect as on firefox, but is also working now for others in the same way. I did not found other solutions that would have same effect by just using `Scrollbar` component interface.
Please test on safari as I don't have mac at home :) But I'm pretty sure that should work.
Small note: The lib itself is super old and not maintained for over 7 years. There is forked version called `react-custom-scrollbars-2` I checked it quickly and seems like it does not break anything, if you are up for it I could do other PR with update. Newer version last publish is 2y ago but it fixes some bugs. …
> MM-58351 Fix showing LHS scrollbar when moving mouse over on chrome and safari

- server/channels/app/support_packet.go
- server/channels/app/support_packet_test.go
- server/einterfaces/ldap.go
- server/einterfaces/mocks/LdapInterface.go
If fetching the LDAP vendor name fails, the Support Packet generation now correctly includes the error in `warning.txt`. If no vendor name is found, the Support Packet lists them as `unknown`.
https://mattermost.atlassian.net/browse/MM-59350
```release-note
Include LDAP vendor errors in Support Packet
```
> [MM-59350] Include LDAP vendor errors in Support Packet

- server/Makefile
Updating copilot plugin to 0.8.3
```release-note
Updating copilot plugin prepackaged version [v0.8.3](https://github.com/mattermost/mattermost-plugin-ai/releases/tag/v0.8.3).
```
Mattermost Copilot [v0.8.3](https://github.com/mattermost/mattermost-plugin-ai/releases/tag/v0.8.1).
> Update Copilot plugin prepackaged version to 0.8.3

- webapp/channels/src/components/post_emoji/post_emoji.test.tsx
- webapp/channels/src/components/post_emoji/post_emoji.tsx
- webapp/channels/src/utils/emoticons.tsx
- webapp/channels/src/utils/message_html_to_component.test.tsx
- webapp/channels/src/utils/message_html_to_component.tsx
The emoji code passes a lower cased version of the emoji's name into `PostEmoji` for lookup, so I changed it to also pass the original text into `PostEmoji` as a fallback for when the emoji can't be found.
master version: https://github.com/mattermost/mattermost/pull/27603
MM-59099
```release-note
Ensured text that looks like an emoji but isn't renders in its original case
```
> MM-59099 Show invalid emoji text with its original case (9.5)

- webapp/channels/src/components/post_emoji/post_emoji.test.tsx
- webapp/channels/src/components/post_emoji/post_emoji.tsx
- webapp/channels/src/utils/emoticons.tsx
- webapp/channels/src/utils/message_html_to_component.test.tsx
- webapp/channels/src/utils/message_html_to_component.tsx
The emoji code passes a lower cased version of the emoji's name into `PostEmoji` for lookup, so I changed it to also pass the original text into `PostEmoji` as a fallback for when the emoji can't be found.
9.5 version: https://github.com/mattermost/mattermost/pull/27604
MM-59099
```release-note
Ensured text that looks like an emoji but isn't renders in its original case
```
> MM-59099 Show invalid emoji text with its original case

- server/cmd/mmctl/commands/webhook.go
- server/cmd/mmctl/commands/webhook_test.go
`mmctl webhooks list` was effectively limited to `200` results despite asking for more, as the server restricts the response accordingly. Leverage pagination support to fix this.
Fixes: https://mattermost.atlassian.net/browse/MM-58756
```release-note
Fixed `mmctl webhooks list` to paginate past 200 results.
```
> MM-58756: paginate webhooks list

- server/i18n/en.json
Desktop app v5.9 will include Electron 31.2 which supports Chrome 126+.
```release-note
Updated minimum Edge and Chrome versions to 126+.
```
> Updated minimum supported Edge and Chrome versions

- webapp/channels/src/components/admin_console/elasticsearch_settings.tsx
The backend title was already there in en.json
```release-note
NONE
```
> Elasticsearch: Remove redundant message string

- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
In #27396, I made it so that histogram metrics always used `Date.now()` to fix the fact that `performance.now()` stops counting while the device is asleep. 
https://mattermost.atlassian.net/browse/MM-58772
```release-note
Fixed more web app performance reports being marked as outdated after the user's computer wakes up from sleep
```
> MM-58772 Fix counter metrics not using Date.now

- server/.golangci.yml
See https://github.com/mattermost/enterprise/pull/1707
https://mattermost.atlassian.net/browse/MM-58045
```release-note
NONE
```
> [MM-58045] Enable errcheck linter for enterprise/cloud package

- server/channels/app/channel_bookmark_test.go
- server/channels/app/integration_action_test.go
- server/channels/app/user_test.go
https://github.com/mattermost/mattermost-govet/pull/40 fixes a bug in `govet` that blocked most linter from running. Since that bug exists, some linter errors have crept into the code base. This PR fixes them.
https://mattermost.atlassian.net/browse/MM-59825
```release-note
NONE
```
> [MM-59825] Fix linter error found by updated govet

- server/Makefile
- Update prepackage Calls v0.29.1
- Dot release is to fix a regression in the Pion library, fixed in https://github.com/mattermost/mattermost-plugin-calls/pull/816
- none
```release-note
Prepackage Calls version [v0.29.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.29.1)
```
Calls [v0.29.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.29.1)
> Update prepackage calls to v0.29.1 for MM v9.11

- server/Makefile
It seems that https://github.com/mattermost/mattermost/pull/26518 broke the `make config-*` targets on at least one machine :smiley:.
The `TMPDIR` env variable didn't got assigned correctly. Using `eval` fixes the issue.
NONE
```release-note
NONE
```
> Fix config targets in Makefile

- webapp/channels/src/components/channel_bookmarks/channel_bookmarks.tsx
- webapp/channels/src/components/channel_bookmarks/utils.ts
- webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap
- webapp/channels/src/components/channel_view/channel_view.test.tsx
- webapp/channels/src/components/channel_view/channel_view.tsx
- webapp/channels/src/components/channel_view/index.ts
Hoists feature flag check to prevent mounting `<ChannelBookmarks/>` when feature flag is off, so an extraneous request is not made.
https://mattermost.atlassian.net/browse/MM-59835
|----|----|
| ![CleanShot 2024-07-23 at 16 06 21](https://github.com/user-attachments/assets/b9771035-fc87-4ec7-b5dd-7921fb27a7f6) | ![CleanShot 2024-07-23 at 16 05 43](https://github.com/user-attachments/assets/59134f44-3fe4-4233-bd9e-ab287fd5d19b) |
```release-note
NONE
```
> MM-59835: Prevent unnecessary channel bookmarks request causing console 404

- webapp/channels/src/components/admin_console/ip_filtering/edit_section/edit_section_edit_table_row.tsx
Remove deprecated overlay and use withTooltip in the edit section of IP filtering in the admin console
Fixes https://github.com/mattermost/mattermost/issues/27566
Jira https://mattermost.atlassian.net/browse/MM-59326
```release-note
NONE
```
> MM-59326: Remove deprecated overlay and use withTooltip in edit section of ip filtering in admin console

- server/channels/web/context.go
- server/channels/web/handlers.go
- server/channels/web/handlers_test.go
- server/i18n/en.json
- server/platform/services/telemetry/telemetry.go
- server/public/model/config.go
Made following changes to HTTP handler security logic-
1. Made payload size limit error more prominent by adding the following line in API error response-
```json
{
"id": "api.context.request_body_too_large.app_error",
"message": "Unable to process request. Request body too large.",
"detailed_error": "",
"request_id": "k51a683tdtdrtq6chwog9zw53o",
"status_code": 413
}
```
and following error log on server side-
```json
{
"timestamp": "2024-07-24 12:57:58.425 +05:30",
"level": "debug",
"msg": "Unable to process request. Request body too large.",
"caller": "web/context.go:120",
"path": "/api/v4/posts",
"request_id": "9w39umwc1tnm7xyouz843jehjo",
"ip_addr": "::1",
"user_id": "f8ama5so7bnaix5z94zj4x77sr",
"method": "POST",
"err_where": "Context",
"http_code": 413,
"error": "Context: Unable to …
```
> Prominent payload limit error and configurable URL length limit

- server/public/model/feature_flags.go
This has been set to true for a while on Community.
Setting it to true now for it to soak in cloud.
https://mattermost.atlassian.net/browse/MM-59865
```release-note
NONE
```
> MM-59865: Set WebsocketEventScope FF to true

- server/public/model/config.go
Here we change the default liveIndexing size.
https://mattermost.atlassian.net/browse/MM-59095
```release-note
Fix a bug where indexing would always be done async
even after setting LiveIndexingBatchSize to 1. Now
we respect the config and index synchronously if the
value is set to 1.
```
> MM-59095: Properly implement IsIndexingSync

- server/channels/app/file_test.go
Unix systems store files with a second precision timestamp. That is one part of the flaky test. The other issue was that the test checked if the file had been generated in the last second, which might not be enough time for CI.
https://community.mattermost.com/core/pl/m8gifco657g6mxmr64y6wte8kh
```release-note
NONE
```
> Fix flaky TestCreateZipFileAndAddFiles/write_one_file

- server/public/model/websocket_message.go
These WS events are no longer used in the code. Can be
removed as part of v10.
https://mattermost.atlassian.net/browse/MM-59846
```release-note
NONE
```
> MM-59846: Removing some deprecated ws events for v10

- webapp/channels/src/components/user_settings/modal/user_settings_modal.test.tsx
- webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
- webapp/channels/src/components/user_settings/plugin/plugin_setting.tsx
- webapp/channels/src/plugins/export.js
- webapp/channels/src/types/plugins/user_settings.ts
- webapp/channels/src/utils/plugins/plugin_setting_extraction.tsx
While implementing the actual thing, I found a couple of issues I am addressing here:
1. Support an icon class in addition to a URL/path to the icon file. This makes it possible to use compass icons and make the style consistent with other sections.
2. Pass the `informChange` prop to custom components so they can properly set the preference that needs updating.
3. Export the `react-select` package so we can conveniently reuse it on the plugin side.
https://mattermost.atlassian.net/browse/MM-51514
```release-note
NONE
```
> [MM-51514] Improvements to custom plugin user settings

- webapp/channels/src/components/user_settings/modal/user_settings_modal.test.tsx
- webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
- webapp/channels/src/components/user_settings/plugin/plugin_setting.tsx
- webapp/channels/src/plugins/export.js
- webapp/channels/src/types/plugins/user_settings.ts
- webapp/channels/src/utils/plugins/plugin_setting_extraction.tsx
On top of the changes in https://github.com/mattermost/mattermost/pull/27535, we'd like a way to programmatically open the user settings modal from a plugin (e.g. from the Calls widget).
PR adds a new `openUserSettings` method to the globally exported `WebappUtils`. To be used as such:
```js
store.dispatch(WebappUtils.openUserSettings({activeTab: 'com.mattermost.calls', isContentProductSettings: true}));
```
Alternatively, we could expose the `UserSettingsModal` component and use the existing `openModal` function. I am also open to stricter solutions but the above offered some flexibility for more use cases as well without exposing too many implementation details.
https://mattermost.atlassian.net/browse/MM-51514
```release-note
NONE
```
> [MM-51514] Allow plugins to open user settings modal

- server/channels/api4/ldap_test.go
Fix flaky test after https://github.com/mattermost/mattermost/pull/24675:
None
```release-note
NONE
```
> use model.NewUsername() for TestAddUserToGroupSyncables

- server/channels/api4/config.go
- server/channels/app/platform/config.go
Overall, there is no bug here. But opportunities for
improvement.
- Used the maps.Clone function.
- Handled the error while writing to the network.
https://mattermost.atlassian.net/browse/MM-59283
```release-note
NONE
```
> MM-59283: Minor improvement in getClientConfig

- server/platform/services/sharedchannel/sync_recv.go
Although we had systems in place to munge a patched username and update the internal props, we were not accepting usernames from updated users, so this change adds those into the patch applied when a user is updated.
https://mattermost.atlassian.net/browse/MM-59398
```release-note
NONE
```
> Allows remote users to change their username

- webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
- webapp/channels/src/components/channel_header/channel_header.tsx
Replaces OverlayTrigger and Tooltip, with WithTooltip in channel_header component
Fixes  [#27786](https://github.com/mattermost/mattermost/issues/27786)
Jira  [https://mattermost.atlassian.net/browse/MM-59895](https://mattermost.atlassian.net/browse/MM-59895)
```release-note
NONE
```
> [MM-59895] Migrate tooltips of 'components/channel_header/channel_header.tsx' to WithTooltip

- server/Makefile
- server/channels/app/plugin.go
This PR adds Playbooks v2 to the prepackaged plugins and maintains Playbooks v1.39.3 for servers without an enterprise license.
A [ticket has been created](https://mattermost.atlassian.net/browse/MM-60026) to add Playbooks 1.39.3 to the transitionally prepackaged plugin list for Mattermost installations without an enterprise license, so in the future we will be able to remove playbooks 1.39.3 from the prepackaged plugins.
https://mattermost.atlassian.net/browse/MM-59522
https://mattermost.atlassian.net/browse/MM-60025
N/A
```release-note
Added Playbooks v2.0.0 to the prepackaged plugins.
```
> [MM-60025][MM-59522] Add playbooks v2 to prepackaged plugins

- server/Makefile
https://mattermost.atlassian.net/browse/MM-59940
```release-note
NONE
```
> MM-59940: Pin govet version to a SHA version

- server/channels/app/platform/log.go
- server/channels/app/platform/log_test.go
- server/channels/app/support_packet_test.go
~~In https://github.com/mattermost/mattermost/pull/27598, I moved `GetNotificationLogFile` from the `app`  package to `platform`. During that process, I made a copy-and-paste mistake and picked the wrong sub-setting. Unfortunately, this also affected the corresponding test :disappointed. The mistake was only caught by a race condition that was introduced accidentally. ~~
Turns out, the notifications log file location was broken for quite some time. https://github.com/mattermost/mattermost/pull/27598 didn't break it, it copied the broken code. But due to a bug in the tests, they didn't caught it.
https://mattermost.atlassian.net/browse/MM-60152
https://community.mattermost.com/core/pl/h5bwzootni8atp5g9kk4ffpc4e
```release-note
NONE
```
> [MM-60152] Fix notifications log file location for Support Packet

- server/channels/app/admin.go
- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/config_test.go
- server/channels/app/platform/service.go
- server/channels/app/platform/session.go
- server/channels/app/platform/session_test.go
- server/channels/app/platform/status.go
- server/channels/store/localcachelayer/layer.go
- server/channels/store/localcachelayer/role_layer.go
- server/channels/store/localcachelayer/user_layer.go
- server/platform/services/cache/cache.go
- server/platform/services/cache/lru.go
- server/platform/services/cache/lru_striped.go
- server/platform/services/cache/lru_striped_bench_test.go
- server/platform/services/cache/lru_striped_test.go
- server/platform/services/cache/lru_test.go
- server/platform/services/cache/mocks/Cache.go
- server/platform/services/cache/provider_test.go
- server/platform/services/cache/redis.go
- We introduce 2 new APIs:
1. Scan: this allows incremental iteration
without blocking the Redis server and is the
recommended way to iterate over keys. With this,
we have entirely removed the need for Keys.
2. RemoveMulti: this allows deletion of multiple
keys in a single operation which optimizes
network round trips.
- While here, we make a small improvement to
GetStatusFromCache, where we remove the shallow
copy which wasn't necessary because we always
serialize the data from the cache.
- We do not use Redis for session cache because of
frequent requests to iterate the entire cache which leads
to a lot of `SCAN` calls.
- Avoid broadcasting status update messages for Redis case.
- Setting cache expiry for status cache
- Removing .Set method altogether to prevent
any chances of setting …
> MM-59932: Migrate remaining caches to Redis

- server/channels/app/file_test.go
The fix in https://github.com/mattermost/mattermost/pull/27737 was incorrect. The test file's timestamp is created before the mocked implementation of `WriteFile` runs. Therefore, it's possible that some time passes before the time stamp checks are executed.
I've relaxed the check a bit. It now confirms that the file was created in the last 10 seconds. To summarize, the initial implementation of the test was fine, but the 1-second timeframe was too short for CI. 10 seconds should do the trick. 
TODO: Enable test once https://github.com/mattermost/mattermost/pull/27881 is merged
https://community.mattermost.com/core/pl/jbqqhqtwhjf15corwifsfbk1sc
```release-note
NONE
```
> Fix flaky TestCreateZipFileAndAddFiles/write_one_file - 2nd round

- webapp/channels/src/components/advanced_text_editor/formatting_bar/formatting_icon.tsx
The changes ensure that the tooltip in "components/advanced_text_editor/formatting_bar/formatting_icon.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.
Fixes #27942
Jira: [MM-60154](https://mattermost.atlassian.net/browse/MM-60154)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/KwhRCmr/formatting-icon.png" alt="formatting-icon" border="0"></a>
```release-note
NONE
```
[MM-60154]: https://mattermost.atlassian.net/browse/MM-60154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-60154] Migrate tooltips of components/advanced_text_editor/formatting_bar/formatting_icon.tsx' to WithTooltip

- webapp/channels/src/components/advanced_text_editor/use_emoji_picker.tsx
The changes ensure that the tooltip in "components/advanced_text_editor/use_emoji_picker.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.
Fixes #27939
Jira: [MM-60157](https://mattermost.atlassian.net/browse/MM-60157)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5F6g0gX/emoji-picker.png" alt="emoji-picker" border="0"></a>
```release-note
NONE
```
[MM-60157]: https://mattermost.atlassian.net/browse/MM-60157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-60157] Migrate tooltips of 'components/advanced_text_editor/use_emoji_picker.tsx' to WithTooltip

- webapp/channels/src/components/global_header/right_controls/at_mentions_button/__snapshots__/at_mentions_button.test.tsx.snap
- webapp/channels/src/components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx
The changes ensure that the tooltip in "components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.
Fixes #27935
Jira: [MM-60161](https://mattermost.atlassian.net/browse/MM-60161)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/8jgD1TF/recent-mention.png" alt="recent-mention" border="0"></a>
```release-note
NONE
```
[MM-60161]: https://mattermost.atlassian.net/browse/MM-60161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-60161] Migrate tooltips of 'components/global_header/right_controls/at_mentions_button/at_mentions_button.tsx' to WithTooltip

- webapp/channels/src/components/post_view/post_edited_indicator/post_edited_indicator.tsx
The changes ensure that the tooltip in "components/post_view/post_edited_indicator/post_edited_indicator.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.
Fixes #27933
Jira: [60163](https://mattermost.atlassian.net/browse/MM-60163)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/9HZ4QZc/post-edit.png" alt="post-edit" border="0"></a>
```release-note
NONE
```
> [MM-60163] Migrate tooltips of 'components/post_view/post_flag_icon' to WithTooltip

- webapp/channels/src/components/post_view/post_time/post_time.tsx
The changes ensure that the tooltip in "components/post_view/post_time/post_time.tsx" now utilizes the WithTooltip component, replacing the previous usage of OverlayTrigger and Tooltip.
Fixes #27932
Jira: [MM-60164](https://mattermost.atlassian.net/browse/MM-60164)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/MCB8t2x/post-time.png" alt="post-time" border="0"></a>
```release-note
NONE
```
[MM-60164]: https://mattermost.atlassian.net/browse/MM-60164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-60164] Migrate tooltips of 'components/post_view/post_time/post_time.tsx' to WithTooltip

- webapp/channels/src/components/threading/virtualized_thread_viewer/virtualized_thread_viewer.tsx
Cherry pick of #27871 on release-10.0.
```release-note
NONE
```
> Automated cherry pick of #27871

- server/channels/app/plugin.go
For servers that do not have an enterprise license, we want to be able to make a local copy of the plugin (using transitional package) so that in the future, we can remove playbooks <v2 from the prepackaged plugins.
https://mattermost.atlassian.net/browse/MM-60026
```release-note
NONE
```
> [MM-60026] Add playbooks <v2 in the transitionaslly packaged list

- server/channels/app/plugin.go
Cherry pick of #27903 on release-10.0.
```release-note
NONE
```
> Automated cherry pick of #27903

- server/Makefile
Prepackaging Calls v1.0.0, to be released with Mattermost v10.
https://mattermost.atlassian.net/browse/MM-59520
```release-note
Prepackaged Calls v1.0.0 - This includes breaking changes such as allowing calls in direct message channels only on unlicensed servers.
```
> [MM-59520] :telephone_receiver: Prepackage Calls v1.0.0

- webapp/channels/src/components/edit_post/edit_post.tsx
- webapp/channels/src/components/emoji_picker/emoji_picker_overlay/emoji_picker_overlay.tsx
The `container` prop of React Bootstrap's `Overlay` and `OverlayTrigger` components is used to control where in the DOM the overlaid component is rendered (like a React Portal), and we used to do that for the emoji picker in some places so that it would move with the surrounding content when that was scrolled. Without it, the component is rendered at the root of the document.
We no longer let users scroll content behind the emoji picker, so we don't need to use a `container` here. By moving it to the root of the document, it'll render on top of everything, and it'll no longer get cut off by the a container that has overflow hidden.
MM-60188
This never shipped, so no release not is needed
```release-note
NONE
```
> MM-60188 Stop rendering EmojiPickerOverlay inside of EditBox

- webapp/channels/src/components/setting_item.tsx
During the [change of this component from class to function component](https://github.com/mattermost/mattermost/commit/c582f497391611715761530f8e0b99f0bf41e07f), we made a small behavior change.
We use to focus the edit button on update if we change from active to inactive. But when migrating, we used a `useEffect`, which also runs on mount. So all edit buttons where trying to get the focus, and in the end, the last one got the focus. Therefore, the scroll there.
Changing to use the `useDidUpdate` hook solves it.
Fix https://mattermost.atlassian.net/browse/MM-60238
Catched before it made it into production
```release-note
NONE
```
> Fix scroll on user settings

- server/channels/app/expirynotify.go
- server/channels/app/notification_push.go
- server/public/model/notification.go
The `sendToPushProxy` returns an specific error when the device token is removed. This is an expected error, so we added a new reason to differentiate from other generic push proxy errors that may imply problems in the delivery metrics.
https://mattermost.atlassian.net/browse/MM-58592
```release-note
Improve metrics related to push proxy errors
```
> Differentiate remove device error from push proxy

- server/Makefile
PR prepackages a dot release of Calls v1 that fixes a regression we caught on Community this week.
https://mattermost.atlassian.net/browse/MM-59520
```release-note
Prepackaged Calls [v1.0.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.0.1) - This includes breaking changes such as allowing calls in direct message channels only on unlicensed servers.
```
> [MM-59520] Prepackage Calls v1.0.1

- server/Makefile
Cherry pick of #28026 on release-10.0.
```release-note
NONE
```
> Automated cherry pick of #28026

- server/channels/app/plugin_api.go
- server/public/plugin/api.go
- server/public/plugin/api_timer_layer_generated.go
- server/public/plugin/client_rpc_generated.go
- server/public/plugin/plugintest/api.go
The new function, GetPluginID, has been added to various server and plugin related files. This function returns the ID of a plugin. The changes include:
- Addition of the GetPluginID method in the PluginAPI interface.
- Implementation of this method in apiTimerLayer and client_rpc_generated files.
- Mocking of this method for testing purposes in plugintest/api.go file.
Fixes https://github.com/mattermost/mattermost/issues/26710
```release-note
NONE
```
> MM-57738 - Added GetPluginID function across multiple files

- server/channels/api4/metrics_test.go
- server/channels/web/handlers.go
Removed an incorrect return statement that caused missed timing metrics for API calls that resulted in 4xx and 5xx errors.
Fixes https://mattermost.atlassian.net/browse/MM-60269
```release-note
None
```
> removed an incorretc return that caused missing API timing metrics for 4xx and 5xx errors

- webapp/channels/src/sass/base/_structure.scss
Fixes a layout issue when view the expanded RHS on screens between 768px and < 1200px
Jira: https://mattermost.atlassian.net/browse/MM-59855
|----|----|
| <img width="1107" alt="image" src="https://github.com/user-attachments/assets/49ee73f6-4f55-42a4-ad8b-41dbcc558a80"> | <img width="1107" alt="image" src="https://github.com/user-attachments/assets/ea63cf7d-dafc-4e02-81bb-84039ff0b5c2">|
| <img width="1156" alt="image" src="https://github.com/user-attachments/assets/082cf40b-256d-4603-8fd4-c3f22e29995b"> | <img width="568" alt="image" src="https://github.com/user-attachments/assets/e5c062b7-2830-42cc-ae38-bc38b3e5998f"> |
```release-note
NONE
```
> MM-59855 Fix layout issue on smaller screens when rhs is expanded

- server/channels/api4/license.go
- server/channels/api4/license_test.go
Looks like the error check was forgotten, this leading to a `nil` struct method to be invoked.
https://mattermost.atlassian.net/browse/MM-60280
```release-note
NONE
```
> [MM-60280] api4/license.go: add err check to JSON unmarshal

- webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
During the migration, I forgot to migrate this piece of code that dealt with these events.
This PR takes back this functionality.
Fix https://mattermost.atlassian.net/browse/MM-60289
```release-note
Allow to use the "react to last emoji" hotkey when the input doesn't have the focus.
```
> Fix unfocussed react to last message

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
There are cases when the application receives threads, for example via `getCountsAndThreadsSince` when the websocket reconnects after a user has been inactive, where we receive threads that are unread. Where this may be reflected is the Unreads tab of Threads view where we list our unread threads. We show that they are marked unread in the Threads view as the information is available on the thread, but we were not updating the reducers that also track the thread IDs.
This PR adds that update to the reducer for `unreadThreadsInTeam` so that we can be assured that the latest unread thread information is available widespread. Definitely worth reading the JIRA ticket to understand how the issue can arise.
https://mattermost.atlassian.net/browse/MM-59912
```release-note
Fixed an issue where …
```
> [MM-59912] Update unread threads in team when threads are received

- server/Makefile
This PR adds two plugins to the prepackaged plugins list:
- [MS Calendar](https://github.com/mattermost/mattermost-plugin-mscalendar)
- [MS Teams Meetings](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings)
**Note:**  Moving the [MS Teams Meetings plugin](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings) to the Mattermost Github org is still pending. Therefore some manual intervention may be need to get the [release binary](https://github.com/mattermost-community/mattermost-plugin-msteams-meetings/releases/tag/v2.2.0) to the right place.
https://mattermost.atlassian.net/browse/MM-59878
```release-note
Prepackage MS Calendar and MS Teams Meetings plugins
```
> Prepackage plugins mscalender and msteams meetings

- webapp/channels/src/components/initial_loading_screen/initial_loading_screen_class.ts
This fixes the issue where the loading indicator doesnt get cleaned up after the loading is complete. It also fixes the issue where the desktop renders the initial loading indicator where it should not have had.
https://mattermost.atlassian.net/browse/MM-60284
none
```release-note
NONE
```
> [MM-60284] Desktop app doesnt stop the initial loading indicator

- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_profile.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_profile.tsx
- webapp/channels/src/components/admin_console/team_channel_settings/channel/list/__snapshots__/channel_list.test.tsx.snap
- webapp/channels/src/components/admin_console/team_channel_settings/channel/list/channel_list.tsx
- webapp/channels/src/components/channel_header/channel_header_title.tsx
- webapp/channels/src/components/channel_members_rhs/member.tsx
- webapp/channels/src/components/forward_post_modal/forward_post_channel_select.tsx
- webapp/channels/src/components/searchable_channel_list.tsx
- webapp/channels/src/components/shared_channel_indicator.tsx
- webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx
- webapp/channels/src/components/suggestion/switch_channel_provider.tsx
Cherry pick of #28132 on release-10.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #28132

- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_send_remote.go
- server/platform/services/telemetry/telemetry.go
- server/public/model/config.go
Cherry pick of #28154 on release-10.1.
```release-note
NONE
```
> Automated cherry pick of #28154

- server/channels/api4/channel_bookmark_test.go
https://mattermost.atlassian.net/browse/MM-60499
```release-note
NONE
```
> Skip racy subtest from TestUpdateChannelBookmarkSortOrder

- server/channels/store/sqlstore/shared_channel_store.go
- server/channels/store/storetest/shared_channel_store.go
- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_send.go
- server/public/model/remote_cluster.go
- server/public/model/shared_channel.go
Invites sent to remotes marked as offline will be stored as pending, and when the remote comes back online, it will fetch and process the pending invites as part of the synchronization process.
https://mattermost.atlassian.net/browse/MM-58800
```release-note
* Adds support for sending channel invites to offline remotes in Shared Channels
```
> Allows invites to be sent to offline remotes

- server/channels/store/sqlstore/shared_channel_store.go
- server/channels/store/storetest/shared_channel_store.go
- server/platform/services/sharedchannel/channelinvite.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/sync_send.go
- server/public/model/remote_cluster.go
- server/public/model/shared_channel.go
Cherry pick of #28176 on release-10.1.
```release-note
NONE
```
> Automated cherry pick of #28176

- server/channels/api4/channel_bookmark_test.go
Cherry pick of #28155 on release-10.1.
```release-note
NONE
```
> Automated cherry pick of #28155

- server/channels/app/notification_email.go
- server/channels/app/notification_email_test.go
GitHub issue: https://github.com/mattermost/mattermost/issues/26309
https://mattermost.atlassian.net/browse/MM-56994
```
Description: Changed the logic of useMilitaryTime to false to default to 12-hour time format unless the user's preference from data.Value is "true".
Field affected: When a notification mail is sent to a user, the time should now default to the 12-hour format except otherwise stated by the user.
```
```release-note
Fixed email notifications using 24 hour timestamps by default
```
> MM-56994 Used false as default for useMilitaryTime

- webapp/channels/src/components/admin_console/schema_text.tsx
Anytime you navigate to a page in the system console that use help_text_values to create <ExternalLinks>. You get the Javascript error. Surprisingly, the error didn't seem to cause any functionality issues.
This PR updates the `textValue` field to either a string or a function that returns a ReactNode, rather than accepting a ReactNode.
Fixes https://mattermost.atlassian.net/browse/MM-60533
```release-note
Fixes issue causing Javascript errors in System Console.
```
> MM-60533 Object to accept function

- server/channels/api4/remote_cluster.go
- server/channels/api4/remote_cluster_test.go
- server/channels/api4/shared_channel.go
- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/platform/shared_channel_notifier.go
- server/channels/app/remote_cluster.go
- server/channels/app/session.go
- server/channels/app/slashcommands/command_share.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/remote_cluster_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/RemoteClusterStore.go
- server/channels/store/storetest/remote_cluster_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/platform/services/remotecluster/recv.go
- server/platform/services/sharedchannel/service_api.go
- server/platform/services/sharedchannel/sync_send.go
This is done for improving code safety and readability, as the caller now needs to explicitly state if they allow deleted remote clusters to be fetched instead of having to control those cases after each call.
https://mattermost.atlassian.net/browse/MM-60535
```release-note
NONE
```
> Adds includeDeleted flag to get remote cluster app and store methods

- server/channels/app/slashcommands/command_share_test.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/service_api.go
Before we were sending the CHANNEL_CONVERTED websockets event, which is intended to notify of a public channel being converted into a private one, so the interface was showing the channel as private until the client was refreshed.
Now a full channel update event is sent when the channel is shared or unshared, so the interface gets the new information correctly.
https://mattermost.atlassian.net/browse/MM-55717
https://mattermost.atlassian.net/browse/MM-52575
```release-note
NONE
```
> Changes the event to send when a channel is shared or unshared

- server/channels/app/slashcommands/command_share_test.go
- server/platform/services/sharedchannel/service.go
- server/platform/services/sharedchannel/service_api.go
Cherry pick of #28183 on release-10.1.
```release-note
NONE
```
> Automated cherry pick of #28183

- server/Makefile
Title says it all.
https://mattermost.atlassian.net/browse/MM-60429
```release-note
Added metrics-plugin to the prepackaged plugins.
```
> [MM-60429] server/Makefile: add metrics-plugin to the prepackaged plugins

- webapp/channels/src/sass/components/_post.scss
The shared channels icon is set to a specific color. This PR changes the color to a system color.
The other items in the Jira ticket are duplicates and have already been fixed.
Fixes https://mattermost.atlassian.net/browse/MM-58229
Before
After
```release-note
NONE
```
> MM-58229 - Update icon color to system color

- server/channels/store/localcachelayer/layer_test.go
- server/channels/store/localcachelayer/user_layer.go
- server/platform/services/cache/lru.go
- server/platform/services/cache/lru_test.go
- server/platform/services/cache/redis.go
We were using a mock cache provider which mixed up LRU caches
with each other. This led to incorrect unmarshalling method calls.
We fix this by using the real cache provider.
https://mattermost.atlassian.net/browse/MM-60413
```release-note
NONE
```
> MM-60413: Fix issues due to incorrect cache provider

- api/v4/source/sharedchannels.yaml
- server/channels/api4/shared_channel.go
- server/channels/api4/shared_channel_test.go
- server/channels/web/params.go
- server/public/model/client4.go
This is necessary to show the pending invites that a server has sent and have not been accepted yet in the system console.
https://mattermost.atlassian.net/browse/MM-60571
```release-note
NONE
```
> Allow shared channel remotes endpoint to be filtered by confirmation status

- server/config/client.go
- server/public/model/config.go
Introducing a client config property that determines if the mobile app should use the default external browser to perform SSO Authentication instead of the internal one.
Value defaults to **false**.
Note: It does not include an admin console UI.
Important: We want to include this in the latest ESR as will mostly be used by certain enterprise customers.
https://mattermost.atlassian.net/browse/MM-60332
```release-note
Added config setting NativeAppSettings -> MobileExternalBrowser that tells the mobile app to perform the SSO Authentication using the external default browser
```
> Add MobileExternalBrowser to client config

- server/Makefile
Prepackaging the latest Calls v0.29 release to be included in the upcoming 9.11 dot release.
```release-note
Pre-packaged Calls v0.29.2
```
> Prepackage Calls v0.29.2 in 9.11

- webapp/channels/src/components/drafts/drafts.scss
Fixed a bug where horizontal alignment of "no draft" graphic was broken.
Fixes https://mattermost.atlassian.net/browse/MM-60581
Before-
After-
```release-note
none
```
> Fixed horizontal alignment of no draft graphic

- server/Makefile
- server/build/docker-compose.common.yml
- server/build/docker/postgres_node_database.sql
This PR allows to run a different Mattermost instance in port :8066 using the `make run-node` target. This instance reuses the frontend files compiled for the main development instance, has its own database and local mode enabled through environment variables, and for the rest of the configuration simply takes whatever properties are set in the `config.json` file.
This target is specially useful to run a Shared Channels development environment, compiling first the frontend and then running `make run-server` and `make run-node` side by side, later connecting both and testing Shared Channels features.
```release-note
NONE
```
> Adds a make target and a database for a shared channels node

- server/channels/store/searchlayer/file_info_layer.go
- server/channels/store/searchtest/file_info_layer.go
Get channel id from file when indexing files associated with bookmarks
https://mattermost.atlassian.net/browse/MM-59990
```release-note
NONE
```
> MM-59990: Fix bookmark file search in ES/OS

- server/channels/app/platform/session.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_conn_test.go
This Pr is another race fix for `WebConn` similar to https://github.com/mattermost/mattermost/pull/20996.
1. A request for `/api/v4/websocket` comes in.
2. `web.Handler.ServeHTTP` get the corresponding session `S`
3. `connectWebSocket` is called. It handles the request, calling `PlatformService.NewWebConn` in the process and starts to `Pump()` the websocket connection.
4. The connection is terminated, e.g. through a bad mobile connection.
5. The deferred statement in `web.Handler.ServeHTTP` returns `S` to the `sync.Pool`.
6. Another request comes in, gets `S` from the pool and calls `UnmarshalMsg`. As part of that method, all existing props get deleted 
https://github.com/mattermost/mattermost/blob/e8de27b043b2971472f30cb2e6c77bf4f8978486/server/public/model/session_serial_gen.go#L348-L352 …
> [MM-60307] Fix racy use of session in NewWebConn

- server/channels/api4/shared_channel.go
- server/platform/services/sharedchannel/service_api.go
This PR changes the error returned by the shared channels service to be a `BadRequest` instead of an `InternalServerError` and updates the API to directly return the error returned by the service instead of a new one.
https://mattermost.atlassian.net/browse/MM-60601
```release-note
NONE
```
> Add a specific error when inviting a remote cluster to a remote channel

- server/Makefile
- server/go.mod
- server/go.sum
Bump Markdown parsing dependency, which got downgraded in https://github.com/mattermost/mattermost/pull/27752.
I've also added a documentation comment to the `modules-tidy` make rule so that it shows in the `make help` command, where it was missing.
https://mattermost.atlassian.net/browse/MM-58746
--
```release-note
NONE
```
> MM58746: Bump yuin/goldmark dependency

- server/public/model/config.go
- server/public/model/config_test.go
https://github.com/mattermost/mattermost/pull/27986 caused an issue with the Calls E2E tests as even for not installed plugin, the config API endpoint would return obfuscated values. See https://github.com/mattermost/mattermost/pull/27986#discussion_r1762107270 for more details.
With this PR, the config values of any non-installed plugin are not returned via the API at all.
https://mattermost.atlassian.net/browse/MM-57194
```release-note
NONE
```
> [MM-57194] Don't return config values from plugins that are not installed

- webapp/channels/src/components/root/root.test.tsx
- webapp/channels/src/components/root/root.tsx
Regex was failing to identify between `admin_console/integrations` and `team_name/integrations` page. Fixed to identify admin console as well 
Jira https://mattermost.atlassian.net/browse/MM-60514
```release-note
```
> [MM-60514] Accessing bot_accounts page directly fails to load

- server/channels/app/notification.go
- server/public/model/channel.go
When adding notifications, in several places we skip profiles that do not belong to the channel, but not all of them. Now we check in all of them.
I was able to reproduce the `missing profile` error by deleting in the database one of the users on a GM and then creating a message in the GM.
I also piggybacked a fix where bot messages in a DM won't show as mention to one of the DM members (the one which ID is on second place).
Fix https://mattermost.atlassian.net/browse/MM-59102
```release-note
Minor improvements in notification metrics
Bot messages will properly mention both users when they happen on non-bot DMs
```
> Fix missing profile messages on notification dashboards

- server/platform/services/cache/redis.go
I forgot to remove this method in my
earlier refactoring. A bit weird that no linter
caught this. :thinking:
```release-note
NONE
```
> Remove some dead code from Redis

- server/channels/app/notification_push_test.go
- server/channels/app/platform/config.go
- server/channels/app/platform/helper_test.go
- server/channels/app/platform/service.go
- server/channels/app/platform/service_test.go
Cherry pick of #28038 on release-10.0.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #28038

- server/channels/api4/api.go
- server/channels/manualtesting/manual_testing.go
- server/cmd/mattermost/commands/server.go
It likely won't affect production as `EnableTesting` should not be enabled for production servers.
https://mattermost.atlassian.net/browse/MM-60648
```release-note
Fixed a race condition that would happen after the server start if EnableTesting is enabled 
```
> [MM-60648] Don't start server until all routes are registered

- webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
- webapp/channels/src/components/channel_header/channel_header.tsx
This PR hides the pinned icon button in the channel header if there are no pinned posts in the channel. It's not particularly useful unless there are pinned posts in the channel, so we should hide it to reduce the extra visual noise it causes.
Jira: https://mattermost.atlassian.net/browse/MM-60604*
| |  before  |  after  |
|----|----|----|
| No pinned posts | <img width="261" alt="image" src="https://github.com/user-attachments/assets/1de6c080-3e97-4d7c-ba75-d7911c7d79ed"> | <img width="264" alt="image" src="https://github.com/user-attachments/assets/6d66b38f-a3f0-4c62-a232-c1948595bd38"> |
| With pinned posts | <img width="271" alt="image" src="https://github.com/user-attachments/assets/d29ee568-e8b5-470f-aa7d-94fdb852e385"> | <img width="268" alt="image" …
> MM-60604 Hide pinned icon in channel header when no pinned posts

- server/channels/api4/system.go
- server/channels/app/admin.go
- server/channels/app/analytics.go
- server/channels/app/busy_test.go
- server/channels/app/platform/busy_test.go
- server/channels/app/platform/log.go
- server/channels/testlib/cluster.go
- server/einterfaces/cluster.go
- server/einterfaces/mocks/ClusterInterface.go
This PR improves the log messages related to cluster communication by
- Passing `request.CTX` all the way down to the `GossipClient`
- Use an annoyed longer inside the cluster event handlers
- Replace calls to the global logger with ones to the request specific one
Related discussion: https://hub.mattermost.com/private-core/pl/nyytm167rpfzbqawfejjm9cuwr and ticket: https://mattermost.zendesk.com/agent/tickets/43714
https://mattermost.atlassian.net/browse/MM-60619
```release-note
Improve log messages for cluster communication
```
> [MM-60619] Annotate cluster logs messages

- server/platform/shared/mfa/mfa.go
- server/platform/shared/mfa/mfa_test.go
Disallow reuse of the same code when updating 2FA secret.
I tried to refactor to reuse the same code for both but it ended up making everything less readable, so I refactored making a compromise for better readability by only moving the actual code verification in it's own method.
https://mattermost.atlassian.net/browse/MM-59069
```release-note
NONE
```
> [MM-59069] Add reuse check on change MFA

- webapp/channels/src/components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
Modifies the condition for the shared channel indicator to show up, fixing an issue where all users in the DM list where being shown as shared.
Manually set `remoteId` to the channel exporter bot.
Before:
After:
```release-note
NONE
```
> fix: dm shared channel indicator

- server/.golangci.yml
- server/channels/api4/channel_bookmark_test.go
This PR solves issue https://github.com/mattermost/mattermost/issues/28353. This is done by capturing the error and handling it appropriately.
Fixes https://github.com/mattermost/mattermost/issues/28353
```release-note
Fixed errcheck issues in server/channels/api4/channel_bookmark_test.go
Removed channel_bookmark_test.go from server/.golangci.yml
```
> [GH-28353] Fix errcheck issues in server/channels/api4/channel_bookmark_test.go 

- webapp/channels/src/actions/views/create_comment.tsx
- webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
Fixed a bug where file attachments in scheduled posts didn't show up until a refresh.
Also, I've hidden the "send now" and "edit" buttons on scheduled posts until they are implemented as a preparation for getting scheduled posts on community.
```release-note
none
```
> Fixed a bug where files in scheduled post didn't show up until refresh

- .github/holopin.yml
See https://github.com/mattermost/mattermost/pull/26808 for historical context
See https://github.com/marketplace/holopin for usage
> Add Hacktoberfest 2024 Holopin badge to holopin.yml

- server/Makefile
Bump `mattermost-plugin-metrics` to `v0.5.3` in prepackaged plugins to fix a versioning issue. Context: https://community.mattermost.com/core/pl/8dqradqz9id3jr7ocj3r39jwxa
```release-note
NONE
```
> server/Makefile: bump mattermost-plugin-metrics version

- server/channels/api4/plugin_test.go
- server/channels/app/plugin.go
Cherry pick of #28366 on release-10.1.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #28366

- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
These tests are incredibly flaky, and I've spent enough time fighting with them that I'm just disabling them until we end up making more changes to this code which I don't expect to be for a while.
```release-note
NONE
```
> Disable PerformanceReporter tests

- server/channels/app/notification_push.go
- server/channels/app/notification_push_test.go
- server/channels/store/sqlstore/session_store.go
- server/channels/store/storetest/session_store.go
- server/public/model/session.go
When the app starts, always sets the device id. This is so potential changes in the device id are up to date in the server.
The server on the other hand, removed the device id whenever the push proxy told it so.
This made it so devices ids kept being added and removed, making more calls than necessary to the push proxy.
By storing in the props the device id that has been removed, we can keep track of what devices ids has been removed and prevent resending when the app resets it.
https://mattermost.atlassian.net/browse/MM-59086
```release-note
Minor improvement on mobile push notifications
```
> Avoid resetting device id when removed from push proxy

- server/channels/app/platform/license.go
To my surprise, we never log the details of a license when it's loaded or cleared. This makes it hard to debug certain scenarios from logs alone. Let's fix that!
Fixes: https://mattermost.atlassian.net/browse/MM-60692
```release-note
Emit license details to logs when added or removed.
```
> Emit license details to logs when added or removed

- server/public/model/client4.go
The client4 in golang was returning the wrong model in the response, this fixes it.
N/A
```release-note
NONE
```
> Fix the response type of create bookmark in go client

- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
Previously I was checking if there is any scheduled post for the channel and showing the post box indicator accordingly. Now I show it only if there is an error-free scheduled post. I also considered showing only for future scheduled posts but since the backend process scheduled posts up tp 24 hours old, it is possible for a scheduled posts few hours in the past to still be processed.
Fixes https://mattermost.atlassian.net/browse/MM-60944
```release-note
None
```
> Only consider error-free scheduled posts for indicator in channel and RHS

- server/channels/app/channel_test.go
- server/channels/jobs/jobs_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_member_history_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_member_history_store.go
- server/channels/store/storetest/mocks/ChannelMemberHistoryStore.go
- server/channels/store/timerlayer/timerlayer.go
- server/i18n/en.json
- server/public/model/config.go
- webapp/channels/src/components/admin_console/message_export_settings.test.tsx
- webapp/channels/src/components/admin_console/message_export_settings.tsx
- [modify GetUsersInChannelDuring to accept a slice of channelIds](https://github.com/mattermost/mattermost/commit/e644d9c2064f778bd8bc8bc0be80533ce885f207)
- [add GetChannelsWithActivityDuring](https://github.com/mattermost/mattermost/commit/106458a1866d72e75d578fa975e5d7f6e95391e3)
- https://mattermost.atlassian.net/browse/MM-60422
```release-note
GetUsersInChannelDuring now accepts a slice; added GetChannelsWithActivityDuring
```
> [MM-60422] Add GetChannelsWithActivityDuring

- server/channels/store/sqlstore/compliance_store.go
- server/channels/store/sqlstore/post_store.go
- server/channels/store/storetest/compliance_store.go
- server/einterfaces/message_export.go
- server/einterfaces/mocks/MessageExportInterface.go
- server/i18n/en.json
- server/public/model/config.go
- server/public/model/message_export.go
- server/public/model/post.go
- server/public/shared/i18n/i18n.go
- Add `UntilUpdateAt` for `MessageExport` and `AnalyticsPostCount` -- this is needed for bounded exports (e.g., in the CLI and possibly in the future through the system console)
- Removed quite a few non-UI facing i18n strings -- slowly removing AppError from the internal code
- Add `TranslationsPreInitFromBuffer` to allow CLI to use i18n
Linked: https://github.com/mattermost/enterprise/pull/1769
- https://github.com/mattermost/mattermost-compliance-export/pull/16
- https://mattermost.atlassian.net/browse/MM-60570
```release-note
NONE
```
> MM-60570 - Server-side changes consolidating the export CLI with server/ent code

- server/channels/store/sqlstore/post_store.go
- server/channels/store/storetest/post_store.go
When we create or update a post in a thread, the root post also gets their update at updated to the same value. But when a post is deleted, it is not.
This created an issue when checking the etag, which was looking for the latest update at, and if two are the same, the one with the "highest id". If any post "in the middle" or a last post with "lower id" is removed, the update at would be the same (the same as the last posted post) and the id too,generating the same etag and forcing this issue.
By updating the `update_at` of the post whenever we delete a post fixes the issue.
Fix https://mattermost.atlassian.net/browse/MM-60791
```release-note
Fix issue when deleted posts on threads may not appear as deleted on certain circumstances
```
> Update root post update at on reply delete

- server/Makefile
- server/cmd/mmctl/commands/channel_test.go
Fix potentially broken make test-server command if GOFLAGS is defined
Also fix channel names typos in channel_test
This PR is splited from https://github.com/mattermost/mattermost/pull/28676 to remove unrelated changes
```release-note
NONE
```
> server: Fix typo in Makefile

- server/channels/store/localcachelayer/user_layer.go
- server/channels/store/localcachelayer/user_layer_test.go
- server/platform/services/cache/lru.go
- server/platform/services/cache/lru_test.go
- server/platform/services/cache/redis.go
We remove the remaining special casing for **model.User
and add unit tests to lock in the behavior.
Additional load tests were done locally to confirm
there are no hidden code paths left out.
https://mattermost.atlassian.net/browse/MM-59947
```release-note
NONE
```
> MM-59947: Remove the remaining **model.User special casing

- server/enterprise/external_imports.go
- server/enterprise/local_imports.go
- server/enterprise/message_export/actiance_export/actiance_export.go
- server/enterprise/message_export/actiance_export/actiance_export_test.go
- server/enterprise/message_export/common_export/common_export.go
- server/enterprise/message_export/common_export/common_export_test.go
- server/enterprise/message_export/csv_export/csv_export.go
- server/enterprise/message_export/csv_export/csv_export_test.go
- server/enterprise/message_export/global_relay_export/deliver.go
- server/enterprise/message_export/global_relay_export/deliver_test.go
- server/enterprise/message_export/global_relay_export/global_relay_export.go
- server/enterprise/message_export/global_relay_export/global_relay_export_test.go
- server/enterprise/message_export/global_relay_export/main_test.go
- server/enterprise/message_export/global_relay_export/smtp.go
- server/enterprise/message_export/global_relay_export/to_html.go
- server/enterprise/message_export/main_test.go
- server/enterprise/message_export/membership_map.go
- server/enterprise/message_export/membership_map_test.go
- server/enterprise/message_export/message_export.go
- server/enterprise/message_export/message_export_test.go
- server/enterprise/message_export/scheduler.go
- server/enterprise/message_export/scheduler_test.go
- server/enterprise/message_export/worker.go
- server/enterprise/message_export/worker_test.go
- Move the message export folder to the monorepo under the source available licensed enterprise folder. 
- Enterprise PR: https://github.com/mattermost/enterprise/pull/1770
- https://mattermost.atlassian.net/browse/MM-60987 
```release-note
The message export code now lives in the source available enterprise folder.
```
> MM-60987: Move message_export code to monorepo

- webapp/channels/src/components/channel_header/__snapshots__/channel_header.test.tsx.snap
- webapp/channels/src/components/channel_header/channel_header.tsx
- webapp/channels/src/components/channel_header/channel_info_button.tsx
- webapp/channels/src/components/channel_header/components/header_icon_wrapper.test.tsx
- webapp/channels/src/components/channel_header/components/header_icon_wrapper.tsx
- webapp/channels/src/components/search/search.tsx
- webapp/channels/src/plugins/channel_header_plug/channel_header_plug.tsx
It seems so counterintuitive to pass the wrapped element as a prop
This is a cleanup patch I made during preparatory work on https://github.com/mattermost/mattermost/issues/22467
```release-note
NONE
```
Jira ticket: https://mattermost.atlassian.net/browse/MM-27291
> HeaderIconWrapper: pass wrapped icon as a children

- server/channels/api4/channel_bookmark_test.go
- server/channels/store/sqlstore/channel_bookmark_store.go
When sorting channel bookmarks, even though the update_at field is modified in the database entry, the WebSocket event objects were not including the modified update_at property.
https://mattermost.atlassian.net/browse/MM-60644
https://mattermost.atlassian.net/browse/MM-60499
```release-note
NONE
```
> set update_at on bookmarks return when changing sort order

- server/cmd/mmctl/commands/webhook.go
- e5f9325b58bc718b691ecb2d0225ec1eed3737dd: Add missing parenthesis in mmctl webhook list
- e30e11115b7504499d3aa02eb353fd2d17bbf411: Use generics in StoreResult, similar to the main server
None
```release-note
NONE
```
> Add missing parenthesis in mmctl webhook list

- api/v4/source/remoteclusters.yaml
- e2e-tests/cypress/tests/integration/channels/system_console/connected_workspaces_management_spec.ts
- server/channels/api4/remote_cluster.go
- server/channels/api4/remote_cluster_test.go
- server/channels/app/slashcommands/command_remote.go
- server/platform/services/remotecluster/invitation.go
- server/platform/services/remotecluster/service.go
- server/public/model/remote_cluster.go
- webapp/channels/src/components/admin_console/secure_connections/controls.tsx
- webapp/channels/src/components/admin_console/secure_connections/modals/modal_utils.tsx
- webapp/channels/src/components/admin_console/secure_connections/modals/secure_connection_accept_invite_modal.tsx
- webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx
- webapp/channels/src/components/admin_console/secure_connections/team_selector.tsx
- webapp/channels/src/components/admin_console/secure_connections/utils.ts
- webapp/channels/src/i18n/en.json
- webapp/platform/types/src/remote_clusters.ts
Adds a destination team selector to the accept invite modal and makes it required
Fixes https://mattermost.atlassian.net/browse/MM-61032
```release-note
Added team selector to accept connection invite flow in Shared Workspaces
```
> MM-61032: Add default_team_id to accept invite flow

- .github/workflows/build-opensearch-image.yml
- server/scripts/mirror-docker-images.json
Fixes two issues introduced with the previous PR https://github.com/mattermost/mattermost/pull/28835 :
- Use the right format for the Opensearch image build's `build-args`
- Delete unsupported mysql 5.7 image, which is currently failing to pull on any modern docker installation
https://mattermost.atlassian.net/browse/CLD-8147
```release-note
NONE
```
> Fix image mirroring issues

- server/channels/store/sqlstore/shared_channel_store.go
Cherry pick of #28842 on release-10.2.
/cc  @sbishel
```release-note
NONE
```
> Automated cherry pick of #28842

- api/v4/source/channels.yaml
- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
- server/channels/app/channel.go
- server/channels/store/sqlstore/channel_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_store.go
- server/public/model/channel.go
- server/public/model/channel_search.go
- webapp/channels/src/components/admin_console/secure_connections/modals/shared_channels_add_modal.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/channels.test.ts
- webapp/platform/client/src/client4.ts
- webapp/platform/types/src/channels.ts
Cherry pick of #28708 on release-10.2.
```release-note
NONE
```
> Automated cherry pick of #28708

- server/channels/api4/shared_channel_test.go
- server/channels/app/channel.go
- server/channels/app/channel_test.go
- server/channels/app/post.go
- server/channels/app/post_test.go
- server/i18n/en.json
- server/platform/services/sharedchannel/service_api.go
This change prevents the application from creating new DMs and GMs when remote users are involved, and prevents as well new posts from being created into preexisting DMs and GMs with remote users created in previous versions.
https://mattermost.atlassian.net/browse/MM-60971
```release-note
NONE
```
> Forbid users from creating DMs and GMs with remote users

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/components/advanced_text_editor/use_emoji_picker.tsx
- webapp/channels/src/components/advanced_text_editor/use_upload_files.tsx
- webapp/channels/src/i18n/en.json
This change makes the text editor behave similarly to the case of read only channels, in a disabled state and showing a placeholder that indicates that DMs and GMs with remote users are currently not supported.
There is no way to create this type of channels now, but chances are that existing servers have some already, so this is intended to explicitly indicate that those won't work.
https://mattermost.atlassian.net/browse/MM-60971
```release-note
NONE
```
> Disables text editor for DMs and GMs with remote users

- .github/workflows/e2e-fulltests-ci.yml
- webapp/README.md
Fix a typo in the workflow, for actually respecting the `MM_SERVICE_OVERRIDES` variable (herestring instead of heredoc, see [this error](https://github.com/mattermost/mattermost/actions/runs/11406709273/job/31741059739#step:3:117)).
Also improve:
- Fix error condition when running with `REPORT_TYPE=NONE`
- Less verbose parameter descriptions, since the `Run workflow` prompt became really big
https://mattermost.atlassian.net/browse/CLD-8147
```release-note
NONE
```
> CLD-8147 Fix typo

- webapp/channels/src/actions/telemetry_actions.jsx
- webapp/channels/src/components/channel_invite_modal/group_option/group_option.tsx
- webapp/channels/src/packages/mattermost-redux/src/client/rudder.ts
- webapp/channels/src/packages/mattermost-redux/src/constants/index.ts
- webapp/channels/src/packages/mattermost-redux/src/constants/telemetry.ts
- webapp/platform/client/src/client4.test.ts
- webapp/platform/client/src/client4.ts
- webapp/platform/client/src/telemetry.ts
Small PR to have a conversation on how to do frontend telemetry for paid features, @M-ZubairAhmed will also be needing this, so we decided to create a small PR so we work on the same code instead of duplicating efforts.
Also adds a small use case to send telemetry from adding a group to a channel using the "user add modal". (there are more cases when this happens, but with just one we can already check.
Some questions:
- category: is paid_features ok for this? 
- if we want to use this for non-paid features we might need to make a bit more generic and pass the category as well.
- installationID. As far as I can tell, we don't have that info in the front. Should we get it from the backend?
- in trackEvent we send a generic 'event', in trackPaidFeature we send the actual event. Let me know …
> [MM-61193] Create trackFeatureEvent telemetry handler for paid features in web

- server/config/client.go
- server/public/model/config.go
Cherry pick of #28180 on release-10.1.
/cc  @enahum
```release-note
NONE
```
> Automated cherry pick of #28180

- e2e-tests/cypress/tests/integration/channels/system_console/connected_workspaces_management_spec.ts
- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx
- webapp/channels/src/components/admin_console/secure_connections/utils.ts
Connected Workspaces in System Console:
- Remove from scope of Restrict System Admin
- Move to Site Configuration
- Consolidate license checks to `licensedForFeature('SharedChannels')`
- https://mattermost.atlassian.net/browse/MM-61197
- https://mattermost.atlassian.net/browse/MM-60615
|----|----|
| ![Arc 2024-10-21 15 39 41](https://github.com/user-attachments/assets/30b0d5c5-4cea-4b84-be0f-af74286ff31b) | ![CleanShot 2024-10-21 at 16 16 19](https://github.com/user-attachments/assets/352fa053-93e7-4357-8a19-dbc563b4fb37) |
```release-note
NONE
```
> MM-61197, MM-60615: Move Connected Workspaces to Site Configuration

- server/channels/app/metrics.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/public/model/metrics.go
- webapp/channels/package.json
- webapp/channels/src/components/root/performance_reporter_controller.tsx
- webapp/channels/src/utils/desktop_api.ts
- webapp/channels/src/utils/performance_telemetry/platform_detection.ts
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
- webapp/package-lock.json
This is the companion PR for the Desktop App work to provide performance metrics to servers with Prometheus turned on: https://github.com/mattermost/desktop/pull/3165
The changes in this PR allow for the `PerformanceMonitor` on the web app to listen for updates to metrics from the Desktop App. It saves those values and will send them up with the report it makes for web app performance metrics.
This also includes the definitions for CPU and memory usage Prometheus metrics.
These two changes in tandem will allow admins to see CPU/memory usage per process in their Grafana instances.
https://mattermost.atlassian.net/browse/MM-60609
https://mattermost.atlassian.net/browse/MM-60612
```release-note
Add Desktop App performance metrics
```
> [MM-60609][MM-60612] Include Desktop App metrics in PerformanceReporter, add metrics in Prometheus for CPU/Memory usage

- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/desktop_api.ts
When I implemented the Desktop/Web App API, I neglected to get the Web App to call `reactAppInitialized()` when it was done loading to tell the Desktop App to hide the loading screen. This wasn't really noticed initially since the Desktop App will eventually just timeout and hide the loading screen anyways, but this issue made it feel like the app was taking longer to load.
This PR adds calls to `reactAppInitialized()` in the same places we hide the Web App specific loading screen, which makes the app feel a bit snappier.
https://mattermost.atlassian.net/browse/MM-61201
```release-note
Fixed an issue where the Web App would feel slower to load in the Desktop App
```
> [MM-61201] Call reactAppInitialized() when app is done loading for Desktop App

- e2e-tests/playwright/.eslintignore
- e2e-tests/playwright/.prettierignore
- e2e-tests/playwright/support/server/default_config.ts
- e2e-tests/playwright/tests/functional/system_console/desktop_landing.spec.ts
- webapp/platform/types/src/config.ts
- Use isolated `page` instance instead of explicitly using `chrome` so that we can ensure we're testing on the expected browser as defined in Playwright's test projects.
- Make use of page object model
- Updated server's default config and types
Follow up to https://github.com/mattermost/mattermost/pull/28839
Jira https://mattermost.atlassian.net/browse/MM-61126
```release-note
NONE
```
> MM-61126: Follow up to desktop landing page

- webapp/channels/src/actions/views/create_comment.test.jsx
- webapp/channels/src/actions/views/create_comment.tsx
Reverting a breaking change in the semantics of `registerSlashCommandWillBePostedHook` that is causing errors to be surfaced in case a plugin returns an empty object, which is a valid case.
https://github.com/mattermost/mattermost/blob/99a95508d2b1a768ee71ed2e848231bbd2b2200b/webapp/channels/src/plugins/registry.ts#L802-L803
Also adding some [extra checks](https://github.com/mattermost/mattermost-plugin-calls/pull/887) in Calls e2e that could have helped us catch this way sooner.
https://mattermost.atlassian.net/browse/MM-61233
```release-note
Reverted a breaking change in registerSlashCommandWillBePostedHook that caused errors to surface in case an expected empty object is returned.
```
> [MM-61233] Revert breaking change in `registerSlashCommandWillBePostedHook`

- server/channels/app/channel.go
- server/channels/app/post.go
- server/platform/services/sharedchannel/service_api.go
- server/public/model/feature_flags.go
- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/i18n/en.json
Controls de availability of DMs with remote users, effectively gating the logic introduced in https://github.com/mattermost/mattermost/pull/28855 and https://github.com/mattermost/mattermost/pull/28861
https://mattermost.atlassian.net/browse/MM-61265
```release-note
NONE
```
> Adds a feature flag to control availability of DMs in shared channels

- server/channels/app/server.go
- webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
- webapp/channels/src/components/custom_status/date_time_input.tsx
- webapp/channels/src/components/date_time_picker_modal/date_time_picker_modal.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
When developer mode is enabled-
1. Allow creating scheduled post in 1 min time increments,
2. Run the scheduled post processing job every 2 seconds, vs every 5 mins in production
This is to help with QA, local testing and E2E tests
Fixes https://mattermost.atlassian.net/browse/MM-60326
```release-note
none
```
> Handled dev mode

- server/.golangci.yml
- server/channels/utils/fileutils/fileutils_test.go
Fixes https://github.com/mattermost/mattermost/issues/28753
JIRA: [MM-61081](https://mattermost.atlassian.net/browse/MM-61081)
```release-note
```
[MM-61081]: https://mattermost.atlassian.net/browse/MM-61081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix errcheck issues in server/channels/utils/fileutils/fileutils_test.go

- server/channels/app/platform/web_conn_test.go
This test actually tested that there is no race
_if_ session pooling is there. But there is no session pooling
any more so this test is irrelevant.
https://mattermost.atlassian.net/browse/MM-61225
```release-note
NONE
```
> MM-61225: Remove incorrect test

- webapp/channels/src/components/admin_console/secure_connections/modals/shared_channels_add_modal.tsx
Fix text overflow
- https://mattermost.atlassian.net/browse/MM-61127
|----|----|
| ![CleanShot 2024-10-24 at 10 37 03](https://github.com/user-attachments/assets/813f5b9f-c413-45a6-be2a-6afd5fb146f6) | ![CleanShot 2024-10-24 at 14 59 00](https://github.com/user-attachments/assets/c5473666-e7c0-4a26-83d1-a4f30f06efab) |
```release-note
NONE
```
> MM-61127: Fix text overflow in channels input for SC

- webapp/channels/src/components/more_direct_channels/index.test.tsx
- webapp/channels/src/components/more_direct_channels/index.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
Adds a filter for remote users, so they are not included in Direct/Group Message modals if Direct/Group messages are not supported.
Fixes https://mattermost.atlassian.net/browse/MM-61152
Fixes https://mattermost.atlassian.net/browse/MM-61202
```release-note
NONE
```
> filter remote users if remote dms not supported

- webapp/channels/src/components/admin_console/secure_connections/modals/shared_channels_add_modal.tsx
Cherry pick of #28952 on release-10.2.
```release-note
NONE
```
> Automated cherry pick of #28952

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
We assumed the elements were strings in case a list of `user_ids` is passed in. Now, we are checking for the right type and also running validation. 
Of note, we are failing the request in case a single element is not valid. I think this is better than ignoring them and proceeding with whatever is left, but we are not very consistent on this front, so I am happy to reconsider if you have concerns.
https://mattermost.atlassian.net/browse/MM-60886
```release-note
NONE
```
> [MM-60886] Fix TypeAssertionError in `api4.addChannelMember`

- webapp/channels/src/components/section_notice/index.test.tsx
- webapp/channels/src/components/section_notice/index.tsx
- webapp/channels/src/components/section_notice/section_notice.scss
- webapp/channels/src/components/section_notice/section_notice_button.tsx
- webapp/channels/src/components/section_notice/types.d.ts
- webapp/channels/src/components/section_notice/types.ts
This PR is to clean the diff from https://github.com/mattermost/mattermost/pull/28334
This PR adds the "hint" section notice, the ability to add trailing, leading and loading icons to the buttons, and some minor refactoring.
NONE
```release-note
NONE
```
> Improvement on Section Notice

- api/package.json
Fix typo in the word repository in api/package.json
N/A
```release-note
NONE
```
> Fix typo in the word repository in api/package.json

- .github/workflows/e2e-fulltests-ci.yml
The `gh` tool unfortunately doesn't like booleans in its JSON payload, when triggering Workflows.
This means we must use strings for controlling if Cypress and Playwright will run: the implication is that we  must compare those inputs with the `"true"` value, instead of just checking for falsity (which would be the wrong thing to do, since a non-empty string always evaluates to `true` in comparisons, even if its value is the string `false`)
```release-note
NONE
```
> E2E fix: use string for cypress/playwright selector

- api/v4/source/introduction.yaml
I've added a new section to the API docs to show our common parameters in more detail, and I added `per_page` at the request of a community member.
https://mattermost.atlassian.net/browse/MM-59396
Closes https://github.com/mattermost/mattermost/issues/27574
```release-note
NONE
```
> [MM-59396] Update API docs to show common parameters, added per_page docs

- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/i18n/en.json
It looks like the changes in https://github.com/mattermost/mattermost/pull/25406 (specifically to the `renderBanner` method of `AdminSchemaSettings`) made it so that system console banner text couldn't be both translated and contain Markdown. Since we want to get rid of Markdown in translated text anyway, I just went ahead and got rid of that. 
I left the code in `AdminSchemaSettings` that handles `label_markdown` to avoid conflicts with Daniel's system console refactoring and because plugins may still use it, but now it's not referenced by the web app any more. Ideally, we'd probably remove it from the type definitions used for the `admin_definitions.tsx` to stop web app devs from using it.
MM-61380
```release-note
Fixed link in Compliance Monitoring page banner
```
> MM-61380 Fix link in Compliance Monitoring page banner

- webapp/channels/src/components/custom_status/date_time_input.test.tsx
- webapp/channels/src/components/custom_status/date_time_input.tsx
When selecting a DST date and a time that is shifted by the DST end, getTimeInIntervals goes into infinite loop
Fixes https://github.com/mattermost/mattermost/issues/25352
Jira https://mattermost.atlassian.net/browse/MM-55192
```release-note
NONE
```
> MM-55192: Fix datepicker hang on DST dates

- server/channels/app/scheduled_post.go
- server/public/model/websocket_message.go
- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/utils/constants.tsx
MM-60147 - ws events on delete scheduled posts
https://mattermost.atlassian.net/browse/MM-60147
https://github.com/user-attachments/assets/b0d157c5-b016-4ac2-8590-2e59118d8014
```release-note
NONE
```
> MM-60147 - ws events on delete scheduled posts

- server/build/docker-compose.common.yml
- server/docker-compose.makefile.yml
After we upgraded minio version, the WebUI (e.g., login page) is not exposed on port 9000 any longer but gets assigned a random port that is not forwarded correctly, so it's tricky to access, especially on non-Linux systems. Forcing the port to be stable (using 9002 since 9001 is already used by inbucket) and exposing it solves it.
```release-note
NONE
```
> Fix minio Web UI access

- webapp/channels/src/components/edit_post/index.ts
Fixed a bug where non-admin user wasn't able to edit their scheduled post.
The issue was it was incorrectly computing whether the user is the author of the scheduled post or not.
Fixes https://mattermost.atlassian.net/browse/MM-61520
```release-note
None
```
> MM-61520 - Fixed a bug where non-admin user wasn't able to edit their scheduled post

- server/channels/app/channel.go
- server/channels/app/notification.go
- server/channels/app/post.go
- server/platform/services/telemetry/telemetry.go
Added events for:
- view shared channel
- mention a remote user
- post a message in a shared channel
Not added:
- DM a remote user as that has been removed from scope of Shared channels
[MM-59363](https://mattermost.atlassian.net/browse/MM-59363)
```release-note
NONE
```
[MM-59363]: https://mattermost.atlassian.net/browse/MM-59363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-59363] Shared channel event telemetry

- server/cmd/mmctl/commands/utils_unix.go
This fixes mmctl build for FreeBSD.
Previous build error was:
```
...
github.com/pelletier/go-toml/v2
github.com/spf13/viper/internal/encoding/toml
github.com/spf13/viper
github.com/mattermost/mattermost/server/v8/cmd/mmctl/commands
cmd/mmctl/commands/channel.go:617:13: undefined: getConfirmation
cmd/mmctl/commands/config.go:466:13: undefined: getConfirmation
cmd/mmctl/commands/init.go:241:12: undefined: checkValidSocket
cmd/mmctl/commands/integrity.go:81:13: undefined: getConfirmation
cmd/mmctl/commands/saml.go:58:13: undefined: getConfirmation
cmd/mmctl/commands/team.go:183:13: undefined: getConfirmation
cmd/mmctl/commands/team.go:304:13: undefined: getConfirmation
cmd/mmctl/commands/user.go:670:13: undefined: getConfirmation
cmd/mmctl/commands/user.go:729:13: undefined: getConfirmation …
```
> Fix mmctl build for FreeBSD

- webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
- webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.test.tsx
- webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx
- webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.test.tsx
- webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/constants.tsx
This PR adds the logic to store in the user preferences the most recently used custom time for scheduled messages so it can be shown in the available options for picking a time for a new schedule message.
https://mattermost.atlassian.net/browse/MM-60123
https://github.com/user-attachments/assets/12fe8372-3e60-4a0a-8a6c-c50ea900285a
```release-note
NONE
```
> MM-60123 - store most recently custom time

- server/channels/app/app_iface.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/scheduled_post.go
- server/channels/app/scheduled_post_job.go
This PR sends a WS event when  a scheduled post is send as a post by de scheduled post job.
https://mattermost.atlassian.net/browse/MM-61068
```release-note
NONE
```
> MM-61068 - send WS event on scheduled message job send

- webapp/channels/src/components/file_preview_modal/image_preview.tsx
- webapp/channels/src/components/size_aware_image.tsx
This PR fixes the issue where SVG files without width and height attributes failed to display in Chrome and Safari browsers. The fix applies conditional inline styling to SVG images in the ImagePreview and SizeAwareImage components, ensuring that images display with defined width and auto height.
- Adds conditional style attributes for SVG files, setting width from file dimensions when available and height to auto.
- Uses `getFileType` and `FileTypes.SVG` utilities to limit the style application to SVG files only.
**QA steps**
1. **Upload SVG File in Channel**:
- Post an SVG file that does not have a set width and height in a channel.
- Verify that the SVG displays correctly in the channel view.
2. **Open SVG File in File Preview Modal**:
- Click on the posted SVG file to open it in the …
> MM-44470 Fix SVG without width not displaying

- server/config/utils.go
- server/config/utils_test.go
Cherry pick of #29029 on release-10.1.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #29029

- .github/workflows/server-test-template.yml
- server/channels/app/bot.go
- server/channels/app/platform/helper_test.go
- server/channels/app/shared_channel.go
- server/channels/app/user.go
The Store variable was written to _after_ the server
started which was causing the race.
We simply move it to before we start the server.
While we are here, we fix yet another race condition
which was unrelated, but doing it in one sweep. This
was related to the user props access. When a user is updated,
there was 3 ws events that get sent out, 2 were deep-copied
whereas 1 was not. This led to race condition in postgres
binary-param mode where we were trying to set the user props.
https://mattermost.atlassian.net/browse/MM-61700
```release-note
NONE
```
> MM-61700: Fix race conditions from web_hub initialization

- server/Makefile
Backporting some fixes included in the latest v0.29 dot release.
```release-note
Prepackage Calls v0.29.4
```
> Prepackage Calls v0.29.4 in `release-9.11`

- server/channels/api4/post_test.go
- server/channels/api4/user_test.go
- Fix broken `TestGetPost`: https://github.com/mattermost/mattermost/pull/29201 introduced additional error checks to that test. It turns out the test was flaky, but we didn't know that until the additional error check kicked in. Fixing the test.
- Skip flaky test `TestPromoteGuestToUser/websocket_update_user_event`. Ticket: https://mattermost.atlassian.net/browse/MM-61736
NONE
```release-note
NONE
```
> Fix broken TestGetPost

- webapp/channels/src/components/custom_status/date_time_input.tsx
- webapp/channels/src/utils/datetime.ts
Made following changes to date time picker common component (used in custom status, post reminder and scheduled messages)-
1. Show date in date picker in user's localized format
2. Don't reset time when changing date.
Fixes https://mattermost.atlassian.net/browse/MM-61697
Fixes https://mattermost.atlassian.net/browse/MM-61720
Fixes https://mattermost.atlassian.net/browse/MM-61719
```release-note
none
```
> [MM-61697] Date time picker - use localized date format and don't reset time when changing dates

- server/channels/api4/post_test.go
- server/channels/api4/user_test.go
Cherry pick of #29228 on release-10.3.
/cc  @hanzei
```release-note
NONE
```
> Automated cherry pick of #29228

- server/.golangci.yml
Removed a line from the golangci.yml file that was excluding a specific go file from linting. This will now allow the linter to check this file for any potential issues.
Fixes https://github.com/mattermost/mattermost/issues/29107
Jira https://mattermost.atlassian.net/browse/MM-61503
```release-note
NONE
```
> MM-61503 Updated golangci.yml configuration

- server/channels/api4/channel_bookmark_test.go
https://hub.mattermost.com/private-core/pl/tghzisj6ubnd9xneurki1tw1zh
https://mattermost.atlassian.net/browse/MM-61779
==
```release-note
NONE
```
> [MM-61779] Skip flaky TestEditChannelBookmark/a_websockets_event_should_be_fired_as_part_of_editing_a_bookmark

- server/.golangci.yml
- server/channels/testlib/helper.go
Fixed `errcheck` lint errors in `server/channels/testlib/helpder.go`
Fixes https://github.com/mattermost/mattermost/issues/28752
```release-note
NONE
```
> GH-28752 fix errcheck lint issues in server/channels/testlib/helper.go

- server/channels/app/scheduled_post_job.go
- server/channels/app/scheduled_post_job_test.go
- server/i18n/en.json
- webapp/channels/src/components/custom_status/date_time_input.tsx
Enhance the message details for the system-bot message sent during the failed scheduled messages event.
https://mattermost.atlassian.net/browse/MM-61731
```release-note
NONE
```
> MM-61731 - enhance failed sent system bot message

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/components/root/root.test.tsx
- webapp/channels/src/components/root/root.tsx
- 22169fed7537104d962c0f9f00d69618d9efd466 fixes an issue in system console where a theme change from another tab would cause `<Root/>` to apply the new theme when it shouldn't be. System Console is statically themed in `denim`. It does this with `resetTheme()` on mount, and `applyTheme(currentTheme)` on dismount. 
- f982b7095d54cdf671b6aad5267c97deb6f9cd95 fixes the onboarding tasklist theming when in system console.
- 43e98aa3793ebdf364a887768a75323e8edb8ea1 fixes an erroneous/404 `fetchMyCategories` request in system console when user preferences are changed from another tab.
- d54c518ae3a10f6d3b715fbc4b398f887a52cd36 prevents applying the theme twice when loading system console directly
- https://mattermost.atlassian.net/browse/MM-61733
1. Open system console, change theme from a …
> MM-61733: Fix system console theme stability

- webapp/channels/src/components/drafts/drafts.scss
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
This PR adds the required logic for the scheduled messages feature respond in a show/hide way when the product is licensed or not. With this PR, the feature will show immediately after the product has been licensed, and will hide in case the license expires or gets removed.
https://mattermost.atlassian.net/browse/MM-61536
https://github.com/user-attachments/assets/dd457850-24e3-4fdb-91b9-5334fdc5e804
```release-note
NONE
```
> MM-61536 - enable schmsgs feature on license upgrade

- .github/workflows/esrupgrade-common.yml
- .github/workflows/server-ci-template.yml
There is no need to use 8 core runners to support our build . 
Testing is using the default free runners 
```release-note
NONE
```
> Disable 8 core runners for mattermost build

- webapp/channels/src/i18n/imports.ts
- webapp/scripts/gen_lang_imports.mjs
After merging https://github.com/mattermost/mattermost/pull/29009 I noticed `tsc` started throwing with:
```
error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.
```
Adding the explicit annotation seems to fix it.
```release-note
NONE
```
> Add type annotation to generated language files map

- server/channels/store/storetest/scheduled_post_store.go
There were couple of errors in the test:
1. UpdatedScheduledPost will automatically
set the ProcessedAt to now internally inside
toUpdateMap. So setting the value from outside
has no effect.
2. The bug was that if it took more than a
milisecond to capture the time, and then
do the internal call, then the Get call
will have a higher value and therefore fail.
Since UpdatedScheduledPost doesn't return
an updated post, so there is no need
to compare the timestamps at all.
```release-note
NONE
```
> Fix flaky test TestScheduledPostStore

- .github/workflows/mmctl-test-template.yml
- .github/workflows/server-test-template.yml
- Check retries when generating report with `action-junit-report`. This fixes the discrepancy in generating unit test report with the recent upgrade (by dependabot) of `mikepenz/action-junit-report`.
- Upgraded to latest v5
- Note: `steps.report.outputs.flaky_summary != '<table><tr><th>Test</th><th>Retries</th></tr></table>'` this workaround means the table for flaky test is empty.
Set the following config to `true`:
- `check_retries` to consider results of retry
- `flaky_summary` to include flaky tests in summary. However,  to generate, it requires `include_passed` to be true since other retried tests may have passed.
none
```release-note
NONE
```
> Check retries when generating report with action-junit-report

- server/channels/api4/post_test.go
- server/channels/app/platform/options.go
We don't clear the Redis cache for every test.
This can cause issues because the cache is shared
across test. We fix that with this PR.
```release-note
NONE
```
> Fix flaky TestCreatePost and others

- server/channels/api4/post.go
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
- webapp/platform/types/src/schedule_post.ts
Added precense check for scheduled posts before accessing error code.
ideally scheduled posts there will not be null, but I suspect it can be in case of unstable websocket connection of lost messages.
Fixes https://mattermost.atlassian.net/browse/MM-61854
```release-note
none
```
> Added precense check for scheduled posts before accessing error code

- server/enterprise/message_export/message_export.go
- server/enterprise/message_export/message_export_test.go
- server/enterprise/message_export/shared/shared.go
- server/enterprise/message_export/shared/shared_test.go
- server/enterprise/message_export/worker.go
- server/enterprise/message_export/worker_test.go
- server/public/model/job.go
- This refactoring/simplification felt very good. It's been bugging me for a long time.
- It allows the CLI to do a quick conversion from `job.Data` -> stringMap and post the status of the job to the db, which was a big request from our customer in yesterday's call.
- CLI side PR: https://github.com/mattermost/mattermost-compliance-export/pull/29
- https://mattermost.atlassian.net/browse/MM-61755
Will be added to the feature branch release note.
```release-note
NONE
```
> MM-61755 - Simplifying and Support reporting to the db from the CLI

- server/channels/app/channel_test.go
We were writing to the `err` variable which was declared before. Fixed that to use the correct variable.
```release-note
NONE
```
> Fix race condition in app/channel_test.go

- webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.test.tsx
- webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx
- webapp/channels/src/components/drafts/drafts.tsx
- webapp/channels/src/components/drafts/drafts_illustration.tsx
- webapp/channels/src/components/drafts/placeholder_scheduled_post_title/placeholder_scheduled_posts_title.tsx
- webapp/channels/src/i18n/en.json
This PR adds the logic to hide the action buttons to non-admin users on scheduled post that were created on channels that the user does not have permissions to.
https://mattermost.atlassian.net/browse/MM-61830
Before:
https://github.com/user-attachments/assets/f423260f-26ac-4df5-89f0-1710beef840d
After:
https://github.com/user-attachments/assets/9e6c96ae-20ad-4054-905d-99a026edf64b
```release-note
NONE
```
> MM-61830 - hide actions to no permissions channels

- e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_1_spec.js
- e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_2_spec.js
https://github.com/mattermost/mattermost/pull/29328 included a fix that improved on System Console test flakiness. Some tests were previously demoted due to that: now that the root cause has been fixed, we can add those back in.
https://mattermost.atlassian.net/browse/CLD-8537
```release-note
NONE
```
> Add fixed testcase back in

- webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
This PR sets the role to none when creating the react-boostrap modal. Removing the prop also causes the outter div to have role='dialog' so the best shot is to set the role='none' and keep the role='dialog' in the inner div element which is set automatically. Screen readers should work fine with this approach. 
We should potentially do this with all the other modal creations, but let's see how the CI behaves with this change, not sure if there are parts of the tests relying on this role for grabbing elements.
Again, facing react-boostrap limitation in terms of usability improvements.
https://mattermost.atlassian.net/browse/MM-61643
Before:
After:
```release-note
NONE
```
> MM-61643 - set role to none since react-boostrap set role='dialog' automagically

- webapp/channels/src/components/channel_header/channel_header_title_favorite.test.tsx
- webapp/channels/src/components/channel_header/channel_header_title_favorite.tsx
This PR makes sure that when the Fav Icon in a channel gets focus and then enter pressed to toggle the favorite state, the focus will remain in the button, allowing the toggle functionality to work correctly via keyboard.
https://mattermost.atlassian.net/browse/MM-61586
https://github.com/user-attachments/assets/05d18d67-ac0d-4c11-a856-383f9015ede6
```release-note
NONE
```
> MM 61586 - fix fav icon accessibility focus problem

- server/.golangci.yml
- server/channels/app/platform/link_cache.go
- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
Fixes errcheck issues in `server/channels/app/platform/link_cache.go`
Fixes subsequent errcheck issues in `server/channels/app/post_metadata.go`
Fixes subsequent errcheck issues in `server/channels/app/post_metadata_test.go`
Fixes  [#29335](https://github.com/mattermost/mattermost/issues/29335)
Jira  [https://mattermost.atlassian.net/browse/MM-61766](https://mattermost.atlassian.net/browse/MM-61766)
```release-note
NONE
```
> [MM-61766] Fix errcheck issues in server/channels/app/platform/link_cache.go

- e2e-tests/cypress/tests/integration/channels/channel/browse_public_channels_spec.ts
- e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/last_viewed_spec.ts
- e2e-tests/cypress/tests/integration/channels/messaging/message_draft_with_attachment_then_switch_channel_spec.js
- e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_cloud_spec.js
This PR:
- Stabilizes some testcases: verifies that an expected page has fully been loaded, instead of relying purely on the timeout
- Demotes an unstable testcase
Fixes implemented after reviewing the videos from today's failures in the daily cloud tests: https://automation-dashboard.vercel.app/cycle/11964438064_1-master-daily-cloud-ent
https://mattermost.atlassian.net/browse/CLD-8301
```release-note
NONE
```
> Stabilize and demote tests

- e2e-tests/playwright/support/ui/components/global_header.ts
- e2e-tests/playwright/tests/functional/channels/search/search_box_suggestions.spec.ts
- webapp/channels/src/components/new_search/search_box.tsx
Fix regression where search suggestion would break when using uppercase letters.
Searching for `In:Off` and pressing enter on the `off-topic` channel would result in the textbox containing `In:Offoff-topic ` instead of `In:off-topic`
https://mattermost.atlassian.net/browse/MM-61969
N/A
```release-note
NONE
```
> [MM-61969] Fix regression where search suggestion would break when using uppercase letters

- server/channels/app/metrics.go
- server/einterfaces/metrics.go
- server/einterfaces/mocks/MetricsInterface.go
- server/enterprise/metrics/metrics.go
- server/public/model/metrics.go
- server/public/model/metrics_test.go
- webapp/channels/src/components/initial_loading_screen/initial_loading_screen_class.ts
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/team_controller/team_controller.tsx
- webapp/channels/src/utils/performance_telemetry/index.ts
- webapp/channels/src/utils/performance_telemetry/reporter.test.ts
- webapp/channels/src/utils/performance_telemetry/reporter.ts
Page load is one of the metrics that we track and present
to MLT. However, in its current form, it is not very
actionable because it also contains the network latency.
We split the whole metric into these parts:
startTime
|
responseStart = TTFB
|
responseEnd = TTLB
|
domInteractive = Start of processing phase
|
loadEventEnd = Load complete
|
splashScreenEnd = Splash screen has finished and MM is fully interactive
This gives us better visibility into exactly
which phase in the load process is slow.
Some actionable points:
1. startTime - domInteractive - out of our control. Dependent on network.
2. domInteractive - loadEventEnd is mainly the time spent in parsing and
processing JS. So any increase there can be attributed to increase
in JS payload.
3. loadEventEnd - splashScreenEnd is mainly …
> MM-61886: Add actionable page navigation metrics

- server/go.mod
- server/go.sum
- server/platform/services/cache/provider.go
While investigating code paths during
Redis downtime, I found out that the library
by default retries indefinitely for read commands.
This leads to it being stuck in a loop
while trying to read anything from Redis.
We fix that by disabling retry.
Secondly, we adjust the ConnWriteTimeout
value slightly from its default of 10s
which is a bit too high for normal working
conditions.
Ref: https://github.com/redis/rueidis/issues/680
```release-note
NONE
```
> Improve Redis failure modes

- server/Makefile
Prepackaging Calls v1.3.1 in the upcoming v10.0 dot release.
```release-note
Prepackage Calls v1.3.1
```
> Prepackage Calls v1.3.1 in v10.0

- server/Makefile
Prepackaging Calls v1.3.1 in the upcoming v10.2 dot release.
```release-note
Prepackage Calls v1.3.1
```
> Prepackage calls v1.3.1 in 10.2

- server/Makefile
Prepackaging Calls v1.3.1 in the upcoming v10.1 dot release.
```release-note
Prepackage Calls v1.3.1
```
> Prepackage Calls v1.3.1 in v10.1

- server/Makefile
Prepackaging Calls v1.3.1 in the upcoming v10.3 dot release.
```release-note
Prepackage Calls v1.3.1
```
> Prepackage calls v1.3.1 in 10.3

- webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/updates.test.ts
- webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/updates.ts
The 'Server Updates' section of 'Workspace Optimizations' in the system console was not comparing version numbers correctly, particularly on double digit version numbers. For example '10.2.0' was returning as an older version than '9.1.0'.
I fixed it by ensuring we were doing proper numeric comparisons. Additionally we had no test coverage so I added those as well.
https://mattermost.atlassian.net/browse/MM-62030
n/a
```release-note
Fix incorrect reporting in 'Server Updates' section in  'System Console' -> 'Workspace Optimizations'
```
> MM-62030 Fix server update message not handling mutli-digit version numbers

- server/public/model/config.go
In Cloud environments where `ExperimentalSettings.RestrictSystemAdmin` are set, any setting that is attempted to be updated with an access type of `write_restrictable` will be silently thrown out, and set to `null`. Cloud-proper environments (ie, those created in the CWS installation group) will have this `RestrictSystemAdmin` setting set, so you're unable to edit the `ExperimentalAuditSettings.AdvancedLoggingJSON` config through the system console. 
This PR removes `write_restrictable` from the setting - it's still only set by system admins, but can now be set in Cloud as well. 
https://mattermost.atlassian.net/browse/CLD-8605
```release-note
None
```
> [CLD-8605] Remove write_restrictable from AdvancedLoggingJSON

- server/Makefile
Prepackaging Calls v1.3.2 in the upcoming v10.0 dot release.
```release-note
Prepackage Calls v1.3.2
```
> Prepackage Calls v1.3.2 in v10.0

- server/Makefile
Prepackaging Calls v0.29.6 in the upcoming v9.11 dot release.
```release-note
Prepackage Calls v0.29.6
```
> Prepackage Calls v0.29.6 in v9.11

- server/Makefile
Prepackaging Calls v1.3.2 in the upcoming v10.1 dot release.
```release-note
Prepackage Calls v1.3.2
```
> Prepackage Calls v1.3.2 in v10.1

- server/Makefile
Prepackaging Calls v1.3.2 in the upcoming v10.2 dot release.
```release-note
Prepackage Calls v1.3.2
```
> Prepackage Calls v1.3.2 in v10.2

- server/channels/app/platform/license.go
[A Sentry crash report](https://mattermost-mr.sentry.io/issues/6083616033/?project=5212327&referrer=webhooks_plugin) showed that dereferencing `license.Features.Users` in `SaveLicense` can end up in a `panic`, so we add some defense code around it.
Speaking of tests: is there a way I can generate a license on the fly for test purposes? I want to generate one with `license.Features` being nil and another with `license.Features.Users` being nil, but not sure if that's even possible without asking other team to do it for us.
https://mattermost.atlassian.net/browse/MM-61992
--
```release-note
NONE
```
> MM-61992: Verify license.Features.Users is not nil

- webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
- webapp/channels/src/components/emoji_picker/utils/index.test.ts
- webapp/channels/src/components/emoji_picker/utils/index.ts
This removes the search input text lowercasing from the `EmojiPickerSearch` component, where it is used as the text displayed to the user.
Instead, filter lowercasing is done in the `getFilteredEmojis` function to make emoji search case-insensitive.
Fixes https://github.com/mattermost/mattermost/issues/29362
Jira https://mattermost.atlassian.net/browse/MM-61946
|  Before  |  After  |
|----|----|
| ![image](https://github.com/user-attachments/assets/ca6703e8-d935-46c3-b3ad-450cc7b7aef0) | ![image](https://github.com/user-attachments/assets/713a8c7c-6204-49c7-81de-8673b3e91390) |
(Before, the text in the input field didn't accept uppercase letters)
```release-note
The search input field in the emoji picker now accepts uppercase letters.
```
> [MM-61946] Don't change the emoji picker search input text case

- webapp/channels/build/emoji/make_emojis.mjs
- webapp/channels/src/sass/components/_emojisprite.scss
- webapp/channels/src/sass/components/_emoticons.scss
Fixes a CSS issue in an upcoming Firefox version. Currently, a `-moz` prefixed `transform: scale` is applied together with non-standard `zoom` rule, causing them to be both applied at the same time, which makes emoticon sprites too small on Firefox 133.
Instead of the vendor-prefixed standard rule combined with a non-standard one, it is better to use the standard counterpart of `zoom`, which is `transform: scale`.
Original context of the issue can be found [here](https://github.com/mattermost/mattermost-webapp/pull/11936). However, as of the latest version of Chrome and Firefox, there does not seem to be a noticeable difference between `transform: scale` and `zoom` in terms of "blurriness", so non-standard `zoom` rule can probably be replaced with `transform: scale`.
Fixes …
> Use standard CSS rules to resize emoticons

- .github/workflows/e2e-fulltests-ci.yml
- e2e-tests/cypress/tests/integration/channels/search_filter/input_spec.js
This PR changes the behaviour of the full E2E tests to match the smoketests: if there is at least one failing testcase, the status check of Cypress or Playwright will now be `Failure`.
In addition, two unstable tests have been demoted.
https://mattermost.atlassian.net/browse/CLD-7077
```release-note
NONE
```
> Enforce 0-failures for E2E tests

- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/status.go
- server/channels/store/localcachelayer/layer.go
- server/channels/store/localcachelayer/layer_test.go
We were incorrectly not broadcasting status cache updates
inspite of that being an LRU cache.
We were also not doing it for profilesInChannel cache.
Now we fix it by properly checking the invalidationEvent
which is something local to the cache itself rather
than the cache provider.
https://mattermost.atlassian.net/browse/MM-62077
```release-note
NONE
```
> MM-62077: Fix cluster broadcast for LRU caches

- server/channels/app/platform/web_conn.go
When opening a websocket, we send a HELLO event that contains the server's hostname. Prior to this PR, if the server is unable to report the hostname we logged an error. Now, we log a warning. Additionally, we now include the user ID and connection ID in the log event.
https://mattermost.atlassian.net/browse/MM-62105
```release-note
NONE
```
> MM-62105 use WARN log level when ws can't report hostname

- server/channels/api4/post_test.go
- Failing test: `TestCreatePost/Create_posts_without_the_USE_CHANNEL_MENTIONS_Permission_-_returns_ephemeral_message_with_mentions_and_no_ephemeral_message_without_mentions`
- Failing job: https://github.com/mattermost/mattermost/actions/runs/12177120268/job/33964435856 
- Output:
```
2024-12-05T09:56:51.7489258Z     post_test.go:171: 
2024-12-05T09:56:51.7490091Z         	Error Trace:	/mattermost/server/channels/api4/post_test.go:171
2024-12-05T09:56:51.7491131Z         	Error:      	Should have received ephemeral message event and not timedout
2024-12-05T09:56:51.7493041Z         	Test:       	TestCreatePost/Create_posts_without_the_USE_CHANNEL_MENTIONS_Permission_-_returns_ephemeral_message_with_mentions_and_no_ephemeral_message_without_mentions
2024-12-05T09:56:51.7494925Z --- FAIL: …
```
> Skip flaky test TestCreatePost/Create_posts_without_the_USE_CHANNEL_MENTIONS_Permission

- server/channels/api4/outgoing_oauth_connection_test.go
Skipping all outgoing oauth connection tests until we figure out what changed/what's wrong with them.
Please merge once approved.
https://mattermost.atlassian.net/browse/MM-61690
```release-note
None
```
> tests: skip flaky outgoing oauth connection tests

- server/channels/api4/license.go
While investigating https://mattermost.atlassian.net/browse/MM-61529,
I noticed that we weren't adding the internal error which made
it impossible to understand what was really happening.
```release-note
NONE
```
> Adding error context in license validation

- server/channels/api4/post_test.go
https://github.com/mattermost/mattermost/pull/29214 fixed the
race condition in web_hub initialization.
The failure in the test is strange because there's no log
for the websocket request. It's as if th.CreateWebSocketClientWithClient()
never got called at all.
I am re-arranging the lines so that even if it fails,
the table rename happens anyways. But overall, I don't see
any reason for the failure.
https://mattermost.atlassian.net/browse/MM-61698
```release-note
NONE
```
> MM-61698: Unskip TestWebHubCloseConnOnDBFail

- server/channels/api4/post_test.go
Finally I figured out why the log message for
/api/v4/websocket does not appear. It is because
the log gets generated only when the request returns,
and for websockets, the request doesn't return
until the client closes. And because we were closing
the client in a defer clause, the flushing of the logger
would happen before closing the client, therefore
leading to a race condition of the log not appearing
from time to time.
https://mattermost.atlassian.net/browse/MM-61698
```release-note
NONE
```
> MM-61698: Fix TestWebHubCloseConnOnDBFail properly

- server/channels/api4/post.go
- server/channels/api4/post_test.go
A change we made to permissions accidentally removed the ability for sysadmins to view posts for DMs they're not in. This PR fixes that permission for the particular call needed.
https://mattermost.atlassian.net/browse/MM-62092
```release-note
Fixed an issue where system admins couldn't pull posts in from DMs they're not in
```
> [MM-62092] Allow system admins to pull posts in from DMs they're not in

- server/channels/store/sqlstore/channel_store.go
When we go to view archived channels via the `/deleted` API, it was noticed that deleted DMs were coming through in the response. These aren't usually able to be created through the system, but it's possible that an admin may manually mark channels with a `DeleteAt` through the DB. This also caused an issue with the Browse Channels dialog where it would try to grab member counts for channels the user couldn't access.
This PR ensures that the API only returns channels that can be archived, to avoid the permissions issue and to avoid leaking any DMs/GMs by accident.
https://mattermost.atlassian.net/browse/MM-62202
https://mattermost.atlassian.net/browse/MM-62086
```release-note
Fixed an issue where DMs/GMs with a `DeleteAt` flag in the database might cause issues with a couple APIs
```
> [MM-62086][MM-62202] Don't include deleted DMs/GMs when returning archived channels

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/packages/mattermost-redux/src/actions/teams.ts
At one point, our unread mentions relied solely on the team-level unreads, which when we introduced CRT, caused a sync issue where we would pull down unreads for a specific team, and it would overwrite the ones that included the unreads/mentions for DMs and GMs.
A bit later on we changed the way we handled unreads/mention counts for other areas of the system, opting for a reducer that combined all of the unreads and used the much more robust channel-level unreads. However, we never went back and reverted the original fix that originally patched this issue. The lack of syncing we were caused the team unreads for the current team (still used by the sidebar to indicate the count ONLY for that team, not including DMs/GMs) caused a mismatch between the threads viewer/link and the team sidebar. …
> [MM-61958][MM-53174][MM-60880] Always fetch team unreads for current team on reconnect

- server/channels/api4/post_test.go
This test failed because TestWebHubCloseConnOnDBFail failed
and therefore the ChannelMembers table failed to be
renamed back.
We can see that in the logs:
```
teams","request_id":"sdxjxsd1wibd9mb7kc3ixj6g1w","ip_addr":"127.0.0.1","user_id":"afw9qqjh7pnddqakraxnjf1oph","method":"POST","user_id":"afw9qqjh7pnddqakraxnjf1oph","team_id":"bocubwmn4jyrmc1p9uxrc4pwfc","error":"JoinDefaultChannels: Unable to save direct channel., channel_members_save: Error 1146 (42S02): Table 'dbrt3jzcosj3nb8g6mgwmqyss9rh.ChannelMembers' doesn't exist"}
{"timestamp":"2024-11-10 13:52:34.260 Z","level":"error","msg":"Error while invalidating channel member cache","caller":"platform/web_hub.go:524","user_id":"afw9qqjh7pnddqakraxnjf1oph","error":"failed to find ChannelMembers, TeamScheme and ChannelScheme data: …
```
> MM-61699: Improve TestDeletePostEvent

- server/enterprise/elasticsearch/common/indexing_job.go
- server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
- server/enterprise/elasticsearch/elasticsearch/indexing_job.go
- server/enterprise/elasticsearch/opensearch/indexing_job.go
- server/enterprise/elasticsearch/opensearch/opensearch.go
- server/i18n/en.json
After https://github.com/mattermost/mattermost/pull/29209, there were some more
strings which were left out. Sending another PR to fix all of them.
The config validation strings are made generic for simplicity, because they
are called before the search backend is started, and even though you could
check for the config setting, it forces the code order. Therefore, changed
the words to just say "Search" for simplicity.
I tried to use Aider initially for a little while, but ended up fighting
a lot with the search/replace and having to repeat myself over and over again
to get it to do the refactoring. Eventually gave up and did rest of the changes
myself.
```release-note
NONE
```
> [Aider assisted]: Templatize rest of the elasticsearch translation strings

- .github/workflows/e2e-fulltests-ci.yml
- e2e-tests/cypress/tests/integration/channels/enterprise/oauth/oauth_spec.ts
- e2e-tests/cypress/tests/integration/channels/integrations/builtin_commands/user_status_commands_spec.js
- e2e-tests/cypress/tests/integration/channels/mark_as_unread/leave_channel_unread_spec.js
- e2e-tests/cypress/tests/integration/playbooks/channels/channel_header_spec.js
- e2e-tests/cypress/tests/support/index.js
This PR:
- Introduces conditional logic for the `testcase_failure_fatal` flag: if we're running tests known to be `UNSTABLE`, then we don't fail the status checks on testcase failure, since the failures are expected.
- Stabilizes two testcases:
* `leave_channel_unread_spec.js` ([sample failure](https://automation-dashboard.vercel.app/cycle/12292405181_1-e978003-pr-onprem-ent))
* `user_status_commands_spec.js` ([sample failure](https://automation-dashboard.vercel.app/cycle/12287775716_1-master-daily-cloud-ent))
```release-note
NONE
```
> Daily E2E test fixes

- webapp/channels/src/components/root/root.test.tsx
One of the tests in this file fails on my laptop because of a series of weird interactions with my local environment. I think what's happening is that, despite our tests using Nock to intercept HTTP requests, the library seems to still make a real request, but that's intercepted by Pi-hole (my ad blocker) which redirects it back to localhost, and then the request runs into an invalid certificate because of the HTTPS certificate I use on my local server.
Anyway, that can be fixed by just mocking all of Rudder's SDK instead of the one method that we care about in this test.
```release-note
NONE
```
> Change how Rudder is mocked in a test

- server/i18n/en.json
Harrison requested to bump the versions to use some new accessibility features of the browser.
```release-note
Updated minimum Safari version to 17.4+ and minimum Firefox version to 119+.
```
> Update minimum supported Safari and Firefox versions

- server/channels/store/sqlstore/channel_store.go
Cherry-pick of #29572 to `release-9.11`
Modified as the code to do this changed since v10.
```release-note
NONE
```
> [MM-62086] Don't include deleted DMs/GMs when returning archived channels (#29572)

- server/channels/app/bot.go
- server/channels/app/bot_test.go
Revokes user session after user is converted to a bot.
Fixes https://mattermost.atlassian.net/browse/MM-62188
```release-note
NONE
```
> MM-62188 - Revoke user sessions when converted to bot

- server/channels/app/import_functions_test.go
Merge queue caught me this time. #29530 had some substantial refactor in `TestImportImportUser` hence some variables had to be declared again and also some entities should've been imported again. I basically had to merge #28658 after the other one. 
```release-note
NONE
```
> server/channels/app/import_functions_test: fix build errors

- e2e-tests/cypress/tests/integration/channels/enterprise/oauth/oauth_spec.ts
Since last Friday, and possibly [this change](https://github.com/mattermost/mattermost/pull/29580/files#diff-d2caff5d5672665becd5e5d91193f55e564766bf7610e017bbf7c0160f219230L355), one of the E2E testcases has caused a single runner to reliably get stuck, leading all E2E runs to take around 2 hours (until the stuck worker is canceled by Github for exceeding the 120 minutes timeout).
Examples of runs with a stuck worker:
- https://automation-dashboard.vercel.app/cycle/12319698165_1-57900c9-pr-onprem-ent
- https://automation-dashboard.vercel.app/cycle/12324850385_1-master-daily-onprem-ent
- https://automation-dashboard.vercel.app/cycle/12341046154_1-8927120-pr-onprem-ent
This PR demotes the problem testcase. It will be reintroduced to production runs in the future. …
> Demote oauth_spec.ts

- server/public/go.mod
- server/public/shared/httpservice/client.go
- server/public/shared/httpservice/client_test.go
Take two. We are simplifying a bit and simply rejecting proxied URLs that have an invalid IPv6 address in the host.
https://mattermost.atlassian.net/browse/MM-61938
```release-note
NONE
```
> [MM-61938] httpservice: improve validation of proxied URLs

- server/channels/app/export_test.go
My PR #28854 got in after https://github.com/mattermost/mattermost/pull/29004 hence linter rules started to apply. This PR addresses the necessary checks required by the linter.
```release-note
NONE
```
> server/channels/app/export_test: fix a lint error due to err check

- server/channels/api4/file_test.go
- server/channels/api4/post.go
- server/channels/api4/post_test.go
- server/channels/app/authorization.go
Cherry pick of #29656 on release-10.1.
```release-note
NONE
```
> Automated cherry pick of #29656

- server/channels/store/sqlstore/sqlx_wrapper.go
In a recent [pull request](https://github.com/mattermost/mattermost/pull/29558#issuecomment-2557681771), a store was refactored to use a query builder and `args` set, but the args was not spread in the subsequent query. The tests caught the regression and the fix was simple (and done before merging):
```diff
- if err := s.GetReplica().Get(&token, query, args); err != nil {
+ if err := s.GetReplica().Get(&token, query, args...); err != nil {
```
But I wanted to check the code base for any other potential oversights. I found one in `QueryX` which this PR fixes, but fortunately it looks like we don't currently use this method anyway.
Note that the `args` vs `args...` is solved even more cleanly by using the `GetBuilder` versions of these APIs, but that's a separate campaign and we're trying …
> Fix cases where args... was not spread

- webapp/platform/eslint-plugin/configs/.eslintrc-react.json
This rule warns us if an element has an onMouseOver/onMouseLeave attributes without corresponding onFocus/onBlur ones. It's helpful for showing where we may be missing some accessible interactions, and I've filed MM-62343 and MM-62345 to follow up on two of these.
In other cases, the component either has alternate accessibility support (the emoji picker), it's something that may not make sense to be accessible (the expanded view of the channel header), or something we're already planning to review accessiblity for (the search component), so I'm going to disable it to avoid introducing noise for the time being.
MM-62344
```release-note
NONE
```
> MM-62344 Disable mouse-events-have-key-events ESLint rule

- server/public/pluginapi/store.go
- server/public/pluginapi/store_test.go
GetReplicaDB return nil because masterDB is not initialized, the fix initialize the masterDB (this is skipped if masterDB is already initialized).
```go
dbDriver, err := p.pluginAPIClient.Store.GetReplicaDB()
```
--> dbDriver is nil
```go
p.pluginAPIClient.Store.GetMasterDB()
dbDriver, err := p.pluginAPIClient.Store.GetReplicaDB()
```
OK!
```release-note
* Fix pluginapi.store.GetReplicaDB return nil if masterDB is not initialized
```
> fix(pluginapi/store): init master db if no replica

- server/channels/app/platform/cluster_handlers.go
- server/channels/app/platform/service.go
- server/channels/app/platform/service_test.go
ps.LoadLicense could end up calling InvalidateAllCaches. Therefore,
we need to intialize those caches before calling LoadLicense
to prevent a panic from happening.
While here, we also remove some unused code.
https://mattermost.atlassian.net/browse/MM-62378
```release-note
NONE
```
> MM-62378: Initialize status and session cache before loading license

- server/enterprise/elasticsearch/elasticsearch/elasticsearch.go
- server/enterprise/elasticsearch/opensearch/opensearch.go
- server/i18n/en.json
- server/public/model/config.go
We cannot simply use Elasticsearch any more because
we support Opensearch as well.
Therefore changing Elasticsearch to just say Search.
Note: There are still some cases where Elasticsearch
is used. That is intentional and necessary.
https://mattermost.atlassian.net/browse/MM-62293
```release-note
NONE
```
> [MM-62293]: Remove Elasticsearch from translation strings

- server/channels/app/bot.go
- server/channels/app/bot_test.go
* revoke user sessions when converted to bot
* lint fixes
(cherry picked from commit faa7e4f2ea0cca2fd2aba271912b9fc3be788842)
Revokes user session after user is converted to a bot.
Fixes https://mattermost.atlassian.net/browse/MM-62188
```release-note
NONE
```
> MM-62188 - Revoke user sessions when converted to bot (#29573)

- server/i18n/en.json
- server/public/model/link_metadata.go
- server/public/model/link_metadata_test.go
URL lengths are not enforced in the LinkMetadata validation, which causes `INSERT` statements to fail repeatedly with long URLs.
Fixes https://github.com/mattermost/mattermost/issues/29588.
```release-note
Fix insertion errors to LinkMetadata table.
```
> Bugfix - Enforce URL length check in LinkMetadata before attempting to insert to database

- server/channels/api4/bot_test.go
- server/channels/api4/post_test.go
- server/channels/api4/user_test.go
- server/channels/api4/user_viewmembers_test.go
The default role permissions weren't being saved
to a separate variable which would have not restored
them properly. This was a problem in various other
tests, potentially causing side-effects in other
flaky tests as well.
We fix that, as well as clean up the for loop
a bit and mention how many messages were recieved
in the failure message so that it becomes clear
whether no messages were recieved, or atleast some
were received.
https://mattermost.atlassian.net/browse/MM-62079
```release-note
NONE
```
> MM-62079: Fix permissions being reset properly

- webapp/channels/src/utils/performance_telemetry/reporter.ts
As in the comments I added, this is to fix an error introduced by changes made by either Firefox or 1Password due to accessing a performance metric's details field when we're not allowed to. The error is more visible on servers like Community and Hub because of the error bar, but as far as I can tell, it doesn't cause any other issues.
https://mattermost.atlassian.net/browse/MM-62371
https://mattermost.atlassian.net/browse/MM-62393
```release-note
Fixed errors logged by performance telemetry due to certain browser extensions
```
> MM-62371 Add additional error handling to PerformanceReporter

- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/compliance_export_ui_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/download_bot_compliance_export_file_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/compliance/download_compliance_export_file_spec.js
- Skipping tests that require the download link. These will be reenabled when https://mattermost.atlassian.net/browse/MM-60115 is implemented (later this week).  (why? I want to make sure everything is green on the feature branch while Dylan is testing)
- https://mattermost.atlassian.net/browse/MM-62436
```release-note
NONE
```
> MM-62436 - Temporarily skip cypress tests that require download link

- webapp/channels/src/components/post_view/index.ts
This PR adds the logic to make sure that the channel identifier match with the expected channel name identifier, being always in lower-case.
https://mattermost.atlassian.net/browse/MM-61411
Before:
https://github.com/user-attachments/assets/6267d9e7-936a-481a-8fee-71652f1ab149
After:
https://github.com/user-attachments/assets/6f7e2014-a472-4382-ac72-681bf07ad505
```release-note
NONE
```
> MM-61411 - fix incorrect linking case sensitive issue

- server/i18n/en.json
- server/public/model/link_metadata.go
- server/public/model/link_metadata_test.go
Cherry pick of #29589 on release-9.11.
/cc  @NadavTasher
```release-note
NONE
```
> Automated cherry pick of #29589

- server/channels/api4/limits.go
- server/channels/web/handlers.go
- server/channels/web/oauth.go
- server/channels/web/saml.go
If a SAML login failed, there would be two almost identical error messages. This PR removes one of them.
**Before**
```
error [2025-01-07 09:23:34.934 +01:00] Failed to complete SAML login                 caller="web/saml.go:132" path=/login/sso/saml request_id=s68tq7w7upgopbepfzcyp8yn9e ip_addr="::1" user_id= method=POST error="SamlInterfaceImpl.DoLogin: SAML login was unsuccessful because one of the attributes is incorrect. Please contact your System Administrator., uid attribute is missing"
error [2025-01-07 09:23:34.934 +01:00] SAML login was unsuccessful because one of the attributes is incorrect. Please contact your System Administrator. caller="web/context.go:124" path=/login/sso/saml request_id=s68tq7w7upgopbepfzcyp8yn9e ip_addr="::1" user_id= method=POST …
```
> Remove duplicate SAML login error message

- webapp/channels/src/components/new_search/new_search.tsx
- webapp/channels/src/components/root/root.tsx
- webapp/channels/src/components/sidebar_right/sidebar_right.tsx
- webapp/channels/src/utils/a11y_controller.ts
- webapp/channels/src/utils/a11y_controller_instance.ts
This PR adds the logic to keep in memory for the a11y controller the origin element that initially triggered the action that displayed a new element. This way, once that element is closed, we can return back the focus to the origin element.
**note:** the current approach for saved posts, recent mentions, files, members and channel info uses the document.activeElement to reference the origin that trigger the opening of the RHS in order to setting the focus back to that origin element.
Even when it works, in the case the feedback of this PR to be positive, the approach for those will also change to the approach added in this PR using the a11ycontroller originElement.
https://mattermost.atlassian.net/browse/MM-62226
https://github.com/user-attachments/assets/9aa63785-33d0-4338-a2a8-dc3a24b490 …
> MM-62226 - set focus back to search button

- server/public/model/builtin.go
- Fix IDE comment warnings (typo, add a comma, change wording)
N/A
Before:
After:
```release-note
NONE
```
> Fix IDE warninings about comment

- webapp/channels/src/components/emoji_picker/emoji_picker.tsx
I have looked at PR #27467. The solution seems bad and not elegant. I have proposed a better and more elegant solution with minimal code. It saves the cursor state and uses already built-in functionality to navigate through icons and save their position.
https://mattermost.atlassian.net/browse/MM-62102
Fixes https://github.com/mattermost/mattermost/issues/29512
```release-note
Improved Icon Navigation and Cursor State Management
Enhanced solution for icon navigation: The previous solution (PR #27467) lacked elegance and had unnecessary complexity. This release refines the approach, minimizing the amount of code and improving performance. 
Cursor state management: The cursor state is now saved and preserved, making it easier to navigate through icons seamlessly.
Built-in functionality …
```
> MM-62102 Scroll position resets when custom emojis requested #29512

- server/channels/store/sqlstore/scheme_store.go
The changes migrate SELECT * queries in scheme_store.go to use the query builder pattern. This improves type safety and maintainability by explicitly defining columns and using structured queries instead of raw SQL strings.
#29680
```release-note
Changed: Migrated scheme store SELECT * queries to use structured query builder with explicit column definitions.
```
> migrate queries in scheme_store.go

- webapp/channels/src/sass/layout/_webhooks.scss
MM-62400 - Updating style for no style attachment
https://mattermost.atlassian.net/browse/MM-62400
-->
```release-note
Fixing webhook attachment button style 
```
> MM-62400 - Updating style for no style attachment

- api/v4/source/users.yaml
The CPA information was never added to the user profile endpoint, but a reference to it was included by mistake on the docs. This change removes that reference.
```release-note
NONE
```
> Remove the CPA query parameter for the user profile endpoint

- webapp/channels/src/components/channel_header/channel_header_text_popover.tsx
`handleFormattedTextClick` isnt pure redux action but it an ~action~ function which uses the globally declared singleton store.
Jira https://mattermost.atlassian.net/browse/MM-62568
```release-note
NONE
```
> [MM-62568] Clicking on the channel header popover content throw js error

- webapp/channels/src/components/channel_header/channel_header_text_popover.tsx
Cherry pick of #29857 on release-10.5.
```release-note
NONE
```
> Automated cherry pick of #29857

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- webapp/channels/src/components/advanced_text_editor/use_submit.tsx
- webapp/channels/src/packages/mattermost-redux/src/action_types/files.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/files.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/files.ts
When removing all/some files when editing, I'm making the following cleanup in store-
1. Set to to date file ID array in `store.entities.files.fileIdsByPostId[<post ID>]` , and
2. Removing the metadata of deleted files from `store.entities.files.files[<file ID]`
Fixes https://mattermost.atlassian.net/browse/MM-62464
```release-note
none
```
> Deleted file from post ID to file ID and file info part of store

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_buttons_spec.js
- e2e-tests/cypress/tests/support/ui/sidebar_right.js
- webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
- webapp/channels/src/components/rhs_card_header/rhs_card_header.tsx
- webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx
This PR adds accessible name to the expand RHS button in RHS header
- Locate the "Expand Sidebar Icon/ collapse Sidebar Icon" button.
- Inspect it with Chrome DevTools.
- Review the value for "Name".
FIxes: https://mattermost.atlassian.net/browse/MM-61637
[Screencast from 2024-12-31 12-35-36.webm](https://github.com/user-attachments/assets/a580a404-f561-4b67-b9a2-a8c9bd34cb7b)
```release-note
```
> [MM-61637]: Add accessible name to the expand RHS button in RHS header

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/scheduled_posts.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
fix logic for channel or thread id scheduled messages count. With this change, the reducer will remove old ids that are no longer returned by the server preventing the count indicator to show invalid data count. Basically now the reducer will prevent duplicate IDs and properly merge new data. 
https://mattermost.atlassian.net/browse/MM-62613
n/a
```release-note
NONE
```
> MM-62613 - remove scheduled messages on ws reconnect

- e2e-tests/cypress/tests/integration/channels/enterprise/system_console/user_management/user_management_admin_control_spec.js
- webapp/channels/src/components/team_settings_modal/team_settings_modal.tsx
- webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx
- webapp/channels/src/sass/components/_settings-modal.scss
- Updated the user settings and team settings modal title component HTML tag from h1 to h2.
- Locate the Settings text heading.
- Inspect it with Chrome DevTools.
- Review the value for "Level".
- The heading does not match with the visual level on the page, Hence the modal heading should be h2.
Jira https://mattermost.atlassian.net/browse/MM-61684
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
> [MM-61684]: Updated the heading element tag

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx
- Added aria-live property to the message status element.
- Programmatically triggering the `Message Sent` prompt.
- Navigate to the write to town square edit field and type 'tester'.
- Now navigate to the Send a message button and select it.
- Notice that after selecting the Send a message button, the screen reader not announcing any status message.
- When the message is successfully sent a screen should announce the status of sent message.
Jira https://mattermost.atlassian.net/browse/MM-61619
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
> [MM-61619]: Added aria-live property for message sent status

- server/channels/app/app_iface.go
- server/channels/app/integration_action.go
- We were lacking any sort of logging in the `POST` request made by `DoActionRequest`
- I chose to log in the two methods that call `DoActionRequest` so that we can log the `userId` and other available information.
- I chose `INFO` level, but open to any suggestions.
- https://mattermost.atlassian.net/browse/MM-60687
```release-note
Added INFO level logging for DoActionRequest POST requests.
```
> [MM-60687] Log DoActionRequest requests to INFO

- server/Makefile
Prepackage [Calls v0.29.7](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.29.7) dot release to ship with v9.11 latest dot release.
```release-note
Prepackage Calls v0.29.7
```
> Prepackage Calls v0.29.7

- server/Makefile
Prepackage [Calls v1.5.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.5.1) dot release to ship with v10.5
```release-note
Prepackage Calls v1.5.1
```
> Prepackage Calls v1.5.1

- server/channels/web/context.go
- Fix Go doc comment so it has the correct method name
- Fix typo "a" -> "an"
NA
Doc comment before/after:
Typo before/after:
```release-note
NONE
```
> Fix LogAuditRecWithLevel doc comment and fix typo

- webapp/channels/src/components/do_verify_email/do_verify_email.tsx
- webapp/channels/src/components/user_settings/general/user_settings_general.tsx
- webapp/channels/src/entry.tsx
- webapp/channels/src/packages/mattermost-redux/src/actions/errors.test.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/errors.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts
- webapp/channels/src/packages/mattermost-redux/test/test_store.js
The changes in `entry.tsx` in https://github.com/mattermost/mattermost-webapp/commit/0c431cd471c66c119608e8429aa55f863def64c5#diff-6bc7849f03060c613ebc8827104a4fabeedde73163f0b36515fdfc699b59aa4d accidentally made it so that `window.onerror` always dispatched `logError` with `displayable` set to true regardless of whether or not developer mode was enabled.
This fixes that and changes the parameters of `logError` to hopefully prevent similar things in the future.
MM-62489
```release-note
Fixed "An error has occurred" bar being shown with developer mode disabled
```
> MM-62489 Fix error bar showing with developer mode disabled

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/threads/index.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/threads/threads.test.js
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/threads/threadsInTeam.ts
When a thread is deleted by another user, the local Redux state is not updated to remove the thread from state, and as a result it gets stuck in the thread viewer if it was being followed/had replies.
This PR updates the reducer to remove the thread on the `POST_DELETED` action as well if a root post was deleted.
https://mattermost.atlassian.net/browse/MM-61319
```release-note
Fixed an issue where deleted threads would get stuck in the thread viewer
```
> [MM-61319] Delete the thread from state when the root post is deleted by another user

- server/i18n/en.json
- Remove unneeded i18n string, for https://github.com/mattermost/enterprise/pull/1825
- https://mattermost.atlassian.net/browse/MM-62515
```release-note
NONE
```
> [MM-62515] Fix: Compliance exports fail when missing s3 file attachment

- e2e-tests/cypress/tests/integration/channels/system_console/site_configuration/link_customization_e20_1_spec.js
- webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_item/product_menu_item.tsx
- webapp/channels/src/components/global_header/left_controls/product_menu/product_menu_list/__snapshots__/product_menu_list.test.tsx.snap
- webapp/channels/src/components/post_priority/post_priority_picker.tsx
- webapp/channels/src/components/post_priority/post_priority_picker_item.tsx
- webapp/channels/src/components/widgets/menu/menu.test.tsx
- webapp/channels/src/components/widgets/menu/menu.tsx
- webapp/channels/src/components/widgets/menu/menu_group.test.tsx
- webapp/channels/src/components/widgets/menu/menu_group.tsx
- webapp/channels/src/plugins/test/__snapshots__/main_menu_action.test.tsx.snap
- The message priority menu does not follow the correct menu structure.
- Updated the Message priority menu structure as recommended by W3C please [refer](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/)
- Navigate to the Message priority button and select it.
- Now navigate to the Standard, Important and Urgent buttons list.
- Inspect the element.
- Notice that the list is implemented incorrectly.
- Please [refer](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/)
Jira https://mattermost.atlassian.net/browse/MM-61674
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
> [MM-61674]: Added appropriate roles to the menu component of post priority

- webapp/channels/src/components/emoji_picker/emoji_picker_tabs.tsx
- webapp/channels/src/i18n/en.json
- Added dialog role to the emoji picker.
- Added ARIA properties such as aria-label and aria-modal to the emoji picker.
- Locate the Emoji Picker dialog.
- Inspect it with Chrome DevTools.
- Review the values for "Name" and "Role".
- Dialog containers must have role="dialog". If the dialog has a visible title, set aria-labelledby on the dialog container to the ID of the visible title. For dialogs without a visible title, set a descriptive aria-label on the dialog element.
Jira https://mattermost.atlassian.net/browse/MM-61612
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
> [MM-61612]: Added dialog role to the emoji picker

- .github/workflows/server-ci-report.yml
Reporting flaky tests on release branches isn't useful, as we aren't likely to go back and patch these. Let's only surface flaky reports from master. (PR semantics remain unchanged).
None
```release-note
NONE
```
> only report flaky on master

- server/enterprise/message_export/actiance_export/actiance_export.go
- server/enterprise/message_export/csv_export/csv_export.go
- server/enterprise/message_export/global_relay_export/global_relay_export.go
- server/i18n/en.json
- This is cherry-picking https://github.com/mattermost/mattermost/pull/30017 from 10.3 to 10.4
- https://mattermost.atlassian.net/browse/MM-62527
```release-note
NONE
```
> [MM-62527] Fix: Compliance exports fail when missing s3 file attachment

- server/channels/api4/apitestlib.go
- server/channels/api4/channel_category_test.go
- server/channels/api4/channel_test.go
- server/channels/api4/plugin_test.go
- server/channels/api4/post_test.go
- server/channels/api4/preference_test.go
- server/channels/api4/system_test.go
- server/channels/api4/team_test.go
- server/channels/api4/user_test.go
- server/channels/api4/websocket_test.go
Follow-up to https://github.com/mattermost/mattermost/pull/29893#issuecomment-2596125259
I updated all instances where simplifying and using the connected client made more sense. 
https://mattermost.atlassian.net/browse/MM-62773
https://mattermost.atlassian.net/browse/MM-42652
https://mattermost.atlassian.net/browse/MM-61736
```release-note
NONE
```
> [MM-62773] Use CreateConnectedWebSocketClient test util

- server/cmd/mmctl/commands/bot_test.go
- server/cmd/mmctl/commands/channel_users_test.go
- server/cmd/mmctl/commands/command_test.go
- server/cmd/mmctl/commands/permission_role_test.go
- server/cmd/mmctl/commands/team_users_test.go
- server/cmd/mmctl/commands/token_test.go
- server/cmd/mmctl/commands/user_test.go
- server/cmd/mmctl/commands/userargs.go
- server/cmd/mmctl/commands/userargs_test.go
- server/cmd/mmctl/commands/webhook_test.go
- See ticket for report that setting email using mmctl was failing. It actually wasn't failing -- the email was being set as expected, but the debug logs showed an error. That error was from the `GetUserByEmail` endpoint. What was happening? `mmctl` was trying to get the user with the mmctl arg (using the client), and it tries the `GetUserByEmail` first. When that fails, it tries finding user by username. 
- Fix: test the mmctl arg to see if it's an email first. If it is, go ahead and try the `GetUserByEmail` endpoint. If it isn't, continue trying to find user by username like before.
- https://mattermost.atlassian.net/browse/MM-62179
```release-note
Fix to mmctl to prevent logging a harmless debug-level "error" to the logs.
```
> [MM-62179] Fix: mmctl debug error when setting email

- server/cmd/mmctl/commands/user_e2e_test.go
Add end to end tests to the "sendPasswordResetEmail" mmctl command
Fixes https://github.com/mattermost/mattermost/issues/15488
Jira https://mattermost.atlassian.net/browse/MM-28673
```release-note
```
> Add end to end tests to the "sendPasswordResetEmail" mmctl command

- webapp/channels/src/sass/components/_search.scss
Removed `display: flex;` from the `.no-results` class. Removing `display: flex;` defaults it to `display: block;` ensures it takes its parent container's full width, aligning the layout as expected.
https://mattermost.atlassian.net/browse/MM-62719
https://github.com/user-attachments/assets/c842b802-645a-4d68-9897-4af510d52e0e
```release-note
NONE
```
> Fix the empty search state container stretching issue

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
- webapp/channels/src/components/channel_layout/channel_identifier_router/actions.test.ts
- webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts
- webapp/channels/src/components/permalink_view/actions.ts
- webapp/channels/src/components/permalink_view/permalink_view.test.tsx
There are two ways to join channel via link.
1 - via permalink to post in channel
2 - via channel link
These two methods use completely separate code paths. 
If a Team Admin attempts to join via a Permalink, they would automatically join the channel. This PR now prompts the TeamAdmin before allowing to join.
If a TeamAdmin attempts to join via a channel link, this path completely fails due to the TeamAdmin not being a member of the channel, the channel cannot be retrieved. Secondly, this path did not actually "join" the channel if not already a member so other areas would fail when attempting to view the channel.
This PR makes the changes necessary to allow a TeamAdmin to join via either method with a prompt. 
Fixes https://mattermost.atlassian.net/browse/MM-61847
```release-note
NONE
```
> Prompt Team Admin before joining private channel

- webapp/channels/src/components/search/search.tsx
Search didn't work anymore in responsive mode. The code relied on the fact that nobody will ever call `preventDefault()` when the user press `Enter`, so eventually the form will trigger a `submit` event, but with our `document` being polluted by various event listeners, it was bound to happen 😅 
This fix deterministically call `handleSearch` when the user press `enter` from the search box if nothing else is supposed to happen. Please note that this is on the old search UI, and not (directly at least) related to the new one, and submitting the form is still handled the way it was before.
Additional change thanks to Lindy's test: in mobile mode, the input should take the focus.
https://mattermost.atlassian.net/browse/MM-62776
```release-note
NONE
```
> [MM-62776] Fix search not working anymore in responsive mode.

- server/build/docker-compose-generator/main.go
- server/build/docker-compose.common.yml
- server/build/docker-compose.yml
- server/docker-compose.makefile.m1.yml
- server/docker-compose.makefile.yml
- server/docker-compose.yaml
- Remove obsolete version in Docker files that produces a warning
N/A
Before:
After:
```release-note
NONE
```
> Remove obsolote docker version

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_post_spec.js
- e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts
- e2e-tests/cypress/tests/integration/channels/mark_as_unread/archive_channel_mark_as_unread_spec.js
- e2e-tests/cypress/tests/integration/channels/mark_as_unread/mark_as_unread_using_shortcuts_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/message_reaction_gm_spec.js
- webapp/channels/src/components/post/post_component.tsx
- webapp/channels/src/components/post_edit_history/__snapshots__/post_edit_history.test.tsx.snap
- webapp/channels/src/components/post_edit_history/edited_post_item/__snapshots__/edited_post_item.test.tsx.snap
- webapp/channels/src/components/post_view/post_message_view/__snapshots__/post_message_view.test.tsx.snap
- webapp/channels/src/components/post_view/post_message_view/post_message_view.tsx
- webapp/channels/src/plugins/test/__snapshots__/post_type.test.tsx.snap
The PR ensures focus order of interactive elements on the page is logical and focus is not moved to non-interactive elements of the page. 
- Navigate to the page using tab key until reaches the entire section of the At 8:08 PM Monday, September 23, Someone wrote, user joined the team text.
- Notice that non-interactive elements receive focus.
Fixes: https://mattermost.atlassian.net/browse/MM-61599
[Screencast from 2024-12-16 18-04-35.webm](https://github.com/user-attachments/assets/583b5396-545c-4de5-8ea5-9445aca68127)
```release-note
```
> [MM-61599]: Remove tabIndex from non-interactive elements

- e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/unread_spec.ts
- webapp/channels/src/packages/mattermost-redux/src/actions/threads.ts
Manually following/unfollowing threads causes some strange behaviour on the front-end, and one of the reasons for this is that we don't properly re-sync our unread information when the thread following status is changed. That status does actually affect the number of unreads that the team sidebar should show, so we should make sure to update that amount once we change that status, which we currently don't do.
To do this however, we'd need to manually figure out how many mentions were in that thread, as well as how many unreads and urgent mentions, which is a lot of information the reducer doesn't have and might not be a perfect calculation, as we don't replicate that calculation on the front-end anywhere else. So as a quick solution, and especially since team unreads may be deprecated in …
> [MM-62113] Force reload of team unreads when following/unfollowing a thread

- e2e-tests/playwright/support/flag.ts
- e2e-tests/playwright/support/test_fixture.ts
- e2e-tests/playwright/support/ui/components/channels/scheduled_draft_modal.ts
- e2e-tests/playwright/support/ui/components/channels/search_popover.ts
- e2e-tests/playwright/support/ui/components/channels/sidebar_right.ts
- e2e-tests/playwright/tests/functional/channels/search/search_box_suggestions.spec.ts
- e2e-tests/playwright/tests/functional/channels/search/team_selector.spec.ts
- One test (mine, oops) was depending on a FF that I was trying to set, turns out it didn't work (except locally because I had the FF set on my local instance)
- One test was trying to close the search box after the search was done, but the search box is already closed after a search.
- The last one want to select on a calendar today+2days, turns out when you do that on January 31st, February 2nd does not show on the calendar 😅 Fixed the test by clicking "next month" if the entry was not found in the first place.
N/A
```release-note
NONE
```
> Fix Playwright tests

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_keyboard_usability_spec.js
- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_post_spec.js
- webapp/channels/src/components/admin_console/admin_user_card/__snapshots__/admin_user_card.test.tsx.snap
- webapp/channels/src/components/admin_console/system_user_detail/__snapshots__/system_user_detail.test.tsx.snap
- webapp/channels/src/components/at_mention/__snapshots__/at_mention.test.tsx.snap
- webapp/channels/src/components/at_mention/at_mention.tsx
- webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap
- webapp/channels/src/components/post/post_component.tsx
- webapp/channels/src/components/profile_picture/__snapshots__/profile_picture.test.tsx.snap
- webapp/channels/src/components/profile_picture/index.tsx
- webapp/channels/src/sass/components/_mentions.scss
This PR ensure ARIA roles, states, and properties are valid in user profile image and @user buttons.
- Navigate to the user profile image button (Avatar) or the @user mention link.
- Inspect the element.
- Notice that the aria-expanded and aria-haspopup attributes implemented for the <span>tag is invalid.
Fixes: https://mattermost.atlassian.net/browse/MM-61598
[Screencast from 2025-01-02 16-51-43.webm](https://github.com/user-attachments/assets/90e57d3e-9f08-401f-9e9e-bb0b2ce14897)
[Screencast from 2025-01-02 16-53-40.webm](https://github.com/user-attachments/assets/283b60bd-d8e8-405d-9bba-697d6af411a3)
```release-note
NONE
```
> [MM-61598]: Fix ARIA roles, states, and properties are valid in user profile image and @user buttons

- e2e-tests/cypress/tests/integration/channels/emoji/custom_emoji_2_spec.ts
- e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_1_spec.ts
- e2e-tests/cypress/tests/integration/channels/emoji/recently_used_emoji_2_spec.ts
- e2e-tests/cypress/tests/integration/channels/emoji/sorted_emojis_spec.ts
- e2e-tests/cypress/tests/integration/channels/messaging/emoji_keyboard_entry_spec.js
- webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
- webapp/channels/src/components/emoji_picker/components/emoji_picker_category_or_emoji_row.tsx
- webapp/channels/src/components/emoji_picker/components/emoji_picker_category_row.tsx
- webapp/channels/src/components/emoji_picker/components/emoji_picker_current_results.tsx
- webapp/channels/src/components/emoji_picker/components/emoji_picker_item.tsx
- webapp/channels/src/components/emoji_picker/components/emoji_picker_search.tsx
- webapp/channels/src/components/emoji_picker/emoji_picker.tsx
- webapp/channels/src/components/post_emoji/post_emoji.tsx
- webapp/channels/src/sass/components/_emoticons.scss
Fix the interactive controls that cannot be navigated to and operated with the keyboard alone in the Emoji picker modal
- Press Tab repeatedly to navigate through the Emoji button controls in the page.
- If the control can be focused, attempt to interact with the control using Enter, Space, Up/Down Arrow, and any other
applicable keystrokes.
- Notice that the control cannot be focused or that the control cannot be interacted with using the keyboard alone.
- The button should be focusable and operable by the keyboard.
- Element can be triggered when using the SPACE bar or ENTER key. 
- Element should have accessible name
Fixes https://mattermost.atlassian.net/browse/MM-61577
```release-note
```
> [MM-61577]: Ensure all interactive functionality is operable with the keyboard in emoji picker

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
- webapp/channels/src/i18n/i18n.jsx
Ukrainian language quality has been consistently climbing so it no longer needs an Alpha status.
```release-note
Upgraded Ukrainian language to official.
```
> Upgrade language from alpha

- webapp/channels/tsconfig.json
- webapp/channels/webpack.config.js
- webapp/package-lock.json
- webapp/package.json
This PR adds `typescript-eslint-language-service`, which is something I hackily reinstall locally everyt ime we make a change the `package(-lock).json` or `tsconfig.json` 😅 
Behind the scene, this package makes your LSP (`typescript-language-server` for most people) report eslint errors, removing the need to obtain an eslint dedicated plugin for your IDE. 
see https://community.mattermost.com/core/pl/c7kp69zfjp8dfk7yf6so1k6kae
N/A
N/A
```release-note
NONE
```
> Add `typescript-eslint-language-service`

- server/channels/api4/job.go
- server/channels/app/file.go
- Add the export file store version of the ZipReader and call that for job exports (since that's where exports are written, that's where we should read from).
- Thanks @DHaussermann for the great find.
- https://mattermost.atlassian.net/browse/MM-62845
```release-note
NONE
```
> [MM-62845] Fix: Compliance export download link fails from S3 when using a dedicated file store

- server/enterprise/message_export/worker.go
- server/enterprise/message_export/worker_test.go
- Early in development of Compliance overhaul, I was cleaning up the json fields we were using. I simplified from `Timestamp` -> `Time`, but I forgot to check for the case where a job from <10.5 would be used as the previous job for the first job in a 10.5 server.
- This PR fixes that case (and adds a test for it). 
- https://mattermost.atlassian.net/browse/MM-62897
```release-note
NONE
```
> [MM-62897] Compliance export backwards compatibility

- server/channels/app/export.go
- server/channels/app/export_test.go
- Adding a warnings.txt to the bulk export's zip file
- Adding a `num_warnings` field in the job.Data so it will be returned when the job is listed from mmctl
- This should help us debug what's happening in cloud, even if the logs are getting lost somehow.
- https://mattermost.atlassian.net/browse/MM-62876
```release-note
NONE
```
> [MM-62876] Bulk export warnings

- server/enterprise/metrics/metrics.go
When the client side metrics were added constLabels
got missed out. Without this, we cannot do the high
level grouping by rings.
https://mattermost.atlassian.net/browse/MM-62901
```release-note
NONE
```
> MM-62901: Apply constLabels on all metrics

- .github/workflows/server-ci-report.yml
I had previously made a change to check `github.ref`, not realizing that this particular workflow always runs from `master` from a workflow completed on a different branch. Use `github.event.workflow_run.head_branch` instead.
None
None
```release-note
NONE
```
> Correctly detect branch to decide if notifying

- server/channels/app/platform/log.go
We were redirecting any logging happening via the Go standard logger
to our own mlog instance. The issue is that all those logs were happening
at LvlStdLog level which is higher than LvlDebug.
LvlStdLog is at 10, and LvlDebug is at 5. So unless a customer
sets the log level specifically to "stdlog" or sets up advanced
logging to specifically log for that level, no standard logs will
ever get logged.
We fix this by logging it at warn level. The reason for warn
is that mostly external libraries use this facility to log
out-of-band errors that could not be returned using standard
error returns.
I saw another plugin error which was logged similarly. This
was never surfaced before due to this bug.
https://mattermost.atlassian.net/browse/MM-62926
```release-note
NONE
```
> MM-62926: Fix standard logger redirection issue

- server/public/model/channel_bookmark.go
- server/public/model/channel_bookmark_test.go
Emoji on mobile is missing because bookmarks are returning emoji name with `:`.  This fix ensure that the API will no longer return that, but at the same time, will also make sure that the emoji name is being stored without the `:`.
[Ticket](https://mattermost.atlassian.net/browse/MM-60645)
[Mobile PR](https://github.com/mattermost/mattermost-mobile/pull/8518)
Combine web and mobile (after fix):
channelbookmarks table (after fix)
```
|id|ownerid|channelid|fileinfoid|createat|updateat|deleteat|displayname|sortorder|linkurl|imageurl|emoji|type|originalid|parentid|
|--|-------|---------|----------|--------|--------|--------|-----------|---------|-------|--------|-----|----|----------|--------|
|he8pdnxkkpbxzdr1gj195pyhfo|up8ng8gd6bnnbqsnz34mj3o3tr|cmkwrprzrirzmyy4ah8p84sw9c||1737752506535|173 …
```
> fix(MM-60645): missing emoji on mobile

- e2e-tests/cypress/tests/integration/channels/channel/channel_bookmarks_spec.ts
- server/channels/api4/channel_bookmark.go
- server/channels/api4/channel_bookmark_test.go
- server/i18n/en.json
- webapp/channels/src/components/channel_bookmarks/utils.ts
Cherry pick of #29490 on release-10.5.
```release-note
NONE
```
> Automated cherry pick of #29490

- server/channels/app/limits.go
- server/channels/app/limits_test.go
- server/channels/app/user_test.go
- webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Update User limits to 2.5K for soft limits (admin dismissible banner) and to 5K for hard limit (admin non-dismissible banner and no additional users can be added) for unlicensed servers. 
https://mattermost.atlassian.net/browse/MM-62769
```release-note
Update User limits to 2.5K for soft limits (admin dismissible banner) and to 5K for hard limit (admin non-dismissible banner and no additional users can be added) for unlicensed servers. 
```
> Update User Limits for unlicensed servers

- webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx
- webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx
- webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.test.tsx
The `name` passed into the checkbox component corresponds to the `id` attribute of the input and the `for` attribute of the label, so we previously had two inputs and labels with the same IDs
MM-62891
```release-note
NONE
```
> MM-62891 Fixed incorrectly applied label in Team Settings modal

- server/channels/store/sqlstore/property_field_store.go
- server/channels/store/sqlstore/property_value_store.go
- server/channels/store/storetest/property_field_store.go
- server/channels/store/storetest/property_value_store.go
This PR refactors the Property Field and Value stores to use a single `UPDATE` query with `SET CASE` statements instead of multiple `UPDATE` queries within the same transaction for improved performance.
The query is still run in a transaction so it can be rolled back in case the amount of rows modified doesn't correspond with the amount of entities that were passed as parameters to be updated.
https://mattermost.atlassian.net/browse/MM-62556
```release-note
NONE
```
> Updates the property field and value update methods to use a single query for multiple entities

- webapp/channels/src/components/admin_console/file_upload_setting.tsx
Prior to https://github.com/mattermost/mattermost/pull/29510, settings involving uploading a file worked by making a button and then stretching a transparent file input over it, but that made them unusable for keyboard users. In that PR, I changed it so that the buttons for those would instead trigger the file input when clicked, but I missed doing it for this setting.
MM-62944
```release-note
NONE
```
> MM-62944 Fix fileupload settings not being clickable

- server/channels/store/storetest/property_value_store.go
https://github.com/mattermost/mattermost/pull/30163 and https://github.com/mattermost/mattermost/pull/30119 conflicted silently, this PR fixes the build on master.
N/A
```release-note
NONE
```
> Fix build: Remove call for removed attribute Page

- webapp/channels/src/sass/components/_post-menu.scss
- webapp/channels/src/sass/components/_search.scss
https://github.com/mattermost/mattermost/pull/29787 changed the structure of the post options to be lists for better accessibility, but the different HTML tags had some minor layout differences that weren't noticed.
This should fix those
MM-62933
What changed|Master|10.3|Now
-|-|-|-
The menu is shifted downwards on master compared to 10.3|![1c community post](https://github.com/user-attachments/assets/6401893b-9d1c-45a6-98bf-bd199f534943)|![1a hub post](https://github.com/user-attachments/assets/1aa290d7-14f9-44c9-809d-f1e22b941e2f)|![1b pr post](https://github.com/user-attachments/assets/1282c046-d8a0-4e10-b783-727742ce08bf)
The box around the menu is shifted downwards while "Jump" is shifted upwards|![2c community search](https://github.com/user-attachments/assets/bebff8b3-6725-4f07-8dac …
> MM-62933 Revert position of post menu to match earlier versions

- server/channels/api4/post_test.go
- server/channels/app/platform/web_conn.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
- server/public/model/config.go
When we added iteration by channelID, this was a known tradeoff during that.
However, it has been observed that the regular connection removal function
creates considerable blocking of the processing loop, leading to high
CPU usage and API latencies.
To fix this, we add a reverse mapping of channelIDs to connections
and their positions in the slice. This helps us to remove the connection
from the slice without iteration.
Unfortunately, this still needs to iterate through all channelIDs
during invalidation of the channel member cache. However, the user
cache invalidation is not a regular activity. So it should be an acceptable
tradeoff to make.
https://mattermost.atlassian.net/browse/MM-62960
```release-note
A new config knob ServiceSettings.EnableWebHubChannelIteration which allows a user …
```
> [Cherry-pick] MM-62960: Improve webConn remove performance from hubConnectionIndex (#30178)

- webapp/channels/src/components/new_search/search_box_input.tsx
- webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- webapp/channels/src/components/threading/common/button/button.tsx
- webapp/channels/src/components/threading/common/follow_button/__snapshots__/follow_button.test.tsx.snap
This fixes some console warnings that are printed to the console when working on the web app. They only appeared in dev mode
For the first one, I don't think the error had any effect since I'm pretty confident that the only reason it caused an error was because of a Babel plugin that was adding `propTypes` to something that it thought was a component.
For the second one, this error was actually indicative of the tooltips for components which used the `Button` component in `components/threading/common/button` being broken because `WithTooltip` couldn't attach a ref to find where the tooltip should be placed. Those tooltips should now work again.
MM-63138
The errors that should now be fixed are the following:
```release-note
NONE
```
> MM-63138 Fix some console warnings

- server/channels/api4/channel_bookmark.go
- server/channels/api4/channel_bookmark_test.go
- server/i18n/en.json
- webapp/channels/src/components/channel_bookmarks/utils.ts
Cherry pick of https://github.com/mattermost/mattermost/pull/29490 on release-10.4.
```release-note
NONE
```
> MM-62050: restrict channel bookmarks in archived channels (#29490)

- server/channels/api4/post_test.go
- server/channels/app/platform/web_hub.go
- server/channels/app/platform/web_hub_test.go
When Channel iteration mode is enabled, we need to ensure that
channel scoped events do not fall through to the connIndex.All()
condition. This is possible because there are multiple hubs
in a given system. So a single event will flow through all of them
and in some hubs, a channel scoped event might not have any connections.
In that case, we need to stop processing further.
https://mattermost.atlassian.net/browse/MM-62960
```release-note
NONE
```
> MM-62960: Support both webhub iteration scopes properly

- server/channels/app/app_iface.go
- server/channels/app/authentication.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/plugin_api_test.go
- server/channels/app/plugin_requests.go
- server/channels/web/context.go
- server/i18n/en.json
We wipe the token if MFA authentication is enabled. Also added a test case
to lock in the functionality.
https://mattermost.atlassian.net/browse/MM-62914
```release-note
NONE
```
> [Cherry-pick] [AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)

- server/channels/app/app_iface.go
- server/channels/app/authentication.go
- server/channels/app/opentracing/opentracing_layer.go
- server/channels/app/plugin_api_test.go
- server/channels/app/plugin_requests.go
- server/channels/web/context.go
- server/i18n/en.json
We wipe the token if MFA authentication is enabled. Also added a test case
to lock in the functionality.
https://mattermost.atlassian.net/browse/MM-62914
```release-note
NONE
```
> [Cherry-pick][AI assisted]: MM-62914: Added MFA authentication for plugin requests as well (#30160)

- server/channels/app/channel_bookmark.go
- server/channels/app/channel_bookmark_test.go
- server/channels/store/opentracinglayer/opentracinglayer.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_bookmark_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_bookmark.go
- server/channels/store/storetest/mocks/ChannelBookmarkStore.go
- server/channels/store/timerlayer/timerlayer.go
Cherry pick of #30034 on release-9.11.
```release-note
NONE
```
> MM-61375: Update file handling for bookmarks (#30034)

- webapp/channels/package.json
- webapp/package-lock.json
This thing's unfortunately difficult to update because it's a dependency of the now-archived `@mattermost/compass-components` package. We do want to remove the Compass Components package at some point, but this overrides the dependency for the time being.
Note that getting to this to work required messing with the `package-lock.json` a bit directly. Here's hoping this doesn't break again in the future before we have a chance to remove the Compass Components.
MM-62866
```release-note
NONE
```
> MM-62866 Update axios dependency

- server/channels/api4/user_test.go
- server/channels/app/bot.go
We did not invalidate the cache after converting a user to bot.
That led to issues. See JIRA for more details.
https://mattermost.atlassian.net/browse/MM-62837
```release-note
NONE
```
> [Cherry-pick][AI assisted] MM-62837: (#30268)

- server/channels/api4/apitestlib.go
- server/channels/api4/post_test.go
- server/channels/app/platform/service.go
- server/platform/services/cache/provider.go
- server/public/model/config.go
I was aware that the Redis cache was shared across tests. But we would clear the cache after every test and Redis was enabled only for the api4 package, so there was no chance of parallel tests causing issues.
Even then, it seems like this particular test was somehow a victim of the Redis cache somehow being stale.
It looks like adding a cache prefix has fixed it, but we'll never know until after a few days. In any case, this is essential to scale properly in Cloud. So the effort isn't wasted in any ways.
For now, we are not exposing this in the system console yet. That can be done as a later improvement.
https://mattermost.atlassian.net/browse/MM-62079
```release-note
NONE
```
> MM-62079: Using a cache prefix to isolate cache keys for each test

- server/channels/app/authorization.go
- server/public/model/permission.go
- server/public/model/session.go
- Fix doc comments
- Fix IDE complaining about "ie." vs "i.e."
NA
|----|----|
```release-note
NONE
```
> Fix doc comments and IDE complaint

- server/platform/services/remotecluster/README.md
- server/platform/services/sharedchannel/README.md
This PR adds a readme to the Remote Cluster and Shared Channels services packages.  This is simply to help anyone new to the project figure out what these packages do.
NONE
-->
```release-note
NONE
```
> Add readme to the remotecluster and sharedchannel service directories

- webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx
The Custom Groups feature shares the same permission that the LDAP groups feature uses, but the permission toggle itself would not show up for non-Enterprise users. This PR makes sure the permission toggle shows for servers with Custom Groups enabled.
https://mattermost.atlassian.net/browse/MM-62609
```release-note
Fixed an issue where the group mentions permission was missing
```
> [MM-62609] Show Group Mentions permissions if custom groups is enabled

- server/Makefile
Prepackage Jira plugin v4.2.1.
```release-note
Prepackage Jira plugin version [v4.2.1](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.2.1).
```
Prepackage Jira plugin version [v4.2.1](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.2.1).
> Bump prepackage Jira plugin version to 4.2.1

- webapp/channels/src/components/header_footer_route/footer.tsx
- webapp/channels/src/plugins/index.ts
- Return early in `registerPlugin` if the `MMEMBED` cookie is `1`
- Don't render the `Footer` component if `MMEMBED` cookie is `1`
https://mattermost.atlassian.net/browse/MM-63325
https://mattermost.atlassian.net/browse/MM-63329
|----|----|
| ![Screenshot 2025-03-03 at 11 03 18](https://github.com/user-attachments/assets/405a8ce8-6540-4435-a15c-9d24a0b69466) | ![Screenshot 2025-03-03 at 11 03 08](https://github.com/user-attachments/assets/17504e2f-4bee-4518-83ce-de542ec3cbe4) |
```release-note
feat: disable webapp plugin loading and footer if MMDEBUG cookie is set
```
> [MM-63325, MM-63329] feat: dont register plugins or show the footer if MMEMBED cookie is set to `1`

- webapp/channels/src/components/profile_popover/profile_popover.scss
Normal text wrapping causes long words to overflow. Switching all `.user-popover__subtitle-text`s to use `overflow-wrap: break-word;` to fix.
https://mattermost.atlassian.net/browse/MM-63301
`70-characters-allowed-000000000000000000123456789012345678901234`
|----|----|
|  ![CleanShot 2025-02-27 at 08 53 41](https://github.com/user-attachments/assets/c7a5e415-986a-4909-9908-a654d8adb443) | ![CleanShot 2025-02-27 at 08 52 05](https://github.com/user-attachments/assets/6cd74741-44c1-4225-83c4-9751bde59434) |
```release-note
NONE
```
> MM-63301: Use break-word in profile popover fields

- server/channels/app/platform/web_hub.go
- server/channels/app/platform/websocket_reliable.go
- server/channels/app/platform/websocket_reliable_test.go
If the deadQueue was full, we would be incorrectly sending
the wrong index for dqPtr. Fixed that and added a test case.
https://mattermost.atlassian.net/browse/MM-63304
```release-note
NONE
```
> [AI assisted] MM-63304: Wrap around dqPtr while unmarshalling

- webapp/channels/src/sass/components/_modal.scss
As part of the accessibility improvements, we made this component use a button which automatically gave it a background on dark themes. This PR removes that
MM-63213
|----|----|
|![Screenshot 2025-02-27 at 5 09 34 PM](https://github.com/user-attachments/assets/e70a5f89-4425-4e16-aef5-705ee05661f3)|![Screenshot 2025-02-27 at 5 09 16 PM](https://github.com/user-attachments/assets/32d654e0-d82e-4c3c-99e0-faec1030603f)
This hasn't shipped in a release yet
```release-note
NONE
```
> MM-63213 Remove background from more modal plus button

- server/channels/app/platform/web_hub.go
- server/channels/app/platform/websocket_reliable.go
- server/channels/app/platform/websocket_reliable_test.go
Cherry pick of #30371 on release-10.6.
/cc  @agnivade
```release-note
NONE
```
> Automated cherry pick of #30371

- server/channels/api4/job.go
- server/channels/api4/job_test.go
PR fixes a panic due to incorrectly wrapping a `nil` error.
https://mattermost.atlassian.net/browse/MM-63352
```release-note
NONE
```
> [MM-63352] Fix incorrect error handling in `api4.downloadJob`

- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/posts.ts
The issue is that the system answer to a command entered in a thread is also posted in the channel.
For me the problem was in the reducer that processes new posts, and especially the condition that allows not to display thread messages into channel.   
To fix it, I removed a particular clause that did an exception on ephemeral messages. I didn't find in commit log any reason why this particular clause has been added at first time (but maybe information was lost during monorepo migration). 
Fixes https://github.com/mattermost/mattermost/issues/23969
Jira https://mattermost.atlassian.net/browse/MM-53506
```release-note
Fixed an issue where the system answer to a command entered in a thread was also posted in the channel 
```
> MM-53506 Fixed duplicated command response in thread/channel (#23969)

- server/Makefile
Prepackage [Calls v0.29.8](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v0.29.8) dot release to ship with v9.11 latest dot release.
```release-note
Prepackage Calls v0.29.8
```
> Prepackage Calls v0.29.8 (v9.11)

- server/Makefile
Prepackage [Calls v1.5.2](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.5.2) dot release to ship with latest dot releases for v10.3, v10.4, v10.5, v10.6 (pending cherry-picks)
```release-note
Prepackage Calls v1.5.2
```
> Prepackage Calls v1.5.2

- server/Makefile
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/30437 to `release-10.4`
```release-note
Prepackage Calls v1.5.2
```
> Prepackage Calls v1.5.2 (`release-10.4`)

- server/Makefile
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/30437 to `release-10.3`
```release-note
Prepackage Calls v1.5.2
```
> Prepackage Calls v1.5.2 (`release-10.3`)

- webapp/channels/src/actions/websocket_actions.test.jsx
- webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx
- webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx
- webapp/channels/src/components/user_settings/general/user_settings_general.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts
At the selector level, sort according to `attrs.sort_order`. Websockets already updating this.
https://mattermost.atlassian.net/browse/MM-63271
https://github.com/user-attachments/assets/7d81a51b-0b76-4bf1-8b98-33a1ceea2c0c
```release-note
NONE
```
> MM-63271: CPA Sorting in Profile Popover & Profile Settings

- server/config/client.go
- server/public/model/config.go
Currently on the mobile app is possible to prompt for biometric authentication as well as to prevent its use if the device is Jailbroken / Rooted and prevent screen captures, but these features are only available with the use of an EMM Provider.
The following config settings is to be able to set this features enabled or disabled on a per server basis and without the need of an EMM provider, although this settings are only available for the enterprise SKU and as soon as we release the Premium SKU it should be included there as well.
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/8645
https://mattermost.atlassian.net/browse/MM-63361
```release-note
Added configuration under the `NativeAppSettings` settings to enable mobile biometric authentication prompt, jailbreak / root …
```
> Add config settings for additional security features on mobile

- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
- webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Fixed a bug where pressing escape when typing a message in create post/comment cleared the input.
Fixes https://mattermost.atlassian.net/browse/MM-63400
```release-note
None
```
> Fixed a bug where escape would delete all typed content

- webapp/channels/src/components/channel_info_rhs/top_buttons.tsx
Fixed styling issue with the copy link icon in the success state. 
https://mattermost.atlassian.net/browse/MM-62824
|----|----|
| ![image-20250130-133721](https://github.com/user-attachments/assets/da010bd1-a23c-4995-a965-b5c8d99e4782)| <img width="582" alt="Screenshot 2025-03-09 at 7 16 49 PM" src="https://github.com/user-attachments/assets/dc12073a-bdfc-4b76-a0d6-43ba2fcb547f" /> |
```release-note
None
```
> Fixed RHS opy link icon styling

- server/Makefile
Prepackage [Metrics Plugin v0.6.0](https://github.com/mattermost/mattermost-plugin-metrics/releases/tag/v0.6.0) which includes the logic to scrape Calls metrics.
```release-note
Prepackage Metrics Plugin v0.6.0
```
> Prepackage Metrics Plugin v0.6.0

- server/channels/store/sqlstore/post_store.go
- server/channels/store/storetest/post_store.go
We used < which meant we missed sending
reminders created for that timestamp, because
the job runs on that exact time.
Using <= to fix that.
https://mattermost.atlassian.net/browse/MM-63545
```release-note
NONE
```
> MM-63545: Fix post reminder off-by-one error

- webapp/channels/src/components/commercial_support_modal/__snapshots__/commercial_support_modal.test.tsx.snap
- webapp/channels/src/components/commercial_support_modal/commercial_support_modal.scss
- webapp/channels/src/components/commercial_support_modal/commercial_support_modal.test.tsx
- webapp/channels/src/components/commercial_support_modal/commercial_support_modal.tsx
When the Support Packet generation fails, an error is now shown in the System Console. Previously, the error would instead be returned as the support packet file, which was not obvious.
https://mattermost.atlassian.net/browse/MM-63534
```release-note
Show errors from Support Packet generation in System Console
```
> [MM-63534] Show errors from Support Packet generation in System Console

- webapp/channels/src/components/emoji_picker/__snapshots__/emoji_picker.test.tsx.snap
- webapp/channels/src/components/emoji_picker/components/emoji_picker_categories.tsx
- webapp/channels/src/components/emoji_picker/components/emoji_picker_current_results.tsx
- webapp/channels/src/components/emoji_picker/constants/index.ts
- webapp/channels/src/components/emoji_picker/emoji_picker.test.tsx
- webapp/channels/src/components/emoji_picker/emoji_picker.tsx
- webapp/channels/src/sass/components/_emoticons.scss
`AI-assisted`
Hide emoji categories when searching/filtering.
[MM-58521](https://mattermost.atlassian.net/browse/MM-58521)
| Before | After |
| -- | -- |
| <img width="364" alt="image" src="https://github.com/user-attachments/assets/dd7d2527-d395-4b77-8ca3-036975343d1b" /> |  <img width="360" alt="image" src="https://github.com/user-attachments/assets/471d586d-d6ab-4fa2-9fc9-57d09be2f8ce" /> |
```release-note
NONE
```
1. Open emoji picker
2. Type in the search box
3. Verify categories are hidden while searching
4. Clear search text
5. Verify categories reappear
[MM-58521]: https://mattermost.atlassian.net/browse/MM-58521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MM-58521 Hide emoji categories while searching emoji picker

- server/channels/app/export_test.go
- server/channels/app/import.go
- server/channels/app/import_test.go
- server/channels/jobs/import_process/worker.go
- server/cmd/mattermost/commands/import.go
Updated the return value order of `BulkImport` and `BulkImportWithPath` functions to follow Go conventions of returning errors as the last return value.
- Changed function signatures from `(*model.AppError, int)` to `(int, *model.AppError)`
- Updated all internal return statements
- Updated all calling code to handle the new return order
- No functional changes, purely refactoring for consistency with Go conventions
None
```release-note
NONE
```
> Return error as last value in BulkImport functions

- server/channels/api4/team.go
- server/channels/api4/team_test.go
- server/channels/app/syncables.go
- webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
This is the same problem as described in https://github.com/mattermost/mattermost/pull/30526 but this is for teams instead of channels.
https://mattermost.atlassian.net/browse/MM-63504
```release-note
Fixed a bug where there was inconsistent behaviour on removing non group members from group synced teams.
```
> [MM-63504] When changing a team to group synced, it doesn't always clear members

- server/channels/app/platform/service.go
This is to make it easier to use mmctl during development, particularly for new contributors to create their first admin account.
MM-63577
```release-note
NONE
```
> MM-63577 Enable EnableLocalMode automatically during development

- webapp/channels/src/components/suggestion/switch_channel_provider.tsx
We made a change recently to add `injectIntl` to the `SwitchChannelSuggestion` component. This broke keyboard navigation as we were missing `forwardRef` which is needed to ensure scrolling works correctly with the keyboard.
This PR adds `forwardRef` to the `injectIntl` call.
https://mattermost.atlassian.net/browse/MM-63280
```release-note
Fix keyboard navigation with the Channel Switcher
```
> [MM-63280] Forward ref properly through SwitchChannelSuggestion

- webapp/channels/src/sass/responsive/_mobile.scss
This modal is likely going to be removed with the new Channel Settings modal, but I'm trying out Cursor for some stuff.
This mobile-specific CSS seems like it was supposed to apply to the post textbox to hide those links back before the Advanced Text Editor was added. It doesn't seem like it needs to apply to the other place the old Textbox is used (ie. this modal)
MM-61589
```release-note
NONE
```
> MM-61589 Keep Help and Preview links visible on small screen sizes

- server/go.mod
- server/go.sum
Updating `golang-jwt/jwt` to latest `v5.2.2`.
https://github.com/mattermost/enterprise/pull/1885
https://mattermost.atlassian.net/browse/MM-63613
```release-note
NONE
```
> [MM-63613] Update `golang-jwt/jwt` dependency to latest

- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
PR fixes a potential nil dereference panic caused by passing a nil channel to `isChannelArchivedAndHidden` during channel permission checks. Interestingly, we had an existing test case for this, but it didn't cover the `TeamSettings.ExperimentalViewArchivedChannels=false` case, which I have now added.
https://mattermost.atlassian.net/browse/MM-63624
```release-note
NONE
```
> [MM-63624] Fix potential nil dereference in `app.isChannelArchivedAndHidden`

- server/.golangci.yml
Enables the bidichk linter in golangci-lint
https://mattermost.atlassian.net/browse/SEC-7737
Tested locally:
```release-note
NONE
```
> Enabld the bidichk linter

- webapp/channels/src/components/start_trial_form_modal/start_trial_form_modal.scss
Overflow was hidden so on small screens (<720 pixels vertically) the start trial button would go off the page never to be seen again. This makes the modal-body scrollable.
https://mattermost.atlassian.net/browse/CLD-9052
Before:
After:
```release-note
None
```
> [CLD-9052] Make trial form modal-body scrollable for small vertical screens

- server/Makefile
See https://github.com/mattermost/mattermost-govet/pull/47
```release-note
NONE
```
> Update mattermost-govet version to latest SHA

- e2e-tests/playwright/lib/src/ui/components/channels/center_view.ts
It seems like this the previous PR got caught before and after a dependency update which let a style error get through CI
```release-note
NONE
```
> Fix failing E2E smoketests

- server/channels/wsapi/websocket_handler.go
In https://github.com/mattermost/mattermost/pull/30293, we started sending PINGs to the server websocket from the clients. The server logs each PING, which clutters the logs with a ton of useless messages.
This PR stops logging PING actions coming over the websocket.
Prior to this change, whenever a client connects, every 30 seconds you should see a debug log like the following on the server:
```
{"timestamp":"...","level":"debug","msg":"Websocket request","caller":"wsapi/websocket_handler.go:26","action":"ping"}
```
After this change, the log will be missing.
https://mattermost.atlassian.net/browse/MM-63693
```release-note
Stop logging websocket PING events received by the server.
```
> [MM-63693] Don't log PING websocket events

- server/Makefile
Today, I learned that we use `mattermost-govet` in multiple make targets. :see_no_evil: 
Follow up to https://github.com/mattermost/mattermost/pull/30688
None
```release-note
NONE
```
> Update mattermost-govet version to latest SHA for vet target

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
- server/public/model/session.go
Cherry pick of #30467 on release-10.8.
```release-note
NONE
```
> Automated cherry pick of #30467

- server/channels/app/import_functions_test.go
This avoids a non-zero chance we append "pi" from the `model.NewId` and end up with an invalid prefix "Api".
None
```release-note
NONE
```
> flaky test: Avoid team names that start with "A".

- .github/workflows/server-ci-report.yml
Let's stop reporting flaky tests on `master`. We'll continue to report on pull requests.
This addresses the steady stream of flaky tests notices in https://community.mattermost.com/core/channels/developers that lack shared ownership:
None
```release-note
NONE
```
> stop reporting flaky tests

- server/channels/store/sqlstore/channel_store_categories.go
It was a mistake to return ANY error as NewErrNotFound. Because this
can be a DB timeout, or any other network error.
Returning NewErrNotFound would categorize it as 404, eventually printing
the error in the DEBUG level. Changing it to normal error fixes this.
https://mattermost.atlassian.net/browse/MM-63739
```release-note
NONE
```
> [AI assisted]: MM-53739: replace store.NewErrNotFound with errors.Wrap in category queries

- webapp/channels/src/plugins/index.ts
Removes the logic that disables plugins in the webapp when the `MMEMBED` cookie is set.
Fixes https://mattermost.atlassian.net/browse/MM-63507
```release-note
fix: removes logic to disable plugins when mattermost is embedded
```
> fix: allow plugins when embedding mattermost

- server/Makefile
Prepackage [Calls v1.7.0](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.7.0) to ship with MM v10.8
https://mattermost.atlassian.net/browse/MM-63444
```release-note
Prepackage Calls v1.7.0
```
> [MM-63444] Prepackage Calls v1.7.0

- server/channels/api4/custom_profile_attributes_test.go
- server/public/model/custom_profile_attributes.go
- server/public/model/custom_profile_attributes_test.go
This change automatically removes options and sync attributes when sanitizing fields that don't support them. As per values, it returns an error when the value for a text type field is longer than the 64 characters limit we're currently applying.
The PR fixes a bug on the create CPA field endpoint that was causing the attrs of the CPAField not to be decoded correctly.
https://mattermost.atlassian.net/browse/MM-63654
https://mattermost.atlassian.net/browse/MM-63721
```release-note
NONE
```
> Improves validation and sanitization for CPA fields and values

- .github/workflows/server-test-template.yml
When Elasticsearch/Opensearch was in enterprise repo,
we had to bump up the runners: https://github.com/mattermost/enterprise/commit/9b151defcc231c187960f29709f7b6f97a13c98c.
However, the ES code was moved inside server repo,
but the test runners were not changed. This led to frequent
test failures. So we are bumping up the test runners.
This will unfortunately lead to an increased cost, but
we have also cut down in other places viz. the build phase
uses the free runner now (https://github.com/mattermost/mattermost/pull/29297).
And the enterprise build also uses free runner (https://github.com/mattermost/enterprise/pull/1792).
```release-note
NONE
```
> Bump up test runners after Elasticsearch move

- .github/workflows/api.yml
- api/Makefile
- api/README.md
- api/package.json
- api/v4/html/ssr_template.hbs
- api/v4/source/definitions.yaml
- api/v4/source/introduction.yaml
1) Moving API documentation from Redoc to Stoplight, which offers sample and interactive requests
2) Performing necessary updates to keep the content while migrating to another frameworks. For example, we were using many redoc extensions like `x-tagGroups` that are not available in Stoplight. 
3) Update the content to be accurate and complete. All content updates are under `api/v4/source/introduction.yaml`. The best way to review the content is to pull the PR locally and build the API docs with `make run`. 
4) Updating the GH Action to only build the final openapi yaml. Pushing to the developers documentation repo happens in our delivery pipelines
Related PR: https://github.com/mattermost/mattermost-developer-documentation/pull/1442.
N/A
screenshots when running `make run` inside /api …
> Migrate API docs from Redoc to Stoplight

- server/channels/store/sqlstore/link_metadata_store.go
Avoid SELECT * in the link metadata store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
> avoid SELECT * in link metadata store

- server/channels/store/sqlstore/channel_member_history_store.go
- server/channels/store/storetest/channel_member_history_store.go
Avoid `SELECT *` in channel member history store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
> avoid SELECT * in channel member history store

- webapp/channels/package.json
- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_popover.tsx
- webapp/package-lock.json
A few weeks back at the offsite, we did an experiment to use Aider to upgrade us to React 18. It couldn't do that, but I did get its help to remove some dependencies that would either block that upgrade or need to be updated with it.
We only had one reference in the web app to react-popper, so it was easy enough to remove. The remaining references to the original popper.js were also through `@types/bootstrap` which we don't actually need because we don't use the JS parts of Bootstrap.
We still have an indirect dependency on react-popper in Compass Components, but this at least gets us closer to removing react-popper entirely.
#30744
MM-62382
MM-63615
```release-note
NONE
```
> MM-62382/MM-63615 Remove explicit reference to react-popper and remaining references to popper.js

- server/channels/store/sqlstore/notify_admin_store.go
Avoid SELECT * in the notify admin store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
> avoid SELECT * in notify admin store

- server/channels/api4/apitestlib.go
- server/channels/api4/channel_bookmark_test.go
- server/channels/api4/channel_test.go
- server/channels/api4/team.go
- server/channels/api4/team_guest_test.go
Cherry pick of #30789 on release-10.8.
```release-note
NONE
```
> Automated cherry pick of #30789

- server/channels/store/sqlstore/preference_store.go
- server/channels/store/storetest/preference_store.go
Avoid SELECT * in the preference store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
> MM-62110 avoid SELECT * in preference_store

- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.down.sql
- server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.up.sql
- server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.down.sql
- server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.up.sql
The (s SqlChannelStore) getSidebarCategoriesT gets called quite frequently.
- Team switch
- WS reconnect
- Category created
- Category updated
- Category deleted
Of these 1 and 2 are probably the most commonly called sources. Based on that,
the sidebarChannels table is not that well-optimized. Even though
the query time might be reasonable, without an index, it has to churn a lot of
DB CPU for a sequential scan.
We add a new index to optimize this.
CREATE INDEX idx_sidebarchannels_categoryid ON sidebarchannels(categoryid);
```
Before:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=40854.18..40854.19 rows=4 width=193) (actual time=251.635..251.646 …
```
> MM-63756: Added index to sidebarchannels table

- server/channels/store/sqlstore/channel_store.go
INSERT IGNORE will ignore ALL errors in the INSERT statement.
This is not what was intended. The right way is to do a
redundant update on duplicate key.
It's not great, but that's how MySQL wants us to do it.
https://mattermost.atlassian.net/browse/MM-63878
```release-note
NONE
```
> MM-63878: Fix INSERT IGNORE in saveChannelT

- server/platform/services/upgrader/upgrader.go
I have no idea why this only just started failing, but fixing the following error for all non-Linux users:
```
go install github.com/mattermost/mattermost-govet/v2@8e4d46e3fad88497dbfe073788a87e75bbae717c
go vet -vettool=/Users/jesse/.local/share/mise/installs/go/1.23.7/bin/mattermost-govet -structuredLogging -inconsistentReceiverName -emptyStrCmp -tFatal -configtelemetry -errorAssertions -license -inconsistentReceiverName.ignore=session_serial_gen.go,team_member_serial_gen.go,user_serial_gen.go,utils_serial_gen.go ./...
platform/services/upgrader/upgrader.go:6:1: Must be an empty line between the build directive and the license
make: *** [vet] Error 1
```
None
```release-note
NONE
```
> fix missing newline in upgrader.go

- server/.golangci.yml
- server/channels/jobs/helper_test.go
This PR fixes errcheck linter issues in the `server/channels/jobs/helper_test.go` file by properly handling all previously unchecked errors using `require.NoError` and `require.Nil`. It also removes the exception for this file from the `.golangci.yml` configuration.
I've added a `testing.TB` field to the `TestHelper` struct to make error handling cleaner throughout the code. This eliminates most panic calls, improving error reporting through the testing framework.
Fixes https://github.com/mattermost/mattermost/issues/28760
```release-note
NONE
```
> [MM-61087] Fix errcheck linter issues in channels/jobs/helper_test.go

- webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
- webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
- webapp/channels/src/components/threading/global_threads/thread_list/__snapshots__/thread_list.test.tsx.snap
- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.scss
- webapp/channels/src/components/threading/global_threads/thread_list/thread_list.tsx
- webapp/channels/src/components/threading/global_threads/thread_menu/__snapshots__/thread_menu.test.tsx.snap
- webapp/channels/src/components/threading/global_threads/thread_menu/thread_menu.tsx
- webapp/channels/src/i18n/en.json
This makes three improvements to the Threads list as described by the corresponding tickets:
1. I added an accessible name/label to the menu on thread items. I used the current tooltip "Actions" for it.
2. I added an accessible name/label to the mark as read button, and I changed the tooltip from "Mark all as read" to "Mark all threads as read" to add a bit more information and so that they match.
3. I made the Followed threads/Unread buttons use the `tab` roles and follow [the Tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/). I could've used the `Tabs` component which wraps React Bootstrap, but that would've required changing the UX here and likely would've required more substantial changes to the markup, so I went with a custom `useTabs` hook which might be usable elsewhere …
> MM-63056/MM-63058/MM-63049 Improve accessibility of Threads list

- webapp/channels/src/components/mobile_channel_header/mobile_channel_header.tsx
- webapp/channels/src/sass/responsive/_mobile.scss
#29917 made some unintentional changes to mobile view, most notably [this one](https://github.com/mattermost/mattermost/pull/29917/files#diff-218a53432099077fd4b46ed6f836803205327f74d49e7850785d20746d5fa9ad) which removed some seemingly unneeded divs which actually prevented some of the CSS used by mobile view from applying correctly.
I also reverted some changes to the CSS that spaced the elements of that header since, while those were more modern, they unintentionally changed the layout of 
MM-63851
|PR|Hub|Community|
-|-|-
```release-note
NONE
```
> MM-63851 Fix mobile view

- server/Makefile
Prepackage [Calls v1.7.1](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.7.1) dot release.
```release-note
Prepackage Calls v1.7.1
```
> Prepackage Calls v1.7.1

- server/channels/store/sqlstore/group_store.go
- server/channels/store/storetest/group_store.go
Partially eliminate `SELECT *` from the group store. This has required a non-trivial number of changes given the manual SQL construction in this file, so I'm breaking this up into multiple pull requests and adding test coverage where it was missing.
Fixes: https://mattermost.atlassian.net/browse/MM-62158
```release-note
NONE
```
> MM-62158: group store no SELECT * (Part 1)

- e2e-tests/playwright/specs/functional/channels/channel_banner/channel_banner.spec.ts
- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
- server/platform/services/telemetry/telemetry.go
- server/public/model/license.go
- server/public/model/license_test.go
- server/public/pluginapi/license.go
- server/public/pluginapi/license_test.go
- webapp/channels/src/components/channel_banner/channel_banner.test.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_modal.test.tsx
- webapp/channels/src/packages/mattermost-redux/src/constants/general.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_banner.ts
- webapp/channels/src/utils/constants.tsx
- webapp/channels/src/utils/license_utils.ts
- webapp/channels/src/utils/subscription.ts
Renamed Premium SKU to `Enterprise Advanced`.
Mobile PR - https://github.com/mattermost/mattermost-mobile/pull/8819
Fixes https://mattermost.atlassian.net/browse/MM-63928
```release-note
None
```
> Renamed premium SKU to Enterprise Advanced

- webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx
- webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
System Console -> User Properties -> Field type menu now defaults to `text` when dealing with legacy fields that are missing `value_type` and `visibility` attrs. This change prevents a runtime error/blank screen crash.
- https://mattermost.atlassian.net/browse/MM-63934
```release-note
NONE
```
> fix default field type if missing value_type in attrs

- server/channels/db/migrations/migrations.list
- server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.down.sql
- server/channels/db/migrations/mysql/000135_sidebarchannels_categoryid.up.sql
- server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.down.sql
- server/channels/db/migrations/postgres/000135_sidebarchannels_categoryid.up.sql
The (s SqlChannelStore) getSidebarCategoriesT gets called quite frequently.
- Team switch
- WS reconnect
- Category created
- Category updated
- Category deleted
Of these 1 and 2 are probably the most commonly called sources. Based on that,
the sidebarChannels table is not that well-optimized. Even though
the query time might be reasonable, without an index, it has to churn a lot of
DB CPU for a sequential scan.
We add a new index to optimize this.
CREATE INDEX idx_sidebarchannels_categoryid ON sidebarchannels(categoryid);
```
Before:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=40854.18..40854.19 rows=4 width=193) (actual time=251.635..251.646 …
```
> [CP] MM-63756: Added index to sidebarchannels table (#30724)

- webapp/channels/src/components/create_team/components/__snapshots__/display_name.test.tsx.snap
- webapp/channels/src/components/create_team/components/display_name.test.tsx
- webapp/channels/src/components/create_team/components/display_name.tsx
- webapp/channels/src/components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap
- webapp/channels/src/components/create_team/components/team_url/team_url.test.tsx
- webapp/channels/src/components/create_team/components/team_url/team_url.tsx
- webapp/channels/src/components/create_team/create_team.test.tsx
- webapp/channels/src/components/create_team/create_team.tsx
- webapp/channels/src/i18n/en.json
Some accessibility fixes for the Create Team screen:
- MM-62974: The focus wasn't updating when an error occurred, now it shifts to the input with an error.
- MM-62984: The header wasn't marked as a label for the text input, I changed the `h5` to a `label` and added `htmlFor`.
- MM-63016: There was no page title set when navigating to Create Team, now there is.
- MM-63025: There was no relation between the error message and the text input, I've added `role=alert` so the message is read, and `aria-describedby` to associate it on re-focus.
```release-note
Various fixes for the Create Team screen
```
> [MM-62974][MM-62984][MM-63016][MM-63025] Various fixes for the Create Team screen

- webapp/channels/src/components/new_search/extension_suggestions.tsx
- webapp/channels/src/components/new_search/search_box.tsx
- webapp/channels/src/i18n/en.json
A couple search box fixes around accessibility:
- MM-62971: File extension list wasn't focusable, I've added `role=button` and added the right `aria-label`.
- MM-63017: The close button was missing an `aria-label`, I've added one so it now reads `Close`.
```release-note
Search box accessibility fixes
```
> [MM-62971][MM-63017] Search box accessibility fixes

- server/channels/store/sqlstore/channel_store_categories.go
For our MySQL customers, we have discovered that the query is not
able to choose the right plan by itself without adequate hints.
This is only for MySQL as we have confirmed from multiple customers
that Postgres takes the right index idx_sidebarcategories_userid_teamid
for the sidebarCategories table. And if it doesn't, then a VACUUM ANALYZE
fixes it.
But for MySQL, we have to do two things:
- Pass an index hint to let it use idx_sidebarcategories_userid_teamid.
- Pass an optimizer hint to materialize the sub-query. This is used
to materialize the doesNotHaveSidebarChannel sub-query into a temporary
table, letting MySQL reuse the contents of the table for further processing
in the parent sections of the query.
I have confirmed both locally and in the customer environment
that it gives a …
> MM-64209: Optimize completePopulatingCategoryChannelsT for MySQL

- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/actions/websocket_actions.test.jsx
Revert #30939, which had reverted #29010.
This PR should be released along with the cherry-pick of https://github.com/mattermost/mattermost/pull/30963.
--
--
```release-note
Bring back bug fix for [MM-61361](https://mattermost.atlassian.net/browse/MM-61361), since the performance regression has been fixed by tweaking the offending SQL query.
```
[MM-61361]: https://mattermost.atlassian.net/browse/MM-61361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Revert #30939

- server/channels/app/authorization.go
- server/channels/app/authorization_test.go
Cherry pick of #30628 on release-10.5.
```release-note
NONE
```
> Automated cherry pick of #30628

- server/channels/web/saml.go
- server/i18n/en.json
We should have been using this error if the plugin decides to return one. This should be merged with https://github.com/mattermost/mattermost/pull/30746 & https://github.com/mattermost/mattermost-plugin-identity-groups-sync/pull/19
https://mattermost.atlassian.net/browse/MM-63775
```release-note
NONE
```
> [MM-63775] Use error from OnSamlLogin

- server/channels/api4/channel_test.go
- server/i18n/en.json
- server/public/model/channel.go
- server/public/model/channel_test.go
- webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
This PR adds extra validation to the channel patch endpoint to enhance reliability of the color value, making sure it will only accept valid hex colors (3&6 digits)
https://mattermost.atlassian.net/browse/MM-63912
https://github.com/user-attachments/assets/42718189-a82b-42a8-a73a-2658ebd0b6f1
```release-note
NONE
```
> MM-63912 - enhance validation for channel banner colors

- server/channels/api4/group.go
- server/channels/api4/group_test.go
- server/channels/app/group.go
- server/i18n/en.json
Improve Groups API error semantics to return clearer information when invalid user IDs are provided or when operations involve users that aren't part of a group.
Fixes: https://mattermost.atlassian.net/browse/MM-63619
```release-note
Improved Groups API error semantics when invalid parameters are specified.
```
> [MM-63619] Improve Groups API error semantics

- server/channels/app/channel_test.go
https://github.com/mattermost/mattermost/pull/30746
```release-note
NONE
```
> Fix flaky test for TestLeaveChannel

- server/platform/services/docextractor/archive.go
Avoid creating a whole temporary directory when a single temporary file suffices.
Fixes: https://mattermost.atlassian.net/browse/MM-64337
```release-note
NONE
```
> MM-64336: simplify doc extractor

- server/channels/api4/post_create_test.go
- server/channels/app/post.go
- server/channels/app/post_test.go
Require access to a post before allowing `PendingPostId` to deduplicate.
Fixes: https://mattermost.atlassian.net/browse/MM-64226
```release-note
NONE
```
> MM-64226: improved post deduplication

- server/channels/api4/channel_category.go
- server/channels/api4/channel_category_test.go
This is a small followup to #30965 since I noticed that, when normalizing/validating the list of channels in an updated category, we were looping over the array of channel IDs once for each channel in each updated category. Now, we'll only loop over the array of channel IDs once no matter how many channels are added to the categories.
If I remember my big-O notation, we're going from O(nm) to O(n+m) where n is the number of channels that the user is in and m is the number of channels in the updated categories
```release-note
Slightly improved performance of sidebar update APIs
```
> Slightly improve performance of sidebar update APIs

- server/channels/app/metrics_test.go
- server/public/model/metrics.go
The Timestamp field was not used at all. Therefore
removing it.
https://mattermost.atlassian.net/browse/MM-62365
```release-note
NONE
```
> MM-62365: Remove unused field from MetricSample

- server/channels/app/busy_test.go
(*Busy).Set would set its own timer, and additionally
send a message across the cluster. In this case, the cluster
is mocked locally. But the timer calculation happens again.
We marshal the expiry time with b.expires.Unix() and send that
as part of model.ServerBusyState. This is parsed again in
ClusterEventChanged and converted to duration with time.Until.
Therefore, if it takes longer for the code to reach those lines,
then the new time calculated would have already expired, failing
the test.
To fix this, we increase the timeout. This slows down the test
at the cost of extra reliability. This is a common failure point
with any timer related tests.
Additionally, we also change the condition in compareBusyState
to check for less-than rather than strict equality. …
> MM-63300: Fix flaky test TestBusySet

- server/Makefile
Prepackage [Calls v1.8.0](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.8.0) to `release-10.9`.
https://mattermost.atlassian.net/browse/MM-63789
```release-note
Prepackage Calls v1.8.0
```
> Prepackage Calls v1.8.0 (`release-10.9`)

- server/Makefile
Cherry-pick https://github.com/mattermost/mattermost/pull/31098 which bumps the Jira prepackage version to v4.3
NONE
```release-note
Prepackage Jira plugin version [v4.3.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v4.3.0).
```
> Cherry-pick: Bump prepackage Jira plugin version to 4.3.0

- server/channels/store/sqlstore/group_store.go
Picking up after https://github.com/mattermost/mattermost/pull/30276 and https://github.com/mattermost/mattermost/pull/30926, this migrates a handful of GroupStore methods away from `SELECT *`.
Relates-to: https://mattermost.atlassian.net/browse/MM-62158
```release-note
NONE
```
> MM-62158: group store no select star, part3

- webapp/channels/src/components/user_settings/notifications/manage_auto_responder/__snapshots__/manage_auto_responder.test.tsx.snap
- webapp/channels/src/components/user_settings/notifications/manage_auto_responder/manage_auto_responder.tsx
Converting the user settings modal to `GenericModal` caused some unwanted side effects in styling. One of these was forcing any `form-control` classed element to be 40px.
It's likely we should audit the `GenericModal` CSS to see how opinionated it really should be on sub element styling, but for this PR the easy fix is to force the height back to `auto`, in order to prevent any other unwanted side effects.
https://mattermost.atlassian.net/browse/MM-64255
```release-note
Fix height of automatic replies textarea
```
> [MM-64255] Fix height of automatic replies textarea

- webapp/channels/src/sass/responsive/_mobile.scss
This was invalid CSS, but it didn't have any effect because we changed the settings sidebar to be a series of buttons instead of a list of `li`s containing links.
```release-note
NONE
```
> Remove unused invalid CSS

- server/channels/api4/access_control_test.go
- server/channels/api4/channel_test.go
- server/channels/api4/license.go
- server/channels/api4/license_test.go
- server/channels/app/platform/license.go
- server/channels/app/platform/license_test.go
- server/i18n/en.json
- webapp/channels/src/components/admin_console/license_settings/index.ts
- webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
- webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
- webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
- webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.test.tsx
- webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
- webapp/channels/src/i18n/en.json
Given v11 launches in September and drops support for MySQL, we don't need to support MySQL for the new Enterprise Advanced SKU at all. Prevent this on upload:
as well as if the license is specified in the environment on startup:
```
{"timestamp":"2025-05-22 16:50:20.444 -03:00","level":"error","msg":"MySQL is not supported for this license","caller":"platform/license.go:234","sku_short_name":"advanced"}
```
As part of this change, disable the trial experience for MySQL altogether. MySQL is already deprecated for new customers since v10. Lastly, fix a typo in the trial prompt.
https://mattermost.atlassian.net/browse/MM-64387
```release-note
Enterprise Advanced SKU is Postgres-only.
```
> Reject mysql for enterprise advanced

- server/channels/api4/access_control_test.go
- server/channels/api4/channel_test.go
- server/channels/api4/license.go
- server/channels/api4/license_test.go
- server/channels/app/platform/license.go
- server/channels/app/platform/license_test.go
- server/i18n/en.json
- webapp/channels/src/components/admin_console/license_settings/index.ts
- webapp/channels/src/components/admin_console/license_settings/license_settings.test.tsx
- webapp/channels/src/components/admin_console/license_settings/license_settings.tsx
- webapp/channels/src/components/admin_console/license_settings/trial_banner/trial_banner.tsx
- webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.test.tsx
- webapp/channels/src/components/announcement_bar/show_start_trial_modal/show_start_trial_modal.tsx
- webapp/channels/src/i18n/en.json
Cherry pick of #31164 on release-10.9.
```release-note
NONE
```
> Automated cherry pick of #31164

- server/channels/app/custom_profile_attributes.go
- server/channels/app/custom_profile_attributes_test.go
- server/channels/app/properties/property_field.go
- server/channels/app/properties/property_value.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/property_value_store.go
- server/channels/store/store.go
- server/channels/store/storetest/mocks/PropertyValueStore.go
- server/channels/store/storetest/property_value_store.go
- server/channels/store/timerlayer/timerlayer.go
- webapp/channels/src/actions/websocket_actions.jsx
- webapp/channels/src/actions/websocket_actions.test.jsx
- webapp/channels/src/packages/mattermost-redux/src/action_types/users.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.test.ts
- webapp/channels/src/packages/mattermost-redux/src/reducers/entities/users.ts
This changes extend the Property Service to include a function that allows to delete values filtered by `fieldID` and `groupID`, and it uses it to delete the CPA field values when the field changes its type.
https://mattermost.atlassian.net/browse/MM-63908
```release-note
NONE
```
> Deletes CPA values on CPA field type change

- server/channels/store/storetest/post_store.go
As of https://github.com/mattermost/mattermost/pull/30735, `GetNthRecentPostTime` is flaky:
Relates-to: https://mattermost.atlassian.net/browse/MM-64438
```release-note
NONE
```
> MM-64438: skip flaky: testGetNthRecentPostTime

- webapp/channels/src/components/post_view/show_more/__snapshots__/show_more.test.tsx.snap
- webapp/channels/src/components/post_view/show_more/show_more.test.tsx
- webapp/channels/src/components/post_view/show_more/show_more.tsx
Unfortunately, https://github.com/mattermost/mattermost/pull/30716 is causing a serious regression:
This reverts commit 20f9f58e4c6ba5e4eceba83a1fab9b28bed5fd71.
Fixes: https://mattermost.atlassian.net/browse/MM-64391
```release-note
NONE
```
> Revert "MM-63648 - markdown images sometimes do not show the more button

- e2e-tests/cypress/tests/integration/channels/channel/channel_settings_menu_permissions_spec.ts
- webapp/channels/src/components/channel_header_menu/menu_items/channel_settings_menu.tsx
- webapp/channels/src/selectors/views/channel_settings.test.ts
- webapp/channels/src/selectors/views/channel_settings.ts
Hide the channel settings options for users that lack any permission to modify any of the channel properties.
https://mattermost.atlassian.net/browse/MM-64378
Before:
https://github.com/user-attachments/assets/f12c1ee8-bee6-4796-8020-da108d0e30df
After:
https://github.com/user-attachments/assets/df76a138-1101-4c9c-b0bb-2c6aee286be1
```release-note
NONE
```
> MM-64378 - hide channel settings menu option for users with no permissions

- server/channels/app/import.go
- server/channels/app/import_functions.go
- server/channels/app/import_test.go
- server/channels/app/imports/import_validators.go
- server/channels/app/imports/import_validators_test.go
- server/cmd/mmctl/commands/import_test.go
- server/i18n/en.json
PR implements some extra validation on the paths used to import file attachments.
We implement a `ValidateAttachmentImportData` util function called by validators on parent structures (namely `PostImportData`, `ReplyImportData`, and `DirectPostImportData`), which returns an error during initial validation in case of invalid paths. At the same time, we add some additional protection to `processAttachmentPaths`, which is called as part of the bulk import logic.
One thing I am omitting for now is any validation on the base path used, noticing that [we default](https://github.com/mattermost/mattermost/blob/62bd9d917d3906a02a2b670254fbfb4bc672a2ca/server/channels/jobs/import_process/worker.go#L128) to the `model.ExportDataDir` constant when running import jobs.
Changes should be fully backward …
> [MM-64402] Improve validation of imported attachments

- webapp/channels/src/components/drafts/scheduled_post_list/scheduled_post_list.scss
- webapp/channels/src/components/edit_scheduled_post/edit_post.tsx
1. Fixed width of edit schedule post UI.
2. Fixed a bug where clicking on `Save` button on edit scheduled post without any change did nothing, and didn't even close the edit.
This got broken in https://github.com/mattermost/mattermost/pull/30563
Fixes https://mattermost.atlassian.net/browse/MM-64363
```release-note
None
```
> Fixed width of edit scheduled post UI

- server/channels/store/sqlstore/channel_store_categories.go
Avoid `SELECT *` in `channel_store_categories.go`. While we're in here, adopt the `*Builder` pattern a bit more aggressively to clean up some ancillary code.
```release-note
NONE
```
> avoid SELECT * in channel_store_categories.go

- server/channels/store/sqlstore/store_test.go
As noted, we could need more than `-test.parallel` active databases from the shared pool since there could be either concurrent subtests or paused tests, which require some extra buffer. Using `parallelism * 2` seems like a good value, which has been working well for `app` and `api4` tests so far.
```release-note
NONE
```
> Bump shared db pool size in store for parallel tests

- server/channels/app/syncables_test.go
- server/channels/store/retrylayer/retrylayer.go
- server/channels/store/sqlstore/channel_member_history_store.go
- server/channels/store/sqlstore/post_store.go
- server/channels/store/sqlstore/thread_store.go
- server/channels/store/store.go
- server/channels/store/storetest/channel_member_history_store.go
- server/channels/store/storetest/group_store.go
- server/channels/store/storetest/mocks/ChannelMemberHistoryStore.go
- server/channels/store/storetest/mocks/PostStore.go
- server/channels/store/storetest/mocks/ThreadStore.go
- server/channels/store/storetest/post_store.go
- server/channels/store/storetest/preference_store.go
- server/channels/store/storetest/reaction_store.go
- server/channels/store/storetest/thread_store.go
- server/channels/store/timerlayer/timerlayer.go
- server/public/model/config.go
- server/public/model/data_retention_policy.go
- webapp/channels/src/components/error_page/error_message.tsx
- webapp/channels/src/components/error_page/error_title.tsx
- webapp/channels/src/components/permalink_view/actions.ts
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/constants.tsx
Added a new global config, `PreservePinnedPosts`, that controls whether data retention should delete pinned posts or not. This config applies to all policies, including channel and team policies. It cannot be configured per policy.
When you pin a post it marks the old post entry as deleted and creates a new post with `IsPinned` set to true. It has the same behaviour when you unpin a post. This means the where clause looks like this:
```sql
WHERE (
Posts.IsPinned = false 
OR (
Posts.IsPinned = true 
AND Posts.DeleteAt > 0
)
)...
```
I did an EXPLAIN ANALYZE on the queries in Postgres and MySQL, the cost is slightly higher with the new filter but it's not much.
**Postgres:**
Preserve pinned posts:
```sql
EXPLAIN ANALYZE DELETE FROM Posts
WHERE (Id)
IN(
SELECT
Posts.Id FROM Posts
INNER JOIN …
```
> [MM-64360] Data retention: optionally preserve pinned posts

- webapp/channels/src/components/threading/global_threads/global_threads.scss
I'm not entirely sure why this only occurred at certain screen sizes, but this stops the thread pane from compressing the thread list
MM-64544
Before|After
-|-
Wider monitors and mobile view were unchanged when I tested
```release-note
Fixed the Threads textbox changing width when a message is typed on certain screen 
```
> MM-64544 Fix width of threads textbox at all screen sizes

- server/build/Dockerfile.buildenv
- server/go.mod
- server/public/go.mod
Update go toolchain version in FIPS 10.8
```release-note
NONE
```
> Update go toolchain version in FIPS 10.8

- webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap
- webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
For some reason an extra class was added that stopped the `Timestamp` component from being read. This PR removes that.
https://mattermost.atlassian.net/browse/MM-62987
```release-note
NONE
```
> [MM-62987] Fix timestamp not actually being read

- webapp/channels/package.json
- webapp/channels/src/utils/performance_telemetry/reporter.ts
- webapp/package-lock.json
Updated the `web-vitals` package from version 4.2.4 to 5.0.3. although there are some breaking changes but they are not applicable to our usage of the library in the project. https://github.com/GoogleChrome/web-vitals/blob/main/CHANGELOG.md 
Jira https://mattermost.atlassian.net/browse/MM-64501
n/a
```release-note
NONE
```
> [MM-64501] Upgrade to v5.0.3 version of web-vitals

- server/i18n/en.json
- webapp/channels/src/components/admin_console/admin_definition.tsx
- webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/index.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_boolean_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_custom_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_dropdown_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_file_upload_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_jobs_table_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
- webapp/channels/src/components/admin_console/types.ts
- webapp/channels/src/components/form_error.tsx
- webapp/channels/src/i18n/en.json
- webapp/channels/src/utils/admin_console_index.test.tsx
- Initial commit on a feature-branch for the new LDAP Wizard
- Purpose of this PR is to move over the rendering of the AD/LDAP page to a new `LDAPWizard` component. This will allow us to control state across the whole page, including:
- error states (and help icons with hover states) on components that are related to other state on the page
- new autocomplete components (that get their state from the server based on the state of the LDAP Wizard's connection)
- log components (state from the server based on LDAP Wizard's state)
- buttons that need to use input from fields that haven't been saved to the config yet
- Could this have been done using the admin definition? Possibly, and I initially tried. But I backtracked after it became too complicated. It would require adding a bunch of …
> [MM-63717] LDAP Wizard skeleton

- api/v4/source/definitions.yaml
- server/public/model/ldap.go
- webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.tsx
- webapp/channels/src/components/admin_console/schema_admin_settings.tsx
- webapp/channels/src/i18n/en.json
- webapp/platform/types/src/admin.ts
- This is the UI component of https://github.com/mattermost/mattermost/pull/31312 and https://github.com/mattermost/enterprise/pull/1934
- @asaadmahmood I kept to most of the design, except for autocomplete (that's complicated for LDAP, but maybe possible -- I'll leave to an enhancement nice to have). I also didn't do the full log with table -- I'm going to do that as a separate PR. I'm putting diagnostic info into the tooltips as the designs suggest, let me know if it looks good to you -- we can control the text and the amount of info, but it's somewhat constrained by the i18n templating system.
- Added three states:
- success (tells you how many records returned)
- warning (successfully parsed the filter, but no results returned)
- error (error in the filter)
- Sister PR here: …
> [MM-64512] - Test user filters UI

- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist_popover.tsx
The checklist used Floating UI to position itself, but it still rendered as part of the rest of the app which caused it to get cut off by `overflow:hidden`. Portalling it up to the root of the DOM where other popovers are rendered prevents that
MM-64372
```release-note
Fixed onboarding checklist being cut off when on multiple teams
```
> MM-64372 Fix onboarding checklist being rendered behind team sidebar

- webapp/channels/src/components/file_preview_modal/file_preview_modal_info/__snapshots__/file_preview_modal_info.test.tsx.snap
- webapp/channels/src/components/file_preview_modal/file_preview_modal_info/file_preview_modal_info.tsx
- webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap
- webapp/channels/src/components/widgets/users/avatars/__snapshots__/avatars.test.tsx.snap
- webapp/channels/src/components/widgets/users/avatars/avatars.tsx
The `Avatars` component was not pass through the username prop to the Avatar component, meaning that it had no proper alt text. This PR adds that.
https://mattermost.atlassian.net/browse/MM-62988
```release-note
NONE
```
> [MM-62988] Add username prop to multi-avatar component

- .github/codecov.yml
We are tweaking the commenting options slightly to only post on uncovered patch lines and hide the project coverage. This will hopefully limit the times the comment is edited in place, although that shouldn't be causing extra notifications, according to the [documentation](https://docs.codecov.com/docs/pull-request-comments#behavior).
```release-note
NONE
```
> Reduce Codecov spam

- webapp/channels/src/components/view_user_group_modal/view_user_group_list_item/view_user_group_list_item.tsx
- webapp/channels/src/i18n/en.json
The Delete button per user on the User Groups modal was using a completely wrong `aria-label`. This PR adds one that is much more descriptive.
```release-note
Fix delete button aria-label on User Groups list modal
```
> Fix delete button aria-label on User Groups list modal

- server/channels/app/limits.go
- server/channels/app/limits_test.go
- server/channels/app/user_limits_test.go
- server/public/model/license.go
Replaces the fixed 5% grace period for user seat limits with a configurable `ExtraUsers` field, providing exact control over additional seats beyond the base license limit.
**Changes:**
- Add configurable `ExtraUsers` field for precise control over additional seats
- Remove fixed 5% grace period and minimum 1 extra user logic  
- When `ExtraUsers` is nil, defaults to 0 (creates hard cap with no overage when `IsSeatCountEnforced` is true)
- Maintain special case: zero user licenses always return 0 grace limit
Fixes https://github.com/mattermost/mattermost/issues/31628
N/A - No UI changes
```release-note
Replaced fixed 5% grace period for user seat limits with configurable ExtraUsers field for exact control over additional seats.
```
> feat: Replace 5% grace period with configurable ExtraUsers field

- webapp/channels/src/components/threading/global_threads/thread_item/thread_item.scss
The styling on the thread item broke as I missed changing the styling on the `thread_item` header. This PR switches to using the class instead of the element name.
https://mattermost.atlassian.net/browse/MM-64639
```release-note
NONE
```
> [MM-64639] Fix styling on thread item header

- e2e-tests/playwright/specs/functional/channels/threads/threads_list.spec.ts
- webapp/channels/src/components/admin_console/admin_definition_ldap_wizard.tsx
- webapp/channels/src/components/admin_console/custom_profile_attributes/custom_profile_attributes.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_button_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_text_setting.tsx
- webapp/channels/src/components/admin_console/ldap_wizard/ldap_wizard.scss
- This is a little PR to highlight the in product i18n string additions for @cwarnermm 's review
- Please expand the area around the lines that are changed just to make sure you see them all -- I made some changes so the new strings are highlighted in this PR, but a few of them didn't need changes. They're all together in these two groups, plus the areas in the `admin_definition_ldap_wizard.tsx` which didn't need changes, so I rearranged the code to highlight them)
- Also this is a commit point for @asaadmahmood to run on his local machine for a UX pass. Make sure you have the LDAP docker container running, and you have the Enterprise repo up to date with master, and then you can experiment with the LDAP filters and attributes. I use the `test-ldap.ldif` file for reference as I did this, …
> [MM-64603] LDAP Wizard: UX and Copy

- server/channels/api4/apitestlib.go
- server/channels/api4/plugin_test.go
- server/channels/app/helper_test.go
- server/channels/app/plugin.go
- server/channels/app/plugin_install.go
- server/channels/app/plugin_prepackaged_test.go
- server/channels/app/plugin_signature.go
- server/channels/app/plugin_test.go
- server/public/plugin/environment.go
We have always required signatures for packages installed via the marketplace -- whether remotely satisfied, or sourced from the prepackaged plugin cache.
However, prepackaged plugins discovered and automatically installed on startup did not require a valid signature. Since we already ship signatures for all Mattermost-authored prepackaged plugins, it's easy to simply start requiring this.
Distributions of Mattermost that bundle their own prepackaged plugins will have to include their own signatures. This in turn requires distributing and configuring Mattermost with a custom public key via `PluginSettings.SignaturePublicKeyFiles`.
Fixes: https://mattermost.atlassian.net/browse/MM-64627
```release-note
Always validate signatures for pre-packaged plugins.
```
> Always require signatures for prepackaged plugins

- server/channels/api4/job_local.go
- server/cmd/mmctl/client/client.go
- server/cmd/mmctl/commands/compliance_export.go
- server/cmd/mmctl/commands/compliance_export_e2e_test.go
- server/cmd/mmctl/commands/compliance_export_test.go
- server/cmd/mmctl/commands/export.go
- server/cmd/mmctl/commands/export_e2e_test.go
- server/cmd/mmctl/commands/mmctl_test.go
- server/cmd/mmctl/docs/mmctl_compliance-export.rst
- server/cmd/mmctl/docs/mmctl_compliance-export_download.rst
- server/cmd/mmctl/docs/mmctl_compliance_export_download.rst
- server/cmd/mmctl/mocks/client_mock.go
- server/public/model/client4.go
- Added `download` cmd
- continuation of https://github.com/mattermost/mattermost/pull/30569
- Some customers are using one-off (buggy) scripts to do compliance_export mgmt, this series of PRs will fix that (and will be well tested, unlike the scripts).
- Plus, we removed the compliance_export cmds from the MM binary in 10.5. We weren't sure if anyone used them, but we need to replace them just in case.
- https://mattermost.atlassian.net/browse/MM-63556
```release-note
mmctl: Add compliance export download cmd
```
> [MM-63556] mmctl: Add compliance export download cmd

- e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js
- e2e-tests/playwright/specs/accessibility/channels/account_settings_sidebar.spec.ts
- server/public/model/channel.go
- webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx
- webapp/channels/src/sass/routes/_settings.scss
Unfortunately, some changes in https://github.com/mattermost/mattermost/pull/30338 broke this, and the changes to the Cypress tests made covered that up. I didn't realize there were Cypress tests when I added that, so now we have two sets of tests for that though. 😅
I also made a couple small fixes to those components that aren't related to those changes, so I'll note them accordingly.
MM-64669
```release-note
Fixed keyboard navigation in user settings sidebar
```
> MM-64669 Fix keyboard navigation of settings sidebar

- webapp/channels/src/sass/layout/_sidebar-right.scss
The line height here caused some accents in Vietnamese to be cut off. Removing the `line-height` fixes the accent being cut off, but it also slightly changes the vertical position of that text if that's a concern
Issue reported here: https://community.mattermost.com/core/pl/skakydy4gpfwmjhzukjc3sizge
In Firefox:
|----|----|
|<img width="413" alt="Screenshot 2025-06-23 at 2 37 16 PM" src="https://github.com/user-attachments/assets/84dba4b4-eb17-4d73-b38f-a96c34dff228" />|<img width="413" alt="Screenshot 2025-06-23 at 2 37 19 PM" src="https://github.com/user-attachments/assets/de07773d-42a3-416f-a212-1da62ca18a94" />
```release-note
Fix accents 
```
> Increase line height in RHS header

- server/channels/app/access_control.go
- server/channels/app/access_control_test.go
- webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
- webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx
- webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
While we are here, we also remove the unnecessary logic for "to be removed" logic. The actual bug about not being able to unassign multiple policies was related to map iteration.
https://mattermost.atlassian.net/browse/MM-64630
```release-note
NONE
```
> [MM-64630] Fix an issue where multiple channels can't be removed from policies

- server/channels/app/user.go
Only log a warning when the created user exceeds the `MaxUserLimits` if `MaxUsersLimit > 0`. This was showing up spuriously on licensed servers for which no actual limit applied.
Note that this is distinct from blocking user creation past `MaxHardUsersLimit` -- the log exists to warn users about the intermediate state between soft and hard user limits.
None.
```release-note
NONE
```
> remove spurious user limits log

- server/Makefile
- Prepackage calls v1.9.2 to 10.5 to resolve a customer's crash
- @amyblais Can you assign to the correct milestone and let me know the correct cherry pick command (if needed)?  Thank you!
- https://mattermost.atlassian.net/browse/MM-64748
```release-note
Prepackage Calls v1.9.2
```
> [MM-64748] Prepackage Calls v1.9.2 to 10.5

- .github/workflows/server-ci-template.yml
- .github/workflows/server-test-template.yml
- .github/workflows/webapp-ci-template.yml
Generating coverage on cherry-picked PRs isn't very valuable, so we skip the job in such a case.
```release-note
NONE
```
> Skip code coverage generation on cherry-pick PRs

- server/cmd/mmctl/commands/ldap.go
- server/cmd/mmctl/commands/ldap_e2e_test.go
- server/cmd/mmctl/docs/mmctl_ldap_idmigrate.rst
- server/cmd/mmctl/docs/mmctl_ldap_job_list.rst
- server/cmd/mmctl/docs/mmctl_ldap_job_show.rst
- server/cmd/mmctl/docs/mmctl_ldap_sync.rst
Fixes https://github.com/mattermost/mattermost/issues/31894
@cpoile Let me know if there's more to consider regarding autocompletion logic.
https://mattermost.atlassian.net/browse/MM-64663
```release-note
Fixed potential panic when running the `mmctl ldap job show` without the required argument.
```
> [MM-64663] Fix potential panic in `mmctl ldap job show` command

- e2e-tests/cypress/tests/integration/channels/search/mobile_search_spec.js
- webapp/channels/src/components/search/index.tsx
- webapp/channels/src/components/suggestion/search_suggestion_list.tsx
The missing `return` caused the `SearchChannelProvider` to not be able to get results from the server.
MM-64681
```release-note
Fixed in: filter not showing an autocomplete on small screens
```
> MM-64681 Fix in: filter in mobile search box

- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx
- webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx
- webapp/channels/src/components/channel_invite_modal/index.ts
The initial work for filter user list in abac invite channel https://github.com/mattermost/mattermost/pull/31219 missed a part where the channel invite component in abac channel was still grabbing the global state list of users, so initially it was just going to populate this with the results of the search api call, and it was doing this correctly, but as soon as user interacts with other part of the app that would populate the state with the full list of users (i.e tagging users), that would cause the invite modal list to show the full list of users. This PR makes sure that the abac channels will only rely in the component state and the fetched user list from the api.
https://mattermost.atlassian.net/browse/MM-64713
Before:
https://github.com/user-attachments/assets/28a8d3bc-3074-43bb-901 …
> MM-64713 - channel invite modal in abac channel should keep filtered list of users

- webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal.scss
Removes the preview modal button when in calls expanded view so that it's not overlapping
https://mattermost.atlassian.net/browse/CLD-9351
before: 
after:
```release-note
None
```
> [CLD-9351] Remove preview modal button when in calls view

- webapp/channels/src/components/common/hooks/useOpenSalesLink.ts
- webapp/channels/src/components/common/hooks/use_external_link.ts
useOpenSalesLink was skipping logic in useExternalLink around utm and other marketing parameters (and their adjustments for Cloud and Cloud Preview environments). This PR makes useOpenSalesLink base its query parameters off of useExternalLink first, then adds in the sales-form autofill specific fields after. 
This also fixed CLD-9352 - it won't send the sales-form specific fields in the event of a Cloud Preview, since the logged in user is a dummy pre seeded one.
https://mattermost.atlassian.net/browse/CLD-9353
https://mattermost.atlassian.net/browse/CLD-9352
```release-note
None
```
> [CLD-9535] [CLD-9352] Adjust useOpenSalesLink bases its query parameters on useExternalLink

- server/channels/app/post_metadata.go
- server/channels/app/post_metadata_test.go
- server/channels/store/storetest/link_metadata_store.go
Cherry pick of #31814 on release-10.10.
```release-note
NONE
```
> Automated cherry pick of #31814

- server/channels/store/sqlstore/attributes_store.go
- server/channels/store/storetest/attributes_store.go
When a `select` type attribute gets cleared from a user, we don't actually delete it. Instead, we are creating an empty string. Since we are trying to join that with `PropertyField.Attr.options`, we get a `NULL` result. 
And unfortunately in DB `NULL != FALSE`, we should treat it with a `COALESCE` call. 
Since we are here, added more unit tests to improve maintainability.
https://mattermost.atlassian.net/browse/MM-64719
```release-note
NONE
```
> [MM-64719] fix select type being ignored when it's null

- server/public/model/remote_cluster.go
Increases rounds from 100K to 600K in PBKDF2 for shared channel encryption key
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2
```release-note
NONE
```
> Increase pbkdf2 rounds to OWASP recommendation

- webapp/channels/src/sass/components/_post.scss
- webapp/channels/src/sass/responsive/_mobile.scss
- webapp/channels/src/utils/utils.tsx
[One of the changes](https://github.com/mattermost/mattermost/pull/31008/files#diff-d6177135b34f4a9fb6057af1f126076a8f1c8359374fd435cdcaaf6cd5d21d5bR384) in https://github.com/mattermost/mattermost/pull/31008 accidentally affected more than it should have because those lines style way too much at once. I moved the intentional change from that into the CSS, and I reverted that change for the unintentional ones
While I was in there, I also took the opportunity to chip away a bit at moving the rest of that to use CSS variables
MM-64880
Before|After
-|-
```release-note
Fixed colour of borders in Browse Channels and Direct Messages modals
```
> MM-64880 Revert change to border colour in list modals and remove a few things from applyTheme

- server/build/Dockerfile
- server/build/passwd
**Problem**
When using sslmode=require in PostgreSQL connection strings, Mattermost containers based on distroless images were failing with: `error setting up connections: stat /home/nonroot/.postgresql/postgresql.crt: permission denied`
**Root Cause**
The PostgreSQL client library expects to find a `~/.postgresql/` directory in the user's home directory for SSL configuration. In distroless images:
* The mattermost user's home directory was set to `/home/nonroot` (owned by distroless nonroot user)
* The mattermost user (UID 2000) couldn't access `/home/nonroot` (owned by UID 65532)
* The `~/.postgresql/` directory didn't exist
**Changes**
* Dockerfile changes: Create `/mattermost/.postgresql/` directory with proper permissions (700)
* passwd changes: Change mattermost user's home …
> Fix PostgreSQL SSL connection issue with sslmode=require in distroless images

- server/public/plugin/api.go
The `GetUsers` API doesn't respect all of the parameters provided by `UserGetOptions`. For now instead of fixing it we'll simply document it so that plugin developers know.
https://mattermost.atlassian.net/browse/MM-56322
```release-note
NONE
```
> [MM-56322] Document GetUsers plugin API limitation

- server/public/model/slack_attachment.go
- server/public/model/slack_attachment_test.go
Attachments fields of type `any` were not being checked for their ability to be an `interface{}` type, which would require `reflect.DeepEqual`. This PR makes that check.
https://mattermost.atlassian.net/browse/MM-64894
```release-note
Fixed a potential crash in UpdatePost
```
> [MM-64894] Check for non-primitive fields using DeepEqual

- webapp/channels/webpack.config.js
- webapp/package-lock.json
Fix 3 critical vulnerabilities in npm packages. The remaining critical is a false positive for the `mattermost-webapp` npm  https://github.com/advisories/GHSA-r5gc-r4qf-2vh7 package which is flagged as extremely dangerous but it shares name with our mattermost-webapp local build package and npm auditory catches it as a vulnerable package but as said before, is a false positive.
n/a
Before:
After:
```release-note
NONE
```
> Fix npm vulnerabilities

- webapp/channels/src/components/login/login.tsx
There are cases where a user might miss redirecting to the browser to login from the Desktop App and need to restart the process. The current workaround was to refresh the page, but that's not an ideal UX.
This PR adds the back button like other login pages have to bring the user back to the login screen where they can just try again.
https://mattermost.atlassian.net/browse/MM-64685
```release-note
Show back button on desktop external login redirect page
```
> [MM-64685] Show back button on desktop external login redirect page

- webapp/channels/src/components/setting_item_max.tsx
The auto focus code was not accounting for the `extraContentBeforeSettingList` section, which could contain focusable elements. This PR moves the ref so that we check the whole section for focusable elements.
https://mattermost.atlassian.net/browse/MM-62991
```release-note
Ensure extra content is also accounted for in the focus order
```
> [MM-62991] Ensure extra content is also accounted for in the focus order

- e2e-tests/cypress/tests/integration/channels/channel/channel_settings_modal_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel/channel_settings_spec.ts
- e2e-tests/cypress/tests/integration/channels/channel_settings/channel_name_validations_spec.ts
- webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.test.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
MM-64725 - channel settings modal do not update url automatically
https://mattermost.atlassian.net/browse/MM-64725
After:
https://github.com/user-attachments/assets/530d2fd0-7f0a-4e99-a92c-72ff3028eeeb
```release-note
NONE
```
> MM-64725 - channel settings modal do not update url automatically

- webapp/channels/src/components/suggestion/switch_channel_provider.test.tsx
- webapp/channels/src/components/suggestion/switch_channel_provider.tsx
- webapp/channels/src/components/widgets/inputs/input/input.scss
- webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.test.ts
- webapp/channels/src/packages/mattermost-redux/src/utils/user_utils.ts
This pr fixes a regression where users could no longer be searched when searching by full email addresses containing "@" in user search modals (DM modal, channel switcher, add members). The solutions is implementing smart context-aware email search so when search term contains "@": full email addresses will be included in suggestions and when the search term do not include the "@" only email prefixes will be used.
https://mattermost.atlassian.net/browse/MM-64955
Before:
https://github.com/user-attachments/assets/95e791b2-91db-4e2b-a4db-9b1d393a3470
After:
https://github.com/user-attachments/assets/0860fd60-0bcf-4d43-a333-0ec640ec2325
```release-note
NONE
```
> MM-64955 - search user email at issue

- server/Makefile
Explicitly remove all prepackaged plugins by `undefine`ing the variable.
https://mattermost.atlassian.net/browse/MM-64987
```release-note
NONE
```
> MM-64987: Remove all prepackaged plugins

- webapp/scripts/update-versions.mjs
We need this for https://github.com/mattermost/delivery-platform/pull/322 to work, and we need that to let us cut the 10.12 branch.
```release-note
NONE
```
> Add script to update web app package versions going forward (10.11)

- .github/workflows/build-server-image.yml
- .github/workflows/dispatch-server-builder-image.yml
We need to identify ourselves to Chainguard for pulling images during build steps. Note that the identity value is not a secret, at least in so far as we're already using it this way over at
https://github.com/mattermost/mattermost/pull/33549/files.
This should fix the build failure: 
Relates-to: https://mattermost.atlassian.net/browse/MM-65018
```release-note
NONE
```
> Use chainctl for fips build images

- webapp/channels/src/components/post_profile_picture/post_profile_picture.tsx
- webapp/channels/src/components/profile_picture/index.tsx
- webapp/channels/src/components/widgets/users/avatar/avatar.tsx
- webapp/channels/src/sass/components/_post.scss
- Remove padding from status and adjust its position in compact mode
https://mattermost.atlassian.net/browse/MM-63579
|----|----|
| <img width="1384" height="784" alt="CleanShot 2025-08-11 at 8  33 06@2x" src="https://github.com/user-attachments/assets/a68ae5ad-a306-4f32-a45e-c3ad1bfe3f5d" /> | <img width="1384" height="784" alt="CleanShot 2025-08-11 at 8  33 40@2x" src="https://github.com/user-attachments/assets/89fa6d20-9157-42a5-a99c-1468a3e6d7c3" /> |
```release-note
NONE
```
> [MM-63579] Missing status indicator in compact display mode

- NOTICE.txt
- webapp/channels/package.json
- webapp/channels/src/sass/layout/_markdown.scss
- webapp/channels/src/sass/layout/_sidebar-left.scss
- webapp/package-lock.json
- webapp/package.json
This is one of the dependencies that would've needed to be updated to support React 18, but it turns out that it's not actually used as of https://github.com/mattermost/mattermost/pull/26856, so we can just remove it instead.
MM-51230
```release-note
NONE
```
> MM-51230 Remove unused react-contextmenu dependency

- .github/workflows/server-ci.yml
- .github/workflows/webapp-ci.yml
Fixes CI workflow evaluation error that was preventing the full test suite from running on master branch pushes since commit 95a9bcec289bb4403fdd0ad415cbb0be6113edc9:
Replace the empty string fallback with `github.run_id`, ensuring each master build gets a unique concurrency group while maintaining the intended behavior:
- **Pull requests**: Proper concurrency control with `cancel-in-progress: true`
- **Master builds**: Each gets unique concurrency group, allowing simultaneous execution
```release-note
NONE
```
> Fix CI concurrency group evaluation error for master builds

- .github/workflows/build-server-image.yml
- server/build/Dockerfile.buildenv
- server/build/Dockerfile.buildenv-fips
Install Node inside the `mattermost-build-server` Docker containers, used as part of CI/CD.
Relates-to: https://mattermost.atlassian.net/browse/MM-64878
```release-note
NONE
```
> add Node to mattermost-build-server

- .github/workflows/mmctl-test-template.yml
- .github/workflows/server-ci.yml
- .github/workflows/server-test-template.yml
- server/Makefile
Consistently use the mattermost-build-server image instead of sometimes building on ubuntu. This unlocks the next change in which we can switch to using the FIPS container image seamlessly.
Broken down into detailed commits for your reviewing ease!
- [`7d84996`](https://github.com/mattermost/mattermost/pull/33679/commits/7d84996) - compute the Go version more centrally
- [`17a3481`](https://github.com/mattermost/mattermost/pull/33679/commits/17a3481) - use the mattermost-build-server instead of setting up Go manually
- [`9c92ada`](https://github.com/mattermost/mattermost/pull/33679/commits/9c92ada) - work around "error obtaining VCS status: exit status 128" in a container"
- [`98c516d`](https://github.com/mattermost/mattermost/pull/33679/commits/98c516d) - no longer require sudo since now …
> consolidate go version computation

- webapp/channels/package.json
- webapp/package-lock.json
- webapp/platform/client/package.json
- webapp/platform/mattermost-redux/package.json
- webapp/platform/types/package.json
Normally, this would be done automatically as part of the release pipeline, but similar to https://github.com/mattermost/mattermost/pull/33709, that step isn't done automatically when we make one release branch from another
```release-note
NONE
```
> Update web app and subpackage versions to 10.12.0 (release-10.12)

- server/build/Dockerfile.buildenv
- server/build/Dockerfile.buildenv-fips
This PR resets the entrypoint to both build environment Dockerfiles (`Dockerfile.buildenv` and `Dockerfile.buildenv-fips`) to unify invoking either a shell or running a command without jumping through hoops.
```release-note
NONE
```
> Unify entrypoint for build Dockerfiles

- webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap
- webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.test.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_access_rules_tab.test.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_access_rules_tab.tsx
- webapp/channels/src/hooks/useChannelAccessControlActions.ts
This PR adds the logic to integrate the save changes panel with the save policies in the backend allowing admins to actually store the changes made by them and create/update the policy.
https://mattermost.atlassian.net/browse/MM-65074
```release-note
NONE
```
> MM-65074 - channel admin save policy flow

- e2e-tests/cypress/tests/integration/channels/channel_settings/more_unreads_position_with_scroll_spec.ts
I think its from this PR https://github.com/mattermost/mattermost/pull/33783, that it was forgotten to remove the unused import.
```release-note
NONE
```
> Fix lint error breaking smoke tests

- server/build/Dockerfile.buildenv-fips
Add `xmlsec1` to the build image used for FIPS builds.
None
```release-note
NONE
```
> add xmlsec1 to FIPS docker build image

- server/channels/api4/channel.go
- server/channels/api4/channel_test.go
- server/channels/api4/user.go
- server/public/model/channel_member.go
- server/public/model/channel_member_test.go
Cherry pick of #33835 on release-10.12.
```release-note
NONE
```
> Automated cherry pick of #33835

- server/channels/jobs/base_workers.go
This log line is triggered quite often as some of our works run frequently, like the persistent notification one. This makes the Info log file quite convoluted. The other log lines regarding the `SimpleWorker` also run `Debug`.
https://community.mattermost.com/core/pl/ifxt4y4477gk3x8ugwnwdt83ie
```release-note
NONE
```
> Lower Job complete log message to debug

- webapp/channels/src/components/login/login.tsx
I repositioned the desktop auth token validation to occur before the configuration checks. This change won't affect existing servers, but it allows servers using the pre-auth header to redirect to the desktop app earlier in the process, before we attempt to validate certain configurations. Those configurations all return false because the request fails in the browser without the pre-auth token.
https://mattermost.atlassian.net/browse/MM-65573
```release-note
NONE
```
> [MM-65573] Fix desktop redirect for pre-auth

- server/Makefile
- server/docker-compose.pgvector.yml
Adds a new command `make run-pgvector` which is a shorthad that wraps the `run` and `run-server` commands to override the base docker-compose database image of postgres/postgres with pgvector/pgvector. This allows for easier local testing of vector search.
N/A
```release-note
None
```
> Add support for pgvector in local dev

- api/v4/source/definitions.yaml
- api/v4/source/users.yaml
This PR makes three updates to the API docs:
1. Updates  the `useAutomaticTimezone` field type to `string` to match implementation
2. Documents more `notify_prop` fields
3. Adds a callout that not all fields will be returned at all times in GET `/api/v4/users`
n/a
n/a
```release-note
NONE
```
> Update api user endpoint docs to fix useAutomaticTimezone type and document more fields

- webapp/channels/src/components/channel_settings_modal/channel_settings_modal.test.tsx
- webapp/channels/src/components/channel_settings_modal/channel_settings_modal.tsx
Cherry pick of #33919 on release-11.0.
/cc  @pvev
```release-note
NONE
```
> Automated cherry pick of #33919

- webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss
- webapp/channels/src/plugins/registry.ts
These are a bit late, but they're small enough that I'm comfortable squeezing them in before feature complete tomorrow. That's also why I'm comfortable jamming them together into a single PR. 😅
This PR does the following:
1. Adds a one-time console warning for each plugin using `registerPostDropdownMenuComponent`
2. Fixes the vertical alignment of icons when using `registerPostDropdownMenuAction`
Screenshots of those can be seen below
https://mattermost.atlassian.net/browse/MM-63447
https://mattermost.atlassian.net/browse/MM-65101
|Current, old version of Playbooks|Current, new version of Playbooks|Branch, new version of Playbooks|
-|-|-
```release-note
Added console warning when a plugin uses the now-deprecated registerPostDropdownMenuComponent API
```
> MM-63447/MM-65101 Remaining changes for deprecated registerPostDropdownMenuComponent API

- webapp/channels/src/components/onboarding_tasks/complete_your_profile_tour_tip.tsx
- webapp/channels/src/components/onboarding_tasks/onboarding_tasks_manager.tsx
- webapp/channels/src/components/onboarding_tasks/start_trial_tour_tip.tsx
- webapp/channels/src/components/onboarding_tasks/visit_system_console_tour_tip.tsx
The current typing for `useCallback` and how the default argument somehow masked that we were now passing arguments wrong as of https://github.com/mattermost/mattermost/commit/8cace746923212ce147e0e9107ed1f81233f1987#diff-0f6c1596ed156b7bd43a5ab6c940fbf2d32560f63d58d88d99ef5834c2d9886f. For whatever reason, the final argument to the callback that's returned by `useHandleOnBoardingTaskList` is treated as `any` which leads to us passing a boolean value as the preference category.
MM-65660
```release-note
NONE
```
> MM-65660 Fix broken calls to save telemetry state

- webapp/channels/src/components/search_results/index.tsx
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.test.ts
- webapp/channels/src/packages/mattermost-redux/src/selectors/entities/posts.ts
Fixed an issue where leaving a channel after jumping to a post from search results would cause a blank page with JavaScript console errors. The root cause was that search results could reference posts that no longer existed in the Redux store, leading to undefined values being processed by UI components.
**QA Test Steps:**
1. Create a channel and post a message
2. Search for words from that message
3. Click "Jump" from search results to navigate to the post
4. Select the channel dropdown and choose "Leave channel"
5. Verify you're redirected to Town Square without errors
Fixes: https://mattermost.atlassian.net/browse/MM-65815
```release-note
NONE
```
> MM-65815: Fix search results causing blank page when leaving channel

- server/channels/store/sqlstore/property_value_store.go
- server/channels/store/storetest/property_value_store.go
- server/public/model/property_value.go
add a since parameter to the plugin api search for properties, which will help plugins do a scoped search in behalf of mobile clients
[MM-65769](https://mattermost.atlassian.net/browse/MM-65769)
```release-note
Added `since` parameter to the property value search method of the PluginApi
```
[MM-65769]: https://mattermost.atlassian.net/browse/MM-65769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-65769] Add UpdatedSince to properties search in pluginapi

- .github/workflows/server-ci.yml
- server/build/Dockerfile.buildenv
- server/build/Dockerfile.buildenv-fips
Build [mattermost-build-server](https://hub.docker.com/repository/docker/mattermost/mattermost-build-server/general) for go 1.24.6. Similar changes for FIPS. Note that this doesn't actually use the image to be built, that will come when we bump `.go-version` in a separate pull request.
As an aside, to expedite this step in the future, I've marked these Docker files to be ignored for server-ci.yml, which doesn't use them anyway.
Relates-to: https://mattermost.atlassian.net/browse/MM-65826
```release-note
NONE
```
> build 1.24.6, ignore Docker.buildenv for server-ci

- webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
Cherry pick of #33961 on release-11.0.
```release-note
NONE
```
> Automated cherry pick of #33961

- e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/shift_up_focuses_on_rhs_spec.js
- e2e-tests/cypress/tests/integration/channels/messaging/focus_move_spec.js
- webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx
- webapp/channels/src/components/advanced_text_editor/use_textbox_focus.tsx
Cherry pick of #33965 on release-11.0.
```release-note
NONE
```
> Automated cherry pick of #33965

- e2e-tests/.ci/server.generate.sh
- server/build/docker-compose.common.yml
- server/build/docker-preview/Dockerfile
- server/channels/store/sqlstore/store.go
- server/channels/store/sqlstore/store_test.go
Bump the minimum supported version of Postgres to 14.
This needs https://github.com/mattermost/mattermost/pull/34009 to be merged to master first.
https://mattermost.atlassian.net/browse/MM-65983
--
```release-note
The minimum supported version for Postgres was bumped to 14.
```
> MM-65983: Bump Postgres minimum supported version to 14

- webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap
- webapp/channels/src/i18n/i18n.jsx
French language has been consistently below the 79% quality threshold for more than three months. Downgrading it from Beta to Alpha.
```release-note
Downgraded French language support from Beta to Alpha.
```
> Downgrade French language

- webapp/channels/src/components/admin_console/admin_definition.tsx
Fix in ABAC/Edit Policy and Content Flagging to use `minLicenseTier` instead of checking directly for `Enterprise Advance` so that it could work properly for Entry sku as well. 
https://mattermost.atlassian.net/browse/MM-66077
```release-note
NONE
```
> Fix license checks in System Console in Entry

- webapp/channels/src/components/admin_console/admin_definition.tsx
Cherry pick of #34027 on release-11.0.
```release-note
NONE
```
> Automated cherry pick of #34027

- e2e-tests/playwright/lib/src/ui/components/channels/settings/sidebar_settings.ts
- e2e-tests/playwright/specs/accessibility/channels/settings_dialog/sidebar.spec.ts
- e2e-tests/playwright/specs/accessibility/channels/settings_dialog/sidebar.spec.ts-snapshots-a11y/group-unread-channels-section.yml
- e2e-tests/playwright/specs/accessibility/channels/settings_dialog/sidebar.spec.ts-snapshots-a11y/number-of-direct-messages-section.yml
This PR adds comprehensive accessibility tests for the Sidebar Settings panel, following the established pattern from the
Notifications settings tests.
Created `specs/accessibility/channels/settings_dialog/sidebar.spec.ts` with 4 test cases:
- Keyboard navigation test (Tab and Arrow key navigation through interactive elements)
- Main Sidebar settings panel accessibility scan with aria-snapshot
- "Group unread channels separately" section accessibility scan when expanded
- "Number of direct messages to show" section accessibility scan when expanded
Extended `SidebarSettings` page object with:
- Edit buttons for each setting section (`groupUnreadEditButton`, `limitVisibleDMsEditButton`)
- Properties for expanded section handling
- Container and element locators using role-based …
> GH-34031: Add accessibility tests for Sidebar settings panel

- webapp/channels/src/components/admin_console/system_properties/user_properties_table.test.tsx
- webapp/channels/src/components/admin_console/system_properties/user_properties_table.tsx
- webapp/channels/src/components/admin_console/system_properties/user_properties_values.test.tsx
- webapp/channels/src/components/admin_console/system_properties/user_properties_values.tsx
- webapp/platform/types/src/properties.ts
Fixes auto focus stability System Console > User Attributes. The Title/Attribute field would steal focus after entering the first option-value. Fixed by making autofocus conditional, and redirecting it to the option-value column when switching field type to select/multiselect.
- [https://mattermost.atlassian.net/browse/MM-65807](https://mattermost.atlassian.net/browse/MM-65807)
| before | after |
| ------ | ----- |
|  https://github.com/user-attachments/assets/33d545ee-19f4-4f2c-8485-cd4436cfd81f  |  https://github.com/user-attachments/assets/1ef521e9-e551-404c-a4bd-7dea37400b5b |
```release-note
NONE
```
> MM-65807: fix focus stability in System Console > User Attributes

- server/cmd/mmctl/commands/init.go
- server/cmd/mmctl/commands/root.go
- server/cmd/mmctl/commands/system.go
- server/cmd/mmctl/commands/system_test.go
Fix `mmctl system status` to return non-zero exit codes when health checks fail. This addresses a customer blocker where AWS ECS health checks were broken after the distroless Docker image change, as they rely on exit codes to determine service health.
See https://hub.mattermost.com/private-core/pl/5hwu8foz8pgmfk7m9uhxkh881a for more details.
**Changes:**
- Return error (non-zero exit) when server status != "OK"
- Return error when database_status != "OK"  
- Return error when filestore_status != "OK"
- Return success (exit code 0) only when all components are healthy
Fixes https://mattermost.atlassian.net/browse/MM-65830
```release-note
Fixed mmctl system status to return non-zero exit codes when health checks fail, ensuring proper integration with container orchestration health check …
```
> [MM-65830] Fix mmctl system status exit code for health check failures

- server/channels/store/sqlstore/property_field_store.go
- server/channels/store/storetest/property_field_store.go
- server/public/model/property_field.go
Follow up to https://github.com/mattermost/mattermost/pull/33959
Add updatedSince to property field search
While this isn't strictly needed right now for displaying playbook run attributes, we might need this in the near future when we allow to add/remove attributes
[MM-65769](Jira https://mattermost.atlassian.net/browse/MM-65769)
This goes along with the previous PR and doesn't need a separete release note
```release-note
NONE
```
[MM-65769]: https://mattermost.atlassian.net/browse/MM-65769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [MM-65769] add updatedSince to field search

- webapp/channels/src/tests/setup_jest.ts
This seems to fix the issue where unit tests are leaking massive amounts of memory since https://github.com/mattermost/mattermost/pull/33858.
I thought I needed this as part of https://github.com/mattermost/mattermost/pull/33858 because I saw some of the tests connecting to my local dev instance, but I reproed that on a previous commit, so that's just the existing behaviour apparently. It seemed like a worse problem when I was working on React 18, so I don't know why it's not a problem now.
https://mattermost.atlassian.net/browse/MM-66128
```release-note
NONE
```
> MM-66128 Remove nock.disableNetConnect
