mattermost/mattermost

webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/__snapshots__/sidebar_channel_link.test.tsx.snap, webapp/channels/src/components/sidebar/sidebar_channel/sidebar_channel_link/sidebar_channel_link.tsx, webapp/channels/src/sass/layout/_sidebar-left.scss
Cherry pick of #27172 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27172

server/Makefile
Cherry pick of #27352 on release-9.10.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #27352

server/Makefile
Prepackage boards back into the Mattermost server.
Ticket link: https://mattermost.atlassian.net/browse/MM-58315
```release-note
NONE
```
=> [MM-58315]: prepackage boards to v9.5+

server/Makefile
Cherry pick of #27307 on release-9.10.
/cc  @Rajat-Dabade
```release-note
NONE
```
=> Automated cherry pick of #27307

server/Makefile
Cherry pick of #27307 on release-9.7.
```release-note
NONE
```
=> Cherry pick of #27307

server/Makefile
Cherry pick of #27307 on release-9.8.
```release-note
NONE
```
=> Cherry pick #27307

server/config/client.go, server/public/model/feature_flags.go
Cherry pick of #27397 on release-9.9.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27397

server/platform/services/sharedchannel/channelinvite.go, server/platform/services/sharedchannel/channelinvite_test.go
Cherry pick of #27357 on release-9.5.
/cc  @wiggin77
```release-note
NONE
```
=> Automated cherry pick of #27357

webapp/channels/src/utils/performance_telemetry/reporter.test.ts, webapp/channels/src/utils/performance_telemetry/reporter.ts
Cherry pick of #27396 on release-9.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27396

server/Makefile
Cherry pick of #27425 on release-9.10.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #27425

server/enterprise/metrics/metrics.go
Cherry pick of #27417 on release-9.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27417

webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/__snapshots__/keyboard_shortcuts_modal.test.tsx.snap, webapp/channels/src/components/keyboard_shortcuts/keyboard_shortcuts_modal/keyboard_shortcuts_modal.tsx
Make keyboard shortcuts modal content div accessible via keyboard
https://mattermost.atlassian.net/browse/MM-55973
https://github.com/mattermost/mattermost/assets/16203333/f78e7161-eb08-4c0c-a09d-03ac4d6aab96
```release-note
UI: Make keyboard shortcuts modal content div accessible via keyboard
```
=> MM-55973: Make keyboard shortcuts modal content div accessible via keyboard

webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap, webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx, webapp/channels/src/components/edit_channel_header_modal/index.ts, webapp/channels/src/components/textbox/textbox_links.tsx, webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx, webapp/channels/src/utils/constants.tsx
Cherry pick https://github.com/mattermost/mattermost/pull/27440
```release-note
NONE
```
=> Cherry pick MM-59059 to v9.5

webapp/channels/src/components/header_footer_route/header.scss, webapp/channels/src/components/header_footer_route/header.tsx, webapp/channels/src/components/signup/signup.scss
Cherry pick of #27394 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27394

server/channels/api4/user.go, server/channels/api4/user_test.go, server/channels/app/notification.go, server/platform/services/sharedchannel/sync_recv.go, server/platform/services/sharedchannel/util.go, server/public/model/user.go, server/public/model/user_test.go
Cherry pick of #27421 on release-9.7.
/cc  @wiggin77
```release-note
NONE
```
=> Automated cherry pick of #27421

webapp/channels/src/components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx, webapp/channels/src/components/with_tooltip/create_tooltip.tsx, webapp/channels/src/components/with_tooltip/index.tsx
Fixes https://github.com/mattermost/mattermost/issues/27236
Jira https://mattermost.atlassian.net/browse/MM-58510
```release-note
NONE
```
=> [MM-58510] Migrate tooltips of "components/file_preview_modal/file_preview_modal_main_actions/file_preview_modal_main_actions.tsx" to WithTooltip

webapp/channels/src/components/file_attachment/__snapshots__/filename_overlay.test.tsx.snap, webapp/channels/src/components/file_attachment/filename_overlay.tsx
Replaces OverlayTrigger and Tooltip, with WithTooltip in the filename_overlay component
Fixes [#27156](https://github.com/mattermost/mattermost/issues/27156)
Jira: https://mattermost.atlassian.net/browse/MM-58407
```release-note 
NONE
```
=> [MM-58407] Migrate tooltips of 'components/file_attachment/filename_overlay' to WithTooltip

webapp/channels/src/components/hint-toast/hint_toast.scss
Jira https://mattermost.atlassian.net/browse/MM-59064
```release-note
NONE
```
=> [MM-59064] Close Icon is not in line with toast text of "search this channel" when RHS threads panel is open

webapp/channels/src/components/hint-toast/hint_toast.scss
Cherry pick of #27464 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27464

webapp/channels/src/components/threading/global_threads/global_threads.scss
Cherry pick of #27428 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27428

webapp/channels/src/components/admin_console/admin_definition.tsx
Cherry pick of #27483 on release-9.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27483

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss, webapp/channels/src/components/announcement_bar/__snapshots__/text_dismissable_bar.test.tsx.snap, webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx, webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx, webapp/channels/src/components/status_dropdown/status_dropdown.scss, webapp/channels/src/sass/components/_announcement-bar.scss
Cherry pick of #27461 on release-9.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27461

server/build/docker-compose.common.yml, server/platform/shared/filestore/s3store.go
Updated necessary code to handle latest Minio version
https://mattermost.atlassian.net/browse/MM-57375
```release-note
NONE
```
=> MM-57375: Update to latest minio image

e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js, e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js, e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js, webapp/channels/src/components/admin_console/admin_definition.tsx
This PR adds some rules to ensure IDs respect a certain format in the system console.
https://mattermost.atlassian.net/browse/MM-58840
```release-note
NONE
```
=> [MM-58840] Add routing restrictions

server/platform/services/sharedchannel/service.go, server/platform/services/sharedchannel/sync_recv.go, server/platform/services/sharedchannel/util.go, server/public/model/shared_channel.go, server/public/model/user.go, server/public/model/user_test.go
Cherry pick of #27170 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27170

e2e-tests/cypress/tests/integration/channels/enterprise/system_console/group_configuration_spec.js, e2e-tests/cypress/tests/integration/channels/enterprise/system_console/team_members_spec.js, e2e-tests/cypress/tests/integration/channels/system_console/user_management_spec.js, webapp/channels/src/components/admin_console/admin_definition.tsx
Cherry pick of #27482 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27482

server/channels/api4/team.go, server/channels/api4/team_test.go
Cherry pick of #27427 on release-9.10.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27427

server/channels/api4/channel.go, server/channels/api4/channel_test.go
Cherry pick of #27468 on release-9.10.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27468

server/channels/db/migrations/migrations.list, server/channels/db/migrations/mysql/000123_remove_upload_file_permission.down.sql, server/channels/db/migrations/mysql/000123_remove_upload_file_permission.up.sql, server/channels/db/migrations/postgres/000123_remove_upload_file_permission.down.sql, server/channels/db/migrations/postgres/000123_remove_upload_file_permission.up.sql, webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/__snapshots__/guest_permissions_tree.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/guest_permissions_tree/guest_permissions_tree.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/__snapshots__/permissions_tree.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/permissions_tree/permissions_tree.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/strings/groups.tsx
(cherry picked from commit 71c25fb316cfcda9b9af09df9318e153d5e7e66a)
```release-note
NONE
```
=> MM-58525 Fix upload file permissions (#27298)

server/channels/api4/role.go, server/channels/api4/role_test.go
Cherry pick of #27481 on release-9.10.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27481

server/public/model/manifest.go, server/public/model/manifest_test.go
This reverts commit 4acc4796edb2c1ff93e861b4732c1c758ac76371.
https://mattermost.atlassian.net/browse/MM-57738
Closes https://github.com/mattermost/mattermost-plugin-starter-template/pull/199
```release-note
NONE
```
=> [MM-57738] Revert "Added GetPluginID method and tests (#27281)"

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/channels/api4/group.go, server/channels/api4/group_test.go, server/channels/db/migrations/migrations.list, server/channels/db/migrations/mysql/000124_remove_manage_team_permission.down.sql, server/channels/db/migrations/mysql/000124_remove_manage_team_permission.up.sql, server/channels/db/migrations/postgres/000124_remove_manage_team_permission.down.sql, server/channels/db/migrations/postgres/000124_remove_manage_team_permission.up.sql, server/public/model/role.go
Cherry pick of #27395 on release-9.9.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27395

.github/workflows/e2e-fulltests-ci.yml, .github/workflows/e2e-tests-ci-template.yml, e2e-tests/.ci/.e2erc, e2e-tests/.ci/report.publish.sh, e2e-tests/.ci/server.cloud_init.sh, e2e-tests/.ci/server.cloud_teardown.sh, e2e-tests/README.md, e2e-tests/cypress/save_report.js
Cherry pick of #27393 on release-9.10.
```release-note
NONE
```
=> Automated cherry pick of #27393

server/platform/services/sharedchannel/sync_recv.go
Cherry pick of #27613 on release-9.10.
/cc  @wiggin77
```release-note
NONE
```
=> Automated cherry pick of #27613

.github/workflows/server-ci-artifacts.yml
Expanding on our ongoing efforts to enhance security, we are integrating container image scanning into the CI pipeline using Wiz.io https://docs.wiz.io/wiz-docs/docs/github-pipeline
The policy defined, will be providing reports in wiz.io for our teams to review. Will not enforcing CI failure at this point.
https://mattermost.atlassian.net/browse/CLD-8041
```release-note
NONE
```
=> [feat] adding container image scanning

.github/workflows/server-ci-artifacts.yml
Fixup on https://github.com/mattermost/mattermost/pull/27624 Exposing the tag variable to be used in the scanning step.
https://mattermost.atlassian.net/browse/CLD-8041
```release-note
NONE
```
=> [fix] ci container image scanning

server/public/model/config.go
Remove deprecated Config.ProductSettings
https://mattermost.atlassian.net/issues/MM-56655
```release-note
Remove deprecated Config.ProductSettings
```
=> [MM-56655] Remove deprecated Config.ProductSettings

server/Makefile
Cherry pick of #27642 on release-9.11.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #27642

server/public/model/config.go
See https://github.com/mattermost/enterprise/pull/1689
https://mattermost.atlassian.net/browse/MM-55215
```release-note
Remove deprecated LdapSettings.Trace
```
=> [MM-55215] Remove deprecated LdapSettings.Trace

server/channels/app/support_packet.go, server/channels/app/support_packet_test.go, server/einterfaces/ldap.go, server/einterfaces/mocks/LdapInterface.go
Cherry pick of #27571 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27571

server/channels/app/support_packet.go, server/channels/app/support_packet_test.go, server/public/model/packet_metadata.go, server/public/pluginapi/system.go
Cherry pick of #27573 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27573

server/Makefile
Cherry pick of #27645 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27645

NOTICE.txt
Cherry pick of #27655 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27655

webapp/channels/src/utils/notifications.test.ts, webapp/channels/src/utils/notifications.ts
Cherry pick of #27629 on release-9.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27629

webapp/channels/src/components/post_emoji/post_emoji.test.tsx, webapp/channels/src/components/post_emoji/post_emoji.tsx, webapp/channels/src/utils/emoticons.tsx, webapp/channels/src/utils/message_html_to_component.test.tsx, webapp/channels/src/utils/message_html_to_component.tsx
Cherry pick of #27603 on release-9.11.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27603

webapp/channels/src/components/admin_console/system_user_detail/system_user_detail.tsx, webapp/channels/src/components/admin_console/system_users/system_users_list_actions/confirm_manage_user_settings_modal.tsx, webapp/channels/src/components/admin_console/system_users/system_users_list_actions/index.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #27668 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27668

webapp/channels/src/components/confirm_modal_redux/confirm_modal_redux.tsx, webapp/channels/src/components/user_settings/advanced/index.ts, webapp/channels/src/components/user_settings/advanced/join_leave_section/index.ts, webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.test.tsx, webapp/channels/src/components/user_settings/advanced/join_leave_section/join_leave_section.tsx, webapp/channels/src/components/user_settings/advanced/performance_debugging_section/index.ts, webapp/channels/src/components/user_settings/advanced/performance_debugging_section/performance_debugging_section.tsx, webapp/channels/src/components/user_settings/advanced/user_settings_advanced.test.tsx, webapp/channels/src/components/user_settings/advanced/user_settings_advanced.tsx, webapp/channels/src/components/user_settings/display/index.ts, webapp/channels/src/components/user_settings/display/user_settings_display.tsx, webapp/channels/src/components/user_settings/index.tsx, webapp/channels/src/components/user_settings/modal/index.ts, webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx, webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/index.ts, webapp/channels/src/components/user_settings/sidebar/limit_visible_gms_dms/limit_visible_gms_dms.tsx, webapp/channels/src/components/user_settings/sidebar/show_unreads_category/index.ts, webapp/channels/src/components/user_settings/sidebar/show_unreads_category/show_unreads_category.tsx, webapp/channels/src/components/user_settings/sidebar/user_settings_sidebar.tsx, webapp/channels/src/components/widgets/smart_loader/index.tsx, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channel_categories.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts, webapp/channels/src/selectors/views/channel_sidebar.ts
Cherry pick of #27636 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27636

api/v4/source/users.yaml, server/channels/api4/user_test.go, server/public/model/user.go, server/public/model/user_test.go
Cherry pick of #27471 on release-9.11.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27471

e2e-tests/cypress/tests/integration/channels/autocomplete/helpers.ts, e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/crt_settings_spec.js, e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/global_threads_spec.js, e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/replies_spec.js, e2e-tests/cypress/tests/integration/channels/collapsed_reply_threads/unread_spec.js, e2e-tests/cypress/tests/integration/channels/enterprise/elasticsearch_autocomplete/helpers/index.js, e2e-tests/cypress/tests/integration/channels/enterprise/elasticsearch_autocomplete/system_console_spec.js, e2e-tests/cypress/tests/support/ui/post_dropdown_menu.js, e2e-tests/cypress/tests/support/ui/sidebar_left.ts
JIRA: https://mattermost.atlassian.net/browse/MM-57345
From: ~[92% seen on PRs testing ](https://community.mattermost.com/core/pl/ezqh5y7yrj8yuez1ym4fwfhiih)
To: ~[95% in current PR](https://community.mattermost.com/core/pl/runxu4tutpf3zxrtu9ef7y9e4w)
```release-note
NONE
```
=> MM-57354: Fix elastic search e2e tests

server/channels/app/elasticsearch.go
Added debugging logs for investigating ES schema check false alerts.
Fixes https://mattermost.atlassian.net/browse/MM-59479
```release-note
none
```
=> Added a bunch of debugging logs for Elasticsearch index check

webapp/channels/src/components/admin_console/feature_discovery/features/saml.tsx
Cherry pick of #27625 on release-9.10.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27625

webapp/channels/src/components/widgets/header/header.scss, webapp/channels/src/sass/base/_structure.scss, webapp/channels/src/sass/components/_post.scss, webapp/channels/src/sass/layout/_content.scss, webapp/channels/src/sass/layout/_headers.scss
MM-58527 - Fixing overflow issue for autocomplete
Fixes https://mattermost.atlassian.net/browse/MM-58527
```release-note
NONE
```
=> MM-58527 - Fixing overflow issue for autocomplete

webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx, webapp/channels/src/components/announcement_bar/notification_permission_bar/index.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/utils/notifications.test.ts, webapp/channels/src/utils/notifications.ts
Cherry pick of #27607 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27607

server/i18n/en.json
Cherry pick of #27691 on release-9.11.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #27691

webapp/channels/src/utils/performance_telemetry/reporter.test.ts, webapp/channels/src/utils/performance_telemetry/reporter.ts
Cherry pick of #27702 on release-9.11.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #27702

webapp/channels/src/components/integrations/bots/add_bot/__snapshots__/add_bot.test.tsx.snap, webapp/channels/src/components/integrations/bots/add_bot/add_bot.tsx, webapp/channels/src/sass/components/_forms.scss
MM-58849 - Fixing upload button in bot screen
Jira https://mattermost.atlassian.net/browse/MM-58849
```release-note
NONE
```
=> MM-58849 - Fixing upload button in bot screen

server/channels/app/channel_bookmark_test.go, server/channels/app/integration_action_test.go, server/channels/app/user_test.go
Cherry pick of #27715 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27715

server/Makefile
Cherry pick of #27706 on release-9.11.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #27706

webapp/channels/src/components/channel_bookmarks/channel_bookmarks.tsx, webapp/channels/src/components/channel_bookmarks/utils.ts, webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap, webapp/channels/src/components/channel_view/channel_view.test.tsx, webapp/channels/src/components/channel_view/channel_view.tsx, webapp/channels/src/components/channel_view/index.ts
Cherry pick of #27745 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27745

server/public/shared/httpservice/client.go
https://mattermost.atlassian.net/browse/MM-59026
```release-note
NONE
```
=> MM-59026: Update reserved IP ranges

server/public/shared/httpservice/client.go
Cherry pick of #27751 on release-9.11.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #27751

server/channels/store/searchtest/file_info_layer.go, server/channels/store/sqlstore/file_info_store.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job.go, server/public/model/post.go
Cherry pick of #27705 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27705

webapp/channels/src/components/admin_console/team_channel_settings/channel/details/__snapshots__/channel_moderation.test.tsx.snap, webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_moderation.tsx, webapp/channels/src/i18n/en.json
Rename `Channel Moderation` to `Advanced Access Control` in channel management section in the System Console. 
https://mattermost.atlassian.net/browse/MM-57437
|----|----|
| <img width="964" alt="Screenshot 2024-07-25 at 8 31 59 PM" src="https://github.com/user-attachments/assets/e158947e-df9f-4885-b437-670e0f5edb80">| <img width="974" alt="Screenshot 2024-07-25 at 8 59 02 PM" src="https://github.com/user-attachments/assets/19eee593-86c3-4b39-8631-006d708608fe"> |
```release-note
Rename `Channel Moderation` to `Advanced Access Control` in channel management section in the System Console. 
```
=> Rename Channel Moderation to Advanced Access Control

server/channels/app/channel_bookmark_test.go, server/channels/app/integration_action_test.go, server/channels/app/user_test.go, server/channels/store/searchtest/file_info_layer.go, server/channels/store/sqlstore/file_info_store.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job.go, server/public/model/post.go
Cherrypick of #27705 for v9.8
Associated enterprise PR - https://github.com/mattermost/enterprise/pull/1721
Fixes https://mattermost.atlassian.net/browse/MM-58545
```release-note
None
```
=> v9.8 cherrypick of #27705

server/channels/app/integration_action_test.go, server/channels/app/user_test.go, server/channels/store/searchtest/file_info_layer.go, server/channels/store/sqlstore/file_info_store.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job.go, server/public/model/post.go
Cherrypick of #27705 for v9.5
Associated enterprise PR - https://github.com/mattermost/enterprise/pull/1722
Fixes https://mattermost.atlassian.net/browse/MM-58545
```release-note
None
```
=> v9.5 cherrypick of #27705

server/channels/api4/channel.go, server/channels/api4/channel_bookmark.go, server/channels/api4/channel_bookmark_test.go, server/channels/api4/channel_test.go, server/channels/api4/file.go, server/channels/api4/integration_action.go, server/channels/api4/integration_action_test.go, server/channels/api4/post.go, server/channels/api4/post_test.go, server/channels/api4/preference.go, server/channels/api4/webhook.go, server/channels/app/app_iface.go, server/channels/app/authorization.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/post.go, server/channels/app/upload.go, server/cmd/mmctl/commands/post_e2e_test.go
Cherry pick of #27409 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27409

server/channels/app/channel_bookmark_test.go, server/channels/app/integration_action_test.go, server/channels/app/user_test.go, server/channels/store/searchtest/file_info_layer.go, server/channels/store/sqlstore/file_info_store.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job.go, server/public/model/post.go
Cherrypick of #27705 for v9.10
Associated enterprise PR - https://github.com/mattermost/enterprise/pull/1719
Fixes https://mattermost.atlassian.net/browse/MM-58545
```release-note
None
```
=> v9.10 cherrypick of #27705

server/channels/api4/channel.go, server/channels/api4/channel_bookmark.go, server/channels/api4/channel_bookmark_test.go, server/channels/api4/channel_test.go, server/channels/api4/file.go, server/channels/api4/integration_action.go, server/channels/api4/integration_action_test.go, server/channels/api4/post.go, server/channels/api4/post_test.go, server/channels/api4/preference.go, server/channels/api4/webhook.go, server/channels/app/app_iface.go, server/channels/app/authorization.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/post.go, server/channels/app/upload.go, server/cmd/mmctl/commands/post_e2e_test.go
Cherry-pick of #27409 to release-9.9
```release-note
NONE
```
=> [MM-58492][MM-58523] Cherry-pick of #27409 to release-9.9

server/channels/api4/channel.go, server/channels/api4/channel_bookmark.go, server/channels/api4/channel_bookmark_test.go, server/channels/api4/channel_test.go, server/channels/api4/file.go, server/channels/api4/integration_action.go, server/channels/api4/integration_action_test.go, server/channels/api4/post.go, server/channels/api4/post_test.go, server/channels/api4/preference.go, server/channels/api4/webhook.go, server/channels/app/app_iface.go, server/channels/app/authorization.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/post.go, server/channels/app/upload.go, server/cmd/mmctl/commands/post_e2e_test.go
Cherry-pick of #27409 to release-9.8
```release-note
NONE
```
=> [MM-58492][MM-58523] Cherry-pick of #27409 to release-9.8

server/channels/app/import_functions_test.go
Found more flaky tests after https://github.com/mattermost/mattermost/pull/27828:
None
```release-note
NONE
```
=> update missed model.NewUsername() for app.TestZippedImportPostAndReliesWithAttachments

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/channels/api4/file.go, server/channels/api4/integration_action.go, server/channels/api4/integration_action_test.go, server/channels/api4/post.go, server/channels/api4/post_test.go, server/channels/api4/preference.go, server/channels/api4/webhook.go, server/channels/app/app_iface.go, server/channels/app/authorization.go, server/channels/app/file.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/post.go, server/channels/app/upload.go, server/cmd/mmctl/commands/post_e2e_test.go
Cherry-pick of #27409 to release-9.5
```release-note
NONE
```
=> [MM-58492][MM-58523] Cherry-pick of #27409 to release-9.5

webapp/channels/src/components/app_bar/app_bar_marketplace.tsx, webapp/channels/src/components/app_bar/app_bar_plugin_component.tsx
Replaces OverlayTrigger and Tooltip, with WithTooltip in app_bar_plugin component
Fixes  [#27787](https://github.com/mattermost/mattermost/issues/27787)
Jira  [https://mattermost.atlassian.net/browse/MM-59894](https://mattermost.atlassian.net/browse/MM-59894)
```release-note
NONE
```
=> [MM-59894] Migrate tooltips of 'components/app_bar/app_bar_plugin_component.tsx' to WithTooltip

webapp/channels/src/components/app_bar/app_bar_binding.tsx
Replaces OverlayTrigger and Tooltip, with WithTooltip in app_bar_binding component
Fixes  [#27789](https://github.com/mattermost/mattermost/issues/27789)
Jira  [https://mattermost.atlassian.net/browse/MM-59892](https://mattermost.atlassian.net/browse/MM-59892)
```release-note
NONE
```
=> [MM-59892] Migrate tooltips of 'components/app_bar/app_bar_binding.tsx' to WithTooltip

webapp/channels/src/components/file_search_results/__snapshots__/file_search_result_item.test.tsx.snap, webapp/channels/src/components/file_search_results/file_search_result_item.tsx
Migrate tooltips to use WithTooltip in 'components/file_search_results/file_search_result_item.tsx' file
Fixes https://github.com/mattermost/mattermost/issues/27780
Jira https://mattermost.atlassian.net/browse/MM-59901
```release-note
NONE
```
=> [MM-59901] Migrate tooltips of 'components/file_search_results/file_search_result_item.tsx' to WithTooltip

webapp/channels/src/components/threading/channel_threads/thread_footer/__snapshots__/thread_footer.test.tsx.snap, webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.test.tsx, webapp/channels/src/components/threading/channel_threads/thread_footer/thread_footer.tsx
Updated 'components/threading/channel_threads/thread_footer/thread_footer.tsx' to use WithToolTip instead of SimpleToolTip
Fixes https://github.com/mattermost/mattermost/issues/27796 
Jira [#59905](https://mattermost.atlassian.net/browse/MM-59905)
|----|----|
| ![59905Before](https://github.com/user-attachments/assets/1ec80289-5b0c-43e7-91c2-6e9465eedd76) | ![59905After](https://github.com/user-attachments/assets/f05bb13b-b5d2-4bf9-8861-f0f800dabd5a) |
```release-note
NONE
```
=> [MM-59905] Migrate tooltips of 'components/threading/channel_threads/thread_footer/thread_footer.tsx' to WithTooltip

webapp/channels/src/components/threading/global_threads/thread_item/__snapshots__/thread_item.test.tsx.snap, webapp/channels/src/components/threading/global_threads/thread_item/thread_item.tsx
Updated 'components/threading/global_threads/thread_item/thread_item.tsx' to use WithTooltip instead of SimpleTooltip
Fixes https://github.com/mattermost/mattermost/issues/27795
Jira [#59906](https://mattermost.atlassian.net/browse/MM-59906)
|----|----|
| ![59906Before](https://github.com/user-attachments/assets/d26e1702-00d1-4202-8285-6a0350565c7d) | ![59906After](https://github.com/user-attachments/assets/9b620641-9746-4af3-af15-7e30b708fc9f) |
```release-note
NONE
```
=> [MM-59906] Migrate tooltips of 'components/threading/global_threads/thread_item/thread_item.tsx' to WithTooltip

webapp/channels/src/components/channel_members_dropdown/__snapshots__/channel_members_dropdown.test.tsx.snap, webapp/channels/src/components/channel_members_dropdown/channel_members_dropdown.tsx
Updated 'components/channel_members_dropdown/channel_members_dropdown.tsx' to use WithTooltip instead of OverlayTrigger and Tooltip
Fixes https://github.com/mattermost/mattermost/issues/27785
Jira https://mattermost.atlassian.net/browse/MM-59896
```release-note
NONE
```
=> [MM-59896] Migrate tooltips of 'components/channel_members_dropdown/channel_members_dropdown.tsx' to WithTooltip

webapp/channels/src/components/create_team/components/team_url/__snapshots__/team_url.test.tsx.snap, webapp/channels/src/components/create_team/components/team_url/team_url.tsx
Migrate tooltips to use WithTooltip in 'components/create_team/components/team_url/team_url.tsx' file
Fixes https://github.com/mattermost/mattermost/issues/27781
Jira https://mattermost.atlassian.net/browse/MM-59900
```release-note
NONE
```
=> [MM-59900] Migrate tooltips of 'components/create_team/components/team_url/team_url.tsx' to WithTooltip

.github/workflows/e2e-fulltests-ci.yml, .github/workflows/e2e-tests-ci-template.yml, e2e-tests/.ci/report.publish.sh, e2e-tests/.ci/server.cloud_init.sh, e2e-tests/.ci/server.cloud_teardown.sh, e2e-tests/.ci/server.prepare.sh, e2e-tests/.ci/server.start.sh, e2e-tests/Makefile, e2e-tests/README.md, e2e-tests/cypress/save_report.js, e2e-tests/cypress/utils/report.js
Cherry pick of #27842 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27842

server/channels/api4/post.go, server/channels/api4/webhook.go
Cherry pick of #27827 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27827

server/channels/app/post_metadata.go, server/public/model/post.go
Manual cherrypick for #27763 for v9.11
Fixes https://mattermost.atlassian.net/browse/MM-59078
```release-note
none
```
=> Websocket cleanup cherrypick for v9.11 

server/channels/app/post_metadata.go, server/public/model/post.go
Manual cherrypick for #27763 for v9.5
Fixes https://mattermost.atlassian.net/browse/MM-59078
```release-note
none
```
=> Websocket cleanup cherrypick for v9.5

server/Makefile
Pre-package the latest MS Teams v2.0.3.
Relates-to: https://mattermost.atlassian.net/browse/MM-59485
```release-note
Pre-package MS Teams v2.0.3
```
=> Pre-package MS Teams v2.0.3

webapp/platform/client/package.json
This [PR](https://github.com/mattermost/mattermost/pull/26354/files#diff-7f39b27c7ea4dce590382a22423e6a796ed28b0810d2eb4e64ee0a2649a0f0d9L24) moved from allowing `*` peer dependency on `@mattermost/types` for `@mattermost/client, This was ok for any mattermost 9.x version upgrade but when we updated to v20 Node; the peer dependency check became a lot stricter. So for now i have allowed any 9.x and 10.x version of types package. 
```release-note
NONE
```
=> Allow v9.x and v10.x for mm/types as peer dependency on mm/client 

webapp/platform/client/package.json
Cherry pick of #27946 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27946

webapp/channels/src/components/user_settings/modal/user_settings_modal.test.tsx, webapp/channels/src/components/user_settings/modal/user_settings_modal.tsx, webapp/channels/src/components/user_settings/plugin/index.test.tsx, webapp/channels/src/components/user_settings/plugin/index.tsx, webapp/channels/src/components/user_settings/plugin/plugin_setting.test.tsx, webapp/channels/src/components/user_settings/plugin/plugin_setting.tsx, webapp/channels/src/components/user_settings/plugin/radio.tsx, webapp/channels/src/plugins/export.js, webapp/channels/src/types/plugins/user_settings.ts, webapp/channels/src/utils/plugins/plugin_setting_extraction.test.tsx, webapp/channels/src/utils/plugins/plugin_setting_extraction.tsx
Cherry pick of #27535 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27535

server/channels/app/file_test.go
Cherry pick of #27923 on release-10.0.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27923

server/config/logger.go, server/platform/services/telemetry/telemetry.go, server/public/model/config.go, server/public/model/config_test.go
Cherry pick of #27386 on release-10.0.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27386

api/v4/source/users.yaml, server/channels/web/params.go, server/channels/web/params_test.go
Cherry pick of #27957 on release-10.0.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27957

webapp/channels/src/components/admin_console/custom_plugin_settings/index.test.tsx, webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts, webapp/channels/src/components/admin_console/schema_admin_settings.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #27831 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27831

e2e-tests/cypress/tests/integration/channels/enterprise/profile_popover/profile_popover_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/system_console/user_management/user_management_admin_control_spec.js, e2e-tests/cypress/tests/integration/channels/messaging/mention_autocomplete_overlap_spec.js
JIRA: https://mattermost.atlassian.net/browse/MM-60183
Dev PR: https://github.com/mattermost/mattermost/pull/27162#pullrequestreview-2211051099
```release-note
NONE
```
=> Fix(e2e): At-mention user autocomplete should open above the textbox in RHS

server/channels/app/plugin.go, server/public/model/license.go
Cherry pick of #27903 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27903

server/Makefile
Cherry pick of #27989 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27989

server/channels/web/handlers.go
- Remove redundant if statement that was already handled by `if csrfCheckNeeded { ...`
- Change language in comment per IDE recommendation
NA
```release-note
NONE
```
=> Remove redundant check and fix language in comment

webapp/channels/src/components/mfa/__snapshots__/confirm.test.tsx.snap, webapp/channels/src/components/mfa/confirm.test.tsx, webapp/channels/src/components/mfa/confirm.tsx, webapp/channels/src/components/mfa/mfa_controller/mfa_controller.tsx
Convert `./components/mfa/confirm.tsx` from Class Component to Function Component
Fixes https://github.com/mattermost/mattermost/issues/27889
Jira https://mattermost.atlassian.net/browse/MM-60067
```release-note
NONE
```
=> [MM-60067] Convert ./components/mfa/confirm.tsx from Class Component to Function Component

webapp/channels/src/components/emoji/__snapshots__/emoji_page.test.tsx.snap, webapp/channels/src/components/emoji/emoji_page.test.tsx, webapp/channels/src/components/emoji/emoji_page.tsx
Convert `./components/emoji/emoji_page.tsx` from Class Component to Function Component 
Fixes https://github.com/mattermost/mattermost/issues/27890
Jira https://mattermost.atlassian.net/browse/MM-60068
```release-note
NONE
```
=> [MM-60068] Convert ./components/emoji/emoji_page.tsx from Class Component to Function Component 

webapp/channels/src/components/select_team/components/__snapshots__/select_team_item.test.tsx.snap, webapp/channels/src/components/select_team/components/select_team_item.test.tsx, webapp/channels/src/components/select_team/components/select_team_item.tsx
The task is to update the component to be a functional component, without any difference in functionality. Also, all related tests that fail may need refactoring.
Fixes https://github.com/mattermost/mattermost/issues/27900
Jira https://mattermost.atlassian.net/browse/MM-60078
```release-note
NONE
```
=> [MM-60078] Convert ./components/select_team/components/select_team_item.tsx from Class Component to Function Component

webapp/channels/src/components/new_channel_modal/new_channel_modal.tsx
Migrate tooltips of `components/new_channel_modal/new_channel_modal.tsx` to WithTooltip
Fixes https://github.com/mattermost/mattermost/issues/27931
Jira https://mattermost.atlassian.net/browse/MM-60165
```release-note
NONE
```
=> [MM-60165] Migrate tooltips of "components/new_channel_modal/new_channel_modal.tsx" to WithTooltip

webapp/channels/src/components/edit_post/edit_post.tsx, webapp/channels/src/components/emoji_picker/emoji_picker_overlay/emoji_picker_overlay.tsx
Cherry pick of #28017 on release-10.0.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #28017

webapp/channels/src/components/admin_console/__snapshots__/bleve_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/push_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap, webapp/channels/src/components/admin_console/admin_settings.tsx, webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap, webapp/channels/src/components/admin_console/custom_terms_of_service_settings/__snapshots__/custom_terms_of_service_settings.test.tsx.snap, webapp/channels/src/components/admin_console/message_export_settings.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_description.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_description.tsx, webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap, webapp/channels/src/components/admin_console/schema_admin_settings.tsx, webapp/channels/src/sass/components/_permissions.scss, webapp/channels/src/utils/position_utils.test.tsx, webapp/channels/src/utils/position_utils.tsx
https://mattermost.atlassian.net/browse/MM-60216
```release-note
NONE
```
=> [MM-60216] Migrate tooltips of admin_consoles "admin_settings", "schema_admin_settings" & "permission_description" to WithTooltip

server/channels/api4/user.go, server/channels/api4/user_test.go, server/channels/web/oauth.go, server/channels/web/saml.go, server/i18n/en.json, server/public/model/client4.go
Cherry pick of #27732 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27732

webapp/channels/src/components/setting_item.tsx
Cherry pick of #28022 on release-10.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #28022

webapp/channels/src/components/channel_header/channel_header_title_favorite.tsx, webapp/channels/src/components/with_tooltip/index.tsx
- Migrate tooltips of `components/channel_header/channel_header_title_favorite.tsx` to WithTooltip
- Add `onEntering` as a prop to `Withtooltip` component
Fixes https://github.com/mattermost/mattermost/issues/27930
Jira https://mattermost.atlassian.net/browse/MM-60166
```release-note
NONE
```
=> [MM-60166] Migrate tooltips of "components/channel_header/channel_header_title_favorite.tsx" to WithTooltip

webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/__snapshots__/custom_theme_chooser.test.tsx.snap, webapp/channels/src/components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx
Migrate tooltips of `components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx` to WithTooltip
Fixes https://github.com/mattermost/mattermost/issues/27926
Jira https://mattermost.atlassian.net/browse/MM-60170
| ![image](https://github.com/user-attachments/assets/a5c7eddf-683e-40d9-a46e-3d6497888063) | ![image](https://github.com/user-attachments/assets/57819bda-62b4-4b1d-af8e-ca1583f3f57e) |
```release-note
NONE
```
=> [MM-60170] Migrate tooltips of "components/user_settings/display/user_settings_theme/custom_theme_chooser/custom_theme_chooser.tsx" to WithTooltip

server/Makefile
Cherry pick of #27994 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #27994

server/Makefile
Cherry pick of #28041 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #28041

server/Makefile
Upgrade the prepackaged playbooks versions
N/A
```release-note
NONE
```
=> Bump prepackaged playbooks versions

webapp/channels/src/components/analytics/doughnut_chart.test.tsx, webapp/channels/src/components/analytics/doughnut_chart.tsx
Migrate `webapp/channels/src/components/analytics/doughnut_chart.test.tsx` from class to function component
fixes #27891
Jira https://mattermost.atlassian.net/browse/MM-60069
```release-note
NONE
```
=> Migrate `webapp/channels/src/components/analytics/doughnut_chart.test.tsx` from class to function component

webapp/channels/src/components/admin_console/__snapshots__/bleve_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/cluster_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/custom_enable_disable_guest_accounts_setting.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/database_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/elasticsearch_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/message_export_settings.test.tsx.snap, webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap, webapp/channels/src/components/admin_console/boolean_setting.tsx, webapp/channels/src/components/admin_console/custom_plugin_settings/__snapshots__/custom_plugin_settings.test.tsx.snap, webapp/channels/src/components/admin_console/plugin_management/__snapshots__/plugin_management.test.tsx.snap
Converts the `./components/admin_console/boolean_setting.tsx` from a class component to a functional component 
Updates test snapshots in settings tests where boolean_setting is used
To view component: Click the Menu Button(left-most icon/button on the global-header); usually before the mattermost logo, select system console >> environment >> session lengths   ...... The first two settings with true-false values
NB: Requires admin status to view
Fixes  [#27899](https://github.com/mattermost/mattermost/issues/27899)
Jira  [https://mattermost.atlassian.net/browse/MM-60077](https://mattermost.atlassian.net/browse/MM-60077)
```release-note
NONE
```
=> [MM-60077] Convert ./components/admin_console/boolean_setting.tsx from Class Component to Function Component

server/channels/api4/metrics_test.go, server/channels/web/handlers.go
Cherry pick of #28049 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #28049

webapp/channels/src/components/advanced_text_editor/use_submit.tsx
Fix how we decide whether the root post is deleted to show the modal telling us the root post is deleted.
Fix https://mattermost.atlassian.net/browse/MM-60270
Catched before releasing
```release-note
NONE
```
=> Fix replying on deleted posts

webapp/channels/src/components/advanced_text_editor/use_submit.tsx
Cherry pick of #28061 on release-10.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #28061

webapp/channels/src/sass/base/_structure.scss
Cherry pick of #28025 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #28025

server/channels/api4/user.go, server/channels/api4/user_test.go, server/channels/web/oauth.go, server/channels/web/saml.go, server/i18n/en.json, server/public/model/client4.go
Cherry pick of https://github.com/mattermost/mattermost/pull/27732/files
```release-note
NONE
```
=> [MM-58549] release-9.5 cherry pick 

webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Cherry pick of #28062 on release-10.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #28062

webapp/channels/src/components/threading/thread_viewer/thread_viewer.scss
Cherry pick of #28087 on release-10.0.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #28087

webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Cherry pick of #28091 on release-10.0.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #28091

server/channels/api4/channel_bookmark_test.go
Fixes the channel bookmarks flaky tests around the websocket events by replacing `require.Eventuallyf` with the way it is done in the posts tests.
https://mattermost.atlassian.net/browse/MM-57312
https://mattermost.atlassian.net/browse/MM-57392
https://mattermost.atlassian.net/browse/MM-58095
```release-note
NONE
```
=> Fix Channel Bookmarks flaky tests

server/Makefile
Cherry pick of #28105 on release-10.0.
/cc  @wiggin77
```release-note
NONE
```
=> Automated cherry pick of #28105

server/channels/store/sqlstore/compliance_store.go
I converted this to squirrel in the CLI tool because there were too many args to keep track of in the args slice. Copied over to here so we keep parity
https://mattermost.atlassian.net/browse/MM-60250
```release-note
NONE
```
=> [MM-60250]Convert MessageExport query to squirrel

webapp/channels/src/sass/base/_structure.scss
cherry pick of https://github.com/mattermost/mattermost/pull/28065
```release-note
NONE
```
=> cherry pick of #28065

server/channels/api4/post_test.go
https://mattermost.atlassian.net/browse/MM-60329
```release-note
NONE
```
=> Skip racy test TestPostReminder

webapp/channels/src/actions/command.ts
Fixes https://github.com/mattermost/mattermost/issues/27873
Jira https://mattermost.atlassian.net/browse/MM-41507
```release-note
NONE
```
=> Code command whitespace fix

server/channels/api4/channel_bookmark_test.go
https://mattermost.atlassian.net/browse/MM-60481
```release-note
NONE
```
=> MM-60481 Skip test TestCreateChannelBookmark

webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_description.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_group.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/__snapshots__/permission_row.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_description.test.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_description.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_group.test.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_group.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_row.test.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_row.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #27614 on release-9.11.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #27614

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/snyk-sbom.yml
Cherry pick of #27733 on release-9.5.
/cc  @enzowritescode
```release-note
NONE
```
=> Automated cherry pick of #27733

.github/workflows/snyk-sbom.yml
Cherry pick of #28161 on release-10.0.
/cc  @enzowritescode
```release-note
NONE
```
=> Automated cherry pick of #28161

server/channels/api4/remote_cluster.go, server/channels/api4/remote_cluster_test.go, server/public/model/client4.go, webapp/platform/client/src/client4.ts
Cherry pick of #27887 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #27887

server/channels/api4/config.go, server/channels/api4/config_local.go, server/channels/app/app_iface.go, server/channels/app/config.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/plugin.go, server/channels/app/plugin_api_test.go, server/channels/app/plugin_api_tests/manual.test_load_configuration_plugin/main.go, server/config/diff.go, server/config/diff_test.go, server/public/model/config.go, server/public/model/config_test.go, server/public/model/manifest.go
Cherry pick of #27986 on release-10.1.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #27986

server/platform/services/sharedchannel/service.go, server/platform/services/sharedchannel/sync_send_remote.go, server/platform/services/telemetry/telemetry.go, server/public/model/config.go
https://mattermost.atlassian.net/browse/MM-56026
```release-note
* Adds the ConnectedWorkspaces.MaxPostsPerSync configuration property
```
=> Adds a ConnectedWorkspaces.MaxPostsPerSync configuration property

webapp/channels/src/components/drafts/drafts.scss
Fixed a bug where drafts won't allow scrolling if you have many drafts.
Fixes https://mattermost.atlassian.net/browse/MM-60539 
```release-note
Fixed a bug where drafts won't allow scrolling if you have many drafts.
```
=> FIxed scrolling issue on drafts

server/channels/app/email/email.go
Updates download app link to the proper config value, with fall back to permalink.
https://mattermost.atlassian.net/browse/CLD-8141
```release-note
None
```
=> [CLD-8141] Update download app link in Cloud welcome email

server/channels/api4/remote_cluster.go, server/channels/api4/remote_cluster_test.go, server/channels/api4/shared_channel.go, server/channels/app/app_iface.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/platform/shared_channel_notifier.go, server/channels/app/remote_cluster.go, server/channels/app/session.go, server/channels/app/slashcommands/command_share.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/remote_cluster_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/RemoteClusterStore.go, server/channels/store/storetest/remote_cluster_store.go, server/channels/store/timerlayer/timerlayer.go, server/platform/services/remotecluster/recv.go, server/platform/services/sharedchannel/service_api.go, server/platform/services/sharedchannel/sync_send.go
Cherry pick of #28182 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28182

webapp/channels/src/actions/views/rhs.test.ts, webapp/channels/src/actions/views/rhs.ts
- Fixes Recent Mentions showing posts for other similar named users.
- Recent Mention now sends first-name and username(even without `@`) within quotes.
JIRA - https://mattermost.atlassian.net/browse/MM-54357
Previous related PR - https://github.com/mattermost/mattermost/pull/25010
```release-note
NONE
```
=> [MM-54357] Fixes Recent Mentions showing posts for other similar named users

webapp/channels/src/actions/views/rhs.test.ts, webapp/channels/src/actions/views/rhs.ts
Cherry pick of #28119 on release-9.5.
/cc  @vish9812
```release-note
NONE
```
=> Automated cherry pick of #28119

server/Makefile
Cherry pick of #28134 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28134

api/v4/source/sharedchannels.yaml, server/channels/api4/shared_channel.go, server/channels/api4/shared_channel_test.go, server/channels/web/params.go, server/public/model/client4.go
Cherry pick of #28213 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28213

server/Makefile
Pre-packaging Calls v1.1.0, to be included in MM v10.1
https://mattermost.atlassian.net/browse/MM-60209
```release-note
Pre-packaged Calls v1.1.0
```
=> [MM-60209] Prepackage Calls v1.1.0

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/public/model/channel.go, server/public/model/channel_test.go
Cherry pick of #28086 on release-10.0.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #28086

server/Makefile
Cherry pick of #28220 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28220

server/channels/store/searchlayer/file_info_layer.go, server/channels/store/searchtest/file_info_layer.go
Cherry pick of #28221 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28221

server/channels/app/platform/session.go, server/channels/app/platform/web_conn.go, server/channels/app/platform/web_conn_test.go
Cherry pick of #28195 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #28195

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of #28251 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28251

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of https://github.com/mattermost/mattermost/pull/28251 on release-9.5.
```release-note
NONE
```
=> Manual cherry pick of #28251

server/channels/api4/shared_channel.go, server/platform/services/sharedchannel/service_api.go
Cherry pick of #28255 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28255

server/go.mod, server/go.sum
Bump yuin/goldmark to v1.7.4 in `release-9.11`
https://mattermost.atlassian.net/browse/MM-58746
--
```release-note
NONE
```
=> Cherry pick #28250 to release-9.11

server/go.mod, server/go.sum
Bump yuin/goldmark to v1.7.4 in `release-9.5`
https://mattermost.atlassian.net/browse/MM-58746
--
```release-note
NONE
```
=> Cherry pick #28250 to release-9.5

server/public/model/config.go, server/public/model/config_test.go
Cherry pick of #28260 on release-10.1.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #28260

server/platform/services/telemetry/telemetry.go, server/platform/services/telemetry/telemetry_test.go
Include known community supported plugins that are no longer available in the market place as part of the telemetry
[MM-59954](https://mattermost.atlassian.net/browse/MM-59954)
```release-note
NONE
```
[MM-59954]: https://mattermost.atlassian.net/browse/MM-59954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MM-59954 Community plugins telemetry

webapp/channels/src/actions/global_actions.tsx, webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/index.tsx, webapp/channels/src/components/date_time_picker_modal/date_time_picker_modal.tsx, webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx, webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx, webapp/channels/src/components/drafts/list_item/list_item.tsx, webapp/channels/src/packages/mattermost-redux/src/action_types/scheudled_posts.ts, webapp/channels/src/packages/mattermost-redux/src/actions/scheduled_posts.ts, webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
Integrated `updatedScheduledPost()` API in reschedule post modal. Also displayed error if any occurred.
Fixes https://mattermost.atlassian.net/browse/MM-60131
```release-note
none
```
=> MM-60131 - Reschedule post integration

webapp/channels/src/actions/status_actions.test.ts, webapp/channels/src/actions/status_actions.ts, webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/components/channel_layout/channel_controller.test.tsx, webapp/channels/src/components/channel_layout/channel_controller.tsx, webapp/channels/src/components/team_controller/actions/index.ts
- Renamed `addVisibleUsersInCurrentChannelToStatusPoll` to `addVisibleUsersInCurrentChannelAndSelfToStatusPoll`
- Added `currentUserId` to function `addVisibleUsersInCurrentChannelAndSelfToStatusPoll`
Jira https://mattermost.atlassian.net/browse/MM-60303
```release-note
NONE
```
=> [MM-60303] Changing status in mobile app doesn't change your status in the webapp

webapp/channels/src/components/root/root.test.tsx, webapp/channels/src/components/root/root.tsx
Cherry pick of #28247 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28247

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of #28270 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28270

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of https://github.com/mattermost/mattermost/pull/28270 on release-9.5.
```release-note
NONE
```
=> Manual cherry pick of #28270 on release-9.5

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of https://github.com/mattermost/mattermost/pull/28270 on release-9.10.
```release-note
NONE
```
=> Manual cherry pick of #28270 on release-9.10

.github/workflows/migration.yml, .github/workflows/server-ci-template.yml
Cherry pick of https://github.com/mattermost/mattermost/pull/28270 on release-9.11.
```release-note
NONE
```
=> Manual cherry pick of #28270 on release-9.11

server/channels/app/platform/session.go
Cherry pick of #28254 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #28254

server/channels/api4/user.go, server/channels/api4/user_test.go, server/channels/app/user.go, server/channels/app/user_test.go, webapp/channels/src/actions/views/threads.ts
Cherry pick of #28263 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28263

server/platform/shared/mfa/mfa.go, server/platform/shared/mfa/mfa_test.go
Cherry pick of #28304 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28304

server/cmd/mmctl/commands/user.go, server/cmd/mmctl/docs/mmctl_user_migrate-auth.rst
Make documentation consistent
https://mattermost.atlassian.net/browse/MM-60353
```release-note
NONE
```
=> [MM-60328] cmd/mmctl/user: attempt to improve migrate-auth documentation

webapp/channels/src/components/drafts/draft_row.tsx
Excluded draft checks from scheduled posts
```release-note
none
```
=> Excluded draft checks from scheduled posts

server/.golangci.yml, server/channels/api4/brand_test.go
Fixes https://github.com/mattermost/mattermost/issues/28351
Jira https://mattermost.atlassian.net/browse/MM-60708
```release-note
NONE
```
=> Errcheck issues fixed in server/channels/api4/brand_test.go

server/.golangci.yml, server/channels/api4/channel_category.go
This PR solves issue https://github.com/mattermost/mattermost/issues/28355. This is done by capturing the error and handling it appropriately.  
Fixes https://github.com/mattermost/mattermost/issues/28355
```release-note
Fixed errcheck issues in server/channels/api4/chanel_category.go
```
=> [GH-28355] Fixed errcheck issues in server/channels/api4/channel_category.go

server/.golangci.yml, server/channels/api4/file.go
Fixes https://github.com/mattermost/mattermost/issues/28386
Jira https://mattermost.atlassian.net/browse/MM-60753
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/file.go

server/.golangci.yml, server/channels/api4/image_test.go
Fixes https://github.com/mattermost/mattermost/issues/28392
Jira https://mattermost.atlassian.net/browse/MM-60759
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/image_test.go

server/Makefile
Cherry pick of #28413 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28413

webapp/channels/src/components/sidebar/sidebar_channel/sidebar_direct_channel/sidebar_direct_channel.tsx
Cherry pick of #28302 on release-10.1.
/cc  @fmartingr
```release-note
NONE
```
=> Automated cherry pick of #28302

server/.golangci.yml, server/channels/api4/oauth.go
Fixes https://github.com/mattermost/mattermost/issues/28451
Jira https://mattermost.atlassian.net/browse/MM-60795
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/oauth.go

server/.golangci.yml, server/channels/api4/post.go
Fixes https://github.com/mattermost/mattermost/issues/28458
Jira https://mattermost.atlassian.net/browse/MM-60802
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/post.go

server/.golangci.yml, server/channels/api4/integration_action.go
Fixes https://github.com/mattermost/mattermost/issues/28394
Jira https://mattermost.atlassian.net/browse/MM-60761
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/integration_action.go

webapp/channels/src/components/channel_select/index.ts
Fixes https://github.com/mattermost/mattermost/issues/28311
```release-note
NONE
```
=> Update index.ts (Filter archived channel from dropdown)

server/.golangci.yml, server/channels/api4/ldap.go
Fixes https://github.com/mattermost/mattermost/issues/28400
Jira https://mattermost.atlassian.net/browse/MM-60767
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/ldap.go

server/.golangci.yml, server/channels/api4/permission.go
Fixes https://github.com/mattermost/mattermost/issues/28455
Jira https://mattermost.atlassian.net/browse/MM-60799
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/permission.go

server/.golangci.yml, server/channels/api4/group.go
Fixes https://github.com/mattermost/mattermost/issues/28388
Jira https://mattermost.atlassian.net/browse/MM-60755
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/group.go

server/.golangci.yml, server/channels/api4/reaction_test.go
=> fix: reaction test errcheck issues

server/.golangci.yml, server/channels/api4/license_test.go
Fixes https://github.com/mattermost/mattermost/issues/28450
Jira https://mattermost.atlassian.net/browse/MM-60794
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/license_test.go

server/.golangci.yml, server/channels/api4/shared_channel.go
fixes #28526
```release-note
NONE
```
=> fix: shared channel errcheck issues

server/.golangci.yml, server/channels/api4/system_local.go
fixes #28533 
```release-note
NONE
```
=> fix: system local errcheck issues

server/.golangci.yml, server/channels/api4/system.go
fixes #28532
```release-note
NONE
```
=> fix: system errcheck issues

server/channels/api4/bot_test.go
Fixes https://github.com/mattermost/mattermost/issues/28331
Jira https://mattermost.atlassian.net/browse/MM-60691
```release-note
NONE
```
=> Errcheck issues fixed

server/.golangci.yml, server/channels/api4/team_local.go
fixes #28536 
```release-note
NONE
```
=> fix: team local errcheck issues

server/.golangci.yml, server/channels/api4/ip_filtering.go
This PR solves issue https://github.com/mattermost/mattermost/issues/28396. This is done by capturing the error and handling it appropriately.
Fixes https://github.com/mattermost/mattermost/issues/28396
```release-note
NONE
```
=> [GH-28396] Fixed errcheck issues in server/channels/api4/ip_filtering.go

server/.golangci.yml, server/channels/api4/preference_test.go
Fixes https://github.com/mattermost/mattermost/issues/28460
Jira https://mattermost.atlassian.net/browse/MM-60804
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/preference_test.go

server/.golangci.yml, server/channels/api4/outgoing_oauth_connection_test.go
Fixes https://github.com/mattermost/mattermost/issues/28454
Jira https://mattermost.atlassian.net/browse/MM-60798
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/outgoing_oauth_connection_test.go

server/channels/app/channel.go, server/channels/app/syncables.go, server/channels/app/team.go, server/channels/app/user.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/channel_store.go, server/channels/store/sqlstore/team_store.go, server/channels/store/store.go, server/channels/store/storetest/channel_store.go, server/channels/store/storetest/group_store.go, server/channels/store/storetest/mocks/ChannelStore.go, server/channels/store/storetest/mocks/TeamStore.go, server/channels/store/timerlayer/timerlayer.go
Cherry pick of #28300 on release-9.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #28300

webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
Fixed a bug causing error message to show up on deleting a scheduled post in a deleted thread
Fixes https://mattermost.atlassian.net/browse/MM-60784
```release-note
none
```
=> MM-60784 - Fix delete scheduled post on deleted thread

server/.golangci.yml, server/channels/api4/webhook.go
Fixes https://github.com/mattermost/mattermost/issues/28569
Jira https://mattermost.atlassian.net/browse/MM-60937
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/webhook.go

server/.golangci.yml, server/channels/api4/shared_channel_test.go
fixes #28527  
```release-note
NONE
```
=> fix: shared channel test errcheck issues

server/.golangci.yml, server/channels/api4/usage.go
Fixes https://github.com/mattermost/mattermost/issues/28564
Jira https://mattermost.atlassian.net/browse/MM-60932
```release-note
NONE
```
=> [MM-60932] Fix errcheck issues in server/channels/api4/usage.go

e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_1_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.ts, e2e-tests/cypress/tests/support/api/user.d.ts
- convert js files to ts
- add types
- update helper functions with optional arguments
Fixes: #21312
```release-note
NONE
```
=> MM-47296 refactor: convert accessibility specs to ts

.github/workflows/e2e-tests-ci-template.yml, e2e-tests/.ci/report.collect.sh, e2e-tests/.ci/server.prepare.sh, e2e-tests/.ci/server.run_cypress.sh, e2e-tests/.ci/server.start.sh, e2e-tests/Makefile, e2e-tests/README.md
Manual cherrypick of https://github.com/mattermost/mattermost/pull/28240 to `release-10.1`
https://mattermost.atlassian.net/browse/CLD-7761
```release-note
NONE
```
=> Enhance reporting, add shellcheck (#28240)

.github/workflows/e2e-tests-ci-template.yml, e2e-tests/.ci/report.collect.sh, e2e-tests/.ci/server.prepare.sh, e2e-tests/.ci/server.run_cypress.sh, e2e-tests/.ci/server.start.sh, e2e-tests/Makefile, e2e-tests/README.md
Cherry pick of #28240 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #28240

server/.golangci.yml, server/channels/api4/brand.go, server/i18n/en.json
Fixes https://github.com/mattermost/mattermost/issues/28350
Jira https://mattermost.atlassian.net/browse/MM-60707
```release-note
NONE
```
=> Errcheck issues fixed in server/channels/api4/brand.go

webapp/channels/src/components/admin_console/session_length_settings.tsx, webapp/channels/src/i18n/en.json
Replaces FormattedMarkdownMessage with FormattedMessage in session_length_settings.tsx
Updates en.json
Fixes  [#28590](https://github.com/mattermost/mattermost/issues/28590)
Jira  [https://mattermost.atlassian.net/browse/MM-60844](https://mattermost.atlassian.net/browse/MM-60844)
```release-note
NONE
```
=> [MM-60844] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/session_length_settings.tsx' with FormattedMessage

webapp/channels/src/components/admin_console/billing/company_info_display.tsx
This PR replaces all instances of FormattedMarkdownMessage with FormattedMessage from the react-intl library in company_info_display.tsx, ensuring rich text formatting is preserved.
Fixes https://github.com/mattermost/mattermost/issues/28596
Jira https://mattermost.atlassian.net/browse/MM-60838
```release-note
NONE
```
=> [MM-60838] Replace FormattedMarkdownMessage in 'webapp/channels/src/components/admin_console/billing/company_info_display.tsx' with FormattedMessage

.github/workflows/e2e-fulltests-ci.yml, .github/workflows/e2e-tests-ci-template.yml, .gitignore, e2e-tests/.ci/.e2erc, e2e-tests/.ci/dashboard.generate_test_cycle.sh, e2e-tests/.ci/report.collect.sh, e2e-tests/.ci/report.publish.sh, e2e-tests/.ci/server.generate.sh, e2e-tests/.ci/server.run_cypress.sh, e2e-tests/.ci/server.run_playwright.sh, e2e-tests/README.md, e2e-tests/playwright/.eslintrc.json, e2e-tests/playwright/package-lock.json, e2e-tests/playwright/package.json, e2e-tests/playwright/playwright.config.ts, e2e-tests/playwright/report.webhookgen.js
Cherry pick of #28492 on release-10.1.
```release-note
NONE
```
=> Automated cherry pick of #28492

server/channels/app/notification.go, server/channels/app/platform/service.go, server/channels/app/platform/utils.go, server/channels/store/localcachelayer/layer.go, server/channels/store/sqlstore/shared_channel_store.go, server/channels/store/sqlstore/utils.go, server/public/pluginapi/cluster/mock_plugin_api_test.go
They are in-built in Go now
```release-note
NONE
```
=> Removed the max/min family of functions

server/channels/app/import_functions_test.go, server/cmd/mmctl/commands/sampledata_util.go, server/public/model/builtin.go, server/public/model/config.go
And we remove the deprecated functions to force uses
only of the new function.
```release-note
NONE
```
=> Remove remaining references to model.NewXX

webapp/platform/components/src/generic_modal/generic_modal.scss
Fixed width of generic modal header to fix browser channel modal
Fixes https://mattermost.atlassian.net/browse/MM-60786
```release-note
None
```
=> MM-60786 - Fixed width of generic modal header to fix browser channel modal

server/channels/store/sqlstore/reaction_store.go, server/channels/store/sqlstore/user_store.go, server/channels/store/storetest/reaction_store.go
- Improve some code to remove ToSQL
- Fix a bug in SqlReactionStore.GetForPostSince
where OrderBy wasn't added properly. Added a test.
- Improve a method to return a slice rather than
pass a pointer to slice.
```release-note
NONE
```
=> store: use Builder

webapp/channels/src/components/drafts/drafts.scss
Fixed draft and scheduled post UI in mobile view
Fixes https://mattermost.atlassian.net/browse/MM-60941
```release-note
none
```
=> Fixed draft and scheduled post UI in mobile view

server/.golangci.yml, server/channels/api4/upload_test.go
Fixes https://github.com/mattermost/mattermost/issues/28563
Jira https://mattermost.atlassian.net/browse/MM-60931
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/upload_test.go

server/.golangci.yml, server/channels/api4/system_test.go
Added error checks 
Ticket: https://github.com/mattermost/mattermost/issues/28534
Jira: https://mattermost.atlassian.net/browse/MM-60926
```release-note
NONE
```
=> MM-60926: updated system_test.go to pass linter

server/.golangci.yml, server/channels/api4/user_local.go
Fixes https://github.com/mattermost/mattermost/issues/28567
Jira https://mattermost.atlassian.net/browse/MM-60935
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/user_local.go

server/Makefile
Prepackage Calls v1.2.0
https://mattermost.atlassian.net/browse/MM-60553
```release-note
Prepackage Calls v1.2.0
```
=> [MM-60553] Prepackage Calls v1.2.0

server/Makefile
Cherry pick of #28717 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28717

server/channels/store/sqlstore/post_store.go, server/channels/store/storetest/post_store.go
Cherry pick of #28688 on release-10.2.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #28688

server/.golangci.yml, server/channels/app/admin_test.go
Fix `errcheck` issues in `server/channels/app/admin_test.go`
This is an example PR for the `errcheck` campaign.
Fixes https://github.com/mattermost/mattermost/issues/28766
https://mattermost.atlassian.net/browse/MM-61093
```release-note
NONE
```
=> Fix errcheck issues in channels/app/admin_test.go

server/public/model/utils.go, server/public/model/utils_test.go
Cherry pick of #28481 on release-10.2.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #28481

server/channels/api4/scheduled_post.go, webapp/channels/src/actions/views/create_comment.tsx
Fixed a bug where API used incoming create at date for scheduled post
Fixes https://mattermost.atlassian.net/browse/MM-60961
```release-note
none
```
=> MM-60961 - Fixed a bug where API used incoming create at date for scheduled post

server/channels/app/channel_bookmark_test.go, server/public/model/channel_bookmark.go, server/public/model/channel_bookmark_test.go, webapp/channels/src/components/channel_bookmarks/channel_bookmarks_create_modal.tsx, webapp/channels/src/components/channel_bookmarks/create_modal_name_input.tsx
Cherry pick of #28424 on release-10.2.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #28424

e2e-tests/cypress/tests/integration/channels/system_console/connected_workspaces_management_spec.ts, webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx, webapp/channels/src/components/admin_console/secure_connections/secure_connection_row.tsx, webapp/channels/src/components/admin_console/secure_connections/team_selector.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #28379 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28379

server/channels/app/remote_cluster.go, server/i18n/en.json, server/public/model/remote_cluster.go, server/public/model/remote_cluster_test.go
Cherry pick of #28624 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28624

api/v4/source/remoteclusters.yaml, server/channels/api4/remote_cluster.go, server/channels/api4/remote_cluster_test.go
Cherry pick of #28709 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28709

api/v4/source/remoteclusters.yaml, e2e-tests/cypress/tests/integration/channels/system_console/connected_workspaces_management_spec.ts, server/channels/api4/remote_cluster.go, server/channels/api4/remote_cluster_test.go, server/channels/app/slashcommands/command_remote.go, server/platform/services/remotecluster/invitation.go, server/platform/services/remotecluster/service.go, server/public/model/remote_cluster.go, webapp/channels/src/components/admin_console/secure_connections/controls.tsx, webapp/channels/src/components/admin_console/secure_connections/modals/modal_utils.tsx, webapp/channels/src/components/admin_console/secure_connections/modals/secure_connection_accept_invite_modal.tsx, webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx, webapp/channels/src/components/admin_console/secure_connections/team_selector.tsx, webapp/channels/src/components/admin_console/secure_connections/utils.ts, webapp/channels/src/i18n/en.json, webapp/platform/types/src/remote_clusters.ts
Cherry pick of #28841 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28841

server/channels/api4/shared_channel_test.go, server/channels/app/channel.go, server/channels/app/channel_test.go, server/channels/app/post.go, server/channels/app/post_test.go, server/i18n/en.json, server/platform/services/sharedchannel/service_api.go
Cherry pick of #28855 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28855

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/use_emoji_picker.tsx, webapp/channels/src/components/advanced_text_editor/use_upload_files.tsx, webapp/channels/src/i18n/en.json
Cherry pick https://github.com/mattermost/mattermost/pull/28861
```release-note
NONE
```
=> Disables text editor for DMs and GMs with remote users (#28861)

e2e-tests/playwright/tests/functional/system_console/desktop_landing.spec.ts
Test case: https://github.com/mattermost/mattermost-test-management/pull/189
```release-note
NONE
```
=> Feat: Make desktop app landing page optional

webapp/channels/src/components/update_user_group_modal/update_user_group_modal.tsx
This PR is to clean up the diff for https://github.com/mattermost/mattermost/pull/28494
This fixes some dependencies on the update user group modal, and uses callbacks instead of arrow functions in the inner components.
NONE
```release-note
NONE
```
=> Fix dependencies and callbacks on update user group modal

e2e-tests/cypress/tests/integration/channels/system_console/connected_workspaces_management_spec.ts, webapp/channels/src/components/admin_console/admin_definition.tsx, webapp/channels/src/components/admin_console/secure_connections/secure_connection_detail.tsx, webapp/channels/src/components/admin_console/secure_connections/utils.ts
Cherry pick of #28887 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28887

server/channels/api4/user_test.go, server/channels/app/app_iface.go, server/channels/app/authentication.go, server/channels/app/authentication_test.go, server/channels/app/channels.go, server/channels/app/ldap.go, server/channels/app/oauth.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/store/localcachelayer/user_layer.go
Cherry pick of #28634 on release-10.2.
/cc  @vish9812
```release-note
NONE
```
=> Automated cherry pick of #28634

webapp/channels/src/components/mfa/__snapshots__/confirm.test.tsx.snap, webapp/channels/src/components/mfa/confirm.tsx, webapp/channels/src/i18n/en.json
I noticed this when testing something
```release-note
NONE
```
=> Remove Markdown from FormattedMessage

server/.golangci.yml, server/channels/jobs/batch_migration_worker.go
Fixes https://github.com/mattermost/mattermost/issues/28757
```release-note
NONE
```
=> Fix errcheck issues in server/channels/jobs/batch_migration_worker.go

server/cmd/mmctl/commands/channel.go, server/cmd/mmctl/commands/command.go, server/cmd/mmctl/commands/permissions.go, server/cmd/mmctl/commands/permissions_role.go, server/cmd/mmctl/docs/mmctl_permissions_role_show.rst
https://mattermost.atlassian.net/browse/MM-61132
```release-note
Fix example for mmctl permissions role show command
```
=> [MM-61132] Fix example for mmctl permissions role show command

server/channels/app/channel.go
Cherry pick of #27846 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #27846

webapp/channels/src/actions/views/create_comment.test.jsx, webapp/channels/src/actions/views/create_comment.tsx
Cherry pick of #28914 on release-10.0.
```release-note
NONE
```
=> Automated cherry pick of #28914

server/platform/services/slackimport/slackimport.go, server/platform/services/slackimport/slackimport_test.go
Cherry pick of #28904 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28904

.github/dependabot.yml
Enable dependabot in order to keep our pipelines up to date 
```release-note
NONE
```
=> feat: enable Github Actions dependabot

server/.golangci.yml, server/channels/app/group_test.go
Fixes https://github.com/mattermost/mattermost/issues/28928
Jira https://mattermost.atlassian.net/browse/MM-61252
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/group_test.go

server/platform/services/remotecluster/error.go, server/platform/services/remotecluster/recv.go
Cherry pick of #28943 on release-10.2.
```release-note
NONE
```
=> Automated cherry pick of #28943

server/channels/app/channel.go, server/channels/app/post.go, server/platform/services/sharedchannel/service_api.go, server/public/model/feature_flags.go, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/i18n/en.json
Cherry pick #28920
```release-note
NONE
```
=> Adds a feature flag to control availability of DMs in shared channels (#28920)

webapp/channels/src/components/pricing_modal/content.tsx, webapp/package-lock.json
Removes a duplication of contact sales that didn't translate well after the self serve deprecation.
https://mattermost.atlassian.net/browse/CLD-8480
Before:
After:
```release-note
None
```
=> [CLD-8480] Remove duplicate 'Contact Sales' link in pricing modal card

server/Makefile
Prepackage Calls v1.2.1 in `release-10.2`
```release-note
Prepackage Calls v1.2.1
```
=> Prepackage Calls v1.2.1 in `release-10.2`

server/Makefile
Prepackage Calls v1.2.1 in `release-10.1`
```release-note
Prepackage Calls v1.2.1
```
=> Prepackage Calls v1.2.1 in `release-10.1`

server/Makefile
Prepackage Calls v1.2.1 in `release-10.0`
```release-note
Prepackage Calls v1.2.1
```
=> Prepackage Calls v1.2.1 in `release-10.0`

server/Makefile
Prepackage Calls v0.29.3 in `release-9.11`
```release-note
Prepackage Calls v0.29.3
```
=> Prepackage Calls v0.29.3 in `release-9.11`

server/i18n/en.json
```release-note
Updated product string for clarity.
```
=> String update for clarity

webapp/channels/src/components/more_direct_channels/index.test.tsx, webapp/channels/src/components/more_direct_channels/index.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.test.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts
Cherry pick of #28953 on release-10.2.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #28953

server/.golangci.yml, server/channels/web/web.go
Fixes https://github.com/mattermost/mattermost/issues/28750
JIRA: [MM-61078](https://mattermost.atlassian.net/browse/MM-61078)
```release-note
```
[MM-61078]: https://mattermost.atlassian.net/browse/MM-61078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix errcheck issues in server/channels/web/web.go

server/channels/api4/bot_test.go, server/channels/api4/config_test.go, server/channels/app/bot_test.go, server/channels/app/import_functions_test.go, server/channels/app/import_test.go, server/channels/app/post_test.go, server/channels/utils/merge_test.go, server/channels/utils/subpath_test.go, server/platform/services/awsmeter/awsmeter_test.go, server/public/model/bot_test.go
https://mattermost.atlassian.net/browse/MM-61302
```release-note
NONE
```
=> [MM-61302] Use model.NewPointer throughout the code base

server/.golangci.yml, server/channels/app/email/helper_test.go
Fixes `errcheck` issues
Fixes: https://github.com/mattermost/mattermost/issues/28814
```release-note
```
=> Fixes errcheck in helper_test.go

server/channels/app/server.go, webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx
To make things easier, we’ll temporarily disable the special dev mode behavior for scheduled posts until we have a clear decision on how to decide if special dev mode is enabled.
```release-note
None
```
=> Removed dev mode behaviour temperorily

webapp/channels/src/sass/components/_suggestion-list.scss
The custom status tooltip was not positioned correctly because the span tag was taking full width. I have fixed it, now the tooltip is positioned correctly.
Fixes https://github.com/mattermost/mattermost/issues/27183
Jira https://mattermost.atlassian.net/browse/MM-58435
|----|----|
| ![custom tooltip before](https://github.com/user-attachments/assets/3ca46a23-6cdb-4520-88e1-76b7608588bd)  |  ![custom tooltip after](https://github.com/user-attachments/assets/1db1cae0-ae68-46e9-aed3-88e678950edc)  |
```release-note
NONE
```
=> Custom status tooltip position fixed in channel switcher items

server/.golangci.yml, server/channels/app/oauth_test.go
Fixes https://github.com/mattermost/mattermost/issues/29034
Jira https://mattermost.atlassian.net/browse/MM-61446
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/oauth_test.go

server/.golangci.yml, server/channels/app/ldap.go
Fixes https://github.com/mattermost/mattermost/issues/29028
Jira https://mattermost.atlassian.net/browse/MM-61264
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/ldap.go

server/.golangci.yml, server/channels/jobs/schedulers_test.go
Fixes https://github.com/mattermost/mattermost/issues/28764
JIRA: [MM-61091](https://mattermost.atlassian.net/browse/MM-61091)
```release-note
```
[MM-61091]: https://mattermost.atlassian.net/browse/MM-61091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix errcheck issues in server/channels/jobs/schedulers_test.go

server/.golangci.yml, server/channels/app/import_utils_test.go
Fixes errcheck issue in import_utils_test.go
Removes `channels/app/import_utils_test.go` from .golangci.yml
Fixes  [#28950](https://github.com/mattermost/mattermost/issues/28950)
Jira  [https://mattermost.atlassian.net/browse/MM-61259](https://mattermost.atlassian.net/browse/MM-61259)
```release-note
NONE
```
=> [MM-61259] Fix errcheck issues in server/channels/app/import_utils_test.go

webapp/channels/src/components/admin_console/admin_settings/__snapshots__/admin_setting.test.tsx.snap, webapp/channels/src/components/admin_console/admin_settings/admin_setting.test.tsx, webapp/channels/src/components/admin_console/admin_settings/admin_settings.tsx, webapp/channels/src/components/admin_console/admin_settings/hooks.tsx, webapp/channels/src/components/admin_console/admin_settings/types.d.ts, webapp/channels/src/components/admin_console/admin_settings/types.ts, webapp/channels/src/components/admin_console/admin_settings/utils.test.ts, webapp/channels/src/components/admin_console/admin_settings/utils.ts, webapp/channels/src/components/admin_console/bleve_settings.tsx, webapp/channels/src/components/admin_console/cluster_settings.tsx, webapp/channels/src/components/admin_console/custom_terms_of_service_settings/custom_terms_of_service_settings.tsx, webapp/channels/src/components/admin_console/database_settings.tsx, webapp/channels/src/components/admin_console/elasticsearch_settings.tsx, webapp/channels/src/components/admin_console/message_export_settings.test.tsx, webapp/channels/src/components/admin_console/message_export_settings.tsx, webapp/channels/src/components/admin_console/old_admin_settings.tsx, webapp/channels/src/components/admin_console/openid_convert/openid_convert.tsx, webapp/channels/src/components/admin_console/password_settings.tsx, webapp/channels/src/components/admin_console/plugin_management/plugin_management.tsx, webapp/channels/src/components/admin_console/push_settings.tsx, webapp/channels/src/components/admin_console/session_length_settings.tsx
First part of https://github.com/mattermost/mattermost/pull/28884 .
This PR deals with preparing the new component to use when migrating all the different settings.
The component is right now not used anywhere. Will start to be used in the following PRs.
NONE
```release-note
NONE
```
=> Refactor admin settings to functional components

server/.golangci.yml, server/channels/app/opengraph_test.go
Fixes https://github.com/mattermost/mattermost/issues/29047
Jira https://mattermost.atlassian.net/browse/MM-61448
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/opengraph_test.go

server/channels/api4/scheduled_post.go, server/channels/app/app_iface.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/scheduled_post.go, server/channels/app/scheduled_post_test.go, server/public/model/websocket_message.go, webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/utils/constants.tsx
MM-60145 - ws events on update scheduled posts
https://mattermost.atlassian.net/browse/MM-60145
https://github.com/user-attachments/assets/440cdedd-4335-423d-8e74-df93350c63df
```release-note
NONE
```
=> MM-60145 - ws events on update scheduled posts

server/channels/app/scheduled_post_test.go
https://mattermost.atlassian.net/browse/MM-61523
```release-note
NONE
```
=> [MM-61523] Skip flaky TestGetUserTeamScheduledPosts/should_get_created_scheduled_posts

server/channels/api4/user_test.go, server/channels/app/app_iface.go, server/channels/app/authentication.go, server/channels/app/authentication_test.go, server/channels/app/channels.go, server/channels/app/ldap.go, server/channels/app/oauth.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/store/localcachelayer/user_layer.go
Cherry pick of #28634 on release-10.1.
```release-note
NONE
```
=> Manual cherry pick of #28634

webapp/channels/src/components/admin_console/__snapshots__/schema_admin_settings.test.tsx.snap, webapp/channels/src/i18n/i18n.jsx
Based on this thread https://community.mattermost.com/core/pl/jaxn7wbrpin4pdpyuscdejoy7w
```release-note
Downgraded Traditional Chinese to Beta.
```
=> Update Traditional Chinese to Beta

server/.golangci.yml, server/channels/app/notification_push.go
Fixes https://github.com/mattermost/mattermost/issues/29032
Jira https://mattermost.atlassian.net/browse/MM-61444
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/notification_push.go

server/.golangci.yml, server/channels/app/app_test.go
Fixes errcheck issue in `server/channels/app/app_test.go`
Fixes  [#28773](https://github.com/mattermost/mattermost/issues/28773)
Jira  [https://mattermost.atlassian.net/browse/MM-61094](https://mattermost.atlassian.net/browse/MM-61094)
```release-note
NONE
```
=> [MM-61094] Fix errcheck issues in server/channels/app/app_test.go

server/channels/api4/scheduled_post.go, server/channels/app/app_iface.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/scheduled_post.go, server/channels/app/scheduled_post_test.go, server/public/model/websocket_message.go, webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/teams.ts, webapp/channels/src/utils/constants.tsx
Emit and consume websocket event for create scheduled post message.
https://mattermost.atlassian.net/browse/MM-60124
https://github.com/user-attachments/assets/2b9333d3-bb55-4ed2-87cf-b4532f4c6e6e
```release-note
NONE
```
=> MM-60124-emit and read create scheduled post WS event

webapp/channels/src/actions/global_actions.tsx, webapp/channels/src/components/announcement_bar/notification_permission_bar/__snapshots__/index.test.tsx.snap, webapp/channels/src/components/announcement_bar/notification_permission_bar/index.test.tsx, webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_never_granted_bar.tsx, webapp/channels/src/components/announcement_bar/notification_permission_bar/notification_permission_unsupported_bar.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/stores/browser_store.tsx, webapp/channels/src/utils/constants.tsx
PR https://github.com/mattermost/mattermost/pull/28890 towards master
```release-note
NONE
```
=> [MM-60964] Update permissions banner button text and dismiss behaviour

server/.golangci.yml, server/channels/app/plugin_hooks_test.go
Fixes https://github.com/mattermost/mattermost/issues/29053
Jira https://mattermost.atlassian.net/browse/MM-61455
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/plugin_hooks_test.go

server/.golangci.yml, server/channels/app/teams/helper_test.go
Fixes errcheck issue in `server/channels/app/teams/helper_test.go`
Fixes  [#29110](https://github.com/mattermost/mattermost/issues/29110)
Jira  [https://mattermost.atlassian.net/browse/MM-61506](https://mattermost.atlassian.net/browse/MM-61506)
```release-note
NONE
```
=> [MM-61506] Fix errcheck issues in server/channels/app/teams/helper_test.go

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/channels/app/app_iface.go, server/channels/app/channel.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/channel_store.go, server/channels/store/store.go, server/channels/store/storetest/channel_store.go, server/channels/store/storetest/mocks/ChannelStore.go, server/channels/store/timerlayer/timerlayer.go
Add parameter in GetDeletedChannels to include private channels if required and enable it for users with PermissionManageSystem
I'm trying to add tests but I need a bit of time to understand how it works
Fixes https://github.com/mattermost/mattermost/issues/19913
Jira https://mattermost.atlassian.net/browse/MM-39918
```release-note
NONE
```
=> MM-39918: mmctl: list archived private channels in channel list command with system admin user

webapp/channels/src/components/advanced_text_editor/post_box_indicator/post_box_indicator.tsx, webapp/channels/src/components/advanced_text_editor/send_button/scheduled_post_custom_time_modal/scheduled_post_custom_time_modal.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.test.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/index.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.test.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/recent_used_custom_date.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/style.scss, webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/timezone.ts, webapp/channels/src/utils/constants.tsx
This PR adds the teammate time at which it will receive the message depending on teammate timezone.
https://mattermost.atlassian.net/browse/MM-60874
```release-note
NONE
```
=> MM-60874 - show usertz in scheduled message options

server/.golangci.yml, server/channels/app/slashcommands/command_leave_test.go
Fixes https://github.com/mattermost/mattermost/issues/29093
Jira https://mattermost.atlassian.net/browse/MM-61495
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/slashcommands/command_leave_test.go

server/.golangci.yml, server/channels/api4/post_test.go
Fixes https://github.com/mattermost/mattermost/issues/28459
Jira https://mattermost.atlassian.net/browse/MM-60803
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/api4/post_test.go

server/Makefile
Prepackage Calls v1.3.0
https://mattermost.atlassian.net/browse/MM-61133
```release-note
Prepackage Calls v1.3.0
```
=> [MM-61133] Prepackage Calls v1.3.0

server/Makefile
Cherry pick of #29232 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29232

server/.golangci.yml, server/channels/app/post_metadata_test.go
fixes #29080 
Jira [MM-61465](https://mattermost.atlassian.net/browse/MM-61465)
```release-note
NONE
```
[MM-61465]: https://mattermost.atlassian.net/browse/MM-61465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-61465] Fix errcheck issues in server/channels/app/post_metadata_test.go

server/.golangci.yml, server/channels/app/plugin_api_test.go
Fixes errcheck issues in `server/channels/app/plugin_api_test.go`
Fixes  [#29182](https://github.com/mattermost/mattermost/issues/29182)
Jira  [https://mattermost.atlassian.net/browse/MM-61516](https://mattermost.atlassian.net/browse/MM-61516)
```release-note
NONE
```
=> [MM-61516] Fix errcheck issues in server/channels/app/plugin_api_test.go

webapp/channels/src/components/drafts/panel/__snapshots__/panel_body.test.tsx.snap, webapp/channels/src/components/drafts/panel/panel_body.test.tsx, webapp/channels/src/components/drafts/panel/panel_body.tsx
Cherry pick of #29226 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29226

webapp/channels/src/components/custom_status/date_time_input.tsx, webapp/channels/src/utils/datetime.ts
Cherry pick of #29215 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29215

webapp/channels/src/components/drafts/draft_title/__snapshots__/draft_title.test.tsx.snap, webapp/channels/src/components/drafts/draft_title/draft_title.test.tsx, webapp/channels/src/components/drafts/draft_title/draft_title.tsx, webapp/channels/src/components/drafts/draft_title/index.ts, webapp/channels/src/packages/mattermost-redux/src/actions/users.ts, webapp/channels/src/utils/test_intl.tsx
Cherry pick of #29211 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29211

server/channels/api4/outgoing_oauth_connection_test.go, server/channels/app/user.go, server/channels/app/user_test.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/scheduled_post_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/ScheduledPostStore.go, server/channels/store/storetest/scheduled_post_store.go, server/channels/store/timerlayer/timerlayer.go, server/i18n/en.json
Cherry pick of #29152 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29152

server/.golangci.yml, server/channels/app/product_notices_test.go
Fixes https://github.com/mattermost/mattermost/issues/29085
Jira https://mattermost.atlassian.net/browse/MM-61487
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/product_notices_test.go

server/.golangci.yml, server/channels/app/session_test.go
Fixes https://github.com/mattermost/mattermost/issues/29090
Jira https://mattermost.atlassian.net/browse/MM-61492
```release-note
NONE
```
=> Fixed errcheck issues in server/channels/app/session_test.go

webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/components/root/root.test.tsx, webapp/channels/src/components/root/root.tsx
Cherry pick of #29257 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29257

server/channels/api4/post_test.go
https://hub.mattermost.com/private-core/pl/niosp5k63bf89yiz8yfbkywmdy
https://mattermost.atlassian.net/browse/MM-61780
```release-note
NONE
```
=> [MM-61780] Skip flaky TestWebHubCloseConnOnDBFail

.github/workflows/e2e-tests-ci-template.yml, e2e-tests/cypress/tests/integration/channels/bot_accounts/display_name_spec.ts, e2e-tests/cypress/tests/integration/channels/bot_accounts/managing_bot_accounts_not_cloud_spec.ts, e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_3_spec.ts, e2e-tests/cypress/tests/integration/channels/custom_status/custom_status_expiry/custom_status_expiry_4_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_modals_dialogs_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/ldap/ldap_login_spec.ts, e2e-tests/cypress/tests/integration/channels/integrations/custom_slash_commands/custom_slash_commands_spec.js, e2e-tests/cypress/tests/integration/channels/integrations/incoming_webhook/attachment_does_not_collapse_spec.ts, e2e-tests/cypress/tests/integration/channels/messaging/pinned_posts_2_spec.js, e2e-tests/cypress/tests/integration/channels/notifications/ignore_channel_mentions_spec.js, e2e-tests/cypress/tests/integration/channels/system_console/unsaved_changes_spec.js, e2e-tests/cypress/tests/integration/playbooks/channels/rhs/start_run_rhs_spec.js, e2e-tests/cypress/tests/integration/playbooks/channels/slash_command/test_spec.js
Further demotion of unstable test cases, after daily tests failures
https://mattermost.atlassian.net/browse/CLD-8301
```release-note
NONE
```
=> Demote unstable tests

webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx, webapp/channels/src/components/drafts/drafts.tsx, webapp/channels/src/components/tabs/tab/index.tsx, webapp/channels/src/components/tabs/tabs/index.tsx
Cherry pick of #29247 on release-10.3.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29247

server/.golangci.yml, server/channels/app/platform/feature_flags.go
handle app error in `PlatformService.updateFeatureFlagValuesFromManagement`.
Fixes #29265 
```release-note
NONE
```
=> GH-29265: Fix errcheck errors in server/channels/app/platform/feature_flags.go

webapp/channels/src/components/advanced_text_editor/send_button/send_button.scss, webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx, webapp/channels/src/utils/utils.tsx
Added hover color on send post button
Fixes https://mattermost.atlassian.net/browse/MM-61546
https://github.com/user-attachments/assets/37559b5a-8998-41c2-b737-46b7956f03e6
https://github.com/user-attachments/assets/43244ddc-b6dc-4938-86e2-fb8ed35042e5
```release-note
None
```
=> Added hover color on split send post button

server/channels/app/scheduled_post_job_test.go
Fixes https://mattermost.atlassian.net/browse/MM-61790
```release-note
None
```
=> Fix flaky TestHandleFailedScheduledPosts test

webapp/channels/src/components/drafts/drafts.scss, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts
Cherry pick of #29274 on release-10.3.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29274

webapp/channels/src/components/advanced_text_editor/send_button/send_button.scss, webapp/channels/src/components/advanced_text_editor/send_button/send_button.tsx, webapp/channels/src/utils/utils.tsx
Cherry pick of #29243 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29243

webapp/channels/src/components/drafts/drafts_link/drafts_link.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #29218 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29218

server/.golangci.yml, server/channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go
Fixed `errcheck` issues in `channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go`
Fixes https://github.com/mattermost/mattermost/issues/29258
Jira https://mattermost.atlassian.net/browse/MM-61518
```release-note
```
=> [MM-61518] Fixed errcheck issues in channels/app/plugin_api_tests/manual.test_serve_metrics_plugin/main.go

server/.golangci.yml, server/channels/app/platform/busy_test.go
This PR fixes the errcheck issues reported by golangci-lint in the server/channels/app/platform/busy_test.go file.
Fixes https://github.com/mattermost/mattermost/issues/29262
Jira https://mattermost.atlassian.net/browse/MM-61760
```release-note
```
=> Fix errcheck issues in server/channels/app/platform/busy_test.go

webapp/channels/src/components/custom_status/date_time_input.tsx, webapp/channels/src/utils/timezone.ts
Cherry pick of #29287 on release-10.3.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29287

server/channels/api4/post.go, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/scheduled_posts.ts, webapp/platform/types/src/schedule_post.ts
Cherry pick of #29322 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29322

.github/workflows/server-ci-template.yml, .github/workflows/server-test-template.yml
When we retry the pipeline permissions for Github Token are not inherited . We need to specify those . 
Hopefully this will work 
Related PR: https://github.com/mattermost/mattermost/pull/29323 
```release-note
NONE
```
=> fix: Fix publish permissions for retries

webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.test.tsx, webapp/channels/src/components/advanced_text_editor/send_button/send_post_options/core_menu_options.tsx, webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.tsx
Hid user's timezone in options if DM user is a bot
Fixes https://mattermost.atlassian.net/browse/MM-61859
```release-note
none
```
=> Scheduled post option bot time exclusion

server/channels/app/notification_test.go
https://mattermost.atlassian.net/browse/MM-61858
```release-note
NONE
```
=> [MM-61858] Fix flaky TestSendNotifications

server/.golangci.yml, server/channels/app/import_functions_test.go
Fixed errcheck issues in server/channels/app/import_functions_test.go
Fixes #28949
=> Fixed errcheck issues in server/channels/app/import_functions_test.go

webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.test.tsx, webapp/channels/src/components/drafts/draft_actions/schedule_post_actions/scheduled_post_actions.tsx, webapp/channels/src/components/drafts/drafts.tsx, webapp/channels/src/components/drafts/drafts_illustration.tsx, webapp/channels/src/components/drafts/placeholder_scheduled_post_title/placeholder_scheduled_posts_title.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #29319 on release-10.3.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29319

server/channels/api4/team.go, server/channels/api4/team_test.go, webapp/channels/src/components/team_settings_modal/index.ts, webapp/channels/src/components/team_settings_modal/team_settings_modal.test.tsx, webapp/channels/src/components/team_settings_modal/team_settings_modal.tsx
Cherry pick of #28670 on release-10.3.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #28670

server/.golangci.yml, server/channels/app/platform/metrics.go
Fix Errcheck in channels/app/platform/metrics.go
Fixes https://github.com/mattermost/mattermost/issues/29337
Jira https://mattermost.atlassian.net/browse/MM-61768
```release-note
NONE
```
=> [MM-61768] Fix #29337 Errcheck in channels/app/platform/metrics.go

server/.golangci.yml, server/channels/app/platform/session_test.go
Fixes errcheck issues in `server/channels/app/platform/session_test.go`
Fixes  [#29359](https://github.com/mattermost/mattermost/issues/29359)
Jira  [https://mattermost.atlassian.net/browse/MM-61773](https://mattermost.atlassian.net/browse/MM-61773)
```release-note
NONE
```
=> [MM-61773] Fix errcheck issues in server/channels/app/platform/session_test.go

webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.test.tsx, webapp/channels/src/components/advanced_text_editor/use_post_box_indicator.tsx
Cherry pick of #29395 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29395

e2e-tests/cypress/tests/integration/channels/status/status_updates_spec.ts, webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/actions/websocket_actions.test.jsx
Cherry pick of #29371 on release-10.3.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #29371

e2e-tests/playwright/support/ui/components/global_header.ts, e2e-tests/playwright/tests/functional/channels/search/search_box_suggestions.spec.ts, webapp/channels/src/components/new_search/search_box.tsx
Cherry pick of #29400 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29400

webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx, webapp/channels/src/components/post_view/combined_system_message/last_users.tsx, webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx, webapp/channels/src/components/post_view/message_attachments/action_menu/index.ts, webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx, webapp/channels/src/packages/mattermost-redux/src/actions/posts.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts, webapp/channels/src/packages/mattermost-redux/src/utils/post_utils.ts, webapp/channels/src/selectors/views/custom_status.test.ts, webapp/channels/src/selectors/views/marketplace.ts
Cherry pick of #29248 on release-10.3.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #29248

webapp/channels/src/components/post_view/combined_system_message/combined_system_message.tsx, webapp/channels/src/components/post_view/combined_system_message/last_users.tsx, webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx, webapp/channels/src/components/post_view/message_attachments/action_menu/index.ts, webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/users.ts, webapp/channels/src/packages/mattermost-redux/src/utils/post_utils.ts, webapp/channels/src/selectors/views/custom_status.test.ts, webapp/channels/src/selectors/views/marketplace.ts
Manual cherrypick of #29248
```release-note
NONE
```
=> Manual cherrypick of #29248

server/Makefile
Prepackaging the latest Calls dot release in the v0.29 series.
```release-note
Prepackage Calls v0.29.5
```
=> Prepackage Calls v0.29.5

webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/updates.test.ts, webapp/channels/src/components/admin_console/workspace-optimization/dashboard_checks/updates.ts
Cherry pick of #29436 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #29436

server/Makefile
Reverts mattermost/mattermost#29462
=> Revert "Prepackage calls v1.3.1 in 10.3"

webapp/channels/src/components/custom_status/custom_status_modal.tsx
Changes custom status 'clear after Today', from clearing next day 8am to clearing at midnight
Fixes  [#29041](https://github.com/mattermost/mattermost/issues/29041)
Jira  [https://mattermost.atlassian.net/browse/MM-61845](https://mattermost.atlassian.net/browse/MM-61845)
```release-note
NONE
```
=> [GH-29041] Make custom status 'clear after Today', clear at midnight

server/public/model/post.go, server/public/model/post_test.go
https://mattermost.atlassian.net/browse/MM-62085
```release-note
NONE
```
=> MM-62085: Handle nil post priority

server/channels/api4/outgoing_oauth_connection_test.go
Cherry pick of #29178 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29178

webapp/channels/src/components/new_search/new_search.tsx
The search input wasn't as accessible at it should be. This PR fixes that.
[MM-61234](https://mattermost.atlassian.net/browse/MM-61234)
```release-note
Fixing accessibility problem in the new search input
```
[MM-61234]: https://mattermost.atlassian.net/browse/MM-61234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixing accessiblity on search input

server/channels/app/platform/cluster_handlers.go, server/channels/app/platform/status.go, server/channels/store/localcachelayer/layer.go, server/channels/store/localcachelayer/layer_test.go
Cherry pick of #29488 on release-10.3.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #29488

webapp/channels/src/components/new_search/new_search.tsx
Cherry pick of #29423 on release-10.3.
/cc  @jespino
```release-note
NONE
```
=> Automated cherry pick of #29423

.gitignore, server/channels/store/sqlstore/webhook_store.go
I was planning to kick off a campaign for this. But aider can do this just fine.
Starting off with a single file for now. But will slowly send more PRs with larger
commit diffs.
```release-note
NONE
```
=> [Aider assisted]: Use SelectBuilder and GetBuilder in webhook_store.go

.github/workflows/server-test-template.yml
Added issue permissions to avoid 403 errors on community PRs 
Related: https://github.com/mattermost/mattermost/pull/29566 
```release-note
NONE
```
=> feat: Added also issues permissions

server/Makefile
Prepackage Calls v1.4.0
https://mattermost.atlassian.net/browse/MM-61793
```release-note
Prepackage Calls v1.4.0
```
=> [MM-61793] Prepackage Calls v1.4.0

server/Makefile
Cherry pick of #29568 on release-10.4.
```release-note
NONE
```
=> Automated cherry pick of #29568

server/channels/store/sqlstore/channel_store.go
Cherry pick of #29572 on release-10.4.
```release-note
NONE
```
=> Automated cherry pick of #29572

.github/workflows/mmctl-test-template.yml, .github/workflows/server-ci-report.yml, .github/workflows/server-test-template.yml
Completely decouple reporting from CI since it needs elevated permissions.  
Use webhook events to trigger the reporting pipeline automatically with the required permissions .  
https://mattermost.atlassian.net/browse/CLD-8698
```release-note
NONE
```
=> feat: Decouple reporting from actual testing

api/v4/source/definitions.yaml, api/v4/source/reports.yaml
This is an example output of the API:
```json
[
{
"id": "a35iwstytb8m8xu3yejkm1fama",
"create_at": 1726737170269,
"update_at": 1726737215826,
"delete_at": 0,
"username": "dev.four",
"auth_data": "",
"auth_service": "ldap",
"email": "success+devfour@simulator.amazonses.com",
"nickname": "Dev4",
"first_name": "Dev4",
"last_name": "User",
"position": "Staff Software Design Engineer",
"roles": "system_user",
"locale": "en",
"timezone": {
"automaticTimezone": "Europe/Berlin",
"manualTimezone": "",
"useAutomaticTimezone": "true"
},
"disable_welcome_email": false,
"last_login": 1726737170291,
"last_status_at": 1726737825387,
"last_post_date": 1726737235922,
"days_active": 1,
"total_posts": 3
},
]
```
The permission notices are also not correct. The user doesn't need to be an admin.
None …
=> Fix user reports API docs

webapp/channels/src/components/post_reminder_custom_time_picker_modal/post_reminder_custom_time_picker_modal.tsx, webapp/platform/components/src/generic_modal/__snapshots__/generic_modal.test.tsx.snap
Fixed a bug where post reminder modal didn't close
Fixes https://mattermost.atlassian.net/browse/MM-62258
```release-note
none
```
=> Fixed a bug where post reminder modal didn't close

server/channels/api4/post.go, server/channels/api4/post_test.go
Cherry pick of #29557 on release-10.4.
```release-note
NONE
```
=> Automated cherry pick of #29557

e2e-tests/cypress/tests/integration/channels/status/status_updates_spec.ts, webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/actions/websocket_actions.test.jsx
Backporting https://github.com/mattermost/mattermost/pull/29371 to 9.11
https://mattermost.atlassian.net/browse/MM-59952
```release-note
Fixed web app status not being updated correctly for the current user
```
=> MM-59952/MM-61438 Fix web app not responding to WS events for status (#29371) (9.11)

.github/workflows/snyk-sbom.yml
- Change `sbom.json` to `sbom-mattermost-vX.Y.Z.json`
https://mattermost.atlassian.net/browse/SEC-7235
```release-note
NONE
```
=> Bump SBOM version

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/use_emoji_picker.tsx
Updated emoji picker alignment in edit post box.
Fixes https://mattermost.atlassian.net/browse/MM-62301
```release-note
none
```
=> Updated emojipicker alignment in edit box

.github/workflows/snyk-sbom.yml
Cherry pick of #29632 on release-10.1.
/cc  @enzowritescode
```release-note
NONE
```
=> Automated cherry pick of #29632

server/public/model/config.go, server/public/model/config_test.go
While we were filtering the struct tags, we were expecting a `struct` not a `map[string]any`. Since `sturct` has the tags, we should always convert `map[string]any` to `model.Config` to be able to read the tags if the passed value is a map.
https://mattermost.atlassian.net/browse/MM-62357
```release-note
NONE
```
=> [/MM-62357] model/config: filtering should work with maps too

e2e-tests/cypress/tests/integration/channels/system_console/user_management/users_reactivation_spec.js
Stabilize `users_reactivation_spec.js`: make it retry-ready
https://mattermost.atlassian.net/browse/CLD-8719
```release-note
NONE
```
=> Stabilize users_reactivation_spec.js E2E testcase

webapp/channels/src/actions/websocket_actions.jsx
Cherry pick of #29623 on release-10.4.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29623

webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
Cherry pick of #29604 on release-10.4.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29604

server/.golangci.yml, server/channels/app/platform/web_hub.go
**Summary**
Fix errcheck issues in server/channels/app/platform/web_hub.go
Ticket Link
https://github.com/mattermost/mattermost/issues/29441
=> [MM-29441] Fix errcheck issues in web_hub.go

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.scss, webapp/channels/src/components/channel_view/__snapshots__/channel_view.test.tsx.snap, webapp/channels/src/components/channel_view/channel_view.tsx
Fixed minor spacing issues in advanced text editor for create and edit post.
Fixes https://mattermost.atlassian.net/browse/MM-62361
Fixes https://mattermost.atlassian.net/browse/MM-62359
```release-note
none
```
=> Advanced text editor misc fixes

server/public/go.mod, server/public/shared/httpservice/client.go, server/public/shared/httpservice/client_test.go
Cherry pick of #29600 on release-10.4.
```release-note
NONE
```
=> Automated cherry pick of #29600

server/channels/app/platform/cluster_handlers.go, server/channels/app/platform/service.go, server/channels/app/platform/service_test.go
Cherry pick of #29686 on release-10.4.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #29686

server/public/go.mod, server/public/shared/httpservice/client.go, server/public/shared/httpservice/client_test.go
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/29600 into `release-9.11`
```release-note
NONE
```
=> [MM-61938] Cherry-pick into `release-9.11`

webapp/channels/src/components/profile_popover/profile_popover.scss, webapp/channels/src/components/profile_popover/profile_popover_controller.tsx, webapp/channels/src/components/profile_popover/profile_popover_full_name.tsx, webapp/channels/src/utils/constants.tsx
Jira https://mattermost.atlassian.net/browse/MM-61800
-->
```release-note
NONE
```
=> [MM-61800] Email is cut off in profile popover

e2e-tests/cypress/tests/integration/channels/channel/channel_header_modal_spec.js, e2e-tests/cypress/tests/integration/channels/enterprise/accessibility/accessibility_input_fields_spec.ts, e2e-tests/cypress/tests/integration/channels/enterprise/system_console/channel_moderation/create_posts_spec.ts, e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/system_message_not_open_for_edit_spec.js, webapp/channels/src/components/__snapshots__/autosize_textarea.test.tsx.snap, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx, webapp/channels/src/components/autosize_textarea.tsx, webapp/channels/src/components/edit_channel_header_modal/__snapshots__/edit_channel_header_modal.test.tsx.snap, webapp/channels/src/components/edit_channel_header_modal/edit_channel_header_modal.tsx, webapp/channels/src/sass/components/_modal.scss, webapp/channels/src/sass/components/_post.scss, webapp/channels/src/utils/performance_telemetry/element_identification.test.tsx
Associate visual label with form field in form - Edit the text appearing next to the channel name in the header.
https://mattermost.atlassian.net/browse/MM-61571
NONE
```release-note
```
=> [MM-61571]: Add label to form field in channel header

server/public/model/client4.go
My IDE was complaining, so I fixed it.
None
```release-note
NONE
```
=> Don't use fmt.Sprintf for constant strings

webapp/channels/src/components/file_attachment_list/file_attachment_list.tsx, webapp/channels/src/components/file_upload_overlay/file_upload_overlay.scss, webapp/channels/src/components/post_view/post_edited_indicator/post_edited_indicator.tsx, webapp/channels/src/components/single_image_view/single_image_view.test.tsx, webapp/channels/src/components/single_image_view/single_image_view.tsx, webapp/channels/src/sass/responsive/_mobile.scss
Bugs fixed-
1. Removed single image actions in restore post confirmation dialog
1. Fixed file drop overlay size and position
1. Made edit indicator accessible
Fixes https://mattermost.atlassian.net/browse/MM-62497
```release-note
none
```
=> Edit attachment misc fixes

server/channels/api4/channel_bookmark_test.go, server/channels/app/imports/import_validators_test.go, server/channels/app/platform/log_test.go
These are a few test cases that I've seen reported as flaky lately in PRs that I've been reviewing
```release-note
NONE
```
=> Skip flaky tests

webapp/channels/src/components/emoji_picker/emoji_picker.tsx
Cherry pick of #29608 on release-10.5.
/cc  @X1Vi
```release-note
NONE
```
=> Automated cherry pick of #29608

webapp/channels/src/components/drafts/drafts.scss
Fix for draft and scheduled post section not scrolling.
Fixes https://mattermost.atlassian.net/browse/MM-62363
```release-note
none
```
=> Fix for draft and scheduled post section not scrolling

server/public/model/manifest.go, server/public/model/manifest_test.go, webapp/channels/src/components/admin_console/custom_plugin_settings/index.test.tsx, webapp/channels/src/components/admin_console/custom_plugin_settings/index.ts, webapp/platform/types/src/plugins.ts
Cherry pick of #29500 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29500

server/Makefile
Prepackage Calls v1.5.0 to ship with v10.5
https://mattermost.atlassian.net/browse/MM-62267
```release-note
Prepackage Calls v1.5.0
```
=> [MM-62267] Prepackage Calls v1.5.0

server/Makefile
Cherry pick of #29828 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29828

server/channels/store/sqlstore/channel_store.go
Avoid SELECT * in channel_store.go
Fixes https://github.com/mattermost/mattermost/issues/29679
Jira [MM-62111](https://mattermost.atlassian.net/browse/MM-62147)
```release-note
NONE
```
[MM-62111]: https://mattermost.atlassian.net/browse/MM-62111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MM-62147] Avoid SELECT * in channel_store.go

webapp/channels/src/sass/layout/_webhooks.scss
Cherry pick of #29809 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29809

webapp/channels/src/actions/views/drafts.test.ts, webapp/channels/src/actions/views/drafts.ts, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
Fixed a bug where post draft isn't deleted on restoring post and incorrect content shows up when editing such post.
Fixes https://mattermost.atlassian.net/browse/MM-62535
```release-note
none
```
=> Edit post restore fix

webapp/channels/src/actions/views/drafts.test.ts, webapp/channels/src/actions/views/drafts.ts, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/post_edit_history/edited_post_item/edited_post_item.tsx
Cherry pick of #29851 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29851

api/Makefile, api/v4/source/custom_profile_attributes.yaml, api/v4/source/definitions.yaml, api/v4/source/introduction.yaml, api/v4/source/users.yaml, server/channels/api4/api.go, server/channels/api4/custom_profile_attributes.go, server/channels/api4/custom_profile_attributes_local.go, server/channels/api4/custom_profile_attributes_test.go, server/channels/app/app_iface.go, server/channels/app/custom_profile_attributes.go, server/channels/app/custom_profile_attributes_test.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/store/sqlstore/property_field_store.go, server/channels/web/context.go, server/channels/web/params.go, server/i18n/en.json, server/public/model/client4.go, server/public/model/custom_profile_attributes.go, server/public/model/feature_flags.go, server/public/model/property_field.go
Cherry pick for https://github.com/mattermost/mattermost/pull/29662
```release-note
* Adds the Custom Profile Attribute fields store, app and API endpoints.
```
=> Custom profile attributes field endpoints (#29662)

api/v4/source/users.yaml
Cherry pick of #29852 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29852

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/use_submit.tsx, webapp/channels/src/packages/mattermost-redux/src/action_types/files.ts, webapp/channels/src/packages/mattermost-redux/src/reducers/entities/files.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/files.ts
Cherry pick of #29871 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29871

webapp/channels/build/emoji/make_emojis.mjs, webapp/channels/src/sass/components/_emojisprite.scss, webapp/channels/src/sass/components/_emoticons.scss
Cherry pick of #29276 on release-9.11.
/cc  @lorumic
```release-note
NONE
```
=> Automated cherry pick of #29276

server/Makefile
Cherry pick of #29638 on release-10.3.
/cc  @wiggin77
```release-note
NONE
```
=> Automated cherry pick of #29638

webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/packages/mattermost-redux/src/actions/scheduled_posts.ts, webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
Cherry pick of #29875 on release-10.5.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #29875

webapp/channels/src/sass/components/_forms.scss
Cherry pick of #29830 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29830

webapp/channels/src/utils/__snapshots__/message_html_to_component.test.tsx.snap, webapp/channels/src/utils/message_html_to_component.test.tsx, webapp/channels/src/utils/message_html_to_component.tsx
Cherry pick of #29858 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29858

server/Makefile
Cherry pick of https://github.com/mattermost/mattermost/pull/29638 on release-9.11.
```release-note
NONE
```
https://mattermost.atlassian.net/browse/MM-57465
```release-note
NONE
```
=> Manual cherry pick of #29638

webapp/channels/src/sass/components/_files.scss, webapp/channels/src/sass/components/_post.scss
Fixed minor misalignments with image component.
Fixes https://mattermost.atlassian.net/browse/MM-62534
```release-note
none
```
=> Fixed minor misalignments with image component

webapp/channels/src/sass/components/_files.scss, webapp/channels/src/sass/components/_post.scss
Cherry pick of #29861 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29861

webapp/channels/src/components/onboarding_tasklist/onboarding_tasklist.tsx
- Updated the onboarding task-list styles conditionally for open and closed state.
- Navigate to the "Side Navigation" section.
- Navigate to the onboarding button and press up/down arrow key.
- Notice that the screen reader announces hidden content/keyboard focus reaches non visible functional elements.
- The hidden content should not be exposed to the screen reader.
Jira https://mattermost.atlassian.net/browse/MM-61679
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
=> [MM-61679]: Handled intended hidden on-boarding task-list from assistive technology

webapp/channels/src/actions/websocket_actions.jsx
=> Mm 62229 schmsg not removed on reconnect (#29623)

server/build/release.mk
Remove windows packaged builds from releases . 
Related: https://hub.mattermost.com/private-core/pl/markd3w18ffhzeasmcx4wggupe
```release-note
Removed windows builds from releases
```
=> feat: Remove windows builds from releases

server/build/release.mk
Cherry pick of #29932 on release-10.5.
/cc  @toninis
```release-note
NONE
```
=> Automated cherry pick of #29932

webapp/channels/src/components/channel_notifications_modal/channel_notifications_modal.tsx
- Added role='alert' to the error message element
- Locate the "Unable to update the channel member." in the notification preference button inside the view info button in the channel header.
- Inspect its element with Chrome DevTools.
- Review the value for "Description".
- The screen reader should announce the selected to keyboard interacted suggested item correctly.
Jira https://mattermost.atlassian.net/browse/MM-61645
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
=> [MM-61645]: Added role='alert' to the error message element

webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/packages/mattermost-redux/src/actions/scheduled_posts.ts, webapp/channels/src/packages/mattermost-redux/src/reducers/entities/scheduled_posts.ts
=> Manual cherry pick of 29875 to release 10.3

server/Makefile
Cherry pick of #29950 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29950

server/Makefile
Updated board prepackaged version to v9.0.5
```release-note
Updated Boards prepackaged version to v9.0.5
```
=> Updated board prepackaged version to v9.0.5

server/channels/jobs/export_delete/worker.go, server/channels/jobs/export_delete_test.go, server/channels/jobs/helper_test.go
Cherry pick of #29897 on release-10.5.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #29897

webapp/channels/src/actions/websocket_actions.jsx, webapp/channels/src/actions/websocket_actions.test.jsx
Cherrypick of #29010 to `release-9.11`
```release-note
NONE
```
=> Cherrypick of #29010 to `release-9.11`

webapp/channels/src/components/profile_popover/profile_popover.scss, webapp/channels/src/components/profile_popover/profile_popover.tsx, webapp/channels/src/components/profile_popover/profile_popover_controller.tsx
Cherry pick of #29860 on release-10.5.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #29860

server/channels/api4/custom_profile_attributes.go, server/channels/api4/custom_profile_attributes_test.go, server/i18n/en.json
Cherry pick of #29906 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29906

server/channels/store/sqlstore/status_store.go
This reverts commit 84a83a1e0f4d2dbd7aa28766acd1e0049cc14094 after an spike in errors on Community:
```
{"timestamp":"2025-01-23 14:23:58.268 Z","level":"error","msg":"Encountered an error retrieving the status.","path":"/api/v4/users/status/ids","request_id":"qerrasaa4iyppkscx1tr3epwfh","ip_addr":"76.64.75.69","user_id":"7ri4633nqbgu9dq48u5uctzw8o","method":"POST","err_where":"GetUserStatusesByIds","http_code":500,"error":"GetUserStatusesByIds: Encountered an error retrieving the status., unable to scan from rows: sql: Scan error on column index 4, name \"dndendtime\": converting NULL to int64 is unsupported","stacktrace":[{"Function":"github.com/mattermost/mattermost/server/v8/channels/web.(*Context).LogErrorByCode","File":"github.com/mattermost/mattermost/server/v8/channels/web/context. …
```
=> Revert "[MM-62142] Avoid SELECT * in status_store.go (#29610)"

.github/workflows/server-ci-report.yml
Better formatting for CI reports
https://mattermost.atlassian.net/browse/MM-62429
```release-note
NONE
```
=> Better formatting for CI reports

webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx, webapp/channels/src/components/user_settings/general/user_settings_general.tsx, webapp/channels/src/packages/mattermost-redux/src/actions/users.test.ts, webapp/channels/src/packages/mattermost-redux/src/actions/users.ts, webapp/platform/client/src/client4.ts
Cherry pick of #29895 on release-10.5.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #29895

server/Makefile
Updated Boards prepackaged version to v9.0.6
```release-note
Updated Boards prepackaged version to v9.0.6
```
=> [9.11] Updated board prepackaged version to v9.0.6

server/channels/api4/handlers.go, server/channels/api4/user_test.go
Cherry pick of #29880 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29880

server/channels/app/permissions_migrations.go, server/channels/testlib/store.go, server/public/model/migration.go, server/public/model/role.go, server/public/model/role_test.go
Cherry pick of #29570 on release-10.5.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #29570

webapp/channels/src/sass/components/_forms.scss
MM-62655 - Updating control label overflow
Jira https://mattermost.atlassian.net/browse/MM-62655 
```release-note
NONE
```
=> MM-62655 - Updating control label overflow

webapp/channels/src/sass/components/_forms.scss
Cherry pick of #29991 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #29991

server/i18n/en.json
- i18n fix for sister branch in enterprise: https://github.com/mattermost/enterprise/pull/1829
- https://mattermost.atlassian.net/browse/MM-62527
```release-note
NONE
```
=> [MM-62527] i18n fix for sister branch in enterprise

server/public/model/integration_action.go, server/public/model/integration_action_test.go
- Fix a nil ptr dereference crash reported in sentry.
- Added tests for both paths for reaching that point.
- https://mattermost.atlassian.net/browse/MM-62537
```release-note
Fix a nil ptr dereference in the Interaction Action system.
```
=> [MM-62537] Fix: Integration action nil ptr dereference

server/channels/api4/handlers.go, server/channels/api4/user_test.go
Port of #29880 to v9.11
```release-note
NONE
```
=> Cherry pick of #29880 to v9.11

server/Makefile
Cherry pick of #30037 on release-10.5.
/cc  @Kshitij-Katiyar
```release-note
NONE
```
=> Automated cherry pick of #30037

webapp/channels/src/sass/components/_search.scss
Cherry pick of #30045 on release-10.5.
/cc  @Rajat-Dabade
```release-note
NONE
```
=> Automated cherry pick of #30045

webapp/channels/src/components/search/search.tsx
Cherry pick of #30041 to v10.5
```release-note
NONE
```
=> Manual cherry pick of #30041 to v10.5

server/channels/api4/channel.go, server/channels/api4/channel_test.go, webapp/channels/src/components/channel_layout/channel_identifier_router/actions.test.ts, webapp/channels/src/components/channel_layout/channel_identifier_router/actions.ts, webapp/channels/src/components/permalink_view/actions.ts, webapp/channels/src/components/permalink_view/permalink_view.test.tsx
Cherry pick of #29955 on release-10.5.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #29955

server/channels/api4/command.go, server/channels/api4/command_test.go, server/i18n/en.json
Cherry pick of #29896 on release-10.5.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #29896

server/Makefile
Upgraded board prepackaged version to v9.1.0
```release-note
Upgraded board prepackage version to v9.1.0
```
=> Upgraded boards prepackaged version to v9.1.0

.github/workflows/server-ci-report.yml
Cherry pick of #30033 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30033

server/channels/api4/job.go, server/channels/app/app_iface.go, server/channels/app/file.go, server/channels/app/opentracing/opentracing_layer.go
Cherry pick of #30092 on release-10.5.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #30092

server/channels/api4/oauth_test.go
Relates-to: https://mattermost.atlassian.net/browse/MM-62895
```release-note
NONE
```
=> t.Skip flaky TestUpdateOAuthApp

server/enterprise/message_export/worker.go, server/enterprise/message_export/worker_test.go
Cherry pick of #30120 on release-10.5.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #30120

.github/workflows/server-ci-report.yml
Cherry pick of #30142 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30142

server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/preference_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/PreferenceStore.go, server/channels/store/storetest/preference_store.go, server/channels/store/timerlayer/timerlayer.go
Fixes https://github.com/mattermost/mattermost/issues/30054
Jira https://mattermost.atlassian.net/browse/MM-62153
```release-note
NONE
```
=> [MM-62153] Avoid SELECT * in preference_store.go

server/channels/store/sqlstore/oauth_store.go
Fixes https://github.com/mattermost/mattermost/issues/30055
Jira https://mattermost.atlassian.net/browse/MM-62152
```release-note
NONE
```
=> [MM-62152] Avoid SELECT * in oauth_store.go

.github/workflows/server-ci-report.yml
Fixes https://mattermost.atlassian.net/browse/MM-62715
Please include @saturninoabril for any other bugs 
https://mattermost.atlassian.net/browse/MM-62715
```release-note
NONE
```
=> fix: MM-62714

NOTICE.txt
Cherry pick of #30152 on release-10.6.
```release-note
NONE
```
=> Automated cherry pick of #30152

server/channels/store/sqlstore/emoji_store.go, server/channels/store/sqlstore/utils.go
Fixes https://github.com/mattermost/mattermost/issues/30057
Jira https://mattermost.atlassian.net/browse/MM-62149
```release-note
NONE
```
=> [MM-62149] Avoid SELECT * in emoji_store.go

server/channels/app/limits.go, server/channels/app/limits_test.go, server/channels/app/user_test.go, webapp/channels/src/packages/mattermost-redux/src/actions/limits.test.ts
Cherry pick of #30134 on release-10.6.
```release-note
NONE
```
=> Automated cherry pick of #30134

server/Makefile
Upgraded board version to v9.1.1
```release-note
Upgraded board version to v9.1.1
```
=> Upgraded board version to v9.1.1

webapp/channels/src/components/team_settings/team_access_tab/allowed_domains_select.tsx, webapp/channels/src/components/team_settings/team_access_tab/open_invite.tsx, webapp/channels/src/components/team_settings/team_access_tab/team_access_tab.test.tsx
Cherry pick of #30116 on release-10.6.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30116

server/channels/app/export.go, server/channels/app/export_test.go
- Manual cherry pick of https://github.com/mattermost/mattermost/pull/30105
- https://mattermost.atlassian.net/browse/MM-62951
```release-note
NONE
```
=> [MM-62951] - CP MM-62876 Bulk export warnings (#30105)

webapp/channels/package.json, webapp/package-lock.json
Cherry pick of #30095 on release-10.6.
/cc  @enzowritescode
```release-note
NONE
```
=> Automated cherry pick of #30095

webapp/channels/src/components/admin_console/file_upload_setting.tsx
Cherry pick of #30182 on release-10.5.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30182

webapp/channels/src/sass/components/_post-menu.scss, webapp/channels/src/sass/components/_search.scss
Cherry pick of #30190 on release-10.6.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30190

server/public/model/property_field_test.go
Fix the build conflict from PRs https://github.com/mattermost/mattermost/pull/30097 and https://github.com/mattermost/mattermost/pull/29987
N/A
```release-note
NONE
```
=> Fix master build

server/channels/api4/post_test.go, server/channels/app/platform/web_conn.go, server/channels/app/platform/web_hub.go, server/channels/app/platform/web_hub_test.go, server/public/model/config.go
Cherry pick of #30178 on release-10.3.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30178

server/channels/app/channel_bookmark.go, server/channels/app/channel_bookmark_test.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/channel_bookmark_store.go, server/channels/store/store.go, server/channels/store/storetest/channel_bookmark.go, server/channels/store/storetest/mocks/ChannelBookmarkStore.go, server/channels/store/timerlayer/timerlayer.go
Cherry pick of #30034 on release-10.6.
```release-note
NONE
```
=> Automated cherry pick of #30034

webapp/channels/src/components/menu/menu.scss, webapp/channels/src/components/menu/sub_menu.tsx
- Updated the pointer event of the submenu.
- Reproduced on Community, Win/Chrome (specifically in the ~bugs channel but behaviour is the same in all channels)
- Have the RHS open
- Hover over a post in the center panel and click on the 3-dot menu 
- Move your mouse down over the list and click on “copy link”
- No option past “remind” works - this is also broken for posts in the RHS
- All options in the list work
Jira: https://mattermost.atlassian.net/browse/MM-62961
https://github.com/user-attachments/assets/7e8c0cb1-11de-4a65-86ac-290b5432ff3f
```release-note
```
=> [MM-62961]: Fixed pointer event of submenu

server/channels/app/authentication.go, server/channels/app/plugin_api_test.go, server/channels/app/plugin_requests.go, server/channels/web/context.go, server/i18n/en.json
Cherry pick of #30160 on release-10.6.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30160

server/Makefile
Use a supported version of `dbcmp`. 
```release-note
NONE
```
=> server/Makefile: pin dbcmp

server/Makefile
Cherry pick of #30245 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #30245

server/channels/api4/post_test.go, server/channels/app/platform/web_hub.go, server/channels/app/platform/web_hub_test.go
Cherry pick of #30224 on release-10.6.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30224

server/Makefile
Cherry pick of #29996 on release-10.3.
```release-note
NONE
```
=> Automated cherry pick of #29996

server/channels/api4/user_test.go, server/channels/app/bot.go
Cherry pick of #30268 on release-10.6.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30268

server/channels/api4/user.go, server/channels/api4/user_test.go
https://mattermost.atlassian.net/browse/MM-63195
```release-note
NONE
```
=> MM-63195: Allow only self for updateUserMFA

server/channels/api4/user.go, server/channels/api4/user_test.go
Cherry pick of #30290 on release-10.6.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30290

webapp/channels/src/components/drafts/drafts.scss
Cherry pick of #29811 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #29811

webapp/channels/package.json, webapp/package-lock.json
Cherry pick of #30265 on release-10.5.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30265

server/channels/api4/team.go, server/channels/api4/team_test.go
Cherry pick of #30170 on release-10.6.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #30170

NOTICE.txt
Cherry pick of #30309 on release-10.6.
```release-note
NONE
```
=> Automated cherry pick of #30309

e2e-tests/cypress/tests/integration/playbooks/channels/rhs/about_spec.js, webapp/channels/src/components/channel_header/channel_header_title.tsx, webapp/channels/src/sass/layout/_headers.scss
- Removed unnecessary aria-level={2} and role="heading" from Channel header title 
- Locate the Town Square text marked as a heading.
- Inspect it with Chrome DevTools.
- Notice that the text uses role="heading".
- Remove role="heading" and aria-level="2" from the <span>tag having class="heading".
Jira https://mattermost.atlassian.net/browse/MM-61652 [Issue reopened]
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
```release-note
NONE
```
=> MM-61652: Removed heading related role from channel header

server/channels/api4/emoji_test.go, server/channels/store/sqlstore/emoji_store.go
https://github.com/mattermost/mattermost/pull/30082 accidentally changed it so that these APIs returned nil which breaks some things on the frontend (notably the emoji autocomplete)
MM-63205
None needed because this regression hasn't shipped yet.
```release-note
NONE
```
=> MM-63205 Revert emoji store methods to return empty arrays instead of nil

server/channels/api4/user_test.go, server/channels/app/authorization.go, server/channels/app/authorization_test.go
Cherry pick of #30292 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30292

webapp/channels/package.json, webapp/channels/webpack.config.js, webapp/package-lock.json
Cherry pick of #30265 on release-9.11.
/cc  @hmhealey
```release-note
NONE
```
=> MM-62866 Update axios dependency (#30265)

server/channels/app/authorization.go, server/channels/app/authorization_test.go
Cherry pick of #30314 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #30314

server/Makefile
Cherry pick of #30273 on release-10.5.
/cc  @Kshitij-Katiyar
```release-note
NONE
```
=> Automated cherry pick of #30273

webapp/channels/src/sass/components/_modal.scss
Cherry pick of #30368 on release-10.6.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30368

webapp/channels/src/components/emoji_picker/components/emoji_picker_skin.tsx, webapp/channels/src/i18n/en.json
There are accordions without appropriate state information like Skin tone button. This PR adds appropriate role, state information to it.
- Navigate to the Skin tone button.
- Inspect its element with Chrome DevTools.
- Review its nesting structure.
- Review the values for and "Expanded".
Fixes: https://mattermost.atlassian.net/browse/MM-61604 [Issue reopened]
```release-note
```
=> [MM-61604]: Fixed aria-expanded not correctly announced by screen reader

server/Makefile
Cherry pick of #30437 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30437

webapp/channels/src/sass/components/_post.scss
Fixes https://github.com/mattermost/mattermost/issues/30052
Jira https://mattermost.atlassian.net/browse/MM-62360
|----|----|
| ![image](https://github.com/user-attachments/assets/b2d411a2-be4a-4717-a331-021b685298dd) | ![image](https://github.com/user-attachments/assets/e6bd794c-1683-4aa8-a968-2964f52623e3) |
```release-note
Fixed edit post textbox being sized incorrectly with the Grammarly browser extension installed
```
=> [MM-62360] Fixed width of edit input box 

e2e-tests/cypress/package-lock.json, e2e-tests/cypress/package.json, e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_sidebar_spec.ts, e2e-tests/cypress/tests/support/index.js, e2e-tests/cypress/tsconfig.json, webapp/channels/src/components/sidebar_right/sidebar_right.tsx, webapp/channels/src/utils/a11y_utils.ts
This PR adds the necessary logic for focusing the first focusable element when the RHS is opened via keyboard enhancing a11y for that region of the app.
*Note that this PR points to another branch that is pending to be merged into master since this change leverages part of the code in that PR.
This is a general change and is intended to cover several RHS content covered by several user stories.
https://mattermost.atlassian.net/browse/MM-61566
https://mattermost.atlassian.net/browse/MM-61567
https://mattermost.atlassian.net/browse/MM-61569
https://github.com/user-attachments/assets/986ec22c-3c3b-4ea8-80ea-7b606190bb14
```release-note
NONE
```
=> MM-61566 - focus first focusable element

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/i18n/en.json
Added missed license check in patchChannel API when updating channel banner.
Fixes https://mattermost.atlassian.net/browse/MM-63404
```release-note
none
```
=> Added missed license check for channel banner in patch channel API

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/i18n/en.json
Cherry pick of #30445 on release-10.7.
```release-note
NONE
```
=> Automated cherry pick of #30445

server/config/client.go, server/public/model/config.go
Cherry pick of #30411 on release-10.7.
/cc  @enahum
```release-note
NONE
```
=> Automated cherry pick of #30411

e2e-tests/cypress/tests/integration/channels/messaging/at_mentions_user_spec.js
Write an e2e test for verifying the search of hashtags from mentions
https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCase/MM-T360/testScript
```release-note
NONE
```
=>  MM-T360 - search hashtags from mentions

server/channels/app/export_test.go, server/channels/jobs/base_workers.go, server/channels/jobs/base_workers_test.go, server/channels/jobs/batch_worker.go, server/channels/jobs/jobs.go, server/channels/jobs/jobs_test.go, server/channels/jobs/migrations/worker.go, server/channels/jobs/plugins/worker.go, server/channels/jobs/s3_path_migration/s3_path_migration.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/job_store.go, server/channels/store/sqlstore/utils.go, server/channels/store/store.go, server/channels/store/storetest/job_store.go, server/channels/store/storetest/mocks/JobStore.go, server/channels/store/timerlayer/timerlayer.go, server/enterprise/elasticsearch/common/indexing_job.go, server/enterprise/elasticsearch/elasticsearch/aggregation_job.go, server/enterprise/elasticsearch/elasticsearch/aggregation_job_test.go, server/enterprise/elasticsearch/opensearch/aggregation_job.go, server/enterprise/elasticsearch/opensearch/aggregation_job_test.go, server/enterprise/message_export/worker.go, server/enterprise/message_export/worker_test.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job.go, server/platform/services/searchengine/bleveengine/indexer/indexing_job_test.go
Cherry pick of #30383 on release-10.6.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #30383

.github/workflows/codeql-analysis.yml, .github/workflows/esrupgrade-common.yml, .github/workflows/mmctl-test-template.yml, .github/workflows/server-ci-template.yml, .github/workflows/server-test-template.yml, webapp/channels/.github/workflows/performance-benchmarks.yml
Migrate tag-based references to commit SHA-based references for github workflows
https://mattermost.atlassian.net/browse/CLD-9005
=> migrate tag-based references to commit SHA-based references for github workflows

server/channels/api4/apitestlib.go, server/channels/api4/team.go, server/channels/api4/team_test.go, server/channels/api4/user_test.go
Cherry pick of #30448 on release-10.7.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30448

server/channels/api4/apitestlib.go, server/channels/api4/team.go, server/channels/api4/team_test.go, server/channels/api4/user_test.go
This is a cherry-pick of #30448
I also made a `api.TestHelper.CreateGuestUser` helper to save some typing
MM-63350
```release-note
NONE
```
=> MM-63350 Add tests for inviting guest users to teams (#30448)

server/Makefile
Cherry pick of #30529 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30529

server/channels/api4/status_test.go
https://mattermost.atlassian.net/browse/MM-63533
```release-note
NONE
```
=> [MM-63533] Skip flaky TestGetUserStatus/dnd_status_timed_restore_after_time_interval

server/platform/shared/filestore/filesstore_test.go
PR implements a new `BenchmarkFileStore,` which I used to compare the Write and Read performance of our three supported storage mediums: a local file system (EBS, gp3), a network file system (EFS), and object storage (S3).
```release-note
NONE
```
=> Implement BenchmarkFileStore

e2e-tests/cypress/tests/support/api/on_prem_default_config.json, e2e-tests/playwright/support/server/default_config.ts, e2e-tests/playwright/tests/functional/channels/search/team_selector.spec.ts, server/config/client.go, server/platform/services/telemetry/telemetry.go, server/public/model/config.go, server/public/model/feature_flags.go, server/tests/test-config.json, webapp/channels/src/components/new_search/new_search.tsx, webapp/channels/src/components/search/index.tsx, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/general.ts, webapp/platform/types/src/config.ts
Remove the Feature flag and add a config option
mobile PR: https://github.com/mattermost/mattermost-mobile/pull/8694
https://mattermost.atlassian.net/browse/MM-63513
```release-note
Remove the Feature flag and add a config option
```
=> [MM-63513] Turn Cross team search feature flag into a setting option

server/channels/api4/group.go, server/channels/api4/group_test.go, server/channels/app/group.go, server/channels/app/plugin_api.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/group_store.go, server/channels/store/store.go, server/channels/store/storetest/group_store.go, server/channels/store/storetest/mocks/GroupStore.go, server/channels/store/timerlayer/timerlayer.go
https://mattermost.atlassian.net/browse/MM-63311
```release-note
None
```
=> MM-63311 10.7 cherry-pick

e2e-tests/cypress/tests/integration/channels/enterprise/channel/channel_groups_spec.ts, server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/channels/api4/group.go, server/channels/api4/group_test.go, server/channels/api4/team.go, server/channels/api4/team_test.go, server/channels/app/syncables.go, webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx, webapp/channels/src/components/admin_console/team_channel_settings/team/details/team_details.tsx
Cherry pick of #30526 on release-10.7.
```release-note
NONE
```
=> Automated cherry pick of #30526

e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js, e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js, e2e-tests/playwright/support/ui/components/channels/post_create.ts, webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx, webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/footer.tsx, webapp/channels/src/components/advanced_text_editor/use_submit.tsx, webapp/channels/src/components/edit_post/edit_post.tsx, webapp/channels/src/components/msg_typing/index.ts, webapp/channels/src/components/msg_typing/msg_typing.test.tsx, webapp/channels/src/components/msg_typing/msg_typing.tsx
Cherry pick of #30470 on release-10.7.
```release-note
NONE
```
=> Automated cherry pick of #30470

e2e-tests/playwright/lib/package.json, e2e-tests/playwright/lib/src/server/default_config.ts, e2e-tests/playwright/package-lock.json, e2e-tests/playwright/package.json, e2e-tests/playwright/test/package.json, webapp/platform/types/src/config.ts
Upgraded playwright dependencies, server config and client config types for v10.7
Jira https://mattermost.atlassian.net/browse/MM-63620
```release-note
NONE
```
=> MM-63620 Upgrade playwright dependencies, server config and client config types for v10.7

e2e-tests/cypress/tests/support/api/system.js
Cherry pick of #30471 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #30471

e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js, e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js, e2e-tests/playwright/support/ui/components/channels/post_create.ts, webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx, webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/footer.tsx, webapp/channels/src/components/advanced_text_editor/use_submit.tsx, webapp/channels/src/components/edit_post/edit_post.tsx, webapp/channels/src/components/msg_typing/index.ts, webapp/channels/src/components/msg_typing/msg_typing.test.tsx, webapp/channels/src/components/msg_typing/msg_typing.tsx
Manual cherrypick of #30470
```release-note
None
```
=> Cherrypicked #30470 for 10.5

e2e-tests/cypress/tests/integration/channels/keyboard_shortcuts/up_arrow_edit_message_spec.js, e2e-tests/cypress/tests/integration/channels/messaging/center_channel_rhs_overlap_spec.js, e2e-tests/playwright/support/ui/components/channels/post_create.ts, webapp/channels/src/components/advanced_create_comment/advanced_create_comment.tsx, webapp/channels/src/components/advanced_create_post/advanced_create_post.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx, webapp/channels/src/components/advanced_text_editor/advanced_text_editor.tsx, webapp/channels/src/components/advanced_text_editor/footer.tsx, webapp/channels/src/components/advanced_text_editor/use_submit.tsx, webapp/channels/src/components/edit_post/edit_post.tsx, webapp/channels/src/components/msg_typing/index.ts, webapp/channels/src/components/msg_typing/msg_typing.test.tsx, webapp/channels/src/components/msg_typing/msg_typing.tsx
Manual cherrypick of #30470
```release-note
None
```
=> Cherrypicked #30470 for 10.6

server/channels/api4/group.go, server/channels/api4/group_test.go, server/channels/app/app_iface.go, server/channels/app/group.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/plugin_api.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/group_store.go, server/channels/store/store.go, server/channels/store/storetest/group_store.go, server/channels/store/storetest/mocks/GroupStore.go, server/channels/store/timerlayer/timerlayer.go
https://mattermost.atlassian.net/browse/MM-63311
```release-note
None
```
=> [MM-63311] Cherry pick 9.11

server/channels/api4/group.go, server/channels/api4/group_test.go, server/channels/app/app_iface.go, server/channels/app/group.go, server/channels/app/opentracing/opentracing_layer.go, server/channels/app/plugin_api.go, server/channels/store/opentracinglayer/opentracinglayer.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/group_store.go, server/channels/store/store.go, server/channels/store/storetest/group_store.go, server/channels/store/storetest/mocks/GroupStore.go, server/channels/store/timerlayer/timerlayer.go
https://mattermost.atlassian.net/browse/MM-63311
```release-note
None
```
=> [MM-63311] 10.5 cherry-pick

server/i18n/en.json
Fixing a typo in en.json
More info https://translate.mattermost.com/translate/mattermost/server/en/?checksum=09142512528acc2d#comments
```release-note
NONE
```
=> Fixing typo in en.json

e2e-tests/playwright/specs/functional/channels/search/search_box_suggestions.spec.ts, webapp/channels/src/components/new_search/search_box.tsx, webapp/channels/src/components/suggestion/search_user_provider.tsx
When using `From:  ` (notice the whitespaces), selecting a user should remove the extra whitespaces
Jira https://mattermost.atlassian.net/browse/MM-63597
```release-note
NONE
```
=> [MM-63597] Fix `From:` autocompletion

server/channels/wsapi/websocket_handler.go
Cherry pick of #30669 on release-10.6.
/cc  @davidkrauser
```release-note
NONE
```
=> Automated cherry pick of #30669

server/public/model/config.go
Adds system setting
https://mattermost.atlassian.net/browse/MM-63618
```release-note
NONE
```
=> [MM-63618] add abac settings

server/channels/app/bot.go, server/channels/app/bot_test.go
Cherry pick of #30466 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30466

webapp/channels/src/components/plugin_link_tooltip/index.test.tsx, webapp/channels/src/components/plugin_link_tooltip/index.tsx
Cherry pick of #30663 on release-10.8.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30663

e2e-tests/playwright/specs/functional/system_console/permissions/team_access.spec.ts, server/public/model/role.go, webapp/channels/src/components/admin_console/system_roles/system_role/__snapshots__/system_role_permission.test.tsx.snap, webapp/channels/src/components/admin_console/system_roles/system_role/system_role_permission.tsx
Cherry pick of #30672 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30672

e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts, server/channels/app/user.go
Manual cherry pick of #30571 to 9.11
```release-note
NONE
```
=> Manual cherry pick of #30571 to 9.11

e2e-tests/cypress/tests/integration/channels/users/deactivated_user_spec.ts, server/channels/app/user.go
Cherry pick of #30571 on release-10.7.
```release-note
NONE
```
=> Automated cherry pick of #30571

server/channels/api4/team.go, server/channels/api4/team_test.go
Cherry pick of #30650 on release-10.7.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30650

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/public/model/session.go
Cherry pick of #30467 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #30467

server/Makefile
Cherry pick of #30742 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30742

.github/workflows/server-test-template.yml
Cherry pick of #30778 on release-10.8.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30778

server/channels/store/sqlstore/group_store.go, server/channels/store/storetest/group_store.go
Change from `ug.` to `UserGroup.`. This supports later removing `SELECT *` in a way that doesn't rely on a convention `ug` and just uses the table name directly. As part of this, upgrade the test coverage for this store to help cover the upcoming removal of `SELECT *`.
Relates-to: https://mattermost.atlassian.net/browse/MM-62158
```release-note
NONE
```
=> MM-62158: Group Store, explicit aliases

webapp/channels/src/plugins/index.ts
Cherry pick of #30739 on release-10.8.
/cc  @fmartingr
```release-note
NONE
```
=> Automated cherry pick of #30739

webapp/.gitignore, webapp/channels/src/actions/views/rhs.test.ts, webapp/channels/src/actions/views/rhs.ts
Cherry pick of #30578 on release-10.5.
/cc  @vish9812
```release-note
NONE
```
=> Automated cherry pick of #30578

server/channels/store/sqlstore/command_store.go, server/channels/store/sqlstore/command_webhook_store.go
Avoid SELECT * in various command stores, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
=> avoid SELECT * in command stores

server/channels/store/sqlstore/cluster_discovery_store.go
Avoid SELECT * in cluster discovery store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
=> avoid SELECT * in cluster discovery store

server/channels/store/sqlstore/audit_store.go
Avoid SELECT * in audit store, ensuring forwards compatibility if new columns are later added.
```release-note
NONE
```
=> avoid SELECT * in audit store

server/.golangci.yml, server/channels/app/team.go
- Fixed errcheck issues in server/channels/app/team.go by properly handling errors with contextual logging
- Removed team.go from the errcheck exceptions list in .golangci.yml
Fixes https://github.com/mattermost/mattermost/issues/29108
N/A
```release-note
NONE
```
=> [MM-29108] Fix errcheck issues in server/channels/app/team.go

server/public/model/version.go
=> Update latest patch version to 10.6.4

server/channels/api4/apitestlib.go, server/channels/api4/channel_bookmark_test.go, server/channels/api4/channel_test.go, server/channels/api4/team.go, server/channels/api4/team_guest_test.go
Cherry pick of #30789 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #30789

server/Makefile
Cherry pick of #30863 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30863

webapp/channels/src/components/channel_header_menu/channel_header_menu.tsx, webapp/channels/src/components/channel_header_menu/channel_header_menu_items/channel_header_direct_menu.tsx, webapp/channels/src/components/channel_header_menu/channel_header_menu_items/channel_header_group_menu.tsx, webapp/channels/src/components/channel_header_menu/channel_header_menu_items/channel_header_public_private_menu.tsx
(cherry picked from commit 077f8e5061ba095d449603175c4e2f14b126e2ac)
https://github.com/mattermost/mattermost/pull/30801
```release-note
NONE
```
=> Cherry-pick - update menus for channel bookmarks (#30801)

webapp/channels/src/components/file_attachment/file_attachment.tsx, webapp/channels/src/sass/components/_files.scss
Cherry pick of #30855 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30855

server/channels/api4/custom_profile_attributes.go, server/channels/api4/custom_profile_attributes_test.go, server/channels/app/custom_profile_attributes.go, server/channels/app/custom_profile_attributes_test.go, server/i18n/en.json, server/public/model/custom_profile_attributes.go
Cherry pick of #30687 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30687

webapp/channels/src/components/advanced_text_editor/advanced_text_editor.test.tsx, webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx
Cherry pick of #30452 on release-10.6.
```release-note
NONE
```
=> Automated cherry pick of #30452

webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.test.tsx, webapp/channels/src/components/admin_console/system_properties/user_properties_type_menu.tsx
Cherry pick of #30913 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #30913

webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.test.tsx, webapp/channels/src/components/profile_popover/profile_popover_custom_attributes.tsx, webapp/channels/src/components/profile_popover/profile_popover_url.test.tsx, webapp/channels/src/components/profile_popover/profile_popover_url.tsx, webapp/channels/src/components/user_settings/general/user_settings_general.test.tsx, webapp/channels/src/components/user_settings/general/user_settings_general.tsx
Cherry pick of #30887 on release-10.8.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #30887

server/channels/app/platform/web_hub_test.go
As it says in the title
```release-note
NONE
```
=> Fix errcheck issue on master

server/build/notice-file/config.yaml
https://mattermost.atlassian.net/browse/CLD-9178
```release-note
NONE
```
=> fix: Ignore mm deps from Notice file

server/channels/store/sqlstore/channel_store_categories.go
Cherry pick of #30963 on release-10.5.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #30963

webapp/channels/src/components/admin_console/server_logs/__snapshots__/logs.test.tsx.snap, webapp/channels/src/components/admin_console/server_logs/logs.test.tsx, webapp/channels/src/components/admin_console/server_logs/logs.tsx
Fixed console search in admin to perform search in all log fields.  
Fixes https://github.com/mattermost/mattermost/issues/26322
Jira https://mattermost.atlassian.net/browse/MM-57014
Added unit test for logs.tsx, covering modified method: 
```release-note
Fixed console search in admin to perform search in all log fields
```
=> MM-57014 Extended console log search to all log attributes

server/channels/store/sqlstore/group_store.go
Picking up after https://github.com/mattermost/mattermost/pull/30276, this migrates the `groupsBySyncableBaseQuery` function away from `SELECT *`. I've pulled this out discretely so it's easier to focus on just one set of changes to review.
Relates-to: https://mattermost.atlassian.net/browse/MM-62158
```release-note
NONE
```
=> MM-62158: group store, migrate groupsBySyncableBaseQuery, part 2

webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/__snapshots__/permission_team_scheme_settings.test.tsx.snap, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.test.tsx, webapp/channels/src/components/admin_console/permission_schemes_settings/permission_team_scheme_settings/permission_team_scheme_settings.tsx
Cherry pick of #30953 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #30953

server/channels/api4/channel_test.go, server/i18n/en.json, server/public/model/channel.go, server/public/model/channel_test.go, webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx
Cherry pick of #30981 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30981

server/channels/app/properties/property_field.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/property_field_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/PropertyFieldStore.go, server/channels/store/storetest/property_field_store.go, server/channels/store/timerlayer/timerlayer.go
Cherry pick of #30859 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #30859

server/go.mod, server/go.sum
Server doesn't necessarily need this but it's better to keep it in sync
https://mattermost.atlassian.net/browse/MM-64222
```release-note
NONE
```
=> [MM-64222] Update gosaml to match enterprise version

server/go.mod, server/go.sum
Cherry pick of #31031 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31031

server/channels/app/channel.go, server/channels/app/channel_test.go, server/i18n/en.json
Cherry pick of #30746 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #30746

webapp/channels/src/components/__snapshots__/autosize_textarea.test.tsx.snap, webapp/channels/src/components/autosize_textarea.tsx, webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss
Cherry pick of #30983 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30983

webapp/channels/src/components/channel_name_form_field/channel_name_form_field.tsx, webapp/channels/src/components/widgets/inputs/input/input.test.tsx, webapp/channels/src/components/widgets/inputs/input/input.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #30979 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30979

webapp/channels/src/components/__snapshots__/textbox.test.tsx.snap, webapp/channels/src/components/textbox/textbox.tsx, webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.scss, webapp/channels/src/components/widgets/advanced_textbox/advanced_textbox.tsx, webapp/channels/src/components/widgets/inputs/input/input.scss
Cherry pick of #30984 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30984

webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.test.tsx, webapp/channels/src/components/channel_settings_modal/channel_settings_configuration_tab.tsx, webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.test.tsx, webapp/channels/src/components/channel_settings_modal/channel_settings_info_tab.tsx
Cherry pick of #30993 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #30993

NOTICE.txt
Cherry pick of #31096 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31096

server/Makefile
Bumps Playbooks-prepackaged
- https://mattermost.atlassian.net/browse/MM-63706
```release-note
NONE
```
=> Prepackage Playbooks 2.2.0

server/platform/services/docextractor/archive.go
Cherry pick of #31103 on release-9.11.
```release-note
NONE
```
=> Automated cherry pick of #31103

server/Makefile
Cherry pick of #31067 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31067

server/channels/api4/ldap.go, server/channels/api4/ldap_test.go, server/channels/app/group.go, server/channels/app/ldap.go, server/channels/app/syncables.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/group_store.go, server/channels/store/store.go, server/channels/store/storetest/group_store.go, server/channels/store/storetest/mocks/GroupStore.go, server/channels/store/timerlayer/timerlayer.go, server/cmd/mmctl/client/client.go, server/cmd/mmctl/commands/ldap.go, server/cmd/mmctl/commands/ldap_test.go, server/cmd/mmctl/docs/mmctl_ldap_sync.rst, server/cmd/mmctl/mocks/client_mock.go, server/einterfaces/ldap.go, server/einterfaces/mocks/LdapInterface.go, server/public/model/client4.go, server/public/model/config.go, webapp/channels/src/components/admin_console/admin_definition.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #30787 on release-10.9.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #30787

server/channels/api4/channel_category.go, server/channels/api4/channel_category_test.go, server/channels/store/sqlstore/channel_store_categories.go, server/channels/store/storetest/channel_store_categories.go
Cherry pick of #30965 on release-10.9.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #30965

server/channels/api4/post_create_test.go, server/channels/app/post.go, server/channels/app/post_test.go
Cherry pick of #31004 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31004

server/Makefile
Prepackage [Calls v1.8.0](https://github.com/mattermost/mattermost-plugin-calls/releases/tag/v1.8.0).
https://mattermost.atlassian.net/browse/MM-63789
```release-note
Prepackage Calls v1.8.0
```
=> [MM-63789] Prepackage Calls v1.8.0

server/channels/app/plugin_api.go, server/i18n/en.json, server/public/plugin/api.go, server/public/plugin/api_timer_layer_generated.go, server/public/plugin/client_rpc_generated.go, server/public/plugin/plugintest/api.go, server/public/pluginapi/group.go
Cherry pick of #30790 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #30790

server/channels/api4/channel_category.go, server/channels/api4/channel_category_test.go, server/channels/store/sqlstore/channel_store_categories.go, server/channels/store/storetest/channel_store_categories.go
Cherry-pick of #30965
MM-63923
MM-63924
MM-63925
```release-note
Fixed possible deadlocks when updating SidebarCategories and SidebarChannels tables
```
=> MM-63923/MM-63924/MM-63925 Prevent deadlocks and constraint errors in UpdateSidebarCategories (#30965) (10.5)

webapp/channels/src/components/admin_console/group_settings/group_details/group_details.test.tsx, webapp/channels/src/components/admin_console/group_settings/group_details/group_details.tsx
Cherry pick of #30629 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #30629

webapp/platform/mattermost-redux/package.json
See #31176
MM-64393
```release-note
NONE
```
=> Explicitly list exports from mattermost-redux (10.8)

server/channels/app/webhook.go, server/channels/app/webhook_test.go
Cherry pick of #31068 on release-10.9.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #31068

webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx, webapp/channels/src/i18n/en.json
Adds an error message when policy enforce is toggled but a policy is not selected
https://mattermost.atlassian.net/browse/MM-64364
https://github.com/user-attachments/assets/2ebcb028-b36a-4694-a37e-c3c49473daa6
```release-note
NONE
```
=> [MM-64364] error when policy toggled but not selected

webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_details.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #31200 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31200

server/Makefile
Cherry pick of #31039 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31039

webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.scss, webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx, webapp/channels/src/i18n/en.json
If the channel is removed instead of adding a text as "To be removed", we remove from the list immediately.
https://mattermost.atlassian.net/browse/MM-64293
```release-note
NONE
```
=> [MM-64293] removed channels will dissappear from channel list in policy edit

webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.scss, webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx, webapp/channels/src/i18n/en.json
Cherry pick of #31140 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31140

server/channels/store/sqlstore/product_notices_store.go
Replace `SELECT *` with explicit column names in the product notices store.
```release-note
NONE
```
=> Remove SELECT * from product notices store

e2e-tests/cypress/tests/integration/channels/channel/channel_settings_menu_permissions_spec.ts, webapp/channels/src/components/channel_header_menu/menu_items/channel_settings_menu.tsx, webapp/channels/src/selectors/views/channel_settings.test.ts, webapp/channels/src/selectors/views/channel_settings.ts
Cherry pick of #31178 on release-10.9.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #31178

server/channels/store/sqlstore/channel_store.go, server/channels/store/storetest/channel_store.go
Cherry pick of #31163 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31163

server/public/model/feature_flags.go
Cherry pick of #31269 on release-10.9.
```release-note
NONE
```
=> Automated cherry pick of #31269

server/channels/app/import.go, server/channels/app/import_functions.go, server/channels/app/import_test.go, server/channels/app/imports/import_validators.go, server/channels/app/imports/import_validators_test.go, server/cmd/mmctl/commands/import_test.go, server/i18n/en.json
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/31201 to `release-10.6`
```release-note
NONE
```
=> [MM-64402] `release-10.6` cherry-pick

server/channels/app/import.go, server/channels/app/import_functions.go, server/channels/app/import_test.go, server/channels/app/imports/import_validators.go, server/channels/app/imports/import_validators_test.go, server/cmd/mmctl/commands/import_test.go, server/i18n/en.json
Manual cherry-pick of https://github.com/mattermost/mattermost/pull/31201 to `release-9.11`.
Merge wasn't trivial so asking for another (hopefully) quick pass.
```release-note
NONE
```
=> [MM-64402] `release-9.11` cherry-pick

server/Makefile
Cherry pick of #31276 on release-10.7.
```release-note
NONE
```
=> Automated cherry pick of #31276

.github/workflows/claude.yml
With this limitation removed, it can do more things in a PR.
```release-note
NONE
```
=> Improve claude code to run bash commands

webapp/channels/src/components/new_search/search_hint.tsx, webapp/channels/src/components/user_settings/notifications/__snapshots__/user_settings_notifications.test.tsx.snap, webapp/channels/src/components/user_settings/notifications/desktop_and_mobile_notification_setting/__snapshots__/index.test.tsx.snap, webapp/channels/src/components/widgets/icons/fa_edit_icon.tsx
Added `aria-hidden=true` to some icons that are only there for decoration.
MM-63057
MM-63003
```release-note
NONE
```
=> [MM-63057][MM-63003] Set aria-hidden on decorative icons

server/channels/app/channel.go, server/channels/app/import_functions.go, server/channels/app/import_functions_test.go, server/channels/app/platform/shared_channel_notifier.go, server/channels/app/post_metadata_test.go, server/channels/app/post_test.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/searchlayer/channel_layer.go, server/channels/store/sqlstore/channel_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/ChannelStore.go, server/channels/store/timerlayer/timerlayer.go, server/platform/services/sharedchannel/channelinvite.go, server/platform/services/sharedchannel/mock_AppIface_test.go, server/platform/services/sharedchannel/service.go, server/platform/services/sharedchannel/sync_recv.go, server/platform/services/slackimport/slackimport.go
Cherry pick of #31403 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #31403

.github/workflows/dispatch-server-builder-image.yml
Add dispatch build
```release-note
NONE
```
=> Add dispatch build

webapp/channels/src/components/profile_popover/profile_popover_other_user_row.test.tsx, webapp/channels/src/components/profile_popover/profile_popover_other_user_row.tsx, webapp/channels/src/sass/components/_post.scss
Cherry pick of #30903 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #30903

server/channels/store/sqlstore/channel_store.go, server/channels/store/storetest/channel_store.go
Cherry pick of #31362 on release-10.9.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #31362

webapp/channels/src/components/admin_console/feature_discovery/feature_discovery.tsx, webapp/channels/src/components/announcement_bar/configuration_bar/__snapshots__/configuration_bar.test.tsx.snap, webapp/channels/src/components/announcement_bar/configuration_bar/configuration_bar.tsx, webapp/channels/src/components/announcement_bar/purchase_link/purchase_link.tsx, webapp/channels/src/components/announcement_bar/renewal_link/renew_link.scss, webapp/channels/src/components/announcement_bar/renewal_link/renewal_link.tsx
Cherry pick of #31425 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #31425

server/channels/api4/shared_channel_metadata_test.go, server/channels/api4/shared_channel_test_utils.go, server/channels/app/platform/shared_channel_notifier.go, server/channels/app/post.go, server/channels/app/post_acknowledgements.go, server/channels/app/post_acknowledgements_test.go, server/channels/db/migrations/migrations.list, server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql, server/channels/db/migrations/mysql/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql, server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.down.sql, server/channels/db/migrations/postgres/000141_add_remoteid_channelid_to_post_acknowledgements.up.sql, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/post_acknowledgements_store.go, server/channels/store/sqlstore/post_priority_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/PostAcknowledgementStore.go, server/channels/store/storetest/mocks/PostPriorityStore.go, server/channels/store/storetest/post_acknowledgements_store.go, server/channels/store/timerlayer/timerlayer.go, server/i18n/en.json, server/platform/services/sharedchannel/mock_AppIface_test.go, server/platform/services/sharedchannel/service.go, server/platform/services/sharedchannel/sync_recv.go, server/platform/services/sharedchannel/sync_send.go, server/platform/services/sharedchannel/sync_send_remote.go, server/public/model/post_acknowledgement.go, server/public/model/shared_channel.go
Cherry pick of #30736 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #30736

server/channels/store/sqlstore/channel_store.go, server/channels/store/storetest/channel_store.go
Manual cherrypick of #31362
NONE
```release-note
Fix issue where mobile may not retrieve DM/GMs.
```
=> MANUAL CHERRYPICK: Fix getAllChannels api not returning DMs/GMs (#31362)

webapp/channels/src/components/login/login.tsx, webapp/channels/src/utils/embed.tsx
Cherry pick of #31002 on release-10.7.
/cc  @fmartingr
```release-note
NONE
```
=> Automated cherry pick of #31002

server/channels/app/limits.go, server/channels/app/limits_test.go, server/channels/app/user_limits_test.go, server/public/model/license.go
Cherry pick of #31629 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #31629

server/channels/api4/remote_cluster.go, server/i18n/en.json
Restrict import upload for shared channels feature, similar to the way we restrict the import upload for the regular upload API.
```release-note
NONE
```
=> MM-64610: Restrict import upload for shared channels feature.

webapp/channels/src/components/channel_header_menu/menu_items/mobile_channel_header_plugins.tsx, webapp/channels/src/plugins/registry.ts
Exposing icon and dropdown text parameters for the Calls plugin
https://mattermost.atlassian.net/browse/MM-61593
```release-note
NONE
```
=> [MM-61593] Add parameters for icon/dropdown text for the Calls button

server/channels/api4/remote_cluster.go, server/i18n/en.json
Cherry pick of #31659 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #31659

server/channels/store/sqlstore/shared_channel_store.go
Cherry pick of #31221 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #31221

server/channels/app/channel.go, server/platform/services/sharedchannel/channelinvite.go
Cherry pick of #32152 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #32152

server/channels/api4/shared_channel_metadata_test.go, server/channels/app/shared_channel_membership_sync_self_referential_test.go
https://mattermost.atlassian.net/browse/MM-64687
```release-note
NONE
```
=> MM-64687: Racy tests in TestSharedChannelPostMetadataSync

webapp/channels/src/components/admin_console/admin_definition.tsx, webapp/channels/src/components/admin_console/feature_discovery/features/user_attributes.tsx, webapp/channels/src/i18n/en.json
Added a feature discovery page for CPA as well.
https://mattermost.atlassian.net/browse/MM-64491
https://github.com/user-attachments/assets/20c22be5-9836-4ca7-9b0d-f7b7138d790f
```release-note
NONE
```
=> [MM-64491] Fix system attributes section not appearting w/o a license

e2e-tests/cypress/tests/integration/channels/accessibility/accessibility_account_settings_spec.js, e2e-tests/playwright/specs/accessibility/channels/account_settings_sidebar.spec.ts, server/public/model/channel.go, webapp/channels/src/components/settings_sidebar/settings_sidebar.tsx, webapp/channels/src/sass/routes/_settings.scss
Cherry pick of #32098 on release-10.10.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #32098

server/channels/app/access_control.go, server/channels/app/access_control_test.go, webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap, webapp/channels/src/components/admin_console/access_control/policy_details/channel_list/channel_list.tsx, webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx
Cherry pick of #32164 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #32164

server/channels/api4/team.go, server/channels/api4/team_test.go
Cherry pick of #32118 on release-10.8.
```release-note
NONE
```
=> Automated cherry pick of #32118

server/channels/app/notification.go, webapp/channels/src/components/post_view/post_add_channel_member/__snapshots__/post_add_channel_member.test.tsx.snap, webapp/channels/src/components/post_view/post_add_channel_member/index.ts, webapp/channels/src/components/post_view/post_add_channel_member/post_add_channel_member.test.tsx, webapp/channels/src/components/post_view/post_add_channel_member/post_add_channel_member.tsx
Cherry pick of #31226 on release-10.10.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #31226

webapp/channels/src/components/admin_console/admin_definition.tsx
Cherry pick of #33011 on release-10.10.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #33011

webapp/channels/src/components/admin_console/team_channel_settings/channel/details/channel_access_control_policy.tsx
Fixes a broken link in channel settings
https://mattermost.atlassian.net/browse/MM-64609
```release-note
NONE
```
=> [MM-64609] Fix bad link to ABAC Policy Edit page from Channel Management page

server/i18n/en.json, server/platform/services/sharedchannel/attachment.go
Cherry pick of #33351 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #33351

server/channels/app/imports/import_validators.go, server/channels/app/imports/import_validators_test.go, server/i18n/en.json
Cherry pick of #33287 on release-10.8.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #33287

server/channels/api4/upload.go, server/channels/api4/upload_test.go
Cherry pick of #33370 on release-10.8.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #33370

webapp/channels/src/components/channel_invite_modal/channel_invite_modal.test.tsx, webapp/channels/src/components/channel_invite_modal/channel_invite_modal.tsx, webapp/channels/src/components/channel_invite_modal/index.ts
Cherry pick of #32803 on release-10.10.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #32803

server/channels/app/platform/shared_channel_service_iface.go, server/channels/app/shared_channel_service_iface.go, server/channels/app/shared_channel_test.go, server/platform/services/sharedchannel/service.go, server/platform/services/sharedchannel/sync_recv.go, server/platform/services/sharedchannel/sync_send_remote.go, server/public/model/shared_channel.go
Cherry pick of #32101 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #32101

server/channels/api4/channel_test.go, server/channels/api4/team_test.go, server/channels/app/channel.go, server/channels/app/team.go, server/i18n/en.json
Manual cherry-pick of #30957 on `release-9.11`
https://mattermost.atlassian.net/browse/MM-64178
```release-note
NONE
```
=> Manual CP 9.11 Fix MM64178 (#30957)

server/channels/api4/channel_test.go, server/channels/api4/team_test.go, server/channels/app/channel.go, server/channels/app/team.go, server/i18n/en.json
Manual cherry-pick of #30957 on `release-10.5`
https://mattermost.atlassian.net/browse/MM-64178
```release-note
NONE
```
=> Manual CP 10.5 Fix MM64178 (#30957)

server/channels/api4/config_local.go, server/channels/api4/config_test.go
Cherry pick of #33376 on release-10.11.
/cc  @agnivade
```release-note
NONE
```
=> Automated cherry pick of #33376

server/Makefile
Cherry pick of #33477 on release-10.11.
/cc  @cpoile
```release-note
NONE
```
=> Automated cherry pick of #33477

e2e-tests/playwright/lib/src/server/default_config.ts, server/public/model/config.go, webapp/channels/src/components/admin_console/access_control/editors/table_editor/attribute_selector_menu.tsx, webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx, webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx, webapp/channels/src/components/admin_console/access_control/policy_details/__snapshots__/policy_details.test.tsx.snap, webapp/channels/src/components/admin_console/access_control/policy_details/index.ts, webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.test.tsx, webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/access_control.ts, webapp/platform/types/src/config.ts
Cherry pick of #32522 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #32522

server/build/Dockerfile, server/build/passwd
Cherry pick of #33523 on release-10.10.
/cc  @esarafianou
```release-note
NONE
```
=> Automated cherry pick of #33523

server/channels/utils/utils.go, server/channels/utils/utils_test.go
https://mattermost.atlassian.net/browse/MM-64755
```release-note
NONE
```
=> MM-64755: Fix redirect in oauth login

server/Makefile
Prepackage playbooks v2.3.0
https://mattermost.atlassian.net/browse/MM-64946
```release-note
Updated Playbooks plugin to v2.3.0 
```
=> [MM-64946] Prepackage playbooks v2.3.0

server/platform/services/sharedchannel/membership.go, server/platform/services/sharedchannel/util.go
Cherry pick of #33560 on release-10.10.
```release-note
NONE
```
=> Automated cherry pick of #33560

server/Makefile
Cherry pick of #33574 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #33574

webapp/channels/src/components/new_search/search_box.tsx, webapp/channels/src/components/new_search/search_box_input.tsx
Cherry pick of #33563 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #33563

server/channels/web/oauth.go, server/channels/web/oauth_test.go
Cherry pick of #33559 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #33559

server/channels/web/oauth.go, server/channels/web/oauth_test.go, server/channels/web/saml.go
Cherry pick of #33626 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #33626

server/i18n/en.json
adding a missing n
https://community.mattermost.com/core/pl/stp5mgax5pgrbknndo6b3rr6xc
```release-note
NONE
```
=> Fixing a typo

server/channels/app/oauth.go, server/channels/app/oauth_test.go, server/channels/app/team.go, server/channels/app/user.go, server/channels/app/user_test.go, server/channels/web/oauth.go, server/channels/web/saml.go
Cherry pick of #33545 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #33545

webapp/channels/src/components/setting_item_max.tsx
Cherry pick of #33624 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33624

server/channels/app/channel.go
Cherry pick of #33411 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33411

webapp/channels/src/components/cloud_preview_modal/cloud_preview_modal.scss
Cherry pick of #33379 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33379

webapp/channels/src/components/common/hooks/useOpenSalesLink.ts
Cherry pick of #33451 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33451

webapp/channels/src/components/__snapshots__/searchable_channel_list.test.tsx.snap, webapp/channels/src/components/searchable_channel_list.tsx
Cherry pick of #33625 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33625

server/public/model/cel.go, webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.test.tsx, webapp/channels/src/components/admin_console/access_control/editors/table_editor/table_editor.tsx, webapp/channels/src/components/admin_console/access_control/editors/table_editor/value_selector_menu.tsx, webapp/channels/src/components/admin_console/access_control/policy_details/policy_details.tsx, webapp/platform/types/src/access_control.ts
Cherry pick of #33494 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33494

webapp/channels/src/components/login/login.tsx
Cherry pick of #33591 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33591

server/i18n/en.json
Cherry pick of #33476 on release-10.12.
/cc  @amyblais
```release-note
NONE
```
=> Automated cherry pick of #33476

webapp/channels/src/components/logged_in/index.test.ts, webapp/channels/src/components/logged_in/index.ts, webapp/channels/src/components/logged_in/logged_in.test.tsx, webapp/channels/src/components/logged_in/logged_in.tsx, webapp/channels/src/components/profile_popover/profile_popover.test.tsx, webapp/channels/src/components/profile_popover/profile_popover.tsx, webapp/channels/src/components/root/index.ts, webapp/channels/src/components/root/root.test.tsx, webapp/channels/src/components/root/root.tsx, webapp/channels/src/components/user_settings/general/index.ts, webapp/channels/src/packages/mattermost-redux/src/actions/users.ts
Cherry pick of #32142 on release-10.12.
/cc  @sbishel
```release-note
NONE
```
=> Automated cherry pick of #32142

webapp/channels/src/components/should_verify_email/should_verify_email.scss
Cherry pick of #33394 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33394

server/platform/services/sharedchannel/membership_recv.go
Cherry pick of #32771 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #32771

webapp/channels/src/components/select_team/__snapshots__/select_team.test.tsx.snap, webapp/channels/src/components/select_team/select_team.test.tsx, webapp/channels/src/components/select_team/select_team.tsx
Cherry pick of #33389 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33389

server/public/model/slack_attachment.go, server/public/model/slack_attachment_test.go
Cherry pick of #33562 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33562

webapp/channels/src/components/advanced_text_editor/use_key_handler.tsx, webapp/channels/src/utils/paste.test.tsx, webapp/channels/src/utils/paste.tsx
Cherry pick of #33459 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33459

server/build/docker-preview/Dockerfile
Cherry pick of #33708 on release-10.9.
/cc  @saturninoabril
```release-note
NONE
```
=> Automated cherry pick of #33708

webapp/channels/src/components/post_profile_picture/post_profile_picture.tsx, webapp/channels/src/components/profile_picture/index.tsx, webapp/channels/src/components/widgets/users/avatar/avatar.tsx, webapp/channels/src/sass/components/_post.scss
Cherry pick of #33651 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33651

webapp/channels/src/components/advanced_text_editor/priority_labels/priority_labels.scss
Cherry pick of #33658 on release-10.12.
```release-note
NONE
```
=> Automated cherry pick of #33658

server/public/model/remote_cluster.go
While investigating the work needed for https://mattermost.atlassian.net/browse/MM-65088, I found out that we were already using `pbkdf2` in a specific part of the codebase. But we were using the old `x/crypto/pbkdf2`, not the now standard `crypto/pbkdf2` ([since Go 1.24](https://tip.golang.org/doc/go1.24#crypto-packages)).
This cleanup PR simply updates that package, with the needed update on the function call.
https://mattermost.atlassian.net/browse/MM-65088
--
```release-note
NONE
```
=> MM-65088: Replace x/crypto/pbkdf2 with crypto/pbkdf2

server/channels/app/slack.go, server/platform/services/slackimport/slackimport.go, server/platform/services/slackimport/slackimport_test.go
Cherry pick of #33609 on release-10.12.
/cc  @pvev
```release-note
NONE
```
=> Automated cherry pick of #33609

webapp/channels/src/actions/notification_actions.tsx, webapp/channels/src/components/post_view/message_attachments/action_button/action_button.tsx, webapp/channels/src/components/post_view/message_attachments/action_menu/action_menu.tsx, webapp/channels/src/components/post_view/message_attachments/message_attachment/message_attachment.tsx, webapp/platform/types/src/integration_actions.ts, webapp/platform/types/src/message_attachments.ts
Cherry pick of #33612 on release-10.11.
/cc  @larkox
```release-note
NONE
```
=> Automated cherry pick of #33612

webapp/channels/package.json, webapp/package-lock.json
We only had an explicit dependency on it to fix a bug in the `@mattermost/compass-components` package, and I forgot to remove that dependency in #33744.
https://mattermost.atlassian.net/browse/MM-64380
```release-note
NONE
```
=> Remove dependency on Axios following Compass removal

server/channels/api4/channel.go, server/channels/api4/channel_test.go
Cherry pick of #31319 on release-10.11.
```release-note
NONE
```
=> Automated cherry pick of #31319

server/channels/app/oauth.go, server/channels/app/session.go
Cherry pick of #33588 on release-10.12.
/cc  @esarafianou
```release-note
NONE
```
=> Automated cherry pick of #33588

webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.test.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/channels.ts
Cherry pick of #33592 on release-10.5.
```release-note
NONE
```
=> Automated cherry pick of #33592

server/Makefile, webapp/channels/src/components/announcement_bar/announcement_bar.test.tsx, webapp/channels/src/components/announcement_bar/announcement_bar_controller.tsx, webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx, webapp/channels/src/components/announcement_bar/post_history_limit_banner/index.tsx, webapp/channels/src/components/announcement_bar/post_history_limit_banner/post_history_limit_banner.scss, webapp/channels/src/components/announcement_bar/post_history_limit_banner/post_history_limit_banner.test.tsx, webapp/channels/src/components/announcement_bar/text_dismissable_bar.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/packages/mattermost-redux/src/constants/preferences.ts, webapp/channels/src/packages/mattermost-redux/src/selectors/entities/preferences.ts, webapp/channels/src/sass/base/_css_variables.scss, webapp/channels/src/sass/responsive/_mobile.scss, webapp/channels/src/sass/routes/_signup.scss, webapp/channels/src/utils/constants.tsx
Cherry pick of #33846 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33846

server/channels/api4/channel.go, server/channels/api4/channel_test.go, server/channels/api4/user.go, server/public/model/channel_member.go, server/public/model/channel_member_test.go
Cherry pick of https://github.com/mattermost/mattermost/pull/33835
```release-note
NONE
```
=> Cherry pick #33835 onto release 10.5

server/channels/api4/limits_test.go, server/channels/app/limits.go, server/channels/app/limits_test.go, webapp/channels/src/components/announcement_bar/default_announcement_bar/announcement_bar.tsx, webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.test.ts, webapp/channels/src/components/announcement_bar/users_limits_announcement_bar/index.tsx, webapp/channels/src/i18n/en.json, webapp/channels/src/sass/components/_announcement-bar.scss, webapp/channels/src/utils/constants.tsx
Cherry pick of #33888 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33888

server/build/Dockerfile.fips
Fixed `/var/tmp` permission
Part of https://mattermost.atlassian.net/browse/MM-65043
```release-note
NONE
```
=> MM-65043 Fix /var/tmp permission

webapp/channels/src/components/widgets/menu/menu_items/menu_item.scss, webapp/channels/src/plugins/registry.ts
Cherry pick of #33928 on release-11.0.
/cc  @hmhealey
```release-note
NONE
```
=> Automated cherry pick of #33928

server/Makefile
Prepackage the FIPS version of Playbooks v2.4.2.
--
--
```release-note
NONE
```
=> Prepackage Playbooks FIPS v2.4.2

server/Makefile
Cherry pick of #33934 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33934

server/channels/api4/custom_profile_attributes.go, server/channels/api4/custom_profile_attributes_local.go, server/channels/api4/custom_profile_attributes_test.go
This PR adds the CPA endpoints to local mode correctly configured and updates the CPA value list endpoint to make it work in local mode.
https://mattermost.atlassian.net/browse/MM-65806
```release-note
NONE
```
=> Adds value endpoints to local mode

server/cmd/mmctl/commands/cpa.go, server/cmd/mmctl/commands/cpa_field.go, server/cmd/mmctl/commands/cpa_field_e2e_test.go, server/cmd/mmctl/commands/cpa_field_test.go, server/cmd/mmctl/commands/cpa_value.go, server/cmd/mmctl/commands/cpa_value_e2e_test.go, server/cmd/mmctl/commands/cpa_value_test.go, server/cmd/mmctl/docs/mmctl_cpa_field_delete.rst, server/cmd/mmctl/docs/mmctl_cpa_field_edit.rst, server/cmd/mmctl/docs/mmctl_cpa_value_set.rst
Cherry pick of #33943 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33943

server/channels/api4/custom_profile_attributes.go, server/channels/api4/custom_profile_attributes_local.go, server/channels/api4/custom_profile_attributes_test.go
Cherry pick of #33950 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33950

.github/workflows/server-ci-report.yml
Cherry pick of #33892 on release-11.0.
```release-note
NONE
```
=> Automated cherry pick of #33892

server/cmd/mmctl/commands/root.go, server/cmd/mmctl/commands/system.go, server/cmd/mmctl/commands/system_test.go
Cherry pick of #33970 on release-10.11.
/cc  @hanzei
```release-note
NONE
```
=> Automated cherry pick of #33970

api/v4/source/users.yaml, server/channels/api4/user.go, server/channels/app/user.go, server/channels/store/retrylayer/retrylayer.go, server/channels/store/sqlstore/tokens_store.go, server/channels/store/store.go, server/channels/store/storetest/mocks/TokenStore.go, server/channels/store/timerlayer/timerlayer.go, server/channels/web/saml.go, server/public/model/feature_flags.go, server/public/model/token.go
Automatic Merge
See the [Jira ticket](https://mattermost.atlassian.net/browse/MM-65084) for details
https://mattermost.atlassian.net/browse/MM-65084
```release-note
See Jira ticket
```
=> MM 65084 server-side (#33861) (#34006)
