- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- api4/oauth.go
- app/auto_posts.go
- app/saml.go
- app/user.go
- cmd/platform/channel.go
- cmd/platform/import.go
- cmd/platform/init.go
- cmd/platform/license.go
- cmd/platform/mattermost.go
- cmd/platform/roles.go
- cmd/platform/server.go
- cmd/platform/team.go
- cmd/platform/test.go
- cmd/platform/user.go
- cmd/platform/version.go
- utils/config.go
- utils/html.go
- utils/i18n.go
- utils/license.go
- web/web.go
It should now panic instead of swallowing errors that occur while loading the translation files. I would've returned the errors to cobra, but that causes the usage message to be printed which I didn't think we wanted whenever an error occurs.
https://mattermost.atlassian.net/browse/PLT-6471
> PLT-6471 Properly panic when translations can't be loaded

- i18n/en.json
[PLT-6392] Make the message "Failed to add from email address" more explicit
JIRA: https://mattermost.atlassian.net/browse/PLT-6392
GitHub: https://github.com/mattermost/platform/issues/6479
> [PLT-6392] Make the message "Failed to add from email address" more explicit

- app/channel.go
This fixes a race condition, that was causing some user statuses to get stuck online, between setting the active channel to blank and the closing of the websocket setting the status to offline.
https://mattermost.atlassian.net/browse/PLT-6333
> PLT-6333 Only update status when clicking onto app

- app/file.go
- app/user.go
The image still appears rotated in the preview, but will be upright once uploaded. I filed an additional ticket to fix the preview since that's also an issue with file attachment previews.
https://mattermost.atlassian.net/browse/PLT-6534
> PLT-6534 Rotated uploaded profile pictures to be upright

- webapp/components/login/login_controller.jsx
- webapp/components/root.jsx
- webapp/routes/route_team.jsx
When the user comes with a link to a specific channel but is not logged in the original destination url is lost. This changes add the ability to have a redirect_to parameter for after successful login.
https://mattermost.atlassian.net/browse/PLT-2780
> PLT-2780 Add RedirectTo after login for Universal linking or deep linking to work

- app/notification.go
- webapp/components/user_settings/user_settings_notifications.jsx
- webapp/i18n/en.json
In Account Settings > Notifications > Words that trigger mentions, add `@here` to the list of channel wide mentions.
https://mattermost.atlassian.net/browse/PLT-6485
> PLT-6485 Add ability to disable `@here` notifications

- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- app/diagnostics.go
- app/file.go
- config/config.json
- model/config.go
- webapp/components/admin_console/storage_settings.jsx
Certain S3 compatible servers only use Legacy Signature (AWS
Signature V2), current code only supports signature v4.
This PR adds facility to click a button on the UI to enable
legacy signature with S3 compatible servers.
This is no ticket for this AFAIK. 
> Support AWS Signature V2 for Mattermost for S3 storage.

- api4/system.go
- api4/system_test.go
- config/config.json
- i18n/en.json
- model/client4.go
- model/config.go
[PLT-5465/APIV4] GET /system/health - Improve ping health check to have limits
returns OK if the running Goroutines is not over the defined settings otherwise return unhealthy
JIRA: https://mattermost.atlassian.net/browse/PLT-5465
GitHub: https://github.com/mattermost/platform/issues/6300
> [PLT-5465/APIV4] GET /system/health - Improve ping health check to have limits

- app/command.go
- app/notification.go
- app/oauth.go
- app/post.go
- app/webhook.go
- app/webrtc.go
- app/webtrc.go
- utils/httpclient.go
- utils/httpclient_test.go
This PR provides a single source of `http.Client` creation logic with internet proxy support, reasonable timeouts and optional insecure connections.
`utils.HttpClient` returns a variation the default implementation of `http.Client`.
It uses a `Transport` with the same settings as `DefaultTransport` but with the following modifications:
* shorter timeout for dial and TLS handshake (defined as constant  `connectTimeout`)
* timeout for the end-to-end request (defined as constant `requestTimeout`)
* skipping server SSL certificate check if specified in "config.json" via "ServiceSettings.EnableInsecureOutgoingConnections"
#6469  and [PLT-5705](https://mattermost.atlassian.net/browse/PLT-5705)
> PLT-5705 Create a single source of http.Client creation logic

- webapp/components/create_post.jsx
- webapp/stores/post_store.jsx
Fixed JS error when adding reaction to channel with latest post as ephemeral
- added `getLatestNonEphemeralPost` at post_store.jsx
- used it when saving reaction
GitHub issue: #6421
Jira ticket: [PLT-6586](https://mattermost.atlassian.net/browse/PLT-6586)
> [PLT-6586] Fixed JS error when adding reaction to channel with latest post as ephemeral

- webapp/stores/team_store.jsx
Ignore correct message types for setting unreads for teams. I couldn't reproduce it with channels but could with teams
https://mattermost.atlassian.net/browse/PLT-6658
> PLT-6658 Ignore correct message types for setting unreads for teams

- webapp/components/sidebar.jsx
This fixes two issues:
1. Do not sort favorite channels state in the render method, sort before setting state
2. Deep compare channels, prefs and profiles to make sure there are changes before trying to build the channel list for the sidebar
> Prevent re-rendering of sidebar when typing into quick switcher

- webapp/utils/text_formatting.jsx
Those tags are used to hint that the browser should do a line break on the slashes in URLs. Obviously, we don't want to encourage the browser to wrap the line in single line mode.
https://mattermost.atlassian.net/browse/PLT-6692
> PLT-6692 Removed wbr tags from single line markdown

- app/notification.go
- i18n/en.json
This fixes the existing message which attempts to print an empty DeviceId and adds an extra debug message for each of the user's sessions containing the actual DeviceIds
> Fixed debug message for push notifications

- webapp/components/suggestion/switch_channel_provider.jsx
Increase quick switcher perf by not storing server results. Storing the server results was causing a number of different components to re-render which could sometimes cause lag while typing.
> Increase quick switcher perf by not storing server results

- webapp/components/user_settings/user_settings_general/user_settings_general.jsx
Fix regression for LDAP users not showing email address. Then follow the same format for:
- Gitlab
- Google
- Office365
-SAML
Jira ticket: [PLT-6690](https://mattermost.atlassian.net/browse/PLT-6690)
> [PLT-6690] Fix regression for LDAP users not showing email address

- webapp/Makefile
- webapp/yarn.lock
Use mutex flag with yarn to prevent concurrent builds interfering. If two yarn commands were being on the same machine, they could cause interference. This interference could result in some packages having incorrect versions in webapp builds.
> Use mutex flag with yarn to prevent concurrent builds interfering

- config/README.md
Added `README.md` under `config` to specify what the `config.json` file is used for.
https://github.com/mattermost/platform/issues/6496
https://mattermost.atlassian.net/browse/PLT-6400
> [PLT-6400] Add README file to config directory

- webapp/components/suggestion/channel_mention_provider.jsx
I wasn't able to repro the lag locally, but this should stop the behaviour where the client lags after typing a ~.
https://mattermost.atlassian.net/browse/PLT-6070
> PLT-6070 Have ChannelMentionProvider stop searching after a term returns no results

- app/team.go
For team unreads return empty array instead of null when there are no teams.
https://mattermost.atlassian.net/browse/PLT-6834
> PLT-6834 For team unreads return empty array instead of null

- api4/apitestlib.go
- api4/websocket_test.go
Add `StopServer()` at the end of API v4 tests.
This is just a small fix hoping to narrow down real issue with random test failures during build.
The ticket specifically described issue with `TestIncomingWebhook`.
Jira ticket: [PLT-6694](https://mattermost.atlassian.net/browse/PLT-6694)
> [PLT-6694] Add StopServer() at the end of API v4 tests

- webapp/i18n/en.json
PR that changed /loadtest to /test: https://github.com/mattermost/platform/pull/6624
Docs PR: https://github.com/mattermost/docs/pull/1265
EDIT: Not sure why the build fails..
> Update help text after renaming /loadtest to /test

- webapp/components/post_view/components/post_body_additional_content.jsx
- webapp/components/post_view/components/post_image.jsx
- webapp/components/post_view/components/post_list.jsx
- webapp/components/youtube_video.jsx
- webapp/stores/scroll_store.jsx
- webapp/utils/markdown.jsx
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).
When filling in a section please remove the help text and the above text.
Remove fake img preview and collapse toggle before it is loaded,
only show img and toggle after it is fully loaded.
Fix markdown img size and add scroll down behaviour.
Issue: https://github.com/mattermost/platform/issues/5368
Jira: https://mattermost.atlassian.net/browse/PLT-5267
> PLT-5267: Remove fake img preview before loaded

- api4/system.go
- api4/system_test.go
- model/client4.go
Add GET /analytics/old endpoint for v4. Reserving /analytics for a new format with different functionality.
> Add GET /analytics/old endpoint for v4

- api4/system_test.go
- app/admin.go
Quick fix for getting logs displaying properly on pre-release.  This is similar to how the v3 api works.
I'll create a follow up tix to fix this correctly.
I created https://mattermost.atlassian.net/browse/PLT-6896
> Setting per-paging for logs to load 10K initially like the old apis

- api4/post_test.go
Couldn't find potential problem with intermittent failure of `TestGetPostsForChannel` encountered at CI server, aside from the timing at the test itself. This PR hopefully addressed the problem.
Jira ticket: [PLT-6750](https://mattermost.atlassian.net/browse/PLT-6750)
> [PLT-6750] Fix intermittent failure of TestGetPostsForChannel on CI server

- webapp/components/new_channel_modal/new_channel_modal.jsx
- webapp/components/search_results_item.jsx
- webapp/components/sidebar.jsx
- webapp/tests/components/__snapshots__/new_channel_modal.test.jsx.snap
This is the last PR for below Jira ticket. Included in this PR are:
10. DM/GM `More...` link in LHS to add a new DM/GM => set ID to 'moreDirectMessage'
11. Name of channel in search results in RHS (can be multiple various) => set ID to 'searchChannelNameX' where X is 0 to 9
12. Public channel `+` button in LHS to add new public channel => set ID to 'createPublicChannel'
13. Private channel `+` button in LHS to add new private channel => set ID to 'createPrivateChannel'
14. Public Channels `More...` link in LHS to view more public channels
15. Form fields in Add New Public Channel form
- Name => set ID to 'newPublicChannelName'
- Purpose => set ID to 'newPublicChannelPurpose'
- Header => set ID to 'newPublicChannelHeader'
16. Form fields in Add New Public Channel form
- Name => set ID to …
> add more Ids for UI automation

- app/channel.go
- model/websocket_message.go
- webapp/actions/websocket_actions.jsx
- webapp/utils/constants.jsx
This is a collaborative PR with @ruzette @jwilander 
This fix originally come from the @ruzette PR: https://github.com/mattermost/platform/pull/6360
When any update on the channel happens, we propagate the changes to all clients.
Jira: https://mattermost.atlassian.net/browse/PLT-5988
GitHub: https://github.com/mattermost/platform/issues/5834
Thanks for all @ruzette and @jwilander your support was really crucial to this 🎉
> [PLT-5988] when a channel is update propagate the channel to everybody

- webapp/components/sidebar_right_menu.jsx
`Leave Team` menu item was in a wrong position
JIRA: https://mattermost.atlassian.net/browse/PLT-6548
> PLT-6548 fix order in the RHS menu

- api/command_loadtest_test.go
- tests/README.md
- webapp/components/admin_console/developer_settings.jsx
Fix places where we still refer to "/loadtest"
> Fix places where we still refer to "/loadtest"

- api/command_settings_test.go
- app/command_settings.go
- i18n/en.json
- webapp/actions/channel_actions.jsx
- webapp/actions/global_actions.jsx
- webapp/components/needs_team/needs_team.jsx
- webapp/components/sidebar_header_dropdown.jsx
- webapp/components/sidebar_right_menu.jsx
- webapp/components/user_settings/user_settings_modal.jsx
- webapp/stores/modal_store.jsx
- webapp/utils/constants.jsx
/settings slash command: Open the Account Settings dialog
I believe this is the first slash command that performs only client-side operations. So what I've done is implement the command as usual, but the server-side execution only does one thing: result in an error saying the command is not supported by your device. The command is handled client-side and never sent to the server.
I have slight hesitations about this approach since it spreads out the command implementation, but there's at least some precedence for it with the "/shortcuts" command. The alternative would be a mechanism to enable the server to interact with the front-end (i.e. respond with a message saying "open the account settings"), but I don't think that's any better.
If this approach is reasonable, I'll be doing a very …
> PLT-6714: add /settings command

- api/command_join_test.go
- api/command_open_test.go
- app/command_open.go
- i18n/en.json
Add duplicate /open command for joining a new channel. The /open command should perform the same action as /join.
https://github.com/mattermost/platform/issues/6545
> PLT-6717: add /open command

- app/user.go
- model/user.go
Apply the Restrict account creation to specified email domains setting for GitLab/Google/Office365 SSO. If the restricted domain is set to "mattermost.com" then a user must have a GitLab/Google/Office365 account pointing to that domain when creating an account.
[![Demo](https://thumbs.gfycat.com/DisfiguredColorfulKentrosaurus-size_restricted.gif)](https://gfycat.com/DisfiguredColorfulKentrosaurus)
I also simplified some surrounding code.
https://github.com/mattermost/platform/issues/5356
> PLT-3744: verify domain for oauth user creation

- api4/post.go
- api4/post_test.go
- app/post.go
Fix permission app error when updating post where UserId is missing on post body.
Note that the `PUT /post/{post_id}` endpoint for v4 is initially intended for the entire post where full post information is expected from the request body including `UserId`. However, since `UserId` is not allowed to be changed, the `UserId` information is from the `oldPost` and not from the request body. That's why the condition check is removed as it seemed to be unnecessary.
For partial post update, it is always encourage to use `PUT /post/{post_id}/patch`.
GitHub issue: #6742 
> [GH-6742] Fix permission app error with updatePost

- webapp/actions/user_actions.jsx
- webapp/components/user_settings/user_settings_advanced.jsx
- webapp/components/user_settings/user_settings_display.jsx
Fix JS errors in saving preferences - for user's display (including custom theme vector) and advanced settings.
The Jira ticket was initially addressed by PR #6734 but the change was affected by the recent PR #6720 
Jira ticket: [PLT-6898](https://mattermost.atlassian.net/browse/PLT-6898)
> [PLT-6898] Fix JS errors in saving preferences - for user's display (including custom theme vector) and advanced settings

- webapp/components/post_view/post_info/post_info.jsx
- webapp/utils/post_utils.jsx
Hide DotMenu container when DotMenu is empty.
https://mattermost.atlassian.net/browse/PLT-6900
> PLT-6900: Hide DotMenu container when DotMenu empty.

- webapp/tests/utils/formatting_hashtags.test.jsx
- webapp/tests/utils/formatting_links.test.jsx
- webapp/utils/text_formatting.jsx
These were added originally to help break long links up across lines, but they kept being inserted in places we didn't want them. Other services (Github, Slack, etc) don't bother with them, so I removed the behaviour.
https://mattermost.atlassian.net/browse/PLT-6799
> PLT-6799 Removed <wbr> tags from markdown links

- api4/team.go
- api4/team_test.go
- api4/user_test.go
- app/team.go
- i18n/en.json
- store/sql_team_store.go
- webapp/components/signup/signup_controller.jsx
API v4 currently overwrites the error messages passed back by the app and DB layers, so I removed those and added status codes to any relevant calls.
If anyone can figure out what status code should be used for the "you can't join the team because it's at the max number of members" error, let me know and I'll add that
> Fixed error information being obscured when joining teams with API v4

- webapp/actions/notification_actions.jsx
- webapp/i18n/en.json
add attachments notification. (if webhook is attachments only.)
1) fallback text
2) pre-text
3) text
4) "posted an image" if there is an image URL
5) "did something new"
- [PLT-3038](https://mattermost.atlassian.net/browse/PLT-3038)
- #6465
> [PLT-3038] Update notification for webhooks sending attachments

- webapp/utils/markdown.jsx
Regression: Code tag is empty for html code blocks
Jira: https://mattermost.atlassian.net/browse/PLT-6796
Github: https://github.com/mattermost/platform/issues/6772
> [PLT-6796] Regression: Code tag is empty for html code blocks

- tests/test-links.md
Some tests used default ports which didn't show up in the address bar (so were reported as incorrect) and then some included the use of basic HTTP authentication which is no longer supported by some major browsers (ie Chrome)
https://mattermost.atlassian.net/browse/PLT-6813
> PLT-6813 Removed misleading and outdated link tests

- webapp/components/markdown_image.jsx
- webapp/components/post_view/post_message_view/post_message_view.jsx
- webapp/tests/utils/formatting_imgs.test.jsx
- webapp/utils/markdown.jsx
This is to allow for better control over inline markdown images so that we can fix the scroll pop caused by them.
The height changing code from `window.markdownImageLoaded` didn't appear to do anything when I posted test-markdown-basics.md, so I didn't bother porting it over.
> Added MarkdownImage component

- glide.lock
- glide.yaml
- vendor/github.com/mattermost/gorp/.gitignore
- vendor/github.com/mattermost/gorp/gorp.go
- vendor/github.com/mattermost/gorp/select.go
- webapp/components/admin_console/database_settings.jsx
- webapp/i18n/en.json
The postgres driver fixed the issue with context cancellation. This updates our fork of gorp to allow query timeouts to occur on postgres. My lock file likes to do weird things whenever I use glide but I don't think that should matter since we check in the vendor directory
> Update gorp to support query timeouts on postgres

- webapp/actions/file_actions.jsx
- webapp/components/file_upload.jsx
This is to fix the ability to cancel in-progress file uploads since fetch used by fetch doesn't support cancelling requests. It should still interact with the redux store just like the action in mattermost-redux
https://mattermost.atlassian.net/browse/PLT-6844
> PLT-6844 Change file uploading to use superagent

- webapp/stores/channel_store.jsx
Remove unneeded return and add logging for marking channels unread. If we ever see the logging then we can be pretty confident that this was the issue.
The removed `this.unreadCounts[id].mentions++;` had no effect since changing the channel member results in `this.unreadCounts` getting immediately recalculated.
> Remove unneeded return and add logging for marking channels unread

- api4/emoji_test.go
- store/sql_emoji_store.go
One of the unit tests randomly fails because it deletes an emoji and then checks for a 404. I assume that's causing some sort of caching thing because it's not being removed from the cache
https://mattermost.atlassian.net/browse/PLT-6909
> PLT-6909 Remove deleted emojis from cache

- api4/team_test.go
- app/team.go
- i18n/en.json
- webapp/components/invite_member_modal.jsx
When using the "Send Email Invite" functionality. Emails were sent to domains that were not on the `RestrictCreationToDomains` list. This would lead to users getting a message that they can't create an account if they follow the link in the email.
This commit will check the email addresses before the mails are sent and warn the user typing them in which ones are blocked.
**note**: is this accepted as a "small contribution" under the current guidelines? Before I read the CLA 😄 
https://mattermost.atlassian.net/browse/PLT-5639
> [PLT-5639] Show a message when invited addresses are blocked

- app/command.go
- i18n/en.json
- webapp/components/create_post.jsx
If a message starts with a / but is not a slash command, put the text back in the input box when it fails to send
JIRA: https://mattermost.atlassian.net/browse/PLT-6847
Github: https://github.com/mattermost/platform/issues/6659
> [PLT-6847] If a message starts with a / but is not a slash command, put the text back in the input box when it fails to send

- app/command_invite_people.go
- i18n/en.json
Returns error `User creation has been disabled on this server, no invite(s) sent` when `TeamSettings.EnableUserCreation` is set to `false` and user attempts to `/invite_people`
[Jira Ticket](https://mattermost.atlassian.net/browse/PLT-6882)
[PLT-6882](https://github.com/mattermost/platform/issues/6698)
> PLT-6882 Disable /invite_people when account creation is set to false

- webapp/components/integrations/components/add_command.jsx
- webapp/components/integrations/components/edit_command.jsx
Before: Creating a slash command as a System Admin throws a permission error
After: It works
https://mattermost.atlassian.net/browse/PLT-6953
> PLT-6953: fix slash command add / edit front-ends

- api4/api.go
- api4/elasticsearch.go
- api4/elasticsearch_test.go
- app/elasticsearch.go
- einterfaces/elasticsearch.go
- i18n/en.json
- model/client4.go
Adds an API endpoint to test the elasticsearch config.
https://mattermost.atlassian.net/browse/PLT-6474
> PLT-6474: Server: Add elasticsearch/test endpoint to API.

- api4/user.go
- api4/user_test.go
- app/analytics.go
- i18n/en.json
- model/client4.go
- store/sql_user_store.go
- store/sql_user_store_test.go
- store/store.go
Add some basic sorting support for GET /users endpoint. This is to cover some functionality needed for a few screens in the system console. This can also be the basis for possibly allowing more advanced sorting in the future.
This also fixes a couple minor bugs.
https://mattermost.atlassian.net/browse/PLT-6906
> PLT-6906 Add some basic sorting support for GET /users endpoint

- app/command_join.go
Fix channel join slash command. Don't show an ephemeral message when the channel join succeeds. Just redirect to the channel.
https://mattermost.atlassian.net/browse/PLT-6951
> PLT-6951: Fix channel join slash command.

- webapp/utils/constants.jsx
Fix collapsed image preview that doesn't stay collapsed after posting a message in the channel by temporarily setting the `TEST_COUNT_ID` from 10 to 0.
The setting 10 makes the last 10 posts re-render every time a new message is posted even if `post` object of those were unchanged (only the `lastPostCount` changed).
Maybe we need to consider to move the TEST_COUNT_ID to System Console > Developer Setting so it can be configurable depending on Selenium test requirement.
Jira ticket: [PLT-6949](https://mattermost.atlassian.net/browse/PLT-6949)
> [PLT-6949] Fix collapsed image preview that doesn't stay collapsed after posting a message in the channel

- webapp/components/suggestion/switch_channel_provider.jsx
Make channel switcher partially obey RestrictDirectMessage setting. If you have multiple teams and previously loaded users, they will still show up regardless of the setting. If the user is only on a single team it should work as expected.
https://mattermost.atlassian.net/browse/PLT-6867
> PLT-6867 Make channel switcher partially obey RestrictDirectMessage setting

- webapp/package.json
- webapp/yarn.lock
IE and Edge were broken in a recent release of redux-persist that we upgraded to. This upgrades to the release including their fix for the issue.
https://mattermost.atlassian.net/browse/PLT-6926
> PLT-6926 Fix IE and Edge by upgrading redux-persist

- api4/channel.go
- api4/channel_test.go
- i18n/en.json
- webapp/components/channel_header.jsx
- webapp/components/delete_channel_modal.jsx
- webapp/components/navbar.jsx
- webapp/utils/channel_utils.jsx
Restrict channel delete option per permission policy even for last channel member
Jira ticket: [PLT-6838](https://mattermost.atlassian.net/browse/PLT-6838)
> [PLT-6838] Restrict channel delete option per permission policy even for last channel member

- webapp/components/post_view/post_body/post_body.jsx
- webapp/components/post_view/post_body_additional_content.jsx
- webapp/components/post_view/post_list.jsx
Fix some scrolling issues. Also fixed an issue where if a user had link previews turned on and then they got turned off by the system admin, the client would get 501s trying to pull opengraph data from the server.
https://mattermost.atlassian.net/browse/PLT-6984
> PLT-6984 Fix some scrolling issues

- app/file.go
Turns out that integers and floats are easy to mix up
https://mattermost.atlassian.net/browse/PLT-6975
> PLT-6975 Fixed image thumbnail size being calculated incorrectly

- config/config.json
- model/config.go
Change config.json default for teammate name display setting to `username`, unless you have LDAP/SAML enabled in which case the default is `full_name`
Note: PR has been submitted on top of https://github.com/mattermost/platform/pull/6809 to avoid similar merge conflicts.
> Teammate name display setting: username as default or full_name when LDAP/SAML is enabled

- api4/elasticsearch.go
- app/elasticsearch.go
- einterfaces/elasticsearch.go
- i18n/en.json
Add optional config parameter to test elasticsearch endpoint to allow testing config without clobbering the actual config.
https://mattermost.atlassian.net/browse/PLT-6474
> Add optional config parameter to test elasticsearch endpoint.

- webapp/components/signup/components/signup_email.jsx
`SignupEmail.getInviteInfo` made some assignments that had no effect. The callback functions appeared to be trying to set the state, but were doing so by modifying some function local variables rather than by using `setState`, which made them ineffective.
I've changed this to instead use `setState`, and, if we are relying on callbacks, to set `state.loading` to `true` whilst the requests are in flight. I believe that this fixes a minor bug:
In master, specifying a bad invite id just directs to the standard signup form:
With this change, it instead displays a relevant error message:
This result was found on https://lgtm.com/projects/g/mattermost/platform/alerts/. (Full disclosure: I work on lgtm.com)
> Fix for SignupEmail invite handling

- webapp/components/post_view/post_list.jsx
Only show unreads below indicator after first load is complete. I wasn't able to reliably reproduce the bug but this should alleviate the problem either way. We can reopen the ticket if it still occurs after this gets merged.
https://mattermost.atlassian.net/browse/PLT-6925
> PLT-6925 Only show unreads below indicator after first load is complete

- webapp/actions/post_actions.jsx
- webapp/actions/websocket_actions.jsx
Reverts mattermost/platform#6881.
After having a quick run with this PR merged, I've got JS error on getProfilesAndStatusesForPosts (see screenshots).
I'm reverting this PR and will queue for next v4.0.0-rc3.
> Revert "PLT-7039 Use loadProfilesAndStatusesForPosts from the redux library"

- app/file.go
- webapp/components/file_preview.jsx
- webapp/components/setting_picture.jsx
- webapp/package.json
- webapp/yarn.lock
Uploaded images were previously failing to respect EXIF orientation, such as in photos taken on mobile devices.
- Used client-side EXIF data to rotate profile picture thumbnails
- Added a small package for correctly translating EXIF orientation into CSS transforms
- Instead of displaying the image using FileReader, used URL.createObjectURL because it is faster
- For upload thumbnails, the original behavior was scaling the entire original image, without accounting for EXIF rotate. I changed this to use the preview image, which does respect rotation.
- The preview image was not available when the upload request returned, because handling the preview image creation was in a goroutine. I used sync.WaitGroup to block until the preview image creation is done. …
> PLT-6659 Fixed upload thumbnails that weren't properly rotated

- cmd/platform/channel.go
- Fix the error messages int he cmd archive to use the archive wording.
- Also, refactor the store the use the Delete name but in fact, just archive, change the name to avoid misunderstandings.
@jasonblais @coreyhulen maybe we also can change the db field name deletedAt to be archievedAt. what do you guys think?
N/A
> Fix archive messages

- webapp/sass/components/_webrtc.scss
Fix extra whitespace between search bar and "@" icon in channel header after expanding the right-hand side
Jira ticket: [PLT-7001](https://mattermost.atlassian.net/browse/PLT-7001)
> [PLT-7001] Fix extra whitespace between search bar and "@" icon in channel header after expanding the right-hand side

- webapp/actions/post_actions.jsx
- webapp/reducers/views/channel.js
Deleting the focused post now sends user to normal channel view instead of getting stuck on a loading screen.
https://mattermost.atlassian.net/browse/PLT-7028
> PLT-7028 Deleting the focused post now sends user to normal channel view

- webapp/components/post_view/post_body_additional_content.jsx
Show expand button when previews defaulted to collapsed.
https://mattermost.atlassian.net/browse/PLT-7076
> PLT-7076 Show expand button when previews defaulted to collapsed

- webapp/actions/global_actions.jsx
- webapp/components/leave_team_modal.jsx
- webapp/components/sidebar_right_menu.jsx
Fix "Mobile web view: UX after leaving a team is confusing" by creating a global action to close sidebar right menu. Hit such action when leaving a team.
Jira ticket: [PLT-7060](https://mattermost.atlassian.net/browse/PLT-7060)
> [PLT-7060] Create global action to close sidebar right menu and hit it when leaving a team

- model/command_response.go
- model/command_response_test.go
- model/incoming_webhook.go
- model/incoming_webhook_test.go
- model/slack_attachment.go
- model/slack_attachment_test.go
Ignores null values in attachments. This emulates Slack behavior.
https://mattermost.atlassian.net/browse/PLT-7077
https://github.com/mattermost/platform/issues/6873
> PLT-7077: ignore null array items in slack attachments

- webapp/sass/layout/_headers.scss
- webapp/sass/layout/_sidebar-right.scss
- webapp/sass/responsive/_desktop.scss
PLT-7098 - Back arrow cut off in sidebar
PLT-7089 - Fixing channel name truncation
https://mattermost.atlassian.net/browse/PLT-7098
https://mattermost.atlassian.net/browse/PLT-7089
> Release 4.0 bug fixes

- model/client4.go
So the loadtests don't fail when the server is unreachable over HTTP.
> Fixing client4 ping

- webapp/yarn.lock
As I stated in my mattermost-redux PR, some routes return `{posts: null, ...}` which we weren't handling correctly
https://mattermost.atlassian.net/browse/PLT-7092
> PLT-7092 Updated mattermost-redux so getProfilesAndStatusesForPosts handles null

- webapp/sass/layout/_headers.scss
PLT-7101 - Reducing LHS header font size
https://mattermost.atlassian.net/browse/PLT-7101
> PLT-7101 - Reducing LHS header font size

- webapp/components/emoji_picker/emoji_picker_overlay.jsx
- webapp/components/rhs_comment.jsx
- webapp/components/rhs_root_post.jsx
- webapp/components/rhs_thread/rhs_thread.jsx
This still doesn't work 100% on screen sizes under ~550px tall. I'm planning a more thorough rewrite in 4.1 since react-overlays fails hard when there's not enough space to display an overlay in the exact position it wants
https://mattermost.atlassian.net/browse/PLT-7062
> PLT-7062 Moved emoji picker in RHS to attach to the body of the page

- api/channel.go
- store/sql_channel_store.go
- store/sql_post_store.go
As discussed in the dev meeting, these were the places I found where we were sometimes having a null PostList.Posts field that was being sent back to the client
https://mattermost.atlassian.net/browse/PLT-7092
> PLT-7092 Fixed creation of PostList with null Posts fields

- webapp/package.json
- webapp/yarn.lock
Escaping wasn't working correctly inside of an email link using angle brackets like `<noreply@example.com>` which caused problems when `html-to-react` went to render it into React components. This is also making me want to get commonmark used in the web app sooner than later. I remember seeing some other edge cases where marked didn't escape HTML entities, and that has me a bit worried that there's others that we're missing.
Changes to marked here: https://github.com/mattermost/marked/commit/c0b5f4a651b0af63e974522b20b93b7999490c53
https://mattermost.atlassian.net/browse/PLT-7133
- Added or updated unit tests (see changes to marked)
> PLT-7133 Updated marked to fix escaping of autolinked email addresses

- app/saml.go
- webapp/package.json
- webapp/yarn.lock
Manually loading the config during SAML certificate upload was conflicting with the config watcher routine and causing a crash. I removed the manual load call, the watcher will pick up any saved changes. Also stopped version checking on the SAML, config and logs endpoint on the client.
Has minor enterprise changes mattermost/enterprise#164
https://mattermost.atlassian.net/browse/PLT-7126
> PLT-7126 Do not version detect on saml endpoints and remove config reloading

- api4/elasticsearch.go
- api4/elasticsearch_test.go
- app/elasticsearch.go
- einterfaces/elasticsearch.go
- i18n/en.json
- model/client4.go
Adds an APIv4 Endpoint to purge Elasticsearch indexes.
https://mattermost.atlassian.net/browse/PLT-6595
> PLT-6595: API to purge Elasticsearch indexes.

- webapp/components/post_view/post/post.jsx
- webapp/components/rhs_comment.jsx
- webapp/components/rhs_root_post.jsx
- webapp/components/search_results_item.jsx
- webapp/components/suggestion/at_mention_provider.jsx
- webapp/components/suggestion/search_user_provider.jsx
- webapp/components/suggestion/switch_channel_provider.jsx
- webapp/components/user_profile.jsx
- webapp/components/user_settings/user_settings_general/user_settings_general.jsx
- webapp/components/webrtc/components/webrtc_notification.jsx
- webapp/components/webrtc/webrtc_controller.jsx
- webapp/utils/channel_intro_messages.jsx
- webapp/utils/post_utils.jsx
- webapp/utils/utils.jsx
The ticket was created because there were apparently a lot of `GET .../users/<id>/image?time=undefined` requests in the logs.
The `time` parameter is not read by any application logic, and was originally added to prevent unwanted caching (see https://github.com/mattermost/platform/commit/c3aed620316241eba48ecd2fd1f36a309bcfdff9). The desired behavior is for the requested query string to change iff the requested image has changed. So when available, the user's `LastPictureUpdate` is placed in the query string. If the user has never updated their picture, `0` is placed in the query string. If we're not able to determine when the user's picture was last updated, we send an arbitrary number to ensure that we don't get cached results (This case is rare and for the sake of performance should be …
> PLT-6689: fix user image requests

- app/slackimport.go
- app/slackimport_test.go
Fix Slack Import of non-ascii channel names.
https://mattermost.atlassian.net/browse/PLT-6971
> PLT-6971: Fix Slack Import of non-ascii channel names.

- webapp/Makefile
Jenkins is now configured to use a local yarn cache in the workspace for each job, so there should be no interaction between different jobs running on the same server.
This removes the global mutex to simplify the interaction between parallel builds, as it is now no longer needed.
~~DO NOT MERGE UNTIL SOME BUILDS HAVE SUCCEEDED WITH THE NEW YARN CACHE DIRECTORY~~
OK, I think this is good to merge now.
> Remove systemwide mutex from Yarn commands.

- webapp/components/user_settings/user_settings_general/user_settings_general.jsx
Failed client-side validation didn't clear previously displayed server-side errors.
I'm really not even sure why `SettingItemMax` is designed to be able to display both types of errors at once. They seem like they should always be mutually exclusive.
https://mattermost.atlassian.net/browse/PLT-7079
N/A
> PLT-7079: fix uncleared server errors in user settings

- app/command_code.go
- app/command_code_test.go
- i18n/en.json
/code [text] slash command: Display the text as a code block
https://mattermost.atlassian.net/browse/PLT-6706
> PLT-6706: add /code command

- api4/command.go
- webapp/components/create_comment.jsx
- webapp/components/create_post.jsx
Reverts DM slash commands to pre-4.0 behavior.
That is, you can use slash commands for the team that you currently have selected in the UI.
https://mattermost.atlassian.net/browse/PLT-7193
N/A
> PLT-7193: Fix DM custom slash command regression

- Makefile
I made it do a simple build to act more like the Makefiles for other projects. I considered having it `make run` by default, but that runs background processes which may catch some people off guard
> Changed default Makefile target

- app/elasticsearch.go
- app/post.go
- config/config.json
- i18n/en.json
- jobs/workers.go
- model/config.go
- utils/config.go
- webapp/components/admin_console/elasticsearch_settings.jsx
Fix capitalisation of Elasticsearch in Config.
This nukes the existing ElasticSearch settings from the config. This is OK, because although those settings have been present in previous releases, they have never previously actually done anything.
https://mattermost.atlassian.net/browse/PLT-7040
> PLT-7040: Fix capitalisation of Elasticsearch in Config.

- app/team.go
- model/websocket_message.go
- webapp/actions/websocket_actions.jsx
- webapp/stores/team_store.jsx
- webapp/utils/constants.jsx
When user A (admin) updates user B's role, user B's dropdown menu is updated to reflect the change without needing a refresh. 
Github issue #6645
> [PLT-6842] Added websocket event and webapp handler for updating user roles

- webapp/yarn.lock
Updated yarn.lock to point to latest mattermost-redux webapp-4.0 addressing issue of cannot login when `user.locale` is empty 
- https://github.com/mattermost/mattermost-redux/pull/209
Jira ticket: [PLT-7231](https://mattermost.atlassian.net/browse/PLT-7231)
> [PLT-7231] Point mattermost-redux to webapp-4.0 latest addressing issue with Gitlab SSO login

- webapp/actions/channel_actions.jsx
- webapp/actions/global_actions.jsx
- webapp/yarn.lock
This change is needed for error handling on the RN app. The web app also wasn't handling how `createDirectChannel` returned data correctly, so I fixed that as well
mattermost-redux PR: https://github.com/mattermost/mattermost-redux/pull/207
https://mattermost.atlassian.net/browse/RN-152
> RN-152 Updated createGroupChannel's return value to match createDirectChannel

- webapp/package.json
- webapp/yarn.lock
This fixes empty table cells rendering correctly and whitespace at the beginning and end of a code block being trimmed away
Marked changes to whitespace being trimmed from code blocks: https://github.com/mattermost/marked/commit/cd82cf9e4d1b1a8bcfc1389e9d2f13ac7800e541
- Stop trimming lines that are just whitespace
- Adjusts boundaries of indented code blocks and horizontal rules to account for previous change
- Adjusts the boundaries of what gets captured by fenced code blocks
- Adds some unit tests where whitespace is actually checked
Marked changes to fix table cell parsing: https://github.com/mattermost/marked/commit/186e3ea2a009979d251ef9fb1ca8b333f27fb11f
- Fixed detection of columns while still allowing escaping of pipes
https://mattermost.atlassian.net/browse/PLT-7032 …
> PLT-7032/PLT-7155 Updated marked to fix empty table cells and code block whitespace

- api/user.go
- api4/oauth.go
- app/oauth.go
When logging in using SAML or OAuth from mobile we need to return a JSON object instead of redirecting to any page
> If login is using mobile respond with JSON object

- app/user_test.go
Fix TestCreateOAuthUser unit test. If the random int was 0 then the test would fail.
https://mattermost.atlassian.net/browse/PLT-6994
> PLT-6994 Fix TestCreateOAuthUser unit test

- webapp/actions/global_actions.jsx
- webapp/components/at_mention/at_mention.jsx
- webapp/components/create_comment.jsx
- webapp/components/create_post.jsx
- webapp/components/post_view/post/post.jsx
- webapp/components/post_view/post_body/post_body.jsx
- webapp/components/post_view/post_header/post_header.jsx
- webapp/components/post_view/post_message_view/post_message_view.jsx
- webapp/components/profile_picture.jsx
- webapp/components/profile_popover.jsx
- webapp/components/rhs_comment.jsx
- webapp/components/rhs_root_post.jsx
- webapp/components/suggestion/suggestion_box.jsx
- webapp/components/textbox.jsx
- webapp/components/user_profile.jsx
- webapp/stores/search_store.jsx
- webapp/stores/suggestion_store.jsx
- webapp/utils/channel_intro_messages.jsx
Click the @username mention on the profile popover title. A mention for `@username` should be added to your post draft:
https://mattermost.atlassian.net/browse/PLT-6485
> PLT-6486 Add an `@username` button to the profile popover, that puts the username in the post when clicked

- webapp/components/login/login_controller.jsx
Uses `Client4.getOAuthUrl` instead of `Client4.getUrl() + /oauth/...` in the login controller, to avoid future breakage and so it is consistent with what is used in the signup_controller.
No ticket.
Nothing I think(?)
> Make login_controller consistent with signup_controller by using Client4.getOAuthRoute

- app/command_away.go
- app/command_offline.go
- app/command_online.go
Repro steps:
1) Type `/away asdf`
Observed: The ephemeral message posted is "asdf You are now away". This also happens for `/online` and `/offline`
Expected: The remaining text is not added to the beginning of the ephemeral message
https://mattermost.atlassian.net/browse/PLT-7227
> PLT-7227: fix away/offline/online commands repeating user message

- webapp/components/view_image.jsx
Prevent ViewImageModal to re-render when file count is unchanged. This addresses the issue of: 
- Image preview modal switches to loading gif if post finishes sending with modal open
Jira ticket: [PLT-7020](https://mattermost.atlassian.net/browse/PLT-7020)
> [PLT-7020] Prevent ViewImageModal to re-render when file count is unchanged

- app/channel.go
- app/channel_test.go
- app/team.go
- app/team_test.go
- i18n/en.json
- store/sql_command_store.go
- store/sql_command_store_test.go
- store/sql_webhook_store.go
- store/sql_webhook_store_test.go
- store/store.go
When doing a PermanentDelete of a team using the CLI, it removed members, channels and posts, but not Commands and Webhooks. Now it removes those too.
https://mattermost.atlassian.net/browse/PLT-7214
https://mattermost.atlassian.net/browse/PLT-7215
> PLT-7214: make cli team / channel delete operations also delete webhooks and slash commands

- app/diagnostics.go
- model/config.go
Add elasticsearch settings to diagnostics.
PR also has changes from PLT-7040 included in it until that is merged, so just ignore them.
https://mattermost.atlassian.net/browse/PLT-6961
> PLT-6961: Add elasticsearch settings to diagnostics.

- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- app/file.go
- model/config.go
This is necessary for certain users where
GetBucketLocation API is disabled using IAM
policies. There is a field AmazonS3Region
which we need to re-purpose and use to support
this properly.
Fixes https://github.com/mattermost/platform/issues/6999
> Allow regions to be set and honored for S3 driver.

- api/context.go
- api/post.go
- api4/context.go
- api4/params.go
- api4/post.go
- api4/post_test.go
- api4/user.go
- api4/user_test.go
- app/session.go
- app/user.go
- config/config.json
- i18n/en.json
- model/authorization.go
- model/client4.go
- model/config.go
- model/session.go
- model/user_access_token.go
- model/user_access_token_test.go
- store/layered_store.go
- store/sql_store.go
- store/sql_supplier.go
- store/sql_user_access_token_store.go
- store/sql_user_access_token_store_test.go
- store/store.go
- utils/config.go
* Adds a model and store for user access tokens
* Adds four APIv4 endpoints for creating, deleting and getting user access tokens
* Adds a new config setting to enable user access tokens
* When config setting is set sessions can now be created from valid user access tokens for active users
* Disabling config setting deauthorizes (but does not delete) existing user access token sessions
* Added three new permissions for user access tokens and one for posting in public channels
* Added two new system-level roles, one for user access token access and another for posting in public channels
* Added one new team-level role, for posting in public channels
* Updated permission on createPost API handlers to handle new public posting permission (@crspeller we might want to run a load test on this …
> PLT-6763 Implement user access tokens and new roles (server-side)

- app/post.go
PLT-6603: Don't return all posts on invalid query.
If the query contains only * or invalid punctuation only components,
don't return all posts - instead return no results.
This also fixes PLT-6608
https://mattermost.atlassian.net/browse/PLT-6603
https://mattermost.atlassian.net/browse/PLT-6608
> PLT-6603: Don't return all posts on invalid query.

- webapp/components/change_url_modal.jsx
- webapp/components/rename_channel_modal.jsx
- webapp/i18n/en.json
- webapp/utils/constants.jsx
When creating a new channel it allows only 22 characters but when editing it allows to enter 64:
Channel name length restrictions are enforced right now with fixed values like 22 or 64 in files like:
webapp/components/change_url_modal.jsx
webapp/components/rename_channel_modal.jsx
webapp/i18n/en.json
Also it's not consistent between files. It should use constant `Constants.MAX_CHANNELNAME_LENGTH` that is set to 22 (Confirmed with @jasonblais that it's right).
> Use Constants.MAX_CHANNELNAME_LENGTH where a fixed number like 22 or 64 is used for max length of channel names.

- webapp/components/post_view/post_info/index.js
- webapp/components/rhs_thread/rhs_thread.jsx
- webapp/components/search_results.jsx
Consider the existence of a flagged post preference as indicating a post is flagged, regardless of the preference value.
https://mattermost.atlassian.net/browse/PLT-7137
#6715
> PLT-7137 Show flagged posts consistently throughout the UI

- webapp/utils/constants.jsx
Fix JS error on handleViewAction due to missing POST_UPDATED constant for socket events
- that should have been added to this commit https://github.com/mattermost/platform/commit/58c6a70d3e225fcc423d4f0ee9316150e097b2c2 
- such socket event is used to propagate changes (to center view) when post is edited at RHS's search results
Jira ticket: [PLT-7236](https://mattermost.atlassian.net/browse/PLT-7236)
> [PLT-7236] Fix JS error on handleViewAction due to missing POST_UPDATED constant for socket events

- webapp/components/emoji_picker/components/emoji_picker_item.jsx
- webapp/make-emojis
- webapp/sass/components/_emojisprite.scss
I'm not sure why Chrome on certain platforms (Windows, Ubuntu) didn't like each `.emoji-####` CSS class having its background image URL set, so I moved the background image URLs into their own classes that are applied separately to avoid the duplication.
https://mattermost.atlassian.net/browse/PLT-7262
> PLT-7262 Stopped including emoji sprite sheets multiple times in CSS

- webapp/components/popover_list_members/popover_list_members.jsx
Modified channel member dropdown list to show user name, as defined by display settings, rather than full name
https://mattermost.atlassian.net/browse/PLT-7238
> PLT-7238: In channel member dropdown list, only show the name (fullname/nickname/username) used elsewhere in the UI

- app/diagnostics.go
- config/config.json
- model/config.go
This is the "quick" part of the fix for PLT-7275. It'll be enough to get 1,000 days of search history working with Elasticsearch in it's default/AWS config. System console UI for these two settings will come in a subsequent PR.
@jasonblais this adds two new config values to the diagnostics, so requesting your review on them.
https://mattermost.atlassian.net/browse/PLT-7275
> PLT-7275: Configure replica/shard count for Elasticsearch indexes.

- cmd/platform/user.go
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).
When filling in a section please remove the help text and the above text.
Fixed typo preventing deleteall command from working as expected. Cleaned up spelling and error messages throughout the user module
https://mattermost.atlassian.net/browse/PLT-7145
https://github.com/mattermost/platform/issues/6925
> PLT-7145: `platform user deleteall` expects a user as argument

- webapp/actions/integration_actions.jsx
Do not show non-autocomplete commands for system admins (and other users too but the server won't return them for those users anyways).
https://mattermost.atlassian.net/browse/PLT-7249
> PLT-7249 Do not show non-autocomplete commands for system admins

- webapp/stores/team_store.jsx
Fix teams being incorrectly marked unread across tabs when the logged in user posts.
https://mattermost.atlassian.net/browse/PLT-6683
> PLT-6683 Fix teams being incorrectly marked unread across tabs

- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- app/file.go
- model/config.go
This is necessary for certain users where
GetBucketLocation API is disabled using IAM
policies. There is a field AmazonS3Region
which we need to re-purpose and use to support
this properly.
Fixes https://github.com/mattermost/platform/issues/6999
> Allow regions to be set and honored for S3 driver. (#7010)

- app/webhook_test.go
- model/command_response.go
- model/incoming_webhook.go
- model/slack_attachment.go
- model/slack_attachment_test.go
I broke webhook and command attachments (just on master, not in any releases).
The bad commit was merged here: https://github.com/mattermost/platform/pull/6904
I made an initial commit `ignore null array items in incoming webhooks / command responses`. But after doing my manual testing, I made another commit `make a bit more idiomatic, add tests` in which I added a named type `SlackAttachments`. This breaks things because we insert objects of this type into a `map[string]interface{}` and later read them out via...
```go
if attachments, success := val.([]*model.SlackAttachment); success {
parseSlackAttachment(post, attachments)
}
```
I'm fixing this by removing the named type for now.
I'll be sure to make less assumptions about our type-safety in the future, but as far as I've seen, …
> PLT-7212: fix missing webhook post attachments

- api/file.go
- api4/file.go
As it turns out, IE11 refuses to display images when the `X-Content-Type-Options` header is set to `nosniff` and their content type header doesn't match the actual type of the file.
https://mattermost.atlassian.net/browse/PLT-7261
> PLT-7261 Fixed incorrect content type for preview and thumbnail images

- webapp/components/file_attachment_list/file_attachment_list.jsx
- webapp/components/file_preview.jsx
- webapp/components/file_upload.jsx
- webapp/utils/utils.jsx
Improve ordering of uploaded attachments
- uploadfiles based on alphabetical order when multiple files are selected.
- show/preview files based on the time they are attached.
Jira ticket: [PLT-2407](https://mattermost.atlassian.net/browse/PLT-2407)
> [PLT-2407] Improve ordering of uploaded attachments

- webapp/components/post_view/post_attachment.jsx
Previously, webhooks would get truncated to 5 lines _or_ 700 characters. Now they get truncated to 5 lines _and 300_ characters.
https://mattermost.atlassian.net/browse/PLT-7230
https://mattermost.atlassian.net/browse/PLT-7263
> PLT-7230: fix some webhook attachments not truncating, limit short text to 300 chars

- i18n/en.json
- utils/config.go
- utils/config_test.go
Make MM config locales more forgiving by assigning default values
- if `DefaultServerLocale` is set to empty string or unsupported language/unknown string, it will be set to `en` as default value.
- if `DefaultClientLocale` is set to empty string or unsupported language/unknown string, it will be set to `en` as default value.
- if `AvailableLocales` has unsupported language/unknown string included, it will be set to empty string ("") as default value which means set to all available language supported by MM.
- `DefaultServerLocale` will be added to `AvailableLocales` when not available.
- `DefaultClientLocale` will be added to `AvailableLocales` when not available.
Jira ticket: [PLT-7306](https://mattermost.atlassian.net/browse/PLT-7306) & …
> [PLT-7231/PLT-7306] Fix GitLab SSO failure with non-English locale and make config locales more forgiving

- webapp/yarn.lock
Bump yarn.lock to have mattermost-redux#master/e5297912f528b822b61c61a36735fb4d6699d08d
- latest commits are critical for v4.1
> bump mattermost-redux#e529791 at yarn.lock

- webapp/components/search_bar.jsx
If the search submitted is empty, don't start the animation in the searchbar.
https://mattermost.atlassian.net/browse/PLT-7311
> PLT-7311 Don't allow empty search in searchbar.

- api4/file_test.go
- model/client4.go
These are the unit tests I wrote a while back for https://mattermost.atlassian.net/browse/PLT-7125. It adds a field to the `model.Response` object in `model/client4.go` containing the original `http.Response` so that we can check the headers.
> Added unit tests for getFile headers

- webapp/components/post_view/post_body_additional_content.jsx
> 1) Go to the "Bugs" channel on pre-release
> 2) Find a post from the "Jira" account containing a message attachment
> 3) Hit the reply arrow to open a reply thread. Note the message attachment on the right-hand sidebar
> 4) Find another post from the "Jira" account and hit the reply arrow to open the right-hand sidebar.
>
> Observed: Message attachment from step 2 & 3) still shown on the right-hand sidebar. The attachment author and title change, but not the body.
> Expected: Message attachment from step 4 shown.
Post attachments store a few things in their state that are not reset when their attachment prop changes. An easy fix is to reset the attachment list when the post body component is re-used.
https://mattermost.atlassian.net/browse/PLT-7324
N/A
> PLT-7324: reset post attachments on post prop change

- webapp/components/user_settings/manage_languages.jsx
- webapp/components/user_settings/user_settings_display.jsx
Removed props mutation that was causing JS error, now passing locale as a prop directly instead of fetching it out of the user object
**Testing Steps**
* Create a second account for testing using an invite link, open this account in an incognito window
* In the primary browser window, use System Console > General > Localization to set the only two available languages on the server to English and French
* In the incognito window, use Account Settings > Display > Language to set the language for the account to French
* Confirm that all on-screen text changes to French
* In the primary browser window, use System Console > General > Localization to remove French as a language option, leaving English as the only available option
* Back in the incognito window, open Account Settings > Display > …
> PLT-7301: JS error when current language setting of a user is removed from system's available languages

- app/team.go
- app/team_test.go
Allow deleting of teams with no channels through CLI.
https://mattermost.atlassian.net/browse/PLT-7288
> PLT-7288: Allow CLI to delete teams with no channels.

- webapp/stores/search_store.jsx
For some reason it was failing silently because of the `Object.values()` when `results` or `results.posts` was undefined. I refactored so that couldn't happen which fixed the issue.
https://mattermost.atlassian.net/browse/PLT-7358
> PLT-7358 Fix pinned posts not updating when list empty

- app/notification.go
Here is a summary of some mention cases, with the two cases I changed marked.
**Note: All dashes can be replaced with periods and the same behavior will occur **
**tim in channel, tim-test not in channel**
1. message: `@tim-test `
results:
- **(NEW BEHAVIOR) tim-test not in channel ephemeral message posted**
- notification sent to tim
2. message: `tim-test `
results:
- notification sent to tim
**tim and tim-test in channel**
1. message: `@tim-test `
results:
- notification sent to tim-test
2. message: `tim-test `
results:
- notification sent to tim-test 
**tim and tim-test not in channel**
1. message: `@tim-test `
results:
- **(OLD BEHAVIOR) tim not in channel ephemeral message posted**
- **(NEW BEHAVIOR) tim and tim-test not in channel ephemeral message posted**
2. message: `tim-test ` …
> PLT-7283 Fix out-of-channel mentions for usernames with dashes/periods

- webapp/package.json
- webapp/yarn.lock
Update mattermost-redux to webapp-4.1 branch. Includes a fix for https://mattermost.atlassian.net/browse/PLT-7341.
> Update mattermost-redux to webapp-4.1 branch

- webapp/utils/markdown.jsx
- webapp/utils/text_formatting.jsx
Doesn't highlight `#hashtag.dot` when searching for `#hashtag`.
This time it also doesn't break when there's links involved. Look at the diff between the two commits in this PR if you want to see the fix for the bug this introduced last time round.
https://mattermost.atlassian.net/browse/PLT-6609
> PLT-6609: Fix hashtag highlighting of search results

- webapp/sass/components/_search.scss
Somehow having the flex-basis set manually for the search box and having it set to not shrink caused it to extend off the right side of the screen
and then that was causing the body of the page to shift left to try to fit it on the screen under certain circumstances (in this case changing to a channel that has unread posts). Changing it back to the default (let it shrink and have it figure out its width automatically) fixed the issue.
I could also fix it by turning the body of the page to use `position: absolute' briefly and then back to `position: relative`, but it would break again the next time the steps were performed. Basically, it's IE11 being IE11 ¯\\\_(ツ)\_/¯
https://mattermost.atlassian.net/browse/PLT-7398
> PLT-7398 Removed flex-basis from search box

- api/webhook.go
- api4/webhook.go
- web/web_test.go
Move webhook handling into api4 package to fix EnableAPIv3 config setting that was disabling webhooks when set to false.
https://mattermost.atlassian.net/browse/PLT-7408
> PLT-7408 Move webhook handling into api4 package to fix EnableAPIv3 config setting

- webapp/components/rhs_comment.jsx
- webapp/components/rhs_root_post.jsx
Add emoji to recently used section when reacting to a post in RHS
Jira ticket: [PLT-7355](https://mattermost.atlassian.net/browse/PLT-7355)
> [PLT-7355] Add emoji to recently used section when reacting to a post in RHS

- webapp/components/search_bar.jsx
- webapp/components/suggestion/suggestion_box.jsx
Don't clear the searchbox when pressing ESC (fixes Chrome).
https://mattermost.atlassian.net/browse/PLT-7368
> PLT-7368: Don't clear search box on ESC in Chrome.

- webapp/package.json
- webapp/yarn.lock
When I made some changes to the regex last year, I accidentally left in part of the regex that only allowed quotes if they were in pairs
Marked changes here: https://github.com/mattermost/marked/commit/5194fc037b35036910c6542b04bb471fe56b27a9
https://mattermost.atlassian.net/browse/PLT-7353
> PLT-7353 Fixed being unable to use quotes in links

- app/diagnostics.go
- einterfaces/cluster.go
- model/cluster_info.go
- utils/config.go
This adds simple leader election.  I looked at stuff like https://github.com/docker/leadership but it has a hard requirement on using Consul, etcd or Zookeeper.  I also found https://github.com/monnand/bully implementation of the https://en.wikipedia.org/wiki/Bully_algorithm, which at it's core is a pretty simple concept.
Since we don't need a strict leader election, meaning we can tolerate multiple leaders and jobs running more than once, this PR is inspired by the bully algo, but does not implement it.
Enterprise PR https://github.com/mattermost/enterprise/pull/175
https://mattermost.atlassian.net/browse/PLT-6079
> PLT-6079 Adding simple leader election

- api4/job_test.go
- config/config.json
- einterfaces/jobs/elasticsearch.go
- i18n/en.json
- jobs/jobs.go
- jobs/jobs_watcher.go
- jobs/schedulers.go
- jobs/workers.go
- model/config.go
- model/job.go
- store/sql_job_store_test.go
- store/sql_supplier.go
Aggregate Elasticsearch indexes over a certain age.
This is done by a scheduled daily job, in order to keep the shard count
to a sensible level in Elasticsearch.
https://mattermost.atlassian.net/browse/PLT-7302
> PLT-7302: Aggregate Elasticsearch indexes over a certain age.

- cmd/platform/channel.go
CLI command to change channel public/private type.
This adds a channel modify CLI command, with the one property that it
can modify being the channel public/private type.
https://mattermost.atlassian.net/browse/PLT-7217
> PLT-7217: CLI command to change channel public/private type.

- plugin/rpcplugin/ipc_test.go
- plugin/rpcplugin/main_test.go
- plugin/rpcplugin/process_test.go
- plugin/rpcplugin/process_windows.go
- plugin/rpcplugin/supervisor_test.go
Required for Windows to support back-end plugins.
This makes me hate myself a little. I'm copying and pasting a big chunk of the standard library to implement a fix for this issue: https://github.com/golang/go/issues/21085
I'm hopeful that in a future Go release (1.10 maybe?), we can get an official fix and delete all of this.
You two are Windows people, right? (Basing that off IE listed in your browser inventory.)
> windows support for plugin ipc

- store/sql_status_store.go
Bunch of errors in Kubernetes under load: 
```
2017-08-18T17:33:10.256229156Z [2017/08/18 17:33:10 UTC] [EROR] Failed to save status for user_id=8ip6dnbqwfdrje8k6xq16k5azy, err=SqlStatusStore.SaveOrUpdate: store.sql_status.save.app_error, Error 1062: Duplicate entry '8ip6dnbqwfdrje8k6xq16k5azy' for key 'PRIMARY'
```
This ignores them since this should only happen rarely when status updates are sent in quick succession to multiple HA servers. No need to pollute the logs.
> Ignoring primary key duplication errors on status saveorupdate

- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/hooks_test.go
- plugin/rpcplugin/main.go
- plugin/rpcplugin/main_test.go
- plugin/rpcplugin/supervisor_test.go
All hooks are now optional. When a plugin is connected, it provides a list of implemented hooks. Then unimplemented hooks can be short-circuited with no i/o.
* ~Back-end plugin mechanism~ https://github.com/mattermost/platform/pull/7177
* ~Implement Windows IPC~ https://github.com/mattermost/platform/pull/7251
* **Make hook methods optional (ideally without a roundtrip for unimplemented methods)**
* Add APIs required for JIRA plugin (HTTP route registration and post creation)
* Port JIRA plugin (this'll be almost entirely build system changes once the above are done)
JIRA still down.
> make plugin hooks optional, short circuit if unimplemented

- webapp/components/sidebar.jsx
Add + link next to 'DIRECT MESSAGES' title in the LHS that behaves just like clicking the `More...` link at the bottom.
> Add a + next to direct message on sidebar to open 'Direct Messages' modal

- webapp/sass/components/_inputs.scss
Changing an automatic browser shadow DOM element's display style to none in order to have the paperclip icon show a finger pointer instead of a default cursor.
https://mattermost.atlassian.net/browse/PLT-6303
> Allowing Paperclip icon to show mouse pointer as a hand

- webapp/sass/layout/_post.scss
Fixed not being able to scroll down in message preview mode when using only a couple of sentences in edit mode.
https://github.com/mattermost/platform/issues/6302
> PLT-6441 - Fixed not being able to scroll down in message preview mode when using  only a couple of sentences in edit mode.

- manualtesting/manual_testing.go
- manualtesting/test_autolink.go
- utils/config.go
- utils/mail.go
- wsapi/websocket_handler.go
This replaces calls to `NewLocAppError` with `NewAppError` and sets the appropriate HTTP status code on the remaining unmigrated errors in the `utils` package and a couple of other misc packages.
> NewLocAppError -> NewAppError for utils and some other miscellaneous packages

- webapp/components/search_results_item.jsx
> When viewed in RHS flagged posts list, integration posts are missing their "attached" content.
>
> 1. Flag an integration post that has an "attachment" (can use a Jira integration post in the Bugs channel)
> 2. Click flag icon to view flagged posts in RHS
> 
> Observed: Post appears empty
> Expected: Post content is displayed
https://mattermost.atlassian.net/browse/PLT-7345
> PLT-7345: add attachments to rhs search results

- app/session.go
Issue found by #7178 causing the server to panic cause the l4g.Error was malformed.
> Fix log error message for UpdateLastActivityAtIfNeeded

- api/emoji_test.go
- api/file.go
- api/file_test.go
- api4/file.go
- api4/file_test.go
- app/emoji.go
- app/file.go
- app/file_test.go
- app/import.go
- app/slackimport.go
- app/user.go
- cmd/platform/server.go
- i18n/en.json
- model/file_info.go
- store/sql_file_info_store.go
- store/sql_file_info_store_test.go
- store/store.go
- utils/file.go
- utils/file_test.go
- utils/time.go
Prepare file upload infrastructure for Data Retention.
This commit prepares the file upload infrastructure for the data
retention feature that is under construction. Changes are:
* Move file management code to utils to allow access to it from jobs.
* From now on, store all file uploads in a top level folder which is the
date of the day on which they were uploaded.
This commit is based on Harrison Healey's branch, but updated to work
with the latest master.
LOL
**ENTERPRISE CHANGES**: https://github.com/mattermost/enterprise/pull/186
> PLT-???? Prepare file upload infrastructure for Data Retention.

- utils/config.go
Omitting the trailing backslash in the directory could cause
Mattermost to crash due to permission issues.
> Use path.Join to form log filename

- api4/oauth.go
Not having the charset set was causing me a JS unexpected token console error in dev mode. Not sure if this affects a prod client build but I'll be checking that soon.
> Set charset for OAuth2 authorize page

- app/notification.go
- model/push_notification.go
Include postId and rootId of the post to be sent along with the push notification.
Also changed the category that is sent, categories are to be use with push notification actions
> Include post_id and root_id to handle actions from the PN

- plugin/hooks.go
- plugin/plugintest/hooks.go
- plugin/rpcplugin/api.go
- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/hooks_test.go
- plugin/rpcplugin/http.go
- plugin/rpcplugin/http_test.go
- plugin/rpcplugin/io.go
- plugin/rpcplugin/muxer.go
- plugin/rpcplugin/muxer_test.go
This allows back-end plugins to handle HTTP requests.
Part of https://mattermost.atlassian.net/browse/PLT-7407
> PLT-7407: Add plugin http handler

- i18n/en.json
- plugin/api.go
- plugin/plugintest/api.go
- plugin/rpcplugin/api.go
- plugin/rpcplugin/api_test.go
* ~Back-end plugin mechanism~ https://github.com/mattermost/platform/pull/7177
* ~Implement Windows IPC~ https://github.com/mattermost/platform/pull/7251
* ~Make hook methods optional (ideally without a roundtrip for unimplemented methods)~ https://github.com/mattermost/platform/pull/7263
* **Add APIs required for JIRA plugin (HTTP route registration and post creation)** (along with https://github.com/mattermost/platform/pull/7289)
* Port JIRA plugin (this'll be almost entirely build system changes once the above are done)
Very straight-forward and easy to add these APIs. `net/rpc` does all the heavy lifting. But it is a little tedious. It's certainly feasible to eliminate the tedium with some code generation.
Once @jwilander's PR (https://github.com/mattermost/platform/pull/7279) is …
> PLT-7407: Add client4 apis needed for JIRA plugin

- webapp/yarn.lock
Not sure what it's really doing here (looks like consolidating different versions of packages into one line) but every time I run `yarn install` it changes it to this and it's incredibly annoying. Everything seems to build and work correctly with the changes.
> Fix yarn.lock getting changed by make run

- webapp/components/post_view/post_body_additional_content.jsx
- webapp/stores/browser_store.jsx
In this change, user action for toggling the preview is stored in the browser localstorage. Hence If there is a preview visibility value present
in the localstorage, that will be given the preference compared to the overall preview setting.
[Github](https://github.com/mattermost/platform/issues/7189)
[Jira](https://mattermost.atlassian.net/browse/PLT-3638)
> PLT-3638: Fix re-opening of collapsed preview on refresh

- webapp/components/select_team/select_team.jsx
Show loading message if a team has been selected, in addition to showing it while loading the list of available teams.
https://mattermost.atlassian.net/browse/PLT-7186
> PLT-7186: "No teams available to join" appears while joining another team

- webapp/components/channel_header.jsx
- webapp/components/navbar.jsx
Removed restriction that prevented last occupant of a channel from leaving. Any user can now leave any channel, except for the default Town Square channel
**NOTE:** This is the second PR for this ticket. The first one dealt with the ticket title, and the second one deals with @esethna's [comment](https://mattermost.atlassian.net/browse/PLT-7206?focusedCommentId=39569&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39569) on that ticket.
https://mattermost.atlassian.net/browse/PLT-7206
> PLT-7206: Remove the "Delete Channel" option for private channels if you're the last channel member and policy setting restricts channel deletion

- api/admin.go
- api/channel.go
- api/context.go
- api/emoji.go
- api/file.go
- api/license.go
- api/oauth_test.go
- api/post.go
- api/preference.go
- api/reaction.go
- api/team.go
- api/user.go
- api/websocket.go
I got fed up with the proliferation of `NewLocAppError` and the fact more of them keep creeping into the codebase despite the fact we're trying to move away from it.
This PR removes it entirely from the `api` package. There are more PRs that do the other packages.
> Convert NewLocAppError -> NewAppError in api package

- app/plugin/api.go
- app/plugin/ldapextras/configuration.go
- app/plugin/ldapextras/plugin.go
- app/plugins.go
- einterfaces/ldap.go
Adds a built-in plugin for adding an endpoint allowing configured attributes to be pulled from LDAP for a user.
1. Configure the `LdapServer`, `LdapPort`, `BaseDN`, `BindUsername`, `BindPassword`, `UserFilter` and `IdAttribute` fields under `LdapSettings` in `config.json`. Note that when using SAML SSO the `IdAttribute` must be the email field in LDAP that is mapped to the user in SAML. If using LDAP SSO, set `IdAttribute` as normal
2. Add the plugin configuration under `PluginSettings.Plugins` in `config.json`, like so:
```
"PluginSettings": {
"Plugins": {
"ldapextras": {
"Enabled": true,
"Attributes": ["attribute1", "attribute2"]
}
}
}
```
The list under `Attributes` will specify which LDAP attributes the API endpoint will use
3. Start the server and perform an HTTP GET against …
> PLT-7412 Add built-in plugin for getting LDAP attributes

- webapp/components/claim/components/email_to_ldap.jsx
- webapp/components/claim/components/ldap_to_email.jsx
> When you enter incorrect information on:  
> - Switch LDAP to Email password screen
> - Switch Email/Password Account to LDAP
>
> All the fields turn red. 
>
> Expected: Only the incorrect field turns red. 
https://mattermost.atlassian.net/browse/PLT-3540
> PLT-3540: only highlight relevant fields on ldap/email switch error

- store/sql_user_store.go
Add `AuthData` to `IsUniqueConstraintError` to indicate duplicated email entry, with the assumption that duplicated AuthData also means duplicated email entry.
Jira ticket: [PLT-7385](https://mattermost.atlassian.net/secure/RapidBoard.jspa?rapidView=1&projectKey=PLT&view=detail&selectedIssue=PLT-7385)
Update: 30-Aug
- mysql error: `Error 1062: Duplicate entry 'xxx' for key 'AuthData'`
- postgresql error: `pq: duplicate key value violates unique constraint "users_authdata_key"`
`AuthData` and `users_authdata_key` were added to `IsUniqueConstraintError` when updating user's auth data.
> [PLT-7385] Add AuthData to IsUniqueConstraintError to indicate duplicated email entry

- i18n/en.json
The messages labeled ID `app.plugin.disabled.app_error` are duplicated.
[platform/en.json at master · mattermost/platform](https://github.com/mattermost/platform/blob/master/i18n/en.json#L407)
It had better to remove the message having no word.
N/A
> Remove duplicated message

- webapp/sass/layout/_markdown.scss
These styles are applied asynchronously by highlight.js so it causes the height of the code block to change slightly. There was a ticket somewhere, but I can't remember where it was
> Fixed code blocks causing minor scroll pop on first load

- app/notification.go
- app/notification_test.go
Changes the regex to capture one or more repeated backquotes instead of just one. There are rare cases when this doesn't line match how inline code is handled in Markdown (it expects an equal number of backquotes), but it's unlikely we'll hit those cases
https://mattermost.atlassian.net/browse/PLT-7473
> PLT-7473 Ignore text surrounded by multiple backquotes when parsing mentions

- model/client4.go
Fix elasticsearch purge indexes URL in client4.go
Enterprise changes: https://github.com/mattermost/enterprise/pull/190
> Fix elasticsearch purge index url in client4.

- app/channel.go
- app/channel_test.go
- cmd/platform/channel.go
- i18n/en.json
Adds a CLI command to move channels between teams.
https://mattermost.atlassian.net/browse/PLT-7216
> PLT-7216: CLI Command to move channels between teams.

- app/server.go
Concerns from business team need to be addressed. In the meantime, placing the experimental implementation of plugins under E20 licenses.
> Temporarily place plugins into E20

- model/config.go
Add status codes to all remaining `NewLocAppError` calls in `model/config.go`.
They are all in the functions that check if the config is valid, and so they all just get `http.BadRequest` as the error, to be consistent with the other similar errors in those functions which already set that error code.
> Add status codes to model/config.go errors.

- webapp/components/file_preview.jsx
- webapp/components/file_upload.jsx
Two bugs:
* SVG thumbnails weren't working. The client was attempting to display them in the same way as other image thumbnails: fetching a lower resolution file from the server. But this doesn't make sense for vector graphics. The fix is to just use the regular file.
* All files pasted into the message box would trigger an upload. But in Chrome, only certain file types can be uploaded (See https://bugs.chromium.org/p/chromium/issues/detail?id=487266). So the UI would break. The fix for this is to not attempt to upload files unless we can actually get a `File` object for them.
In addition, I've removed the image filtering so that non-image files can be copied/pasted on browsers if/when they support it.
https://mattermost.atlassian.net/browse/PLT-7373
N/A
> PLT-7373: fix svg thumbnails and non-png copy/pastes

- webapp/components/activity_log_modal/activity_log_modal.jsx
Since personal access tokens need to be managed from the Personal Access Tokens section, it's best to avoid confusion by hiding them from the user sessions modal (logging out of a personal access token session won't revoke the token).
If later we want to show them here and allow token revoking here that's fine, but that's a 4-8 mana ticket.
https://mattermost.atlassian.net/browse/PLT-7516
> PLT-7516 Skip personal access token sessions in view sessions modal

- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- app/admin.go
- i18n/en.json
- model/config.go
- utils/config.go
- utils/file.go
- webapp/components/admin_console/storage_settings.jsx
- webapp/i18n/en.json
Add S3 region to system console and add S3 validation to endpoint, region and bucket
Jira ticket: [PLT-7475](https://mattermost.atlassian.net/browse/PLT-7475)
@jasonblais please help validate the System Console UI, translation/logs and UX experience. Below are some key points:
1. If Driver is set to S3 and given valid credentials,
- Endpoint is validated against the predefined S3 endpoint mapping. If not found, it will be set to .default: "s3.amazonaws.com"
- Region is validated against the predefined S3 endpoint mapping. If not found, it will be set to default: "us-east-1".
- Bucket cannot be empty.
- if bucket does not exist, it will be created automatically according to endpoint/region. 
- if bucket exists, endpoint and region will be filled up / modified accordingly.
- Changes to S3 …
> [PLT-7475] Add S3 region to system console and add S3 validation

- app/plugin/jira/plugin.go
- webapp/utils/post_utils.jsx
The JIRA plugin has a requirement of "use user image" and "have bot label". Which means we either need a prop to make webhook posts use the user image or a prop to add the bot label to non-webhook posts. The "from_webhook" prop is somewhat tightly coupled with our notification handling, so the much simpler and lower risk option for good bot behavior was to use it in addition to a "use_user_icon" prop.
I think ideally we would probably create separate props that can produce the effects of "from_webhook" such as "from_bot" and "notify_user", but that requires a little more thought and effort.
https://mattermost.atlassian.net/browse/PLT-7300
N/A
> PLT-7300: Add use_user_icon prop to allow bots to just use their user icon

- webapp/components/sidebar_right_menu.jsx
There's different logic for 'Get Team Invite Link' for RHS and LHS menu. This causes that the link is displayed differently when `EnableUserCreation=false`:
- RHS menu: `webapp/components/sidebar_right_menu.jsx`
`if (this.props.teamType === 'O') {`
https://github.com/mattermost/platform/blob/master/webapp/components/sidebar_right_menu.jsx#L196
- LHS menu: `webapp/components/sidebar_header_dropdown.jsx`
`if (this.props.teamType === Constants.OPEN_TEAM && config.EnableUserCreation === 'true') {`
https://github.com/mattermost/platform/blob/master/webapp/components/sidebar_header_dropdown.jsx#L254
> Fix 'Get Team Invite Link' logic on RHS menu to match LHS menu.

- webapp/components/file_upload.jsx
The desktop app seems to be subject to this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=361145
So if a file name isn't available, this falls back to using the mime type to get the extension as it did before.
https://mattermost.atlassian.net/browse/PLT-7555
N/A
> PLT-7555: more robust file upload extension

- webapp/components/profile_popover.jsx
- webapp/plugins/pluggable/pluggable.jsx
Production builds weren't including the component names, causing plugin components not to render. This may not be the final solution but it's good enough for 4.2
> Fix webapp plugins for production builds

- webapp/components/shortcuts_modal.jsx
Fixes the crash on load for non-English languages that happened because we expected the shortcuts header to contain a tab character followed by a shortcut key. Since it was translated before the header included that, it was crashing
https://mattermost.atlassian.net/browse/PLT-7561
https://github.com/mattermost/mattermost-server/issues/7395
> PLT-7561 Fixed crash when translated shortcuts don't include keys (4.2)

- api4/api.go
- api4/plugin_test.go
- app/app.go
- app/plugins.go
- app/server.go
- cmd/platform/server.go
- i18n/en.json
- plugin/hooks.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
- plugin/plugintest/hooks.go
- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/hooks_test.go
- plugin/rpcplugin/io.go
- plugin/rpcplugin/io_test.go
- plugin/rpcplugin/ipc.go
- plugin/rpcplugin/supervisor.go
- plugin/rpcplugin/supervisor_test.go
- utils/extract.go
It is finished.
https://mattermost.atlassian.net/browse/PLT-7407?filter=14400
> PLT-7407: Back-end plugins

- utils/html.go
The support email was being passed in as a pointer which was causing the sanitization function to complain. I also added some extra debugging in case we start passing more stuff into these templates
https://mattermost.atlassian.net/browse/PLT-7563
> PLT-7563 Fixed template handling to support more values (4.2)

- model/command_response.go
- model/command_response_test.go
Ensures that content-types like `application/json; charset=utf-8` are handled correctly.
https://mattermost.atlassian.net/browse/PLT-7569
> PLT-7569: More robust command response content-type checking

- webapp/actions/notification_actions.jsx
- webapp/components/channel_header.jsx
- webapp/components/navbar.jsx
- webapp/components/sidebar.jsx
- webapp/utils/channel_utils.jsx
Fix sorting of group channel display name
Jira ticket: [PLT-7577](https://mattermost.atlassian.net/browse/PLT-7577)
UPDATE:
Make use of channel.display_name (for group channel) which is already sorted from mattermost-redux. Just realized after the comment made by @enahum on PR submitted to master.
> [PLT-7577] Fix sorting of group channel display name

- webapp/components/channel_view.jsx
- webapp/components/tutorial/tutorial_view.jsx
When the tutorial view was displayed by the channel view, after navigating through the tutorial, the tutorial view would leave the `<body>` without an `app__body` class.
https://mattermost.atlassian.net/browse/PLT-7579
N/A
> PLT-7579: fix broken css after tutorial

- utils/html.go
The support email was being passed in as a pointer which was causing the sanitization function to complain. I also added some extra debugging in case we start passing more stuff into these templates
https://mattermost.atlassian.net/browse/PLT-7563
> PLT-7563 Fixed template handling to support more values

- Makefile
Other option to solve this is use "ln -s -f" to force overwrite of client link, but the current approach allows you to link to your client in other place temporary without been overwritten accidentally.
> Avoid error linking client dist directory every time

- api4/webhook_test.go
- app/webhook.go
Invalidate webhook cache after updating webhook.
https://mattermost.atlassian.net/browse/PLT-7535
> PLT-7535 Invalidate webhook cache after updating webhook

- api4/command_test.go
- model/access.go
- model/authorize.go
- model/channel.go
- model/channel_member.go
- model/client.go
- model/client4.go
- model/cluster_discovery.go
- model/command.go
- model/compliance.go
- model/emoji.go
- model/file_info.go
- model/license.go
- model/post.go
- model/preference.go
- model/reaction.go
- model/team_member.go
- model/utils.go
- model/utils_test.go
- model/websocket_client.go
This adds status codes to the remaining errors in the model package that don't have them. Nearly all the changes are adding `BadRequest` to `IsValid` errors, for consistency with all the other errors in this package where this is the case. There are a few `0` ones added where appropriate in the various client drivers, and a few others as appropriate in some other places.
Apologies once again for the long, boring PR. Github helpfully highlights the characters within the line that have changed, which makes it much less painful to review than some other diff tools!
> Add status codes to remaining errors in model package

- api4/plugin.go
- api4/plugin_test.go
- api4/system.go
- app/plugins.go
- cmd/platform/server.go
- model/client4.go
- model/manifest.go
- model/manifest_test.go
- model/websocket_message.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
- web/web.go
* Add new REST API endpoint for getting sanitized versions of webapp plugins to download
* Removed temporary code loading plugin manifest into client config
* Fix webapp plugin directory based on repo split and move webapp plugins into their own directory
* Add own HTTP handler for plugin js bundles, in developer mode disable caching of plugin js bundles
* Fix setting of EnableDeveloper to true for dev builds
* Add websocket events for plugin activation/deactivation
https://mattermost.atlassian.net/browse/PLT-7622
> PLT-7622 Improvements to server handling of webapp plugins

- api/cli_test.go
- cmd/platform/channel.go
Remove redundant license checks from CLI commands.
https://mattermost.atlassian.net/browse/PLT-7539
> PLT-7539: Remove redundant license checks from CLI commands.

- store/sql_oauth_store.go
- store/sql_post_store.go
- store/sql_preference_store.go
This PR adds error codes to the errors of the last remaining package where this hasn't been done: `store`. There's quite a few, so in the interests of everyone's sanity I've split it into 4 separate PRs.
> Add error codes to oauth/post/preference store errors.

- api4/oauth.go
> In the error message that displays when trying to switch to a GitLab login already in use, if there is a plus sign in the email address, the error message prints a space instead, so the email link is incomplete.
https://mattermost.atlassian.net/browse/PLT-7511
N/A
> PLT-7511: Fix error message escaping

- api/api.go
- api/post_test.go
- api4/api.go
- app/admin.go
- app/app.go
- app/cluster_discovery.go
- app/cluster_discovery_test.go
- app/server.go
- cmd/platform/channel.go
- cmd/platform/channelargs.go
- cmd/platform/import.go
- cmd/platform/jobserver.go
- cmd/platform/roles.go
- cmd/platform/team.go
- cmd/platform/teamargs.go
- cmd/platform/user.go
- cmd/platform/userargs.go
- einterfaces/account_migration.go
- einterfaces/cluster.go
- einterfaces/compliance.go
- einterfaces/ldap.go
- einterfaces/metrics.go
- einterfaces/mfa.go
- einterfaces/saml.go
- store/layered_store.go
- store/local_cache_supplier.go
- store/sql_store_test.go
- utils/config.go
This one's exciting: I'm finally actually removing some package level variables!
This allows me to remove the last of the `app.Global` references in our enterprise code. I've also started to replace some of the `utils.Cfg` references.
Very few `app.Global` references remaining. Then I'll probably do a find/replace or AST patch to replace all of the `utils.Cfg` references in one big sweep.
Enterprise PR: https://github.com/mattermost/enterprise/pull/198
> Remove more global refs

- einterfaces/elasticsearch.go
- i18n/en.json
Clean up elasticsearch indexes when running data retention jobs.
https://mattermost.atlassian.net/browse/PLT-7667
> PLT-7667: Clean up elasticsearch indexes when running data retention jobs.

- config/default.json
- model/config.go
Allow setting a prefix for Elasticsearch indexes.
https://mattermost.atlassian.net/browse/PLT-7694
> PLT-7694: Allow setting a prefix for Elasticsearch indexes.

- i18n/en.json
- store/sql_preference_store.go
- store/sql_preference_store_test.go
- store/store.go
Adds a function to the posts store to clean up dangling flagged posts which point to posts that no longer exist.
https://mattermost.atlassian.net/browse/PLT-7619
> PLT-7619: Cleanup flags in data retention.

- Makefile
- utils/file_test.go
This ports the file tests to testify, and runs the suite twice - once using the `local` driver and once using the `s3` driver with minio.
This adds a minio docker image to the Makefile.
> Run file tests on Minio and local drivers.

- app/file.go
- app/post.go
- app/webhook.go
- model/utils.go
- utils/file.go
This cleans up the few NewLocAppError calls that crept in since the main
bulk of them were removed, and finally removes the NewLocAppError
function altogether.
> Finally do away with NewLocAppError function.

- store/sqlstore/channel_store.go
- store/sqlstore/user_store.go
- store/sqlstore/user_store_test.go
The current (fulltext based) implementation of user filtering search can't cope with <3 character long names. This is causing issues for some customers.
This PR fixes it to support searching names of any length, by switching to LIKE queries instead of fulltext. Given we don't really utilise any features of fulltext in these search queries, and we don't need any prefix wildcards, LIKE queries on these fields are indexed.
I have been testing locally on a DB with 100,000 users, and performance of the user filtering seems to actually be *better* than before after this change. It will need proper performance/load testing before it gets merged though.
I don't think this results in any feature loss, but it might, so we need to check the functionality of any user search/filtering features …
> PLT-7207: Change from fulltext to LIKE search for user filtering

- app/plugins.go
Minor fix for ldapextras built-in plugin.
> Only check LDAP attributes if auth data set

- api/post_test.go
- api4/command.go
- api4/command_test.go
- app/command.go
- app/webhook.go
- model/command_response.go
- model/outgoing_webhook.go
- model/outgoing_webhook_test.go
Add support to outgoing webhooks and slash commands to set post type and props. Incoming webhooks already had support for it.
https://mattermost.atlassian.net/browse/PLT-7684
> PLT-7684 Add support to outgoing webhooks and slash commands to set post type and props

- i18n/en.json
Tidies up error messages for data retention invalid inputs.
This doesn't fix the error when you enter an enormous number of days - that needs to happen client side actually as it's generating an invalid config json which the parser chokes on, so I can't validate it specifically server side.
> PLT-7750: Improve the error messages for invalid data retention config.

- api/channel.go
- api4/channel.go
- api4/channel_test.go
- app/channel.go
- model/channel_view.go
- model/channel_view_test.go
- model/client4.go
- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_test.go
I used a transaction to select the LastPostAt times out of the database and then update the ChannelMembers. This might have perf implications because it adds a read on a hot route so if either of you can think of a better method that doesn't require an extra read let me know
API reference update: mattermost/mattermost-api-reference#288
https://mattermost.atlassian.net/browse/PLT-7404
> PLT-7404 Return viewed at times in view channel API response

- store/sqlstore/job_store.go
- store/sqlstore/job_store_test.go
Make GetNewestJobByStatusAndType not fail when no jobs match. It should not error, but should return a nil job.
https://mattermost.atlassian.net/browse/PLT-7759
> PLT-7759: Make GetNewestJobByStatusAndType not fail when no jobs match.

- api4/data_retention_test.go
```
api4/data_retention_test.go:12: undefined: TearDown
```
> Fix bad merge

- api4/channel.go
- api4/context.go
- api4/post.go
- api4/user.go
This is an update to the PR that added the idle session timeout features. Some endpoints get hit even if there is no activity from the user, making it look like the session activity is from the user. I moved the session activity update from all requests to a few active routes that generally require user action.
> Only update session activity on specific endpoints

- api4/command.go
- api4/command_help_test.go
- api4/command_test.go
- model/client4.go
Ensured that specified channel is a part of specified team prior to executing the slash command.
https://mattermost.atlassian.net/browse/PLT-7785
> PLT-7785: Slash commands can be issued to a channel in a team without it

- app/command.go
When some commands return an empty message it should not post in the channel, this PR check if the message is empty and if it blocks the post.
JIRA: https://mattermost.atlassian.net/browse/PLT-7787
> [PLT-7787] remove an extra ephemeral message posted for slash commands

- app/import.go
- app/team.go
This fixes bulk import failing on importing team members due to raciness between select on read replicas and insert on the master. This is most noticeable when using bulk import on an Aurora cluster.
Not sure if there's a better way of doing it than having a function which returns 3 parameters, which feels a bit unusual.
https://mattermost.atlassian.net/browse/PLT-7789
> PLT-7789: Fix raciness on Aurora with importing team members.

- app/command.go
- app/command_test.go
- cmd/platform/command.go
- cmd/platform/commandargs.go
- cmd/platform/mattermost.go
- i18n/en.json
- store/sqlstore/command_store.go
- store/sqlstore/command_store_test.go
- store/store.go
Adds a CLI command to move slash commands between teams.
https://mattermost.atlassian.net/browse/PLT-7218
> PLT-7218: CLI to move slash commands between teams.

- api/api.go
- api/apitestlib.go
- api4/api.go
- api4/apitestlib.go
- app/admin.go
- app/app.go
- app/apptestlib.go
- app/oauth.go
- app/options.go
- app/post.go
- app/server.go
- app/webhook.go
- app/webrtc.go
- app/websocket_router.go
- cmd/platform/init.go
- cmd/platform/jobserver.go
- cmd/platform/server.go
- cmd/platform/test.go
- store/sqlstore/store_test.go
- store/sqlstore/upgrade.go
- store/storetest/docker.go
- web/web_test.go
Cleans up a few things:
* `App.New` now returns a functional app. You don't have to call `NewServer`, `InitStore`, `NewRouter`, or `NewWebSocketRouter` anymore. Those functions have all been deleted.
* You don't have to assign `App.Jobs.Store` anymore.
* The `CloseBody` function has been deleted. You don't have to consume the body of a response before closing it. This also fixes some inefficient / leaky code near one of those calls.
* `App.New` now accepts options. There's only one so far: `StoreOverride`. This is almost the entire reason I'm putting in this PR. I'm going to need that very soon to inject a faster store into the app for our tests.
N/A
> Miscellaneous app cleanup

- app/post.go
`PatchPost` calls `UpdatePost` which already does a `sendUpdatedPostEvent()` and `InvalidateCacheForChannelPosts()`. This was causing two post edit events to be sent and the cache to be invalidated twice.
None.
> Remove duplicate post edit WS event and cache invalidation

- store/sqlstore/channel_store.go
- store/sqlstore/user_store.go
- store/storetest/channel_store.go
`in:{channel}` search uses IN BOOLEAN MODE full text search where `-` is considered as NOT operator. Thus, search query like below will cause `syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'`.
```
SELECT * FROM Channels 
WHERE TeamId = 'qocdorjddi858f4przgz5hujxw' AND Type = 'O' AND DeleteAt = 0 
AND MATCH(Name, DisplayName) AGAINST ('+off-*' IN BOOLEAN MODE) 
ORDER BY DisplayName LIMIT 100;
```
This is fixed by following the same search query used in  `from:{user}`. Search query will now become like:
```
SELECT * FROM Channels 
WHERE TeamId = 'qocdorjddi858f4przgz5hujxw' AND Type = 'O' AND DeleteAt = 0 
AND (Name LIKE 'off-t%' escape '*' OR DisplayName LIKE 'off-t%' escape '*' ) 
ORDER BY DisplayName LIMIT 100;
```
Jira ticket: …
> [PLT-7764] Fix in:channel search when channel name/displayname includes `-`

- utils/config.go
The SAML client config setting where named the same as the LDAP ones. So they would overwrite and cause the client to misbehave.
> PLT-7837 Fixing LDAP and SAML settings detection

- Makefile
- scripts/test-xprog.sh
For every package, we run a command like this to test it:
```
go test -run=asdqwqwe -short -v -timeout=2000s -covermode=count -coverprofile=cprofile.out
-coverpkg=github.com/mattermost/mattermost-server,
github.com/mattermost/mattermost-server/api,
github.com/mattermost/mattermost-server/api4,
github.com/mattermost/mattermost-server/app,
github.com/mattermost/mattermost-server/app/plugin,
github.com/mattermost/mattermost-server/app/plugin/jira,
[and about 30 other packages...]
github.com/mattermost/mattermost-server/api
```
Under the hood, `go test` compiles every source file in every one of those packages with additional instrumentation added:
```
/usr/local/go/pkg/tool/darwin_amd64/cover -mode count -var GoCover_183 -o <...>
/usr/local/go/pkg/tool/darwin_amd64/cover -mode count -var …
```
> Make test execution not take quadratic compilation time

- app/app_test.go
- app/server.go
- app/web_conn.go
The race:
1. client closes connection
2. readPump returns, unregistering the connection from the hub
3. server shuts down. because the connection is no longer registered, we can't wait on it
4. writePump is still executing, panics because log channel has been closed
Fix: Wait for writePump before unregistering. Now the hub properly waits on the connection before returning from Stop().
N/A
N/A
> Fix webconn shutdown race

- app/diagnostics.go
- config/default.json
One for session timeout (https://github.com/mattermost/mattermost-server/pull/7524), second for elasticsearch index prefix
And rename `SessionIdleTimeout` --> `SessionIdleTimeoutInMinutes` in config.json.
> Add two missing diagnostics entries

- api4/user.go
- api4/user_test.go
- model/client4.go
mattermost-server
mattermost-redux
mattermost-webapp
mattermost-api-reference
Adds api endpoint for revoking all sessions for a user, as used by this new feature accessed from the system users dropdown.
https://github.com/mattermost/mattermost-server/issues/7493
> [PLT-7396] Add the ability to revoke user sessions in System Console > Users #7493

- api4/apitestlib.go
- api4/command.go
- api4/command_test.go
- model/client4.go
No longer overriding specified team id for DMs/GMs, as these types of channels don't belong to a team, and doing so breaks slash commands for them
https://mattermost.atlassian.net/browse/PLT-7193
> PLT-7193: Regression - Custom slash commands don't work in direct or group message channels

- api4/preference_test.go
The websocket tests sometimes fail because websocket events can be dispatched before the websocket fully connects:
Client: Calls Connect()
Server: Begins processing the authentication message
Client: Calls Listen() and triggers a websocket event
Server: Sends the websocket event to the appropriate websockets, which does not include the not-yet-authenticated client
Server: Finishes processing the authentication message and registers the connection with the hub
Client: Waits for event that never comes
Once the okay comes, we're guaranteed to receive any newly triggered events.
> Fix preference test races

- api4/job_test.go
Can't count on `GetMillis` to return the same thing three times in a row.
N/A
N/A
> Fix job test race condition

- cmd/platform/team.go
Fix the "team create" command wrongly shows a `teams create` example, where an extra "s" is appended to the command name.
> Fix teams create example

- api/apitestlib.go
- api4/apitestlib.go
Previously, all test users would share the same mailbox ("success@simulator.amazonses.com"). This gives each user a distinct mailbox when using the default docker SMTP server, so calls to functions like `utils.DeleteMailBox` don't delete the emails for users in parallel tests.
N/A
N/A
> Fix email race condition

- build/Jenkinsfile
Attempts to download a webapp build from S3 before invoking `make build`.
N/A
N/A
> Use webapp build from cache when possible

- api4/user.go
- api4/user_test.go
- app/session.go
- model/client4.go
- model/user_access_token.go
- model/version.go
- store/sqlstore/upgrade.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/user_access_token_store.go
Adds functionality to enable/disable user access tokens. A disabled user access token is not revoked but cannot be used to authenticate a session.
Adds a column in the UserAccessTokens table for token active/inactive status. Adds two new endpoints to the APIv4, allowing for temporarily enabling and disabling user access tokens.
Disabling a user access token also deletes any sessions associated with the token.
A companion client-side PR is forthcoming.
Github #7583 
Jira PLT-7794
See also https://github.com/mattermost/mattermost-api-reference/pull/295
> [PLT-7794] Add user access token enable/disable endpoints

- api4/file.go
Replace query escaping with path escaping from filenames in Content-Disposition header. I don't think this is a security concern because:
* CRLF injection is prevented by Golang itself https://github.com/golang/go/commit/2c420ece67e25c7692e28f641d374deb0bec9b7d
* The recipient is responsible for dealing with malicious filenames https://tools.ietf.org/html/rfc6266#section-4.3
* We remove path separators on upload https://github.com/mattermost/mattermost-server/blob/master/app/file.go#L295
Let me know if there are other security implications to consider.
https://mattermost.atlassian.net/browse/PLT-7740
> PLT-7740 Update encoding of filename in file headers

- app/channel.go
- app/import.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/post_store.go
- store/storetest/team_store.go
- store/storetest/user_store.go
`MaxChannelsPerTeam` and `MaxUsersPerTeam` are the only config values the stores rely on. Imo they aren't enough to justify a dependency on `utils.Cfg` and it's better to just add arguments to `ChannelStore.Save` and `TeamStore.SaveMember`. This makes that change for the former (The latter is in [this PR](https://github.com/mattermost/mattermost-server/pull/7691).).
It also fixes an off-by-one error, which made the actual channel limit `MaxChannelsPerTeam+1` per team and adds a unit test for it.
N/A
N/A
> Refactor max channels per team enforcement (and fix off-by-one)

- app/auto_users.go
- app/team.go
- manualtesting/manual_testing.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/team_store.go
- store/storetest/user_store.go
See https://github.com/mattermost/mattermost-server/pull/7690
Previously, the tests assumed that they were running in an environment where the config value was left as the default. Now they no longer depend on the configuration at all.
N/A
N/A
> Refactor max users per team enforcement

- api/apitestlib.go
- api/command_loadtest_test.go
- api/file_test.go
- api/post_test.go
- api/user_test.go
- api/webhook_test.go
- api4/apitestlib.go
- api4/user_test.go
- api4/webhook_test.go
- app/channel_test.go
- app/diagnostics.go
- app/diagnostics_test.go
- model/config.go
I'm aiming to make it impossible for tests to contaminate global state. That means I'm eliminating all of this sort of thing:
```go
prevX = utils.Cfg.X
defer func() {
utils.Cfg.X = prevX
}()
utils.Cfg.X = testXValue
```
There is a lot of code that can just be deleted. This doesn't cover all of it. Just some that I covered by hand. I'll have some follow up reviews to get the rest.
N/A
N/A
> Reduce cfg boilerplate

- app/post.go
- model/post_list.go
- model/post_list_test.go
Fixes the order of search results using OR (notifications) so that they are in the right order, even if the terms include hashtags (which results in two separate queries being issued).
https://mattermost.atlassian.net/browse/PLT-7822 - there will be a separate fix coming for this ticket when using the Elasticsearch backend, as the bug is actually different in that case.
> PLT-7822: Fix search order for SQL search backend.

- api/webhook_test.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/post.go
Previously, large attachments would fail to post. Now they get truncated. Requests with multiple attachments get split into multiple posts if possible.
This also fixes some bugs with the previous splitting logic:
* Splitting logic for the post body now splits on UTF8 runes, not bytes. Previously, the effective limit for UTF8 was smaller than it should have been, and UTF8 characters could have been split in the middle, resulting in corrupted posts.
* When post bodies are split, attachments are no longer duplicated as well. Attachments will now always appear just once each, beginning with the last post that contains part of the post body.
As an example, a post with a large message, two small attachments, and a large attachment might result in 3 posts:
1. The first part of the message
2. The …
> PLT-7599: webhook post splitting

- api4/plugin.go
- api4/plugin_test.go
- app/plugins.go
- cmd/platform/server.go
- i18n/en.json
- model/client4.go
- model/config.go
- model/plugins_response.go
- model/plugins_response_test.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
Description of states:
* **Installed** - Plugin is uploaded into the /plugins directory but not running
* **Activated** - Plugin was previously installed and is now running
* **Uninstalled** - Plugin does not exist on the server
To install and activate:
1. Upload a plugin through the API or manually places the plugin in the /plugins directory
2. Hit the API for activating the plugin or set `PluginStates: {"mypluginid": {"Enable": true}}` under `PluginSettings` and reload the config
To deactivate:
1. Hit the API for deactivating the plugin or set `PluginStates: {"mypluginid": {"Enable": false}}` under `PluginSettings` and reload the config
https://mattermost.atlassian.net/browse/PLT-7637
> PLT-7637 Differentiate between installed and activated states for plugins

- app/notification.go
- app/notification_test.go
Fix emoji names that trigger mention, by skipping word of with pattern of `:word:` with the assumption that it's an emoji pattern only.
Jira ticket: [PLT-7701](https://mattermost.atlassian.net/browse/PLT-7701)
> [PLT-7701] Fix emoji names that trigger mention

- Makefile
- cmd/platform/init.go
- model/bundle_info.go
- model/manifest.go
- plugin/api.go
- plugin/hooks.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/options.go
- plugin/pluginenv/search_path.go
- plugin/plugintest/api.go
- plugin/plugintest/hooks.go
- plugin/rpcplugin/api.go
- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/http.go
- plugin/rpcplugin/io.go
- plugin/rpcplugin/ipc.go
- plugin/rpcplugin/main.go
- plugin/rpcplugin/muxer.go
- plugin/rpcplugin/process.go
- plugin/rpcplugin/process_unix.go
- plugin/rpcplugin/supervisor.go
- plugin/supervisor.go
- scripts/license-check.sh
- store/constants.go
- store/sqlstore/file_info_store.go
- utils/i18n.go
- utils/inbucket.go
- utils/logger/log4go_json_writer.go
- utils/logger/logger.go
- utils/time.go
I knew this would find a ton of violations when I eventually got around to it. Admittedly, a lot of them were made by me, but a lot of them weren't.
Output looks like this:
```
FAIL: /Users/chris/go/src/github.com/mattermost/mattermost-server/enterprise/oauth/google/google.go is missing a license header.
1 file is missing a license header.
make: *** [check-licenses] Error 1
```
Enterprise fixes: https://github.com/mattermost/enterprise/pull/222
https://mattermost.atlassian.net/browse/PLT-7264?filter=14400
N/A
> PLT-7264: add missing license headers, test to makefile

- config/default.json
- i18n/en.json
- model/config.go
Configurable timeout for Elasticsearch requests.
https://mattermost.atlassian.net/browse/PLT-7976
> PLT-7976: Configurable timeout for Elasticsearch requests.

- api/admin.go
- api/apitestlib.go
- api/status_test.go
- api/user.go
- api4/saml.go
- api4/user_test.go
- app/admin.go
- app/app.go
- app/authentication.go
- app/oauth.go
- app/oauth_test.go
- app/plugins.go
- app/saml.go
- app/server.go
- app/session.go
- app/session_test.go
- app/user.go
- app/user_test.go
- jobs/server.go
- jobs/workers.go
- model/config.go
- utils/config.go
- web/web.go
This replaces a bunch of utils.Cfg / utils.CfgFileName references, and eliminates the global session cache by moving it into `app.App`.
Hoping that relatively soon I can elegantly make the tests run using temporary config files.
N/A
N/A
> Remove more global refs / state

- utils/config.go
Ran into some trouble trying to put together a plugin. Maps with user-controlled keys in Viper configurations don't really work. In particular, periods in map keys make weird things happen. So reverse-dns plugin ids like "com.mattermost.plugins.jira" weren't working.
See https://github.com/spf13/viper/issues/324 and https://github.com/spf13/viper/issues/348.
~~I think it's probably best if we just avoid maps in configurations.~~
~~@jasonblais Are we okay with a breaking change for the JIRA plugin? Users would have to reconfigure it.~~
~~I'll need to put in a webapp PR as well, so no one merge this until I do that.~~
Edit: Figured out a less impactful workaround. Let's just go with that for now.
N/A
N/A
> Fix plugin config parsing

- app/notification.go
- app/notification_test.go
I realize I forgot to add some tests for the push part when the user is in DND mode.
Doing the tests I discovery my logic was totally wrong.
This PR fixes the wrong logic and when MM is checking if need to send a push to the user if the users status is set to DND it will block that.
N/A
> fix push notification when user status is in DND

- Makefile
Fixed GOPATH in makefile to prevent make mock-store from rewriting mattermost-server imports
> make mock-server fix

- api/admin_test.go
- api/api_test.go
- api/apitestlib.go
- api/file_test.go
- api/user.go
- api/user_test.go
- api4/api_test.go
- api4/apitestlib.go
- api4/saml.go
- api4/user.go
- app/admin.go
- app/analytics.go
- app/app.go
- app/app_test.go
- app/apptestlib.go
- app/plugins.go
- app/post_test.go
- app/saml.go
- app/user.go
- app/user_test.go
- cmd/platform/test.go
- cmd/platform/user.go
- store/sqlstore/store_test.go
- utils/config.go
- utils/config_test.go
- utils/file_test.go
- utils/mail_test.go
- web/web_test.go
Mostly localized changes to replace more `utils.Cfg` references with propagated references. After this, there's about 75 left in the repo.
The things that need careful review here are the changes to utils/config.go. I've renamed `LoadConfig` to `LoadGlobalConfig`. I'm working on eliminating that function entirely, and as a start, I've separated bits and pieces out of it into new functions (`FindConfigFile`, `EnsureConfigFile`, `ReadConfig`, `ReadConfigFile`). All of these are stateless and safe for concurrent use, with no side-effects (other than the obvious and documented effects of `EnsureConfigFile`). The `EnableConfigFromEnviromentVars` [sic] function was removed as part of this, as the effects of calling it were both global and completely irreversible.
N/A
> Refactoring cfg refs and load / save functions

- store/sqlstore/channel_store.go
- store/sqlstore/user_store.go
- store/storetest/channel_store.go
The search code was changed to split up all search terms so searching for "town square" searched for a channel with a name starting with "town" and with "square", so that obviously didn't work. Those changes to the search code also fixed an issue where "~town square town" autocompleted to "~town-square" because it's now using a like statement instead of the previous full text search that ignored the extra word
https://mattermost.atlassian.net/browse/PLT-6071
https://mattermost.atlassian.net/browse/PLT-8004
> PLT-6071/PLT-8004 Fixed not being able to autocomplete 'Town Square'

- api/channel.go
- api4/channel.go
- api4/channel_test.go
- app/channel.go
- model/client4.go
- Follow up PR to #7619 and #7726 
- Add post' root ID to APIv4 `addChannelMember` to render added user (as system post) at RHS. Feature is requested while testing `webapp` https://github.com/mattermost/mattermost-webapp/pull/149#pullrequestreview-72349879
Note that corresponding APIv3 was not updated.
Jira ticket: [PLT-7362](https://mattermost.atlassian.net/browse/PLT-7362)
> [PLT-7362] Add post' root ID to APIv4 addChannelMember to render added user (as system post) at RHS

- app/command_msg.go
- app/command_msg_test.go
Before: When you use that command, you'll sometimes be switched to another team. This seems to be the same team each time, and it'll happen unless you're already viewing that team.
After: When you use that command, you stay on your current team.
https://mattermost.atlassian.net/browse/PLT-8001
> Fix /msg switching teams

- api/user.go
- api4/user.go
- api4/user_test.go
- app/user.go
- app/user_test.go
- i18n/en.json
Just replaces our LDAP check and error message with a check and error message for all SSO users.
https://mattermost.atlassian.net/browse/PLT-7932
> PLT-7932: prevent deactivation of sso users

- app/user.go
- app/user_test.go
When `RestrictCreationToDomains` is used, this prevents users from changing their email address to anything outside of those domains.
https://mattermost.atlassian.net/browse/PLT-7863
> PLT-7863: prevent users from changing email addresses to restricted domains

- app/diagnostics.go
ElasticsearchSettings: LiveIndexingBatchSize, BulkIndexingTimeWindowSeconds
LdapSettings: EnableSync
SamlSettings: EnableSyncWithLdap
> Update diagnostics.go with missing config settings

- utils/config.go
The viper singleton shouldn't be used anymore.
N/A
N/A
> config watcher fix

- cmd/platform/server.go
This makes the Elasticsearch startup happen asynchronously, so that if there is a delay connecting to Elasticsearch it doesn't block the rest of the app startup sequence.
https://mattermost.atlassian.net/browse/PLT-8011
> PLT-8011: Make Elasticsearch startup fully async.

- app/app.go
- app/plugins.go
- cmd/platform/server.go
The built-in plugin routes need to be registered before the others.
https://mattermost.atlassian.net/browse/PLT-8060
N/A
> PLT-8060: fix builtin plugin http router

- app/diagnostics.go
- model/manifest.go
- model/manifest_test.go
Add UI settings to the plugin manifest for defining configuration settings to display in the system console.
Part of https://mattermost.atlassian.net/browse/PLT-7709
> PLT-7709 Add UI settings to plugin manifest

- model/manifest.go
Just adding basic some documentation to be parsed out by the dev site.
See https://github.com/mattermost/mattermost-developer-documentation/pull/34
It'll be used to populate this page: http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/manifest-reference/extend/manifest-reference/
N/A
N/A
> Basic manifest docs

- tests/test-attachments.md
Test files are in a folder on Drive now (not Dropbox). Updating the link to the folder.
> Update with new link to mm_file_testing in Drive

- Makefile
Recreates the `client` symlink so that changing mattermost-webapp repo locations with the `BUILD_WEBAPP_DIR` environment variable works smoothly.
n/a
n/a
> Fixes running webapp from custom location using ENV variable.

- .codecov.yml
- app/command_channel_header_test.go
Adds a codecov yaml file, which can be used to exclude directories from coverage reports and altar Codecov behavior in several ways.
Also adds a test for demo purposes.
N/A
N/A
> Add codecov yaml file

- model/manifest.go
- model/manifest_test.go
Needed a placeholder field and decided to add a user_autocomplete type to plugin manifest.
Part of https://mattermost.atlassian.net/browse/PLT-7709
> Add placeholder field and user_autocomplete type to plugin manifest

- app/plugins.go
- utils/file.go
- utils/file_test.go
Replace os.Rename with directory copy util in plugin extraction. os.Rename was causing issues on some Unix systems. Also fixes a bug where some error handling got missed.
https://pre-release.mattermost.com/core/pl/33r7s7s8i3ypfxga1umwpj5jth
https://mattermost.atlassian.net/browse/PLT-8125
> PLT-8125 Replace os.Rename with directory copy util in plugin extraction

- utils/mail.go
This prevents auto-responses from out-of-office agents.
Sets the `Auto-Submitted` and `Precedence` headers so that e.g. out-of-office agents to not respond to mattermost mails.
#7740
> 7740: Set auto-submitted and precedence headers for emails

- app/command_groupmsg.go
Was getting a compilation error but I have no clue about the wider context here so I'm relying on the original reviewers to figure out if this change makes sense.
https://github.com/mattermost/mattermost-server/pull/7419
> PLT-7111: Fix for groupmsgProvider.GetCommand method signature.

- app/app.go
- app/options.go
- cmd/platform/config_test.go
- cmd/platform/init.go
- cmd/platform/platform_test.go
- cmd/platform/server.go
- utils/config.go
- utils/config_test.go
* `FindConfigFile` now works if the given path is an absolute path. This fixes the `config validate` CLI command with absolute paths.
* `app.New` now accepts a `ConfigFile` option and that option is set by the app construction in cmd/platform. This fixes the config CLI argument being ignored.
* Added a few tests and clarified behavior of relevant utils functions.
* Fixes #7838
https://mattermost.atlassian.net/browse/PLT-8149
> PLT-8149: Fix config path overrides (master)

- app/app.go
- app/options.go
- cmd/platform/cli_test.go
- cmd/platform/init.go
- cmd/platform/server.go
- utils/config.go
- utils/config_test.go
https://github.com/mattermost/mattermost-server/pull/7850 with slight changes to the tests for 4.4
* `FindConfigFile` now works if the given path is an absolute path. This fixes the `config validate` CLI command with absolute paths.
* `app.New` now accepts a `ConfigFile` option and that option is set by the app construction in cmd/platform. This fixes the config CLI argument being ignored.
* Added a few tests and clarified behavior of relevant utils functions.
* Fixes #7838
https://mattermost.atlassian.net/browse/PLT-8149
> PLT-8149: Fix config path overrides (release-4.4)

- cmd/platform/mattermost_test.go
I really want to make sure we don't see another config flag / discovery regression, especially since I have major refactors for our config code in my sights.
I added a test for `config validate` in the other PR, but every other command loads the config a little differently. Wanted to make sure that codepath was covered too.
N/A
> Add one more config test

- cmd/platform/config.go
- cmd/platform/config_test.go
- cmd/platform/mattermost_test.go
Makes it usable by non-humans as well.
N/A
> make `config validate` exit with non-zero code on failure

- api/admin.go
- api/user.go
- app/authentication.go
- app/user.go
- model/config.go
- utils/password.go
- utils/password_test.go
This separates the *massive* `SetDefaults` method in models/config.go into several `SetDefaults` methods, one for each settings struct. In addition to enforcing better organization, this makes testing easier when functions don't require the full configuration. This is demonstrated with a refactor of `utils.IsValidPassword`, which is now purely functional (doesn't use any global state) and has clean unit tests with 100% coverage.
N/A
> Refactor password validation and config defaults

- app/user.go
To alert other clients of the logged-in user that the user's profile image changed.
https://mattermost.atlassian.net/browse/PLT-8103
> PLT-8103 Include current user in WebSocket update event when setting profile image

- api/api.go
- api/user.go
- api4/api.go
- app/app.go
- app/apptestlib.go
- app/email.go
- app/email_batching.go
- app/notification.go
- app/session.go
- app/user.go
- cmd/platform/user.go
- utils/html.go
- utils/html_test.go
- web/web.go
The goal of this was to eliminate global state in the template code, improve testability, increase coverage, and eliminate races.
* `(*utils.HTMLTemplate).addDefaultProps` (a global config offender) is now part of a new method `(*app.App).NewEmailTemplate`. Calls to `utils.NewHTMLTemplate` that required the props set by that function have been replaced.
* `utils.InitHTML` and `utils.InitHTMLWithDir` have been removed. The template directory watching functionality is now encapsulated by a new `HTMLTemplateWatcher` struct instead of being global. `app.App` now owns an instance of this type.
* The code in `utils/html.go` has brand new tests with much better coverage than before.
N/A
> Refactor HTML template code

- app/server.go
Now looks like this when people forget to `setcap`:
```
[2017/11/16 20:10:52 CST] [EROR] Unable to setup forwarding: listen tcp :80: bind: permission denied
```
Slightly better.
N/A
N/A
> Add error message to forwarding log error

- config/default.json
- model/config.go
- utils/config.go
Adds config property `EnablePreviewFeatures` to the config for enabling/disabling the display of the advanced preview features in the user settings. The default is `true`.
webapp: https://github.com/mattermost/mattermost-webapp/pull/333
> Hide pre-release features section of advanced settings pane.

- app/email.go
- app/email_batching.go
- app/notification.go
- app/security_update_check.go
- utils/mail.go
- utils/mail_test.go
Just moves `utils.SendMail`, a one-liner which uses the global configuration, to `app.App`.
N/A
N/A
> SendMail refactor

- app/command.go
There are many backend proxy layers that can easily block header. We've added this to pass those requirements.
cc @dmeza
> Add token to header for commands

- app/notification.go
- config/default.json
- model/config.go
Add config option to place channel name instead of team name. For servers with users primarily on single team, the email notifications have no context in the subject without the channel name.
@dmeza
> Replace Channel Name for Team in Email Notifications

- config/default.json
In [this issue](https://mattermost.atlassian.net/browse/PLT-7475), it says that the UI text should be `Help Text: (Optional) AWS region you selected when creating your S3 bucket. If no region is set, Mattermost attempts to get the appropriate region from AWS, or sets it to "us-east-1" if none found.` 
The [Mattermost documentation](https://docs.mattermost.com/administration/config-settings.html#amazon-s3-region) says the default for this value is `""`, but it's set here. For this reason the behavior described above (getting the appropriate region from AWS, then falling back to `us-east-1` only if that fails) **does not happen**; Mattermost tries region `us-east-1` even if `AmazonS3Endpoint` points to a different region.
Stop forcing AmazonS3Region of `us-east-1` by default
Closes …
> Don't force AmazonS3Region by default

- api4/user_test.go
- app/diagnostics.go
- app/ldap.go
- app/oauth.go
- config/default.json
- model/config.go
- utils/config.go
Again, this might not be the right approach given the growth of the platform. But this api allowed critical exploit of user auth to change their auth type. It was blocked completely.
> Add Config to disable Auth Transfers.

- app/channel.go
- app/post.go
- app/post_test.go
- model/post.go
- model/post_test.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/SqlStore.go
This adds hints to posts that the client can use to identify and build channel links when the user isn't in those channels and the client has no knowledge of them.
It's a resubmission of the server portion of https://github.com/mattermost/mattermost-server/pull/7324 with some optimizations. We held off on merging it last time so we could load test it.
https://mattermost.atlassian.net/browse/PLT-5458
> PLT-5458: If someone posts a channel link to channel_A that you don't belong to, it doesn't render properly

- plugin/plugintest/mock/mock.go
- plugin/plugintest/plugintest.go
So this is a little weird, but I don't think there's any other way to make this kind of thing compile:
https://github.com/mattermost/mattermost-plugin-jira/blob/master/plugin_test.go
The problem is that we vendor testify/mock, and external packages can't import our vendored packages. So to be able to use things like `mock.AnythingOfType` with the plugintest mocks, we have to expose it like this.
N/A
N/A
> Expose vendored mock package with plugintest/mock

- Makefile
Adds the `mattermost_test` database to the docker run command for the postgres container so that one doesn't need to create it manually.
n/a
> Adds dev db for postgres so that one doesn't need to make it manually.

- model/config.go
- model/config_test.go
Changed config behaviour such that exportFromTimestamp is set/unset when message export is enabled/disabled
https://mattermost.atlassian.net/browse/PLT-8198
> PLT-8198: Set the message export timestamp to the date feature was enabled, and remove the setting from the System Console

- plugin/example_hello_user_test.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
- plugin/rpcplugin/supervisor.go
- plugin/rpcplugin/supervisor_test.go
- plugin/supervisor.go
`OnActivate` needs to be called again when plugins are relaunched. This moves that responsibility from the environment to the supervisor.
https://mattermost.atlassian.net/browse/PLT-8282
> PLT-8282: call OnActivate after plugin crash, update example

- i18n/en.json
- store/sqlstore/channel_member_history_store.go
- store/store.go
- store/storetest/channel_member_history_store.go
- store/storetest/mocks/ChannelMemberHistoryStore.go
Changed the way that the purge method in the ChannelMemberHistory store works to better follow the pattern used in other stores that can be cleaned up by the Data Retention job. 
In order to get the tests to run cleanly, I had to differentiate between purging all records, and purging records for a specific channel, because all tests share the database, and permanent deletes can trash data that other tests depend on.
https://mattermost.atlassian.net/browse/PLT-8233
> PLT-8233: Purge ChannelMemberHistory Data when Data Retention Job runs

- app/plugin.go
- i18n/en.json
- model/manifest.go
- model/plugin_key_value.go
- store/sqlstore/plugin_store.go
- store/sqlstore/upgrade.go
Resubmit of #7915. Apparently my key length calculation was off a little bit. Lowered the plugin ID length to 190 to fit and tested both new table and upgrading against a MySQL 5.6 database.
> Resubmit: Hash key for plugin store and limit id length

- plugin/rpcplugin/api.go
- plugin/rpcplugin/api_test.go
This apparently is necessary for any types transferred via `interface{}`. :-/
https://mattermost.atlassian.net/browse/PLT-8301
> PLT-8301: make slack attachments gobable

- model/config.go
- model/config_test.go
- utils/file.go
- utils/file_backend_test.go
Removed export directory config setting, in favour of hard-coding it to an 'export' directory under the local file directory. Improved the local file backend copy implementation to implicitly create the destination directory if it's missing
https://mattermost.atlassian.net/browse/PLT-8314
> PLT-8314: Test Message Export Against S3 Bucket

- api4/user.go
- api4/user_test.go
- cmd/platform/user.go
Allow deactivation of SSO users through the API and CLI.
Needs PM review on the text printed when deactivating an SSO user through the CLI:
```
You must also deactivate this user in the SSO provider or they will be reactivated on next login or sync.
```
https://mattermost.atlassian.net/browse/PLT-8100
> Allow deactivation of SSO users

- app/channel.go
- i18n/en.json
- model/post.go
Fixes case 3 of #6483. Adds a system message when a user joins a team. This completes this merged [PR](https://github.com/mattermost/mattermost-server/pull/7752) on the server side and this [other one](https://github.com/mattermost/mattermost-webapp/pull/244) on the client side.
https://mattermost.atlassian.net/browse/PLT-6217
> PLT-6217-bis Fixes system message posted to Town Square when a user joins a team #7863

- config/default.json
- model/config.go
- utils/config.go
Add config option to hide tutorial screens. The tutorial doesn’t necessarily apply, rather than choose parts to show and not others, we’ve added a config to be sent to frontend.
web pr: https://github.com/mattermost/mattermost-webapp/pull/325
cc @dmeza
> Hide tutorial with config

- api4/plugin_test.go
- app/app.go
- app/apptestlib.go
- app/command.go
- app/plugin.go
- app/plugin_api.go
- app/plugin_test.go
- cmd/platform/server.go
- i18n/en.json
- plugin/api.go
- plugin/hooks.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
- plugin/plugintest/api.go
- plugin/plugintest/hooks.go
- plugin/rpcplugin/api.go
- plugin/rpcplugin/api_test.go
- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/hooks_test.go
* Adds two new plugin APIs: `RegisterCommand` and `UnregisterCommand`.
* Adds a new plugin Hook: `ExecuteCommand`
So now plugins can implement slash commands:
```go
type HelloUserPlugin struct {}
func (p *HelloUserPlugin) OnActivate(api plugin.API) error {
api.RegisterCommand(&model.Command{
Trigger: "pcmd",
})
return nil
}
func (p *HelloUserPlugin) ExecuteCommand(args *model.CommandArgs) (*model.CommandResponse, *model.AppError) {
if args.Command == "/pcmd" {
return &model.CommandResponse{
ResponseType: model.COMMAND_RESPONSE_TYPE_IN_CHANNEL,
Text:         "hello!",
}, nil
}
return nil, model.NewAppError("ExecuteCommand", "this is an error", nil, "", http.StatusBadRequest)
}
```
N/A
> Add plugin slash command support

- api/webhook.go
- api4/webhook.go
We were comparing the session's user id to the wrong thing.
https://mattermost.atlassian.net/browse/PLT-8360
> PLT-8360: Fix invalid permission error when updating webhooks

- app/channel.go
Do not auto-join 'off-topic' channel if it is private channel.
This PR contains server side change for issue #7775 
Corresponding client side PR:
https://github.com/mattermost/mattermost-webapp/pull/418
#7775 
> issue #7775: Do not auto-join 'off-topic' channel if it is private

- api4/params.go
- api4/system.go
- api4/system_test.go
- app/admin.go
- model/client4.go
* Add new request parameter `logs_per_page`
* Set default value of per_paging for logs to 10000 (for backward compatibility)
* Read logs from end of log file
* Revert #6697
[PLT-6896](https://mattermost.atlassian.net/browse/PLT-6896)
#6724
* [PLT\-6896 Fix descriptions of \`/logs\` by kaakaa · Pull Request \#310 · mattermost/mattermost\-api\-reference](https://github.com/mattermost/mattermost-api-reference/pull/310)
> PLT-6896 per-paging for logs

- store/sqlstore/post_store.go
- store/storetest/post_store.go
This was not the issue I expected to find when investigating this test failure.
Turns out there were multiple mistakes in both the test and the function being tested, and it just so happened that _usually_ (if the test ran at a certain speed) the test passed.
N/A
> Fix GetPostsCreatedAt bug / test

- api4/reaction_test.go
Fails at high speeds ([example](https://build.mattermost.com/job/mattermost-platform-pr-split/932/consoleFull)). If two or more of the reactions have the same CreateAt time, the order that they're returned in is undefined. So `reflect.DeepEqual` can't be used like this.
N/A
> Fix reaction test

- app/notification.go
- app/notification_test.go
Fire "mention" when `channel user count <= max allowed number`. 
Previously when `channel user count == max allowed number`, notification was not filed because of the wrong conditional statement in place.
https://github.com/mattermost/mattermost-server/issues/7969
> Plt 8350 fire mention when channel user count smaller or equals to max allowed number

- config/default.json
- model/config.go
- utils/config.go
Adds a config value  "DefaultTeamName" that allows to config the name of a default team:
```
"TeamSettings": {
"DefaultTeamName": ""
```
CC @dmeza
> Allow default team to be configured

- model/config.go
Set default for DefaultTeamName setting if not present in config.
> Set default for DefaultTeamName setting if not present in config

- store/sqlstore/user_store.go
- store/storetest/user_store.go
Fix user search so it doesn't error when the cleaned-up query ends up just being whitespace.
https://mattermost.atlassian.net/browse/PLT-8354
> PLT-8354: Fix user search error when terms end up as empty space.

- api4/team_test.go
Summary
When user invite email subject is customized on language file, this test fails. This change allows for custom subject in TestInviteUsersToTeam.
This is the test: go test -v -run='TestInviteUsersToTeam' ./api4
> Allow for custom subject in TestInviteUsersToTeam

- i18n/en.json
Spotted during another change, this fixes the typo `api.incoming_webhook.disabled.app_errror` to
match `api.incoming_webhook.disabled.app_error` as used in the code.
> fix i18n identifier

- api4/webhook_test.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/incoming_webhook.go
- model/incoming_webhook_test.go
- store/sqlstore/upgrade.go
This issue exposes a Username and Profile Picture configuration for incoming webhooks to override the defaults:
It remains possible to override the Username and Profile Picture when posting the webhook. These settings are tied to the "Enable integrations to override usernames" and "Enable integrations to override profile picture icons" configurations respectively.
https://github.com/mattermost/mattermost-server/issues/7880
> [PLT-8173] Add username and profile picture to webhook set up pages

- app/user.go
This will allow other clients (tabs, mobile, etc.) to be notified of updates to the logged-in user, instead of just other users.
Server portion of https://mattermost.atlassian.net/browse/PLT-8352
> PLT-8352 Don't omit current user from updated user WS event

- config/default.json
- model/config.go
- utils/config.go
This PR adds the following properties to the Email, LDAP, and SAML settings in the config:
- LoginButtonColor
- LoginButtonBorderColor
- LoginButtonTextColor
These properties allow the category login buttons to have different styles applied for white labeling purposes.
via @jarredwitt
> Add color properties to config to white label login buttons

- api4/webhook_test.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/incoming_webhook.go
- model/incoming_webhook_test.go
- store/sqlstore/upgrade.go
This addresses some feedback from https://github.com/mattermost/mattermost-api-reference/pull/315, tweaking nomenclature related to https://github.com/mattermost/mattermost-server/issues/7880.
https://github.com/mattermost/mattermost-server/issues/7880
> [PLT-8173] Strip the post_ prefix on incoming webhook overrides.

- config/default.json
- model/config.go
- utils/config.go
Rename DefaultTeamName to ExperimentalPrimaryTeam based on discussion on `webapp` PR: https://github.com/mattermost/mattermost-webapp/pull/334
> rename DefaultTeamName to ExperimentalPrimaryTeam

- store/sqlstore/post_store.go
Add join/leave team system messages to the ignored list of messages type to
count as unread messages in channels.
This only solve the backend part of the problem, the frontend part (mattermost/mattermost-webapp#552) is not needed to merge this, but to close the issue both PRs have to be merged.
[PLT-8483](https://mattermost.atlassian.net/browse/PLT-8483)
> PLT-8483: Ignore join/leave team messages for unread counts

- store/sqlstore/channel_store.go
- store/sqlstore/user_store.go
- store/storetest/channel_store.go
This PR partially reverts the switch to LIKE searching from FULLTEXT searching when searching for channels. The intention is to get the best of both worlds - matching on any word in the channel name, not just the first, but also being able to search stop words. This is achieved by combining both search techniques with an `OR` in a single query.
There is one small draw back with this: in order to be able to match on full words, not just their stems, in PostgreSQL, we need to relax the strict matching criteria. This means, for example that typing `~off-topics` into the search will match the channel name with `off-topic`. This limitation is not applicable on MySQL.
https://mattermost.atlassian.net/browse/PLT-8312
> PLT-8312: Use combined LIKE/Full Text search for channels.

- cmd/platform/platform_test.go
This (kinda) fixes the race condition that caused this failure: https://build.mattermost.com/job/mattermost-platform-pr-split/1041/
Whenever the configuration is reloaded, the logger is reconfigured. Reconfiguring the logger has a decent chance of blowing things up any time there are other goroutines that may be using it. This doesn't fix that. That's a more difficult thing to fix (but I am working on it).
This just disables the config watching during the CLI tests since it's really not necessary and it'll ensure we won't see the problem again for them.
N/A
N/A
> Disable config watching during CLI tests

- api4/user.go
- api4/user_test.go
- app/session.go
- i18n/en.json
- model/client4.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
Adds a new endpoint called `/users/tokens` which gets all tokens for all users if one has the `manage_system` permission.
- [Documentation PR](https://github.com/mattermost/mattermost-api-reference/pull/318)
- [Webapp PR](https://github.com/mattermost/mattermost-webapp/pull/496)
- [Server PR](https://github.com/mattermost/mattermost-server/pull/8038)
- Redux PR
- [Jira](https://mattermost.atlassian.net/browse/PLT-7793)
- [Github](https://github.com/mattermost/mattermost-server/issues/7584#issuecomment-352808489)
> [PLT-7793] Added /users/tokens endpoint

- api/context.go
- api/general.go
- api/user.go
- api4/context.go
- api4/system.go
- api4/team_test.go
- app/app.go
- app/diagnostics.go
- app/diagnostics_test.go
- app/email.go
- app/notification.go
- app/security_update_check.go
- app/web_conn.go
- cmd/platform/server.go
- utils/config.go
- utils/config_test.go
- utils/license.go
Feels like it's been a while since my last refactor PR. This one removes some of the config globals. I was hoping to remove `utils.Cfg`, but this had to come first.
N/A
> Remove utils.ClientCfg and utils.ClientCfgHash

- app/channel.go
- app/team.go
- model/post.go
The previous PR changed this so that the "user was removed from channel" message said "user was removed from team", and that message was posted for both actions. This splits them out so that there's a proper "user was removed from team" message.
https://mattermost.atlassian.net/browse/PLT-8522
> PLT-8522 Added separate messages for being removed from channel or team

- api/apitestlib.go
- api4/apitestlib.go
- app/admin.go
- app/app.go
- app/app_test.go
- app/apptestlib.go
- app/config.go
- app/options.go
- cmd/platform/init.go
- cmd/platform/server.go
- utils/config.go
- web/web_test.go
* `utils.watcher`, `utils.CfgDisableConfigWatch`, `utils.InitializeConfigWatch`, `utils.DisableConfigWatch`, and `utils.EnableConfigWatch` are all gone.
* The code from the above now lives in the `utils.ConfigWatcher` struct.
* `app.App` instances now own `utils.ConfigWatcher` instances.
* `app.New` can now return an error instead of a new `App` instance. This is to preserve the old error behavior after the above changes.
* Config-related `app.App` methods have been moved to a new file, app/config.go.
* `utils.LoadGlobalConfig` has been split. The reusable stuff is now in `utils.LoadConfig`.
N/A
N/A
> Remove global config watcher

- api4/user.go
- api4/user_test.go
- app/session.go
- i18n/en.json
- model/client4.go
- model/user_access_token_search.go
- model/user_access_token_search_test.go
- model/user_access_token_test.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
Adds a new endpoint called `/users/tokens/search` which gets all tokens based on the search term if one has the `manage_system` permission.
- [Documentation PR](https://github.com/mattermost/mattermost-api-reference/pull/320)
- [Webapp PR](https://github.com/mattermost/mattermost-webapp/pull/496)
- [Server PR](https://github.com/mattermost/mattermost-server/pull/8088)
- Redux PR
- [Jira](https://mattermost.atlassian.net/browse/PLT-7793)
- [Github](https://github.com/mattermost/mattermost-server/issues/7584#issuecomment-352808489)
> [PLT-7793] Add /users/tokens/search endpoint

- api4/oauth.go
Redirect error URI when OAuth SSO is setup but account creation is disabled.
Note: I think the client app should not show `Create one now` in the first place whenever account creation is disabled. The only downside is that the user will never know if account creation is disabled by the system admin.
Jira ticket: [PLT-8531](https://mattermost.atlassian.net/browse/PLT-8531)
> [PLT-8531] Redirect error URI when OAuth SSO is setup but account creation is disabled

- app/admin.go
- app/app.go
- app/app_test.go
- app/config.go
- app/config_test.go
- app/plugin.go
- cmd/platform/mattermost_test.go
- cmd/platform/message_export_test.go
- cmd/platform/server.go
- jobs/schedulers.go
- jobs/server.go
- jobs/workers.go
- utils/config.go
- utils/config_test.go
- utils/logger/logger.go
- utils/mail_test.go
- utils/redirect_std_log_test.go
This eliminates very nearly all of the remaining global config state. Next PR will eliminate the rest. Then I'll be making some big improvements to stability (like actually making all of this stuff thread-safe) and deleting boilerplate throughout our tests.
Enterprise PR: https://github.com/mattermost/enterprise/pull/251
N/A
N/A
> Remove global cfg vars

- api/user.go
PR: Allow deactivation of SSO users #7952 https://github.com/mattermost/mattermost-server/pull/7952
reverted to allow deactivation of SSO user on api4 but not api3. This PR reverts those changes for api3.
The changes were originally made with this PR: PLT-7932: prevent deactivation of sso users #7759: https://github.com/mattermost/mattermost-server/pull/7759
> Allow deactivation of SSO users api3

- cmd/platform/server.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
Move session clean-up to daily task instead of on every session save and gets.
https://mattermost.atlassian.net/browse/ABC-73
> ABC-73 Move session clean-up to daily task

- api/apitestlib.go
- api/oauth_test.go
- api/team_test.go
- api4/apitestlib.go
- api4/post_test.go
- api4/team_test.go
- api4/user_test.go
- app/app_test.go
- app/apptestlib.go
- app/config.go
- app/diagnostics_test.go
- app/license.go
- app/oauth_test.go
- app/user_test.go
- app/webhook_test.go
- cmd/platform/server.go
- jobs/server.go
- manualtesting/manual_testing.go
- utils/config.go
- utils/license.go
This finally eliminates `utils.Cfg` and makes each test run with its own temporary config file (so you don't have to worry about reverting config changes after tests).
N/A
N/A
> Finally remove utils.Cfg

- app/channel.go
- app/team.go
Fixes a case missed in #7961 where leaving the team would still post in town-square when `ExperimentalEnableDefaultChannelLeaveJoinMessages` was set to false.
Heads-up @csduarte and @dmeza in case you need to cherry pick this
https://mattermost.atlassian.net/browse/ABC-85
> ABC-85 Handle missed case with ExperimentalEnableDefaultChannelLeaveJoinMessages setting

- app/channel.go
- app/channel_test.go
- cmd/platform/channel.go
- i18n/en.json
- model/post.go
Post a System message to the affected channel.
This PR will change command semantic from:
`$ platform channel modify myteam:mychannel --private`
to:
`$ platform channel modify myteam:mychannel --private --username`
The reason is described at #7877 issue.
#7877
> Issue #7877: post change channel privacy message

- api4/api.go
- api4/emoji.go
- api4/emoji_test.go
- app/emoji.go
- model/client4.go
- model/emoji_search.go
- model/emoji_search_test.go
- store/sqlstore/emoji_store.go
- store/store.go
- store/storetest/emoji_store.go
- store/storetest/mocks/EmojiStore.go
Add POST /emoji/search and GET /emoji/autocomplete API endpoints.
These are split into two different endpoints because:
* Consistency with other search endpoints, all others are also POSTs
* Don't want to miss out on the benefits of GET for performance important actions like autocompleting (browser/proxy caching, etc.)
* Consistency with user search/autocomplete endpoints
https://mattermost.atlassian.net/browse/ABC-90
> ABC-90 Add POST /emoji/search and GET /emoji/autocomplete API endpoints

- app/command.go
See https://pre-release.mattermost.com/core/pl/66qx8kufcbygtcrc1poidbqkfh
This doesn't impact webhook-based slash commands, and I don't believe any of our built-in commands do any overriding.
https://mattermost.atlassian.net/browse/ABC-126
N/A
> ABC-126: set from_webhook if a builtin slash command overrides username or icon

- app/webhook.go
- model/outgoing_webhook.go
This PR adds support for Slack attachments for outgoing webhook responses.
It also adds support for mentions with <@userid> and announcement tokens (eg. <!here>) in the outgoing webhook responses as implemented in #7615 
The GitHub issue opened for this ticket is #7774
> PLT-3658 Support for Slack attachments in outgoing webhook response (#7774)

- app/team.go
- i18n/en.json
These changes are sort of a follow up to https://mattermost.atlassian.net/browse/PLT-6217 to deal with the inconsistent tenses between system messages ("User added to channel" vs "User was removed from channel"). It also makes sure they all end with periods where applicable.
This is waiting for the changes to release-4.6 containing https://github.com/mattermost/mattermost-server/pull/8078 to be merged into master. The changes specific to this PR are https://github.com/mattermost/mattermost-server/commit/1045ec0aa9918bea036c94f44edb1706a95c7816
- Includes text changes and localization file ([.../i18n/en.json]
> Make system messages always use "User did something" instead of "User has done something"

- api4/channel.go
- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/UserAccessTokenStore.go
As discussed in [this very long thread](https://pre-release.mattermost.com/core/pl/3nzompitxpfi8do54r1xtb7ooa), this changes the autocomplete query to return an arbitrary subset of results rather than the first X in the complete, sorted result set.
The impact on some autocomplete searches on my local database with over ~400,000 in-team channels prefixed with "channel":
| Search Term | Before | After |
|-|-|-|
| ~ | 7.65s | 0.021s |
| ~c | 9.48s | 2.83s |
| ~ch | 9.34s | 1.89s |
| ~cha | 10.60s | 1.48s |
| ~t | 7.68s | 0.592s |
| ~to | 8.32s | 0.027s |
| ~tow | 7.37s | 0.023s |
There are more things I could do to reduce those "~c..." cases down to a few milliseconds as well, but I'm suspecting that 400,000+ matching channels is not the norm, so it would probably be premature to put much …
> ABC-79: Optimize channel autocomplete query

- api/context.go
- api4/context.go
- app/authentication.go
- app/authentication_test.go
- app/ratelimit.go
- app/ratelimit_test.go
- app/server.go
- config/default.json
- model/config.go
Adding user based rate limiting. 
Two stage. Will rate limit on token and on userID.
> ABC-55 User based rate limiting

- app/team.go
- model/websocket_message.go
`app.SoftDeleteTeam` - Add `delete_team` websocket event to notify client (especially those currently viewing the team) whenever a team is deleted, so that client will be able to redirect to his other team membership 
Note: Should I add same WS event to `app.PermanentDeleteTeam`. I didn't add it since it's something we'll remove (?) in the future.
Jira ticket: [PLT-8494](https://mattermost.atlassian.net/browse/PLT-8494)
> [PLT-8494] Add delete_team websocket event

- app/post.go
- app/post_test.go
I originally thought this was a recursion issue since my test string also included deeply nested block quotes. Then I realized Go has an infinite stack size. 🤦‍♂️ This is why automated fuzzing is one of my goals.
https://mattermost.atlassian.net/browse/ABC-210
> ABC-210: Fix image url replacement for blank urls

- app/oauth.go
- utils/api.go
> The Location response header indicates the URL to redirect a page to. It only provides a meaning when served with a 3xx (redirection) or 201 (created) status response.
– https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location
Browsers and clients have varying/undefined behavior when the header is used with other status codes.
This uses HTML redirects for 4xx/5xx status codes.
https://mattermost.atlassian.net/browse/ABC-153
N/A
> ABC-153: don't use http redirects with 4xx/5xx status codes

- cmd/platform/server.go
Currently, if an error occurs when starting the server using `platform server`, the command exit with a 0 exit code (i.e. "success") – although the server failed to launch.
This means it is not possible to know whether the server started successfully or not. From the shell point of view, it started successfully and existed very quickly. Additionally, no error message is printed to the console.
```shell
$ rm config/config.json
$ if bin/platform server; then echo "Success"; else echo "Failure"; fi
Success
```
With this change, the `platform server` command simply reports its errors to `cobra`. When an error occurs while initializing the app (like a missing or invalid configuration file, or missing locales), cobra prints the error to the console, and the shell command exits with a "-1" exit …
> Return an error code to the shell if an error occurs when running `platform server`

- api/user.go
- api/user_test.go
- app/authentication.go
This change changes the authentication checks to be:
* "preflight checks"
** mfa
** not disabled
** login attempts
* password
* "postflight checks"
** email verified
Checking whether the email is verified or not last avoids the weird edge
case where entering any bogus password for an account with an unverified
email shows a message about verifying the email and offering to resend.
Also fix a unit test assertion error along with a typo.
https://mattermost.atlassian.net/browse/ABC-179
> ABC-179: check email verification last

- model/compliance.go
- model/user.go
- model/user_test.go
This centralizes the source of truth on the rules for username / email
processing instead of scattering `strings.ToLower` invocations.
https://mattermost.atlassian.net/browse/ABC-173
> ABC-173: introduce Normalize(Username|Email)

- app/ratelimit.go
- app/ratelimit_test.go
- app/server.go
Currently, initialization errors occurring in `NewRateLimiter` make the function return a nil reference – which is de-referenced just after by the caller, making the server crash.
This PR propagates the error to the caller, which can then log it properly.
It prepares a future PR that will propagate the handful of critical server initialization errors to the command line handler.
> Handle RateLimiter initialization errors

- api/context.go
- api/team.go
- api/user.go
- api4/context.go
- api4/user.go
- app/authentication.go
- app/cluster_discovery.go
- app/compliance.go
- app/config.go
- app/diagnostics.go
- app/email_batching.go
- app/ldap.go
- app/license_test.go
- app/notification.go
- app/oauth.go
- app/post.go
- app/session.go
- app/user.go
- app/web_conn.go
- app/webhook.go
- cmd/platform/server.go
* Added `App.License()`
* Replaced all calls to `utils.IsLicensed` / `utils.License`
The primary objective is to eliminate the licensing global state this week after making the same changes in the enterprise repo and replacing `utils.SetLicense` / `utils.RemoveLicense`.
This also eliminates race conditions:
`utils.IsLicensed() && *utils.License().Features.PasswordRequirements` is not a safe expression. The license could be removed before `utils.License()` is evaluated, resulting in a nil dereference. Hence the decision to remove `IsLicensed` altogether.
This doesn't touch the tests yet. A lot of the save, set, restore code will simply be deleted in the PR that removes the global variable.
This was done by hand. Please check each line to make sure I didn't accidentally negate any …
> add App.License, remove utils.IsLicensed / utils.License calls

- config/default.json
- i18n/en.json
- model/config.go
- model/config_test.go
- utils/config.go
There's some code in there as well to make sure that it still accepts true/false values for any servers like pre-release that are running off master.
https://mattermost.atlassian.net/browse/ICU-715
- Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
> ICU-715 Change ExperimentalGroupUnreadChannels setting to allow for default on/off

- api/apitestlib.go
- api4/apitestlib.go
- app/app_test.go
- app/apptestlib.go
- app/server.go
- app/server_test.go
- cmd/platform/server.go
- cmd/platform/test.go
- web/web_test.go
For now only a handful of critical errors are present in the codebase. They all occur during server startup (in `app.StartServer()`).
Currently, when one of these critical error occurs, it is simply mentioned in the logs – then the error is discarded, and the app attempts to continue the execution (and probably fails pretty quickly in a weird way).
Rather than continuing operations in an unknown state, these errors should trigger a clean exit.
This commit refactor critical startup errors to be correctly propagated, logged, and then terminate the command execution. Additionally, it makes the server return a proper error code to the shell.
n/a
> Abort on critical error during server startup

- api4/apitestlib.go
I'm 2/5 about it, but looks like a debug print forgotten there.
> Remove fmt.Println trace on api4 tests

- api/apitestlib.go
- app/channel.go
- app/channel_test.go
- cmd/platform/channel.go
- cmd/platform/channel_test.go
- i18n/en.json
- model/post.go
changes the text on the success message when moving channels.
@grundleborg I updated some code but the old PR got closed so I opened a new one.
https://mattermost.atlassian.net/browse/PLT-7537
#7876
> PLT-7537: Move channel CLI command posts system message to channel.

- api/api.go
- api/context.go
- api/file.go
- api4/file.go
- api4/oauth.go
- app/app.go
- app/config.go
- app/config_test.go
- model/system.go
- utils/api.go
- utils/api_test.go
- web/web.go
Sign error page parameters so client can verify they're from the server.
https://mattermost.atlassian.net/browse/ABC-132
> ABC-132: sign error page parameters

- api/channel_test.go
- api/post_test.go
- api/team_test.go
- api/user_test.go
- api/webhook_test.go
- api4/channel_test.go
- api4/post_test.go
- api4/team_test.go
- api4/user_test.go
- app/app.go
- app/config.go
- app/license.go
- app/session_test.go
- model/license.go
I love deleting code.
This adds an `(*app.App)SetLicense` function and replaces all calls to `utils.SetLicense`. It also deletes a bunch of crap that we don't need any more. There's no longer any need to restore the config or license state at the end of a test, and there's no need to call `SetDefaultRolesBasedOnConfig` (in a future PR I'll remove the remaining calls and make it a private method).
As a convenience for testing, there's also a new `model.NewTestLicense(features ...string)` function, which can be used to set up a test license with a one liner:
```go
th.App.SetLicense(model.NewTestLicense("mfa"))
```
There's a lot more stuff to delete in future PRs. And of course, I'll finish eliminating the license globals entirely after another PR or two hopefully.
N/A
N/A
> Eliminate utils.SetLicense calls

- model/authorize.go
- model/authorize_test.go
- store/sqlstore/oauth_store.go
- store/sqlstore/upgrade.go
Increase OAuth2 state parameter limit from 128 to 1024.
https://mattermost.atlassian.net/browse/ABC-239
> ABC-239 Increase OAuth2 state parameter limit

- api4/role.go
- api4/role_test.go
- i18n/en.json
- model/role.go
This adds the license check to `patchRoles()`, which provides enforcement of which permissions can be set as "Advanced Permissions" and which permissions can already be set.
The list of permissions might need adjusting - I'm investigating that now.
https://mattermost.atlassian.net/browse/XYZ-76
> XYZ-76: Add license check to patchRoles endpoint.

- app/post.go
- app/post_test.go
This doesn't work:
```
https://image-proxy.mattermost.com//https://pre-release.mattermost.com/plugins/memes/templates/success-kid.jpg?text=assigned&text=chrome+testing
```
The auth headers are stripped as the request passes through the proxy.
I think it's reasonable to not proxy any images hosted on the Mattermost installation itself, and it facilitates authenticated / dynamically generated images from plugins (e.g. dank memes).
N/A
N/A
> Don't proxy same-site image urls

- store/sqlstore/post_store.go
- store/storetest/post_store.go
This wouldn't affect the loadtest results since those were using a limit of 60 but the webapp uses a limit of 30 when requesting posts so in a real environment this could have significant benefit. Note that limit has a maximum of 1000 so we won't be caching more posts than that.
Couldn't think of an easy to unit test this since the caches are in a different package from the tests. If anyone has good ideas for that, let me know.
Part of https://mattermost.atlassian.net/browse/ABC-228
> ABC-228 Update GetPosts caching to work for non-60 limits

- api4/team_test.go
- app/email.go
- app/team.go
- app/team_test.go
- i18n/en.json
Added invite_id field to email invite url, along with validation of this field on the server. 
Log into the test server with two users in different browsers. Both users should be on the same team
* With UserA:
* From the team menu, select "Create a new Team" and follow the steps to create a second team on the server
* From the team menu, select "Team Settings", verify that "Allow any user with an account on this server to join this team" is set to "No"
* From the team menu, select "Send Email Invite" and send an invite to UserB
* From the team menu, select "Team Settings", expand the "Invite Code" section, click on "Regenerate Code", and then click on "Save"
* Log into UserB's email account and verify that the invite email arrived. Copy the invite link out of it.
* With UserB
* Verify …
> XYZ-104: Can join a team with email invite link after regenerating the invite code

- app/app.go
- cmd/platform/server.go
- cmd/platform/server_test.go
- jobs/jobs_watcher.go
Add tests for the `platform server` command. The tests ensure that the server will start and stop normally when correctly configured; and that it will return a proper error in case of (for instance) an invalid configuration file.
Writing the tests uncovered an issue in the code (that I introduced in #8204): when the App initialization fails and an error is returned, some of the app state is left dirty (notably `appCount` is not decremented).
The impact is quite limited, as during normal usage an initialization error makes the program terminate quickly afterwards (so not cleaning up isn't an issue). However, during tests, we may create more than one App instance. This PR fixes the issue by ensuring the app cleans itself when encountering an initialization error, before returning the error …
> Add tests for the `platform server` command

- api/command_test.go
- api4/post_test.go
Removes the last removable instances of `EnableOnlyAdminIntegrations` on the server for Phase 1 of Advanced Permissions. There are other instances but they can't be removed because of the migration, etc.
[XYZ-73](https://mattermost.atlassian.net/browse/XYZ-73)
> XYZ-73: Removes EnableOnlyAdminIntegrations.

- app/post.go
- app/post_test.go
It sounds like web sites should only be including absolute URLs in their OpenGraph metadata, but since that isn't the case in practice, we can have the server fix that before it reaches the clients.
https://mattermost.atlassian.net/browse/ICU-669
> ICU-669 Ensure all URLs returned from OpenGraph are absolute

- app/diagnostics.go
- model/config.go
- utils/authorization.go
- utils/authorization_test.go
- utils/config.go
- utils/policies-roles-mapping.json
Changes were made to the [config mapping](https://github.com/mattermost/mattermost-webapp/blob/advanced-permissions-phase-1/utils/policy_roles_adapter.js#L45) and this change updates the JSON used in the tests for the config-to-permissions migration. 
Also changes `ServiceSettings`' `EnableTeamCreation` field to use a pointer consistent with  `EnableOnlyAdminIntegrations` field (for ease of testing).
[XYZ-109](https://mattermost.atlassian.net/browse/XYZ-109)
> XYZ-109: Mapping updates

- api/admin.go
- api/admin_test.go
- api4/system.go
- api4/system_test.go
Prevent changing PluginSettings.EnableUploads through the API. Follow-up webapp PR will remove the setting from the UI.
https://mattermost.atlassian.net/browse/ABC-176
> ABC-176 Prevent changing PluginSettings.EnableUploads through the API

- app/team.go
- app/team_test.go
- i18n/en.json
Check MaxUsersPerTeam when the user "re-join" after leave a team (before that it only check when is a new join).
[XYZ-111](https://mattermost.atlassian.net/browse/XYZ-111)
> XYZ-111: Check max users per team on re-join after leave a team

- app/notification.go
- app/notification_test.go
- i18n/en.json
For these messages, we treated GMs as if you were always being mentioned. This removes that behaviour and adds a load of tests for this.
I also changed the case of a couple of the messages since they were resulting in messages like "Joe Uploaded files" instead of "Joe uploaded files"
https://mattermost.atlassian.net/browse/ICU-753
- Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json) updates
> ICU-753 Remove special behaviour for group messages in generic push notifications

- cmd/platform/server.go
Currently, when running the tests locally, they might panic on `cmd/platform/server_test.go` with a segfault.
This is because when running the tests, the server instance will shutdown while some jobs spawned through a goroutine are still running. This may crash the test harness, as the jobs try to access a shut down app instance.
Fortunately the fix is easy: we just have to use the same App goroutine-counting facility used in the rest of this function's code. This will ensure that on shutdown the app waits for this goroutines to be finished before returning the control to the caller.
```shell
$ go test -v -run=TestRunServer ./cmd/platform/
=== RUN   TestRunServerSuccess
[2018/02/13 06:24:36 GMT] [INFO] Starting Server...
[2018/02/13 06:24:36 GMT] [INFO] Server is listening on [::]:8065 …
```
> [Fix tests] Wait for goroutines to finish before shutting down server

- utils/mail.go
- utils/mail_test.go
Modified advanced mail implementation to properly support multiple attachments with the same file name. My initial implementation had some scoping issues that caused two distinct files that had the same file name to be treated incorrectly. Rather than attaching each file to the email, one of the files was attached multiple times.
https://mattermost.atlassian.net/browse/XYZ-106
> XYZ-106: Compliance Export is not able to distinguish between two different file uploads that have the same file name

- app/import.go
The bulk import feature allows you to create teams an members of the team without being member of the town-square channel. This solve that problem.
[XYZ-114](https://mattermost.atlassian.net/browse/XYZ-114)
> XYZ-114 Adding mandatory membership to town-square in bulk-import

- store/sqlstore/supplier_reactions.go
Fix the DeadLock on reactions insertions (it only happens when a lot or reactions and posts are created in parallel with sampledata command). It fix the DeadLock for insertion, but there still the posibility of the DeadLock on deletion.
This solve the problem of parallel workers inserting data with sampledata or bulk_import into mysql with reactions.
And maybe it can go into the release.
[PLT-8723](https://mattermost.atlassian.net/browse/PLT-8723)
> PLT-8723: Fix DeadLock on reactions insertions

- cmd/platform/server.go
- cmd/platform/server_test.go
When managed by `systemd`, notify when the server is actually ready to receive network connections.
Currently, when starting Mattermost programmatically, it's hard to tell when the server is actually ready to receive network connections. This is cumbersome:
- for monitoring: the systemd service status is "running" although the server is still booting ;
- for programmatic use: when a script needs to know when the server is ready to perform further actions.
To improve this, systemd allow processes to tell when they started successfully. The launcher waits for this notification before reporting the service as successfully launched.
The way processes notify systemd is by sending a `READY=1` string over a standard unix socket, whose path is provided in an environment var.
The systemd service …
> Send systemd READY notification

- app/license.go
See https://pre-release.mattermost.com/core/pl/um9dx4s38tr9ij8phuwgf6xg9r
If `SetLicense` is never called, the client license will always be nil. This now matches old behavior again.
N/A
N/A
> Always return non-nil client license

- api4/apitestlib.go
Using `t.Helper()` makes it so that the line that calls these functions is displayed when a test fails rather than the line in apitestlib.go. This means we can also stop manually printing the stack trace on failure
> Added t.Helper to CheckXStatus test functions

- api/team.go
Check for ADD_USER_TO_TEAM also in the API 3 endpoint.
[MM-8825](https://mattermost.atlassian.net/browse/MM-8825)
> MM-8825: Make consistent INVITE_USER and ADD_USER_TO_TEAM permissions checking

- api/file.go
- api4/context.go
- api4/file.go
- api4/file_test.go
- api4/params.go
- app/file.go
- i18n/en.json
- model/client4.go
This is the new file upload endpoint for use in the iOS share extension. Instead of being a separate route, it adds additional handling to the existing file upload endpoint so that it supports uploading a single file with the channel_id and filename specified as query parameters. This is as opposed to the original behaviour which just uses a multipart request to upload any number of files.
Elias will be the one making the changes to the redux library so that these can be used from the share extension.
API Reference PR: https://github.com/mattermost/mattermost-api-reference/pull/335
https://mattermost.atlassian.net/browse/MM-9556
- Added API …
> MM-9556 Added ability to upload files without a multipart request

- app/web_hub.go
- model/websocket_message.go
- model/websocket_message_test.go
* This greatly optimizes web socket events destined for a single user (such as the "channel viewed" event). Instead of iterating through every connection of every hub, sending of these events iterates only through the destination user's connections in the user's hub.
* This precomputes the raw JSON for websocket events. So the event fields (except for `Sequence`) are now only serialized once when sent to thousands of users.
https://mattermost.atlassian.net/browse/MM-8710
> MM-8710: Web Hub optimizations

- api4/user.go
- app/config.go
- app/diagnostics.go
- app/login.go
- config/default.json
- i18n/en.json
- model/config.go
- utils/config.go
Adds two configuration settings:
1. AllowCookiesForSubdomains, which set's the Domain parameter on our cookies, which allows the browser to send the cookies to subdomains as well. 
2. WebsocketURL, allows the server to instruct clients where they should try to connect by websockets to. 
Combined these allow the bypass of a main proxy server or CDN such as cloudfront that does not support websockets by using a websocket subdomain (like ws.pre-release.mattermost.com for example).
Accomplishing this with a redirect was not possible because the Chrome browser does not appear to follow websocket redirects. (I did not check other browser behavior)
Documentation PR for using these settings with CloudFront can be found here: https://github.com/mattermost/docs/pull/1796
> MM-8681 Adding config settings necessary for using CloudFront.

- cmd/platform/user.go
- einterfaces/account_migration.go
- i18n/en.json
I have splited the auth migration to two commads because the parameters changes
from one command to another.
Probably is necesary too to review the texts. The new command format is:
- `platform user migrate_auth_to_saml [fromAuth] [usersFile.json] [--dryRun] [--auto]`
- `platform user migrate_auth_to_ldap [fromAuth] [matchField] [--dryRun] [--force]`
Other option would be something like `platform user migrate_auth [ldap|saml]` being ldap and saml subcommands of migrate_auth.
[XYZ-31](https://mattermost.atlassian.net/browse/XYZ-31)
> Adding saml migration command

- app/notification.go
- app/notification_test.go
- i18n/en.json
Fix push notification content for file only messages.
https://mattermost.atlassian.net/browse/MM-8006
> MM-8006 Fix push notification content for file only messages

- api/apitestlib.go
- config/default.json
- utils/config.go
- web/web_test.go
* Default APIv3 to disabled for new installs
* Add EnableAPIv3 setting to client config to support related webapp changes
https://mattermost.atlassian.net/browse/MM-8593
> MM-8593 Default APIv3 to disabled for new installs

- Makefile
- build/release.mk
Pretty much the same thing as this: https://github.com/mattermost/mattermost-server/pull/8325/files
Being able to package for Linux only helps a lot with my load test tooling / process.
N/A
N/A
> Add packaging targets for individual platforms

- utils/mail_test.go
This test is now failing locally for some reason that I couldn't figure out within a reasonable amount of time. Since it's blocking release we're just disabling for now and a ticket to investigate it is here: https://mattermost.atlassian.net/browse/MM-9705
> Temporarily disable flaky TestSendMailUsingConfigAdvanced test

- scripts/prereq-check.sh
Fixes prerequisites version checking by using `sort -t.` to use dot as separator instead of `sort -n` in `scripts/prereq-check.sh`.
[https://github.com/mattermost/mattermost-server/issues/8333](https://github.com/mattermost/mattermost-server/issues/8333)
> Fix prerequisites checker so 1.10 > 1.9

- utils/lru.go
- utils/lru_test.go
This removes some of the stuff we weren't using from the LRU and uses a generation-based approach to purging the LRU rather than releasing and reallocating the underlying map's memory.
Previously, every call to `InvalidateAllCachesSkipSend` would allocate multiple megabytes of memory for large maps on each call. Now, rather than reallocating the maps, a counter is simply incremented.
The change is extremely apparent in the heap profiles, and somewhat apparent in the CPU profiles (reducing garbage collection time a bit). End-of-test reports show improvements in response times as well.
[lrultafter.txt](https://github.com/mattermost/mattermost-server/files/1765286/lrultafter.txt)
[lrultbefore.txt](https://github.com/mattermost/mattermost-server/files/1765287/lrultbefore.txt) …
> Optimize LRU purging

- store/sqlstore/channel_store.go
This PR simplifies a ChannelMembers query that has extra tables in it that aren't used.
> Simplification of a Channel Members query.

- plugin/rpcplugin/sandbox/sandbox_linux.go
The `pid` field should be 4 bytes. With Go 1.9, the build just happens to work. With Go 1.10, the padding between the `version` and `pid` fields happens to be non-zero, and the syscalls fail.
I can update the build slaves to 1.10 once this is merged.
N/A
N/A
> Fix linux cap header structure

- api/post.go
- api/websocket_test.go
- app/channel.go
- app/command_expand_collapse.go
- app/emoji.go
- app/post.go
- app/preference.go
- app/status.go
- app/team.go
- app/user.go
- wsapi/user.go
- wsapi/webrtc.go
I traced the Git history back to the origin of this and it seems to me like the `go Publish(...)` calls were remnants of `store.PublishAndForget()`, which originally had a totally different implementation. I don't believe they actually improve performance anymore as `Publish` doesn't do anything that takes any significant amount of time. The only exception is if the hub's broadcast queue (of 4096 messages) is full. In that case, goroutines will now block until the channel can receive a new message. I think this is actually preferable behavior. Spinning up a new goroutine wouldn't really buy us any actually performance gains anyways. The queue is full because resources are under contention, and the server's performance will still suffer just as much regardless, but in far less predictable …
> Remove `go Publish(...)` idiom

- api4/system.go
- app/app.go
- app/config.go
- app/config_test.go
- model/websocket_message.go
Emit new websocket events whenever the license or configuration changes. This will eventually allow us to stop reloading the webapp when these change and react purely to the Redux state changes.
https://mattermost.atlassian.net/browse/MM-8604
> MM-8604: emit config/license websocket events

- web/web.go
- web/web_test.go
Changing to only check Safari and Edge, Updating UA check dependency to better library.
See: https://pre-release.mattermost.com/core/pl/xou45eqebtro3qx4euzm3nho5w
Current:
https://mattermost.atlassian.net/browse/PLT-7574
Browser Compatibility Check Implementation:
https://github.com/mattermost/mattermost-server/pull/6945
https://mattermost.atlassian.net/browse/PLT-959
> [PLT-7574] Update and Simplify Compatibility Check and Replace UA Dependency

- plugin/rpcplugin/api.go
- plugin/rpcplugin/api_test.go
Required to support passing of certain posts through the plugin API: https://github.com/mattermost/mattermost-server/issues/8401
https://mattermost.atlassian.net/browse/MM-9731
https://github.com/mattermost/mattermost-server/issues/8401
> MM-9731: Register additional gob types to support arrays and dicts in post props

- app/channel.go
- app/channel_test.go
- store/sqlstore/compliance_store.go
- store/storetest/compliance_store.go
Two fixes:
* `ChannelMemberHistory` records are now created for DM channels
* DM and GM channels are given pretty names in Compliance Exports, since the channel members are listed at the start of the export, so there's no need to use unique display names for them
https://mattermost.atlassian.net/browse/XYZ-87
> XYZ-87: GlobalRelay DM Exports do not Include Channel Name

- plugin/rpcplugin/sandbox/sandbox_linux.go
This adds a /dev/null writability test to the sandboxing support check.
I'll try to figure out if there's a way we can get sandboxing to work in these environments, but this at least keeps things from breaking.
https://mattermost.atlassian.net/browse/MM-9716
https://mattermost.atlassian.net/browse/MM-9742
N/A
> MM-9742: Plugin sandbox fixes

- model/manifest.go
- plugin/pluginenv/environment.go
> The path to your webapp bundle. This should be relative to the root of your bundle and the location of the manifest file.
This was actually completely ignored by the server. And if it was anything other than `/static/[plugin id]_bundle.js`, nothing would work. This fixes it, including a backwards-compatibility fallback until we update the Zoom plugin and `mdk`.
N/A
N/A
> Respect plugin manifest webapp bundle_path

- i18n/en.json
- model/config.go
- model/config_test.go
Added settings, validation, and internationalization strings for new GlobalRelay config settings. These settings will be used as a part of [MM-8838](https://mattermost.atlassian.net/browse/MM-8838).
https://mattermost.atlassian.net/browse/MM-8840
> MM-8840: Add GlobalRelay Configuration Settings

- store/sqlstore/upgrade.go
Probably should have done this with #8408 but didn't notice it until after the reviews had happened.
> Moved team icon upgrade code to 4.9 since it didn't make it in for 4.8

- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/TeamStore.go
Per the ticket description, Shift was seeing a lot of the following error when deactivating users:
```bash
[2018/01/02 10:03:51 UTC] [EROR] Problem updating members last updated time id=<chanid> err=SqlChannelStore.extraUpdated: store.sql_channel.extra_updated.app_error, id=<id>, context deadline exceeded
```
The error was coming from the `ExtraUpdateByUser` query. This query would update the `channel.ExtraUpdateAt` timestamp field for every channel the user was in. From what I can remember and tell by grep'ing through the code, the original use of this field was for calculating the etag for an old endpoint `GET /api/v3/teams/tid/channels/cid/extra_info`. [This big PR from a year ago](https://github.com/mattermost/mattermost-server/commit/365b8b465e8a53ebb2da2bf3aef659ac81a2bc6a#diff-8dd82 …
> MM-8729 Remove query to update channel extra_update_at field on user activation/deactivation

- app/webhook.go
- app/webhook_test.go
Slack compatibility code in webhooks captures incorrect text
Jira: https://mattermost.atlassian.net/browse/MM-9725
GitHub: https://github.com/mattermost/mattermost-server/issues/8407
> [MM-9725] Slack compatibility code in webhooks captures incorrect text

- api4/system_test.go
- model/client4.go
doing the implementation for the S3 file storage, I realize that the driver for email test connection does not expect to send the config. But actually, we are sending that. this update the driver and the tests
N/A
> update email test in the driver to be able to send the config in the body

- app/plugin.go
- i18n/en.json
We just decided we were gonna try to improve the error message, right? Not really much else we can do if the config is read-only.
Before:
> [2018/02/22 20:26:52 UTC] [EROR] failed to enable prepackaged plugin: EnablePlugin: Error saving plugin state in config, saveConfig: System Console is set to read-only when High Availability is enabled unless ReadOnlyConfig is disabled in the configuration file.
After:
> [2018/03/09 15:57:57 CST] [EROR] failed to enable prepackaged plugin: EnablePlugin: The plugin configuration in your config.json file must be updated manually when using ReadOnlyConfig with clustering enabled.
Maybe a little more straight-forward. :-/ Open to suggestions.
https://mattermost.atlassian.net/browse/MM-9688
N/A
> MM-9688: Better error message for plugin enabling in HA mode

- api4/system.go
- api4/system_test.go
- utils/file_backend_s3.go
- utils/file_backend_s3_test.go
Fix some comments addressed in this PR: https://github.com/mattermost/mattermost-webapp/pull/772#issuecomment-372481474
and also fix when user save the config and retest the connection. Because the UI will show `*****` in the AWS secret key (when used) and when click in the test button it will send the `****` instead of the secret. the server side will take care.
N/A
> remove s3 region to be mandatory and fix when user call test s3 when the config is saved

- utils/config.go
Fix theme chooser not working at all on non-EE builds and allow EE builds to enforce theme/disable theme chooser.
Discussion here: https://pre-release.mattermost.com/core/pl/9tm7f8b36jrobmg37omzhkuucc
> MM-9795: Fix theme chooser for non-EE builds

- app/notification.go
Push notifications are sent for own DM's.
If you receive a webhook notification it will send push/email notification. if you write your own messages it will not send any notification.
Jira: https://mattermost.atlassian.net/browse/MM-9703
> [MM-9703] Push notifications are sent for own DM's

- utils/mail.go
- utils/mail_test.go
Splitting the email sending process in 2 steps, create the client connection to the SMTP server and, send the email. This allow to send various emails using the same connection (needed to global relay email sends). Besides, I have removed the hard dependency between the configuration and the email sending, because I need to send emails through other SMTP server (the Global Relay server), so I can't use the default email configuration.
[MM-8838](https://mattermost.atlassian.net/browse/MM-8838) and [MM-8826](https://mattermost.atlassian.net/browse/MM-8826)
> Isolating configuration, sending emails and connection to SMTP.

- store/sqlstore/post_store.go
- store/storetest/post_store.go
See discussion on ~developers-performance, but the basic idea here is to force the database to use the `PRIMARY` index when fetching posts instead of trying to filter down by channel and doing a scan.
Part of this change includes a proposed "bug fix" to the semantics of the query. I've broken out separate commits for first reworking the tests and then adding coverage for the new case, and I've written up the analysis on ~developers-performance, but I want to call out this point in more detail. Here's my original comments from the channel discussion:
-----
The existing JOIN conditions on the query could be commented as follows:
```SQL
-- The root post of any replies in the window
q1.RootId = q2.Id 
-- The reply posts to all threads intersecting with the window.
OR q1.RootId = q2.RootId
``` …
> MM-9770: rewrite getParentsPosts to improve performance

- config/default.json
- model/config.go
Adds two SAML config keys: `ScopingIDPProviderId` and `ScopingIDPName`.
https://mattermost.atlassian.net/browse/MM-9679
> MM-9679: Add config for saml home realm discovery bypass

- app/session.go
The error message expects to receive three parameters (the user id, session id, and error), but we were only passing in the two
```
Failed to update LastActivityAt for user_id=%v and session_id=%v, err=%v
```
> Fixed missing error in log message

- utils/mail.go
Allow to specify the Date email header as a parameter directly in the SendMail
function. This is needed for GlobalRelay exports.
> Receive the email date as parameter

- api/file_test.go
- api/user_test.go
- api4/apitestlib.go
- api4/oauth.go
- api4/plugin_test.go
- app/app.go
- app/auto_posts.go
- app/import_test.go
- app/saml.go
- app/user.go
- utils/config.go
- utils/html.go
- utils/i18n.go
- utils/license.go
- web/web.go
I encountered a lot of difficulty manually running the unit tests inside `enterprise/account_migration`. This had nothing to do with those tests, but with a series of assumptions made by the application and testing code, documented as individual commits in this PR. Hopefully this helps anyone trying to run `go test` instead of being forced to run the whole test suite from the root.
None
> Fix various segfaults when running `go test` manually

- app/server.go
- i18n/en.json
Customers with Forward80To443 enabled but not actually listening on :443 (because they had an Nginx instance listening there and on port 80) would get an instance of Mattermost that ran but didn't listen on anything. This PR improves semantics around this setting, making the following changes:
* If Forward80To443 is true, but not configured to listen on 443, fail to start the server with an error message.
* If Forward80To443 is false and LetsEncrypt is true, fail to start the server with an error message.
It's accompanied by a corresponding webapp change: https://github.com/mattermost/mattermost-server/pull/8496
https://mattermost.atlassian.net/browse/MM-9843
> MM-9843: improve semantics around Forward80To443

- api4/role.go
- api4/role_test.go
If the getRolesByName request includes any blank/whitespace rolenames, just ignore them rather than returning 400.
> Ignore blank role names in getRolesByName call.

- store/sqlstore/role_supplier.go
Fixes startup on MySQL < 5.7
This should bring pre-release back to life.
> Fix roles table ID max length so MySQL 5.6 doesn't fail.

- model/version.go
- store/sqlstore/channel_store.go
- store/sqlstore/upgrade.go
As outlined in [this discussion](https://pre-release.mattermost.com/core/pl/uw5bwmkb6irkbkn6pk9rkzpytr), this index causes issues with MySQL's query planner, leading to full table scans in a case where it would have made more sense to leverage a filesort.
This is the version of this change for master.
https://mattermost.atlassian.net/browse/MM-9965
> Remove the index on Channels.DisplayName (master/v4.9)

- Makefile
- build/release.mk
This reverts commit f0f4f68defef1e9360394ba740c57cff7124dc9c.
This doesn't work because the targets need to be run in order. This breaks the windows build and causes local builds to not have a binary available unzipped.
> Revert "add individual platform packaging targets (#8366)"

- i18n/en.json
- store/sqlstore/post_store.go
Call out the number of supported characters explicitly, moving the byte limit to parentheses. This also makes the log an INFO log so as to avoid having to describe enabling the TRACE level in the migration document.
(I suspect the TRACE level should be reserved for things the customer would normally never want to see outside of a deeper investigation.)
https://mattermost.atlassian.net/browse/MM-9661
> MM-9661: tweak post message size log

- model/user.go
- model/user_test.go
This change adds a default state to a nil timezone field.
https://github.com/mattermost/mattermost-server/pull/8547
Unfortunately, the above PR breaks mattermost-redux logic.
None
> Initialize timezone to a default state

- api4/context.go
- app/session.go
Under high load, if the DB timed out or returned some random error when fetching the user's session, they would be logged out because the internal server error generated would be lost to one that says unauthorized. This would cause the user's cookie to be deleted. This fixes that by returning the DB error.
> MM-9967 Fixing DB load causing user logout.

- app/command_mute.go
The channel /mute slash command now works with and without the `~` prefix
> Make channel mute command respond with and without ~ prefix

- app/notification.go
- app/notification_test.go
It turns out that mentioning like `Hello @user.name.` worked, but `Hello @user.name...` did not
https://mattermost.atlassian.net/browse/MM-9868
> MM-9868 Fixed mentioning users when followed by multiple periods

- model/version.go
- store/sqlstore/channel_store.go
- store/sqlstore/upgrade.go
As outlined in [this discussion](https://pre-release.mattermost.com/core/pl/uw5bwmkb6irkbkn6pk9rkzpytr), this index causes issues with MySQL's query planner, leading to full table scans in a case where it would have made more sense to leverage a filesort.
This is the version of this change backported to 4.7.
https://mattermost.atlassian.net/browse/MM-9965
> Remove the index on Channels.DisplayName (v4.7)

- model/version.go
- store/sqlstore/channel_store.go
- store/sqlstore/upgrade.go
As outlined in [this discussion](https://pre-release.mattermost.com/core/pl/uw5bwmkb6irkbkn6pk9rkzpytr), this index causes issues with MySQL's query planner, leading to full table scans in a case where it would have made more sense to leverage a filesort.
This is the version of this change backported to 4.8.
https://mattermost.atlassian.net/browse/MM-9965
> Remove the index on Channels.DisplayName (v4.8)

- i18n/en.json
Minor text changes to slash commands. Discussed in UX channel.
1) In autocomplete entry for /mute, /join and /open slash commands, add `~` in front of [channel] similar to `@[username]` to make the channel linking more discoverable
2) Update error message when channel cannot be found in /mute command.
N/A
> Minor text changes to /open, /join and /mute slash commands

- app/notification.go
- app/notification_test.go
Where `@test.example` and `@test` are users, posting out of channel mention of "@test.example" will determine that `@test.example` is mentioned but not `@test`.
Initially I thought that it can't always be the case because there's a possibility that the user might intend to mention `@test`. However, after preliminary change, I am convinced that it is `@test.example` since our client is already doing it.
This change somehow aligned the behavior of server and client.
Fix out of channel mentions for mentioned word with valid punctuations by:
- when a `word` starts with `@`, add it to potential mentions (e.g. `@test.example`)
- if not, split the word if with valid punctuations and check at-mention (e.g. `test.@example` will get `@example`)
Jira ticket: …
> [MM-10046] Fix out of channel mentions for mentioned word with valid punctuations

- app/channel.go
- app/channel_test.go
- app/plugin_api.go
- plugin/api.go
- plugin/plugintest/api.go
- plugin/rpcplugin/api.go
- plugin/rpcplugin/api_test.go
This effectively exposes AddChannelMember, UpdateChannelMemberRoles,
UpdateChannelMemberNotifyProps and LeaveChannel via the plugin API.
It also modifies the semantics of AddChannelMember to explicitly allow
for an empty user requestor, left as such for now via the plugin API.
https://mattermost.atlassian.net/browse/MM-8678
> MM-8678: add CUD support for channel members via plugins

- app/channel.go
- app/command_mute.go
- app/command_mute_test.go
- i18n/en.json
Fixes the mute slash command when the user is not a member of the channel to mute and fixes the unit tests
https://mattermost.atlassian.net/browse/MM-10053
> Fix mute channel when not a member and adding unit tests

- app/admin.go
- i18n/en.json
This exposes the detailed error (which will be the actual error from the SMTP server) to the system admin when they're testing SMTP connections. It's not perfect or super clean error message but it would be a lot of mana to clean it up anymore and beyond the scope of this bug ticket.
https://mattermost.atlassian.net/browse/MM-8180
> MM-8180 Improve error message for testing smtp connections

- cmd/commands/team.go
- cmd/commands/team_test.go
The team command hasn't a way to get the list of teams, so is harder to work
only with the comand line. Now you can list your teams, and start to do actions
on your channels based on that.
No ticket
> Add list command to teams command in CLI

- model/websocket_client.go
If one wishes to change something in the HTTP client, for example System Proxy, Insecure connection or compression, one could change or override the HttpClient.
But the same can't be done to the WebSocket, as it is always using gorilla's DefaultDialer (with system proxy always used).
Now custom dialers can be passed, with no proxy for example, with the default API signature unharmed (with the default one is still used).
None
> Websocket custom dialer support

- model/config.go
- model/config_test.go
- model/utils.go
- model/utils_test.go
We've had regressions in the past where `config.SetDefaults` wasn't updated for one or more field. Ensure we don't see `nil` fields ever again.
https://mattermost.atlassian.net/browse/MM-9977
> MM-9977: test config.SetDefaults leaves nothing nil

- cmd/commands/channel.go
CLI channel command line examples some explicit mention the team:channel and
other not. The team part is always needed, so not include that in the example
is error prone.
No ticket
> Fixed the example text on CLI channel command

- app/app.go
- utils/config.go
The underlying l4g library is not resilient to filter modifications in
the presence of concurrent goroutines. In particular, it's not safe to
call Close() on filters which might be actively held by a goroutine for
logging.
This change disables all modifications to existing filters once
initialized by the App layer. In practice, we might be able to get away
with some modifications to the existing filters (i.e. changing levels),
but the [golang memory model](https://golang.org/ref/mem) makes no
guarantees that it is safe to do so:
> Programs that modify data being simultaneously accessed by multiple goroutines must serialize such access.
We can solve this holistically by introducing the requisite locking
within our fork of the l4g library. For now, we just disable all
modifications. …
> Prevent disabling or modifying l4g logging filters

- app/user.go
- cmd/commands/channel.go
- cmd/commands/command.go
- cmd/commands/import.go
- cmd/commands/ldap.go
- cmd/commands/license.go
- cmd/commands/message_export.go
- cmd/commands/reset.go
- cmd/commands/roles.go
- cmd/commands/sampledata.go
- cmd/commands/team.go
- cmd/commands/user.go
When running a command sometimes we can have some goroutines running in parallel, with the 
`a.shutdown` we wait for all routines to finish
https://mattermost.atlassian.net/browse/MM-9720
> add app shutdown to make sure the goroutines finish and all process are closed

- api/team.go
- api/user.go
- api/user_test.go
- api4/team.go
- api4/team_test.go
- api4/user.go
- api4/user_test.go
- app/email.go
- app/team.go
- app/team_test.go
- app/user.go
- app/user_test.go
- i18n/en.json
- model/client.go
- model/client4.go
It binds each invitation to a token, avoiding the invitations re-use.
[MM-9779](https://mattermost.atlassian.net/browse/MM-9779)
PR for the API documentation mattermost/mattermost-api-reference#349
> MM-9779: Incorporate a Token into the invitations system

- app/session.go
Even if personal access tokens were disabled the error message made it look like there was one being used here. The solution is just suppress that unhelpful error message and add logging for any errors that we would need to worry about.
https://mattermost.atlassian.net/browse/MM-10133
> MM-10133 Suppress confusing personal access token message in invalid session error

- api4/team.go
- api4/team_test.go
- app/team.go
- i18n/en.json
- model/client4.go
- store/sqlstore/team_store.go
Add feature to remove team icon by setting `team.LastTeamIconUpdate` to 0.  It might not be intuitive but:
- `team.LastTeamIconUpdate == 0` means no team icon set
- `team.LastTeamIconUpdate > 0` means with team icon set
Redux PR - https://github.com/mattermost/mattermost-redux/pull/474
API docs to follow
Jira ticket: [MM-10354](https://mattermost.atlassian.net/browse/MM-10354)
> [MM-10354] Add feature to remove team icon

- mlog/log.go
- mlog/stdlog.go
- mlog/stdlog_test.go
This allows the stdlib log adapter to set the level of entries that are fed to it. It also strips out the `[DEBUG]` messages because those are part of the structure.
> Add stdlib log level interpreter for structured logger

- app/plugin.go
- i18n/en.json
- mlog/log.go
- model/manifest.go
- plugin/pluginenv/environment.go
- plugin/pluginenv/environment_test.go
- plugin/rpcplugin/hooks.go
- plugin/rpcplugin/hooks_test.go
- plugin/rpcplugin/main.go
- plugin/rpcplugin/main_test.go
- plugin/rpcplugin/rpcplugintest/supervisor.go
- plugin/rpcplugin/sandbox/main_test.go
- plugin/rpcplugin/supervisor.go
- plugin/valid.go
- plugin/valid_test.go
This PR contains a series of commits -- each self-documenting -- proposing a set of improvements around plugin error handling and logging. This came about as I was researching https://mattermost.atlassian.net/browse/MM-8622 in a bid to determine how to present plugin errors to the system administrator more effectively.
A quick summary:
* leverage mlog, `plugin_id`
* improved logging of various events, including sideloaded plugins with malformed manifest files 
* allow deleting of plugins whose manifests are corrupted (e.g. `id` doesn't match installation path)
* if a plugin exits three times, don't keep restarting it (and we'll eventually surface this error)
* further constrain plugin ids, preventing a plugin id akin to `../../path/to/evil` and successfully installing files to arbitrary …
> MM-8622: improved plugin error handling

- api4/channel.go
- api4/channel_test.go
- api4/team.go
- api4/team_test.go
- app/channel.go
- app/channel_test.go
- app/team.go
- app/team_test.go
- i18n/en.json
- model/client4.go
- model/scheme.go
Adds API endpoint to set a team's scheme and channel's scheme. 
This is awaiting https://github.com/mattermost/mattermost-server/pull/8615.
[MM-10182](https://mattermost.atlassian.net/browse/MM-10182)
[MM-10183](https://mattermost.atlassian.net/browse/MM-10183)
> MM-10182 & MM-10183: Adds channel scheme and team scheme API endpoint.

- api4/system_test.go
- app/analytics.go
- model/client4.go
Add inactive user count so I can use that on the client in an upcoming PR. Also fixed a bad query parameter in the `GetAnalyticsOld` client function.
Server part of https://mattermost.atlassian.net/browse/MM-10268
> MM-10628 Add inactive user count to analytics and fix client analytics function

- app/notification_test.go
- utils/utils.go
TestSendNotifications was randonly failing because the order of mentions
depends on the order of profiles, and wasn't specified an order by in the
query. So, we have to check all the possible notifications.
> Fix TestSendNotifications test

- utils/config.go
- utils/config_test.go
The problem was that we were telling it to default MessageExportSettings.GlobalRelaySettings to nil since it's a pointer unlike every other Settings type. That appears to have been intentional, but it was causing it to sometimes set it based on the environment variables but then blank out the entire struct with the default value before applying the values from the config so it would sometimes work like
1. Set MessageExportSettings.GlobalRelaySettings to nil from the default
2. Set MessageExportSettings.GlobalRelaySettings.CustomerType to "test" from an environment variable
3. Set MessageExportSettings.GlobalRelaySettings.SmtpUsername to "user" from an environment variable
which works fine but other times, it may look like
1. Set MessageExportSettings.GlobalRelaySettings.SmtpUsername to …
> MM-10189 Fixed inconsistency when using environment variables for MessageExportSettings

- app/file.go
Respect image orientation before saving height and width of FileInfo during file upload of image.
The issue on high-resolution image attached to that ticket was that it has exif orientation of rotate CW. Currently, the server respects orientation before writing/saving the file but not when saving the FileInfo - where the webapp depends on during single image view calculation.
Jira ticket: [MM-10200](https://mattermost.atlassian.net/browse/MM-10200)
> [MM-10200] Respect image orientation before saving height and width of FileInfo

- store/sqlstore/upgrade.go
I normalized all the emails stored in the AuthData of the users in the saml
authentication and migration. This migration normalize the AuthData for the
existing saml accounts.
My unique concern here is that now can exists 2 accounts with the same AuthData
(email) with different case, and if this happens for 2 different accounts with
saml authentication, the migration will fail.
[MM-10319](https://mattermost.atlassian.net/browse/MM-10319)
> MM-10319: Use normalized email for Saml (migration)

- Makefile
Set default GOPATH to $(shell go env GOPATH)
https://github.com/mattermost/mattermost-server/issues/8722
- [x ] Touches critical sections of the codebase (build process)
> Fix empty GOPATH behaviour in Makefile

- app/login.go
- app/user_agent.go
- app/user_agent_test.go
When removing the old library, I missed that the enums that the new library used did not follow the same naming as the previous library, so I've added code to emulate that along with unit tests for different types of sessions. This should also fix the sessions modal since it was displaying based on those props.
https://mattermost.atlassian.net/browse/MM-10495
> MM-10495 Updated user agent detection to match output of previous library

- api/emoji_test.go
- app/emoji.go
- app/file.go
- app/team.go
- app/user.go
- utils/file_backend.go
- utils/file_backend_local.go
- utils/file_backend_s3.go
- utils/file_backend_test.go
- utils/mail_test.go
This is a reworked [set of changes](https://github.com/mattermost/mattermost-server/pull/8679) originally from @josephGuo to begin reducing the duplicated memory required when uploading files.
https://mattermost.atlassian.net/browse/MM-10188
> MM-10188: expect io.Reader in FileBackend.WriteFile

- app/apptestlib.go
- app/command_invite.go
- app/command_invite_test.go
- i18n/en.json
Cherry pick from ebd322163477f4e0aa08b3b06ff297f84512beee
Change system response to "Could not find the channel" when trying to invite user to private channel you can't see
JIRA: https://mattermost.atlassian.net/browse/MM-10458
> [MM-10458] Change system response to "Could not find the channel" - bug fix

- mlog/default.go
- mlog/global.go
- mlog/global_test.go
- mlog/log.go
Dump mlog to STDOUT before initialized, to allow for logging failures that occur due to config parsing, etc. 
Fix file logging to honour logger.FileJson instead of copying the logger.ConsoleJson setting.
https://mattermost.atlassian.net/browse/MM-10513
> MM-10513: fix mlog-ing before initialization

- app/notification.go
- app/notification_test.go
The issue with the ticket of "no notification received" was due to the keywords followed by `:`. This PR adds notification/mention when `@user`, `@here`, `@all` and `@channel` has colon `:` at the end.
Jira ticket: [MM-10533]
> [MM-10533] Add notification when @user, @here, @all and @channel has colon ":" at the end

- i18n/en.json
- model/channel.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Deprecate the now unused Channels.ExtraUpdateAt. Not actually removing the database column from existing installs.
https://mattermost.atlassian.net/browse/MM-9739
> MM-9739: deprecate the now unused Channels.ExtraUpdateAt

- api4/channel_test.go
- api4/scheme_test.go
- api4/team_test.go
- app/app.go
- app/scheme.go
- i18n/en.json
- imports/placeholder.go
- jobs/interfaces/migrations_interface.go
- jobs/jobs.go
- jobs/jobs_watcher.go
- jobs/schedulers.go
- jobs/server.go
- jobs/workers.go
- migrations/advanced_permissions_phase_2.go
- migrations/migrations.go
- migrations/migrations_test.go
- migrations/migrationstestlib.go
- migrations/scheduler.go
- migrations/worker.go
- model/job.go
- model/migration.go
- store/sqlstore/channel_store.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/SqlStore.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Implements a online-migration system using the job server for doing generic online database migrations (out of scope: offline migrations, lazy migrations, blocking migrations).
Also implements the Advanced Permissions Phase 2 migration.
https://mattermost.atlassian.net/browse/MM-9728
> MM-9728: Online migration for advanced permissions phase 2

- cmd/commands/roles.go
- cmd/commands/roles_test.go
This makes the `roles` CLI commands advanced-permissions aware. It doesn't make any backwards incompatible changes to the commands, or any changes to their functionality, so they won't be particularly useful as advanced permissions progresses, but we'll be adding new CLI commands for the new functionality in due course, so the objective here is mostly not to break things for existing users who use or script the CLI.
https://mattermost.atlassian.net/browse/MM-10234
> MM-10234: Make CLI roles command advanced-permissions aware.

- api4/scheme_test.go
- app/scheme.go
- i18n/en.json
Checks migration state on *all* scheme-related API endpoints, and returns a well known error if the migration is not complete, so the UI can disable the scheme sections and show a useful message about the migration state.
https://mattermost.atlassian.net/browse/MM-10591
> MM-10591: Well known error for all scheme endpoints pre-migration.

- api4/scheme_test.go
- i18n/en.json
- store/sqlstore/scheme_supplier.go
- store/storetest/scheme_store.go
Instead of blocking deletion of a scheme that's in use, reset all teams/channels using it to the default scheme.
https://mattermost.atlassian.net/browse/MM-10615
> MM-10615: Reset teams/channels to default scheme on delete scheme.

- app/permissions.go
- i18n/en.json
- store/layered_store.go
- store/layered_store_supplier.go
- store/local_cache_supplier_schemes.go
- store/redis_supplier_schemes.go
- store/sqlstore/channel_store.go
- store/sqlstore/scheme_supplier.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/LayeredStoreDatabaseLayer.go
- store/storetest/mocks/LayeredStoreSupplier.go
- store/storetest/mocks/SchemeStore.go
- store/storetest/mocks/TeamStore.go
- store/storetest/scheme_store.go
- store/storetest/team_store.go
This PR makes the `permissions reset` CLI command schemes aware (i.e. it can reset the Phase 2 permissions stuff).
https://mattermost.atlassian.net/browse/MM-10235
> MM-10235: Make permissions reset CLI shcemes-aware.

- api4/scheme.go
- api4/scheme_test.go
- model/license.go
- model/license_test.go
- utils/license.go
Adds a license feature flag for custom schemes and checks it in the relevant API endpoints.
I've named it `CustomPermissionsSchemes` on the assumption that `CustomRoles` will be behind a different license feature when we implement them. However, I can modify this to just be `AdvancedPermissions` or something if we only want 1 license feature flag for the whole feature.
https://mattermost.atlassian.net/browse/MM-10606
> MM-10606: License feature flag for custom schemes.

- api4/oauth.go
- api4/user_test.go
- app/command_invite_people.go
- app/diagnostics.go
- app/user.go
- app/user_test.go
- model/config.go
- utils/config.go
Closes: #8813
Set default value of EnableUserCreation to true.
https://github.com/mattermost/mattermost-server/issues/8813
https://mattermost.atlassian.net/browse/MM-10640
> MM-10640 Set EnableUserCreation to true by default

- app/status.go
Skip cluster send when getting non-cached statuses. Not sure if this will completely fix the issue, but it should reduce cluster messages either way. I'll look at pre-release metrics after this goes in to see if the spikes still occur.
https://mattermost.atlassian.net/browse/MM-10498
> MM-10498 Skip cluster send when getting non-cached statuses

- web/web.go
Changes the order for registering the web endpoints, somehow saml endpoints where being considered as static preventing the actual code from running
> Change order of web endpoints

- app/webhook.go
- i18n/en.json
- model/incoming_webhook.go
- store/sqlstore/upgrade.go
- web/webhook_test.go
Adds the ability to lock an incoming webhook to a single channel.
Webapp changes: https://github.com/mattermost/mattermost-webapp/pull/1237
https://mattermost.atlassian.net/browse/MM-10352
> MM-10352: Add locking incoming webhooks to a single channel.

- model/channel.go
- store/storetest/channel_store.go
The previous complete removal of this field resulted in an incompatibility with 4.x servers that could not handle the now null column field.
Instead, ensure this field is at least always set to 0, with a plan to remove it altogether in a future release.
To test this, I created a fresh database with the 5.0 schema, added a few channels, then switched back to 4.10 without issues. Doing so without this branch resulted in the query failures observed in MM-10649.
https://mattermost.atlassian.net/browse/MM-10649
> MM-10649: soften Channels.ExtraUpdateAt deprecation

- config/default.json
- model/config.go
This change allows tuning the various *IdleConn* parameters for the `http.Client` used for intra-cluster messages.
I haven't tested this with an actual cluster yet, but want to get a build going for easy deployment/loadtesting.
None.
> allow tuning *IdleConn* for intra-cluster messages

- api4/post.go
- app/authorization.go
This PR removes the implicit granting of EDIT/DELETE permissions on posts when being accessed by their owners. It deliberately doesn't alter the situation as the code currently stands as to whether `XXX_POST` is a pre-requisite of `XXX_OTHERS_POSTS` or not (it appears to vary).
This is ready for review, but probably belongs in Phase 2 so don't merge it yet.
https://mattermost.atlassian.net/browse/MM-8814
> MM-8814: Remove implicit permission grants from post ownership.

- api4/user.go
- api4/user_test.go
- app/email.go
- config/default.json
- i18n/en.json
- model/config.go
- templates/deactivate_body.html
- utils/config.go
Add an option to user deactivated his account.
- add email template, when user deactivate his account
- add new config option to enable/disable this feature
Jira: https://mattermost.atlassian.net/browse/MM-1915
> [MM-1915] Add Deactivate Account - server side

- app/notification.go
Fixes email issues from MM-10638:
* Email notification from `@System` is sent to the user who DMed the OOO user
* Email notifications are sent to the OOO user
https://mattermost.atlassian.net/browse/MM-10638
> Avoid emails if user status is OOO or post is an auto response

- api4/scheme_test.go
- app/apptestlib.go
- app/permissions.go
- app/permissions_test.go
- store/sqlstore/scheme_supplier.go
- store/sqlstore/team_store.go
- store/storetest/scheme_store.go
- store/storetest/team_store.go
Roles are keyed by `name` rather than ID when assigned to member objects, but custom schemes were keying them by ID instead, meaning that permissions checks in custom schemes were looking up invalid roles.
Thanks to @mkraft for investigating the cause of this bug.
https://mattermost.atlassian.net/browse/MM-10757
> MM-10757: Default roles from scheme should be keyed by name not ID.

- api4/post.go
- app/plugin_api.go
- app/post.go
- model/post.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Adds `deleteBy` to the `Props` json of deleted posts. Normally the value is set to the user id of the current user except for deletion by a plugin in which case the value is set to the plugin id (but that may be changed in the future if the plugin API is changed to allow the plugin to set an arbitrary value).
[MM-10412](https://mattermost.atlassian.net/browse/MM-10412)
> MM-10412: Adds deleteBy prop to posts.

- api4/user.go
- config/default.json
- model/config.go
- web/handlers.go
Changes made when this mode is enabled:
- Login will return a generic error message instead of a specific messages for username and password.
- If MFA is enabled, the route to check if a user has MFA enabled will always return true. This will cause the MFA input screen to show even if the user does not have MFA enabled. The user may enter any value to pass the screen. Note that you can enable the setting to enforce MFA and there will be no user experience cost.
- Password reset will not inform the user that they can not reset their SSO account through Mattermost and claim to have sent the password reset email.
- All 500 errors are sanitized before being returned to the client. Use the supplied `request_id` to match user facing errors with the server logs.
> MM-10348 Adding experimental hardened mode.

- model/config.go
I missed changing this when I updated the wording of the setting from "protocol" to "scheme". The translation string reads `The custom URL scheme {{.Scheme}} is invalid...`
> MM-9547 Fixed invalid CustomUrlSchemes error message

- app/notification.go
- app/notification_test.go
The main fix here is to do a left trim to remove the punctuation preceding the word. I looked at improving the splitting logic to not be so clunky, but because we're matching arbitrary words and not just at mentions, it broke some existing behaviour, so I left that as it was.
https://mattermost.atlassian.net/browse/MM-10597
- Touches critical sections of the codebase (notifications)
> MM-10597 Improved handling of punctuation around notifications

- plugin/rpcplugin/rpcplugintest/supervisor.go
This test is failing sporadically, largely due to the use of a timeout
to verify results. A more robust solution is required.
N/A
> disable Supervisor_PluginRepeatedlyCrash

- Makefile
Setting the minio to a specific release and not to latest
n/a
will update the jenkins slaves and master with that
> use minio release instead of latest

- cmd/platform/main.go
- utils/config.go
- utils/config_test.go
The [original PR](https://github.com/mattermost/mattermost-server/pull/8853) got [reverted](https://github.com/mattermost/mattermost-server/pull/8876) due to a comedy of errors on my part, though exclusively around code meant to support `platform` invoking the `mattermost` binary -- the actual `config.json`, `i18n/`, etc. handling was correct.
This PR first cherry-picks the original commits, and then addresses said comedy with subsequent commits.
https://mattermost.atlassian.net/browse/MM-6839
> MM-6839: searching for paths relative to executable

- api4/apitestlib.go
- api4/user_test.go
- app/user.go
- app/user_test.go
The API to deactivate a user prematurely sanitized the user object before `sendUpdatedUserEvent` had a chance to distinguish admin websocket events from non-admin websocket events. When `PrivacySettings.ShowEmailAddress` was `false`, this resulted in both the admin and the non-admin receiving a blank email address, and triggering the resulting bug.
I've included a change in this PR to remove `UpdateNonSSOUserActive` altogether from the `App`. It wasn't used anywhere (outside of tests), and appears to have been deprecated in favour of alternate APIs. I wanted to ensure no one currently relied on the previous sanitizing behaviour -- all other uses of `UpdateActive` discard the returned `*model.User`.
https://mattermost.atlassian.net/browse/MM-10803
> MM-10803: remove premature user sanitization on deactivation

- app/notification.go
The code change skips push notifications for expired sessions as reported in #8930. Currently the notifications test-suite does not have any tests covering session handling. Since this is a bug \w potential information disclosure I guess fixing it first and then enhancing the entire notification test suite to test `sendPushNotification` would be a solid approach, I would hope for your feedback though!
https://mattermost.atlassian.net/browse/MM-10836
https://github.com/mattermost/mattermost-server/issues/8930
> Skip notifications for expired sessions

- store/sqlstore/channel_store.go
- store/sqlstore/team_store.go
This fixes the issue where if the migration tries to migrate an already
scheme-aware member object it would end up removing it's scheme-derived
roles.
Instead, only if the member object is unmigrated do we default to
setting the scheme-derived role booleans to false. We tell if it is an
unmigrated member object by checking if the booleans are set to null.
???
> Fix idempotency of scheme migrations.

- app/slackimport.go
- i18n/en.json
Fixes a bunch of `mlog` statements in the Slack Import code that got messed up during some of the big refactoring commits around logging and i18n.
https://mattermost.atlassian.net/browse/MM-10790
> MM-10790: Fix Slack Import logs that got broken in refactoring.

- cmd/mattermost/commands/import.go
Show importer logs at the end of CLI SLack import, to make it the same as the web based import.
https://mattermost.atlassian.net/browse/MM-10684
> MM-10684: Show logs on Slack Import CLI.

- app/import.go
In Slack importer, don't try and generate thumbnails for non-image files and SVGs.
https://mattermost.atlassian.net/browse/MM-10791
> MM-10791: Don't try and generate thumbnails for non-images/svgs.

- web/handlers.go
- web/handlers_test.go
The /login/sso/saml was returning to the browser json errors. Now redirect to an error page in the webapp.
[MM-10863](https://mattermost.atlassian.net/browse/MM-10863)
> MM-10863: Handle non-API errors with redirect to webapp

- api4/system.go
- api4/system_test.go
- app/app.go
- app/config.go
- config/default.json
- model/config.go
- utils/config.go
- utils/config_test.go
This is for an upcoming security improvement to only provide a limited version of the client config to non-logged-in users, so we need to be sure to pull down the complete client config after logging in. 
Because this is a breaking change for older apps, this setting is disabled by default with an experimental setting to turn it on for testing. Once we get to a point where we drop support for the 1.9 mobile apps, we can remove the setting and enable it for everyone.
https://mattermost.atlassian.net/browse/MM-8701
> MM-8701 Limit the number of client config fields sent before user logs in

- api4/post.go
- app/post.go
- einterfaces/elasticsearch.go
- i18n/en.json
- model/client4.go
- model/post_search_results.go
As discussed with George, this adds a `matches` field to search results done with Elasticsearch containing a list of all words in the post that will be highlighted
```
// Searching for appl*
{
"posts": ...,
"order": ...,
"matches": {
"postid1": ["apple", "apples"],
"postid2": ["apply", "#apple"],
}
}
```
Searches done without Elasticsearch will not contain this field.
https://mattermost.atlassian.net/browse/MM-6992
- Added API documentation (https://github.com/mattermost/mattermost-api-reference/pull/374)
required for all new APIs)
- All new/modified APIs include changes to the drivers
- Has enterprise changes (https://github.com/mattermost/enterprise/pull/300)
> MM-6992 Added highlighting to elasticsearch results

- Gopkg.lock
- Gopkg.toml
- utils/config_test.go
- vendor/github.com/mattermost/viper/flags_test.go
- vendor/github.com/mattermost/viper/overrides_test.go
- vendor/github.com/mattermost/viper/remote/remote.go
- vendor/github.com/mattermost/viper/util_test.go
- vendor/github.com/mattermost/viper/viper.go
- vendor/github.com/mattermost/viper/viper_test.go
Viper uses `os.Getenv` which doesn't distinguish between unset environment variables and those set to the empty string, so I had to make a change on their end to switch to `os.LookupEnv` which does differentiate between the two. I've submitted an upstream PR to hopefully take the changes on their end, but they're just living on our fork for now.
Changes to Viper are here: https://github.com/spf13/viper/pull/516
https://mattermost.atlassian.net/browse/MM-10730
> MM-10730 Added support for empty environment variables to viper

- app/notification.go
This PR fixes a regression where the option to reply to a push notification on iOS was not available cause of the Category not being set.
https://mattermost.atlassian.net/browse/MM-10991
> Add back the ability to reply to push notifications in iOS

- app/import_test.go
There is a typo in import_test.go for the theme's mentionBg value.
See:
https://github.com/mattermost/mattermost-webapp/pull/1340
https://github.com/mattermost/mattermost-mobile/pull/1770
> Fixing mentionBg typo in import_test.go

- app/cluster_handlers.go
- app/status.go
- model/status.go
- model/status_test.go
I'm pretty sure this will fix getting push (and other) notifications for plugins/integrations triggered by you (e.g. starting a zoom meeting in a DM) while you're viewing the channel.
https://mattermost.atlassian.net/browse/MM-10425
> MM-10425 Include active_channel in cluster update user status messages

- i18n/en.json
First commit simply re-sort the entire file to sort it alphabetically, the
second one extract the untranslated string, and remove the unussed ones.
I test it manually using `rg` command line tool to search for each of the "ids"
removed in the source file. It was the way that I used to polish the extractor approach.
The summary is 192 ids added (102 of them from permissions names and descriptions). Which I'm not sure we are using yet) and 520 deletions. We can remove the 102 ids from permission name and descriptions for now if you want. How do you see it @grundleborg?
> Using i18n extract to generate the i18n/en.json file

- web/static.go
Without this plugin web app bundles were 404ing because they were being handled at `/plugins/` when they are actually at `/static/plugins/`
> Fix plugins serving after subpath changes

- app/permissions.go
- i18n/en.json
- store/sqlstore/channel_store.go
- store/sqlstore/team_store.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/TeamStore.go
- store/storetest/mocks/UserStore.go
- store/storetest/team_store.go
- store/storetest/user_store.go
Make the `permissions reset` CLI command clear any custom role assignments.
This means the command will now work to clear up after full-custom (phase 3 advanced permissions style) roles.
https://mattermost.atlassian.net/browse/MM-10570
> MM-10570: Make permissions reset command clear custom role assignments.

- app/file.go
- app/user.go
- app/user_test.go
- store/sqlstore/file_info_store.go
- store/store.go
- store/storetest/file_info_store.go
- store/storetest/mocks/FileInfoStore.go
- utils/file_backend.go
- utils/file_backend_local.go
- utils/file_backend_s3.go
- utils/file_backend_test.go
This pull requests implements the following functionality:
- Clean Up FileInfo from user upon permanent user delete
- Delete files remaining files from users `FileStore`
- Implement `FileExists` function
- Related unit tests
https://mattermost.atlassian.net/browse/MM-10830
(Unsure about the critical, since it's user deletion I would define that as critical.)
> [MM-10830] Delete FileInfo and Files on Permanent User Delete; Implement File Exists Functionality

- app/app.go
- jobs/workers.go
Make job server work properly when license is uploaded and/or jobs are configured on/off without a server restart. There were duplicate config checks in the wrong place which caused the problem with some job types before. See enterprise changes.
https://mattermost.atlassian.net/browse/MM-10269
Enterprise changes: https://github.com/mattermost/enterprise/pull/316
> MM-10269: Make jobserver work without restart.

- app/import.go
- store/layered_store.go
- store/sqlstore/store.go
- store/sqlstore/supplier.go
- store/store.go
- store/storetest/mocks/LayeredStoreDatabaseLayer.go
- store/storetest/mocks/SqlStore.go
- store/storetest/mocks/Store.go
- store/storetest/store.go
This is to prevent races between replication and reads against the replicas during bulk import.
Based on https://pre-release.mattermost.com/core/pl/m1wwgtakttnnfquh6pxo79rr1h
> Lock bulk importing to master database node

- app/command_join.go
- app/command_join_test.go
fix join and open channel commands to work with a tilde
[MM-10910](https://mattermost.atlassian.net/browse/MM-10910)
> MM-10910 fix join and open channel commands to work with tilde

- app/session.go
- app/status.go
- app/web_conn.go
- app/web_hub.go
Fixes the case described in the ticket where a user is away on one or more devices, then briefly connects with a new device and then disconnects, causing their status to stay as online for 5 minutes (away timeout) before they start receiving notifications again. This tracks the last activity at for each websocket connection separately. If one disconnects, it checks the last activity time of the other web conns to set the status appropriately.
@esethna not sure if you or QA want to try this out on the spinmint first
https://mattermost.atlassian.net/browse/MM-7088
> MM-7088 Reset status to away after web conn disconnect if necessary

- utils/subpath.go
- utils/subpath_test.go
This addresses a missing component of the subpath support: rewriting `manifest.json` to reflect the configured subpath.
https://mattermost.atlassian.net/browse/MM-11036
> MM-11036: subpath: rewrite manifest.json too

- app/import.go
- app/import_test.go
This doesn't introduce new fields as we would then break backwards
compatability with old "roles" fields if we change the "roles" field to 5.0 semantics.
We can add custom fields if/when
we go to "version 2" of the bulk import format.
https://mattermost.atlassian.net/browse/MM-11078
> Make import compatible with scheme-roles.

- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
It was causing a syntax error in the full text search clause for Postgres.
https://mattermost.atlassian.net/browse/MM-10972
> MM-10972 Ignore | characters in postgres channel search

- model/message_export.go
- store/sqlstore/compliance_store.go
Adding RootId information to MessageExport. The idea is to include
"conversation" concept in to the compliance exports (for now only for CSV, but
in the future for Actiance and Global Relay)
> Adding RootId information to MessageExport

- app/app.go
- cmd/mattermost/commands/server.go
Make sure diagnostic ID is loaded before client config.
https://mattermost.atlassian.net/browse/MM-10999
> Make sure diagnostic ID is loaded before client config.

- api4/channel.go
- api4/channel_test.go
- i18n/en.json
Originally reported as an issue restoring a channel, the root problem here is that we shouldn't allow a direct or group channel to be marked as deleted in the first place.
https://mattermost.atlassian.net/browse/MM-11118
https://github.com/mattermost/mattermost-server/issues/9001#issue-335775057
> MM-11118: disallow deleting direct or group channels

- app/post.go
This PR is a small behavior change with link previews. When a user posts a message with a URL, we get the contents of that URL and check for `<meta>` annotations that conform to the [Open Graph protocol](http://ogp.me/). If these annotations are present, we show a link preview in Mattermost (if that setting is enabled.) We also follow redirects when performing this action, which means that sometimes we follow a redirect, and our final landing page provides a `og:url` different from the URL the user put in their message. This behavior is intended, but confusing. **This PR ignores the `og:url` property, and always uses the link the user originally provided instead.** We still follow redirects for displaying other link preview information.
Closes: Github #9008, JIRA …
> MM-10603: Ignore Redirects and Other Changes when Displaying Link Previews

- app/webhook.go
- web/web_test.go
- web/webhook_test.go
Allow systeadmin webook to post to read only town square. This makes webhook behaviour consistent with regular API-based posting behaviour.
https://mattermost.atlassian.net/browse/MM-11106
> MM-11106: Allow systeadmin webook to post to read only town square.

- api4/command.go
- api4/command_test.go
Remove unnecessary command_test route.  Test functionality is replaced with `httptest` whenever needed.
Jira ticket: [MM-10754](https://mattermost.atlassian.net/browse/MM-10754)
> [MM-10754] Remove unnecessary command_test route

- model/user.go
- model/user_test.go
This PR blacklists System as a username. The justification is that system notifications, e.g. user join messages are sent with that nickname, allowing an attacker to act as a system user for social engineering, an example would be:
Implementation was discussed with @crspeller, there is no ticket or issue right now for it.
> Blacklist System as Username

- i18n/en.json
- model/config.go
- model/config_test.go
The markdown renderer on the client doesn't support protocols containing a plus or period, so update the validation on the server to match that
- Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
> Update custom url schemes error message to reflect what we actually support

- api4/emoji.go
Firefox Fetch implementation consider a cut in the connection when is
too soon a "Network error". If we manage the post data before close the
connection it behaves correctly.
[MM-11189](https://mattermost.atlassian.net/browse/MM-11189)
> MM-11189: Do not close the connection abruptly on too big emojis

- web/handlers.go
- web/saml.go
I missed the context's SiteURLHeader when testing, in part because I had implemented the root redirect and wasn't testing using a proxy server that redirected `/` elsewhere. Hurrah for the spinmint testing!
https://mattermost.atlassian.net/browse/MM-11241
https://mattermost.atlassian.net/browse/MM-11246
> MM-11241: fix context site url header

- app/notification.go
- model/user.go
This PR addresses the teammate display name not being shown when a push notification was sent.
It should be tested and loadtested in order to ensure it does not creates performance issues, if that is the case we can always remove the user preference and always use the server one.
https://mattermost.atlassian.net/browse/MM-11105
> push notifications follow teammate name display user or server setting

- utils/markdown/inlines.go
- utils/markdown/text_range_test.go
This includes information of the original location of (inline) text nodes when inspecting a markdown string.
There's no ticket for this, but having this functionality is a prerequisite for mattermost/mattermost-plugin-autolink#11 and mattermost/mattermost-plugin-autolink#7
---
See the discussion in mattermost/mattermost-plugin-autolink#7 on why having this information is useful.
Also, I think it would make sense (as a general optimization in the markdown parser) to concatenate consecutive text nodes. Currently there are a few cases where correct but not very obvious results are produced. For example, `hello!` consists of two text nodes (`hello` and `!`); same for things like `&randomstuff;` (looks like a char ref, but isn't one, and becomes `&` and `randomstuff;`).
FWIW, this is an …
> Expose range information for markdown text nodes [WIP]

- app/user.go
This PR enhances the log output from MM-10830 to print a warning when a file was not found or the delete failed for various reasons. Previously, deletion errors were ignored and the file not found warning was opaque.
https://mattermost.atlassian.net/browse/MM-10830
> [MM-10830] Enhance Log Output from Permanent Delete

- app/notification.go
- app/notification_test.go
- model/user.go
Add localized timestamp support for email notifications
Also, added support to respect `use_military_time` preference
* User timezone set to **America/Denver** . 
* Time from screenshots: 3pm Denver vs 5pm NewYork
**Direct Message**
**12 Hour Format**
**24 Hour Format**
**Group Message**
**Public Channel**
**Private Channel**
> Add localized timestamp support for email notification

- api4/reaction_test.go
- app/reaction.go
- i18n/en.json
Apply the same rule to town square when it's read only for reactions as we do for posts. Web client and RN changes to follow in separate PRs.
https://mattermost.atlassian.net/browse/MM-11172
> MM-11172: Don't allow reacting in read-only town square.

- utils/markdown/inlines.go
- utils/markdown/inspect.go
- utils/markdown/text_range_test.go
This optimizes the way markdown text nodes are exposed in `Inspect()`. For example, "hello!" was previously separated into two text nodes ("hello" and "!") due to the way the parser works. With my PR such nodes are now merged when inspecting a markdown string.
---
Related: #9067
> Merge consecutive text nodes when inspecting markdown

- model/manifest.go
- model/manifest_test.go
- plugin/supervisor.go
This avoids the need to distribute multiple plugins per architecture. The manifest can now look like:
```
...
"backend": {
"executables": {
"linux-amd64": "backend/dist/plugin-linux-amd64",
"darwin-amd64": "backend/dist/plugin-darwin-amd64",
"windows-amd64": "backend/dist/plugin-windows-amd64.exe"
}
},
...
```
The old `executable` parameter remains supported, so this is a backwards-compatible change.
https://mattermost.atlassian.net/browse/MM-11366
> MM-11366: support a plugin bundle with multiple executables

- api4/brand.go
- api4/file.go
- api4/team.go
- api4/user.go
This is a continuation of the MM-11189 bug fix already merged in
release-5.1 (#9083). The emoji upload was failing, the brand one is failing
until this PR is merged, and the other 2 cases are for API endpoints
that wasn't failing because the ui prevent the file upload.
[MM-11189](https://mattermost.atlassian.net/browse/MM-11189)
> Do not close the connection abruptly on too big file uploads

- app/extension.go
- config/default.json
- i18n/en.json
- model/config.go
- model/oauth.go
- templates/complete_saml_extension_body.html
- web/saml.go
Add authentication support for extensions.
This supports multiple extensions via the `ExtensionSettings.AllowedExtensionsIDs` config property.
The key in this change is the communication layer between the api and the extension.
We are relying on the chrome api to send data safely between the api and the extension that made the request.
https://mattermost.atlassian.net/browse/MM-11151
> Support for Embeded chat

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/hashicorp/yamux/session.go
I only locked `go-plugin` and `go-hclog` as those were the only packages we're using in our `plugin` package. Not super familiar with dep so let me know if there's anything else I need to do here.
https://mattermost.atlassian.net/browse/MM-11349
> MM-11349 Lock go-hclog and go-plugin dependencies to a revision

- app/diagnostics.go
- model/manifest.go
- model/manifest_test.go
- model/plugins_response_test.go
- plugin/environment.go
This lets us converge on the use of the term `server` everywhere instead of sometimes `backend` and sometimes `server`. We're still using `webapp` and will eventually support `mobile` as well.
The plan is actually to rip out these deprecations as part of releasing 5.2, but I want to coordinate the extra additional breakage at the same time, so for now this is a backwards compatible change.
None.
> Support `server`, deprecate `backend` in plugin manifest

- utils/markdown/inlines.go
- utils/markdown/text_range_test.go
Fixes a bug in the Range generation for markdown Text nodes, which caused e.g. the autolink plugin to fail/crash (depending on the message containing `&`).
> Fix invalid markdown text ranges

- api4/post.go
- api4/post_test.go
- app/post.go
- model/client4.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Add API `GET 'api/v4/channels/{channel_id:[A-Za-z0-9]+}/posts/unread'`.
The idea is to jump into the last unread post and return a list of posts around it.  This API prevents having multiple requests of loading more posts when there are too many unread post.
Jira ticket: [MM-11210](https://mattermost.atlassian.net/browse/MM-11210)
> [MM-11210] Add API GET 'api/v4/channels/{channel_id:[A-Za-z0-9]+}/posts/unread' for scrolling overhaul

- app/import.go
- app/import_test.go
- i18n/en.json
Currently the bulk import tool doesn't support file attachments. Added the support for the same
https://github.com/mattermost/mattermost-server/issues/9006
> Support attachments in post and replies - Bulk import

- app/email.go
- app/notification.go
- app/session.go
- i18n/en.json
- templates/deactivate_body.html
- templates/email_change_body.html
- templates/email_info.html
- templates/invite_body.html
- templates/mfa_change_body.html
- templates/password_change_body.html
- templates/post_body_full.html
- templates/reset_body.html
- templates/signin_change_body.html
- utils/html.go
- utils/html_test.go
(Some messages have not been fixed yet. See the bottom of Issue for details.)
Broke messages containing HTML tag to individual messages, and modifyed accordingly other resources such as e-mail templates etc.
#6174
[JIRA](https://mattermost.atlassian.net/browse/MM-3736)
---
UPDATED: 2018/06/27
| No | Status  | Message ID |
|:--:|:--------|:-----------|
| 1  | [DONE](https://github.com/mattermost/mattermost-server/pull/8903/commits/298194723a8d8555bcb304e1a147d85f888a6c4f)       | api.admin.test_email.body |
| 2  | [DONE](https://github.com/mattermost/mattermost-server/pull/8903/commits/6a014c90a304521a71f5e6f30ff0db07947dae79)    | api.templates.email_change_body.info |
| 3  | [DONE](https://github.com/mattermost/mattermost-server/pull/8903/commits/4b510c95d1ce754b5e418a2b8594ba30dca06fcd) …
> Break HTML blocks to individual strings

- app/channel.go
- app/channel_test.go
- app/diagnostics.go
- model/config.go
Implementation of custom default channel functionality using an experimental config entry. Config entry has to be a string array containing channel names of default channels. 
Change is non breaking since previous behavior is kept if experimental flag is not set. Code duplication was removed and consistency for `ExperimentalEnableDefaultChannelLeaveJoinMessages` implemented, since previously all other default channels but `town-square` still sent `Join/Leave` messages. In this PR all default channels don't post a join message.
https://github.com/mattermost/mattermost-server/issues/9058
https://mattermost.atlassian.net/browse/MM-11180
> [MM-11180] Experimental Custom Default Channels (closes #9058)

- app/diagnostics.go
- config/default.json
- model/config.go
- utils/config.go
Exposes `ExperimentalSidebarPreference` in config, to be used in the new sidebar channel ordering feature.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1374
Redux PR: https://github.com/mattermost/mattermost-redux/pull/549
> Add ExperimentalSidebarPreference in the config

- utils/markdown/autolink.go
- utils/markdown/autolink_test.go
- utils/markdown/commonmark_test.go
- utils/markdown/html.go
- utils/markdown/inlines.go
- utils/markdown/markdown.go
This is required for the scrolling overhaul, but since it's a large change to a mostly unrelated part of the codebase, I figured I'd commit this to master and then merge master back into the feature branch.
I did my best to translate https://github.com/github/cmark/blob/master/extensions/autolink.c into Go so that we match GitHub's behaviour as perfectly as possible. Hopefully this is easier to understand than the reference code.
https://mattermost.atlassian.net/browse/MM-11451
> MM-11451 Added autolinking to Markdown parser

- api4/webhook_test.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/outgoing_webhook.go
- model/outgoing_webhook_test.go
- store/sqlstore/upgrade.go
- store/sqlstore/webhook_store.go
- store/storetest/webhook_store.go
added the custom icon and username for the outgoing webhook and its response
https://github.com/mattermost/mattermost-server/issues/8272
> added the custom icon and username for the outgoing webhook and its response

- app/app.go
- cmd/mattermost/commands/server.go
- einterfaces/elasticsearch.go
- i18n/en.json
Make Elasticsearch work after config/license change without restart.
https://mattermost.atlassian.net/browse/MM-11243
> MM-11243: Make Elasticsearch work after enabling without restart.

- plugin/client_rpc.go
- plugin/client_rpc_generated.go
- plugin/interface_generator/main.go
We never actually initialized `log` on `apiRPCClient`, and it can't log without making an RPC call anyway, so just switch to logging errors from the plugin to STDERR instead.
https://mattermost.atlassian.net/browse/MM-11425
> MM-11425: s/mlog/log/ in apiRPCClient

- app/plugin_deadlock_test.go
- app/plugin_hooks_test.go
- plugin/environment.go
- plugin/hooks.go
- plugin/supervisor.go
[sync.RWMutex](https://golang.org/pkg/sync/#RWMutex) was unsafe for our usage within the plugin environment:
> If a goroutine holds a RWMutex for reading and another goroutine might call Lock, no goroutine should expect to be able to acquire a read lock until the initial read lock is released. In particular, this prohibits recursive read locking. This is to ensure that the lock eventually becomes available; a blocked Lock call excludes new readers from acquiring the lock.
When a plugin calls the API to create a post, the environment triggers hooks and effectively triggers recursive read locking. This "works", up until someone needs an exclusive lock (like during activate or deactivate). I pursued releasing the lock early, but that just shifted the manifestation elsewhere without removing …
> MM-11431: handle plugin deadlocks

- app/oauth.go
We save it for the auth code flow, so saving it in the implicit flow as well. Makes it easier for deauthorizing apps and other later use. Note there's no refresh tokens for the implicit flow.
> Save OAuth access token to DB for consistency with other flows

- api4/oauth.go
Allow OAuth 2.0 clients redirecting to the Mattermost login and authorize pages to provide a hint that the user they are trying to authenticate with will be logging in using SAML. This allows the OAuth 2.0 client to skip the Mattermost login page and go straight to the SAML IDP's login page, removing a previously required user click in the process.
> Add OAuth2 login hint for SAML

- plugin/client_rpc.go
This allows plugin hooks to return the result of calling the API as an `error`.
None.
> gob register AppError for plugins

- app/app.go
- app/cluster.go
- jobs/schedulers.go
- jobs/server.go
At present, in a HA cluster, every app node will run all the job schedulers, resulting in time-based scheduled jobs being scheduled `n` times where `n` is the number of app servers in the cluster, rather than just once. This changes the schedulers subsystem to only schedule jobs on the cluster master when operating in HA mode. Outside of HA mode, or where HA app servers have `RunSchedulers: false` in the config, this change has no effect.
https://mattermost.atlassian.net/browse/MM-10502
> MM-10502: Only cluster master should run job schedulers.

- model/manifest.go
- plugin/environment.go
- web/static.go
- Adds the ability for plugins to use code-splitting or serve static assets separate from their main bundle. 
- Also adds the ability for plugins to use wasm code.
> Adding support for code split plugins.

- app/post_test.go
- utils/markdown/inlines.go
- utils/markdown/links.go
- utils/markdown/links_test.go
- utils/markdown/markdown.go
This logic is needed because both the server and client attempt to rewrite image links in the post. If the client sees that the server has rewritten the image link, it won't bother rewriting them as well, but it does have logic to rewrite them if the server hasn't rewritten them.
Prior to this, the server couldn't rewrite images with dimensions specified since those don't conform to the CommonMark spec. If you just posted an image with dimensions, the client would know to proxy the image since it understood them.
The problem came when you posted multiple images, one without dimensions (that gets rewritten by the server) and another that has dimensions (that the server couldn't rewrite). Because the first one was rewritten, the client wouldn't know to rewrite the second one, so it would be …
> MM-11175 Add logic to server to understand markdown images with dimensions

- app/team_test.go
- app/user_test.go
- model/user.go
- model/user_test.go
- model/utils.go
- model/utils_test.go
- store/storetest/channel_member_history_store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/post_store.go
- store/storetest/scheme_store.go
- store/storetest/status_store.go
- store/storetest/storetestlib.go
- store/storetest/team_store.go
- store/storetest/user_access_token_store.go
- store/storetest/user_store.go
Actually use the existing validation to test if a user's email field is valid
https://mattermost.atlassian.net/browse/MM-11521
https://mattermost.atlassian.net/browse/MM-11522
> MM-11521/MM-11522 Fix being able to create users with invalid emails through API

- LICENSE.txt
We are removing the mention of the webapp/ directories as they have been moved to their own repository that is entirely under Apache License v2.0.
https://mattermost.atlassian.net/browse/MM-11430
> MM-11430 Update LICENSE.txt to include plugin/ under Apache License v2.0

- app/login.go
- app/oauth.go
- app/plugin_api.go
- app/plugin_requests.go
- model/session.go
- model/session_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/context.go
- plugin/plugintest/api.go
This PR implements CSRF token which are being attached to users sessions. The CSRF tokens are rolled out and can be enforced as alternative to XHR checks in the plugin request system. The plugin API was extended to allow a simple implementation in the plugins code base.
The PR lays the foundation for the further roll out in the MM core.
https://mattermost.atlassian.net/browse/MM-10346
> [MM-10346] CSRF Token Implementation for Plugins

- app/notification.go
Push notification is sent as a channel wide mention when using `at-here`
https://mattermost.atlassian.net/browse/MM-11545
> send channel wide push notification type when at-here is used

- api4/channel.go
- api4/channel_test.go
- app/channel.go
- app/notification.go
- app/notification_test.go
Allow to Leave an archived channel from the API when you are the channel
member. Also avoid any notification outgoing from archive channels
interaction.
[MM-11529](https://mattermost.atlassian.net/browse/MM-11529)
> MM-11529: Allow to Leave an archived channel from the API

- app/file.go
- app/plugin_deadlock_test.go
- app/plugin_hooks_test.go
- app/post.go
- plugin/hooks.go
As discussed, this changes the interpretation of the nil return values for `MessageWillBePosted` and `FileWillBeUploaded` to no-op. This has the nice performance improvement of not requiring the plugin to return the data back over net/rpc in the common case of no-oping, and avoids the previous "shoot yourself in the foot" semantics of implementing what appears to be a no-op hook function only to block all posts and/or file uploads.
https://mattermost.atlassian.net/browse/MM-11575
> MM-11575: change plugin nil semantics

- app/web_hub_test.go
Remove the `th.App.HubStop()` because when the server is shut down it calls the hubstop and adds the close for the WS connections.
with that, I was able to run in my local machine all the time, before most of the test execution failed.
and in the CI it starts passing without the issue we saw in other build/releases (timeout)
Opening this against release-5.2, I opened one for master to test and I ran around 10 builds and the issue did not happen anymore before we saw that very often 
jira: https://mattermost.atlassian.net/browse/MM-11317
> try to fix the flaky test - TestHubStopWithMultipleConnections

- cmd/mattermost/commands/message_export.go
We decide to remove the global relay export command because the behavior
defer from the other commands (csv and actiance export). The expectation
of similar behavior can generate problems to some users, so we prefer to
disable it for now.
[MM-11003](https://mattermost.atlassian.net/browse/MM-11003)
> Remove global-relay export command from the cli

- api4/file.go
- app/import_functions.go
- app/import_functions_test.go
Small fixes for attachments import. Force the thumbnail/preview
generation and follow the "not-destroy" policy appending attachments at
the end of the current existing post/reply. Besides I improved how it
checks for reply posts to update.
[MM-9747](https://mattermost.atlassian.net/browse/MM-9747)
> MM-9747: Small fixes for attachments import

- utils/markdown/autolink.go
- utils/markdown/autolink_test.go
- utils/markdown/commonmark_test.go
- utils/markdown/html.go
- utils/markdown/inlines.go
A followup to the previous autolinking PR since there were a few issues with that code and links containing unicode.
@coreyhulen If your autolinking plugin is updated to use the autolinking provided by utils/markdown, this will improve that behaviour
> Update serverside markdown parser to respect unicode and capitalized links

- model/utils.go
Ignore link-local class addresses when selecting the IP address to advertise to the cluster.
Requested by Jason Blais via e-mail
> Ignore link-local addresses in cluster advertisement

- cmd/mattermost/commands/jobserver.go
- cmd/mattermost/commands/server.go
The new locking primitives in 5.2 around jobs assume the worker/scheduler was actually started, so don't try to stop if not started.
https://mattermost.atlassian.net/browse/MM-11637
> MM-11637: avoid stopping unstarted jobs

- utils/config.go
- utils/config_test.go
Because of some issues reading settings keys containing periods, this code used to pave over the plugin settings with the contents of `MM_PLUGINSETTINGS`. That was preventing the user from specifying any single plugin setting from the environment, even if `MM_PLUGINSETTINGS` is not being used. This makes sure that setting is actually in use before paving over the PluginSettings field.
https://mattermost.atlassian.net/browse/MM-11382
> MM-11382 Remove special handling of PluginSettings when loading config

- store/sqlstore/channel_store.go
The problem was that the method was caching without taking care that
some times may be asked for the memberships with the deleted channels
and sometimes not. If we share the cache there, there will be
inconsistencies.
[MM-11678](https://mattermost.atlassian.net/browse/11678)
> MM-11678: Split the cache for includeDeleted and not includeDeleted memberships requests

- app/post.go
- model/post.go
This PR adds a `PostId` field to `model.PostActionIntegrationRequest`. This plugins to e.g. delete the post, when a action button is pressed.
See [discussion on pre-release](https://pre-release.mattermost.com/core/pl/j5nauysw9fn4mp8ce6gmdfyi1e)
> Add PostId to PostActionIntegrationRequest

- api4/post_test.go
- app/channel.go
- app/diagnostics.go
- app/post.go
- config/default.json
- model/config.go
- utils/config.go
Change View Archive Channels to a new config setting that's off by default.
https://mattermost.atlassian.net/browse/MM-11782
Webapp Changes: https://github.com/mattermost/mattermost-webapp/pull/1598
> MM-11782: Make archived channels experimental and off-by-default.

- app/import.go
- cmd/mattermost/commands/sampledata.go
- i18n/en.json
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
Force correct order on messages generated in the bulk, and at the end of
the import, update the LastPostAt (this is needed because we import replies as part of the original message, so a reply can be anywhere in the time, but the import will be at the same time of the "parent post").
[MM-11572](https://mattermost.atlassian.net/browse/11572)
> MM-11572: Force correct order on messages generated in the bulk

- utils/api.go
For non-browser clients trying to connect to the WebSocket that don't provide an Origin header, don't fail the WebSocket upgrade when `ServiceSettings.AllowCorsFrom` is non-blank.
Cause: Introduced over a year ago with a security fix to WebSockets for CORS.
https://mattermost.atlassian.net/browse/MM-11506
> MM-11506 If no origin header is set for WebSocket, do not fail upgrade when AllowFromCORS is set

- api4/post.go
- app/post.go
- app/post_test.go
- model/post.go
Adds more fields for post actions to support the "select" type in message attachments.
Now a post with this attachment:
```
"attachments": [
{
"pretext": "This is the attachment pretext.",
"text": "Action options",
"actions": [
{
"name": "Select an option...,
"integration": {
"url": "http://127.0.0.1:5000/action_users",
"context": {
"action": "do_something"
}
},
"type": "select",
"options": [
{
"text": "Option1",
"value": "opt1"
},
{
"text": "Option2",
"value": "opt2"
},
{
"text": "Option3",
"value": "opt3"
}
]
}
]
}
]
```
Will get a POST with the following payload, when a user selects an option:
```
{
"user_id": "bn5yzq7jmpgz8rszcgxa1dxokh",
"post_id": "89wkk3u9npbbmrdfowd1wz6pcy",
"type": "select",
"data_source": "",
"context": {
"action": "do_something",
"selected_option": "opt3"
}
} …
```
> MM-8477 Support for interactive menus in message attachments

- api4/system.go
- api4/system_test.go
- model/client4.go
Adds API endpoint to retrieve redirect location from a URL for use to follow shortened links (ex bitly) to preview the content in the webapp. Because of CORS the request cannot be done directly from via the browser.
[MM-11786](https://mattermost.atlassian.net/browse/MM-11786)
> MM-11786: Adds API endpoint to retrieve redirect locations.

- api4/team.go
The import team api endpoint was checking the max size using a "Magic
number" directly in the code, I moved it at the top of the file as a
constant and give it a name.
> Moving magic number to constant in team import

- Makefile
To easy run mattermost using delve, I added a task in to the Makefile.
Instead of `make run-server` you can `make debug-server` and it will
compile and load mattermost server in `delve`, and then you can set your
break points and run it.
> Add debug-server task to make file to run mattermost using delve

- app/diagnostics.go
- config/default.json
- model/config.go
Adding IdAttribute setting for SAML for allow more robust treatment of
deactivated accounts
[MM-10532](https://mattermost.atlassian.net/browse/10532)
> Adding IdAttribute setting for SAML

- api4/team_test.go
- app/team.go
- app/team_test.go
- i18n/en.json
- model/team.go
This allows individual teams to be restricted to an email domain whitelist. The per team setting overrides the server-wide whitelist, but teams which do not set the option will still fallback to the server-wide setting.
The change leverages the preexisting team.allowedDomains model property. For now, it must be modified via REST API, as UI has not been implemented.
I started modifying the SanitizeTeam code to permit updates to allowedDomains, but wasn't sure if that should be included in this PR or later when UI is added. I left it out for now, but can update the PR, if appropriate?
Tests have been added for the AddUserToTeam* methods to make sure bad email domains get blocked when the whitelist is enabled. I'm unsure if there are other code paths which may need testing. Open vs invite …
> [WIP] MM-11327: Restrict Teams by Email

- app/diagnostics.go
- config/default.json
- model/config.go
Add EnableSyncWithLdapIncludeAuth config to allow to include the
AuthData in the synchronization process or not.
[MM-10532](https://mattermost.atlassian.net/browse/10532)
> MM-10532: Add EnableSyncWithLdapIncludeAuth config

- api4/reaction_test.go
- app/reaction.go
- i18n/en.json
Forbid to react and remove reactions in archived channels.
[MM-11270](https://mattermost.atlassian.net/browse/11270)
> MM-11270: Forbid react/de-react in archived channels

- cmd/mattermost/commands/channel.go
this morning @jespino and I was running the move channel command and I did not set the `--username` because I did not read the full help and just checked the example and in the example, it not contains this flag.
So adding this flag in the example.
N/A
> add --username in the example for the commands

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Add GetLDAPUserAttributes method to the plugin API to add back functionality that the `ldapextras` built-in plugin had.
Example usage:
```go
attributesMap, err := p.API.GetLDAPUserAttributes(userID, []string{"sAMAccountName", "description"})
if err != nil {
return err
}
// do something with attributesMap
```
https://mattermost.atlassian.net/browse/MM-11762
> MM-11762 Add GetLDAPUserAttributes method to the plugin API

- api4/post_test.go
- model/search_params.go
bug fix: after and before search flags should not be inclusive of the selected date
N/A
> bug fix: after and before search flags should not be inclusive of the selected date

- app/notification.go
Change subject line for email when in a DM with webhooks to use other username instead of webhook override.
[MM-11710](https://mattermost.atlassian.net/browse/MM-11710)
> MM-11710 Add a check to webhook messages to populate username from DM channel for email subject

- utils/config.go
- utils/config_test.go
There are numerous issues here, including some non-determinism in the viper library (fixable) and some annoying behaviour regarding periods in keys, often used by plugin ids (fix unknown). Let's defer the handling of same until we can get our config loading library to do what we need it to do vs. having to hack around viper all the time.
https://mattermost.atlassian.net/browse/MM-11720
> MM-11720: disable loading plugin specific config from the environment

- api4/apitestlib.go
- api4/brand_test.go
- api4/file_test.go
- api4/openGraph.go
- api4/post_test.go
- api4/team_test.go
- api4/user_test.go
- app/app.go
- app/opengraph.go
- app/opengraph_test.go
- app/post.go
- app/post_metadata.go
- app/post_metadata_test.go
- app/post_test.go
- i18n/en.json
- model/post.go
- utils/testutils/testutils.go
Here's the rest of the metadata stuff. It's more expensive than the earlier stuff, but I did add at least some basic caching for the new stuff. There's a lot that we could do to further improve performance as well like paralleling network requests or adding additional caching, even perhaps on-disk caching.
The only thing potentially missing from this is that OpenGraph images don't have dimensions. I'm not 100% sure if we need this, so I left it out for the time being since that would require an additional network request.
I'm also going to make a follow up ticket to improve the tests for this. We have no way to mock the http.Client calls here so these tests need an internet connection to pass. I've pointed them at files in https://github.com/hmhealey/test-files so that we have full …
> MM-11272 Add OpenGraph and image dimension metadata to posts

- api4/channel.go
- model/channel.go
Fixes the Channel Update & Patch endpoints to work on a *copy* of the cached object so as not to pollute the cache if the update fails.
https://mattermost.atlassian.net/browse/MM-11649
> MM-11649: Fix caching issue in channel API endpoints.

- app/user.go
App.SendPasswordResetEmail already returns a properly formatted AppError, so App.SendPasswordReset was just re-wrapping it except with the details replaced with a generic error message
> Stop re-wrapping password reset email error in another error

- api4/command_test.go
- app/command.go
This fix for https://github.com/mattermost/mattermost-server/issues/9356 naively concatenates the GET query parameters on the provided endpoint URL with Mattermost's ones.
Parameters specified by both the user and Mattermost will be duplicated (see https://github.com/mattermost/mattermost-server/issues/9279#issuecomment-416783023). Currently, no warning is shown for this, either in the webapp/documentation, or on the server logs.
Jira: https://mattermost.atlassian.net/browse/MM-11895
Github: https://github.com/mattermost/mattermost-server/issues/9356
> MM-11895: Don't crush user-provided GET parameters on slash command URLs

- api4/channel.go
- app/channel.go
- model/client4.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Add specific autocomplete endpoint for search autocomplete. It list all
your channels, instead of all public channels, because when you search
what makes sense is to search in your own channels because the search
results only will be in your own channels.
[MM-11725](https://mattermost.atlassian.net/browse/11725)
> MM-11725: Add specific autocomplete endpoint for search autocomplete

- app/command_channel_header.go
- app/command_channel_purpose.go
- app/command_channel_purpose_test.go
- app/command_channel_rename.go
- app/command_channel_rename_test.go
- app/command_invite.go
- app/command_invite_test.go
- app/command_join.go
- app/command_join_test.go
- app/command_remove.go
- app/command_remove_test.go
Where necessary, rewrite permissions checks in built-in slash command handlers to be fail-safe and more robust against future code changes. Also add unit tests where the modified code is not properly unit tested.
https://mattermost.atlassian.net/browse/MM-11230
> MM-11230: Make permissions checks in commands failsafe.

- app/plugin_hooks_test.go
- plugin/client_rpc.go
- plugin/client_rpc_generated.go
- plugin/interface_generator/main.go
It is not possible to register the unexported `errorString` from the github.com/pkg/errors package with gob (or the golang.org/pkg/errors package for that matter), making it impossible to return an `error` constructed this way over an RPC plugin. Instead, adopt the proposal outlined in https://github.com/golang/go/issues/23340 and encode an unregistered `error` type to a newly created `ErrorString` type that merely preserves the `.Error()` string value but still allows registered error types to be sent across the wire. Ensure `model.AppError` (which is registered) can be sent without loss of fidelity.
It will not be possible for plugins to take complete advantage of these changes until they are recompiled and running against 5.4, since the `ErrorString` must be registered by both server …
> MM-11734: better plugin `error` handling

- app/login.go
On LDAP login it was getting the user from the LDAP, not from
mattermost. It makes sense because the login can be done without
existing mattermost user. But for be sure the MFA is activated we need
to check the real user when it exists.
[MM-12045](https://mattermost.atlassian.net/browse/MM-12045)
> MM-12045: Fix MFA for ldap accounts

- app/command.go
- app/post.go
- app/slackimport.go
- app/webhook.go
- model/slack_attachment.go
Refactored parseSlackAttachment functions from https://github.com/mattermost/mattermost-server/blob/master/app/post.go#L312
into model/slack_attachments.go so that plugins have access to them.
https://mattermost.atlassian.net/browse/MM-11860
Nothing in the checklist really applied, but I did write a plugin to test my changes located here:
https://github.com/cjbirk/mattermost-slackparse-plugin
> [MM-11860]: Expose slack attachment parsing functions in the model package

- config/default.json
- model/config.go
Creating triggers on Amazon RDS seems to reqiure extra privileges. More
investigation is required. See https://pre-release.mattermost.com/core/pl/ddmtpshtyp843y1sk46smeo8jo for discussion.
N/A.
> disable EnablePublicChannelsMaterialization by default

- config/default.json
- model/config.go
This reverts commit 5786b0d6d57b90bbb0c262235dd9d19b497b5fae, now that
the feature is safe to enable by default.
None.
> Revert "disable EnablePublicChannelsMaterialization by default (#9418)"

- app/post.go
- app/post_test.go
- model/post.go
This PR adds a `ChannelId` and `TeamId` field to `model.PostActionIntegrationRequest`.
See https://pre-release.mattermost.com/core/pl/se1g1wck47raxp9ui91fwtuc4w
> Add ChannelId and TeamId to PostActionIntegrationRequest

- app/server.go
On go 1.11, I can't run the tests because it generates a compilation
error. This commit fixes the problem.
It only happens in the compilation process for the tests, not for the normal binary.
> Add missing dots (fixing compilation error on go 1.11)

- api4/post.go
- api4/post_test.go
- app/post.go
- einterfaces/elasticsearch.go
- model/client4.go
- model/post.go
- Adds paging to Elasticsearch API
- Note that paging is not supported with DB search.
- Modifies the location of include_deleted_channels parameter to the POST body rather than the query string
- Client support PR in progress. 
API PR: https://github.com/mattermost/mattermost-api-reference/pull/392
Enterprise PR: https://github.com/mattermost/enterprise/pull/357
> Adding paging to elasticsearch API

- api4/channel.go
- api4/post.go
- app/app.go
- app/channel.go
- app/channel_test.go
- app/command_invite.go
- app/notification_push.go
- app/plugin_api.go
- app/post.go
- app/post_test.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
This replace the mattermost/mattermost-server#8477 PR.
Clear the push notifications every time you mark as read a channel, not only in
channel switch.
Ensure the push and clear messages are always sent in order to the Push
Proxy for the same user.
[MM-7188](https://mattermost.atlassian.net/browse/7188)
> MM-7188: Cleaning push notification on every read, not only on channel switch

- web/static.go
The previous code appended a `/` to the end of the URL, breaking if a query string was present. I encountered this as part of implementing https://mattermost.atlassian.net/browse/MM-12205 when I tried to redirect to the root without a trailing slash but with a non-empty query string. Since I always run with subpath enabled, this exposed the bug.
None.
> ensure subpath redirect preserves query string correctly

- app/channel.go
If you see the logs of the mattermost-server, when you leave a channel a
panic happens. With this PR it is solved.
[MM-12339](https://mattermost.atlassian.net/browse/MM-12339)
> MM-12339: When leave a channel the push notification can fail

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetServerVersion() string` methode to the plugin API.
Fixes #9408
> GH-9408: Add plugin API methode to return the current server version

- api4/apitestlib.go
- api4/post_test.go
- app/authorization.go
Fixes post-derived permission checks to cascade properly to System level when there isn't a team (i.e. the post is in a DM or GM channel).
https://mattermost.atlassian.net/browse/MM-12013
> MM-12013: Fix post-permission checks to cascade for DM/GM channels.

- model/authorize.go
See #9462 and linked issues. Bumps OAuth state value max length from 128 to 1024 in last place where
given small limit is enforced.
#9462
> Bump AuthorizeRequest State max length to 1024

- app/app.go
- app/cluster.go
Added some extra logging to cluster leader changed.
Purpose of this is to make in-field debugging of cluster leader issues
(particularly around duplicate job scheduling) easier to debug from
production server logs.
https://mattermost.atlassian.net/browse/MM-12080
> MM-12080: Added some extra logging to cluster leader changed.

- api4/user.go
- api4/user_test.go
- i18n/en.json
If a teamId is provided, require it to match the channel's team id.
https://mattermost.atlassian.net/browse/MM-12192
> MM-12192: autocompleteUsers: if a teamId is provided, require it to match the channel's team id

- app/command_invite.go
- app/command_invite_test.go
- app/command_remove.go
- app/command_remove_test.go
- i18n/en.json
Fix /invite /kick and /remove to not work on deactivated users.
Also take the opportunity to tidy up the functions that have been touched to be a little more readable.
Finally, update the UI strings as requested.
https://mattermost.atlassian.net/browse/MM-12110
> MM-12110: Don't /invite or /kick deactivated users.

- api4/system.go
- api4/system_test.go
if enablelinkpreview is disabled this function should not be executed
https://mattermost.atlassian.net/browse/MM-12264
mattermost/mattermost-server#9457
mattermost/mattermost-server#9437
ui changes https://github.com/mattermost/mattermost-webapp/pull/1772
> [MM-12264] if EnableLinkPreviews not enabled, do not execute function

- api4/user.go
- api4/user_test.go
- app/user.go
- app/user_test.go
- model/client4.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
Add SetDefaultProfileImage to reset the user profile image to a generated one
[MM-12067](https://mattermost.atlassian.net/browse/MM-12067)
> MM-12067: Add SetDefaultProfileImage to reset the user profile image to a generated one

- app/channel.go
- app/channel_test.go
- cmd/mattermost/commands/channel.go
- i18n/en.json
Disallow renaming direct and group message channels
[MM-10699](https://mattermost.atlassian.net/browse/MM-10699)
> MM-10699: Disallow renaming direct and group message channels

- app/plugin_api_test.go
- plugin/client.go
- plugin/client_rpc.go
- plugin/example_hello_world_test.go
- plugin/example_help_test.go
- plugin/hooks.go
This removes support for automatically unmarshalling a plugin's server configuration, as there was no way to safely synchronize reads and writes to these public fields across multiple plugin threads without additional plugin coordination.
https://mattermost.atlassian.net/browse/MM-12193
> MM-12193: remove auto unmarshalling

- app/post.go
- services/httpservice/client.go
- services/httpservice/client_test.go
- services/httpservice/httpservice.go
- utils/testutils/mocked_http_service.go
Previously, mattermost-server would always request with the default
user-agent of Go's net/http package that is `Go-http-client/1.1` or
something similar.
This has several disadvantages, one is that the default user-agent
made it pretty hard to distinguish mattermost requests from other
service requests in a network log for example.
Now a user-agent of the form `mattermost-<current-version>` is set in
the client.
> Set a proper HTTP user-agent header

- cmd/mattermost/commands/init.go
`cmd/mattermost/commands/init.go` doesn't check if the DB Command Context Init returns an error before initializating the plugin system, which can cause a null pointer exception without showing the user the actual error cause.
https://github.com/mattermost/mattermost-server/issues/9496
cc @jwilander
> [GH-9486] Fix CMD Initilization Error Checks

- app/plugin_api.go
- app/plugin_key_value_store.go
- app/plugin_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- store/sqlstore/plugin_store.go
- store/store.go
- store/storetest/mocks/PluginStore.go
The pull request adds a method to the plugin API called KVList() that returns a list of all the keys stored by the plugin.
[A brief description of what this pull request does.]
https://github.com/mattermost/mattermost-server/issues/9377
- [x ] Added or updated unit tests (required for all new features)
> MM-11863 Add KVList method

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR will add GetChannelMembers method to the plugin API
https://github.com/mattermost/mattermost-server/issues/9458
Signed-off-by: Akash Srivastava <akash.srivastava@openebs.io>
> Add GetChannelMembers method to the plugin API

- app/diagnostics.go
PR that added the setting is at https://github.com/mattermost/mattermost-server/pull/9450
> Move CustomServiceTermsEnabled to the correct table in diagnostics

- app/channel.go
- app/channel_test.go
- cmd/mattermost/commands/channel.go
- i18n/en.json
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Add flag to MoveChannel to remove all deactivated users. This fixes the issue where you can't move a channel to a target team if there are deactivated users in the channel who aren't in the target team. To preserve consistency, a new flag is added to the CLI command to get the fixed behaviour, rather than changing the existing behaviour.
https://mattermost.atlassian.net/browse/MM-12251
> MM-12251: Add flag to MoveChannel to remove all deactivated users.

- app/import_functions.go
- app/import_functions_test.go
- app/import_types.go
- app/import_validators.go
- app/import_validators_test.go
- model/preference.go
- model/user.go
This pull request provides the necessary changes to specify an email batching interval while during bulk import.
The supported values are:
immediately
fifteen
hour
If the user specifies false as email NotifyProp, the bulk email interval preference will be 0.
https://mattermost.atlassian.net/browse/MM-8860
https://github.com/mattermost/mattermost-server/issues/8498
> MM-8860: Bulk import email intervals (#8498)

- app/plugin.go
- app/plugin_api.go
- app/plugin_key_value_store.go
- jobs/interfaces/plugins_interface.go
- jobs/schedulers.go
- jobs/server.go
- jobs/workers.go
- model/job.go
- model/plugin_key_value.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- plugin/scheduler/plugin.go
- plugin/scheduler/scheduler.go
- plugin/scheduler/worker.go
- store/sqlstore/plugin_store.go
- store/sqlstore/upgrade.go
- store/store.go
- store/storetest/mocks/PluginStore.go
- store/storetest/plugin_store.go
This PR implements two new methods for the Plugin KV Store
- Create entry with expiry that gets deleted automatically
- Delete all keys for a plugin
The entry expiry is stored in a new column, the entries get cleaned every 1 minute by a watchdog. Already expired entries are ignored when executing a `Get` on the KV. When an update for a key gets executed where the entry is already is expired, the expiry time + value gets updated. 
https://github.com/mattermost/mattermost-server/issues/9376
https://mattermost.atlassian.net/browse/MM-11864
https://github.com/mattermost/mattermost-server/issues/9375
https://mattermost.atlassian.net/browse/MM-11865
> [MM-11864/MM-11865] Entries with Expiry / Delete All Keys for Plugin KV Store

- app/plugin_commands_test.go
- app/plugin_hooks_test.go
- app/plugin_install.go
Remove any previously installed plugin commands when a plugin is removed, otherwise the command remains until the server is restarted.
https://mattermost.atlassian.net/browse/MM-11905
> MM-11905: delete plugin commands on removal

- cmd/mattermost/commands/command.go
- cmd/mattermost/commands/command_test.go
Implements `command create` to create slash commands in the CLI.
https://github.com/mattermost/mattermost-server/issues/9489
> MM-12355: Add CLI command "command create"

- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_experimental.go
This attempts to fix an issue with deleted/restored state of channels being reported incorrectly intermittently, as it looks like the cache sometimes contains invalid data. This should ensure the channel cache gets cleared at the appropriate times.
https://mattermost.atlassian.net/browse/MM-12419
> MM-12419: Flush channels from cache when deleted/restored.

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetPostThread(postId string)` method to plugin API.
Fixes  #9629
> GH-9629: Add GetPostThread() to plugin API

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetPostsSince(channelId string, time int64)` method to plugin API.
Fixes  #9632
>  GH-9632: Add GetPostsSince() to plugin API

- api4/brand.go
- api4/brand_test.go
- app/brand.go
- model/client4.go
This PR adds a delete brand image action to the API v4.
It is needed in order to fulfill #9507 as discussed in the contributors channel of the pre-release instance.
Cheers !
https://github.com/mattermost/mattermost-server/issues/9507
> Add a delete brand image action on the APIv4

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetPostsBefore(channelId, postId string, page, perPage int)` method to plugin API.
Fixes  #9631
> GH-9631: Add GetPostsBefore() to plugin API

- model/manifest.go
While developing a new plugin I need a setting that is a multi line string, reading the doc it did not mention. but I tried the longstring and it rendered the multi line string for me in the plugin setting
So I think it is usefull to add this reference in the doc as well for others see how powerfull is our plugin system 😄 
Do i need to do anything more?
> Added TextArea (longstring) to the docs in manifest to be rendered in the documentation

- app/plugin_install.go
Plugins that listen for config changes might incorrectly re-register
their commands before being /actually/ deactivated, leaving the new
commands alive thereafter.
https://mattermost.atlassian.net/browse/MM-11905
> MM-11905: deactivate plugins before unregistering

- plugin/api.go
This PR adds an additional comment line to the API methods in `plugin/api.go` to documented the minimum server version.
If this PR gets accepted, a note about this should be added to https://developers.mattermost.com/contribute/server/plugins/.
https://pre-release.mattermost.com/core/pl/uoysz3mtrfyc7ksdt7buuds64e
> Document minimum server version for plugin API methods

- app/export_converters.go
- app/import_validators.go
- app/import_validators_test.go
- i18n/en.json
Accept and use "" for user/pass AuthService in import/export. This brings consistency with the docs.
https://mattermost.atlassian.net/browse/MM-12670
> MM-12670: Accept and use "" for user/pass AuthService in import/export.

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetPostsAfter(channelId, postId string, page, perPage int)` method to plugin API.
Fixes  #9630
> GH-9630: Add GetPostsAfter() to plugin API

- templates/post_body_generic.html
Timestamp is not being displayed when the setting for generic emails is active: `"EmailNotificationContentsType": "generic"`
This refactoring added the regression on the generic email: 
https://github.com/mattermost/mattermost-server/commit/178ccd16cba26144eac404f413440867b360033c#diff-0721f391e39910fa6d56994bae49e7b4
> MM-12781 Fix display of timestamp on generic email. This is a regression.

- app/post_metadata.go
- app/post_metadata_test.go
- model/post.go
- model/post_embed.go
- model/post_metadata.go
As discussed previously, this changes the following:
1. The structure of the post metadata has been changed so that:
1. All metadata is now in its own `post.Metadata` struct to make it easier to tell whether or not it was populated by the server
2. `ImageDimensions` is now a map of image URL to dimensions to allow for multiple images coming from different parts of the post
3. There's a new `Embeds` field containing whether the post has message attachments, has an image preview, or has an OpenGraph preview. For image previews, this also includes the URL of the image. For OpenGraph, this contains a URL as well as the previous the OpenGraph data.
2. Image dimensions for OpenGraph images are now always included in `ImageDimensions` instead of only sometimes existing in the OpenGraph data …
> MM-11868/MM-12010/MM-12011/MM-12036 Improve post metadata structure

- plugin/client_rpc.go
Fixes a race in the plugin ServeHTTP. `http.ResponseWriter` headers are not safe for concurrent writing. Removing the redundent `http.Error` calls fixes the race. Setting the state is still handled by the `g.client.Call` relying on the other side of the RPC connection to return an error if it can not connect to the streams.
> MM-12768 Fixing race in plugin ServeHTTP

- app/auto_responder.go
- app/auto_responder_test.go
- app/notification.go
When a user is OOO and another user sends a DM the OOO message did not appear consistently. It was detected that the issue was the setting of the RootID:
https://pre-release.mattermost.com/core/pl/1emgzm9r8bnx5ciz3gpfkazxey
> Fix for OOO bug that reply message does not get inserted consistently.

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetChannelMembersByIds(channelId string, userIds []string)` method to plugin API.
Fixes [#9611](https://github.com/mattermost/mattermost-server/issues/9611)
> GH-9611: Add GetChannelMembersByIds to Plugin API

- web/saml.go
The missing `signin_change` is necessary to triggered the desired behaviour client-side when switching from SAML/OAuth back to email.
https://mattermost.atlassian.net/browse/MM-12708
> MM-12708: tack on signin_change when completing email to saml change

- app/export.go
- app/export_converters.go
- app/export_test.go
Include favorite indicator for channels in bulk export
https://github.com/mattermost/mattermost-server/issues/9539
- [ x] Added or updated unit tests (required for all new features)
> [MM-12462] Include favorite channels in bulk export

- Gopkg.lock
- Gopkg.toml
- model/manifest.go
- model/manifest_test.go
- plugin/environment.go
- vendor/github.com/blang/semver/.travis.yml
- vendor/github.com/blang/semver/LICENSE
- vendor/github.com/blang/semver/README.md
- vendor/github.com/blang/semver/json.go
- vendor/github.com/blang/semver/package.json
- vendor/github.com/blang/semver/range.go
- vendor/github.com/blang/semver/semver.go
- vendor/github.com/blang/semver/sort.go
- vendor/github.com/blang/semver/sql.go
This PR add `min_server_version` to plugin manifests. This allows to set a minimum Mattermost server version which is required for the plugin to start.
Two notes on backwards compatibility: If a plugin doesn't set `min_server_version` the sever doesn't perform a version check and just starts the plugin. This way plugins aren't force the set the option.
If a plugin sets `min_server_version` and the plugins gets executed on a Mattermost server prior to v5.6 the server will just ignore the setting. This means plugins can't enforce a server version on servers prior to v5.6!
If an admin tries to enable a plugin, which requires an higher server version then provided, they will see the error message "This plugin failed to start. Check your system logs for errors.". This is the same message that …
> GH-9737: Allow setting min_server_version in plugin manifest

- cmd/mattermost/commands/command.go
- cmd/mattermost/commands/command_test.go
Checks the `EnableOnlyAdminIntegrations` setting and only allows team admins to create slash commands if set to `true`
https://github.com/mattermost/mattermost-server/issues/9489
> MM-12355: Add CLI command "command create" revision

- store/sqlstore/user_store.go
- store/storetest/user_store.go
This trims the "@" symbol from the beginning of the search term before executing the query in the /api/v4/users/search API.
Allows for user searches to work as expected when an "@" is included at the beginning.
[GH-9755](https://github.com/mattermost/mattermost-server/issues/9755)
> Ignore "@" sign at the beginning of user searches

- app/post_metadata.go
- app/post_metadata_test.go
The SQL statement generated by GetMultipleEmojiByName is invalid when an empty array is passed in
https://mattermost.atlassian.net/browse/MM-13021
> MM-13021 Fix warning logged when getting metadata for post without emojis
