mattermost/mattermost

- api4/commands_test.go
- api4/image_test.go
- api4/oauth_test.go
- api4/post_test.go
- api4/team_test.go
- api4/user_test.go
Other improvements to restore the config after the test case finish 
N/A
> Restore config after finisht the test case

- app/status.go
Taking a look into the app/status.go I saw some unneded code duplication
and removed it.
> Deduplicating some code in app/status.go

- app/notification.go
- app/notification_test.go
Enables the mention notification for the fields in attachment ( Text and PreText )
#8964
> GH-8964 enable notification for text and preText fields in Attachments

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1434
> translations PR 20180711

- app/diagnostics.go
For https://github.com/mattermost/mattermost-server/pull/9063
> Add telemetry for ServiceSettings.EnableEmailInvitations

- api4/commands_test.go
- api4/image_test.go
- api4/oauth_test.go
- api4/post_test.go
- api4/team_test.go
- api4/user_test.go
- app/notification.go
- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
- model/user.go
- web/handlers.go
- web/saml.go
Merge from `release-5.1` to `master`
> Release 5.1 daily merge 20180712

- build/PRIVACY_POLICY.md
> Update privacy policy for v5.1

- build/PRIVACY_POLICY.md
Final merge from `release-5.1` to `master`
> Release 5.1 daily merge 20180716

- Makefile
- build/release.mk
Add pre package plugins to the package
Jira: https://mattermost.atlassian.net/browse/MM-11031
> add pre-package plugins to the MM package

- api4/plugin_test.go
- app/plugin.go
- model/manifest.go
- model/manifest_test.go
Make plugin IDs case insensitive.
https://mattermost.atlassian.net/browse/MM-11224
> MM-11224 Make plugin IDs case insensitive

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1457
> translations PR 20180718

- app/diagnostics.go
- model/config.go
https://mattermost.atlassian.net/browse/MM-11389
> MM-11389 Added diagnostics for FileSettings.Directory

- app/plugin_statuses.go
- i18n/en.json
Add translation to plugin statuses list error.
> Add missed plugin error translation

- store/sqlstore/channel_store.go
Migrated the channel store to use idiomatic error handling.
I was touching other parts of the channel store for archived channels and I decided to refactor it.
> Using idiomatic error handling in channel store

- cmd/mattermost/commands/message_export.go
- i18n/en.json
Added the Global Relay Export CLI command and the i18n strings.
[MM-11003](https://mattermost.atlassian.net/browse/MM-11003)
> MM-11003: Global Relay Export Refactor

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/import.go
- cmd/mattermost/commands/message_export.go
Add idiomatic error handling in mattermost commands
> Add idiomatic error handling in mattermost commands

- api4/file.go
- app/file.go
Improve file download API to stream files instead of loading them entirely into memory
- #8718 
- [Jira ticket](https://mattermost.atlassian.net/browse/MM-10381)
- ~~Has enterprise changes (please link)~~
- ~~Has UI changes~~
- ~~Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates~~
- ~~Touches critical sections of the codebase (auth, upgrade, etc.)~~
Let me know if an additional unit test is required, but it seems the existing test doesn't care about the changed part.
> MM-10381: Change the file downloading API to stream file

- plugin/example_hello_world_test.go
Fix plugin example docs, as it's of course necessary to embed `plugin.MattermostPlugin`.
None.
> fix plugin example docs

- app/plugin_requests.go
- app/plugin_test.go
Ensure `plugin.ServeHTTP` strips any leading `/subpath`, otherwise route handling breaks relative to plugins running without a subpath configured.
None.
> Fix plugin.ServeHTTP subpath

- api4/plugin.go
- app/plugin.go
- app/plugin_install.go
- cmd/mattermost/commands/plugin.go
- i18n/en.json
Unpack prepackaged plugins on plugins initialization.
https://mattermost.atlassian.net/browse/MM-11373
> unpack prepacked plugins on plugins initialization

- api4/oauth.go
- api4/oauth_test.go
- app/oauth.go
- app/oauth_test.go
- model/authorize.go
- model/oauth.go
Implement OAuth2 implicit grant flow. [RFC spec](https://tools.ietf.org/html/rfc6749#section-4.2).
https://mattermost.atlassian.net/browse/MM-11393
> MM-11393 Implement OAuth2 implicit grant flow

- app/login.go
- app/plugin_hooks_test.go
- plugin/client_rpc_generated.go
- plugin/hooks.go
- plugin/plugintest/hooks.go
Implements Pre and Post Login Hooks, incl. tests for all three cases.
https://github.com/mattermost/mattermost-server/issues/9157
https://mattermost.atlassian.net/browse/MM-11464
> [MM-11464] Implement Plugin Login Hooks (closes #9157)

- api4/channel.go
https://mattermost.atlassian.net/browse/MM-11516
> MM-11516: Check channel ID in URL param and Body are same.

- app/notification_push_test.go
Migrate notification_push_test to table testing
> Migrate notification_push_test to table testing

- app/plugin.go
- model/manifest.go
- model/manifest_test.go
- plugin/environment.go
- web/static.go
Use this hash to bust client caches whenever the plugin bundle changes.
https://mattermost.atlassian.net/browse/MM-11420
> MM-11420: plugins: compute bundle hash on load

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1494
> translations PR 20180730

- api4/brand.go
- api4/command.go
- api4/data_retention.go
- api4/emoji.go
- api4/image.go
- api4/job.go
- api4/oauth.go
- api4/post.go
- api4/preference.go
- api4/reaction.go
- api4/role.go
- api4/scheme.go
- api4/status.go
- api4/system.go
- api4/team.go
- api4/user.go
- api4/webhook.go
Migrate all the api4 files to handle errors in idiomatic way
> Migrate all the api4 to handle errors in idiomatic way

- app/team_test.go
- app/user_test.go
- model/user.go
- model/user_test.go
- model/utils.go
- model/utils_test.go
- store/storetest/channel_member_history_store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/post_store.go
- store/storetest/scheme_store.go
- store/storetest/status_store.go
- store/storetest/storetestlib.go
- store/storetest/team_store.go
- store/storetest/user_access_token_store.go
- store/storetest/user_store.go
Backport of https://github.com/mattermost/mattermost-server/pull/9199
https://mattermost.atlassian.net/browse/MM-11521
https://mattermost.atlassian.net/browse/MM-11522
> MM-11521/MM-11522 Fix being able to create users with invalid emails through API (5.0)

- app/team_test.go
- app/user_test.go
- model/user.go
- model/user_test.go
- model/utils.go
- model/utils_test.go
- store/storetest/channel_member_history_store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/post_store.go
- store/storetest/scheme_store.go
- store/storetest/status_store.go
- store/storetest/storetestlib.go
- store/storetest/team_store.go
- store/storetest/user_access_token_store.go
- store/storetest/user_store.go
Backport of https://github.com/mattermost/mattermost-server/pull/9199
https://mattermost.atlassian.net/browse/MM-11521
https://mattermost.atlassian.net/browse/MM-11522
> MM-11521/MM-11522 Fix being able to create users with invalid emails through API (5.1)

- app/team_test.go
- app/user_test.go
- model/user.go
- model/user_test.go
- model/utils.go
- model/utils_test.go
- store/storetest/channel_member_history_store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/post_store.go
- store/storetest/status_store.go
- store/storetest/storetestlib.go
- store/storetest/team_store.go
- store/storetest/user_access_token_store.go
- store/storetest/user_store.go
Backport of https://github.com/mattermost/mattermost-server/pull/9199
https://mattermost.atlassian.net/browse/MM-11521
https://mattermost.atlassian.net/browse/MM-11522
> MM-11521/MM-11522 Fix being able to create users with invalid emails through API (4.10)

- api4/channel_test.go
- app/channel.go
- i18n/en.json
Allow to join and add members to archived channels.
[MM-11576](https://mattermost.atlassian.net/browse/MM-11576)
> MM-11576: Allow to join and add members to archived channels

- api4/user_test.go
- store/sqlstore/team_store.go
Idiomatic error handling on team sql store
> Idiomatic error handling on team sql store

- model/version.go
- store/sqlstore/upgrade.go
Uncomment code to upgrade to 5.1.0
N/A Release manager activities
> Uncomment upgrade for 5.2.0

- i18n/de.json
- i18n/es.json
- i18n/nl.json
- i18n/pl.json
- i18n/ro.json
- i18n/ru.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20180802 (Adds Romanian)

- store/sqlstore/upgrade.go
Add preparatory upgrade code for 5.3.0
Release manager tasks
> Add preparatory upgrade code for 5.3.0

- cmd/mattermost/commands/jobserver.go
- cmd/mattermost/commands/server.go
- utils/config.go
- utils/config_test.go
Merge from `release-5.2` to `master`
> Release 5.2 daily merge 20180810

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1561
> translations PR 20180813

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
- plugin/api.go
- store/sqlstore/channel_store.go
Merge from `release-5.2` to `master`
> Merge release-5.2-20180816094046

- config/default.json
As per https://pre-release.mattermost.com/core/pl/ifrx3n5q6pgr9xri5abedgyf3r
> Add ExperimentalDefaultChannels to default.json

- api4/post.go
- api4/post_test.go
- app/post.go
- model/client4.go
- web/params.go
- Add userId to path in the "posts/unread" path per comment on https://github.com/mattermost/mattermost-api-reference/pull/384#discussion_r205077899
- Update test with time delay to fix intermittent failure
Jira ticket: [MM-11528](https://mattermost.atlassian.net/browse/MM-11528) &&  [MM-11583](https://mattermost.atlassian.net/browse/MM-11583)
> [MM-11528 &&  MM-11583] Add userId to in the "posts/unread" path and update test with time delay to fix intermittent failure

- api4/channel.go
- api4/channel_test.go
- i18n/en.json
Prevent user to remove from a direct channel
Jira ticket: [MM-11593](https://mattermost.atlassian.net/browse/MM-11593)
> [MM-11593] Prevent user to remove from a direct channel

- app/diagnostics.go
- i18n/en.json
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Add telemetry for the advanced permissions feature.
https://mattermost.atlassian.net/browse/MM-11348
> MM-11348: Add telemetry for advanced permissions.

- api4/post_test.go
- app/channel.go
- app/diagnostics.go
- app/post.go
- config/default.json
- model/config.go
- utils/config.go
Merge from `release-5.2` to `master`
> Merge release-5.2-20180824093638

- i18n/pt-BR.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1589
> translations PR 20180820

- i18n/en.json
"id": "plugin.api.update_user_status.bad_status",Unable to set the user statys. Unknown user status.
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).
When filling in a section please remove the help text and the above text.
[A brief description of what this pull request does.]
[Please link the GitHub issue or Jira ticket this PR addresses.]
> Update en.json typo

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1624
> translations PR 20180827

- app/import_functions.go
- app/import_functions_test.go
- app/import_types.go
Added the import attachment functionality to direct post
https://github.com/mattermost/mattermost-server/issues/9304
> 9304 added the attachments import to direct post

- model/utils.go
- model/utils_test.go
Remove `testing` imports from non-test code.
https://mattermost.atlassian.net/browse/MM-11694
> Remove testing imports from non-test code.

- app/post.go
- app/post_test.go
- utils/httpclient.go
Merge from `release-5.3` to `master`
> Merge release-5.3-20180903124813

- i18n/en.json
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Avoid Archived channels editions throught Patch
[MM-11728](https://mattermost.atlassian.net/browse/11728)
> MM-11728: Avoid Archived channels editions throught Patch

- model/version.go
- store/sqlstore/upgrade.go
Uncomment code to upgrade to 5.3.0
N/A Release manager activities
> Uncomment upgrade for 5.3.0

- i18n/en.json
- model/version.go
- store/sqlstore/channel_store.go
- store/sqlstore/upgrade.go
- store/storetest/channel_store.go
- utils/config.go
- utils/config_test.go
Daily merge from `release-5.3` to `master`
> Release 5.3 daily merge 20180904

- store/sqlstore/upgrade.go
Add preparatory upgrade code for 5.4.0
Release manager tasks
> Add preparatory upgrade code for 5.4.0

- api4/emoji_test.go
- app/emoji.go
- i18n/en.json
> MM-12007 Add max dimensions to emoji images

- cmd/mattermost/commands/channel.go
Allow deleting all members from a channel through the CLI.
https://mattermost.atlassian.net/browse/MM-11882
> MM-11882: Remove all users from a channel via CLI.

- api4/channel.go
- api4/file.go
- app/post.go
- model/channel.go
- store/sqlstore/post_store.go
- store/storetest/post_store.go
Merge from `release-5.3` to `master`
> Merge release-5.3-20180910141320

- utils/file_backend_s3.go
Currently mattermost is using `-1` size option when using s3 file upload. One writefile function call causes 576MB memory consumption and that can easily lead to server crash. Lets say we have 10 users uploading files at the same time, it takes already 5GB of memory.
So this fix is first copying the whole stream to buffer, and with that way we can define how much memory we really need. However, this is not good solution if the files are larger than original 576MB, because then the buffer size is going to be problem. At least for us we have maxfilesize limit lower than 576MB, so that is not problem for us.
https://github.com/mattermost/mattermost-server/issues/8838
https://github.com/mattermost/mattermost-server/issues/9078
> MM-10677 memory fix to s3 upload

- api4/emoji_test.go
- app/emoji.go
- i18n/en.json
> MM-12007 Add max dimensions to emoji images (4.10)

- api4/emoji_test.go
- app/emoji.go
- i18n/en.json
> MM-12007 Add max dimensions to emoji images (5.1)

- api4/emoji_test.go
- app/emoji.go
- i18n/en.json
> MM-12007 Add max dimensions to emoji images (5.2)

- i18n/en.json
Minor grammar & spelling fixes
As discussed in https://pre-release.mattermost.com/core/pl/b5gpxp5rqtr8deox1pube88b1w
> Minor grammar & spelling fixes

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1685
> translations PR 20180911

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
- utils/file_backend_s3.go
Merge from `release-5.3` to `master`
> Merge release-5.3-20180912130732

- api4/emoji_test.go
- app/emoji.go
- i18n/en.json
The original PR for this was accidentally merged into master
> MM-12007 Add max dimensions to emoji images (5.3)

- api4/oauth.go
- api4/oauth_test.go
https://mattermost.atlassian.net/browse/MM-10573
> MM-10573 Add error page if user doesn't authorize Mattermost for OAuth

- app/channel.go
I only migrated the second half in this PR because the files is very big
(almost 1800 LOC) so I prefer to keep PRs small when possible.
The other half is in the PR #9413
> Migrate to idiomatic error handling the second half to the app/channel.go

- app/import_functions.go
- app/notification.go
- app/notification_email.go
- cmd/mattermost/commands/server.go
> fixing log messages

- app/channel.go
I only migrated the first half in this PR because the files is very big
(almost 1800 LOC) so I prefer to keep PRs small when possible.
The other half is in the PR #9414
> Migrate to idiomatic error handling the first half to the app/channel.go

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1712
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2132
> translations PR 20180917

- plugin/environment.go
Fail plugin activation if no web app and server component.
https://mattermost.atlassian.net/browse/MM-11582
> MM-11582 Fail plugin activation if no web app and server component

- app/cluster_discovery.go
- app/compliance.go
- app/config.go
Idiomatic error handling for app/c*.go
> Idiomatic error handling for app/c*.go

- web/webhook.go
Include webhook ID in debug log.
https://mattermost.atlassian.net/browse/MM-11935
> MM-11935 Include webhook ID in debug log

- api4/user_test.go
- i18n/en.json
add translations string for missing ids
Jira: https://mattermost.atlassian.net/browse/MM-11612
> MM-11612 Add translation strings and add test case

- app/admin.go
- app/analytics.go
- app/audit.go
- app/authorization.go
- app/brand.go
Migrate to idiomatic error handling app/a*.go and app/b*.go
> Migrate to idiomatic error handling app/a*.go and app/b*.go

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1766
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2162
> translations PR 20180924

- model/version.go
- store/sqlstore/upgrade.go
Uncomment upgrade for 5.4.0
cc @amyblais 
Need to add the changes in the DB in the changelog
> Uncomment upgrade for 5.4.0

- api4/channel_test.go
- app/post.go
- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_experimental.go
- store/storetest/channel_store.go
Autocomplete search in: for DMs and GMs
[MM-11567](https://mattermost.atlassian.net/browse/MM-11567)
> MM-11567: Autocomplete search in: for DMs and GMs

- app/import.go
- app/import_functions.go
- app/import_validators.go
Idiomatic error handling for app/import*.go
> Idiomatic error handling for app/import*.go

- app/diagnostics.go
Added by https://github.com/mattermost/mattermost-server/pull/9349
Also fixes a style error.
> Add EnablePublicChannelsMaterialization to diagnostics.go

- app/job.go
- app/license.go
- app/login.go
Idiomatic error handling for app/{job,license,login}.go
> Idiomatic error handling for app/{job,license,login}.go

- store/sqlstore/upgrade.go
I will merge after cut the release branch
> Add preparatory upgrade code for 5.5.0

- cmd/mattermost/commands/team.go
- cmd/mattermost/commands/team_test.go
- cmd/mattermost/commands/teamargs.go
This PR adds the `team search` CLI command to search for teams based on team names.
MM-12367
> [MM-12367] Added CLI command 'team search'

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1807
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2204
> translations PR 20181001

- i18n/en.json
Added missed translations
GH #9549
> Added missed translations

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
- store/sqlstore/webhook_store.go
Add the webhook list command.
Important changes: 
Altered the GetIncomingByTeam sql to match GetOutgoingByTeam by allowing for a negative offset/limit to allow fetching all data.
The JIRA ticket didn't specify the format for printing the webhooks. I used the display name and ID together.
https://mattermost.atlassian.net/browse/MM-12371
Addresses: https://github.com/mattermost/mattermost-server/issues/9522
> MM-12371 Add webhook list command

- cmd/mattermost/commands/command.go
Signed-off-by: sonasingh46 <sonasingh46@gmail.com>
The PR will add a cli command for listing commands under a team.
https://github.com/mattermost/mattermost-server/issues/9490
> MM-12357: Add CLI command "team list"

- cmd/mattermost/commands/webhook.go
Small fix in the webhook list error handling
> Small fix in the webhook list error handling

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2239
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1862
> translations PR 20181009

- api4/channel.go
- api4/channel_test.go
- app/channel.go
- app/channel_test.go
- i18n/en.json
- model/client4.go
- model/user.go
- model/utils.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
Added an API to get all timezones from users for a specific channel
n/a
webapp: https://github.com/mattermost/mattermost-webapp/pull/1607
redux: https://github.com/mattermost/mattermost-redux/pull/612
api reference: https://github.com/mattermost/mattermost-api-reference/pull/387
> [APIv4] add getChannelMembersTimezone 

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
* Added the get command to get the value of a config setting.
* Depending on the config setting it can work on any depth of the
setting.
* Added test for the get command.
> [MM-12360] Created CLI command "config get" (#9534)

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetChannelsForTeamForUser method to plugin API.
https://github.com/mattermost/mattermost-server/issues/9606
> GH-9606: Add GetChannelsForTeamForUser to plugin API

- app/session.go
in the mattermost-server (#9573)
* Refactor and make error handling idiomatic
* Golint gives a warning when using method parameters with names like
'deviceId', so rename them to `deviceID`
> [MM-12538] Migrate to idiomatic error handling the file `app/session.go`

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetEmojiByName method to plugin API.
#9618
> Add GetEmojiByName method to plugin API

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
* Add the subcommand by creating a new Command instance.
* Implemented the structure of the subcommand function.
* Register our new command
* Write some helper functions
* finish the pretty print function
* write some test for config show
> [MM-12362] Add CLI command 'config show'

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
Adds CLI command to create incoming webhook
[Jira ticket](https://mattermost.atlassian.net/browse/MM-12368)
Fixes #9560
> MM-12368 Add create webhook-incoming command

- app/notification_email.go
Migrate to idiomatic error handling in the file `app/notification_email.go` in the mattermost-server repo.
Fixes #9673
> Migrate to idiomatic error handling in app/notification_email.go

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetUsersInChannel method to plugin API.
https://github.com/mattermost/mattermost-server/issues/9607
> GH-9607: Add GetTeamsForUser to plugin API

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetUsersInChannel method to plugin API.
https://github.com/mattermost/mattermost-server/issues/9608
> GH-9608: Add GetUsersInChannel to plugin API

- plugin/api.go
Missed this one in #9616
cc @lieut-data
> Document minimum server version for SearchChannels

- app/plugin_api.go
- i18n/en.json
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetFileLink method to plugin API.
#9622
[x] Added or updated uint tests (required for all new features)
> Add GetFileLink method to plugin API

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add GetUsersByUsernames method to plugin API.
https://github.com/mattermost/mattermost-server/issues/9635
> GH-9635: Add GetUsersByUsernames to plugin API

- app/security_update_check.go
Migrate to idiomatic error handling in the file `app/security_update_check.go` in the mattermost-server repo.
Fixes #9687
> GH-9687: Migrate to idiomatic error handling in app/security_update_check.go

- app/websocket_router.go
Migrate to idiomatic error handling in the file `app/websocket_router.go` in the mattermost-server repo.
Fixes #9703
> GH-9703: Migrate to idiomatic error handling in app/websocket_router.go

- app/preference.go
Migrate to idiomatic error handling in the file `app/preference.go` in the mattermost-server repo.
Fixes #9583
>  GH-9583: Migrate to idiomatic error handling in app/preference.go

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
GetEmojiImage added to plugin API
#9619
> GH-9619 GetEmojiImage added to plugin API

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
Adds CLI command to modify incoming webhook
[Jira ticket](https://mattermost.atlassian.net/browse/MM-12372)
Fixes #9669 
> MM-12372 Add modify-incoming webhook command

- app/web_conn.go
Migrate to idiomatic error handling in the file `app/websocket_router.go` in the mattermost-server repo.
Usually I don't do line break changes in this PRs. But the formatting was quite messed sometimes.
Fixes #9705
> GH-9705: Migrate to idiomatic error handling in app/web_conn.go

- app/post.go
Migrate to idiomatic error handling in the file `app/post.go` in the mattermost-server repo.
Even though this is a big file the changes are pretty strait forward. I changed the code structure a few time to make the code simple, but the rest is just standard error handling.
Fixes #9688
> GH-9688: Migrate to idiomatic error handling in app/post.go

- app/user.go
Migrate to idiomatic error handling in the file `app/user.go` in the mattermost-server repo.
Fixes #9706
> GH-9706: Migrate to idiomatic error handling in app/user.go

- app/slackimport.go
Migrate to idiomatic error handling in the file `app/slackimport.go` in the mattermost-server repo.
Closes #9686
> Migrate to idiomatic error handling in app/slackimport.go

- api4/apitestlib.go
- app/command.go
- cmd/mattermost/commands/command.go
- cmd/mattermost/commands/command_test.go
Add cli command "command delete"
https://github.com/mattermost/mattermost-server/issues/9492
- [x ] Added or updated unit tests (required for all new features)
> MM-12356 Add cli command "command delete"

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Creates the plugin API equivalent of the model/client4.go GetEmoji method
https://github.com/mattermost/mattermost-server/issues/9617
- [x ] Added or updated unit tests (required for all new features)
> GH-9617 Add plugin API for GetEmoji method

- README.md
Move from old to new Twitter Handle in Readme, "MattermostHQ" to "MatterMost".
> Update Twitter Handle in Readme

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
* Create the config set command in the variable
* Register the command and declare the command in the run function
* Finish implementation of 'config set' cli command
* Write tests for config set command
> [MM-12361] Create CLI-command "config set" (#9535)

- app/team.go
Migrate to idiomatic error handling in the file `app/team.go` in the mattermost-server repo.
Fixes #9685
> GH-9685: Migrate to idiomatic error handling in app/team.go

- api4/user_test.go
fix panic in TestUpdateUserAuth test
> fix panic in TestUpdateUserAuth test

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/1967
> translations PR 20181029

- app/export_converters.go
- app/export_test.go
Include the per-channel NotifyProps for Users in Bulk Export
https://github.com/mattermost/mattermost-server/issues/9763
> [MM-12461] Include the per-channel NotifyProps for Users in Bulk Export

- README.md
Avoid devs to guess the IRC server we are talking about
N/A
N/A
> Add link to Freenode

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
Implement `webhook create-outgoing` command in the CLI
resolves #9768 (Jira link: https://mattermost.atlassian.net/browse/MM-12369)
> MM-12369 Add Create Outgoing Webhook Command

- app/command_leave.go
- app/command_leave_test.go
- i18n/en.json
Remove the ephemeral post after leaving a channel
Jira ticket: [MM-12805](https://mattermost.atlassian.net/browse/MM-12805)
> [MM-12805] Remove ephemeral post after leaving a channel

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Add GetEmojiList API method to plugin.
https://github.com/mattermost/mattermost-server/issues/9620
> Added GETEmojilist plugin api

- model/version.go
- store/sqlstore/upgrade.go
> upgrade to 5.5

- model/version.go
- store/sqlstore/upgrade.go
> upgrade db to 5.5

- cmd/mattermost/commands/channel.go
- cmd/mattermost/commands/team.go
1. Added `MinimumNArgs` to required commands in channels.go and team.go
2. Removed arguments length comparison as `MinimumNArgs` would handle it.
No existing ticket. Relates to code refactoring.
> Added MinimumNArgs to required commands in channels.go and team.go

- i18n/fr.json
- i18n/zh-TW.json
> translations PR 20181105

- app/post_metadata.go
- app/post_metadata_test.go
https://mattermost.atlassian.net/browse/MM-12829
> MM-12829 Check message attachments for emojis for post metadata

- app/plugin_api.go
- app/plugin_api_test.go
- app/plugin_statuses.go
- model/client4.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a couple methods to interact this plugins to the plugin API 
Fixes #9740
> GH-9740:  Add plugin methods to plugin API 

- store/sqlstore/upgrade.go
- store/sqlstore/user_store.go
Adds a postgres-specific optimization to the database query used when searching for users.
[GH-9781](https://github.com/mattermost/mattermost-server/issues/9781)
> Optimize searching for users on Postgres

- i18n/de.json
- i18n/ko.json
- i18n/ru.json
> translations PR 20181112

- config/default.json
- model/saml.go
remove text "with SAML" and keep only "SAML"
Jira: https://mattermost.atlassian.net/browse/MM-12984
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2036
> [MM-12984] default text to SAML

- api4/post.go
- api4/post_test.go
- app/post.go
- app/post_metadata.go
- app/post_test.go
- model/post_list.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Add cursor to posts list such as next_post_id and previous_post_id with the shape like:
```json
{
"next_post_id": "post_id_3",
"order": ["post_id_1", "post_id_2"],
"posts": {
"post_id_1": {...}, 
"post_id_2": {...}, 
},
"previous_post_id": "post_id_0",
}
```
This adds cursor to posts list returned by the following:
- getPostsForChannel `GET api/v4/channels/{channel_id:[A-Za-z0-9]+}/posts`
- [UPDATE] On query `?before={post_id}`, said before post ID is automatically set as `next_post_id`.  Only `previous_post_id` will be queried from the database after getting the post list.
- [UPDATE] On query `?after={post_id}`, said after post ID is automatically set as `previous_post_id`.  Only `next_post_id` will be queried from the database after getting the post list.
- [UPDATE] On query …
> [MM-11876] Add cursor to posts list such as next_post_id and previous_post_id

- app/import_functions.go
- app/plugin_api.go
- app/plugin_api_test.go
- app/user.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Add SetProfileImage to the plugin API 
n/a
> Add SetProfileImage for plugin API

- app/plugin_api.go
- app/plugin_api_test.go
- app/team.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Add GetTeamIcon to the plugin API 
n/a
> Add GetTeamIcon plugin api method

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
> add SetTeamIcon plugin api

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
See https://community.mattermost.com/core/pl/euq36dd5ejfbugak97rxcwkxqc
> Remove *model.ChannelList from plugin API return parameter

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
> Add RemoveTeamIcon plugin api

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
add CreateDirectChannel plugin api
> add CreateDirectChannel plugin api

- api4/group.go
- api4/ldap.go
- model/license.go
- model/license_test.go
- utils/license.go
Adds new feature flag for "LDAP groups"
https://mattermost.atlassian.net/browse/MM-13106
> Adds 'LDAP groups' feature flag.

- api4/post.go
- app/notification.go
- app/post.go
- app/post_metadata.go
- app/post_metadata_test.go
https://mattermost.atlassian.net/browse/MM-11434
> MM-11434 Only call PreparePostForClient once when creating a post

- model/version.go
- store/sqlstore/upgrade.go
> upgrade db to 5.6.0

- app/plugin_key_value_store.go
- app/plugin_test.go
- model/plugin_key_value_test.go
Stop hashing keys for plugins when inserting new key/values. 
https://github.com/mattermost/mattermost-server/issues/9813
> [MM-12452] Stop inserting hashed plugin keys

- api4/system.go
- api4/system_test.go
- model/config.go
- model/config_test.go
Fix Message Export config special case. It should only apply when setting through the System Console, to avoid messing up externally managed config files.
https://mattermost.atlassian.net/browse/MM-13185
> MM-13185: Fix Message Export config special case.

- Makefile
- api4/apitestlib.go
- api4/system_test.go
- app/server_test.go
- build/Jenkinsfile
- model/manifest_test.go
- services/filesstore/filesstore_test.go
- services/mailservice/inbucket.go
- store/sqlstore/system_store.go
As we march towards build containerization, these are a handful of changes required to enable the build to pass inside Docker, as well as some changes that generally just improved logging when tests go awry.
N/A
> Various unit test related improvements

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
Improving create-outgoing webhook command
> Improving create-outgoing webhook command

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20181128 (adds Ukrainian)

- cmd/mattermost/commands/webhook.go
Fixing webhook create incomming (required channel and user parameter)
[MM-12368](https://mattermost.atlassian.net/browse/MM-12368)
> MM-12368: Fixing webhook create incomming

- Makefile
Adding make i18n-extract command to the makefile.
> Adding make i18n-extract command to the makefile

- app/server.go
HTTPService needs to be created before push notification service.
> Fixing initalization order.

- app/webhook.go
Will be removed after debugging on community-daily is complete.
> Add temporary webhook debug logs

- app/post.go
- app/webhook.go
@cpanato you can turn off debugging on community-daily as well, I figured out the issue. Thanks for your help!
> Revert temporary webhook debugging

- cmd/mattermost/commands/command.go
- cmd/mattermost/commands/command_test.go
Improved how CLI "command delete" command works
[MM-12356](https://mattermost.atlassian.net/browse/MM-12356)
> Improved how CLI "command delete" command works

- app/post.go
Temporary fix for slack attachment fields being clobbered by plugins.
https://mattermost.atlassian.net/browse/MM-13088
> MM-13088 Temporary fix for slack attachment fields being clobbered by plugins

- api4/post.go
Made changes in the function getPost() and getPostThread()
> MM-13292 Migrate api4/post.go to idiomatic error handling

- services/filesstore/localstore.go
* migrate to idiomatic handling the Reader method of LocalFileBackend
* migrate to idiomatic handling the ReadFile method of LocalFileBackend
* migrate to idiomatic handling the ListDirectory method of LocalFileBackend
* gofmt done
> [MM-13318] Migrate to idiomatic error handling in the file `services/filesstore/localstore.go` in the mattermost-server repo

- Makefile
Follow up on https://github.com/mattermost/mattermost-webapp/pull/2126
https://mattermost.atlassian.net/browse/MM-13334
> Depreciate fullmap target

- i18n/en.json
Reading months to translation (included in the extraction tool too)
[MM-13213](https://mattermost.atlassian.net/browse/MM-13213)
> Reading months to translation (included in the extraction tool too)

- api4/handlers.go
Add documentation comments to the API Handlers so others don't have to figure out what they mean.
I think the comments are correct, but would appreciate you guys pointing out anything that is wrong or omitted.
https://mattermost.atlassian.net/browse/MM-13184
> MM-13184: Add some documentation to API handlers.

- api4/user.go
Migrate to idiomatic error handling in the file `api4/user.go` in the mattermost-server repo.
Fixes #9941
> [MM-13293] Migrate to idiomatic error handling in api4/user.go

- utils/config.go
Add client config of `ExperimentalEnablePostMetadata`
Jira ticket: [MM-13174](https://mattermost.atlassian.net/browse/MM-13174)
> [MM-13174] Add client config of ExperimentalEnablePostMetadata

- i18n/en.json
Reported inconsistency in https://community.mattermost.com/core/pl/8g91zz64zjnsumz9exoiwxwyuh
> Change "user terms of service" to "terms of service" for consistency

- i18n/de.json
- i18n/ko.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/uk.json
> translations PR 20181203

- app/notification.go
- app/notification_test.go
I'm not 100% sure if this is not breaking other parts of the parsing.
From my perspective I keep the intention of the original commit, but I'm
not sure.
[MM-12941](https://mattermost.atlassian.net/browse/MM-12941)
> MM-12941: Fixed problem with not-in-channel mentions users

- build/Jenkinsfile.pr
- build/local-test-env.sh
Server side of https://github.com/mattermost/enterprise/pull/380
> add inbucket smtp port env vars

- build/Jenkinsfile.pr
- build/local-test-env.sh
Fix an issue running `local-test-env.sh` and archive the `report*.xml` files for introspection.
N/A
> Build tweaks

- i18n/de.json
- i18n/fr.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/uk.json
- i18n/zh-CN.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2170
> translations PR 20181210

- api4/user.go
- app/app.go
- app/authentication.go
- app/enterprise.go
- app/options.go
- app/server.go
- app/user.go
- i18n/en.json
- services/mfa/mfa.go
- services/mfa/mfa_test.go
- utils/config.go
Moving the MFA feature from enterprise to team edition.
[MM-12076](https://mattermost.atlassian.net/browse/MM-12076)
> MM-12976: Moving MFA to Team edition

- app/config.go
- utils/config.go
Fix TOS not displaying when using SSO login in RN apps
https://mattermost.atlassian.net/browse/MM-13349
> MM-13349: Fix TOS not displaying when using SSO login in RN apps

- app/file.go
- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Added GetFile API in app and plugin.
#9621
> Add GetFile API in app and plugin

- app/diagnostics.go
- app/diagnostics_test.go
Don't have a diagnostics segment key in dev builds.
https://mattermost.atlassian.net/browse/MM-13027
> MM-13027: Don't have a diagnostics segment key in dev builds.

- i18n/ko.json
- i18n/ru.json
> translations PR 20181213

- app/plugin_install.go
If a plugin upload overwrites an existing plugin, the new one will be immediately enabled if the old one was enabled.
https://mattermost.atlassian.net/browse/MM-8662
This complements https://github.com/mattermost/mattermost-redux/pull/739 and is used from https://github.com/mattermost/mattermost-webapp/pull/2147
> MM-8662: Preserve plugin's enabled state when overwriting

- api4/user.go
- api4/user_test.go
See: https://community-daily.mattermost.com/core/pl/gzfbi3mke3nojfhckukbb3w19y
> Fix update user auth.

- api4/channel.go
- api4/emoji_test.go
- api4/file.go
- api4/file_test.go
- api4/webhook_test.go
This PR fixes shadowed variables in some files of the `app` package. The issues where found with `go tool vet -shadow ./api4/`.
Follow up on #10000
> Fix shadowed variables in api4 package

- i18n/de.json
> translations PR 20181217

- model/version.go
- store/sqlstore/upgrade.go
in the release branch 5.7 it is ok
> upgrade db to 5.7

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20181224

- api4/reaction.go
- api4/reaction_test.go
- app/reaction.go
- i18n/en.json
- model/client4.go
- model/reaction.go
- store/layered_store.go
- store/layered_store_supplier.go
- store/local_cache_supplier_reactions.go
- store/redis_supplier_reactions.go
- store/sqlstore/supplier_reactions.go
- store/store.go
- store/storetest/mocks/LayeredStoreDatabaseLayer.go
- store/storetest/mocks/LayeredStoreSupplier.go
- store/storetest/mocks/ReactionStore.go
- store/storetest/mocks/SqlStore.go
- store/storetest/reaction_store.go
Add a new endpoint for bulk selecting reactions to posts.
Fixes #6798
> [GH-6798] added a new api endpoint to get the bulk reactions for posts

- i18n/de.json
- i18n/ru.json
- i18n/tr.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2236
> translations PR 20181231

- app/integration_action.go
- app/integration_action_test.go
Added a missing error check in DoActionRequest, was causing crashes before.
https://mattermost.atlassian.net/browse/MM-13598
> MM-13598 Added missing error check to DoActionRequest

- app/oauth.go
Idiomatic error handling in `app/oauth.go`
#9672
> GH-9672 idiomatic err handling in app/oauth.go

- app/channel.go
If your notification prefs are set only for mentions but the channel is a DM no clear notification was being sent
https://mattermost.atlassian.net/browse/MM-13600
> Send clear push notification when DM has unread messages

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
A CLI command has been added to modify an outgoing webhook.
https://github.com/mattermost/mattermost-server/issues/9668
> [MM 12373] Create CLI command "webhook modify-outgoing"

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/nl.json
- i18n/pt-BR.json
> translations PR 20190107

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190110

- utils/config.go
- utils/config_test.go
Moved the one place we were setting it but needed to move both.
https://mattermost.atlassian.net/browse/MM-13725
> MM-13725 Fix client config overriding MFA enforcement set in limited config

- app/oauth_test.go
This is just a bunch of extra tests I added while doing https://github.com/mattermost/mattermost-server/pull/10066 so that every code path in AuthorizeOAuthUser is covered. I tested them prior to that PR and outside of a small change in error handling, they also pass without those changes as well.
This PR is based on that one, so the changes specific to this PR are here: https://github.com/mattermost/mattermost-server/pull/10070/commits/cb9b4545da91257aef4a22b1aaf6543d36c34fed
- Touches critical sections of the codebase (auth, upgrade, etc.)
> Add exhaustive tests for AuthorizeOAuthUser 

- app/plugin_api.go
- app/team_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Added GetTeamStats to plugin api.
Fixes https://github.com/mattermost/mattermost-server/issues/10098
or
https://mattermost.atlassian.net/browse/MM-13748
> MM-13748 Add GetTeamStats to plugin API

- api4/channel_test.go
- api4/user_test.go
These are some unit test changes factored out of my various `bots` PRs, intended to fix some spurious issues and clean up some unit tests in advance of merging `bots` to `master`. The refactoring, in particular, would make for a messy merge conflict if `master` deviates from the `bots` branch before we merge everything back in.
https://mattermost.atlassian.net/browse/MM-13117 (related)
> Unit test fixes

- app/command_channel_header.go
- app/export.go
- app/login.go
- app/notification_push.go
> Fix shadowed variables in app package: Part 2 of 3

- app/channel_test.go
- app/import_functions_test.go
- app/team_test.go
> Fix shadowed variables in app package: Part 3 of 3

- api4/post.go
- api4/post_test.go
- api4/preference.go
Optimize the way posts are stored in the preference table and returned by the flagged post endpoint.
https://mattermost.atlassian.net/browse/MM-13820
> [MM-13820] Optimize flagged post handling in preferences and web handler

- api4/post.go
- api4/post_test.go
- i18n/en.json
Don't allow pin/unpin in read-only town square.
https://mattermost.atlassian.net/browse/MM-13796
> MM-13796: Don't allow pin/unpin in read-only town square.

- app/post.go
- services/mailservice/inbucket.go
- services/mailservice/mail.go
- utils/config.go
- utils/lru.go
- utils/markdown/blocks.go
- utils/markdown/inlines.go
This PR fixes shadowed variables in the following packages:
- `app`
- `utils`
- `utils/markdown`
- `services/mailservice`
Follow up on #10000
Part 2 of https://github.com/mattermost/mattermost-server/pull/10175
> Fix shadowed variables in various places: Part 2 of 2 

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190128

- model/version.go
- store/sqlstore/upgrade.go
- uncomment db upgrade to 5.8.0
- add preparatory db upgrade for 5.9.0
When approved and merged I will cherry pick the first commit to the release branch 5.8.0
> DB upgrades

- cmd/mattermost/commands/sampledata.go
- cmd/mattermost/commands/server_test.go
- plugin/environment.go
- plugin/supervisor.go
- store/storetest/channel_store.go
- web/webhook_test.go
This PR fixes shadowed variables in the following packages:
- `cmd`
- `plugin`
- `store`
- `web`
Follow up on #10000
> Fix shadowed variables in various places: Part 1 of 2

- app/user.go
- einterfaces/ldap.go
Changes signature of `FirstLoginSync` function.
n/a
> Changes signature of FirstLoginSync function.

- api4/user.go
- api4/user_test.go
- app/authentication.go
- app/user.go
- model/user.go
The changes introduced in this PR requires that one submits the password in the patch request of a email change.
https://mattermost.atlassian.net/projects/MM/issues/MM-13839
> [MM-13839] Check for password when updating the eMail

- api4/system_test.go
- app/diagnostics.go
- build/release.mk
- config/default.json
- model/config.go
- services/mailservice/mail.go
- services/mailservice/mail_test.go
- tests/test-config.json
Please make sure you've read the [pull request](http://docs.mattermost.com/developer/contribution-guide.html#preparing-a-pull-request) section of our [code contribution guidelines](http://docs.mattermost.com/developer/contribution-guide.html).
When filling in a section please remove the help text and the above text.
[A brief description of what this pull request does.]
[Please link the GitHub issue or Jira ticket this PR addresses.]
> Adds configuration for separate reply-to email header.

- build/Jenkinsfile.pr
When checking out a branch for other repos it always checkout master, but sometimes the PR point to another branch like the release branches, this PR fix and checkout the correct destination branch
> Update jenkins file

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2332/
> translations PR 20190204

- api4/user_test.go
- model/user.go
- store/sqlstore/user_store.go
- store/storetest/user_store.go
Add an `IsBot` field to `model.User`.
https://mattermost.atlassian.net/browse/MM-13120
> MM-13120: Add IsBot field to model.User

- app/server_app_adapters.go
Switches to using s.FakeApp() dynamically instead of only generating one once at the top of some functions so that changes to the server will reflect in the new fake apps. 
The fake app was not updating after cluster initialization, therefore the plugin API did not have access to the cluster in order to propagate plugin messages across the cluster.
In addition, this may fix the emoji reaction flux issue (https://mattermost.atlassian.net/browse/MM-13550) as a similar issue was happening with the store code. I have not yet verified this.
> MM-14027 Fixing plugin API not having proper access to Cluster.

- api4/user_test.go
- app/authentication.go
- model/client4.go
Improvements to password lockout functionality. 
https://mattermost.atlassian.net/browse/MM-14039
> MM-14039 Improving password lockout functionality.

- app/post.go
This PR logs the errors returned by the Elasticsearch `IndexPost` and `DeletePost` methods.
> Logs the errors when indexing and deleting posts with elasticsearch

- store/sqlstore/user_store.go
This PR removes updated fields from the `UpdatePassword` store method that aren't required for that action.
FYI @lindalumitchell 
https://mattermost.atlassian.net/browse/MM-14161
> [MM-14161] Only change required fields when updating the user password

- i18n/ro.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2390
> translations PR 20190218

- api4/bot_test.go
- app/bot.go
- app/bot_test.go
- app/diagnostics.go
- app/user.go
- app/user_test.go
- model/config.go
Adds DisableBotsWhenOwnerIsDeactivated setting that when true deactivates all bots when their owner is deactivated.
> MM-13136 Disable user bots when user is disabled.

- api4/post.go
- api4/team.go
[MM-13810](https://mattermost.atlassian.net/browse/MM-13810)
> [MM-13810] Modifies invalid parameter error message for update post and team

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2408
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2595
> translations PR 20190225

- app/command_test.go
This test would sometimes fail spuriously because the timeout wasn't triggered. Instead, just make the "slow" HTTP server block altogether.
N/A
> TestDoCommandRequest: fix non-determinism

- app/post_metadata.go
This is to reduce some log spam since some of these messages will be printed if anyone posts a broken or inaccessible link
This is also getting merged into 5.8.1
https://mattermost.atlassian.net/browse/MM-14558
> MM-14558 Downgrade warnings printed by post metadata to be debug messages

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190314

- api4/ldap.go
- app/ldap.go
- einterfaces/ldap.go
- model/group.go
- web/params.go
Accepts parameters to search and filter LDAP groups.
https://mattermost.atlassian.net/browse/MM-12488
> MM-12488: Accepts parameters to search and filter LDAP groups.

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190318

- store/sqlstore/upgrade.go
Updates upgraded column types to match new column types used by gorp (and other `sql.NullBool` columns such as `[Channel|Team]Members.SchemeUser` and `[Channel|Team]Members.SchemeAdmin`).
https://mattermost.atlassian.net/browse/MM-14652
> MM-14652: Updates upgrade column type to match gorp.

- app/license.go
- app/license_test.go
Fix the handling of expired licenses to behave as was previously documented (and expected).
https://mattermost.atlassian.net/browse/MM-14626
> MM-14626: Make license expiry checks behave how they are meant to.

- app/plugin_api.go
Fixes GetLDAPUserAttributes so it doesn't fail for SAML users if SAML sync with LDAP is enabled.
Tests are in enterprise repository: https://github.com/mattermost/enterprise/pull/411
https://mattermost.atlassian.net/browse/MM-14304
> MM-14304 Fixing GetLDAPUserAttributes to work with SAML as well.

- model/version.go
- store/sqlstore/upgrade.go
> upgrade database to 5.10.0

- build/release.mk
- model/config.go
- model/config_test.go
Enables NPS plugin if prepackaged.
[MM-13744](https://mattermost.atlassian.net/browse/MM-13744) and [MM-13745](https://mattermost.atlassian.net/browse/MM-13745)
> [MM-13744] Enable NPS plugin if prepackaged

- store/sqlstore/upgrade.go
> prepare db upgrade to 5.11

- api4/user.go
- api4/user_test.go
- model/user.go
Returned User TermsOfService Data in Certain GetUser APIs To Be Used on Webapp for Decicion Making
WIP: pending test cases and further testing
> Returned User TermsOfService Data in Certain GetUser APIs To Be Used on Webapp for Decicion Making

- model/channel.go
- model/channel_test.go
- model/team.go
- model/team_test.go
Switches field type from sql.NullBool to a bool pointer.
https://mattermost.atlassian.net/browse/MM-14768
> MM-14768: Switches field type from sql.NullBool to a bool pointer.

- app/file.go
- i18n/en.json
Fixed the error message displayed when an uploading file gets rejected by a plugin's FileWillBeUploaded hook.
https://mattermost.atlassian.net/browse/MM-14803
> Fixed error message displayed for FileWillBeUploaded rejections

- api4/channel.go
- api4/channel_test.go
Fix Update and Patch channel for private channels.
https://mattermost.atlassian.net/browse/MM-14845
> MM-14845: Fix Update and Patch channel for private channels.

- web/context.go
Bots should be exempt from MFA rules.
https://mattermost.atlassian.net/browse/MM-14752
> MM-14752 Exempting bot accounts from MFA requirements.

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190401

- i18n/en.json
- store/sqlstore/user_store.go
Adding all the missed translations and fixed an invalid translation
> Fixing translations

- api4/channel.go
- api4/channel_test.go
Fixing some permissions related to join channels. I found it working on changing the default channel redirect behavior.
[MM-14639](https://mattermost.atlassian.net/browse/MM-14639)
> Fixing permissions checks where related to join public channels

- build/Jenkinsfile.pr
Add the check i18n to the pipeline to check missing or orphans translation strings
https://mattermost.atlassian.net/browse/MM-14785
> add check i18n en.json to the pipeline

- model/client4.go
Adding the client part of the new endpoint to invalidate email invites
[MM-14748](https://mattermost.atlassian.net/browse/MM-14748)
> Adding the client part of the new endpoint to invalidate email invites

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2627
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2704
> translations PR 20190408

- app/permissions_migrations.go
- store/sqlstore/upgrade.go
Moving the creation of the new bot permissions to permissions migrations
> Moving the creation of the new bot permissions to permissions migrations

- api4/channel.go
- api4/channel_test.go
- api4/team.go
- api4/team_test.go
- i18n/en.json
Restricts deleting team and channel members if the team or channel is group constrained.
https://mattermost.atlassian.net/browse/MM-14757
and
https://mattermost.atlassian.net/browse/MM-14758
> MM-14757/14758: Restricts deleting team and channel members if the team or channel is group constrained.

- api4/channel.go
- api4/channel_test.go
- api4/team_test.go
[MM-14640](https://mattermost.atlassian.net/browse/MM-14640) and [MM-14641](https://mattermost.atlassian.net/browse/MM-14641)
> Expose GroupConstrained flag where needed and add tests

- app/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
This PR migrates the `GetIncomming` method from the `Webhook` store to Sync by
default.
> SyncStore: Migrate Webhooks.GetIncomming method to Sync

- app/webhook.go
- cmd/mattermost/commands/channel.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Migrates the WebHook.UpdateIncoming method to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10622
> [MM-15117] Migrate "WebHook.UpdateIncoming" to Sync by default

- app/channel.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
SyncStore: GetIncomingByChannel to sync
Fixes #10617
> GH-10617 SyncStore: GetIncomingByChannel to sync

- app/webhook.go
- cmd/mattermost/commands/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
[MM-15122] Migrate "WebHook.GetIncomingByTeam" to Sync by default
https://github.com/mattermost/mattermost-server/issues/10623
> [MM-15122] Migrate "WebHook.GetIncomingByTeam" to Sync by default

- i18n/ko.json
- i18n/nl.json
- i18n/ro.json
- i18n/ru.json
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2734
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2688
> translations PR 20190422

- app/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
[MM-15183] Migrate "WebHook.SaveOutgoing" to Sync
https://github.com/mattermost/mattermost-server/issues/10653
[MM-15183]: https://mattermost.atlassian.net/browse/MM-15183
> [MM-15183] Migrate "WebHook.SaveOutgoing" to Sync

- app/channel.go
- app/command.go
- app/email_batching.go
- app/file.go
- app/post.go
- app/webhook.go
- cmd/mattermost/commands/channelargs.go
- store/sqlstore/channel_store.go
- store/sqlstore/group_supplier.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/post_store.go
- store/storetest/scheme_store.go
Migrate the Channel.Get and Channel.GetFromMaster methods to Sync by default
Fixes #10655
> MM-15198 Migrate Channel.Get/GetFromMaster to Sync by default

- app/channel.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Migrate PermanentDeleteIncomingByChannel to Sync
Fixes https://github.com/mattermost/mattermost-server/issues/10619
> [MM-15120] Migrate PermanentDeleteIncomingByChannel to Sync

- app/analytics.go
- app/diagnostics.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Migrate Webhook.AnalyticsIncomingCount to Sync
Fixes https://github.com/mattermost/mattermost-server/issues/10645
> [MM-15191] Migrate Webhook.AnalyticsIncomingCount to Sync

- api4/main_test.go
- api4/post_test.go
- api4/scheme_test.go
- app/team.go
- cmd/mattermost/commands/command_test.go
- cmd/mattermost/commands/main_test.go
- migrations/main_test.go
- model/post_test.go
- model/utils_test.go
- services/httpservice/client_test.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/storetest/user_store.go
- web/main_test.go
This PR migrates the Update method from the TeamStore to Sync by default.
Fixes https://github.com/mattermost/mattermost-server/issues/10690
> MM-15276: Migrate Team.Update to sync by default

- app/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
This PR Migrates WebHookStore.GetOutgoingList  method to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10652
> GH-10652: Migrate WebHookStore.GetOutgoingList  method to sync by default

- app/channel.go
- app/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
This PR migrates the "WebHook.DeleteOutgoing" to Sync by default.
Fixes #10649
> MM 15187: Migrate "WebHook.DeleteOutgoing" to Sync by default

- app/webhook.go
- cmd/mattermost/commands/channel.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
This PR migrates the "WebHook.UpdateOutgoing" to Sync by default.
Fixes #10646
> [MM-15190] Migrate "WebHook.UpdateOutgoing" to Sync by default

- app/user.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Summary
This PR migrates the "WebHook.PermanentDeleteIncomingByUser" to Sync by default.
Ticket Link
Fixes #10620
> MM 15119 : migrates the "WebHook.PermanentDeleteIncomingByUser" to Sync by default.

- app/webhook.go
- cmd/mattermost/commands/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Summary
This PR migrates the "WebHook.GetOutgoingByTeam" to Sync by default.
Ticket Link
Fixes #10651
> MM-15186: Migrate "WebHook.GetOutgoingByTeam" to Sync by defa

- app/user.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
This PR migrates the "WebHook.PermanentDeleteOutgoingByUser" to Sync by default.
Fixes #10648
> MM-15188: Migrate the "WebHook.PermanentDeleteOutgoingByUser" to Sync by default

- app/command.go
- cmd/mattermost/commands/command.go
- store/sqlstore/command_store.go
- store/store.go
- store/storetest/command_store.go
- store/storetest/mocks/CommandStore.go
This PR migrates commandstore.GetByTeam to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10728
> MM-15289 Migrate commandStore.GetByTeam to sync by default

- app/user.go
- store/sqlstore/command_store.go
- store/store.go
- store/storetest/command_store.go
- store/storetest/mocks/CommandStore.go
This PR migrates commandstore.PermanentDeleteByUser to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10724
> MM-15293: migrate commandstore.PermanentDeleteByUser to sync by default

- app/command.go
- store/sqlstore/command_store.go
- store/store.go
- store/storetest/command_store.go
- store/storetest/mocks/CommandStore.go
This PR migrates commandstore.Update to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10723
> MM-15294: migrate commandstore.Update to sync by default

- app/command.go
- store/sqlstore/command_store.go
- store/store.go
- store/storetest/command_store.go
- store/storetest/mocks/CommandStore.go
This PR migrates commandstore.save to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10730
> MM-15287: Migrate commandstore.save to sync by default

- api4/scheme_test.go
- api4/team_test.go
- app/team.go
- manualtesting/manual_testing.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/TeamStore.go
- store/storetest/post_store.go
- store/storetest/scheme_store.go
- store/storetest/status_store.go
- store/storetest/team_store.go
- store/storetest/user_store.go
[MM-15275] Migrate "Team.Save" to Sync
Fixes https://github.com/mattermost/mattermost-server/issues/10691
[MM-15275]: https://mattermost.atlassian.net/browse/MM-15275
> [MM-15275] Migrate "Team.Save" to Sync

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Change Channel.GetChannelUnread to sync by default.
Fixes https://github.com/mattermost/mattermost-server/issues/10766
> Change Channel.GetChannelUnread to sync

- app/import.go
- app/import_functions.go
- app/import_test.go
Log warning message and continue bulk import when the error is related to large image size.
Fixes https://github.com/mattermost/mattermost-server/issues/10754
> [MM-13033] Continue bulk import on large image error

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190506

- i18n/en.json
Update the error message for - LDAP Result Code 4 "Size Limit Exceeded" to provide some help for the user to troubleshoot.
This change is needed for https://github.com/mattermost/enterprise/pull/429
Fixes https://mattermost.atlassian.net/browse/MM-15314
> MM-15314 - Update Error message in System Console for LDAP result code 4 "Size Limit Exceeded"

- cmd/mattermost/commands/group.go
- cmd/mattermost/commands/group_test.go
- store/sqlstore/group_supplier.go
Adds group commands for channel and team to check the status, enable and disable group constrains, and to list the associated groups for a given team or channel.
https://mattermost.atlassian.net/browse/MM-15164
> [MM-15164] Add group commands

- app/emoji.go
- store/sqlstore/emoji_store.go
- store/store.go
- store/storetest/emoji_store.go
- store/storetest/mocks/EmojiStore.go
Migrate "Emoji.Get" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10644
> [MM-15193] Migrate "Emoji.Get" to Sync by default

- app/post.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
This PR  Migrates Post.Delete to sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10760
> GH-10760: Migrate Post.Delete to sync by default

- api4/file.go
This bug appeared with the introduction of gzipping our API responses. The problem boils down to when an HTTP response's body is gzipped, the `Content-Length` header should contain the length of the content after compression. This can cause a problem when setting `Content-Length` to something other than the compressed length resulting in EOF errors if the content is too long or "wrote more than length" errors when too short. To deal with this the library we're using deletes any `Content-Length` headers before writing the response (see https://github.com/nytimes/gziphandler/blob/master/gzip.go#L157).
All this causes our clients a problem because they need the total length of the content uncompressed to display a progress percentage for how much of the file is loaded. The remedy is to use a …
> MM-15320/MM-15518 When gzipping file responses add header for uncompressed content length

- api4/scheme_test.go
- app/channel.go
- app/import_functions.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/user_store.go
This PR migrates the Channel.Update method from the store to Sync.
Fixes https://github.com/mattermost/mattermost-server/issues/10767
> [MM-15356] Migrate "Channel.Update" to Sync by default

- i18n/fr.json
- i18n/pl.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190513

- app/email_batching.go
- app/notification_email.go
- app/notification_push.go
- app/preference.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
**Summary**
Migrate "Preference.Get" to Sync by default
[**Ticket Link**](https://mattermost.atlassian.net/browse/MM-15297)
Fixes #10721
> [MM-15297] Migrate "Preference.Get" to Sync by default #10721

- model/version.go
- store/sqlstore/upgrade.go
Before we cut 5.11.0-rc3 need to merge this and this PR https://github.com/mattermost/mattermost-server/pull/10826
> upgrade db to 5.11.0

- app/opengraph.go
- app/post_metadata.go
This is from a small followup ticket to the post metadata changes that I found in my backlog
https://mattermost.atlassian.net/browse/MM-13142
> MM-13142 Replace mlog.Any with mlog.Err

- config/default.json
- tests/test-config.json
Changed authentication URL for Google OAuth. Needed for https://github.com/mattermost/enterprise/pull/430
Fixes https://mattermost.atlassian.net/browse/MM-14874
> MM-14874 - Google SSO: Migrate user API endpoint from Google+ API to People API

- app/channel.go
- app/opengraph.go
- app/web_conn.go
This change lowers the levels of a few log messages in an attempt
to bring them more in line with the severity of the actual message.
The primary goal is to reduce logging noise where possible.
More information can be found here: https://mattermost.atlassian.net/browse/MM-15497
> [MM-15497] Review error logging

- api4/plugin.go
- stop exposing unnecessary plugin SettingsSchema in the api
fixes: [MM-15503](https://mattermost.atlassian.net/browse/MM-15503)
> [MM-15503] Stop exposing plugin's SettingsSchema in api/v4/plugins/webapp

- store/sqlstore/user_store.go
Fixing Elasticsearch indexing that was failing with the new SchemeGuest field.
> Fixing Elasticsearch indexing

- api4/channel.go
- app/channel.go
- app/channel_test.go
- i18n/en.json
- model/channel.go
- model/channel_search.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- web/params.go
Adds new parameters for retrieving pages of channels and searching channels.
https://mattermost.atlassian.net/browse/MM-15422
> MM-15422: Adds new parameters for retrieving pages of channels.

- app/command_loadtest.go
On `/test` command, added the ability to post a message using a different user in another channel/team.  It's added so that during test (like in Rainforest), a tester does not need to use another browser/tab just to post a message from another user.  Applicable for test cases like observing unread message, at-mentions, etc.
Usage:
```
Post - Add post to a channel as another user.
/test post u=@username p=passwd c=~channelname t=teamname "message"
Example:
/test post u=@user-1 p=user-1 c=~town-square t=ad-1 "message"
```
To enable `/test` command, "Enable Testing Commands" should be set to true in System Console settings.
Jira: https://mattermost.atlassian.net/browse/MM-15370
> [MM-15370] Add /test post command to post a message as different user to a channel/team

- build/Jenkinsfile.pr
- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190527

- app/emoji.go
- app/helper_test.go
- app/import_functions.go
- store/sqlstore/emoji_store.go
- store/store.go
- store/storetest/emoji_store.go
- store/storetest/mocks/EmojiStore.go
This PR migrates `Save` in `Emoji Store` to be Sync by default. 
Fixes #10642
> [MM-15194] Store: Migrate Emoji.Save to Sync as default #10642

- app/diagnostics.go
- model/config.go
https://mattermost.atlassian.net/browse/MM-15637
> [MM-15637] Add Trace config option to the Elasticsearch block

- app/group.go
- store/sqlstore/group_supplier.go
- store/store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/GroupStore.go
Migrate Groups store to sync by default, functions:
- GetGroupsByChannel
- CountGroupsByChannel
- GetGroupsByTeam
- CountGroupsByTeam
- GetGroups
> Migrate Groups store to sync by default (GetGroups and Counts)

- config/default.json
- model/config.go
[Related enterprise PR](https://github.com/mattermost/enterprise/pull/443)
> Change ES trace config type from boolean to string

- app/group.go
- store/sqlstore/group_supplier.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/GroupStore.go
- store/storetest/user_store.go
Migrate Store groups to sync by default (GroupSyncable methods)
> Migrate Store groups to sync by default (GroupSyncable methods)

- Makefile
- build/release.mk
Adds Autolink as a prepackaged plugin
https://mattermost.atlassian.net/browse/MM-15819
> MM-15819 Add Autolink as a prepackaged plugin

- Makefile
[MM-15818](https://mattermost.atlassian.net/browse/MM-15818)
[MM-15816](https://mattermost.atlassian.net/browse/MM-15816)
> Add welcomebot and aws-SNS to prepackaged plugins

- Makefile
Add custom-attributes as a bundled plugin
[MM-15817](https://mattermost.atlassian.net/browse/MM-15817)
> MM-15817 Add custom-attributes as a bundled plugin

- i18n/es.json
- i18n/it.json
- i18n/ko.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/tr.json
- i18n/zh-CN.json
> translations PR 20190603

- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
Migrate "Session.RemoveAllSessions" to Sync by default
https://mattermost.atlassian.net/browse/MM-15798
Fixes https://github.com/mattermost/mattermost-server/issues/10934
> [MM-15798] Migrate Session.RemoveAllSessions to Sync by default

- app/export.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
This PR made changes to Post.GetRepliesForExport to be sync and made changes to code that called this function, to no longer call it async as a channel.
(This is my first contribution to OSS, so sorry if more detail is needed. Let me know if it is)
Fixes #10964
https://mattermost.atlassian.net/browse/MM-15864
> MM-15864 - Made Post.GetRepliesForExport sync

- Makefile
> zoom v1.0.6 -> v1.0.7

- Makefile
> Updated prepackaged Jira plugin version to 2.0.1

- store/sqlstore/upgrade.go
preparing code for db upgrade to 5.13
> prepare upgrade to 5.13

- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Migrate "Team.SearchByName" to Sync by default
https://mattermost.atlassian.net/browse/MM-16160
Fixes https://github.com/mattermost/mattermost-server/issues/11095
> [MM-16160] Migrate Team.SearchByName to Sync by default

- app/channel.go
- app/email_batching.go
- app/import_functions.go
- app/team.go
- cmd/mattermost/commands/teamargs.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
This pull request migrates the `GetByName` in the `Team` store to use Sync by default. I followed the instructions laid out in the issue description and updated all necessary files.
Resolves #11094
> [MM-16159] Migrate "Team.GetByName" to Sync by default

- app/channel.go
Allow to have town-square in ExperimentalDefaultChannels
[MM-16154](https://mattermost.atlassian.net/browse/MM-16154)
> MM-16154: Allow to have town-square in ExperimentalDefaultChannels

- app/session.go
- app/session_test.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
Migrates "Session.UpdateLastActivityAt" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10932
> GH-10932 Migrate 'Session.UpdateLastActivityAt' to Sync by default

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190611

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Fixes #11122. GetMembers is sync now
> Migrate `Team.GetMembers` to Sync by default

- api4/apitestlib.go
- app/channel.go
- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
This PR makes Team.GetMember sync now. Fix #11123
> Migrate `Team.GetMember` to Sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrates `Channel.GetMoreChannels` to sync by default. Fix #11166 
https://mattermost.atlassian.net/browse/MM-16323
> Channel.GetMoreChannels to sync by default

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
Migrate Team.GetAllPage to Sync by default
https://mattermost.atlassian.net/browse/MM-16165
Fixes  #11089
> [MM-16165] Migrate Team.GetAllPage to Sync by default

- app/channel.go
- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate `Channel.GetChannelsByIds` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11161
> Migrate Channel.GetChannelsByIds to Sync by default

- app/channel.go
- app/team.go
- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrates `Channel.GetTeamChannels` to sync by default. Solves #11162 
https://mattermost.atlassian.net/browse/MM-16327
> Channel.GetTeamChannels to sync by default

- model/version.go
- store/sqlstore/upgrade.go
- upgrade db to 5.13
- prepare upgrade to 5.14
when merge will cherry-pick and upgrade the db in the release-5.13 branch
> upgrade db to 5.13 and prepare upgrade to 5.14

- app/channel.go
- cmd/mattermost/commands/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16342
Fixes #11217
> Migrates Channel.PermanentDeleteMembersByChannel to sync by default

- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
Migrate "Channel.UserBelongsToChannels" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11249
> Migrate Channel.UserBelongsToChannels to Sync by default

- app/export.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16360
Fixes #11251
> Migrates Channel.GetChannelMembersForExport to sync by default

- app/channel.go
- app/team.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/group_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/user_store.go
Migrate "Channel.RemoveMember" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11220
> Migrate "Channel.RemoveMember" to Sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate "Channel.RemoveAllDeactivatedMembers" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11250
> Migrate Channel.RemoveAllDeactivatedMembers to Sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
Fixes #11226
https://mattermost.atlassian.net/browse/MM-16334
> Migrate Channel.GetChannelMembersTimezones to Sync by default

- app/authorization.go
- app/integration_action.go
- app/post.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This pull request migrates "Channel.GetForPost" to sync and updates any impacted code caused by the change. 
Resolves https://github.com/mattermost/mattermost-server/issues/11159
> [MM-16330] Migrate "Channel.GetForPost" to Sync by default

- app/permissions.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16357
Fixes #11254
> Migrates Channel.ClearAllCustomRoleAssignments to sync by default

- app/export.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16358
Fixes #11253
> Migrates Channel.GetAllChannelsForExportAfter to sync by default

- app/diagnostics.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16353
Fixes #11258
Included are two other light refactoring commits which I'm not sure are desired.
> [MM-16353] Migrate Channel.AnalyticsDeletedTypeCount to Sync by default

- app/channel.go
- app/team.go
- manualtesting/manual_testing.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR migrates `Channel.GetChannels` to sync by default.
https://mattermost.atlassian.net/browse/MM-16321
Fixes #11169
> Migrates Channel.GetChannels to sync by default

- app/authorization.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate Channel.GetMemberForPost to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11223
> Migrate Channel.GetMemberForPost to Sync by default

- migrations/advanced_permissions_phase_2.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate Channel.MigrateChannelMembers to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11256
> Migrate Channel.MigrateChannelMembers to Sync by default

- app/emoji.go
- store/sqlstore/emoji_store.go
- store/store.go
- store/storetest/emoji_store.go
- store/storetest/mocks/EmojiStore.go
Migrate "Emoji.Delete" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11293
> Migrate Emoji.Delete to Sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR will migrate `Channel.GetMemberCount` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11222
> [MM-11222] Migrate 'Channel.GetMemberCount' to Sync by default

- app/export.go
- app/export_test.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16359
Fixes #11252
> Migrates Channel.GetAllDirectChannelsForExportAfter to sync by default

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
Migrate UserAccessToken.GetAll to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11302
> [MM-16485] Migrate UserAccessToken.GetAll to Sync by default

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
Migrate `UserAccessToken.Get` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11303
> [MM-16484] Migrate UserAccessToken.Get to Sync by default

- app/permissions.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
https://mattermost.atlassian.net/browse/MM-16356
Fixes #11255
> Migrates Channel.ResetAllChannelSchemes to sync by default

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
This PR will migrate `UserAccessToken.GetByToken` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11301
> [MM-11301] Migrate 'UserAccessToken.GetByToken' to Sync by default

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
This PR will migrate `UserAccessToken.Save` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11306
> [MM-11306] Migrate 'UserAccessToken.Save' to Sync by default

- app/emoji.go
- app/import_functions.go
- app/import_functions_test.go
- store/sqlstore/emoji_store.go
- store/store.go
- store/storetest/emoji_store.go
- store/storetest/mocks/EmojiStore.go
made the emoji store getByName method sync
Fixes https://github.com/mattermost/mattermost-server/issues/11299
> made the emoji store getByName method sync

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
This PR will migrate `UserAccessToken.GetByUser` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11300
> [MM-11300 ] Migrate 'UserAccessToken.GetByUser' to Sync by default

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
https://mattermost.atlassian.net/browse/MM-16490
Fixes #11296
> [MM-16490] Migrate UpdateTokenDisable to Sync by default

- i18n/es.json
- i18n/it.json
- i18n/ja.json
- i18n/pl.json
- i18n/ro.json
- i18n/tr.json
- i18n/zh-CN.json
> translations PR 20190617

- wsapi/user.go
See [Desktop App PR](https://github.com/mattermost/desktop/pull/993) for details.
Desktop: [MM-7970](https://github.com/mattermost/desktop/pull/993)
Webapp: [MM-7970](https://github.com/mattermost/mattermost-webapp/pull/2992)
Server: [MM-14582](https://github.com/mattermost/mattermost-server/pull/11312) (this PR)
> [MM 7970] Support maintaining online status while the Desktop App is in the background ... and other things.

- api4/team_test.go
- api4/user_test.go
- app/oauth.go
- app/team.go
- app/team_test.go
- app/user.go
- app/user_test.go
- store/sqlstore/tokens_store.go
- store/store.go
- store/storetest/mocks/TokenStore.go
https://mattermost.atlassian.net/browse/MM-16514
Fixes #11346
> [MM-16514] Migrate Token.GetByName to Sync by Default

- app/diagnostics.go
- model/config.go
https://mattermost.atlassian.net/browse/MM-16244
- [Has enterprise changes](https://github.com/mattermost/enterprise/pull/458)
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/2968)
> [MM-16244] Add Elasticsearch SkipTLSVerification parameter to the config

- store/sqlstore/status_store.go
- store/store.go
- store/storetest/mocks/StatusStore.go
- store/storetest/status_store.go
https://mattermost.atlassian.net/browse/MM-16525
Fixes #11335
> Migrates Status.GetOnline to sync by default

- store/sqlstore/status_store.go
- store/store.go
- store/storetest/mocks/StatusStore.go
- store/storetest/status_store.go
Migrate Status.GetAllFromTeam method to Sync
Fixes https://github.com/mattermost/mattermost-server/issues/11334
> Migrate Status.GetAllFromTeam method to Sync

- app/session.go
- store/sqlstore/user_access_token_store.go
- store/store.go
- store/storetest/mocks/UserAccessTokenStore.go
- store/storetest/user_access_token_store.go
Migrate UserAccessToken.Delete to Sync by default
https://mattermost.atlassian.net/browse/MM-16482
Fixes #11305
> MM-16482 Migrate UserAccessToken.Delete to Sync by default

- i18n/de.json
- i18n/pt-BR.json
> translations PR 20190624

- app/security_update_check.go
- store/sqlstore/status_store.go
- store/store.go
- store/storetest/mocks/StatusStore.go
- store/storetest/status_store.go
**Summary**
Migrate "Status.GetTotalActiveUsersCount" to Sync by default
Fixes #11339
> MM-16521 Migrate "Status.GetTotalActiveUsersCount" to Sync by default

- plugin/health_check_test.go
This PR modifies the panic test in `plugin/health_check_test.go` to assert that a general error occurred during the health check, instead of checking specifically (1) if the process is not responding or (2) if the RPC ping failed. This is because these two failures happen virtually simultaneously, so the tests for asserting the reason of failure are brittle because of OS-level race conditions.
What's important is that the health check can determine that the plugin has crashed and restart/disable the plugin.
https://mattermost.atlassian.net/browse/MM-15706
> [MM-15706] Make plugin health check test look for general failure

- app/ratelimit_test.go
- app/status.go
- store/sqlstore/status_store.go
- store/store.go
- store/storetest/mocks/StatusStore.go
- store/storetest/status_store.go
Migrate "Status.GetByIds" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11343
> Migrate "Status.GetByIds" to Sync by default

- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate "Channel.PermanentDeleteMembersByUser" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11219
> Migrate "Channel.PermanentDeleteMembersByUser" to Sync by default

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Migrate Team.SearchOpen to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11092
> [MM-16162] migrate Team.SearchOpen to Sync by default

- api4/team_test.go
- api4/user_test.go
- app/email.go
- app/oauth.go
- app/oauth_test.go
- app/team_test.go
- app/user.go
- app/user_test.go
- store/sqlstore/tokens_store.go
- store/store.go
- store/storetest/mocks/TokenStore.go
https://mattermost.atlassian.net/browse/MM-16512
Fixes #11348
> [MM-16512] Migrate Token.Save to Sync by default

- app/analytics.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
**Summary**
Migrate "User.GetNewUsersForTeam" to Sync by default
Fixes #11391
> MM-16565 Migrate "User.GetNewUsersForTeam" to Sync by default

- app/post_metadata.go
- store/sqlstore/link_metadata_store.go
- store/store.go
- store/storetest/link_metadata_store.go
- store/storetest/mocks/LinkMetadataStore.go
Migrate "LinkMetadata.Get" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11336
> MM-16524 Migrate "LinkMetadata.Get" to Sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.Search" to Sync by default
Fixes #11389
> [MM-16566] Migrate "User.Search" to Sync by default

- app/channel.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
Migrate "User.GetAnyUnreadPostCountForChannel" to Sync by default
Fixes #11393
> [MM-16563] Migrate "User.GetAnyUnreadPostCountForChannel" to Sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate ```User.GetChannelGroupUsers``` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11377
> MM-16579 Migrate User.GetChannelGroupUsers to Sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate ```User.GetTeamGroupUsers``` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11378
> MM-16578 Migrate User.GetTeamGroupUsers to Sync by default

- app/server.go
- store/sqlstore/status_store.go
- store/store.go
- store/storetest/mocks/StatusStore.go
- store/storetest/status_store.go
Migrate "Status.ResetAll" to Sync by default
Fixes #11340
> [MM-16520] Migrate "Status.ResetAll" to Sync by default

- app/export.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate ```User.GetAllAfter``` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11379
> MM-16577 Migrate User.GetAllAfter to Sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.GetProfilesNotInTeam" to Sync by default.
Fixes https://github.com/mattermost/mattermost-server/issues/11383
> Migrate 'User.GetProfilesNotInTeam' to Sync by default

- api4/user_test.go
- services/mfa/mfa.go
- services/mfa/mfa_test.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.UpdateMfaSecret" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11465
> GH-11465 Migrate User.UpdateMfaSecret to Sync by default

- cmd/mattermost/commands/channel.go
- cmd/mattermost/commands/channel_test.go
CLI channel list and search commands currently show if a channel is archived.
This PR improves on that by showing also when a channel is private.
https://mattermost.atlassian.net/browse/MM-16476
> MM-16476 Update CLI channel list and search commands to show if a channel is private

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrate "User.SearchNotInChannel" to Sync by default
Fixes #11387
> [MM-16569] Migrate "User.SearchNotInChannel" to Sync by default

- Makefile
This is to fix a bug where the NPS plugin responds to the autoresponder, causing it to get in a funny state
https://mattermost.atlassian.net/browse/MM-16682
> MM-16682 Update NPS plugin to 1.0.1

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16670
Fixes #11450
> Migrate User.GetEtagForProfiles to sync by default

- app/channel.go
- app/slack.go
- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16666
Fixes #11454
> Migrate User.GetProfileByIds to sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16664
Fixes #11456
> Migrate User.GetAllProfiles to sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16669
Fixes #11451
> Migrate User.GetEtagForAllProfiles to sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.UpdateLastPictureUpdate" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11469
> GH-11469 Migrate User.UpdateLastPictureUpdate to Sync by default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
make `user.GetAll` return `[]*model.User` and `*model.AppError`
fixing its usage
run `make store-mocks`
Fixes https://github.com/mattermost/mattermost-server/issues/11463
> make user.Get all return []*model.User and *model.AppError

- app/channel.go
- app/notification.go
- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16660
Fixes #11460
> 11460 user.get all profiles in channel

- app/channel.go
- app/command_loadtest.go
- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16665
Fixes #11455
> Migrate User.GetProfiles to sync by default

- app/authentication.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16671
Fixes #11449
> Migrate User.UpdateFailedPasswordAttempts to sync by default

- app/permissions.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
https://mattermost.atlassian.net/browse/MM-16575
Fixed #11381
> Migrate User.ClearAllCustomRoleAssignments to sync by default

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Migrate "Team.UpdateLastTeamIconUpdate" to Sync by default
https://mattermost.atlassian.net/browse/MM-16775
Fixes https://github.com/mattermost/mattermost-server/issues/11553
> Migrate "Team.UpdateLastTeamIconUpdate" to Sync by default

- store/storetest/group_store.go
Fix flaky group store test.
https://mattermost.atlassian.net/browse/MM-16759
> MM-16759: Fix flaky group-store test.

- i18n/ko.json
- i18n/ru.json
> translations PR 20190701

- store/sqlstore/user_store.go
- store/storetest/user_store.go
Set UpdateAt correctly on deleting profile pic.
https://mattermost.atlassian.net/browse/MM-16625
> MM-16625: Set UpdateAt correctly on deleting profile pic.

- app/plugin_key_value_store.go
- store/sqlstore/plugin_store.go
- store/store.go
- store/storetest/mocks/PluginStore.go
This PR migrates Plugin.List in the Store layer to be sync by default
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-16773)
Fixes #11534
> [MM-16794] Migrate Plugin.List to Sync by default

- app/user.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
Make the call to Team.GetUserTeamIds synchrounous as part of the effort in https://mattermost.atlassian.net/browse/MM-15277
Fixes #11544
> [MM-16784] Sync GetUserTeamIds

- app/permissions.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Migrate "Team.ResetAllTeamSchemes" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11550
> GH-11550 Migrate "Team.ResetAllTeamSchemes" to Sync by default

- app/plugin_key_value_store.go
- app/plugin_test.go
- store/sqlstore/plugin_store.go
- store/store.go
- store/storetest/mocks/PluginStore.go
- store/storetest/plugin_store.go
https://mattermost.atlassian.net/browse/MM-16788
> Migrate Plugin.SaveOrUpdate to sync by default

- app/webhook.go
- store/sqlstore/command_webhook_store.go
- store/store.go
- store/storetest/command_webhook_store.go
- store/storetest/mocks/CommandWebhookStore.go
https://mattermost.atlassian.net/browse/MM-16785
> Migrate CommandWebhook.Save to sync by default

- app/webhook.go
- store/sqlstore/command_webhook_store.go
- store/store.go
- store/storetest/command_webhook_store.go
- store/storetest/mocks/CommandWebhookStore.go
https://mattermost.atlassian.net/browse/MM-16786
> Migrate CommandWebhook.Get to sync by default

- i18n/zh-TW.json
> translations PR 20190708

- app/permissions.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
**Summary**
Migrate "Team.ClearAllCustomRoleAssignments" to Sync by default
https://mattermost.atlassian.net/browse/MM-16779
Fixes #11549
> Migrate "Team.ClearAllCustomRoleAssignments" to Sync by default

- api4/bot.go
- api4/bot_test.go
- app/bot.go
- app/bot_test.go
- app/plugin_api.go
- i18n/en.json
- model/client4.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- Extended PluginAPI to include `GetBotIconImage` `SetBotIconImage` `DeleteBotIconImage`
Fixes https://mattermost.atlassian.net/browse/MM-16872
Created a HW ticket to override LHS bot icon using the new plugin api
https://mattermost.atlassian.net/browse/MM-16903
> MM-16872 - Extend Plugin API to set LHS bot icon

- store/sqlstore/post_store.go
- store/storetest/post_store.go
See a full explanation of this fix here: https://github.com/mattermost/mattermost-server/pull/11618
https://mattermost.atlassian.net/browse/MM-16921
> MM-16921 Fix getPostsSince caching no results (5.13)

- README.md
please ignore
@stylianosrigas and @saturninoabril can you guys do me a favor and approve this pr? :)
> just to test the cherry pick

- README.md
please ignore
@stylianosrigas and @saturninoabril can you guys do me a favor and approve this pr? :)
> test cherry pick again

- api4/channel.go
- app/channel.go
- app/plugin_api.go
- app/web_hub.go
- model/channel_stats.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Adding guest counts for channel stats
> Adding guest counts for channel stats

- Makefile
The new version includes some dependency upgrades, an improvement for dark theme support, and an improvement for the community server's multiple site URLs
https://mattermost.atlassian.net/browse/MM-16797
> MM-16797 Update NPS plugin to v1.0.2

- app/post_metadata.go
- app/post_metadata_test.go
This is a complement to https://github.com/mattermost/mattermost-server/pull/11586 after a change on https://github.com/mattermost/mattermost-webapp/pull/3074 and https://github.com/mattermost/mattermost-mobile/pull/2961.
> MM-16389 - complement for emoji_icon issue

- store/sqlstore/post_store.go
This change modifies the database query used by the getPostsAround()
method in order to improve the performance of loading posts when
scrolling through a channel.
https://mattermost.atlassian.net/browse/MM-16936
Note that I didn't find any meaningful holes in the original testing of this
code, so it should still be valid.
> Improve DB performance on getPostsAround()

- Makefile
> jira to 2.0.7

- app/opengraph.go
https://mattermost.atlassian.net/browse/MM-17043
> MM-17043 Downgrade OpenGraph logging to debug level

- api4/plugin_test.go
- app/cluster_handlers.go
- app/file.go
- app/plugin.go
- app/plugin_event.go
- app/plugin_install.go
- app/plugin_test.go
- i18n/en.json
- model/cluster_message.go
- model/plugin_event_data.go
- services/filesstore/filesstore_test.go
- services/filesstore/localstore.go
- services/filesstore/s3store.go
- testlib/cluster.go
Cherry pick of #11657 on release-5.14.
- #11657: MM-16272 - Synchronize plugins across cluster (#11611)
> Automated cherry pick of #11657

- Makefile
This update includes a rebranding of NPS surveys from Net Promoter Score surveys to user satisfaction surveys
https://mattermost.atlassian.net/browse/MM-16825
> MM-16825 Update NPS plugin to 1.0.3

- Makefile
Cherry pick of #11664 on release-5.14.
- #11664: MM-16825 Update NPS plugin to 1.0.3
/cc  @hmhealey
> Automated cherry pick of #11664

- app/user.go
Fixing guest domain restrictions
> Fixing guest domain restrictions

- app/user.go
- app/user_test.go
Cherry pick of #11425 on release-5.14.
- #11425: Add bot store PermanentDelete() method to
/cc  @jfrerich
> Automated cherry pick of #11425

- store/sqlstore/post_store.go
Cherry pick of #11662 on release-5.14.
- #11662: Improve DB performance on getPostsAround()
/cc  @gabrieljackson
> Automated cherry pick of #11662

- store/sqlstore/channel_store.go
Fixing initial DMs/GMs load
[MM-17223](https://mattermost.atlassian.net/browse/MM-17223)
> Fixing initial DMs/GMs load

- app/diagnostics.go
Cherry pick of #11677 on release-5.14.
- #11677: Add telemetry for new cluster settings
> Automated cherry pick of #11677

- app/export.go
- cmd/mattermost/commands/export.go
- store/sqlstore/post_store.go
This change modifies some of the logic for processing posts during
bulk export in order to improve performance.
This resolves the main issue I found when testing against a very large
dataset. More improvements could be made in the future.
https://mattermost.atlassian.net/browse/MM-16278
> [MM-16278] Improve bulk export of posts

- app/analytics.go
- app/diagnostics.go
- store/sqlstore/user_store.go
- store/sqlstore/user_store_test.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Cherry pick of #11658 on release-5.14.
- #11658: Add model.UserCountOptions to analyticsActiveCount method
/cc  @jfrerich
> Automated cherry pick of #11658

- app/export.go
- cmd/mattermost/commands/export.go
- store/sqlstore/post_store.go
Cherry pick of #11702 on release-5.14.
- #11702: Improve bulk export of posts
/cc  @gabrieljackson
> Automated cherry pick of #11702

- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
More robust guest members for users and tests for it
- https://mattermost.atlassian.net/browse/MM-17237
- https://mattermost.atlassian.net/browse/MM-17223
- https://mattermost.atlassian.net/browse/MM-17222
- maybe https://mattermost.atlassian.net/browse/MM-17093
> More robust guest members for users and tests for it

- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
Fix pagination bug on LDAP groups users listing
[MM-17309](https://mattermost.atlassian.net/browse/MM-17309)
> Fix pagination bug on LDAP groups users listing

- Makefile
- api4/apitestlib.go
- build/docker-compose.yml
Cherry pick of #11709 on release-5.14.
- #11709: MM-16935 - Flaky test: Elastic Search IndexChannel Error
> Automated cherry pick of #11709

- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
Cherry pick of #11711 on release-5.14.
- #11711: Fix pagination bug on LDAP groups users listing
/cc  @jespino
> Automated cherry pick of #11711

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190724

- store/storetest/channel_store.go
- store/storetest/post_store.go
- store/storetest/status_store.go
- store/storetest/team_store.go
Cherry pick of #11705 on release-5.14.
- #11705: MM-17053: avoid colliding with reserved team names
> Automated cherry pick of #11705

- i18n/en.json
- store/sqlstore/preference_store.go
- store/sqlstore/status_store.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/mocks/StatusStore.go
- store/storetest/mocks/TeamStore.go
- store/storetest/preference_store.go
- store/storetest/status_store.go
- store/storetest/team_store.go
Removing unnused store methods
[MM-16231](https://mattermost.atlassian.net/browse/MM-16231)
> Removing unnused store methods

- api4/post_test.go
- app/post.go
Cherry pick of #11729 on release-5.14.
- #11729: leverage testify for
> Automated cherry pick of #11729

- app/slackimport.go
Cherry pick of #11704 on release-5.14.
- #11704: changes for channel and post import for corp slack
/cc  @svelle
> Automated cherry pick of #11704

- build/Jenkinsfile.pr
Adding a step to jenkins clean up to record docker logs to help investigate https://mattermost.atlassian.net/browse/MM-16935
> MM-16935 - Capture docker logs

- app/plugin_hooks_test.go
Cherry pick of #11684 on release-5.14.
- #11684: MM-16479: panic on io.Copy error in test
> Automated cherry pick of #11684

- app/webhook_test.go
Cherry pick of #11712 on release-5.14.
- #11712: fix flaky TestDoOutgoingWebhookRequest/with_a_slow_response
> Automated cherry pick of #11712

- store/storetest/channel_store.go
Cherry pick of #11715 on release-5.14.
- #11715: MM-17235: fix flaky TestChannelStore tests
> Automated cherry pick of #11715

- app/export.go
- app/export_test.go
Cherry pick of #11738 on release-5.14.
- #11738: don't fail on deleted users
/cc  @reflog
> Automated cherry pick of #11738

- app/post_metadata.go
- app/post_metadata_test.go
Cherry pick of #11766 on release-5.14.
- #11766: MM-17326 Properly specify multiple Accept headers for
/cc  @hmhealey
> Automated cherry pick of #11766

- model/version.go
- store/sqlstore/upgrade.go
Before we cut rc1 we need to upgrade the database
This Pr points to release 5.14 branch
> upgrade db to 5.14

- Makefile
- app/plugin_test.go
- build/Jenkinsfile.pr
- build/docker-compose.yml
- build/legacy.mk
The recent docker-compose changes broke the build -- Jenkins uses `master` when building a community branch, and the breakage wasn't detected. 
https://mattermost.atlassian.net/browse/MM-7971
> Tweak docker compose setup

- app/import_functions.go
- app/import_functions_test.go
Cherry pick of #11770 on release-5.14.
- #11770: prevent attachment duplication
/cc  @reflog
> Automated cherry pick of #11770

- model/version.go
- store/sqlstore/upgrade.go
Enabling the release-5.14 migration and adding the 5.15 and 5.16 skel
> Enabling the release-5.14 migration and adding the 5.15 and 5.16 skel

- app/email.go
- i18n/en.json
- templates/invite_body.html
Update email templates for guest accounts
[MM-17336](https://mattermost.atlassian.net/browse/MM-17336)
> Update email templates for guest accounts

- i18n/fr.json
- i18n/it.json
- i18n/ko.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/tr.json
> translations PR 20190805

- api4/plugin.go
Fixes  #11808
Jira ticket: https://mattermost.atlassian.net/browse/MM-17590
> Fix NPE when installing a plugin via URL

- i18n/en.json
From my last PR there was an unnecessary linebreak in the translation file which is getting removed by this PR.
> Removed unncessary newline from i18n file

- api4/apitestlib.go
- api4/config_test.go
- app/helper_test.go
- app/plugin_api_test.go
- config/common.go
- config/common_test.go
- config/database.go
- config/database_test.go
- config/file.go
- config/file_test.go
- config/memory.go
- config/memory_test.go
- migrations/helper_test.go
- model/config.go
- web/web_test.go
Cherry pick of #11821 on release-5.14.
- #11821: Respect env var overrides when setting config
> Automated cherry pick of #11821

- store/sqlstore/group_store.go
- store/storetest/group_store.go
Removes deactivated users from the group member counts.
https://mattermost.atlassian.net/browse/MM-17432
> MM-17432: Removes deactivated users from the group member counts.

- api4/plugin.go
Cherry pick of #11809 on release-5.14.
- #11809: Fix NPE when installing a plugin via URL
/cc  @hanzei
> Automated cherry pick of #11809

- Makefile
Cherry pick of #11838 on release-5.14.
- #11838: Updating prepackaged jira and adding antivirus.
> Automated cherry pick of #11838

- einterfaces/ldap.go
- einterfaces/mocks/LdapInterface.go
Cherry pick of #11737 on release-5.14.
- #11737: MM-17117: Updates einterface for FirstLoginSync.
/cc  @mkraft
> Automated cherry pick of #11737

- app/brand.go
- app/team.go
- app/user.go
Cherry pick of #11827 on release-5.14.
- #11827: images crash the
/cc  @levb
> Automated cherry pick of #11827

- Makefile
- cmd/mattermost/commands/sampledata.go
Cherry pick of #11769 on release-5.14.
- #11769: update sampledata users passwords
/cc  @cpanato
> Automated cherry pick of #11769

- plugin/supervisor.go
Simplify the plugin health check to only leverage the `Ping` API instead of sending signals, the latter of which is not supported on Windows.
Verified this continues working with a plugin that `os.Exit(1)`s ten seconds after startup.
https://mattermost.atlassian.net/browse/MM-17488
> MM-17488: simplify plugin health check

- plugin/supervisor.go
Cherry pick of #11820 on release-5.14.
- #11820: MM-17488: simplify plugin health check
> Automated cherry pick of #11820

- api4/post_test.go
- app/plugin_api_test.go
- store/sqlstore/file_info_store.go
- store/storetest/file_info_store.go
Cherry pick of #11837 on release-5.14.
- #11837: tweak AttachToPost formatting
> Automated cherry pick of #11837

- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
Cherry pick of #11870 on release-5.14.
- #11870: Explicits the search configuration when using full
> Automated cherry pick of #11870

- app/diagnostics.go
- app/server.go
- mlog/log.go
- model/config.go
- plugin/health_check.go
- plugin/health_check_test.go
Cherry pick of #11819 on release-5.14.
- #11819: revert 4e5f6fcfbc85ea24788241c716862e1833c6f60e
> Automated cherry pick of #11819

- api4/post.go
- api4/post_test.go
Cherry pick of #11834 on release-5.14.
- #11834: leverage testify
> Automated cherry pick of #11834

- api4/team_test.go
- app/team.go
- app/user.go
- app/user_test.go
- i18n/en.json
Fixes the domain check when sending email invitations to guests and checks for guest email domains when updating users.
https://mattermost.atlassian.net/browse/MM-17213
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3358)
> [MM-17213] Fix domain check when inviting guests and update user checks

- i18n/de.json
- i18n/it.json
- i18n/ko.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190812

- app/diagnostics.go
- app/post_metadata.go
- app/post_metadata_test.go
- config/client.go
- model/config.go
Cherry pick of #11874 on release-5.14.
- #11874: MM-17609 Add EnableSVGs setting
/cc  @hmhealey
> Automated cherry pick of #11874

- Makefile
Releasing Gitlab prepackaged as v1.0.0
> Introduce gitlab prepackaged v1.0.0

- Makefile
Cherry pick of #11882 on release-5.14.
- #11882: introduce gitlab prepackaged v1.0.0
> Automated cherry pick of #11882

- app/diagnostics.go
Cherry pick of #11876 on release-5.14.
- #11876: MM-17483 Add Pre-packaged plugins to telemetry
/cc  @aaronrothschild
> Automated cherry pick of #11876

- Makefile
Cherry pick of #11884 on release-5.14
Automated cherry-pick was not created due to merge conflict
> Cherry-pick 5.14 Jira Plugin version to v2.1.0 (#11884)

- app/diagnostics.go
Update diagnostics to fix gofmt issue that's breaking master
broken by https://github.com/mattermost/mattermost-server/pull/11876
> Update diagnostics to fix gofmt issue

- app/diagnostics.go
Cherry pick of #11891 on release-5.14.
- #11891: Update diagnostics to fix gofmt issue
> Automated cherry pick of #11891

- Makefile
Releasing Jenkins prepackaged as v1.0.0
> Cherry-pick 5.14 Jenkins Plugin version to v1.0.0 (#11881)

- Makefile
Adds comments to make targets to include them in the output of `make help`.
n/a
> Adds comments to include targets in 'make help'.

- Makefile
Bump bundled Autolink plugin to v1.1.0
> Bump bundled Autolink plugin to v1.1.0

- i18n/ko.json
- i18n/nl.json
- i18n/ru.json
- i18n/zh-CN.json
> translations PR 20190819

- build/docker-compose.common.yml
Update minio to the latest release
> update minio docker image

- build/Dockerfile
Cherry pick of #11901 on release-5.14.
- #11901: bump dockerfile with latest mattermost package
/cc  @cpanato
> Automated cherry pick of #11901

- api4/plugin.go
- api4/plugin_test.go
Cherry pick of #11887 on release-5.15.
- #11887: Bumped http request timeout for plugin install from URL
> Automated cherry pick of #11887

- api4/plugin_test.go
- app/plugin.go
- app/plugin_install.go
- i18n/en.json
- plugin/environment.go
Cherry pick of #11779 on release-5.15.
- #11779: MM-17087 - Disable plugin on removal
> Automated cherry pick of #11779

- app/channel.go
- i18n/en.json
- model/post.go
https://mattermost.atlassian.net/browse/MM-17200
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3366)
- [Has redux changes](https://github.com/mattermost/mattermost-redux/pull/893)
> [MM-17200] Adds specific messages when guest is added or joins a channel

- api4/user.go
- api4/user_test.go
- model/user.go
Cherry pick of #11937 on release-5.15.
- #11937: Add additional input validation for user creation
/cc  @DSchalla
> Automated cherry pick of #11937

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190826

- app/helper_test.go
- app/notification_push.go
- app/notification_push_test.go
Cherry pick of #11979 on release-5.15.
- #11979: Use GetAnyUnreadPostCountForChannel for NotifyProps.push
/cc  @migbot
> Automated cherry pick of #11979

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190830

- model/version.go
- store/sqlstore/upgrade.go
> Upgrade database to 5.15 on release branch 5.15

- services/mailservice/mail.go
Converting to structured logging the file services/mailservice/mail.go
[MM-18206](https://mattermost.atlassian.net/browse/MM-18206)
> Converting to structured logging the file services/mailservice/mail.go

- Makefile
Cherry pick of #12045 on release-5.15.
- #12045: bump jira plugin version to 2.1.1
> Automated cherry pick of #12045

- app/team.go
- app/team_test.go
Except bots from team email domain restrictions.
https://mattermost.atlassian.net/browse/MM-18081
> MM-18081 Except bots from team email domain restrictions

- app/team.go
- app/team_test.go
Cherry pick of #12041 on release-5.15.
- #12041: Except bots from team email domain restrictions
> Automated cherry pick of #12041

- app/authorization_test.go
Migrate tests from `app/authorization_test.go` to use testify
[MM-18323](https://mattermost.atlassian.net/browse/MM-18323)
Fixes https://github.com/mattermost/mattermost-server/issues/12063
> [MM-18323] Migrate tests from "app/authorization_test.go" to use testify

- jobs/schedulers.go
Converting to structured logging the file jobs/schedulers.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12112
> Converting to structured logging the file jobs/schedulers.go

- web/handlers.go
Converting to structured logging the file web/handlers.go
https://mattermost.atlassian.net/browse/MM-18254
> Converting to structured logging the file web/handlers.go

- store/sqlstore/supplier_reactions.go
Converting to structured logging the file store/sqlstore/supplier_reactions.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12050
> Converting to structured logging the file store/sqlstore/supplier_reactions.go

- store/sqlstore/session_store.go
Converting to structured logging the file store/sqlstore/session_store.go
https://github.com/mattermost/mattermost-server/issues/12053
> Converting to structured logging the file store/sqlstore/session_store.go

- store/sqlstore/supplier.go
Converting to structured logging the file store/sqlstore/supplier.go
Fixes https://github.com/mattermost/mattermost-server/issues/12051
> Converting to structured logging the file store/sqlstore/supplier.go

- app/user.go
- app/user_test.go
Remove premature optimization that was generating a bad users isolation
[MM-18232](https://mattermost.atlassian.net/browse/MM-18232)
> Remove premature optimization that was generating a bad users isolation

- app/team.go
Converting to structured logging the file app/team.go
https://mattermost.atlassian.net/browse/MM-18261
> MM-18261 Converting to structured logging the file app/team.go

- app/command_echo.go
Converting to structured logging the file app/command_echo.go
https://mattermost.atlassian.net/browse/MM-18269
> MM-18269 Converting to structured logging the file app/command_echo.go

- api4/plugin_test.go
- app/plugin.go
Searching plugins locally on the server
Fixes https://mattermost.atlassian.net/browse/MM-18450
> MM-18450 - Local-only plugin search

- jobs/jobs_watcher.go
Converting to structured logging the file jobs/jobs_watcher.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12110
> Converting to structured logging the file jobs/jobs_watcher.go

- api4/system.go
Converting to structured logging the file api4/system.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12108
> Converting to structured logging the file api4/system.go

- app/notification.go
Converting to structured logging the file app/notification.go
https://mattermost.atlassian.net/browse/MM-18265
> MM-18265 Converting to structured logging the file app/notification.go

- app/web_conn.go
Converting to structured logging the file app/web_conn.go
https://mattermost.atlassian.net/browse/MM-18266
> MM-18266 Converting to structured logging the file app/web_conn.go

- api4/plugin_test.go
- model/marketplace_plugin.go
Extend the model definitions to support plugin icons from the marketplace.
https://mattermost.atlassian.net/browse/MM-17846
> MM-17846: plugin icons

- app/notification_email_test.go
- i18n/en.json
Cherry pick of #12131 on release-5.15.
- #12131: Remove double @ for email notifications
/cc  @enahum
> Automated cherry pick of #12131

- app/emoji.go
Converting to structured logging the file app/emoji.go
https://mattermost.atlassian.net/browse/MM-18264
> MM-18264 Converting to structured logging the file app/emoji.go

- utils/html.go
Converting to structured logging the file utils/html.go
https://mattermost.atlassian.net/browse/MM-18258
> MM-18258 Converting to structured logging the file utils/html.go

- app/export_test.go
Convert app/export_test.go t.Fatal calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12101
> Convert app/export_test.go t.Fatal calls into assert/require calls

- app/license.go
Converting to structured logging the file app/license.go
https://mattermost.atlassian.net/browse/MM-18271
> MM-18271 Converting to structured logging the file app/license.go

- Makefile
Fixes https://mattermost.atlassian.net/browse/MM-18506
> Bumped Jira plugin to 2.1.3

- Makefile
Cherry pick of #12185 on release-5.15.
- #12185: Bumped Jira plugin to 2.1.3
/cc  @levb
> Automated cherry pick of #12185

- model/user_search.go
Cherry pick of #12198 on release-5.15.
- #12198: Initialise UserSearch struct before trying to
> Automated cherry pick of #12198

- model/message_export.go
- store/sqlstore/compliance_store.go
Fix to included updated posts in the compliance export.
Requires enterprise PR: https://github.com/mattermost/enterprise/pull/491
https://mattermost.atlassian.net/browse/MM-18522
> MM-18522: Include edited posts in compliance export.

- model/message_export.go
- store/sqlstore/compliance_store.go
Cherry pick of #12197 on release-5.14.
- #12197: MM-18522: Export all post edits in compliance exports.
/cc  @mkraft
> Automated cherry pick of #12197

- app/user.go
Summary
Converting to structured logging the file app/user.go
Ticket Link
Fixes: #12194
> GH-12194 Converting to structured logging the file app/user.go

- app/email_batching.go
Converting to structured logging the file app/email_batching.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12115
> Converting to structured logging the file app/email_batching.go

- app/helper_test.go
Convert app/helper_test.go t.Fatal calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12212
> Convert app/helper_test.go t.Fatal calls into assert/require calls

- app/cluster_discovery.go
Converting to structured logging the file app/cluster_discovery.go
Fixes https://github.com/mattermost/mattermost-server/issues/12193
> Converting to structured logging the file app/cluster_discovery.go

- app/team_test.go
Migrate app/team_test.go to use testify for checks.
Solves https://github.com/mattermost/mattermost-server/issues/12215.
> Migrate app/team_test.go to use testify (#12215) 

- app/file.go
Converting to structured logging the file app/file.go
Fixes https://github.com/mattermost/mattermost-server/issues/12113
> Converting to structured logging the file app/file.go

- cmd/mattermost/commands/utils.go
Converting to structured logging the file cmd/mattermost/commands/utils.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12047
> Converting to structured logging the file cmd/mattermost/commands/utils.go

- model/version.go
- store/sqlstore/upgrade.go
- store/sqlstore/upgrade_test.go
Cherry pick of #12172 on release-5.16.
- #12172: Bump model version to 5.16
/cc  @hanzei
> Automated cherry pick of #12172

- app/authorization.go
Fixes #12195 
*Ticket link*
https://mattermost.atlassian.net/browse/MM-18285
> Refactor "app/authorization.go" to use structured logging

- api4/user.go
- api4/user_test.go
Cherry pick of #12147 on release-5.16.
- #12147: Fixing autocomplete endpoint for in/out of channels
/cc  @jespino
> Automated cherry pick of #12147

- config/database.go
- config/database_test.go
Cherry pick of #12250 on release-5.16.
- #12250: Fix database source parsing on go 1.12.8
/cc  @hanzei
> Automated cherry pick of #12250

- api4/handlers.go
- einterfaces/metrics.go
- web/handlers.go
Add prometheous metrics for each api handler
> Add prometheous metrics for each api handler

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
Cherry pick of #12083 on release-5.16.
- #12083: Fix config set panic
/cc  @iomodo
> Automated cherry pick of #12083

- plugin/client_rpc.go
Cherry pick of #12249 on release-5.16.
- #12249: simplify FileWillBeUploaded
> Automated cherry pick of #12249

- config/file.go
- config/file_test.go
Cherry pick of #12237 on release-5.16.
- #12237: MM-18344 Honour absolute paths to SAML certificates
/cc  @sbishel
> Automated cherry pick of #12237

- i18n/en.json
Cherry pick of #12238 on release-5.16.
- #12238: MM-17620 - Web: Error when entering an invalid MFA token is
/cc  @sbishel
> Automated cherry pick of #12238

- app/web_hub.go
Converting to structured logging the file app/web_hub.go
Fixes https://github.com/mattermost/mattermost-server/issues/12192
https://mattermost.atlassian.net/browse/MM-18288
> MM-18288 Converting to structured logging the file app/web_hub.go

- app/notification_push.go
Converting to structured logging the file app/notification_push.go
Fixes https://github.com/mattermost/mattermost-server/issues/12114
> Converting to structured logging the file app/notification_push.go

- store/sqlstore/channel_store.go
Refactor "store/sqlstore/channel_store.go" to use structured logging
Fixes https://github.com/mattermost/mattermost-server/issues/12049
> GH-12049 use structured logging

- app/command.go
change the usages of mlog. methods with fmt.Sprintf to proper mlog.Field() calls in file app/command.go.
[MM-18289](https://mattermost.atlassian.net/browse/MM-18289)
Fixes https://github.com/mattermost/mattermost-server/issues/12191
> chore: refactor to use structured logging

- store/layer_generators/main.go
- store/timer_layer.go
Migrating nanoseconds to senconds in the store timer layer
> Migrating nanoseconds to senconds in the store timer layer

- manualtesting/manual_testing.go
Refactor "manualtesting/manual_testing.go" to use structured logging
https://mattermost.atlassian.net/browse/MM-18253
Fixes #12336
> MM-18253 Refactor "manualtesting/manual_testing.go" to use structured logging

- config/database.go
- config/utils.go
- config/utils_test.go
Cherry pick of #12309 on release-5.16.
- #12309: Make config.DatabaseStore.String() more robust
/cc  @hanzei
> Automated cherry pick of #12309

- store/sqlstore/audit_store.go
> seems like copy-paste from line 85 (err)

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190923

- app/diagnostics.go
- app/diagnostics_test.go
- app/server.go
Cherry pick of #12317 on release-5.16.
- #12317: diagnostics_test.go: fix spacing
> Automated cherry pick of #12317

- app/oauth.go
Converting to structured logging the file app/oauth.go
https://mattermost.atlassian.net/browse/MM-18260
> MM-18260 Converting to structured logging the file app/oauth.go

- api4/post.go
- app/auto_posts.go
- app/channel_test.go
- app/command_loadtest.go
- app/file.go
- app/plugin_api.go
- app/post.go
- model/post.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/reaction_store.go
- store/timer_layer.go
This reverts commit b3517eaf2f7ce51898dcdf9130d75197cd0c1fa9.
https://mattermost.atlassian.net/browse/MM-18624
https://github.com/mattermost/mattermost-server/pull/12387
https://github.com/mattermost/mattermost-webapp/pull/3789
https://github.com/mattermost/mattermost-redux/pull/935
> MM-18624: revert fetch threads support

- config/database.go
I resolved a merge conflict incorrectly when submitting [MM-18636](https://mattermost.atlassian.net/browse/MM-18636), and
want to remove the unused code I left behind.
https://mattermost.atlassian.net/browse/MM-18636
> MM-18636: fix wrong merge conflict

- config/database.go
Cherry pick of #12386 on release-5.16.
- #12386: MM-18636: fix wrong merge conflict
> Automated cherry pick of #12386

- app/email.go
- services/mailservice/inbucket.go
- services/mailservice/mail.go
- services/mailservice/mail_test.go
- templates/invite_body.html
Cherry pick of #12328 on release-5.16.
- #12328: Embedding avatar in guest invite emails
/cc  @jespino
> Automated cherry pick of #12328

- config/database_test.go
Update config/database test to use testify 
Fixes https://github.com/mattermost/mattermost-server/issues/12428
> update database test to use testify

- Makefile
Cherry pick of #12402 on release-5.16.
- #12402: Bumped the Jira plugin to v2.2.0
/cc  @levb
> Automated cherry pick of #12402

- cmd/mattermost/commands/server.go
Cherry pick of #12394 on release-5.16.
- #12394: MM-18721: disable SIGPIPE handling
> Automated cherry pick of #12394

- app/user_test.go
Convert app/user_test.go t.Fatal calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12208
> Convert app/user_test.go t.Fatal calls into assert/require calls

- app/post_metadata_test.go
Cherry pick of #12365 on release-5.16.
- #12365: use local httptest server instead of github.com
> Automated cherry pick of #12365

- config/file_test.go
- Update config/file_test to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12429
> update config/file test to use testify

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20190930

- cmd/mattermost/commands/user_test.go
Modify the calls to t.Fatal and the condition checks that led to them, replacing them with calls to the testify require.
[MM-19014](https://mattermost.atlassian.net/browse/MM-19014)
Fixes https://github.com/mattermost/mattermost-server/issues/12409
> MM-19014 Migrate tests from "cmd/mattermost/commands/user_test.go" to use testify

- model/suggest_command_test.go
Convert model/suggest_command_test.go t.Fatal call to assert call
Fixes https://github.com/mattermost/mattermost-server/issues/12546
> Convert model/suggest_command_test.go t.Fatal call to assert call

- Makefile
Cherry pick of #12403 on release-5.16.
- #12403: Bumped Zoom plugin version to 1.1.0
/cc  @levb
> Automated cherry pick of #12403

- model/reaction_test.go
Fixes: https://github.com/mattermost/mattermost-server/issues/12595
> refactor tests in model/reaction_test.go and move to testify tests

- model/access_test.go
Migrate tests from "model/access_test.go" to use testify
Fixes #12548
> [MM-19119] Migrate tests from "model/access_test.go" to use testify

- model/team_search_test.go
Moves testing for `team_search.go` from the standard library to testify.
Fixes https://github.com/mattermost/mattermost-server/issues/MM-19163
Fixes #12593 on Github
> MM-19163 - Refactored team search tests to testify

- model/cluster_message_test.go
This PR converts t.Fatal calls used in cluster_message_test.go into assert/require calls from the testify toolkit.
Fixes https://github.com/mattermost/mattermost-server/issues/12598
> [MM-19158] Migrate to testify in model/cluster_message_test.go

- app/notification.go
- app/notification_test.go
Turns off the email notifications in case of DND status
Fixes https://github.com/mattermost/mattermost-server/issues/12325
> turned off email notification for the status DND

- store/sqlstore/upgrade.go
Cherry pick of #12260 on release-5.16.
- #12260: upgrade db to 5.16
/cc  @cpanato
> Automated cherry pick of #12260

- model/channel_view_test.go
"model/channel_view_test.go" is migrated to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12565
JIRA: https://mattermost.atlassian.net/browse/MM-19132
> MM-19132 Migrate tests from "model/channel_view_test.go" to use testify

- api4/team.go
- api4/team_test.go
- i18n/en.json
Not allowing to use team invite links by guest accounts
[MM-18487](https://mattermost.atlassian.net/browse/MM-18487)
> Not allowing to use team invite links by guest accounts

- Makefile
Cherry pick of #12689 on release-5.16.
- #12689: Bumped the Jira plugin to v2.2.0
/cc  @levb
> Automated cherry pick of #12689

- api4/team.go
- api4/team_test.go
- i18n/en.json
Cherry pick of #12608 on release-5.16.
- #12608: Not allowing to use team invite links by guest accounts
/cc  @jespino
> Automated cherry pick of #12608

- model/status_test.go
**Summary**
change t.Fatal to assert.Equal in model/satatus_test.go
JIRA: [MM-19271](https://mattermost.atlassian.net/browse/MM-19271)
Fixes #12666 
Test Result:
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/mattermost/mattermost-server/model -run ^(TestStatus|TestStatusListToJson|TestStatusListFromJson)$ -v
=== RUN   TestStatus
--- PASS: TestStatus (0.00s)
=== RUN   TestStatusListToJson
--- PASS: TestStatusListToJson (0.00s)
=== RUN   TestStatusListFromJson
--- PASS: TestStatusListFromJson (0.00s)
PASS
ok  	github.com/mattermost/mattermost-server/model	(cached)
Success: Tests passed.
```
> change t.Fatal to assert.Equal in model/status_test.go

- model/team_test.go
Migrate tests from 'model/team_test.go' to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12632
> MM-19238 Migrate tests from 'model/team_test.go' to use testify

- .circleci/config.yml
Cherry pick of #12560 on release-5.16.
- #12560: MM-19050 Testing circle ci fix
/cc  @stylianosrigas
> Automated cherry pick of #12560

- app/plugin.go
- app/plugin_deadlock_test.go
Cherry pick of #12371 on release-5.16.
- #12371: MM-18540 - Demo plugin crashes on server shutdown
> Automated cherry pick of #12371

- model/oauth_test.go
Migrated t.fatal to testify/require.
Fixes: #12589
JIRA: https://mattermost.atlassian.net/browse/MM-19157
> [MM-19157] Migrate tests from "model/oauth_test.go" to use testify

- model/user_test.go
Migrated tests from model/user_test.go to use testify.
Fixes #12673
> GH-12673 : Migrated tests from model/user_test.go to use testify

- api4/team.go
Fixing guest invites acceptance
[MM-19319](https://mattermost.atlassian.net/browse/MM-19319)
> Fixing guest invites acceptance

- api4/team.go
Cherry pick of #12698 on release-5.16.
- #12698: Fixing guest invites acceptance
/cc  @jespino
> Automated cherry pick of #12698

- model/search_params_test.go
Migrate tests from "model/search_params_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12572
> Migrate tests from model/search_params_test.go to use testify

- model/channel_test.go
Convert model/channel_test.go validation calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12594
> Convert model/channel_test.go validation calls into assert/require calls

- store/sqlstore/upgrade.go
Converting to structured logging the file store/sqlstore/upgrade.go
Fixes https://github.com/mattermost/mattermost-server/issues/12055
> Converting to structured logging the file store/sqlstore/upgrade.go

- plugin/health_check.go
Refactor "plugin/health_check.go" to use structured logging
Fixes https://github.com/mattermost/mattermost-server/issues/12725
JIRA ticket.
https://mattermost.atlassian.net/browse/MM-18277
> [MM-18277] Refactor plugin/health_check.go to use structured logging

- .circleci/config.yml
we dont need that anymore, so making more clean
will apply the same for enterprise
> remove -p=8

- cmd/mattermost/commands/sampledata.go
Add an option to generate deactivated users via sampledata.  This is useful like in a case of E2E where hundreds of inactive users are required to test particular bug in listing/showing such inactive status at System Console.
```
./mattermost sampledata -w 4 -u 60 --deactivated-users 200
```
Jira ticket: [MM-18512](https://mattermost.atlassian.net/browse/MM-18512)
> MM-18512 Add option to generate deactivated users via sampledata

- .circleci/config.yml
Cherry pick of #12799 on release-5.16.
- #12799: remove -p=8
/cc  @cpanato
> Automated cherry pick of #12799

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20191014

- services/mfa/mfa_test.go
Migrate tests from `services/mfa/mfa_test.go` to use testify
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-19347)
Fixes https://github.com/mattermost/mattermost-server/issues/12718
> Migrate tests from mfa_test.go to use testify

- store/storetest/session_store.go
Migrate tests from "store/storetest/session_store.go" to use testify
Fixes #12761
> Migrate tests from "store/storetest/session_store.go" to use testify

- store/sqlstore/utils_test.go
This PR migrates tests from 'store/sqlstore/utils_test.go' to use testify.
Fixes https://github.com/mattermost/mattermost-server/issues/12780
> [MM-19456] Migrate tests from 'store/sqlstore/utils_test.go' to use testify

- api4/plugin_test.go
- app/plugin_install.go
Cherry pick of #12687 on release-5.17.
- #12687: MM-18881 - Attempting to configure uninstalled plugins
> Automated cherry pick of #12687

- app/file.go
- app/file_test.go
PR adds proper parsing and validation for old filenames during `Filenames` to `FileInfo` migration.
https://mattermost.atlassian.net/browse/MM-19489
> [MM-19489] Add parsing and validation for old filenames migration

- .circleci/config.yml
- app/server_test.go
- build/Dockerfile.buildenv
- build/Jenkinsfile.branch
- build/Jenkinsfile.pr
Upgrade to use go 1.13 (latest 1.13.3)
> update build image to go 1.13

- api4/channel_test.go
- app/channel.go
Cherry pick of #12527 on release-5.17.
- #12527: MM-18651: no spurious mentions on leaving channels
> Automated cherry pick of #12527

- model/manifest.go
- model/manifest_test.go
Model `HomepageURL` and `SupportURL` for use in listing plugins in the marketplace.
Fixes: https://mattermost.atlassian.net/browse/MM-19477
> MM-19477: model extra manifest data

- app/post_metadata.go
- app/post_metadata_test.go
Cherry pick of #12878 on release-5.17.
- #12878: MM-19574 Don't return metadata for deleted posts
/cc  @hmhealey
> Automated cherry pick of #12878

- model/session_test.go
Migrate tests from "model/session_test.go" to use testify
Fixes #12631
> [GH-12631] Migrate tests from "model/session_test.go" to use testify

- api4/websocket_test.go
Migrate tests from "api4/websocket_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12881
> Migrate tests from "api4/websocket_test.go" to use testify

- app/user.go
- cmd/mattermost/commands/user.go
- i18n/en.json
- store/sqlstore/channel_store.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
Updated code so that when you run `mattermost delete user` it will also permanently delete the user from the GroupMembers table in the database
https://mattermost.atlassian.net/browse/MM-13704
> [MM-13704] Updated CLI "deleter user" to also permanently delete GroupMembers associated to user

- build/Jenkinsfile.branch
Cherry pick of #12903 on release-5.17.
- #12903: use the branch to tag the docker image and also build team
/cc  @cpanato
> Automated cherry pick of #12903

- app/permissions_migrations.go
Cherry pick of #12908 on release-5.17.
- #12908: Unbinding the permission INVITE_GUEST from INVITE_USER
/cc  @jespino
> Automated cherry pick of #12908

- utils/emoji.go
> Conv emoji to testify

- web/handlers.go
Cherry pick of #12880 on release-5.17.
- #12880: Include request_id in HTTP request logs
/cc  @hanzei
> Automated cherry pick of #12880

- api4/preference_test.go
Update `api4/preference_test.go` to use `testify`.
Fixes #12862 
[MM-19623](https://mattermost.atlassian.net/browse/MM-19623)
> preference_test: use testify

- api4/job_test.go
Migrates tests from "api4/job_test.go" to use testify
Fixes #12887
> Migrate tests from "api4/job_test.go" to use testify

- app/diagnostics.go
- config/client.go
- model/config.go
Cherry pick of #12907 on release-5.17.
- #12907: add option to render latex
> Automated cherry pick of #12907

- .circleci/config.yml
Fix npm ci step with new mattermost-redux
https://github.com/mattermost/mattermost-webapp/pull/4064
> Fix npm ci step with new mattermost-redux

- store/storetest/terms_of_service_store.go
Migrate tests from "store/storetest/terms_of_service_store.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12763
> Migrate tests from "store/storetest/terms_of_service_store.go" to use testify

- api4/file_test.go
- api4/system.go
- api4/user_test.go
- app/notification_push.go
- app/post_metadata.go
- app/post_metadata_test.go
- app/server.go
- app/web_conn.go
- cmd/mattermost/commands/command.go
- mlog/human/parser.go
- model/config.go
- model/slack_attachment.go
- plugin/helpers_kv_test.go
- store/localcachelayer/role_layer.go
- store/sqlstore/user_store.go
- testlib/resources.go
This PR simplifies parts of the codebase. There where found via [`gosimple`](https://github.com/dominikh/go-tools/tree/master/simple). Fixing this issue is part of the afford to fix all problems found by `golangci-lint`.
Follow up on https://github.com/mattermost/mattermost-server/pull/12909
> Run gosimple against codebase

- api4/webhook_test.go
Summary
Convert api4/webhook_test.go t.Fatal calls into assert/require calls
Issue Link
Fixes #12865
> Convert api4/webhook_test.go t.Fatal calls into require/assert calls

- store/storetest/oauth_store.go
Migrate tests from store/storetest/oauth_store.go to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12762
> Migrate tests from store/storetest/oauth_store.go to use testify

- app/bot_test.go
- model/bot.go
Cherry pick of #12905 on release-5.17.
- #12905: MM-19310 - Wrong validation message when Bot name ends in
> Automated cherry pick of #12905

- app/bot.go
- app/bot_test.go
Cherry pick of #12373 on release-5.17.
- #12373: When patching a bot, perform these two additional steps:
/cc  @jfrerich
> Automated cherry pick of #12373

- Makefile
Fix a spelling mistake in https://github.com/mattermost/mattermost-server/pull/12934
> Fix golangci-lint target

- api4/system.go
- api4/system_test.go
This pull request enhances the log statement used as part of the logs endpoint to ensure that admins are aware that the message originates from a client.
https://mattermost.atlassian.net/browse/CR-458
> [CR-458] Enhance Logs Endpoint Message

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20191104

- Makefile
- scripts/prereq-check.sh
For details check #13014 
None
> Change the minor version of go to 1.13

- model/manifest.go
Illustrate `homepage_url`, `support_url`, and `icon_path` in the GoDoc for model.Manifest.
Relates-to: https://mattermost.atlassian.net/browse/MM-19477
> MM-19477: update manifest documentation example

- store/sqlstore/supplier.go
- store/sqlstore/upgrade.go
- store/sqlstore/upgrade_test.go
Making private the sqlstore upgrade functions because nobody needs to call them from the outside
> Making private the sqlstore upgrade functions because nobody needs to call them from the outside

- config/database_test.go
- config/file_test.go
- config/memory_test.go
- config/watcher_test.go
- utils/testutils/testutils.go
Use the util function introduced in 8ab0e80b7799ba9fbcc90bbc62a609961143c679 to refactor more instances of such code.
> Refactor more code to use testutils.WasCalled

- i18n/de.json
- i18n/ja.json
- i18n/ko.json
- i18n/zh-TW.json
> translations PR 20191111

- model/version.go
- store/sqlstore/upgrade.go
Upgrade DB to 5.17 in the release branch
/cc @amyblais
> upgrade db to 5.17

- model/marketplace_plugin.go
Include `ReleaseNotesURL` in the `BaseMarketplacePlugin` to relay from the marketplace.
https://mattermost.atlassian.net/browse/MM-19603
> MM-19630: marketplace: model ReleaseNotesURL

- model/config.go
Add new prepackage configuration
Fixes https://mattermost.atlassian.net/browse/MM-19609
> MM-19609 - Add new prepackage configuration settings

- api4/system.go
- app/notification_push.go
- app/notification_push_test.go
- i18n/en.json
A couple of fixes:
* Return after the ack response is written
* Add the default message to ID loaded push notifications
TODO: localize default message
https://mattermost.atlassian.net/browse/MM-16232
> [MM-16232] Return after writing response and add default message

- Makefile
With 1.13, it is enabled by default on repos where a go.mod file is present.
> Remove GO111MODULE variable

- build/release.mk
This PR will add signatures to the prepackaged plugins
Fixes https://mattermost.atlassian.net/browse/MM-19615
> [MM-19615] Signatures for prepackaged plugins

- api4/plugin_test.go
- app/plugin.go
- app/plugin_install.go
- app/plugin_install_test.go
- app/plugin_test.go
- i18n/en.json
- model/marketplace_plugin.go
Cherry pick of #13086 on release-5.18.
- #13086: MM-17549: use StatusNotFound when deleting plugin
> Automated cherry pick of #13086

- api4/system.go
- app/notification.go
- app/notification_email.go
- app/notification_push.go
- app/notification_push_test.go
- app/notification_test.go
- i18n/en.json
- model/config.go
- model/push_notification.go
Cherry pick of #13137 on release-5.18.
- #13137: Update BuildPushNotificationMessage (#12974)
/cc  @migbot
> Automated cherry pick of #13137

- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/ja.json
- i18n/ko.json
- i18n/nl.json
- i18n/pl.json
- i18n/pt-BR.json
- i18n/ro.json
- i18n/ru.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh-CN.json
- i18n/zh-TW.json
> translations PR 20191118

- api4/system.go
- app/app.go
- app/enterprise.go
- app/notification.go
- app/notification_email.go
- app/notification_push.go
- app/notification_push_test.go
- app/notification_test.go
- app/options.go
- app/server.go
- einterfaces/notification.go
- i18n/en.json
- model/license.go
- model/license_test.go
- model/push_notification.go
- utils/license.go
Moves ID Loaded Push Notifications under E20
https://mattermost.atlassian.net/browse/MM-20347
> MM-20347  Move ID Loaded Push Notifications to E20

- api4/system.go
- app/app.go
- app/enterprise.go
- app/notification.go
- app/notification_email.go
- app/notification_push.go
- app/notification_push_test.go
- app/notification_test.go
- app/options.go
- app/server.go
- einterfaces/notification.go
- i18n/en.json
- model/license.go
- model/license_test.go
- model/push_notification.go
- utils/license.go
Cherry pick of #13185 on release-5.18.
- #13185: Move ID Loaded Push Notifications to E20
/cc  @enahum
> Automated cherry pick of #13185

- cmd/mattermost/commands/plugin.go
Cherry pick of #13065 on release-5.18.
- #13065: Fix naming for CLI plugin list command
/cc  @hanzei
> Automated cherry pick of #13065

- Makefile
Use `$(GO)` consistently in the Makefile
> Use predefined go command consistently

- app/analytics.go
- app/diagnostics.go
- app/helper_test.go
- app/import_functions_test.go
- app/security_update_check.go
- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
- store/timer_layer.go
Cherry pick of #13181 on release-5.18.
- #13181: MM-20305: Adds ability to choose whether deleted teams are
/cc  @mkraft
> Automated cherry pick of #13181
