- app/post.go
- app/post_test.go
Delete FileInfos when deleting the post they belong to.
https://mattermost.atlassian.net/browse/MM-12818
> MM-12818: Delete FileInfos when deleting the post they belong to.

- app/channel_test.go
- app/plugin_api.go
- app/team_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This changes the parameter of two plugin API methods to use `page, perPage` instead of `offset, limit`.
Both API methods just call the respective method so the actual code for this ticket is very small.
Because both `GetPublicChannelsForTeam()` and `GetTeamMembers()` didn't had unit tests until now, I went ahead and added them. I _could_ add tests to `app/plugin_api_test.go` but these tests would mostly be a copy of the tests I added to `team_test.go` and `channel_test.go`.
I would like replace `*model.ChannelList` in the return value of `GetPublicChannelsForTeam()` with `[]*model.Channel`. This would make it easier to plugin developer to work with the method as they don't have to figure out what exactly `model.ChannelList` is. ~~Note that this would hard break old plugins. Which might be …
> [MM-12476] Consistent paging arguments limit/offset vs page/perPage for plugin API

- app/export.go
- app/export_converters.go
- app/export_test.go
- cmd/mattermost/commands/export.go
- model/emoji.go
Added capability to bulk export custom emojis.
Whenever the command to bulk export custom emoji's is entered, a directory named `exported_emoji` is created in the same location of the file specified in the bulk export command. And the emojis from `data/emoji` directory are copied into this new directory.
https://github.com/mattermost/mattermost-server/issues/9542
> MM-12463 : Added capability to bulk export custom emojis

- app/command.go
- model/command_response.go
- model/command_response_test.go
Allows a slash command response to send multiple posts back to the UI.
[Github Ticket](https://github.com/mattermost/mattermost-server/issues/8511)
[JIRA Ticket](https://mattermost.atlassian.net/browse/MM-9938)
Originally reported at: https://forum.mattermost.org/t/mention-or-push-message-to-another-channel-from-a-slash-command/4393
- I have a draft on my fork [here](https://github.com/mickmister/mattermost-developer-documentation/commit/0cbd1d7280581d4cd64e5ee865f5b57e42479a85)
The original proposed structure is
```
[
{
"text": "message 1",
},
{
"text": "message 2"
},
{
"text": "message 3"
}
]
```
We have to keep the integrity of the current API, while supporting the new functionality of sending multiple messages. As far as the code processing this response is concerned, it has to hold …
> [MM-9938] Add support for multiple responses from a slash command

- app/channel.go
- app/diagnostics.go
- app/file.go
- app/login.go
- app/plugin.go
- app/plugin_api_test.go
- app/plugin_commands.go
- app/plugin_hooks_test.go
- app/plugin_install.go
- app/plugin_requests.go
- app/plugin_statuses.go
- app/plugin_test.go
- app/post.go
- app/server.go
- app/team.go
Shutting down the app could race with a goroutine that uses the plugins environment, since we shut down the plugins first before cleaning up goroutines. Avoid this by always accessing the plugins environment through a lock, and relying on Go's cleanup semantics to ensure the plugin environment is still valid (though not necessarily hosting any plugins!).
Most of the code changes:
```go
if a.PluginsReady()
a.Srv.Go(func() {
// a.Srv.Plugins might be nil by this point!
a.Srv.Plugins.DoSomething();
// ...
}
}
```
to:
```go
if pluginsEnvironment := a.GetPluginsEnvironment(); pluginsEnvironment != nil {
a.Srv.Go(func() {
// pluginsEnvironment won't be nil, but it might be shutting down. 
// It manages it's own concurrency concerns at that point.
pluginsEnvironment.DoSomething();
// ...
}
} …
```
> MM-12974: guard app plugins with mutex

- model/slack_attachment.go
Now, when returning CommandResponse that has post.type, it's overridden by `slack_attachment` anyway. So we can't replace it by custom post type of webapp plugin.
With this fix, if post.type is already set, it will not overwrite the type.
**Caution**: This fix has tiny breaking changes. If there are integrations that create posts with attachments props and post.type (not `slack_attachments`), it will not create attachment post successfully. 
N/A
(Refs: https://pre-release.mattermost.com/core/pl/3oex4ng45brpfx3gfkr1o6oy8c)
N/A
> Block to override post_type if already set

- api4/apitestlib.go
- app/apptestlib.go
- app/web_conn.go
- app/web_hub.go
- app/web_hub_test.go
Fix a variety of shutdown races:
* avoid trying to send to a webhub that has shutdown
* handle a webconn race that fails to notify all callers of shutdown
* panic if app shutdown takes >30 seconds, to avoid waiting 30 *minutes* to discover deadlock
N/A
> Webhub race condition

- model/client4.go
Migrate to idiomatic error handling in the file `model/client4.go` in the mattermost-server repo.
Fixes #9846
> GH-9846: Migrate to idiomatic error handling in model/client4.go

- app/channel.go
- app/channel_test.go
Fix moving a channel with no members.
https://mattermost.atlassian.net/browse/MM-12957
> MM-12957: Fix moving a channel with no members.

- app/post_metadata.go
- model/post.go
As I explained [here](https://github.com/mattermost/mattermost-server/pull/9786#discussion_r235758827), it'd be nice to deprecate these to remove the two way data linkage that's hard to track, but we use them to simplify PreparePostForClient, so they'll stay for now.
> Remove comments about deprecating FileIds and HasReactions

- api4/post.go
- app/notification.go
- app/post.go
- app/post_metadata.go
- app/post_metadata_test.go
When I merged post-metadata into master, I did it with a version of post-metadata that was missing this PR: https://github.com/mattermost/mattermost-server/pull/9868
https://mattermost.atlassian.net/browse/MM-11434
> MM-11434 Only call PreparePostForClient once when creating a post

- app/post_metadata.go
- app/post_metadata_test.go
- config/default.json
- model/config.go
- utils/config.go
This is a temporary setting to disable post metadata in case it causes major performance concerns for larger deployments. We're planning on removing it in the next feature release.
https://mattermost.atlassian.net/browse/MM-13015
> MM-13015 Add safety valve setting to disable post metadata

- model/integration_action.go
- model/integration_action_test.go
This PR adds To/FromJson methods to `SubmitDialogResponse` and `SubmitDialogRequest`. This is useful for plugins and other integrations.
NA
> Add helper methods for SubmitDialog structs

- app/app.go
- app/migrations.go
App level migrations were in the 'app/app.go' file, which is very
generic. I think makes a lot of sense to have this in other file and let
it grow independently.
I haven't changed any code, I only moved it from one place to another
> Moving app level migrations to its own file

- api4/post.go
- app/post.go
- app/post_metadata.go
`app.GetFileInfosForPost` (which is now called `app.GetFileInfosForPostWithMigration`) tries to get the post from the database to run some outdated migration logic. Since we already have the post when we're getting metadata for it, we can skip that extra database hit
> Skip getting the post again when getting file metadata for a post

- app/post_metadata_test.go
- model/post.go
This change makes it so that a server with metadata disabled returns posts exactly as a pre-metadata server would.
https://mattermost.atlassian.net/browse/MM-13015
> MM-13015 Remove metadata field from post when metadata is disabled

- app/diagnostics.go
- app/post_metadata.go
- app/post_metadata_test.go
- config/default.json
- model/config.go
As discussed, the performance issues are big enough that we want to turn this off by default for 5.6
https://mattermost.atlassian.net/browse/MM-13208
> MM-13208 Rename DisablePostMetadata setting to EnablePostMetadata and turn off by default

- app/opengraph.go
- app/opengraph_test.go
Properly unescape OpenGraph metadata containing HTML entities.
https://mattermost.atlassian.net/browse/MM-12648
> MM-12648: Properly unescape OpenGraph metadata containing HTML entities.

- app/post_metadata.go
- app/post_metadata_test.go
This turns out to support a rather contrived case since relative links are prevented from accessing dimensions of local images due to the default security settings, but I don't think it hurts to still include this code.
https://mattermost.atlassian.net/browse/MM-12009
> MM-12009 Resolve relative links in posts as the web app does

- app/auto_responder.go
- app/notification.go
- app/notification_push.go
- app/team.go
- model/user.go
We have constants for (most) of the notify props keys. We should use
them consistently, instead of sometimes and other times having strings
scattered around the place.
> Use constants for NotifyProps keys.

- api4/apitestlib.go
- api4/channel.go
- api4/post_test.go
- app/apptestlib.go
- app/channel.go
- app/channel_test.go
- app/command_msg.go
- app/command_mute_test.go
- app/import_functions_test.go
- app/notification_test.go
- app/plugin_api.go
- app/plugin_api_test.go
- app/post.go
- app/webhook.go
- migrations/migrationstestlib.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- Refactor Get/Create Direct Channel into one function
- removed the CreateDirectChannel plugin api and use the GetDirectChannel plugin api (also update the comments)
> Refactor Get/Create Direct Channel into one function

- app/plugin_api.go
- app/plugin_api_test.go
- app/plugin_key_value_store.go
- app/plugin_test.go
I ran across an instance where `page, perPage` was being passed down to the store but being interpreted as `offset, limit`. Fixing these in place, but it would be nice to converge on `offset, limit` even in the store to make this easier to verify during code review.
For reference in reviewing this, the plugin store accepts `offset, limit`:
https://github.com/mattermost/mattermost-server/blob/da265fbaf78a02333c00eec167540ac2119b2b89/store/sqlstore/plugin_store.go#L121
And the app `GetUsersInTeam` accepts `offset, limit` directly:
https://github.com/mattermost/mattermost-server/blob/da265fbaf78a02333c00eec167540ac2119b2b89/app/user.go#L411
None.
> fix two page, perPage -> offset, limit mistranslations

- app/enterprise.go
Initialization of Cluster must happen after its dependencies.
Along with EE pr fixes master issue on clustered servers: https://github.com/mattermost/enterprise/pull/370
> Fixing enterprise init order.

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `SearchUsers(search *UserSearch)` method to plugin API.
Fixes [#9639](https://github.com/mattermost/mattermost-server/issues/9639)
> [GH-9639] Add plugin API for SearchUsers method

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
Validating config before save it on `mattermost config set` command
> Validating config on set command

- web/handlers.go
Updating CSP header to specify script-src as well. This was already specified in the HTML of the webapp.
`frame-ancestors 'self'` is not specified in the HTML of the webapp because it is not supported there (you must specify it using the header)
Webapp Changes: https://github.com/mattermost/mattermost-webapp/pull/2102
> Updating content security policy.

- app/app.go
- app/channel.go
- app/file.go
- app/login.go
- app/plugin_commands.go
- app/plugin_context.go
- app/plugin_hooks_test.go
- app/plugin_requests.go
- app/post.go
- app/team.go
- plugin/context.go
- web/context.go
- web/handlers.go
- Adds the ability for plugins to receive the context of the request their hooks are executed in.
- Adds some fields to the plugin context:
- ReqeustId
- IpAddress
- AcceptLanguage
- UserAgent
We didn't discuss what exactly would be in the context. So I just added everything I have heard up to this point. Further suggestions can be incorporated into this PR or if difficult, a separate one.
> MM-12855 Plugin Context

- cmd/mattermost/commands/channel_test.go
- cmd/mattermost/commands/command_test.go
- cmd/mattermost/commands/config_test.go
Using `RunCommand` obscures the error if, indeed, the assertion fails because the cmd fails to run.
None.
> leverage CheckCommand when a cmd should pass

- app/diagnostics.go
- model/config.go
- model/config_test.go
- utils/config.go
Converts type from `*[]string` to `[]string`. 
Not sure why this fixes this panic...
```
goroutine 1 [running]:
github.com/mattermost/mattermost-server/utils.GenerateClientConfig(0xc001ff6000, 0xc002450ba0, 0x1a, 0x0, 0x0)
/home/christopher/go/src/github.com/mattermost/mattermost-server/utils/config.go:628 +0x2daa
github.com/mattermost/mattermost-server/app.(*App).regenerateClientConfig(0xc00105a700)
/home/christopher/go/src/github.com/mattermost/mattermost-server/app/config.go:283 +0x148
github.com/mattermost/mattermost-server/app.(*App).configOrLicenseListener(0xc00105a700)
/home/christopher/go/src/github.com/mattermost/mattermost-server/app/app.go:67 +0x2b
github.com/mattermost/mattermost-server/app.(*Server).RunOldAppInitalization.func1(0xc001d88000, 0xc001ff6000) …
```
> Fix panic with customurlschemes

- store/sqlstore/store.go
- store/sqlstore/supplier.go
- store/sqlstore/upgrade.go
Upgrading from `v5.0` to `master` produced a different schema than running a fresh install from `master`. Except in one case, this is entirely the result of a mismatch between the hand-written migration and the underlying gorp library.
Filed https://mattermost.atlassian.net/browse/MM-13341 to track the work required to automate these checks going forward and prevent future mismatches.
https://mattermost.atlassian.net/browse/MM-12378
> MM-12378: synchronize migrations with actual schema

- app/user.go
We were trying to set a *model.AppError to an error type and that was causing the nil check to pass when it should have failed.
https://mattermost.atlassian.net/browse/MM-13371
> MM-13371 Fix error checking when setting profile image

- store/sqlstore/supplier.go
- store/storetest/settings.go
This matches the default root password set when the database is created by `make start-docker`
> Update default MySQL password for unit tests

- app/command.go
- app/command_test.go
- i18n/en.json
- model/command_response.go
- model/command_response_test.go
This allows a slash command's response to decide which channel the response post will be sent to, rather than defaulting to the channel that the command was used in.
Jira ticket: https://mattermost.atlassian.net/browse/MM-9937
GitHub ticket: https://github.com/mattermost/mattermost-server/issues/8512
I have docs update here: https://github.com/mattermost/mattermost-developer-documentation/pull/190
There may be a change (like adding a config for overriding the channel to post to)
Permissions:
There was some discussion on permissions on this PR https://github.com/mattermost/mattermost-server/pull/8678 pertaining to a similar situation with slash commands and posting to a different channel. If this permission check is appropriate, which user needs to have posting privileges, the slash …
> [MM-9937] Add support for sending a message to a different channel than where the slash command was issued from

- app/export.go
- app/export_converters.go
- app/export_test.go
- model/user.go
Fixes for bulk export problems
- the favorite detection may fail if the user preferes aren't set.
- The reactions where exported using the UserId instead of the Username as is expected
- The mobile notify props are the constants "PUSH", no the new added "MOBILE"
[MM-13220](https://mattermost.atlassian.net/browse/MM-13220)
> MM-13220: Fixes for bulk export problems

- plugin/client_rpc.go
This was causing the server's plugin RPC client to error out with:
```
{"level":"error","ts":1544618340.2658787,"caller":"log/log.go:301","msg":"rpc: gob error encoding body: gob: type not registered for interface: opengraph.OpenGraph","source":"stdlog"}
```
> Register opengraph struct with gob for plugins

- app/post_metadata.go
This will be fixed when the image proxy is added, but this fix is is needed for 5.7
https://mattermost.atlassian.net/browse/MM-13238
> MM-13238 Fix link cache being cleared too often with image proxy

- api4/plugin.go
- api4/plugin_test.go
- model/client4.go
Added support for the `force` flag in the `updatePlugin` http API (as a multipart form value) to enable plugin replacement.
https://mattermost.atlassian.net/browse/MM-8662
https://github.com/mattermost/mattermost-redux/pull/732
https://github.com/mattermost/mattermost-api-reference/pull/409
https://github.com/mattermost/mattermost-webapp/pull/2147
> MM-8662: Added `force` flag to uploadPlugin http API

- utils/config.go
This is needed so that plugins load for users not logged in. It was caused by a new feature moving out of experimental that returned a limited client config to non-logged in users.
Only needs 2 of 3 reviews, whoever sees it first
> Include PluginsEnabled in limited client config

- api4/integration_action.go
- api4/integration_action_test.go
Require at least one element in interactive dialogs. Re-enabled the test and removed the flaky websocket part of it.
> Require at least one element in interactive dialogs

- app/channel.go
Follow up on #10000
The changes will let the CI fail. I'm not sure if the tests are wrong and relied on an bug or my changes are bad. They problem is that it's not clear to me if https://github.com/mattermost/mattermost-server/blob/6dbd7bbef2b5d31b146a120ac562d1989026d12a/app/channel.go#L537 should return an error from `PostUpdateChannelDisplayNameMessage()`, `PostUpdateChannelHeaderMessage()` and `PostUpdateChannelPurposeMessage()`. I would like to hear your thoughts on this. @jespino @grundleborg
> Fix shadowed variables in app package: Part 4

- api4/user.go
- api4/user_test.go
- app/user.go
- i18n/en.json
Instead of just sanitizing the user's email address when using this route, we're going to completely prevent the user from using it if they can't see emails because of privacy settings.
https://mattermost.atlassian.net/browse/MM-13512
- Added API documentation (https://github.com/mattermost/mattermost-api-reference/pull/413)
- Includes text changes and localization file ([.../i18n/en.json](https://github.com/mattermost/mattermost-server/blob/master/i18n/en.json)) updates
> MM-13512 Prevent getting a user by email based on privacy settings

- model/user.go
- model/user_test.go
Without this validation, a user could set their locale to something invalid which would prevent them from using the web app because it would crash whenever it tries calling `localeCompare` on two strings.
https://mattermost.atlassian.net/browse/MM-13526
> MM-13526 Add validation when setting a user's Locale field

- app/oauth.go
Since OAuth has a different login flow than normal logins, currently the login hooks weren't trigger. This PR fixes this situation.
https://mattermost.atlassian.net/projects/MM/issues/MM-13610
> [MM-13610] Trigger Login Hooks with OAuth

- api4/channel.go
- api4/channel_test.go
Fixes a bug where the server was rejecting viewing no channel represented by "". This happens when the browser loses focus.
> MM-13492 Allow empty channel in /channels/view

- utils/config.go
The client needs this setting as it is logging in, before it requests the full client config.
https://mattermost.atlassian.net/browse/MM-13647
> MM-13647 Move MFA enforcement setting into limited client config

- app/web_hub.go
The websocket hub, on stopping, closes all associated websocket connections, and each connection
in turn tries to unregister itself with the hub, but this naturally creates a deadlock.
This PR reverts the line commented (incorretly...) at
https://github.com/mattermost/mattermost-server/pull/9863/files#r235583929.
https://mattermost.atlassian.net/browse/MM-13678
> MM-13678: fix web hub deadlock

- app/channel.go
- app/command_mute_test.go
- app/export_test.go
While iterating on the bots feature branch, I ran into some spurious unit test failures that I've fixed below. As discussed in https://community-daily.mattermost.com/core/pl/px9p8s3dzbg1pf3ddrm5cr36uw, this also makes `ToggleMuteChannel` wait for the database to be updated.
N/A
> Fix various unit tests

- app/command.go
- app/command_test.go
- i18n/en.json
This fixes the issue of errors being swallowed in the `HandleCommandResponse` method, and underlying methods within, namely `CreateCommandPost`.
Github Ticket: https://github.com/mattermost/mattermost-server/issues/9862
Jira Ticket: https://mattermost.atlassian.net/browse/MM-13061
It is still under discussion in this PR's comments how these errors should be handled.
---
Testing these code paths is covered in https://github.com/mattermost/mattermost-server/pull/9878
> [MM-13061] Improve error handling of slash command responses

- app/command.go
- app/command_test.go
- app/integration_action.go
- app/notification_push.go
- app/oauth.go
- app/opengraph.go
- app/plugin_commands.go
- app/post_metadata.go
- app/security_update_check.go
- app/server.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/outgoing_webhook.go
- model/outgoing_webhook_test.go
- services/httpservice/client.go
- services/httpservice/client_test.go
- services/httpservice/httpservice.go
It may be easier to review this PR if you look at the individual commits since it accomplishes two main things:
1. I removed the `consumeAndClose` function used throughout the app layer since it seems like you don't need to read from a TCP request's body any more to have the connection reused
2. I did some refactoring of the outgoing webhook and slash command code so that I add some tests for that code
https://mattermost.atlassian.net/browse/MM-13606
- Touches critical sections of the codebase (auth, upgrade, etc.)
> MM-13606 Remove consumeAndClose and clean up integration response handling

- app/command.go
- app/command_test.go
- app/http_service_test.go
- app/integration_action.go
- app/notification_push.go
- app/oauth.go
- app/opengraph.go
- app/plugin_commands.go
- app/post_metadata.go
- app/security_update_check.go
- app/server.go
- app/webhook.go
- app/webhook_test.go
- i18n/en.json
- model/outgoing_webhook.go
- model/outgoing_webhook_test.go
- services/httpservice/client_test.go
- services/httpservice/httpservice.go
This is for backporting https://github.com/mattermost/mattermost-server/pull/10066 to 5.7 since there was some refactoring done on master that didn't exist here. As such, I'll also likely base any other backporting off of this version rather than the original PR. The notable conflicts were:
1. Some unrelated unit tests had to be removed since they didn't exist in 5.7
2. Some refactoring of error handling in app/oauth.go caused conflicts. I just overwrote with the newer version
3. Some of the session-scoped App changes happened in the same place in app/server.go where consumeAndClose was so those conflcited
4. I had to remove some changes to the HTTPService and comment out the timeout related tests I added since that functionality didn't exist in 5.7's version of that code. …
> MM-13606 Remove consumeAndClose and clean up integration response handling (5.7)

- app/plugin.go
- app/plugin_commands_test.go
If a plugin is disabled we should unregister the slash commands associated with it. Otherwise they appear in autocomplete and throw errors on execution.
> MM-13599 Unregistering plugin commands on disabling of plugin.

- api4/user.go
- app/channel.go
- app/command_loadtest.go
- app/plugin_api.go
- app/user.go
- model/user_get.go
- model/user_search.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Implement the role and inactive filters as part of the users search api
```
POST /users/search
```
and 
```
GET /users
```
For the get api the filter has been added just to support the getAllUsers and GetUsersInTeam. 
This is intended to validate the approach in the smaller scale and then propagate it to all the code branchings in `get /users` like in channel, in team with sorting etc
Also the permission `User with Access Token Permission` is ignored for this iteration. As discussed with @jasonblais  we will do this whole ticket in 2 iterations for easy delivery.
https://github.com/mattermost/mattermost-server/issues/7494
> [GH-7494] Added the role to the user search filter

- api4/user.go
- app/login.go
- app/login_test.go
Fix typo: (*App).CheckForClienSideCert to (*App).CheckForClientSideCert
N/A
> Fix typo: (*App).CheckForClienSideCert to (*App).CheckForClientSideCert

- utils/config.go
- utils/config_test.go
This fixes a race condition client-side that fails to connect to websockets during MFA enforcement since the necessary config data isn't fetched. There are no security concerns in exposing this data to non-authenticated users, though we'd like to revisit this to tighten it down later: https://mattermost.atlassian.net/browse/MM-13785.
https://mattermost.atlassian.net/browse/MM-13726
> MM-13276: expose Websocket(URL|(Secure)Port) in limited client config

- app/cluster.go
- app/enterprise.go
- app/options.go
- app/server.go
- app/server_app_adapters.go
- cmd/mattermost/commands/server.go
Enterprise PR: https://github.com/mattermost/enterprise/pull/384
To prevent a problem where the embedded app inside the cluster struct was a fake app that did not have the cluster ID, this pr moves the enterprise cluster code to using the Server struct directly instead of though a fake app.
> MM-13560 Migrate cluster to use Server struct directly.

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Add SearchTeams in plugin/api,
[10100](https://github.com/mattermost/mattermost-server/issues/10100)
> [MM-13750] Add ability to search teams to plugin API

- i18n/en.json
Fix extra 's' in "systems administrator". Fixed in all cases, not just the one outlined in ticket.
Cross-checked that these strings aren't included in other files, so only fixing in en.json is sufficient.
https://mattermost.atlassian.net/browse/MM-13641
> MM-13641 Fix extra 's' in "systems administrator"

- api4/file_test.go
- app/import_functions.go
- app/post.go
- app/post_test.go
- app/slackimport.go
- model/post.go
- store/sqlstore/file_info_store.go
- store/store.go
- store/storetest/file_info_store.go
- store/storetest/mocks/FileInfoStore.go
This can cause some weird behaviour in the UI, especially because the files are only partly attached (the post thinks it has files because `post.FileIds` is set, but the files are still attached to their original post because `file.PostId` is the original value).
To prevent this, we now track whether we were able to set the file's `PostId` when creating the post. If we couldn't, we have some extra logic to go back and set `post.FileIds` to match what was actually attached.
https://mattermost.atlassian.net/browse/MM-13718
> MM-13718 Prevent files from being attached to multiple posts

- model/manifest.go
This PR allows plugin to include arbitrary data in the manifest. This data can be used by other plugin. My use case is the update plugin (https://github.com/hanzei/plugin-update/).
See https://github.com/hanzei/mattermost-plugin-sample/blob/master/plugin.json for an example how this looks like.
1/5 on the naming.
> Add props to plugin manifest

- model/slack_attachment.go
- model/slack_compatibility.go
- model/slack_compatibility_test.go
Some slack integrations encode bool fields as `"true"`/`"false"`, which was previously unsupported in mattermost due to how `encoding/json` works. This commit adds an aliased type for bool that implements `json.Unmarshaler` to maintain compatibility with Slack.
I've tested these changes locally (after fighting with `mattermost/mattermost-webapp`) and the example in #10108 now functions as expected.
Fixes GH-10108
https://mattermost.atlassian.net/browse/MM-13826
> MM-13826 Webhooks: Allow "true"/"false" for bool values in payload body

- app/analytics.go
- app/channel.go
- app/import_functions.go
- app/plugin_install.go
This PR fixes shadowed variables in some files of the `app` package. The issues where found with `go tool vet -shadow ./app/`. This PR is mostly for paying technical debts.
This PR is part of a small campaign to remove all shadowed variables in `app`.
If this kind of PR is appreciated, I would be happy to do this code improvements in other packages.
> Fix shadowed variables in app package: Part 1 of 3

- model/slack_attachment.go
- model/slack_attachment_test.go
This PR fixes a panic in `ParseSlackAttachment` if it got called with `nil` as a element of `attachments []*SlackAttachment`. The method now skips every `nil` passed to it.
I would also like to change the method so it would do nothing if you can it with `[]*SlackAttachment{}`. See the first test case https://github.com/mattermost/mattermost-server/blob/6f8f3b401d45133f84c84d6605ef047c0581ad2b/model/slack_attachment_test.go#L10-L23. But since this technical a breaking change, I thought it would be our of scope.
Ref https://github.com/mattermost/mattermost-plugin-jira/pull/19
> Fix panicing of ParseSlackAttachment for nil in attachments list

- cmd/mattermost/commands/webhook.go
I was creating some scripts using the CLI and notice that some commands do not output some information that we might need as input for others commands.
This PR adds some outputs when using the CLI to create webhooks
N/A
> add output when creating webhooks with the CLI

- cmd/mattermost/commands/channel.go
I was creating some scripts using the CLI and notice that some commands do not output some information that we might need as input for others commands.
This PR adds some outputs when using the CLI to create a channel
N/A
> add output when creating channel using cli

- api4/post.go
This is a second patch of https://github.com/mattermost/mattermost-server/pull/10135, which sorts the modified `PostList` again by the creation date, avoiding that the flagged post list is rendered with random order. 
https://mattermost.atlassian.net/browse/MM-13820
> [MM-13820] Sort modified PostList in flags endpoint to return the correct order

- build/Jenkinsfile.pr
Adding timeout for Jenkins pipeline to abort jobs that run for more than 2 hours.
This weekend on PR was running for more than 7 hours and did not get killed.
Adding this timeout is also a good practice to make Jenkins abort jobs running for a long time this save machine resource and avoid build queue get long.
Our build is running in mean for 30 min all the steps adding a 2-hour timeout is enough
NA
> Add timeout for jenkins pipeline

- model/manifest.go
This PR migrates the example plugin manifest to JSON.
This is how https://developers.mattermost.com/extend/plugins/manifest-reference/ would look like after this got merged.
Ref https://github.com/mattermost/mattermost-server/issues/10173
> MM-13852 Migrate example manifest to JSON

- app/license.go
This fix is only trying to restart the workers and the schedulers if the
workers and the schedulers are already initialized. If not, the normal startup
should start them properly
This only happens if you have the license file in the `config/mattermost.mattermost-license`.
[MM-13873](https://mattermost.atlassian.net/browse/MM-13873)
> MM-13873: Fix race condition on filesystem licence load

- app/plugin_hooks_test.go
- app/user.go
- plugin/client_rpc_generated.go
- plugin/hooks.go
- plugin/plugintest/hooks.go
Added a UserWasCreated(c *plugin.Context, user *model.User) hook for server-side plugins.
[Jira ticket](https://mattermost.atlassian.net/browse/MM-13851) | Fixes [GitHub Issue #10174](https://github.com/mattermost/mattermost-server/issues/10174)
> MM-13851 Added a UserWasCreated hook for server-side plugins

- cmd/mattermost/commands/webhook.go
- cmd/mattermost/commands/webhook_test.go
Added support to show webhook data based on webhookId
Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement webhook show command in the CLI.
Allow seeing the webhook detailed information.
Example: `webhook show w16zb5tu3n1zkqo18goqry1je`
[MM-12375](https://mattermost.atlassian.net/browse/MM-12375)
#9562
> MM-12375 added webhook show command

- app/diagnostics.go
- app/post_metadata.go
- app/post_metadata_test.go
- config/default.json
- model/config.go
This makes it so that errors from the HTTP client instead of our own code are cached properly. This is how I was intending it to work originally, but I didn't cache the response properly when those errors occurred.
It also adds a lower timeout for these requests since those request block the post from being made. I chose 5 seconds pretty arbitrarily based on how long it should reasonably take the server to connect and test the dimensions of a ~20MB image (assuming roughly 40mbps between MM and the remote image server), but I'm willing to take suggestions on it. I also made it configurable in the case that something goes horribly wrong with it. Note that this only applies to slow servers since non-existent URLs and bad content types will return much quicker. …
> MM-13207 Add customizable timeout for link metadata and improve caching of errors

- app/diagnostics.go
Adds telemetry under the activity category for:
- Total Slash Commands
- Total Incoming Webhooks
- Total Outgoing Webhooks
> MM-13543 Adding telemetry for slash commands, and webhook counts.

- api4/user_test.go
- app/diagnostics.go
- app/login.go
- app/plugin_requests.go
- config/default.json
- model/client4.go
- model/config.go
- model/session.go
- web/handlers.go
- web/handlers_test.go
This PR implements CSRF protection tokens for additional hardening compared to the currently used custom header. When the user logs in, an additional cookie is created with the CSRF token contained. The webapp / redux will read that cookie and attach it as a custom header to each non-GET request made. 
Since the same origin policy will limit the access to the non-HTTP cookie for other domains, the value of the CSRF cookie is sent to the server when a CSRF attempt is made, but since it's value is not set accordingly as custom header the request is ignored.
As a deprecation step, the current method is still enabled but a warning will be printed to the system console to allow users to migrate towards the stricter enforcement step by step. While there won't be any issues with the official …
> [MM-10346] CSRF Token Implementation + Tests

- app/diagnostics.go
- app/post_metadata.go
- app/post_metadata_test.go
- app/post_test.go
- config/default.json
- model/config.go
- utils/config.go
Since we're only renaming the setting to apply the new default to existing installations, and the setting itself is supposed to be temporary, so I didn't change the name of the setting on the clients.
https://mattermost.atlassian.net/browse/MM-13917
> MM-13917 Enable post metadata by default

- app/opengraph.go
- app/post_metadata.go
Currently the OpenGraph metadata requests aren't limited in response size, this PR introduces a 50mb limit for responses, which should be sufficient for any scenarios.
https://mattermost.atlassian.net/projects/MM/issues/MM-13889
> [MM-13889] Limit OpenGraph data response size

- app/post_metadata.go
- app/post_metadata_test.go
`getLinkMetadata` returns nil image dimensions with a nil error if the server was able to get metadata for the link, but it was not an image.
https://mattermost.atlassian.net/browse/MM-13932
> MM-13932 Fix image metadata for invalid image links

- app/post_metadata.go
- app/post_metadata_test.go
- services/imageproxy/atmos_camo.go
- services/imageproxy/atmos_camo_test.go
- services/imageproxy/error.go
- services/imageproxy/imageproxy.go
- services/imageproxy/local.go
- services/imageproxy/local_test.go
There's two reasons we can't just hit the image proxy API directly when getting these dimensions:
1. The AllowUntrustedInternalConnections setting rightfully prevents it
2. The image proxy API requires that the user is logged in, but the server can't log into itself
So instead, we just bypass the API entirely and talk directly to the image proxy. Due to how the image proxy is set up for both the local one and the atmos/camo one, this isn't exactly straightforward, but it's not completely terrible.
This is based off of #10188, but you can see the changes specific to this PR here: https://github.com/mattermost/mattermost-server/compare/mm13207...mm13838
https://mattermost.atlassian.net/browse/MM-13838
>  MM-13838 Bypass the HTTP client when getting image dimensions from the image proxy

- api4/user.go
This PR is an addition to https://github.com/mattermost/mattermost-server/pull/10207 changing the error returned in the case of an invalid password to the following message:
`{"id":"api.user.check_user_password.invalid.app_error","message":"Login failed because of invalid password","detailed_error":"user_id=xr3qg3g6mbd7ujigksp6ckpjcy","request_id":"u37ffkjfnbbfippqhgybzpmrer","status_code":401}`
Since it has an unique error id, we can intercept it properly within the webapp to display the correct error to the end user:
https://github.com/mattermost/mattermost-webapp/pull/2304/commits/09a41df1456436855cdf11918f950dcffc4168cc#diff-384b37409a3c3d1830b7bc3d042ce794R282
https://mattermost.atlassian.net/projects/MM/issues/MM-13839
> [MM-13839] Return password check error as API response to failed eMail patch

- build/Jenkinsfile.pr
follow up from this https://github.com/mattermost/mattermost-server/pull/10228
When building PR from upstream, Jenkins is building the PR and the Branch.
for the branch build, some git environment variables are not available as the target branch, because it is not a PR.
to be in the safe side we need to checkout from master, we don't know in the branch build for which branch it will be merged.
But in most of the times, we are interested only on the PR build.
> Add Fallback to master in jekinsfile when checkout webapp/enterprise repos

- api4/api.go
- api4/bot.go
- api4/bot_test.go
- app/bot.go
- model/bot.go
- model/client4.go
- store/sqlstore/bot_store.go
- store/store.go
- store/storetest/bot_store.go
- store/storetest/mocks/BotStore.go
- web/context.go
- web/params.go
Adds a parameter to get bots to specify that you only want the orphaned entries. This will allow an admin to find bots that need to be taken care of.
Also adds the new route `/assign` which allows users with permissions to assign bots to themselves or others. 
Future:
- Change "CreatorId" to "OwnerId" as the value may no longer be the creator.
> MM-13129 Adding functionality to deal with orphaned bots

- store/sqlstore/post_store.go
- store/storetest/post_store.go
We were ignoring all the other channel/team join/leave/add/remove messages but not these ones so in some cases town square was being marked unread for these messages when that should not happen.
https://mattermost.atlassian.net/browse/MM-13662
> Do not update channel message count for team add/remove message

- app/post_metadata.go
- app/post_metadata_test.go
For images in the OpenGraph metadata, we only looked for the `url` field, but we should've also been looking for the `secure_url` field for sites that defined it. We also set the `secure_url` field when proxying OpenGraph images as well, so we were not properly giving image dimensions for OpenGraph images.
https://mattermost.atlassian.net/browse/MM-13996
> MM-13996 Properly get image dimensions for OpenGraph images using secure_url

- model/config.go
- utils/config_test.go
When moving these settings, I renamed the fields which caused the library responsible for loading the config to not load the old ones. I thought the `json` struct tags would help the library find the old fields, but it turned out that the mapstructure library needed its own struct tags.
https://mattermost.atlassian.net/browse/MM-14037
> MM-14037 Ensure deprecated image proxy settings are read correctly

- api4/user_test.go
- app/authentication.go
- app/login.go
- app/oauth.go
- i18n/en.json
User accounts corresponding to bots should not be allowed to login. In practice, this is already impossible as we don't give bots the necessary AuthData, but add some explicit checks and coverage around this.
https://mattermost.atlassian.net/browse/MM-13104
> MM-13104: forbid bot login

- app/post_metadata.go
Some websites such as giphy serve both HTML or an image for a given link. By switching the order, we prioritize receiving images instead of HTML that might contain OpenGraph metadata.
The reason we need this is that when we're loading metadata for a given link, we don't care if the link is in a Markdown image or if it's just a raw link in the post. Unless we start to differentiate the two (which requires some changes around how we store this metadata), we need to pick one or the other to use here. Since we can show previews for plain images, but we can't render OpenGraph as a Markdown image, I've picked to prefer images.
I didn't add a test for this since there's no built-in utility in Go for doing content negotiation, and any such unit test would be pointless anyway with a mocked server. …
> MM-13997 Prioritize images over OpenGraph metadata when requesting metadata

- services/imageproxy/local.go
Based on the values used by GitHub's atmos/camo image proxy
https://mattermost.atlassian.net/browse/MM-14146
> MM-14146 Update CSP for local image proxy

- config/utils.go
This fixes a bug that the config desanitize can crash if the amount of `DataSourceReplicas` is higher than `DataSourceSearchReplicas`, causing a out of range panic.
FYI @lieut-data
> Fix out of range error if Search Replicas < Replicas in Config Parsing

- utils/subpath.go
- utils/subpath_test.go
- web/handlers.go
- web/handlers_test.go
The server now emits a `script-src` CSP directive that overrides the `root.html` rewrite. Fix this by emitting the requisite `sha-256` hash server-side as well as rewriting `root.html`. We can't remove the `root.html` rewrite, since the assets may be on a CDN instead and we use the same code path to rewrite them (on demand).
Prior to this change, going from `/` -> `/subpath` -> `/` would leave changes in `root.html`: the `Content-Security-Policy` header would still have the `sha-256` hash, and the inline script would still override the `publicPath` but to the default subpath value. To avoid sending down a `sha-256` hash server-side when no subpath is required, change this to fully strip out the subpath changes. This is the only unit test change to the existing subpath tests, as the …
> MM-14052: fix subpath yet again

- store/sqlstore/post_store.go
Fix missing message when using unread API
- the status returns 304 (not modified) when the cache item in getting the etag has a value of 0 (initial value).
Note:  Attempted to add test but can't see how to test it effectively.
Jira ticket: [MM-12753](https://mattermost.atlassian.net/browse/MM-12753)
> [MM-12753] Fix missing message when using unread API

- cmd/mattermost/commands/channel.go
- cmd/mattermost/commands/channel_test.go
add command search on channel group.
it could search channel by name or id in general
and search channel with team by team name or id
Fixes https://github.com/mattermost/mattermost-server/issues/9491
https://mattermost.atlassian.net/browse/MM-12304
> [MM-12304] Add channel search support in mattermost cli

- .github/stale.yml
Stale bot should ignore PR's that are further in the life cycle. These are the ones, we have to check manually.
Follow up on https://github.com/mattermost/mattermost-server/pull/10143
> Let stale bot ignore pr further in the lifecycle

- app/plugin_requests.go
- web/handlers.go
This PR makes the logging of the in [MM-10346](https://mattermost.atlassian.net/projects/MM/issues/MM-10346) introduced CSRF token implementation less verbose unless it's actually enforced. If it's not enforced, the warning message is only printed in LogDebug. If it's enforced, the LogWarn is used.
> Make CSRF Logging less verbose if not enforced

- api4/user.go
- api4/user_test.go
Currently it's possible for users to disable themselves using the delete handler, this PR checks whether it's enabled and returns a 401 error otherwise. System admins are unaffected by this change.
https://mattermost.atlassian.net/browse/MM-14233
> [MM-14233] Check whether self-deactivation is enabled in delete handler

- app/login.go
- app/oauth.go
- app/plugin_hooks_test.go
The SAML authentication flow returns an error from the normal login flow and continues from a dedicated `completeSaml` handler. Since the login hooks were executed in a section that was skipped by SAML, they were never invoked that way. This PR moves the hook execution to the `DoLogin` flow which is invoked by all 3 login flows:
1. `completeOAuth` - `oauth.go:521`
2. `login` - `user.go:1144`
3. `completeSaml` - `saml.go:129`
Since that's the only place where we invoke `App.CreateSession`, it should cover all authentication flows.
FYI @lindalumitchell 
https://mattermost.atlassian.net/projects/MM/issues/MM-13610
> [MM-13610] Fix Login Hooks for SAML

- app/user.go
- app/user_test.go
This PR invalidates password recovery tokens when an email change was done to ensure that after an account takeover the attacker won't be able to gain control after the eMail was changed again. 
https://mattermost.atlassian.net/browse/MM-14234
> [MM-14234] Invalidate password recovery tokens on eMail change

- api4/user.go
This PR changes two invocations of LogAuditWithUser to LogAudit to avoid the situation that admin action audit entries are leaked to the user audit log. The user that is modified is now stored in the extra data itself.
https://mattermost.atlassian.net/browse/MM-14235
> [MM-14235] Use LogAudit instead of LogAuditWithUser when logging user modification changes

- app/saml.go
- i18n/en.json
- model/client4.go
As a follow up to the last SAML PR, and continuing to support configuration in the database, this PR modifies our SAML certificate upload process to write to fixed-name files. Previously, we accepted an arbitrary filename from the enduser and used that to name the file in the `config/` folder. This seemed needlessly risky (and more complicated to support), so this PR uses fixed names instead.
The fixed names are written to the config as normal and use to look up the resources, allowing us to maintain backwards compatibility with existing SAML setups. The `mattermost config migrate` command should probably convert to the fixed names at that time if users want to adopt that functionality.
https://mattermost.atlassian.net/browse/MM-14294
> MM-14294: Hard code SAML certificate "file" names

- model/token.go
Increase the time limit of tokens existency from 24h to 48h.
How this works? Every hour is run a cleanup of exiting tokens, removing any
token older than 24 hours. For now we have 4 kind of tokens. One for Oauth
(without explicit expiration, but with a 30 minutes cookie expiration), a
verify email (without explicit expiration), invitations with explicit
expiration after 48h, and password recovery with explicit expiration after 1
hour. Every token is removed after 24 hours. If we change the limit of the
cleanup to 48h, we will see that email verification, oauth tokens, and
invitations start to work during 48 hours (I’m not sure about the OAuth,
because I didn’t investigate properly the cookie expiration implications).
[MM-13817](https://mattermost.atlassian.net/browse/MM-13817)
> MM-13817: Increase the time limit of tokens existency from 24h to 48h

- web/handlers.go
- web/handlers_test.go
The SiteURL organically doesn't take effect until server restart, but in v5.8, the required CSP directive would change immediately. If changing from one subpath to another, the webapp would effectively be bricked until a server restart.
Avoid this by determining the CSP directive when the static handler is created.
I'm not super happy about the inability to unit test this in v5.9, but the foundation for "doing this properly" is almost present in master, so I'm content to leave the changes as-is and circle back once my final config store changes are merged.
https://mattermost.atlassian.net/browse/MM-14194
> MM-14194: fix subpath csp directive until server restart

- store/sqlstore/link_metadata_store.go
- store/storetest/link_metadata_store.go
Attempting to save duplicate metadata is harmless and just means that multiple threads are trying to get metadata for a link at the same time. This generally won't happen, but the Zoom plugin seems to make a post and then edit it quickly, so it was causing this to happen frequently.
https://mattermost.atlassian.net/browse/MM-14082
> MM-14082 Don't print warnings when saving duplicate metadata

- app/admin.go
- app/config.go
- app/saml.go
- cmd/mattermost/commands/config.go
- config/common.go
- config/database.go
- config/database_test.go
- config/file.go
- config/file_test.go
- config/memory.go
- config/store.go
When UpdateConfig (and configStore.Set) is called in admin.go and
config.go, commonStore.Set now takes a store-specific persist function.
It uses that persist function to save the configuration automatically.
Removed: Now callers do not have to call configStore.Save or
app.PersistConfig, and those functions have been removed.
Possible downside: this means a "failed to persist config" error can now
be thrown during a app.UpdateConfig or commonStore.Set call. But
considering application code never really sets a config without saving
it (except in the test cases, which were testing that -- see below), it
seems fine to group these responsibilities.
Also removed: tests for 'set without save'. Since that can not happen
anymore, the tests are not needed. …
> MM-14145: The config store Set will now Save automatically

- api4/user.go
In order to avoid leaking the admin session, log the modification in the current users audit log and refer to the user ID in the extra data.
https://mattermost.atlassian.net/browse/MM-14313
> [MM-14313] Use LogAudit for Active/Deactive Action

- cmd/mattermost/commands/sampledata.go
Skip tutorial steps for sysadmin, user-1 and user-2 from generated sample data
- to prevent flaky E2E tests when using these users due to tutorial icons and tooltips covering some of the target elements.
Jira ticket: [MM-14375](https://mattermost.atlassian.net/browse/MM-14375)
> [MM-14375] Skip tutorial steps for sysadmin, user-1 and user-2 from generated sample data

- services/httpservice/client.go
- services/httpservice/client_test.go
- services/httpservice/httpservice.go
Currently if you make a request through the image proxy / by other means to the public IP of the Mattermost service, it will be considered an external request for our request checker while it will actually be routed through the loop-back, since commonly there is a default route for that case in place. This PR adds a check that requires that any publicly assigned IP of the Mattermost server needs to be explicitly whitelisted before it's accepted for any HTTP Request (Image Proxy, ...)
https://mattermost.atlassian.net/browse/MM-14333
> [MM-14333] Stricten external HTTP Calls to require that own IPs need to be explicitly whitelisted

- Makefile
- api4/user_test.go
- app/command_test.go
Unfortunately, `which shadow` didn't resolve to the shadow binary, so hard-code the expected path in `$GOPATH/bin`. At the same time, run `go vet` across both the server and enterprise (if present), reducing the number of required invocations.
This is accompanied by an enterprise change to fix shadowing issues there.
N/A (tooling upgrade)
> fix vettool; run vet on all available packages

- api4/user_test.go
`TestUserLoginMFAFlow/WithCorrectMFA` seems to be brittle. If you run `while go test -run 'TestUserLoginMFAFlow'; do echo "PASSED"; done`, it will eventually fail with:
```
--- FAIL: TestUserLoginMFAFlow (2.63s)
--- FAIL: TestUserLoginMFAFlow/WithCorrectMFA (0.09s)
user_test.go:1911: Expected no error, got ": Error trying to authenticate MFA token, "
```
I suspect it wraps over the TOTP token timeout, generating the code right before and trying to verify it right after. Skipping for now until we can circle back on this one.
N/A
> skip TestUserLoginMFAFlow/WithCorrectMFA as it fails at random

- app/import.go
- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/post_store.go
Remove a store call that is causing some deadlocks in the app at the end of an import.
This function was introduced to ensure the "LastPostAt" after the import, but
we can ensure that simply being more explicit about when we update the
LastUpdateAt in the channel (not allowing to update the lastPostAt for a
previous post).
[MM-14357](https://mattermost.atlassian.net/browse/MM-14357)
> MM-14357: Remove store call that can provoke dead locks

- api4/user_test.go
In `master`, unit tests are run with a config generated from `*model.Config.SetDefaults`, which has `DisableLegacyMFA` defaulting to be `false`. This value is distinct from `default.json` so as to avoid breaking existing servers that upgrade their configurations, but in release-5.9 we run tests against `default.json` copied as `config.json`. This particular test didn't make the preconditions for `DisableLegacyMFA` explicit and thus failed to pass on release-5.9.
Medium term, we should eliminate `default.json` altogether and encode this business logic exclusively in `*model.Config.SetDefaults`.
N/A
> explicitly configure DisableLegacyMFA for TestCheckUserMfa

- app/post.go
- app/post_test.go
This PR checks that the `root_id` of a new `Post` is the root of the thread, and returns a `400 Bad Request` if it's not.
[MM-14300](https://mattermost.atlassian.net/browse/MM-14300)
> [MM-14300] Return 400 if a post is created with a child post as root

- i18n/en.json
- model/config.go
- model/config_test.go
This PR updates the config defaults so if the `SiteName` field is blank in `TeamSettings`, it is set to a default value.
[MM-13694](https://mattermost.atlassian.net/browse/MM-13694)
> [MM-13694] Sets a default value for SiteName if empty

- codecov.yml
Removing the reference from our jenkins because some jobs run protected like the master branch, so I have my doubts if this is not the issue we are having
This is an experiment :-)
> remove reference from jenkins

- cmd/mattermost/commands/init.go
- model/permission.go
Fixing emojis and webhooks permissions split. The old permission is need to be
able to save multiple migrations at one shot, so in need the old permissions as
valid values in the roles model.
[MM-11101](https://mattermost.atlassian.net/browse/MM-11101)
> Fixing emojis and webhooks permissions split

- app/post.go
- app/post_test.go
- i18n/en.json
Check it the channel is archived before post actions like edit and delete.
[MM-14481](https://mattermost.atlassian.net/browse/MM-14481)
> MM-14481: Do not allow to edit or delete in archived channels

- app/import_functions.go
- app/import_functions_test.go
Autogenerate mention_keys on creation if mention_keys aren't provided
[MM-14488](https://mattermost.atlassian.net/browse/MM-14488)
> MM-14488: Autogenerate mention_keys on creation if mention_keys aren't provided

- api4/group_test.go
- app/group_test.go
- app/syncables_test.go
- model/group_syncable.go
- store/sqlstore/group_supplier.go
- store/storetest/group_supplier.go
Removes 'CanLeave' field.
https://mattermost.atlassian.net/browse/MM-14415
> MM-14415: Removes 'CanLeave' field.

- app/server.go
- cmd/mattermost/commands/server.go
- utils/i18n.go
Adds a check to `TranslationsPreInit` so it only loads the translations if they are not already, and add a call to it when starting through the server command before loading the config, avoiding the default locales being applied.
[MM-14361](https://mattermost.atlassian.net/browse/MM-14361)
> [MM-14361] Initialise the translations before loading the config store

- app/plugin_api.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Exposes these fields so that we can include the following information with NPS results:
- Server version
- Server install date
- Server diagnostics ID
- License ID
- License SKU
Let me know if there's anywhere else that I should be documenting these plugin APIs or if this is sufficient.
https://mattermost.atlassian.net/browse/MM-13740
> MM-13740 Add additional plugin APIs for NPS plugin

- config/default.json
- model/config.go
- model/config_test.go
This is being disabled by default due to concerns about breaking image previews and integration icons for links on the local network. 
Note that it's also being cherry-picked onto 5.8.1 as well.
https://mattermost.atlassian.net/browse/MM-14560
> MM-14560 Changed local image proxy to be off by default

- config/client.go
- config/default.json
- model/config.go
Adds an experimental feature flag to enable/disable click-to-reply feature ([See video](https://youtu.be/uzUFp-1iLQA)). Can be merged, but depends on webapp PR I'll be submitting.
https://mattermost.atlassian.net/browse/MM-14502
N/A
> [MM-14502] Add experimental flag to enable click-to-reply

- config/default.json
To avoid breaking outdated mobile versions with the deactivation of the legacy MFA mechanism, we will enable it in version 5.9 by default. The activation by default will be postponed to 5.10.
Needs to be cherry-picked.
https://mattermost.atlassian.net/browse/MM-14568
> [MM-14568] Activate Legacy MFA for release 5.9 by default

- app/diagnostics.go
Pretty straightforward. Just adds tracking for whether or not the NPS plugin and the periodic NPS surveys are enabled
https://mattermost.atlassian.net/browse/MM-14335
> MM-14335 Add telemetry for NPS plugin state

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/init.go
- cmd/mattermost/commands/jobserver.go
- cmd/mattermost/commands/root.go
- cmd/mattermost/commands/server.go
Consider the `MM_CONFIG` environment variable if `--config` is not explicitly specified. Also, fix the `jobserver` to honour `--config`.
https://mattermost.atlassian.net/browse/MM-14562
https://mattermost.atlassian.net/browse/MM-14564
> Address config startup issues

- api4/user.go
After the recent MFA refactor, we use an error-based flow to check whether a MFA token was required or not. Since we are obfuscating all errors before returning them to the client, this resulted in the MFA prompt never be shown.
This PR adds an exception to the error that is returned with a correct credential pair, but missing MFA token.
https://mattermost.atlassian.net/browse/MM-13816
> [MM-13816] Fix MFA prompt not being shown for hardened mode

- plugin/api.go
- plugin/client_rpc_generated.go
This is to fix the generated code so that it actually passes arguments correctly. If you look at the diff, the client-side call doesn't actually pass any values for the unnamed parameter.
I also filed https://mattermost.atlassian.net/browse/MM-14621 in case we want to actually fix the generator code.
https://mattermost.atlassian.net/browse/MM-14620
> MM-14620 Specify parameter name for PluginAPI.GetUsers

- api4/channel.go
- api4/post.go
- app/channel.go
- app/channel_test.go
- app/command_invite.go
- app/integration_action_test.go
- app/notification_push.go
- app/plugin_api.go
- app/post.go
- app/post_test.go
- app/syncables.go
- app/syncables_test.go
- store/sqlstore/user_store.go
Currently we are sending a notification when reading a channel to clear existing notifications for that channel in the devices **only** if the channel is read from a non-mobile device.
If you have more than one device with an active session all the devices were getting the notifications for new messages but not a clear notification when you read the channel from a mobile device.
This PR changes the way we send those "clear" notifications in a way that no matter where you read the channel "clear" notifications are sent to every mobile device as long as is not the one you used to read the channel in.
https://mattermost.atlassian.net/browse/MM-14532
> MM-14532 Send "clear" notification to every other session

- cmd/mattermost/commands/init.go
This PR adds Elasticsearch to the initialisation of the `Server` when running a command. This will allow the commands to update Elasticsearch indexes when required (e.g. creating a public channel in EE).
[MM-14254](https://mattermost.atlassian.net/browse/MM-14254)
> [MM-14254] Add elasticsearch initialisation to the cmd

- api4/team_test.go
- model/channel.go
- model/channel_test.go
- model/team.go
- model/team_test.go
- store/sqlstore/upgrade.go
Adds new field on `Team` and `Channel` for use by LDAP groups removals.
Originally I was planning to call the new fields `LimitMembershipToGroups` and then I thought `GroupConstrained` seems to capture the intent but I'm open to other ideas or opinions. I'm 0/5.
https://mattermost.atlassian.net/browse/MM-14416
> MM-14416: Adds new fields to Channels and Teams for use by LDAP groups removals.

- app/plugin_api.go
- app/plugin_api_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
This PR adds a `GetBundlePath() string` method to the Plugin API. This will return the path where the plugin bundle was unpacked.
By default the plugin directory is `./plugins`. Hence the returned path will most likely be relative e.g. `plugins/com.github.matterpoll.matterpoll`. Currently this should not cause problems, because the plugin working directory is the same as the servers one. If we want to change this to an absolute path, the signature for the method has to be `GetBundlePath() (string, error)` because [`filepath.Abs()`](https://golang.org/pkg/path/filepath/#Abs) can error. Or is there a smarter solution?
If someone wants test for this changes, just request them.
cc @kaakaa
Fixes #10448
> [MM-14576] Add GetBundlePath method to Plugin API

- i18n/en.json
- model/user.go
- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
This PR adds functions to get batches of channels and users ready to index on Elasticsearch using the bulk index mechanism.
[MM-14253](https://mattermost.atlassian.net/browse/MM-14253)
> [MM-14253] Adds channels and users to the bulk index process 

- api4/config.go
- api4/config_test.go
- config/common.go
- config/common_test.go
- config/export_test.go
- config/utils.go
- i18n/en.json
- model/config.go
- utils/merge.go
- utils/merge_test.go
These changes annotate fields in `model.Config` with a `restricted:"true"` tag, used by api4 to reject changes to certain fields when the system is configured to restrict the system admin (for Mattermost Cloud). No feedback is given to the system admin when this occurs, since the system console is expected to be updated to hide these settings/sections altogether in this mode.
This leverages the work of @cpoile to support merging configs recursively, with some minor changes from me to allow for struct field filters and tweak the documentation.
https://mattermost.atlassian.net/browse/MM-14441
> MM-14441: restrict system admin config

- config/default.json
This pull request changes the DisableLegacyMFA flag back to true after reverting it to false for 5.9 - The effect will be that new installations will disable the legacy MFA endpoint by default, while existing installations will keep it enabled by default.
https://mattermost.atlassian.net/browse/MM-14573
> [MM-14573] Toggle DisableLegacyMFA to true by default

- app/app_test.go
- app/permissions_migrations.go
- model/permission.go
- model/role.go
Remove any unused PERMANENT_DELETE_USER permission. I maintain the definition
of the permission (marked as deprecated) because is need for the migrations,
because any posible permission that can be in the store, must be in the list of
permissions (and during the migration the permission will be there)
[MM-14243](https://mattermost.atlassian.net/browse/MM-14243)
> MM-14243: Remove any unused PERMANENT_DELETE_USER permission

- api4/ldap.go
- api4/ldap_test.go
Adds license check to LDAP test and LDAP sync API endpoints.
https://mattermost.atlassian.net/browse/MM-14590
> MM-14590: Adds license check to LDAP test and LDAP sync API endpoints.

- app/diagnostics.go
Add diagnostics for EnableClickToReply and RestrictSystemAdmin.
https://mattermost.atlassian.net/browse/MM-14687
https://mattermost.atlassian.net/browse/MM-14688
> add diagnostics for EnableClickToReply and RestrictSystemAdmin

- api4/group.go
- api4/group_test.go
- app/group.go
- app/group_test.go
- model/client4.go
- store/layered_store.go
- store/layered_store_supplier.go
- store/local_cache_supplier_groups.go
- store/redis_supplier_groups.go
- store/sqlstore/group_supplier.go
- store/store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/GroupStore.go
- store/storetest/mocks/LayeredStoreDatabaseLayer.go
- store/storetest/mocks/LayeredStoreSupplier.go
Adds the endpoints and store logic to retrieve groups by team and by channel
API changes [documented in this PR](https://github.com/mattermost/mattermost-api-reference/pull/433).
[MM-14645](https://mattermost.atlassian.net/browse/MM-14645) and [MM-14646](https://mattermost.atlassian.net/browse/MM-14646)
> Adds the endpoints and store logic to get groups by team and by channel

- build/release.mk
Fixing prepackaged plugins by adding -L to curl command to follow redirects. 
https://mattermost.atlassian.net/browse/MM-14847
> MM-14847 Fixing prepackaged plugin build process.

- app/integration_action.go
- app/integration_action_test.go
- model/integration_action.go
- Fixed the wrong initialization of `remove`
- Consolidated the list of properties to retain in `model.PostActionRetainPropKeys`
- Added a test
https://mattermost.atlassian.net/browse/MM-14627
> Fixed MM-14627, was incorrectly removing props from updated post

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
Implements config migration command (mattermost config migrate) and includes automated unit test. The process is broken down in an attempt to provide relevant error messages.
The migrate command accepts 2 flags:
**1. --from** 
Optional flag - Sets the source config. Overrides the global --config flag. If the --from flag is not specified, command will fall back to what is specified in --config.
**2. --to**
Required flag - Sets destination config. Command will return error if unspecified.
Github: https://github.com/mattermost/mattermost-server/issues/10337
JIRA: https://mattermost.atlassian.net/browse/MM-13895
> [MM-13895] Implement config migration command

- web/handlers.go
In `web/handlers.go:104` we are receiving the session from the token, but actually don't verify if it's returning `nil` resulting in a panic when `GetCSRF()` is executed, since the error is never checked. This PR moves the session validation before the CSRF check component, which now is only executed after the session was validated and only executed if currently no error was set for the request.
> Avoid panic from reading CSRF of nil session pointer

- cmd/mattermost/commands/command.go
- cmd/mattermost/commands/command_test.go
This pull requests add new functionality that allows users to modify an existing command via the Mattermost CLI. This new command is added to improve the functionality of the Mattermost CLI as per ticket MM-12358. This command requires the existing command Id as a parameter and accepts any number of the following flags:
- title
- description
- trigger-word
- url
- creator
- response-username
- icon
- autocomplete 
- post
Something to consider with this PR is that if the flags --autocomplete and --post are not specified, the specified command will be updated to false and "G" respectively, as per their function via the "command create" command.  This includes modify commands that have no flags assigned.
Fixes https://github.com/mattermost/mattermost-server/issues/9597
> MM-12358 Create CLI command "command modify"

- app/authorization.go
This comment was introduced by @crspeller refering to a function without `*App`
scope, and to be replaced with the `*App` scoped version (in this commit:
4491b5ecdfad96959f9a9ab32a5f127bbfa7eac5).  Some time later @ccbrown removed
the function but not the comment itself (here:
816a30397da6ceff836d8723233dc5cdbda70871), and now looks like the legacy
function is the current valid function.
> Removed confusing and obsolete comment

- model/config.go
We removed LogSettings.FileFormat way back in 4.10 but it got added back accidentally with the merge of #9033 into master that happened recently.
https://mattermost.atlassian.net/browse/MM-14970
> Remove LogSettings.FileFormat after it was accidentally added back

- app/post_metadata.go
- app/post_metadata_test.go
Without post metadata, the server doesn't request information on pasted links if EnableLinkPreviews is false, but when the server has post metadata enabled currently, it ignores EnableLinkPreviews even though the client won't show anything for them. This makes it respect that setting by not making those requests when it doesn't need to.
https://mattermost.atlassian.net/browse/MM-15032
> MM-15302 Don't get post embeds with link previews disabled

- api4/config.go
- api4/config_test.go
With the new config, any config save failing because invalid configuration
fields is returning a 500 error with the same error. This happens because the
code in app config "flat" any error other than `ErrReadOnlyConfiguration`. My
solution is to validate the config in the Api, but now is validating the config
twice for this api endpoint (not a big deal)
[MM-15006](https://mattermost.atlassian.net/browse/MM-15006)
> MM-15006: Returning informative errors on config validation

- app/channel.go
- app/team.go
- app/user.go
Removing touchpoints with Elasticsearch for indexing and autocompletion related to `user` and `channel` entities.
- [Related enterprise PR](https://github.com/mattermost/enterprise/pull/417)
- [Related webapp PR](https://github.com/mattermost/mattermost-webapp/pull/2632)
> Disable elasticsearch indexing and autocompletion

- app/integration_action_test.go
- model/integration_action.go
Per @hanzei's request
- https://github.com/mattermost/mattermost-server/pull/10546#issuecomment-481997493
- https://mattermost.atlassian.net/browse/MM-14795
> MM-14795 Added "from_webhook" to protected props in DoPostAction

- plugin/hooks.go
Documenting the behavior of OnConfigurationChange. 
It is called before OnActivate so that configuration is available in that function. 
https://mattermost.atlassian.net/browse/MM-14788
> MM-14788 Documenting OnConfigurationChange being called before OnActivate.

- api4/user_test.go
The PR fixes the brittle `TestUserLoginMFAFlow/WithCorrectMFA` test. It was validated using:
`SECONDS=0; while go test ./... -run 'TestUserLoginMFAFlow/WithCorrectMFA'; do echo "PASSED - $SECONDS seconds elapsed"; done` with a runtime 1000s+ without any failures.
Since this is no guarantee, @lieut-data since you were able to replicate the races locally I'd appreciate a second test on your machine eventually to make sure that we don't introduce an unstable test once again.
https://mattermost.atlassian.net/browse/MM-14381
> [MM-14381] Fix brittle MFA Login Successful Test

- api4/user.go
- api4/user_test.go
Login response was not including the state of the ToS, so even when they were accepted, the client would still show them to the user to accept.
[MM-15126](https://mattermost.atlassian.net/browse/MM-15126)
> [MM-15126] Adding terms of service to the login response

- app/notification.go
- app/notification_test.go
- app/post.go
- i18n/en.json
- model/user.go
Updates the payload of WS ephemeral messages notifying of non-channel-members mentioned in a channel that cannot join the channel because of group constraints.
https://mattermost.atlassian.net/browse/MM-14417
> MM-14417: Messaging for mentions of users who are not in associated channel groups.

- api4/system_test.go
- app/admin.go
Fix new line being returned in logs, improved the test of GetLogs by actually checking the contents
Fixes https://github.com/mattermost/mattermost-server/issues/10558
> [MM-14890] Logs endpoint always returns an empty line

- api4/handlers.go
- api4/handlers_test.go
- Update `api4/handlers` to use gziphandler wrapper if server configured to
use gzip
- Add test to ensure `Content-Encoding="gzip"` header is set  if `WebserverMode=="gzip"` and `Accept-Encoding="gzip"` present in http request
I only added a single test to `ApiHandler` method as logic is the same in other methods. Happy to extend unit tests to the other 4 if necessary however. 
The `NewHandler` method in `web/handlers.go` appears to be used only in the webhook, so also not covered by the scope of the issue summary. 
I did not include changes to web and mobile apps - this would be separate repos/PRs I assume. 
Fixes https://github.com/mattermost/mattermost-server/issues/10325
> Use gzip for API responses [MM-11426]

- store/sqlstore/supplier.go
- store/sqlstore/upgrade.go
- store/sqlstore/upgrade_test.go
This is to support running another community cluster that stays on the most recent stable version while we test upcoming versions.
During the past few releases, we have committed to not making backwards incompatible schema changes across minor versions. This means that a 5.x server can run against any 5.y schema, y >= x. (It will upgrade to x if y < x).
https://mattermost.atlassian.net/browse/MM-15064
> MM-15064: allow running with future minor db versions

- model/integration_action.go
This PR is pretty straightforward. This value starts selected in the dropdown, allowing integrations to "save" a value which we wanted for the NPS plugin.
Webapp PR: https://github.com/mattermost/mattermost-webapp/pull/2677
Mobile PR: https://github.com/mattermost/mattermost-mobile/pull/2724
https://mattermost.atlassian.net/browse/MM-14741
> MM-14741 Add default option to post action dropdown

- app/channel.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Migrate WebHook.PermanentDeleteOutgoingByChannel to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/10647
> [MM-15189] Migrate WebHook.PermanentDeleteOutgoingByChannel to Sync by default

- app/plugin_api.go
- app/plugin_api_test.go
- app/plugin_key_value_store.go
- app/plugin_test.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
- store/sqlstore/plugin_store.go
- store/store.go
- store/storetest/mocks/PluginStore.go
Adding transactions semantics to KV store
- Added `KVCompareAndSet(key string, old []byte, new []byte)` to PluginAPI
- Added `CompareAndSet(kv *model.PluginKeyValue, oldValue []byte)` to `PluginStore`
- Added unit tests for `KVCompareAndSet`, `CompareAndSetPluginKey`
Other design considerations:
1. Update `model.PluginKeyValue` struct to include `OldValue []byte` field.
- Decided against it because `PluginKeyValue` struct is used to fetch a kv pair. Don't think it'll be  _clean_  to have a field on that struct called `OldValue`  which has no meaning when fetching a kv pair.
2. Create a new struct `model.UpsertPluginKeyValue` for `PluginStore.SaveOrUpdate(keyVal *model.UpsertPluginKeyValue)`
```
type UpsertPluginKeyValue struct {
*PluginKeyValue
// Used to update a key-value pair 
// if …
```
> MM-14246 - Plugin framework: support transactional semantics with KV Store

- app/webhook.go
- store/sqlstore/webhook_store.go
- store/store.go
- store/storetest/mocks/WebhookStore.go
- store/storetest/webhook_store.go
Migrates the WebHook.SaveIncoming methods to sync by default. I was previously working on this issue in PR #10635 but I made this mistake of adding to many changes. This PR Is only for the SaveIncoming method.
Fixes #10616
> MM-15116 Migrate WebHook.SaveIncoming Method to Sync by default

- api4/integration_action.go
- api4/integration_action_test.go
This pull request is to add support for interactive dialogs with no elements (#10686). As far as I know, the small change here should be enough to add support on the server side. As for the web app, we still need to modify the InteractiveDialog component to not require elements. While my experience with react is limited, I think the change needed is to simply drop the .isRequired tag for the array of elements in that component and add proper checks/test cases. Also, as @hanzei said in #10686 we probably need an integration test as well.
If I am missing the scope of the problem, I'll gladly go back and rework the solution 👍. 
Addresses #10686
> MM-15128 change openDialog to allow dialogs with no elements

- store/sqlstore/team_store.go
We have several different e-mail domains for a team and recently ran
into a length issue while adding an additional one. I did a little bit
of searching and it looks like the only limit is in the ORM mapping
code (here). The column data type seems to be TEXT.
> sqlstore/team: Updates maximum length of AllowedDomains to 1000 characters.

- app/user_viewmembers_test.go
Removing the possible race condition about GetRecentlyActiveUsersForTeam in the
TestViewMembers getting the entire list and comparing all the elements (in this
case are 3 at max). I guess this flaky tests are related to time generation in
test environment which makes the Activity of the users be the same.
> Fixing flaky test in view members

- utils/markdown/autolink.go
- utils/markdown/autolink_test.go
Fix panic in markdown link parsing by making sure we're not accessing a slice out of its bounds.
https://mattermost.atlassian.net/browse/MM-15328
> MM-15328 Fix panic in markdown link parsing

- store/sqlstore/group_supplier.go
- store/storetest/group_supplier.go
Do not remove bot accounts from teams or channels during LDAP group sync removals.
Purposely not removing bots that have a `DeleteAt` value `!= 0` but rather leaving that to the bots code to clean up memberships after itself.
https://mattermost.atlassian.net/browse/MM-15261
> MM-15261: Do not remove bot accounts from teams or channels.

- app/server.go
- config/default.json
- model/config.go
- plugin/environment.go
- plugin/health_check.go
- plugin/health_check_test.go
- plugin/supervisor.go
This PR adds new functionality to monitor running plugins, and take action when they are not responding. With this new functionality, all plugins are periodically monitored, and restarted or deactivated based on their health status.
[Github Ticket](https://github.com/mattermost/mattermost-server/issues/10386)
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-13507)
This PR was made to review the core functionality of the plugin monitoring/restart issue. The [original PR](https://github.com/mattermost/mattermost-server/pull/10462) had gotten a bit out of scope of the original task, and so there were many intermediate commits that added and removed pieces that are outside of what should be part of this PR. I've consolidated the appropriate changes into this PR for review.
> [MM-13507] Plugin framework: auto-restart plugins that crash

- app/app.go
- web/web.go
When the web server is disabled just default 404 instead of trying to render the 404 page in the web app. This fixes an infinite redirect loop.
https://mattermost.atlassian.net/browse/MM-15367
> MM-15367 Do not try to render web app 404 error page when web server is disabled

- model/utils.go
This pull request adds `error` and `help` to the reserved name list, since we use those in static paths in the web app.
https://mattermost.atlassian.net/browse/MM-15493
> [MM-15493] Add Error and Help to reserved name list

- config/client.go
This PR allows the CreateBotAccounts flag under ServiceSettings to be used outside of the System Console. This is needed for the PR [#2751 in webapp](https://github.com/mattermost/mattermost-webapp/pull/2751) to allow for conditional rendering based on the status of the flag. 
#10776
> MM-14723: Add CreateBotAccounts to client.go

- api4/group.go
- api4/group_test.go
- app/group.go
- app/group_test.go
- cmd/mattermost/commands/group.go
- model/client4.go
- model/group.go
- store/layered_store.go
- store/layered_store_supplier.go
- store/local_cache_supplier_groups.go
- store/redis_supplier_groups.go
- store/sqlstore/group_supplier.go
- store/store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/GroupStore.go
- store/storetest/mocks/LayeredStoreDatabaseLayer.go
- store/storetest/mocks/LayeredStoreSupplier.go
- web/params.go
Changes to be able to add and remove groups from channels.
Pretty similar to some of the changes from https://github.com/mattermost/mattermost-server/pull/10701 but for Channels.
https://mattermost.atlassian.net/browse/MM-14897
> MM-14897: Changes to be able to add and remove groups from channels.

- api4/user.go
- app/user.go
- app/user_viewmembers_test.go
- model/user_get.go
- model/user_search.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Adds the `group_constrained` parameter to both `/users` and `/users/search` endpoints.
https://mattermost.atlassian.net/browse/MM-14751
> [MM-14751] Adds group_constrained filter to user list and search endpoints

- app/channel.go
- cmd/mattermost/commands/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/group_supplier.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/post_store.go
Makes the store method Restore and Delete Channel sync
Fixes https://github.com/mattermost/mattermost-server/issues/10765
> made the Restore and Delete store method to be sync

- app/plugin_api.go
- app/post.go
- plugin/api.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Before it was accepting `post *model.Post`, and returning one.
This is a breaking change for the giphy plugin and any other that rely
on the API. cc @scottleedavis 
https://mattermost.atlassian.net/browse/MM-15632
> MM-15632 DeleteEphemeralMessage to accept a `postId string`

- api4/channel.go
- api4/team.go
- app/channel.go
- app/command_invite.go
- app/command_remove.go
- app/notification.go
- app/team.go
- cmd/mattermost/commands/group.go
- i18n/en.json
- model/channel.go
- model/team.go
* Adds `(*Channel).IsGroupConstrained()` and `(*Team).IsGroupConstrained()` helper methods.
* At the app tier, prevents removing users from group-constrained channels if the user is a member of the associated groups.
* At the app tier, prevents adding users from group-constrained if the user is not a member of the associated groups.
* Updates the ephemeral message text for `/kick`/`/remove` when performed on a group-permitted channel member.
* Updates the ephemeral message text for `/invite` when performed on a non-group-permitted channel member.
I don't like the awkward API of `(*App).FilterNonGroupChannelMembers`. Something like `(*App).UserCanJoinGroupConstrained[Channel|Team]` would be nicer to work with so my plan is to refactor that in the near future. …
> MM-15485: In-channel system behaviour for at-mentions and slash commands for group-constrained channels.

- app/user.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
This PR migrates PermanentDeleteByUser in the Preference store to use a synchronous call by default.
Fixes https://github.com/mattermost/mattermost-server/issues/10717
> [MM-15300] Migrate "Preference.PermanentDeleteByUser" to Sync by default

- store/sqlstore/user_store.go
Fixing not initialized SchemeGuest field on bulk indexing query for channel members
[MM-15728](https://mattermost.atlassian.net/browse/MM-15728)
> MM-15728: Fixing not initialized SchemeGuest field on bulk indexing query

- model/channel_member_history_result.go
- model/message_export.go
- store/sqlstore/channel_member_history_store.go
- templates/globalrelay_compliance_export.html
- templates/globalrelay_compliance_export_message.html
- templates/globalrelay_compliance_export_participant_row.html
Added new field 'UserType' to compliance export. Right now supports 'bot' and 'user'
Fixes https://mattermost.atlassian.net/browse/MM-14721
Related enterprise PR: https://github.com/mattermost/enterprise/pull/437
> MM-14721 - Add an identifier for compliance exports when a message is posted by a bot account

- model/config.go
Add support for tracing in LDAP. It adds a setting in the `LdapSettings` to
enable debug mode in the ldap client library. Asked by Paul Rothrock.
Enterprise PR: mattermost/enterprise#439
> Add support for tracing in LDAP

- app/app.go
- app/plugin_requests.go
- app/ratelimit.go
- app/ratelimit_test.go
- app/server.go
- config/default.json
- model/config.go
- utils/utils.go
- utils/utils_test.go
- web/handlers.go
- web/web.go
Currently we always trust the `X-Forwarded-By` and `X-Real-Ip` header as an authority what the clients IP address is. The problem with this behavior is when Mattermost is running without a proxy, a client can essentially send those headers himself and bypass rate limiting and/or the audit log. For environments that use a reverse proxy this problem does not exist, if the headers are set by NGINX itself. However, if `X-Real-Ip` is used and `X-Forwarded-By` is not filtered by the proxy it will essentially be overwritten.
This pull request adds a new configuration called `TrustedProxyIPHeader` that is a string array, allowing the administrator to pass an array of headers that will be checked one by one for IP addresses (order is important). All other headers are ignored.
New configs will have …
> [MM-15639] Add config setting to explicitly define which IP headers are trusted

- model/config.go
- model/config_test.go
Fixes https://github.com/mattermost/mattermost-server/issues/9155
Add functionality to allow `+` and `.` in custom URL schemes, in System Console > Customization > Posts > Custom URL Schemes (in addition to hyphen)
[Jira ticket](https://mattermost.atlassian.net/browse/MM-11287)
Related PR:
* https://github.com/mattermost/marked/pull/11
* https://github.com/mattermost/commonmark.js/pull/7
> [MM-11287] Add support for plus sign and period/dot in custom URL schemes (#9155)

- app/post.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
Migrate the `DeleteCategoryAndName` method from the `Preference` store to Sync by
default.
Fixes #10713
> [MM-15304] Migrate "Preference.DeleteCategoryAndName" to Sync by default

- app/analytics.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
This pull request migrates the AnalyticsSessionCount in the Session store to use Sync by default. I followed the instructions laid out in the issue description and updated all necessary files.
Fixes #10929
> [MM-15803] Migrate "Session.AnalyticsSessionCount" to Sync by default

- app/post_metadata.go
- app/post_metadata_test.go
Adds a special case to `parseImages in app/post_metadata.go` so that format returns nil when the `DecodeConfig` is tiff. This prevents empty boxes/previews from appearing for tiff image links since most browsers can't render them.
Special additional PR for the [webapp PR ](https://github.com/mattermost/mattermost-webapp/pull/2333)for the [ticket](https://github.com/mattermost/mattermost-server/issues/8092)
> [MM-8421] Special PR to have parseImages return nil when format is tiff

- app/team.go
- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
Migrate the `DeleteCategory` method from the `Preference` store to Sync by
default.
Fixes #10714
> [MM-15303] Migrate "Preference.DeleteCategory" to Sync by default

- app/notification_push.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
This pull request migrates the `GetSessionsWithActiveDeviceIds` in the `Session` store to use Sync by default. I followed the instructions laid out in the issue description and updated all necessary files.
Resolves #10936
> MM-15796 Migrate "Session.GetSessionsWithActiveDeviceIds" to Sync by default

- store/sqlstore/preference_store.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/preference_store.go
This pull request migrates the IsFeatureEnabled in the Preference store to use Sync by default. I followed the instructions laid out in the issue description. 
Fixes https://github.com/mattermost/mattermost-server/issues/10716
> [MM-15301] Migrate "Preference.IsFeatureEnabled" to Sync by default

- plugin/environment.go
Changes the active plugin to only return "active" plugins that are actually running. This prevents /api/v4/plugins/webapp from returning plugins that have failed to start.
This isn't ideal, the proper solution to this would be to restore the semantics of env.activePlugins to be only plugins that are truly active or make the name more clear. Ticket for that investigation: https://mattermost.atlassian.net/browse/MM-15831
Ticket: https://mattermost.atlassian.net/browse/MM-15202
> MM-15202 Preventing failed plugins webapp components from being served.

- app/channel.go
- app/post.go
- app/user.go
This PR trims leading and trailing spaces for search terms when searching for posts, users and autocomplete users
https://mattermost.atlassian.net/browse/MM-15703
> Trim leading and trailing spaces for search terms

- api4/user.go
- api4/user_test.go
Currently we indicate if a user account exists, if the password was incorrect or the wrong authentication method used. This PR uses the previous existent code used for the hardened mode to obfuscate the error message before sent back to the client, with the following exceptions:
- Invalid MFA Token
- Blank password
- Bot Login is forbidden
- Client Certificate error
The error messages above don't expose any additional information, and communicate that something was invalid before any specific user is valdiated.
**ToDo:** The error message might need additional UX work.
https://mattermost.atlassian.net/browse/MM-15767
> [MM-15767] Limit exposure of any information about the user status on login failure

- plugin/health_check_test.go
Temporarily disabled the PluginHealthCheck_RPCPingFail test, filed a follow-up ticket https://mattermost.atlassian.net/browse/MM-15870. cc @mickmister 
https://mattermost.atlassian.net/browse/MM-15706
> MM-15706: disable PluginHealthCheck_RPCPingFail test

- app/channel.go
- app/command_expand_collapse.go
- app/email_batching_test.go
- app/export_test.go
- app/import_functions.go
- app/oauth.go
- app/preference.go
- app/user.go
- store/sqlstore/preference_store.go
- store/sqlstore/preference_store_test.go
- store/store.go
- store/storetest/mocks/PreferenceStore.go
- store/storetest/oauth_store.go
- store/storetest/post_store.go
- store/storetest/preference_store.go
Removes preference length return argument from Preference.Save function
Discussed in #10866
> [GH-10866] Preferrence.Save - Remove preference length return arg

- app/oauth.go
- web/handlers.go
- web/web.go
Returning json responses for errors on oauth API endpoints, and returning 4xx
errors instead of 500 error when is something that could happend because the
user input.
[MM-15835](https://mattermost.atlassian.net/browse/MM-15835)
> MM-15835: correct errors and content types for oauth api calls

- api4/oauth.go
Adding `text/html` Content-Type header instead of `application/json` to the OAuth complete endpoint.
[MM-15752](https://mattermost.atlassian.net/browse/MM-15752)
> Adding Content-Type header to the OAuth complete endpoint

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/config_test.go
This changes the syntax of the config migrate command from:
mattermost config migrate --from <from config> --to <to config>
to:
mattermost config migrate <from config> <to config>
making it more consistent with our other CLI commands.
https://mattermost.atlassian.net/browse/MM-15956
> MM-15956: consistent params for config migrate

- app/session.go
- Skips email sending when creating personal access tokens for bot users.
- Logs an error instead of returning an error when failing to send email confirming bot token creation.
- This prevents the bot creation page skipping the access token screen when the email configuration in the Mattermost server is incorrect. 
https://mattermost.atlassian.net/browse/MM-15777
> MM-15777 Preventing bad email configuration from failing personal access token creation

- app/user.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
Migrate the `PermanentDeleteSessionsByUser` method from the `Preference` store to Sync by
default.
Fixes #10933
> [MM-15799] Migrate "Session.PermanentDeleteSessionsByUser" to Sync by default

- app/session.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
- store/storetest/session_store.go
This pull request migrates the `UpdateDeviceId` in the `Session` store to use Sync by default. I followed the instructions laid out in the issue description and updated all necessary files.
Resolves #10931
> [MM-15802] Migrate "Session.UpdateDeviceId" to Sync by default

- app/export.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Summary
Migrate `Post.GetParentsForExportAfter` in `store/sqlstore/post_store.go` to Sync by default removing the `return.Do` wrapper.
Ticket Link
Fixes #10965
> Migrate "Post.GetParentsForExportAfter" to Sync by default #10965

- Makefile
- build/release.mk
- Pulling from new CI
- Stripping out alternate platform binaries from prepackaged plugins.
> MM-15882 Switching to new ci for prepackaged plugins and stripping alternate platform binaries.

- app/diagnostics.go
Re-submitting from #10956 
Add pre-packaged plugins to telemetry diagnostics
This includes the following plugins:
- Jira 2.0
- Zoom
- GitHub
- Autolink
- WelcomeBot 
- Custom attributes
- Amazon SNS Alerts
https://mattermost.atlassian.net/browse/MM-15833
> MM-15833 Add new pre-packaged plugins to telemetry diagnostics

- app/import_functions.go
- app/import_functions_test.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Migrate "Post.GetPostsCreatedAt" in `store/sqlstore/post_store.go` to Sync by default removing the `return.Do` wrapper.
Fixes #10970
> [MM-15858] Migrate "Post.GetPostsCreatedAt" to Sync by default

- app/import_test.go
- app/post.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Migrate "Post.GetPostsByIds" in `store/sqlstore/post_store.go` to Sync by default removing the `store.Do` wrapper.
Fixes #10969
> [MM-15859] Migrate "Post.GetPostsByIds" to Sync by default

- api4/oauth.go
This fixes the `redirect_to` value being ignored after logging in via OAuth.
fixes #10943
> [MM-15836] Fix redirect after OAuth login

- config/database_test.go
- config/file.go
- config/file_test.go
Fix a regression in the file-based `HasFile` check that spuriously accepts an empty string and tests the existence of the parent folder.
I've added an equivalent database test, but I note that it's not subject to the same problem given there is no path resolution required. (And technically an empty string is currently allowed as a filename there.)
Fixes https://github.com/mattermost/mattermost-server/issues/11030
> Issue 11030: fix HasFile to avoid false positives for no filename

- app/user.go
The problem here had to do with the return type for a `nil`
`[]string`. If `listOfAllowedChannels` is an empty list, that means
that the user doesn't have permissions to view anything, hence we have
to return an empty result. If it is `nil`, there are no restrictions
and we can proceed.
`[]string(nil)` behaves both as a `nil` value and as an "empty" slice,
so this improves the check to be able to distinguish between both
cases.
https://mattermost.atlassian.net/browse/MM-16005
- [Has enterprise changes](https://github.com/mattermost/enterprise/pull/446)
> [MM-16005] Check listOfAllowedChannels to be a not nil empty slice

- app/session.go
- app/session_test.go
As discussed with @crspeller we are going to exclude the mobile sessions for now as described in the system console and then for the next release will add a new setting to control the idle timeout for mobile sessions explicitly as we do with session lengths (ticket here https://mattermost.atlassian.net/browse/MM-16111)
Note: Submitting only against the release branch.
https://mattermost.atlassian.net/browse/MM-15971
> Mobile sessions to be excluded from idle timeout

- Makefile
Includes part of the fix for https://mattermost.atlassian.net/browse/MM-8647 and an ESLint dependency upgrade from GitHub
> Update NPS plugin to 1.0.0-rc2

- model/user.go
- store/sqlstore/user_store.go
- store/storetest/user_store.go
Related client PR: https://github.com/mattermost/mattermost-webapp/pull/2921
The issue was that the clients need the bot description to display in verious places in the UI (channel header, profile popover) but they where using the bot accounts api to retrieve that information. That API is restricted with a separate set of permissions so it was failing for some users.
This PR removes the secondary retrieval process and includes the bot description with users that are bots. This allows all clients that need to display this information access with only a single request while keeping the bots API for administration only. It also ensures that the two APIs don't diverge in terms of permissions. (they had already done so).
https://mattermost.atlassian.net/browse/MM-16001
> MM-16001 Adding bot description field to bot users.

- plugin/helpers_bots.go
- plugin/helpers_bots_test.go
Allows the plugin to takeover a regular user account with EnsureBot while logging an error letting the admin know what happened.
> MM-16114 Preventing plugin startup failure if bot account already exists as regular user.

- api4/user.go
- api4/user_test.go
- i18n/en.json
This is a follow up pull request of https://github.com/mattermost/mattermost-server/pull/10925 where instead of relying on a exception list, we will now only mask a specific set of errors that would expose sensitive errors. 
FYI @lindalumitchell 
https://mattermost.atlassian.net/browse/MM-15767
> [MM-15767] Mask errors in login flow only explicitly

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
This pull request migrates the `GetAll` in the `Team` store to use Sync by default. I followed the instructions laid out in the issue description and updated all relevant files.
Resolves #11090
> [MM-16164] Migrate "Team.GetAll" to Sync by default

- plugin/health_check_test.go
This PR disables a test affected by a race condition, waiting for the host OS to register the panicked plugin process as dead. Solutions for writing a deterministic test are being discussed by the EXT team.
[Jira Ticket](https://mattermost.atlassian.net/projects/MM/issues/MM-16245)
> Disable plugin health check process check test

- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Summary
Migrate Preference to Sync by default removing the `return.Do `wrapper.
Ticket Link
Fixes #11096
> Migrate "Team.UpdateDisplayName" to Sync by default #11096

- api4/user.go
- api4/user_test.go
This ticket fixes a regression introduced from the login error message rework, where the account lockout message wasn't shown. This whitelists the lockout message to be unmasked, a follow up ticket to move to an eMail based notification / client specific lockout will be created.
FYI @lindalumitchell 
https://mattermost.atlassian.net/browse/MM-16242
> [MM-16242] Unmask Account Lock Message

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
This pull request migrates the `GetChannelUnreadsForTeam` in the `Team` store to use Sync by default. I followed the instructions laid out in the issue description and updated all relevant files.
Resolves #11115
> [MM-16184] Migrate "Team.GetChannelUnreadsForTeam" to Sync by default

- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
This PR migrates method "Post.GetOldest" to Sync by default.
Fixes https://github.com/mattermost/mattermost-server/issues/10966
> Migrate Post.GetOldest to Sync by default

- app/team.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
+ GetTotalMemberCount returns (int64, *model.AppError) now instead of StoreChannel.
+ Updated store mock.
+ Updated code that referenced GetTotalMemberCount to handle the sync result.
[MM-16179](https://mattermost.atlassian.net/browse/MM-16179)
[MM-16179]: https://mattermost.atlassian.net/browse/MM-16179
> [MM-16179] Migrate Team.GetTotalMemberCount to Sync by default #11120

- app/user.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
This PR Migrates `Post.PermanentDeleteByUser` to Sync by default in `Post Store` and updates all referencing files to not handle the response from a channel but instead the error directly.
Fixed #10984
> MM-15844: migrate post PermanentDeleteByUser to sync by default #10984

- Makefile
No changes were made between this version and the current 1.0.0-rc2 version. In the future, I'm thinking we'll just do 1.0.0, 1.0.1, 1.0.2, etc releases for this plugin instead of doing RCs since it saves having to cut a final release with no changes like this
https://mattermost.atlassian.net/browse/MM-16277
> MM-16277 Update NPS plugin to v1.0.0

- app/team.go
- app/user.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
This pull request migrates the `GetByInviteId` in the Team store to use Sync by default. I followed the instructions laid out in the issue description and updated all relevant files.
Resolves #11127
> [MM-16171] Migrate "Team.GetByInviteId" to Sync by default

- app/plugin.go
Instead of going though the active plugins to find disabled we go though all plugins because some may have failed to start, but still need disabling.
> MM-16295 Properly disabling plugins that are not marked as running.

- api4/user_test.go
- app/session.go
- model/session.go
- store/sqlstore/upgrade.go
- web/context.go
Adds a prop to sessions created by bot access tokens to exclude them from being disabled when the `EnableUserAccessTokens` setting is false. 
Needs a migration for any existing sessions.
https://mattermost.atlassian.net/browse/MM-16148
> Fix bots being unable to post when personal access tokens are disabled.

- api4/apitestlib.go
- app/import_functions.go
- app/post.go
- app/slackimport.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/compliance_store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
- store/storetest/preference_store.go
- store/storetest/reaction_store.go
- store/storetest/user_store.go
This PR Migrates `Post.Save` to Sync by default in `Post Store` and updates all referencing files to not handle the response from a channel.
Fixed #10987
> [MM-15841] Store: Migrate "Post.Save" to Sync by default

- app/post.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
Migrate `GetPostsSince` to sync by default, removing the `return.Do `wrapper.
Fixes #10976
> Migrate "Post.GetPostsSince" to Sync by default #10976

- api4/post.go
- api4/post_test.go
- app/plugin_api.go
- app/post.go
- i18n/en.json
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/mocks/PostStore.go
- store/storetest/post_store.go
This PR intends to finalize unread API so the 'post-list-improvements' branch could finally submitted against master.
It includes:
- fix to failing TestGetPostsForChannelAroundLastUnread
- reverts unnecessary change to GetPostsSince - https://github.com/mattermost/mattermost-server/pull/11039/commits/15fb9a4238a568a05bb3a0a874c59169224fd2aa
- migrate the new functions - GetPostAfterTime and GetPostBeforeTime - to sync by default - https://github.com/mattermost/mattermost-server/pull/11039/commits/ce3540428fb137bafbf3a69949e16a53a28c297e
This PR was originally submitted as https://github.com/mattermost/mattermost-server/pull/10861.  However, I messed up that PR and `unread-posts-api` branch.
I copied over the comments made by HH.  Sorry for inconvenience in reviewing this PR.
Jira ticket: …
> MM-15569 Fixes failing test on TestGetPostsForChannelAroundLastUnread

- app/analytics.go
- app/diagnostics.go
- app/helper_test.go
- app/import_functions_test.go
- app/security_update_check.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
+ Modified team_store.AnalyticsTeamCount to return (int64, *model.AppError) instead of store.StoreChannel.
+ Updated the mock store to reflect new return value.
+ Updated referencing code to handle new sync return value.
This PR modifies team_store.AnalyticsTeamCount to return (int64, *mode.AppError) instead of a store.StoreChannel. This will make the call sync.
[MM-16173](https://mattermost.atlassian.net/browse/MM-16173)
Fixes #11126
> app/analytics.go
I moved the var down in the method body. This was to let the openChan and privateChan run their async code and then we block on the analytics team count. I know some people prefer to have all the var initialized at the top of the method, so I could move that around if you want.
> security_update_check.go 
> diagnostics.go
The default …
> [MM-16173] Migrate Team.AnalyticsTeamCount to Sync by default #11126

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrates `Channel.GetChannelCounts` to sync by default.
https://mattermost.atlassian.net/browse/MM-16326
Fixes #11163
> Channel.GetChannelCounts to sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR migrates `Channel.GetByNames` to sync by default. Fixes #11172  
https://mattermost.atlassian.net/browse/MM-16317
> Migrate Channel.GetByNames to sync by default

- api4/channel.go
- api4/channel_test.go
- app/group.go
- model/client4.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
Adds new API endpoint + (App & Client & Store) to retrieve the difference between the set of channel members and given group members.
This is the channel equivalent of https://github.com/mattermost/mattermost-server/pull/11176.
https://mattermost.atlassian.net/browse/MM-16224
> MM-16224: Adds new API endpoint + (App & Client & Store) to retrieve the difference between the set of channel members and given group members.

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
Migrates `Channel.GetDeleted` to sync by default. Fix #11168 
https://mattermost.atlassian.net/browse/MM-16320
> Channel.GetDeleted to sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR migrates the 3 methods described above to sync by default.
The first goal of this PR was to resolve #11213 but I had to modify some internal shared functions and that pushes me to refactor `Channel.SearchInTeam` and `Channel.SearchMore`.
Some details [here](https://github.com/mattermost/mattermost-server/issues/11213#issuecomment-502750845)
https://mattermost.atlassian.net/browse/MM-16347
> Migrates Channel.AutocompleteInTeam, Channel.SearchInTeam and Channel.SearchMore

- api4/user.go
Enables the display of a message that Mattermost has reached its maximum configured number of users accounts or team members.
https://mattermost.atlassian.net/browse/MM-15788
> MM-15788: Unmasks errors related to max team members and accounts.

- app/channel.go
- app/config.go
- app/post.go
- app/user.go
This is a simple implementation of a fallback mechanism in case that an Elasticsearch query fails. Instead of simply reporting the error, it logs it and tries to run the same query on the database.
https://mattermost.atlassian.net/browse/MM-15811
> [MM-15811] Adds fallback mechanism for elasticsearch queries

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR will Migrate `Channel.GetMembersByIds` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11259
> [MM-11259] Migrate 'Channel.GetMembersByIds' to Sync by default

- app/channel.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR will migrate `Channel.GetMembers` to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11227
> [MM-11227] Migrate "Channel.GetMembers" to Sync by default

- Makefile
Otherwise commands will look like this:
```
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
ignoring go.mod;
see 'go help modules'
```
> Run go get commands explicitly without modules

- api4/system.go
- api4/system_test.go
- model/client4.go
- services/filesstore/localstore.go
- services/filesstore/s3store.go
This change adds the option for additional server health checks
to be performed when the system ping endpoint is hit. An additional
field 'getserverstatus' is required to run the enhanced health
checks to ensure previous default ping behavior is not modified.
https://mattermost.atlassian.net/browse/MM-16032
> [MM-16032] Add system ping endpoint health checks

- build/Jenkinsfile.pr
This PR changes the way we tag the docker image for PRS. before we were using the PR + number to tag the image. the proposed idea is the use the short commit hash.
This will make the things  easier when we request a test server using the mattermost cloud infra, as well as the update of the test server
Also, we need to do a clean checkout to get the git commit hash to use to tag the docker image, when jenkins checkout it merges master in top of the PR which produce a new git hash and this is not store in the PR in github, so we need to get the git hash from github to use to tag the image and in sequence use in the test servers (using the cloud infra)
Jira: https://mattermost.atlassian.net/browse/MM-16411
> [MM-16411] tagging the docker image using the sha instead of the PR number

- cmd/mattermost/commands/config.go
- cmd/mattermost/commands/utils.go
- cmd/mattermost/commands/utils_test.go
Print config ordered by key alphabetically for easy diffing of two different versions.
https://mattermost.atlassian.net/browse/MM-16439
> MM-16439: Print config ordered by key alphabetically for easy diff.

- api4/channel.go
- api4/channel_test.go
- api4/user.go
- api4/user_test.go
- app/channel.go
- app/user.go
- i18n/en.json
- model/client4.go
- store/sqlstore/channel_store.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Adds a `/search_group` endpoint that will return the group channels whose members' usernames match the search term.
https://mattermost.atlassian.net/browse/MM-13500
> [MM-13500] Adds channel /search_group endpoint

- build/Jenkinsfile.pr
only perform a clean checkout when is a PR, since we are pushing the docker image for a PR as well
> fix the clean checkou and only check in PR

- api4/team.go
- api4/team_test.go
- app/team.go
- model/client4.go
- model/team.go
- web/params.go
Adds ability to retrieve the total count of teams for use by paginated teams views.
https://mattermost.atlassian.net/browse/MM-16500
> MM-16500: Adds ability to retrieve the total count of teams via the API.

- model/config.go
- model/config_test.go
SMTP password should be redacted in system console.
Fix Santize function to be the opposite of the Desanitize function for
the config file, and add a unit test for Sanitize.
https://mattermost.atlassian.net/browse/MM-16474
> MM-16474: SMTP password should be redacted in system console.

- app/diagnostics.go
- app/server.go
- model/config.go
- plugin/health_check.go
This PR removes the config value `PluginSettings.EnableHealthCheck`, as it has been determined that there isn't a practical reason why we would want admins to turn off the health check functionality. Discussion on this is here https://github.com/mattermost/mattermost-webapp/pull/2959
https://mattermost.atlassian.net/browse/MM-16378
> [MM-16378] Remove "enable plugin health check" config option

- app/channel.go
- app/email_batching.go
- app/user.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR makes `Channel.GetMembersForUser` to sync by default.
https://mattermost.atlassian.net/browse/MM-16345
Fixes #11215
> Migrates Channel.GetMembersForUser to sync by default

- app/notification_push.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
This PR Migrates `TeamStore.GetChannelUnreadsForAllTeams` to Sync by default in `Team Store` and updates all referencing files to not handle the response from a channel but instead the response and the error directly.
Ticket Link
Fixes #11395
> [MM-16561] Store: Migrate UserStore.GetUnreadCount to sync as default

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.SearchWithoutTeam" to Sync. Functions `User.SearchWithoutTeam`  returns `([]*model.User, *model.AppError)` instead of `store.StoreChannel` now.
https://mattermost.atlassian.net/browse/MM-16570
> Migrate "User.SearchWithoutTeam" to Sync by default

- api4/channel_test.go
- api4/team_test.go
- app/group.go
- app/group_test.go
- app/syncables_test.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/group_store.go
- store/storetest/mocks/GroupStore.go
- store/storetest/user_store.go
Changes a method name from `CreateOrRestore...` to `Upsert...`. Removes "error" case where the record already exists and is un-deleted. It's the desired state.
n/a
https://github.com/mattermost/enterprise/pull/464
> Changes method name, removes error case.

- plugin/helpers.go
- plugin/helpers_bots.go
- plugin/helpers_bots_test.go
- plugin/plugintest/helpers.go
This pull request adds the helper methods KVGet, KVSet, KVSetWithExpiry, and KVCompareAndSet to the Helpers interface in the plugin package.
Jira Ticket: https://mattermost.atlassian.net/browse/MM-8602
Fixes https://github.com/mattermost/mattermost-server/issues/11193
> Add KV helper methods to Helpers interface

- app/analytics.go
- app/diagnostics.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.AnalyticsGetInactiveUsersCount" to Sync by default
Fixes https://github.com/mattermost/mattermost-server/issues/11385
> GH-11385 Migrate User.AnalyticsGetInactiveUsersCount to Sync by default

- model/manifest.go
Markdown support for rendering plugin settings in the system console is inconsistent. Let's start by at least documenting where it is supported.
This documentation is automatically extracted onto https://developers.mattermost.com/extend/plugins/manifest-reference/.
https://mattermost.atlassian.net/browse/MM-16637
> Document markdown-enabled manifest fields.

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
Migrate "User.ResetLastPictureUpdate" to Sync by default
https://mattermost.atlassian.net/browse/MM-16652
Fixes #11468
> [MM-16652] Migrate "User.ResetLastPictureUpdate" to Sync by default

- app/security_update_check.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate "User.GetSystemAdminProfiles" to Sync by default and updates any impacted code.
Fixes https://github.com/mattermost/mattermost-server/issues/11448
> [MM-16672] Migrate "User.GetSystemAdminProfiles" to Sync by default

- app/login.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
This PR migrates GetForLogin in the Store layer to be sync by default
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-16668)
#11452
> SyncStore: Migrate User.GetForLogin method to Sync 

- app/login.go
- app/session.go
- app/session_test.go
- app/user.go
- app/web_conn.go
- i18n/en.json
- model/session.go
- store/sqlstore/session_store.go
- store/store.go
- store/storetest/mocks/SessionStore.go
Avoiding leaking users data through websockets for guest accounts. Now the
guest accounts only receive update notifications from users that they can see.
[MM-15810](https://mattermost.atlassian.net/browse/MM-15810)
> Avoiding leaking users data through websockets for guest accounts

- api4/command.go
- api4/command_test.go
This PR adds an additional check to the listCommands API handler to validate that the requesting user is actually a team member of the team.
https://mattermost.atlassian.net/browse/MM-16698
> [MM-16698] Rework membership validation in list command handler

- app/admin.go
- app/email.go
- app/email_batching.go
- app/notification_email.go
- app/plugin_api.go
- services/mailservice/mail.go
This PR moves the conditional that checks for the `EmailSettings.SendEmailNotifications` config parameter from the email service to the application layer, and splits the `SendMail` function into two: `SendNotificationMail` that will send nothing if the config is not enabled, and `SendMail` that will send the email even with the check disabled.
This allows the platform to send email invites when the email notifications config option is disabled.
https://mattermost.atlassian.net/browse/MM-15661
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3037)
> [MM-15661] Create SendNotificationEmail and move config option check to it

- app/notification.go
- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
This PR migrates GetProfilesByUsernames in the Store layer to be sync by default
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-16663)
Fixes #11457
> Migrate "User.GetProfilesByUsernames" to Sync by default

- config/common.go
- config/database_test.go
- config/environment.go
- config/file_test.go
- We're using reflection to find the original config value and then find the place in the new config that we want to `Set` to the original config value. The problem was, on the first recursion we were sending in the raw interface of the second (and third, and forth, etc) levels. This meant that second+ levels were no longer settable. So, recurse on the value itself (which we got from the config pointer, so it is settable).
- Added more tests, which caught another problem I didn't know of: the loadedCfgWithoutEnvOverrides was not being initialized with default values. This caused a problem if you wanted to set the active config to those (non-environment-overriden) values -- you would be trying to set the config values to a nil pointer, which you can't do. = panic
- It doesn't look like …
> [MM-16719] Setting the MM_SQLSETTINGS_DATASOURCEREPLICAS environment variable breaks the server startup

- plugin/helpers.go
- plugin/scheduler/scheduler.go
- store/sqlstore/upgrade.go
The Jobs infrastructure isn't currently setup for running frequent jobs,
as it spams the Jobs table with useless records. Update the plugin job
interval to run less frequently -- since the cleanup doesn't affect
semantics anyway -- and clean up the previously created entries in the Jobs table.
https://mattermost.atlassian.net/browse/MM-16796
> MM-16796: reduce plugin job interval to once per day

- app/export.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Summary
Migrate `Team.GetTeamMembersForExport` to sync by default.
Fixes https://github.com/mattermost/mattermost-server/issues/11546
> [MM-16782] Migrate "Team.GetTeamMembersForExport" to Sync by default

- app/plugin_key_value_store.go
- store/sqlstore/plugin_store.go
- store/store.go
- store/storetest/mocks/PluginStore.go
- store/storetest/plugin_store.go
This PR migrates Plugin.Get in the Store layer to be sync by default
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-16790)
Fixes #11538
> [MM-16790] Migrate Plugin.Get to Sync by default

- app/import.go
- app/import_test.go
The way that we were detecting the first import iteration was colliding with the "empty type" case for import.
[MM-16548](https://mattermost.atlassian.net/browse/MM-16548)
> MM-16548: Fixing bug with empty type in the second line of the bulk import

- app/user.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
Transforms "Team.UserBelongsToTeams" to a synchronous method, updates the calls and removes a wrapper for the async method.
Fixes https://github.com/mattermost/mattermost-server/issues/11545
> MM-16783 Migrate "Team.UserBelongsToTeams" to Sync by default

- app/notification.go
- app/notification_test.go
This change does the following:
- Fixes a bug where mention counts could be set incorrectly for
users in the database.
- Updates the original notification unit test to check for more
possible notification issues.
- Adds a new unit test that performs mention count checking to
prevent a regression to this fix.
https://mattermost.atlassian.net/browse/MM-16647
> [MM-16647] Fix issue with setting mention count

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
This PR migrates `User.GetProfilesWithoutTeam` to Sync by default.
https://github.com/mattermost/mattermost-server/issues/11458
I am still very new to Golang, please let me know if anything doesn't conform to proper style, as I am very eager to learn (and to contribute to Mattermost)!
> Migrate "User.GetProfilesWithoutTeam" to Sync by default

- app/file.go
- app/notification.go
- app/notification_email.go
- app/post.go
- store/sqlstore/file_info_store.go
- store/store.go
- store/storetest/file_info_store.go
- store/storetest/mocks/FileInfoStore.go
Adds the `includeDeleted` flag to the `GetForPost` function so the global relay export can fetch the deleted files for a given post.
https://mattermost.atlassian.net/browse/MM-15925
- [Has enterprise changes](https://github.com/mattermost/enterprise/pull/469)
> [MM-15925] Add includeDeleted flag to GetForPost in FileInfoStore

- store/sqlstore/post_store.go
- store/storetest/post_store.go
The missing posts problem was caused by a few things:
1. GetPostsSince could sometimes cache that the latest post in the channel was at time 0. This happened whenever a call to it would return an empty post list ([link](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/post_store.go#L557)). As lost as GetPostsSince has a 0 timestamp cached, future calls to it will always return an empty list ([link](https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/post_store.go#L509)).
2. GetPostsSince and GetEtag share a cache, so when a timestamp of 0 gets cached, it can cause any API to get posts to return stale data.
3. The previous two bugs have existed since 2016. The reason that this started to happen more frequently in 5.12 is that the web app …
> MM-16921 Fix getPostsSince caching invalid data

- api4/plugin_test.go
- app/plugin_install.go
- model/plugin_event_data.go
As per conversation https://github.com/mattermost/mattermost-server/pull/11615#discussion_r304061674 removing `FileStorePath` from `PluginEventData`
> Removing FileStorePath from PluginEventData

- app/diagnostics.go
- store/sqlstore/team_store.go
- store/store.go
- store/storetest/mocks/TeamStore.go
- store/storetest/team_store.go
Transforms "Team.AnalyticsGetTeamCountForScheme" into a synchronous call.
Fixes https://github.com/mattermost/mattermost-server/issues/11548
> MM-16780 Migrate "Team.AnalyticsGetTeamCountForScheme" to Sync by default

- store/sqlstore/team_store.go
This PR replaces the string concatenation in UserBelongsToTeams with a strings.Builder.
None, minor improvement
> Use a strings.Builder to create the idQuery string

- app/plugin_requests.go
- web/handlers.go
This pull request implements enhanced logging for CSRF warnings, adding the following information to each request:
- Remote Adddress
- Path
- User ID
- Session ID
The goal of this pull request is to simplify debugging of CSRF warnings.
> Enhance logging of CSRF Warning

- app/plugin.go
- app/plugin_install.go
- i18n/en.json
- services/filesstore/filesstore_test.go
- services/filesstore/localstore.go
- services/filesstore/s3store.go
- Updated `s3store.go` to return same result when querying `plugins` vs `plugins/`
- Updated `localstore.go` to not return an error when directory is not found
- Added unit test to cover new functionality
Once approved i'll merge this into https://github.com/mattermost/mattermost-server/pull/11608 to do the final testing and then merge it into the feature branch
> Fix plugin path

- app/plugin.go
Small change to install pre-packaged plugins only locally, without propagating to the file store or notifying the cluster, after the plugin sync at server startup.
> Install prepackaged plugins locally only

- app/notification.go
- model/user.go
- model/user_test.go
When bots are mentioned in a channel they are not a member of, do not include them in the system message suggesting to add them to the channel.
https://mattermost.atlassian.net/browse/MM-16744
Fixes https://github.com/mattermost/mattermost-server/issues/11329
> [MM-16744] Filter bots out of notifications for members not in channel

- store/sqlstore/post_store.go
This change modifies the database query used by the getPostsAround()
method in order to improve the performance of loading posts when
scrolling through a channel.
https://github.com/mattermost/mattermost-server/pull/11662
https://mattermost.atlassian.net/browse/MM-16936
> Improve DB performance on getPostsAround()

- app/server.go
The job workers and cluster discovery components require access to the database during shutdown. To avoid issues, we leave the database open until the last step of the shutdown process.
Fixes [MM-16951].
[MM-16951]: https://mattermost.atlassian.net/browse/MM-16951
> MM-16951 Close database connections last on shutdown

- app/diagnostics.go
Track if the default value is used for NetworkInterface, BindAddress and AdvertiseAddress.
Do not track the actual value, as this could expose sensitive data of the system.
PRs that added the settings:
- https://github.com/mattermost/mattermost-server/pull/11283
- https://github.com/mattermost/mattermost-server/pull/10917
> Add telemetry for new cluster settings

- config/client.go
Exposing enforce mfa in client config to decide properly if i need to redirect you to the mfa activation when enforce mfa is enforced for all users.
[MM-17196](https://mattermost.atlassian.net/browse/MM-17196)
> Exposing enforce mfa in client config

- utils/test_files_compiler.go
Output go build output on errors when compiling embedded unit test plugins
no ticket
> no ticket: Show go compile output for embedded unit test plugins

- app/user.go
- store/sqlstore/user_store.go
- store/store.go
- store/storetest/mocks/UserStore.go
- store/storetest/user_store.go
Migrate `User.GetProfilesInChannel` to sync by default.
Fixes #11462
> [MM-16658] Migrate User.GetProfilesInChannel to Sync by default #11462

- Makefile
- api4/apitestlib.go
- build/docker-compose.yml
Fixing jenkins build failures caused by elastic docker container running out of memory and resulting in flaky elastic search tests
- Bumping up JVM heapsize to `512m` for elastic search container
- Disabled `cfg.ElasticsearchSettings.Sniff` for tests to allow running enterprise tests locally on Mac OSX
Example build: https://build.mattermost.com/blue/organizations/jenkins/mp%2Fmattermost-server-pr-new/detail/PR-11698/2/tests/
Fixes https://mattermost.atlassian.net/browse/MM-16935
> MM-16935 - Flaky test: Elastic Search IndexChannel Error

- store/storetest/channel_store.go
- store/storetest/post_store.go
- store/storetest/status_store.go
- store/storetest/team_store.go
There are a handful of “reserved” team names that will be rejected if found at the start of the team name – e.g. “api21251251” or “error1251251”. Turns out we just got really unlucky and a model.NewId invocation generated just such a collision. I've changed all such random generations to include a prefix (mimicking other such tests).
https://mattermost.atlassian.net/browse/MM-17053
> MM-17053: avoid colliding with reserved team names

- api4/channel.go
- api4/channel_test.go
- app/channel.go
- app/channel_test.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
When a user that doesn't have the `PERMISSION_LIST_TEAM_CHANNELS` performs a channel search for a team, instead of responding with a 403, this PR modifies the behaviour of the endpoint, performing the search over the channels that the user is a member of.
https://mattermost.atlassian.net/browse/MM-17194
> [MM-17194] Add search channels for user in case the user doesn't have the list channels permission

- store/storetest/channel_store.go
Address more model.GetMillis() races.
https://mattermost.atlassian.net/browse/MM-17325
> MM-17235: fix flaky TestChannelStore tests

- store/storetest/channel_store.go
Removed extra unnecessary save done on a scheme object in the GetChannelsByScheme test. This could have been causing the intermittent error of `Message:"store.sql_scheme.save.update.app_error", DetailedError:"no record to update"` seen in the CI build tests. 
Possibly fixes [MM-16838](https://mattermost.atlassian.net/browse/MM-16838)
> MM-16838 - Fix for flaky GetChannelsByScheme test

- store/storetest/channel_store.go
Cherry pick of #11701 on release-5.14.
- #11701: Removed unnessary save in GetChannelsByScheme test
> Automated cherry pick of #11701

- store/storetest/group_store.go
- testlib/helper.go
`GroupStore.UpsertMember` uses `CreateAt: model.GetMillis()` to update `GroupMember`. When updated in quick successions, MySQL implementation of RowsAffected returns 0, even if the row exists but no actual changes were made, which eventually causes the test to fail.
- Went with the retry approach for now but in the future we should consider looking at https://github.com/go-sql-driver/mysql#clientfoundrows. Started a discussion: https://community.mattermost.com/core/pl/ugqb4pnfjinobnf6wnrff9gyka
Fixes https://mattermost.atlassian.net/browse/MM-17311
> MM-17311 - Flaky TestGroupStore/UpsertMember

- testlib/helper.go
When a test run is stopped by a panic, before it can go and log that error, `MainHelper.Close()` calls `os.Exit(...)` and the panic is lost, making it harder to debug what caused the error. Adding a `recover` block to catch the panic and log the error.
> Log panic when exiting (if any)

- api4/post_test.go
- app/post.go
Fix the new `/posts/unreads` endpoint to handle the case when the selected "pivot post" is itself part of a thread whose replies are not fully in the window. If the corresponding root post was never fetched, the frontend would assume the root post was deleted and render a data retention policy explanation.
Note that I've broken up the PR into multiple commits that should be reviewed independently for the greatest clarity.
https://mattermost.atlassian.net/browse/MM-17339
> MM-17339: fix missing post thread

- app/export.go
- app/export_test.go
Bulk export fails with the following error log: "Error: SqlUserStore.Get: Unable to find the user., user_id=XXXXXXXXXXXXXXXXX"
The cause of this issue is little complex.If executing the deleting user command, PermanentDeleteUser doesn't delete any reactions that deleting user add. So reactions that the deleted user add are left.After that, when executing bulk export, it collects all reactions and try to get user who add a reaction. It results in error of bulk export.
Fixes https://mattermost.atlassian.net/browse/MM-17224
> MM-17224 - Bulk export fails due to missing user

- services/mfa/mfa.go
- services/mfa/mfa_test.go
Address another classic case of `var err error` and then trying to assign a `*model.AppError`. We really need to switch to passing `error` everywhere.
https://mattermost.atlassian.net/browse/MM-17411
> MM-17411: fix err != nil check

- app/post_metadata.go
- app/post_metadata_test.go
We specify multiple Accept headers for the post metadata because we're either looking for image previews or HTML to scrape for OpenGraph metadata. The way that we were specifying both headers before was incorrect, so we'd sometimes get HTML results instead of an image for certain sites that serve multiple types of content on a single URL. This causes an OpenGraph preview to be displayed in certain places where we'd want an image preview to be displayed.
Oddly enough, the previous fix for this in https://github.com/mattermost/mattermost-server/pull/10241 did fix this issue for some websites (eg giphy.com), but not others (tenor.com)
https://mattermost.atlassian.net/browse/MM-17426
> MM-17426 Properly specify multiple Accept headers for post metadata

- services/mfa/mfa.go
- services/mfa/mfa_test.go
Cherry pick of #11736 on release-5.14.
- #11736: MM-17411: fix err != nil check
> Automated cherry pick of #11736

- Makefile
- cmd/mattermost/commands/sampledata.go
I've deployed a master version and tried to run the `./bin/mattermost sampledata -w 4 -u 60` and got this error
```
Error: User.IsValid: Your password must contain at least 10 characters made up of at least one lowercase letter, at least one uppercase letter, at least one number, and at least one symbol (e.g. "~!@#$%^&*()").,  (line: 24)
```
This PR update the password to match the security enforcement.
please let me know if we need to use other passwd strings.
https://mattermost.atlassian.net/browse/MM-17493
> update sampledata users passwords

- app/email.go
Allows to send account related emails when the notifications are disabled.
https://mattermost.atlassian.net/browse/MM-16856
- [Has webapp changes](https://github.com/mattermost/mattermost-webapp/pull/3137)
> [MM-16856] Allow account related mails to be sent with notifications disabled

- app/user.go
When registering a new user, this PR uses the `AddChannelMember` method instead of `AddUserToChannel`, triggering indexing, the plugins and the system message for the newly registered user.
https://mattermost.atlassian.net/browse/MM-17214
> [MM-17214] Use AddChannelMember method when registering a new guest

- app/syncables.go
Cherry pick of #11790 on release-5.14.
- #11790: MM-17496: Skip adding user to default channel (rather than
/cc  @mkraft
> Automated cherry pick of #11790

- app/brand.go
- app/team.go
- app/user.go
Due to a bug in creating the user-friendly error message, attempts to upload special image files with the size exceeding https://github.com/mattermost/mattermost-server/blob/4734215a114ef7fd7dcf4ccf3f72a7568b170229/model/file.go#L12 was leading to a crash in the server.
https://mattermost.atlassian.net/browse/MM-17607
> MM-17607: large [brand, team, profile] images crash the server

- app/notification.go
- app/notification_test.go
This is part of a series of changes to separate the code that figures out what users are mentioned by a given message from the code that sends notifications and handles the other side effects of mentioning a user. We're doing this so that we can reuse the mention detecting code for the Mark as Unread feature.
----
So far, this is just extracting this logic into its own method, but I'll eventually be moving this out of the mention parsing section of `App.SendNotifications`.
There's one small functional change here that shouldn't make any real difference, but the previous version of the code would synchronously find what users had been mentioned before asynchronously warning the sender of it. I made it all happen asynchronously from the rest of sendNotifications so that I could test …
> MM-17071 Extract and add tests for handling of out of channel mentions

- Makefile
Same change to server repo as done in https://github.com/mattermost/mattermost-webapp/pull/3405 to include `i18n-extract` in `make help` output.
n/a
> Includes 'i18n-extract' in 'make help' output.

- api4/apitestlib.go
- api4/config_test.go
- app/helper_test.go
- app/plugin_api_test.go
- config/common.go
- config/common_test.go
- config/database.go
- config/database_test.go
- config/file.go
- config/file_test.go
- config/memory.go
- config/memory_test.go
- migrations/helper_test.go
- model/config.go
- web/web_test.go
When loading the config from the backing store we were correctly overriding config settings using the environment variables but when setting the config after an API request, a cluster configuration propagation event, or by some other method we were not applying the environment variable overrides. This was hard to notice when not running in HA because the API request from a change in the system console already had the environment variable overrides but running in HA with different app servers using different environment variable overrides (like we do on community.mattermost.com) the bug became more apparent.
https://mattermost.atlassian.net/browse/MM-16725
> MM-16725 Respect env var overrides when setting config

- store/sqlstore/group_store.go
- store/storetest/group_store.go
Cherry pick of #11829 on release-5.14.
- #11829: MM-17432: Removes deactivated users from the group member
/cc  @mkraft
> Automated cherry pick of #11829

- api4/post_test.go
- app/plugin_api_test.go
- store/sqlstore/file_info_store.go
- store/storetest/file_info_store.go
As part of https://mattermost.atlassian.net/browse/MM-13718, the file info store was modified to only attach a file to a post on two conditions:
* if the `PostId` was already empty
* and if the `CreatorId` matched the requesting user
Unfortunately, files uploaded by plugins are marked as being created by `nouser` (literally), and thus fail the check when attaching a file to a post created for a real user. This PR effectively tweaks the query to allow a `CreatorId` of `nouser` too. It's not possible to leverage this via the API proper, since it's not possible to upload a file outside of a user context.
Technically, if a plugin uploads a file and another user knows that file id, they can claim it for themselves on a new post. I don't know the full history of `nouser`, but I'm suspecting …
> MM-17438: allow attaching nouser files to posts

- api4/post.go
- api4/post_test.go
The `updatePost` endpoint incorrectly stripped the files from posts. The `patchPost` had the same code, but executed the `post.Patch` operation, which explicitly ignores a `nil` `FileIds`. The update code path accepted the `nil` value and cleared things out.
This PR is broken up into individual commits if you'd like to review it that way.
https://mattermost.atlassian.net/browse/MM-17412
> MM-17412: update post incorrectly removing files

- app/diagnostics.go
- app/server.go
- mlog/log.go
- model/config.go
- plugin/health_check.go
- plugin/health_check_test.go
Revert https://github.com/mattermost/mattermost-server/commit/4e5f6fcfbc85ea24788241c716862e1833c6f60e, restoring the ability to disable plugin health checks.
I've also thrown in a commit here to improve logging of the job, as well as fully disable it whenever plugins are themselves disabled.
I'll be submitting a separate PR to reduce the health check to just the ping interactions vs. the process signals.
@prapti, I suspect we'll verify this one after merging, along with the fix for https://mattermost.atlassian.net/browse/MM-17488.
https://mattermost.atlassian.net/browse/MM-16378
> MM-16378: revert plugin health check config removal

- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
When using full text search in postgres and not explicitly stating the search configuration, [default_text_search_config](https://www.postgresql.org/docs/9.4/runtime-config-client.html#GUC-DEFAULT-TEXT-SEARCH-CONFIG) is used, which can differ from the `english` that we use when creating the indexes depending on the `lc_ctype` locale of the host, and causing searches not to return results.
This PR explicits the same config used when creating the indexes to avoid a missmatch.
https://mattermost.atlassian.net/browse/MM-17758
> [MM-17758] Explicits the search configuration when using full text search in postgres

- Makefile
- build/docker-compose.common.yml
- build/docker-compose.yml
- docker-compose.yaml
We use tmpfs for CI builds to speed things up, but this is unsuitable for local development. Also, don't use `--no-ansi` in the `Makefile` to allow colours to show up.
> fix tmpfs usage

- app/diagnostics.go
- app/post_metadata.go
- app/post_metadata_test.go
- config/client.go
- model/config.go
This is adding a new setting to enable/disable SVG rendering in the web app. The setting will be disabled by default on new installs, and enabled by default on existing installs to maintain backwards compatibility.
The mobile app currently doesn't render SVGs, so no changes are required to support it there.
https://mattermost.atlassian.net/browse/MM-17609
https://github.com/mattermost/mattermost-webapp/pull/3437
> MM-17609 Add EnableSVGs setting 

- app/channel.go
Currently when a user signs up for a team and joins that team, they will automatically join `town-square` and `off-topic` and other channels mentioned in `TeamSettings.ExperimentalDefaultChannels` in `config.js` however the websocket message `user_added` is not broadcasted. This PR fixes this problem.
Fixes https://github.com/mattermost/mattermost-server/issues/11823
[Jira Link](https://mattermost.atlassian.net/browse/MM-17604)
> [MM-17604] Fix websocket message not being broadcasted when a user automatically joins a channel

- i18n/en.json
This functionality was changed in 5.14, but the contributor who made the change forgot to update the error message.
https://mattermost.atlassian.net/browse/MM-17492
> MM-17492 Update error message for CustomURLSchemes setting

- api4/plugin_test.go
- app/plugin.go
- app/plugin_install.go
- i18n/en.json
- plugin/environment.go
- Disable plugin on removal
- Updated cluster peers synchronization logic to notify clients ONLY after all cluster peers have been fully updated, as opposed to notifying them when one of them was updated
- Re-activates plugin on upgrade via `PluginEnvironment` as opposed to `EnablePlugin` api which caused a config change + notify cluster peer of a config change and wreaked havoc -- true story.
- Added a unit test to confirm `disabled` state on plugin re-install
- Not able to write a unit test to test cluster functionality, but hopefully in the future we can add isolated env to test these cases and lock down behaviour
- Wrote a mini stress script that does the following. See attached script to the jira.
-- Removed plugin 1.0
-- Installs plugin 1.0
-- Enables plugin
-- Installs plugin 2.0 …
> MM-17087 - Disable plugin on removal

- app/notification.go
- app/notification_test.go
- model/user.go
- model/user_test.go
Following the spec those push notifications where the sender name is the username we need to prepend an `@` sign so it is clear that is the username of the person sending the message. The current user model has a function `GetDisplayName` that will return the display name based on the teammateDisplayName setting and it is used in various places, so this PR adds a new function `GetDisplayNameWithPrefix` that is basically a copy of the previous one but will add a prefix to the username.
https://mattermost.atlassian.net/browse/MM-16093
> Add @ prefix for sender username in push notifications

- app/notification.go
- app/notification_test.go
- model/user.go
- model/user_test.go
Cherry pick of #11934 on release-5.15.
- #11934: Add @ prefix for sender username in push notifications
/cc  @enahum
> Automated cherry pick of #11934

- api4/user.go
- api4/user_test.go
- model/user.go
This pull request adds additional filtering to the user object created as part of the signup flow.
https://mattermost.atlassian.net/browse/MM-17958
> [MM-17958] Add additional input validation for user creation

- plugin/environment.go
- plugin/health_check.go
The enterprise circleci pipeline is failing for quite some time and the failures are related to memory issues.
in the job logs we saw this error:
```
goroutine 566288 [select]:
github.com/mattermost/mattermost-server/plugin.(*PluginHealthCheckJob).Start.func1(0xc0cb2ef700)
/go/src/github.com/mattermost/mattermost-server/plugin/health_check.go:60 +0x162
created by github.com/mattermost/mattermost-server/plugin.(*PluginHealthCheckJob).Start
/go/src/github.com/mattermost/mattermost-server/plugin/health_check.go:51 +0x70
```
The root cause was not shutting down the plugin health checks when the server stops. In the CI pipeline, this resulted in hundreds of goroutines left holding onto plugin environments and all the associated memory.
> Stop plugin healthchecks before shutting down plugins

- model/config.go
Before the docker compose change for the development environment, the default
SMTP port was the previous inbucket port, now the inbucket port has change, so
the default port should change too.
> Changing default smtp port to use the new inbucket port as default

- app/notification.go
- app/notification_test.go
When a `---` message is posted the [trimmed word here](https://github.com/mattermost/mattermost-server/blob/MM-17300/app/notification.go#L746) is an empty string. If a profile's notify props includes an empty string once split, then the [key here](https://github.com/mattermost/mattermost-server/blob/MM-17300/app/notification.go#L595) is an empty string causing that empty string to be used as a keyword for all profile ids in that channel and sending a notification to all channel members.
https://mattermost.atlassian.net/browse/MM-17300
> [MM-17300] Do not add empty string as a keyword key

- app/notification.go
- app/notification_test.go
Cherry pick of #11961 on release-5.15.
- #11961: Do not add empty string as a keyword key
/cc  @migbot
> Automated cherry pick of #11961

- app/notification_email_test.go
- i18n/en.json
The fix for the double at sign is cause one @ sign is part of the translation string
https://mattermost.atlassian.net/browse/MM-18066
> Remove @ sign from app.notification.subject.direct.full translation

- app/notification_email_test.go
- i18n/en.json
Cherry pick of #11990 on release-5.15.
- #11990: Remove @ sign from app.notification.subject.direct.full
/cc  @enahum
> Automated cherry pick of #11990

- app/helper_test.go
- app/notification_push.go
- app/notification_push_test.go
When a user sets their mobile settings to send push notifications for all activity, we want to include all unread messages in the badge count.
* Im not sure if this additional code is idiomatic Go. Let me know if it can be changed.
https://mattermost.atlassian.net/browse/MM-18058
> [MM-18058] Use GetAnyUnreadPostCountForChannel for NotifyProps.push == all

- web/oauth.go
This PR resolves an issue with `{"status":"OK"}` flashing on the screen after signing on via SSO.  This occurs only on mobile. 
The issue was a call to `ReturnStatusOK()` which sends `{"status":"OK"}` through http.ResponseWriter.
I decided not to write a test for this case because 1) there aren't existing tests that exercise this part of the function and 2) the test would be written to check that nobody randomly decides to add this code back into the system.  
https://mattermost.atlassian.net/browse/MM-15886
> [MM-15886] Don't send {"status":"OK"} json response if mobile SSO login

- utils/test_files_compiler.go
git.apache.org is down since 31.09.2019 this migate the issue pointing the thrift to use github.com/apache/thrift
> When creating the go mod for plugin test replace git.apache.org/thrift.git to github.com/apache/thrift

- utils/test_files_compiler.go
Cherry pick of #12033 on release-5.15.
- #12033: when creating the go mod replace git.apache.org/thrift.git to
/cc  @cpanato
> Automated cherry pick of #12033

- app/channel.go
- app/channel_test.go
Do not count deleted channels when checking max channel limit. This is just matching the behaviour in the store code.
https://mattermost.atlassian.net/browse/MM-18038
> Do not count deleted channels when checking max channel limit

- app/command_msg.go
- app/command_msg_test.go
Guest users were allowed to `/msg` other users in the system even if they were not in a common team/channel. This PR fixes that by checking if the guest can see the user he/she's attempting to message.
https://mattermost.atlassian.net/browse/MM-17919
> [MM-17919] Add permission check for guest users before sending a /msg command

- plugin/helpers_kv.go
- plugin/helpers_kv_test.go
Returning a `nil` `*model.AppError` does not make a `nil` `error` interface. As a consequence, all of the KV* helper methods would always appear to fail, even if the underlying API call was successful.
Fix this mismatch by explicitly assigning `appErr` in the helpers and only ever returning a `nil` `error` interface. Extend unit tests to achieve 100% coverage of the associated files.
In the long run, we must change all function signatures to return the `error` interface instead of the abomination that is returning `*model.AppError` today.
https://mattermost.atlassian.net/browse/MM-18167
> MM-18167: fix KV* helpers error handling

- Makefile
This PR helps include recent bug fixes affecting users running early versions of Jira Server 7.x
https://mattermost.atlassian.net/browse/MM-18202
https://github.com/mattermost/mattermost-plugin-jira/pull/287
> [MM-18202] Bump jira plugin version to 2.1.1

- app/webhook_test.go
Convert app/webhooks_test.go t.Fatal calls into assert/require calls
[MM-18207](https://mattermost.atlassian.net/browse/MM-18207)
> Convert app/webhooks_test.go t.Fatal calls into assert/require calls

- api4/team.go
A `null` response from the endpoint was causing the reducer to fail with a javascript error. Initialising the teams variable to an empty slice ensures that the empty response will be an empty list, which the client is able to process correctly.
https://mattermost.atlassian.net/browse/MM-17219
> [MM-17219] Return an empty list instead of null when no teams

- app/plugin_hooks_test.go
This pr is in reference to migrating the tests from "app/plugin_hooks_test.go" to use testify. 
The t.Fatal have been replaced with require and the Errorf have been replaced by apt assert package methhods.
Fixes https://github.com/mattermost/mattermost-server/issues/12058
>  Convert  tests in "app/plugin_hooks_test.go" to use assert/require 

- app/notification_push_test.go
Replace t.Fatal with assert.Equals
Fixes https://github.com/mattermost/mattermost-server/issues/12067
> [MM-18319] Replace t.Fatal with assert.Equals

- app/opengraph_test.go
**Summary**
Migrates the t.fatal() calls to testify
**Ticket link**
https://mattermost.atlassian.net/browse/MM-18321
Fix #12065
> MM-18321 Replace t.fatal() calls to testify assert/require calls

- jobs/schedulers.go
Fixes panic caused by https://github.com/mattermost/mattermost-server/pull/12122
`schedulers.nextRunTimes[idx]` is `nil` in some circumstances so calling `.String()` on it causes a panic.
This was causing my local server to repeatedly crash.
> Fix panic in jobs structured logging.

- Makefile
Fixes https://mattermost.atlassian.net/browse/MM-18467, failed build
> Updated mattermost-plugin-jira to v2.1.2 to fix a failed build

- Makefile
Cherry pick of #12151 on release-5.15.
- #12151: Updated mattermost-plugin-jira to v2.1.2 to fix a failed
/cc  @levb
> Automated cherry pick of #12151

- app/command_groupmsg.go
- app/command_groupmsg_test.go
Restricting groupmsg command to only allow to create group chats with know people
[MM-18229](https://mattermost.atlassian.net/browse/MM-18229)
> Restricting groupmsg command to only allow to create group chats with know people

- model/user_search.go
Initialises the `UserSearch` struct before trying to decode the JSON to avoid null pointers in case the decoding fails
https://mattermost.atlassian.net/browse/MM-18544
> [MM-18544] Initialise UserSearch struct before trying to decode JSON

- app/file_test.go
Modify the calls to t.Fatal and the condition checks that lead to them, replacing them with calls to the testify require or assert
[MM-18376](https://mattermost.atlassian.net/browse/MM-18376)
Fixes https://github.com/mattermost/mattermost-server/issues/12105
> MM-18376 Migrate tests from "app/file_test.go" to use testify

- app/slackimport.go
Converting to structured logging the file app/slackimport.go
https://mattermost.atlassian.net/browse/MM-18262
> MM-18262 Converting to structured logging the file app/slackimport.go

- app/license_test.go
Convert app/license_test.go  t.Fatal calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12207
> Convert app/license_test.go  t.Fatal calls into assert/require calls

- app/command_mute_test.go
Migrate tests from "app/command_mute_test.go" to use assert calls instead of t.Fatal.
Fixes https://github.com/mattermost/mattermost-server/issues/12064
JIRA: https://mattermost.atlassian.net/browse/MM-18322
> Migrate tests from "app/command_mute_test.go" to use testify

- plugin/client_rpc.go
We've had a flaky unit test for a while that's actually exposed a bug in the `FileWillBeUploaded` hook: sometimes we allow the hook to return before the `io.Copy` in the goroutine completes. This manifested infrequently in the unit tests, and was also [spotted](https://community.mattermost.com/core/pl/oficg6nb9bb6igzz87fpumgxuo) by community member @scottleedavis before @streamer45 correctly identified the race condition at play.
I haven't been able to find a way to reliably reproduce this issue as a unit test -- but we /do/ know the existing unit tests have spotted the problem, so I'm counting on those to continue to help as such.
https://mattermost.atlassian.net/browse/MM-16479
> MM: 16479: ensure replacement file finishes io.Copy

- app/user_agent_test.go
Convert app/user_agent_test.go t.Fatal calls into assert/require calls
Fixes https://github.com/mattermost/mattermost-server/issues/12213
> Convert app/user_agent_test.go t.Fatal calls into assert/require calls

- app/notification_email_test.go
Convert app/notification_email_test.go t.Fatal calls into assert/require calls
https://github.com/mattermost/mattermost-server/issues/12211
Fixes https://github.com/mattermost/mattermost-server/issues/12211
> Convert app/notification_email_test.go t.Fatal calls into assert/require calls

- app/import_validators_test.go
Convert app/webhooks_test.go t.Fatal calls into assert/require calls
[MM-18317](https://mattermost.atlassian.net/browse/MM-18317)
Fixes https://github.com/mattermost/mattermost-server/issues/12069
> MM-18317 Migrate tests from import_validators_test.go to use testify

- model/version.go
Given that the release branch for 5.16 has been cut, we can safely bump the app version to 5.18 now. Please note that we will have to bump the version on the 5.17 release branch, after 5.16 is cut.
For more context see https://github.com/mattermost/mattermost-server/pull/12172
> Bump app version to 5.18

- store/layer_generators/main.go
- store/timer_layer.go
- web/handlers.go
We were using seconds for api metrics, and nanoseconds for store metrics, this
way both related metrics are consistent
> Use seconds instead of nanoseconds for the store time layer metrics

- app/post_metadata_test.go
This PR makes the `TestPreparePostForClient` and `TestPreparePostForClientWithImageProxy` tests use a local httptest server instead of hitting github.com directly during the tests.
There was an issue with intermittent failures of fetching the data from github at: https://github.com/mattermost/mattermost-server/blob/b8f0546c1936fd13c7af8df74b70dcbb0af4765d/app/post_metadata.go#L386-L394 After these changes, I've confirmed these tests pass with no internet connection.
https://mattermost.atlassian.net/browse/MM-18628
> [MM-18628] Fix flaky OpenGraph test

- store/sqlstore/group_store.go
Fix for scan error querying `TeamMembers` or `ChannelMembers` when the `SchemeGuest` column is `null`.
https://mattermost.atlassian.net/browse/MM-18668
> MM-18668: Fix for scan error selecting null SchemeGuest columns.

- model/config.go
Pivoting to locate the default marketplace at api.integrations.mattermost.com. This is effectively a data-only change, and thus has no unit tests.
https://mattermost.atlassian.net/browse/MM-18894
> MM-18894: Update production marketplace URL

- store/sqlstore/group_store.go
Cherry pick of #12370 on release-5.16.
- #12370: MM-18668: Fix for scan error selecting null SchemeGuest
/cc  @mkraft
> Automated cherry pick of #12370

- mlog/default.go
- mlog/log.go
This PR updates `mlog` to write console output to `os.Stderr ` by default.
https://mattermost.atlassian.net/browse/MM-18638
> [MM-18638] Send mlog console output to stderr

- cmd/mattermost/commands/server.go
We recently added support for handling SIGPIPE cleanly, in order to safely shutdown plugins in the event that the STDOUT/STDERR had been closed unexpectedly. Unfortunately, this signal is also emitted when writing to a closed socket connection: an event that occurs frequently for a webserver. Normally, if no signal handler is registered for same, the Go subsystem distinguishes the file descriptor and ignores those from the network. But once a handler is registered, all SIGPIPEs are passed through: and sadly there is no way to distinguish the original file descriptor.
We don't strictly need the SIGPIPE handling for development any longer since `make stop-server` no longer shuts down the logrus process which explained the majority of hanging plugin processes. It remains suboptimal that a …
> MM-18721: disable SIGPIPE handling

- Makefile
Adding `MM_NO_DOCKER` env variable to Makefile allowing developers to use his
own services (mysql, postgres, elasticsearch, minio, ldap, redis) instead of the
dockerized ones.
> Adding MM_NO_DOCKER env variable to Makefile

- Makefile
Bumper Jira plugin version to 2.2.0 - awaiting the release to be cut, see https://github.com/mattermost/mattermost-plugin-jira/pull/323
Fixes https://mattermost.atlassian.net/browse/MM-18451
> Bumped the Jira plugin to v2.2.0

- config/memory_test.go
- Migrate from using t.Fatal to using testify package. 
Fixes https://github.com/mattermost/mattermost-server/issues/12427
> migrate memory_test to use testify

- config/watcher_test.go
- utils/testutils/testutils.go
- Converted calls to `t.Fatal` into require calls.
- Added a helper function `wasCalled` to accomplish this which can be used in further issues like - #12429 and #12428. 
[MM-19022](https://mattermost.atlassian.net/browse/MM-19022)
Fixes https://github.com/mattermost/mattermost-server/issues/12430
> MM-19022: Convert config/watcher_test.go t.Fatal calls into require calls

- Makefile
- Send stderr to stdout during development
- logrus dev-readable output was stopped because of #12366 
- #12366
> Redirect stderr to stdout for dev-readable logrus output

- model/mfa_secret_test.go
Replace `t.Fatal` call with `require.Equal` call.
Fixes #12422 
JIRA: https://mattermost.atlassian.net/browse/MM-19030
> MM-19030 GH-12422 Replaced t.Fatal with require.Equal

- Makefile
Bump the autolink plugin version to 1.1.1
- Awaiting https://github.com/mattermost/mattermost-plugin-autolink/pull/77
> Bumped Autolink plugin version to 1.1.1

- model/websocket_message_test.go
Modify the calls to t.Fatal and the condition checks that lead to them, replacing them with calls to the testify require or assert
Fixes #12549
> [MM-19118] Migrate tests from "model/websocket_message_test.go" to use testify

- api4/channel_test.go
- api4/emoji_test.go
- api4/user_test.go
- app/bot_test.go
- cmd/mattermost/commands/teamargs.go
- config/file_test.go
- config/migrate.go
- model/file_info.go
- model/integration_action_test.go
- model/link_metadata.go
- store/storetest/audit_store.go
- store/storetest/channel_store.go
- store/storetest/group_store.go
- store/storetest/post_store.go
- store/storetest/team_store.go
- store/storetest/user_store.go
Caught by the ineffassign tool. This does not remove all cases yet.
Just the most important ones. The cases still remaining are:
```
mattermost/mattermost-server/api4/openGraph.go:40:2: ineffectual assignment to ok
mattermost/mattermost-server/app/migrations.go:100:6: ineffectual assignment to err
mattermost/mattermost-server/model/config_test.go:189:2: ineffectual assignment to temp
mattermost/mattermost-server/store/sqlstore/post_store.go:1340:6: ineffectual assignment to maxPostSize
mattermost/mattermost-server/store/sqlstore/user_store.go:1270:2: ineffectual assignment to searchType
mattermost/mattermost-server/utils/merge_test.go:515:3: ineffectual assignment to m2
```
> Fixed some ineffective assignments

- Makefile
Cherry pick of #12404 on release-5.16.
- #12404: Bumped Autolink plugin version to 1.1.1
/cc  @levb
> Automated cherry pick of #12404

- model/system_test.go
Summary
Migrate tests from "model/system_test.go" to use testify
Ticket Link
[MM-19177](https://mattermost.atlassian.net/browse/MM-19117)
Fixes https://github.com/mattermost/mattermost-server/issues/12550
> MM-19117 Migrate tests from "model/system_test.go" to use testify #12550

- model/push_notification_test.go
Modify the calls to t.Fatal and the condition checks that lead to them, replacing them with calls to the testify require or assert
Fixes #12544
> [MM-19123] Migrate tests from "model/push_notification_test.go" to use testify

- cmd/mattermost/commands/channel_test.go
Modify the calls to t.Fatal and the condition checks that lead to them, replacing them with calls to the testify require or assert,
[MM-19012]( https://mattermost.atlassian.net/browse/MM-19012)
Fixes https://github.com/mattermost/mattermost-server/issues/12411
> MM-19012 Migrate tests from "cmd/mattermost/commands/channel_test.go" to use testify

- model/incoming_webhook_test.go
Replaced test assertions with testify
Fixes https://github.com/mattermost/mattermost-server/issues/12597
https://mattermost.atlassian.net/browse/MM-19159
> Migrated tests from "model/incoming_webhook_test.go" to use testify

- model/security_bulletin_test.go
Converts model/security_bulletin_test.go `t.Fatal`/`CheckXxx` calls into testify `require` calls
Fixes #12547
> [MM-19120] Migrate tests from "model/security_bulletin_test.go" to use testify

- cmd/mattermost/commands/config_test.go
- change t.fatal to use require package of the testify toolkit.
[MM-19015](https://mattermost.atlassian.net/browse/MM-19015)
> MM-19015 Migrate tests from "cmd/mattermost/commands/config_test.go" to use testify

- app/diagnostics.go
- model/config.go
- tests/test-config.json
Removes `ExperimentalLdapGroupSync` config so that the feature is always enabled.
https://mattermost.atlassian.net/browse/MM-17767
https://github.com/mattermost/enterprise/pull/499
> MM-17767: Remove ExperimentalLdapGroupSync config.

- model/analytics_row_test.go
Mattermost is migrating its server tests from using the t.Fatal method calls on their checks to use the testify toolkit. The goal of this migration is to improve the readability of the tests, making them more concise and meaningful. This Help Wanted issue is to migrate the tests in the model/analytics_row_test.go file.
The expected way to migrate this is to go to the model/analytics_row_test.go file and modify the calls to t.Fatal and the condition checks that lead to them, replacing them with calls to the the require package if a failure should stop the execution of the test, or the assert package if it shouldn't.
Fixes: https://github.com/mattermost/mattermost-server/issues/12596
> Migrate tests from "model/analytics_row_test.go" to use testify

- model/cluster_discovery_test.go
This PR adjusts the test in `model/cluster_discovery_test.go` to use the `require` package.
Fixes https://github.com/mattermost/mattermost-server/issues/12570
> MM-19138 - Adjust test to use require.

- api4/plugin_test.go
- app/plugin_install.go
Emitting `notifyPluginStatusesChanged` when a plugin is removed.
Fixes https://mattermost.atlassian.net/browse/MM-18881
> MM-18881 - Attempting to configure uninstalled plugins gets stuck at Loading... without timeout.

- app/channel.go
- app/channel_test.go
As [requested](https://mattermost.atlassian.net/browse/MM-18038), this change reverts commit d6700e3b40fb7f11c300559b3c31b8799926ce3d. It seems the nuance is that archived channels (i.e. deleted channels) should count towards the limit. We're raised the dissonance with the help text and the in-product experience with UX to resolve this in a later release.
https://mattermost.atlassian.net/browse/MM-18038
> Revert "Do not count deleted channels when checking max channel limit (#12021)"

- model/channel_search_test.go
Convert model/channel_search_test.go to use Testify's assert instead of t.Fatal
Fixes https://github.com/mattermost/mattermost-server/issues/12671
Jira: https://mattermost.atlassian.net/browse/MM-19270
> use testify's assert on channel_search's tests

- model/license_test.go
Convert model/license_test.go to use Testify's assert instead of t.Fatal
Fixes https://github.com/mattermost/mattermost-server/issues/12672
Jira: https://mattermost.atlassian.net/browse/MM-19269
> use testify's assert on model/license's tests

- model/modeltestlib_test.go
Convert model/modeltestlib_test.go to use Testify's assert instead of t.Fatal
Fixes https://github.com/mattermost/mattermost-server/issues/12669
Jira: https://mattermost.atlassian.net/browse/MM-19272
> use testify's assert on modeltestlib tests

- app/channel.go
- app/channel_test.go
Cherry pick of #12730 on release-5.16.
- #12730: Revert "Do not count deleted channels when checking max
> Automated cherry pick of #12730

- model/cluster_info_test.go
Replaced test assertions with testify
Fixes #12635
Fixes https://mattermost.atlassian.net/browse/MM-19235
> [MM-19235] Migrate tests from "model/cluster_info_test.go" to use testify

- model/outgoing_webhook_test.go
Summary
change t.Fatal to assert.Equal in model/outgoing_webhook_test.go
Ticket Link
JIRA: [MM-19273](https://mattermost.atlassian.net/browse/MM-19273)
issue #12668
Test Result:
```
Running tool: /usr/local/go/bin/go test -timeout 30s github.com/mattermost/mattermost-server/model -run ^(TestOutgoingWebhookJson|TestOutgoingWebhookIsValid|TestOutgoingWebhookPayloadToFormValues|TestOutgoingWebhookPreSave|TestOutgoingWebhookPreUpdate|TestOutgoingWebhookTriggerWordStartsWith|TestOutgoingWebhookResponseJson)$ -v
=== RUN   TestOutgoingWebhookJson
--- PASS: TestOutgoingWebhookJson (0.00s)
=== RUN   TestOutgoingWebhookIsValid
--- PASS: TestOutgoingWebhookIsValid (0.00s)
=== RUN   TestOutgoingWebhookPayloadToFormValues
--- PASS: TestOutgoingWebhookPayloadToFormValues (0.00s)
=== RUN …
```
> change t.Fatal to assertions in model/outgoing_webhook_test.go

- services/filesstore/s3store_test.go
change `t.Fatal` method to `require` functions in `services/filesstore/s3store_test.go`
Fixes: #12664
> services/filestore: migrate s3store_test to testify

- model/channel_member_test.go
Summary
MM-19135 Migrate tests from "model/channel_member_test.go" to use testify #12573
Ticket Link
[MM-19117](https://mattermost.atlassian.net/browse/MM-19117)
Fixes #12573
> MM-19135 Migrate tests from "model/channel_member_test.go" to use testify #12573

- app/email.go
Cherry pick of #12747 on release-5.16.
- #12747: Only include the avatar attachment if is going to show a
/cc  @jespino
> Automated cherry pick of #12747

- store/storetest/audit_store.go
This PR aims to migrate tests to use testify, especially ones that should break the test with `t.Fatal` before
Fixes https://github.com/mattermost/mattermost-server/issues/12713
JIRA: https://mattermost.atlassian.net/browse/MM-19352
> MM-19352 - Migrated test in store/storetest/audit_store.go to use testify

- README.md
Changes the `Contributing Code` link in the README.md section [Get Involved](https://github.com/mattermost/mattermost-server#get-involved) to point to https://developers.mattermost.com/contribute/getting-started/
Fixes https://github.com/mattermost/mattermost-server/issues/12721
> Update Contributing Code link in README.md

- model/emoji_test.go
Converts model/emoji_test.go to use require calls instead of t.Fatal
[MM-19237](https://mattermost.atlassian.net/browse/MM-19237)
Fixes https://github.com/mattermost/mattermost-server/issues/12633
> MM-19237: convert t.Fatal to use require calls

- api4/ldap.go
Truncates the display name of a group with a name > 128 characters upon linking (not just in the sync job, as before).
https://mattermost.atlassian.net/browse/MM-17477
> MM-17477: Truncates group display name upon linking.

- api4/ldap.go
Cherry pick of #12751 on release-5.16.
- #12751: MM-17477: Truncates group display name upon linking.
/cc  @mkraft
> Automated cherry pick of #12751

- api4/system_test.go
Migration of test from api4/system_test.go to use testify by modifying the calls to t.Fatal replacing them with calls to the `require` package
Fixes https://github.com/mattermost/mattermost-server/issues/12791
> [MM-19464] Migrate tests from api4/system_test.go to use testify

- .circleci/config.yml
- Makefile
- -mod=vendor flag was not being passed during the build stage, forcing
it to download everything again.
- Optimize the git clone of webapp with --depth=1 and use GIT_SSH_COMMAND to clone.
- Add $(GOFLAGS) to some other places which got missed out.
> Fix CI config

- plugin/checker/main_test.go
Cherry pick of #12588 on release-5.17.
- #12588: enable GOPACKAGESPRINTGOLISTERRORS for plugin check tests
> Automated cherry pick of #12588

- app/channel.go
- app/channel_test.go
Cherry pick of #12380 on release-5.17.
- #12380: trim whitespace on channel display name during create
> Automated cherry pick of #12380

- api4/terms_of_service_test.go
Migrate tests from "api4/terms_of_service_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12789
> Migrate tests from "api4/terms_of_service_test.go" to use testify

- store/storetest/command_store.go
Modify the calls to `t.Fatal` method to using `require` functions in `store/storetest/command_store.go`
Fixes: #12716
> store/storetest: migrate command_store.go to use testify

- model/config.go
- model/config_test.go
We changed the production marketplace URL to `api.integrations.mattermost.com`, but I never backported https://github.com/mattermost/mattermost-server/pull/12378 to v5.16, and we shipped with the invalid marketplace.integrations.mattermost.com instead.
While we've added the old hostname to enable the functionality immediately for v5.16 customers, I'd like to patch this properly for an eventual future deprecation of the old hostname.
This change should be backported to v5.16 and v5.17 alongside the PR above.
https://mattermost.atlassian.net/browse/MM-19516
> MM-19516: fix production marketplace url

- web/context_test.go
Migrate tests from "web/context_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12795
> GH-12795: Replace t.fatal with testify package functions

- .circleci/config.yml
when using the `||` in bash you can have just one command in the right side if have more it will always run for some reason that I did not know and did not research
the issue was, if webapp is already built and we download that sucessufuly it always runs the npm install, and we don't want that. this PR fix this
> fix bash to not build webapp when it is already built

- app/channel.go
- app/channel_test.go
This change introduces new functionality, and therefore should not be included in the quality release 5.17
https://mattermost.atlassian.net/browse/MM-18831
https://github.com/mattermost/mattermost-server/pull/12380
https://github.com/mattermost/mattermost-server/pull/12825
cc @amyblais
> Revert 5.17 cherrypick "Trim whitespace of Display Name when channel is created"

- store/storetest/plugin_store.go
Switched to using testify instead of t.Fatal()
Fixes https://github.com/mattermost/mattermost-server/issues/12758
Thought about splitting the checks out to separate functions, as there is a lot of repeated code, but not sure if it would improve or reduce readability.  🤷‍♂️
> #12758 - switch plugin_store to using testify

- store/storetest/command_webhook_store.go
Migrate tests from "store/storetest/command_webhook_store.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12766
> Migrate tests from "store/storetest/command_webhook_store.go" to use testify

- app/command.go
- app/command_test.go
- Text from a `/code` command needs to be treated differently when processed by CreateCommandPost.
- We were processing the text of a `/code` command with `ParseSlackLinksToMarkdown`, which we shouldn't do.
- Unfortunately, I can't think of a better way than simply special-casing this. Open to suggestions to make it cleaner.
[MM-19526](https://mattermost.atlassian.net/browse/MM-19526)
> [MM-19526] /code is rendering HTML incorrectly

- app/command.go
- app/command_test.go
Cherry pick of #12840 on release-5.17.
- #12840: text from /code command needs to be treated differently
/cc  @cpoile
> Automated cherry pick of #12840

- api4/apitestlib.go
- api4/file_test.go
Changes tests to use testify.
Fixes https://github.com/mattermost/mattermost-server/issues/12788
> Changes tests to use testify.require at api4/file_test.go fixes #12788

- app/post_metadata.go
- app/post_metadata_test.go
Nothing particularly special here. We just want to stop returning metadata for deleted posts to prevent clients from getting into weird states like https://mattermost.atlassian.net/browse/MM-19507
https://mattermost.atlassian.net/browse/MM-19574
> MM-19574 Don't return metadata for deleted posts

- api4/status_test.go
This PR replaces the `t.Fatal` calls with `testify` helper calls.
https://github.com/mattermost/mattermost-server/issues/12889
> [MM-19664] Migrate tests from api4/status_test.go to testify

- utils/time_test.go
- utils/utils_test.go
Migrate tests from "utils/time_test.go" and "utils/utils_test.go" to use testify
Fixed https://github.com/mattermost/mattermost-server/issues/12883
> MM-19670: Migrate tests to use testify (#12883)

- build/Jenkinsfile.branch
update to use the branch name only to make a bit easier to use in mattermod and also make the docker hub a bit cleaner.
also add a stage to build the team edition as well
Part of this Jira: https://mattermost.atlassian.net/browse/MM-18865
> use the branch to tag the docker image and also build team edition

- app/permissions_migrations.go
Now `INVITE_GUEST` permissions is only given to system admin, before of that
was given to any user with `INVITE_USER` permission during the migration
execution.
[MM-19684](https://mattermost.atlassian.net/browse/MM-19684)
> Unbinding the permission INVITE_GUEST from INVITE_USER

- app/diagnostics.go
- config/client.go
- model/config.go
Add new setting to console to enable/disable rendering of latex code. When rendering is disable it'll do syntax highlighting. By default is set to false. This way it should prevent the app from crashing when sharing code that might outgrow assigned memory.
[MM-19344](https://mattermost.atlassian.net/browse/MM-19344)
> [MM-19344] add option to render latex

- web/handlers.go
This adds the request_id to the HTTP request logs. I also altered the log message to be more consistent to other log messages.
https://mattermost.atlassian.net/browse/MM-19550
> Include request_id in HTTP request logs

- .golangci.yml
- Makefile
To start off with, we are using the new-from-rev=HEAD~ option which just checks the current
commit. This allows us to quickly integrate golangci-lint and not spend time in fixing all the
outstanding issues.
Things pending:
- Slowly fix the existing issues. To test them, just uncomment the "new-from-rev: HEAD~" line
from .golangci.yml and have at it.
- There are a number of unused functions and methods which are only invoked from enterprise code.
We are ignoring them for now because removing them will stop enterprise build from working.
The correct solution here is to use a build tag to separate TE and EE code. As a long term goal,
we would want to use that build tag throughout the EE codebase and remove the `TE_PACKAGES` and `EE_PACKAGES` variables in the Makefile and just use the build …
> MM-19172: Add golangci-lint to the CI pipeline

- api4/post.go
- api4/team.go
- app/web_hub_test.go
- cmd/mattermost/commands/channel_test.go
- cmd/mattermost/commands/command_test.go
- cmd/mattermost/commands/config_test.go
- cmd/mattermost/commands/group_test.go
- mlog/stdlog.go
- model/integration_action.go
- services/imageproxy/local.go
- store/storetest/group_store.go
This PR fixes unnecessary type conversions in the codebase. There where found via [`unconvert`](https://github.com/mdempsky/unconvert). Fixing this issue is part of the afford to fix all problems found by `golangci-lint`.
Follow up on https://github.com/mattermost/mattermost-server/pull/12909
> Fix unnecessary type conversions

- app/notification_push.go
- cmd/mattermost/commands/server_test.go
This PR removes unused struct fields. There where found via `structcheck`. Fixing this issue is part of the afford to fix all problems found by `golangci-lint`.
Follow up on https://github.com/mattermost/mattermost-server/pull/12909
> Remove unused struct fields

- api4/channel_test.go
- app/migrations.go
- model/config_test.go
- store/sqlstore/post_store.go
- store/sqlstore/supplier.go
- store/sqlstore/user_store.go
- utils/merge_test.go
This PR fix ineffective assignments in the codebase. There where found via [`ineffassign`](https://github.com/gordonklaus/ineffassign). Fixing this issue is part of the afford to fix all problems found by `golangci-lint`.
Follow up on https://github.com/mattermost/mattermost-server/pull/12909
> Run ineffassign against codebase

- jobs/schedulers.go
time.After might leave stray timers if other channels in select triggered early
> Replace time.After with time.NewTimer

- api4/emoji_test.go
Update `api4/emoji_test.go` to use `testify`.
Fixes #12861 
[MM-19624](https://mattermost.atlassian.net/browse/MM-19624)
> emoji_test: update to use testify

- api4/oauth_test.go
Update `api4/oauth_test.go` to use `testify`.
Fixes #12867 
[MM-19618](https://mattermost.atlassian.net/browse/MM-19618)
> oauth_test: use testify

- api4/license_test.go
- api4/openGraph_test.go
Update `api4/license_test.go` and `api4/openGraph_test.go` to use `testify`.
Fixes #12860 
[MM-19625](https://mattermost.atlassian.net/browse/MM-19625)
> license, openGraph tests: convert to testify

- plugin/client_rpc.go
- plugin/http.go
Cherry pick of #11276 on release-5.17.
- #11276: add a check so that we don't write an invalid
/cc  @cpoile
> Automated cherry pick of #11276

- api4/brand_test.go
- api4/cluster_test.go
Migrate the tests in the api4/cluster_test.go and api4/brand_test.go to use testify
[MM-19663](https://mattermost.atlassian.net/browse/MM-19663)
Fixes #12890
> MM-19663 | Migrate brand_test and cluster_test to testify

- api4/plugin_test.go
- app/plugin.go
- app/plugin_install.go
This is a minor change to support e2e testing of plugin upgrade by returning a 404 instead of a 400 when trying to delete a plugin that is not installed.
https://mattermost.atlassian.net/browse/MM-17549
> MM-17549: support upgrading plugins

- cmd/mattermost/main.go
- go.mod
This PR adds `github.com/gorilla/handlers` to the [file](https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/main.go) as it is used in enterprise version but not in community edition. It consequence is that when running `go mod tidy` it removes the dependecy from the `go.mod` file. 
Discussion thread: [link](https://community.mattermost.com/core/pl/qko3f9er3tgpue44cu4j78m5dh)
> Add gorilla/handlers dependency as it is used in enterprise version

- cmd/mattermost/commands/server.go
This PR fixes a race condition between *main* and server startup goroutines.
Detailed info can be found in the ticket below.
https://mattermost.atlassian.net/browse/MM-19629
> [MM-19629] Fix data race in server start goroutine

- templates/unsupported_browser.html
My company's security scanner picked up on a potential problem in this
template in our deployed Mattermost instance.
https://www.owasp.org/index.php/Reverse_Tabnabbing
> Remove a potential tabnabbing attack in a template.

- Makefile
I feel this was missing, when i run `make stop` I would like to stop everything including the server / client and docker-compose.
so we dont need to run additional commands to stop, only if needed like `stop-server`
> add stop-docker to stop make command

- app/config.go
fixed syntax error in comment in config.go
> Fixed comments syntaxt in app config file

- app/server.go
- app/server_app_adapters.go
Found some typo in server_app_adapters.go, "initalization" -> "initialization".
None
> Fix typo in server_app_adapters.go

- app/plugin.go
- app/plugin_install.go
- app/plugin_install_test.go
- app/plugin_test.go
- i18n/en.json
When locally installing prepackaged plugins, skip if a plugin exists with the same id and is the same or a newer version.
This is effectively a "poor man's" rework of prepackaged plugins to allow upgrade of prepackaged plugins via the marketplace. The larger plan to rework prepackaged plugins was deferred from v5.18.
Fixes: https://mattermost.atlassian.net/browse/MM-20065
> MM-20065: allow prepackaged plugin upgrade

- .circleci/config.yml
- Makefile
- build/Jenkinsfile.pr
- model/config_test.go
- golangci-lint already does the vet and fmt checks. Remove those
as it is redundant now.
- Also start running golangci-lint as part of the CI pipeline now
just as an extra layer of reliability.
> Remove fmt and vet checks from CI

- app/user.go
- app/user_test.go
PR fixes a problem with channel header not getting updated in channels (with only one guest) when promoting/demoting the guest user due to channel stats cache not getting refreshed.
https://mattermost.atlassian.net/browse/MM-20209
> [MM-20209] Invalidate channel members cache when promoting/demoting a guest

- app/user.go
- app/user_test.go
Cherry pick of #13180 on release-5.18.
- #13180: Invalidate channel members cache when promoting/demoting a
> Automated cherry pick of #13180

- app/channel_test.go
- app/post.go
- app/post_test.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
The previous code included posts made by the current user when setting the mention badge for a DM channel that is marked as unread. This fixes that and makes it so that `app.countMentionsFromPost` returns an explicit value for DM channels instead of just a magic value.
https://mattermost.atlassian.net/browse/MM-20649
> MM-20649 Fix incorrect mention count when marking a DM channel as unread

- api4/system.go
- app/admin.go
- app/busy.go
- app/busy_test.go
- app/cluster_handlers.go
- app/server.go
- model/cluster_message.go
- model/system.go
This pull request builds on https://github.com/mattermost/mattermost-server/pull/13212 by adding cluster support.
When server busy state is changed on a server instance via system console UI, that change will be propagated to the other cluster nodes.
https://mattermost.atlassian.net/browse/MM-8607
> MM-8607: Add ability to turn off non-critical services when under load; cluster support

- .circleci/config.yml
And normalize all paths to refer from $HOME as ~ rather than
an absolute path.
We still need to remain under ~/go because the package building takes assets from $GOPATH/bin. A later commit will move everything from $GOPATH/bin to $GOBIN, and then we can get rid of ~/go prefix as well, and perform everything under ~/mattermost.
Updates #13129
@hanzei
> Remove references of GOPATH from circleCI config

- app/post.go
- model/post.go
- store/sqlstore/channel_store.go
- store/sqlstore/post_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
This PR is based off https://github.com/mattermost/mattermost-server/pull/13245. The changes specific to it are visible here: https://github.com/mattermost/mattermost-server/pull/13245
The previous version of this code only counted regular posts (ie posts with an empty post type) when updating the `ChannelMember.MsgCount`. That value is supposed to include all non-join/leave messages, so I've updated `CountPostsAfter` to match the expected behaviour.
https://mattermost.atlassian.net/browse/MM-20681
> MM-20681 Fix custom post types not marking channel unread when using Mark as Unread

- store/sqlstore/preference_store_test.go
Migrate tests from using t.Fatal() methods in some cases to use appropriate testify methods to check errors.
If this pull request addresses a Help Wanted ticket, please link the relevant GitHub issue, e.g.
Fixes https://github.com/mattermost/mattermost-server/issues/12781
[ticket](https://mattermost.atlassian.net/browse/MM-19455)
> GH-12781: Migrate tests to use testify

- services/marketplace/client.go
- services/marketplace/client_test.go
- Update Client#buildURL to normalize both the incoming path and the existing marketplace url by removing leading & trailing slashes and then adding a single slash in between the two strings
- Also add some unit tests for `buildURL`
Fixes https://github.com/mattermost/mattermost-server/issues/13271
JIRA: https://mattermost.atlassian.net/browse/MM-20620
> [MM-20620] Handle trailing slash when building marketplace api path

- .circleci/config.yml
those branches are being built in the internal Jenkins
`master` and `release-*` are built using the internal release Jenkins, and it does both `TE` and `EE`, plus the docker images for the branches and push to the release s3 bucket. 
So we don't need to have another source of potentials flakes and debugging, also reduce the usage of credits we have (equals less money spend) and also have one source of truth 
will do the same for `enterprise` if we merge this one
> Dont build master or release branches

- api4/system_test.go
The flaky test was a super weird race condition where the websocket connection is not counted yet, but is already "started", this happens because the goroutines schedule is not giving the control to the server to handle the channel received for register the websocket connection on time.
I think this fix should avoid the problem in the future (is not super sexy solution, but should deal with the underneath problem, giving the websocket connection time to be counted there).
[MM-19004](https://mattermost.atlassian.net/browse/MM-19004)
> Fixing flaky test around websocket counts in analytics API endpoint

- services/filesstore/localstore.go
corrected file permissions for localstore
https://mattermost.atlassian.net/browse/MM-20970
> MM-20970 - Unnecessarily permissive file mode in server-local file storage

- web/handlers.go
- web/handlers_test.go
PR enables CSRF check also for handlers that do not require an authenticated session but still might get one.
https://mattermost.atlassian.net/browse/MM-21048
> [MM-21048] Add CSRF check for handlers that do not require a session but have one

- api4/apitestlib.go
- api4/channel_test.go
- api4/websocket_test.go
- wsapi/user.go
PR adds a permissions check before sending the `user_typing` WebSocket event.  
A bit of a **note**: the fix in itself is trivial but the cost in performance might be significant since it's a very frequent event. 
https://mattermost.atlassian.net/browse/MM-21115
> [MM-21115] Add permissions check on user_typing event

- store/sqlstore/channel_store.go
- store/sqlstore/channel_store_test.go
The likeTerm from buildFulltextClause was being built inefficient using strings.
We change it to use squirrel to build the query.
And while at it, we also change the len check with checking with
an empty string which is more idiomatic. Both compile to the same
code, so there is no difference performance wise.
https://mattermost.atlassian.net/browse/MM-21116
> MM-21116: Improve channelSearch SQL query generation

- api4/plugin_test.go
- app/plugin.go
- app/plugin_install.go
- app/plugin_signature.go
- app/plugin_test.go
Save as `<plugin_id>.tar.gz.sig` instead of `<plugin_id>.sig`. The latter was a relic of the previous design to support multiple plugin signatures, but now creates an inconsistency with how the original source files were supplied as `<some_name>.tar.gz` and `<some_name>.tar.gz.sig`.
Fixes: https://mattermost.atlassian.net/browse/MM-21103
> MM-21103: change plugin signature path

- api4/channel.go
- api4/channel_test.go
- i18n/en.json
PR eliminates the possibility of changing a channel's type through the `/update` endpoint.
The new `/privacy` endpoint should be used for such purposes.
https://mattermost.atlassian.net/browse/MM-21217
> [MM-21217] Disallow changing type when updating a channel

- mlog/log.go
Exposing named error from zap api on our mlog api
This is needed for properly migrating the elasticsearch code to structured logging.
> Exposing named error from zap api on our mlog api

- app/plugin.go
- i18n/en.json
Updated error id for marketplace error to make a bit more descriptive given that is now currently used in the webApp. 
[MM-19614](https://mattermost.atlassian.net/browse/MM-19614)
WebApp:https://github.com/mattermost/mattermost-webapp/pull/4500
> MM-19614- Updated Marketplace Service error id

- config/file_test.go
Fixes failing TestFileSetFile due to using the wrong path.
> Fix failing TestFileSetFile

- store/sqlstore/channel_store.go
We use the querybuilder API instead of just building the query string
manually using fmt.Sprintf
https://mattermost.atlassian.net/browse/MM-21118
> MM-21118: Use querybuilder instead of fmt.Sprintf in channelStore

- store/sqlstore/channel_store.go
Cherry pick of #13385 on release-5.19.
- #13385: MM-21118: Use querybuilder instead of fmt.Sprintf in
/cc  @agnivade
> Automated cherry pick of #13385

- README.md
This pull request modifies the `README.md` file to achieve the following: 
- Reference the community server as `community.mattermost.com` instead of `pre-release.mattermost.com` as mentioned by @lieut-data [here](https://community.mattermost.com/core/pl/9nzyqs3ewbrrjmyrhmrge4yjmo).
- Add a bit of explanation on the purposes of the servers in "Try out Mattermost" to enable new people to choose the right one for their purpose.
- Add a link to the community Mattermost server in the "Get the Latest News" section to direct people to the community server looking for it there.   
This ticket is created in response to https://github.com/mattermost/mattermost-server/issues/13376 created after [this discussion](https://community.mattermost.com/core/pl/9nzyqs3ewbrrjmyrhmrge4yjmo) on the community …
> GH-13376: Improve community server links and phrasing in README.md to be more inviting.

- api4/license.go
- app/license.go
- app/license_test.go
Removing unnused/unnecesary getClientLicense etag generation. It wasn't
generating it consistenly before, so there is no performance penalties in this
PR.
[MM-21254](https://mattermost.atlassian.net/browse/MM-21254)
> MM-21254: Removing unnused/unnecesary getClientLicense etag

- api4/license.go
- app/license.go
- app/license_test.go
Cherry pick of #13416 on release-5.19.
- #13416: MM-21254: Removing unnused/unnecesary getClientLicense etag
/cc  @jespino
> Automated cherry pick of #13416

- i18n/en.json
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
PR makes sure we return the same error when attempting to create a channel with the same name of an existing one, whether or not the existing one is active or archived.
https://mattermost.atlassian.net/browse/MM-21020
> [MM-21020] Return same error when creating a duplicate channel

- store/sqlstore/channel_store.go
The `channelByNameCache` in the `GetByNames` query checks each teamId+channelName
combination in the cache and if any of the keys is not present, it queries the DB.
In this case, this is effectively a cache miss from the point of view of user.
But since the cache is at a teamId+channelName level, there may be several hits and some misses.
This is misleading as it does not generate proper metrics and might lead to a
false assumption of how effective the cache is.
We create separate metrics which account for all or none cache hits/misses.
This removes the old metrics which are used by other queries. So they are now separated,
and it will improve both the old and new metric. Because the old metric is not contaminated,
and the new metric is also separate. …
> MM-21331: Add aggregate cache metrics for channelByNameCache

- api4/plugin_test.go
- app/plugin.go
- plugin/environment.go
`GetMarketplacePlugins` will also include prepackaged plugins allowing them to be installed from webapp when:  
- `EnableRemoteMarketplace` is disabled and/or `local_only` was requested.
- A prepackaged plugin has a newer version than a same one available in the marketplace service.
[MM-19613](https://mattermost.atlassian.net/browse/MM-19613)
> MM-19613 - Include prepackaged plugins in marketplace results

- api4/channel.go
- api4/channel_test.go
- store/sqlstore/channel_store.go
PR makes sure we return the same error (NotFound) whether a channel does not exists or the user doesn't have permissions to view it.
https://mattermost.atlassian.net/browse/MM-21337
> [MM-21337] Return consistent errors when trying to get a channel by name

- app/server_app_adapters.go
- store/localcachelayer/main_test.go
- store/localcachelayer/user_layer.go
- store/localcachelayer/user_layer_test.go
- store/storetest/user_store.go
We already have userProfileByIdsCache to store the user profiles by Id.
It just wasn't being used for the (*UserStore).Get method. We add a wrapper
method in LocalCacheUserStore to intercept that call and check for the
presence of the user Id in the cache.
There is no need to add any code for invalidation as all of that is already
present.
Loadtest results for the basic profile:
The score is the average of the 95th percentile, median and interquartile ranges in the routes below.
| Metric | Baseline | Actual | Delta | Delta % |
| --- | --- | --- | --- | --- |
| Hits | 53 | 47 | -6 | -11.32%
| Error Rate | 0.00% | 0.00% | 0% | 0% |
| Mean Response Time | 2.68ms | 2.83ms | +0.15ms | +5.62% |
| Median Response Time | 2.00ms | 2.00ms | 0ms | 0% |
| 95th Percentile | 7.00ms | 7.00ms | 0ms | 0% …
> MM-21209: Use the LRU cache for UserStore.Get call too

- api4/saml_test.go
- web/saml.go
PR fixes Email to SAML migration by using the `ApiTrustRequesterHandler` for the `POST /login/sso/saml` endpoint which was failing with `401`.
https://mattermost.atlassian.net/browse/MM-21472
> [MM-21472] Fix Email to SAML migration

- api4/saml_test.go
- web/saml.go
Cherry pick of #13562 on release-5.19.
- #13562: Use ApiTrustRequester for SAML complete endpoint
> Automated cherry pick of #13562

- app/cluster_handlers.go
- app/web_hub.go
While invalidating a channel, we send out a cluster message
from the app layer as well as from the localcachelayer.
This causes multiple redundant messages to be sent out.
And additionally multiple cluster handlers were being registered
from the app layer as well as the localcachelayer.
We fix this by removing the cluster broadcast from the app layer
and directly calling the store method. We also remove
the duplicate event handler registration.
https://mattermost.atlassian.net/browse/MM-21396
> MM-21396: fix duplicate channel cluster invalidations

- cmd/mattermost/commands/channel.go
- cmd/mattermost/commands/channel_test.go
Fixes panic when using the `mattermost channel modify` CLI command to change channel public status. If you mistype the username or the system fails to find the user the command will panic because it did not check if it succeeded in retrieving the user. 
Fixes #13325 
https://mattermost.atlassian.net/browse/MM-21008
> MM-21008 Fix CLI nil pointer panic

- .gitignore
Added any log file to be ignored in gitignore
Fixes : https://github.com/mattermost/mattermost-server/issues/13580
Jira : nill
> Fixes #13580 : notification.log should be ignored in the gitignore

- web/static.go
- web/web_test.go
Reinstates "allow caching" as the default behavior for the `/static/plugins/*` endpoint.  If there's a 404 response then caching is disabled.  This should improve upon the behavior added in https://mattermost.atlassian.net/browse/MM-20948.
Fixes https://github.com/mattermost/mattermost-server/issues/13570
> GH-13570 Allow /static/plugins/* endpoint responses to be cached (except for 404s)

- tests/test-markdown-basics.md
Removing in-line image tests from this markdown file; some URLs became outdated, then were updated directly in the Selenium test (MessagingMan.html) rather than here.
Old investigation ticket was https://mattermost.atlassian.net/browse/MM-13821 but since then the tests were updated elsewhere so I'm closing that ticket as done/invalid.
The Se test uses the following:
```
[![Build Status](https://travis-ci.org/mattermost/platform.svg?branch=master)](https://travis-ci.org/mattermost/platform)
```
> Remove redundant in-line image tests

- store/sqlstore/utils.go
- store/sqlstore/utils_test.go
- Use strings.Builder which minimizes allocations.
- Avoid fmt.Sprintf which is slower than simple string concat.
Results:
```
name                                      old time/op    new time/op    delta
MapStringsToQueryParams/one_item-8           512ns ± 2%     377ns ± 1%  -26.27%  (p=0.000 n=10+9)
MapStringsToQueryParams/multiple_items-8     858ns ± 5%     748ns ± 2%  -12.82%  (p=0.000 n=10+9)
name                                      old alloc/op   new alloc/op   delta
MapStringsToQueryParams/one_item-8            456B ± 0%      384B ± 0%  -15.79%  (p=0.000 n=10+9)
MapStringsToQueryParams/multiple_items-8      608B ± 0%      592B ± 0%   -2.63%  (p=0.000 n=10+10)
name                                      old allocs/op  new allocs/op  delta
MapStringsToQueryParams/one_item-8 …
```
> MM-21368: Optimize MapStringsToQueryParams

- store/storetest/channel_store.go
If testing conditions fall just right, DeleteAt and UpdateAt can be set to different values, 1 millisecond apart. You can duplicate the error by putting a 1 ms sleep between when the values are set. 
Fix is to simply always set the UpdateAt property from the DeleteAt property.
https://mattermost.atlassian.net/browse/MM-21548
> MM-21548: Fix Flakey Test

- model/config_test.go
Migrate tests from "model/config_test.go" to use testify
Fixes https://github.com/mattermost/mattermost-server/issues/12667
> MM-19274 - Migrate tests from "model/config_test.go" to use testify

- store/sqlstore/bot_store.go
- store/sqlstore/bot_store_test.go
- store/storetest/bot_store.go
Handle a potentially `NULL` `Bots.LastIconUpdate` and `COALESCE` back to `0`. This column has no default, and while v5.20 should never write it as `NULL`, any pre-v5.20 server writing to the new schema will. As a result, this change ensures backwards compatibility.
I briefly considered just adding a default, but we don't have a precedent for doing that (for non-boolean columns), and worse yet, gorp doesn't seem to make that easy.
Fixes: https://mattermost.atlassian.net/browse/MM-21645
Fixes: https://mattermost.atlassian.net/browse/MM-21585
> MM-21645: COALESCE(Bots.LastIconUpdate, 0)

- api4/user.go
- api4/user_test.go
This is part of the problem of the MM-20345 bug, when you get all the users it was generating an etag based on your view restrictions, but is not enough to decide to not update the data, so we need also all the memberships to all the channels (which is not possible), so I removed the etag completely here.
[MM-20345](https://mattermost.atlassian.net/browse/MM-20345)
> MM-20345: Fixing etag problem not reloading all users when needed

- .golangci.yml
There have been spontaneous failures with golangci lint. @agnivade discovered that they are happen when both `unused` and `govet` are used. This PR disables `unused` for now. I've chosen `unused` because there where only a few issues found by this linter and there are a lot more issues found by `govet`.
Fixed https://mattermost.atlassian.net/browse/MM-21069
> Disable unused linter

- model/version.go
Given that the release branch for 5.20 has been cut, we can safely bump the app version to 5.22 now. Please note that we will have to bump the version on the 5.21 release branch, after 5.20 is cut.
None
> Bump app version to 5.22

- api4/role.go
- api4/team.go
- api4/user.go
Makes the Guest Accounts flag not required to use the feature, fixing https://github.com/mattermost/mattermost-server/pull/13231
https://mattermost.atlassian.net/browse/MM-16798
> Ignore guest accounts flag

- Makefile
This allows EE repo to call Makefile commands from a different directory
> Allow GOBIN to be overriden with environment variables

- api4/apitestlib.go
- api4/user_test.go
- app/user.go
We're updating the user in the store but we're not invalidating the
cache until the end so we're sending the old copy of it when we're
calling `sendUpdatedUserEvent`
When a system admin tries to demote/promote a user, the role is not updated but in the server is doing it right. Basically the problem is that we're sending the cached profile through the websocket instead of the new one.
https://mattermost.atlassian.net/browse/MM-21875
> User Management > User role change not reflected in the UI without a refresh

- store/sqlstore/team_store.go
- store/storetest/team_store.go
Fix GetMembers store methods order, which wasn't working properly in postgres.
This is already checked at app layer tests. See the `TestGetTeamMembers` in the
`app/team_test.go` file, where is checked that the expected order is always by
UserId.
> Fix GetMembers store methods order, which wasn't working properly in postgres

- store/sqlstore/group_store.go
- store/storetest/group_store.go
- Ensures that `getGroups`, `getGroupsByTeam` and `getGroupsByChannel` api endpoints do not return deleted `UserGroups` by appending`ug.DeleteAt = 0` to queries where they were not previously present
- Fixes two tickets caused by the same issue
https://mattermost.atlassian.net/browse/MM-21946
https://mattermost.atlassian.net/browse/MM-21945
- In order to reproduce I had to connect to the database and modify one of my `UserGroup` entries to have a `DeleteAt` entry of `1`
- Then I opened the add groups to team modal and the deleted group was not present as expected
> [MM-21946] [MM-21945] Ensure deleted groups are not returned from the groups API

- .gitignore
Ignore `prepackaged_plugins/` and `report.xml`, artifacts of various processes but not meant for commit.
> .gitignore prepackaged_plugins and report.xml

- store/sqlstore/group_store.go
- store/storetest/group_store.go
Cherry pick of #13747 on release-5.20.
- #13747: MM-21946 Ensure deleted groups are not returned from the
/cc  @fm2munsh
> Automated cherry pick of #13747

- app/import.go
- app/import_functions.go
- app/import_functions_test.go
- app/import_test.go
The methods where public but weren't designed to be used from the outside of
the App layer, and weren't necesarily useful outside, so I make them private.
> Making private import methos in the app layer

- build/Jenkinsfile.branch
Use new Jenkins release method for usage with GOBIN.
> Add 5.20 method to release branches for adding GOBIN.

- api4/system.go
- api4/system_test.go
- app/notification_push.go
- app/notification_push_test.go
- i18n/en.json
- model/push_notification.go
- model/push_notification_test.go
This PR includes measures to avoid panics related to passing empty or nil
data / messages to the push notification build or send methods.
It also includes test for all those parts
https://mattermost.atlassian.net/browse/MM-22002
> Avoid panic when push messages are empty or nil

- app/plugin_test.go
- store/sqlstore/plugin_store.go
Setting a `nil` value should actually delete the row instead of preserve it with a `nil` value.
The existing tests passed because they only checked the return value of `nil`. When running the tests on Postgres, this value is returned as an empty `[]byte{}` instead of `nil`, so update the test to reflect this semantically equivalent behaviour.
https://mattermost.atlassian.net/browse/MM-22074
> delete kv on setting nil

- web/static.go
Go mime sniffer supports the application/wasm mimetype natively
now. So there is no need to set this explicitly.
1. Have any .wasm file inside the client/files directory.
2. Run `curl http://localhost:8065/static/files/<file.wasm> -v -o /dev/null`
3. Verify that you still see `Content-Type: application/wasm` in the response.
> Remove explicit application/wasm mimetype

- model/manifest.go
- model/manifest_test.go
Actually `longtext` and `number` can also have a placeholder.
None
> Allow placeholder for types number and longtext

- store/localcachelayer/main_test.go
- store/localcachelayer/user_layer.go
- store/localcachelayer/user_layer_test.go
- store/storetest/user_store.go
Cherry pick of #13824 on release-5.20.
- #13824: Revert "MM-21209: Use the LRU cache for UserStore.Get call
> Automated cherry pick of #13824

- app/file.go
- web/handlers.go
Set the max request body size to be equal to MaxFileSize.
Ideally, non-file request bodies should be smaller than file request bodies,
but we don't have a clean way to identify all file upload handlers.
There shouldn't be any valid request which exceeds the max file upload size.
So this is a safe global limit to apply.
https://mattermost.atlassian.net/browse/MM-22057
> MM-22057: Limit incoming request bodies

- app/team.go
- app/web_conn_test.go
Fixed sending of update_team to every user
Fixes https://mattermost.atlassian.net/browse/MM-22265
> MM-22265  - Restrict the WS "update_team" event broadcast

- app/team.go
- app/web_conn_test.go
Cherry pick of #13848 on release-5.20.
- #13848: fixes sending of update_team to every user
/cc  @reflog
> Automated cherry pick of #13848

- Makefile
Roll back Zoom version from 1.2.0 to 1.1.2 equivalent commit (named `v1.3.0`)
Relevant Conversation
https://community.mattermost.com/core/pl/ppjt5k8e9pr898xqiqxios3bxy
plugin | prev | new 
--- | --- | ---
zoom | `v1.2.0` | `v1.3.0`
> Bump zoom plugin version to v1.3.0

- app/diagnostics.go
"AutomaticPrepackagedPlugins" missing in diagnostics.go, added with https://github.com/mattermost/mattermost-server/pull/13449
cc @marianunez @lieut-data @prapti please help with reviews ~~(no permissions to request)~~
cc @amyblais
> Add missing "AutomaticPrepackagedPlugins" to diagnostics.go

- api4/scheme_test.go
- app/syncables_test.go
- manualtesting/manual_testing.go
- store/storetest/group_store.go
- store/storetest/team_store.go
- store/storetest/user_store.go
There was a low chance of having a Team with an invalid name generated with
`model.NewId` without any prefix. For example a Team name starting with `api`
is going to fail.
[MM-22340](https://mattermost.atlassian.net/browse/MM-22340)
> MM-22340: Fixing flaky tests around Team name validation

- api4/config.go
- api4/config_test.go
Need to set the defaults to make sure we don't panic when checking config validity. Primarily an issue when the client making the API request omits sections or fields for whatever reason.
https://mattermost.atlassian.net/browse/MM-22579
> MM-22579 Fix panic when receiving a config to update to if some settings are not set

- Makefile
The behaviour of `echo` [varies](https://stackoverflow.com/questions/8467424/echo-newline-in-bash-prints-literal-n) between operating systems. Use `printf` for maximum compatibility, ensuring `bin/mmctl` is reliably detected when using `make prepackaged-binaries` (it wasn't working for me on MacOS).
> fix bin/mmctl detection using printf

- app/diagnostics.go
- app/diagnostics_test.go
- app/helper_test.go
Check if plugins were disabled before attempting to collect metrics and emit telemetry for same.
Fixes: https://mattermost.atlassian.net/browse/MM-22619
> MM-22619: check for nil plugins environment

- api4/plugin_test.go
- Fix panic due to not checking for JSON marshal error
- Reorder the FileExists check which would fail if we were to pass
the -short flag to bypass the slow URL test. In which case, the plugin
would have been removed from the filesystem.
So we move the check before we remove the plugin.
https://mattermost.atlassian.net/browse/MM-22666
> Fix flaky TestPlugin

- app/web_hub.go
- einterfaces/metrics.go
- einterfaces/mocks/MetricsInterface.go
Now we send metrics when the websocket's broadcast queue receive or
consume a message from the queue
https://mattermost.atlassian.net/browse/MM-22046
> Added Websocket's broadcast queue load metrics

- api4/group_test.go
- app/team.go
I could not figure out the actual root cause for this.
But a possible area of concern is that somewhere in the call stack,
the login failed partially. Therefore, the session did not have the teamMembers
populated. And the permission check failed therefore. Since the errors from login are actually masked, unless we check them, we would never know what failed.
Adding the error checks should let us know in future if this is not the case.
Another possible case is the app.ClearTeamMembersCache which gets called in
the goroutine app.SyncRolesAndMembership. If this races with the session,
then it's possible that the teamMember is wiped off from the session. But this
happens after the permission check. So it's not very likely.
Also, while we are here, I found that (*app).ClearTeamMembersCache …
> MM-22190: Add error checks to TestUnlinkGroupTeam

- app/server.go
- app/web_hub.go
- app/web_hub_test.go
Hubs property has been detected by the race condition detector
as a possible one because we could set the Hubs variable
and also we're spawning goroutines that could ask for that property
This condition is not happening right now because we're setting the
Hubs variable in the server start and after that, we're spawning the
goroutines but the tests are failing because of this and in the future
this could be a problem
I've been unable to reproduce the flaky test but this could be a cause of that
https://mattermost.atlassian.net/browse/MM-22655
> Include Mutex for Hubs property

- app/web_conn.go
Metrics operations are done in memory so there is no need
to spawn a new goroutine
https://mattermost.atlassian.net/browse/MM-22714
> Metrics operations shouldn't be inside goroutine

- app/server_app_adapters.go
This reverts commit daebc93d90958aa2831618f64e0ab2f667a1aa01.
The change in that commit caused Metrics not to be initialized properly
Fixes https://mattermost.atlassian.net/browse/MM-22980
> MM-22980 - Revert "server init order fixed"

- app/channel.go
- app/team.go
- app/user.go
- app/web_hub.go
Somehow something got merged wrongly in a PR and was using the old public
`InvalidateCacheForUser` method in different places, now is back to private.
> Fix bad merge problem

- .circleci/config.yml
This PR adds a build step that checks that the App layers are correctly generated. The step is run before the build/test steps to shortcircuit the build as soon as possible if there is any errors
> Add an app-layers check to the server's CI

- api4/group_test.go
There is a race at the DB level where the goroutine c.App.SyncRolesAndMembership
would set the the SchemeAdmin attribute to false. If this happens after
UpdateUserToTeamAdmin happens and before the Login, then the user does not
have the required permissions to unlink the group and it fails.
Thanks to @streamer45 for spotting the issue.
https://mattermost.atlassian.net/browse/MM-22190
> Fixing flaky test TestUnlinkGroupTeam

- app/channel.go
- model/role.go
- model/role_test.go
- This fixes the edge case where `manage_members` needs to defer to `manage_public_channel_members` for public channels and `manage_private_channel_members` for private channels to the
- I made the change in `role.GetChannelModeratedPermissions` which is used in both patch channel moderations and get channel moderations 
- TODO: Add some more tests
> [MM-22122] Fix manage channel members edge case for public and private channels

- app/channel.go
- model/websocket_message.go
Sends a websocket event when a channel scheme is created or deleted from patching channel moderations 
Fixes issue 1 on this PR https://github.com/mattermost/mattermost-server/pull/13813
> [MM-22212] Add channel scheme update event

- api4/apitestlib.go
- app/helper_test.go
- migrations/helper_test.go
- web/web_test.go
Recovering and immediately panicking does not make sense. So we just remove it.
This also fixes the bug of tempWorkspace not getting cleaned up in case of panics.
> Remove unncessary recover() calls

- app/plugin.go
- cmd/mattermost/commands/plugin_test.go
There was a race in (*App).SyncPlugins where if the same plugin
existed in availablePlugins and pluginSignaturePathMap, then
we would try to add/remove at the same time.
This would lead to a possible removal / addition of a plugin directory
or even unable to remove a directory because it was already in use.
We fix this by first finishing the removal of availablePlugins
before syncing it with the file store.
https://mattermost.atlassian.net/browse/MM-22762
> MM-22762: Deflake TestPlugin in cmd/mattermost/commands

- app/user_agent.go
- app/user_agent_test.go
Cherry pick of #13894 on release-5.22.
- #13894: Add mmctl to the User-Agent parser
> Automated cherry pick of #13894

- .circleci/config.yml
- build/Dockerfile.buildenv
- build/Jenkinsfile.branch
- build/Jenkinsfile.pr
- build/README.md
- build/local-test-env.sh
- plugin/helpers_plugin_test.go
Bumping the Golang version for the build CI image. Additionally changed the naming scheme. 
https://mattermost.atlassian.net/browse/IS-364
> IS-364: Bump Golang CI.

- dependency-suppression.xml
Suppress the Dependency-Check alert for CVE-2020-10675; we are unaffected.
> Suppress CVE-2020-10675

- app/plugin_api.go
- app/plugin_api_test.go
`GetPostsForChannel` called `GetPostsPage` with the `page` and `perPage` parameters swapped. This PR fixes this and adds a test checking the basic behaviour of the function.
https://mattermost.atlassian.net/browse/MM-23508
> MM-23508 Fix plugin API's GetPostsForChannel

- store/localcachelayer/layer.go
- store/localcachelayer/role_layer.go
- store/localcachelayer/scheme_layer.go
- store/localcachelayer/team_layer.go
The role cache must be invalidated when a team is associated or disassociated from a team scheme.
https://mattermost.atlassian.net/browse/MM-23606
> MM-23606: Fix role cache invalidation.

- api4/status_test.go
- model/status.go
During status serialization the serialized object could be modified while is
been serialized, so I copied the object before serializing it.
[MM-23505](https://mattermost.atlassian.net/browse/MM-23505)
> Fixing race condition on status serialization

- .circleci/config.yml
Checkout the webapp repo over HTTPS to avoid `StrictHostKeyChecking=no`.
https://mattermost.atlassian.net/browse/IS-299
> IS-299: Checkout webapp over HTTPS on CircleCI

- model/websocket_client.go
- model/websocket_client_test.go
We create a separate writer goroutine where all the writes happen.
And we also clean up a lot of things related to the reader goroutine.
Now all cleanup related activities happen inside the Close method.
We also fix a bug where pingWatchdog would not have been initialized
if ConnectWithDialer was called after initializing a WebSocketClient
struct manually.
The code has been decorated with a lot of comments to explain the flow
of events. Overall, there are still a lot of edge conditions
which cannot be removed due to compatibility reasons. This entire
client is due for an overhaul in v6.
https://mattermost.atlassian.net/browse/MM-23503
> MM-23503: Fix race in websocket_client writer

- app/plugin_test.go
- mlog/log.go
- mlog/stdlog.go
- plugin/supervisor.go
- testlib/assertions.go
This change effectively reverts https://mattermost.atlassian.net/browse/MM-18150, since plugins emit other logs over STDERR that ended up spamming the ERROR logs. 
It turned out we were already logging panics as debug logs even without those changes (thanks to the `SyncStderr` configuration), so I reverted the core of the changes but kept the tests to assert the required behaviour (now at the debug level). I'll reopen the original ticket to revisit the idea of surfacing just the panics as error logs.
Fixes: https://mattermost.atlassian.net/browse/MM-23261
> MM-23261 plugin stderr debug logs

- app/plugin_test.go
- mlog/log.go
- mlog/stdlog.go
- plugin/supervisor.go
- testlib/assertions.go
Cherry pick of #14166 on release-5.22.
- #14166: explicitly assert panic as error log
> Automated cherry pick of #14166

- app/channel_test.go
- app/command_test.go
- cmd/mattermost/commands/integrity.go
- model/client4.go
This PR fixes errors from `make check-style` due to new `gosimple`.
The upgrade to Go 1.14.x, triggered VSCode to update tools, which included an updated `gosimple`.  The linter is now complaining about 
```
S1038: should use fmt.Printf instead of fmt.Println(fmt.Sprintf(...)) (but don't forget the newline) (gosimple)
```
- replace all instances of `fmt.Sprintf("whatever")` with simply "whatever".
- replace all instances of `fmt.Println(fmt.Sprintf("whatever %d", i))` with `fmt.Printf("whatever %d\n", i)`
https://mattermost.atlassian.net/browse/MM-23747
> MM-23747 fix Sprintf linter errors from new gosimple

- app/plugin_health_check_test.go
- plugin/environment.go
- plugin/health_check.go
- plugin/health_check_test.go
Cherry pick of #14110 on release-5.22.
- #14110: store failed timestamps on health check job instead of
> Automated cherry pick of #14110

- api4/image.go
- api4/image_test.go
- i18n/en.json
Local images (like the ones provided by plugins) should not go through proxy.
This PR checks is URL being passed is an absolute one before passing it to proxy
https://mattermost.atlassian.net/browse/MM-23185
> MM-23185 - Markdown image hosted by plugins are not shown if local image proxy is enabled

- store/searchlayer/channel_layer.go
Seen in Kibana logs. I took a look through the related files and couldn't find a parallel instance that needed to be fixed beyond these two.
Note also that I haven't found a place to add unit tests to help cover this bug.
Original panic:
```
http: panic serving 10.128.148.31:47536: runtime error: invalid memory address or nil pointer dereference
goroutine 1063732 [running]:
net/http.(*conn).serve.func1(0xc0042995e0)
net/http/server.go:1767 +0x139
panic(0x1a4e080, 0x2edab40)
runtime/panic.go:679 +0x1b2
github.com/mattermost/mattermost-server/v5/model.(*AppError).Error(0x0, 0xc000032000, 0x1a618c0)
github.com/mattermost/mattermost-server/v5@/model/utils.go:73 +0x26
go.uber.org/zap/zapcore.encodeError(0x1c9c1d0, 0x5, 0x1fd6cc0, 0x0, 0x2028c60, 0xc0089fdfb0, 0xc0089fdfb0, 0x34) …
```
> avoid panic in search channel store

- app/layer_generators/main.go
- app/layer_generators/opentracing_layer.go.tmpl
Opentracing layer generator supported annotations in form of:
```go
// @openTracingParams teamId, skipSlackParsing
CreateCommandPost(post *model.Post, teamId string, response *model.CommandResponse, skipSlackParsing bool) (*model.Post, *model.AppError)
```
This allowed passing params to opentracing spans.
This PR improves that syntax to allow getting struct fields, i.e:
```go
// @openTracingParams post.Id, teamId, skipSlackParsing
CreateCommandPost(post *model.Post, teamId string, response *model.CommandResponse, skipSlackParsing bool) (*model.Post, *model.AppError)
```
> Opentracing layer generator improvement

- api4/channel_test.go
- app/channel.go
There are cases where `Schemes` records exist without a `DefaultChannelGuestRole` value and this change handles those.
https://mattermost.atlassian.net/browse/MM-23770
> MM-23770: Fix for blank DefaultChannelGuestRole on team schemes.

- store/searchlayer/user_layer.go
Cherry pick of #14182 on release-5.22.
- #14182: Fixing searching users without team
/cc  @jespino
> Automated cherry pick of #14182

- build/docker-compose.yml
- docker-compose.yaml
Reverts mattermost/mattermost-server#14223
This PR resulted into jenkins build issues.
> Revert "Updating to use a different network cidr for the mm-test network"

- model/version.go
Given that the release branch for 5.22 has been cut, we can safely bump the app version to 5.24 now.
> Bump app version to 5.24

- services/httpservice/client_test.go
The existing `TestHTTPClient` actually tries to reach google.com, making it brittle to network hiccups (as unlikely as that might be). Rewrite the test to rely on a local server instead.
I found the existing implementation of `TestHTTPClient` extremely hard to understand, so I've rewritten it more explicitly, expanded coverage somewhat. In doing so, I found myself somewhat surprised by the current behaviour. If `allowHost` returns `true`, we ignore `allowIP` altogether. If `allowHost` returns `false`, we check with `allowIP`. There's a lack of symmetry here that the current filter names don't make clear. Perhaps `allowHost` should be renamed `skipIPCheckForHost`?
Fixes: https://mattermost.atlassian.net/browse/MM-23666
> MM-23666: rewrite TestHTTPClient

- README.md
The invite link in the readme is no longer valid, so people can't sign up for community. I changed it to point to the login screen since people can sign up from there anyway.
> Fix community signup link

- store/localcachelayer/role_layer_test.go
- store/sqlstore/role_store.go
- store/sqlstore/role_store_test.go
- store/storetest/role_store.go
Same reason as the channel moderations API changes: there are team schemes in the wild with blank `DefaultChannelGuestRoles` fields. This supports that in the query.
https://mattermost.atlassian.net/browse/MM-23399
> MM-23399: Fix for old team schemes that have a blank guest role.

- store/localcachelayer/role_layer_test.go
- store/sqlstore/role_store.go
- store/sqlstore/role_store_test.go
- store/storetest/role_store.go
Cherry pick of #14267 on release-5.22.
- #14267: MM-23399: Fix for old team schemes that have a blank guest
/cc  @mkraft
> Automated cherry pick of #14267

- app/diagnostics.go
This PR adds telemetry for the `SMTPServerTimeout` configuration.
https://mattermost.atlassian.net/browse/MM-24097
> [MM-24097] app/diagnostics: add telemetry for smtp_server_timeout

- app/brand.go
- app/file.go
- app/team.go
- app/user.go
- model/file.go
- store/opentracing_layer.go
- store/timer_layer.go
Fixing int overflow in 32 bits on MaxImageSize check. The width/heigh was
working with big-enough numbers for handling huge images in 64 bits, but in 32
bits, there were using 32 bits to represent the width and the height (what is
enough) but not when you multiple them. This was generating and overflow that
can lead to allow you to upload images bigger than the allowed ones.
I tested the solution in ARM and 386 architectures (only the overflow situation, not whole upload image process).
[MM-20934](https://mattermost.atlassian.net/browse/MM-20934)
> MM-20934: Fixing int overflow in 32 bits on MaxImageSize check

- app/diagnostics.go
added enable_opentracing to diagnostics
https://mattermost.atlassian.net/browse/MM-24094
Docs PR: https://github.com/mattermost/docs/pull/3534
> MM-24094  EnableOpenTracing config setting missing from telemetry

- build/Dockerfile
Default the dockerfile to use the release 5.22.0
will be good to cherry pick this to the release 5.22 branch as well to default there as well
> dockerfile: set 5.22.0 version

- api4/channel.go
- api4/channel_test.go
In the autocompleteChannelsForTeamForSearch method we're checking for
the PERMISSION_LIST_TEAM_CHANNELS permission in order to avoid filtering
channels in the autocomplete search but this check is not necessary.
Now we're going directly to the database to search for those channels
in this specific method and we're filtering by channel membership and
team so there is no chance that we are going to filter undesired
channels to the user.
[Here](https://github.com/mattermost/mattermost-server/blob/v5.22.0/store/sqlstore/channel_store.go#L2014) is the query where you can see the filtering we're making
https://mattermost.atlassian.net/browse/MM-24065
> [MM-24065] Guest users should be able to search by channel

- app/license.go
- model/license.go
- model/license_test.go
- utils/license.go
Per request of the biz team and checking the code this field `PhoneNumber` is not used
in any place and also is one information that is not needed at all.
JIRA: https://mattermost.atlassian.net/browse/MM-24297
GH: https://github.com/mattermost/license-generator/issues/1
> license: dropping PhoneNumber field from the license

- store/sqlstore/post_store.go
Cherry pick of #14119 on release-5.23.
- #14119: MM-23369: Allow mysql to choose a better index
/cc  @agnivade
> Automated cherry pick of #14119

- scripts/test.sh
- store/storetest/settings.go
```
panic: failed to drop temporary database dbxssrb7uhnb8o384mprrxg4fo1r: failed to execute `DROP DATABASE dbxssrb7uhnb8o384mprrxg4fo1r` against mysql database as root: Error 1008: Can't drop database 'dbxssrb7uhnb8o384mprrxg4fo1r'; database doesn't exist
goroutine 1 [running]:
github.com/mattermost/mattermost-server/v5/store/storetest.CleanupSqlSettings(0xc000152150)
/go/src/github.com/mattermost/mattermost-server/store/storetest/settings.go:229 +0x234
```
> Fix build failure.

- api4/user_test.go
Fix assertExpectedWebsocketEvent ignoring the passed event
Discovered while working on #12609 https://mattermost.atlassian.net/browse/MM-18756
> Fix assertExpectedWebsocketEvent ignoring the passed event

- build/docker-compose.common.yml
- build/docker-compose.optional.yml
- docker-compose.yaml
Proposal to add [dejavu](https://github.com/appbaseio/dejavu), an Elasticsearch UI, to our docker-compose as an optional tool. So it's configured but you can run it if needed
It's a proposal because when you need to check or edit the ES data or indexes is painful so this tool helps a lot in that task
> Include dejavu in docker compose

- .circleci/config.yml
Currently the API documentation check step in CircleCI uses `master` branch of mattermost-api-documentation.
This PR adds an attempt to use a branch that matches the `mattermost-server` branch name to avoid failing builds
https://mattermost.atlassian.net/browse/MM-24197
> MM-24197 - CI: API checks should take into account existing documentation branch (if exists)

- api4/channel.go
- api4/channel_test.go
- i18n/en.json
- model/channel.go
- model/client4.go
- store/opentracing_layer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/mocks/ChannelStore.go
- store/timer_layer.go
- Adds an endpoint to get member counts for each group that has >0 members in the channel
- Allows optional `include_timezones` parameter
- This endpoint is to be used on channel load to grab all the user counts for each group in order to allow the client to know when to display a warning dialog and when not to.
https://mattermost.atlassian.net/browse/MM-23264
**Unblocks**
https://github.com/mattermost/mattermost-webapp/pull/5331
https://github.com/mattermost/mattermost-redux/pull/1086
> [MM-23264] Get channel member counts by group

- app/channel.go
- app/channel_test.go
- i18n/en.json
- model/channel.go
- ~Channel creation enforces that the channel URL must not contain `__` no matter which characters surround it so this PR changes the update and rename logic to match the create channel validations~
- This PR now removes the strict unnecessary validation (must not contain `__`) at the server level and ensures that it is consistent no matter where in the server a rename is done from.
https://mattermost.atlassian.net/browse/MM-23727
- Attempt to rename a channel using the rename channel modal (or the CLI) and set the url to something like `channel__name`
- Ensure that it does not save
> [MM-23727] Make channel validation consistent on the server

- app/team.go
- model/websocket_message.go
- Adds a new websocket event to be triggered when a scheme is assigned to a team 
- `update_team` which was previously being used only reloads the team in the state and not the memberships, so I created a new websocket event for a scheme being added/removed from a team
https://mattermost.atlassian.net/browse/MM-23605
> [MM-23605] Create new team scheme updated socket event

- app/web_conn.go
We invert the skipSend condition and outdent the remaining block
to make the code a bit more idiomatic.
While here, we also change the dropping message level from info to
warn because that's what it should be.
> app: outdent skipSend condition

- model/websocket_client.go
The core problem was that conn.ReadMessage allocated a buffer every time it was read.
This created heavy amount of allocations every single time we read a message from the websocket.
To avoid this, we bypass the ReadMessage which was more of a helper method,
and actually call the NextReader which returns a reader object.
We can then reuse a single byte.Buffer instance to read the object unmarshal
into a WebSocketEvent object. This gets rid of the allocation in the read path completly
and allows GC more time to do other tasks.
As we can see from the alloc_space profile here:
Before:
After:
There were 2 big boxes in the original profile. Not there's just one. So effectively 10GB of allocation is gone.
https://mattermost.atlassian.net/browse/MM-24397
> MM-24397: Reusing the read buffer while reading messages from websockets

- app/email_batching.go
- app/email_batching_test.go
On user activity, we were clearing the job.pendingNotifications map.
But we had already created a copy of the notifications slice while
iterating the map. Therefore, if we pass the copied slice, it would
still have the old notifications which were originally deleted.
The unit tests would not catch this because it was testing the
job.pendingNotifications map and not actually checking if the email
handler was being called or not. We fix that now.
https://mattermost.atlassian.net/browse/MM-23896
> MM-23896: Fix clearing of batched emails on user activity (#14340)

- app/auto_responder.go
- app/post.go
This PR fixes the issue where an error was appearing in the logs any time a user sends a DM to themself.  `GetUser` was being called with a blank id.
https://mattermost.atlassian.net/browse/MM-24575
> MM-24575 Error in logs when sending DM to same account

- services/imageproxy/local.go
- services/imageproxy/local_test.go
We check the file extension and appropriately set the response header.
SVG images without a file extension aren't proxied at all. So there's no
problem with that.
https://mattermost.atlassian.net/browse/MM-24395
> MM-24395: Set response header to be attachment for SVG images.

- store/sqlstore/role_store.go
Given that this query is part of the top 5 most used queries
we want to move it to use raw queries instead of gorp so we
can get rid of the reflection overhead
https://mattermost.atlassian.net/browse/MM-24087
> Move Rolestore.GetByNames query to raw query

- model/websocket_client.go
- model/websocket_client_test.go
When the connection is closed, the exit path does not
shut down the writer goroutine. In which case, it will keep spinning forever.
Since we already have the CAS mechanism now, we can use that to close the writer
and guard from a double-close.
The problem with refactoring the writer closing to a common
function was that we needed to wait for the reader to exit
before closing the EventChannel and ResponseChannel.
But then there is another problem that the API can be used in such
a way that the client is liable to call Close without even calling
Listen. In that case, we cannot wait for Listen to quit.
So from Close, we can only close the connection. And therefore
we need to duplicate the writer closing in the read loop's
defer block.
This makes closing the websocket client idempotent from …
> MM-24547: Fix writer leak when connection closes

- app/import_functions.go
This PR fixes a bug where replies to posts were not importing during bulk import.
Root cause is an optimization added in 5.22 which batch adds the replies.  Unfortunately the logic is in error and mismatches the replies with the posts.  Occasionally this will result in no error but the reply will appear under the wrong post.  More often the reply will generate the error above, depending on the time stamp of the last post in every 1000 post batch.  
https://mattermost.atlassian.net/browse/MM-24707
> MM-24707 fix bug when bulk importing post replies

- scripts/depcheck-alert.sh
CircleCI changed their API for artifact downloads: the URL now redirects to S3. Because of this, alerting is currently broken. This change enables redirections in the alerting script.
> Fix dependency alerting

- model/websocket_client.go
The read of the timer channel happened in 2 different goroutines
which created a race, and therefore if one was read before,
it would cause the other to deadlock.
To fix this, we use yet another channel to pass the message
and thereby make the reads happen in the same goroutine.
https://mattermost.atlassian.net/browse/MM-24685
> MM-24547: Fix deadlock in pingTimeoutTimer

- app/channel.go
- app/channel_test.go
- Instead of always calling `GetSchemeRolesForChannel` modify this block to load use the scheme returned from create (if one is created) or call `GetScheme` directly using the channel struct already loaded into memory.
- This is required since there were cases where retrieving the channel from store would return a channel with an outdated scheme id resulting in the function `GetSchemeRolesForChannel` returning the team scheme roles (or system scheme roles) 
- https://mattermost.atlassian.net/browse/MM-24987
- Apply label `Setup HA Cloud Test Server`
- Create a team scheme and set all permissions to true
- Open channel moderation for a channel in that team and enable / disable create posts multiple times 
- Eventually it will say "Create posts is disabled in the team scheme" and you will …
> [MM-24987] Dont call GetSchemeRolesForChannel and instead load the scheme from channel

- api4/websocket_test.go
This test writes directly to a connection
which causes panics and more frustration in an already fragile CI.
Since this anyways checks an edge condition, and will anyways be
removed in v6, let's remove this for now and let CI be happy.
https://mattermost.atlassian.net/browse/MM-25011
> MM-25011: Remove concurrent write to websocket connection

- app/layer_generators/main.go
- app/opentracing_layer.go
- store/layer_generators/main.go
- store/opentracing_layer.go
- store/timer_layer.go
Fixed a bug in layer generators with handling of error return type (previously, only model.AppError were handled)
Bug discovered during https://github.com/mattermost/mattermost-server/pull/14339
> Layer generators error return type fix

- app/webhook.go
- app/webhook_test.go
This PR fixes an infinite loop when splitting post attachments into multiple posts.  This bug was due to performing an assignment copy of a model.Post instead of using model.Post.clone().  The Post.Props map was being inadvertently carried over to the copy.
Includes new unit tests for this case and a few others.
This is meant to be the minimum fix as it is likely to be cherry picked for a dot release.  I plan to revisit this implementation as it generates more posts than necessary when the message text and attachments need to be split.
https://mattermost.atlassian.net/browse/MM-24644
> MM-24644 fix infinite loop splitting post attachments

- app/notification.go
- i18n/en.json
- This attribute returned should be `group.Name` not `group.DisplayName`
- https://mattermost.atlassian.net/browse/MM-25016
> MM-25016 Send group Name to in out of channel group users message

- api4/system.go
- store/sqlstore/system_store.go
The code was writing to master and immediately after that reading
from a replica causing it to fail intermittently.
Since this is not a very high-traffic table, it should be safe to read
from master always.
https://mattermost.atlassian.net/browse/MM-25238
> MM-25238: Fix system ping check to read from master

- model/channel_sidebar.go
- store/sqlstore/channel_store.go
Just in case we decide to change how categories are sorted by default, having separate values for the default sorting method and for manual sorting lets us keep track of whether or not a user has actually used manual ordering. The client will treat them the same for now.
https://mattermost.atlassian.net/browse/MM-25126
> MM-25126 Add a separate default sorting method for categories

- app/session.go
This PR fixes a bug where mobile clients were being logged out via Session Idle Timeout.  This setting only applies to desktop app and browsers.  See system console text.
Original ticket with "doesn't apply to mobile" here:  https://mattermost.atlassian.net/browse/MM-7481
https://mattermost.atlassian.net/browse/MM-25256
> MM-25256 don't logout mobile users via Session Idle Timeout

- model/integration_action.go
Add `Style` field to `model.PostAction`, which allows integrations to define a button style.
See https://github.com/mattermost/mattermost-webapp/pull/4993 for the webapp changes.
https://mattermost.atlassian.net/browse/MM-22734
> [MM-22734] Support different interactive message button styles

- web/static.go
The front-end save-to-reload time went from about 13 to 40 seconds on my local machine, which is annoyingly slow, so I've disabled Brotli in "dev" mode.
https://mattermost.atlassian.net/browse/MM-25369
> MM-25369: Disable Brotli in 'dev' mode.

- api4/system.go
The enhanced ping endpoint can return an unhealthy database read
result if the database read replicas have a high-enough replication
delay. Instead of adding the complexity and delay of retry logic,
we are opting to remove the read check for now and will re-add it
in the future in a separate health check flow.
https://mattermost.atlassian.net/browse/MM-25428
> Remove database read check from enhanced ping endpoint

- model/websocket_client_test.go
This fails in SuddenClose because we check for closing the writeChan
only after waiting the closure of Event and Response channels.
Therefore, it is still racy and can panic.
There is no use chasing this again because it will be completely overhauled in v6.
https://mattermost.atlassian.net/browse/MM-25439
> MM-25439: Skip SuddenClose flaky test

- app/cluster.go
- app/server.go
- app/server_app_adapters.go
The order of booting up a server should be
Job scheduler -> Cluster.
And shutdown should be the opposite. This is needed because the job scheduler
initializes certain data structures that are later called by ClusterLeaderChanged
event handlers. And the event handlers run in a separate goroutine.
Therefore, if the cluster initialization happens before the job scheduler,
then a race happens between accessing the jobs variable and setting it.
To prevent this race, we fix the order of startup, and add comments in both
places to prevent things from regressing again.
https://mattermost.atlassian.net/browse/MM-25154
> MM-25154: Fix data race in InvokeClusterLeaderChangedListener

- store/errors.go
We check if the err is nil or not before calling the Error() method.
> Check for nil error in ErrConflict

- model/client4.go
PR fixes `client4.GetPluginStatuses()` which cause of an error in passing the arguments was essentially behaving like `client4.GetPlugins()`.
Tested with (assuming there's at least one plugin enabled):
```go
package main
import (
"fmt"
"os"
"github.com/mattermost/mattermost-server/model"
)
func main() {
client := model.NewAPIv4Client("http://localhost:8065")
if _, res := client.Login("sysadmin", "adminpass"); res.Error != nil {
fmt.Println(res.Error)
os.Exit(-1)
}
plugins, res := client.GetPlugins()
if res.Error != nil {
fmt.Println(res.Error)
os.Exit(-1)
}
fmt.Printf("%+v\n", plugins.Active[0])
statuses, res := client.GetPluginStatuses()
if res.Error != nil {
fmt.Println(res.Error)
os.Exit(-1)
}
fmt.Printf("%+v\n", statuses[0])
}
```
https://mattermost.atlassian.net/browse/MM-25405
> [MM-25405] Fix client4.GetPluginStatuses()

- app/channel_test.go
- store/sqlstore/channel_store.go
When a new category is created, it should be placed as follows:
1. If the Favorites category is first, the new category should be placed after it
2. Otherwise, the new category should be placed first.
https://mattermost.atlassian.net/browse/MM-25281
> MM-25281  Place new categories in the correct position

- model/version.go
Given that the release branch for 5.24 has been cut, we can safely bump the app version to 5.26 now.
> Bump app version to 5.26

- app/diagnostics.go
- Adds an attribute to the ldap telemetry to determine if the picture attribute has been set to something other than the default (empty) 
- https://mattermost.atlassian.net/browse/MM-25388
> [MM-25388] Add telemetry for default picture attribute

- app/config.go
- app/server.go
There are 3 client config related variables which are set in regenerateClientConfig
but can be read from public methods in the App struct.
We use the same approach as the license fields in the App struct and use atomic.Value
for modifying them.
https://mattermost.atlassian.net/browse/MM-24481
> MM-24481: Use atomics for load/store of client configs

- app/diagnostics.go
Jitsi plugin: https://github.com/mattermost/mattermost-plugin-jitsi
@amyblais wondering if we can add to 5.24? This adds one telemetry, low risk.
cc @aaronrothschild FYI
> Add Jitsi plugin to diagnostics

- services/searchengine/bleveengine/search.go
Adds the term operator for both term and hashtag queries and for normal and excluded terms
https://mattermost.atlassian.net/browse/MM-25538
> [MM-25538] Adds the termOperator and takes it into account for terms and hashtag queries

- web/webhook.go
- web/webhook_test.go
mime.ParseMimeType returns and "no media type" error if the passed
string is empty.
Given that the Content-Type header is optional we shouldn't return error
in that case so we're fixing that allowing the users to call the webhook
without passing that header
https://mattermost.atlassian.net/browse/MM-25677
> [MM-25677] Content-Type is optional

- web/webhook.go
- web/webhook_test.go
* Content-Type is optional
mime.ParseMimeType returns and "no media type" error if the passed
string is empty.
Given that the Content-Type header is optional we shouldn't return an error
in that case, so we're fixing that allowing the users to call the webhook
without passing that header
* Include webhook id in the error message
Given that the number of webhooks could be big the user could
need the id to check which one of the multiple webhooks are failing
so include the id aids in that part
https://mattermost.atlassian.net/browse/MM-25677
> Cherry pick 5.23 - [MM-25677] Content-Type is optional (#14705)

- app/post.go
- app/server.go
- app/session.go
- app/session_test.go
- app/status.go
- i18n/en.json
- scripts/test.sh
This CR is a continuation from [#14496](https://github.com/mattermost/mattermost-server/pull/14496). 
- It migrates post, session and status cache to cache2 package, by using the new cache `Provider` interface. 
- This CR also provides a new field called `CacheProvider2` in struct `app/server`. This facilitates further migration as there are many existing usages of the `server.CacheProvider` which are based on the old cache interface.
https://mattermost.atlassian.net/browse/MM-25115
> MM-25115- migrate post, session and status cache to cache2

- web/webhook.go
- web/webhook_test.go
* Content-Type is optional
mime.ParseMimeType returns and "no media type" error if the passed
string is empty.
Given that the Content-Type header is optional we shouldn't return an error
in that case, so we're fixing that allowing the users to call the webhook
without passing that header
* Include webhook id in the error message
Given that the number of webhooks could be big the user could
need the id to check which one of the multiple webhooks are failing
so include the id aids in that part
https://mattermost.atlassian.net/browse/MM-25677
> Cherry pick 5.24 - [MM-25677] Content-Type is optional (#14705)

- app/channel.go
- i18n/en.json
- store/opentracing_layer.go
- store/searchlayer/channel_layer.go
- store/sqlstore/channel_store.go
- store/store.go
- store/storetest/channel_store.go
- store/storetest/group_store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/user_store.go
- store/timer_layer.go
This is a proposal PR that migrates the method `ChannelStore.Update` to return idiomatic go error interface (when it applies).
Fixes https://github.com/mattermost/mattermost-server/issues/14689
> Migrate Update method from ChannelStore to return idiomatic plain error

- api4/group_test.go
- app/channel.go
- app/command.go
- app/group.go
- app/integration_action.go
- app/post.go
- app/webhook.go
- i18n/en.json
- store/localcachelayer/channel_layer.go
- store/opentracing_layer.go
- store/sqlstore/channel_store.go
- store/sqlstore/group_store.go
- store/store.go
- store/storetest/mocks/ChannelStore.go
- store/storetest/scheme_store.go
- store/timer_layer.go
This is a proposal PR that migrates the method `ChannelStore.Get` and `ChannelStore.GetFromMaster` to return idiomatic go error interface (when it applies).
Fixes https://github.com/mattermost/mattermost-server/issues/14690
> Migrate Get/GetFromMaster methods from ChannelStore to return error interface

- app/authorization.go
- app/authorization_test.go
- app/helper_test.go
This PR adds a check to verify if a team member got deleted in HasPermissionToTeam,
and accordingly returns false.
https://mattermost.atlassian.net/browse/MM-25641
> MM-25641: Check if member was deleted in HasPermissionToTeam

- store/sqlstore/group_store.go
- store/storetest/group_store.go
Fixes incorrect SQL query that filters groups even if the parent team is not group-constrained.
https://mattermost.atlassian.net/browse/MM-25737
> MM-25737: Fix for groups list not returning results.

- api4/channel.go
- store/sqlstore/channel_store.go
- store/storetest/channel_store.go
Fixes for some bugs I'm coming across while attaching the redux and server code for the new sidebar. Most are fairly trivial, but I do want to call out a couple:
1. I removed the unique constraint on both sidebar tables. I had intended for that constraint to remove the possibility that we somehow end up with two items having the same SortOrder value, but I ran into issues because gorp updates rows one at a time, so something like rearranging items A, B, and C to A, C, B would cause a constraint error.
2. I added some stuff to the handling of orphaned channels since I was running into issues where channels from the wrong team and in custom categories were being added to the Channels category.
I'm also aware of another issue with channels not being unfavourited properly in the preferences, …
> MM-24914 Various fixes for sidebar channel handling

- api4/channel.go
- api4/channel_test.go
- model/channel_sidebar.go
- model/client4.go
- store/sqlstore/channel_store.go
The endpoint was returning an array of categories instead of just the one that was updated. I also fixed a couple cases where `model.Client4` constructed URLs wrong and a spot where I broke updating sorting method in my last PR.
> MM-24914 Fix updateCategory endpoint returning the wrong type

- api4/post_test.go
We improve the flakyness of the test by making the websocket
status checks synchronous after making each request.
This makes the status responses more reliable because in very
busy CI environments the goroutine scheduler can indeed send
the response which is made by a later HTTP request before the first one.
https://mattermost.atlassian.net/browse/MM-26167
> MM-26167: improve CreatePostCheckOnlineStatus

- app/plugin_api.go
- plugin/api.go
- plugin/api_timer_layer_generated.go
- plugin/client_rpc_generated.go
- plugin/plugintest/api.go
Reverts plugin API breaking change. 
The only field from `model.GroupSearchOpts` that is being used is `FilterAllowReference`, which defaults to the original behaviour when `false`. By invoking `(*App).GetGroupByName` with `model.GroupSearchOpts{}` there should be no changes to the response received by plugins. 
In the future, consideration can be made to adding that field to the plugin API in a SemVer-compatible way, and I don't see that requiring the whole `model.GroupSearchOpts` struct.
https://mattermost.atlassian.net/browse/MM-26231
> MM-26231: Reverts plugin API breaking change.

- store/storetest/channel_store.go
- store/storetest/team_store.go
Using random strings for channel names creates chances of collisions
when searching for specific strings.
We increase the search space increasing the size of the search string
to be searched. This reduces collisions and makes the tests more reliable.
For the "off-" family of tests, this probably needs more length. But
it would also need the tests to be changed slightly as the "off-" part
acts as a prefix. I accidentally stumbled upon it while running the test
50 times. Adding a "-" is probably good enough for now. We can revisit
if it fails again in CI.
https://mattermost.atlassian.net/browse/MM-26203
> MM-26203: Fix TestChannelStore//SearchAllChannels flake

- app/plugin.go
Cherry pick of #14679 on release-5.25.
- #14679: Correctly log if plugin icon is invalid
/cc  @hanzei
> Automated cherry pick of #14679

- .circleci/config.yml
The pipeline errors if the commit for the webapp does not yet exist in the bucket for uploading the webapp PRs. 
Which means the if else did not work as expected. Instead now we use `when: on_fail`, which basically uses `trap` underneath so it still errors, but initiates the npm commands (so part of the webapp pipeline).
> Fix webapp checkout part 2

- store/sqlstore/supplier.go
We work around the lack of LATERAL keyword by making the query separately.
https://mattermost.atlassian.net/browse/MM-26514
> MM-26514: Fix ALTER PRIMARY KEY migration for Postgres <9.3

- cmd/mattermost/commands/server.go
Just a minor fix to remove a duplicated reference to `syscall.SIGINT` when listening for interruptions
There is no ticket
> Remove duplicated signal

- api4/user.go
- api4/user_test.go
- model/client4.go
- model/user_get.go
- store/sqlstore/user_store.go
- store/storetest/user_store.go
In the webapp's Team Members modal, there is an inconsistency where the frontend assumes it is getting a page of users that are all active. It filters the inactive ones out client-side, but then the page is not full. This PR allows the frontend to request profiles using the query `api/v4/users?active=true`.
https://mattermost.atlassian.net/browse/MM-26532
https://mattermost.atlassian.net/browse/MM-26022
https://github.com/mattermost/mattermost-webapp/pull/5798
> [MM-26532] Support "active" filter on profile search

- api4/post_test.go
We just skip the test instead of failing because waiting for more than 5 seconds
to get a response does not make sense, and it will unncessarily slow down
the tests further in an already congested CI environment.
https://mattermost.atlassian.net/browse/MM-26563
> MM-26563: Skip TestCreatePostCheckOnlineStatus if timeout exceeds

- app/notification_push.go
This avoids the race of assigning the sema field from the start method
which runs in a goroutine.
The race that happens is
```
==================
WARNING: DATA RACE
Write at 0x00c003a9d1b0 by goroutine 67:
github.com/mattermost/mattermost-server/v5/app.(*PushNotificationsHub).start()
/home/agniva/mattermost/mattermost-server/app/notification_push.go:264 +0x90
Previous read at 0x00c003a9d1b0 by goroutine 69:
github.com/mattermost/mattermost-server/v5/app.(*Server).createPushNotificationsHub()
/home/agniva/mattermost/mattermost-server/app/notification_push.go:260 +0x1d5
```
> MM-26571: Move the semaphore creation before hub start

- app/license.go
This PR adds support for a new environment variable `MM_LICENSE` which can contain the contents of a license file.  When set, this license takes priority over all other license sources.  
- Database and file licenses are not overwritten but simply ignored while `MM_LICENSE` is set.
- If MM_LICENSE is set to a non-empty string, but the license is not valid, the server will be started without a license.
https://mattermost.atlassian.net/browse/MM-26064
> MM-26064 - ENV var license override

- api4/command.go
- app/app_iface.go
- app/command_autocomplete.go
- app/command_autocomplete_test.go
- app/opentracing_layer.go
- This basically just treats each call to `doPluginRequest` like it is a plugin's `ExecuteCommand` hook. The `ExecuteCommand` takes a `plugin.Context` and a `model.CommandArgs`, so I am stuffing all of that information into the url params of the `doPluginRequest` call. The plugin can decide what it wants to parse, but it should have all the context it needs. If you can think of anything else you want to send, let me know.
- https://mattermost.atlassian.net/browse/MM-26339
- Redux: https://github.com/mattermost/mattermost-redux/pull/1181
- Webapp: https://github.com/mattermost/mattermost-webapp/pull/5816
> MM-26339 - Add context and CommandArgs to dynamic autocomplete calls

- app/command.go
- app/command_test.go
- app/plugin_commands_test.go
Support command overrides. Built in commands can now be overridden by plugins and custom commands.
Also fixes a bug in slash command autocomplete where duplicate checking was done incorrectly. 
https://mattermost.atlassian.net/browse/MM-26201
> Mm 16292 support command overrides

- model/post.go
- model/post_test.go
Sometimes a PostPatch may not contain the message field. For example,
while pinning a post, only the IsPinned field is set, and everything
else is nil. In that case, DisableMentionHighlights would throw a panic.
We handle that case by checking for nil first.
https://mattermost.atlassian.net/browse/MM-26346
> MM-26346: check for nil Message in DisableMentionHighlights

- app/authorization.go
- app/authorization_test.go
- Ensure admin retains permissions to team after being removed from a team
- https://mattermost.atlassian.net/browse/MM-26015
> MM-26015: ensure admin has permission after removal from team
